### ISSUE TITLE
Wearing Main hand weapons in off hand

### ISSUE THREAD

**Issue by koochy414** [SunwellWoW/Sunwell-TBC-Bugtracker#1]
Decription: 
I'm an enhancement shaman and can wear main hands in the off hand slot. Tested with both fools bane and Dragonmaw. Also can not change a unique weapon to the other slot while equipped.

How it works: 
Can simply equip main hand weapons in any weapon slot. 

While wearing Blackout Trucheon i can not change it to off hand while wearing it. "you can not equip more than one of those"

How it should work: 
Should not be able to wear main hand weapons in the offhand slot.

Should be able to switch a weapon while wearing to the other slot if it is unique.

Source (you should point out proofs of your report, please give us some source): 

![image](https://user-images.githubusercontent.com/41968067/43476635-fa4504d8-94f0-11e8-8302-955eea6fff98.png)

**Comment by Haipethdev** [comment]
Can confirm this, I had the same on Tyba.  Not sure if it is to do with GM commands or if real players would experience the same issue.

**Comment by akrom23** [comment]
@Haipethdev  @koochy414  This weapon should be one-handed or main-handed?

**Comment by akrom23** [comment]
No response. Closed.
