### ISSUE TITLE
[zone] darkshore [quest] The sleeper has awakened (escort quest)

### ISSUE THREAD

**Issue by Pumpuli8** [SunwellWoW/Sunwell-TBC-Bugtracker#1000]
Decription: 
Quest not working. bear follows when he is sleep and doesnt wake up with horn. 

How it works: 

How it should work: 
You need to escort bear to maestrar's post, if he (bear) sleeps u need to awake him with horn.

Source (you should point out proofs of your report, please give us some source):

**Comment by seki98** [comment]
@Dootz not working completely:

* no gank of the fulborgs.
* The quest should be completed on enter to Maestra's post, not only when approached to the hand in NPC
