### ISSUE TITLE
Vel'rin hangout down under (npc under building instead of in it).

### ISSUE THREAD

**Issue by amarathTESTER** [SunwellWoW/Sunwell-TBC-Bugtracker#1003]
Decription: 
Vel'rin of Sen'jin is preparing for a storm and hiding out under his building instead of in it. (not sure if this is a larger placement issue or specific to him).

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/t8bvOM2

**Comment by Dootz** [comment]
moved to megathread
