### ISSUE TITLE
[NPC] Bloodscalp Mystic

### ISSUE THREAD

**Issue by Reflekz** [SunwellWoW/Sunwell-TBC-Bugtracker#1005]
Decription: 
Bloodscalp Mystic just runs to you then melee auto-attack.

How it works: 
Bloodscalp Mystic does not cast spells.

How it should work: 
Bloodscalp Mystic should cast Lightning Bolt , Healing wave , Fire ward , Enrage , Throw

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?npc=701

**Comment by Dootz** [comment]
moved to megathread

**Comment by Dootz** [comment]
I'm falling asleep :(
