### ISSUE TITLE
Evade bug

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#1015]
Decription: 
Very often, an evade occurs where it should not be.

How it works: 
For example, these pirates are afraid of water so much that as soon as me make a step into the water, they go to evade.
![wowscrnshot_102918_201952](https://user-images.githubusercontent.com/43764742/47718872-3803c400-dc52-11e8-8136-d543a46f5d14.jpg)
![wowscrnshot_102918_201956](https://user-images.githubusercontent.com/43764742/47718873-389c5a80-dc52-11e8-89ca-5ebc143922d6.jpg)
Also, threshadons go to evade if the character floats to the surface of the water.
![wowscrnshot_103018_154900](https://user-images.githubusercontent.com/43764742/47719185-0c350e00-dc53-11e8-8ae2-d83c3e281f56.jpg)
![wowscrnshot_103018_154905](https://user-images.githubusercontent.com/43764742/47719187-0c350e00-dc53-11e8-83e5-227269fe25af.jpg)

How it should work: 
In the event of an encounter where you do use the transition between land and sea to break a fight, the mob in question will evade but remain in combat with you. It should, in most cases, reset within a few seconds.
Threshadons, Frenzy, Sharks should evade only  when the character stops swimming (for example, goes to land).
Some amphibious mobs can pursue from land into the water and swim after you or from water to land and run after you. For example, a murloc.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/QXIsZViwYQc?t=110
http://wowwiki.wikia.com/wiki/Swim
http://wowwiki.wikia.com/wiki/Frenzy
http://wowwiki.wikia.com/wiki/Threshadon
http://wowwiki.wikia.com/wiki/Shark

**Comment by Feydil** [comment]
Can add that quite similar happends when moving close to enemys in stealth, sometimes they attack you and your character will either evade, parry or dodge. Then the mob resets. This happends with all mobs and not one specific. Will try get a screenshot of it if wanted? Sadly can't record.

**Comment by Wojtyas** [comment]
Oh, an old issue. It's been fixed while ago.
