### ISSUE TITLE
[zone] moonglade. Denrite starblaze inside floor.

### ISSUE THREAD

**Issue by Pumpuli8** [SunwellWoW/Sunwell-TBC-Bugtracker#1016]
Decription: 
[zone] moonglade. Denrite starblaze inside floor.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/44476400/47738666-42d34e80-dc7c-11e8-8eea-7c46127d41dd.png)

**Comment by Dootz** [comment]
Moved to #megathread
