### ISSUE TITLE
The Woodland Protector

### ISSUE THREAD

**Issue by pedichenko** [SunwellWoW/Sunwell-TBC-Bugtracker#102]
Decription: 
Seek out the dryad Tarindrella

How it works: 
She isnt even in the zone

How it should work: 
She should be just southeast of the first questgiver you meet in teldrassil 

Source (you should point out proofs of your report, please give us some source): 
https://tbc-twinhead.twinstar.cz/?quest=459

**Comment by Dootz** [comment]
will be fixed with next server update
