### ISSUE TITLE
[Interactive Object] Wickerman Effigy

### ISSUE THREAD

**Issue by Jeansapin** [SunwellWoW/Sunwell-TBC-Bugtracker#1029]
Decription: The Wickerman Effigy for the Draenei Quest : Call of Fire

How it works: The Wickerman Effigy has an arm in the tree.
https://imgur.com/M2xs7xy
And when you click on it, nothing happens except a red message on your screen saying : "Invalid target"
https://imgur.com/8eFuQV7

How it should work: It should be leaning against the tree.
https://www.wowhead.com/object=181672/wickerman-effigy
https://imgur.com/OtBYTnr
And when clicked, it starts to burn, revealing a fire elemental named Hauteur ( https://www.thegeekcrusade-serveur.com/db/?npc=17206 )
1) https://youtu.be/YG-fDz9onKk?t=67
2) https://youtu.be/VhyrJBqhjZ4?t=354

Source (you should point out proofs of your report, please give us some source): 
wowhead, screenshot on retail, youtube

**Comment by akrom23** [comment]
Will work after update.

**Comment by Jeansapin** [comment]
It's well fixed, thanks, but the Wickerman still got an harm in the tree https://imgur.com/Rw1PFNr

**Comment by akrom23** [comment]
Perhaps it needs some hug.
