### ISSUE TITLE
[Quest] Freedom to Ruul

### ISSUE THREAD

**Issue by Reykjavikshore** [SunwellWoW/Sunwell-TBC-Bugtracker#1038]
Decription: 
 https://tbc-twinhead.twinstar.cz/?quest=6482
https://tbc-twinhead.twinstar.cz/?npc=12818
![wowscrnshot_103118_203328](https://user-images.githubusercontent.com/44321901/47817528-c3ae4b00-dd4d-11e8-9349-81261dbec6f8.jpg)

How it works: 
That npc escort didnt work correct. NPC didnt aggro bears pack and other trash in the cave If our character wont aggro them. So u can complete quest just staying back and do nothing.

How it should work: 
Rull should aggro the bears pack or they should aggro him not only player

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=oBnMZKvnJeU

**Comment by ArekJadach** [comment]
It need to be fixed. Mobs are not attacking the bear. The bear is attacking enemies(fast running to them) if another player fights. Then bear slowly goes back where he was before.  https://imgur.com/a/q4SMIRA
