### ISSUE TITLE
[NPC] Thistleshrub Rootshaper

### ISSUE THREAD

**Issue by Reflekz** [SunwellWoW/Sunwell-TBC-Bugtracker#1041]
Decription: 
His totem attacks , has 1500 hp and moves (slowly)

How it works: ^

How it should work: 
Totem should have low health , not attack , and cast earthbind every few seconds.

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?npc=5485
![wowscrnshot_103118_195314](https://user-images.githubusercontent.com/44597439/47823477-41bb2380-dd47-11e8-855c-8fc41b6267dd.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented.
