### ISSUE TITLE
[Quest] Inspecting the Ruins (Horde)

### ISSUE THREAD

**Issue by sunwelldude** [SunwellWoW/Sunwell-TBC-Bugtracker#1043]
Decription: 
The quest chain works in the wrong order.
https://wow.gamepedia.com/The_Shady_Rest_Inn_quest_chain

How it works: 
You can pick all the 3 quests at the Shady Rest Inn before completing the quest https://wow.gamepedia.com/Inspecting_the_Ruins_(Horde) as horde.
Referring to these 3:
The Black Shield
Suspicious Hoofprints
Lieutenant Paval Reethe

After you turn in Inspecting the Ruins you get a red message saying "Requires you to be in the Shady Rest inn" and you don't get a buff.

How it should work: 
When completing this quest, Tarem gives you the buff "Spread Reflective Dust", which lasts for 2 minutes. While buffed, 3 arrows appear in the general area. Hoofprints are next to Tarem, a Theramore Guard Badge is on the floor of the Inn, and a Black Shield is over the fireplace. Inspect each of the items to pick up a new quest. Players can ask Tarem to reapply the buff if necessary.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=LU4SEgOXm1Q

**Comment by neheri** [comment]
As of today quest is still missing role play from Inspector Tarem. He keeps kneeling down and standing up. You are able to turn in the quest to him and then pick up other quests though.
