### ISSUE TITLE
Rogue finishers remove combo points if missed

### ISSUE THREAD

**Issue by mistermeta** [SunwellWoW/Sunwell-TBC-Bugtracker#1046]
Decription: 

Rogue finisher Eviscerate removes all combo points if it's dodged by creatures.
How it works: 
Rogue finisher Eviscerate removes all combo points if it's dodged by creatures.

How it should work: 
Finishers shouldn't remove the combo points if dodged.

Source (you should point out proofs of your report, please give us some source):

**Comment by Sollmyr** [comment]
Source for how it should work:
https://www.youtube.com/watch?v=iR7nz6jpuHQ between 1:35 and 1:40, the rogue has 5 points on the target and attempts to use Rupture, at 1:37 precisely he uses Rupture once, the energy is consumed, the Rupture misses and the combo points on the target remain, at 1:39 he uses Rupture again, this time it lands and the combo points are consumed.

The mechanic should work the same way for misses, dodges and parries. None should consume the combo points.
