### ISSUE TITLE
Ressurection sickness on lvl below 20

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1047]
Decription: I received 10 minutes long RS debuff on lvl 12.

How it works: Ressurection sickness on levels below 20 grants full 10 minutes long debuff.

How it should work: 
< lvl 10 no RS, 
<10 lvl 10- lvl < 20 lvl (for an instance 12 - 10 = 2 minutes on lvl 12
< 30 - 10 minutes  

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/spell=15007/resurrection-sickness#comments:id=174872

![wowscrnshot_110118_201747](https://user-images.githubusercontent.com/37372869/47874280-b22f7680-de13-11e8-8b17-afda1964fdae.jpg)

EDIT: 

Apparently it was only visual. After relogging it was 2 minutes and faded off quickly. 

May be worth checking though.

**Comment by akrom23** [comment]
#685
