### ISSUE TITLE
[NPC] Overlord Mok'Morokk

### ISSUE THREAD

**Issue by sunwelldude** [SunwellWoW/Sunwell-TBC-Bugtracker#1051]
Decription: 
https://wow.gamepedia.com/Overlord_Mok%27Morokk

How it works: 
He has way too much health (12667hp) when you start the quest Challenge Overlord Mok'Morokk and he becomes hostile. He also hits really hard for that level but I can't find values on that.

How it should work: 
Should have significantly less health.
Health 	2,894 according to https://wow.gamepedia.com/Overlord_Mok%27Morokk

Source (you should point out proofs of your report, please give us some source): 
![omm](https://user-images.githubusercontent.com/44537968/47886735-8d9fc280-de44-11e8-9145-1508c10034a2.jpg)

**Comment by Dootz** [comment]
http://db.hellfire-tbc.com/?npc=4500
dmg adjusted. Hp was probably nerfed during wotlk.
