### ISSUE TITLE
Autoattack after attacking Evaded target

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1054]
Decription: After charging a Centaur from Water I was standing in front of it but my character didn't attack. It shown "Evade" when I charged him, after that I was locked from attacking. Please notice that when I got to him with charge, he was no longer evaded. 

How it works: After attacking target from water, my character was suspended from attacking. It said that my charge was "Evaded" and I couldn't attack until I died.

How it should work: Attacking evaded target should prevent him from getting the spell effect (in this case stun) but should not stop characters from attacking.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Evade

![wowscrnshot_110218_113540](https://user-images.githubusercontent.com/37372869/47910787-2f023500-de94-11e8-8538-1b2352617b35.jpg)

![wowscrnshot_110218_113536](https://user-images.githubusercontent.com/37372869/47910783-2c074480-de94-11e8-93a2-257b9951451d.jpg)

Edit: After charging from land I could kill the mob without any issues.

**Comment by Wojtyas** [comment]
When players uses Charge on evaded creature (its returning to home position) the charge effect won't occur but warrior will gain +rage and Charge cd.

**Comment by Wojtyas** [comment]
Fixed & implemented.
