### ISSUE TITLE
[NPC] Engineer Whirleygig

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1057]
Decription: Hits like a truck. 3 hits a player.
Same as https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1056. 
I think all rare spawns need to be checked.

How it works: Hits 150+.

How it should work: Should hit 20-40. Should be soloable.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=TywvARTdLe0

**Comment by akrom23** [comment]
#669
