### ISSUE TITLE
[Spell] Charge underwater

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1058]
Decription: If you charge underwater it will bring you to the same place as the NPC you're charging is however it won't move you vertically. You will usually end up on the water surface while the NPC is walking on the bottom.

How it works: Charge only moves your X and Z coords. Your height is not moved at all underwater.

How it should work: Charge should bring you right next to the NPC, even if you're floating on the surface and the NPC is on the bottom.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/1qHsxM4lz2E?t=72

**Comment by akrom23** [comment]
#669
