### ISSUE TITLE
[Object] Tin Vein

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1059]
Decription: On the first try to mine minerals from a tin vein I was unsuccessful, gained mining skill but did not loot anything (loot window did not open). When I tried to mine again it says "That is already being used", like somebody else tried to mine that vein too, but nobody's around.

How it works: Tin vein is unlootable after first mining cast. I pressume that same can happen with other veins (objects?) however so far I encountered this only with tin vein.

How it should work: If nobody else is mining the same vein you should be able to clear it out. "That is already being used" error should not happen.

Source (you should point out proofs of your report, please give us some source): 

![wowscrnshot_110218_143931](https://user-images.githubusercontent.com/37372869/47918658-8234b180-dead-11e8-969b-aa0066610a51.jpg)

**Comment by akrom23** [comment]
Try relog.

**Comment by neheri** [comment]
Relog helps. And yes that usually happens from max range. However I don't think that this is the way it's supposed to be and that's why I report.

**Comment by akrom23** [comment]
Max range should be fixed. If any object causes problems, just write it here.

**Comment by neheri** [comment]
Apparently other objects are causing the same problem as well. If you try to loot it from max range it becomes unlootable. 

![wowscrnshot_110318_202941](https://user-images.githubusercontent.com/37372869/47956612-4bdb5d00-dfa7-11e8-9efb-0726f49b643c.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented.
