### ISSUE TITLE
Ranged NPC targeting but not attacking

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1061]
Decription: I had aggro on several mobs, which one of those was ranged Grimtotem Mercenary. I've killed other melee (Ruffians) and when noticed that only ranged left I noticed something weird. He was targeting me but not shooting, he was only moving from one place to another, like it was hung.

How it works: Axe throwing NPC was targeting me but not attacking and walking from place to place.

How it should work: He should attack me all the time. 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_110218_152316](https://user-images.githubusercontent.com/37372869/47920982-caef6900-deb3-11e8-813e-34d793a96b9a.jpg)
![wowscrnshot_110218_152321](https://user-images.githubusercontent.com/37372869/47920990-cf1b8680-deb3-11e8-9dbd-c24571a7682b.jpg)

EDIT:

I've noticed that this has some connection to being out of range. Instead of getting into the range, NPC behaves like it was out of combat. Should get into range and start shooting.

**Comment by Dootz** [comment]
Weird I just tested it and it seems fine. They enter "ranged" phase correctly and start casting "Throw". When out of the line of sight they followed me and started to attack.
