### ISSUE TITLE
[NPC] Stone Guardian

### ISSUE THREAD

**Issue by Reflekz** [SunwellWoW/Sunwell-TBC-Bugtracker#1063]
Decription: 
Stone Guardian isn't patrolling.

How it works: ^

How it should work: 
Stone Guardian should be patrolling around Un'Goro

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?npc=6560
![wowscrnshot_110218_142903](https://user-images.githubusercontent.com/44597439/47930763-ae4f3300-deab-11e8-9d37-e8cab41db47b.jpg)

**Comment by Dootz** [comment]
There are two patroling un'gore. Rest is stationary. One was moving a bit weird so I corrected it.
