### ISSUE TITLE
[Quest] Rise, Obsidion!

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#1075]
Decription: 
[Rise, Obsidion!](http://wowwiki.wikia.com/wiki/Quest:Rise,_Obsidion!)

How it works: 
No event. Lathoric the Black not appears, Obsidion can't be attacked.
![wowscrnshot_110318_010722](https://user-images.githubusercontent.com/43764742/47943305-1890c380-defe-11e8-80e2-1d0aecc0db71.jpg)

How it should work: 
https://youtu.be/ST3kBpw1_Ec?t=52
https://www.youtube.com/watch?v=APFLfm3ipO0

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented.
