### ISSUE TITLE
[Spell] Tracking gets removed upon disconnect

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1078]
Decription: I had track minerals enabled, before disconnect it was reset to none.

How it works: Tracking gets reset to none upon disconnect.

How it should work: Tracking should be saved unless player manually changes it.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Everything works fine for me. Maybe it was a server crash?
@neheri Can you reproduce it?

**Comment by neheri** [comment]
It was on server crash. Apologies for not accurate title.

**Comment by akrom23** [comment]
And you just learned mining prof before crash?

**Comment by neheri** [comment]
No I had mining since lvl 5 and I noticed that tracking was disabled when I was like lvl 25, not sure.

I will be watching tracking carefully now whether it's disabled after crash or not.

**Comment by akrom23** [comment]
Okay. I think works good, but maybe crash reset.
