### ISSUE TITLE
Mulgore Quests

### ISSUE THREAD

**Issue by forafriend** [SunwellWoW/Sunwell-TBC-Bugtracker#108]
Description: Various Mulgore Quest Items have drop rates set too high

How it works: 

- [ ] * The Hunt Begins - Drop rate seemed to be ~80-90%
- [ ] * The Hunt Continues - Recorded 10 drops in 12 lion kills
- [ ] * The Battleboars - 8/8 [Battleboar Snouts] & 8/8 [Battleboar Flanks] within 10 kills, retried after crash and roll back and got all items within 9 kills
- [ ] * Mazzranache - Drop rate for [Prarie Wolf Heart], [Flatland Cougar Femur], [Plainstrider Scale], and [Swoop Gizzard] seem to be at 100%. Testing destroying the item and killing the mob again, and it always dropped.
- [ ] * Swoop Hunting - Drop rate seems to be 100%
- [ ] * The Hunter's Way - Drop rate for [Flatland Prowler Claw] seems to be 100%
- [ ] * Dangers of the Windfury - Drop rate for [Windfury Talon] seems to be ~80%, if not a little higher

How it should work: 

Drop rates should be lower.

Source (you should point out proofs of your report, please give us some source): 

I'll comment if I find any helpful source!

**Comment by Silroth** [comment]
I dont think this should be changed, its a low leveling zone and lowering the drop rate would just make it a nightmare for thousands of players during launch. If anything the drop rates for quests that are very low (around 2-10%) should be increased to something decent.

**Comment by forafriend** [comment]
@Dootz Forgive my autism. I'll be the first to admit this is a fairly minor issue, but frankly the twinstar db is not a good source, and I would err towards the 40%. Here's better proof for the quest [The Hunter's Way]

https://www.wowhead.com/quest=861/the-hunters-way

- Patch 2.0.12 `.. rather pathetic drop rate for me however :(`

- Patch 2.1.3: `Kind of a slow drop rate.`

- Patch 2.3.0 `Got mine 4 in 7 mobs, easy done, North of TB` (~57% drop)

The following comment from 2.4.1 makes it seem like the drop rate was increased in 2.4, but the 3.03 comment leads me to believe the 2.4.1 poster got lucky.

- Patch 2.4.1 `51,30 i got a 100% drop rate from there. Might be they changed it on 2.4`

- Patch 3.0.3 `Thought this quest was a fairly good drop rate. Got all of mine in 8 kills, not so bad as some of the other comments.` (50% drop)

Please also note the page: https://www.wowhead.com/item=5203/flatland-prowler-claw#dropped-by notes a 43% drop rate.

https://web.archive.org/web/20071015055033/http://thottbot.com:80/q861
Oct 2007 `got drop on my 1, 2, 3 and 6 kill xD done this 5times with different quests... ` (~66.7% drop)

As you can see there's more evidence against the 80% value than for it. 

I don't know much about mangos programming, but I'd also like to add that the cmangos db (https://github.com/cmangos/tbc-db/commit/7497216a9b30cbc6d81396addfff214e16538f64) just got updated, and may be a good cross reference going forward with world loot.

**Comment by Dootz** [comment]
ok, i'll check again, sorry it took soo long, somehow i missed notification about your response. Thanks for digging and finding amazing sources.

**Comment by Dootz** [comment]
after some digging, I decided that we'll use values from light's hope database. Not all items have different (lower) drop chance but extensive percentage does. PTR will be updated most likely tomorrow.

**Comment by notsofamous** [comment]
I wouldn't trust wowhead comments as a good source to base drop rate % of. People usually go there and comment to complain/when they feel something is wrong. All the people who got their quest items with a fairly good drop rate won't go there and comment because... well, who does that  after every quest?

**Comment by Dootz** [comment]
yea, i know. Drop chance where adjusted based on Nost and LH databases.
