### ISSUE TITLE
Water pathing

### ISSUE THREAD

**Issue by Pizzle93** [SunwellWoW/Sunwell-TBC-Bugtracker#1083]
Decription: 
Mobs are a bit jumpy in water when chasing you (varying in depth instantly every second or so)

How it works: 
Mobs are a bit jumpy in water when chasing you (varying in depth instantly every second or so)

How it should work: 
Should move smoothly towards you

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
#669.
