### ISSUE TITLE
Palemane Gnoll Out of Combat Pathing and spamming spells

### ISSUE THREAD

**Issue by swimatt7000** [SunwellWoW/Sunwell-TBC-Bugtracker#1084]
Decription:  Tethered a group of Palemane Gnolls near the wall in Mulgore, and I left combat. When I ran over to begin pulling again the Palemane Tanner started shooting wraths at me at pauses during his normal out of combat "pathing". 

How it works: Mob not coming out of Out of Combat pathing and way points attacking player. Did not chase, and had not yet engaged in run away mechanic.

How it should work:  Mob should transition out of normal patroling mechanic when combat starts and move towards player. 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_103118_212057](https://user-images.githubusercontent.com/44726434/47952543-83b2b800-df47-11e8-8033-82ebefa0be1c.jpg)
![wowscrnshot_103118_212059](https://user-images.githubusercontent.com/44726434/47952544-87463f00-df47-11e8-83a8-feae43192d93.jpg)
![wowscrnshot_103118_212102](https://user-images.githubusercontent.com/44726434/47952546-89a89900-df47-11e8-88f1-9397aa2c8136.jpg)

**Comment by neheri** [comment]
That out of combat pathing is the same that happened yesterday to me in the report:
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1061
