### ISSUE TITLE
Palemane Tanner Pathfinding is Off

### ISSUE THREAD

**Issue by swimatt7000** [SunwellWoW/Sunwell-TBC-Bugtracker#1085]
Decription:  Shot a wrath at this palemane tanner in the cave when I ran back to pull him up via line of site mechanic he became stuck (Not inside of) but on the wall.  He did not evade, did not continue attacking. I had to jump down and kill him, where pathing should clearly be available for him to have come attack me. 8

How it works:  LOS pulls from on top of a ledge caused a mob to become stuck to a wall.

How it should work:  LOS pulls from on top of a ledge should either allow the mob to path towards you, or evade. 

Source (you should point out proofs of your report, please give us some source): 

![wowscrnshot_110218_205404](https://user-images.githubusercontent.com/44726434/47952595-692d0e80-df48-11e8-8e8f-14a3016d9eb6.jpg)

**Comment by akrom23** [comment]
ToDO: Mob should evade after a while beeing not able to reach the target.

**Comment by Wojtyas** [comment]
Fixed & implemented.
