### ISSUE TITLE
[NPC][Object] Thistlefur Totemic's Healing Ward IV

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1087]
Decription: Healing Ward summoned by hostile NPC was following and attacking me. Other creatures summoning totems should be checked for an instance Zul'farrak trolls. Because of low population on beta at the moment it will be hard to check and report that I am afraid.

How it works: Totem was moving and attacking.

How it should work: Totems should never move nor attack.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_110318_160630](https://user-images.githubusercontent.com/37372869/47953809-c34ac580-df82-11e8-9e61-9101e5d1391b.jpg)
![wowscrnshot_110318_160636](https://user-images.githubusercontent.com/37372869/47953813-c645b600-df82-11e8-9781-24f7bb171022.jpg)

**Comment by Wojtyas** [comment]
Totems got root flag. Fixed and implemented.
