### ISSUE TITLE
Kira Songshine

### ISSUE THREAD

**Issue by donque86** [SunwellWoW/Sunwell-TBC-Bugtracker#109]
Decription: 
shes a travelling vendor in elwynn forest that patrols back and forth to stormwind

How it works: 
she is flying mid air on her way from goldshire to stormwind city

How it should work: 
she should be walking normally on the ground

Source (you should point out proofs of your report, please give us some source): 
https://ibb.co/gvk1O9

**Comment by Nadiirr** [comment]
Still floating. 

![screenshot_86](https://user-images.githubusercontent.com/36300104/45595509-eb924c80-b961-11e8-99df-4b4f1d013137.png)
