### ISSUE TITLE
[NPC] Grimtotem Geomancer

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1093]
Decription: NPCs in Darkcloud Pinnacle are flying or walking in textures.

How it works: NPCs in Darkcloud Pinnacle are flying or walking in textures.

How it should work: They should walk over the bridge not through the bridge.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_110318_203603](https://user-images.githubusercontent.com/37372869/47956663-387cc180-dfa8-11e8-811a-e3df717b3f4f.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented.
