### ISSUE TITLE
[Spell] Charge under textures

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1096]
Decription: So it happened yes. For the first time on the Beta server after charging hundreds of times I did charge under textures. It was charge from water to a target on a land so maybe that caused the problem.

In addition to that after releasing spirit I was unable to move until relog. No mater if I pressed 'w' or both mouse buttons my char was just standing in place.

How it works: Charge brought me under textures.

How it should work: Charge shouldn't bring me under textures.

Source (you should point out proofs of your report, please give us some source): 

![wowscrnshot_110318_211829](https://user-images.githubusercontent.com/37372869/47956981-6107ba00-dfae-11e8-990e-170709ba1cbe.jpg)

**Comment by neheri** [comment]
Charge is working very well. I am charging to the extent and after 30hrs of played I only fell under textures once.

Somebody on beta test whispered me how Charge works so I think that a lot of people care about that and this is in some way quality test of a server that's why I report.

**Comment by akrom23** [comment]
@networm555 I doubt it.
@neheri Of course, there might be some problems with mmaps. We'll look into it :)
