### ISSUE TITLE
[NPC] Wrathguard, Doomwhisperer

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#1106]
Decription: 
[Wrathguard](https://tbc-twinhead.twinstar.cz/?npc=18975)
[Doomwhisperer](https://db.excalibur.ws/?npc=18981)

How it works: 
Wrathguard spell Flame Wave not working correctly.
![wowscrnshot_110418_021333](https://user-images.githubusercontent.com/43764742/47958365-edc46f00-dfd2-11e8-977e-960fa4dc2c3f.jpg)
Doomwhispere spell Draining Bolt has wrong dmg.
![wowscrnshot_110418_024930](https://user-images.githubusercontent.com/43764742/47958502-1a798600-dfd5-11e8-8d78-010e3e452f35.jpg)

How it should work: 
Flame Wave: summons a line of fire that hits (250 fire dmg for each tick) enemies in the way.
Draining Bolt: Causes the enemy to take 80 Shadow damage. The caster gains 100% of the damage caused in health.

Source (you should point out proofs of your report, please give us some source): 
Flame Wave links:
https://db.excalibur.ws/?spell=38607
https://tbc-twinhead.twinstar.cz/?spell=38607
https://www.wowhead.com/npc=18975/wrathguard#comments - can take info about dmg.

Draining Bolt link:
https://db.excalibur.ws/?spell=33969

**Comment by Fuzedknight** [comment]
Can confirm that this is still broken on the live server, the flame wave still summons an infernal and doesn't work as intended.

**Comment by tuigan** [comment]
https://gyazo.com/5fcf4c5471f5036c5a5e047e37894a7b

Still bugged
