### ISSUE TITLE
[NPC] Enraged Feral Scar

### ISSUE THREAD

**Issue by sunwelldude** [SunwellWoW/Sunwell-TBC-Bugtracker#1108]
Decription: 
http://db.hellfire-tbc.com/?npc=5295#abilities

How it works: 
Does way too much damage with his frostbolt valley.

How it should work: 
Inflicts 226 to 241 Frost damage to nearby enemies, reducing their movement speed by 50% for 10 sec.

Source (you should point out proofs of your report, please give us some source): 
![efs](https://user-images.githubusercontent.com/44537968/47958920-4e0cde00-dfde-11e8-8c10-6b6cec5806a1.jpg)

**Comment by Dootz** [comment]
this spell's damage is affected by level so damage received may vary.
