### ISSUE TITLE
[Ability / Mob's Abilities] Lighting Shield

### ISSUE THREAD

**Issue by Unfairy** [SunwellWoW/Sunwell-TBC-Bugtracker#111]
Decription: 
Poor Scripting of mob's use of this ability.

How it supposed to work:
Mob respawn -> Mob cast on himself ability Lighting Shield -> After engaging the battle and depleting shield, after certain period of time mob will recast it again.

How it works:
Either of 2:
1) Mob spawned with this ability
2) Mob isnt spawned with ability and wont cast it.

Easy test. Deplete mobs Lighting Shield and go evade. He will run away to his spell and ability will be recasted insta after mob evade - not supposed to be like this.

Need to be checked with other mobs.

**Comment by Wojtyas** [comment]
Already fixed with some core changes.
