### ISSUE TITLE
[Pet] Water Elemental pulling enemies from very far away.

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#1110]
Description: If you manually send your water elemental to attack an enemy, the enemy will instantly aggro even though the water elemental hasnt actually attacked, entered aggro range or finished casting his water bolt ability.

How it works: Read above.

How it should work: Mobs should only aggro once they are hit by an attack/spell (maybe missed & resisted as well?) if you are in their aggro range or if you aggro a nearby mob that calls for help.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@Eternae1 Cannot reproduce it. Could you test it again and give me some screenshots?

**Comment by Eternae1** [comment]
Seems to be fixed now.
