### ISSUE TITLE
Shaman totems dropping too far away from caster

### ISSUE THREAD

**Issue by jbwilson11** [SunwellWoW/Sunwell-TBC-Bugtracker#1112]
Decription: 
Shaman totems dropping too far away from caster

How it works: 

It feels like the totems are being cast 8-12 yards from caster. (eyeball measurement)
Links shows how far away stoneskin totem is from caster (overhead & front view).  I have only been able to verify earth and fire totems (only lvl 16).  
https://pasteboard.co/HLyydwt.png
https://pasteboard.co/HLyxxbY.png

How it should work: 
Totems should be laid at feet of caster and useful for people within 20 yard range..  This misplacement of totems can lead to unwanted mobs/aggro.

Source (you should point out proofs of your report, please give us some source): 
Youtube video shows different view https://youtu.be/beeUTMpLdwY?t=166]
Youtube video with totem twisting showing how close totems are set down https://www.youtube.com/watch?v=cKj6kYMe2-g

**Comment by Reflekz** [comment]
If this helps at all , mine are working fine (on a draenei)
![wowscrnshot_110418_033323](https://user-images.githubusercontent.com/44597439/47961490-82829900-dfe2-11e8-9400-af0bd12d6840.jpg)
![wowscrnshot_110418_033327](https://user-images.githubusercontent.com/44597439/47961494-844c5c80-dfe2-11e8-9fec-aa7bbd3799b4.jpg)

Might be a Racial thing ?

**Comment by akrom23** [comment]
@jbwilson11  It happens only with stoneskin?
