### ISSUE TITLE
[NPC] Deadwood Pathfinder

### ISSUE THREAD

**Issue by sunwelldude** [SunwellWoW/Sunwell-TBC-Bugtracker#1115]
Decription: 
http://db.hellfire-tbc.com/?npc=7155#abilities

How it works: 
Deadwood Pathfinders Piercing shot ability reduces armor too much.

How it should work: 
Piercing Shot
Armor reduced by 580.
15 seconds remaining

Source (you should point out proofs of your report, please give us some source): 
![dph](https://user-images.githubusercontent.com/44537968/47961389-bf668400-e012-11e8-8992-879a1f029e56.jpg)

**Comment by Dootz** [comment]
580 is a basic value of armor reduction. There is also level-dependent coefficient added to a final value.
