### ISSUE TITLE
[NPC] Jaedenar Adept

### ISSUE THREAD

**Issue by sunwelldude** [SunwellWoW/Sunwell-TBC-Bugtracker#1116]
Decription: 
http://db.hellfire-tbc.com/?spell=20832

How it works: 
Jaedenar Adept uses Fire Blast while stunned.

How it should work: 
I can't cast that.

Source (you should point out proofs of your report, please give us some source): 
![ja](https://user-images.githubusercontent.com/44537968/47961609-14a49480-e017-11e8-8cfa-edb49b9d4f1b.jpg)

**Comment by arcwizard** [comment]
Not only when stunned, but also in polymorph.
