### ISSUE TITLE
[Quest] The Fare of Lar'korwi

### ISSUE THREAD

**Issue by sunwelldude** [SunwellWoW/Sunwell-TBC-Bugtracker#1119]
Decription: 
http://db.hellfire-tbc.com/?quest=4290

How it works: 
Can't loot quest item Piece of Threshadon Carcass from the fresh threshadon carcass.

How it should work: 
http://db.hellfire-tbc.com/?item=11504 should be lootable from the carcass.

Source (you should point out proofs of your report, please give us some source): 
![tfol](https://user-images.githubusercontent.com/44537968/47962105-16268a80-e020-11e8-8445-1b859a1d700c.jpg)

**Comment by Reflekz** [comment]
I had no problems looting it , you need to be at the "sweet" spot because hes quite big.

**Comment by Eternae1** [comment]
I did this quest a few hours prior to you posting this, perhaps there is a bug where its not respawning the loot on the body?

**Comment by Reflekz** [comment]
We just encountered the same issue in WPL questing as 2 man group.
Inten was able to loot the item , and i was not (we waited a good 15 mins with no loot inside the box)
![wowscrnshot_110418_060932](https://user-images.githubusercontent.com/44597439/47962819-d7c9a500-dff8-11e8-8328-bcf97503da05.jpg)

**Comment by Dootz** [comment]
where aware of it. It's global bug after the recent update. Megathread was created and we're working on a fix.
