### ISSUE TITLE
[Object] Silver Vein, Gold Vein, Iron Vein

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1121]
Decription: 3 veins have been spawned on top of each other. "Special" veins have a chance to be spawned INSTEAD of (not on top of) standard veins, for example:

Tin Vein -> small chance to spawn silver vein
Iron Vein -> small chance to spawn gold vein and even smaller to spawn silver vein

Probably the same applies to khorium, if I manage to get to Outland before release I will test that.

How it works: 3 veins have been spawned on top of each other. 

How it should work: Silver Veins can spawn instead of any Tin veins. This is like a rare spawn among the veins. EDIT: Iron can also spawn them. But it has more chance to spawn a Gold Vein than a Silver Vein.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/object=1733/silver-vein#comments:id=540

![wowscrnshot_110418_101952](https://user-images.githubusercontent.com/37372869/47962322-97c7e980-e01b-11e8-80c5-95bfab99b9c8.jpg)
![wowscrnshot_110418_101953](https://user-images.githubusercontent.com/37372869/47962323-98608000-e01b-11e8-8914-3761504148f5.jpg)
![wowscrnshot_110418_102005](https://user-images.githubusercontent.com/37372869/47962324-98608000-e01b-11e8-959c-6e1312033fa2.jpg)

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1460
