### ISSUE TITLE
[Quest] Mission: The Murketh and Shaadraz Gateways

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#1122]
Decription: 
Perhaps there is no bug as such, but  is possible to have someone done this quest before me and the portals have been burning for too long (I flew for 20 minutes). In any case, when you open the server, at the one time this quest will do a lot of people.

How it works: 
It seems that the portals do not stop burning, and it does not allow to complete the quest.
![wowscrnshot_110418_120723](https://user-images.githubusercontent.com/43764742/47962440-5b998680-e025-11e8-9cf2-69a2c87c4759.jpg)
![wowscrnshot_110418_123128](https://user-images.githubusercontent.com/43764742/47962441-5b998680-e025-11e8-8b12-eae08b2f34bf.jpg)

How it should work: 
It is necessary to reduce the burning time of the portals to 1 minute (and it is better to make it dynamic depending on the online, but with a maximum limit of 1 minute).

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Quest%3AMission%3A_The_Murketh_and_Shaadraz_Gateways

**Comment by Eternae1** [comment]
They should be almost instant respawn so if someone is right behind you doing the same quest they can still get their own credit for it.

**Comment by Reflekz** [comment]
I just tried before and after this mornings "restart" and was unable to get credit.

**Comment by badmannerkid** [comment]
https://streamable.com/hykb7

quest still bugged, portals on fire etc

**Comment by neheri** [comment]
Same thing today, portals are on fire, bombing them but no credit - shame because it blocks you from remaining parts of the chain.

**Comment by Dootz** [comment]
I'm sorry it took so long. It will be fixed with next server update (tomorrow/day after tomorrow)
