### ISSUE TITLE
Solanian's Belongings

### ISSUE THREAD

**Issue by automnex** [SunwellWoW/Sunwell-TBC-Bugtracker#1123]
Decription: Quest 'Solanian's Belongings' in blood elf starting zone seems broken.

How it works: The three quest items are unobtainable.

How it should work: One should be able to obtain the three quest items by clicking on them (the scroll of scourge magic, the orb and the journal)

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_110418_115350](https://user-images.githubusercontent.com/44744075/47962644-67d31300-e028-11e8-8fdb-f4b2cace00e6.jpg)

**Comment by Dootz** [comment]
moved to megathread
