### ISSUE TITLE
[NPC] Bleeding Hollow Peon, Grunt, Tormentor, Dark Shaman, Necrolyte

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#1127]
Decription: 
[Bleeding Hollow Peon](https://db.excalibur.ws/?npc=16907)
[Bleeding Hollow Grunt](https://db.excalibur.ws/?npc=16871)
[Bleeding Hollow Tormentor](https://db.excalibur.ws/?npc=19424)
[Bleeding Hollow Dark Shaman](https://db.excalibur.ws/?npc=16873)
[Bleeding Hollow Necrolyte](https://db.excalibur.ws/?npc=19422)

How it works: 
All NPC have low melee dmg (considering value of my armor and talents). 
![wowscrnshot_110418_124411](https://user-images.githubusercontent.com/43764742/47963178-124f3400-e031-11e8-9fa6-e5cdb847a509.jpg)
![wowscrnshot_110418_124443](https://user-images.githubusercontent.com/43764742/47963179-12e7ca80-e031-11e8-93f6-1cfb2a346fe4.jpg)

Bleeding Hollow Tormentor, some of them go on foot, and even those who ride, don't dismount from the wolf and don't summon him.
![wowscrnshot_110418_125330](https://user-images.githubusercontent.com/43764742/47963181-1c713280-e031-11e8-8cd7-7c55f06f6d93.jpg)
![wowscrnshot_110418_125043](https://user-images.githubusercontent.com/43764742/47963185-2e52d580-e031-11e8-9924-56e45a55f1de.jpg)

Bleeding Hollow Dark Shaman has shadow bolt and Raise Soul, about which no information in wowhead, as well as in the comments. But they are found in the databases of other private servers (https://db.excalibur.ws/?npc=16873#abilities, http://db.hellfire-tbc.com/?npc=16873#abilities), but even if compared with the databases of those servers, the damage value of shadow bolt is too high. Also Bloodlust takes up a debuff slot.
![wowscrnshot_110418_130356](https://user-images.githubusercontent.com/43764742/47963187-3743a700-e031-11e8-8f2a-037028794468.jpg)

Bleeding Hollow Necrolyte has wrong fireball dmg, don't use Raise Dead.
![wowscrnshot_110418_130316](https://user-images.githubusercontent.com/43764742/47963191-4296d280-e031-11e8-8ac1-e7f2a7ed28d0.jpg)

How it should work: 
Bleeding Hollow Peon 
~175-225 dmg on a lvl 60 with 0 armor

Bleeding Hollow Grunt
~210 - 285 dmg on a lvl 60 with 0 armor
Strike ~260- 335 dmg on 0 armor around every 10 seconds

Bleeding Hollow Tormentor
Sits on his worg when OOC
~250-313 dmg on a lvl 60 with 0 armor.
Mend pet on his pet, restores 38 health per second.
Can fear a second target, will never fear the guy highest on his threatlist.
Hamstring 42-55 dmg, 9-10 seconds 60% slow <15% hp
Summons his wolf when aggrod.

Bleeding Hollow Dark Shaman 
Bloodlast must placed in buff slot.
~200-275 dmg on a lvl 60 with 0 armor, around 2 speed
I’m not sure about the fact that he has a bolt shadow and Raise Soul, but if you look at other private servers and leave a shadow bolt to him, then his damage should be [90-120 value](https://db.excalibur.ws/?spell=20825) (however, it seems to me personally (looking at fireball damage of necrolite) that this is also not true, too little for the outland creatures).

Bleeding Hollow Necrolyte
~255-310 dmg, slow attackspeed
Casts ~364-465 Fireball,  ~every 7 seconds
Casts Raise dead, <75% hp, source for the Bleeding Hollow Skeletons

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/npc=16907/bleeding-hollow-peon#comments
https://www.wowhead.com/npc=16871/bleeding-hollow-grunt#comments
https://www.wowhead.com/npc=19424/bleeding-hollow-tormentor#comments
https://www.wowhead.com/npc=16873/bleeding-hollow-dark-shaman#comments
https://www.wowhead.com/npc=19422/bleeding-hollow-necrolyte#comments

**Comment by Eternae1** [comment]
Also Bleeding Hollow Tormentor is casting his fear ability on himself lol....

**Comment by Reflekz** [comment]
![wowscrnshot_110618_025715](https://user-images.githubusercontent.com/44597439/48047847-cc4cba00-e16f-11e8-86f0-848275aac51f.jpg)
![wowscrnshot_110618_025717](https://user-images.githubusercontent.com/44597439/48047850-ceaf1400-e16f-11e8-912f-f53793e7675e.jpg)

**Comment by Dootz** [comment]
thank you for pointing it out. When it comes to self-fear it was a result of "failsafe" check that I've prepared (if it worked, it was supposed to make sure he can't self-fear). However i missed one negation making is so he can ONLY fear himself :D  Thank you very much once more.
When it comes to Shadow Bolt's damage I'll correct it as he's using wrong spell.
