### ISSUE TITLE
[Talent][Skill] Swepping strikes

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1147]
Decription: Execute procs swepping strike even if the other target has more than 20% of health. Swepping strikes has incorrect damage (two high - probably gets is impacted by some effects like enrage twice) but I am going do another report for that soon.

wowwiki:

Sweeping Strikes will not cause [Execute] to strike a nearby opponent unless the nearby opponent has less than 20% health (does not consume a charge of Sweeping Strikes either).

How it works: Execute procs swepping strike even if the other target has more than 20% of health. 

How it should work: Execute should not proc swepping strike unless the other target has less than 20% health.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Sweeping_Strikes
![wowscrnshot_110418_174738](https://user-images.githubusercontent.com/37372869/47967099-23606b00-e05a-11e8-8a27-e3f17edf4eb5.jpg)

**Comment by akrom23** [comment]
https://wow.gamepedia.com/Warrior_patch_history

> Execute - This ability will now work with Sweeping Strikes again. If the second victim is below 20% health, they will be hit with the full Execute amount. If the second victim is not below 20% health, they will be hit with normal melee swing damage.

**Comment by neheri** [comment]
My normal melee swings were ~70 OH and 110 MH. 
I was fighting 2 mobs. One had ~50% hp and the other one ~15%.
I had swepping strikes on. I used execute on mob with ~15% HP. 

Execute hit for 380. It cloned execute through swepping strike to 524. Damage transfered through swepping strike was 100% not normal melee swing, it was execute damage on mob ~50% health.

In addition to that swepping strikes takes enrage two times into consideration:

No enrage:
- white hit: 100, swepping strike: 100
Enrage:
- white hit: 100 * 1.25 = 125, swepping strike: 125 * 1.25 = 156,25 (instead of 125). 

At least that's how it was when I reported that. Swepping strikes taking talents multiple times into calculation needs separate report. However regarding that execute clone, I am 100% sure that it didn't work properly when I created this report.

**Comment by neheri** [comment]
Today tests:

![wowscrnshot_112018_181605](https://user-images.githubusercontent.com/37372869/48790826-8146b100-ecf0-11e8-8e80-c67be2de1a6f.jpg)
~1600 execute cloned to ~1430 swepping strike.
![wowscrnshot_112018_181609](https://user-images.githubusercontent.com/37372869/48790882-a509f700-ecf0-11e8-8f16-62b66fb5c18b.jpg)
 To compare in case if you wonder if a white attack was cloned - two crits ~450 ~330

![wowscrnshot_112018_181432](https://user-images.githubusercontent.com/37372869/48790980-e9959280-ecf0-11e8-9f03-cca04c75532c.jpg)
![wowscrnshot_112018_181434](https://user-images.githubusercontent.com/37372869/48790983-ec908300-ecf0-11e8-8c32-8fdd5b60482a.jpg)
![wowscrnshot_112018_181603](https://user-images.githubusercontent.com/37372869/48790992-f0bca080-ecf0-11e8-8078-088395e44160.jpg)
![wowscrnshot_112018_181604](https://user-images.githubusercontent.com/37372869/48790994-f1edcd80-ecf0-11e8-9434-47243e5046b2.jpg)
