### ISSUE TITLE
Hunter pet LoS issue

### ISSUE THREAD

**Issue by Switze** [SunwellWoW/Sunwell-TBC-Bugtracker#1150]
Decription: Hunter pet when commanded to attack an npc who's behind a tree for an example. it does nothing

How it works: not possible to command pet to engage combat with LoS npc even close range.

How it should work: Pet shouldnt care whether the npc is Los or not. 

Source (you should point out proofs of your report, please give us some source): 
the issue is everywhere. right here im clicking my pet attack button and nothing happens.
![los issue](https://user-images.githubusercontent.com/44751881/47967506-50168180-e05e-11e8-9748-cdf309850002.jpg)

**Comment by Wojtyas** [comment]
So the question is: is it fair enough? Actually reported part is fixed but should it also work for pet spells?

**Comment by Wojtyas** [comment]
Fixed & implemented. Pet will start to chase targeted creature upon Attack Command with respect to LoS.
