### ISSUE TITLE
[NPC] Unyielding Footman, Knight, Sorcerer, Lieutenant Commander Thalvos, Arch Mage Xintor

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#1153]
Decription: 
[Unyielding Footman](http://db.darkwizard.pl/?npc=16904)
[Unyielding Knight](http://db.darkwizard.pl/?npc=16906)
[Unyielding Sorcerer](http://db.darkwizard.pl/?npc=16905)
[Lieutenant Commander Thalvos](http://db.darkwizard.pl/?npc=16978)
[Arch Mage Xintor](http://db.darkwizard.pl/?npc=16977)

How it works: 
All NPCs have low melee damage.
![wowscrnshot_110418_180814](https://user-images.githubusercontent.com/43764742/47966004-3bce8680-e056-11e8-98aa-600712bbb431.jpg)
![image](https://user-images.githubusercontent.com/43764742/47965933-6409b580-e055-11e8-8501-d17a9a8a3fbe.png)
![wowscrnshot_110418_181119](https://user-images.githubusercontent.com/43764742/47967459-61fc2280-e066-11e8-9112-249e0f2c44b9.jpg)
![wowscrnshot_110418_190231](https://user-images.githubusercontent.com/43764742/47967492-98d23880-e066-11e8-861f-00eadaf5b2b9.jpg)

Arch Mage Xintor use blizzard with 1 physical dmg per tick against player, and fireball with ~ 600-800dmg.
![wowscrnshot_110418_201242](https://user-images.githubusercontent.com/43764742/47967495-9ff94680-e066-11e8-954c-a610d9db5867.jpg)
![wowscrnshot_110418_201220](https://user-images.githubusercontent.com/43764742/47967494-9ff94680-e066-11e8-95fa-81b2775b77bc.jpg)

How it should work: 
Melee dmg value for NPC in description. 
Arch Mage Xintor must use spell [blizzard](https://www.wowhead.com/spell=29458/blizzard), [fireball](https://www.wowhead.com/spell=29456/fireball), [frostbolt](https://www.wowhead.com/spell=29457/frostbolt) and [pyroblast](https://www.wowhead.com/spell=29459/pyroblast) only against dummyes, there must be some event (in which the NPC uses the above listed spells against dummies).  Arch Mage Xintor against player must use [fireball (same name, but other spell) with 475-609 base dmg](http://db.darkwizard.pl/?spell=10150), [arcane missiles](http://db.darkwizard.pl/?spell=15735) and [ice barrier](https://www.wowhead.com/spell=33245/ice-barrier).

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=2p_ykqlen4g here other patch, and not good quality, but you can see how this NPC cast blizzard on dummies, unfortunately I could not find a video with this event of better quality.

**Comment by Eternae1** [comment]
Arch Mage Xintor's Arcane Missiles ability is showing the animation of being casted by the player, not the NPC Xintor himself.
