### ISSUE TITLE
[NPC] Ringo

### ISSUE THREAD

**Issue by sunwelldude** [SunwellWoW/Sunwell-TBC-Bugtracker#1166]
Decription: 
http://db.hellfire-tbc.com/?npc=9999
http://db.hellfire-tbc.com/?quest=4491

How it works: 
The npc doesn't respawn after failing/completing the escort quest. I came back after an hour and he still wasn't there.

How it should work: 
Should respawn shortly after someone has done or failed the quest.

Source (you should point out proofs of your report, please give us some source):

**Comment by Eternae1** [comment]
It worked fine for me when I did it yesterday, I went back to see if he had respawned and he was there after I finished it.
