### ISSUE TITLE
Fisher guys feet in Crystal Lake are stuck in the dock

### ISSUE THREAD

**Issue by leahnie956** [SunwellWoW/Sunwell-TBC-Bugtracker#1168]
Decription: 
Fisher guys feet in Crystal Lake are stuck in the dock

How it works: 
should not be in the dock

How it should work: 
not like that

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/25886407/47975636-41d36000-e074-11e8-9792-4121c9da429e.png)

**Comment by Wojtyas** [comment]
Fixed & implemented.

![image](https://user-images.githubusercontent.com/22802214/48845849-e1476100-ed9d-11e8-8274-2a21a56067bc.png)
