### ISSUE TITLE
[NPC] Deathclasp

### ISSUE THREAD

**Issue by Reflekz** [SunwellWoW/Sunwell-TBC-Bugtracker#1178]
Decription: 
I killed Deathclasp and then returned maybe an hour or two later to see him Not being respawned yet.

How it works: 
Deathclasp is showing a 10minute respawn and is way over that 10 mins.

How it should work: 
Deathclasp should respawn roughly in a 10min window.

Source (you should point out proofs of your report, please give us some source): 
Might not be related to Deathclasp - But the more you know :)
http://db.hellfire-tbc.com/?npc=15196
http://db.darkwizard.pl/?npc=15196
![wowscrnshot_110518_035235](https://user-images.githubusercontent.com/44597439/47984889-5d5b5c80-e0ae-11e8-86c5-2b3c1dff38e2.jpg)
![wowscrnshot_110518_035245](https://user-images.githubusercontent.com/44597439/47984896-60564d00-e0ae-11e8-94fc-a9b47c3b6222.jpg)

**Comment by Reflekz** [comment]
Hes back up , but not patrolling , just standing in one spot.
iirc he should patrol up and down.
![wowscrnshot_110518_060307](https://user-images.githubusercontent.com/44597439/47991501-af0ce280-e0c0-11e8-8233-d24314f399da.jpg)

**Comment by nimeral** [comment]
I think it's still bugged. 've been waiting for him for 15 minutes now. I'm virtually the only person in Silithus at the moment, so it's highly unlikely he was killed "recently".

**Comment by Dootz** [comment]
Hi, I just checked and he's walking up and down his standard path. He's respawn timer is 10 minutes.
![obraz](https://user-images.githubusercontent.com/25490436/56084412-fac37500-5e32-11e9-9e68-a74ce21119db.png)
