### ISSUE TITLE
[NPC] Morin Cloudstalker

### ISSUE THREAD

**Issue by forafriend** [SunwellWoW/Sunwell-TBC-Bugtracker#118]
Decription: NPC Morin Cloudstalker in Mulgore is not patrolling/pathing the correct route.
Entry 2988
GUID 26577

How it works: Morin Cloudstalker currently is at cords 57.4 61.2 just randomly walking about.

How it should work: Morin Cloudstalker should patrol the path from 51.8,59.5 to 59.1,62.1

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=751/the-ravaged-caravan#comments
Comment Patch 2.3 `The Quest NPC walks a line between 51.8,59.5 (The three-way intersection in the bloodhoof village roads) to 59.1,62.1 (about half-way to the barrens going east on the road.)`

https://web.archive.org/web/20080305082434/http://thottbot.com:80/c2988
Multiple Comments 
`Yes, he is not really in any specific location, but rather patrols that road south of the village that leads to Barrens. `
`He walks up and down the Bloodhoof road `
`He's easy to find. Just start at the signposts outside Bloodhoof Village and follow the road along to The Barrens. You'll bump into him somewere along there :) `

**Comment by Dootz** [comment]
will be fixed with next server update
