### ISSUE TITLE
[NPC] Quillfang Ravager, Quillfang Skitterer, Stonescythe Whelp, Stonescythe Alpha

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#1181]
Decription: 
[Quillfang Ravager](http://db.hellfire-tbc.com/?npc=16934)
[Quillfang Skitterer](http://db.hellfire-tbc.com/?npc=19189)
[Stonescythe Whelp](http://db.hellfire-tbc.com/?npc=16927)
[Stonescythe Alpha](http://db.hellfire-tbc.com/?npc=16929) 

How it works: 
All NPC have low melee dmg.
![wowscrnshot_110518_115213](https://user-images.githubusercontent.com/43764742/47993075-42f9a100-e0f7-11e8-971c-e5139ccab403.jpg)
![wowscrnshot_110518_120730](https://user-images.githubusercontent.com/43764742/47993077-42f9a100-e0f7-11e8-9d3c-0d36043efc5a.jpg)
![wowscrnshot_110518_133822](https://user-images.githubusercontent.com/43764742/47993294-c6b38d80-e0f7-11e8-807e-1257c0473229.jpg)

Stonescythe Whelp and Stonescythe Alpha ability Desperate Defense works incorrectly (During the Desperate Defense action, the NPC continues to beat the character if he stand in melee range. After Desperate Defense gone, NPC stand in one place and can't move.  If NPC took(absorb) damage during the Desperate Defense action, the NPC don't activate [Desperate Rage](https://www.wowhead.com/spell=33898/desperate-rage).
![wowscrnshot_110518_123625](https://user-images.githubusercontent.com/43764742/47993097-5147bd00-e0f7-11e8-9e64-b9ccb6801bb6.jpg)
![wowscrnshot_110518_123636](https://user-images.githubusercontent.com/43764742/47993098-5147bd00-e0f7-11e8-924f-7f71c50291ad.jpg)
![wowscrnshot_110518_133107](https://user-images.githubusercontent.com/43764742/47993099-5147bd00-e0f7-11e8-912b-6c3854ae5e04.jpg)
![wowscrnshot_110518_133116](https://user-images.githubusercontent.com/43764742/47993101-51e05380-e0f7-11e8-9597-4342ea1159f2.jpg)

How it should work: 
All NPC must do more melee dmg, like in description.
Desperate Defense: makes them invulnerable to harm but unable to attack. When they do this, if you hit them while they're invulnerable not only will they not take damage, but it will activate their Desperate Rage. After Desperate Defense gone,  NPC can move.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/npc=16927/stonescythe-whelp#comments
https://www.wowhead.com/npc=16929/stonescythe-alpha#abilities

**Comment by Reflekz** [comment]
So i got to test , everything stated is true except for the Rage part.
I can trigger the Desperate Rage while Desperate Defense is up.
![wowscrnshot_110618_075820](https://user-images.githubusercontent.com/44597439/48062900-c79cfb80-e199-11e8-9f95-2adc1b034bda.jpg)
