### ISSUE TITLE
[General]Spamming

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1184]
Decription: 
Im able to spam

How it works: 
typing s every 1 sec, no problems doing it

How it should work: 
Well., im not sure if it was allowed on tbc, but its a suggestion to prevent spamming, do mute automatically someone for like 1 minute after a spam and more minutes after continuing it, AUTOMATICALLY, like its on Agrathar ;)

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Spam what? Macro? Spell? Just /say?
