### ISSUE TITLE
Torek's Assault bug

### ISSUE THREAD

**Issue by Stondis** [SunwellWoW/Sunwell-TBC-Bugtracker#1189]
Decription:  Torek's Assault (https://db.excalibur.ws/?quest=6544) in Ashenvale is bugged. Quest worked fine initially and I got it completed,
but after like 15 minutes I got a message in chat saying the quest had failed and had to redo it (and turn
it in right away) 

How it works:  It shouldnt fail after its already been completed

How it should work:  It should stay completed in your log.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
merged with https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2250
