### ISSUE TITLE
Loot Table for "Venture Co. Supervisor" and "Venture Co. Worker"

### ISSUE THREAD

**Issue by forafriend** [SunwellWoW/Sunwell-TBC-Bugtracker#119]
Description: Loot Table for "Venture Co. Supervisor"(c 2979)  and "Venture Co. Worker" (c  2978) in Mulgore seem to be incorrect. They are dropping too many armor pieces. I did the quest "The Venture Co." (q 764) and "Supervisor Fizrocket" twice for the following drop stats.

![image](https://user-images.githubusercontent.com/42325739/44107925-1f3fe9f4-9fb6-11e8-8c19-c872ca66363d.png)

How it works: 
- Warrior's Gloves (2968) dropped 11/15 times from Venture Co. Supervisor
- Journeyman's Gloves (2960) dropped 7/15 times from Venture Co. Supervisor
- Pioneer Bracers (6519) dropped 10/15 times from Venture Co. Supervisor
- Warrior's Bracers (3214) dropped 28/51 times from Venture Co. Worker (Also dropped 7/11 times from Prairie Wolf Alpha)
- Warrior's Girdle (4659) dropped 10/51 times from Venture Co. Worker
- Burnt Leather Belt (4666) dropped 14/15 times from times from Venture Co. Supervisor
- Fine Scimitar (4560) dropped 25/51 times from Venture Co. Worker

How it should work: 
Drops shouldn't be as high as they are. Shouldn't loot a mob and get 3 armor pieces at a time in addition to coppers and linen cloths.

Source (you should point out proofs of your report, please give us some source): 
Drop tables for mobs in question:
https://web.archive.org/web/20071016050728/http://thottbot.com:80/c2978
https://web.archive.org/web/20071016050733/http://thottbot.com:80/c2979

https://www.wowhead.com/npc=2978/venture-co-worker
https://www.wowhead.com/npc=2979/venture-co-supervisor

**Comment by Dootz** [comment]
will be fixed with next server update
