### ISSUE TITLE
(Quest-Enhancement) Outland Sucks!

### ISSUE THREAD

**Issue by Krefty** [SunwellWoW/Sunwell-TBC-Bugtracker#1198]
Decription: 
There are about 5 gobjects that contain the quest item spawned http://db.darkwizard.pl/?object=183934 , there should be a bit more spawned.
http://db.darkwizard.pl/?quest=10236
How it works:
Only 4 - 5 gobjects are spawned at a time.

How it should work: 
There should be more

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/9CW0Z9z0l2I?t=19

**Comment by Mikov1605** [comment]
confirmed https://www.wowhead.com/quest=10236/outland-sucks
