### ISSUE TITLE
[hunter] pet issue mounting and dismounting.

### ISSUE THREAD

**Issue by anubyss** [SunwellWoW/Sunwell-TBC-Bugtracker#120]
Decription:  Hunter pet have a problem with mount and dismount

How it works: When as hunter u use mount, your pet dissmis as it should BUT when u missmount it appears as unknown and the one way to get your pet back is dissmising and recalling.

How it should work: When u dismount your pet should auto spawn and not need to be called or dismissed and called.

Source (you should point out proofs of your report, please give us some source): 

this is how works now on our server: https://imgur.com/a/7lb8tsI

this is how it should work: https://imgur.com/a/6LwaDxL

**Comment by anubyss** [comment]
Add: u must to dissmis in the same spot u mounted or teleported to get your pet back

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC/commit/c44a9cc02b4625125155e368ac99d53a9cbe0796
