### ISSUE TITLE
[Serpentshrine Cavern] The Lurker Below

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1208]
Decription: 
Coilfang Archer's Shoot does 15 dmg
Spout one shots
Whirl doesn't knock you back at all
Fish don't spawn in SSC water and water also isn't hot

How it works: 

- [x] Coilfang Archer's Shoot does 15 dmg

- [x] Spout one shots players

- [x] Whirl  doesn't knock you back at all

- [x] Fish don't spawn in SSC water and water also isn't hot

- [x] Submerge timer was off

How it should work: 

- [x] off Spout shouldn't one shot

- [x] Coilfang archer should deal a bit more dmg, i think round 1300 on cloth

- [x] Whirl should knock you back

- [x] Fish should spawn in water and if they aren't spawning the water should be hot like lava

- [x] Submerge timer was off by at least 30s

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=JhWuAKAwTaw&

**Comment by notsofamous** [comment]
- Coilfang Ambusher's spread shot should be ~3000 damage.
http://www.mmopurge.com/forum/archive/index.php/t-2939.html
http://www.tentonhammer.com/guides/serpentshrine-cavern-guide-the-lurker-below

**Comment by Wojtyas** [comment]
- [ ] Lurker should be tauntable.
