### ISSUE TITLE
[Quest] A Little Help From My Friends

### ISSUE THREAD

**Issue by sunwelldude** [SunwellWoW/Sunwell-TBC-Bugtracker#1211]
Decription: 
http://db.hellfire-tbc.com/?quest=4491

How it works: 
Ringo keeps following mobs if you enter combat after he feints.

How it should work: 
He should be stationary until you wake him up using Spraggle's Canteen.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=Tm7rQ88Ig5E

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1166
