### ISSUE TITLE
[Quest] Disrupt Their Reinforcements - Object not working properly.

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#1212]
Description: You need to get 8 quest items total to drop from mobs and disrupt two portals. The "Portal Grimh" is not working. I can not interact with it to finish the quest. It also is not highlighted in anyway when I mouse-over it. ( Yes I have enough of the required quest item to "disrupt the portal" )

How it works: ^

How it should work: Game objects should be interact-able and usable if you have enough of required items.

EDIT: I was able to get "Portal Grimh" to work by right clicking the item "Kingston's Primers" and then clicking on the Portal. It still did not show as an object like the "Portal Kaalez" does.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_110518_231812](https://user-images.githubusercontent.com/42300476/48046478-d233a280-e151-11e8-9948-b55e5f520e8c.jpg)

**Comment by Reflekz** [comment]
Working for me :o
![wowscrnshot_110618_032843](https://user-images.githubusercontent.com/44597439/48049161-294a6f00-e174-11e8-8771-ffa940d4dd94.jpg)
