### ISSUE TITLE
[NPC] Mistress Natalia Mar'alith

### ISSUE THREAD

**Issue by sunwelldude** [SunwellWoW/Sunwell-TBC-Bugtracker#1217]
Decription: 
http://db.hellfire-tbc.com/?npc=15215

How it works: 
Has way too much health.

How it should work: 
Should have less hp.
http://db.hellfire-tbc.com/?npc=15215
http://db.darkwizard.pl/?npc=15215

Source (you should point out proofs of your report, please give us some source): 
![mnm](https://user-images.githubusercontent.com/44537968/48047229-19488480-e1a0-11e8-9fea-62cec36c7eff.jpg)

**Comment by nimeral** [comment]
You nerfed her to 13000 HP, but it's not enough. About 5500/5149/5180 should be the correct number of HP, https://www.wowhead.com/npc=15215/mistress-natalia-maralith#comments:id=188119, https://www.wowhead.com/npc=15215/mistress-natalia-maralith#comments:id=281372, http://db.darkwizard.pl/?npc=15215.

Also I feel she overcasts stuns/fears - one thing is to use it often as WoWHead suggests, another thing is to chain it 3 times in a row so player can do literally nothing.
