### ISSUE TITLE
[hunter] pet movement when using dash is wrong

### ISSUE THREAD

**Issue by anubyss** [SunwellWoW/Sunwell-TBC-Bugtracker#122]
Decription:  when you send your pet with Dash used if runs in and out without sense.

How it works: when you send your pet with Dash used if runs in and out without sense.

How it should work:  no weird movement should happen.

Source (you should point out proofs of your report, please give us some source): 

how it works: https://imgur.com/a/WCRNRMB

how it should work: https://imgur.com/a/xGcmkZI

**Comment by notsofamous** [comment]
Works
