### ISSUE TITLE
[Vendors] Magus Zabraxis

### ISSUE THREAD

**Issue by Reflekz** [SunwellWoW/Sunwell-TBC-Bugtracker#1224]
Decription: 
Magus Zabraxis should have infinite stock of vials , but only has 5.

I've also noticed many other vendors in the world which had Infinite stock of potions (is this a vendor per vendor issue or a general issue ?) i Plan to go back and search many vendors (for examble the herbalist vendor in Stormwind has infinite stock of peacebloom,silverleaf and liferoot )

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?npc=16829#sells
https://db.excalibur.ws/?npc=16829
![wowscrnshot_110618_081854](https://user-images.githubusercontent.com/44597439/48063896-be615e00-e19c-11e8-9cfb-4322999b9904.jpg)
![wowscrnshot_110618_081850](https://user-images.githubusercontent.com/44597439/48063901-c02b2180-e19c-11e8-990a-c75908912c81.jpg)
![wowscrnshot_110618_081900](https://user-images.githubusercontent.com/44597439/48063905-c28d7b80-e19c-11e8-93bd-7dbc2bdbde07.jpg)

**Comment by Dootz** [comment]
It was probably intentional, question is why? :D i wasn't able to find anything about it :(

**Comment by Reflekz** [comment]
about the stock ?
![vendor](https://user-images.githubusercontent.com/44597439/48110252-6caee700-e221-11e8-9764-b24a10302316.png)

**Comment by Dootz** [comment]
sorry about that. My bad. I should have researched more before that question.
