### ISSUE TITLE
Mindcontroling mobs in Slave Pens causes clipping 

### ISSUE THREAD

**Issue by liepelt089** [SunwellWoW/Sunwell-TBC-Bugtracker#1225]
Decription: When you get mindcontrolled and feared by a teammate, you start to clip in the air.

![2018-11-06](https://user-images.githubusercontent.com/44815226/48084969-5a20b780-e1f9-11e8-9fae-0e480f75bcb0.png)

Got feared up onto a rockface in the roof. After the first tunnel in Slave Pens

How it works: Get mindcontrolled, a teammate use fear.

How it should work: Should not clip in the air when feared

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Probably got fixed during recent mechanics changes. Feel free to reopen if needed.
