### ISSUE TITLE
[Serpentshrine Cavern] Leotheras the Blind

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1226]
- [x] Greyheart Spellbinder low HP, 115k sunwell, 191400 according to Nihilum

- [x] Inner Demon too low HP, should be 12k

- [x] Can't damage your Inner Demon

- [x] On one occasion the demon just disappeared and the person was MCed anyway.

- [x] His general running speed is too slow

- [x] Movement speed during whirlwind is too slow

- [x] Greyheart Spellbinders do not start channeling again if you reset the boss.

- [x] Leotheras kneels down and is dragged across the room when resetting, should be walking.

- [x] Weird behaviour after whirlwind, he keeps following his last target but has aggro on someone else
https://gyazo.com/48831c23447b76bf9c21c6b5fdf91324
https://gyazo.com/8f7cea0565464e0936ebbaaa8e1459ae

- [x] Leotheras too low HP, 3,7 million, should be 4500000 

- [x] Whirlwind Bleed should not be mitigated by armor, should always tick for 2500, varies a lot atm
![Image](https://i.gyazo.com/804923401278c23c316d1dc2d87ead26.png)

- [x] Leotheras wrong position, should be closer to the wall

https://www.youtube.com/watch?v=HnDQi2RCkSE
https://github.com/Schaka/TBC-research/issues/10
http://wowwiki.wikia.com/wiki/Greyheart_Spellbinder

**Comment by Kokaina** [comment]
Health points of entire encounter creatures will be set to prenerf values later. Thanks for feedback.

**Comment by notsofamous** [comment]
- [x] His default position is currently weird
![Image](https://i.gyazo.com/4fc570f075261992bf54ae3ae5be98d0.png)

**Comment by Wojtyas** [comment]
wtf, on SSC realm?

**Comment by notsofamous** [comment]
was on closed beta, not sure how up to date it is
