### ISSUE TITLE
Casting through pillars

### ISSUE THREAD

**Issue by mrnorr** [SunwellWoW/Sunwell-TBC-Bugtracker#1227]
Decription: 
Nagrand Arena (Ring of Trials) can cast through pillars

How it works: 
Nagrand Arena (Ring of Trials) can cast through pillars

How it should work: 
You should not be able to cast spells through a pillar object

Source (you should point out proofs of your report, please give us some source): 
Dueling in the Ring of Trials now with a mage on the beta server

**Comment by akrom23** [comment]
And what about the arena?

**Comment by mrnorr** [comment]
What I'm saying is is that in that arena, open world, non-instanced, the mage was able to cast full cast Frostbolt on me and hit me through the four pillars, at that location

**Comment by akrom23** [comment]
Okay. Can you test it on Nagrand Arena (arena)?

**Comment by mrnorr** [comment]
Sure thing, hopefully can get some others to join so I can get in the instanced version

-------- Original Message --------

**Comment by akrom23** [comment]
Tell me, how you get there?

**Comment by akrom23** [comment]
Cannot reproduce on open beta. Some screenshots please?

**Comment by akrom23** [comment]
Will be fixed after restart on SSC realm..
