### ISSUE TITLE
The Deadmines

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#123]
### **TO DO:**

- [ ] 1. Mr. Smite issues:
- Boss doesn't pull when we cross his pull spot. Defias Blackgrounds pull w/o boss.
![image](https://user-images.githubusercontent.com/22802214/45474449-17cb8480-b73a-11e8-8514-6a847bf0a290.png)
- [ ] 2. Captain Greenskin (647) has undead model while it should be goblin lol.
**EDIT: Looks like he's undead only for horde players. Or i dunno.**
- [ ] 3. I dunno what happened but Defias Companions changed to neutral from hostile and don't attack players now.
![image](https://user-images.githubusercontent.com/22802214/45474370-e18e0500-b739-11e8-852d-49d6ee94800d.png)

### **DONE:**

- [x] 1. Defias Miner (598) should use his Pierce Armor spell (6016) more often.
- [x] 2. Defias Evoker (1729) should be more focused on casting spells instead of damage by melee.
- [x] 3. Defias Evoker should cast his Quick Flame Ward spell (4979) on other Defias npcs as well. For now he casts it only on himself.
- [x] 4. Game object Factory Door (30533) should open instantly once Rhahk'Zor boss (644) is dead. For now the doors are clickable while they shouldn't.
- [x] 5. Miner Johnson (3586) should be rare spawn which app. 25% chance to be present in dungeon.
- [x] 6. Miner Johnson should have digging animation like other miners have.
- [x] 7. Looks like Goblin Woodcarver (641) doesn't use his Axe Toss spell (6466) when he and his target are over 20yards apart.
- [x] 8. Sneed's Shredder (642) should use his Distracting Pain (3603) spell more often.
- [x] 9. Sneed (643) should use his Disarm spell (6713) more often.
- [x] 10. Defias Wizard (4418) can interrupt his own cast by starting cast new spell (if I figured it out he always interrupts his casts by starting cast Quick Flame Ward 4979).
- [x] 11. Defias Wizard has same issue as Defias Evoker - sometimes he's more focused to melee damage than casting spells. He can run to players in order to melee hit them even if he's able to cast damaging spells.
- [x] 12. Goblin Craftsman (1731) doesn't use his Summon Remote-Controlled Golem spell (3605). Each of Craftsman should spawn 1 Golem.
- [x] 13. In Goblin Foundry location there are a lot of Remote-Controlled Golem NPCs. Well, they shouldn't be there. They should be spawned by Goblin Craftsmans and Goblin Engineers (622) but they never should be present before that.
- [x] 14. Spawned Remote-Controlled Golem should be Craftsman's/Engineer's guardian.
- [x] 15. When we use Defias Cannon (26205) and destroy Iron Clad Door (30534) 2-3 Defias Pirates (657) should spawn and attack players immediately. For now they are spawning but they run God knows where.
- [x] 16. Defias Companion (3450) should be Defias Pirate's (657) guardian.
- [x] 17. Every Defias Companion should be already spawned by Defias Pirate's spell named Bloodsail Companion (5172). Defias Companion should walk as formation with its owner. There should be only one spawned companion per Pirate.
- [x] 18. Defias Squallshaper (1732) doesn't use his Frost Nova spell (122). I was there alone, maybe he uses it when more meele is around him?
- [x] 19. Cookie (645) should use his Cookie's Cooking spell (5174) more often when below 50% hp.
- [x] 20. Edwin VanCleef (639) should use his VanCleef's Allies spell (5200) right after pull in order to summon 2x Defias Blackguards, who should start attak players immediately. Once party wipe they should disappear and should be summoned again after next pull. I believe he doesn't use that spell because someone put 2 Defias Blackguard npc as perm creatures there ;p
- [x] 21. Those two Defias Blackguard just before Edwin VanCleef shouldn't be present at all. GUIDs: 79368 and 79383
- [x] 22. Captain Greenskin's path has to be corrected. He should walk around VanCleefs house.
- [x] 23. Spawned Remote-Controlled Golem should start to attack players immediately.
- [x] 24. Those 3 NPCs should walk around from top of the room to below instead of stayin in place. GUIDs: 79378, 79379, 79380.
![image](https://user-images.githubusercontent.com/22802214/44147110-f476a5b8-a092-11e8-9f57-6d9bcb9e76e6.png)
- [x] 25. Item An Unsent Letter (2874) should only drop if party is from Alliance.
- [x] 26. When we use Defias Cannon in order to open Iron Clad Door there are two Defias Pirates rushin at us. Their parrots Defias Companions should rush as well.
- [x] 27. After Sneed's Shredder is dead Sneed boss doesn't spawn or he's spawning dead already.
- [x] 28. Comment with position code puts those 3 creatures in unknown location :( 2 79283 and 79285 are in textures while 79284 is invisible or in wall.
_UPDATE creature SET position_x = -229.343414, position_y = -578.556519, position_z = 51.227772, orientation = 3.129497 WHERE guid IN(79284);
UPDATE creature SET position_x = -268.245270, position_y = 1125.750000, position_z = 42.495678, orientation = 4.704379 WHERE guid IN(79285);
UPDATE creature SET position_x = -237.204117, position_y = 1127.095947, position_z = 42.064510, orientation = 4.704379 WHERE guid IN(79283);
UPDATE creature SET MovementType = 0 WHERE guid = 79285;
UPDATE creature SET MovementType = 0 WHERE guid = 79283;_

**Comment by Kokaina** [comment]
Lets add this as well:

UPDATE creature SET position_x = -229.343414, position_y = -578.556519, position_z = 51.227772, orientation = 3.129497 WHERE guid IN(79284);
UPDATE creature SET position_x = -268.245270, position_y = 1125.750000, position_z = 42.495678, orientation = 4.704379 WHERE guid IN(79285);
UPDATE creature SET position_x = -237.204117, position_y = 1127.095947, position_z = 42.064510, orientation = 4.704379 WHERE guid IN(79283);
UPDATE creature SET MovementType = 0 WHERE guid = 79285;
UPDATE creature SET MovementType = 0 WHERE guid = 79283;

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
List updated.
