### ISSUE TITLE
[NPC] Bleed Hollow Dark Shaman's Shadowbolt ability dealing too much dmg.

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#1230]
Description: Bleed Hollow Dark Shaman's Shadowbolt ability is dealing around 2k shadow damage. I dont believe he is supposed to cast shadowbolt, but if he is then its not supposed to hit for 2k.

How it works: ^

How it should work: Lower the damage on Shadowbolt if it belongs on that NPC.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_110518_234045](https://user-images.githubusercontent.com/42300476/48092892-2333ad00-e1cb-11e8-94a7-6d740a0319e1.jpg)

**Comment by Pizzle93** [comment]
It should cast shadow bolt per http://db.hellfire-tbc.com/?spell=20825

**Comment by arcwizard** [comment]
2k? i took max 700 dmg and wrote report some time ago

**Comment by Eternae1** [comment]
I took 2k shadowbolts last night and today. So something is up. Reflekz also had the same issue of 2k shadowbolts

**Comment by notsofamous** [comment]
> Bleeding Hollow Dark Shaman
200-275 dmg on a lvl 60 with 0 armor, around 2 speed
lvl 60~61
Casts Lightning Shield, 3 Charges. 50% of inflicting 120 dmg on hit
Casts Bloodlust +30% attackspeed on self, after 15-20 seconds
attempts to run away in fear! <15% hp

https://www.wowhead.com/npc=16873/bleeding-hollow-dark-shaman#comments

No sign of them having Shadow Bolt

**Comment by notsofamous** [comment]
problem is that they are all based on the same DB originally, so if there was a mistake in that one, they will all copy it
