### ISSUE TITLE
[NPC] Illidari Taskmaster / Dreghood Brute / Fleeing Dreghood Warrior

### ISSUE THREAD

**Issue by Reflekz** [SunwellWoW/Sunwell-TBC-Bugtracker#1237]
Decription: 
The Illidari Taskmaster and the Dreghood Brute have low damage.
The Fleeing Dreghood Warrior seem to have correct damage but are not "fleeing" and keep player in combat while "Mining" the player.

How it should work: 
The Illidari Taskmaster and the Dreghood Brute should hit harder.
The Fleeing Dreghood Warrior should flee away and despawn.

Source (you should point out proofs of your report, please give us some source): 
Illidari Taskmaster
http://db.hellfire-tbc.com/?npc=17058
http://db.darkwizard.pl/?npc=17058
https://db.excalibur.ws/?npc=17058
Dreghood Brute
http://db.hellfire-tbc.com/?npc=16938
http://db.darkwizard.pl/?npc=16938
https://db.excalibur.ws/?npc=16938
Fleeing Dreghood Warrior
http://db.hellfire-tbc.com/?npc=19477
http://db.darkwizard.pl/?npc=19477
https://db.excalibur.ws/?npc=19477
![wowscrnshot_110718_081055](https://user-images.githubusercontent.com/44597439/48131158-7a865b80-e265-11e8-89f2-7c5201b04616.jpg)
![wowscrnshot_110718_081123](https://user-images.githubusercontent.com/44597439/48131160-7d814c00-e265-11e8-8d8d-a36a0eea4553.jpg)
![wowscrnshot_110718_081717](https://user-images.githubusercontent.com/44597439/48131201-a1449200-e265-11e8-9990-5f243e9fa713.jpg)

**Comment by arcwizard** [comment]
I started writing this report in the morning, I was called to work, I felt that when I came back, someone would write ...
P.S. sry for offtopic.
