### ISSUE TITLE
[NPC] Dreghood Geomancer

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#1239]
Decription: 
[Dreghood Geomancer](http://db.hellfire-tbc.com/?npc=16937)

How it works: 
Dreghood Geomancer have low melee dmg, but his Fireball have high dmg. And NPC don't flee after Illidari Taskmaster dead.
![wowscrnshot_110718_113453](https://user-images.githubusercontent.com/43764742/48132476-5c881d80-e29c-11e8-9f2b-1dfcc234503f.jpg)
![wowscrnshot_110718_112547](https://user-images.githubusercontent.com/43764742/48132462-5003c500-e29c-11e8-9580-f7a5c90a5e4e.jpg)

How it should work: 
NPC must do more melee dmg, like in description. 
Fireball must do less than 147 damage. **
After Illidari Taskmaster dead, NPC must run away and desappered.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/npc=16937/dreghood-geomancer#abilities

** 147 damage value it from wowhead, but on others p. servers (http://db.hellfire-tbc.com/?npc=16937#abilities , https://db.excalibur.ws/?npc=16937#abilities) value - 34-46.

**Comment by Dootz** [comment]
"flee" part will be fixed as a part of other ticket with "Dreghood Brutes"
