### ISSUE TITLE
[Zone] Eversong Woods

### ISSUE THREAD

**Issue by Adamsek** [SunwellWoW/Sunwell-TBC-Bugtracker#124]
**Feral Tender** (GUID: 55004, Entry: 15294) not using his **Renew** spell,
http://db.hellfire-tbc.com/?npc=15294#abilities

**Tainted Arcane Wraith** (GUID: 55056, Entry: 15298) not using his **Slow** spell,
http://db.hellfire-tbc.com/?npc=15298#abilities

**Springpaw Stalker**  (GUID: 55922, Entry: 15651) is not in **Prowl** spell,
http://db.hellfire-tbc.com/?npc=15651#abilities

Missing NPC **Marniel Amberlight** Coords: 43.6, 71.2, she's Innkeeper and quest giver:
http://db.hellfire-tbc.com/?quest=9358 and quest is not present anywhere
https://www.wowhead.com/npc=15397/marniel-amberlight#starts

![wowscrnshot_081518_172944](https://user-images.githubusercontent.com/42385556/44156756-f9d667aa-a0b0-11e8-980f-a545d13cc250.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
