### ISSUE TITLE
Northshire Abbey Stair bug

### ISSUE THREAD

**Issue by wilhermil** [SunwellWoW/Sunwell-TBC-Bugtracker#1242]
Decription: there is a bug with treshold

How it works: block character for 2 sec and after that you can pass(tiny invisible wall)

How it should work: crossing treshold 
it should not be a problem

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_110718_140546](https://user-images.githubusercontent.com/44753762/48136225-65c6b980-e29f-11e8-8f97-860c4ed42d97.jpg)
![wowscrnshot_110718_140550](https://user-images.githubusercontent.com/44753762/48136234-6c553100-e29f-11e8-8ca2-68bb7bb98a09.jpg)

**Comment by akrom23** [comment]
It's clientside.
