### ISSUE TITLE
[Shaman] Elemental Mastery 

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1244]
Elemental Mastery is getting consumed by Lightning Overload procs, it shouldn't.

https://github.com/Looking4Group/L4G_Core/issues/3388

**Comment by akrom23** [comment]
@notsofamous Lightning Overload vs Lightning Bolt: should proc on cast (second LB is casted when the first one s casted) or on hit (second LB is casted when the first one hits target)?

**Comment by doomnyx** [comment]
Overload bolts should release after LB cast, not LB landing target. Same with CL procs ("instant" kinda).
Typical scenario is animation of releasing LB ends, then overload bolt is released.

Video from retail: [3:20]

https://youtu.be/CSVg3Xf6HVw?t=200

**Comment by akrom23** [comment]
Okay.
