### ISSUE TITLE
[Core] NPC attacking and using skills while stunned 

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1249]
Decription: To save myself from death I slowed down the enemy, moved few years away and intercepted it to ensure I will have 3 seconds while he was stunned to kill him safely.

I was standing right next to the NPC and while he was stunned he melee attacked me and used Cleave ability.

Similar thing happens to fleeing and feared enemies, however I will make separate reports for that if I manage to test it out.

How it works: NPCs are using abilities while stunned.

How it should work: NPCs should do nothing while stunned.

Source (you should point out proofs of your report, please give us some source): 

![wowscrnshot_110718_174548](https://user-images.githubusercontent.com/37372869/48147651-1d67c580-e2b8-11e8-9836-5c84e61cd0f0.jpg)

**Comment by Wojtyas** [comment]
Fleeing mechanic was rewritten and I can't reproduce it now seems it got fixed.
