### ISSUE TITLE
Can"t open gate with Key 

### ISSUE THREAD

**Issue by Hnidka** [SunwellWoW/Sunwell-TBC-Bugtracker#125]
Decription:  U can"t open gate from loch modan to searing gorge with key... 
                   

How it works:  U can"t open gate from loch modan to searing gorge with key... Entrance from searing gorge to loch modan working... 
Entrance GUID : 8369 , Entry : 3836

How it should work: with key u can open both gates....

Source (you should point out proofs of your report, please give us some source): 

This video showing everything from first Quest item...
https://www.youtube.com/watch?v=LBmotUOL2-g

**Comment by Dootz** [comment]
will be fixed with next server update
