### ISSUE TITLE
[Quest] What We Don't Know...

### ISSUE THREAD

**Issue by Jeansapin** [SunwellWoW/Sunwell-TBC-Bugtracker#1257]
Decription: This quest : https://www.wowhead.com/quest=9756/what-we-dont-know

How it works: You can complete it, and you're not disguised in blood elfe, and you don't have to talk to the captured sunhawk agent to do it.

How it should work: like this video shows us : https://www.youtube.com/watch?v=8WwJ6Mg9AL8 you should be disguised in blood elf, and be able to talk to the captured sunhawk agent inside his prison

Source (you should point out proofs of your report, please give us some source): 
wowhead and official account

**Comment by Jeansapin** [comment]
I have probably made a mistake, don't count this one for the moment !

**Comment by hypestar20** [comment]
You still can not get the disguise from this quest.

**Comment by amarathTESTER** [comment]
Some say you can complete it for my the Quest giver will not recognize me clicking complete quest or cancel.
