### ISSUE TITLE
[Transport] Boat Azuremyst - Darkshore

### ISSUE THREAD

**Issue by Jeansapin** [SunwellWoW/Sunwell-TBC-Bugtracker#1259]
Decription: I don't know if every boats are doing that, but you should try, it's quite weird ...

How it works: You're teleported, something is wrong ...

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by VocableWAZZAM** [comment]
Are you referring to the bug where the boat from Azuremyst to Darkshore(and vice-versa) isn't allowing you to board, due to it phasing out of existence before reaching the docks?

Sorry if it was a different issue but nonetheless, here's footage of an issue.
Source : https://streamable.com/05v4f

**Comment by nickycakes** [comment]
broken for me as well https://streamable.com/p0hqq

seems like the start point of the boat is in the wrong place or something

**Comment by Nadiirr** [comment]
https://www.youtube.com/watch?v=FWDXxRTGhII
