### ISSUE TITLE
[Spell] Energizing Spores

### ISSUE THREAD

**Issue by Reflekz** [SunwellWoW/Sunwell-TBC-Bugtracker#1262]
Decription: 
Upon killing sporebats , you should get a 5 minute buff of +30 attributes. But you don't get the buff.

I noticed it is mentioned in #288 but it states that sporewing works. but it doesn't.

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?spell=35336 (Energizing Spores)
http://db.darkwizard.pl/?spell=35336#used-by-npc (Energizing Spores)
http://db.darkwizard.pl/?npc=18129 (Greater Sporebat)
http://db.darkwizard.pl/?npc=18128 (Sporebat)
http://db.darkwizard.pl/?npc=18280 (Sporewing)
http://db.darkwizard.pl/?npc=20387 (Young Sporebat)
![wowscrnshot_110718_230209](https://user-images.githubusercontent.com/44597439/48175370-15bd1680-e2e2-11e8-8469-02e92c373374.jpg)
![wowscrnshot_110718_230916](https://user-images.githubusercontent.com/44597439/48175380-2c636d80-e2e2-11e8-9e64-8f04e3bbad9a.jpg)

**Comment by akrom23** [comment]
https://www.wowhead.com/spell=35336/energizing-spores#comments

**Comment by notsofamous** [comment]
Strange, used to work on sporewing
