### ISSUE TITLE
SSC - Raid, high oportunity to get WoW Crash after wipe/entry ect.

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#1273]
Decription: 
Yesterday we tryed to do some SSC with Time Walkers members. Game was crashy as hell during the run. Mostly when you try release spirits (after wipe) or just entry/leave the raid instance. Its hard to say whats specyficly was the reson... but in whole raid group a LOT of ppl had same problem, and its showd up so ofen... so We decide to sign it in as a "Bug".

How it works: 
like in decription.

How it should work: 
I know its easy to say but... Client shoudnt crash atal. :)

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Feel free to repopen when happens again.
