### ISSUE TITLE
[warrior] [talent] sword specialization

### ISSUE THREAD

**Issue by sowan** [SunwellWoW/Sunwell-TBC-Bugtracker#1276]
Decription:  Sword specialization is not working properly on warrior, gets triggered by non-sword attacks and does damage based on yellow attacks instead of white.

How it works: 
It is getting triggered by attacks as deep wounds and doing the damage of the yellow attack instead of the white damage of the weapon.

How it should work: 
It should get triggered by sword attacks (no matter if white or yellow), but sword attacks doing sword base damage.

Source (you should point out proofs of your report, please give us some source): 

[IMG]https://cdn.discordapp.com/attachments/227132954453737482/510155301710987274/unknown.png[/IMG]

http://db.hellfire-tbc.com/?spell=13964

**Comment by akrom23** [comment]
https://imgur.com/a/Ueo7R3S
