### ISSUE TITLE
[spell] double mongoose procs. When you right click one the other dissapeas

### ISSUE THREAD

**Issue by sicknot1** [SunwellWoW/Sunwell-TBC-Bugtracker#1277]
Decription: 
Mongoose enchant procs as fury war, test on dummy, when two procs i right click makes dissapear one

How it works: 
I hit dummies until i have two procs, right click one regardless of the time difference of two (be same time or with a seconds different of each proc) and the other dissapears

How it should work: 
They should be independant (tail of a bigger issue?)

Source (you should point out proofs of your report, please give us some source): 
Tested on my warrior on dummies. 

FURTHER TESTS: we have to try with 2 same enchants that aren't mongoose. then we also have to try with one mongoose and another enchant.
Potential issue: While one wouldn't right click a beneficial buff on PvE, dispelling a buff that procced twice from a different source could mean the other will be dispelled too.

**Comment by Wojtyas** [comment]
Double proc of Mongoose fixed recently.
