### ISSUE TITLE
Talent points issue

### ISSUE THREAD

**Issue by dogshep** [SunwellWoW/Sunwell-TBC-Bugtracker#1279]
Decription: When quickly applying talent points it's possible to use two points for one application.

How it works: Quickly applying points can use two points for one talent point application

How it should work: One for one

Source (you should point out proofs of your report, please give us some source): I have not been able to reproduce but Cola#4761 also had the issue today so wanted to report it

**Comment by sicknot1** [comment]
#1278 

Could it be related to the information from client to server regarding clicks?. The artificial delay could need a touch.

**Comment by akrom23** [comment]
I think it was a common bug on Blizzard servers?

**Comment by Wojtyas** [comment]
@sicknot1 @dogshep still happening to you? dunno if i click to slow or it's not working anymore ;d

**Comment by dogshep** [comment]
I haven't been able to reproduce. I would say safe to close. Can create a new issue if needed. Thanks all!
