### ISSUE TITLE
Melee range in pvp

### ISSUE THREAD

**Issue by nurger** [SunwellWoW/Sunwell-TBC-Bugtracker#1283]
Decription: 
wrong melee range

How it works: 
i can hit another player from 2-3 yard as melee

How it should work: 
much closer

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_111018_002826](https://user-images.githubusercontent.com/44910114/48289306-04aa0c00-e480-11e8-9c14-1ab3fc56af4b.jpg)
![wowscrnshot_111018_002830](https://user-images.githubusercontent.com/44910114/48289309-083d9300-e480-11e8-80c2-6635787f8d03.jpg)

**Comment by akrom23** [comment]
Really, I don't see here any bug. Need some proofs from retail servers.

**Comment by akrom23** [comment]
No response.
