### ISSUE TITLE
Necklace missing

### ISSUE THREAD

**Issue by Sparkaj** [SunwellWoW/Sunwell-TBC-Bugtracker#1284]
Decription: I logged into the SSC test realm after building a character and using it.  It had full gear, now the neck is missing.

How it works: Log in, and [Worgen Claw Necklace] was missing from character and inventory.

How it should work: After logging out properly, gear should be saved.

Source (you should point out proofs of your report, please give us some source): Source?  It was on SSC test Nov.9.18, also you spelled Description wrong, above me on this form.

**Comment by akrom23** [comment]
It was caused by recent crashes. Should be okay.
