### ISSUE TITLE
[NPC] Water Elemental

### ISSUE THREAD

**Issue by ahlens** [SunwellWoW/Sunwell-TBC-Bugtracker#1285]
Decription: 
Mage's [Water Elemental](http://db.hellfire-tbc.com/?spell=31687) can't be attacked during duel.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Cannot reproduce it.

**Comment by Wojtyas** [comment]
Water Elemental's AI was rewritten by Akrom. It's probably fixed but feel free to reopen if needed.

**Comment by ahlens** [comment]
123
