### ISSUE TITLE
Quest: Freedom for All Creatures

### ISSUE THREAD

**Issue by Sabre142** [SunwellWoW/Sunwell-TBC-Bugtracker#1287]
Description: 
Freedom for All Creatures (https://db.excalibur.ws/?quest=2969) is not completable

How it works: 
Nothing happens when you open the bamboo gate.

How it should work: 
Kindal should follow the player
The sprites should leave the cage once the door is opened

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/cbyKV88LfEg?t=113

**Comment by Azmodeane** [comment]
This is not fixed. I have done the quest 4 times now after abandoning and it will not give credit for the Sprites leaving the bamboo cage. Will I have to submit a new ticket to get this looked at?
