### ISSUE TITLE
[Spell] Electrical Charge (37658)

### ISSUE THREAD

**Issue by TP-Caitlin** [SunwellWoW/Sunwell-TBC-Bugtracker#1288]
Decription: 
Electrical Charges persist even when the The Lightning Capacitor (28785) is unequipped.

How it works: 
Once you swap a trinket, if you currently have one or two "Electrical Charges" stacked on you, when you equip a new trinket the buff charge still persists.

How it should work: 
When you un-equip the item the charges should be dispelled from you, and the count reset to 0.

Source (you should point out proofs of your report, please give us some source): 
https://i.imgur.com/xq7Yx92.jpg
https://i.imgur.com/80QARAC.jpg

**Comment by TheMoneyHater** [comment]
INCORRECT!
https://i.imgur.com/dUNb9DU.png
Also know that the Electrical Charge buff persists through log-out(don't think it does through death though). But it's nice to log on and still see the charges still there. And the charges still stay on you if you switch trinkets around. Or deequip it.

**Comment by TP-Caitlin** [comment]
Ah my bad then, didn't notice that. (lol at caps)
