### ISSUE TITLE
[Quest] Miner's Fortune (q 896)

### ISSUE THREAD

**Issue by forafriend** [SunwellWoW/Sunwell-TBC-Bugtracker#129]
Description: The droprate for [Cat's Eye Emerald] (i 5097) needed for the quest is too high.

How it works: Current droprate for the item seems to be at 100%

How it should work: Droprate should be significantly lower. This one was a pain on retail.

Proofs: 
* https://web.archive.org/web/20081004095628/http://thottbot.com:80/i5097
	- Droprate of item below 3%
	- Clicking back in the archive to https://web.archive.org/web/20080313180235/http://thottbot.com:80/i5097 loads comments, and looks like the droprate was even lower
	
* https://www.wowhead.com/item=5097/cats-eye-emerald#comments
	- Patch 2.1 `This site says the droprate on this item is about 3%....Then again, I just killed somewhere between 40-50..`
	- Patch 2.1.3 `Took me around 10 kills to loot it.`
	- Patch 2.1.3 `Took a while for it to drop for me, had to kill about 20-30.`
	Various other comments, some getting lucky, etc.
	
I'd suggest a drop rate nerf somewhere in the range of 3-10%.

**Comment by Dootz** [comment]
will be fixed with next server update
