### ISSUE TITLE
while stealth and detected i'm loosing aggro way to fast

### ISSUE THREAD

**Issue by marco321** [SunwellWoW/Sunwell-TBC-Bugtracker#1291]
Decription: loosing aggro we to fast when i mob see me while i'm stealth

How it works: i'm stealth and when a mob see me... he start cast but when i moving to loose aggro.. after 3-4 steps i loose it. 

How it should work: i'm not supposed to loose aggro when a mob see me while stealth

Source (you should point out proofs of your report, please give us some source): 
![nightbane bug](https://user-images.githubusercontent.com/44928070/48304092-62bb0b80-e4e1-11e8-96ca-68ca7a814c3d.png)

**Comment by Atrecom** [comment]
if i`m not mistaken when u step close to agressive mob there is a chance they detect you. especially when they are lvl higher.
nope?

**Comment by akrom23** [comment]
But I guess you are not in combat till the mob cast spell on you?

**Comment by akrom23** [comment]
So when the mob sees, you should drop stealth or wait till the spell hit you?
