### ISSUE TITLE
[Mage][Talent] Arcane Concentration

### ISSUE THREAD

**Issue by Kentamentiu** [SunwellWoW/Sunwell-TBC-Bugtracker#1293]
Decription: 
Gives you a 10% (5/5 rank) of entering a Clearcasting state after any damage spell hits a target

How it works: 
On the SSC test realm Clearcasting does not proc at all on the test dummy. 14min of non stop casting did not yield a single proc. Tested with multiple spells.

How it should work: 
10% chance to proc on every spell that lands.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/ieaoFpC

**Comment by akrom23** [comment]
#572
