### ISSUE TITLE
[Mage][Spell:30451]Arcane Blast

### ISSUE THREAD

**Issue by Kentamentiu** [SunwellWoW/Sunwell-TBC-Bugtracker#1294]
Decription: 
When casting Arcane Blast, player gets a debuff that increases manacost and reduces cast time of Arcane Blast, for 8 seconds.

How it works: 
When starting the cast of Arcane Blast with three stacks of the debuff to increase the casting speed and cost, but finishing the cast after the debuff has worn out, does not use the unstacked manacost for the cast like it is supposed to. The manacost remains the same like when you start casting the spell, instead of being calculated when the cast finishes. This severely cripples the Arcane mage spec, by making the mana regen rotation impossible.

How it should work: 
Castspeed is calculated when cast starts, manacost is calculated when spell finishes casting, this is how it is supposed to work.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/index.php?title=Cast_time&diff=1432620&oldid=850144
https://web.archive.org/web/20080304065127/http://elitistjerks.com:80/f31/t18441-mage_sweet_informational_thread/
https://web.archive.org/web/20080926040517/http://elitistjerks.com:80/f31/t25772-mage_raiding_arcane_mage_post_2_4_a/
https://archive.codeplex.com/?p=rawr

**Comment by akrom23** [comment]
Nope. everything works fine. Need some screenshots.

**Comment by akrom23** [comment]
Mana cost must be calculated on cast I think - you cannot start casting if you have no enough mana.

**Comment by Kentamentiu** [comment]
If you can tell me how to screenshot something like that, I will.
You can indeed not start a cast without enough mana. The amount of mana taken away however is deducted upon completing the cast, it was quite clearly recalculated on retail.
The whole of 2.0 up to 2.3 default arcane rotation was testament to that.
