### ISSUE TITLE
[Mage][Spell:27070] Fireball

### ISSUE THREAD

**Issue by Kentamentiu** [SunwellWoW/Sunwell-TBC-Bugtracker#1295]
Decription: 
Fireball hits for direct damage and applies a dot that ticks 4 times over 8 seconds, for a total of 84 Fire damage.

How it works: 
Fireball dot hits 1 tick for 21 then drops off from the target as tested on Combat Dummy! on the SSC ptr.

How it should work: 
8seconds of dot, 4 ticks. 4x 21 damage.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/DXgWCe8

**Comment by Kentamentiu** [comment]
After more testing it became apparent that sometimes it stays on for 2 ticks, sometimes for 3, sometimes not at all. The dot should always run it's full duration.

**Comment by Atrecom** [comment]
> After more testing it became apparent that sometimes it stays on for 2 ticks, sometimes for 3, sometimes not at all. The dot should always run it's full duration.

Man, did u notice dummy cant be debuffed for a long period of time? Test it on players or mobs pla, then be sured it works fine.

**Comment by notsofamous** [comment]
Yea test it in a duel, probably just on target dummies

**Comment by Kentamentiu** [comment]
What's the point of having testing dummies if you're not supposed to use them for testing?

**Comment by akrom23** [comment]
Works fine on mobs and players.
