### ISSUE TITLE
[NPC] Stormwind City Patroller 

### ISSUE THREAD

**Issue by F4play** [SunwellWoW/Sunwell-TBC-Bugtracker#13]
Decription: Doesn't stop when talking to it

NPC ID: 1976

How it works: Doesn't stop when opening the dialog window to ask for directions

How it should work: Should stop when dialog window is opened by a player

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
general error, related to more cases

**Comment by akrom23** [comment]
#16.
