### ISSUE TITLE
Priest/Spell : Mind Control works badly

### ISSUE THREAD

**Issue by Hnidka** [SunwellWoW/Sunwell-TBC-Bugtracker#130]
Decription:  MC target cant use spells (if it have some like casters...)

How it works:  MC target can only autoattack

How it should work: u should be able to use spells
                                 there is plenty information how it should work i post some links...
                          

Source (you should point out proofs of your report, please give us some source): 

http://wowwiki.wikia.com/wiki/Mind_Control 

http://wowwiki.wikia.com/wiki/List_of_mind_controllable_mobs   -- this is list of controllable mobs in dungeons + which spell u are able to use...

**Comment by zapsuu** [comment]
I could use every spell on any controlled mob. Could you show which mob correctly has a problem?

**Comment by Wojtyas** [comment]
It's old report and probably solved time ago. I guess @lukaasm or @akrom23 will close it soon.

**Comment by Wojtyas** [comment]
Fixed & implemented ages ago.
