### ISSUE TITLE
[Core] NPC reset/evade

### ISSUE THREAD

**Issue by Squarz** [SunwellWoW/Sunwell-TBC-Bugtracker#1301]
Description: 
Once an NPC starts resetting it should not be be possible to re-engage it until it has fully reset.

How it works: 
NPCs will re-engage if you move to close to them during the reset:
https://streamable.com/osi2t

How it should work: 
Once an NPC starts resetting it should not be be possible to re-engage it until it has fully reset.

**Comment by Kokaina** [comment]
https://gyazo.com/0f9ff8674ce70d9861ee401d76749387

**Comment by nickycakes** [comment]
not resolved for me on beta server, shooting mobs while they're in the process leashing bugs them/me until i relog still

**Comment by Kokaina** [comment]
@nickycakes Its implemented on SSC realm so far, fix will be present on open world realm soon ;)

**Comment by Wojtyas** [comment]
Fixed & implemented.
