### ISSUE TITLE
[Quest] Boiling Blood

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1306]
Decription: 
Throwing the Bleeding Hollow Blood into the Cursed Cauldron will not spawn any skeletons to fight

How it works: 
Throwing the Bleeding Hollow Blood into the Cursed Cauldron will not spawn any skeletons to fight
https://streamable.com/6gb3a
How it should work: 
Should spawn a bunch of little scarabs to fight, they're on a respawn timer and have a chance to spawn as a trap when you click the cursed cauldron

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/6gb3a

**Comment by fakelort** [comment]
Addendum to that: Currently red crystals spawn around the cauldron, sometimes on top of you such that you get stuck.

**Comment by Wojtyas** [comment]
Scarabs should spawn instead of crystals.
https://i.gyazo.com/bcf647d33a752e57e3a8bd64235bac16.png
