### ISSUE TITLE
Warlock Healthstones Stack

### ISSUE THREAD

**Issue by Euphemistic** [SunwellWoW/Sunwell-TBC-Bugtracker#1307]
Decription: Able to take several Healthstones from a warlock Soulwell

How it works: Has unique tag but still able to carry as many as you want, but still invokes a cooldown when used.

How it should work: Only able to carry 1 of each rank of healthstone.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/Lt8U1WD

**Comment by notsofamous** [comment]
Seems like it's the Unique tag that's actually broken, not the healthstone.

Can equip 2 of this unique item, shouldn't even be able to have 2 in my bags.
![Image](https://i.gyazo.com/46fa40a6b504b4a2b437415ba129468e.png)

Related unique(-equip) item bug: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1292
