### ISSUE TITLE
[NPC] Bleeding Hollow Tormentor

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1309]
Decription: 
Bleeding Hollow Tormentor casts fear on his own pet, on targets he's not even targeting, and when he fears a player it comes up as a buff that you can right click off

How it works: 
Bleeding Hollow Tormentor casts fear on his own pet, on targets he's not even targeting, and when he fears a player it comes up as a buff that you can right click off
https://streamable.com/0dotf
How it should work: 
Should fear the target he is targeting, should not fear his own pet, when the mob dismounts you can leash the master and the mount will stay attacking you and he will summon a new mount as he resets

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/0dotf

**Comment by Sabre142** [comment]
I still experience this bug where I can right-click off the fear buff.
