### ISSUE TITLE
[Hunter] Melee Attack Animation

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1312]
Decription: 
When auto shooting a mob, a hunter will go back to his melee in combat animation in between the cast time of auto shot

How it works: 
https://streamable.com/nd8tt
When auto shooting a mob, a hunter will go back to his melee in combat animation in between the cast time of auto shot
How it should work: 
https://gyazo.com/2693a88143381daf7f48652a6bb7b726
this is a point of view from the hunter's perspective, and seems normal to him. but from someone else's perspective its as if he's out of range in combat melee
Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/nd8tt

**Comment by akrom23** [comment]
@badmannerkid I need the names/ids of these items.

**Comment by akrom23** [comment]
No response. Closed.
