### ISSUE TITLE
[Paladin] [Spell] Divine Shield

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1313]
Decription: 
When you cast Divine Shield while you and others are in combat with a mob, the mob will stay on you even though you're bubbled. It will not run to the 2nd eligible target on the threat table. It will just continue attacking the paladin in the bubble

How it works: 
When you cast Divine Shield while you and others are in combat with a mob, the mob will stay on you even though you're bubbled. It will not run to the 2nd eligible target on the threat table. It will just continue attacking the paladin in the bubble
https://streamable.com/x3plc
How it should work: 
If you cast Divine Shield it should make you ineligible to be their main agro target on the threat table. The mob should start hitting the 2nd highest threat target that is eligible on the threat table

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/x3plc
https://wow.gamepedia.com/Divine_Shield

**Comment by Atrecom** [comment]
Rly? Didn't mention it for ages.
