### ISSUE TITLE
[Hunter] [Pet]s attack mobs from the front automatically

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1314]
Decription: 
Hunter Pets default to attacking the target from the front

How it works: 
When you send your pet in, the pet will immediately start attacking straight ahead of the hunter, usually in front of the mob's hit box instead of the back. This results in the hunter having to circle around any mob
https://streamable.com/o5j0c
https://streamable.com/52tdc

How it should work: 
If the pet is not the primary target on the threat table, the pet should prefer to hit a mob from the back of its hitbox to avoid parry haste on the target. If all hunter pets prefer to attack from the front instead of the back it will make bosses and other mobs parry more. It should resposition to the back of the mob if its not the primary target on the threat table

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/o5j0c
https://streamable.com/52tdc

**Comment by badmannerkid** [comment]
https://streamable.com/h072u

**Comment by lukaasm** [comment]
No, I am not satisfied with movement yet, they will be slowly tweaked till release and after.
For now doing raw "feature" complete implementation.

Closing :)
