### ISSUE TITLE
[Hunter] [Spell] Tame Beast

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1319]
Decription: 
When taming a pet, the cast bar disappears but the debuff remains on the target

How it works: 
https://streamable.com/k11b8
When the cast bar disappears, the debuff remains on the target and once the debuff expires on the target the beast is tamed.

How it should work: 
Cast bar should complete and line up with the tame beast debuff on the target, and you should finish taming the best at the same time the debuff expires and the cast ends.

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/k11b8
https://wow.gamepedia.com/Tame_Beast

**Comment by Wojtyas** [comment]
Fixed & implemented.
