### ISSUE TITLE
[NPC] Venture Co Enforcer (npc 3283), Venture Co Overseer (npc 3286)

### ISSUE THREAD

**Issue by forafriend** [SunwellWoW/Sunwell-TBC-Bugtracker#132]
Description: Venture Co Enforcer (npc 3283) and Venture Co Overseer (npc 3286) are not using their abilities.

How it works: Mobs in question just melee you.

How it should work: Mobs should use their abilities. 
- Venture Co Enforcer (npc 3283) has a battle shout and a disarm.
- Venture Co Overseer (npc 3286) uses a poison.

Proofs: 
http://db.hellfire-tbc.com/?npc=3283#abilities
http://db.hellfire-tbc.com/?npc=3286#abilities

**Comment by Dootz** [comment]
will be fixed with next server update
