### ISSUE TITLE
[Quest] [Hunter] Taming The Beast

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1320]
Decription: 
Hunter --
Hunter quest "Taming the Beast". (VIDEO) 
- Taming Rod starts casting on beast and randomly ends early, if you move it just instantly tames the mob you wanted. 
After taming you cannot abandon the pet via right click pet or target frame. You need to use /script PetAbandon().

NOTE: This seems to be the same issue with casting Tame Pet. 
Cast can randomly end early or if you get hit it's possibly taking spell knockback into effect meaning cast ends early even though you're still technically taming it as seen by the debuff on the beast.
https://streamable.com/239z7

How it works: 
Hunter --
Hunter quest "Taming the Beast". (VIDEO) 
- Taming Rod starts casting on beast and randomly ends early, if you move it just instantly tames the mob you wanted. 
After taming you cannot abandon the pet via right click pet or target frame. You need to use /script PetAbandon().

NOTE: This seems to be the same issue with casting Tame Pet. 
Cast can randomly end early or if you get hit it's possibly taking spell knockback into effect meaning cast ends early even though you're still technically taming it as seen by the debuff on the beast.
https://streamable.com/239z7

How it should work: 
The cast bar should not vanish when using a taming rod and the cast bar should not end early from player movement. 

This could be related to #6, but this was closed a while ago.

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/239z7
#6

**Comment by Wojtyas** [comment]
Fixed & implemented.
