### ISSUE TITLE
[NPC] Fel Reaver Attacking Towns/Neutral NPCs unprovoked

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1322]
Decription: 
Fel Reaver will engage with Neutral NPCs and invade Towns unprovoked

How it works: 
Fel reaver will pat too close to a Neutral NPC or a town and automatically engage the NPC whether its a town guard or a questgiver under a hut. 

How it should work: 
Fel Reaver shouldn't attack NPCs or Town Guards in towns unless kited into the town by an actual player or attacked first by the NPCs/Town Guards themselves. NPCS/Town Guards shouldn't attack the Fel Reaver unless a player kites the Fel Reaver into the town and his abilities hit the guards

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/chqyc
https://streamable.com/vohjp

**Comment by notsofamous** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/930

I think he might just have the wrong path, but he should fight NPCs if someone were to kite him close enough.

https://www.wowhead.com/npc=18733/fel-reaver#comments

**Comment by badmannerkid** [comment]
makes sense yeah i think he has the wrong path as well. but he was engaging with the town guards without being kited into the town by a player. aggro radius also might be a bit too large if he's able to engage town guards. 

only NPC i've really only seen him usually engage with is Magister Aledis who patrols inside the Fel Reaver's patrol path
