### ISSUE TITLE
[NPC] Fel Reaver Stopping abruptly in his path

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1323]
Decription: 
Fel Reaver will randomly stop in his pathing and stand there not doing anything

How it works: 
Fel Reaver will randomly stop in his pathing and stand there not doing anything

How it should work: 
Fel Reaver should smoothly walk along his path only engaging those that enter his aggro radius or those that enter combat with him

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/73ace18a340ad68a4e47e17600080c5c

**Comment by notsofamous** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1223
