### ISSUE TITLE
[Event] [Zangarmarsh] Twin Spire Graveyard

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1328]
Decription: 
The event itself works, but the faction who lost the battle for the Twin Spire Graveyard stays upright even though the other faction controls it.

How it works: 
Horde capped the event, gained the Twin Spire Blessing for zone wide Zangarmarsh buff. The alliance banner visual stayed on the Twin Spire Banner post, and the Horde banner is simply overlapping it

How it should work: 
Should replace with the victor's banner and have no trace of the loser's banner

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/k62hb

**Comment by akrom23** [comment]
#288.
