### ISSUE TITLE
[Barrens] Willix

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#133]
Willix (id 2, guid 1259) should be present just before Razorfen Kraul entrance for those people who escorted him in RFK dungeon. If they have [Willix the Importer - 1144] quest completed then he should stay there. Maybe change his phase to show him only for those certain players.

For now he's present there entire time.

![image](https://user-images.githubusercontent.com/22802214/44171348-4a9e4080-a0da-11e8-9365-ea48b5f87586.png)

**Comment by Adrestiah** [comment]
[Willix the Importer] is Now not showing up for players- and upon completion of the quest he vanishes.
