### ISSUE TITLE
[NPC] [Zone] Nagrand Murkblood Invaders

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1332]
Decription: 
Murkblood Invaders stop to analyze the situation at the Consortium hub in Nagrand, then proceed to patrol into the camp and engage the consortium, killing some questgivers and engaging the gemcrafter.

How it works: 
Murkblood Invaders stop to analyze the situation at the Consortium hub in Nagrand, then proceed to patrol into the camp and engage the consortium, killing some questgivers and engaging the gemcrafter without ever leaving the safety of their mounts

How it should work: 
Murkblood Invaders should not patrol close enough to the camp to engage neutral mobs to them

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/ygxxo

**Comment by akrom23** [comment]
#300.
