### ISSUE TITLE
[NPC] [Movement] Blackscale 

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1333]
Decription: 
Blackscale never lands, just bounces up and down indefinitely in the air trying to gain elevation

How it works: 
Unable to attack the hostile target as he's only attackable when he lands. With his current pathing he bounces around and never lands.
https://streamable.com/v2bqu
How it should work: 
He should fly around in the air and only occasionally come down to kill Dire Ravens. When he lands is really the only time you should be able to engage him.

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/v2bqu
https://wow.gamepedia.com/Blackscale

**Comment by akrom23** [comment]
#58.
