### ISSUE TITLE
[Druid] Relogging 

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1336]
Relogging while already in bear (and probably moonkin form) form will make the armor bonus of the form be applied twice for a total of *16 of your normal armor. And dodge chance went down by 4% (Feral Swiftness talent not applied?)

Bugged stats:
![Image](https://i.gyazo.com/31a7969334ff1b69126b93b641b927ea.png)

Actual stats:
![Image](https://i.gyazo.com/625abe9b29d22ce0835558df7900c733.png)

**Comment by akrom23** [comment]
Cannot reproduce it. @notsofamous Still happens?

**Comment by notsofamous** [comment]
Seems to work now!
