### ISSUE TITLE
Living Root of the Wildheart

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#1339]
Decription: 
This is special druid trinket from SSC.

How it works: 
Trinket completly doesn't work in any form. No proc

How it should work: 
In each form any attack/spell can proc 1 buff for 15 seconds. no icd

"this, on the other hand, has been confirmed to have no hidden cooldown at all.... it can even proc before the effect has worn off and therefore renew the duration."
"This trinket procs much much more [than Hourglass of the Unraveler] often (it really procs like mad in cat form)"

Buffs:
"Catform: 64 strength Bearform: 4070 armor Moonkin: 209 dmg Treeform: 326 healing Caster: 175 dmg/healing"

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=30664/living-root-of-the-wildheart#comments

**Comment by Therealvaxe** [comment]
Still doesn't work.

**Comment by moiragny** [comment]
Still not working as it should...please fix this asap!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
