### ISSUE TITLE
Pet not attacking Alliance NPCs when commanded to

### ISSUE THREAD

**Issue by Sabre142** [SunwellWoW/Sunwell-TBC-Bugtracker#1341]
Description: 
Pet isn't attacking Kul Tiras NPCs in Durotar when pressing the 'Attack' button (works fine on non alliance NPCs).

How it works: 
The pet and NPC just keep making noises but don't fight.

How it should work: 
The pet should start attacking the NPC.

Video of bug demonstrated: https://www.youtube.com/watch?v=zoiZyCnj3ZI

**Comment by Sabre142** [comment]
This is also happening to all NPCs sometimes, the pet just won't attack when commanded

**Comment by akrom23** [comment]
Cannot reproduce it. Still valid @Sabre142 ?

**Comment by Sabre142** [comment]
The issue appears to be fixed now @akrom23 

Therefore I'm going to close it.
