### ISSUE TITLE
[Quest] Treant Muisek

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1345]
Decription: Quest is completable, however the quest item does not always work properly.

The same problem happens with other quests:

Testing the Vessel
Hippogryph Muisek
Faerie Dragon Muisek
Treant Muisek
Mountain Giant Muisek

How it works: After killing appropriate NPC and using quest item only 50% of uses grant credit. Sometimes there's an error "Out of range" or "Can't use it yet".

How it should work: After killing appropriate NPC and using quest item on the body you should get the credit 100% of time. I've killed 5 NPCs, used the item 5 times and have 1/3 completion.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_111118_171748](https://user-images.githubusercontent.com/37372869/48315376-c9b9ec80-e5d5-11e8-94a3-6d83ed62d37a.jpg)
![wowscrnshot_111118_171750](https://user-images.githubusercontent.com/37372869/48315377-cc1c4680-e5d5-11e8-8e78-7fef395dbab2.jpg)

**Comment by neheri** [comment]
Update:

Quest cannot be completed. I've killed like 20 treants and same thing happens over and over. Body disappears but there's no credit given for the q, you can't go past 1/3. This locks you from 2 quests available in the chain.

**Comment by Dootz** [comment]
Works fine locally on latest update. I'll re-check on beta once it's updated.

**Comment by neheri** [comment]
Have you checked Treant Museik quest? It's 3rd or 4th in a chain as far as I remember. Previous parts were completable, however one with treants took me 20 kills and I was able to get only 1 credit. It should be 3 kills/3 credits.
