### ISSUE TITLE
Wrong pvp rewards from vendors

### ISSUE THREAD

**Issue by fakesunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#1347]
Decription: 
As title say. Should be s1 rewards

How it works: 
https://clips.twitch.tv/LongAmazingPlumageBleedPurple

How it should work: 
The rewards for s1. has to be general pvp off piece epics.
And there should be blue level 70 pvp gear from badges+honor ( level 70 high warlord and GM gear )

Source (you should point out proofs of your report, please give us some source): 
Played back in tbc on retail. All servers that try to recreate a tbc progressive server have this gear at the vendors duing s1 and 2.

**Comment by fakesunwell** [comment]
not fixed

**Comment by MrTide** [comment]
Hello can you put the name of the items here our developers will check it out.. couple of them should be enough ... (also not sure if quartermaster pvp items got removed due content difference)

**Comment by fakesunwell** [comment]
hello @MrTide 
Blue PvP items was avaible duing season 1 and 2. It was an upgraded version of the old level 60 grand marshal gear. Had the same look.
All items did cost honor and marks.
This blue gear was removed in season 3. These items was replace with season 1 gladiator items.

**Example of the 70 gear**
https://www.wowhead.com/item-set=590/grand-marshals-battlegear

**Comment by feelmy1taps** [comment]
Hey this pvp blue set from reputation should be available aswell?

https://www.wowhead.com/item=35361/kodohide-gloves#sold-by

**Comment by fakesunwell** [comment]
nope

**Comment by fakesunwell** [comment]
was in s3
