### ISSUE TITLE
"Mark V is alive!" quest does not work at all

### ISSUE THREAD

**Issue by Young991** [SunwellWoW/Sunwell-TBC-Bugtracker#135]
Decription: The pathing is just horrible.

How it works: As soon as you start the quest he just shoots right and under the ground.

How it should work: He walks around the town and back.

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC/commit/094ba516a1779c32808abd8553e84400f888f098
