### ISSUE TITLE
[Dungeon] Fear not pulling packs

### ISSUE THREAD

**Issue by ninc** [SunwellWoW/Sunwell-TBC-Bugtracker#1354]
Decription: 
Fear mobs straight into multiple packs without pulling the extra packs.

How it works: 
Fear a mob, it runs into additional mobs. When the fear breaks only the feared mob is aggroed and returns to the caster.

How it should work: 
Fear a mob into additional mobs should pull the additional mobs.

Source (you should point out proofs of your report, please give us some source): 
Played Heroic dungeons 2018-11-11.

**Comment by Wojtyas** [comment]
Moved to https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/656
