### ISSUE TITLE
Huge Combat Bug In PvP (arena)

### ISSUE THREAD

**Issue by Euphemistic** [SunwellWoW/Sunwell-TBC-Bugtracker#1356]
Decription: Basically a lot of abilities that should not be able to be used in combat can be used. Rogues can re-stealth off CD in combat, warriors can charge, rogues can also sap targets that are in combat, meaning they can stealth right next to a target and sap instantly if they want to while in combat the entire time, you can eat food while in combat etc.

How it works: I've mainly tested it in arena, but I've found that outside of the arena while dueling you can't charge while in combat, which is how it should be. I've also charged a target and got sapped as i was charging and my character got completely stuck and I couldn't move for the rest of the arena until I was dead.

How it should work: No charge in combat, no sapping targets that are in combat, shouldn't be able to use any ability that doesn't work in combat, stealth, food, etc.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/0mpY3ap

**Comment by akrom23** [comment]
Need more screenshots.

**Comment by badmannerkid** [comment]
you guys should be recording and uploading videos if you want these bugs to be understood

**Comment by neheri** [comment]
Not sure how it works in arenas, however outside arenas it appears to be working 100% fine. I am playing warrior and charge can only be used in combat. Also combat is removed after killing mob, bandaging does not trigger combat, etc.

**Comment by teaNcrumpets** [comment]
https://streamable.com/rm75l   here is a video of the bug  - notice how i spam cheapshot (audio) every 6sec, and keep an eye on the large stealth icon above normal actionbars

**Comment by notsofamous** [comment]
Same as https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1346 ?

**Comment by notsofamous** [comment]
Also same issue https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1297

**Comment by Jeansapin** [comment]
Same issue, it's always happening to me, as a rogue, in arena.

**Comment by Jeansapin** [comment]
I don't know, but it was exactly the same on the Kara/Dungeons testing server. It's happening in arena so it's quite easy to reproduce.
