### ISSUE TITLE
Coilfang Pipe (Water Breathing)

### ISSUE THREAD

**Issue by Tyton89** [SunwellWoW/Sunwell-TBC-Bugtracker#1357]
Decription: Coilfang Reservoir entrance should restore breath towards the middle of the pipe entrance

How it works: There is no breath restore when swimming inside the pipe towards the Coilfang entrance

How it should work: The water breathing should restore breath to full near or around the middle of the path when swimming towards the underground area.

Source (you should point out proofs of your report, please give us some source): Testing this on the test server swimming through the pipe multiple times.

**Comment by akrom23** [comment]
As I remember, Blizz changed that on Wotlk. Are sure about it on TBC?

**Comment by Tyton89** [comment]
It wasn't in the initial TBC release, but was added around the BT patch. I assume the server is running 2.4.3? or is it being completely faithful to patch changes?
