### ISSUE TITLE
Dr. Boom bots going the wrong way

### ISSUE THREAD

**Issue by Young991** [SunwellWoW/Sunwell-TBC-Bugtracker#136]
Decription:  The boom bots dr boom summons do not work.

How it works: The boom bots phase through the rocks and start flying off

How it should work: The boom bots follow a path inside the rocks.

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
fixed 
https://github.com/SunwellWoW/Sunwell-TBC/commit/094ba516a1779c32808abd8553e84400f888f098
