### ISSUE TITLE
[Hunter] Freezing Trap

### ISSUE THREAD

**Issue by honkies** [SunwellWoW/Sunwell-TBC-Bugtracker#1361]
Context: 
Enemy player was stuck and could not move after Freezing Trap cancelled by damage.

How it works: 
Place a frost trap that freezes the first enemy that approaches, preventing all action for up to 5sec. _Any damage caused will break the ice._ 

Source (Duel Video): 

I was spamming heaps because I never play hunter, so probably another spell just bugged it out.

https://www.youtube.com/watch?v=E_JQ5gX6Mqo&feature=youtu.be

-noblelight

**Comment by akrom23** [comment]
What did the priest use to remove the trap effect?

**Comment by Dewsch** [comment]
Yeah I've been stuck in place in this AV game for almost 6 minutes.  I can mount, sit, bandage, etc.  I just cannot move at all.  I was trapped by a hunter, and a warlock cast devour on me to remove the trap.

It has happened to me 3 times, all of them were when I charged the hunter (I'm a warrior), was instantly trapped, and the trap was broken shortly after.  I can't move until I relog.

**Comment by akrom23** [comment]
@Dewsch Next time, give me some screenshots with your combat log, where I can see applied root/stun effects and all the stuff that happened after that.
