### ISSUE TITLE
Shaman: Elemental Mastery (2)

### ISSUE THREAD

**Issue by nennx** [SunwellWoW/Sunwell-TBC-Bugtracker#1362]
Decription: Elemental mastery is being consumed by spell in progress and it is not causing a crit

How it works: If you are casting spells then pop elemental mastery while one is in mid-air, the mid-air spell is not gauranteed to crit and the buff will be consumed.

How it should work: Elemental mastery should cause your next casted spell to crit

Source (you should point out proofs of your report, please give us some source):

**Comment by nennx** [comment]
this only occurred on the ssc test server *

**Comment by Avishai97** [comment]
This happened today on Nightbane Open World server aswell.
https://www.twitch.tv/videos/338589629

**Comment by Avishai97** [comment]
This happened today on the Nightbane Open World server aswell.
https://www.twitch.tv/videos/338594082

**Comment by NickBrah** [comment]
This is still not fixed btw.
