### ISSUE TITLE
[Movement] [Core] Elevation

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1363]
Decription: 
After dueling and being feared, a player can gain elevation by zoning into a dungeon and jumping

How it works: 
Player duels, is feared in the duel, jumps while feared and ends the fear at a higher elevation. Can also replicate this by being feared, juumping while feared, then zoning into an instance and being at a higher elevation.
https://streamable.com/9khjs
How it should work: 
players shouldn't not be able to gain elevation past the normal jump value

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/9khjs

**Comment by akrom23** [comment]
```juumping while feared``` How? As you are feared, you cannot perform movement actions.

**Comment by notsofamous** [comment]
Happened to me while taking the Shattrath portal to Orgrimmar

https://i.gyazo.com/48a605ebb3dff1bec4e53eb8a01ace92.mp4

Relog fixes the issue

**Comment by badmannerkid** [comment]
worth mentioning this was on the Nightbane SSC PvP realm

**Comment by badmannerkid** [comment]
> `juumping while feared` How? As you are feared, you cannot perform movement actions.

not sure, the bug didn't happen to me personally. but what did happen to me personally is controlling my character while mind controlled. will post video about that soon

**Comment by akrom23** [comment]
@notsofamous: Again druid.

**Comment by notsofamous** [comment]
Yes, unable to jump.

https://i.gyazo.com/18c6af9a5d43e9b41e22243979923531.mp4

Character is "floating"

**Comment by akrom23** [comment]
You were in flight form before using the portal?

**Comment by notsofamous** [comment]
yes

**Comment by akrom23** [comment]
Okay. I know where is the bug :) Thx a lot
