### ISSUE TITLE
[Mob] Rabid Shadowhide Gnoll

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1366]
Decription: 
This NPC uses a wrong ability. Poison.

How it works: 
He uses Poison. 

How it should work: 
He should use only https://vanilla-twinhead.twinstar.cz/?npc=434#abilities

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
http://db.hellfire-tbc.com/?npc=434#abilities
https://db.excalibur.ws/?npc=434#abilities

**Comment by Mikov1605** [comment]
it still does not use Rabbies :P
