### ISSUE TITLE
[Paladin] Talent and Draenei Racial Spell +% melee and spell hit does not work

### ISSUE THREAD

**Issue by Vitoshka** [SunwellWoW/Sunwell-TBC-Bugtracker#1368]
**_Decription:_** 

Paladin talent **Precision** and draenei racial ability **Heroic Presence** does not work

**_How it works:_** 

There is no increase in the number equivalent, in percent, for melee attacks and spell attacks, and this also does not appear in the character menu

_Examples:_

[1](https://a.radikal.ru/a16/1811/d1/62f151787641.jpg)
[1-2](https://b.radikal.ru/b42/1811/18/da0712861d6a.jpg)
[2](https://a.radikal.ru/a14/1811/79/b469b9d1a881.jpg)
[2-1](https://a.radikal.ru/a30/1811/71/8e767df18182.jpg)
[2-3](https://d.radikal.ru/d37/1811/ee/19a79e6fd1cc.jpg)

**_How it should work:_** 

It should be shown in green as a percentage, in numbers
If _Precession_ talent is taken (+ 3% melee hit and + 3% spell hit)
_Heroic Presence_ is an racial autobuff, he is always present and automatically gives an increase in hit + 1% to me and my group and does not scale if there are two draenei in the group and more with this racial ability.
Also very important - Heroic Presence cannot be cancelled

**_Source (you should point out proofs of your report, please give us some source):_** 

http://wowwiki.wikia.com/wiki/Heroic_Presence

http://wowwiki.wikia.com/wiki/Precision_(Paladin_talent)

**Comment by neheri** [comment]
Have you checked whether it actually doesn't work or is only not shown in starts? I am not sure if it should be shown there at all, it only shows % from hit rating, not from talents.

Go fight mob of level equal to yours. Do 1000 swings without and with talent. Check if the percentage of "hit" is the same. Use recount for stats.

I am playing warrior on beta test and have noticed that precision (3% hit) brought succesfull hit rate by 3% indeed.

**Comment by Vitoshka** [comment]
I checked in combat, misses of spells hit and in melee periodically occur, I think only developers can find out more about these spells in more detail.

It is also possible differences work of similar talents in the warrior and paladin.

**Comment by neheri** [comment]
Misses and spell hits should occur. There's 8% miss chance vs mob on the same level (not counting dodge, parry and block). 

Talents should only reduce that amount by proper percentage point. 

You would need to make 1000 of swings against mob on the same level to have this reliably tested.

**Comment by arcwizard** [comment]
This is all displayed in the addon Dr. damage, in game have some value which don't display (for example shaman talent Tidal Mastery), on 2.4.3. Draenei Racial give 1% melee hit for hunter, warrior and paly, or 1% spell hit for shaman, mage, priest.
And judging by all the talent gives 2 times more hit than it should: base resist chance for target with 3 more lvl = 17%, then spell have 83% base chance hit. On screen with shaman, there no gear, no talents. On screen with priest there no talents with spell hit and no gear with spell hit.
![424](https://user-images.githubusercontent.com/43764742/48359840-7d8aad00-e6a6-11e8-8562-8581a75be3db.jpg)
![ppr](https://user-images.githubusercontent.com/43764742/48359841-7d8aad00-e6a6-11e8-9488-ab41c8cf3f12.jpg)

**Comment by akrom23** [comment]
> There is no increase in the number equivalent, in percent, for melee attacks and spell attacks, and this also does not appear in the character menu

This is AMERICA. (I mean TBC). These values are not show in the character menu.

**Comment by neheri** [comment]
I think that DrDamage just reads buffs and talents and calculates those values on the result.

That means, buff can be shown and talent can be displayed and DrDamage can take it into consideration but talent can actually not work at the same time.

1000 white swings with 2h on a mob with equal level and stats of that in recount would solve all the concerns.

**Comment by arcwizard** [comment]
1000 white swings, one swing per 3,6 sec (or u have 2h wep with high speed?) = 3600 sec = min 1h and there anyway can be some random :)

**Comment by neheri** [comment]
1.4 one handed dagger should work as well, just without second one hander. Maybe you can get some haste to decrease it to 1.0. 1000 attacks should give roughly 10 misses difference, which should noticeable, if that's not enough it can be increased to 10 000. Will there be a better time for this than beta?

Every private server I played had players complaining about their bad performance because of an excuse of not working: hit/threat/stun ressistance talents, so if this could be significant if that was tested and fixed if needed during beta.

**Comment by akrom23** [comment]
https://imgur.com/a/QxNO1Z2
First one w/o Precision
Second one - w Precision 3/3

**Comment by neheri** [comment]
As long as in both cases you had weapon skill maxed up, it works 100% perfect. Thanks for testing this out.
