### ISSUE TITLE
[Spell] Polymorph

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1374]
Decription: 
Mobs can enrage while under the effect of poly.

How it works: 
"Blackrock Sentry becomes enraged". In poly state.

How it should work: 
It shouldnt happen, no proof, i remember it from every server i've been on.

Source (you should point out proofs of your report, please give us some source):

**Comment by Mikov1605** [comment]
Dear Gm, i would like to add, that only a few(blackrock shadowcasters) use Demon Armor. Some doesnt. They also lack the mana bar. Sorry for reporting it here, but u closed my report while i was writing it :P

**Comment by lukaasm** [comment]
Please create another issue with NPCs using/not using proper spells.

**Comment by akrom23** [comment]
It's just a script text. Enrage effect does not apply.
