### ISSUE TITLE
Hunter pet [ravager]

### ISSUE THREAD

**Issue by Asherdoom** [SunwellWoW/Sunwell-TBC-Bugtracker#1376]
Decription: 
Ravager pet in setekk halls remains stuck in the ground into setekk halls entrance (after first 2 mobs pulled). this happened like 50% of the time i entered instance. had to dismiss and recall pet to solve this bug

How it works: 
read above

How it should work: 
pet should not stuck  into the ground

Source (you should point out proofs of your report, please give us some source): i found none in the bugtracker that is why i am reporting this

**Comment by Wojtyas** [comment]
Me neither. Feel free to reopen when needed. (with screens/videos!)
