### ISSUE TITLE
[NPC] Wrathguard

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1377]
Decription: When using a spell he summons a small infernal called Flame Wave I.

How it works: When using a spell he summons a small infernal called Flame Wave I.

How it should work: There should be a flame wave on the ground but no infernal visible.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_111218_151828](https://user-images.githubusercontent.com/37372869/48352959-7657a500-e68e-11e8-9d7f-e15abdfb3749.jpg)

**Comment by neheri** [comment]
![wowscrnshot_111218_152128](https://user-images.githubusercontent.com/37372869/48353031-ad2dbb00-e68e-11e8-8630-729110aed83c.jpg)

**Comment by arcwizard** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1106
