### ISSUE TITLE
[Mob] Defias Night Blade

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1378]
Decription: 
His Slowing poison ability has a wrong slowing effect.

How it works: 
Desciprtion says 30% reduced, but u are actually slower than when under harmstring(which reduces by 60%)

How it should work: 
You should be slowed by 30%(movement). Actually im like 80%. But debuff description is 30%. The difference is seeable.

Source (you should point out proofs of your report, please give us some source): 
https://db.excalibur.ws/?spell=7992 - should be 30% in description and reality.

**Comment by Dootz** [comment]
Slow percentage is affected by level of creature. In this example if Defias Night Blade have level 25
he'll slow player by 30 + 25*1 = 55%.
