### ISSUE TITLE
[Dungeon Heroic Auchindoun Mana-Tombs][NPC] Ethereal Priest, Ethereal Sorcerer

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#1383]
Decription: 
[Ethereal Priest](http://db.hellfire-tbc.com/?npc=18317)
[Ethereal Sorcerer](http://db.hellfire-tbc.com/?npc=18313)

How it works: 
Ethereal priests does buff [Power Word: Shield](http://db.hellfire-tbc.com/?spell=35944) for NPCs from other groups, and do so before pull.

This NPC i pulled without other NPC, but he took buff Power Word: Shield.
![wowscrnshot_111218_170022](https://user-images.githubusercontent.com/43764742/48354530-a5741380-e69a-11e8-9e24-92e7a4f4c44c.jpg)
![wowscrnshot_111218_170058](https://user-images.githubusercontent.com/43764742/48354451-7493de80-e69a-11e8-919a-073986b9bf23.jpg)

Here you can see NPC priest from another group (not from group what was pulled), which buff target. Also NPC which in my target (as alot NPC casters on beta), after pull continued to move along its usual route, instead of moving to us at the moments when it doesn't cast.
![wowscrnshot_111218_170120](https://user-images.githubusercontent.com/43764742/48354452-7493de80-e69a-11e8-93b7-9f56648d3328.jpg)
![wowscrnshot_111218_170208](https://user-images.githubusercontent.com/43764742/48356022-09e4a200-e69e-11e8-8e57-97007bfabd1a.jpg)

How it should work: 
Ethereal priests must buff up (Power Word: Shield) only after pull, and only on himself and NPC from their group. Ethereal Sorcerer should moving to us at the moments when it doesn't cast.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/OigEEnBJrsw?t=202 , https://youtu.be/KEfwCh_CtgQ?t=210 (normal mode)  On this video you can see the behavior of NPC-casters who behave like any other NPCs with melee at the time when he doesn't cast.
https://youtu.be/KEfwCh_CtgQ?t=287 Here you can see that NPCs before pull are without shields of priest, and just after pull Ethereal Priest start buff Power Word: Shield.

**Comment by Anduyon** [comment]
Can confirm Priests are still shielding other groups.

**Comment by Anduyon** [comment]
Eternal Sorcerers currently also cast Arcane Missiles on themselves.

**Comment by Anduyon** [comment]
Eternal Sorcerers don't move from their position when their target is out of line of sight.
