### ISSUE TITLE
[NPC] Zorus the Judic - PATHING

### ISSUE THREAD

**Issue by Lashington** [SunwellWoW/Sunwell-TBC-Bugtracker#1387]
Decription: 
He walks around in a nice and coordinated path, which is very nice. But he stops his path and stands still for a good 40 seconds when you interact with him.

How it works: 
When you go interact with, accept his quest or even just right click him, he stops moving and stands still in that exact place you interacted with him. 

How it should work: 
He should be working his fine path, which you have done amazing, but he should only stop when spoken to. He should start working the second after you interact with him. 
![wowscrnshot_111218_184625](https://user-images.githubusercontent.com/44973281/48365691-ec1e3980-e6ab-11e8-864e-11cc750ecf7f.jpg)
![wowscrnshot_111218_184630](https://user-images.githubusercontent.com/44973281/48365692-ec1e3980-e6ab-11e8-8082-891698d97ce3.jpg)
![wowscrnshot_111218_184642](https://user-images.githubusercontent.com/44973281/48365693-ecb6d000-e6ab-11e8-844f-fe606323a15e.jpg)
![wowscrnshot_111218_184735](https://user-images.githubusercontent.com/44973281/48365695-ecb6d000-e6ab-11e8-9ae7-c6c5b604a12b.jpg)
![wowscrnshot_111218_184621](https://user-images.githubusercontent.com/44973281/48365697-ed4f6680-e6ab-11e8-94b0-bc4d1dab17a0.jpg)

Here are some screenshots that show me following him and showing he actually is working a correct path, but then I speak with him and he stops. I got a Stop timer on the last screenshot to show how long it took before he started his path again.

**Comment by Dootz** [comment]
Isn't it normal/ expected behavior of all npcs? If you want to talk with him he should stop.

**Comment by Lashington** [comment]
Yes he should, but not for 40 seconds after you have stopped interracting with him. It feels weird

**Comment by Dootz** [comment]
It's global behavior and wont be changed right now.
