### ISSUE TITLE
[Q] Lazy Peons #897

### ISSUE THREAD

**Issue by infp40** [SunwellWoW/Sunwell-TBC-Bugtracker#1389]
Again broke this quest :(
[link](https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/897)

**Comment by FrauHolle86** [comment]
no working on PTR atm

**Comment by Wojtyas** [comment]
Peons still have some issues. 
- [ ] Part of them never sleep. They "work" in place where they suppose to sleep.
- [ ] Those who are sleeping work but after "poke" them by item they can immediately start to sleep again (after 1-10 seconds). So they even don't reach nearly wooden piles where they suppose to work.

**Comment by FrauHolle86** [comment]
imo it would be very importent to solve this issue till friday. otherwise ppl wanna start leveling but cant finish that quest --> no follow up quest --> lack of xp --> cant leave the starting area properly

**Comment by Wojtyas** [comment]
This quest has to be done ;) It's one of first in-game and would be so shame its broken :fire:

**Comment by Wojtyas** [comment]
Fixed & implemented.
