### ISSUE TITLE
Macros for pet functions not working

### ISSUE THREAD

**Issue by mhdemn** [SunwellWoW/Sunwell-TBC-Bugtracker#1390]
/petautocasttoggle
/petautocaston
/petautocastoff

Macros above, all related to pet, aren't working,

They should be.

Source: Every wow wiki or info site there is, works in other servers

**Comment by doomnyx** [comment]
Not working after retesting.

**Comment by lukaasm** [comment]
on which spells did u test it?
https://streamable.com/8x6d5

**Comment by doomnyx** [comment]
Didnt include spell name after command, so probably it works 😊

**Comment by Piootrek** [comment]
Fixed
