### ISSUE TITLE
goretusks in westfall nearly oneshot after charge

### ISSUE THREAD

**Issue by Zerroc1** [SunwellWoW/Sunwell-TBC-Bugtracker#1399]
Decription: 
Goretusks in Westfall will start a charge on range attackers, if they reach them they deal 60-100% of casters life damage, depends if it crits or not. im not sure if this is working as intended

How it works: 
Goretusks charge till he is in meleerange to the attacker, if he reaches the attacker the first hit deal (on cloth-classes) 60-100% of their maxlife hp.

How it should work: 
Im not sure if its working correctly that way. 

Source (you should point out proofs of your report, please give us some source): 
every goretusk with charge in westfall (near sentinell hill)

**Comment by Zerroc1** [comment]
*it should add additional damage: https://www.wowhead.com/npc=454/young-goretusk#abilities

but i couldnt figure out how much additional dmg. cant believe its over 60% of caster hp

**Comment by Mikov1605** [comment]
i reported it already my friend, the fix is not out yet ;) 
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1183

**Comment by Zerroc1** [comment]
oh ok, didnt see it
