### ISSUE TITLE
[Warlock] [Quest] Voidwalker Quest (The Binding) Causes DC/Rollback 

### ISSUE THREAD

**Issue by F4play** [SunwellWoW/Sunwell-TBC-Bugtracker#14]
Decription: 2nd Part of Alliance Voidwalker Quest (The Binding: ID#1689) causes a dc & rollback at the end of the cast of Summon Voidwalker caused by using the Bloodstone Choker (ID# 6928) item in the summoning circle.

Also causes a DC/Rollback as an orc/horde when using the quest item to summon a voidwalker in orgrimmar. Seems to be just the spell "Summon Voidwalker" itself causing the DC I'm guessing which is shared across the different versions of the quest. 

How it works: Head downstairs to the summoning circle at the bottom of the slaughtered lamb, use bloodstone choker, starts cast of "Summon Voidwalker" to summon a voidwalker to fight, gets to complete cast then instantly dc's the player and causes a rollback. 

How it should work: At the end of the cast a voidwalker should be summoned/fought to complete the quest.

Source (you should point out proofs of your report, please give us some source): No source needed

**Comment by akrom23** [comment]
Cannot reproduce. 
I think it's already fixed.
