### ISSUE TITLE
[Mob][Spell] Defias Enchanter in polymorph

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1401]
Decription: 
He breaks out of poly after like 9 sec 

How it works: 
Casted poly on him, so i could easily attack another defias, but he broke out of my poly after 8-10 sec.

How it should work: 
He should be in poly unless damaged/getting out of combat/poly duration finishes.

Source (you should point out proofs of your report, please give us some source):

**Comment by notsofamous** [comment]
Heartbeat resists, mobs can resist CC effects every 3 seconds. Not a bug.

>A heartbeat resist is an early break in a spells effects due to periodic checking for resistance. The result is that the resisted effect ends prematurely.
https://wow.gamepedia.com/Heartbeat_resist

**Comment by notsofamous** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20072
https://us.battle.net/forums/en/wow/topic/7591980330
https://forum.nostalrius.org/viewtopic.php?f=25&t=378
https://www.mmo-champion.com/threads/820741-The-complete-crowd-control-Guide

**Comment by akrom23** [comment]
Not a bug.
