### ISSUE TITLE
[Core] Abilities with cast timers are uninterrupted by side steps

### ISSUE THREAD

**Issue by tethbetatest** [SunwellWoW/Sunwell-TBC-Bugtracker#1402]
Decription: 
Using abilites with a cast-timer (such as spells, heals, etc.) are able to be uninterrupted whilst performing side steps (this is also able to be chained - see the video below).

How it works:
1. Start casting an ability with a cast time.
2. Side step by clicking on A or D (whichever one).
3. Cast is **not** interrupted and **continues**.

How it should work: 
1. Start casting an ability with a cast time.
2. Side step by clicking on A or D (whichever one).
3. Cast is **interrupted and cancelled**.

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/vf4gu

**Comment by neheri** [comment]
I've also seen creatures doing that. I've even seen fleeing NPCs that continue casting while running away.

**Comment by arcwizard** [comment]
I also saw many such creatures, both in the dungeons and beyond, I think this is a common bug.
