### ISSUE TITLE
Mob pull after evade

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#1403]
Creature may enter combat once again right after it evades which is quite wrong. After mob evades it should go back to its starting position and then be possible to pulled once again.

https://gyazo.com/0f9ff8674ce70d9861ee401d76749387

**Comment by notsofamous** [comment]
Same as https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1301 ?

**Comment by Wojtyas** [comment]
Oh, indeed.
