### ISSUE TITLE
Nature's Grace(druid balance talent) doesnt work sometimes.

### ISSUE THREAD

**Issue by Jekenius** [SunwellWoW/Sunwell-TBC-Bugtracker#1404]
Decription: 
Nature's Grace isnt working all time.

How it works: 
After landing starfire, healing touch, regrowth, wrath and moonfire crit sometimes Nature's Grace buff(making next spell cast shorter for 0.5sec) just not applies on character. Sometimes it works, sometimes it doesnt. Also, i have never seen buff from any spell but wrath, and wrath doesnt apply that buff every time also(seen few crits that didnt give the buff).
How it should work: 
All spell crits should give Nature's Grace buff.

Source (you should point out proofs of your report, please give us some source): 
Was testing balance druid spec on target dummy but found that not every crit does Nature's Grace buff but it should give it following the description("All spell criticals grace you with a blessing of nature, reducing the casting time of your next spell by 0.5 sec.")

**Comment by sicknot1** [comment]
Could it have internal CD?

**Comment by Jekenius** [comment]
I dont think so because the only ability gave me that buff was wrath and few times i got that buff 2 times in a row(2 times in ~4sec). But i havent seen that buff was applied by any other ability at all(checked for starfire, moonfire, healing touch, regrowth and wrath. Maybe i havent done enough tries but counting description in the game it should work like warrior talent "Flurry" that goes in to the board on every warrior's crit. Also there's no markers for that talent to be "proccable", means that effect should be guaranteed on crit(you can compare similar talents: warrior "Flurry" and hunter "Frenzy").

**Comment by zapsuu** [comment]
Same bug like here:
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1281

**Comment by zapsuu** [comment]
On every critical spell I got Nature Grace. Maybe you don't feel it, because you casted Wrath 1 by 1?

**Comment by Jekenius** [comment]
I cany feel it because i was casting these spells and looking to my buff bar to catch that buff. I dont know what's the reason, but i saw that buff only for wrath and not always.

**Comment by zapsuu** [comment]
When you cast Starfire, the buff will show instantly and dissaper instantly after second cast. Wrath have to land on the target, so if you will cast critical Wrath and you will start cast new one before the first will land on the target (and get crit), then you lose your buff. You will get buff and lose it after 0,5 sec or less, because Wrath has the some way between you and your target.

This is not a bug. If you will use Starfire or stay really close your target, then you will not feel the problem. The same situation is in ele shammy. Shammy cast Lightning Bolt, and he start cast CL, before critical LB land on target you finish casting the CL and you spend more mana (crits in ele makes your next spell cost 40% mana less).

**Comment by Jekenius** [comment]
Okay, but why i'm not getting Nature's Grace on casting heals and moonfire?

**Comment by Jekenius** [comment]
Heals are almost the same as Starfire so i could miss it, but if i cast Moonfire Nature's Grace buff is spent on next Moonfire cast, i.e. wasted?

**Comment by Jekenius** [comment]
Rechecked that taking in account info about thing you told, Zapsuu, but that still isnt working fine. Combat log says on wrath crit "Me gained Nature's Grace" but on starfire crit it says "Me's Nature's Grace is refreshed."

**Comment by zapsuu** [comment]
I checked it, you are right. Moonfire, Starfire, Regrowth and Healing Touch don't proc Nature's Grace. Only Wrath works well. Last time, when I tested balance druid (around 4-5 days ago) everything works well.

![wowscrnshot_111418_080331](https://user-images.githubusercontent.com/43937876/48465747-2854b580-e7e4-11e8-9c71-b531ec17eb8c.jpg)
![wowscrnshot_111418_080359](https://user-images.githubusercontent.com/43937876/48465748-2854b580-e7e4-11e8-8ccb-e8f774bfcd8b.jpg)
![wowscrnshot_111418_080707](https://user-images.githubusercontent.com/43937876/48465994-cea0bb00-e7e4-11e8-9a06-ef64c2434959.jpg)
![wowscrnshot_111418_080642](https://user-images.githubusercontent.com/43937876/48466000-d4969c00-e7e4-11e8-9bfb-9ff81536e84a.jpg)

**Comment by Altgreen** [comment]
If it helps any I also noticed this today but at least it's behaving consistently - there are no spells that are giving me the Nature's Grace buff.

**Comment by Altgreen** [comment]
Why closed ? It's not fixed, just checked !

**Comment by Jinzo25** [comment]
Crucial Bug for Moonkins, still not fixed, so like Altgreen said, why is it closed?

**Comment by Wojtyas** [comment]
There was an update in the morning. Fix should be live now.

**Comment by Altgreen** [comment]
Well, you semi fixed it. It is proccing, but it's being consumed by moonfire ticks and lightning capacitor charges which are definitely spells being cast.

**Comment by Wojtyas** [comment]
I will make new ticket about it cuz its new issue :D
