### ISSUE TITLE
[Macro] Improper icon displayed

### ISSUE THREAD

**Issue by ahlens** [SunwellWoW/Sunwell-TBC-Bugtracker#1406]
**Decription:** 
Macro with parameters:
- [stance:1]
- [stance:2]
- [stance:3]

display wrong icon depending on our stance.

**How it works:** 
Screenshoot provides in-depth explenation
![macro](https://user-images.githubusercontent.com/23612673/48420635-1b3fb400-e75b-11e8-94b2-8f380ce55292.jpg)

**How it should work:** 
Skill icon should be displayed accordingly to current stance.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
``
#show [stance:1] Overpower; [stance:2] Revenge; [stance:3] Whirlwind
```

**Comment by ahlens** [comment]
Haven't tested that one, still
#show should display only icon
#showtooltip should display icon + tooltip

**Comment by akrom23** [comment]
```
#showtooltip
/cast [stance:1] Overpower; [stance:2] Revenge; [stance:3] Whirlwind
```
Works fine too.
