### ISSUE TITLE
NPC-names are not displayed correctly in the chat

### ISSUE THREAD

**Issue by Zerroc1** [SunwellWoW/Sunwell-TBC-Bugtracker#1407]
Decription: 
NPC Names are not displayed correctly in the chat

How it works: 
NPC name is displayed as ????? in the chat.

How it should work: 
NPC name should be displayed in the chat
![unbenannt](https://user-images.githubusercontent.com/44994995/48428720-e0924780-e76b-11e8-9497-2e8a2bb2b1e7.JPG)

Source (you should point out proofs of your report, please give us some source):

**Comment by neheri** [comment]
Same happened in HP:
![wowscrnshot_111318_203543](https://user-images.githubusercontent.com/37372869/48438225-c19faf80-e783-11e8-980c-7e860980aaa0.jpg)
It was shattered hand guard.

**Comment by Zerroc1** [comment]
123 Zerroc
