### ISSUE TITLE
Combat Bug After Healing

### ISSUE THREAD

**Issue by rubicus2** [SunwellWoW/Sunwell-TBC-Bugtracker#1408]
Decription: Combat Bug After you heal yourself after Duel finished.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
Video of bug: https://www.youtube.com/watch?v=DRjEFrH7yOI&feature=youtu.be

**Comment by akrom23** [comment]
Maybe the problem was causde by these mobs?
Next time use command .debug hostile on yourself.

**Comment by notsofamous** [comment]
Chain heal jumped to a pet that was in combat. 

The only bug here is that you're able to chain heal someone who's dueling.
