### ISSUE TITLE
Invissible/Unlootable/ Rare Npc 

### ISSUE THREAD

**Issue by Hnidka** [SunwellWoW/Sunwell-TBC-Bugtracker#141]
Decription: Gravis Slipknot :  GUID : 86756 Entry : 14221 
                   Gravis Slipknot is a level 36 RARE mob human found in the Alterac Mountains. 

How it works:  U can target him only with /target Gravis Slipknot 
                        U see just big yellow moving name Gravis Slipknot 

How it should work:  At first u can see him, u can click on him, hes rare npc, lootable 

Source (you should point out proofs of your report, please give us some source): 

https://www.wowhead.com/npc=14221/gravis-slipknot#comments
http://wowwiki.wikia.com/wiki/Gravis_Slipknot
https://www.youtube.com/watch?v=0Kvy1ZkelPU

**Comment by Dootz** [comment]
![wowscrnshot_082918_174711](https://user-images.githubusercontent.com/25490436/44799193-9f01ef80-abb3-11e8-93be-480e5e5d93fd.jpg)

looks like it was fixed
