### ISSUE TITLE
[Core] Object visibility distance

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1412]
Decription: I presume that this is not really a bug but it is noticeable that object visibility distance is quite low. I remember you could see NPCs and players from much further on Hellground and other servers. It has probably some connection to server performance especially with large amount of players, but maybe we could test larger distance on Beta. 

How it works: Object visibility distance is very low. I estimate it to be like 50 yds. Fel reaver can come out of nowhere and just one shot you.

How it should work: I remember finding Fel reaver to complete the Shattered Halls quest on HG. It was quite easy because you could see objects from like 300 yds as far as I remember. However doubling current visibility range would also be significant. 

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=jcKJ2LlgyZs

**Comment by akrom23** [comment]
#63.
