### ISSUE TITLE
[Quest] Traitors Among Us

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#1415]
"The traitors turn red (hostile), but you cant attack them and they don't share in party either. There's not enough of them to complete for an entire party/more than two people doing the quest. Will have to make the traitors killable and respawn. This needs to be fixed, as it will block the entire quest chain in Dustswallow otherwise."

PROOF -https://www.youtube.com/watch?v=DHzve5DxV6s

**Comment by Dootz** [comment]
fixed yesterday, should be live now.
