### ISSUE TITLE
[Spell Mechanics] Charge issue

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1425]
On below videos we can see when player is trying to use Charge/Intercept spell and there is no charge effect at all. Player gets rage bonus and deal damage by this spell anyway.

https://clips.twitch.tv/EmpathicInterestingRavenVoteYea - Charge w/o charging
https://clips.twitch.tv/PowerfulWonderfulLarkPunchTrees - Charge w/o charging
https://clips.twitch.tv/AffluentTentativeSharkShazBotstix - Intercept used but w/o charge effect (same story)
https://clips.twitch.tv/ImpossibleEndearingMeerkatDoubleRainbow - Warrior falls into textures after Charge use near wall

**Comment by ahlens** [comment]
I think the same problem is with training dummies.

**Comment by lukaasm** [comment]
merge with https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1809
