### ISSUE TITLE
[ZONE] [Darkshore] escort quest

### ISSUE THREAD

**Issue by Lonoss** [SunwellWoW/Sunwell-TBC-Bugtracker#143]
- [x] Quest - The Absent Minded Prospector
http://db.hellfire-tbc.com/?quest=731
How it works: After start quest NPC goes in to textures, disappear. Quest can't be completed.
How it should work: NPC should go thru ruins in order to retrieve fossil. Typical escort quest.
Source: Realy good example how it shoud work.
https://www.youtube.com/watch?v=qHJv1qrpMLc

- [x] Quest - Escape Through Force
http://db.hellfire-tbc.com/?quest=994
How it works: NPC teleporting instead of walking, runing away to a cave. I don't think quest can be complited like that.
How it should work: Standard escort quest, he shoud simply walk to his pet.
Source: Wideo from 2009 but shoud be accurate.
https://youtu.be/8zDB-ucQAqw?t=5m30s

- [x] Quest - Escape Through Stealth
http://db.hellfire-tbc.com/?quest=995
How it works: NPC teleporting instead of walking in human form. Quest isn't complete.
How it should work: NPC should change in to cat form. Run from cave and quest should be done soon after, automatickly.
Source: Wideo from 2010 but shoud be accurate.
https://www.youtube.com/watch?v=y5AMXINUv3Q

- [x] Quest - Therylune's Escape
http://db.hellfire-tbc.com/?quest=945
How it works: NPC run in to textures. Quest can't be completed.
How it should work: Standard escort quest.
Source: It shoud be somthing like this:
https://www.youtube.com/watch?v=bmrHHDLVivk
I don't find retail info but for sure is not working now.

- [x] Quest - The Sleeper Has Awakened
http://db.hellfire-tbc.com/?quest=5321
How it works: NPC don't react after using quest item. Quest can't be done.
How it should work: After using horn NPC should folow you.
Source: It shoud be somthing like this:
https://www.youtube.com/watch?v=oubCOj1nVbI

**Comment by Dootz** [comment]
thanks for report, will be fixed with next ptr update.
