### ISSUE TITLE
[The Black Morras] Portal creatures and Crocolisks issue

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#1432]
- [x] 1. Darkwater Crocolisks should be hostile.
- [ ] 2. Literally no mobs spawn from each of portals where the suppose to: 1-5, 7-11, 13-17.

https://clips.twitch.tv/IncredulousNiceEggnogResidentSleeper

**Comment by notsofamous** [comment]
Darkwater Crocolisks still not hostile on heroic.
