### ISSUE TITLE
[Item] Bullets gets unequiped

### ISSUE THREAD

**Issue by ninc** [SunwellWoW/Sunwell-TBC-Bugtracker#1434]
Decription: 
When I die my bullets gets unequiped.
I played protection warrior.

How it works: 
When I die my bullets gets unequiped.

How it should work: 
When I die my bullets should stay equiped.

Source (you should point out proofs of your report, please give us some source): 
Played slave pens 2018-11-13

**Comment by akrom23** [comment]
Canno reproduce.
