### ISSUE TITLE
Shaman grounding not working

### ISSUE THREAD

**Issue by fakesunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#1435]
Decription: 
Grounding is not working. The totem is just placed without protection you.

How it works: 
https://clips.twitch.tv/SmallUninterestedPelicanKreygasm

How it should work: 
It should absorb the next incomming spell by applying a buff to the caster of the totem, but it does nothing

Source (you should point out proofs of your report, please give us some source): 
Been like that since vanilla

**Comment by notsofamous** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/663
