### ISSUE TITLE
[Old Hillsbrad Foothills] Epoch Hunter

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#1438]
Caster mob (Infinite Defiler) spawned on last encounter during event was friendly for entire fight and only Thrall was able to fight him. He should be hostile obviously.

https://clips.twitch.tv/VivaciousUglyAuberginePastaThat

**Comment by Silroth** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/638
