### ISSUE TITLE
[item] item containers 

### ISSUE THREAD

**Issue by anubyss** [SunwellWoW/Sunwell-TBC-Bugtracker#144]
Decription: when u right click an item container like jaggad clam or package of identified plants u get items but the container doesnt get deleted from inventory

How it works: when u right click an item container like jaggad clam or package of identified plants u get items but the container doesnt get deleted from inventory

How it should work: the item container should delete from your inventory.

Source (you should point out proofs of your report, please give us some source): 

https://imgur.com/a/MxjJise

https://imgur.com/a/vnUGV3D

**Comment by Nadiirr** [comment]
Can't reproduce / Fixed.
