### ISSUE TITLE
Mind Control - break

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#1440]
Decription: When mobs hits you there is a chance to break the MC.

How it works: Mobs can kill you, but the MC will not break. When mobs attacks controled mob, then MC break really fast.

How it should work: 
When mobs hit you there should be a chance to break MC, but when controled mob get damage the MC shouldn't break.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Proofs confirmed that MC should be break on damage?

> When mobs attacks controled mob, then MC break really fast.

Cannot reproduce it.

**Comment by Wojtyas** [comment]
Feel free to reopen when needed.
