### ISSUE TITLE
[Quest] A Spirit Guide

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1444]
Decription: To complete the quest you must use [Ancestral Spirit Wolf Totem] near Fel Orc Corpse. You must follow him to Maghar fortress and when he's nearby he gives you friendly reputation with Maghar, which lets you turn in the quest and start quest chain with Maghar faction.

When the first time I summoned the wolf, it was working perfect, he did emotes and starting to go towards Maghar fortress. However because of short object visibility range (also reported today) I made one step to more and lost him, he despawned.

When I tried to summon the wolf again (impossible to turn in the quest without the wolf) he no longer appeared. I removed and took the quest again, same thing - no wolf after using the quest item.

How it works: You cannot resummon wolf if you use the quest item for the first time.

How it should work: If you lose the wolf, you should be able to resummon him at the orc's body and start the escort over again. There should be bigger object visibility because now it's very easy to lose an escorted NPC (happened to me several times, also with other quests).

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_111318_222603](https://user-images.githubusercontent.com/37372869/48444029-20b8f080-e793-11e8-86f8-d739083f38e9.jpg)
![wowscrnshot_111318_222605](https://user-images.githubusercontent.com/37372869/48444033-2282b400-e793-11e8-994e-67d04443577f.jpg)
https://youtu.be/4BGlnjGieUk?t=95

**Comment by Dootz** [comment]
confirmed. Right now you can use quest item to summon next wolf only after relog.
