### ISSUE TITLE
[Serpentshrine Cavern] General Trash

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1447]
- [x] 1. Coilfang Frenzy fishses seems to not appear when players are in water.
- [x] 2. Coilfang Shatterer melees cloth for 1355.
Source: Damage: 11000-15500 (corecraft)
- [x] 3. Coilfang Serpentguard's Spell Reflection charges do not disappate on spells being applied to the shield.
- [x] 7. Tidewalker Depth-Seer interrupts its own tranquility to auto attack its target or cast rejuvenation on itself.
- [x] 8. Greyheart Shield-Breaker has 180k hp and melees 16k armor tank for 1.5k.
Source: Health: 332500, Damage: 10500-14800 (cc)
- [x] 9. Greyheart Tidecaller's Virulent Poison hits for 7.2k nature dmg
- [x] 10. Fearing trash mobs makes them run a ridiculous distance away. Can be a big issue on Lurker with the Ambushers etc.

**Comment by notsofamous** [comment]
5. Should spam it only when they are on low HP.
6. Just confirming that it shouldn't be interruptable, so the Earth Shock/counterspell thing should be fixed.
9. It should hit for 4k per stack, is it possible the player had 2 stacks?
