### ISSUE TITLE
[Serpentshrine Cavern] The Lurker Below

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1448]
- [x] 1. Melee hitbox is too large, the boss can auto people on edge of platform. - needs to be verified (video compared to retail's one)
https://streamable.com/juugm - warlock was tanking boss from outer platform and recieved auto-attacks. MT should be on inner platform, otherwise boss shall Water Bolt raid.
- [x] 2. Melee on 27.5k tank hitting 2.8k - 3k.
Source: Damage: 19600-27000 (cc)
- [x] 3. Coilfang Ambushers spawn with 5% mana, should with full mana.
- [x] 4. Coilfang Ambushers will spawn 300 yds away and shoot players from that position. Should spawn on small platforms around Lurker.
- [x] 5. Coilfang Ambushers can be mindcontrolled, and when mindcontrol drops they simply despawn while they shouldn't be able to get MC. Same like guardians.
- [x] 6. Lurker drops no loot.
He should drop one of these items: 30064, 30067, 30062, 30060, 30066, 30065, 30057.
And one of these items: 30059, 30061, 33054, 30665, 30063, 30058.

**Comment by notsofamous** [comment]
- [x] Coilfang Ambushers shouldn't move from their platforms. They should swim to their position and then stay there and shoot people.
