### ISSUE TITLE
Priest Tier 5 (2) set bonus

### ISSUE THREAD

**Issue by JuhaLintunen** [SunwellWoW/Sunwell-TBC-Bugtracker#1452]
Decription: "If your Greater Heal brings the target to full health, you gain 100 mana."

How it works: Right now it seems that you only get the mana if (I think) the greater heal brings you to max _base_ health. For example when I heal myself from 2k to 7k (while 9k is my health pool) it gives 100 mana.

How it should work: Greater Heal should give 100 mana whenever you heal the target to full of their health pool, not base health.

Source (you should point out proofs of your report, please give us some source): Worked like this on 2 different TBC servers, plus https://www.wowhead.com/item-set=665/avatar-raiment#comments
https://imgur.com/a/S0NkSN0

**Comment by koshimo** [comment]
This is still broken. Tested today 12/31.

https://i.imgur.com/OKhMGcl.jpg
https://i.imgur.com/F19vztI.jpg
https://i.imgur.com/QiObQMo.jpg

First two pictures shows my Greater Heal mana cost, my mana, and showing that I have T5 2p equip. 
5430 total mana, 825 cost of gheal. After casting the gheal and topping myself I should end at 4705 mana (5430-825+100). 
The third picture shows me casting greater heal on myself, topping myself, and ending at 4605 mana which is just my total mana minus the cost of greater heal. If the set bonus was working correctly I should be ending at 4705 mana. Also worth noting there is nothing in my combat log about the 100 mana I should be gaining.

https://i.imgur.com/J3USufe.jpg

Also tested healing someone else and had the same outcome.

**Comment by Spoohne** [comment]
Confirming the exact same findings as Koshimo. 2PC T5 is broken and does not return the 100 mana. Any updates?

**Comment by JuhaLintunen** [comment]
Still bugged! Please fix, this is crucial for priest healing ::]!

**Comment by Spoohne** [comment]
Hi, it's been 3 months now? Any word?

**Comment by akrom23** [comment]
Should be fixed.
