### ISSUE TITLE
[Warlock] Pet auto-cast doesn't work properly

### ISSUE THREAD

**Issue by RPAncap** [SunwellWoW/Sunwell-TBC-Bugtracker#1454]
Decription: Pets don't autocast spells. (or atleast the Imp doesn't - didn't try other ones yet).

How it works: For auto-cast to actually work - you have to disable and enable auto-cast everytime you summon your pet or mount/dismount.

How it should work: 
It should just work :-)

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=qz31EjlFCVE&feature=youtu.be

**Comment by RPAncap** [comment]
I can confirm this does happen with hunter pets aswell.

**Comment by Scarith** [comment]
Just tested with a Wolf and Furious Howl. It's on auto-cast but it's not casting it, however, he does cast it as an attack when I'm fighting a mob (as in, he thinks it's a damaging ability and thus when he's attacking a mob he does cast Furious Howl). After combat however he does not cast it or whenever he's not attacking, even if I am attacking.

**Comment by doomnyx** [comment]
The issue from the first post is gone, autoattack working. @Scarith reporting Furious Howl in separate report is good idea, as this one can be closed.

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1696
