### ISSUE TITLE
[Mob] Skeletal Horror

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1456]
Decription: 
Mob isnt using his ability

How it works: 
Normal meele mob 

How it should work: 
Should use Terrify. 

Source (you should point out proofs of your report, please give us some source): 
https://db.excalibur.ws/?npc=202#abilities

**Comment by Mvtsvraev** [comment]
He does, you're wrong.And start read the bug tracker and research information if you really want help project.

**Comment by Mikov1605** [comment]
Im helping more than you just complaining ur ass. Killed 11 of them, not a single one used it.

**Comment by Mikov1605** [comment]
And i was in meele range by every one since 50% hp

**Comment by Mvtsvraev** [comment]
Proof of that they must cast on 1 target?Cause i know they does cast it till 2man attack him.

**Comment by Mikov1605** [comment]
They always did on any server i played. No matter if one single or multi targets, its a aoe cast, like Terrific Howl(warrior skill)

**Comment by Mikov1605** [comment]
https://vanilla-twinhead.twinstar.cz/?spell=7399
