### ISSUE TITLE
[Character] Weird animation in stormwind

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1458]
Decription: 
My character, while in trade district, is randomly using "Flamestrike" animation
EDIT: Same happens at Ironforge, at the main square(before the bank)
How it works: 
While running through SW, my character( on mount or w/o) is randomly using "Flamestrike" animation, so i mean, he puts the left hand in the air and the right down.
![wowscrnshot_111418_103525](https://user-images.githubusercontent.com/43579401/48473751-6c05ea00-e7f9-11e8-969b-3e0872db8478.jpg)

How it should work: 
Well, he shouldnt do that. 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
#1562 is more general.
