### ISSUE TITLE
[ quest ][npc] as the crow flies credit master npc quest id 9718

### ISSUE THREAD

**Issue by anubyss** [SunwellWoW/Sunwell-TBC-Bugtracker#146]
Decription: NPC spawns when u complete the route and quest from as the crow flies ( quest id 9718 )

How it works: When u use item from quest and u end route and u complete quest, the npc spawns.

How it should work: No npc should spawn

Source (you should point out proofs of your report, please give us some source): 

https://imgur.com/a/vktIMmY

**Comment by forafriend** [comment]
I don't think that's an npc, but a GM trigger. Turn off GM and you shouldn't see it.

**Comment by Dootz** [comment]
yup, that's true
