### ISSUE TITLE
Copper Vein inaccessible

### ISSUE THREAD

**Issue by Sabre142** [SunwellWoW/Sunwell-TBC-Bugtracker#1460]
Description: 
Copper Vein in Durotar (coordinates 48,19) is inside a large rock and cannot be mined.

How it works: 
![capture](https://user-images.githubusercontent.com/26516348/48477250-3abb0780-e855-11e8-8357-41336804eb15.PNG)

How it should work: 
Should be outside of the rock so it can be accessed.

**Comment by Dootz** [comment]
I'll mention this ticket in other one mining-related because all veins need to be re-spawned.
