### ISSUE TITLE
[Mob] Splinter Fist Warrior

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1461]
Decription: 

Something is wrong with the "Say" script of this mob
How it works: 
![wowscrnshot_111418_114521](https://user-images.githubusercontent.com/43579401/48477841-ef780900-e802-11e8-8a51-3dc865b9913c.jpg)

How it should work: 

???? replaced with Splinter Fist Warrior 
Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented.
