### ISSUE TITLE
[Visual] Rage bars on most mobs

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1462]
Decription: 
nearly 75% from the mobs i encountered got rage bars. i already mentioned it on the spiders and wolves in duskwood (here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1271) 
whats new? 
90% of the undead on raven hill got it as well, even though they are not warriors.

How it works: 
Most mobs around in the zones i checked(duskwood/elwynn/redridge/westfall) got rage bars

How it should work: 
ONLY mobs that generate rage and use it, should have a rage bar! 
Non-rage users should have just a health bar, eventually a mana bar, if caster class.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Same here #1271.
