### ISSUE TITLE
[Mob]Eliza

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1463]
Decription: 
Mob spawns w/o mana, she regenerates it during the fight. 
Her guard should aid her for 10 sec, not for the entire fight.
She got a incredible movement speed.
How it works: 
Eliza is spawning w/o mana, her emote is "???? says..." + the guard is active for the whole fight.
Even with frostbolt on her, she moves fast as f*ck. 
![wowscrnshot_111418_141835](https://user-images.githubusercontent.com/43579401/48485224-987d2e80-e818-11e8-92f1-d8463cdc97b9.jpg)

How it should work: 
Should spawn with full mana. 
Should have normal movement speed. 
Guard should be active for 10 sec.

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?npc=314#abilities

**Comment by akrom23** [comment]
#1298
