### ISSUE TITLE
[Mob] Spawning mobs using mana

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1464]
Decription: 
Done Eliza quest(post below) + The Legend of stalvan. It appears, that all mobs that are being summoned by a action on a item, and using mana, spawn w/o mana, they regenerate if after being spawned.

How it works: 
Spawning Eliza spawns her w/o mana. Same with ghosts during The Legend of Stalvan questline(those banshees)

How it should work: 
Mobs should spawn with their full mana

Source (you should point out proofs of your report, please give us some source):

**Comment by notsofamous** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1298
