### ISSUE TITLE
RiperPaw Gnoll Combat Bug

### ISSUE THREAD

**Issue by wilhermil** [SunwellWoW/Sunwell-TBC-Bugtracker#1467]
Decription: 
After Attacking 1 mob second attacked me too but i wanted to run away,after runing away i wanted to use fireball but he started to evading (far from spawn point) and i cause 1 fireball dmg but all the time i cant do nothing to him 

How it works: 
Infinite Battle ,immortal enemy ,chasing me evrywhere

How it should work: he go away or i end combat 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_111418_180247](https://user-images.githubusercontent.com/44753762/48499402-aa6ec980-e838-11e8-98ad-18364055c5f2.jpg)
![wowscrnshot_111418_180327](https://user-images.githubusercontent.com/44753762/48499428-b8244f00-e838-11e8-9280-65b2ffde022a.jpg)
![wowscrnshot_111418_180409](https://user-images.githubusercontent.com/44753762/48499439-bf4b5d00-e838-11e8-9b00-ec9e7c337dc1.jpg)
![wowscrnshot_111418_180419](https://user-images.githubusercontent.com/44753762/48499440-c1152080-e838-11e8-8de5-50e563e5c51f.jpg)

**Comment by lukaasm** [comment]
It's already fixed, but realms were not yet updated

**Comment by wilhermil** [comment]
okay you can close :)
