### ISSUE TITLE
(Proffs) Mining

### ISSUE THREAD

**Issue by TBCKillshot** [SunwellWoW/Sunwell-TBC-Bugtracker#1472]
Decription: 
I was asked to test out mining and this is conclusion i came with after few days of testing.

How it works: 
The Mining itself works perfectly fine and has no apperant issues with it but on the other hand there is some mining nodes that are out of their place. Plus there is also huge piles of  ore spawning.

The Nodes that are spawning should be bit reduced mainly copper ore there is so much of it u can't even turn around not it. Also the zone (Shadowmoon Valley) lacks many of it's nodes because it's hard to find more then 2 to 4 nodes in the whole zone.

How it should work:  The nodes are not supossed to be spawned inside objects so that should be fixed but came only on 1 - 2 of them near OGG.
![wowscrnshot_111318_231353](https://user-images.githubusercontent.com/42093565/48502675-68e21c80-e840-11e8-887f-71e5dcf34723.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by neheri** [comment]
Please notice that population on beta is very low compared to what it's going to be on release, so you can have an impression of overwhelming amount of nodes - but if you split it into hundreds of players it doesn't look so impressing anymore.

**Comment by Dootz** [comment]
This is probably no longer relevant. We made several changes to number of spawns in each zone and respawn time.
