### ISSUE TITLE
Mobs dont reset, When they cant reach you ontop of gameobjects.

### ISSUE THREAD

**Issue by Tanesiris** [SunwellWoW/Sunwell-TBC-Bugtracker#1473]
Decription: While you standing ontop of gameobjects high up where you are unreacheable the mobs wont reset and run back.

How it works: If the mob cant reach you or deal damage to you it should reset or resist attacks so range cant kill them without taking any damage

How it should work: The mob atm just stand there and cant reach you becuase it cant find a path to the player.

 

Source (you should point out proofs of your report, please give us some source): 
![ezgif com-resize](https://user-images.githubusercontent.com/16453643/48505135-9cc04080-e846-11e8-8484-0ea53b34445b.gif)

**Comment by Kokaina** [comment]
I believe ur source is video from our beta. Do u have any proof to compare with?

**Comment by Kokaina** [comment]
Now they sometimes evades after ~15seconds and sometimes don't evade at all.

**Comment by Wojtyas** [comment]
Fixed & implemented.
