### ISSUE TITLE
[The Eye] High Astromancer Solarian

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1475]
- [x] Hunter can maintain sight on Solarian by using Hunter’s Mark while she is in vanish - shouldn't happen.
- [x] She casts Arcane Missiles at those who are affected by Wrath of the Astromancer debuff which K.Os them. She should cast that at random players but w/o this debuff.
- [x] Mark of Solarian debuffs should disappear upon player's death.
Proof at 4:55 when player dies and his Marks are gone - https://www.youtube.com/watch?v=6uGkhNzo7Zc
- [x] Solarian shouldn't reset his threat when passes to phase 2.
- [x] Solarian shouldn't be immune to taunt
- [x] Solarian in Void form is kiteable. He should move quite faster in order to avoid that.
- [x] Wrath of the Astromancer: the explosion deals 5400-6600 arcane damage to everyone in a 10-yard radius, and throws everybody affected by it high enough into the air for about 90% falling damage. Upon landing, the person with the debuff is **protected against falling damage**, while everybody else is usually killed or took mass of dmg due falling. Actually target with debuff also takes fall dmg.
https://youtu.be/Up9Qp1UijRM?t=125 - no fall dmg
- [x] Notsofamous: Oh yeah, in early versions of Solarian Ice block/Bubble/clos would instantly trigger the explosion of Wrath of the Astromancer rather than removing the effect.

**Comment by badmannerkid** [comment]
i'm not 100% sure on her not being kiteable in void form. depends on the version
