### ISSUE TITLE
Fear running characters off edges

### ISSUE THREAD

**Issue by Felynda** [SunwellWoW/Sunwell-TBC-Bugtracker#1476]
Decription: 
Got feared in Blades Edge Arena on top off the bridge. My character ran straight off.

How it works: 
While feared my character ran off the bridge.

How it should work: 
When feared your character should run around randomly but stop at the edges so it will not fall down.

Source (you should point out proofs of your report, please give us some source): 
Didn't record it happening unfortunately. To test just get feared near an edge.

Source of proof: warlock tbc pvp video: https://www.youtube.com/watch?v=86ZCLm910uo

**Comment by Wojtyas** [comment]
Fixed & implemented.

**Comment by Khryx** [comment]
Still the case, i was feared at the graveyard of WSG, and the fear (who doesn't break at all btw, even if u take a bunch of damage) make me fall down of the gy.
