### ISSUE TITLE
mobs perma evade if you shoot them while leashing

### ISSUE THREAD

**Issue by nickycakes** [SunwellWoW/Sunwell-TBC-Bugtracker#1481]
Decription: 
If you shoot a mob while it's leashing, it will reaggro you but still be evaded keeping you in combat and causing the mob to permanently follow you until you log off.

How it works: 

1. Shoot mob (did it with a hunter)
2. Run away until mob leashes
3. Shoot mob as it's pathing back to its spawn
4. mob will then run back to you and stay evaded

How it should work: 

1. Shoot Mob
2. Run away until mob leashes
3. Shoot mob as it's pathing back to spawn
4. Mob continues to evade until it is reset at its spawn

Source (you should point out proofs of your report, please give us some source): 

Gathered up most of the mobs in the starting zone
![image](https://user-images.githubusercontent.com/2413942/48519674-57306180-e8a0-11e8-93da-f83e15f28d00.png)

**Comment by notsofamous** [comment]
Duplicate: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1301
