### ISSUE TITLE
Mob perma evade

### ISSUE THREAD

**Issue by jackal111** [SunwellWoW/Sunwell-TBC-Bugtracker#1482]
Decription: 
Pulled a treant in sunstrider isle after playing the game for 10 min and it was permanently evading and not able to be reset. I had to alt f4 to reset the mob.

How it works: 
Check video link

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/nz6qf

**Comment by notsofamous** [comment]
Duplicate: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1301

**Comment by lukaasm** [comment]
It was the same source of the bug. Should be fixed now.
