### ISSUE TITLE
[Item] Oil of Immolation (8956)

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1484]
Shows up as a debuff when you use it instead of a buff.

http://db.hellfire-tbc.com/?item=8956
http://db.hellfire-tbc.com/?spell=11350

**Comment by Wojtyas** [comment]
Still nothing - checked yesterday.

![image](https://user-images.githubusercontent.com/22802214/48977698-8f555280-f09f-11e8-9d4b-175d0919e19f.png)
