### ISSUE TITLE
Heroic Mechnar - Pack chains

### ISSUE THREAD

**Issue by Vaanx** [SunwellWoW/Sunwell-TBC-Bugtracker#1489]
Decription: 
Sunseeker Engineer didn't pull with driller and other packs.

How it works: 
The Sunseeker Engineer didn't pull with the drillmaster and the other smaller mobs that throw bombs before the first boss.

How it should work: 
All 5 mobs should pull together.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
#628
