### ISSUE TITLE
[Quest] The Disruption Ends

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#1500]
Decription: 
looks like you forgot to implement this quest

How it works: 
"The Disruption Ends" is not implemented / quest is missing

How it should work: 
after finishing "Disrupt the Attacks", Thork should give you the follow up quest "The Disruption Ends"

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Thork

**Comment by neheri** [comment]
This quest works. I have completed it on my toon. Maybe you were too low level?

**Comment by FrauHolle86** [comment]
- refering to Bug Report #1499
- the quest exisit and works find, but should be the follow up quest of "Disrupt the Attacks"
- "Supplies for the Crossroads" should be a separate quest, not included in the quest chain
