### ISSUE TITLE
[Druid] Sharpened Claws

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1502]
Increases critical strike chance while in Bear, Dire Bear or Cat Form 2/4/6%.

- [ ] The talent is not applied after relogging.
Character has 29.84% crit without the talent, 35.84% with.
Before relog:
![Image](https://i.gyazo.com/4cc4232763a19191dbb4341c0afb4e7b.png)
After relog:
![Image](https://i.gyazo.com/d3ec4ff14bdc8a214ae26af589010328.png)

- [ ] The critical strike chance does not show up in the character pane when in cat/bear form.

**Comment by Kokaina** [comment]
Added to massive report.
