### ISSUE TITLE
[Druid] Predatory Instincts

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1503]
While in Cat Form, Bear Form or Dire Bear Form, increases your damage from melee critical strikes by 2/4/6/8/10% and your chance to avoid area effect attacks by 3/6/9/12/15%.

The minimum damage from critical strikes is not increased by 10%

Without talent:
![Image](https://i.gyazo.com/d3ec4ff14bdc8a214ae26af589010328.png)

With talent:
![Image](https://i.gyazo.com/d8673742431d80b300c3a0c98cf8700d.png)

In both cases the minimum damage was 306 from critical strikes. With the talent the minimum damage should be 10% higher.

**Comment by Kokaina** [comment]
Added to massive report.
