### ISSUE TITLE
Seal of blood makes damage 4 times after aura stacking

### ISSUE THREAD

**Issue by CreybeN** [SunwellWoW/Sunwell-TBC-Bugtracker#1506]
Decription: Seal of blood makes damage 4 times after aura stacking patch

How it works: Seal of blood makes damage 4 times after aura stacking patch

How it should work: do it once like before the patch xD

Source (you should point out proofs of your report, please give us some source):  https://cdn.discordapp.com/attachments/482245713112203266/512646597247631393/WoWScrnShot_111518_161354.jpg

**Comment by Kokaina** [comment]
Moved to massive raport including issues from morning aura merge.

**Comment by CreybeN** [comment]
123
