### ISSUE TITLE
 Priest/ Power Word: Shield by macro is stunning

### ISSUE THREAD

**Issue by sleezSunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#1507]
Decription: Priest/ Power Word: Shield spell is giving me stun. 

How it works:  Power Word: Shield is giving me stun from shadow tallents (Blackout) when im using it by macro.

How it should work:  Blackout is telling that only Shadow Damage spells have chance to stun but Power Word: Shield is a Discipline spell and it causes not damage.

Source (you should point out proofs of your report, please give us some source): The macro is 
#showtooltip Power Word: Shield
/cast [target=player] Power Word: Shield

**Comment by sleezSunwell** [comment]
But i see today everything is bugged so i dont know...

**Comment by Kokaina** [comment]
Moved to massive raport including issues from morning aura merge.
