### ISSUE TITLE
[Spell][Paladin] Fire/Frost/Shadow Resistance Aura, Devotion Aura

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#1510]
Decription: 
[Fire Resistance Aura Rank 4](https://tbc-twinhead.twinstar.cz/?spell=27153)
[Frost Resistance Aura Rank 4](https://tbc-twinhead.twinstar.cz/?spell=27152)
[Shadow Resistance Aura Rank 4](https://tbc-twinhead.twinstar.cz/?spell=27151)
[Devotion Aura Rank 8](https://tbc-twinhead.twinstar.cz/?spell=27149)

How it works: 
All resistans auras give 71 resistance value, devotion aura give 862 armor value.
![4124](https://user-images.githubusercontent.com/43764742/48565745-efaafe00-e901-11e8-8d34-d2258f1f9871.jpg)
![4214](https://user-images.githubusercontent.com/43764742/48565746-f0439480-e901-11e8-82af-2b1451f95f0c.jpg)
![124124](https://user-images.githubusercontent.com/43764742/48565748-f0439480-e901-11e8-86f6-752a054e6812.jpg)
![412412](https://user-images.githubusercontent.com/43764742/48565749-f0439480-e901-11e8-85f1-835ddf788377.jpg)

How it should work: 
Resistans auras should give 70 resistance, devotion should give 861 (without talent) armor value. 

Source (you should point out proofs of your report, please give us some source): 
In description

**Comment by Kokaina** [comment]
Moved to massive raport including issues from morning aura merge.
