### ISSUE TITLE
[Hunter] Tame Beast does not work

### ISSUE THREAD

**Issue by Scarith** [SunwellWoW/Sunwell-TBC-Bugtracker#1511]
Decription: 
It just doesn't work I tried it on a lot of different mobs and it's not working 

How it works: 
I tried Tame Beast on a whole bunch of different beasts in Outlands and even the ones on the starting zone and it's not working
How it should work: 
You press Tame Beast while targetting a tameable beast and after the channeling time is over it becomes your pet
Yesterday it was working perfectly (ish, some bugs like the range but I already reported that bug) I have no idea what changed but it's bugged now
Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_111518_100959](https://user-images.githubusercontent.com/45055496/48565887-31ff1b80-e8bf-11e8-8103-cc7a4cef813a.jpg)
![wowscrnshot_111518_101002](https://user-images.githubusercontent.com/45055496/48565889-31ff1b80-e8bf-11e8-81d7-707bf257a7b6.jpg)
![wowscrnshot_111518_092433](https://user-images.githubusercontent.com/45055496/48565952-4fcc8080-e8bf-11e8-8068-11ca0999d268.jpg)
![wowscrnshot_111518_092436](https://user-images.githubusercontent.com/45055496/48565953-4fcc8080-e8bf-11e8-9873-c647025377a8.jpg)
![wowscrnshot_111518_092539](https://user-images.githubusercontent.com/45055496/48565954-4fcc8080-e8bf-11e8-9b42-f6731143ae7a.jpg)
![wowscrnshot_111518_092542](https://user-images.githubusercontent.com/45055496/48565955-50651700-e8bf-11e8-883e-dc2b9126ada1.jpg)
![wowscrnshot_111518_092645](https://user-images.githubusercontent.com/45055496/48565958-50651700-e8bf-11e8-8ad5-0760ed424b5d.jpg)
![wowscrnshot_111518_092648](https://user-images.githubusercontent.com/45055496/48565959-50651700-e8bf-11e8-99af-7b4edbe92b66.jpg)
![wowscrnshot_111518_092921](https://user-images.githubusercontent.com/45055496/48565961-50fdad80-e8bf-11e8-8cd4-e19317eee577.jpg)
![wowscrnshot_111518_092923](https://user-images.githubusercontent.com/45055496/48565964-50fdad80-e8bf-11e8-819a-fca1c9d90840.jpg)
![wowscrnshot_111518_093113](https://user-images.githubusercontent.com/45055496/48565967-50fdad80-e8bf-11e8-8186-ae9f9896e7b5.jpg)
![wowscrnshot_111518_093116](https://user-images.githubusercontent.com/45055496/48565968-50fdad80-e8bf-11e8-88de-db9d8e2daa27.jpg)
![wowscrnshot_111518_093314](https://user-images.githubusercontent.com/45055496/48565969-51964400-e8bf-11e8-97d9-3fb4417bbd1a.jpg)
![Uploading WoWScrnShot_111518_093316.jpg…]()
![Uploading WoWScrnShot_111518_093516.jpg…]()
![Uploading WoWScrnShot_111518_093519.jpg…]()
![Uploading WoWScrnShot_111518_093627.jpg…]()
![Uploading WoWScrnShot_111518_093629.jpg…]()
![Uploading WoWScrnShot_111518_093714.jpg…]()
![Uploading WoWScrnShot_111518_093716.jpg…]()

**Comment by Scarith** [comment]
Sorry for not recording video don't have any programs to do that so what I did was take a screenshot at the last second of tame beast and then screenshot 1 second later (after it failed, it doesn't give me any message error or Failed Attempt or anything)

**Comment by Kokaina** [comment]
Moved to massive raport including issues from morning aura merge.
