### ISSUE TITLE
[Hunter] Mend Pet triggering Quick Shots

### ISSUE THREAD

**Issue by Scarith** [SunwellWoW/Sunwell-TBC-Bugtracker#1512]
Decription: 
Ability Mend Pet is trigerring Quick Shots buff from Improved Aspect of the Hawk

How it works: 
You can spam Mend Pet and get a proc of Quick Shots if you're in AotH 

How it should work: 
Quick Shots should only trigger from your normal ranged attacks (autoshots) and only then. No other abilities should trigger it

Source (you should point out proofs of your report, please give us some source): 
In this screenshot you can see my combat log and the only thing casted is Mend Pet, on the top right corner you can see the Quick Shots buff triggered
![captura de pantalla 2018-11-15 a la s 10 18 46 a m](https://user-images.githubusercontent.com/45055496/48566323-25c78e00-e8c0-11e8-85d8-06c675517a45.png)

**Comment by Kokaina** [comment]
Moved to massive raport including issues from morning aura merge.
