### ISSUE TITLE
[Hunter] The Beast Within talent not working

### ISSUE THREAD

**Issue by Scarith** [SunwellWoW/Sunwell-TBC-Bugtracker#1513]
Decription: 
The BM talent The Beast Within (you are affected by Bestial Wrath and turn red with increased damage) is not triggering

How it works: 
When casting BW your pet is affected, but you are not

How it should work: 
You should get The Beast Within talent when casting Bestial Wrath and cause 10% initial damage
I think this is not working because of the aura change in the morning

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_111518_120003](https://user-images.githubusercontent.com/45055496/48572191-57475600-e8ce-11e8-860c-c656a32fa8cb.jpg)
![wowscrnshot_111518_120012](https://user-images.githubusercontent.com/45055496/48572192-57475600-e8ce-11e8-9416-468d5b8594a5.jpg)

**Comment by Kokaina** [comment]
Moved to massive raport after today's aura stacking merge.

**Comment by Scarith** [comment]
It's working fine now
