### ISSUE TITLE
Chain lightning jumps consume Clearcasting charges

### ISSUE THREAD

**Issue by Felynda** [SunwellWoW/Sunwell-TBC-Bugtracker#1516]
Decription: 
Cast Chain Lightning on a bunch off mobs. Got a critical strike on a jump. Giving me clearcasting buff. But instantly charges are taken away because the Chain Lightning jumped to another mob.

How it works: 
Cast Chain Lightning on a bunch off mobs. Got a critical strike on the second jump. Giving me clearcasting buff. But instantly 1 charge was taken away because Chain Lightning jumped hit a third mob. If the first hit crits and the 2 jumps afterwards don't, you will get 0 charges of Clearcasting.

How it should work: 
Once any jump of Chain Lightning crits, Clearcasting should proc (this works.) But jumps should not consume Clearcasting procs since they're not seperate spells. It currently only works when the third hit crits. Then you will get the proper 2 charges.

Source (you should point out proofs of your report, please give us some source): 
Jumps should not consume Clearcasting procs since they're not seperate spells.

To test just spec clearcasting and start firing at the bunched up target dummies. You will notice as i described.

**Comment by Kokaina** [comment]
Moved to massive raport after today's aura stacking merge.
