### ISSUE TITLE
[Talent] Protection Warrior 'Improved Shield Bash'

### ISSUE THREAD

**Issue by Denziz** [SunwellWoW/Sunwell-TBC-Bugtracker#1517]
Decription: 
Hello! When I am using the Improved Shield Bash talent and I'm casting/using a spell, for example Bloodrage/Shield Block or just casting Battle Shout triggers the silence effect from that talent. This happens also when I switch stances so for example if I would switch from Defensive Stance to Arms Stance etc.

However, when I use Heroic Strike, Shield Slam, Thunder Clap (pretty much any offensive ability on a target) the target is getting the silence effect from the talent.

How it should work: 
Whenever you use Shield Bash on an enemy there is a 100% chance (if 2/2 Improved Shield Bash and 50% if 1/2 Improved Shield Bash) to silence the enemy for 3 seconds.

Source (you should point out proofs of your report, please give us some source): 
Here is a picture from the first example I used in the description, which is whenever I use a spell or cast a shout I get the silence effect on me.

Note, this happens when I cast any spell for example Bloodrage, Shield Block, Shield Wall, Stance switching, Berserker Rage, Mocking Blow, Spell Reflection.

Spells that does not trigger the silence on me: Last Stand, Trinkets (on use), Demoralizing Shout, Intimidating Shout, Taunt, Challenging Shout, 

![casted bloodrage silence effect](https://user-images.githubusercontent.com/5758943/48579340-7bca1f00-e91c-11e8-976e-6eedda36a171.PNG)

Here is another picture where I demonstrate the second example in the description text which was whenever I use any kind of offensive spell on the target, the target is silenced from the talent effect.

![shield slammed target silence effect](https://user-images.githubusercontent.com/5758943/48579787-bf715880-e91d-11e8-88d1-b62693f304d9.PNG)

Edit: This also works in PvP, I've tested it by dueling a few players both on the Horde and Alliance side.

**Comment by Kokaina** [comment]
Moved to massive raport after today's aura stacking merge.
