### ISSUE TITLE
Mana Regeneration

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1518]
It's only a guess but looks like players get same amount of regenerated mana in combat as out of combat so its possible that one part of MR doesn't work.

**Comment by neheri** [comment]
Should combat matter at all? In case of mana regeneration you take cast time into consideration. Druid and priest talents allow 30% of mana regenration **while casting**.

MP5 from items and talents also grant mana **while casting**. 

Let say somebody has 100 MP5 without cast and 20 MP5 while casting. If there's no cast player has 100 mana per 5 seconds, if continues to cast should get 20 mana per 5 seconds even while casting and after last cast is complete 5 timer starts after which regeneration is brought back to 100 MP5.

Combat should only be considered when it comes to health regeneration, mana has nothing to do with combat.
