### ISSUE TITLE
[Hunter][Talent] Quick Shots making autoshot slower

### ISSUE THREAD

**Issue by Scarith** [SunwellWoW/Sunwell-TBC-Bugtracker#1523]
Decription: 
Quick Shots talent is actually increasing the duration between my autoshots

How it works: 
When Quick Shots procs I am gaining .02 more attack speed (as in im .02 seconds slower
) instead of .028 seconds faster

How it should work: 
I should be gaining 0.028 seconds of faster attack speed (or just 0.02 sec) when Quick Shots procs

Source (you should point out proofs of your report, please give us some source): 
Bottom-left you can see my 1.92 s attack speed and on the top-right corner you can see there is no Quick Shots proc
![captura de pantalla 2018-11-15 a la s 5 47 49 p m](https://user-images.githubusercontent.com/45055496/48588987-000da980-e8ff-11e8-9114-53f5d08d09d0.png)
But here, bottom-left my speed is 1.94s even though you can see on the top right corner that Quick Shots is active
![captura de pantalla 2018-11-15 a la s 5 47 40 p m](https://user-images.githubusercontent.com/45055496/48589006-187dc400-e8ff-11e8-9aef-d148fe15f523.png)

**Comment by Scarith** [comment]
Don't know if this is necessary to say but Quick Shots is the buff you get from the talent Improved Aspect of the Hawk

**Comment by lukaasm** [comment]
![obraz](https://user-images.githubusercontent.com/48881/48642031-f5751200-e9db-11e8-947e-539061e65d1d.png)

**Comment by Scarith** [comment]
Just tested this - still adding speed of 0.02 to my attacks instead of lowering

**Comment by lukaasm** [comment]
Sorry, there was an issue and realm didn't update. On SSC PVP should work fine now, just tested it to be sure :)

**Comment by Scarith** [comment]
It's working!
