### ISSUE TITLE
[Hunter] [Spell] Frost Trap and Flare put you in combat

### ISSUE THREAD

**Issue by Scarith** [SunwellWoW/Sunwell-TBC-Bugtracker#1531]
Decription: 
When a mob gets Flared or Frost Trap'd it'll make you enter combat and have that mob (or mobs) attack you

How it works: 
Using Flare or Frost Trap and having anything trigger it will get you into combat with that mob 

How it should work: 
Neither of these abilities should trigger combat or make you enter combat at all, let alone have the mob come and attack you 

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/pOm5TeMg6zw

**Comment by Scarith** [comment]
Flare - working perfectly and as intended; doesn't put you in combat, cause aggro or anything.
Frost Trap -  It is still putting me in combat when triggered, I found another bug where Neutral mobs (AKA mobs with yellow bars that don't attack you) are NOT triggering ANY of the traps (Snake, Explosive, Fiery, Frost and Freezing) UNLESS the neutral mob is already attacking you (ex: I put down a frost trap and Distract Shot a boar into the trap, he triggers it then and only then. As for hostile mobs that do attack you they seem to be triggering Frost Trap, however, they are still coming for me and attacking me when they trigger it.

**Comment by lukaasm** [comment]
all mentioned issues should be fixed after next update

**Comment by Wojtyas** [comment]
Both spells are fixed & implemented (only SSC realm for now).
