### ISSUE TITLE
[Warlock][Minions/pets]Incorrect melee crit

### ISSUE THREAD

**Issue by doomnyx** [SunwellWoW/Sunwell-TBC-Bugtracker#1534]
Decription: Atm my succubus should have around 12,78% of melee crit chance (agility of minion + 5% from Demon Tactics 5/5). Same problem also exists for Felhunter.

How it works: It seems that only talent is working, as presented on the screenshot.
https://imgur.com/a/vvyvZEm

How it should work: Melee crit chance should be correct, based on warlock talents and minion's agility.

Source (you should point out proofs of your report, please give us some source):

**Comment by Silroth** [comment]
Did you test with other demon pets or is this an issue only for succubus?

**Comment by doomnyx** [comment]
https://imgur.com/a/ie8RtNV Felhunter's melee crit also incorrect.

**Comment by Silroth** [comment]
Retest with all pets and update the title and post please.

**Comment by doomnyx** [comment]
Actually, it seems like all pets have base crit chance, while neither minion's agility and talents are not modifying this stat at all. Gonna make complex report about that.

**Comment by Gelori** [comment]
Confirming the issue with Felguard aswell! Demon tactics doesn't work. I was mainly fighting mobs around 46-48 levels. So the crit chance should be at least equal to agility + talents Demon Tactics 3/5
6,88% + 3 = 9,88%, recount with >100 attacks shows 4,8%

[**FELGUARD Screenshot of recount +talents and Agility!**](https://imgur.com/JdcE690)
