### ISSUE TITLE
ghouls in raven hill cemetery often stuck next to the tombstones

### ISSUE THREAD

**Issue by Zerroc1** [SunwellWoW/Sunwell-TBC-Bugtracker#1535]
Decription: 
The Ghouls in raven hill cemetery often stuck at the big tombstones in this area

How it works: 
ghouls pathing is buggy necxt and they need up to 20 seconds to find away out of the BIG tombstones

How it should work: 
they should pass the tombstone like other objects

Source (you should point out proofs of your report, please give us some source):

**Comment by Zerroc1** [comment]
How it works:
ghouls pathing is buggy next to the stones and they need up to 20 seconds to find away out of the BIG tombstones

**Comment by Azathothh** [comment]
Please always try to add some screenshoot or video. It would be much easier to figure out what do you mean. Is it about issue on this screen?
![obraz](https://user-images.githubusercontent.com/37483678/48661118-57ca2300-ea6d-11e8-9a6d-870f2463f3ad.png)

**Comment by Azathothh** [comment]
[13:42:07]Map: [0, 0] - Eastern Kingdoms
[13:42:07]Zone: [10] - Duskwood
[13:42:07]Area: [2098] - Dawning Wood Catacombs
[13:42:07]Position: -10415.2, 399.517, 47.7974 | 4.34011
[13:42:07]Grid: 12, 32 | 7, 11
[13:42:07]Height: 
[13:42:07]  * ground: 46.8221
[13:42:07]  * floor: 47.7975
[13:42:07]  * allowed: 47.7975

**Comment by Wojtyas** [comment]
Fixed & implemented.
