### ISSUE TITLE
[Warlock][Talents][Minions/pets] Fel Intellect and Fel Stamina working only on warlock, but not on pet

### ISSUE THREAD

**Issue by doomnyx** [SunwellWoW/Sunwell-TBC-Bugtracker#1536]
Decription: Stats which should be modified by demonology talents are not modified at all.
http://db.hellfire-tbc.com/?spell=18750
http://db.hellfire-tbc.com/?spell=18744

How it works: Before putting points in talents: https://imgur.com/a/oOk5FgB
After putting points and relogging: https://imgur.com/a/MODt6D2

How it should work: Those talents should work on minions.

Source (you should point out proofs of your report, please give us some source):  It's obvious.

**Comment by Kokaina** [comment]
Moved to massive raport after recent aura stacking merge.
