### ISSUE TITLE
[Warlock][Spell] Health Funnel and talent Improved Health Funnel

### ISSUE THREAD

**Issue by doomnyx** [SunwellWoW/Sunwell-TBC-Bugtracker#1538]
Decription: 

- [x] Health Funnel is not taking any hp from Warlock, just adding hp to minion.
http://db.hellfire-tbc.com/?spell=27259

- [x] Improved Health Funnel is only working for initial health cost, but health transferred is the same as without 2/2 in this talent.
http://db.hellfire-tbc.com/?spell=18704

How it works: Works like a heal. Except initial cost (around 100hp), no health is transferred but minion gets healed out of the blue.
https://imgur.com/a/a1lz1p0
https://imgur.com/a/tbnRrWp

Talent does not work for funnel ticks.

How it should work: Health should be transferred from warlock properly, talent should increase health transferred on every tick.

Source (you should point out proofs of your report, please give us some source):   http://wowwiki.wikia.com/wiki/Health_Funnel?oldid=1586771

**Comment by doomnyx** [comment]
skill works, talent % increase is increased but not exactly 20%

**Comment by doomnyx** [comment]
Retested, same issue as here:
https://github.com/ccshiro/cc-buglist/issues/925

That means it works correct, can be closed.

**Comment by lukaasm** [comment]
k, closing
