### ISSUE TITLE
[Warlock][Talent] Unholy Power does not work

### ISSUE THREAD

**Issue by doomnyx** [SunwellWoW/Sunwell-TBC-Bugtracker#1539]
Decription: http://db.hellfire-tbc.com/?spell=18773
5/5 should increase melee of minions by 20%, Imp's Firebolt damage by 20%

How it works: Talent does not work, tested on Firebolt and Voidwalker/Felhunter/Succubus melee.

How it should work: It should increase dmg done from melee and Firebolt by 20%.

Source (you should point out proofs of your report, please give us some source): Tooltip

**Comment by zapsuu** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/595

Tested it 2 days ago and it worked.

**Comment by ZaoQ** [comment]
i believe all those issues are connected to auras changes, like demonic aegis talents doesnt work too, fel armor increases spell dmg by 99 instead of 130

**Comment by doomnyx** [comment]
after new aura system introduction, talents that increase minion damage does not work at all, my succubus always doing 50 dps, which is sooo off.

**Comment by doomnyx** [comment]
works now.
