### ISSUE TITLE
[Quest] - ID : 8470 can"t talk with quest npc + item drop chance too low

### ISSUE THREAD

**Issue by Hnidka** [SunwellWoW/Sunwell-TBC-Bugtracker#154]
Decription:  After u obtain (npc drop) quest item : Deadwood Ritual Totem ID : 20741 (btw i killed over 200mobs till i got drop can u check it ?) ( drop ratio should be about 2.50% ) 
 
                  It started Quest ID: 8470 (When u reach Neutral reputation with Timbermaw Hold its completed)
                   
                   

How it works: Can"t complete Quest because NPC Kernda GUID 39359 ENTRY 11558 ID 1997 is unspeakable (u just cant talk with her) (she have question mark)

How it should work:  When u reach Neutral reputation u can finish it 

Source (you should point out proofs of your report, please give us some source): 

http://wowwiki.wikia.com/wiki/Deadwood_Shaman 
http://wowwiki.wikia.com/wiki/Deadwood_Avenger
http://wowwiki.wikia.com/wiki/Deadwood_Den_Watcher
http://wowwiki.wikia.com/wiki/Deadwood_Ritual_Totem

https://www.wow-freakz.com/quest_helper.php?quest=8470

**Comment by Dootz** [comment]
"At war" check/uncheck to interact
