### ISSUE TITLE
[Warlock][Spell] Create Master Firestone

### ISSUE THREAD

**Issue by doomnyx** [SunwellWoW/Sunwell-TBC-Bugtracker#1540]
Decription: 

- [ ] Master Firestone procs too rarely, 200 melee attacks registered just 2 procs.
https://imgur.com/a/XjkFebD

- [ ] Talent 'Master Conjuror' works only with proc dmg, but not with adding fire spell damage. While it visually ads the correct damage in the Firestone tooltip, Fire Spell damage is increased like from the basic non-talented version.

How it works: It does not work correctly.

How it should work: Should work correctly, proc should be ppm based and should be vastly increased.

Source (you should point out proofs of your report, please give us some source): Tooltips
https://www.wowhead.com/item=22128/master-firestone-deprecated#comments

**Comment by Kokaina** [comment]
Moved to massive raport after recent aura stacking merge.

**Comment by doomnyx** [comment]
https://www.youtube.com/watch?v=i1IDWqHpHds

This movie is from vanilla times, but suggests Firestone having ~50% proc rate, so it's safe to put this value in formulas.

**Comment by doomnyx** [comment]
http://db.hellfire-tbc.com/?item=1254
http://db.hellfire-tbc.com/?item=13699
http://db.hellfire-tbc.com/?item=13700
http://db.hellfire-tbc.com/?item=13701
http://db.hellfire-tbc.com/?item=22128
