### ISSUE TITLE
T5 tuning

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1542]
### **Trash**

- [ ] **Coilfang Beast-Tamer** Entry 21221
HP: 425,000
Damage: 16,720 - 20,591
Armor: 7,089
Cleave for 135% damage

- [ ] **Serpentshrine Sporebat** Entry 21246
HP: 214,300
Damage: 8,149 - 10,084
Armor: 7,089
Spore Burst for 1400-1600 and DoT ticking 532-806

- [ ] **Coilfang Hate-Screamer** Entry 21339
HP: 265900
Damage: 8,811 - 10,985
Armor: 5,714
Sonic Scream for 4600-5360

- [ ] **Underbog Colossus** Entry 21251
HP: 1025000
Damage: 17,308 - 20,556
Armor: 7,387

- [ ] **Colossus Rager** Entry 22352
HP: 27,944
Damage: 1,671 - 1,985
Armor: 6,792

- [ ] **Colossus Lurker** Entry 22347
HP: 143,620
Damage: 14,165 - 16,824
Armor: 4,089

- [ ] **Purified Water Elemental** Entry 21260
HP: 10772
Damage: 782-992
Armor: 7,089

- [ ] **Tainted Water Elemental** Entry 21253
HP: 17950
Damage: 1260-1770
Armor: 7,089

- [ ] **Vashj'ir Honor Guard** Entry 21218
HP: 425500
Damage: 14,443 - 16,665
Armor: ?
Mortal Strike for 80% damage

- [ ] **Coilfang Priestess** Entry 21220
HP: 239300
Damage: 8,411 - 9,985
Armor: 5,714
Holy Smite for 3180-3850, Greater Heal for 40000-50000, Holy Fire for 2500 and 1300 ticks, Holy Nova for 4000 (on death)

- [ ] **Greyheart Technician** Entry 21263
HP: 39900
Damage: 2,266 - 2,691 
Armor: 7,089
Hamstring for 1800-2100

- [ ] **Coilfang Shatterer** Entry 21301
HP: 332500
Damage: 14,732 - 17,497
Armor: 7,089

- [ ] **Coilfang Frenzy** Entry 21508
HP: 81,000
Damage: 2,022 - 2,326
Armor: 6,792

- [ ] **Coilfang Serpentguard** Entry 21298
HP: 332500
Damage: 14,732 - 17,497
Armor: 7,089

- [ ] **Greyheart Nether-Mage** Entry 21230
HP: 265900
Damage: 8,411 - 9,985
Armor: 5,714
Rain of Fire ticking 2700-3000, Fireball for 2900-3700, Scorch for 2450-3050, Arcane Volley for 3800-4200, Arcane Lightning for 3100-3200, Frostbolt for 3200-4000, Cone of Cold for 3000-3700

- [ ] **Greyheart Tidecaller** Entry 21229
HP: 194900
Damage: 10,512 - 12,480
Armor: 5,714
Virulent Poison ticking 7200 stacking 3 times

- [ ] **Greyheart Skulker** Entry 21232
HP: 199472
Damage: 8800-12400
Armor: 5,349

- [ ] **Coilfang Fathom-Witch** Entry 21299
HP: 194900
Damage: 8,411 - 9,985
Armor: 5,414
Shadow Bolt for 2950-3250, Shadow Nova for 3300-5100

- [ ] **Serpentshrine Lurker** Entry 21863
HP: 194050
Damage: 16,716 - 19,852
Armor: 6,792
Poison Bolt Volley for 2600-2800 leaving DoT ticking 509-591

- [ ] **Rancid Mushroom** Entry 22250
HP: 69860
Damage: -
Armor: -
Spore Cloud for 1000-1300 with DoT 360-540 per stack stacking up to 5 times

- [ ] **Greyheart Shield-Bearer** Entry 21231
HP: 332500
Damage: 14,165 - 16,824
Armor: 7,089
Avenger's Shield for 3100-3900, Shield Charge targeted at furthest players for 3325-3675

- [ ] **Tidewalker Warrior** Entry 21225
HP: 332500
Damage: 8400-11800
Armor: 7,089
Bloodthirst for 10000-14000 and 5200-5800 heal, Uppercut for melee damage

- [ ] **Tidewalker Shaman** Entry 21226
HP: 194900
Damage: 6300-8800
Armor: 5,714
Lightning Shield for 1575-2025, Lightning Bolt for 2000-2400, Chain Lightning for 2000-2700

- [ ] **Tidewalker Hydromancer** Entry 21228
HP: 194900
Damage: 6300-8800
Armor: 5,714
Frostbolt 2700-3400, Frost Shock for 2400-2800, Frost Nova for 1750-2000

- [ ] **Tidewalker Depth-Seer** Entry 21224
HP: 194900
Damage: 7000-9500
Armor: 5,714
Tranquility ticking 5100-5900, Healing Touch for 11800-12000, Rejuvenation ticking 1616

- [ ] **Tidewalker Harpooner** Entry 21227
HP: 299000
Damage: 8000-10800
Armor: 7,089
Impale ticking 710-740

### **Bosses**

- [ ] **Hydross the Unstable** Entry 21216
HP: 3,700,000
Damage: 6,500 - 7,500
Armor: 7,700
Water Tomb for 900/tick, Vile Sludge for 500/tick

- [ ] **Tainted Spawn of Hydross** Entry 22036
HP: 64600 
Damage: 3,500 - 4,500
Armor: 7,089

- [ ] **Pure Spawn of Hydross** Entry 22035
HP: 64600 
Damage: 3,500 - 4,500
Armor: 7,089

- [ ] **The Lurker Below** Entry 21217
HP: 6323000 
Damage: 26,371 - 31,317
Armor: 7,700
Geyser for 3250-3690, Whirl for 4700-5370, Spout for 3238-3762, Water Bolt for 8750-11250

- [ ] **Coilfang Ambusher** Entry 21919
HP: 27,945
Damage: 5,170 - 6,138
Armor: 5,474
Spread shot 3500 damage

- [ ] **Coilfang Guardian** Entry 21873
HP: 116400
Damage: 16,716 - 19,852
Armor: 6,792
Hamstring for 2000-3500, Arcing Smash for 125% damage 

- [ ] **Leotheras the Blind** Entry 21215
HP: 4,494,000
Damage: 15,822 - 18,789
Armor: 7,700
Whirlwind for 3000 leaving DoT ticking for 2500, Chaos Bolt for 150 and +1675 fire damage taken debuff stacking up to 20 times

- [ ] **Greyheart Spellbinder** Entry 21806
HP: 191400 
Damage: 12,615 - 14,977
Armor: 5,714
Mind Blast for 3500-4000 (12yd AoE)

- [ ] **Inner Demon** Entry 21857
HP: 12,395
Damage: 3,084 - 3,625
Armor: 6,792
Shadow Bolt for 3000-4000

- [ ] **Fathom-Lord Karathress** Entry 21214
HP: 1821000 
Damage: 20,560 - 24,216
Armor: 6,200
Cataclysmic Bolt targeted at mana-users for 50% of their max health, Sear Nova 2900-3100

- [ ] **Fathom-Guard Tidalvess** Entry 21965
HP: 861600 
Damage: 22,076 - 26,209
Armor: 5,714
Frost Shock for 5400-6600, Spitfire Totem (2250-3450 damage and 25000 health), Earthbind Totem, Poison Cleansing Totem (both with 20k health)

- [ ] **Fathom-Guard Sharkkis** Entry 21966
HP: 861600 
Damage: 13,142 - 15,602
Armor: 5,714
Multi-Toss for 2500-4000, Leeching Throw 3150 health/mana over 12sec, Hurl Trident for 1000-1500 damage on random target

- [ ] **Fathom-Guard Caribdis** Entry 21964
HP: 861600
Damage: 13,142 - 15,602
Armor: 5,714
Healing Wave for 110000-140000, Tidal Surge for 1600-1900, Water Bolt Volley for 2800-3200

- [ ] **Fathom Sporebat** Entry 22120
HP: 179525
Damage: 14,958 - 17,766
Armor: 7,089
Knock Away for damage+30

- [ ] **Fathom Lurker** Entry 22119
HP: 179525
Damage: 14,958 - 17,766
Armor: 7,089
Knock Away for damage+30

- [ ] **Morogrim Tidewalker** Entry 21213
HP: 5691000
Damage: 28,128 - 33,404
Armor: 7,700
Tidal Wave for 3938-5062, Earthquake for 4500, Watery Grave for 5800-6400, Watery Globule explosion for 4000-6000 

- [ ] **Tidewalker Lurker** Entry 21920
HP: 29920
Damage: 2500-3600
Armor: 7,089
Carnivorous Bite ticking 208/stack 

- [ ] **Lady Vashj** Entry 21212
HP: 5,356,000
Damage: 24,449 - 29,020
Armor: 6,200
Entangle Ticking for 500, Shock Blast for 8325-9675, Static Charge for 1619-1882, Forked Lightning for 2313-2687, Shoot 20000-23000

- [ ] **Enchanted Elemental** Entry 21958
HP: 9980
Damage: -
Armor: 6,792

- [ ] **Tainted Elemental** Entry 22009
HP: 9980
Damage: -
Armor: -
Poison Bolt for 1885-2115 and DoT ticking 2000

- [ ] **Coilfang Elite** Entry 22055
HP: 344,650
Damage: 17,413 - 20,679
Armor: 6,792
Cleave for 125% damage, Hamstring for 20% damage

- [ ] **Toxic Spore Bat** Entry 22140
HP: 6,986
Damage: 557 - 662
Armor: 6,792
Toxic Spores for 2775-3225

- [ ] **Coilfang Strider** Entry 22056
HP: 344,650
Damage: 33,434 - 39,705
Armor: 6,792
Note: Mind Blast 2313-2687 damage

#

### Trash

- [ ] **Bloodwarder Legionnaire** Entry 20031
HP: 332450
Damage: 12,691 - 15,074
Armor: 7,089
Dual Wield, Bloodthirst for 120% damage and restoring 380-420 health, Cleave for 110% damage (on next swing), Channelled whirlwind for +120

- [ ] **Star Scryer** Entry 20034
HP: 265925
Damage: 8,411 - 9,985
Armor: 5,714
Arcane Blast for 3500-4500, Starfall for 1900-2100

- [ ] **Bloodwarder Vindicator** Entry 20032
HP: 425500
Damage: 16,820 - 19,969
Armor: 5,714
Flash of Light for 8750-11250

- [ ] **Bloodwarder Marshal** Entry 20035
HP: 546700
Damage: 14,769 - 17,540
Armor: 7,387
Channelled Whirlwind for +736, Uppercut for +250, Bloodthirst for 120% and healing 380-420

- [ ] **Bloodwarder Squire** Entry 20036
HP: 265925
Damage: 12,615 - 14,977
Armor: 5,714
Flash of Light for 8750-11250, Hammer of Wrath for 3719-4781 

- [ ] **Astromancer** Entry 20033
HP: 265925
Damage: 7,359 - 8,737
Armor: 5,714
Fireball Volley for 2125-2875, Fire Blast for 2700-3300, Blast Wave for 2400-2700

- [ ] **Phoenix-Hawk** Entry 20039
HP: 750,000
Damage: 7,802 - 9,265
Armor: 6,792
Dive for 1850-2150 (cast at further player), Wing Buffet for 1800-2200, Mana Burn for 1900-2100

- [ ] **Tempest Falconer** Entry 20037
HP: 332450
Damage: 9400-13200 (melee), 3300-4500 (shoot)
Armor: 6,147
Fire Shield for 523-577, Knockback, Immolation Arrow for 3700-4300

- [ ] **Phoenix-Hawk Hatchling** Entry 20038
HP: 129370
Damage: 7,802 - 9,265
Armor: 6,792
Wing Buffet for 1575-2025

- [ ] **Crystalcore Devastator** Entry 20040
HP: 1025000
Damage: 18,461 - 21,926
Armor: 7,387
Countercharge for 1497-1653 and counterspell component for 4050-4950, Charged Arcane Explosion for 5550-6450, Knock Away for 4000

- [ ] **Crystalcore Sentinel** Entry 20041
HP: 615000
Damage: 16,154 - 19,185
Armor: 7,387
Charged Arcane Explosion for 5550-6450, Overcharge for 14250-15750, Trample for melee damage

- [ ] **Tempest-Smith** Entry 20042
HP: 359050
Damage: 7,261 - 8,935
Armor: 5,955
Fragmentation Bomb for 2150-2850, Shell Shock for 2975-4025

- [ ] **Crystalcore Mechanic** Entry 20052
HP: 332450
Damage: 11,331 - 13,458
Armor: 7,089
Recharge golgems for 10000 a tick, Saw Blade for 1937-2364 and DoT ticking 807-892

- [ ] **Astromancer Lord** Entry 20046
HP: 437250
Damage: 10,701 - 12,703
Armor: 5,945
Fire Shield for 523-577, Dragon's Breath for 2313-2687, Fire Blast for 2700-3300, Fireball Volley for 2125-2875, Blast Wave for 3300-3750

- [ ] **Novice Astromancer** Entry 20044
HP: 58220
Damage: 5,555 - 7,777
Armor: 5,164
Fire Shield for 380-420, Rain of Fire ticking 1392-1611, Fireball for 1700-2300, Fire Nova for 1390-1590

- [ ] **Apprentice Star Scryer** Entry 20043
HP: 58220
Damage: 5,555 - 7,777
Armor: 5,416
Arcane Buffet for 250 and +50, Arcane Volley for 1400-1600, Arcane Explosion for 1425-1555, Arcane Shock for 1125-1325 and DoT ticking 200-300

- [ ] **Nether Scryer** Entry 20045
HP: 437260
Damage: 10,701 - 12,703
Armor: 5,954
Arcane Blast for 3500-4500

- [ ] **Crimson Hand Centurion** Entry 20048
HP: 215430
Damage: 8,411 - 9,985
Armor: 7,092
Arcane Flurry for 5525-7475

- [ ] **Crimson Hand Blood Knight** Entry 20049
HP: 425500
Damage: 8,411 - 9,985
Armor: 7,092
Hammer of Wrath for 3719-4781, Renew ticking 1200, Flash of Light for 11375-14625

- [ ] **Crimson Hand Battle Mage** Entry 20047
HP: 299200
Damage: 8,411 - 9,985
Armor: 5,714
Blizzard for 2375-2625, Frost Attack for 22000-23000 (20s cooldown), Cone of Cold for 2187-2812, Frostbolt Volley for 2125-2875

- [ ] **Crimson Hand Inquisitor** Entry 20050
HP: 437260
Damage: 8,411 - 9,985
Armor: 6,314
Mind Flay ticking 2000, Shadow Word: Pain ticking 3500

### **Bosses**

- [ ] **Al'ar** Entry 19514
HP: 3377421 
Damage: 20,444 - 23,999
Armor: 7,700
Flame Buffet for 1750-2250 and stacking debuff for 10% fire damage taken, Flame Quills for 6562-8438, Meteor for roughly 150-160k (split between all units, including snake trap), Rebirth for 4375-5625, Flame Patch for 2187-2812 and stacking debuff for 10% fire damage taken

- [ ] **Ember of Al'ar** Entry 19551
HP: 139720
Damage: 6,294 - 6,438
Armor: 6,792
Ember Blast for 7000-9000 upon death

- [ ] **Void Reaver** Entry 19516
HP: 5,007,750
Damage: 19,560 - 23,216
Armor: 8,800
Pounding for 1350-2250, Arcane Orb for 4675-6325, Knock Away for damage+30

- [ ] **High Astromancer Solarian** Entry 18805
HP: 5323000
Damage: 13,584 - 16,123
Armor: 6,200
Arcane Missiles for 3500, Blinding Light for 2400-3800, Void Bolt for 4394-5106 (P2)

- [ ] **Solarium Agent** Entry 18925
HP: 34930
Damage: 2,511 - 2,933
Armor: 6,400

- [ ] **Solarium Priest** Entry 18806
HP: 129150
Damage: 800-1100
Armor: 6,200
Holy Smite for 775-1075, Greater Heal for 23125-26875

- [ ] **Thaladred the Darkener** Entry 20064
HP: 756,000
Damage: 21,096 - 25,053
Armor: 7,684
Rend Ticking 2250/stack, Psychic Blow for 4375-5625

- [ ] **Lord Sanguinar** Entry 20060
HP: 552,000
Damage: 18,752 - 22,269
Armor: 7,684

- [ ] **Grand Astromancer Capernian** Entry 20062
HP: 562,000
Damage: 5,508 - 6,623
Armor: 3,878
Fireball for 5525-7475, Conflagration ticking 900, Arcane Burst for 2475-3025, Shadow Bolt for 5875-7125

- [ ] **Master Engineer Telonicus** Entry 20063
HP: 754,000
Damage: 13,383 - 14,383
Armor: 7,684
Bomb for 6375-8625 

- [ ] **Infinity Blades** Entry 21271
HP: 349298
Damage: 9,999 - 12,221
Armor: 6,792

- [ ] **Devastation** Entry 21269
HP: 407516
Damage: 16,716 - 19,852
Armor: 6,792
Whirlwind for +300

- [ ] **Warp Slicer** Entry 21272
HP: 465733
Damage: 8,358 - 9,926
Armor: 6,792
stacking Rend for 437-563

- [ ] **Cosmic Infuser** Entry 21270
HP: 465733
Damage: 8,358 - 9,926
Armor: 6,792
Holy Nova for 875-1125 and heal for 5 times that damage, Heal for 32375-37625

- [ ] **Phaseshift Bulwark** Entry 21273
HP: 523950
Damage: 7,998 - 8,887
Armor: 12,792
Shield Spike for 1087

- [ ] **Staff of Disintegration** Entry 21274
HP: 291085
Damage: 8,358 - 9,926
Armor: 6,792
Frostbolt for 2975-4025, Frost Nova for 1387-1916

- [ ] **Netherstrand Longbow** Entry 21268
HP: 349298
Damage: 8,358 - 9,926
Armor: 6,792
Multi-Shot for 3500-4500

- [ ] **Kael'thas Sunstrider** Entry 19622
HP: 6070000
Damage: 24,451 - 29,021
Armor: 6,200
Arcane Disruption for 1750-2250, Fireball for 18000-22000, Pyroblast for 45000-55000, Nether Beam for 2150-2150, Flame Strike for ~120k in 6yd AoE and debuff ticking 3000 at 10yd

_Shock barrier absorb would need to be increased._

- [ ] **Phoenix** Entry 21362
HP: 291083
Damage: 5,572 - 6,617
Armor: 6,792
Phoenix egg with 116433 health upon death

**Comment by Kokaina** [comment]
Well tuned sir.
