### ISSUE TITLE
Well Fed removed by drinking

### ISSUE THREAD

**Issue by Arom** [SunwellWoW/Sunwell-TBC-Bugtracker#1544]
Description: 
Well Fed buff is being removed by drinking. Also, when eating and drinking, once well fed is granted, drinking is suspended.

How it works: 
Eat buff food (Tested using Ravager Dog), wait for Well Fed buff, start drinking (Tested using Star's Tears), Well Fed disappears.

Also, when eating and drinking at the same time (Ravager Dog + Star's Tears in my case), once Well Fed is granted from food, drinking is suspended.

How it should work: 
Well fed should not be removed by drinking, and it should not suspend drinking when its granted.

Source (you should point out proofs of your report, please give us some source):

**Comment by zapsuu** [comment]
I tried another foods and drinks and this is the same problem. No matter do you gain buff, move on and try then drink, Well feed will dissapper.

I tried do it in second way, first I start drink, then use any feed, when we get Well Feed buff the drinking dissapper.

**Comment by zapsuu** [comment]
Works good.

**Comment by Arom** [comment]
123
