### ISSUE TITLE
Reduction/Increase damage buffs/debuffs

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#1546]
Decription: 
I saw this while affected  by Resurrection Sickness (reduce all dmg and stats by 75%).

How it works: 
It's reduce dmg by 75% twice in some situations.
For example: paladin Seal of Blood. Damage of the seal is 35% normal weapon damage, but while sickness damage of weapon is reduce by 75%, so the seal damage is reduce too, but at this moment damage seal is reduce by next 75%.
I think this bug can works also in second way, when we got increasing damage buffs/debuffs (like on Netherspite).

How it should work: 
The seal should be reduce once.

Source (you should point out proofs of your report, please give us some source): 
Below damage without buffs and sickness:
![bez sick sob](https://user-images.githubusercontent.com/43937876/48638279-6dd5d600-e9d0-11e8-9b2c-ac8d503f99e7.jpg)
![bez sick melee](https://user-images.githubusercontent.com/43937876/48638291-73332080-e9d0-11e8-865c-bc783ef8bcbc.jpg)

Here damage with Sickness:
![wowscrnshot_111618_180036](https://user-images.githubusercontent.com/43937876/48638366-aa093680-e9d0-11e8-8749-71654a3197c4.jpg)
![wowscrnshot_111618_180037](https://user-images.githubusercontent.com/43937876/48638368-ab3a6380-e9d0-11e8-962f-06199c207ec8.jpg)

Without sickness:
Seal of Blood - max 527 non-crit
Melee - max 767 non-crit

With sickness:
Seal of Blood - max 24 non-crit
Melee - max 197 non-crit

Melee: 197 / 767 * 100% = 25,68% (reduction 74,32%) = OK
Seal of Blood: 24 / 527 * 100% = 4,55% (reduction 95,45%) = BUG
4,55% * 4 = 18,20%

I think, the problem with difference could make by talent Vengeance (+15% physical and holy dmg). Weapon dmg is increased and then holy SoB damage is increased.

The same problem can be with warrior skills (Whirlwind, maybe Heroic Strike), Seal of Command (retri pala), Lightning Overload (elemental shammy talent), Stormstrike (shaman enh), rogue skills (Hemorrhage, Sinister Strike, Mutilate, Backstab).

**Comment by zapsuu** [comment]
Works like before. Still 17 damage from SoB on Sickness. Same eq.

**Comment by lukaasm** [comment]
Ok we fixed a general issue with DMG scaling, forgot to check SoB which uses different custom dmg calculations

**Comment by Wojtyas** [comment]
@zapsuu can you retest it please?
