### ISSUE TITLE
Quivers and Serpent's Swiftness Haste Bonus Interaction Incorrect

### ISSUE THREAD

**Issue by YoshGit** [SunwellWoW/Sunwell-TBC-Bugtracker#1549]
Description: 
Haste bonus from quivers and serpent's swiftness are being added together rather than multiplied together.

Sunfury Bow Of The Phoenix (2.9 speed), Quiver of the Night Watch (11% haste), and Serpent's Swiftness (20% haste) is used in the examples below.

How it works: 
Final speed = 2.21
2.21 = 2.9 / (1+0.11+0.20)

How it should work: 
Final speed = 2.18
2.18 = 2.9 / (1.11 * 1.2)

Source (you should point out proofs of your report, please give us some source): 
http://wow.allakhazam.com/wiki/Haste_%28WoW%29

**Comment by lukaasm** [comment]
No, they are not added issue was related to all modifiers being reduced by -1 which gave:
2.21 = 2.9 / (1.10 * 1.19)

Should be resolved after update

**Comment by Piootrek** [comment]
Fixed
