### ISSUE TITLE
[Quest] Jungle Secrets ID 215 

### ISSUE THREAD

**Issue by retkingjr** [SunwellWoW/Sunwell-TBC-Bugtracker#155]
Decription: 
Private Thorsen(738) STV quest event not triggering

How it works: 
Private Thorsen is offering the quest without having to go through with the event fighting the kurzen boys

How it should work: 
Private Thorsen should pat down from rebel camp, and fight some kurzen badboys and then u get teh quest

Source (you should point out proofs of your report, please give us some source): 
https://classicdb.ch/?quest=215

**Comment by Dootz** [comment]
fixed, he'll start his escort every 10-15 minutes. If you manage to defend him from ambush he'll offer you a quest. After some time ~2 minutes he'll go back to his spawn point and to get this quest you'll need to escort him again.

**Comment by nimeral** [comment]
Idk, I've just taken Jungle Secrets without fighting anyone. Seems broken.
