### ISSUE TITLE
Issue with charge/intercept range, related to tauren range and spell leeway

### ISSUE THREAD

**Issue by SuddenDeath** [SunwellWoW/Sunwell-TBC-Bugtracker#1551]
Decription: 
range issue with charge/intercept-like spells, involving tauren range + leeway.

How it works: Can't charge when tooltip/client says you should.
https://streamable.com/4edos - example.

How it should work: Should be able to charge when tooltip/client allows you to.
https://streamable.com/fg8zr - Other spells seem to function correctly.
Probably related to pathing part of charge spell that somehow doesn't allow the spell to go through at the correct range. I remember reporting this specific bug with charge-spells on Warmane TBC before too.

**Comment by Wojtyas** [comment]
Fixed & implemented. You are able to use Charge always in proper range (LoS is exception).
