### ISSUE TITLE
[Talent][Mage] Arcane Potency

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#1552]
Decription: 
[Arcane Potency](http://db.hellfire-tbc.com/?spell=31573)

How it works: 
The talent works during proс clearcasting, and now during clearcasting it reduces crit chance by 1%.
![wowscrnshot_111718_005324](https://user-images.githubusercontent.com/43764742/48649647-f6b63700-e9fb-11e8-9b3e-b9d0427cbe21.jpg)
![wowscrnshot_111718_005321](https://user-images.githubusercontent.com/43764742/48649656-fc138180-e9fb-11e8-8a49-99964eeeb988.jpg)

How it should work: 
During proс clearcasting, crit chance should increase by 30% for next spell.

Source (you should point out proofs of your report, please give us some source): 
In description.

**Comment by zapsuu** [comment]
Works good. Now when I have 3% crit, and got Arcane Potency I have 33% crit.
