### ISSUE TITLE
Fulgorge not attackable

### ISSUE THREAD

**Issue by sharkman800** [SunwellWoW/Sunwell-TBC-Bugtracker#1556]
Decription:  Fulgorge (rare mob in hellfire) moves underground and emerges when triggering combat, but then immediately goes back underground. Cannot attack this mob, and even if you do it cancels combat instantly.

How it works: Walk up the Fulgorge and he pops out of the ground but then goes back under and continues his pat. He will continue to pop up for a second or so but always goes back underground.

How it should work: Fulgroge should pop out of the ground and then proceed to attack you while staying above the ground.

Source (you should point out proofs of your report, please give us some source): I was walking around his spawn area and he popped out but was not attackable.

**Comment by neheri** [comment]
Exactly same happens with Marauding Crust Burster. They look the same but are smaller and normal NPCs.

Surprisingly there's another NPC which looks the same - Tunneler - and this one works perfectly.
