### ISSUE TITLE
Shaman totem 

### ISSUE THREAD

**Issue by ahmetcizmecioglu** [SunwellWoW/Sunwell-TBC-Bugtracker#1557]
Decription: Wrath air totem rank 1 doesnt work

How it works:  İt gives 120 healing and 0 spell damage

How it should work: It should give 120 healing + 120 spell damage

Source (you should point out proofs of your report, please give us some source):  https://imgur.com/a/3KPKoia / https://imgur.com/DHjuE1h

**Comment by Wojtyas** [comment]
Fixed & implemented.
