### ISSUE TITLE
[Chain-Quest] The Cipher of Damnation

### ISSUE THREAD

**Issue by Adamsek** [SunwellWoW/Sunwell-TBC-Bugtracker#156]
- [ ] **Quest: I Was A Lot Of Things...**
How it works: Shadowmoon Tubers are laying on the ground, easy to collect
How it should be: You should use your **Oronok's Boar Whistle** while standing on a tuber to call a Domesticated Felboar who will dig whole tuber up.

https://www.youtube.com/watch?v=5Tdchy-zSY4
https://www.wowhead.com/quest=10514/i-was-a-lot-of-things

- [x] Missing 14 of Domesticated Felboars in this location, neutral boars,

https://www.wowhead.com/npc=21195/domesticated-felboar

![wowscrnshot_081618_173141](https://user-images.githubusercontent.com/42385556/44297525-5f91f400-a2d3-11e8-8db8-94332609c196.jpg)

- [x] **The Cipher of Damnation - Grom'tor's Charge**
How it works: You can open any chest without key to find first fragment inside.
How it should works: You need to drop coilskar key from nearby Nagas (keys are present in loot), to open chests, 1 key for 1 chest.

http://db.hellfire-tbc.com/?quest=10522

![wowscrnshot_081618_173636](https://user-images.githubusercontent.com/42385556/44297589-535a6680-a2d4-11e8-8c7d-71f8d785d1ba.jpg)

- [x] Missing 2 out of 10 **Coilskar Waterkeeper** in there and what's more, 5 of them are just not interactable like this:

![wowscrnshot_081818_104650](https://user-images.githubusercontent.com/42385556/44297654-67529800-a2d5-11e8-936c-c79054401f6e.jpg)

https://www.wowhead.com/npc=19789/coilskar-waterkeeper

- [x] Missing 17 out of 23 **Coilskar Siren** in the area

https://www.wowhead.com/npc=19768/coilskar-siren

- [x] **Quest: The Cipher of Damnation - Ar'tor's Charge**
How it works: After taking the quest you can just kill Veneratus the Many and collect an item.
He spawns here:

![wowscrnshot_081618_174204](https://user-images.githubusercontent.com/42385556/44297706-4b032b00-a2d6-11e8-8ce1-00352795de3a.jpg)

How it should work: After taking the quest, **Spirit Hunter** https://www.wowhead.com/npc=21332/spirit-hunter#abilities is summoned as a companion who can attacks minions and you should run with him somewhere here:
![wowscrnshot_081618_174325](https://user-images.githubusercontent.com/42385556/44297720-7e45ba00-a2d6-11e8-85c2-fc4a2d22e712.jpg)

then Veneratus the Many should appear if you have your **Spirit Hunter** with you.

https://www.youtube.com/watch?v=XX_BN6eQExk

http://db.hellfire-tbc.com/?quest=10540

- [x] **Quest: To Catch A Thistlehead**
How it works: You need to kill **Envoy Icarius** and collect an item**
How it should work: You need to place **Bundle of Bloodthistle** at the end of the bridge, then **Envoy Icarius** should appear and walk towards **Bundle of Bloodthistle** with his bodyguard and do the quick talk with him, after it you can finally kill him.

https://www.wowhead.com/npc=21410/blood-lord-zarath
https://www.youtube.com/watch?v=qyiS0FaqjtA
http://db.hellfire-tbc.com/?quest=10570

- [x] You can't use your **Bundle of Bloodthistle**
![wowscrnshot_081618_174935](https://user-images.githubusercontent.com/42385556/44297834-a33b2c80-a2d8-11e8-838d-cda4fd04b62b.jpg)

- [x] **Quest: The Cipher of Damnation - Borak's Charge**
How it works: You need to kill **Ruul the Darkener** and collect an item.
How it should works: You need to kill **Ruul the Darkener** who should fly and walk/patrol path like on the map here: ![nowy obraz mapy bitowej](https://user-images.githubusercontent.com/42385556/44297922-e649cf80-a2d9-11e8-8177-026d59a7a843.jpg) intead of patrolling he stands still:

![wowscrnshot_081618_175513](https://user-images.githubusercontent.com/42385556/44297880-45f3ab00-a2d9-11e8-9226-b4a464b427b2.jpg)

- [x] **Ruul the Darkener** doesn't use any of his abilities: https://www.wowhead.com/npc=21315/ruul-the-darkener#abilities

- [x] **Cyrukh the Firelord** (The Cipher of Damnation quest) doesn't use any of his abilities: https://www.wowhead.com/npc=21181/cyrukh-the-firelord#abilities

**Comment by Azathothh** [comment]
There's also RP event with Gul'dan missing in The Cipher of Damnation id 10588
https://www.youtube.com/watch?v=dn9Yuy00hZg

**Comment by Azathothh** [comment]
Also Cyrukh the Firelord can be summoned multiple times by same person and spawn lots of them.
