### ISSUE TITLE
[Spell] Channeled skills cancel when you kill a mob with it / you drop combat

### ISSUE THREAD

**Issue by Trolltilla** [SunwellWoW/Sunwell-TBC-Bugtracker#1561]
Decription: 
When you kill a mob while channeling blizzard (for example) the spell doesn't finish but cancels instantly
Also when you do rain of fire on combat dummies in tanaris from far away (probably works with blizzard too) the spell cancels
How it works: 
above description

How it should work: 
The blizzard cast should continue even if you kill a mob with it
Rain of fire should continue on the dummies even if they are far away from you and you channel the spell on them

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Proofs? I think you might be wrong.

**Comment by Trolltilla** [comment]
> Proofs about the first one? I think you might be wrong.

Just pull a mob and kill it with blizzard. Can't take a video atm but should be easy to replicate.

**Comment by akrom23** [comment]
Okay.

**Comment by Wojtyas** [comment]
Fixed & implemented.
