### ISSUE TITLE
[Core] Weird Animation in Ironforge

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1562]
Decription: 
Same issue like in https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1458 
EDIT: It appears, this animation only happens on the main squares in Ironforge/Stormwind(not sure bout other cities). It looks like some kind of Midsummer Festival animation.
How it works: 
Like in the issue, difference is, it works like that in Ironforge, main square(before the bank).

How it should work: 
The characters shouldnt do that, its annoying.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Caused by [Fire Festival Fury Trap] - 181431.
