### ISSUE TITLE
[Mage] [Spell] Ice / Frost / Molten armor issues with Clearcasting

### ISSUE THREAD

**Issue by Trolltilla** [SunwellWoW/Sunwell-TBC-Bugtracker#1564]
Decription: 

The 3 mage armor procs grant / consume clearcasting when someone hits you

How it works: 

Any of the 3 armors can proc clearcasting when they apply their debuff to the target that hits the mage
The proc also consumes clearcasting when someone hits you

How it should work: 

Ice / Frost armor (not sure about molten because it actually does dmg to the enemy on hit) should not give or consume clearcasting procs when hit

Source (you should point out proofs of your report, please give us some source): 

Can't find proof but it clearly states on Arcane Concentration that it gives you chance to enter clearcasting state after any damage spell hits a target.

**Comment by Wojtyas** [comment]
- [ ] Clearcasting also proc when u cast Arcane Explosion (w/o hit anyone). It should proc only on hit.

**Comment by baade123** [comment]
also clearlasting goes away on secondary arcane missles , wrong.
