### ISSUE TITLE
weapon skill in "Ghost Wolf"

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#1569]
Decription: 
- i am lvl 23 atm and got a new 2h axe (1 of 115 skill)
- i am missing alot of hits regarding my non existing weapon skills (skilling up is to slow imo), which is fine
- BUT when i switch into Ghost Wolf I hit every single hit like i would be max weapon skill already
- also when i am in Ghost Wolf, i am not getting any weapon skill points

How it works: 
- see description

How it should work:
- beeing in Ghost Wolf or not shouldn't make any differance in weapon skilling

**Comment by notsofamous** [comment]
Works the same way as druid forms, don't need weapon skill to attack in ghost wolf. Thus you should not gain any weapon skill when you attack in ghost wolf. (Imagine a cat druid without any attacks)

"Attack with a bite attack (damage and attack speed depend on what weapon the shaman has equipped) even if you have 1 weapon skill in wolf form you will have full skill. "
http://vanilla-wow.wikia.com/wiki/Ghost_Wolf

**Comment by FrauHolle86** [comment]
thanks, my bad - can be closed
