### ISSUE TITLE
[Dungeon] Shattered Halls Normal

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#157]
Trash mobs:

- Shattered Hand Savage missing weapons 
![image](https://user-images.githubusercontent.com/42102450/44297797-eba61a80-a2d7-11e8-9b3f-71c001311a17.png)
 and Dual Wield ability.
Base damage should be 1127-1591.
 When engaged they spam their Slice and Dice making it have almost 90% uptime, Slice and Dice should last 8 seconds and be used every 20 seconds. They are spamming Deathblow which shouldnt be used until they are at low health (it should be used after dropping below 25% and Enraging). They properly Enrage at 25% but right now instead of using it once they are spamming it non-stop like crazy.

- Shattered Hand Legionnaire missing offhand weapon 
![image](https://user-images.githubusercontent.com/42102450/44297913-c5817a00-a2d9-11e8-8bc9-01b99751603a.png) and Dual Wield ability.
Base damage should be 1262-1785.
 When engaged right now they do nothing but autoattack, they should provide an aura called Aura of Discipline to nearby units (Spell ID 30472), Pummel casters that are in melee range and should Enrage at 25%. They should have RP events where they yell orders to other orcs depending on situation which is shown here https://wow.gamepedia.com/Shattered_Hand_Legionnaire

- Shattered Hand Sentry missing shield in offhand 
![image](https://user-images.githubusercontent.com/42102450/44298047-4ccfed00-a2dc-11e8-8fc5-95f6e73e6771.png)
Base damage should be 1127-1591.
When engaged they use their abilities but their Charge isnt working properly, it stuns and damages from range but they slowly walk instead of charging/intercepting the target.

- Shattered Hand Heathen missing weapons 
![image](https://user-images.githubusercontent.com/42102450/44298081-ffa04b00-a2dc-11e8-8c70-08da236c349f.png) and Dual Wield ability.
Base damage should be 1014-1431.
When engaged they use their abilities properly but uptime should be checked. Bloodthirst should be used every 10 seconds and they should Enrage at 25%.

- Shattered Hand Brawler Base damage should be 1177-1664. 
When engaged they use their abilities properly.

- Shadowmoon Acolyte Base damage should be 916-1330.
When engaged they use Mind Blast and Power Word Shield. During combat they should also buff their group with Resist Shadow which gives 105 shadow resistance and use Prayer of Mending (Heals for 5k crits for 7500) and use Power Word Shield on allies aswell.

- Shattered Hand Sharpshooter missing weapon 
![image](https://user-images.githubusercontent.com/42102450/44298318-13e64700-a2e1-11e8-8820-014237575045.png)
Base damage should be 1127-1591 (Thats their melee, ranged damage from Shoot ability is roughly ~400 lower).
When engaged they use Incendiary Shot and Viper Sting. Viper Sting should be used only in heroic mode on players with mana pool, in normal they should use Scatter Shot on person who is in their melee range and has highest threat (usually its the tank) and then switch target to other players. They should have ability called Shoot which is basicly their ranged autoattack.

- Shattered Hand Reaver missing weapon 
![image](https://user-images.githubusercontent.com/42102450/44298386-8d326980-a2e2-11e8-8812-311bc1943652.png)
Base damage should be 1127-1664.
When engaged uses all abilities properly.

- Shadowmoon Darkcaster base damage should be 916-1330.
When engaged uses all abilities properly, only issue is sometimes they interrupt their Shadow Bolt cast to use Rain of Fire, they should finish casting Shadow Bolt and then use Rain of Fire.

- Shattered Hand Houndmaster missing both melee and range weapons 
![image](https://user-images.githubusercontent.com/42102450/44298509-a0463900-a2e4-11e8-8d60-af24d254c27d.png) 
![image](https://user-images.githubusercontent.com/42102450/44298512-a5a38380-a2e4-11e8-8aba-fcef30245c4e.png) 
![image](https://user-images.githubusercontent.com/42102450/44298519-c79d0600-a2e4-11e8-95b4-9325a3775916.png)
Base damage should be 1177-1664.
When engaged uses Volley and Impaling Bolt but does not cast Shoot ability which is a ranged autoattack for this mob. Shoot ability damage should be around 400 less damage than his normal melee attack.

- Rabid Warhound base damage should be 298-419.
When engaged uses Carnivorous Bite but not Furious Howl. Furious Howl should be used every 10 seconds.

- Creeping Oozeling base damage should be 121-171.
When engaged only autoattacks, should have Sticky Ooze ability (Spell ID 30494)

- Creeping Ooze base damage should be 1127-1591.
When engaged uses Sticky Ooze ability properly.

- Fel Orc Convert base damage should be 435-634.
When engaged uses all abilities properly.

- Shattered Hand Assassin missing weapons 
![image](https://user-images.githubusercontent.com/42102450/44298862-8f4cf600-a2eb-11e8-80a5-24c62e20ae37.png) and Dual Wield ability.
Base damage should be 1010-1452.
When engaged they only use Backstab ability, if they attack first from Stealth they should Sap one player and then use Cheap Shot on other player. They should also have Wound and Crippling Poison.
NOTE: After leaving Grand Warlock Nethekurse chamber you should encounter them in stealth at 33.5, 51.6 , after  Shattered Hand Blood Guard/Blood Guard Porung you should encounter them again at 34.6, 13.8, again at 48.4, 14 and again at 53.8, 18.6 and through the hall there are many of them at random spawn points between Warbringer's Ring and Hall of Blades. 
![image](https://user-images.githubusercontent.com/42102450/44299166-3da76a00-a2f1-11e8-930c-36ec05748f8b.png)

- Shattered Hand Zealot missing weapon 
![image](https://user-images.githubusercontent.com/42102450/44298895-2d40c080-a2ec-11e8-8b5c-27cf55ddea9a.png) 
Base damage should be 242-341.
When engaged they use their abilities properly.

- Shattered Hand Scout missing weapon 
![image](https://user-images.githubusercontent.com/42102450/44298944-0b940900-a2ed-11e8-8f1d-818296ba0662.png)
As you approach the gauntlet after Grand Warlock Nethekurse, this mob should shout out a warning "Invaders have breached the defenses!" then run to the end of the hallway toward and Blood Guard Porung and despawn. Shattered Hand Zealots that are linked to him should move forward and attack you. Currently the fires are already on the ground and they deal no damage, there should be animation from Shattered Hand Archers casting fire arrows into the places where the fire should spawn and if a player enters that area it should deal fire damage

- Shattered Hand Archer missing their melee and ranged weapons 
![image](https://user-images.githubusercontent.com/42102450/44299028-73971f00-a2ee-11e8-8bee-958490fc4363.png) 
![image](https://user-images.githubusercontent.com/42102450/44299029-77c33c80-a2ee-11e8-9a43-616ad033cb8f.png)
Base damage should be 967-1365.
When engaged they use their abilities such as Shoot and Multishot properly.

- Shattered Hand Blood Guard missing weapon 
![image](https://user-images.githubusercontent.com/42102450/44299077-71819000-a2ef-11e8-8222-a45e591698cb.png)
In heroic mode he is replaced with Blood Guard Porung so his melee damage is prob a bit less than Porung. At the start of gauntlet event he should yell "Archers, form ranks!" "On my mark!
"Ready!" "Aim!" "Fire!"  When engaged right now he just autoattacks but judging from Blood Guard Porung's abilities the Shattered Hand Blood Guard should have a Cleave that deals 110% weapon damage used every 6 seconds or so.

NOTE: Trash packs after this fight are badly organized, some are just idling and not doing their event animations such as simulating combat with other one (Shattered Hand Gladiator) while other packs are just put randomly instead of being put in middle doing and doing the "combat ready" animation.

- Shattered Hand Centurion missing weapon 
![image](https://user-images.githubusercontent.com/42102450/44299266-194c8d00-a2f3-11e8-9801-7323c4945b45.png)
Base damage should be 1284-1815.
When engaged uses Sunder Armor, he should Battle Shout aswell at start of combat. Also for some reason he casts a buff on himself called Propagandized! this ability doesnt belong to him and its prob taking the place of Battle Shout. As Centurion's patrol around while Shattered Hand Gladiator's are simulating combat Centurion should say one of the following things every 10-15 seconds or so "Fight!" "For Kargath! For Victory!" "Gakarah ma!" "That's enough. Now back off!" "This world is OURS!"

- Shattered Hand Gladiator missing weapon 
![image](https://user-images.githubusercontent.com/42102450/44299404-4ef27580-a2f5-11e8-8fcc-095a9c6841da.png)
Base damage should be 1177-1664.
When engaged they use Mortal Strike but they are not engaged in event. They should be simulating combat with other Gladiator and damage each other until they reach around ~40% health then reset back to 100% and repeat it again, its very hard to survive if you pull them at 100% because their Mortal Strike is 200% weapon damage.

- Shattered Hand Champion missing weapon and shield  
![image](https://user-images.githubusercontent.com/42102450/44299457-67af5b00-a2f6-11e8-9771-cbf1816962cc.png)

Base damage should be 1284-1815.
When engaged they use their abilities properly.

- Heathen Guard missing weapons 
![image](https://user-images.githubusercontent.com/42102450/44299628-523c3000-a2fa-11e8-9a7d-1b4bfd86ba3b.png) and Dual Wield ability.
Base damage should be 1014-1431.

- Reaver Guard missing weapon 
![image](https://user-images.githubusercontent.com/42102450/44299643-8b74a000-a2fa-11e8-8370-09139f396088.png)
Base damage should be 1127-1664.

- Sharpshooter Guard missing weapon 
![image](https://user-images.githubusercontent.com/42102450/44299648-a6dfab00-a2fa-11e8-8076-bdc1f26cf864.png)
Base damage should be 1127-1591.

Bosses:

- Grand Warlock Nethekurse missing his weapon 
![image](https://user-images.githubusercontent.com/42102450/44298706-1ef0a580-a2e8-11e8-81dc-3dc6f08d8563.png)
Base damage should be 1406-1986.
When engaged uses all his abilities properly.

- Warbringer O'mrogg base damage should be 1610-2277.
When engaged uses all of his abilities except Beatdown but in a very chaotic order, timers on his abilities need to be adjusted also even tho he does his yells like left or right head talking the sound files arent playing.

- Warchief Kargath Bladefist base damage should be 1388-1963.
When engaged he uses only some of his abilities.  He doesnt use Sweeping Strikes or Thrash and timers for them need to be checked and the adds need to adjusted aswell.

**Comment by Silroth** [comment]
[Dungeon] Shattered Halls Heroic

Trash mobs:

- Shattered Hand Savage base damage should be 2200-3200.

- Shattered Hand Legionnaire base damage should be 3000-4500.

- Shattered Hand Sentry base damage should be 4500-6200.

- Shattered Hand Heathen base damage should be 4000-5700.

- Shattered Hand Brawler base damage should be 2300-2700.

- Shadowmoon Acolyte base damage should be 1300-2250.
Mind Blast hits for 1200-1700 (need more info on this for heroic)

- Shattered Hand Sharpshooter base damage should be 2200-3200.
Shoot ability for 1800-2800, Incendiary Shot for 950-1150 and on heroic mode in addition to his normal abilities also uses Viper Sting for 2736 mana over 8 seconds on random player on his aggro list with a mana pool.

- Shattered Hand Reaver base damage should be 5200-8400.

- Shadowmoon Darkcaster base damage should be 1550-2250.
Shadow Bolt for 1700-2700, Rain of Fire ticking for 1200-1400.

- Shattered Hand Houndmaster base damage should be 3500-4500.
Shoot ability for 1900-2800, Impaling Bolt for 1800 to 2201, Volley ticking for 540 and when his Rabid Hounds get CCed every few seconds he should use some ability that breaks the CC with some "Nothing can stop us!" message.

- Rabid Warhound base damage should be 6000-8500.
Should use stronger version of Furious Howl and Carnivorous Bite.

- Creeping Oozeling base damage should be 1700-2400.

- Creeping Oozeling base damage should be 150-420.

- Fel Orc Convert base damage should be 1099-1428.

- Shattered Hand Assassin base damage should be 3200-3800.

- Shattered Hand Zealot base damage should be 2100-2600.

- Shattered Hand Scout should follow same script as on normal for the gauntlet event.

- Shattered Hand Archer base damage should be 1900-2600.
Shoot ability for 1800-2600, Multi-Shot 1160-1360

- Shattered Hand Centurion base damage should be 6600-9200.

- Shattered Hand Gladiator base damage should be 1400-3300.

- Shattered Hand Champion base damage should be 5000-7100.

- Heathen Guard base damage unknown need more info (could put double the amount of normal version until more info is found)

- Reaver Guard base damage unknown need more info (could put double the amount of normal version until more info is found)

- Sharpshooter Guard base damage unknown need more info (could put double the amount of normal version until more info is found)
Incendiary Shot for 950-1150

- Shattered Hand Executioner base damage should be 4500-5000.
Cleave for 110% damage and War Stomp.

Bosses

- Grand Warlock Nethekurse base damage should be 3800-4400.
Instead of Shadow Cleave he uses Shadow Slam which has a bigger radius, Lesser Shadow Fissure ticking for 3500.

- Blood Guard Porung base damage should be 6300-8900.
Cleave for 110% damage every 6 seconds.

- Warbringer O'mrogg base damage should be 3100-4400.
Blast Wave for 2500-3000, Burning Maul dealing 2800-3500 extra fire damage each hit.

- Warchief Kargath Bladefist base damage should be 2700-3900.

**Comment by Wojtyas** [comment]
- [ ] Gauntlet of Flames: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1428
- [ ] Trash link: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1430

**Comment by Wojtyas** [comment]
- [ ] Also new topic: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3017
but seems like most is duplicated from here
