### ISSUE TITLE
Models with flag MOD M2 should not be LoS checked. 

### ISSUE THREAD

**Issue by SuddenDeath** [SunwellWoW/Sunwell-TBC-Bugtracker#1577]
The Problem: Currently pretty much all models in the game, trees, small road signs, rocks etc block line of sight

How it should work: They shouldn't block line of sight, only larger objects such as buildings, structures and other things should.

How to reproduce: Try to cast a spell on a target that is behind a tree.

Proof:
Retail videos:
https://www.youtube.com/watch?v=JX2q2Vu0_t0 - Cata
https://youtu.be/5VNF3UkQ5bU?t=1m22s - TBC
https://youtu.be/g8Nr3RpUE0w?t=25s - Vanilla
https://www.youtube.com/watch?v=wVWzGElLW3A - WoD

Discussion and commits on TC github:
https://github.com/cmangos/mangos-classic/pull/239
https://github.com/TrinityCore/TrinityCore/pull/18528
https://github.com/raczman/TrinityCore/commit/286f8147aba74860536c717f609f8e276c36e3f6

**Comment by akrom23** [comment]
Could you give some screenshots from our server?

**Comment by SuddenDeath** [comment]
@akrom23 https://i.imgur.com/aE78eHj.jpg

**Comment by sicknot1** [comment]
Don't.

**Comment by SuddenDeath** [comment]
@akrom23 did this get fixed or?
