### ISSUE TITLE
Player movement stutter when running in from draw distance

### ISSUE THREAD

**Issue by SuddenDeath** [SunwellWoW/Sunwell-TBC-Bugtracker#1578]
Decription: 
Player movement will be stutter/lag when running in from draw distance without stopping.

How it works: 
Player movement will be stutter/lag when running in from draw distance without stopping, if player stops at any point, then continues, movement will be smooth & normal.
Watch entire video: https://streamable.com/mst5u 

How it should work: Should be smooth at all times, even if someone runs in from your maximum draw distance... Since this will happen quite a lot I suspect in world pvp, might be worth looking into.

**Comment by Wojtyas** [comment]
Fixed & implemented.
