### ISSUE TITLE
[core] Mobs resets and start to attack you again (video)

### ISSUE THREAD

**Issue by sicknot1** [SunwellWoW/Sunwell-TBC-Bugtracker#1579]
Decription: 
Video

How it works: 
Video

How it should work: 
Mob should reset to 100% and not initiate attack unless you attack/aggro them again.

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/h98ll

**Comment by Wojtyas** [comment]
Fixed & implemented.
