### ISSUE TITLE
[Item] Unique Items

### ISSUE THREAD

**Issue by Lashington** [SunwellWoW/Sunwell-TBC-Bugtracker#1581]
Decription: 
I am able to equip two of the same trinket/ring. You should only be able to equip one of the unique ring etc.

How it works: 
There is no limitation. It doesn't stop you or anything. You just put the two rings on like nothing. 

How it should work: 
You should only be able to equip one of the unique ring etc.

Here is some images showing me equiping 2x DST and 2x Band of the Ranger-General, which are both unique items !

![wowscrnshot_111718_190744](https://user-images.githubusercontent.com/44973281/48664291-c1adf100-ea9c-11e8-8f60-e60cb63064d0.jpg)
![wowscrnshot_111718_190746](https://user-images.githubusercontent.com/44973281/48664292-c1adf100-ea9c-11e8-9d1c-0a79f99aa951.jpg)

**Comment by notsofamous** [comment]
Same issue as https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1414 and https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1307
