### ISSUE TITLE
Wrong work of Seal of Blood

### ISSUE THREAD

**Issue by Noyzi** [SunwellWoW/Sunwell-TBC-Bugtracker#1583]
Decription: 
Seal of Blood(SoB) makes more hits then it should

How it works: 

SoB deal 5 hits per 1 swing of weapon it's wrong
How it should work: 

SoB deal 1 hit per 1 swing thats how should be
Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
#1498
