### ISSUE TITLE
Blink (With proofs)

### ISSUE THREAD

**Issue by Adrestiah** [SunwellWoW/Sunwell-TBC-Bugtracker#1584]
Decription: Blink IS broken- 

How it works: Blink currently ignores elevation, walls, doors, and the like. I can demo this in game for you if you'd like, I'll also attach videos of a player testing it, though it's currently in a more broken state than it was in these videos. 
Feel free to message me on discord: Adrestia, or ping me through guild chat in game 

How it should work: Blink shouldn't ignore elevation, walls, doors, and the like. you can currently stand at the base of the mountain outside crypts by Kara, Blink, end up in crypts ( go through the wall,) Then jump down the well of souls, blink at the base of the skull pile, and end up on TOP of the mountain by crypts ( at least 200 yards) 

Source (you should point out proofs of your report, please give us some source): 
https://cdn.discordapp.com/attachments/497544716762611713/513436533253210113/Blink5.mp4
https://cdn.discordapp.com/attachments/497544716762611713/513436730754465815/Blink3.mp4
https://cdn.discordapp.com/attachments/497544716762611713/513436743945682964/Blink4.mp4

**Comment by Adrestiah** [comment]
I only have mp4 recordings, which I linked, but if you don't want to download them I'll send them through Discord upon request

**Comment by Piootrek** [comment]
Using blink on grave on Ruins of Lordeaeron put player under textures.

https://youtu.be/_TGPw3qOZ-Y
