### ISSUE TITLE
[Priest][Spell] Spirit of Redemption (Immortality)

### ISSUE THREAD

**Issue by SwishersweetWU** [SunwellWoW/Sunwell-TBC-Bugtracker#1586]
Decription: 
Holy priests will not die after clicking off Spirit of Redemption. They simply return to life where they died. 

How it works:
I die as a holy priest. I go into spirit of redemption mode and after it wears off or I remove the buff, I come back to life instantly at the place I died. 

How it should work: 
I die as a holy priest (pretty commonly). I gain spirit of redemption and it wears off and I die. 

Source (you should point out proofs of your report, please give us some source): 
I showed Adrestia and Zed the issue in person. They can back up my claim.

**Comment by Kokaina** [comment]
https://www.twitch.tv/videos/337658341

**Comment by SwishersweetWU** [comment]
You also noticed the extension timer on the spell too right?

**Comment by Wojtyas** [comment]
Fixed & implemented (only SSC realm for now).
