### ISSUE TITLE
[Priest][Spell] Spirit of Redemption (Refreshing)

### ISSUE THREAD

**Issue by SwishersweetWU** [SunwellWoW/Sunwell-TBC-Bugtracker#1587]
Decription: 
Spirit of redemption will actually refresh after the first time it runs through its 15 second timer. 

How it works: 
I die. (Again..) Spirit of Redemption runs its course for 15 seconds, and instantly refreshes to another 15 seconds.

How it should work: 
I die. (Another time) Spirit of  Redemption runs its course for 15 seconds, and I really die.

Source (you should point out proofs of your report, please give us some source): 
Both Adrestia and Zed were witness to this bug.

**Comment by Wojtyas** [comment]
Fixed & implemented (only SSC realm for now).

**Comment by SwishersweetWU** [comment]
123
