### ISSUE TITLE
[Quest] Bring Me The Egg!

### ISSUE THREAD

**Issue by Squarz** [SunwellWoW/Sunwell-TBC-Bugtracker#1589]
[Bring Me The Egg!](http://db.darkwizard.pl/?quest=10111)
[Mysterious Egg](http://db.darkwizard.pl/?object=183147)

How it works: 
There is a Mysterious Egg on the floor as well as in the nest:
The Jump-a-tron 4000 throws you backwards, regardless of where you stand.
Quest credit for clicking the Mysterious Egg is self only.
Windroc Matriarch appears spawns below the nest

How it should work: 
There should only be one Mysterious Egg that's in the nest.
The direction the Jump-a-tron 4000 throws you should be related to where you stand on it and not the direction you are facing.
Everyone in the group should get credit if one person clicks the Mysterious Egg
Windroc Matriarch should spawn in the air, fly in and land.

Source:
https://www.wowhead.com/quest=10111/bring-me-the-egg
" if you form a group for the quest, only one of you needs to get into the nest. I was able to get in and my partner stood on the ground under the nest. We both got credit for opening the egg."

https://www.youtube.com/watch?v=Az6GSKXkipM
https://www.youtube.com/watch?v=GMIm5QHNqVY

**Comment by notsofamous** [comment]
New issue: egg only spawns on server restart.

**Comment by LezChap** [comment]
I don't know if this is part of the "fix NOT live yet"...but the Matriarch doesn't despawn, causing several to exist at the same time and wiping anyone attempting this quest.

**Comment by Byrcio** [comment]
You cannot cancel the slow falling buff wich makes quest a lot of harder to complete

**Comment by bhe0** [comment]
this quest still doesn't work, the slowfall activates too early and you overshoot the nest every time.

however you can run to the cliff to the left of the tree and jump off with the slowfall debuff and hit the nest that way.
