### ISSUE TITLE
[ZONE] [Elwynn Forest]

### ISSUE THREAD

**Issue by Lonoss** [SunwellWoW/Sunwell-TBC-Bugtracker#159]
- [x] NPC - Murloc Forager Crawler GUID: 81277 Entry: 46
http://db.hellfire-tbc.com/?npc=46#abilities
How it works: Abilty Drink Minor Potion heals for 12-15.
How it should work: Drink Minor Potion should heal for 47-54

- [x] NPC - Morgan the Collector GUID: 80853  Entry: 473
http://db.hellfire-tbc.com/?npc=473#abilities
Does not use ability: Gouge (Rank 1)

- [x] NPC - Surena Caledon GUID: 80854  Entry: 881
http://db.hellfire-tbc.com/?npc=881#abilities
How it works: After pulling one mob from pack ( 2 other NPC are in same house) Surena just standing. Sometime even after normal pull she can be easy to freeze. Additionaly sometime after unpulling she stay in place, when she lost combat (not go back).
How it should work: After pull if she can't cast fireball she should go to player direction until she can cast. In case she lost combat she need to go back to respond location.
https://imgur.com/a/65xNV0f

- [x] NPC - Stonetusk Boar GUID: 80572  Entry: 113
http://db.hellfire-tbc.com/?npc=113#abilities
Does not use ability: Rushing Charge

- [x] NPC - Porcine Entourage GUID: 80848 Entry: 390
http://db.hellfire-tbc.com/?npc=390#abilities
Ability: Rushing Charge (Rank 1) not giving additional speed and he use it really rarely. 
Should be one pack with Princess. If only part of pack die all should be respownd.

- [x] NPC - Princess GUID: 80849 Entry: 330
http://db.hellfire-tbc.com/?npc=330#abilities
Ability: Rushing Charge (Rank 1) not giving additional speed and he use it really rarely.
Should be one pack with dwo Porcine Entourage (from patch 2.3 just one). If only part of pack die all should be respownd.

- [x] NPC - Rockhide Boar GUID: 80740 Entry: 524
http://db.hellfire-tbc.com/?npc=524#abilities
Use ability Rushing Charge (Rank 1) really rarely aprox 1 of 10.

- [x] NPC - Murloc Streamrunner GUID: 81023 Entry: 735
http://db.hellfire-tbc.com/?npc=735#drop:0+12+1
Does not drop quest item Crystal Kelp Frond for quest Collecting Kelp.
Should get same drop as Murlock.
Source: http://db.hellfire-tbc.com/?item=1256

- [x] Quest - Riverpaw Gnoll Bounty
http://db.hellfire-tbc.com/?quest=11
Drop rate of quest item (Painted Gnoll Armband) is much to low. From all mobs on Forest's Edge i berly get neded 8 for quest. Drop rate aprox 10-20% should be 40%.
Riverpaw Runt GUID: 80518 Entry: 97
Riverpaw Outrunner GUID: 80530 Entry: 478
Source: http://db.hellfire-tbc.com/?item=782

- [x] Quest - The Escape
http://db.hellfire-tbc.com/?quest=114
How it works: You finishing quest nothing hapening after.
How it should work: After give Invisibility Liquor to NPC she should drink it and dissaper for a while (aprox 10-60 sec, I am not sure).
Source: https://youtu.be/sgCpQoZT2Vs?t=88
Wideo from 2018 but realy good showing what NPC do.

**Comment by Dootz** [comment]
thanks for report, will be fixed with next ptr update.
