### ISSUE TITLE
Blood Fury (Orc-Racial)

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#1594]
Decription: 
- Blood Fury (Orc-Racial) should give u a debuff, reducing all healing effects on you by 50%.

How it works: 
- debuff is missing and healing effects on you are not reduced

How it should work: 
- Blood Fury (Orc-Racial) should give u a debuff, reducing all healing effects on you by 50%

Source (you should point out proofs of your report, please give us some source): 
![3](https://user-images.githubusercontent.com/45068171/48667571-7e25a800-ead9-11e8-9743-6d5d535689e5.jpg)

**Comment by FrauHolle86** [comment]
Note: Tooltip should adjust to your level

**Comment by Wojtyas** [comment]
Fixed & implemented.

**Comment by FrauHolle86** [comment]
tooltip is not adjusting with your level but the rest is working fine. thanks for the fix =)
