### ISSUE TITLE
[Talent bug] Shamanistic Focus

### ISSUE THREAD

**Issue by Haradokz** [SunwellWoW/Sunwell-TBC-Bugtracker#1597]
Decription: 

Shamanistic Focus - Reduces the mana cost of you next shock spell by %60.

How it works: 

My procs are being eaten when I proc WF. Pretty sure it is WF anyways eating the procs but they are for sure randomly disappearing without using a shock spell.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Haradokz** [comment]
Confirmed it is WF eating the buff.

**Comment by FrauHolle86** [comment]
Note: buff is also eaten by any kind of heals or spells like lightning bolt etc. --> it should only get consumed by shocks.

![2](https://user-images.githubusercontent.com/45068171/48674976-0ac07c80-eb53-11e8-8067-35d6fde54431.jpg)

**Comment by FrauHolle86** [comment]
not working on LIVE

**Comment by potty** [comment]
Confirming, it's not working.
