### ISSUE TITLE
[Quest] Surveying the Ruins

### ISSUE THREAD

**Issue by Squarz** [SunwellWoW/Sunwell-TBC-Bugtracker#1599]
Description: 
[Surveying the Ruins](http://db.darkwizard.pl/?quest=10335)
Place the three [Surveying Markers](http://db.darkwizard.pl/?item=29445)

How it works: 
You do not receive credit for placing the Surveying markers:
https://streamable.com/sj2s9

How it should work: 
You should receive quest credit when placing the surveying markers.

**Comment by twoPlusThree** [comment]
I can't place the markers for this quest
