### ISSUE TITLE
[Quest] Teleport This!

### ISSUE THREAD

**Issue by Squarz** [SunwellWoW/Sunwell-TBC-Bugtracker#1600]
Description:
Use the [Mental Interference Rod](http://db.darkwizard.pl/?item=31678) to control [Cyber-Rage Forgelords](http://db.darkwizard.pl/?npc=16943) and use [Detonate Teleporter](http://db.darkwizard.pl/?spell=38920) to destroy the teleporters.

How it works: 
 Casting Detonate Teleporter on the teleporter does not give quest credit:
https://streamable.com/wtfvi

How it should work: 
Using Detonate Teleporter on a teleporter should give quest credit.

**Comment by fudlow** [comment]
I don't get the extra button to detonate
