### ISSUE TITLE
[Paladin][Spell] Seal of Blood

### ISSUE THREAD

**Issue by zhanjor** [SunwellWoW/Sunwell-TBC-Bugtracker#1601]
Decription: 
Seal of Blood is broken

How it works: 
Seal of Blood strikes 6 times per swing

How it should work: 
Seal of Blood should strike once per swing
(Also it should double tap into crit since you can't crit yourself with the damage you deal)
Source (you should point out proofs of your report, please give us some source): 
![paladinbugreport](https://user-images.githubusercontent.com/37549853/48668007-871b7700-eae3-11e8-9491-53fead6af816.jpg)
https://wow.gamepedia.com/Seal_of_Blood

**Comment by akrom23** [comment]
#1498.
