### ISSUE TITLE
Feign Death Fails To Drop Threat

### ISSUE THREAD

**Issue by YoshGit** [SunwellWoW/Sunwell-TBC-Bugtracker#1603]
Description: 
Hunter spell Feign Death frequently (almost always) fails to drop threat and interrupt casting.

How it works: 
When a hunter is being targeted and casts feign death, the enemy continues to attack the hunter. 

How it should work: 
When a hunter is being targeted and casts feign death, all threat should be dropped from the hunter and casts in progress should be interrupted.

Source (you should point out proofs of your report, please give us some source):

**Comment by RPAncap** [comment]
I observed the same thing very frequently while running heroic dungeons. :-(

**Comment by nacsdale** [comment]
same

**Comment by YoshGit** [comment]
Recently ran some heroics and it seems to be working. Could have been fixed between then and now. I’ll check in the open world again

**Comment by akrom23** [comment]
Okay. I'll be waiting.

**Comment by Wojtyas** [comment]
Seems to work now. Feel free to reopen if happens again.

**Comment by nacsdale** [comment]
still fucking same

**Comment by RPAncap** [comment]
Also doesnt work when you get attacked by a other hunters pet.
