### ISSUE TITLE
Kill Command Fails Without Pet Target

### ISSUE THREAD

**Issue by YoshGit** [SunwellWoW/Sunwell-TBC-Bugtracker#1604]
Decription: 
When hunter spell Kill Command is cast while pet does not have a target, Kill Command's cd is triggered but deals no damage.

How it works: 
When hunter spell Kill Command is cast while pet does not have a target, Kill Command's cd is triggered but deals no damage.

How it should work: 
Need confirmation, but I believe Kill Command should deal damage and the pet should engage in combat.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Cannot use this spell without target. @YoshGit Any screenshots?

**Comment by YoshGit** [comment]
I’ll try to reproduce andgenerate some when I get back from work. When I tested this originally my hunter had a target but pet was by my side without target.

**Comment by Wojtyas** [comment]
Fixed & implemented.
