### ISSUE TITLE
Dismissing Pets After Quest Taming the Beast

### ISSUE THREAD

**Issue by Euphemistic** [SunwellWoW/Sunwell-TBC-Bugtracker#1605]
Decription: Dun Morogh hunter quest Taming the Beast, after completing the first part to tame the boar, I dismissed it after turning it in, and it runs back to where it was tamed, but then instantly runs back to where I am, and follows you everywhere without leashing. I tried it again for the second part to tame the snow leopard, and it does the same thing except it leashes since it's hostile. After leashing back to its location however, it continuously tries to run towards my location, regardless of how far away I get from it, before leashing back again. It does this continuously. I haven't done the Ice Claw bear yet, but I imagine it works the same way as the Snow Leopard. This is all after dismissing the pets after turning in each part.

How it works: Neutral pet (boar) runs back to its location after being dismissed, and then runs to you again. Hostile pet (snow leopard, ice claw bear) runs back to its location and then continuously runs towards you and leashes back. So theoretically if you abandoned the first part of the quest to tame the boar and redid it over and over you could get an army of boars to follow you around.

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/l16x7

**Comment by Euphemistic** [comment]
I also ran to Ironforge and back, and the hostile mobs were still doing the same thing. Logging off seems to fix it though.

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).
