### ISSUE TITLE
[Shaman] Totem Aggro without Player Aggro

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#1611]
Decription: 
- Mobs aggro totem and reset after

How it works: 
- you drop a totem near a mob
- you take 2 steps back
- the mob aggro's the totem (you instantly enter & leave combat at the same time)
- after destroying the totem, the mob does not aggro you and resets

How it should work: 
- you drop a totem near a mob
- you take 2 steps back
- the mob aggro's the totem
- after destroying the totem, the mob should aggro you if u are right next to the totem and not out of "evade range"

Source (you should point out proofs of your report, please give us some source): 
![1](https://user-images.githubusercontent.com/45068171/48671343-c4edbf00-eb26-11e8-9497-b17aedff9d9e.jpg)
![2](https://user-images.githubusercontent.com/45068171/48671344-c4edbf00-eb26-11e8-988f-d8481b4db890.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented.

**Comment by FrauHolle86** [comment]
still the same issue on PTR

**Comment by Wojtyas** [comment]
Huh :cry: tested that on Friday and it worked. I will retest it once again today.
Reopened.

**Comment by Wojtyas** [comment]
Fixed & implemented (only SSC realm so far).

![image](https://user-images.githubusercontent.com/22802214/48985823-89e22180-f10c-11e8-95ee-b968a79a6060.png)

**Comment by FrauHolle86** [comment]
not working on LIVE... mobs should aggro you after destroying the totem

**Comment by FrauHolle86** [comment]
issue should be reopened
