### ISSUE TITLE
[Spell] Mark of War, Mark of Lore

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#1615]
Decription: Those buffs are granted by ancients in Cenarion refugee in Zangarmarsh and they work only in Zangarmarsh. If you leave to area you should still have the buff but it should be inactive. 

On hellground there was similar problem with Shattrath flasks. They are meant to work only in T5/T6 raids. What happened on HG is that flasks couldn't be used at all until you were in the location and if you left it it was removed. There are several other "area buffs" in the game and I think that all of them shared the same problem.

This needs confirmation. 

How it works: If you leave zangarmarsh buffs are removed. 

How it should work: If you leave zangarmarsh you should still have the buffs but they should be inactive.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_111818_120645](https://user-images.githubusercontent.com/37372869/48671616-83134780-eb2b-11e8-987b-a61b535fd604.jpg)
![wowscrnshot_111818_120649](https://user-images.githubusercontent.com/37372869/48671617-83abde00-eb2b-11e8-8330-f9a8a20f96f9.jpg)

**Comment by koostosh** [comment]
Any source that they should not be removed?
