### ISSUE TITLE
Blizzard clearcast bug

### ISSUE THREAD

**Issue by fakesunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#1626]
Decription: 
Clearcast has a chance to proc from spells. This should only happen with spells that hit a target.
talent:  [Arcane Concentration] in arcane tree.

How it works: 
When I cast a spell then it has a chance to proc. 
Also it doesn't work in other ways.
If you cast a blizzard and it deals dmg, then it can proc. But it remove the buff from you, even tho you didnt cast a new spell.
https://clips.twitch.tv/HappyEmpathicMoosePJSalt

How it should work: 
Clearcast may only proc from dmg spell.
The effect shall last till you cast a new spell. Not if you are casting blizzard already. The buff has to expire when you cast a new spell only.

Source (you should point out proofs of your report, please give us some source): 
https://vanilla-twinhead.twinstar.cz/?spell=12577

**Comment by fakesunwell** [comment]
not fixed

**Comment by grand-lotus-iroh** [comment]
not fixed - check https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3691
