### ISSUE TITLE
[NPC][TRAINER]Mount training price.

### ISSUE THREAD

**Issue by TBCKillshot** [SunwellWoW/Sunwell-TBC-Bugtracker#1630]
Decription: 
The mount training cost for 60% riding is at 85g while 100% (ground mount) is at cost of a 570g.

How it works: 
It should be much less gold required to get your ground mount.

How it should work: 
60% mount should be at around 4 g (if i remember correctly) and 100% at around 50 g. (Not counting reputation with faction you're in to decrease the cost.)

![wowscrnshot_111818_175951](https://user-images.githubusercontent.com/42093565/48675717-b91cef80-eb5c-11e8-9f17-6c8cfa1a3f34.jpg)
![wowscrnshot_111818_175953](https://user-images.githubusercontent.com/42093565/48675722-c2a65780-eb5c-11e8-9b1c-178a1abc8888.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Eternae1** [comment]
Your screenshots are the proper prices for TBC. The prices you are thinking of are WotLK or Pre-WotLK patch.

**Comment by neheri** [comment]
It works 100% correct.

100g - lvl 30 - 60%
600g - lvl 60 - 100%

Price can be decreased by reputation discount. 

As of Patch 2.3, all vendors with an associated faction now give discounts at all levels above Neutral.

Friendly: 5% discount
Honored: 10% discount
Revered: 15% discount
Exalted: 20% discount
This includes the Riding skill below expert and Mounts.[citation needed]

**Comment by Eternae1** [comment]
Mount is also at level 40 not 30 on this server.

**Comment by neheri** [comment]
Well, I've just checked 

https://wow.gamepedia.com/Mount#Burning_Crusade

and it seems that lvl 30 mount should cost 35g. 600g still applies for 100% mount at level 60.

**Comment by Eternae1** [comment]
Yes, like I said. the server is not starting at the end of the content. Your client may be 2.4.3 but that does not mean the server is on that content patch.
