### ISSUE TITLE
(TBC Dungeon Set) beastlord set

### ISSUE THREAD

**Issue by tigeron** [SunwellWoW/Sunwell-TBC-Bugtracker#1637]
Decription: beastlord dungeon set  4pc set does not work 

How it works: nothing happens when u use your kill command

How it should work: it suppossed to give you 600 armor pen for 15 sec  when  you use ur kill command 

Source (you should point out proofs of your report, please give us some source): i was on the server and tested it  on dummies and mobs and nothing happend

**Comment by YoshGit** [comment]
It should also provide 600 ARP to your pet as well*

**Comment by tigeron** [comment]
yea you are right i forgot about that one
