### ISSUE TITLE
(Meta Gem)Thundering Skyfire Diamond 

### ISSUE THREAD

**Issue by tigeron** [SunwellWoW/Sunwell-TBC-Bugtracker#1638]
Decription: Thundering Skyfire Diamond meta gem 

How it works: dosent give you the proc it needs to 

How it should workit should give you 240 haste rating for 6seconds

Source (you should point out proofs of your report, please give us some source): 
i tested it myself on  dummies  for atleast 20 min and no proc

**Comment by koostosh** [comment]
Works for me without any problems
