### ISSUE TITLE
Reputation for Heroic keys

### ISSUE THREAD

**Issue by nimeral** [SunwellWoW/Sunwell-TBC-Bugtracker#1641]
Decription: Heroic key reputation should be Revered, not Honored

How it works: you can get a Heroic key as soon as your respective reputation is Honored

How it should work: you should only be able to get a Heroic key when Revered

Source (you should point out proofs of your report, please give us some source): http://wowwiki.wikia.com/wiki/Patch_2.3.0 - _The Requirement for Heroic Keys has been lowered to honored_

**Comment by Kokaina** [comment]
Will be changed on start but thank you for remind ;)
