### ISSUE TITLE
[Warlock][Spell] Ritual of doom - Doomguard skills

### ISSUE THREAD

**Issue by doomnyx** [SunwellWoW/Sunwell-TBC-Bugtracker#1642]
Decription: 4 other ppl clicking the portal, 1 dies, but doomguard is not summoned.

http://db.hellfire-tbc.com/?spell=18540

Should work and summon hostile doomguard which can be enslaved.

Source (you should point out proofs of your report, please give us some source): Tooltip.

**Comment by akrom23** [comment]
Works good to me.

**Comment by doomnyx** [comment]
works for me as well.

**Comment by doomnyx** [comment]
Reopening, he uses his skills on his own will, even when I turn off all autocasts.

**Comment by akrom23** [comment]
Should be alright now @doomnyx
