### ISSUE TITLE
Linked Mob Packs Don't Pull On One Shot

### ISSUE THREAD

**Issue by blackwife** [SunwellWoW/Sunwell-TBC-Bugtracker#1646]
Decription: We were testing some bosses with modified spellpower values that resulted in our lock being able to one shot the channelers for Magtheridon.  On one shot kill, the boss was not engaged and it was possible to lock the instance so that Mag was unkillable.  On live this specific one shot mechanic won't be possible but any pack that has critical mobs that are capable of being one-shot (like the mana/hp NPCs before Curator in Karazhan) will trigger a similar response.  One shot kills should place the group in combat with the pack/encounter they are linked to in order to prevent future bugginess.

How it works: One shot any NPC from outside of its pull range, No combat will be entered if it is part of a linked pack/boss encounter.

How it should work: Attacking (even one shotting) an NPC should enter into combat with its linked pack or encounter.

Source (you should point out proofs of your report, please give us some source): Tested the mechanic as a group of 5 at Magtheridon with one shotting Shadowbolts on the Channelers, should apply elsewhere but haven't personally tested.  This should be universal behavior to prevent future bugs.

**Comment by Squarz** [comment]
Should also apply to linked NPCs in the world too.
Current behaviour: https://streamable.com/bz4ua

**Comment by lukaasm** [comment]
for now resolved formation issue, a small ooze from the clip is currently not linked to big one, so it won't work currently on it.
But such situation should be resolved with chain pull implementation, which is planned

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).
