### ISSUE TITLE
Die in darkshore as horde, respawn near felwood

### ISSUE THREAD

**Issue by nickycakes** [SunwellWoW/Sunwell-TBC-Bugtracker#1650]
Decription: 

Dying at the dock in darkshore as horde and then releasing transports you to ashenvale near felwood

How it works: 

See description

How it should work: 

Ghost should spawn at the appropriate gy for horde in darkshore

**Comment by Mikov1605** [comment]
Nah, if u die in northern darkshore, or even middle dark, u will spawn at felwood, center location, near the horde base there. Worked like that everywhere. Unless u die in south Darkshore, then u get started at darkshore south graveyard ;)

**Comment by Mikov1605** [comment]
It works well like that, unless u wanna run from south darkshore till the dock. Worked like that on tbc, and wotlk servers i played one. You can close this issue ;)
