### ISSUE TITLE
[NPC][Spell]Frost Nova

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1652]
Decription: 
NPC, that are in Frost Nova effect, which get below 20% and want to "run away in fear" dont do it after Frost Nova ends.

How it works: 
Mobs ignore "running away in fear" when they get it in frost nova and nova ends

How it should work: 
They should try to run away in fear(idk for how long, like 5-7 secs) and then come back to fight. If they get below 20% hp WHILE in frost nova, and nova ends in 1 sec, they should still try to run away. Frost Nova, any other frezzing effect shouldnt stop the run away attempt( i mean, okay, frost nova ends in 2 seconds, and the mob just wants to run away in fear, but he quits it after frost nova ends). I hope u understand what I mean

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
Partially fixed, a mob will try to flee after other effects wear off.

Only thing I am not sure if it is proper behaviour:
If a mob is prevented from fleeing by roots, should he still attack player until root fades off?

Situation:
Fleeing -> nova -> mob stays still ( can he attack player here?) -> nova fades -> fleeing

**Comment by Wojtyas** [comment]
Now fleeing removes Frost Nova debuff. 

 Answering your question it seems to be logic but I have no clue if it worked that way.
