### ISSUE TITLE
[Priest]Surge of light

### ISSUE THREAD

**Issue by Sheyroth** [SunwellWoW/Sunwell-TBC-Bugtracker#1654]
Decription: 

Surge of light (in holy tree) is consumed by any spells.

How it works: 

When you have surge of light buff and use a smite, the smite is instant and free and consumes the buff. If you use any other spell and have SoL buff, it will consume it too.

How it should work: 

Only Smite should consumes SoL buff.

Source (you should point out proofs of your report, please give us some source): 

From experience and by reading the description of the perk, that's how it should work

**Comment by GrindPlayer** [comment]
Hello,
It's a priest bug in his holy tree talent^^

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).
