### ISSUE TITLE
[Hunter] no queueing during autoshot bug

### ISSUE THREAD

**Issue by Jeansapin** [SunwellWoW/Sunwell-TBC-Bugtracker#1665]
Decription: Hunter no queueing during autoshot bug

How it works: Once the 0.5s Auto Shot cast time starts, it shouldn't be interrupted by other spell casts, all spell casts performed during the Auto Shot wind up time should be queued and handled by the server immediately after the auto shot goes off.

How it should work: Someone has already reported it somewhere else : https://github.com/Schaka/TBC-research/issues/28

Source (you should point out proofs of your report, please give us some source):

**Comment by notsofamous** [comment]
I don't think there is any spell queuing system at all right now

**Comment by Jeansapin** [comment]
Idk, but it's really annoying for hunters

**Comment by lukaasm** [comment]
Did you test it? because there is ranged spell scheduling system in place.

https://streamable.com/gepvb none of my auto-shots was interrupted even if I tried to cast my ranged spell little before/after AS timer was ready.

**Comment by MiekZer** [comment]
lukaasm you are wrong about the issue.

https://streamable.com/m5trj

Important problem that must be fixed.

**Comment by lukaasm** [comment]
there seems to be an issue that queue window is shorter than 500ms I will recheck it later

**Comment by Zarant** [comment]
It feels very inconsistent atm, also whenever I cast kill command + steady shot via macro, my auto shot will immediately get interrupted even if I cast at the very end of the auto shot cycle.

Here is a short clip showing that:
https://youtu.be/bRal0xt5U3c

**Comment by lukaasm** [comment]
Not everything is live yet. Kill Command I will recheck for sure

**Comment by ta55el** [comment]
On CC they resolve this problem implementing 3:2 rotation into Steady Shot skill, so u dont have to use macro to do 3:2 rotaton. Maybe thats the way to do it.

**Comment by Wojtyas** [comment]
Looks fixed, feel free to reopen/comment when needed.
