### ISSUE TITLE
[Warlock][Fel Armor]

### ISSUE THREAD

**Issue by doomnyx** [SunwellWoW/Sunwell-TBC-Bugtracker#1680]
Decription: http://db.hellfire-tbc.com/?spell=28189
Surrounds the caster with fel energy, increasing the amount of health generated through spells and effects by 20% and increasing spell damage by up to 100. Only one type of Armor spell can be active on the Warlock at any time. Lasts 10 sec.

How it works: Max rank Healthstone without Fel Armor healed me for 2080. After casting Fel Armor it heals me for 2620, which is wrong.

2080 * 1.20 = 2496

2080 *1.26 ~= 2620

How it should work: Should have flast 20% of healing increased, not 26% or something.

Source (you should point out proofs of your report, please give us some source):  Tooltip.

**Comment by sicknot1** [comment]
isn't there a talent? or it's wotlk

**Comment by doomnyx** [comment]
Basic pve and pvp warlock buff, gives 100 sp or 130 talented

**Comment by doomnyx** [comment]
Should stay at 20%, so it's a bug.

**Comment by Silroth** [comment]
Its properly affected by talent and that wowwiki is wrong, the effect of talent is as follows:
 (6) Apply Aura #108: Mod Spell Effectiveness % 
Value: 30

Which means it affects the entire spell not just part of it.

**Comment by doomnyx** [comment]
I will gry to find some videos tomorrow.

**Comment by doomnyx** [comment]
https://youtu.be/qmJYMarQb_I

8:10, seems like he had 2/2 imp healthstones and 3/3 aegis. 
2080 *1.2*1.26 =3144,96 (amplify magic does bot work with hstones and potions).

Not a bug then, wowwiki is indeed wrong
