### ISSUE TITLE
[Rogue] Relentless strikes proc 2 times

### ISSUE THREAD

**Issue by Sheyroth** [SunwellWoW/Sunwell-TBC-Bugtracker#1687]
Decription: 

When you use a finisher and have this talent, it procs two times instead of one.

How it works: 

Take that talent, build combo points and use a finisher. When Relentless strikes procs, it gives you 50 energy instead of 25.

How it should work: 

It should proc one time and gives you 25 energy.

Source (you should point out proofs of your report, please give us some source):

**Comment by zapsuu** [comment]
Works good

**Comment by JuhaLintunen** [comment]
bugged again
