### ISSUE TITLE
Scarlet Monastery - Library

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#169]
- [x] 1. Scarlet Adept (4296) should be more focused on casting spells (Holy Smite [9734], Heal [6063]) instead of damaging by melee.
- [x] 2. Scarlet Beastmaster (4288) uses his Exploding Shot spell (4288) in correct way. However the animation of spell should fly to target. For now player takes damage from spell but spell flies in random location (where there are no players).
- [x] 3. Houndmaster Loksey (3974) doesn't use his Blood Shout spell (6192) at all. He should cast it time to time in order to increase his, and nearby Scarlet Tracking Hounds attack power.
- [x] 4. Houndmaster Loksey doesn't use his Bloodlust spell (6742) too. He should cast it on random Scarlet Tracking Hound time to time.
- [x] 5. Looks like Scarlet Diviner (4291) doesn't use his Mana Burn spell (11981) at all.
- [x] 6. Scarlet Chaplain should use his Renew (8362) and Power Word: Shield (6066) spells on other Scarlet npcs too.

**Comment by Silroth** [comment]
- Houndmaster Loksey missing Dual Wield passive ability (he isnt attacking with offhand for 50% damage)

- Scarlet Monk should use his Kick and Thrash abilities more often and have a really fast attack rate.
