### ISSUE TITLE
[Quest] Test of Endurance

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#1692]
Decription: 
- [Quest] Test of Endurance is not working as it should be

How it works: 
- you fight yourself all the way through the cave
- you destroy 1 box
- Grenka and nearly 20 Harpy are spawning

How it should work: 
- you fight yourself all the way through the cave
- you destroy 1 box
- with patch 2.3.0 Grenka should spawn all by herself --> its not a group quest anymore like vanilla --> no waves

Source (you should point out proofs of your report, please give us some source): 
![grafik](https://user-images.githubusercontent.com/45068171/48733277-77ff0b00-ec42-11e8-8aa3-c0a17d1a0a25.png)

**Comment by FrauHolle86** [comment]
resolved? =))

**Comment by Afgann** [comment]
@FrauHolle86 yeah

**Comment by FrauHolle86** [comment]
thanks =)

**Comment by FrauHolle86** [comment]
had the same issue 3 days ago on LIVE while leveling --> tonnes of adds are spawing
