### ISSUE TITLE
[Spell] [Hunter] Misdirection

### ISSUE THREAD

**Issue by kiterama** [SunwellWoW/Sunwell-TBC-Bugtracker#1694]
Decription: 
Misdirection didnt work with multi-shot

How it works: 
If you use Misdirection in combination with Multi-Shot, the target will get the aggro of one target (one shot) and the hunter gets aggro of other two mobs.

How it should work: 
All three mobs should aggro the misdirection target.

Source (you should point out proofs of your report, please give us some source): 
Spell itself: Misdirects all threat you cause to the targeted party or raid member for the next 8 sec.

**Comment by akrom23** [comment]
It works fine if you have 3 charges. Problem is when you have 2 or 1 charge.
Every single charge is consumed per target, not single use/cast.
If you have ony two charges, 3 targets and you use multi-shot, the last one will atack you.
I know that the spell's tooltip says:

> Threat caused by your next 3 **attacks** is redirected to the target raid member.  Caster and target can only be affected by one Misdirection spell at a time.  Effect lasts $d.
> ToolTip: Redirecting threat.

So we need more info: misdirection should consume charges per target or per cast.
Multi-Shot should be considered as a single attack?

**Comment by akrom23** [comment]
No response.
