### ISSUE TITLE
 Furious Howl autocast rules

### ISSUE THREAD

**Issue by lukaasm** [SunwellWoW/Sunwell-TBC-Bugtracker#1696]
From other issue:

It's on auto-cast but it's not casting it, however, he does cast it as an attack when I'm fighting a mob (as in, he thinks it's a damaging ability and thus when he's attacking a mob he does cast Furious Howl). After combat however he does not cast it or whenever he's not attacking, even if I am attacking.

**Comment by akrom23** [comment]
https://www.youtube.com/watch?v=BsRO1NRDUI4&feature=youtu.be&t=422 - Vanilla
https://www.youtube.com/watch?v=Iu4qoFKTlC8&feature=youtu.be&t=580 - TBC.
Should be castable only in combat.
