### ISSUE TITLE
Windfury Attack When Not In Party

### ISSUE THREAD

**Issue by YoshGit** [SunwellWoW/Sunwell-TBC-Bugtracker#1699]
Description: 
Pet is gaining windfury attacks when I am not in any party

How it works: 
While solo testing against a dummy, I noticed my pet was gaining windfury attacks. Cant confirm if this is related to the known dueling issue, a pet exclusive issue, or an issue affecting all friendly allies

How it should work: 
Windfury totem should only apply to allies in party.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_111918_190725](https://user-images.githubusercontent.com/12674486/48742850-af63bc80-ec2e-11e8-9e20-ec863758427e.jpg)

**Comment by Wojtyas** [comment]
Related to dueling issue ;) Fix is on way.
