### ISSUE TITLE
Scarlet Monastery - Armory

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#170]
### **TO DO:**

- [x] 1. Scarlet Protector Devotion Aura doesnt give armor to nearby Scarlet units if those Scarlet units are aggroed first, Devotion Aura is present on other Scarlet units only when Scarlet Protector is aggroed first.

- [x] 2. Scarlet Myrmidon missing Dual Wield passive ability (they arent attacking with offhand for 50% damage)

- [x] 3. Herod when Herod is aggroed 4 Scarlet Champions should spawn outside his room near Herod's Door (this was added to prevent players from pulling him outside his room), when engaged he uses Rushing Charge and Cleave properly however he Enrages at 30% while he should at 50%, his Whirlwind ability is on a wierd timer and he will interrupt it most of the time to move closer and autoattack which makes this fight very easy right now.

### **DONE:**

- [x] 1. Herod (3975) should use his Rushing Charge spell (6268) more often. For now he used it only at the beginning of the fight when his target was far away from him. He should cast it everytime his main target is far away from him.
- [x] 2. Scarlet Defender (4298) should use his Shield Bash spell (11972) more often.
**Edit:** They should use that spell when target is casting some spells.
- [x] 3. Spawned Scarlet Trainees (6575) who appear after Herod is defeated should be split by half while they run down to room. 10 of them should choose right way of stairs, and second 10 of them should choose left.
**Edit:** Right now they are run to inner circle through walls and they do no melee damage to players.
![image](https://user-images.githubusercontent.com/22802214/44692219-263f4e00-aa62-11e8-9ff2-3707b238c176.png)

**Comment by Dootz** [comment]
thanks for report, will be fixed with next ptr update.
