### ISSUE TITLE
[Boat] Theramore -> wetlands boat seems to not exist

### ISSUE THREAD

**Issue by nacsdale** [SunwellWoW/Sunwell-TBC-Bugtracker#1708]
as the title says or if it does it appears invisible.

**Comment by Haradokz** [comment]
Can confirm, I waited a long time for the boat and no luck.

**Comment by akrom23** [comment]
Should be fixed after update.

**Comment by Wojtyas** [comment]
Spent around 20 minutes in Theramore and still no ship on the horizon.
