### ISSUE TITLE
[Object]Ship Theramore ----> Auberdine

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1713]
Decription: 

After seeing report about bout from theramore to wetlands ( https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1708 ) i was curious about the other boat , from auberdine. The boat was there, so i waited to check if it will swim away. It just dissappeared. Guess the swim effect is skipped, and it teleports instant to Auberdine, or idk. Anyway, it just dissapeared. I waited again, and it came normal from Auberdine(i mean it came normally on the water). So my guess is, the "swim away" effect + transport is bugged, but it normally swims from Auberdine till here
How it works: 
Boat dissapears instead docking away.

How it should work: 
Quite obvious, aint it? :P 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Spent around 20 minutes in Theramore and still no ship on the horizon.

**Comment by Wojtyas** [comment]
I believe there was no theramore -> auberdine boat.
Auberdine has only 3 spots in its docks and there are filled right now: Exodar, Teldrassil, Wetlands.
Just checked all of them after morning update and everything seems to work fine with each of ship.
Closing.
