### ISSUE TITLE
[NPC] Commoners

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1718]
Decription: 
The holiday commoners are still in Stormwind/Ironforge etc

How it works: 
As in descritpion

How it should work: 
They should be only during one of the holidays(Midsummer, Hallows End etc) and have the right "Description" when we click on them to talk with them.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
18927 - [Human Commoner] 
19148 - [Dwarf Commoner] 
19169 - [Blood Elf Commoner] 
19171 - [Draenei Commoner] 
19172 - [Gnome Commoner] 
19173 - [Night Elf Commoner] 
19175 - [Orc Commoner] 
19176 - [Tauren Commoner] 
19177 - [Troll Commoner] 
19178 - [Forsaken Commoner] 
20102 - [Goblin Commoner] 
Not all of them are visible (for example there are only couple of Human Commoners, not all of them).
Also i've seen Tauren Commoner in Silvermoon City, not in Thunder Bluff.
