### ISSUE TITLE
Razorfen Downs

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#172]
### **TO DO:**

- [ ] 1. Withered Spearhide (7332) doesn't use his Infected Spine spell (12245) when fightning by melee.
**EDIT: He still doesn't use it.**
- [ ] 2. Death's Head Geomancer's Flame Spike spell (6725) should be used on targeted area where are two or more players.
- [ ] 3. After activate Holding Pen gob (32023) there should be quote from resuced Henry Stern (8696):
"Henry Stern says: Thank again, <name>. Now I'll just wait here until it's safe to leave."
![image](https://user-images.githubusercontent.com/22802214/44342777-58621600-a48c-11e8-882d-162da54baa81.png)
- [ ] 4. Frost Spectre should disappear in ~30s after evade.
- [ ] 5. Sah'rhee (8767) has his text missing.
- [ ] 6. Check out Belnistrasz's protecting event. When he yelled:
"Belnistrasz yells: Just two minutes to go! We're half way there, but don't let your guard down!"
There were no more spawns, after that 1 min before event ends boss spawned when he should after full duration is complete.

### **DONE:**

- [x] 1. Death's Head Geomancer (7335) doesn't use his Slow spell (11436).
- [x] 2. Withered Quilguard (7329) should have a chance to apply Withered Touch (11442) disease on target with melee hits. For now he doesn't apply that. Probably he has no Withered Touch passive aura (11441).
- [x] 3. Skeletal Servant (8477) should be Death's Head Necromancer's guardian.
- [x] 4. Spawned Skeletal Servant should start to attack players immediately.
- [x] 5. Tuten'kash (7355) should cast Curse of Tuten'kash (12255) on random players. He shouldn't cast it on targets who already have this curse.
- [x] 6. Plaguemaw the Rotting (7356) should use his Withered Touch spell (11442) more often.
- [x] 7. Lady Falther'ess (14686) shouldn't be present in dungeon. This is boss from Scourge Invasion event.
- [x] 8. Mordresh Fire Eye (7357) should use his Fire Nova spell (12470) only when there are melee players around him.
- [x] 9. Skeletal Summoner (7342) should use his Summon Skeletal Shadowcaster spell (12258) once pulled. For now he might skip that spell sometimes.
- [x] 10. Skeletal Shadowcaster (7340) should start to attack players immediately after spawned.
- [x] 11. Splinterbone Centurion (7346) shouldn't use his Thunderclap spell (8078) when there are no players in spell radius.
- [x] 12. Death's Head Necromancer (7337) should use his Summon Skeletal Servant spell (12420) once pulled.
**EDIT: Looks like Death's Head Necromancer doesn't use this spell when in combat. When I try .cast back 12420 when out of combat he does it but not when pulled**
- [x] 13. Looks like every spawned creatures during Tutan'kash event appear in one place instead of spawn in corridors and come to chamber. Have they should spawn:
- 1 wave: 4x Tomb Fiends in Right Corridor and 4x Tomb Fiends in Left Corridor
- 2 wave: 2x Tomb Reavers in Right Corridor and 2x Tomb Reavers in Left Corridor
- 3 wave: Tutan'kash in Left Corridor
**EDIT: Each of waves should walk into middle room firstly. For now they try to attack players once spawned and they walk on walls.**
![image](https://user-images.githubusercontent.com/22802214/44343855-5baad100-a48f-11e8-85b1-aa4af245174d.png)
- [x] 14. Henry Stern has only "Greetings" text while he should have:
![image](https://user-images.githubusercontent.com/22802214/44342857-8cd5d200-a48c-11e8-93b9-611351a69f17.png)
- [x] 15. Belnistrasz (8516) should has 8 minutes respawn time.
- [x] 16. Amnennar the Coldbringer (7358) doesn't use his Summon Frost Spectres spell (not sure ID).
**EDIT: He still doesn't use it. I believe spell id is 12670**
- [x] 17. Spawned Frost Spectre (8585) should start to attack players immediately.
**EDIT: It was still staying in place when i summoned it by .cast back**
- [x] 18. Belnistrasz (8516) should walk instead of run during his escort on Extinguishing the Idol (3525) quest.
- [x] 19. During Extinguishing the Idol quest we have to protect Belnistrasz from attacking creatures. Those creatures seem to spawn in same points all the time while the should spawn in random locations in this room.

**Comment by Kokaina** [comment]
List updated.
