### ISSUE TITLE
Elemental Focus

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#1722]
Decription: Elemental Focus gives 2 stacks that reduces the cost of next two spells
When you cast a spell it still shows 2 stacks, then after casting another the buff disappears.

How it works: https://www.twitch.tv/videos/338595915

How it should work: https://youtu.be/YYUe_tq2ryM?t=26

Source (you should point out proofs of your report, please give us some source):

**Comment by Avishai97** [comment]
Sometimes lightning bolt / chain lightning doesn't use the proc at all, don't know how to recreate, i was being hit by mobs at the same time though, might be something about that

**Comment by Avishai97** [comment]
Maybe it is a visual bug?
https://www.twitch.tv/videos/338595915

**Comment by Avishai97** [comment]
https://www.twitch.tv/videos/338595502
It seems to consume the buff correctly but visual shows you have two left after first cast

**Comment by Avishai97** [comment]
https://youtu.be/YYUe_tq2ryM?t=26 
thats how it should work

**Comment by Wojtyas** [comment]
I spent some time there and probably LBs that don't consume EF buff are from Lightning Overload talent. w/o this talent all of my casts were consuming this buff so it was fine. With this talent lbs created by this talent simply dont consme that.

Feel free to reopen if needed but for me it works as intented.

**Comment by Eveer** [comment]
This is still bugged as described and flameshock DOT ticks consume it as well as searing totem damage and flame tongue damage.
It does not work at all as intended, with just elemental focus, it is obvious just leveling as your stack is consumed by searing totem if you do nothing. If you just cast lighting bolt, it consumes both charges.
