### ISSUE TITLE
What's Haunting Witch Hill

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#1723]
Decription:  You can slay Risen Husks and Risen Spirits for this quest but only Risen Spirits work.

How it works: When you slay Risen Husks it doesn't give credit towards the quest.

How it should work: When you slay Risen Husks it gives credit towards the quest.

Source (you should point out proofs of your report, please give us some source):

**Comment by Mikov1605** [comment]
Do you checked many Risen Husks? because the credit is earned randomly, its not 100% to gain credit for killing one mob. Its like 60% or something. Try killing many Husks. Maybe u just were unlucky.

**Comment by Avishai97** [comment]
we killed 10 spirits to complete the quest, 2-3 husks along the way that didn't give credit
