### ISSUE TITLE
You are too far away from that corpse

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#1724]
Decription: Sometimes when you loot items on the ground it says You are too far away from that corpse, and then if you try to loot it again it doesn't work.

How it works: Sometimes when you loot items on the ground it says You are too far away from that corpse, and then if you try to loot it again it doesn't work. https://www.twitch.tv/videos/338589629

How it should work: When you loot something at max range you should be able to pick up what is inside.

Source (you should point out proofs of your report, please give us some source):

**Comment by Avishai97** [comment]
https://gyazo.com/f586a71065ff990fd481b7e8432b1103 
Same concept but with opening a cage instead, no credit for opening at max range

**Comment by akrom23** [comment]
And those corpses?

**Comment by Avishai97** [comment]
It was the message i received when looting items on the ground such as 
http://wowwiki.wikia.com/wiki/Emitter_Spare_Part

**Comment by Avishai97** [comment]
And I didn't receive any loot from the item on the ground, and when i tried looting it again it did not work.

**Comment by Avishai97** [comment]
https://www.twitch.tv/videos/338589629

**Comment by akrom23** [comment]
Try logout and login.

**Comment by Avishai97** [comment]
Other people who were in the proximity of the item can't loot it either, people who are out of range when it bugs can come in and loot it, sure logout and login works but GL doing that on release if u get stuck on some early quest

**Comment by Trolltilla** [comment]
> Other people who were in the proximity of the item can't loot it either, people who are out of range when it bugs can come in and loot it, sure logout and login works but GL doing that on release if u get stuck on some early quest

Yeah this really can hurt the server when people can't get their quest items properly at the start of the server. Thousands of players will be fighting over mobs and quest items and when stuff like this happens people will get mad really fast.

**Comment by Wojtyas** [comment]
Fixed & implemented.
