### ISSUE TITLE
EM + NS Interaction not working properly

### ISSUE THREAD

**Issue by thedonnager** [SunwellWoW/Sunwell-TBC-Bugtracker#1725]
Decription: 
Elemental Mastery and Natures swiftness not interacting correctly.

How it works: 
The abilities overwrite each other when used together

How it should work: 
EM + NS should interact w/ the next spell being 100% crit and instant. 

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=rmgMsDGyCVE

**Comment by akrom23** [comment]
It works fine. @thedonnager Test it again.
