### ISSUE TITLE
[Spell] Chain Heal

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1727]
Chain Heal has probably two issues:

- [ ] "You're able to heal enemy faction charakters with Chain Heal and there might be potential to abuse this (in addition to that, you weren't able to do so in the TBC expansion). 
To reproduce this, simply cast chain heal on you or a nearby ally and it will jump on a enemy faction player."

- [x] Chain Heal suppose to be "smart" spell and each of jumps should target unit with lowest hp in jump range.

**Comment by badmannerkid** [comment]
worth mentioning that chain heal is also not jumping to hunter/warlock pets correctly. you have to directly target a pet with chain heal for it to jump to other pets. when targeting a player and casting chain heal the chain heal seems to not jump to pets off the main target player

worth replicating, will post again with affirmation. just something we noticed while testing last night

**Comment by doomnyx** [comment]
also, can somebody check:
http://us.battle.net/wow/en/game/patch-notes/3-2-0

> Chain Heal: Jump distance increased by 25% to 12.5 yards. In addition, the amount of healing now decreases by 40% as it jumps to each new target, instead of 50%.

Check if jump distance is 10 yds, as it should be.

**Comment by akrom23** [comment]
```
"You're able to heal enemy faction charakters with Chain Heal and there might be potential to abuse this (in addition to that, you weren't able to do so in the TBC expansion).
To reproduce this, simply cast chain heal on you or a nearby ally and it will jump on a enemy faction player."
```
Cannot reproduce. Need screenshots.

**Comment by Wojtyas** [comment]
First part works - won't jump on full hp targets.

Second part doesn't work - it won't jump to the lowest hp targets. It should have prio lowest hp > not full hp.

https://www.youtube.com/watch?v=nc7waKVzZU8
