### ISSUE TITLE
[Zone] Thahonda Ruins in Thousand Needles

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#1730]
Decription: 
- standing in the water trying to kill Stonesalt Mobs
- you pull & enter combat
- Mobs run to the edge of the water, stay there for 2 sec and evade
- you leave combat

Source (you should point out proofs of your report, please give us some source): 

![grafik](https://user-images.githubusercontent.com/45068171/48791021-016d1680-ecf1-11e8-9260-301552f9a94f.png)

**Comment by Wojtyas** [comment]
Fixed and implemented.
