### ISSUE TITLE
Magtheridon's Lair

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1731]
**TRASH**

- [x] Hellfire Warder’s Shadow Word: Pain is cast on entire raid at once. Everyone gets 3 Shadow Word: Pains on themselves all at the same time whenever the mob casts it
- [x] Hellfire Warder’s shadow word pain has unlimited range and casts on people that are out of line of sight as well
- [x] Hellfire Warder’s emote channel does not work correctly, only one warder is channeling - visibility?

**BOSS**

- [x] ~~Magtheridon should have 100% chance to drop Magtheridon's Head item (32385 - A, 32386 - H) For now he doesn't loot it.~~
- [x] Magtheridon should drop only 1 token, for now he drops 3.
- [x] Knockback doesn't seem to be knocking you back at all.
- [x] Conflagaration fire patches are much larger than they appear (this is consistent with a lot of spell effects on the server) .
Source: https://www.youtube.com/watch?v=QpgdAHJANcA#t=2m43s
https://streamable.com/4yx9d
- [x] Burning Abyssal Fire Blast hits for 2.5k - 3.5k, will one shot most people if two fall on stacked people or Shadowbolt Volley goes off at same time.
CoreCraft Soruce: Fire Blast: 1750-2250 
- [ ] Burning Abyssal can spawn up to three at the same time, should be spawning one at a time
https://streamable.com/foscu
- [x] ~~Burning Abyssal don’t despawn fast enough, we had about 10 up at one time.~~
- [ ] Burning Abyssal probably don’t despawn at all. It should despawn after 1 min once summoned.
- [ ] Burning Abyssal cast Fire Blast twice on one target, no spell cooldown?
- [x] Hellfire Channeler melee swing hit armor capped tank for 19k on 4 stacks of Soul Transfer. 4 stacks should be 80%, they’re hitting a bit too hard I think.
**Graal: If pure melee is 6000-10000 then with 4 stacks should be max to 18k pure melee if buffs are added or 20.7k if they are multiplied. And yet this melee dmg is even higher on stacks so I guess Soul Transfer spell has issue**
- [x] Manticron Cube: Player A clicks Cube A and channels, Player B clicks Cube B and channels but is interrupted, Player B’s cube click will cancel Player A’s channel
https://streamable.com/57a3w
- [x] Mag’theridon does not cast his Quake properly. First cast should be 30s after Mag’theridon is released, and then cast every 50 seconds subsequently.
Our PoV: https://streamable.com/3gsi4
SOURCE: https://www.youtube.com/watch?v=v0PNXZYuAnU#t=3m5s (Boss released at 3m5seconds and starts first quake at 3m36 seconds)
- [x] ~~Debris randomly hit one of our members for 83667. He was one of the last people alive. Could Debris be splitting dmg amongst raid members and doing more to these people becuase they were the only ones able to split Debris dmg?~~
~~Our PoV:~~
~~https://i.gyazo.com/4feed9e5799d8c6b7f89b818be678ec5.png~~
~~https://i.gyazo.com/177b915f3a68dc31ff08a8dcd574d76c.png~~
~~https://i.gyazo.com/4a7ccc72b58820c45627114b4a5045b1.png~~
~~https://cdn.discordapp.com/attachments/514291482396459018/514291705156206595/WoWScrnShot_111918_220956.jpg~~

**Comment by neheri** [comment]
Debris works in two ways:

1. At 30% when entering phase 3 Debris deals 5250-6750 physical damage plus a 2 sec stun to every raid member.
2. Sometimes rocks will start falling from the ceiling (similar to cave in gruul mechanics) and if player doesn't leave that spot debris will one shot that player. 

If this works the same way it was on HG I remember sometimes there was neither rocks dropping from the ceiling animation nor debuff and you still got one shotted by debris. 

There should be an animation and debuff and if player doesn't move is one shotted by Debris.

**Comment by notsofamous** [comment]
- Magtheridon's Head was added in 2.1, he shouldn't drop it.

- You should be able to have 10 Burning Abyssals up at the same time if you dont kill the warders fast enough (each warder can summon 2 of them). However there should be like a 30 sec CD?

**Comment by notsofamous** [comment]
Tested him on closed beta

- [x] Knockback doesn't seem to be knocking you back at all.
- [x] He's constantly doing his "fire breath" animation.
https://i.gyazo.com/cdb126b4b215ad1f06fe00775c4c6d53.mp4

- [x] AoE Debris worked fine for me while soloing (at 30%)
![Image](https://i.gyazo.com/447f7db1ed473ef418e30590aad3d555.png)
- [x] The falling debris also correctly hit for 100 000 damage.

**Comment by Silroth** [comment]
- Magtheridon's Head was added in 2.1, he shouldn't drop it. However he should only be dropping 1 chest token, not 3.

True but Blizzard corrected that mistake in 2.1 just like they did with 2.0 itemization, its a 1 boss raid and drops too few items for its difficulty.

**Comment by akrom23** [comment]
@Wojtyas

**Comment by badmannerkid** [comment]
Updated for Live server

- Hellfire Channelers do not reset to their proper start location after a wipe (This is a visual thing, and players that rezone see the Channeler in its proper spot. Very odd)
https://cdn.discordapp.com/attachments/347882981311905802/524058702378958860/unknown.png

- 5 channels on the Manicron Cubes does NOT cancel Mag'theridon's Blast Wave

If you need more information or need us to test further please contact me

**Comment by akrom23** [comment]
@badmannerkid The one who's standing weird, was not killed?
