### ISSUE TITLE
 [Taming the Beast] [Taming Totem] Pet Dismissing 

### ISSUE THREAD

**Issue by Tanesiris** [SunwellWoW/Sunwell-TBC-Bugtracker#1738]
Decription: The three different quests to tame 3 diffrent pets to earn the spell tame beast. The issue have been seen on alot of servers and the item in question is [Taming Totem].

How it works: Once the pet has been dismissed under the effect of [Taming Totem] it starts to running back to where it was tamed clipping through game objectives/buldings to its fastest way to reach the spawn point which looks very weird.

How it should work: Works like a normal pet dismiss the pet disappears and later respawns like a normal mob.

Source (you should point out proofs of your report, please give us some source):
![wowscrnshot_112018_193607](https://user-images.githubusercontent.com/16453643/48795475-53b43480-ecfd-11e8-976c-4559ceb65cef.jpg)
![wowscrnshot_112018_193608](https://user-images.githubusercontent.com/16453643/48795483-57e05200-ecfd-11e8-865b-839b27f2b8c7.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).
