### ISSUE TITLE
Damage scaling 

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1739]
Damage scaling seems to be completely broken. Tested on closed beta with 0 armor. 

### Gruul

8000-10000
+90%
28000-36000 (should be 15900-19000)

### Doomwalker

15700-20000
+100%
67000-81000 (should be 31400-40000)

### Hellfire Channeler

8000-12300
+30%
13000-20000
+60%
23000-31000
+90%
29000-44500
+120%
45000-61000
At this point damage should be roughly twice as much as before but it's almost 6 times as high.

**Comment by badmannerkid** [comment]
great work, saw this on hellfire channelers and gruul last night during testing as well

**Comment by notsofamous** [comment]
I tested 
Gruul with 6 growths (+90% damage)
Hellfire channeler for each add that dies (+30% damage for each killed add)
Doomwalker enrage (+100% damage)

I think it's new

**Comment by akrom23** [comment]
Okay.

**Comment by lukaasm** [comment]
seems like bug was introduced 30 days ago :p

**Comment by zapsuu** [comment]
I think it's general bug +/- % dmg
The same problem is with -% dmg (sickness)
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1546

We are waiting for fix live.

**Comment by lukaasm** [comment]
I am closing this one as duplicate, if anything post in #1546
