### ISSUE TITLE
[Hunter] [Pets] [Spell] Revive Pet 

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1740]
Decription: 
Hunter Revive Pet spell is reviving the pet at the pet's death location when the hunter is casting the spell more than 40 yds away from the pet's body from the Hunter's PoV. From another player PoV the pet is being revived correctly on top of the hunter

How it works: 
Revive Pet Bug - 

When a Hunter casts Revive Pet the pet should appear back at the Hunters feet. At the moment it's showing differently for the Hunter and any other player on the server.

When the Hunter casts Revive Pet, if over 40 yards away the Pet will appear at death location and then run to the Hunter, if you're under 40 yards as the Hunter, it will appear at your feet.

If you're another player watching a Hunter do this, regardless of his distance away from the dead pet, the pet will always appear at the Hunters feet.

I've documented this below with dual PoV videos.

OVER 40 yards - Cast Res (+Stay) = 
Hunter PoV: https://streamable.com/movjf
Other player PoV: https://streamable.com/6m7kc

OVER 40 yards away - Res (+Follow) = 
Hunter PoV: https://streamable.com/0ru56
Other player PoV: https://streamable.com/r4712

40 yards or UNDER - Cast Res (+Follow) = 
Hunter PoV: https://streamable.com/qq7u1
Other player PoV: https://streamable.com/sxf2

I also tested in a dungeon to see if mobs would aggro on pet res location to prove it is ressing on the location of death, rather than at the Hunters feet: https://streamable.com/71386

How it should work: 
When a Hunter casts Revive Pet the pet should appear back at the Hunters feet.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented (only SSC realm for now).
