### ISSUE TITLE
Star Trek related NPCs in The Exodar missing their walking route.

### ISSUE THREAD

**Issue by Tanesiris** [SunwellWoW/Sunwell-TBC-Bugtracker#1741]
Decription: There are some Star Trek related NPCs in Exodar in the Exodar Holographic Emitter. They are known to have a walking route and prehaps some sort of dialog im not sure. The npc are Curzon, Tobin, Torias, Emony, and Audrid.

How it works: Right now they have no walking route and are standing in a bunch in Holographic Emitter.

How it should work: They should walk around in a tour group in Holographic Emitter. 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_112018_200355](https://user-images.githubusercontent.com/16453643/48797044-7c3e2d80-ed01-11e8-80a6-6cab350b415a.jpg)

Source:
https://wow.gamepedia.com/Exodar_Holographic_Emitter
The holographical display of the various demons in the Vault of Lights.
The Exodar Holographic Emitter is located in the Vault of Lights in the Exodar. It shows information about the various Burning Legion demon projections. Whenever the group of draenei NPCs touring the area approach each hologram, the emitters state information about that demonic race.

The tour group is made up of five draenei: Curzon, Tobin, Torias, Emony, and Audrid.

**Comment by doomnyx** [comment]
Also, those guys are missing their dialogs and behaviors:
https://wow.gamepedia.com/Chakaa

**Comment by Tanesiris** [comment]
> Also, those guys are missing their dialogs and behaviors:
> https://wow.gamepedia.com/Chakaa

Yeah saw that now aswell :)
