### ISSUE TITLE
Silencing caster type mobs

### ISSUE THREAD

**Issue by Azathothh** [SunwellWoW/Sunwell-TBC-Bugtracker#1744]
How it works:  Currently when we silence npc's that are casters they stand still for a while, before starting to chase us (tested on 21370 - ethereal nethermancer and 5617 - wastewander shadow mage)

How it should work: I guess they should start chasing us right after being silenced.
If anyone have proof for that (video from tbc would be perfect) or thinks it's working like it should, please write about it in comments.

**Comment by MaceMaul** [comment]
Same thing with ANY primary Caster mobs in Ghostlands, for example the Wraith casters in Windrunner Spire

**Comment by popalexandrudan** [comment]
also in TBC dungeons, for example summoners in blood furnance just cast summons, and don.t move. The only way they will move is if the tank pulls agro and goes LoS. If some1 alse has agro and is not in rage, it will stand still
