### ISSUE TITLE
[Hunter] [Pet] Pathing

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1746]
Decription: 
If a hunter jumps down from elevation, the pet with attempt to run to the hunter's landing spot rather than the hunter's current spot

How it works: 
Pet Pathing - Ledge/Height Issue?

Clip shows jumping off a fairly high roof.
 
Pet goes to return to Hunter but will only return to the spot the Hunter initially landed in rather than readjusting to follow the Hunter when he runs back to where the pet is.

When the Hunter jumps off a lower roof, the pet readjusts himself to come straight to the Hunter and not become obsessed with the spot the Hunter landed in.

https://streamable.com/v70hq

How it should work: 
Pet should recalibrate its path to meet up with the hunter rather than pathing to the pet's last recorded position of the hunter

Source (you should point out proofs of your report, please give us some source):

**Comment by sicknot1** [comment]
Good finding

**Comment by lukaasm** [comment]
Added not totally blizzlike QoL change ( same as in our Wotlk) that pet will jump together with the owner if the path after jump is to long.

Ofc, this is disabled in PvP environment.

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).
