### ISSUE TITLE
[Quest] Tribal Leatherworking

### ISSUE THREAD

**Issue by Gedlund** [SunwellWoW/Sunwell-TBC-Bugtracker#1747]
Decription: 
Unable to get Tribal Letherworking on the test server as the NPC Se'Jib dosen't give you a quest.

How it works: 
Se'Jib allows you to train all of the recipies for Tribal Letherworking without completing a quest first.
(Windhawk Hauberk)
(Windhawk Belt)
(Windhawk Bracers)

How it should work: 
Se'Jib should offer the player a quest where he asks for a (Wild Leather Vest) and a (Wild Leather Helmet)
Upon completion he should teach you "Tribal Leatherworking" and make you able to wear the gear. 

Source (you should point out proofs of your report, please give us some source): 
https://tbc-twinhead.twinstar.cz/?quest=5148

**Comment by Dootz** [comment]
Requirements:
- Level 40
- Leatherworking at 225
- Horde
- Dragonscale leatherworking Or Elemental Leatherworking not taken
