### ISSUE TITLE
[Hunter] [Pets] [Spell] Mend Pet

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1748]
Decription: 
Hunter Improved Mend pet spell is removed friendly buffs instead of removing non friendly debuffs

How it works: 
Improved Mend Pet - Talent Bug

Casting Mend Pet with the Improved Mend Pet talent causes any friendly buffs to be dispelled from your pet.

The talent will frequently cause the pet to dispel all of it's own magic buffs, including it's own Mend Pet.

Video shows testing 1/2 and 2/2 Improved Mend Pet with the talent causing friendly magic buffs to be dispelled.

The talent should give a chance (25%/50%) to cleanse Curse, Disease, Magic or Poison effects from the pet with each tick.

https://streamable.com/uxfqk

How it should work: 

The talent should give a chance (25%/50%) to cleanse Curse, Disease, Magic or Poison effects from the pet with each tick.
Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).
