### ISSUE TITLE
[Hunter] [Spell] Misdirection

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1749]
Decription: 
Misdirection charges are not consumed when using distracting shot, but the threat from distracting shot is being redirected

How it works: 
The Misdirection spell when casted gives 3 charges in which 3 Hunter shots will redirect threat to the target you have casted Misdirection on.

Currently Distracting Shot is not consuming charges from Misdirection but it is still redirecting threat as shown in the video.

Distracting Shot should consume charges on this spell.

https://streamable.com/2zyp5

How it should work: 
Should consume the charges when using distracting shot

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Distracting_Shot

**Comment by akrom23** [comment]
Distraction Shot does not deal damage, so that's why it is not considered as an attack that consumes Misdirection charges.
@badmannerkid Got some proof from retail?

**Comment by akrom23** [comment]
No response.
