### ISSUE TITLE
[Stormwind/Quest] Buggy 

### ISSUE THREAD

**Issue by Hnidka** [SunwellWoW/Sunwell-TBC-Bugtracker#175]
Decription:  Chain Quest :
                                        1. Better Late Than Never : ID : 5022
                                        2. Good Natured Emma : ID : 5048 Ends at : Ol' Emma Guid 79796 , Entry 3520 

How it works: Heh it was a quite pita to find her :D there are more npcs 
![wowscrnshot_082018_211026](https://user-images.githubusercontent.com/42386888/44361816-59f90180-a4bf-11e8-8988-55a899e8ae7d.jpg)
![wowscrnshot_082018_211041](https://user-images.githubusercontent.com/42386888/44361820-5d8c8880-a4bf-11e8-9e90-0ffd349e7ac0.jpg)

How it should be: That slut have her own house + she walk around her house to AH 
http://db.hellfire-tbc.com/?npc=3520

https://vanilla-twinhead.twinstar.cz/?npc=3520#starts  -- her route

**Comment by Dootz** [comment]
works fine now
