### ISSUE TITLE
[Hunter][Spell] Feign Death clearing Mob Threat Table

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1751]
Decription: 
Hunter's Feign Death will completely reset the threat table of the mob rather than reset the threat that the hunter personally has on the mob

How it works: 
Hunter has primary threat on the mob, casts feign death and the mob will reset regardless of whether or not other players are also on the mob's threat table

https://streamable.com/b8hoz

Even if a different player aggros the mob first, and the hunter pulls threat on the mob and then feigns death the mob will still reset instead of going to the player that had originally pulled the mob and is in combat with the mob. You'll also see below that even when the hunter and the hunter's pet are in combat with a mob, and the hunter feigns; the mob will reset instead of just going on the hunter's pet

https://streamable.com/fsjgi

https://streamable.com/w4384

How it should work: 
When multiple people are in combat with a mob and the hunter pulls primary threat and feigns death, the mob should then target the next player on the threat list. Instead, the hunter's feign death appears to be completely clear the threat list of the mob entirely

> he hunter loses all aggro, which causes the enemy to stop attacking them and either flee back to its "territory", attack the hunter's pet, or attack whomever has the next highest threat.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Feign_Death

**Comment by akrom23** [comment]
@badmannerkid Cannot reproduce it.
Still happens?
