### ISSUE TITLE
[Pets] [Movement] Pets sink to bottom of water

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1752]
Decription: 
Pets won't swim with the player, they will sink to the bottom and ride the floor pulling lots of mobs in the process.

How it works: 
Pets won't swim with the player, they will sink to the bottom and ride the floor pulling lots of mobs in the process.
Hunter (on SSC PVP Realm): https://streamable.com/k8z8m
Mage (on SSC PVP Realm): https://streamable.com/boq86

How it should work: 
The version of how it should work is seen here:
Mage (on Warmane Outland Realm): https://streamable.com/kj1lj

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/kj1lj

**Comment by badmannerkid** [comment]
might have something to do with #370

**Comment by Wojtyas** [comment]
Fixed & implemented.

![image](https://user-images.githubusercontent.com/22802214/48944050-86d90c80-ef25-11e8-9dda-bf5db306fb40.png)
