### ISSUE TITLE
Critical Strikes Generating AoE Threat?

### ISSUE THREAD

**Issue by Euphemistic** [SunwellWoW/Sunwell-TBC-Bugtracker#1753]
Decription: Sent my pet into a pack of 5 or so mobs, and attacked the one that my pet was on. (single target) Everything stays on my pet until I get a critical strike, and then every mob I'm in combat with that I have not attacked starts to attack me.

How it works: Critical strikes seem to generate threat on all mobs near the target that you critically hit.

How it should work: Mobs should all stay on whatever pulled them (my pet) as long as the target that the mobs are on doesn't get healed, or the mobs don't get cleaved etc. If I had cast Mend Pet or something like that, then that should generate threat and the mobs should attack me, but I didn't.

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/a4m25 Notice that none of them attack me until I get a critical strike with Steady Shot

**Comment by YoshGit** [comment]
I notice that you have a buff that looks like spirit bond up. Might be worth investigating if that is the root cause as I know it has a healing component. Still a bug imo, but I’m curious.

**Comment by Euphemistic** [comment]
@YoshGit I checked to make sure it wasn't spirit bond. In the video you can see after I pulled I get a heal tick for 57, that was spirit bond. Threat wasn't ripped until a couple seconds after that when I got that 800 crit with Steady Shot. I believe if it was spirit bond, as soon as that tick healed me threat would've ripped instantly and they would've all attacked me considering my pet didn't have any threat on any of them. I also just tested it again and got 2 ticks of spirit bond this time without attacking and still didn't get any aggro, started attacking and as soon as I crit I ripped aggro on everything again.

**Comment by notsofamous** [comment]
Mana regen is a source for AoE threat, you gain +50 mana twice when get aggro.

**Comment by Wojtyas** [comment]
Invalid report. Single-target crits don't generate aoe threat.
