### ISSUE TITLE
Mobs Not Chasing Hunter

### ISSUE THREAD

**Issue by Euphemistic** [SunwellWoW/Sunwell-TBC-Bugtracker#1754]
Decription: If you send your pet in to attack a mob and it gets the first attack, and then you rip aggro off of your pet, the mob stays stationary and doesn't chase you even though you have aggro on it and it is targeting you. I have also noticed however, that this only happens to mobs that cannot fly. The vultures in Hellfire will chase if I get aggro. I also assume this works the same way with warlock pets as well, but not sure.

How it works: 

How it should work: Mob should chase you when you get aggro off of your pet.

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/jxoqe There is also another example in here of me getting aggro on mobs I have not attacked. When fighting the two ravagers at the beginning the 2nd ravager that I didn't attack started targeting me after I got a critical strike. However it also stayed stationary after my pet pulled it first.

**Comment by akrom23** [comment]
#1756.
