### ISSUE TITLE
[Hunter] [Pet] Reload UI will remove your pet bar

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1755]
**Decription:** 
Reload UI will remove your pet bar and not allow you to use any pet ability

**How it works:** 

When you reload UI while your pet is active, your pet bar disappears and you cannot cast such spells as Petattack, Pet abilities like Lightning Breath or Growl, and you cannot cast abilities such as Mend Pet or Feed Pet. The only thing that fixes this is dismissing and resummoning your pet.
https://streamable.com/wdu3y
https://streamable.com/oajyk

**How it should work:** 

When you reload UI it should restore your UI, not remove elements from it. 

**Source (you should point out proofs of your report, please give us some source):** 

https://wow.gamepedia.com/API_ReloadUI

**Comment by doomnyx** [comment]
Happens for warlock sometimes

**Comment by Wojtyas** [comment]
@doomnyx can you retest it please?

**Comment by doomnyx** [comment]
seems gyyyd

**Comment by Wojtyas** [comment]
:heart: 
Fixed & implemented.
