### ISSUE TITLE
Mobs Following Hunter While Attacking Pet

### ISSUE THREAD

**Issue by Euphemistic** [SunwellWoW/Sunwell-TBC-Bugtracker#1756]
Decription: I made a post earlier about how when your pet pulls mobs and you pull aggro off of your pet, the mobs will stand in place while targeting you. However, if the player pulls a mob instead of the pet, and the pet gets aggro on the mob, the mob will still chase the player while attacking the pet.

How it works: 

How it should work: Mob should stand still while attacking the pet, and if the mob is on the player it should run to the player, not stand still.

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/ff2zn
https://streamable.com/jxoqe here is the video of the mobs standing still when the pet pulls

**Comment by Avishai97** [comment]
Same issue with two players pulling threat of eachother, not just hunter / pet

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1778
