### ISSUE TITLE
[Druid][Talent] Primal Fury does not always give two combo points

### ISSUE THREAD

**Issue by bigripper** [SunwellWoW/Sunwell-TBC-Bugtracker#1757]
Decription: Primal Fury talent is supposed to grant you two combo points when you crit with an ability (mangle, claw, etc). 

How it works: Sometimes does not give two combo points. I would say 30-40% of the time. =

How it should work: Should give two combo points 100% of the time when you crit with a cat combo point builder ability.

Source (you should point out proofs of your report, please give us some source): Dont have any proof because I dont make videos, but this was a bug on Feenix's ArchAngel server back in 2012. Devs refused to fix it for a long time because they said it was a "visual bug" but I finally convinced them otherwise.

**Comment by zapsuu** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1281
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1498

**Comment by Wojtyas** [comment]
Already reported. Will be fixed soon ;)
