### ISSUE TITLE
Goblin Commoners in Booty Bay

### ISSUE THREAD

**Issue by Sabre142** [SunwellWoW/Sunwell-TBC-Bugtracker#1760]
Description: 
There are two Goblin Commoners in Booty Bay giving a Midsummer Fire Festival quest, despite it not being Midsummer currently.

How it should work: 
They should only be there during the Midsummer holiday, and other holidays. https://wow.gamepedia.com/Goblin_Commoner

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_112118_215619](https://user-images.githubusercontent.com/26516348/48837143-a282cc80-edd8-11e8-8a2d-cf44d7f3b8bd.jpg)

**Comment by Azathothh** [comment]
already reported here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1718
