### ISSUE TITLE
[General]Step in Duskwood(Adlle Stead) 

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1761]
Decription: 
I already have seen reports about buggy 1st steps on stairs etc. It affected players. Now i have seen also a problem with mobs trying to pass it. They cannot.

How it works: 
Mob is stuck at first stair, he was in the house before attacking, he cant reach me.
![image](https://user-images.githubusercontent.com/43579401/48837145-d0d6bc80-ed84-11e8-83a2-43d945523baa.png)

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Looks like general issue same as here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1535

**Comment by Wojtyas** [comment]
Fixed & implemented.
