### ISSUE TITLE
[Quest] Reputation bug

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1768]
Decription: 
Completing 'Morbent Fel' quest should give you 150 rep with gnomeregan and 500 with stormwind

How it works: 
got 165 with gnomeregan(human racial with 10% rep, thats why more)
![image](https://user-images.githubusercontent.com/43579401/48845131-00dd8a00-ed9c-11e8-85e1-617bd511a89e.png)

How it should work: 
I should also become 500 reputation with stormwind for completing this quest.

Source (you should point out proofs of your report, please give us some source): 
https://tbc-twinhead.twinstar.cz/?quest=55

**Comment by Wojtyas** [comment]
Fixed & implemented.
