### ISSUE TITLE
[PvE][Dungeon] Sethekk Halls starting pulls

### ISSUE THREAD

**Issue by Ibuprofeno** [SunwellWoW/Sunwell-TBC-Bugtracker#1771]
Decription: Sethekk Halls starting pulls should patrol to the entrance. At the moment only one of the patrols (the one with the bird) walks.

How it works: First two defenders stay still behind the chandeliers.

How it should work:  They should walk up to the entrance (a bit closer to the entrance from where they currently stand.)

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=QvOvY0l_nsI retail

**Comment by Wojtyas** [comment]
They are patrolling actually ;O

![image](https://user-images.githubusercontent.com/22802214/48868051-9eef4580-edd8-11e8-900d-5b0367432eb3.png)
