### ISSUE TITLE
[PvE][Dungeon] Bog giants before Hungarfen aren't linked.

### ISSUE THREAD

**Issue by Ibuprofeno** [SunwellWoW/Sunwell-TBC-Bugtracker#1774]
Decription: 
Bog giants before Hungarfen in Underbog aren't linked and can be pulled one at a time.

How it works:  They aren't linked.

How it should work: They should be linked.

Source (you should point out proofs of your report, please give us some source): https://youtu.be/_fWgnggYZ3g?t=502

**Comment by badmannerkid** [comment]
https://www.youtube.com/watch?v=CRMNLQtsxig

decent source
