### ISSUE TITLE
[PvE][Dungeon] Ghazan in Underbog resets when being tanked back to the wall.

### ISSUE THREAD

**Issue by Ibuprofeno** [SunwellWoW/Sunwell-TBC-Bugtracker#1779]
Decription: 
Ghazan resets combat when you tank it with your back to the wall at the start of the entrance to the platform.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Can u make screenshots or something? There is no wall on his platform.

**Comment by Ibuprofeno** [comment]
https://youtu.be/Daq_80QIM34?t=23 I can't make a screenshot as I don't have a party to clear to it again this is the wall I'm referring to.

**Comment by Wojtyas** [comment]
Got it. Thank you.

![image](https://user-images.githubusercontent.com/22802214/48866430-1d48e900-edd3-11e8-94a3-7fe2a8f67bd5.png)
