### ISSUE TITLE
[Raid] Karazhan - PART ONE

### ISSUE THREAD

**Issue by Adamsek** [SunwellWoW/Sunwell-TBC-Bugtracker#178]
Overall notes:
- [ ]  **Melee damage** of monsters need to be increased. Mobs and bosses as well hit too low. +50% damage increase could be enough and should be tested again. **Damage from spells is OK though, not needed to be changed.**
- [x]  Mobs are ignoring effect of charm, gouge, blind, snare. They are just damaging the player which they CC'd. Other cc than stun and fear, should force mob to change his target.
- [x]  **Mobs should use their abilities way more often. Some spells are used once throughout whole fight. I could stand for 5-6 minutes and minion won't use his spell for a 2nd time. This apply almost to every mob (most of bosses were ok, if any of them should use something more often i will write it down)**
- [x]  Same as Gruul's Lair trash: '_When one minion from a pack is killed and other is not after raid-wipe the killed one should respawn, for now killed mob is not respawning._'
- [x]  Some patrols have weird movements, some of them have 'run n stop' stuff - waiting for 2nd mob from patrol to come. When patrol gain and lose combat in tiny amount of time (pull and vanish, for us that was UBER STEALTH), they are freezing in one place, won't back in their patrol-path.
- [ ] Badge of Justice should't drop from bosses.

**These things listed above will apply to whole Karazhan - not only part one mobs.**

- [ ] **Apprentice Darius** near Karazhan entrance shouldn't sell 4 of his items: Pattern: Cloak of Darkness, Pattern:Shadowprowler's Chestguard, Formula: Enchant Weapon - Greater Agility and Recipe: Flask of Chrmoatic Wonder.
- [x] There is no **attunement** implemented yet.
- [x] After entering i don't think that Concubine should yell...
![wowscrnshot_081918_135138](https://user-images.githubusercontent.com/42385556/44407831-5b7a0680-a55f-11e8-955d-af4a1c0d9cc3.jpg)
- [x] **Spectral Charger** doesn't use his charge and fear properly. He should charge member of raid (minimum of 8y) and AoE fear at the same time, instead of it he charges in melee range and has no visual effect of it.
- [x] **Spectral Apprentice** doesnt' use his Burning Brand spell.
http://db.hellfire-tbc.com/?npc=16389#abilities
- [x]  Trash before Midnight respawns too fast, that was 20-30 minutes, should be about 1 hour at least
- [x] **Attumen the Huntsman** should use his abilities more often
- [x] **Midnight** should use her abilities more often
- [x]  The whole fight is bugged, after reaching certain amount of percentage HP, they should connect, but they just don't... and won't die...
![wowscrnshot_081918_145109](https://user-images.githubusercontent.com/42385556/44408691-2b336780-a561-11e8-82fa-9eab79a12dd7.jpg)
![wowscrnshot_081918_145523](https://user-images.githubusercontent.com/42385556/44408699-2d95c180-a561-11e8-8a06-04e486879025.jpg)
- [x] **Spectral Sentry** has bugged his range/melee attacks, when tank run in and out of melee range they stop shoot and stand still.
- [x] **Skeletal Waiter**'s spell **Brittle Bones** is not triggering on a player
http://db.hellfire-tbc.com/?npc=16415#abilities
- [ ] Minions in Banquet Hall, and in rooms connected with it have some really weird level changes. Before pull they were 65-66 lvl, after reset they were 70-71 (which is appropriate) and then after pull again, they changed their lvls to 65-66 and so on. Only Moroes stays with same Boss level, even his adds were changing levels. I dont know if its visual but we didn't notice damage change.
- [x] Trash in Banquet Hall and in rooms connected is respawning even if Moroes is killed. Moreover their respawn is bugged... **"One chair to rule them all?"**
![wowscrnshot_081918_213107](https://user-images.githubusercontent.com/42385556/44409568-ec061600-a562-11e8-98a8-3f992b2a0854.jpg)
![wowscrnshot_081918_213240](https://user-images.githubusercontent.com/42385556/44409599-fa543200-a562-11e8-8d9a-3c9bb5287ad6.jpg)
- [x] There were two **Moroeses** in Hall, one on the top of each other, also all of the adds were spawned, two of them twice
- [x] **Moroes pull** was broken, adds died, Moroes stood in place, then adds respawned, got combat and they were staying at spawn place for the moment... seems that whole fight is really broken
- [x] **Baron Rafe Dreuger** deals no damage with his seal of command.
- [x] **Lady Catriona Von'Indi** should use his abilities on friendly targets, she use it on herself only
- [x] **Baroness Dorothea Millstipe** has broken Mind Fly, she doesn't finish casts of it
- [x] Adds from Moroes fight shouldn't give reputation when killed.
- [x] **Shadikith the Glider** doesn't use any of his abilities
http://wowwiki.wikia.com/wiki/Shadikith_the_Glider
- [x] **Hyakiss the Lurker** doesn't use any of his abilities
http://wowwiki.wikia.com/wiki/Hyakiss_the_Lurker
- [x] **Rokad the Ravager** he didnt't spawn but im pretty sure that... he doesn't use any of his abilities
http://wowwiki.wikia.com/wiki/Rokad_the_Ravager
- [x] **Shadowbat** doesnt use his **Dark Shriek** ability
http://db.hellfire-tbc.com/?npc=16173#abilities
- [x] **Coldmist Widow** doesnt use his **Frost Mist** ability
http://db.hellfire-tbc.com/?npc=16171#abilities
- [x] **Coldmist Stalker** is staying in his **Sneak** ability even if he's attacking
- [x] We cannot check monsters like Vampiric Shadowbat, Dreadbeast, Shadowbeast and Phase Hound becouse...
https://www.youtube.com/watch?v=TqwYit0ssC0
- [x] **Concubine** doesnt use **Seduction** and **Tormenting Lash**
http://db.hellfire-tbc.com/?npc=16461#abilities
- [x] **Maiden of Virtue** doesnt use his Holy Ground ability
http://wowwiki.wikia.com/wiki/Maiden_of_Virtue
- [x] **Skeletal Usher** should be immune to any kind of CC, also they should switch targets after they use Ice Tomb on tank, they are ignoring it  (seems to be same issue as charms and blind)
- [x] **Spectral Performer** - his **Spotlight** ability should also affect raid players
http://db.hellfire-tbc.com/?spell=29683
- [x] **Phantom Stagehand** has bug with **Mallet Toss** should stand still and use it right after pull, but he just run an attack with melee (should run when player is in loss)
- [x] **Julianne** doesnt use **Eternal Affection** on Romulo in Phase 3 (just healing herself)
- [x] **Romulo** doesnt use **Backward Lunge** ability, **Deadly Swathe** is broken, he hits random target ignoring range, he should strike it in front of him (up to 3 targets)
http://wowwiki.wikia.com/wiki/Romulo_and_Julianne
- [x] Only one item drops from **Julianne&Romulo** fight.

_(We didnt check other Opera encounters, TBD in next parts)_

**Comment by notsofamous** [comment]
https://github.com/Schaka/TBC-research/issues/11
