### ISSUE TITLE
[PvE][Dungeon] Underbog The Black Stalker summonned adds.

### ISSUE THREAD

**Issue by Ibuprofeno** [SunwellWoW/Sunwell-TBC-Bugtracker#1780]
Decription: The Black Stalker summons about 4 adds every 2 seconds after ~10 seconds into the fight.
This was it https://gyazo.com/6e50c37bdfa76a4d98a0bbd0eb83ba1d

How it works: The Black Stalker summons about 4 adds every 2 seconds after ~10 seconds into the fight.

How it should work: Spore Strider Adds (Heroic only): Throughout the fight, the Black Stalker will spawn sets of three ~5000 HP adds every 10-15 seconds that will cast 1000 nature damage lightning bolts at targets. These adds are immune to fear. 

Source (you should point out proofs of your report, please give us some source): 
Spore Strider Adds (Heroic only): Throughout the fight, the Black Stalker will spawn sets of three ~5000 HP adds every 10-15 seconds that will cast 1000 nature damage lightning bolts at targets. These adds are immune to fear.  http://wowwiki.wikia.com/wiki/The_Black_Stalker

**Comment by Wojtyas** [comment]
Boss spawns new adds in correct intervals 10-15 seconds.

I assume you were killing those adds and thats the reason of their amount. When you kill one add three more will appear upon its death. The point is you have to kite them instead of killing, or just simply burn the boss before he spawns to many of them.

**Comment by Ibuprofeno** [comment]
I don't think we'd killed any add when they started spawning in groups. I'd checked it's wowwiki and wowhead page (for both TBS and it's adds) and couldn't find that they spawned faster where'd it come from?
https://www.wowhead.com/npc=22299/spore-strider#comments 
http://wowwiki.wikia.com/wiki/The_Black_Stalker
quoting from the latter : 
"Adds

The adds in heroic mode are the only things that seem to bring about a wipe on this boss. The spawn rate can sometimes seem like a lot faster than every 10 seconds and then in other encounters the adds hardly materialise at all. Generally there will be 3 or 4 adds at once **and they can be burned very quickly** with decent dps or ignored completely if they spawn towards the end of the encounter."
