### ISSUE TITLE
[Mechanic][Partial Resist]

### ISSUE THREAD

**Issue by Ibuprofeno** [SunwellWoW/Sunwell-TBC-Bugtracker#1781]
DISCLAIMER: THIS REPORT CONTAINS A COPY PASTE OF vexxedd's POSTS IN L4G'S GITHUB AS IT CONTAINED MOST OF THE INFORMATION REQUIRED FOR A PROPER REPORT AND BECAUSE I DECIDED TO TEST THIS ON THIS SERVER BECAUSE OF SAID POST.

> 1. Binary Spell vs. Non-Binary Spell
> 
> Talking about spells, there are different types of them. Instant spells, cast spells, spells that are doing instant damage, spells that are providing DoT effect, spells that are doing damage and providing some CC (frost nova). But all spells in WoW are determined by hidden value Binary or Non-Binary.
> 
> http://wowwiki.wikia.com/wiki/Resistance?oldid=2297931
> 
>     Binary spells are spells which deal a debuff (like Frost Nova or Vampiric Embrace)
> 
>     Non-binary spells are spells which only deal damage (like Fireball or Shadow Bolt)
> 
> Here is another description by Blizzard:
> 
>     Binary - "most spells"
>     Non-binary - "direct-damage spells (spells that deliver their full damage upon impact, such as Fireball, Mind Blast, and Earth Shock)"
> 
> There are few tricks and exceptions though:
> 
>     All DoTs are Non-Binary spells.
> 
>     DoTs used to be binary spells, but this was changed. (PROOF. Also, great proof of that is Arena, you can see difference in DoT ticks.)
> 
>     Frostbolt is also Non-Binary spell in TBC.
> 
>     Frostbolt is no longer a Binary Spell. (PROOF. Also, great proof of that is Duel against warlock.)
> 
>     Drain Life is Binary spell.
> 
>     Life Drains are always binary effects, as such they can only hit or miss, there are no partial resists. Some creatures, generally constructs, are immune to life draining effects. (PROOF.)
> 
>     Blizzard should be Non-Binary spell
> 
>     Blizzard is a channeled DoT spell and therefore cannot critically hit (PROOF)
> 
> So taking in mind those points we can assume:
> 
>     Binary are all spells with some sort of CC debuff, slow effect or mana burn effect, excluding Frostbolt as exception (Fear, Silence, Counterspell, Frost Nova, Mind Flay, Death Coil, Drain Mana, Drain Life, Mana Burn, HoJ etc.)
>     Non-Binary are all other spells, that do damage instantly or as DoT effect, or both (Corruption, Vampiric Touch, Immolate, Firebolt, Shadow bolt, Earth Shock, Blizzard etc.)
> 
> This is very important gradation because there are 2 rules which are working depending on whether it is Binary Spell or Non-Binary Spell.
> 2. Binary Resist
> 
> http://wowwiki.wikia.com/wiki/Resistance?oldid=2297931
> http://wowwiki.wikia.com/wiki/Formulas:Magical_resistance
> https://web.archive.org/web/20090206211016/http://www.worldofwarcraft.com/info/basics/resistances.html
> 
>     For binary spells: resistance reduces the chance for the binary spell to land by a certain percentage.
> 
>     The higher your resistance score in relation to the level of the attacking caster, the higher your average resistance percentage, up to a maximum of 75%. Against most spells, this resistance percentage is the straight % chance to completely resist the spell. ("most spells" here - are Binary Spells)
> 
>     For binary spells, both spell penetration and spell hit rating can be used to overcome resistances.
> 
> If 1 point of penetration just removes 1 point of resistance (PROOF), spell hit formula on Binary spells is a little different.
> https://web.archive.org/web/20080518164254/http://www.wowwiki.com/Spell_hit_rating
> 
>     For binary spells that do not partially resist, the resistance mitigation is combined with the spell hit chance to give an overall percentage for the spell to land or be resisted. The chance to hit is multiplied by the mitigation factor from the resistance to give an overall chance to hit. For the following formula, B is base chance to hit with spells, H is increased chance to hit from gear and talents, and R is the mitigation factor given from resistance.
> 
> (B + H) * R
> 
>     For example, a caster with 6% increased chance to hit, attacking a mob 3 levels higher (83% base chance) that has enough resistance to mitigate 50% of spell damage, the overall chance to hit with a binary spell is 44.5%
> 
> (83% + 6%) * 50% = 44.5%
> 
> What is mitigation factor from resistance? Well it's bascially "Average Resistance".
> Formula for "Average Resistance"
> 
> Average Resistance = (Target's Resistance / (Caster's Level * 5)) * 0.75
> 
>     Why is it called "average resistance"? For spells that have a non-damage effect—such as slow, root, stun - you'll either take the hit or avoid the hit altogether; these are examples of binary spells. The average resistance is the chance you'll totally avoid the hit. Adding the word "average" is a little redundant in this case.
> 
> If we try to cast Silence (on a warlock with 70 shadow resist (non-undead with 5/5 Master Demonologist) on the long distance we should have 15%+(1% miss with bonus 3% hit rating) resist.
> 
> Resistance = (70 /( 70 * 5)) * 0.75 = 15%
> 
> If we add for example 40 spell penetration with pvp off hand and cast Silence on the same target, calculation will be like this
> 
> Resistance = ((70-40) / (70 * 5)) * 0.75 = ~6%
> 
> Here is table of SpellHit vs Level in PvP and PvE.
> resist vs level
> Level 70 player will have 96% chance to hit another Level 70 player without any hit rating.
> Take in mind that, there are always 1% miss chance, or in other words, maximum SpellHit is 99%.
> 
>     Chance to hit can be increased by talents or gear with spell hit rating up to a cap of 99%.
> 
> Also
> 
>     Talents and gear combined, chance to hit with spells cannot exceed 99%
> 
> So if you PvP spell hit capped (3%) there will be NO difference, if you have additional spell hit on items or spell hit on talents.
> However
> 
>     Note that some classes (for example Paladins and Rogues) can spec to gain extra chance to have spells miss them. Also, some abilities (e.g. - Cloak of Shadows) gives the player using the ability extra chance to have spells miss as well. Extra spell hit does in fact mitigate this extra chance to miss, but is otherwise useless.
> 
> This should be taken into considering.
> 3. Non-Binary Resist
> 
>     For non-binary spells, resistance increases the chance to suffer only a fraction of the spell's normal damage. In The Burning Crusade, the percent resisted had a chance to be 0%, 25%, 50%, 75%, or 100%. The probabilities were weighted such that the average damage mitigated worked out to the same percentage as with binary spells.
> 
> https://web.archive.org/web/20080113124757/http://www.wowwiki.com/Resistance#Resistance_caps
> 
> Instead of Resist/Hit Non-Binary spells are rolled to do 100% (full effect)/75%/25%/0% (full resist) of damage
> 
> Table of Resist level
> You can only mitigate Non-Binary resists with Spell penetration.
> So if you are warlock, with 70 resists and eating Pyroblast in your face, you have 54% to take full damage of that Pyroblast, and another 46% distributed between 25%/50%/75% damage reduction. With that level of resistance, you have 0% to fully resist that spell (Take in mind, there are always 1% MISS chance, that also described as "resist" in BC).

After this long wall of text I'll explain what/how I tested.

At first, I wanted to figure out partial resists on non-binary spells and I did this against 2 different classes/resist amounts. I spammed r1 Frostbolt at a Dwarf Rogue with 48 frost resistance, 2/2 Fleet Footed (10% movement impairing effects resist chance) and Surefooted (5% snare/root resist) only fully resisted one (there's always a 1% miss chance that can't be capped) but no FB slow/frostbite/frost nova were ever resisted. https://gyazo.com/8eec541eab9f748a25108b90bf79949e average dmg was 62.

With ~22 more resist warlock's received dmg is very similar ( ~61 taking SL's dmg into account) https://gyazo.com/80f4e6deafcf36fe9450f221f87bc597 , however warlock's pet (98 resist, 70 from talents +28 from warlock's own scaling) took ~10 less dmg compared to the ~22 resist difference and only ~1dmg diff between the rogue and the warlock.  https://gyazo.com/588023196b81d57d9a8f6a38253eea84 Though it resisted much more often.

- What's wrong at the moment - 
It seems %resist to slows/snares/roots isn't working properly as they should give a higher chance to resist the whole spell. 
Warlock's resist chance due to resistances seem a bit low, pet looks okay.
Resisted elemental dmg isn't shown in the combat log.

**Comment by Ibuprofeno** [comment]
I believe I made a mistake and the dmg reflected when attacking the lock isn't accurate as my mage had full pvp gear with ~64 spellpen will need to retest without any spellpen for accurate warlock resists.
Still think resisted dmg should be shown in the combat log.

**Comment by ZaoQ** [comment]
Frostbolt is also Non-Binary spell in TBC. **WRONG**, frostbolt is a binary spell, no partial resists, frostbolt was changed to non-binary spell in 3.0.2 or something like that

**Comment by Wojtyas** [comment]
@ZaoQ You mean in pvp? Or both pvp+pve.

**Comment by ZaoQ** [comment]
I dont think that spell can behave differently in pve/pvp but yea in pvp for sure it is a binary spell. A cry of wotlk mages spreads across all cosmos.

**Comment by koostosh** [comment]
> It seems %resist to slows/snares/roots isn't working properly as they should give a higher chance to resist the whole spell.

Why? Each spell effect can be resisted separetely, %resist to movement impairing effects affect only slow/snare/root, not the damage.

I see resisted elemental damage in combat log
