### ISSUE TITLE
"Defiance" the Protection [Warrior] [talent] does not add the 6 Expertise.

### ISSUE THREAD

**Issue by Fleshdoll** [SunwellWoW/Sunwell-TBC-Bugtracker#1783]
Decription: 
Defiance the Protection Warrior talent does not add the 6 Expertise.

How it works: 
I have 0 added Expertise eventhough I specced 3/3 Defiance.

How it should work: 
I should have 6 more expertise if Im 3/3 Defiance.

Source (you should point out proofs of your report, please give us some source): 
![ss](https://user-images.githubusercontent.com/45242050/48862293-34cda500-edc6-11e8-995d-45d2bcae3093.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented.
