### ISSUE TITLE
[Tree's Company][Quest]

### ISSUE THREAD

**Issue by Tanesiris** [SunwellWoW/Sunwell-TBC-Bugtracker#1785]
Decription: The quest about you hiding as a tree to identify whos the traitor, The quest is greatly scripted here but there is one small issue the quest wont complete after the event is done. This breaks the quest chain and you cant keep playing further.

How it works: A thing i notice was that after the event was  done the npcs left and was standing still for a sec and just died and disappeard this works but not very visual appealing.

How it should work: After the script is done they should run off and dissappear and the quest should complete which in this case it dont.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_112118_202851](https://user-images.githubusercontent.com/16453643/48864472-f2f42d00-edcc-11e8-8fc8-10e407ec87c5.jpg)

**Comment by Krefty** [comment]
Same issue happened today

**Comment by vasilisxd** [comment]
I confirm the Quest works fine , says Objective Complete , but at the end , it doesn't give you the "Complete". BUT ! when you go to the Quest Giver , it Gives you the Exp and completes the Quest.
