### ISSUE TITLE
Rogue - combo points (full points all time)

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#1786]
Decription: 
even after i used finishng skill, i had 5 combo points on my target. "all time up"

How it works: 
https://youtu.be/r-YxCwIixK4 

How it should work: 
each finishing move thats hits the targets (succesed) remove all combo points on it.

Source (you should point out proofs of your report, please give us some source):

**Comment by Bursztynek** [comment]
I see 1 more thing, there is also a energy issue... just look at the film i post in. Every finisher (secunde by secunde) i start with full energy. - its defenetly wrong... this regen is so high atm. 
But unlikly i dont know for sure whats regen rate it shoud be.

**Comment by lukaasm** [comment]
the issue was related to MindControl probably used earlier :)

**Comment by Wojtyas** [comment]
Cannot reproduce seems it works good now. Feel free to reopen if needed.
