### ISSUE TITLE
Priest - Dispell Magic  - shoud remove 2 spells

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#1787]
Decription: 
Priest Dispel Magic removes only 1 beneficial buff from his enemy target  (there is somthin wrong while lifeblooms are on enemy targets). 

How it works: 
https://youtu.be/PApJl1i8Ekg

How it should work: 
Like in description it shoud remove 2.

Source (you should point out proofs of your report, please give us some source):

**Comment by Bursztynek** [comment]
bug on video showed around 1:00 min

**Comment by Atrecom** [comment]
if u have talent with 30% immune to dispel, it wont work like in description. check it.
Tested it with no immune. working fine.

**Comment by Bursztynek** [comment]
oh , ok true... sorry about that :p
