### ISSUE TITLE
[Movement] Creatures hopping between two targets

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1788]
Video below. 

It looks like movement imperfection. Creature should attack (and target) only his main threat all time in cases if it doesn't cast any spells on others.

https://www.youtube.com/watch?v=f9fTMtV4RZ8

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1778
