### ISSUE TITLE
[TALENT] Paladin Spiritual Attunement works 50%

### ISSUE THREAD

**Issue by Atrecom** [SunwellWoW/Sunwell-TBC-Bugtracker#1789]
Decription: 
spell=31786
When paladin is healed by friendly healer he gets mana equal to 10% of healing.

How it works: 
10% from hots, 10% from average direct heal, but 2-5% from critical heals.

How it should work: 
10% from amount healed.

Source (you should point out proofs of your report, please give us some source): 

![img-20180626-wa0002](https://user-images.githubusercontent.com/44858756/48869493-7b36fa00-edee-11e8-95d4-e851a966fe9c.jpg)
![1](https://user-images.githubusercontent.com/44858756/48869555-b33e3d00-edee-11e8-97cd-da0ba6c07d30.jpg)
![video-games-world-of-warcraft-spirit-pc-angel-1920x1080-15243](https://user-images.githubusercontent.com/44858756/48869568-bc2f0e80-edee-11e8-87bf-4102e9fe9cf3.jpg)
_________________________________
wrong here
![kmvwizd](https://user-images.githubusercontent.com/44858756/48869580-c9e49400-edee-11e8-9135-f1b9c4d0d9bc.jpg)
![img-20180626-wa0002](https://user-images.githubusercontent.com/44858756/48869590-d10ba200-edee-11e8-96d2-11244d3af571.jpg)

**Comment by neheri** [comment]
Please notice that it gives mana only if it actually heals. Overheal doesn't count.

**Comment by Atrecom** [comment]
> Please notice that it should give mana only if it actually heals. Overheal doesn't count.

ofc i kknow. teste it with 10% hp and 20% mana. it`s ok.

**Comment by akrom23** [comment]
Works fine to me. Needs test.

**Comment by Atrecom** [comment]
Gonna retest later today.

**Comment by Atrecom** [comment]
> Works fine. Needs test.

ye. works fine now. thx.

**Comment by Penthax** [comment]
Dunno, but that Talent still dont work for me.

- Fighting  with 10-20% Hp, Mana is low also.
https://gyazo.com/bc8ca1fc79d5a0a6962017ae1c7b07b6

https://gyazo.com/7a5cbe6d33555dce09294883aac0188f

Its not overhealing or something, i was  on like 10-20% HP.

**Comment by Atrecom** [comment]
Well. gonna retest later today.

**Comment by Penthax** [comment]
When i got healed from a Level 40+ Shaman  "Healing Wave" as example works fine.
When i got healed from our Level 70 Priest - Spiritual Attunement is broken for me.
Screenshots are above.

**Comment by gastroslim** [comment]
Does not work as it should. When overhealed (even by 1 point) no mana is returned to paladin.

**Comment by pinkisnotgay** [comment]
Bump!!
