### ISSUE TITLE
Gnomeregan

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#179]
### **TO DO:**

- [ ] 1. Kernobee npc (7850) offers A Fine Mess (2904) quest and wants to escort him to dungeons exit. Once quest is accepted nothing happens.
**EDIT: There are 3 issues:**
- **Once we reach destination of escort there is no credit and npc still follows us.**
- **There should be spawned robot that follows Kernobee. Forgot the name but his perm spawn was removed recently.**
- **Kernobee shouldn't pull dungeons creature at all. He should only help fighting when players pulls some creatures but npc shouldn't pull anything.**
- [ ] 2. Irradiated Slime (6218), Corrosive Lurker (6219) and Irradiated Horror (6220) don't have Corrosvie Ooze (9460) aura. This aura should give him a chance to apply Corrosive Ooze (9459) debuff while melee attacking but it doesn't proc even with aura. Dunno if it's not working or proc chance is extremely low.
**EDIT: All of them have this aura but there was still no proc on melee hit when they were dealing melee dmg for few minutes.**
- [ ] 3. Irradiated Horror doesn't use his Radiation Cloud spell (10341) too.
**EDIT: Still doesn't have it.**
- [ ] 4. Mobile Alert System npc (7849) spawns several creatures once pulled. It's correct but after party wipe those spawned creatures should disappear immediately, otherwise they start to behave in unwanted way like flying, chasing etc.
- [ ] 5. Caverndeep Invader (6208) doesn't use his spells: Radiation (9770), Dazed (1604) and Gouge (12540).
**EDIT: He still doesn't use anything.**
- [ ] 6. Leprous Machinesmith (6224) doesn't use his Tune Up spell.
**EDIT: Still nothing happens after full spell cast.**
- [ ] 7. During Supercharge channel, all nearby enemies (friendly to caster) should gain Supercharge buff which is absent for now.
**EDIT: Still no buff on nearby friendly units.**
- [ ] 8. Dark Iron Agent's (6212) uses his Dark Iron Land Mine spell (11802) correctly. But spawned Dark Iron Land Mine (8035) should explode after 10 seconds. For now it explodes faster if it got pulled by player. It also doesn't explode at all if players are not moving.
**EDIT: Spawned Mine shouldn't auto attack players and shouldn't move from place where spawned.**
- [ ] 9. Walking Bomb's explode spell (I believe 11504) doesn't hurt players.
### **TROGGS ATTACK EVENT**
- [ ] 10. Double gaps between text shall be removed.
![image](https://user-images.githubusercontent.com/22802214/45473108-68d97980-b736-11e8-8505-469ceaef60b5.png)
### **DONE:**

- [x] 1. Dupe Bugs (7732) summoned by Techbot's (6231) Summon Dupe Bug spell (10858) should start to attack players once spawned.
- [x] 2. Not every of Irradiated Pillager (6329) npc have Radiation (9798) aura. All of them should have it.
- [x] 3. Holdout Medic (6392) shouldn't use Renew and Heal spells when he or his comrades have 100% hp.
- [x] 4. Holdout Medic should also heal Houldout Warriors (6391) and Holdout Technicians (6407).
- [x] 5. Looks like Holdout Medic doesn't use his Power Word: Fortitude spell (13864). He should cast it on himself and Holdout Warriors/Technicians.
- [x] 6. Corrosive Lurker doesn't use his Radiation Poisoning spell (11638) too.
- [x] 7. Viscous Fallout (7079) should use his Toxic Volley spell every 15 seconds.
- [x] 8. Viscous Fallout should be doubled size compared to current. .mod scale 2 him or something ;P
- [x] 9. Mobile Alert System npc should use two quotes. First quote on pull and second quote on every spawn wave of corridor guardians. For now he uses only one quote entire time in both situations.
Proper quotes:
- Internalizing subward transport! Defense units inbound! - When he's pulled
- Warning! Warning! Intruder alert! Intruder alert! - When he spawns creatures
- [x] 10. Looks like Leprous Defender (6223) doesn't use Concussive Shot spell (5116).
- [x] 11. Peacekeeper Security Suit (6230) doesn't use Pacify spell (10730).
- [x] 12. Leprous Machinesmith interrupts his own channeling spell named Supercharge (10732).
- [x] 13. Mechano-Tank (6225) shouldn't use Pacify spell.
- [x] 14. Dark Iron Ambassador (6228) should be rare spawn boss with 20% chance of appearance in dungeon.
- [x] 15. Dark Iron Ambassador interrupts his own spells (I believe all of them were interrupted somehow).
- [x] 16. Dark Iron Ambassador shouldn't use Frost Armor spell (12544).
- [x] 17. Dark Iron Ambassador shouldn't use Summon Embers spell (10869).
- [x] 18. Burning Servant (7738) should start to attack players once spawned.
- [x] 19. Embers (7266) should start to attack players immediately after spawned.
- [x] 20. Both Burning Servant and Embers should be friendly for Dark Iron Ambassador. For now, Embers attack boss.
- [x] 21. Walking Bomgs (7915) shouldn't be present in final boss room before engage. They should appear during fight.
![image](https://user-images.githubusercontent.com/22802214/44415754-7c4b5780-a571-11e8-881d-ed6f5f49c428.png)
- [x] 22. There shouldn't be perm Dupe Bugs (7732) spawns.
- [x] 23. Lag spell (10855) debuff lasts for 10 seconds and after that Link Dead spell (10856) debuff should appear on those players who had Lag debuff before. For now Link Dead debuff appears after 8 seconds instead of  full duration of Lag debuff.
**EDIT: Still work in same way.**
- [x] 24. Radiation Aura properly proc with Irradiated Pillager's death to nearby friendly (to him) creatures buffing them with Radiation Aura as well. The only missing thing is second emote:
- Irradiated Pillager blood sprays into the air! - Correct
- [creature name] is splashed by the blood and becomes irradiated! - Missing
**EDIT: I don't know what happened but now they dont spread radiation aura on their death at all. Also there are no emotes.**
- [x] 25. Caverndeep Ambushers (6207) are moving to fast.
- [x] 26. Mechano-Tank should use Machine Gun spell (10346).
**EDIT: Lets replace this spell id for 15249 cuz this id above hits for 10 -,-**
- [x] 27. Mechanized Guardian's (6234) Electrified Net spell (11820) should damage and immobilize players. For now it doesn't immobilize players for 6 seconds.
- [x] 28. Dark Iron Ambassador should use Summon Burning Servant spell (10870).
**EDIT: He uses that be he spawns 2x Burning Servants instead of 1.**
- [x] 29. Burning Sevant should use Summon Embers spell (10869).
**EDIT: Still doesn't use it.**
- [x] 30. Blastmaster Emi Shortfuse (7998) has no dialogue option so I can't even start event with first encounter. Below is proper text with dialogue:
![image](https://user-images.githubusercontent.com/22802214/44411346-92074f80-a566-11e8-8463-05450376fb87.png)
- [x] 31. Entire mechanics with Walking Bombs doesn't work. Once pulled, boss should randomly activate one of the gobs named Gnome Face 1-6 (9593, 9265, 11994, 6388, 6755, 28377) every ~10 seconds. When he activates one of them there should be yell:
"Explosions! MORE explosions! I've got to have more explosions!"
Since now, activated gob will spawn Walking Bombs every 3 seconds that will chase random player and explose when touched. In order to deactivate this spawning gob players should press red button next to spawn point as soon as possible. There are 6 gobs that spawn bombs, and 6 buttons that will deactivate that, as u can see in attached figure. I will list those spawn gobs with adequate buttons:
- spawn: 9593 button: 6582
- spawn: 9265 button: 6726
- spawn: 11994 button: 6748
- spawn: 6388 button: 11977
- spawn: 6755 button: 14140
- spawn: 28377 button: 15766
![image](https://user-images.githubusercontent.com/22802214/44416415-1bbd1a00-a573-11e8-9e5f-88b75bfdc39e.png)
**EDIT: Literally nothing happens since beginning of the fight. There are no spawns of bombs etc.**
- [x] 32. Mekgineer Thermaplugg's Knock Away spell from phase 1 doesn't knock players actually. There is pure spell damage but without second effect.
- [x] 33. Blastmaster Emi Shortfuse shouldn't pull or fight with Troggs during this event.
- [x] 34. When Blastmaster Emi puts a bomb near tunnel he should put gobs which look like barrels with exploding powder.
- [x] 35. When Barrels explode they should hit nearby players and kill them. Players should run away from exploding spots. At 8:15 u can see explosive barrels and explosions itself who killed player.
https://www.youtube.com/watch?v=qyQjU_mhOq8
- [x] 36. In second tunnel there should spawn Caverndeep Burrowers as well who accompany Ambushers.
- [x] 37. Emi seems to have wrong timers when he puts explosived on second tunnel.
- [x] 38. Increase Emi's armor to 1k.
- [x] 39. There are no final emotes after boss defeating. He stops with "FIRE IN THE HOLE".

**Comment by worugru** [comment]
Also: "Caverndeep Ambusher" ID : 6207 Runs in super speed.

https://streamable.com/32eja

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
List updated.

**Comment by notsofamous** [comment]
- [ ] These Holdout Warriors don't stand up when you engage them
https://i.gyazo.com/e25b35cc3e66594fa06834d71911f9ac.mp4

**Comment by sicknot1** [comment]
The Tune Up - specifically at the last door leading to the last boss. Can be stacked unto the mechanog rider giving him 40% multiplied by as many gnomes are casting it.
The instance mobs resetted after that wipe, dunno if intended.
