### ISSUE TITLE
[Spell] Elemental Mastery

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#1792]
Decription: Elemental Mastery causes your next Fire, Frost or Nature damage spell to cost 100% less mana and have 100% crit chance

How it works: 
-When you throw a totem, it eats the buff https://www.twitch.tv/videos/339028836
-When you cast ?any? spell it eats the buff https://www.twitch.tv/videos/339029952
I tried a healing spell now also and it soaked the buff, so it just considers any spell a damage spell at the moment.
-Flametongue weapon eats the buff 

How it should work: Fire, Frost or Nature damage spells should eat the buff

Source:

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).

**Comment by Avishai97** [comment]
bugged again
