### ISSUE TITLE
[Quest] Seer Udalo

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1799]
- [x] Akama questgiver (21700) should offer us Seer Udalo quest (10705) only after full outro event after Akama quest (10628) is done. For now we can get next quest and skip watching this amazing dialogues between Maiev and Akama :o 
- [x] Udalo npc (21962) should be present only on Heroic version of Arcatraz! He can be found on normal for now as well which is WRONG OMG.

**Comment by mjk6994** [comment]
False. This has always been a normal quest, hence the reason it requires 67 opposed to 70.

**Comment by Aledati** [comment]
I do not know who is worse, this guy who cried about something he has no clue or ppl who listened him
