### ISSUE TITLE
[Zone] [Redridge Mountains]

### ISSUE THREAD

**Issue by Lonoss** [SunwellWoW/Sunwell-TBC-Bugtracker#180]
### **TO DO:**

- [x] Vmaps in Render's Rock (cave) location cords 33,5 7,4 are really bad. Lots of mobs going underground or on ceiling.

- [x] Same problem with castle Stonewatch Keep cords 69 55. All mobst runing in textures. Adtionaly building isn't treded as a building (you can use mount inside).

- [x] Likeshire town hall (29 45) is not a building you can mount inside.
https://imgur.com/a/RCALaOX

- [x] NPC - Blackrock Summoner GUID: 17318 Entry: 4463
http://db.hellfire-tbc.com/?npc=4463#abilities
Mob is not linked with his summoned imp. You can pull him without imp.

- [x] Quest - Missing In Action
http://db.hellfire-tbc.com/?quest=219
Corporal Keeshan GUID: 17874 Entry: 349
How it works: Quest is done after akcept.
How it should work: It's escort quest. You should escort him to Likeshire.
Source: https://www.youtube.com/watch?v=nRyMHR0SlAs&t=55s

### **DONE:**

- [x] NPC - Alma Jainrose <Herbalism Trainer> GUID: 6264 Entry: 812
http://db.hellfire-tbc.com/?npc=812
Walking path is wrong. She going in to the roof.
https://imgur.com/a/wQ5JRz7

- [x] NPC - Bellygrub GUID: 10105 Entry: 345
http://db.hellfire-tbc.com/?npc=345#abilities
Does not use ability: Rushing Charge

- [x] NPC - Redridge Mystic GUID: 11668 Entry: 430
http://db.hellfire-tbc.com/?npc=430#abilities
Does not use ability: Healing Wave (Rank 3)

- [x] NPC - Murloc Minor Tidecaller GUID: 8783 Entry: 548
http://db.hellfire-tbc.com/?npc=548#abilities
Does not use ability:Healing Wave (Rank 3)

- [x] NPC - Murloc Tidecaller GUID: 6189 Entry: 545
http://db.hellfire-tbc.com/?npc=545#abilities
Does not use ability: Frost Nova 

- [x] NPC - Blackrock Shadowcaster GUID: 18452 Entry: 436
http://db.hellfire-tbc.com/?npc=436#abilities
Does not use ability:Shadow Word: Pain. I don't see Banish, but maybe they use it if is more than 1 person.
Plus that specific one is in texts. Whats worst he can cast shadow bolts from there until he run out of mana.
https://imgur.com/a/dnFoDbC

- [x] NPC - Blackrock Gladiator GUID: 18451 Entry: 4464
http://db.hellfire-tbc.com/?npc=4464#abilities
Does not use ability: Disarm, Defensive Stance

- [x] NPC - Tharil'zun GUID: 18397 Entry: 486
http://db.hellfire-tbc.com/?npc=486#abilities
Ability: Battle Fury not working corectly. He should use it on nearby allies but it work only on him.
http://db.hellfire-tbc.com/?spell=3631

- [x] NPC - Shadowhide Warrior GUID: 22275 Entry: 568
http://db.hellfire-tbc.com/?npc=568#abilities
Does not use ability: Sunder Armor

- [x] NPC - Shadowhide Slayer GUID: 6295 Entry: 431
http://db.hellfire-tbc.com/?npc=431#abilities
Does not use ability: Execute

- [x] NPC - Shadowhide Assassin GUID:  Entry: 
http://db.hellfire-tbc.com/?npc=579#abilities
Does not use ability: Backstab (Rank 3)
Ability: Poison is used to rarely.

- [x] NPC - Morganth GUID: 6268 Entry: 397
http://db.hellfire-tbc.com/?npc=397#abilities
Does not use ability: Minion of Morganth
His normal atack (not fireboll) is to strong. Should be even 50% less, couse his normal dmg should be from fireboll.
Acording to database Damage: 57 - 68
On 70 lvl with 2900 armor (21,6% redaction) normal hits 90-105

**Comment by Nadiirr** [comment]
Vmaps were fixed with other updates. I updated those.

The summoner issue is still there, but now he does not even have an imp.

**Comment by Wojtyas** [comment]
Fixed & implemented.
