### ISSUE TITLE
[Quest] The Ata'mal Terrace

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1800]
Hi there, 
It's Nightbane beta and welcome to Jackass.

We have several issues correlated with The Ata'mal Terrace quest (10707).

- [ ] Shadowlord Deathwail (22006) misses his AI and emotes he supposes to use during event. He should fly above location on his mount (nether drake) but he doesnt have it. After we engage whole event this mount should put some flames below players feet (aerial phase).
![image](https://user-images.githubusercontent.com/22802214/48906468-d4417500-ee64-11e8-9804-7e35890a8d0b.png)
- [ ] Each of Shadowmoon Soulstealers (22061) should be connected by link with Heart of the Fury visual trigger (22058)
![image](https://user-images.githubusercontent.com/22802214/48908176-dce87a00-ee69-11e8-8ee8-fa6572214db3.png)
- [ ] After we start to fight with Shadomoon Soulstealer there should appear 3x Shadowmoon Retainers (22102). For now they spawn only once after first Soulstealer is attacked, when in total there should be 9 units - 3 for each Soulstealer's started to being attacked.
- [ ] When 3x Soulstealers are dead, Deathwail should slowly land at Shadowlord Deathwail Visual Trigger place (22096) and phase 2 - fighting with him on ground should start.

Videos:
https://www.youtube.com/watch?v=HoeSAheA36M
From 1:40 https://www.youtube.com/watch?v=8QAvDrW89iY

**Comment by Aledati** [comment]
Quest is not working. 
We waiting for the boss more than 1 hour before we gave up and later we checked few times during a day and nobody saw him yet.
There is to many summoned units around and they never stop coming.
