### ISSUE TITLE
Kiting / Mob leash

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#1802]
Decription: 
You are supposed to be able to kite mobs indefinetly if you keep hitting them, there is a 10 second timer after you hit a mob before it resets if you dont touch it again.

How it works: 
https://clips.twitch.tv/FrozenCogentSparrowPMSTwin their reset point basically
https://www.twitch.tv/videos/339261573 the second mob i Frost shock should not reset at it's reset point

How it should work: https://www.youtube.com/watch?v=qSgbKojDlVQ
https://www.youtube.com/watch?v=kYeBkX6bC1k&feature=youtu.be&t=50

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Yey it suppose to work like you mention. 
Probably for now it works only for melee and we forgot to implement SPELL as damage which should providing kiting as well. 
Thank you for checking this.

**Comment by Avishai97** [comment]
also if you run out of range faster they reset before their reset point, not sure what is supposed to happen in that scenario

**Comment by Wojtyas** [comment]
Fixed, will be implemented with next updated.
