### ISSUE TITLE
[Shaman] Totems

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#1804]
Decription: 
Totems haven't LoS.

How it works: 
I can put Totem near the wall, stand on second side (no LoS) and I still get effects from the totems. For exaple I lost fear by Tremor Totem.

How it should work: 
Totems should include LoS.

Source (you should point out proofs of your report, please give us some source):

**Comment by ZaoQ** [comment]
they should work when you are not in los

**Comment by Wojtyas** [comment]
Yee I agree with @ZaoQ :o any proof dude?

**Comment by notsofamous** [comment]
The only totems affected by LoS should be Stoneclaw and Earthbind.

**Comment by ahlens** [comment]
True, many years ago I did enormous research about that. Totems ignore LoS. Not sure if all of them.

**Comment by Wojtyas** [comment]
Closing for now, will test Stoneclaw and Earthbind in the morning.
