### ISSUE TITLE
Mind Control - duels

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#1805]
How it works: 
Mind Control doesn't work in duels. We cannot move, attack or do anything at all. If we try move, then our character is moved and MC is fade. If MC timer debuff fades on the enemy, then we still channel the spell.

If we try MC shaman with Grounding Totem then we Mind Control the totem.

How it should work: 
We should can in 10 sec to melee attack and move by controled enemy. Our character should move when controling another player. When debuff fades the chanelling should stop.
If you try Mind Control the shaman with Grounding Totem, totem should be destroyed.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
1. ~~MC is eaten by Grouning Totem correctly.~~
2. When MC ends while we were running this character will still run w/o of control of its char. MC is done be he has literally no control of keyboard and char is moving still forward.
3. After MC ends player is still channeling the spell.
![image](https://user-images.githubusercontent.com/22802214/48987470-8310da00-f11f-11e8-852d-0bec04e36b44.png)

**Comment by akrom23** [comment]
2.  Cannot reproduce.
