### ISSUE TITLE
[Transport] Boat Menethil Harbor ---> Theramore

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1807]
Decription: 
I made a wrong report here, https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1713, i thought about menethil --> theramore, but wrote auberdine XD its my bad
TBC boat passages 
auberdine ---> wetlands/azuremyst isle/ru'theran village 
booty bay ---> ratchet 
Menethil Harbor ---> Auberdine/Theramore(2nd is not present on the beta realm) 
How it works:
there is no passage between Menethil and Theramore,. the ship isnt there
How it should work: 
There MUST be a ship between theramore and menethil harbor
THis NPC informs bout it https://www.wowhead.com/npc=12658/adam-lind#comments
Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Menethil_Harbor  LOOK at travel connections
https://www.youtube.com/watch?v=hitTWQemZXk

**Comment by Mikov1605** [comment]
Sorry Wojtas, was my fault, i thought about one but wrote the other :P

**Comment by Wojtyas** [comment]
np ;p

**Comment by Wojtyas** [comment]
Anyway there is ship Wetlands-Theramore since today :D
