### ISSUE TITLE
[Spell] Charge

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1809]
- [ ] Players should be able to use Charge when they are in air (literally falling).

- [x] Players should be able to use Charge spell when targets are in spell range, no matter what road player will choose (even if charge will take many seconds and rush target around way).

On below videos we can see when player is trying to use Charge/Intercept spell and there is no charge effect at all. Player gets rage bonus and deal damage by this spell anyway.

https://clips.twitch.tv/EmpathicInterestingRavenVoteYea - Charge w/o charging
https://clips.twitch.tv/PowerfulWonderfulLarkPunchTrees - Charge w/o charging
https://clips.twitch.tv/AffluentTentativeSharkShazBotstix - Intercept used but w/o charge effect (same story)
https://clips.twitch.tv/ImpossibleEndearingMeerkatDoubleRainbow - Warrior falls into textures after Charge use near wall

**Comment by doomnyx** [comment]
Additional charge bugs which I encountered while dueling a warrior:

- [ ] charge should cause stun effect **after** warrior reaches the target, not when starting to charge

- [ ] above means that charge should be stoppable in the proccess; if warrior is CCed while charging he should not be able to finish the charge, thus no stun effect should occur. Proof:
https://youtu.be/0xAuRkhnetk?t=360

- [ ] while trying to reproduce behavior from video above, following things happened:
1. warrior pressed charge before my fear cast finished
2. fear cast finished, fear affected the warrior
3. I got the stun effect, while warrior was standing in fear in one place
4. after fear warrior was unable to move. following intercepts/charges caused stun effect but warrior was still in one place, alt f4 resolved the problem

**Comment by ZaoQ** [comment]
charge should cause stun effect after warrior reaches the target, not when starting to charge 
this charge/intercept thing is rly tricky :D https://youtu.be/TYawfgVBSEc?t=430, as u can see, interrupt part of it is applied right when warrior starts charging followed by a stun, definitely not when he reaches the target

**Comment by doomnyx** [comment]
found it:
While Charge is extremely fast, the one-second stun only keeps the target in place long enough for you to get there. It's useful to interrupt spells when running into a battle that's already taking place, but if you want a running player or mob to stay near you, you need to use Hamstring or some other movement-restricting skill as soon as you finish charging.

http://wowwiki.wikia.com/wiki/Charge?oldid=1598449

That means charge stuns before reaching the target, but there is a possibility of interrupting movement.

**Comment by ZaoQ** [comment]
from others yes, not from a target

**Comment by Wojtyas** [comment]
- [ ] Still cannot use charge while falling. I can use that immediately after I reach ground (falling dmg) but not when in air.

**Comment by Nadiirr** [comment]
- [ ] While underwater, if there is terrain in the path you will jump up after a charge
https://gfycat.com/AridWebbedArmyworm
