### ISSUE TITLE
[Movement] Fences

### ISSUE THREAD

**Issue by dredd-sunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#1813]
Decription: Walking around fences to reach the player

How it works: Mobs go through fences to reach the player

How it should work: Mob should go around the fence to reach the player

Source (you should point out proofs of your report, please give us some source): retail

**Comment by akrom23** [comment]
Screenshots? Video?

**Comment by Nadiirr** [comment]
Red is what it does
Green is what it should do

![screenshot_130](https://user-images.githubusercontent.com/36300104/48928030-04ead400-ee90-11e8-9598-e2e80ef5e2a4.png)


one place I've noticed this is in Duskwood

![screenshot_131](https://user-images.githubusercontent.com/36300104/48928041-221fa280-ee90-11e8-8d3d-9511ce72f6d4.png)

**Comment by Wojtyas** [comment]
Fixed & implemented.
