### ISSUE TITLE
[Warlock][Spell] Felhunter's Spell Lock

### ISSUE THREAD

**Issue by doomnyx** [SunwellWoW/Sunwell-TBC-Bugtracker#1814]
Decription: Silences the enemy for 3 sec. If used on a casting target, it will counter the enemy's spellcast, preventing any spell from that school of magic from being cast for 6 sec.
http://db.hellfire-tbc.com/?spell=19647

How it works: 
Silence works ok, but there is no actual 5s/6s (depending on rank) spell lock on school of magic if interrupted while casting a spell. Tested on Priest's Greater Heal and Mind Blast.

How it should work:  

> However, if the enemy was in the process of casting a spell, then the spell will be interrupted, and the target will be unable to cast a spell from the same school of magic for either 5 or 6 seconds. For example; if a Felhunter casts Spell Lock on a Mage, in the process of casting  [Frostbolt], the the spell will be cancelled, and the mage will be locked out of their other Frost spells for the duration of the debuff (either 5 or 6 seconds).

Source (you should point out proofs of your report, please give us some source):  Tooltip, wow.gamepedia
https://wow.gamepedia.com/index.php?title=Spell_Lock&oldid=1465314

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).
