### ISSUE TITLE
[Halaa/Item] Fire Bomb [24538]

### ISSUE THREAD

**Issue by Piootrek** [SunwellWoW/Sunwell-TBC-Bugtracker#1815]
Decription: Fire Bombs don't work. After using Fire Bomb while flying on Wyvern nothing happens. Fire bomb just disappears from inventory.

How it should work: Fire Bomb should fly toward target and deal ~1000 damage on impact, and then a 1% of Max HP as a damage over time.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Halaa

**Comment by KayleeFrye1** [comment]
Not gonna patch this? Can't do Halaa daily

**Comment by codyboulton** [comment]
Yeh any updates? Nagrand Police Dept can't fully operate without it's HQ.

**Comment by foxxhound** [comment]
Bumping this. Halaa needs to be fixed.

**Comment by SaerisTM** [comment]
Bump, Halaa still requires manual killing.

**Comment by brabideau** [comment]
Still not working. I raid marked a few guards and checked their health before and after some bombing runs. No change in health on any of the ones I checked, even though I hit them several times.

**Comment by Trentone** [comment]
This fixed it for me:
[17631.txt](https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/files/2936007/17631.txt)

**Comment by Dootz** [comment]
https://github.com/TrinityCore/TrinityCore/issues/6649
