### ISSUE TITLE
[Warlock][Spell][Pet] Lesser Invisibility

### ISSUE THREAD

**Issue by doomnyx** [SunwellWoW/Sunwell-TBC-Bugtracker#1816]
Decription: Grants the Succubus Lesser Invisibility for up to 5 min. This spell can only be used out of combat.
http://db.hellfire-tbc.com/?spell=7870

How it works: When Succubus is under that effect, she cannot break out when commanded to attack. Commanded to cast abilities breaks her out of invisibility.

How it should work: 

> Any command given to or damage taken by the Succubus will take her out of invisibility mode.

> Just like Stealth, invisibility comes undone if you take most actions other than movement.

Any, except movement commands (follow, stay).

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Lesser_Invisibility?oldid=1465486
https://www.wowhead.com/spell=7870/lesser-invisibility#comments
http://wowwiki.wikia.com/wiki/Invisibility_(mechanic)

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).
