### ISSUE TITLE
[Transport][Question] Boat Menethil--->Theramore

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1818]
Decription: 
I just wanted to ask, if the boat fix is already live yet. sorry for making extra topic

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Yep it's on SSC realm for sure. Probably on open realm as well (I think there was update too).

**Comment by Mikov1605** [comment]
Its not on the open realm, i just saw it :)
