### ISSUE TITLE
Mark of the Wild (rank 8)

### ISSUE THREAD

**Issue by Altgreen** [SunwellWoW/Sunwell-TBC-Bugtracker#1821]
Decription: 
The mouseover on this buff icon shows different stats than those in the spell book. Tp duplicate, cast mark of the wild rank 8 and check the tooltip against the spellbook tooltip

How it works: See above

How it should work:  It should show the same stats in the tooltip

Source (you should point out proofs of your report, please give us some source): 
![screenshot 14](https://user-images.githubusercontent.com/45273682/48922317-248cf700-eea6-11e8-9c42-9e328a4959fe.png)
![screenshot 15](https://user-images.githubusercontent.com/45273682/48922319-26ef5100-eea6-11e8-8ada-17a01dee2716.png)

**Comment by Wojtyas** [comment]
Actually tooltip its client's side aspect and we can't change it both on tbc or even wotlk.

**Comment by Altgreen** [comment]
You mean to say that it's my version of the game that's buggy ?

**Comment by notsofamous** [comment]
No, buffs simply dont show the updated stats. If you mouse over on the ability you see the stats properly.

**Comment by Altgreen** [comment]
Yes, but why don't they ? What, if anything, can be done to fix it ?
