### ISSUE TITLE
[Mobs] Ironjaw Basilisk

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#1825]
Decription: / How it works: 
- reguarding [Mobs] Ironjaw Basilisk in Stranglethorn Vale
- Spell "Crystal Flash" can not be interrupted by Earth Shock
- Spell "Crystal Flash" is not redirected by Grounding Totem

How it should work: 
- "Crystal Flash" is a magic spell and should be interruptable by Earth Shock
- if you consider "Crystal Flash" as a non AoE Spell, it should be redirected by Grounding Totem

Source (you should point out proofs of your report, please give us some source): 
![grafik](https://user-images.githubusercontent.com/45068171/48924442-78084080-eeb8-11e8-8053-79ea37312241.png)

**Comment by Wojtyas** [comment]
Adding General Core label due its common issue in recent days.

**Comment by FrauHolle86** [comment]
**Side Note (same goes for following Mobs):**
- [Mobs] Thunderhead in Barrens
- [Mobs] Deepmoss Venomspitter in Stonetalon Mountains

**Comment by Wojtyas** [comment]
Ye thats what General Core means :D it seems to occur in global scale
