### ISSUE TITLE
[Mob] Umbrafen Eel

### ISSUE THREAD

**Issue by Haradokz** [SunwellWoW/Sunwell-TBC-Bugtracker#1826]
Decription: 

Umfrafen Eels reseting if you are attacking them at the surface of the water

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![eels](https://user-images.githubusercontent.com/37354103/48925187-fb14a100-ee8e-11e8-805c-8c2ff9c0973b.jpg)

**Comment by Wojtyas** [comment]
best proof eva :d

**Comment by Wojtyas** [comment]
Fixed & implemented.
