### ISSUE TITLE
[Herbalism] Picking Up Outland Herbs

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1829]
Picking up Outland herb should provide players some buffs/debuffs depending on herb type.

- [x] After opening Nightmare Vine gob (181280) there should be ~30% chance to apply Nightmare Vine debuff (28720) on player.
- [x] After opening Dreaming Glory gob (181271) there should be 100% chance to apply Dreaming Glory buff (28694) on player (not sure if buff works).
- [x] After opening Netherbloom gob (181279) player should always recieve one (random) of following auras: 28703, 28704, 28705, 28706, 28707, 28708, 28709, 28710, 28711 or 28712. When one of auras is applied, others from this list should be faded (they should replace one another).
- [x] After opening Mana Thistle gob (181281) there should be ~50% chance to recieve spell cast (28718) restoring some mana.

**Comment by NickBrah** [comment]
bump, can confirm dreaming glory does not provide buff, nor do any of the other herbs,

**Comment by koostosh** [comment]
Netherbloom behavior was changed in ~2.1 it should have 25% chance, only positive buffs should be applied and they do not exclude eachother.
