### ISSUE TITLE
[General][Core][NPC]rage bars

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1831]
Decription: 
Reported already, closed, fix is still not live yet. I just would like to ask if u will, or can, fix it :) 

How it works: 
Many mobs got rage bars, even beasts,demons, undead etc

How it should work: 

ONLY warrior classed mobs should have it
Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
SSC realm? Some screenshots?

**Comment by Mikov1605** [comment]
i talk about the Open World realm :)

**Comment by Mikov1605** [comment]
![rage 1](https://user-images.githubusercontent.com/43579401/48940346-82a5f280-ef17-11e8-9f9b-8631db217719.jpg) 
![rage 2](https://user-images.githubusercontent.com/43579401/48940681-d1a05780-ef18-11e8-95d3-0c4e0076fb7d.jpg)
![rage 3](https://user-images.githubusercontent.com/43579401/48940684-d36a1b00-ef18-11e8-8fb5-d9fa2af243fb.jpg)
![rage 4](https://user-images.githubusercontent.com/43579401/48940685-d533de80-ef18-11e8-9f7b-215a6fff1ba5.jpg)
![rage 5](https://user-images.githubusercontent.com/43579401/48940691-d9f89280-ef18-11e8-8826-f83e617954d7.jpg)
![rage 6](https://user-images.githubusercontent.com/43579401/48940699-e1b83700-ef18-11e8-9d80-c44060b60401.jpg)
![rage 7](https://user-images.githubusercontent.com/43579401/48940703-e250cd80-ef18-11e8-974d-67a0ed7ca939.jpg)
![rage 8](https://user-images.githubusercontent.com/43579401/48940704-e381fa80-ef18-11e8-9b03-5c42581df1cd.jpg)
![rage 9](https://user-images.githubusercontent.com/43579401/48940706-e4b32780-ef18-11e8-98dc-7efcf718c8e6.jpg)
![rage 10](https://user-images.githubusercontent.com/43579401/48940707-e54bbe00-ef18-11e8-8265-26e8b77cdd96.jpg)
![wowscrnshot_112318_121242](https://user-images.githubusercontent.com/43579401/48940767-1af0a700-ef19-11e8-8c77-151e975b0c3a.jpg)

**Comment by Mikov1605** [comment]
On the screens i presented only SOME of the mobs with this issue, including beasts,mechanicals, humanoids and even a demon.

**Comment by Mikov1605** [comment]
I just might add, its not present on some mobs i already reported, so duskwood area mobs. But in elwynn/westfall, on mobs i have on screenshot, its common(not on all goretusks, harvesters etc, but on 70% of them)

**Comment by Azathothh** [comment]
All of mobs mentioned by you seems fine on instant 70 realm, probably fix isn't yet on "open world" beta.
There's one exception: 
![obraz](https://user-images.githubusercontent.com/37483678/48942898-9f472800-ef21-11e8-9640-0771c3664bc8.png)
Dafias Looter - id 590 - got mana now, while he shouldn't

**Comment by Wojtyas** [comment]
It's fixed in general. If there will pop some exceptions just make new tickets so I will change those npcs.
