### ISSUE TITLE
Druid using polearms.

### ISSUE THREAD

**Issue by Jekenius** [SunwellWoW/Sunwell-TBC-Bugtracker#1833]
Decription: 
My druid can use polearms, even though he havent skill for it.

How it works: Polearm is equipped and can be used for attack even though druid havent skill for it and cant learn for that.

How it should work: Druid shouldnt be able to use polearms.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_112318_192945](https://user-images.githubusercontent.com/45003723/48943827-0f23d580-ef57-11e8-967f-dd0eae4dc092.jpg)
![wowscrnshot_112318_192959](https://user-images.githubusercontent.com/45003723/48943831-1519b680-ef57-11e8-9f80-c1421d2fb9b2.jpg)

**Comment by Jekenius** [comment]
My second druid character can't use polearms while not having skill(which is fine), but cant learn it for some reason.
![wowscrnshot_112318_194034](https://user-images.githubusercontent.com/45003723/48944048-cf112280-ef57-11e8-9a92-dd0e8afab10a.jpg)

**Comment by notsofamous** [comment]
![Image](https://i.gyazo.com/78c6e26c4055a99a344866ed7cb65a22.png)
http://wow.allakhazam.com/wiki/weapon_proficiencies_(wow)

You shouldn't be able to...

**Comment by Jekenius** [comment]
I remembered that wotlk druids can use polearms, after i found that i changed the issue's subject.

**Comment by notsofamous** [comment]
It's probably some left over from instant 70. Try to create more new characters and they shouldn't be able to train it.

**Comment by Jekenius** [comment]
I have 2 more druid characters which can't use polearms.
![wowscrnshot_112318_194034](https://user-images.githubusercontent.com/45003723/48944712-6d9e8300-ef5a-11e8-99ef-a24b913c110e.jpg)

**Comment by akrom23** [comment]
So everything's fine?

**Comment by Jekenius** [comment]
If that thing wont appear again that will be fine. I don't know why that happened, so decided to make a report.

**Comment by akrom23** [comment]
I'll close it. Feel free to reopen if it happens again.
