### ISSUE TITLE
[Map] Trees - LoS

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1834]
Looks like I can cast through every tree in game. I assume there is lack of LoS here.

![image](https://user-images.githubusercontent.com/22802214/48944497-411d4380-ef27-11e8-9527-ac2938242ceb.png)
![image](https://user-images.githubusercontent.com/22802214/48944557-804b9480-ef27-11e8-85f4-045e069b4636.png)
![image](https://user-images.githubusercontent.com/22802214/48944567-8d688380-ef27-11e8-8354-bf946c2e16ad.png)
![image](https://user-images.githubusercontent.com/22802214/48944803-7b3b1500-ef28-11e8-938a-56ed931ec3d4.png)
![image](https://user-images.githubusercontent.com/22802214/48944879-a32a7880-ef28-11e8-89b2-ab373f3007db.png)

**Comment by notsofamous** [comment]
Pretty sure you should be able to. Should work in BGs at least. don't see why it should be different in the open world.

**Comment by Wojtyas** [comment]
> Pretty sure you should be able to. Should work in BGs at least. don't see why it should be different in the open world.

Even for really big trees? I'm quite confused ;d
