### ISSUE TITLE
[spellcast - not sure] changing offhand puts you on global cooldown

### ISSUE THREAD

**Issue by maciekk57** [SunwellWoW/Sunwell-TBC-Bugtracker#1836]
Decription: 

As title, when you are in combat and you change offhand after spellcast, you receive global cd as if main hand was swapped. As i said i'm not sure whether it should work like that, but mage guides suggest creating macros where you swap offhands depending on school of spell you cast which means there shouldn't be global cd after swapping offhand.

If someone is certain that's how it's supposed to work, just delete this thread.

**Comment by doomnyx** [comment]
Changed in later patch to trogger gcd and reset swing timer, works correctly.
