### ISSUE TITLE
[Spell] [Arena] Fel Domination

### ISSUE THREAD

**Issue by Jeansapin** [SunwellWoW/Sunwell-TBC-Bugtracker#1838]
Decription: The spell Fel Domination : https://www.thegeekcrusade-serveur.com/db/?spell=18708

How it works : The spell's CD isnt reseted while entering in arena.
https://imgur.com/reyP9DS

How it should work: It should be reseted, as every spell in the game when you're entering in arena.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented.
