### ISSUE TITLE
[Zone] [Silverpine Forest]

### ISSUE THREAD

**Issue by Piootrek** [SunwellWoW/Sunwell-TBC-Bugtracker#184]
### **TO DO:** 

- [ ] Quest 452 - Pyrewood Ambush. According to Wowhead comments NPC should be able to solo this quest. Now she is dying after few hits. In addition quest acts weird after failure(when npc died). After retakeing quest, it's autocompleted or starts from the middle wave. (https://www.wowhead.com/quest=452/pyrewood-ambush#comments:id=275707)
JEBAĆ NIE MA TAK ŁATWO

### **DONE:**

- [x]  NPC 1769- Moonrage Whitescalp doesn't use any abilities (http://db.hellfire-tbc.com/?npc=1769#abilities)
- [x]  NPC 1779- Moonrage Glutton doesn't use any abilities (http://db.hellfire-tbc.com/?npc=1779#abilities)
- [x]  NPC 1780- Moss Stalker doesn't use any abilities (http://db.hellfire-tbc.com/?npc=1780#abilities)
- [x]  NPC 1782- Moonrage Darksoul doesn't use any abilities (http://db.hellfire-tbc.com/?npc=1782#abilities)
- [x]  NPC 1924- Moonrage Bloodhowler doesn't use any abilities (http://db.hellfire-tbc.com/?npc=1924#abilities)
- [x]  NPC 1891- Pyrewood Watcher doesn't use any abilities (http://db.hellfire-tbc.com/?npc=1891#abilities)
- [x]  NPC 1894- Pyrewood Sentry doesn't use any abilities (http://db.hellfire-tbc.com/?npc=1894#abilities)
- [x]  NPC 1895- Pyrewood Elder doesn't use any abilities (http://db.hellfire-tbc.com/?npc=1895#abilities)
- [x]  NPC 3530- Pyrewood Tailor doesn't use any abilities (http://db.hellfire-tbc.com/?npc=3530#abilities)
- [x]  NPC 2332- Valdred Moray doesn't use any abilities (http://db.hellfire-tbc.com/?npc=2332#abilities)
- [x]  NPC 1773- Rot Hide Mystic doesn't use spell Curse of Thule (3237) (http://db.hellfire-tbc.com/?npc=1773#abilities)
- [x]  NPC 1939- Rot Hide Brute doesn't use spell Curse of Thule (3237) (http://db.hellfire-tbc.com/?npc=1939#abilities)
- [x]  NPC 1940- Rot Hide Plague Weaver doesn't use spell Curse of Thule (3237) (http://db.hellfire-tbc.com/?npc=1940#abilities)
- [x] NPC 1868 - Ravenclaw Servant uses spell Soul Siphon (7290), but channeling is almost immediately interrupted (probably related with https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/182)
- [x] NPC 1957 - Vile Fin Shorecreeper doesn't use spell Gouge (1776) (http://db.hellfire-tbc.com/?npc=1957#abilities)
- [x] NPC 1914 - Dalaran Mage uses spell Fire Shield (134) only on himself. According to spell description he should be able to cast that spell on other mobs too (Surrounds an ally...)
- [x] NPC 2120 - Archmage Ataeric doesn't use spell Polymorph (118) (http://db.hellfire-tbc.com/?npc=2120#abilities)

**Comment by Wojtyas** [comment]
Fixed & implemented.
