### ISSUE TITLE
[Hunter][Spell]Ferocious Inspiration Spell Not Stacking

### ISSUE THREAD

**Issue by YoshGit** [SunwellWoW/Sunwell-TBC-Bugtracker#1840]
Description: 
BM hunter spell Ferocious Inspiration is not stacking with Ferocious Inspiration from other hunters.

How it works: 
FI does not stack.

How it should work: 
FI should stack and have a separate buff for each hunter.

Source (you should point out proofs of your report, please give us some source): 
On Nightbane:
![wowscrnshot_112318_135141](https://user-images.githubusercontent.com/12674486/48957797-17fdb280-ef29-11e8-906c-1cff425ed28c.jpg)

On retail:
https://www.youtube.com/watch?v=0bZi5KWON38

**Comment by tigeron** [comment]
confirmed

**Comment by akrom23** [comment]
Linked to #385

**Comment by shadowraider** [comment]
because those are three different ranks

also...
"Ferocious Inspiration does not stack with other hunters', a paladin's Sanctified Retribution" (http://wowwiki.wikia.com/wiki/Ferocious_Inspiration)

**Comment by YoshGit** [comment]
I think the page you reference talks about the wrath version of the spell. It is clearly stacking in the retail video. Here is a thread from 2008 where hunters discuss how many times that it stacks https://www.wowhead.com/forums&topic=26477

**Comment by YoshGit** [comment]
123

**Comment by akrom23** [comment]
Works fine.
