### ISSUE TITLE
Rogue pickpocket

### ISSUE THREAD

**Issue by xrewz** [SunwellWoW/Sunwell-TBC-Bugtracker#1841]
Decription: 
pickpocket puts the rogue out of stealth instead of picking the targets pocket

How it works: 
https://gyazo.com/9ce91a71bd22ae39e6a00e7d6a42ebe4

How it should work: 
You should remain in stealth and get a lootwindow with some copper/silver and other shit

Source (you should point out proofs of your report, please give us some source):

**Comment by ahlens** [comment]
I suppose there is chance to be resisted, that's why you are put out of stealth. Someone catched you while you were trying to steal his money!

Correct me if I am wrong. I haven't tested to be honest.

**Comment by xrewz** [comment]
ye resist is possible. but this happend 10/10 times

**Comment by akrom23** [comment]
```
int32 chance = 10 + int32(m_caster->getLevel()) - int32(unitTarget->getLevel());
```
This is the formula we use.
If you are on the same level as you target, than you have 50% chance to pickpocket. 10 levels higher - you are always successful, 10 levels lower - never successful.
Is it the right formula?

**Comment by xrewz** [comment]
I think 50% is to high when equal level, should prolly be around 10-15% to be resisted. 
But if what you are writing is true then pickpocketing as a level 70 with rank 2 stealth should always work. but it acctuly dosent so it would seem like the problem is linked to what stealth rank ur using.

id recmmoned you try it urself. pickpocketing a level 20 mob as level 70 with stealth rank 2.

**Comment by akrom23** [comment]
Yes, i tried 70 level vs 15 mob level - always successful.

**Comment by xrewz** [comment]
Ok the level 70 thing is working now but 2 days ago it wasent working.
But the formula is still not correct. as a level 22 im having way to much trouble to pickpocket mobs between level 18-21. You should change it from 50% to 5%.
Pickpocketing mob as a rogue is a legit strat for making som extra cash early on and with 50% resist its never gonna be worth doing it cuase ur litterarly wasting your opener half the time.

**Comment by xrewz** [comment]
surely you must have heard of brd and lbrs pickpocket runs? if pickpocket would resist to often you wouldent be able to do stuff like that cuase it would take you out of stealh and then ur dead.

https://gyazo.com/682330be51f7c5a7a666c36eb811a20c
Post made back in 2008 saying it should be around 5%

http://vanilla-wow.wikia.com/wiki/Pick_Pocket
Here's a screenshot so you dont have to read the entire thread. https://gyazo.com/3c19a520fd03f1e7ccdf118db3c60429
Also confirming it to be 5%

https://forum.elysium-project.org/topic/38132-pickpocket/
A post from elysium where you can see that people are complaining about resist rates that happens in 1/15  and even 1/25.

ive also asked alot of rogue friend this question and they say that resist only happens every 20-30 mobs but ofc if ur unlucky it can happen 2 times in a row but you get the point.

**Comment by Avishai97** [comment]
"Pick Pocket can be resisted, and at some point probably will, so don't do it." Reading this sounds like it has a chance to resist sure, but 50% nah
source: http://wow.allakhazam.com/wiki/Sap_%28WoW%29

**Comment by akrom23** [comment]
Okay.

**Comment by akrom23** [comment]
Increased to:

- same level - 80% to success
- 5 levels lower than mob - 50% to success
- 5 levels higer than mob - 100% to success.
