### ISSUE TITLE
[Buffs]Mongoose does not stack

### ISSUE THREAD

**Issue by doomnyx** [SunwellWoW/Sunwell-TBC-Bugtracker#1842]
Decription: Increases Agility by 120 and slightly increases attack speed for 10 sec.
http://db.hellfire-tbc.com/?spell=28093

How it works:  Mongoose is only able to refresh itself (sometimes 3 times in 20 secs), while for 20 minutes i have not seen 2 separate procs.

How it should work: When dual wielding, player should be able to have 2 separate procs of "Lightning speed" effect from both weapons (2 buffs)

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/tcO5rg_LiB4?t=1779 (2x Lightning speed)
https://www.wowhead.com/forums&topic=33225#p302100

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).

![image](https://user-images.githubusercontent.com/22802214/48988515-311f8280-f126-11e8-8d31-264ac80a9e64.png)
