### ISSUE TITLE
[Serpentshrine Cavern] Lady Vashj

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1845]
- [x] She's facing the wrong direction, should be facing the players as they approach her from the bridge.
![Image](https://i.gyazo.com/c98c10485e0ca8cf5878650e0b4ee905.jpg)

- [x] Aggro range is too short, she should aggro as soon as you step up on her platform.

Current aggro range
![Image](https://i.gyazo.com/880f804e632652cc6e381e460de3f5cf.jpg)

Should aggro from here
![Image](https://i.gyazo.com/94b814811bd79eca91e8d1d6b15ebff3.jpg)

- [x] Her movement speed is too slow.

- [x] Her shoot does almost no damage
![Image](https://i.gyazo.com/4bfce60b6897f79b2b9be635cc132cfd.png)

- [x] Her AI is wrong. She should not try approach the player if she's ranged. 
https://i.gyazo.com/b3b994012613b003a064413c2548483a.mp4

- [ ] She should run away from the tank when she roots it and start shooting it.

- [ ] Root breaks almost instantly on damage.

- [ ] She can glitch through the stairs if you try to drag her up.
https://i.gyazo.com/f378f00b4a633b15bd2534e233acd8ad.mp4

### Phase 2

- [x] Vashj is supposed to have 1 "buff" for each generator that's active.

- [x] Elementals walk VERY fast

- [ ] All adds glitch through the platform

- [x] This happened
https://i.gyazo.com/c6b33c5e14cae49ea358067ee0d75085.mp4

- [x] You cannot throw the core to other people

- [x] There's a cast time on using the shield generator, should be instant

- [x] There's a delay on the "root" from the tainted core. It doesn't disappear instantly 

- [x] Phase 3 started when we only used 2 generators
https://i.gyazo.com/45b8af8c80a4af10f18e85ecf920589d.mp4

_How it seems to work: When you click the generator it's deactivated but the beam is up until you've finished the cast, you also keep the core until you finish the cast on the generator._

- [x] When you use the Tainted Core on a generator there's a chance that is permanently roots you.

### Phase 3

- [x] There's not damage from the spore bat clouds (pre nerf clouds also do damage on impact)

- [x] She doesn't cast mind control (+200% movement speed, damage and healing. Immune to all CC)
http://db.hellfire-tbc.com/?spell=38511

**Comment by notsofamous** [comment]
- [ ] **Elementals still walk way too fast**

- [x] Shapeshifted druids can't click generators, the core just disappears and nothing happens

- [x] Enchanted elementals are stunnable, slowable and CCable. Should be immune to it.

- [ ] Coilfang Striders should be rootable with Netherweave Net, they are currently immune.

- [ ] Coilfang Striders are trapable by hunters

- [ ] MCed targets are fully CCable

- [ ] She doesn't move at all in P3. There's no deadzone, she instantly starts multishotting people when you are 1 yd out of melee range.

- [ ] Attacking the sporebats will make them fly down to the platform, they also stop casting poison when you tag them.

- [ ] Vashj is not using her shoot ability, only multi shot

- [ ] Sometimes MCed targets could move their characters

- [ ] MCed targets sometimes just stand there and do nothing

**Comment by notsofamous** [comment]
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**
- [ ] **WATER ELEMENTALS STILL RUN TWICE AS FAST AS THEY SHOULD**

**(first reported 23/11)**

**Comment by notsofamous** [comment]
- [ ] **ADDS ARE STILL GLITCHING THROUGH THE FLOOR**

**(first reported 23/11)**

**Comment by Cherryxo** [comment]
Adds still sometimes glitch through the floor.

**Comment by xethra89** [comment]
[ ] **ADDS ARE STILL GLITCHING THROUGH THE FLOOR**
