### ISSUE TITLE
[Quest] A Watchful Eye

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#1846]
Decription: Quest in Redridge

How it works: Statue is in place but can't deliver to the statue.

How it should work: You can deliver to the statue.
And you can pick up another quest from the statue after delivering the followup of A Watchful Eye.
"Looking Further" http://wowwiki.wikia.com/wiki/Quest:Looking_Further
https://gyazo.com/6fcb4e76b01d2a75a411bfecb9845a3a
http://wowwiki.wikia.com/wiki/Quest:Morganth

Source (you should point out proofs of your report, please give us some source):

**Comment by xrewz** [comment]
Can confirm
