### ISSUE TITLE
[Quest] Fire At Will!

### ISSUE THREAD

**Issue by Squarz** [SunwellWoW/Sunwell-TBC-Bugtracker#1847]
Description:
[Naturalized Ammunition](http://db.darkwizard.pl/?item=31807)
[Death's Door Fel Cannon](http://db.darkwizard.pl/?npc=22443)

How it works: 
You are unable to use Naturalized Ammunition on the Death's Door Fel Cannons:
https://streamable.com/dpbz9 - North Cannon
https://streamable.com/1tc9y - South Cannon

How it should work: 
You should be able to use Naturalized Ammunition on the Death's Door Fel Cannons
You then gain control of the cannon as your pet, allowing you to use [Artillery on the Warp-Gate](http://db.darkwizard.pl/?spell=39221) to destroy the  Warp-Gate.
"Seven shots will destroy a warp-gate."

Source:
https://www.wowhead.com/quest=10911/fire-at-will#comments
https://www.youtube.com/watch?v=cw41YDvokoU
https://www.youtube.com/watch?v=_aRqYXFDYis&feature=youtu.be

"After converting the cannon, nothing happens until after your first cannonball attack on the portal.
The cannonball & AoE flamethrower share a 15 second cooldown.
The first cannonball attack causes imps to spawn non-stop from the portal -- about one every 2-3 secs.
The imps explode in a short-range AoE to attack and head straight at the cannon.
The imps have 450hp, according to http://www.wowhead.com/?npc=22474
If you one-shot kill them, they don't explode, they just die.
If you hit and don't kill them, or generate threat in any way, they turn and explode on you instead of the cannon.

You need to have a pet bar available and visible to do this quest.

If you convert the cannon without clearing the area first, the mobs will attack the cannon if they wander within standard aggro range. 

Dogs (http://www.wowhead.com/?npc=22500) can / do spawn in at random intervals instead of imps. For me, southern portal spawned none, while the north one spawned two in succession halfway through the cannon blasts.

Some claim that side-stepping, or stepping away from the imp as you hit it may help dodge their exploding damage. 

If the cannon dies, just wait. It will respawn.

**Comment by Bzmode** [comment]
Still isn't working

**Comment by Squarz** [comment]
123

**Comment by codey07** [comment]
Please fix this quest! It contains a pre - BiS neck for resto shaman
