### ISSUE TITLE
Uldaman

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#185]
### **TO DO:**

- [ ] 1. Stonevault Oracle's (4842) Healing Ward totem (3560) should also heal npc's allies. For now it only heal its owner.
- [ ] 2. Alliance players should be able to talk with npcs from point 5. they should have some text to reply. I wasn't able to find anything about it :( 
**VIDEO NEEDED*
- [ ] 3. Summon Sand Storm (7226) should chase random player.
- [ ] 4. Sand Storm should chase player but never damage him by melee.
- [x] 5. Ancient Keeper Stone (7206) runs to fast.
- [ ] 6. Uldaman Boss Object Visual aura (11206) fades when player rotates while it shouldn't.
- [ ] 7. Grimlok and Basilisk next to him should have linked threat when pulled.

### **DONE:**

- [x] 1. Looks like Stonevault Oracle doesn't use his Lava Spout Totem spell (8264).
- [x] 2. Stonevault Oracle should cast Healing Wave spell (8005) also on his allies. For now he heals only himself.
- [x] 3. Stonevault Oracle should refresh Lightning Shield spell (945) even when he's out of combat. 
- [x] 4. There should be third dwarf boss next to those two named Olaf (6908).
![image](https://user-images.githubusercontent.com/22802214/44466146-db67a580-a61f-11e8-935e-82723aa45219.png)
- [x] 5. Eric "The Swift" (6907) uses his Rushing Charge spell (6268) even when he's in melee range. Was wondering if this spell should be able to cast when target is in 5-25y range? **Info needed.**
- [x] 6. Revelosh (6910) interrupts his own Lightnig Bolt (15801) casts by casting Chain Lightning (16006).
- [x] 7. Ironaya (7228) shouldn't have random movements.
- [x] 8. Ironaya should use her Arcing Smash spell (8374) more often.
- [x] 9. Cleft Scorpid (7078) uses his Poison spell (744) in correct way. However, no matter how many of them fightning me, only one Poison is applied on player. Every Cleft Scorpid should apply his own Poison even if target have it from other creature.
- [x] 10. Same thing but with Venomlash Scorpid's (7022) Venom Sting spell (8257).
- [x] 11. Shadowforge Sharpshooter (7290) should use his Piercing Shot spell (6685) more often.
- [x] 12. Shadowforge Darkcaster (4848) interrupts his own Mana Burn spell (15800) cast.
- [x] 13. Galgann Firehammer (7291) always casts two spells in same order Flame Shock (8053) -> Amplify Flames (9482) instead of more random choose.
- [x] 14. Stonevault Brawlers (4855) are moving extremely fast.
- [x] 15. Looks like Grimlok doesn't use his Shrink spell (11892) at all.
- [x] 16. Looks like Stonevault Ambusher (7175) doesn't use his Backstab spell (8721). He should use it only when melee from behind.
**EDIT: Still doesn't use it. Maybe becaused it requires energy and npc doesn't have it.**
- [x] 17. Looks like Stonevault Cave Lurker (4850) doesn't use Backstab spell (8721).
**EDIT: Still doesn't use it. Maybe becaused it requires energy and npc doesn't have it.**
- [x] 18. Looks like Ironaya doesn't use her Knock Away (10101) and War Stomp (11876) spells.
_Edit: She does at 50% and 25%. Confirmed with LH_
**EDIT: Her Arcane Blast spell (at 50%) should be replaced with mentioned Knock Away spell.** 
- [x] 19. Galgann Firehammer (7291) should spread those two spell through party members instead of casting/refreshing them only on tank: Flame Shock (8053), Amplify Flames (9482).
- [x] 20. All of four Stone Keepers (4857) are targetable before Altar event begins. They should have Stone aura (33652) when event is not active.
![image](https://user-images.githubusercontent.com/22802214/44471172-a3fef600-a62b-11e8-8596-c8ceecae0b00.png)
_GM off ;)_
**EDIT: Okey they aint targetable ;D but still they should stay "grey" with stoned aura before activation**
- [x] 21. Stone Keeper (4857) doesn't use Trample spell (5568).
- [x] 22. Stone Keeper shouldn't use Ground Tremor spell (6524).
- [x] 23. In Hall of the Crafters event we should face 4 Stone Keepers, after the are dead in order to open the door to final boss. After we kill first of Stone Keepers, second should activate and start to attack players immediately. For now he activates and become targetable but he doesn't attack till players move.
![image](https://user-images.githubusercontent.com/22802214/44484981-817ed400-a64f-11e8-8fbe-9184847ca826.png)
- [x] 24. Baelog, Olaf and Eric "The Swift" should be in pull formation with linked threat.
**EDIT: Olaf and Baelog are linked but Eric doesn't pull with them.**
- [x] 25. Looks like Jadespine Basilisk (4863) doesn't use his Reflection (9906) spell.
**EDIT#2: Still doesn't use it**
- [x] 26. Looks like Grimlok doesn't use his Bloodlust (6742) spell. He should cast it on other Stonevault npcs or his pet.
**EDIT: He didn't cast it even once for two entire fights**
_At 40% of HP :)_
**EDIT#2: Ye but he casts it on himself instead of ally**

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
List updated.
