### ISSUE TITLE
Spellstrike infusion set 

### ISSUE THREAD

**Issue by Adrestiah** [SunwellWoW/Sunwell-TBC-Bugtracker#1850]
Description : Spellstrike set is not proccing off channels. It also has a low proc chance right now. 

How it works: spell strike currently only works off spells that aren’t channeled like pyroblast or shadowbolt. It does not proc off channels (like mindflay) The proc rate is also low- less than 1/100 spells.

How it should work: The buff should proc off channels (such as mindflay) as it’s when harmful spells land. It should also be a 5% proc rate rather than a <1% proc rate

Source for proc rate: https://www.wowhead.com/item-set=559/spellstrike-infusion#comments

**Comment by ZaoQ** [comment]
well from the cast of the mindflay not from every tick of dmg i believe

**Comment by Wojtyas** [comment]
Quite important thing if it should proc on tick or complete channel

**Comment by Adrestiah** [comment]
If my research is correct, it should proc off only the first tick of a dot. Not sequential ticks, as the first tick is when the spell " lands". Currently it doesn't appear to be proccing off these. It WILL proc off burst damage, ( pyroblast, shadowbolt) but after sitting there for 15 minutes exclusively casting Mindflay, the spellstrike infusion buff never procced- that's about 350 spell casts give or take. either to proc rate is entirely too low, I have **_HORRID_** rng, or it's not procing off channels.

**Comment by Ghettomagus** [comment]
Issue opened 24th of November, still not fixed..... are you even trying?

**Comment by Woosty** [comment]
^^^ Two months later and no fix to gear that is supposed to be bis for multiple classes

**Comment by Euphx** [comment]
On behalf of all shadow priests, please prioritise fixing the issue with the set bonus. It's a noticeable DPS loss as it cannot proc via Mind Flay & other channelled spells.

**Comment by Macnjacks** [comment]
Can we get some attention on this bug? It's pretty major for people pushing the harder content. Shadowpriests are people too!

**Comment by akrom23** [comment]
I don't think that it should proc on every tick, rather on initial cast.
Mind Flay is a DoT.
```Each time you land a harmful spell``` for me it means ```Each time you casted and hit with a harmful spell```.
https://vanilla-twinhead.twinstar.cz/?issue=6587 - this is very similar issue.

Proc chance is already set to 5%.

**Comment by Ghettomagus** [comment]
> 
> 
> I don't think that it should proc on every tick, rather on initial cast.
> Mind Flay is a DoT.
> `Each time you land a harmful spell` for me it means `Each time you casted and hit with a harmful spell`.
> https://vanilla-twinhead.twinstar.cz/?issue=6587 - this is very similar issue.
> 
> Proc chance is already set to 5%.

Yes but as it stands now it is not proccing from the initial cast of Mind Flay or application of DoT's, which should also be "Landing a harmful spell", I'm sure other classes also have examples of spells where they don't proc the set. 
Also, Quagmirran's Eye which has almost exactly the same wording as spellstrike set procs just fine from both initial Mind Flay cast and application of DoT's.

**Comment by akrom23** [comment]
> Also, Quagmirran's Eye which has almost exactly the same wording as spellstrike set procs just fine from both initial Mind Flay cast and application of DoT's.

Are you sure? - just tested and did not proc off.

EDIT: You were right - works fine. I know now where is the problem with this set.
