### ISSUE TITLE
[Spell] [Warlock] Drains can be dispelled

### ISSUE THREAD

**Issue by Jeansapin** [SunwellWoW/Sunwell-TBC-Bugtracker#1851]
Decription: Theses 2 spells can be dispelled by a paladin or something that can dispell magical effects.
https://www.thegeekcrusade-serveur.com/db/?spell=27220  and https://www.thegeekcrusade-serveur.com/db/?spell=30908

How it works: Cast it on someone, he can dispell it. When he dispells it, the canalization is interrupted ...

How it should work: It should not be cleansed ... 

Source (you should point out proofs of your report, please give us some source):

**Comment by doomnyx** [comment]
https://us.battle.net/forums/en/wow/topic/2046567365

It is mentioned twice, that it is possible to dispel it, report seems invalid.

Also, why it should not be possible to dispel magic effects if those 2 spells?

**Comment by arcwizard** [comment]
Read for yourself what is written in your links https://www.thegeekcrusade-serveur.com/db/?spell=27220 "Type de dissipation | Magie"
