### ISSUE TITLE
[General] Deathknell House evade bugs mobs

### ISSUE THREAD

**Issue by koshimo** [SunwellWoW/Sunwell-TBC-Bugtracker#1852]
Decription: 
A house in the undead starting area evade bugs mobs that try to enter or leave it. It looks like the small steps are not scripted properly and mobs cannot walk on them. 

How it works: 
https://i.imgur.com/XTLJa0V.jpg
https://i.imgur.com/hRfhVBK.jpg

Mobs gets stuck on stairs in second picture.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented.
