### ISSUE TITLE
[NPC] Aean Swiftriver <Alliance Outrunner>

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1854]
Decription: 
Aean Swiftriver Patrol in The Barrens has two nightelves that pat directly on top of eachother

How it works: 
Aean Swiftriver Patrol has two nightelves that pat directly on top of eachother
https://streamable.com/4r023
How it should work: 

Aean Swiftriver Patrol pack should be evenly dispersed and not be patting with their models directly on top of eachother
Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented (SSC realm so far).
