### ISSUE TITLE
[Spell] Nature's Grace

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1856]
New issue related to fix from https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1404#issuecomment-441363593

"It is proccing, but it's being consumed by moonfire ticks and lightning capacitor charges which are definitely NOT spells being cast."

**Comment by Altgreen** [comment]
And now it's not working again at all.

**Comment by Wojtyas** [comment]
<crying>

**Comment by Jekenius** [comment]
Working fine to me, but it consumes by any kind of spells it seems(for example my trinket proc(30626) ate the buff at same time it appeared or smth like this), not only castable my the druid spells only.
![image](https://user-images.githubusercontent.com/45003723/48968835-d3a50c00-f027-11e8-9080-a97df7fcea5b.png)
![image](https://user-images.githubusercontent.com/45003723/48968837-dbfd4700-f027-11e8-92f8-08bbb09fa2a6.png)

**Comment by Altgreen** [comment]
Works with Moonfire, still doesn't work with Lightning Capacitor.
![screenshot 16](https://user-images.githubusercontent.com/45273682/48973415-027aac80-f03f-11e8-870f-3b555071404e.png)

**Comment by RavenRiley** [comment]
It have been consumed by any kind of trinket's power ups too

**Comment by Altgreen** [comment]
yeah, but it's not supposed to be ... hence the issue :)
