### ISSUE TITLE
[Raid] Karazhan - PART TWO

### ISSUE THREAD

**Issue by Adamsek** [SunwellWoW/Sunwell-TBC-Bugtracker#186]
**Overall notes:**
 Same notes as previous: see Karazhan - PART ONE: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/178

**More issues of Karazhan B is related to bosses, so trashes first then bosses one by one.**

- [x] Most of trashes just respawns (after killing every boss)
- [x] **Arcane Watchman**'s **Overload** spell is not dealing any damage to player(s)
http://wowwiki.wikia.com/wiki/Arcane_Watchman
- [x] **Arcane Anomaly** doesnt use **Teleport** spell, he cast **Mana Shield** too late, he shouldnt be one-shoted (lethal damage on pull should activate his Mana Shield immediatly)
http://wowwiki.wikia.com/wiki/Arcane_Anomaly
- [x] **Mana Feeder** should be immune to any kind of magic, not using **Astral Bite**
http://wowwiki.wikia.com/wiki/Mana_Feeder
- [x] **Chaotic Sentience**'s **Unstable Magic** gives to much spell power (600) but damage taken seems to be fine
![wowscrnshot_082118_211908](https://user-images.githubusercontent.com/42385556/44469504-f2aa9100-a627-11e8-8831-7f25ff92b52f.jpg)
- [ ] **Sealed Tomes**, as soon as **Wrath of the Titans** and **Legacy of the Mountain King** procs are okay while **Torment of the Worgen** is way too powerful, **Redemption of the Fallen** also has issue with AoE heal( summonig to much healers), procs from single traget heal are rather OK.
![wowscrnshot_082118_212413](https://user-images.githubusercontent.com/42385556/44469809-95fba600-a628-11e8-8f9e-071d4c8bf2cc.jpg)
![wowscrnshot_082118_212803](https://user-images.githubusercontent.com/42385556/44469819-9a27c380-a628-11e8-9545-ed325301476f.jpg)
http://wowwiki.wikia.com/wiki/Torment_of_the_Worgen http://wowwiki.wikia.com/wiki/Redemption_of_the_Fallen

- [x] **Shadow Pillager** doesnt cast **Shadow Bolt** ability
http://wowwiki.wikia.com/wiki/Shadow_Pillager
- [x] **Sorcerous Shade** should be immune to any kind of CC
- [x] **Ethereal Thief** doesnt use **Cleave** and **Disarm** abilities
- [x] **Ethereal Spellfilcher**'s **Transference** not working as intended
http://db.hellfire-tbc.com/?spell=30039
- [x] There are no **Greater Fleshbeasts** in Karazhan 
http://wowwiki.wikia.com/wiki/Greater_Fleshbeast
- [x] **Fleshbeast** acts like **Greater Fleshbeast** (spells)
http://wowwiki.wikia.com/wiki/Fleshbeast_(mob)
- [x] I noticed that every Kara reset there is same setup in Servant Quater, there are Shadikith the Glider and Hyakiss the Lurker, Rokad the Ravager never spawns.

**Bosses**

**Dorothee and The Crone**
- [x] **Roar** is not immune to hibernate
- [x]  Players with fear falling in textures sometimes
- [x] Fire spells should disorient **Strawman** (sometimes did but it looks like 1%chance)
http://wowwiki.wikia.com/wiki/Strawman
- [x]  **The Crone**'s **Cyclone** left stage area goes into textures

**Big Bad Wolf**
- [x]  Should use abilities more often
- [x]  After **Little Red Riding Hood** debuff fades, Wolf stays on target ignoring previous tank.
- [x] Players with fear falling in textures sometimes

**The Curator**
- [x] Visual bug when patrolling his area, he looks like freezed sometimes but its just visual, he is walking his path as intended - it can cause happy pulls.

**Terestian Illhoof**
http://wowwiki.wikia.com/wiki/Terestian_Illhoof
- [x] Two Terestian's were spawned
- [x] You can pull boss without Kil'rek and the other way u can pull Kil'rek, and then kill boss (he won't spawn him again)
- [x] Imps from portals won't aggro if u are far enough from portals
- [x] Terestian doesnt use **Sacrifice** spell
- [x] Boss doesnt get debuff after Kil'rek is killed
- [x] He doesnt summon Kil'rek (there is only one at start)
- [x] There shouldnt be any reputation from small imps
- [x] Sometimes only one portal spawns imps

**Shade of Aran**
http://wowwiki.wikia.com/wiki/Shade_of_Aran
- [x] **Flame Wreath** doesnt deal any damage if u are moving in fires
- [x] In some circumstances he is able to move from the middle of the room - he shouldnt
- [x] He cast **Arcane Missiles** and then channel them, it should be channelling only
- [x] In pre-nerf he used to have **Dragon's Breath** - the trick is if any person gets Breath and he is affected by **Flame Wreath** he shouldnt blow up another players (if devs decide to implement Dragon's Breath, that is how it works)

**Chess event**
- [ ] Some Footmans dont give a fuck
![wowscrnshot_082118_223000](https://user-images.githubusercontent.com/42385556/44471422-28517900-a62c-11e8-9a4e-2ead2b3632ee.jpg)
- [x]  **Move** spell has too much delay
- [ ]  Some of Horde figures didnt move (they used spells)
- [ ] Warchief Blackhand was healed with both Necromancers dead somehow (?)
- [ ] Another players can't open chest (Group Loot issue)
- [x] **Silence** in chess room didn't disappear after game was finished

**Prince Malchezaar**
http://wowwiki.wikia.com/wiki/Prince_Malchezaar
- [x]  Should walk around platform
- [x]  Should have 300% movemnet speed
- [x] There is no -100% to heal debuff on **Enfeeble**
- [x] He is placing Infernals in the same spot (Phase 1 and 2 at least)
- [x] Infernals are despawning too fast

**_Note: Melee damage of Prince seems to be accurate, maybe his melee damage in phase 1 and 3 could be a little bit higher but i remember on Hellground they buffed whole Karazhan including bosses and Malchezaar was one-shoting tanks in phase two (roughly 20k damage in 0.01 sec)_**

**Netherspite**
http://wowwiki.wikia.com/wiki/Netherspite
- [x] If u target him right-clicking he will pull on you at any range (even behind door)
- [x] Lasers from portals are not visible
- [x] He doesnt reset aggro between phases
- [x] He doesnt use **Void Zone** ability

**Nightbane**
http://wowwiki.wikia.com/wiki/Nightbane_(boss)
- [x] Summoning space is very small (urn triggers at wall only)
- [x] Should casts his spells way more often
- [x] He uses **Bellowing Roar** on one person
- [x] He doesnt use **Tail Sweep** ability
- [x] After initial flying around, he should land and get aggro immedietly, instead he is in the air not in line of sight, needed to be body pulled
- [x] When tank wants to move him he flies into the air and then lands, he should just run on the ground.
- [x] **Restless Skeletons** doesnt use their aura AoE spell (pre-nerf spell - fire aoe damage 10y range or 
so(?), cant remember the name)
- [x] Skeletons didnt despawn after wipe
- [ ] **Fireball Barrage** works inappropriate, he should cast it on target that is too far away but he casted it no matter of range and hit way too low

Some cool screens after fixes (?) minions just walking wherever they want even outside Kara

![wowscrnshot_082218_184919](https://user-images.githubusercontent.com/42385556/44477937-6c4c7a00-a63c-11e8-8260-d6b8792b6cef.jpg)
![wowscrnshot_082218_183142](https://user-images.githubusercontent.com/42385556/44477980-87b78500-a63c-11e8-9884-0e7c4ab2c0e0.jpg)
![wowscrnshot_082218_180510](https://user-images.githubusercontent.com/42385556/44477988-8e45fc80-a63c-11e8-9f81-13bf8a10566a.jpg)

Fight with Nightbane an Curator just outside Karazhan:
![wowscrnshot_082218_183640](https://user-images.githubusercontent.com/42385556/44477994-93a34700-a63c-11e8-8813-17a4f1afe6ec.jpg)

**Comment by babno** [comment]
Adding onto yours, romulo and juliet, romulo does not drop loot while juliet drops 1 badge and 1 item. Fight seems to work as intended otherwise.

**Comment by Adamsek** [comment]
@babno Before commenting please read the whole.

**Comment by notsofamous** [comment]
https://github.com/Schaka/TBC-research/issues/11
