### ISSUE TITLE
[Druid] Primal Tenacity

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1860]
"Increases your chance to resist stun and fear mechanics by 5/10/15%"

Tested the stun resistance against Vashj, did not work at all.

![Image](https://i.gyazo.com/833187228826d5d7c9a9f1fecc1bcdbe.png)

Basic spell resistance is ~7.5% shown here:
![Image](https://i.gyazo.com/8dd754043951faf3b377c2b97def554c.png)

I haven't tested the fear resistance but I would guess it doesn't work either.

**Comment by akrom23** [comment]
You should also check with other spells. This spell (Shock Blast) is missing mechanic stun.

**Comment by lukaasm** [comment]
yeah, the issue lies with Shock Blast and other non-pure stuns. Will be fixed anyway :)

**Comment by akrom23** [comment]
Talent works. The problem are specific spells.
