### ISSUE TITLE
[Spell] Dust Cloud (Elder Plainstrider in Mulgor) 

### ISSUE THREAD

**Issue by urodphoenix** [SunwellWoW/Sunwell-TBC-Bugtracker#1862]
Decription:  Ability "Dust Cloud" (id=7272) of Elder Plainstrider (id=2957)  has no description.

How it works: when apply shows debuff name, type and timing only

How it should work: must show name, type, timing and debuff description

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/spell=7272/dust-cloud

**Comment by Dootz** [comment]
It most likely didn't have description back in tbc days. 
https://db.excalibur.ws/?spell=7272
http://db.hellfire-tbc.com/?spell=7272
