### ISSUE TITLE
[Item] Powerful Earthstorm Diamond

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1863]
The 5% stun resistance on this gem doesn't work.

With the gem:
![Image](https://i.gyazo.com/f444ed463e0def7638d66c1c6ae59abd.png)

Without the gem:
![Image](https://i.gyazo.com/833187228826d5d7c9a9f1fecc1bcdbe.png)

Note: this is with Primal Tenacity talent, so base stun resist should be 20% and then regular resistance to spells on top of that.

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1860
