### ISSUE TITLE
[Dungeon] The Shattered Halls: Sometimes mobs are unkillable.

### ISSUE THREAD

**Issue by Denziz** [SunwellWoW/Sunwell-TBC-Bugtracker#1864]
Decription: 
Today when me and 4 other people went to test out The Shattered Halls on Heroic Mode, we noticed on the first pack that we killed that people were flopping over for no reason, that people were taking damage but there were no mobs in sight. 

It seems that one mob that we killed was not dead, but it was dead. I know that sounds really weird but I have a screenshot here to make this a lot easier to understand and GM. Crafty was really nice to help us out. He also witnessed the bug in action and tried to fix it.

Here is the screenshot of the bugged mob that is dead, it has 0 HP yet it goes around and attacks people. 

Screenshot:
![mob on a frenzy](https://user-images.githubusercontent.com/5758943/48970849-c9781300-f011-11e8-83bc-90b1eb8391d1.jpg)

How it works: 
We do not know what is the occurring factor that triggers this bug. However, Ugar said it might have been his execute but we tested this by making him 1v1 a mob and to use execute in order to kill the mob and sometimes it happened and sometimes it didn't.

We also noticed when for example I was targeted by the invincible mob that in order to fix it I had to go out of the dungeon and back inside. When it reset the mob that was unkillable was back in place with around 25k HP,  (I do not have a screenshot of this, sadly).

I would also like to say that this is not a specific mob, it happened to us on a boss, Blood Guard Porung.

Here is a screenshot proving it.
![boss bugged](https://user-images.githubusercontent.com/5758943/48970886-7488cc80-f012-11e8-90b0-e80608ac006f.jpg)

How it should work: 
The mob should not go on a mad frenzy when it's dead and start to attack people. When the HP reaches 0 it should lie down on the floor DEAD.

Source (you should point out proofs of your report, please give us some source): 
I don't know what to put here as this is obviously a bug of some sort, the mob should stay dead and should not be able to attack people when it has 0 HP.

**Other bugs:**
1. Decription:
I would also like to point out that warrior's execute heals for a ridicilous amount, here is a screenshot to show this is true.

Execute heals:
![execute heals](https://user-images.githubusercontent.com/5758943/48970938-8880fe00-f013-11e8-8c95-aae1f6cfccf5.PNG)

I do not know how much it should heal for.

2. Decription:
Priest's Spirit of Redemption upon death they are respawning with full health and mana back, so they are pretty much unkillable. (Do not have a screenshot of this).

**Comment by Sanders9352** [comment]
That NPC could not be killed (die or Death Touch) or respawned. After everyone was dead (reset encounter) it went to his original spawn point and regained HP, and standing up. Everything was normal afterwards.

NPC Info while it was immortal https://imgur.com/a/BfkpUnk
NPC Info afterwards https://imgur.com/a/H8XGj2p

**Comment by Jekenius** [comment]
One thing i can add about that "execute heals", our fury warrior executed mobs sometimes and some of his executes made huge amount of healing(that healing was done to the mob he executed) after that thing mobs were crazy and attacking from the death. Havent done any screenshots, sadly.

**Comment by Krefty** [comment]
That NPC could not be attacked or killed (.die, death touch or .respawn) but he could attack the players.
After resetting the encounter (everyone being dead) the NPC went back to his original spawn point, regaining HP and standing up.

NPC Info while it was immortal - https://imgur.com/a/BfkpUnk
NPC Info afterwards - https://imgur.com/a/BfkpUnk

**Comment by Dagarz** [comment]
Here's screenshot of issue in Old Hillsbrad Foothils - http://wrzuc.se/i/5bf9b0774566a

Here's screenshot of exact amount of healing by Execute (from SHH) - http://wrzuc.se/i/5bf9b1d54dc00

**Comment by sicknot1** [comment]
Hapenned in Kara today, the undead horses
