### ISSUE TITLE
[Item] Warclok's tier 5 (4) set bonus is not working.

### ISSUE THREAD

**Issue by Jekenius** [SunwellWoW/Sunwell-TBC-Bugtracker#1865]
Decription: Shadowbolt hits should affect corruption damage, but they dont do anything(no buff applied, no combat log info about that set bonus is working).
![wowscrnshot_112518_002216](https://user-images.githubusercontent.com/45003723/48971245-ad906380-f049-11e8-9b00-ca57d94b8fcd.jpg)

How it works: If i cast shadowbolt and use corruption afterwards corruption deals same damage if i wouldnt use shadowbolt.

How it should work: I dont know how should that set work exactly, but it doesnt work at all. Suppose there should be some kind of buff applied. Also, that buff should stack, following info sites about that set.
http://wowwiki.wikia.com/wiki/Corruptor_Raiment
https://wow.gamepedia.com/Corruptor_Raiment

Source (you should point out proofs of your report, please give us some source): Tested in game, some proofs here.
![wowscrnshot_112518_000454](https://user-images.githubusercontent.com/45003723/48971195-1c20f180-f049-11e8-9fc4-8e7b4a3af795.jpg)
(Shadow trance is affli warlock talent(Nightfall) caused by corruption tick and making next shadow bolt instant cast)
![image](https://user-images.githubusercontent.com/45003723/48971220-4e325380-f049-11e8-974d-3bb7e7dced19.png)

![wowscrnshot_112518_000909](https://user-images.githubusercontent.com/45003723/48971200-2216d280-f049-11e8-8e6c-1a85962e52c0.jpg)
(Used Immolate before the Corruption)
Same 451 damage from corruption.

**Comment by woortoo** [comment]
Wish to contact you. Do you know The RED TS?

**Comment by koostosh** [comment]
Works correctly. You should cast corruption before shadow bolt (or immolate before incinerate) not the other way. It increases effect of dots currently on target.
