### ISSUE TITLE
[Rogue] Sword Specialization 

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#1869]
Decription: 
I dide like 1,5K melee swings during the fight on dummie. I see Sword specialization impact only basic melee (white) hit. I shoud have chance to get additional hit while Sinister Strike and other kinds of atack types

How it works: 
onle simple (white hit) melee had chance to do an extra atack.
![wowscrnshot_112418_214845](https://user-images.githubusercontent.com/43553985/48972887-140a8700-f034-11e8-96d1-f5c97e96c943.jpg)

How it should work: 
every kind of atack shoud have 5% chance to get an extra atack of his kind. 

Source (you should point out proofs of your report, please give us some source):

**Comment by doomnyx** [comment]
Sword specializations for warrior and for rogue proc as white attacks, categorized as Melee (Sword Specialization). They do proc from yellow attacks, sum up your hit + crit + glancing on direct damage abilities and * 0.05.

![image](https://user-images.githubusercontent.com/14941185/48973280-3e604280-f03c-11e8-9033-fc058311ca4e.png)

Image self explanatory, report invalid.
