### ISSUE TITLE
[warrior][spell] Thunderclap and improved thunderclap - tooltip

### ISSUE THREAD

**Issue by sicknot1** [SunwellWoW/Sunwell-TBC-Bugtracker#1872]
Decription: 
Thunderclap reduces attack speed by 10% instead of 20%

How it works: 
Thunderclap reduces attack speed by 10% instead of 20% with the talent IMPROVED THUNDERCLAP
![image](https://user-images.githubusercontent.com/35937937/48973114-ed8a2300-f016-11e8-8c4f-9bc4bcc3a2b3.png)

How it should work: should be 20% reduction
should work like this
![image](https://user-images.githubusercontent.com/35937937/48973123-23c7a280-f017-11e8-89a5-8abe438cae2b.png)

Source: posted at the start

**Comment by Wojtyas** [comment]
Exactly, tooltip won't show values increased by talents modifications and it's not a bug but normal feature.
