### ISSUE TITLE
[Spell] Chain Heal

### ISSUE THREAD

**Issue by KespadA** [SunwellWoW/Sunwell-TBC-Bugtracker#1875]
Decription: 

**How it works:** It bounces to random players, regardless of faction.
It never bounces to hunter pets, especially if they are in a party with you.
Chain Heal sometimes will and sometimes won't bounce at all.

**How it should work:** Per the tooltip, Chain Heal should not bounce to unpartied players if it is cast on a party member (same with pets). 
It should not bounce to the other faction, even if they are in a sanctuary. Chain Heal should bounce to hunter pets.

Source (you should point out proofs of your report, please give us some source): 
Chain Heal bouncing to unpartied members: https://gfycat.com/HandyPeacefulBedlingtonterrier
Chain Heal bouncing then not bouncing arbitrarily based on caster position: https://gfycat.com/SparklingGrossAchillestang
Chain Heal not bouncing to pets: https://gfycat.com/SaltyCaringFirebelliedtoad

**Comment by Wojtyas** [comment]
Looks like its done in 50%.

- [x] It won't jump to target with full hp when there are not full hp players in spell range - correct.
- [ ] Spell jumps should always pick lowest hp targets in jump range.

**Comment by Aeded** [comment]
1. Chain heal should always bounce to player/pet that has lowest amount of HP (not by number but by %)
2. Chain heal should bounce to pets
3. Chain heal should never bounce to friendly NPC (alliance and horde troops during encounter in hyjal) and to Earth or Fire Elemental. However, you should be able to directly cast chain heal on these units. 
4. If you cast directly chain heal on friendly NPC/Shaman elementals like mentioned above, it should still only bounce to player/pet if there are in range. If there are no players/pets in range it should not bounce at all.
