### ISSUE TITLE
[Heroic] Blood Furnace Broggok 

### ISSUE THREAD

**Issue by Anduyon** [SunwellWoW/Sunwell-TBC-Bugtracker#1879]
Decription: 
Broggok is not casting his Poison Cloud Ability.
How it works: 
Currently does not cast this ability.

How it should work: 
Broggok should be casting Poison Clouds under him, making it necessary to move him around a bit.
https://www.wowhead.com/spell=30916/poison-cloud
Source (you should point out proofs of your report, please give us some source): 
Video will be added when its uploaded.

**Comment by YoshGit** [comment]
Last I ran blood furnace it looked like he was casting the cloud, but the clouds were disappearing too quickly. Probably the same issue.
