### ISSUE TITLE
[Item] Health Potion, Mana Potion, Healthstone

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1881]
All Health Potions, Mana Potions and Healthstones (probably demonic/dark runes also?) should have a base chance to crit, increasing it's effect by 50%. The exact crit chance is unknown but I would guess it's around 5%?

https://www.mmo-champion.com/threads/618263-Health-potion-Healthstone-crit
http://wow.allakhazam.com/wiki/potions_%28WoW%29
http://wowwiki.wikia.com/wiki/Potion

Tested ~400 health potions without getting a crit

**Comment by doomnyx** [comment]
I got a crit from Healthstone recently, dk about potions.
