### ISSUE TITLE
[Zone] [Duskwood]

### ISSUE THREAD

**Issue by Lonoss** [SunwellWoW/Sunwell-TBC-Bugtracker#189]
- [x] NPC - Mabel Solaj <General Goods> GUID: 4203 Entry: 227
http://db.hellfire-tbc.com/?npc=227
I dont know exact route or place for this NPC but moste of time he is in textures.

- [x] NPC - GUID: 5945 Entry: 565
http://db.hellfire-tbc.com/?npc=565#abilities
He use his ability (Rabies) to rarely.

- [x] NPC - Skeletal Fiend GUID: 5958 Entry: 531
http://db.hellfire-tbc.com/?npc=531#abilities
Does not use ability: Fiend Fury

- [x] NPC - Skeletal Horror GUID: 5942 Entry: 202
http://db.hellfire-tbc.com/?npc=202#abilities
Does not use ability: Terrify

- [x] NPC - Insane Ghoul GUID: 4444 Entry: 511
http://db.hellfire-tbc.com/?npc=511#abilities
Use his ability to rarely.

- [x] NPC - Bone Chewer GUID: 4962 Entry: 210
http://db.hellfire-tbc.com/?npc=210#abilities
Use his ability to rarely.

- [x] NPC - Mor'Ladim GUID: 5086 Entry: 522
http://db.hellfire-tbc.com/?npc=522#abilities
Uptime abilty Enraging Memories is almoste 100%
That create a posibility to kite mob all time even with no speed boost ability. I can kite it 1 min and get 3-5 hits from him. With instant cast spels you can solo it. I am not sure how should work but now looks to easy.

- [x] NPC - Skeletal Warder GUID: 5095 Entry: 785
http://db.hellfire-tbc.com/?npc=785#abilities
Does not use ability: Quick Flame Ward
Source: By Shoo on 2007/10/16 (Patch 2.2.3)		
these mobs can be a pain for a fire mage..they cast a very quick "Quick Fire Ward" making them immune to fire for a few seconds.

- [x] NPC - Nightbane Shadow Weaver GUID: 533 Entry: 27
http://db.hellfire-tbc.com/?npc=533#abilities
Does not use ability: Shadow Word: Pain (Rank 4)

- [x] NPC - Splinter Fist Warrior GUID: 5079 Entry: 212
http://db.hellfire-tbc.com/?npc=212#abilities
Does not use ability: Battle Shout (Rank 2)

- [x] NPC - Morbent Fel GUID: 5056 Entry: 1200
http://db.hellfire-tbc.com/?npc=1200
NPC runig in textures. His normal spown place shoud be upstairs.
https://www.wowhead.com/quest=55/morbent-fel#screenshots:id=99620

- [x] NPC - Eliza GUID: 0 Entry: 314
http://db.hellfire-tbc.com/?npc=314#abilities
Does not use ability: Summon Eliza's Guard

- [x] Quest - Digging Through the Dirt
http://db.hellfire-tbc.com/?quest=254
How it works: Quest can't be taken. 
How it should work: After complete other quest you should be able to take a quest from Eliza's Grave Dirt. Prapobly it should be a repetable quest.

**Comment by Dootz** [comment]
~~[ ] NPC - Mabel Solaj <General Goods> GUID: 4203 Entry: 227
http://db.hellfire-tbc.com/?npc=227
I dont know exact route or place for this NPC but moste of time he is in textures.~~

> Most likely something with movement-related is not updated on ptr, locally it works fine. I followed her for couple minutes.

~~[ ] NPC - GUID: 5945 Entry: 565
http://db.hellfire-tbc.com/?npc=565#abilities
He use his ability (Rabies) to rarely.~~

> Timer for Rabies is the same across different databases (TrinityCore, Sunwell, Hellground) so i'm not sure if we should adjust it.

~~[ ] NPC - Skeletal Fiend GUID: 5958 Entry: 531
http://db.hellfire-tbc.com/?npc=531#abilities
Does not use ability: Fiend Fury~~

> He does - at 30% of HP

~~[ ] Quest - Digging Through the Dirt
http://db.hellfire-tbc.com/?quest=254
How it works: Quest can't be taken. 
How it should work: After complete other quest you should be able to take a quest from Eliza's Grave Dirt. Prapobly it should be a repetable quest.~~

> Nah, that's how it is supposed to work. There are two quests. You need to have http://db.hellfire-tbc.com/?quest=253 active to be able to pick up http://db.hellfire-tbc.com/?quest=254 from grave.
