### ISSUE TITLE
druid natures swiftness going away on instant casts. 

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#1891]
Decription: 

NS goes away if u cast farei fire for isntance.
How it works: 
it goes away on instant

How it should work: 

should only be consumed if u use a spelll with cast time
Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
There should be already fix for it - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1795
Not sure if it's not implemented yet or Akrom's fix it's not working properly.

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).
