### ISSUE TITLE
arcane missles does not always cast

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#1892]
Decription: 
the spell does not cast but consumes mana, then when it does the visual is not there.

How it works: 

wrong
How it should work: 

should go on first time you try
Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Observed on players/hostile/neutral mobs?

**Comment by baade123** [comment]
players. also sometimes it channels but does -0 dmg

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).
