### ISSUE TITLE
should not be able to charge up / down bridge in arena

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#1893]
Decription: 
blades edge i believe its called (with the bridges) You can charge from up top to down below and vice vversa.

How it works: 

How it should work: 
dont think thats right

Source (you should point out proofs of your report, please give us some source):

**Comment by siof** [comment]
proofs

**Comment by Wojtyas** [comment]
or didnt happen

**Comment by Riztazz** [comment]
NUDES?
