### ISSUE TITLE
[Spell] Execute

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1894]
There is a glitch in Execute spell (or maybe some more?) that shows it healed owner for enormous amount when actually its not healing him.

https://gyazo.com/1f9f295ebf9746814eca03d2dea64594

**Comment by neheri** [comment]
It actually heals. In addition to that, it heals mobs after their death (lol) which causes them to walk and attack while dead.

![wowscrnshot_112618_171346](https://user-images.githubusercontent.com/37372869/49026694-ceb69880-f19e-11e8-8763-a50b3fee4052.jpg)
![wowscrnshot_112618_171312](https://user-images.githubusercontent.com/37372869/49026695-ceb69880-f19e-11e8-95e7-32c110affe66.jpg)
![wowscrnshot_112618_171341](https://user-images.githubusercontent.com/37372869/49026696-cf4f2f00-f19e-11e8-95b8-5ae058c4c4d8.jpg)
![wowscrnshot_112618_171343](https://user-images.githubusercontent.com/37372869/49026699-cf4f2f00-f19e-11e8-8673-6afa765ab4b4.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented.
