### ISSUE TITLE
[Movement] Mob Fanning issue?

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#1896]
Decription: Night elves have a large hitbox which forces npcs to run through you and behind you or to your side at the start of combat.

How it works: https://www.youtube.com/watch?v=7lIAkYFtzNE The mob is engaged and then runs directly behind or to the side of the night elf.
https://www.youtube.com/watch?v=UTyXdVol1DY also happens when engaged via melee.

How it should work: The mob should engage you from the front.

Source (you should point out proofs of your report, please give us some source): https://youtu.be/5VNRq7BmQwA?t=381 I'm not necessarily going to find a source on how mobs interact with your character, should be somewhat common sense to realize the issue is incorrect. Posted is an Elysium (nostalrius core) video.

**Comment by Wojtyas** [comment]
Fixed & implemented (only on SSC realm for now).
