### ISSUE TITLE
[Mobs] [Movement] Un'Goro Crater

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#1897]
Decription: / How it works: 
- Mobs in Un'Goro Crater often have weird movement
- after pull or even infight, mobs run behind and/or next to you very often in order to attack
- i should get a video tool to record this properly coz screenshots wont rly show the issue - can u recommand one?

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Same as https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1896
Probably correction to mob fanning is needed
