### ISSUE TITLE
Moonkin able to cast Mount while shapeshifted

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#1898]
Decription: Moonkins are able to cast and complete the casting of mounts (does not actually mount you) without the game automatically shifting you back to human form. All other shapeshift forms work properly and currently will cancel your shapeshift aura to mount excluding moonkin form.

How it works: https://imgur.com/a/Zuxeb0d Currently I am able to completely cast my mount in moonkin form.

How it should work: The game should remove me from Moonkin form back to Human form.

Source (you should point out proofs of your report, please give us some source): https://eu.battle.net/forums/en/wow/topic/916823184 As you can see the poster mentions that the old functionality was as explained, you should be sent to human form and mount anyways.

**Comment by akrom23** [comment]
Please, check other mounts - it might be a problem only with this specific mount.

**Comment by Jseay1313** [comment]
you are spot on, only happening with the AQ40 mount, can go ahead and close it my bad
