### ISSUE TITLE
[Spell] Ancestral Fortitude and Inspiration

### ISSUE THREAD

**Issue by doomnyx** [SunwellWoW/Sunwell-TBC-Bugtracker#1899]
Decription:  http://db.hellfire-tbc.com/?spell=16237
http://db.hellfire-tbc.com/?spell=15359

How it works:  Buffs are stacking, both giving 25% extra armor.

How it should work: They should not stack, if one of those effect is present on the target, the second one should overwrite other because of longer duration.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Ancestral_Healing?direction=next&oldid=1658119

Information from WotLK prepatch, but could not find stacking both buffs at once when watching many vids from retail.

**Comment by notsofamous** [comment]
Are you sure about that scroll part? Because they do completely different things

**Comment by doomnyx** [comment]
Then, why people on retail were buffed with agi and str scrolls, but not armor?

**Comment by akrom23** [comment]
Linked to #385.

**Comment by notsofamous** [comment]
Afaik the armor buff from the scroll does not scale with % increases like the healing buff or druid bear form, making the benefit from using it very minor. That's the main reason people didnt use it.

**Comment by doomnyx** [comment]
123
