### ISSUE TITLE
Channeled Spells are being partially resisted

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#1900]
Decription: Channeled spells are currently being partially resisted as well as completely resisted, prior to dots being changed in 4.0.1 to crit, channeled spells behaved like damage over time abilities and they were not able to be partially resisted. Channeled spells should either hit for full damage or be flat out resisted.

How it works: https://imgur.com/a/K2JaLof Hurricane is currently being partially resisted and fully resisted.
https://imgur.com/a/up4LkCu blizzard as well

How it should work: Channeled spells should only be fully resisted or hit for full on the damage applications.

Source (you should point out proofs of your report, please give us some source): https://wow.gamepedia.com/Channeling

Resists: Due to most channeled spells being binary effects (with the exception of [Arcane Missiles]), such spells can only hit or miss; partial resists are not possible

Currently, all channeling spells (except Arcane Missiles) technically cause periodic damage, which means that they behave like damage over time spells for the most part.

https://wow.gamepedia.com/Damage_over_Time

As of patch 4.0.1, all DoTs can crit,

**Comment by Jseay1313** [comment]
I can't really argue with that video, nor dots in general, but vividly remember channeling spells not being partially and fully resisted,

**Comment by Wojtyas** [comment]
"Due to most channeled spells being binary effects..." so there may be some channeling spells that should be resisted anyway :D 

I can't argue, in general they have only 0-1 resist so fair enough.

**Comment by Jseay1313** [comment]
bump, almost seems like casting blizzard or hurricane would be useless if it can be fully resisted each individual tick and partialed.
