### ISSUE TITLE
Battle chicken

### ISSUE THREAD

**Issue by Boza1610** [SunwellWoW/Sunwell-TBC-Bugtracker#1902]
Decription: 

How it works: 
She just standing still after summoning 

How it should work: 
She sould ofc go for enemy and after exiting combat give haste buff .

Source (you should point out proofs of your report, please give us some source):

**Comment by RPAncap** [comment]
Any info on this ? This is pretty important thing in raid enviroment - 5% HASTE BUFF for whole party for 4 minutes is something that imba and its one of the things progression guilds used to bring down bosses.

This is what it is supposed to cast : 
https://db.excalibur.ws/?spell=23060

**Comment by RPAncap** [comment]
BUMP ?

**Comment by akrom23** [comment]
It works. There is no 100% chance.
![wowscrnshot_012319_220040](https://user-images.githubusercontent.com/1035215/51636812-727fb300-1f5a-11e9-909c-efb0523f5c74.jpg)

**Comment by RPAncap** [comment]
Sorry for opening this again but could you please tell me what is the chance for it to actually cast the buff ? Because I havent seen it yet :-(

**Comment by Dootz** [comment]
Hi, there's 40% chance every 30-60 seconds.

**Comment by RPAncap** [comment]
And does the pet have to be actively fighting for the cast to happen ? Because sometimes the pet just stands next to me and doesnt engage in the fight :-X
