### ISSUE TITLE
[Karazhan] Can re-enter instance after dying to a boss, while encounter is in progress. not sure if intended

### ISSUE THREAD

**Issue by sicknot1** [SunwellWoW/Sunwell-TBC-Bugtracker#1905]
Decription: i can re-enter instance while encounter is in progress

How it works: i can re-enter instance while encounter is in progress

How it should work: i guess i shouldn't be able to do it.

Source (you should point out proofs of your report, please give us some source):

**Comment by sicknot1** [comment]
Attumen the Huntsman @akrom23

**Comment by Wojtyas** [comment]
Fixed & implemented.
