### ISSUE TITLE
Autoattack's bug when kiting (NOT THE SAME AS MELEE RANGE BUG)

### ISSUE THREAD

**Issue by Bugadin** [SunwellWoW/Sunwell-TBC-Bugtracker#1906]
Description: 
Melee range seems to work decently but there is a bug at kiting, which is a bit difficult to reproduce, that happens when players fights at melee range. The bug has to do with melee range but it's not the same as that bug that happened to all melees  1 week ago.

How it works: When you are fighting at melee range and you kite your enemy (you slow him and go back a bit to avoid his damage) the last autoattacks before players separate keeps landing on each other a few miliseconds. The number of AA that someone land on the other depends on your speed attack: As a rogue, I can land him 2-3 AA and the warrior lands me 1 most cases.
Then, range turns correctly again until you try to kite again.

How it should work: At melee range, if a player kites other, the last autoattacks right after you separate from the other player shouldn't land on the enemy in both cases( enemy to me or viceversa). The autoattack's animation should get canceled until enemy player is in range again.
This is an annoying bug that turns some matches(mage vs warr,  rogue vs warr,  hunter vs any melee... and so on) nearly impossible.

Source (you should point out proofs of your report, please give us some source): 

https://ibb.co/HPBT422 On this picture, we can see that the rogue avoid the warrior's AA and lands him 
                                       a critic
https://ibb.co/6rx8gL6  On this one we can se the warrior's AA animation and how the rogue avoid it.

https://ibb.co/dBG9tqz  Same case but we both parry.

**Comment by chajn** [comment]
Hey I have som footage of this I guess, I think it's both the issue you're explaining and also that the hit box in pvp seems too big.

https://www.twitch.tv/videos/341423987## 

Wasn't sure if I should post it here or make a seperate report.

**Comment by Bugadin** [comment]
> Hey I have som footage of this I guess, I think it's both the issue you're explaining and also that the hit box in pvp seems too big.
> 
> https://www.twitch.tv/videos/341423987##
> 
> Wasn't sure if I should post it here or make a seperate report.

It's not only about hit box because when I'm running (with sprint) behind a druid and I'm literally inside of him I can't hit him at all sometimes.

Maybe is just the hit box, maybe not but I'm pretty sure that hit box isn't working properly.
