### ISSUE TITLE
[Stress-Test-Server] Strange xp Rates

### ISSUE THREAD

**Issue by Zerroc1** [SunwellWoW/Sunwell-TBC-Bugtracker#1911]
Decription: 
Dont know if the xp rate was x1 or x2 on the stresstest server. was a way faster level 5 on the open world server (with less quests).

How it works: 
On Open world server i finished first quest  (talk to marshall mcbride, round about 300xp) and killed a lvl2 wolf(round about 100xp) and reached level2. on the stresstest server i had to kill 4 or 5 mobs to get level 2 (with the quest)

How it should work: 
idk how it should work properly :D maybe im dumb :O

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
We increased exp rates for killing creatures and implemented DynamicRespawn for them so people could exp quite faster ;) That was in purpose.

See you around.
