### ISSUE TITLE
Duels on stress test realm

### ISSUE THREAD

**Issue by Azathothh** [SunwellWoW/Sunwell-TBC-Bugtracker#1912]
How it works:  Currently on "stress test" realm players can kill each other in duels.

How it should work: Well...players shouldn't die after duel :P

**Comment by Wojtyas** [comment]
- [ ] Dots are still ticking on players after duel (they don't fade).
- [ ] Sometimes direct damaging spells casts can be finished after duel ends.
http://priv.wherego.pl/files/umkkfg3o97gauys3ipw7jtsttw/public?h=04S63jfYCoXLB0IX49IlfG9CTgi3DhTbbaxg2-GLePA

**Comment by Wojtyas** [comment]
It's still possible to kill player after duel by casting direct spell (used Smite rank1).
