### ISSUE TITLE
[Item] [Aura] Scroll of Protection interferes with Devotion Aura.

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#1913]
Description: If you have Devotion Aura on and use a Scroll of Protection the Scroll will remove Devo Aura even though the scroll has a lower armor buff, if you use Devo aura with a scroll of protection on, it removes the scroll buff. 123

How it works: ^

How it should work: Lower buff should not cancel out stronger buff, if scroll cannot be used in addition with aura buff, scroll should not be usable and give error "There is already a stronger buff active"

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Bug still present.

![image](https://user-images.githubusercontent.com/22802214/49149986-db0c3400-f30b-11e8-82de-d6a15aa8145c.png)
