### ISSUE TITLE
Stress test Mob respawn rate (Dynamic issue?)

### ISSUE THREAD

**Issue by dedalo91** [SunwellWoW/Sunwell-TBC-Bugtracker#1914]
Decription: Probably I'm wrong, but I'm seeing a few problems with respawn (don't know if it's already dynamic, and I don't really know how it works to be honest) In undead starting zone there are just a few hostile mobs, specifically spiders in a cave: what happens is that, when you kill a few, they respawn all at the same time, same place and in a pack of 4-5 Don't know if it's intended, but it can be a problem during leveling

How it works: don't know, need confirm from a dev

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
We did in purpose ;) DynamicRespawn will be described soon in post before main realm release.
