### ISSUE TITLE
Stress test Mob sound bug

### ISSUE THREAD

**Issue by dedalo91** [SunwellWoW/Sunwell-TBC-Bugtracker#1915]
Decription: just a minor issue: when you attack with a pet any mob, they will play the sound of being attacked before the attack of the pet lands (only tried with warlock's Imp)

How it works: when the imp start the firebolt cast, the mob play the sound

How it should work: the mob should play the sound when the attack lands

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
I believe that works good - should play these sounds on attack and cast spell - not hit.
