### ISSUE TITLE
[NPC] Lizzarik and Jorb

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#1916]
**Decription:** 
The Goblin NPC Lizzarik <Arms Dealer> patrols along the path from Ratchet to Crossroads. He's meant to have his bodyguard Jorb patrolling with him but currently Lizzarik is walking the patrol route alone. Jorb should always be alongside him.

**How it works:** 
The Goblin NPC Lizzarik <Arms Dealer> patrols along the path from Ratchet to Crossroads. He's meant to have his bodyguard Jorb patrolling with him but currently Lizzarik is walking the patrol route alone. Jorb should always be alongside him.

Video: https://streamable.com/hdu31

**How it should work:** 
 He's meant to have his bodyguard Jorb patrolling with him but currently Lizzarik is walking the patrol route alone. Jorb should always be alongside him.

Source (you should point out proofs of your report, please give us some source): 

Proof: https://www.wowhead.com/npc=3658/lizzarik#comments
Proof 2: https://www.wowhead.com/npc=3659/jorb#comments

**Comment by Wojtyas** [comment]
yee I reported it somewhere here :P probably in my massive open world topic, his ogre bodyguards stays in Ratchet w/o patrol as formation with his boss

**Comment by peanutcheese** [comment]
He's meant to have his bodyguard Jorb patrolling with him but currently Lizzarik is walking the patrol route alone. Jorb should always be alongside him.
^this has been fixed
