### ISSUE TITLE
Respawn time of mobs (ruins of karabor)

### ISSUE THREAD

**Issue by BIGCHESTDAY** [SunwellWoW/Sunwell-TBC-Bugtracker#1923]
Decription:  Demon hunter supplicants.

How it works: Demon hunter supplicants Very long respawn rate about 5+ min

How it should work: fairly quick respawn rate 2-3min max also the elite that patrols here is suppose to have a mana burn mechanic that i dont believe works

Source (you should point out proofs of your report, please give us some source):

**Comment by ZaoQ** [comment]
making research for your tomes farm? :D

**Comment by Wojtyas** [comment]
Which elite cuz there are at least 4-5 of them around :P and source for this respawn timer?

**Comment by ZaoQ** [comment]
i believe he thinks Netharel

**Comment by Wojtyas** [comment]
**-[ ] Graal: Netharel (21164) misses his AI. He doesn't use Mana Burn (39262), Metamorphosis (36298) and Debilitating Strike (39135).**

Literally no info about decreased respawn timer of Supplicants so I would leave it.
