### ISSUE TITLE
[Arena] does not end

### ISSUE THREAD

**Issue by feelmy1taps** [SunwellWoW/Sunwell-TBC-Bugtracker#1925]
Decription: 
When one player will be dead in arena and another player from same team will leave before he die the arena does not end.

How it works: 
In this situation, the winning team must leave the arena and it is considered a loss

How it should work: 
The arena should end automatically after the exit or death of the players of the team

**Comment by Wojtyas** [comment]
Already reported - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/i
