### ISSUE TITLE
[Suggestion]Any chance to increase nameplate visibility range

### ISSUE THREAD

**Issue by ymli1989** [SunwellWoW/Sunwell-TBC-Bugtracker#1926]
Decription: 
This is a suggestion/discussion about increasing enemy nameplate visibility range. It seems there is no addon or command like '/SetCVar("xxxxxx")' can change it now.

How it works: 
Nameplate become visible when mobs/enemies is near enough (10~15yds) to player, and invisible when 
 mobs/enemies are out of that range.

How it should work: 
It is working well as it was in TBC-2007. 
It is NOT a bug, just hope that it can be increased to 30yds or can be set with console command. It is a great benefit to the game experience of ranged class players. Thank you in advance. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
I've spoken with devs cuz already one player asked me about it but we probably can't do anything here :(

**Comment by ymli1989** [comment]
> I've spoken with devs cuz already one player asked me about it but we probably can't do anything here :(

OK then...Ty anyway. 
And...is there any opportunity to change it, I mean...in the future, still under 2.4.3 framework. Or this can ONLY be changed in some later WOW version like 6.x or 7.x because of some unsupported lower level API?

**Comment by Wojtyas** [comment]
Well, we have to ask chiefs.
@akrom23 @Riztazz @lukaasm HELP PLOX

**Comment by Wojtyas** [comment]
Unfortunately there is no such a way to do it on TBC :(
