### ISSUE TITLE
Key required locations

### ISSUE THREAD

**Issue by MrTide** [SunwellWoW/Sunwell-TBC-Bugtracker#1927]
issue seems like when open closed doors that require keys .. they don't require key anymore and anyone can open them for example shattered halls door or SL door
checked with multiple characters once it opened everyone else can open it
![wowscrnshot_112618_071651](https://user-images.githubusercontent.com/36106057/48992169-b4070400-f14b-11e8-9970-dfe745a19793.jpg)
![wowscrnshot_112618_071302](https://user-images.githubusercontent.com/36106057/48992172-b6695e00-f14b-11e8-9d0e-8ba44d9129bc.jpg)
sadly seems like it applies to every door
![wowscrnshot_112618_072340](https://user-images.githubusercontent.com/36106057/48992234-fdefea00-f14b-11e8-9769-b2a37c729dfe.jpg)

**Comment by Wojtyas** [comment]
Thrall is probably from outro event from 10170 quest.

Key thing is interesting, did you check u can open the gate from other character afterwards?

**Comment by MrTide** [comment]
Yes i did on both realms
you can open them with everyone else

**Comment by notsofamous** [comment]
Thrall reported here: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/300

**Comment by Wojtyas** [comment]
Fixed & implemented.
