### ISSUE TITLE
Mana Tombs Heroic Ethereal Sorcerer 

### ISSUE THREAD

**Issue by jaydee96brebre** [SunwellWoW/Sunwell-TBC-Bugtracker#1929]
Decription: Ethereal Sorcerer Casts Arcane missiles on HIMSELF.

How it works: Ethereal Sorcerer casts Arcane missiles on HIMSELF.

How it should work: Ethereal Sorcerer should cast arcane missiles on his TARGET.

Source (you should point out proofs of your report, please give us some source): I think this is pretty logical.

**Comment by jaydee96brebre** [comment]
Aswell the mobs in the pack im not entirely sure which, are Counterspelling people for 15seconds, pretty sure thats not how it should work

**Comment by Wojtyas** [comment]
Still present.

![image](https://user-images.githubusercontent.com/22802214/49150074-160e6780-f30c-11e8-8648-599ebbffdd28.png)
