### ISSUE TITLE
[NPC]Defias Looter

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1934]
Decription: 
Has mana bar(open world/ssc realm)

How it works: 
![image](https://user-images.githubusercontent.com/43579401/49002445-e9b5e800-f15f-11e8-8fee-159f045c5b64.png)

How it should work: 
Its a normal meele NPC, he shouldnt have a mana bar

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
UPDATE creature_template SET `unit_class` = 4 WHERE `entry` IN (590);
UPDATE creature_template SET `unit_class` = 8 WHERE `entry` IN (1536);
