### ISSUE TITLE
Vanilla mobs move too slow

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#1936]
Decription: Vanilla mobs are currently moving way too slow, somewhat trivializing the initial leveling experience.

How it works: https://www.youtube.com/watch?v=qfWlBqB0juY&feature=youtu.be Currently Vanilla npcs are moving way too slow, this video was taken with no form of run speed enchants. Also tested Brack (rare level 18 westfall), young stranglethorn tigers, and elite demons in blasted lands. Vanilla mobs just move too slow.

How it should work: Mobs should be more difficult to outrun or kite, the base movement speeds for mobs on Vanilla should be speedwalk = 1.0, speedrun = 1.14286

Source (you should point out proofs of your report, please give us some source): speedwalk = 1.0, speedrun = 1.14286 is the stock mangos Vanilla speeds, 
https://youtu.be/FaV6oAteJGI?t=4124 here is a time specific clip from Joanas unedited speed run, you can see that despite running away and having a substantial lead the troll is atleast able to still hit him twice before he escapes. By viewing my original clip it should be pretty obvious that they are way too slow.

Tested the mobs in Outlands and they move at appropriate speeds, difficult to leash and kite without taking damage.

**Comment by Mikov1605** [comment]
I can confirm it, ALL classic mobs do it, back on apocalypse wow or even any servers, i remember that mobs could always reach me. Now i can just freely run away from them. Back there, it was annoying to be dazed from running away, but it was a part of the game, which made it more harder.

**Comment by Jseay1313** [comment]
Just wanted to reiterate I tested this on multiple level tiers, 5-10, 15-20, 30-35, and 60-63 (blasted lands elites) and the problem persisted in every Vanilla zone/test I did. 

Proceeded to test mob speeds in Hellfire, Zangarmarsh, and Terrokar and all mobs tested moved at appropriate speeds, seems to be limited to Vanilla.

**Comment by Dootz** [comment]
speed of 3 000 different creatures that were moving too slow was updated. Should be live on ptr tomorrow.
