### ISSUE TITLE
pre-Maraudon

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#194]
### **TO DO:**

- [ ] 1. The Nameless Prophets (13718) are elite creature in pre-instance part. They should spawn in 4 locations but for now I can find him only one of them. Description in this comment:
![image](https://user-images.githubusercontent.com/22802214/44524744-fea55a00-a6de-11e8-8759-699a35c0e188.png)
- [ ] 2. Cursed Centaur (11688) is rare boss in pre-instance part. For now he's no present in game at all. Need to be added. He should patrol (walk) entire cave before dung portal entrance.
- [ ] 3. Rock Worm (11788) doesn't use Acid Spit spell (44477).
**EDIT: It still doesn't use it, through it has SmartAI.**
- [ ] 4. Cursed Centaur should has around 10h respawn time. For now he has 5 min.
**EDIT: After change he has 8 min respawn time.**
- [ ] 5. The Nameless Prophet (13718) shouldn't cast Curse of Blood (16098) on target who already has this debuff.

### **DONE:**

- [x] 1. Ghostly Rider (11686) doesn't use any of his spells: Concussive Shot (17174), Shoot (6660), Net (6533).
- [x] 2. The Nameless Prophet (13718) doesn't use any of his spells: Curse of Blood (16098), Earth Shock (15501), Festering Rash (15848).
- [x] 3. Looks like Ghostly Marauder (11687) doesn't use Strike spell (11976).
- [x] 4. Maraudine Priest (11685) doesn't use any of his spells: Mind Flay (16568), Shadow Word: Pain (11639).
- [x] 5. Cursed Centaur moves extremely fast.
- [x] 6. Cursed Centaur doesn't use his Curse of the Tribes spell (21048).
- [x] 7. Rock Borer (11787) doesn't use Tunneler Acid spell (14120).
- [x] 8. Shadowshard Smasher (11778) should use both of his spells more often: Knock Away (10101), Knockdown (11428).

**Comment by Kokaina** [comment]
List updated.
