### ISSUE TITLE
[Spell][Item] Recently Bandaged vs Bandages

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1943]
Using a bandage will put Recently Bandaged (11196) debuff correctly and when player will try to use next bandage while on this debuff it will pop "Immune" text and it won't heal which is quite ok. Nevertheless, even that it won't heal you target with debuff, you are losing bandage from your bagpack.

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/867

**Comment by babno** [comment]
Adding to this, you can bandage someone recently bandages by someone else. So multiple people can bandage one person within a minute. The immune happens when you try to bandage the same person twice.
