### ISSUE TITLE
[Quest]The End of the Deserters

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1946]
Decription: 
Quest is working, just a minor bug. Gavis Greyshield should not be killable, he should turn friendly at 10% hp and say a quote. He also should give credit then.

How it works: 
He is killable, doesnt say a word but gives credit.
![wowscrnshot_112618_151902](https://user-images.githubusercontent.com/43579401/49019770-01f12b80-f18f-11e8-966b-433bee858933.jpg)

How it should work: 
https://www.youtube.com/watch?v=7USO7ySdSOg

Source (you should point out proofs of your report, please give us some source):

**Comment by ghost** [comment]
NPC Gavis Greyshield is not attackable by players. He should be according to https://www.youtube.com/watch?v=7USO7ySdSOg

Respawning the NPC does not solve it. Players attempting the quest are Alliance.
