### ISSUE TITLE
Maraudon

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#195]
### **TO DO:**

- [ ] 1. Celebrian Dryad (11793) doesn't use two spells: Throw (16000) - when in distance, and Dispel Magic (17201) from ally npc.
**EDIT#4: Still no dispels :(**
- [ ] 2. Constrictor Vines and Barbed Lashers stay in place. They should patrol corridors as formation.
- [ ] 3. Cavern Lurkers (12223) should patrol corridors.
- [ ] 4. Corruptors (12217), Poison Sprites (12216) should patrol as formation.
- [ ] 5. Packs of Deep Borers (11789) should walk as a formations and patrol halls.
- [ ] 6. There is huge lack of Theradrim Guardian creatures.

### **DONE:** 

- [x] 1. Looks like Barbed Lasher (12219) doesn't use Thrash spell (3391).
- [x] 2. Constrictor Vine (12220) doesn't use Thrash spell (3391).
- [x] 3. Those four Creeping Sludges should been linked with threat.
![image](https://user-images.githubusercontent.com/22802214/44526807-6494e000-a6e5-11e8-9aad-0928f05f9cdf.png)
- [x] 4. Spewed Larva (13533) moves to fast.
- [x] 5. Vile Larvas (12218) should have random movements.
- [x] 6. Noxxion's (13282) melee hits should count as nature damage instead of physical.
- [x] 7. Razorlash (12258) doesn't use two of his spells: Puncture (15976) and Thrash (3391).
- [x] 8. Putridus Tricksters (11791), Deeproot Tanglers (13142) should have random movements.
- [x] 9. Deeproot Tangler should cast Thorns spell (21337) on other Maraudon creatures as well. For now he only buffs himself.
- [x] 10. Lord Vyletounge should focus on keepin distance from players and shot them with his ranged spells. For now he tries to melee attack everyone.
- [x] 11. Trinkerer Gizlock interrupts his own channeling spell Goblin Dragon Gun (21833).
- [x] 12. Stolid Snapjaws (13599), Subterranean Diemetradons (13323), Thessala Hydras (12207) should have random movements.
- [x] 13. There shouldn't be permanent packs of Theradrim Shardlings (11783).
- [x] 14. Theradrim Guardian (11784) doesn't use Summon Theradrim Shardling spell (21057). He should spawn 3x Shardlings to aid him when pulled.
- [x] 15. Deep Borers (11789) should use Thrash spell (3391).
- [x] 16. When Landslide (12203) starts to cast Landslide spell (21808) he interrupts it.
- [x] 17. Spawned Theradrim Shardlings from Landslide spell should start to attack players once spawned.
- [x] 18. Rotgrip doesn't use Fatal Bite spell (20539). 
- [x] 19. I started to fly when I was under Repulsive Gaze effect (21869).
- [x] 20. Princess Theradras (12201) shouldn't cast Dust Field spell (21909) if there are no players in spell radius.
- [x] 21. Tinkerer Gizlock (13601) shouldn't cast Goblin Dragon Gun (21833) if there is noone in spell range.
- [x] 22. Tinkerer Gizlock (13601) stays in wrong location. On screen are proper coords+orientation by gps.
**EDIT: Dunno what happened but there are now two Tinkerers Gizlocks spawns in correct location. Guids: 56538 and 16898348.**
![image](https://user-images.githubusercontent.com/22802214/44529757-24d1f680-a6ed-11e8-98e4-2ffc054feba4.png)
- [x] 17. Theradrim Shardlings (11783) should use Strike spell (13584).
**EDIT: Looks like they still miss that spell.**
- [x] 18. Rotgrip's (13596) swim movement requires little corrections.
- [x] 19. On corridor between The Wicked Grotto and Poison Falls there should be rare boss Meshlok the Harvester (12237). For now he's not present in game.
**EDIT: We still miss him ;o**
![image](https://user-images.githubusercontent.com/22802214/45161296-d001a600-b1eb-11e8-8f86-5670fdb6c1b2.png)
- [x] 20. Meshlok the Harvester should have app. 20% chance to appear in dungeon.
**EDIT: We still miss him ;o**
![image](https://user-images.githubusercontent.com/22802214/45161296-d001a600-b1eb-11e8-8f86-5670fdb6c1b2.png)
- [x] 21. Noxxion (13282) shouldn't be immune to frost school damage.
**EDIT: Noxxion's Spawns are immune to frost but not Noxxion itself**
- [x] 22. Lord Vyletounge's (12236) Blink spell (21655) work in strange way. It does not teleport boss in 20y forward but I don't know its spell bug or movement (cuz boss likes to fly when in melee range).
- [x] 23. Once clicked on gob Larva Spewer (32892) it activates and disappears. It shouldn't disappear.
**EDIT: When clicked it deactivates properly but doesn't have broken animation**
- [x] 24. Larva Spewer gob doesn't work at all. It should spawn Spewed Larva npcs continuosly time to time (info about time needed). When spawned they should start to chase players immediately. Gob should spawn those npcs when players are 70y range.
**EDIT: Looks fine, please change only trigger that spawn creatures to 300y range**
![image](https://user-images.githubusercontent.com/22802214/44527492-3ca67c00-a6e7-11e8-9497-c826a1b11bb0.png)
- [x] 25. After Noxxion uses Summon Noxxion's Spawns (21707) he shouldn't appear till all of 5x Noxxion's Spawns (13456) are killed. For now he appears after 20s (i guess) no matter what.
**EDIT#2: He still appears back even when spawns are not dead.**
- [x] 26. Lord Vyletongue should have Dual Wield spell (674).

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
Updated.

**Comment by Kokaina** [comment]
Updated.

**Comment by Kokaina** [comment]
Updated.
