### ISSUE TITLE
Rogue pickpocket

### ISSUE THREAD

**Issue by xrewz** [SunwellWoW/Sunwell-TBC-Bugtracker#1954]
Decription: pickpocket is not working correct . It seems like it has to do with what kind of stealth rank you have.

How it works:  Rank 1 and 2  Stealth makes you unable to pickpocket mobs over level 15

How it should work: 
pickpocket should not be affected by the rank of stealth but rather  by the level difference of the player and the mob.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
#1841.
