### ISSUE TITLE
Flying Mount on Ground too fast

### ISSUE THREAD

**Issue by RalukWoW** [SunwellWoW/Sunwell-TBC-Bugtracker#1955]
Decription: The fast Flying Mount is too fast while on the ground.

How it works: 
The mount is moving with the 280% speed while running on the ground.

How it should work: 
The mount should move with +100% speed while running.

Source (you should point out proofs of your report, please give us some source): 
Tested in shadowmoon valley with swift green and swift red windrider.

**Comment by Wojtyas** [comment]
We changed values of mounting speed in order to make more comfortable tests. It's in purpose and will be reverted soon.
