### ISSUE TITLE
[Quest] Cleansing Witch Hill

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1956]
Decription: 
During the quest Cleansing Witch Hill (11183) we summon a Zelfrax npc (23864). There should rp event when he's appearing, saying something, and then be attackable.

How it works: 
He just spawns and is attackable

How it should work: 
Like in description

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=uQENN-834fg 

its cata video but the quote he should say is the same

**Comment by neheri** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1151
