### ISSUE TITLE
[Zone] [Arathi Highlands]

### ISSUE THREAD

**Issue by Piootrek** [SunwellWoW/Sunwell-TBC-Bugtracker#196]
- [x] NPC 2574 - Drywhisker Digger doesn't use spell Suder Armor (8380) (http://db.hellfire-tbc.com/?npc=2574#abilities)
- [x] NPC 2609 - Geomancer Flintdagger uses spell Fire Shield III (2601) only on himself (http://db.hellfire-tbc.com/?npc=2609#abilities)
- [x] NPC 2761 - Cresting Exile doesn't use spell Frost Armor (12544) (http://db.hellfire-tbc.com/?npc=2761#abilities) 
- [x] NPC 2564 - Boulderfist Enforcer doesn't use spell Demoralizing Shout (13730) (http://db.hellfire-tbc.com/?npc=2564#abilities)

Creatures listed below used to be elites. Blizzard changed them to normal mobs witch patch 2.3. On our server they are normal mobs, but have hp and melee dmg like elites. 
- [x] NPC 2588 - Syndicate Prowler doesn't use spell Sinister Strike (14873) (http://db.hellfire-tbc.com/?npc=2588#abilities)
- [x] NPC 2590 - Syndicate Conjuror doesn't use spell Sleep (15970) (http://db.hellfire-tbc.com/?npc=2590#abilities)
- [x] NPC 2783 - Marez Cowl has wrong animation of Shadow Channeling spell. Screenshot from Wowhead (2008/01/08) https://wow.zamimg.com/uploads/screenshots/small/68540.jpg. Probably she uses wrong spell, 43897 looks correctly.
- [x] NPC 2571 - Boulderfist Lord (http://db.hellfire-tbc.com/?npc=2571#abilities)
- [x] NPC 2570 - Boulderfist Shaman (http://db.hellfire-tbc.com/?npc=2570#abilities)
- [x] NPC 2773 - Or'Kalar (http://db.hellfire-tbc.com/?npc=2773#abilities)
- [x] NPC 2569 - Boulderfist Mauler (http://db.hellfire-tbc.com/?npc=2569#abilities)
- [x] NPC 2558 - Witherbark Berserker (http://db.hellfire-tbc.com/?npc=2558#abilities)

**Comment by Dootz** [comment]
thanks for report, will be fixed with next ptr update.
