### ISSUE TITLE
[Warlock][Spell] Enslave Demon - pet bar interactions

### ISSUE THREAD

**Issue by peanutcheese** [SunwellWoW/Sunwell-TBC-Bugtracker#1960]
Description: 
-When enslaving a demon, the pet bar doesn't always show their abilities. Eventhough they will still autocast them.

-When a demon is freshly enslaved, the pet bar shows it's on follow but you have to make it go to stay and then back to follow to unlock its movement. Even if you press petattack, you have to undertake these steps first.

How it works: 
""

How it should work: 
-All castable abilities on an enslaved demon should be shown on the ability bar.

-A freshly enslaved demon should automatically be on follow - AND FOLLOW YOU - not be stuck in place until you perform the sequence.

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/353b550fe910fcefa8f807e65e33c15f (demon auto-casting rain of fire without it being on bar)

**Comment by Wojtyas** [comment]
Fixed & implemented. Checked by Peanut.
