### ISSUE TITLE
[Warlock][Spell] Enslave Demon - threat interactions

### ISSUE THREAD

**Issue by peanutcheese** [SunwellWoW/Sunwell-TBC-Bugtracker#1961]
Decription: 
Some enslaved demon spells cause threat to the player instead of to the demon.

How it works: 
Felguard Destroyer level 60 elite demon in Hellfire Peninsula uses Mortal Strike on a mob -> player gains aggro. The Mortal Strike gets counted as if it is cast by the player (combat log).

How it should work: 
The threat for an ability used by a pet should be added to the pet's threat table.

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/cef2dca29a3caf7f65c130b17823255c

**Comment by neheri** [comment]
All these enslave reports should be checked with Priest mind control, high probability it will work the same way.

**Comment by peanutcheese** [comment]
-Some enslaved demon spells cause threat to the player instead of to the demon.
^this has been fixed
>report closed

**Comment by Wojtyas** [comment]
Fixed & implemented. Checked by Peanut.
