### ISSUE TITLE
[Warlock][Spell] Enslave Demon - broken pet spells

### ISSUE THREAD

**Issue by peanutcheese** [SunwellWoW/Sunwell-TBC-Bugtracker#1963]
Decription: 
One of the mobs that has it as an example is the level 71 Wrath Master elites at the Dark Portal in Hellfire Peninsula.
This spell does not do anything when the player commands his/her pet to use it.
This spell is on multiple enslaveable mobs in Outland.

How it works: 
""

How it should work: 
This spell should not be on the cast bar when a player enslaves these demons.
This spell should not be castable by the pet whilst enslaved.

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/021e23087097e429fd3622cf8ed2bc06 (fullscreen view)
https://gyazo.com/c25754f5946bf2da572ff2c61777d23a (pet bar showing samwise spell icon)
https://gyazo.com/9d686170d395ce201488f1d532e8cfe3 (spell tooltip, presumably what they use to call for help to their allied mobs when they get pulled by a player)

**Comment by peanutcheese** [comment]
-One of the mobs that has it as an example is the level 71 Wrath Master elites at the Dark Portal in Hellfire Peninsula.
^this has been fixed

**Comment by Wojtyas** [comment]
Fixed & implemented. Checked by Peanut.
