### ISSUE TITLE
Dragonstrikes Haste Proc stacking

### ISSUE THREAD

**Issue by alexnxs** [SunwellWoW/Sunwell-TBC-Bugtracker#1965]
Decription: 

The haste buff from Dragonstrike is stacking, when it should only refresh the buff.

How it works: 

Hit target with while dual wielding Dragonstrikes, observe your haste value during a double proc.

How it should work: 

When dual wielding Dragonstrikes, if you receive another proc while you already have the Haste buff it should refresh the buff instead of applying a second one.

Source (you should point out proofs of your report, please give us some source): 

https://www.wowhead.com/item=28439/dragonstrike#comments:id=287394

**Comment by Wojtyas** [comment]
Already reported: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1932
