### ISSUE TITLE
Scrolls and Buffs

### ISSUE THREAD

**Issue by alexnxs** [SunwellWoW/Sunwell-TBC-Bugtracker#1967]
Decription: 

Using any scroll of intellect will overwrite any rank of Arcane Intellect. Also any rank of arcane intellect will overwrite any scroll. I would wager this also happens with other buff & scroll interactions.

How it works: 

Cast any rank Arcane Intellect, then use a Scroll of Intellect V on the same target. The weaker Intellect buff will overwrite AI. 

How it should work: 

The scroll should only overwrite Arcane Intellect if the scroll buff is more powerful and vise versa.

Source (you should point out proofs of your report, please give us some source): 

https://www.wowhead.com/forums&topic=111568
https://www.mmo-champion.com/threads/630938-So-will-scrolls-be-useful-now
http://maintankadin.failsafedesign.com/forum/viewtopic.php?t=17543

**Comment by akrom23** [comment]
#385.
