### ISSUE TITLE
Kara 11-27

### ISSUE THREAD

**Issue by Xploitz10** [SunwellWoW/Sunwell-TBC-Bugtracker#1970]
Decription:

- [x] ~~attunemen fine~~
- [x] ~~moroes, standing on table still bugs encounter~~
- [x] ~~maiden is fine~~
- [x] romulon and juliet - bugged, got both down to below 5% and finished romulon, juliet immediately went to 100% health, not even 1 second after rumulon kill
- [x] ~~curator was fine, sparks and hateful bolt worked
(all the above bosses were bugged at end of encounter when execute was used ... execute user received 3million heal and bosses immediately died and kept attacking after boss was dead)~~
- [x] ~~illhoof was fine~~
- [x] ~~shade of aran was bugged, execute was used and boss was bugged, adds remained alive after boss died, boss didnt pull in raid when arcane explosion happened~~
**GRAAL: Fixed, not implemented**
- [x] chess was bugged, couldnt move any of the pieces, couldnt use any abilities, could only turn the pieces
- [x] ~~prince visual bug ... was dw in ph1, infernals hellfire had larger radius than it should i believe~~
**GRAAL: Cannot reproduce, he had no visual bugs on my all 15 attempts :( Hellfire range is 20y which is correct.**
![image](https://user-images.githubusercontent.com/22802214/49105491-f3833c80-f280-11e8-91e1-68b8ca37b37b.png)
- [x] ~~netherspite , targeted random ppl  in melee range coming out of 2nd phase, breath wasnt doing damage, and knockback wasnt happening~~
**GRAAL: And again for me it worked on every attempt I checked (breath+kb). About meele and threat:**
- It also aggroes Netherspite as soon as the banish phase ends, providing time for the tank to pick him up. **Means no melee should be near him right after p2 cuz he has no threat**
- Netherspite is still able to deal melee damage to you during the Banish phase if you get too close to him. He will not pursue players and has no aggro table. **Means he will hit melee players cuz he has no threat table**
![image](https://user-images.githubusercontent.com/22802214/49106693-224ee200-f284-11e8-8a3b-30f200ac3c61.png)
- [x] ~~nightbane, first attempt no adds during air phase, 2nd attempt there was no air phase, boss was disarmable, fear was kickable, charred earth was kickable, charred earth seemed to have larger radius tham visual, pathing coming in and out of air phase was off~~
**GRAAL: Fixed**

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by sicknot1** [comment]
can confirm

**Comment by Wojtyas** [comment]
@Xploitz10 can u tell me which table bugged Moroes? Just jump on/off every table and he always follows me.
