### ISSUE TITLE
[Spell]Combustion

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#1972]
Decription: 
Spell should give 10% crit, and add 10% aditional crit with each spell cast, until 3 non periodic crits hit the target.

How it works: 
Altough it gives the crit, it is not shown in stats.

![wowscrnshot_112718_130242](https://user-images.githubusercontent.com/43579401/49081413-1264dd00-f247-11e8-9ebf-0f45932cecc1.jpg)
![wowscrnshot_112718_131701](https://user-images.githubusercontent.com/43579401/49081412-109b1980-f247-11e8-8e3e-ff69e4076419.jpg)

How it should work: 
It should be visible in stats ;) 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Nope - it is not visible in stats.

**Comment by Mikov1605** [comment]
I Just Remember it from other servers, got no proof from net, because it is a cosmetic feature and noone cares xd
