### ISSUE TITLE
Druid Aquatic Form cancelling when jumping in water

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#1973]
Decription: Druid aquatic form is cancelling when player jumps above water, common bug on most private servers but working properly on a few

How it works: Currently jumping above the water in aquatic form is instantly cancelling your water form.

How it should work: The game should compensate for barely jumping out of the water and not cancel aquatic form

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented.
