### ISSUE TITLE
Druid Talent: Natures Grace still not functioning properly

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#1974]
Decription: Natures Grace is still being consumed without applying to the next spell. This is only happening in regards to the projectile time of wrath and casting starfire after.

How it works: https://www.youtube.com/watch?v=OlduAVgIeAs&feature=youtu.be Nature's grace is obtained after critting Wrath, but the speed is not applied to the next cast, and the buff is consumed on the spell landing.

How it should work: Natures Grace should apply to the next spell regardless of when its cast before the previous spell hits, usually added at the end of the spell. If anything it should atleast still apply to the next spell cast and not consume at the end of the previous cast.

Source (you should point out proofs of your report, please give us some source): My video and the numerous other natures grace bug reports.

**Comment by Wojtyas** [comment]
Still doesn't work ;O
Its not consuming Wrath casts, buff should disappear upon spell cast not when spell reach target.

**Comment by Jseay1313** [comment]
save natures grace make moonkin great again
