### ISSUE TITLE
Stoneform not granting immunity to effects

### ISSUE THREAD

**Issue by Sabre142** [SunwellWoW/Sunwell-TBC-Bugtracker#1975]
Description: 
Stoneform should grant immunity to bleeds, diseases and poisons when activated as well as for the full duration

How it works: 
![unknown](https://user-images.githubusercontent.com/26516348/49083460-c5adf000-f2a0-11e8-95b1-01ed9c66492a.png)

How it should work: 
![unknown 1](https://user-images.githubusercontent.com/26516348/49083482-d3fc0c00-f2a0-11e8-8137-d1d51bb4e201.png)

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/spell=20594/stoneform#comments wowhead comments

**Comment by Exeasd** [comment]
Example of proper working here [https://youtu.be/u43fdVsxop4?t=729](url)

**Comment by Wojtyas** [comment]
Fixed & implemented.
