### ISSUE TITLE
Abilities not present in pet bars

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#1976]
Decription: 
https://i.imgur.com/8sR8dGu.jpg I got the same result when I summoned the imp, voidwalker, succubus, and felhunter

How it works: 
https://i.imgur.com/8sR8dGu.jpg

How it should work: 
Should have abilities

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@babno Try it on newly created character.

**Comment by babno** [comment]
New character worked normally.

**Comment by Wojtyas** [comment]
Fixed & implemented.
