### ISSUE TITLE
Steady Shot NOT RESPONSIVE?! - Advanced Hunter Gameplay BROKEN

### ISSUE THREAD

**Issue by meditationasami** [SunwellWoW/Sunwell-TBC-Bugtracker#1978]
**Summary:** 
After some personal research, I've come to the conclusion that the nature of the Hunter class feels VERY different here in comparison to other servers. It's kind of hard to narrow down what the precise issues are, but from my experience for a Hunter coming from Warmane to be precise I had a much easier time squeezing through a 3:2 rotation there, while on this server minor haste buffs would break the rotation (as they wouldn't on Warmane). But why? Could be something with GCD.... or something else, as I said it's kind of hard to narrow down but I did want to say how I'm overall feeling about the class here so far. It feels like a NEW class honestly.

**Aimed Shot into Steady Shot (How it works):** 
One issue I did really narrow down when it comes to Hunters is that, often when I cast my Aimed Shot into a Steady Shot it leads to the Steady Shot having some sort of cooldown. which makes the ability unable for me to press at that point, ofcourse that leads to awkwardness in rotation.

**Aimed Shot into Steady Shot (How it should work):** 
There shouldn't be a cooldown of any sort, an Aimed Shot should count as an Auto Shot in rotation, so when I finish my Aimed Shot I SHOULD be able to cast Steady Shot RIGHT AWAY! 

**Source (you should point out proofs of your report, please give us some source):** 
https://www.youtube.com/watch?v=QPMVlNUfwKw. [VIDEO MATERIAL OF ME PERFORMING AIMED SHOT INTO STEADY SHOT]

_//With everything above stated I personally feel this class is rather broken (negatively ofcourse) ATM. Hope Aimed into Steady gets fixed ASAP, if applicable I'll submit more issues, good day._

**Comment by akrom23** [comment]
Other private server is not the best source of info.
I will look into it.

**Comment by meditationasami** [comment]
Well, the video 

> Other private server is not the best source of info.
> Needs more info and proofs how it is supposed to work.

Well, the video shows that after an Aimed Shot cast completes Steady Shot becomes unable for action and displays as a CD, if you check what happens to the ability as I spam it you'll notice something is wrong anyway, it seems pretty logical to me and others no matter how things go on Warmane. This is not something that occurs 100% of the time aswell, it happens on- and off which should also indicate a problem. Not sure where to pull proof from but the way the ability is working ATM is for sure not intended, I hope that comes to your realization sooner or later then.
