### ISSUE TITLE
[Quest] Archmage Alturus

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1980]
Archamge Alturus quest (11216) **should be** prequest for quests  Arcane Disturbances (9824) and Restless Activity (9825). For now we can pick up 9824 and 9825 w/o prequest completed.

**Comment by peanutcheese** [comment]
For now we can pick up 9824 and 9825 w/o prequest completed.
^this has been fixed, as a fresh 70 with 0 quests completed I could not pick up any quests off the guy
https://gyazo.com/f4558a5c45e01c19cf4ff89635ef8f95

**Comment by Wojtyas** [comment]
Fixed & implemented.

**Comment by babno** [comment]
This is WRONG. You should be able to get both without a pre-requisite. It was working correctly and is now broken. As you can tell from the ID even that quest was added much later as a breadcrumb to get people to go to deadwind pass for kara attunement, much like the other various "go to new zone" quests that are present in tbc.
https://tbc-twinhead.twinstar.cz/?quest=9824
https://tbc-twinhead.twinstar.cz/?quest=9825
