### ISSUE TITLE
[Mount] Full Mount Cast Black Qiraji Resonating Crystal Indoors

### ISSUE THREAD

**Issue by mrnorr** [SunwellWoW/Sunwell-TBC-Bugtracker#1983]
Description: I am able to fully cast/use the item Black Qiraji Resonating Crystal in areas that are not meant to be mounted, aka 'indoors', and then it fails right at the end.

How it works: I click on the spell/item, it casts/uses the mount, and once the cast is finshed it fails.

How it should work: I click on the spell/item, it casts/uses the mount, fails instantly when indoors.

Source (you should point out proofs of your report, please give us some source): Can replicate in game, and in comparison to a normal mount. If this is working as intended please feel free to close, I have never owned one of these in any other version of the game.

**Comment by babno** [comment]
Since you can only get that via the AQ gates opening event (or gm powers) seems rather moot.

**Comment by Wojtyas** [comment]
Fixed & implemented.
