### ISSUE TITLE
[Mechanic][Buffs][Debuffs] De/Buffs are being overwritten by weaker spells

### ISSUE THREAD

**Issue by Ibuprofeno** [SunwellWoW/Sunwell-TBC-Bugtracker#1985]
Decription: Buffs and debuffs are being overwritten by weaker versions.

How it works: If you're buffed with Arcane Intellect rank 6 and cast AIr1 on yourself it will replace the former.
For debuffs: if you frostbolt (max rank) and instantly frostbolt rank1 your maxrank debuff (40%, 50% if improved, 12 seconds) will get replaced by your rank1 debuff (same slow, 8sec duration) 

How it should work: Weaker de/buffs shouldn't replace stronger active ones.

Source (you should point out proofs of your report, please give us some source): I couldn't find an specific patch stating this mechanic, however, changes made through TBC (and pre-Lk patches) confirm that stronger spells aren't overwritten by their weaker versions: 
In the 2.3.0 patch there's 10 issues resolved about spells being overwritten : http://wowwiki.wikia.com/wiki/Patch_2.3.0  
examples of buffs and debuffs fixed in this patch
Earth Shield: This ability will no longer be overwritten when the new Earth Shield would do less healing. 
Entangling Roots: This ability will no longer be overwritten when the new Entangling Roots would do less damage. 
In patch 2.3.2 we see something similar with druid's agi on proc idol (this is slightly different as it refers to buffs-of-the-same-kind-stacking) 
http://wowwiki.wikia.com/wiki/Patch_2.3.2
[Idol of Terror]: The triggered agility buff from this item no longer overwrites other agility buffs. 
and the clearer one is from 3.0.3 (pre-LK) when they buffed Greater blessing of might not to be removed by warrior's battle shout
Blessing of Might: Rank 8 points increased slightly to prevent from being overwritten by Battle Shout 8 that has a shorter duration (also applies to Greater Blessing of Might 3.)

**Comment by Wojtyas** [comment]
Already reported - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/385
