### ISSUE TITLE
Dreadlord NPCS spamming shadowbolt

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#1986]
Decription: Dreadlord NPC currently just spams shadowbolt and only melees immediately after a cast or resist

How it works: https://puu.sh/C8JTs/3a4c7ae2a6.mp4 As you can see the dreadlord is a shadow bolt machine gun

How it should work: The mob should have a proper spell database and functional AI. Other npcs share the same casting selection AI, but that is too much to get into 2 days before launch.

Source (you should point out proofs of your report, please give us some source): The mob should not just spam a nearly instant shadowbolt over and over and over and over.

**Comment by Dootz** [comment]
thank you. I've also made changes to AI of 300 creatures that are spamming one ability now. Cooldown on their spells will be a bit longer.
