### ISSUE TITLE
Black label rum stam

### ISSUE THREAD

**Issue by BIGCHESTDAY** [SunwellWoW/Sunwell-TBC-Bugtracker#1987]
Decription: 
Rumsey rum should stack with food buff

How it works: Overides food buff

How it should work: They should stack

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=QpgdAHJANcA&t=222s Video from retail

**Comment by akrom23** [comment]
Linked to #385

**Comment by doomnyx** [comment]
https://www.wowhead.com/item=21151/rumsey-rum-black-label#comments:id=66452

Invalid.

**Comment by notsofamous** [comment]
After 2.1 they changed buff stacking so it would no longer stack with other food buffs.

**Comment by akrom23** [comment]
We try to take spell mechanics from the last patch.

**Comment by ZaoQ** [comment]
Wowhead comment states that after 2.1 it no longer stacks with stamina food, no mention about other food buffs, currently rum is overwritten by any food and vice versa
