### ISSUE TITLE
You can sit at the same time as casting some spells/items

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#1988]
Decription: You can press sit the exact same time you cast your hearthstone, cyclone, instants and many other spells which shouldn't be allowed to happen

How it works: Press sit at the same time you cast hearthstone, or lifebloom, or rejuv

How it should work: the spell should be prioritized and the player should remain standing

Source (you should point out proofs of your report, please give us some source):

**Comment by Jseay1313** [comment]
https://imgur.com/a/Ef4TFzz

**Comment by koostosh** [comment]
Hearthstone is castable when sitting and it is not a bug. Not all spells require character to be standing, many positive spells can be cast when sitting including lifeblum and rejuvenation.
