### ISSUE TITLE
[Druid][Talent/Spell] Feral Aggression/Ferocious Bite

### ISSUE THREAD

**Issue by Patrulek** [SunwellWoW/Sunwell-TBC-Bugtracker#199]
Decription: 
https://db.darkwizard.pl/?spell=16862

How it works: 
Talent INCREASE dmg done of the Ferocious Bite, but the tooltip of that spell is not updating (DrDamage correctly shows the dmg depending on the talent level).

How it should work: 
Tooltip of the ferocious bite probably should update when you level up talent Feral Aggression (Demoralizing Roar behave correctly).

Source (you should point out proofs of your report, please give us some source): 
Just level up your talent and look at the tooltip.

**Comment by akrom23** [comment]
It's clientside bug. Tooltip of this spell is never updating - it's constant description.
```Description: Finishing move that causes damage per combo point and converts each extra point of energy into $f1 additional damage.  Damage is increased by your attack power.
   1 point  : 259-292 damage
   2 points: 428-461 damage
   3 points: 597-630 damage
   4 points: 766-799 damage
   5 points: 935-968 damage
