### ISSUE TITLE
Threat In kara 

### ISSUE THREAD

**Issue by BIGCHESTDAY** [SunwellWoW/Sunwell-TBC-Bugtracker#1990]
Decription: Threat On attument 1st boss in kara Bugged threat

How it works: According to omen i was 10k threat above the first dps and people were pulling

How it should work: Threat should work properly dps shouldnt shouldnt pull till 110% melee and 130% for ranged

Source (you should point out proofs of your report, please give us some source):

**Comment by KimmoKM** [comment]
WoW API doesn't allow addons to access threat information prior to 3.0.3. Consequently, all threat values are estimates, and in the case of Omen if not everyone has the addon, not very accurate estimates at all (if everyone does, I believe it's the most accurate).

More rigorous testing might be appropriate (calculating threat the mobs should have by hand), but I'd wager there's no issue.
