### ISSUE TITLE
Warlock ritual of summoning

### ISSUE THREAD

**Issue by BIGCHESTDAY** [SunwellWoW/Sunwell-TBC-Bugtracker#1992]
Decription: Attempting to summon a player in the instance results in shard loss and no summon

How it works: Attempting to summon a player in the instance results in shard loss and no summon

How it should work: Successful summon first time

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Till Sunwell Plateau content warlock shouldn't summon players into instances. Our dev is actually working on this spell.
