### ISSUE TITLE
[Warrior] Switching Stances resets Swing Timer

### ISSUE THREAD

**Issue by LudwigvanAT** [SunwellWoW/Sunwell-TBC-Bugtracker#1995]
Decription: 
Title

How it works: 
https://gyazo.com/e545a68662148582f83fc004f125b17c

How it should work: 
If you watch Auto-Attacks troughout the video you can see that switching Stance did not affect the Swing Timer, only switching weapons does.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=oo_vcsdBKXc&t=2m00s

**Comment by Wojtyas** [comment]
@Afgann revert please, make it works just for shapeshift change ;P

**Comment by Wojtyas** [comment]
Fixed & and implemented.
