### ISSUE TITLE
Vendors with infinite major mana potion stock

### ISSUE THREAD

**Issue by KimmoKM** [SunwellWoW/Sunwell-TBC-Bugtracker#1996]
Currently, Argent Dawn quartermasters at WPL and EPL have an infinite supply of Major Mana potions, a well-known HG quirk. I don't know where to begin about finding a black-on-white source, but I believe this should be self-explanatory: if this was Blizzlike, no one would ever have crafted mana pots in retail vanilla.

**Comment by Jseay1313** [comment]
nice find, never knew about this but def a concern
