### ISSUE TITLE
Dungeon: BRD flame cannons dont work

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#1997]
Decription: flame cannons during the Magmus event are not doing anything
**GRAAL: Gout of Flame (15529) does no dmg.**

How it works: the flame cannons cast their animation and do no damage or anything

How it should work: the player should take fire damage

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Duplicate.
