### ISSUE TITLE
Dungeon: BRD mobs in the Imperial Seat do not run and help the Emperor if left alive

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#1999]
Decription: The mobs in the Imperial Seat at the end of blackrock lair are not assisting the Emperor when he is attacked if they are left alive.

How it works: https://imgur.com/a/YxhumQD mobs can be skipped and emperor can be killed without clearing the adds

How it should work: Adds should assist the emperor if not cleared before pulling him when he yells and emotes "Come to aid the Throne!"

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
#21 - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/280
