### ISSUE TITLE
[Hunter] Taming the beast - Quest

### ISSUE THREAD

**Issue by Nok3m** [SunwellWoW/Sunwell-TBC-Bugtracker#2]
**Decription:** 
Quest is bugged, it instantly taming the beast.
Quest Pets are bit buggy <doesn't follow you>

**How it works:** 
When using the Taming Rod it instantly make quest "complete"

**How it should work:** 
It should be channeled 15 sec spell.

**Source (you should point out proofs of your report, please give us some source):** 

https://youtu.be/PxlqEUzRjao?t=48s

http://www.wowhead.com/item=15908/taming-rod

**Comment by akrom23** [comment]
#6.

**Comment by Bezimienny95** [comment]
Yep. Confirmed pet still w
![wowscrnshot_091018_205748](https://user-images.githubusercontent.com/31216921/45318284-b094b100-b53c-11e8-8cb8-216fd1e0538b.jpg)
ont move>
