### ISSUE TITLE
[Core][Spells] Block & Parry

### ISSUE THREAD

**Issue by Azathothh** [SunwellWoW/Sunwell-TBC-Bugtracker#200]
Decription: 
Block & Parry currently seems to don't work properly for player's characters - it's always 0% and can't be increased at all.
Checked at lvl70char with 350/350 def skill (block+parry learned from trainer) + some items with defense + talents increasing block chance - always stayed at 0%

Not sure if it's working on creatures or not.

**Comment by worugru** [comment]
Also spells such as paladins Redoubt or Holy Shield does not increase the block chance either. Character gets the debuff but block stays still at 0
