### ISSUE TITLE
Pet stops attacking 

### ISSUE THREAD

**Issue by Yumajii** [SunwellWoW/Sunwell-TBC-Bugtracker#2001]
When you attack a target dummy your pets just runs back to you and stops attacking, and you have to constanly and manually tell it to attack but it keeps running back anyway, sometimes you might get it to attack the dummy for a while but it will always run back to your character.

**Comment by Jseay1313** [comment]
Theres some evade issue with the dummies try standing at 9 meters to it or within 10

**Comment by Yumajii** [comment]
You are right, that actually helped, do you know if this is only an issue on dummys? I'll admit to no trying it on a real mob just yet.

**Comment by Wojtyas** [comment]
I highly belive its only dummies issue since we forced them to leave combat when possible to prevent more combat bugs.
Feel free to reopen if happens in open world but it was never noticed.
