### ISSUE TITLE
[Spell] Execute (minor)

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#2002]
Sometimes <Execute> text will pop upon targeting dead creature. Also Execute spell icon insinuates that it's able to use when its actually not. There was plenty of dead creatues around but only 2 of them gave me Execute call.

![image](https://user-images.githubusercontent.com/22802214/49150313-b95f7c80-f30c-11e8-821e-38a2ea7f36d1.png)

**Comment by notsofamous** [comment]
Is it the same with hammer of wrath?

**Comment by Wojtyas** [comment]
Fixed & implemented.
