### ISSUE TITLE
[Spell] Ritual of Summoning

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#2003]
Ritual of Summoning spell (698) shouldn't be able to use for summoning people inside instances and raids. It shouldn't also work in entire Netherstorm zone [zone: 3523].

https://www.wowhead.com/spell=698/ritual-of-summoning#comments

**Comment by Wojtyas** [comment]
Ok it looks like it works but with one exception and one more minor issue:

- [ ] Meeting Stone in Netherstorm doesn't work now - it should
- [ ] After recieving info that somebody cannot be summoned it would be nice to interrupt channeling spell

**Comment by Jseay1313** [comment]
This is just plain wrong, http://wowwiki.wikia.com/wiki/Ritual_of_Summoning And whatever fix you've done now doesnt allow people to summon players already inside the instance, great server.

**Comment by Wojtyas** [comment]
Cuz this is how it worked till Sunwell Plateau content? And we implemented patch changes so using this ability in instance will literally don't work.

_2.4.0 (2008-03-25): Can be used to summon players into instances if they meet the instance requirements._
