### ISSUE TITLE
Moroes combat bug after wipe

### ISSUE THREAD

**Issue by jackal111** [SunwellWoW/Sunwell-TBC-Bugtracker#2009]
Decription:
While attempting to kill Moroes on the instant 70 realm just 2 days ago we wiped and Moroes kept us locked in combat so we could not get back into the dungeon. He was just standing over someone's dead body looking at them but not resetting.

How it works:
Stuck in combat after wiping to Moroes.

How it should work:
When you wipe it should drop combat.

Source (you should point out proofs of your report, please give us some source):
There were 9 other members of the group there that can back me up. I didn't think to take a screenshot at the time.

I looked for this issue in the other Kara bug reports and didn't see it so decided to post this.

**Comment by Wojtyas** [comment]
It's fixed. Vanish issues.
