### ISSUE TITLE
Spell interruption

### ISSUE THREAD

**Issue by TechnoMulen** [SunwellWoW/Sunwell-TBC-Bugtracker#2017]
Decription:  When you interrupt an npc spellcast the mob is supposed to run towards you but here it just stands still doing nothing or takes a few steps back

How it works: 
I cast earth shock to interrupt.. it interrupts but mob does not run towards me 

How it should work: when interrupted the mob should run towards the top aggroholder 

Source (you should point out proofs of your report, please give us some source): 
easy to recreate

**Comment by akrom23** [comment]
Example?

**Comment by TechnoMulen** [comment]
shocking a razormane geomancer  with earth shock. 
and other mobs. They dont run towards me as they should to engage in melee combat

**Comment by akrom23** [comment]
Okay.

**Comment by Wojtyas** [comment]
Fixed & implemented.
