### ISSUE TITLE
Warlock quest in OG THE BINDING

### ISSUE THREAD

**Issue by magicborne** [SunwellWoW/Sunwell-TBC-Bugtracker#2019]
Decription: 

voidwalker quest in og.  summoning circle

How it works: 
summoning circle, is not there, it despawn.  and we are already waiting for 20 min to reappear.

How it should work: 
Summoning circle, use item, kill void, done.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
It's 15min cooldown, lets remove it significantly.

**Comment by Dootz** [comment]
changed to 30 seconds
