### ISSUE TITLE
Fireball  (mage)

### ISSUE THREAD

**Issue by lohanysarah** [SunwellWoW/Sunwell-TBC-Bugtracker#2031]
Decription: 

the spell's periodic damage does not work, in rank 2 it has to do 3 damage and only deals 1 damage in all the mobs.
How it works: 
the spell's periodic damage does not work, in rank 2 it has to do 3 damage and only deals 1 damage in all the mobs.

How it should work: 
deal 3 damage ( rank 2 of the spell) lvl 10 mage

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
It works good.

> 3 Fire damage **over** 6 sec.
