### ISSUE TITLE
elementary precision (mage Talent)

### ISSUE THREAD

**Issue by lohanysarah** [SunwellWoW/Sunwell-TBC-Bugtracker#2033]
Decription: 

reduce the mana cost and the probability the targets resist your frost and fire spells 1% (1 point)
How it works: 

it does not reduce the mana cost of the spells, they still have the same cost.

How it should work: 

reduce de mana cost of the spell frost and fire

Source (you should point out proofs of your report, please give us some source):

**Comment by Mikov1605** [comment]
You can close this one, it works. You cant see difference on rank 1 of the spell, because it is a 1% mana reduce. I got already a 100 mana cost spell, and after using this talent i get 99 mana cost. Please watch before reporting.

**Comment by Mikov1605** [comment]
Check spells which cost more than 100 mana. I bet they are reduced
