### ISSUE TITLE
Hunter pet can't learn growl, also negative training points

### ISSUE THREAD

**Issue by SolitudeFTW** [SunwellWoW/Sunwell-TBC-Bugtracker#2034]
Decription: 
Accidentaly learned growl before having a pet. Pet does not have growl anymore.

How it works: Growl does not exist in pet spell book or anywhere else.

How it should work: Growl should be available to any pet in the spellbook.

Source (you should point out proofs of your report, please give us some source): Sunwell TBC realm

**Comment by notsofamous** [comment]
Afaik pets can have negative training points if they already have an ability when you tame them.

Growl should be available in Beast Training, should **not** be in the pet spell book by default.

**Comment by SolitudeFTW** [comment]
Appears to work as intended

**Comment by Holeheart** [comment]
there should be negative training points.

also you teach pet by Beast Training spell in general tab of ur spellboook. then it comes to pet tab (if ur pet knows nothing, there is no tab).
source:

http://et.worldofwarcraft.wikia.com/wiki/Training_point

quote: Growl costs no training points at all ranks, and can even be trained with negative TP.
