### ISSUE TITLE
[mage] permafrost + frostbolt

### ISSUE THREAD

**Issue by maciekk57** [SunwellWoW/Sunwell-TBC-Bugtracker#2037]
Decription: 
Permafrost slow duration and effectiveness amplify doesn't apply to frostbolt.

How it works: 
^

How it should work: 
It should extend duration and make slow better.

edit: it also doesn't apply to frost armor chill effect so i assume it doesn't work at all

**Comment by maciekk57** [comment]
123

**Comment by akrom23** [comment]
Works good.
@maciekk57 Needs more info.

**Comment by akrom23** [comment]
No response. Closed.
