### ISSUE TITLE
swimming up with space not working correctly

### ISSUE THREAD

**Issue by PowerKeeper666** [SunwellWoW/Sunwell-TBC-Bugtracker#2038]
Decription: 
the problem is encountered while swimming underwater. I encountered this issue in Durotar, near the coast where the [from the wreckage](https://www.wowhead.com/quest=825/from-the-wreckage) quest is done.

How it works: 
When a character is underwater and presses space (jump hotkey), they jump as if they were on the ground.

How it should work: 
When space (jump hotkey) is pressed, a character should start swimming up with constant speed.

Source (you should point out proofs of your report, please give us some source):
you can use Angrathar/Feronis for reference.

**Comment by akrom23** [comment]
#2040.
