### ISSUE TITLE
[Druid] Shapeshift crit chance and weapon skill

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#2039]
When a druid is shape shifted their weapon skill doesn't matter (it counts as max). I'm not sure but I assume this should also work for the crit chance when you enter a form, otherwise all feral druids would be forced to skill up their weapon skills.

In conclusion:
When shape shifting your melee crit chance should be equal to if you had max weapon skill.

**Comment by Jeansapin** [comment]
Yep, source : https://www.wowhead.com/forums&topic=17401

**Comment by ahlens** [comment]
Yes, Druids weapon skill level should be always treated as max, the same goes for crit chance accordingly as both elements are related one to each other.

**Comment by tojothethief** [comment]
Made an issue about this as well but thought the Wrath tracker was for all their servers. Bumperino
