### ISSUE TITLE
[Movement] Teleports with .tele command

### ISSUE THREAD

**Issue by Azathothh** [SunwellWoW/Sunwell-TBC-Bugtracker#204]
Decription: Teleporting between certain areas with .tele command will result in fall dmg (even though we're not falling). Example is going to crossroads and teleporting to orgrimmar - always fall dmg (no dmg when going from orgrimmar to crossroads)
Tried using fly master between those locations and it was fine, with no fall dmg, but it may also occur with other types of teleports.

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC/commit/516cc978d60e6706c4deeeb6b070466324920a88
