### ISSUE TITLE
Jumping underwater

### ISSUE THREAD

**Issue by pakkom** [SunwellWoW/Sunwell-TBC-Bugtracker#2040]
Decription: 
You can jump underwater and swim up faster

How it works: 
If you press jump underwater your char jumps up instead of swimming. Makes for a faster way of swimming up than normally.

How it should work: 
You should just swim up

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Blizzlike - this is how it worked in TBC.
