### ISSUE TITLE
Loggin problem!

### ISSUE THREAD

**Issue by onferflay** [SunwellWoW/Sunwell-TBC-Bugtracker#2045]
Decription: 
i just createa an account, activate it via email and now when i try to login server down! ok i waiting it for up again check the sitepage that server work and population slowly grow , i start wow try login on realm list i see server is up population is high but i cant connect to them still disconnect from server and i try again and again like 20 min still can't login!

How it works: 
disconnect from server

How it should work: 
should login instant!

Source (you should point out proofs of your report, please give us some source):

**Comment by mario713** [comment]
Same here. Im stuck on "Connected" box and it's disconnecting me after a while of waiting.
