### ISSUE TITLE
Oxygen under Water doesnt work

### ISSUE THREAD

**Issue by Nghedi** [SunwellWoW/Sunwell-TBC-Bugtracker#2047]
Decription: 

Oxygen under Water doesnt work.

How it works: 

Nothing happens. You loose breath.

How it should work: 

You should be able to breath.

Source (you should point out proofs of your report, please give us some source):

**Comment by Nghedi** [comment]
F.e. at the forgotten pools in barrens.

**Comment by Jseay1313** [comment]
They dont work in moonglade or anywhere, fix fix fix

**Comment by Nghedi** [comment]
Closing, since it seems to work now.
