### ISSUE TITLE
Shamanistic Focus

### ISSUE THREAD

**Issue by Bzmode** [SunwellWoW/Sunwell-TBC-Bugtracker#2048]
Decription: Autoattacks / Flametongue / Searing Totem(Almost all effects) weapon eat the procs

How it works: Autoattacks / Flametongue weapon eat the procs

How it should work: Should only be used when you cast a shock spell.

Source (you should point out proofs of your report, please give us some source):

**Comment by Fredd32** [comment]
Maybe it's a lower spell rank issue, but Shamanistic Focus 100% gets eaten up by Searing Totem at rank 1 and 2 searing totem levels, not so sure that flametongue does anything seeing as I keep the buff when I crit and don't use searing totem.

**Comment by bajensvin** [comment]
Damaging an enemy with lightning shield seems to eat the buff as well.

**Comment by amarathTESTER** [comment]
Lightning Bolt also eats it.

**Comment by ShazBurger** [comment]
![wowscrnshot_120418_135444](https://user-images.githubusercontent.com/45581174/49415926-523e3e00-f7cc-11e8-99d2-957d99341db9.jpg)
![wowscrnshot_120418_135438](https://user-images.githubusercontent.com/45581174/49415930-536f6b00-f7cc-11e8-8771-c2ab4d52da59.jpg)

managed to get some screenshots of me getting the proc then placing totem n letting it attack an enemy.

**Comment by s2nratio** [comment]
it is also consumed by healing wave and lesser healing wave, very easy reproducable. caught that while skilling weapons and not using anything else.

**Comment by zanthed1** [comment]
Lesser healing wave, Healing wave, Lightning bolt + Chain lightning, Lightning shield, Flametongue + Windfury, Searing totem, and maybe something else I'm missing all consume this. Seems like all elemental dmg.
