### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by Koublis** [SunwellWoW/Sunwell-TBC-Bugtracker#2053]
Decription: 
Been playing for one hour last night, then i DCed, and since then cant login at all. Been askin Game Masters on Discord what is goin on. The only response i get is "keep trying, lot of ppl has this problem"...
Im not here to keep trying to log in the server, i want to play,... Write a password and jump in game. 
Discord updates are saying new machines updates etc. but nothing of it works for me. 
So i want a clear answer what should i do. I see 4000ppl online and i still cant connect.
Thanks

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by magicborne** [comment]
Not only you have this problem, dont worry.  The authentication server has some/many issues and it is slow af.

They are working on it.  The only thing you can do is try constantly,  with friends we also try for 10 min without stop and then if we are lucky we get in .   Hopefully they fix it soon.
