### ISSUE TITLE
[General] One-faction lock

### ISSUE THREAD

**Issue by nimeral** [SunwellWoW/Sunwell-TBC-Bugtracker#2055]
Decription: you are locked to one faction on Nightbane

How it works: if you have an Alliance char, you can't create a Horde one

How it should work: if you have an Alliance char, you should still be able to create a Horde one

Source (you should point out proofs of your report, please give us some source): what I'm asking for isn't technically Blizzlike, but it's the only thing that makes sense on a free to play server. Please remove the lock and allow people to have opposite faction chars without them needing to swap account.

**Comment by Dootz** [comment]
Hi,

we don't plan to modify it anytime soon. It's blizzlike behavior.

**Comment by nimeral** [comment]
It is, but isn't it obvoius that it's only annoying but adds nothing to the actual Blizzlikeness? Those who want opposite faction chars just need another _free_ account.
