### ISSUE TITLE
Game CRASHES when logging in IRONFORGE

### ISSUE THREAD

**Issue by Sciobelo** [SunwellWoW/Sunwell-TBC-Bugtracker#2056]
Decription: 
Game crashes when logging in Ironforge

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Sciobelo** [comment]
turned off all addons, still crashes

**Comment by Sciobelo** [comment]
Logged in after 6 times

**Comment by Nadiirr** [comment]
If you're still having issues message me your character name on discord and i'll move you out of there Nadiir#0364

**Comment by LezChap** [comment]
I had this happen right after the crash where Dredd says "it was our fault" around 4:06pm EST (9pm server).  I was on a FP to Wetlands when the crash occurred, when I tried to log in I could see IF but my client would hard crash with a report similar to the Screenshot above.  A GM (Adrestia) had to move my toon in order for me to be able to log in.  Hope that gives more details to try to track the issue down.

**Comment by akrom23** [comment]
Still happens?
