### ISSUE TITLE
Gubber Blump Sold out

### ISSUE THREAD

**Issue by dogshep** [SunwellWoW/Sunwell-TBC-Bugtracker#2058]
Decription:  Gubber Blump in Auberdine sold out of Fishing Poles and Shiny Baubles for quest

How it works: Sold out

How it should work: Not so much sold out

Source (you should point out proofs of your report, please give us some source): See Gubber Blump at 36.1, 44.9
![gubber](https://user-images.githubusercontent.com/1896042/49333964-1f742a00-f5c1-11e8-944a-0cc72ef6938b.PNG)

**Comment by Dootz** [comment]
fixed, live on server. Thank you for report.
