### ISSUE TITLE
Default nameplate cast bar not working.

### ISSUE THREAD

**Issue by PedroHrafn** [SunwellWoW/Sunwell-TBC-Bugtracker#2059]
Decription: 
The built in nameplate cast bar isn't working.

How it works: 
The cast bar itself shows up but there is no bar progress animation bar inside it (It just stays empty).
Then after casting the cast bar stays up.

How it should work: 
Bar animation should show up.

Source (you should point out proofs of your report, please give us some source): 
I've been leveling in mulgore and barrens and I've seen this on all caster mobs that I've encountered.

**Comment by koostosh** [comment]
Works for me on clean client, possibly error with some addon.
