### ISSUE TITLE
Rogue/druid energy regen when fail to land.

### ISSUE THREAD

**Issue by Valesisback** [SunwellWoW/Sunwell-TBC-Bugtracker#2060]
Decription: When a special ability that uses energy and generate combo point fail to land, it does not regenerate 80% of the cost of the ability.

How it works: The ability fail to land and you lose the amount of energy that the ability should use if it had landed.

How it should work: You should get a 80% refund on energy after a special ability fail to land.

Source (you should point out proofs of your report, please give us some source): Hum I don't know guys, I've been playing rogue for like 15years and it's always been the case. I guess i found this link : https://jira.vengeancewow.com/browse/TBC-177

**Comment by ZaoQ** [comment]
You can find multiple sources on that topic, if your special attack misses, you will get no refund, if your attack is dodged you will get 80% refund, if your attack is parried you will get 20% refund
