### ISSUE TITLE
NPCs making noise when using the pet attack button

### ISSUE THREAD

**Issue by Sabre142** [SunwellWoW/Sunwell-TBC-Bugtracker#2067]
Decription: 
NPCs will make a noise when you use your pet attack ability (including players).

How it works: 

How it should work: 
They should not make a noise until you get in combat.

Source (you should point out proofs of your report, please give us some source):

**Comment by fishworld** [comment]
Yes, I can confirm this. They should make a sound but only their own, i.e. if you have a cat and have it attack a boar, it should make the cat sound not that NPC sound (in the case, the boar).
