### ISSUE TITLE
NPCs in Darkshire do not have correct pathing

### ISSUE THREAD

**Issue by leahnie956** [SunwellWoW/Sunwell-TBC-Bugtracker#207]
Decription: 
NPCs in Darkshire do not have correct pathing

How it works: 
should walk normally

How it should work: 
should walk normally

Source (you should point out proofs of your report, please give us some source): 
![etnetyne](https://user-images.githubusercontent.com/25886407/44631066-a499d400-a92c-11e8-91ad-a20481412aa2.jpg)
![wrthwh](https://user-images.githubusercontent.com/25886407/44631067-a9f71e80-a92c-11e8-93d3-07f9b7ae1e0a.png)

**Comment by Dootz** [comment]
thanks for report, will be fixed with next ptr update.
