### ISSUE TITLE
Mounts Paladins and Warlocks vs the other classes.

### ISSUE THREAD

**Issue by Gunerus** [SunwellWoW/Sunwell-TBC-Bugtracker#2071]
Decription: Everybody except Paladins and Warlock can't but their mounts till lvl 40,while paladins and warlock can buy them at level 30.

How it works: 
After 2.3 everybody should be able to buy the mount at 30 and it depends on you if we're getting it at 30 or at 40.

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
Just go to Thousand Needles and look at people,lol,i'm so annoyed that i ain't even posting a screenshot.

**Comment by Dootz** [comment]
Hi, it was fixed with last restart.

**Comment by Delfury** [comment]
> Hi, it was fixed with last restart.

Which way was it supposed to be fixed to, 30 or 40?
