### ISSUE TITLE
[Warlock][Talent] Improved Drain Soul

### ISSUE THREAD

**Issue by przemekga** [SunwellWoW/Sunwell-TBC-Bugtracker#2073]
Decription: 
Improved Drain Soul is not giving a mana regen buff.

How it works: 
It's not working at all, whether you kill a mob with DS tick or mob is killed by anything else during DS channeling.

How it should work: 
Should give mana regen buff after dealing a killing blow while channeling Drain Soul.

Source (you should point out proofs of your report, please give us some source): 

123

**Comment by Sabre142** [comment]
It's working for me. It restores 15% of your mana on the killing blow.

**Comment by ArekJadach** [comment]
I tried that in ragefire chasm and  this talent when is 1/2  gives 7% but on 2/2 gives nothing :(
edit: in open world it works fine

**Comment by ghost** [comment]
MANA FROM NON-TARGET

Scenario:

1. Pull 2 mobs, drain soul one.
2. Mob without Drain Soul debuff dies, you gain mana

You should only gain mana from target with applied drain soul debuff
