### ISSUE TITLE
shaman totems following people like mobs 

### ISSUE THREAD

**Issue by lazerdagerr** [SunwellWoW/Sunwell-TBC-Bugtracker#2077]
Decription: Shaman totems following people like aggrod mobs

How it works: totems following people like aggrod mobs

How it should work: the totem should be static. after casting the totem should be stuck in place and not be shown like an enemy mob

Source (you should point out proofs of your report, please give us some source): Umm.. i saw it in game. people were chatting about it in general?

**Comment by TheRealestMcCoy** [comment]
I have seen this issue to along with pets and totems being enemies once they reach your field of view.

**Comment by MellevaSipe** [comment]
Can confirm. The totems move and auto attack targets. For example Furbolg totems in Ashenvale did this frequently.

**Comment by akrom23** [comment]
@coltonreeves You mean players' totems?

**Comment by ghost** [comment]
Yes, player's totems.

**Comment by TheRealestMcCoy** [comment]
ive seen it happen with npc totems as well the ogers in stv the shamans drop healing totems that attack a player as well

**Comment by akrom23** [comment]
@lazerdagerr  Cannot reproduce it with player's totem. Would you tell me what should I do? And what totem summon? Maybe some screenshots?

**Comment by ghost** [comment]
It never happened with MY totems when I was playing shaman, it was only other shaman's totems. Literally, it was just other player's totems turning red and aggroing like any mob in game. If i got close enough they would melee me and I would take damage. It wasn't every totem all of the time, it was some totem's some of the time. I don't have any screen shots, but I'm sure if you give it enough time it will happen. It is a pretty well known problem to everyone in game.

**Comment by akrom23** [comment]
I tried many times - with no success.
