### ISSUE TITLE
Lupos Loot

### ISSUE THREAD

**Issue by Proseccobabe** [SunwellWoW/Sunwell-TBC-Bugtracker#2079]
Decription:  Lupos cape drops from some Quilboars in Barrens.

How it works: Kill some quilboars, the ones for the weapon quest in Camp Taurajo were the ones where it dropped for me. (Sorry forgot the name, currently waiting for server so doing some of these).

How it should work: Cape should only drop from Lupos.

Source (you should point out proofs of your report, please give us some source): 
Check character Never, he has it.

**Comment by Dootz** [comment]
fixed, live on server. Thank you for report.
