### ISSUE TITLE
[Warlock][Talent] Aftermath

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#208]
Decription: It is affecting the casting warlock.

How it works: While casting Hellfire or Rain of Fire and Aftermath procs it will affect the casting warlock aswell.

How it should work: It shouldnt affect the casting warlock at all.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@Silroth Tell me - every target of Rain of Fire/Hellfire should be afflicted by Aftermath effect? Or it should triggers only once?

**Comment by Silroth** [comment]
Every hostile target should get affected by it and it can proc multiple times in a row but its unlikely to happen due to 10% proc chance.

**Comment by Silroth** [comment]
Aftermath from Hellfire is still affecting the casting warlock 
![image](https://user-images.githubusercontent.com/42102450/45811251-e8ce8900-bccc-11e8-9b9e-091591973ba7.png)
