### ISSUE TITLE
Returning mail causes items to disappear.

### ISSUE THREAD

**Issue by supfam123** [SunwellWoW/Sunwell-TBC-Bugtracker#2084]
Decription: Sent some items to my bank alt, pressed return to send them back to my main, they are gone, my main never received the mail.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Proseccobabe** [comment]
Happened to me as well, can be circumvented by sending it with a cod.

**Comment by myacxy** [comment]
I also had whole batches disappear when returning mail from my bank char to my main.

**Comment by ZaoQ** [comment]
Will we get items from those missing mails???

im missing like 50 items guys !!!

can u tell me why this bug was not labeled CRITICAL? and it was fixed after 2 ******* days??!!
