### ISSUE TITLE
[Quest] Need For a Cure

### ISSUE THREAD

**Issue by bfrazee11** [SunwellWoW/Sunwell-TBC-Bugtracker#2090]
Decription: 
When you pick up the quest your game completely stops responding. even after logging back in the game stops.

How it works: 
Pick it up and your stuck.

How it should work: 
actually be able to do the quest.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=812/need-for-a-cure

**Comment by Lamberdo** [comment]
Venomtail Poison Sac  this quest item dont drop from Venomtail Scorpid/Corrupted Scorpid...
