### ISSUE TITLE
Feral Swiftness Druid talent

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#2093]
Decription: currently gives speed indoors if cast outside first, does not give speed when cast indoors and then you go outdoors, does not transition correctly between an indoor and outdoor environment

How it works: currently gives speed indoors if cast outside first, does not give speed when cast indoors and then you go outdoors, does not transition correctly between an indoor and outdoor environment

How it should work: it should disable the buff when outdoors and enable when indoors regardless of where you cast cat form

Source (you should point out proofs of your report, please give us some source):

**Comment by christoffer-bolin** [comment]
Second this, works like this all the time so if you need proof just /w me and i can go in at any house to prove

**Comment by ahlens** [comment]
Quite complicated explanation from author.

Feral Swiftness movemeent speed is not applied correctly when indoors/outdoors. You have to shapeshift again in order to regain movement speed or accordingly - lose it.

Should be applied automatically when entering certain areas.
