### ISSUE TITLE
Hunter pets moving too fast

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#2096]
Decription: certain hunt pets are permanently moving too fast, out running a druid in travel form with ease, looks to be near 60% mount speed

How it works: hunter pets are currently moving absurdly fast without dash/sprint

How it should work: normalized speed

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
Are you sure the pet didn't use "Dash" or something? For me my pet walks at normalized speed (+30% per talent).

**Comment by Jseay1313** [comment]
Says in the bug report that dash wasn't happening, engage the pet on a player and not an NPC, same for warlock pets atm, they are as fast as a 60% mount.

**Comment by pleasse** [comment]
got chased by hunter pet BM vs travel form no dash active out ran me, worth looking in to was in the heat of the moment so did not print ill try to catch a print screen 
*it was a bear pet from plague lands, might be specific pets moving faster?

just killed another hunter with a cat pet popping the bm cd, i out ran the pet without dash active.

**Comment by akrom23** [comment]
@Jseay1313 @ujellyx @pleasse I need to know exaclty what pets make problems here.
Remember that pets inherit player's speed.
Maybe got some auras/buff/talent from hunter?
Bestial Swiftness adds 30%.

**Comment by akrom23** [comment]
Seems to work fine.
When pet is not in combat - it shares the speed of the owner.
When pet is in combat - apply all its modifiers.
Default pet speed rate is 1.15. 30% extra from Bestial Swiftness:
1.15 * 1.30 = 1.495 - means 50% higher speed.
