### ISSUE TITLE
Pets not leashing after certain distance from owner

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#2097]
Decription: Pets currently can chase a player infinitely in WSG or in the open world

How it works: Pet does not leash when sent on player in WSG despite being on the complete other side of the map

How it should work: Pet shouild leash or disappear when far enough away from owner

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Works fine.
