### ISSUE TITLE
[Zone] [Darkshore] [Low Priority] Untextured Ground

### ISSUE THREAD

**Issue by Azbine** [SunwellWoW/Sunwell-TBC-Bugtracker#2099]
Description: Some areas around Bashal'Aran are not textured and display purple and white cubes. Low priority, as it does not break the game. However, it is still a bug

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/AKuO6c5

**Comment by Wojtyas** [comment]
Fixed & implemented.
