### ISSUE TITLE
[Blood Elf][NPC] Springpaw Cub & Springpaw Lynx

### ISSUE THREAD

**Issue by dredd-sunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#21]
Decription:  Springpaw Cub (15366) and Springpaw Lynx (15372) should have linked aggro.

Video TBC: https://youtu.be/WlCPdUq4GyU?t=1m47s

WoWhead comment WotLK: "these guys walk about with their cub and (as if the cub is their pet) the cub will attack too.. kinda cool"

Video Cata: https://youtu.be/oFkapGk9t2o?t=22s

**Comment by artemmavrich** [comment]
The bug is not fixed, why closed?
