### ISSUE TITLE
hunter pet breaks prowl before attack

### ISSUE THREAD

**Issue by headshot420** [SunwellWoW/Sunwell-TBC-Bugtracker#2100]
Decription:  

hunter pet prowl breaks.

How it works: 

hunter pet prowl breaks before it attacks, as soon as I command him to attack, he will come out of prowl and start running at the mob, not sure but maybe something to do with the 30% pet run speed hunter talent, seems like he starts running fast because of it and it breaks the prowl.

How it should work:  should walk up to mob in stealth and get 20% bonus damage on first attack.

Source (you should point out proofs of your report, please give us some source):

**Comment by Xyter** [comment]
Yes, have noticed this as well

**Comment by ryosuki** [comment]
Bump, still breaks when entering combat - unable to get bonus of Prowl.

**Comment by zendar123** [comment]
+1 still waiting

**Comment by akrom23** [comment]
Cannot reproduce it.
![wowscrnshot_012119_104610](https://user-images.githubusercontent.com/1035215/51466153-d0997400-1d69-11e9-8acf-9b3f2d391f8e.jpg)

**Comment by akrom23** [comment]
No response.
