### ISSUE TITLE
Power Word: Fortitude makes you lose HP even when you already have it

### ISSUE THREAD

**Issue by tacotal** [SunwellWoW/Sunwell-TBC-Bugtracker#2102]
Description: 
When you first apply fort, you lose current HP because your maximum HP goes up. When you reapply it, it shouldn't make you lose HP as you don't get more maximum HP.

How it works: 
When you apply fort on someone and they already have it, they lose current HP. I'm assuming it's because they temporarily lose the buff and regain it, which lowers their maximum HP and then your max hp goes up again.

How it should work: 
Your current and maximum HP should remain exactly the same when you reapply fort.

Source (you should point out proofs of your report, please give us some source): 
Self explanatory, uploading a video would take too long.

**Comment by koostosh** [comment]
You provided no source that it should not lower your hp temporarily.
