### ISSUE TITLE
The daily BG quest give absurd rewards

### ISSUE THREAD

**Issue by tacotal** [SunwellWoW/Sunwell-TBC-Bugtracker#2104]
Description: 
The daily BG quest seems to give a fix amount of gold / XP, which makes it overpowered for lower levels. Players between 10-19 get pretty much a full level and 4g40s for completing it.

How it works: 
The daily BG quest seems to give a fix amount of gold / XP, which makes it overpowered for lower levels. Players between 10-19 get pretty much a full level and 4g40s for completing it.

How it should work: 
I don't know the exact rewards it should give, but frankly I report so many bugs that I honestly don't wanna do the research myself.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed, live on server. Thank you for report.
