### ISSUE TITLE
Damage doesn't break fear

### ISSUE THREAD

**Issue by tacotal** [SunwellWoW/Sunwell-TBC-Bugtracker#2106]
Decription: 
When you fear someone (so far I can only confirm with warlock fear), damaging the target doesn't break the fear.

How it works: 
When you fear someone (so far I can only confirm with warlock fear), damaging the target doesn't break the fear.

How it should work: 
After taking a certain amount of damage (more or less 25% HP), the target should have their fear break.

Source (you should point out proofs of your report, please give us some source):

**Comment by Jseay1313** [comment]
confirmed

**Comment by ujellyx** [comment]
Yeah can confirm. Was feared by a warlock in bg today and was killed 100-0 while being feared.

**Comment by Khryx** [comment]
Confirmed, still the case, i did 100%-0 on fear, very annoying, and he make you run where he shouldn't, like a mountain or whatever place where you usually can't go.

**Comment by potty** [comment]
This should be marked as High priority/Critical as fear is OP now.

**Comment by tacotal** [comment]
???? Bump

This is a game breaking bug, can this be addressed?
