### ISSUE TITLE
(Class Quest- Warlock) Creature of the Void

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#2107]
Decription: 

How it works: 
Player cannot open chest Entry 58595 , Guid 12194, it says "Already in use" to loot http://db.darkwizard.pl/?item=6535

How it should work: 
Chest should despawn if someone else looted it then respawn for another player.

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?quest=1501

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2124
It's most likely due to general issue. The chest itself seems to work normally.
