### ISSUE TITLE
" Thunderbrew Lager " quest by Grimbooze Thunderbrew, 

### ISSUE THREAD

**Issue by Imsdal92** [SunwellWoW/Sunwell-TBC-Bugtracker#2108]
Decription: 
Its not possible to accept the quest. 

How it works: 
When right clicking NPC, the quest window opens but its not possible to push "Continue". He also doesnt have the quest (!) sign above him. 

How it should work: 
Right Click NPC, deliver your x5 Hops, get your Keg of Thunderbrew Lager. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2069

**Comment by ghost** [comment]
Two other players reported this issue today.
