### ISSUE TITLE
[NPC]{Barrens} Hezrul Bloodmark missing Guard NPCs

### ISSUE THREAD

**Issue by forafriend** [SunwellWoW/Sunwell-TBC-Bugtracker#211]
Description: Hezrul Bloodmark (npc 3396) is missing his two guard npcs.

How it works: Hezrul currently pats around the Lushwater Oasis south of the wailing caverns by himself.

How it should work: Hezrul should have two "guard" npcs that path with him. From the thottbott source it mentions "Bloodcharger body guards", so the npc with him should be Kolkar Bloodcharger (npc 3397). Wowhead comments also state the guards cast corruption, which the Bloodcharger's do cast.

Source (you should point out proofs of your report, please give us some source): 
https://web.archive.org/web/20071011033344/http://thottbot.com:80/c3396
`Killed him with a 17 shaman.  Pick off one of the bloodcharger body guards with DPS, then run straight for the graveyard.  Hezrul and the other bodyguard will probabbly kill you, but by then your corpse is a quick run from the GY. `

https://www.wowhead.com/npc=3396/hezrul-bloodmark#comments
Patch 1.12 - `Walks around the oasis clockwise. To find him go counterclockwise. He has 2 adds with him.`
Patch 2.4.3 - `His adds cast a Corruption spell that can mess you up if you're at the lower level range. Hezrul himself has a ranged (bow) attack. Taking out all three is not so bad for most classes, as long as you're not under-leveled...`

**Comment by Dootz** [comment]
thanks for the detailed report, will be fixed with next update.
