### ISSUE TITLE
Instant enchant in trade

### ISSUE THREAD

**Issue by oloens** [SunwellWoW/Sunwell-TBC-Bugtracker#2110]
Description: 
When you enchant something in trade window the enchant is applied instantly instead of upon the trade agreement completing.

How it works: 
The enchant applies instantly just as if you enchanted your own item

How it should work: 
The enchant does not apply until a trade is made

**Comment by Pizzle93** [comment]
it should also show that it will be enchanted (currently shows nothing).

This is quite important as people can screw you over massively by taking the enchant without paying
