### ISSUE TITLE
Trouble at the Docks

### ISSUE THREAD

**Issue by Gingervituz** [SunwellWoW/Sunwell-TBC-Bugtracker#2112]
Description: 

Mad Magglish isnt spawning
How it works: 

How it should work: 
he should spawn

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
You can find him in Wailing Caverns. He's in stealth
![wowscrnshot_120218_100808](https://user-images.githubusercontent.com/25490436/49337853-3b57ea00-f61a-11e8-8288-207dd82e4d09.jpg)
