### ISSUE TITLE
Action bar become invisible when using map during combat

### ISSUE THREAD

**Issue by AceArthur** [SunwellWoW/Sunwell-TBC-Bugtracker#2114]
Description: 
Action bar become invisible when using map during combat

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/13106680/49337021-15522b80-f5c1-11e8-9eb2-44c1fdf190fd.png)

**Comment by Afgann** [comment]
disable all addons and try again

**Comment by TheRealestMcCoy** [comment]
are you using elvui?

**Comment by Nadiirr** [comment]
I've had this happen to me a few times as well. Unknown why.
Had questhelper addon + Chatter addon

**Comment by AceArthur** [comment]
Resolved after disable add-ons.
