### ISSUE TITLE
Fishing bobbers

### ISSUE THREAD

**Issue by Overzealoustherealone** [SunwellWoW/Sunwell-TBC-Bugtracker#2116]
Description: Fishing bobbers aren't despawning at all.

How it works:  Fishing bobbers aren't despawning at all.

How it should work: They should be despawning after being looted.

Source (you should point out proofs of your report, please give us some source): 
Yeah just , go fish youknow! 🐟

**Comment by Braderman88** [comment]
I noticed this too, although for me, the bobbers did disappear when there was a fish caught. If the fish was caught, the bobber disappeared for me, if I failed to catch the fish, the bobber remained. Loads in the lake near goldshire.

**Comment by ghost** [comment]
When using the fishing skill on rivers there is a minor problem with the fishing bobber it will do replica on the spot where u are fishing after a while there can be many replicas on the fishing bobber in the same place u where fishing this can be a bit annoying when there is tons of bobbers all over the place where you are trying to fish

**Comment by Wojtyas** [comment]
Fixed & implemented.
