### ISSUE TITLE
gift of the naaru

### ISSUE THREAD

**Issue by dalaraz** [SunwellWoW/Sunwell-TBC-Bugtracker#2119]
Description: it overheals by a lot 

How it works: it heales for 20% per tik for 5 ticks every 3 seconds.total 15 seconds

How it should work: 4% healing per tick for 5 ticks every 3 seconds,total 15 seconds

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Gift_of_the_Naaru

**Comment by lukaasm** [comment]
if u use historical WoWWiki entry:
http://wowwiki.wikia.com/wiki/Gift_of_the_Naaru?oldid=1423006
You will see that Gift of Naaru behaviour during TBC was different:
- it should heal for value of: 7 + 3 * level per tick + 100% healing coeff

Spell works fine.
