### ISSUE TITLE
Taking damage from untargetable/invisible mob in Darkshore - Twilight Vale

### ISSUE THREAD

**Issue by glassjaaw** [SunwellWoW/Sunwell-TBC-Bugtracker#2120]
Description: Randomly taking dmg from an unknown mob in Darkshore - Twilight Vale.

How it works:  Will be running around working on quests, and will then enter combat and start taking dmg from invisible mob in which you can't see or target.

How it should work:  Mob should be seen so we can attack and kill it.

Source (you should point out proofs of your report, please give us some source):  Read general chat in darkshore.. everyone is complaining about it.. can't take a picture cause it's an invisible mob.
https://imgur.com/a/wcX2X57

**Comment by Nadiirr** [comment]
![screenshot_150](https://user-images.githubusercontent.com/36300104/49338514-beefe780-f5d6-11e8-913c-6dc4f855963a.png)


This is the cause. Rabid Thistle Bears

**Comment by mario713** [comment]
Also I can confirm that some of the Rabid Thistle Bears are visible and targetable on the north of the darkshore.

**Comment by Dootz** [comment]
fixed, live on server. Thank you for report.
