### ISSUE TITLE
Lizzarak is not spawned with his body guard

### ISSUE THREAD

**Issue by Gingervituz** [SunwellWoW/Sunwell-TBC-Bugtracker#2122]
Description: 

Lizzarak is not spawned with his body guard
How it works: 

How it should work: 
lizzarak should be spawned

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
He's traveling between Crossroads and Ratchet. But you're right his bodyguard should follow. Thank you for report.

**Comment by Dootz** [comment]
fixed, live on server. Thank you for report.
