### ISSUE TITLE
Rogue Talent remoreseless attacks proc gets removed by thrown wepon skill.

### ISSUE THREAD

**Issue by Raiilan** [SunwellWoW/Sunwell-TBC-Bugtracker#2127]
Description: as title says. When rogue has talents in assassination tree (remorseless attacks and kills a target that yields experience or honor the rogue gets a buff that increase critchance by 20/40% for a set of abilities.

The problem is if the rogue uses thrown wepon skill the buff gets consuned.

How it works: the buff should only get consumed if using 1 of the spells mentioned in the tooltip of the talent. (Remoreseless attacks)

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by za-x-az** [comment]
Can confirm this. it gets removed by any attack, but an auto attack.
