### ISSUE TITLE
Hunter Auto Attack Interrupted

### ISSUE THREAD

**Issue by Macnjacks** [SunwellWoW/Sunwell-TBC-Bugtracker#2128]
Description: 
When auto attacking from ranged, if you swap targets quickly, it will cause your auto attack to not do anything and keep saying "Interrupted" over and over. Only way to fix is to jump and move or use an ability.

How it works: 
When you swap targets frequently from attacking, it causes your auto attack to fail and start saying "Interrupted".

How it should work: 
Auto attack should continue no matter what if you swap targets.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=qUpC-KjuQeI&feature=youtu.be   made a video

**Comment by ujellyx** [comment]
As i suppose the last restart implemented the hotfix - right now a new bug occurs: the Auto Shot continues on the old target after I switch to a new target and even after I use abilities on my new target... but the Auto Shot should switch the target with me switching it and not continue on the old target. @lukaasm
