### ISSUE TITLE
Shaman Clearcasting

### ISSUE THREAD

**Issue by Semibonge** [SunwellWoW/Sunwell-TBC-Bugtracker#2129]
Description: 
Consumes both stacks on one attack 

How it works: 
consumes both stacks and doesnt reduce mana

How it should work: 
reduce the next 2 elemental attacks by 40% mana

Source (you should point out proofs of your report, please give us some source): 
Im playing elemental shaman so im the source i guess. Semi in game

**Comment by Semibonge** [comment]
Seems like it does remove the manacost after all, just the stacks working after further inspection

**Comment by dalaraz** [comment]
theres an issue with shamanistic focus which seems the same maybe? lighting shield concumes the effect
