### ISSUE TITLE
Celebras [Maraudon]

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#213]
### **TO DO:** 

- [x] 1. During Twisted Tranquility channel spell () players should got debuff dealing damage, reducing movement speed and increasing time between melee attacks but they don't.
![image](https://user-images.githubusercontent.com/22802214/44658420-0d528080-aa01-11e8-8d41-f9858756083d.png)
- [x] 2. Celebras the Redeemed should has his Reju aura for quite longer during his scepter creation on quest 7046.

### **DONE:**

- [x] 1. Corrupt Force of Nature (entry: 13743; guids: 55107, 55108, 55109) shouldn't have random movements.
- [x] 2. After wipe/boss evade those 3 Corrupt Force of Nature npcs should respawn.
- [x] 3. Celebras the Cursed (12225) should use his first summon spell Corrupt Forces of Nature (21968) around 5 seconds after pull.
- [x] 4. Corrupt Force of Nature (with guid 0) that are spawned by spell mentioned in point 3. should start to attack players immediately after summoned.
- [x] 5. Corrupt Force of Nature (with guid 0) that are spawned by spell mentioned in point 3. should disappear when boss evades.
- [x] 6. Celebras the Redeemed (13716) appears after we defeat his cursed version which works properly. After we accept his quest The Scepter of Celebras (7046) nothing happens. Actually we should start an event where we have to protect our questgiver while he's creating scepter. After we recieve this item we have completed Maraudon attunement and we can now create portal to last quarter of instance in pre-instance location.
- [x] 7. When player uses TEMP Maraudon Portal gob he is teleported into last part of Maraudon instance. Destination point of teleportation is wrong at this moment. Correct tele location on screen below:
![image](https://user-images.githubusercontent.com/22802214/44659054-307e2f80-aa03-11e8-8f30-ad11e0ad9df6.png)
- [x] 8. Portal to Inner Maraudon gob (178404) is spawned by spell. It should always be spawned in the middle of square gob named CentaurTeleporter (32566) when requirements are fulfilled. 
Coords of spawned portal:
![image](https://user-images.githubusercontent.com/22802214/45576458-911cc180-b877-11e8-8bfc-9a62cf960693.png)
- [x] 9. On same quest time between his emotes should be increased for 1-2 seconds.

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
Updated.

**Comment by Wojtyas** [comment]
Fixed & implemented.
