### ISSUE TITLE
Anticipation bug (Paladin)

### ISSUE THREAD

**Issue by herwineric** [SunwellWoW/Sunwell-TBC-Bugtracker#2130]
Description: 

The talent increases defence limit with 20, but i 

How it works: 

If I am lv 30, normaly i have 150/150 defence, but with the talent I have 150/170, and I can not increase that skill.

How it should work: 

I will automatically get the 20 defence added to my current defence skill.

Source (you should point out proofs of your report, please give us some source): 

I did this ticket for a friend becuse i had a github account. The characters name in-game is "Paj" and he can provide screenshots and more exlenation.

Thank you!

**Comment by Ejit** [comment]
is the same issue with warrior
