### ISSUE TITLE
[Blood elf] Mana Tap is useable on mobs without mana.

### ISSUE THREAD

**Issue by fakelort** [SunwellWoW/Sunwell-TBC-Bugtracker#2131]
Description: 
Mana tap should not be useable on mobs without mana. it's described in #827 which is for some reason closed.

How it works: 
Using Mana tap on creatures without mana works the same as mobs with mana.

How it should work: 
It should generate en exception, invalid target or something similar.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
thank you. I'll reopen previous issue.
