### ISSUE TITLE
[Shaman] Elemental Focus

### ISSUE THREAD

**Issue by TP-Caitlin** [SunwellWoW/Sunwell-TBC-Bugtracker#2137]
Description: 
Element Focus should give 2 stacks of focus casting but only gives one

How it works: 
After critting with a spell you get Focus Casting, reducing your next cast by 40%. This has visually 2 stacks but disables after 1 successful cast.

How it should work: 
It should have 2 stacks

Source (you should point out proofs of your report, please give us some source):

**Comment by NickBrah** [comment]
it is also bugged being consumed by totem damage and lightning shield procs, possibly also flametongue weapon swings

**Comment by FallenAngel80** [comment]
Can confirm this is an issue.

**Comment by Eveer** [comment]
This issue still exists, it also consumes the stacks from searing totem as well as flame shock DOT ticks, as well as flame tongue weapon damage.

**Comment by Cameltotems** [comment]
Can confirm its still an issue, it goes away after 1 instead of 2 spells casts.. this is a pretty big issue since the Elemental Focus talent is a key talent for an elemental shaman, especially when its time to do some raids, i would say game breaking at that point! Please fix this<3

**Comment by Wojtyas** [comment]
Already reported here: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2129
Will be fixed soon.
