### ISSUE TITLE
Dire Maul - East

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#214]
### **TO DO:**

- [x] 1. Pusillin (14354) should be friendly with first meeting. We should talk with him several times and after each of them he should run down into Dire Maul. In the end of his running event we should fight him. For now we can do it w/o tribute.
![image](https://user-images.githubusercontent.com/22802214/44660380-b7cda200-aa07-11e8-82d5-a2d2b34d8992.png)
- [x] 2. Phase Lasher (13196) works completely wrong. It should work similar to Evolving Ectoplasm (3640) from Wailing Caverns. It should changes phases and colours during fight every ~10 seconds. Every of phase should makes him immune to specific school of magic and forces him to cast specific spell.
**EDIT: Looks like they have only increased resistance to school of magic that they should be immune to**
![image](https://user-images.githubusercontent.com/22802214/44661444-ff096200-aa0a-11e8-872e-22c01d34c9d3.png)
- [x] 3. Wildspawn Betrayer has some weird random movements while fightning by melee. He's walking around his melee target.
**Looks like core issue after evade.**
- [x] 4. Wildspawn Hellcaller (11457) should use his Rain of Fire spell (20754) when there are two or more players in spell radius.
- [x] 5. Hydrospawn uses his Summon Hydroling spell (22714) right after pull while he should cast it on 50% hp.
**EDIT: Hydrolings should disappear after boss evades**
- [x] 6. Warpwood Stomper (11465) doesn't use his Lightning Bolt spell (22414) at all. It should be his main focus.
**EDIT: Still doesn't use it, ps. spell requires mana when npc doesn't have it**
- [x] 7. Alzzin the Wildshaper should change his shape more often. Like every ~20 seconds.
- [x] 8. Corrupted Crystal Vine (80191) should be activated.
- [ ] 9. Looks like Alzzin the Wildshaper's Enervate spell (22661) doesn't drain mana from target.
- [x] 10. Two things should happen when boss reaches 50% of his health:
- Cramble Wall gob should activates (perm destroys), which means hidden cave should appear. From cave should run out 10x Alzzin's Minions (11460) and rush to players. If party wipes wall shouldn't repair but minions should still run out from cave on next encounter attempt.
- Whatever creature is still alive in The Shrine of Eldretharr location it should be pulled and start to rush to players as well.
- [x] 11. Pairs of guids: 248377+248376 and 248374+248375 are walking in same pixel while should next to each other.
![image](https://user-images.githubusercontent.com/22802214/45811210-cccae780-bccc-11e8-9d18-bbc94c3b0022.png)

### **DONE:**

- [x] 1. There are literally no single trash creatures in Warpwood Quarter. There should be plenty of:
- Warpwood Treants (11462) who should be present in packs of 2 units with one Warpwood Tangler (11464) and walk as a formation.
- Warpwood Crushers (13021) standing near walls.
- Phase Lashers (13196) randomly spawned on balconies.
- Whip Lashers (13022) who should be present in packs of 7 units in balcony corners. They should walk around balcony in threat-linked groups.
![image](https://user-images.githubusercontent.com/22802214/44661034-b43b1a80-aa09-11e8-8f91-ca01c17488a2.png)
![image](https://user-images.githubusercontent.com/22802214/44661049-bb622880-aa09-11e8-855e-57c01a149b1d.png)
- [x] 2. Wildspawn Shadowstalker (11456) should use his Backstab spell (22416) only when he attacks players from behind.
- [x] 3. Fel Lash (13197) shouldn't use Arcane Explosion spell (22271) when there are no players in spell radius.
- [x] 4. Wildspawn Betrayer doesn't use his two ranged spells: Explosive Shot (7896) and Shadow Shot (18649).
- [x] 5. Wildspawn Betrayer doesn't use his Knockdown spell (11428) when in melee range.
- [x] 6. Wildspawn Felsworn (11455) have some weird random movements between casts.
- [x] 7. Wildspawn Felsworn doesn't use his Shadow Word: Pain (15654) spell.
- [x] 8. Wildspawn Felsworn may interrupt his spell casts by casting Shadow Shield (22417).
- [x] 9. Wildspawn Felsworn doesn't use his Chaotic Focus spell (22418).
- [x] 10. Wildspawn Trickster (11453) should use his two curses spells more often: Curse of Impotence (22371) and Curse of Weakness (12493). He should cast them on various targets.
- [x] 11. Wildspawn Trickster doesn't use his Paralyzing Poison spell (3609).
- [x] 12. Lethtendris (14327) and Pimgib (14349) should walk around bonfire as a formation.
![image](https://user-images.githubusercontent.com/22802214/44662594-8efcdb00-aa0e-11e8-94e1-e9158920985c.png)
- [x] 13. Lethendris doesn't use his Enlarge spell (22710). She should cast it once on Pimgib during fight.
- [x] 14. Wildspawn Imps (13276) should have random movements.
- [x] 15. There shouldn't be perm Hydrolings (14350) creatures.
- [x] 16. Hydrospawn (13280) should use his Submersion spell (22420) more often. 
- [x] 17. Zevrim Thornhoof (11490) should use his both spells on random party players: Intense Pain (22478) and Sacrifice (22651).
- [x] 18. Wildspawn Tricksters, Rogues, Betrayers, Felsworns and Satyrs should have random movements.
- [x] 19. Looks like gob Conservatory Door doesn't exist. Details:
"_269092 (Entry: 176907) - [Conservatory Door X:131.285995 Y:-278.890015 Z:-56.521099 MapId:429]_"
![image](https://user-images.githubusercontent.com/22802214/44664842-a939b780-aa14-11e8-9ed7-a7b3fb1b2e40.png)
- [x] 20. Warpwood Guardians (11461) should walk as a formations in pack of 3 units.
- [x] 21. Whip Lashers (13022) should have random movements.
- [x] 22. Whip Lasher should be able to use Lash of Pain spell (21987) only when melee players from behind.
- [x] 23. Warpwood Guardian's Pummel spell (15615) should be used only when caster's target is casting a spell which may be interrupted.
- [x] 24. There is lack of Warpwood Stompers (11465) who should run with Warpwood Guardians in The Conservatory location
- [x] 25. There shouldn't be any Fel Lashes and Whip Lashers in the top of The Shrine of Eldretharr location.
- [x] 26. When people enter The Shrine of Eldretharr location there should be one Warpwood Crusher on the left and one on the right standing near wall. Also there are should be two additional patrolling corridor down to boss, one on left and one on right as well (cuz its circle lol!).
- [x] 27. There should be 1-2 Death Lashers and Fel Lashes with 2-3 Whip Lashers around them in inner circle just in front of the boss Alzzin the WIldshaper.
- [x] 28. Corrupted Crystal Vine gob is missing. It should stays in inner circle of The Shrine of Eldretharr just next to boss. Alzzin the Wildshaper should move around in the circle and go back to this gob while on his pre-combat movement. For now he stays in place.
![image](https://user-images.githubusercontent.com/22802214/44666545-eef87f00-aa18-11e8-9f47-d6379e3a1a7b.png)
- [x] 29. Alzzin's Minions (11460) shouldn't be perm spawns. They should be summond during boss fight.
- [x] 30. Isalien (16097) boss should be present once summoned during questline. For now she's present entire time.
- [x] 31. Next important missing gob Cramble Wall:
![image](https://user-images.githubusercontent.com/22802214/44667562-69c29980-aa1b-11e8-96bd-0288277fc1e1.png)
- [x] 32. Alzzin the WIldshaper should use his Wild Regeneration spell (7948) only when he has Tree Form buff (22688).
- [x] 33. Enervate spell should be casted on players who have mana.
- [x] 34. Wildspawn Shadowstalker (11456) shouldn't cast his Slowing Poison spell (14897) on target who already have it. He should choose other player in melee range.
- [x] 35. Wildspawn Shadowstalker should use Sneak spell (22766).
- [x] 36. Wildspawn Shadowstalker stops attack when player rotate his character backwards to creature. He stays in position lookin at player but not attacking. It acts like he stops when he's about to use his Backstab spell (22416).
- [x] 37. Phase Lashers (13196) and Fel Lashes (13197) are staying in same place. They should stay next to each other.
![image](https://user-images.githubusercontent.com/22802214/44775181-4b70b100-ab75-11e8-8f78-743c5a7d6c55.png)
- [x] 38. Fel Lash is moving to fast.
- [ ] 39. Wildspawn Betrayer (11454) has no shoot animation at all. Its core bug with shooting spells.
- [x] 40. Wildspawn Betrayer should use his Knockdown spell (11428) more often when in melee range.
- [x] 41. Wildspawn Felsworn (11455) doesn't use his Fear (12542) spell.
- [x] 42. Wildspawn Felsworn shouldn't refresh Shadow Word: Pain spell (15654) on target who already have it. He should choose player w/o it.
- [x] 43. Wildspawn Felsworn should cast his Chaotic Focus spell (22418) on himselft even without a combat and refresh when its gone or dispelled.
- [x] 44. Wildspawn Hellcaller interrupts his Rain of Fire channeling spell by casting next Fireball (15228).
- [x] 45. Similar to Wildspawn Shadowstalker - Wildspawn Trickster (11453) also stops to attack when he's about to use his Paralyzing Poison (3609).
- [x] 46. Wildspawn Rogue (11452) shouldn't use Poison spell (13298).
- [x] 47. Fel Lashes w/o paths should have random movements but in quite bigger range than usual creatures.
- [x] 48. Spawned Hydrolings (14350) should start to attack players immediately once summoned.
- [x] 49. Hydrospawn melee hits for around 300 while he should for 541 - 643.
- [x] 50. After Zevrim Thornhoof is dead npc named Old Ironbark (11491) should die and be replaced with npc Ironbark the Redeemed (14241). Also with that, an yell should appear:
"Ironbark the Redeemed yells: At last... Freed from his cursed grasp!"
For now, Old Ironbark dies and yells when players enter the instance. After he dies Ironbark the Redeemed doesn't appear.
- [x] 51. Ironbark the Redeemed should be friendly npc with dialogue option once spawned:
![image](https://user-images.githubusercontent.com/22802214/44664885-d2f2de80-aa14-11e8-9bc3-0f92d1d92cb1.png)
- [x] 52. Gob Conservatory Door 80204 are open entire time. They be closed till we talk with Ironbark the Redeemed (14241) who is suppose to open them.
- [x] 53. Warpwood Guardian (11461) stops to react and attack  for around 15 seconds when he's about to use Head Crack spell (16172).
- [x] 54. Death Lash (13285) shouldn't use Virulent Poison spell (16427).
- [x] 55. Death Lash should use two spells: Thrash (3391) and Thorns (25640).
- [x] 56. Crumble Wall gob (80250) should be activated.
- [x] 57. Alzzin the Wildshaper shouldn't cast Wither spell (22662) on targets who already have this disease.
- [x] 58. Alzzin the Wildshaper should use his Thorns spell (22128) even when out of combat, and refresh it everytime its gone/dispelled.
- [x] 59. Alzzin the Wildshaper stops react or attack for around 15 seconds when he's about to use Vicious Bite spell (19319).
- [x] 60. Looks like Alzzin the Wildshaper doesn't use his Knock Away spell (10101).
- [x] 61. Alzzin's Minions are hostile to Alzzin the Wildshaper while they should be friendly to each other.
- [x] 62. Alzzin the Wildshaper should have pull yell:
"Alzzin the Wildshaper yells: I will not be lured from this place."
- [x] 63. Thornling (14362) has AI missing.
- [x] 64. This one Fel Lash (13197, guid 248379) should have path changed. He tries to walk on walls.
- [x] 65. When Hydrospawn uses his Massive Geyser spell (22421) he spawns Massive Geyser npc (14122) who does nothing and actually is targetable. Geyser shouldn't be targetable and it should deal frost damage and knockback all players within 10 yards of it.
_"Summon Massive Geyser — Hydrospawn summons a Massive Geyser that inflicts Frost damage to all players within 10 yards and knocks them back."_
**EDIT: When Massive Geyser npc (14122) is spawned it auto attacks players (we can't target it). It shouldn't hit players by melee but cast Water spell (22422) and disappear after that**
- [x] 66. Warpwood Guardians and Warpwood Stompers are run to fast.
- [x] 67. Conservatory Door (80204) shouldn't be "clickable" by players. Only Ironbark the Redeemed should be able to open them.

**Comment by Bezimienny95** [comment]
New bug:
Warpwood Guardians and Stompers in Old Ironbark area should walk a lot slower

**Comment by Kokaina** [comment]
Updated.

**Comment by Kokaina** [comment]
Updated.
