### ISSUE TITLE
Ragefire Chasm Bazzalan

### ISSUE THREAD

**Issue by Thiazole** [SunwellWoW/Sunwell-TBC-Bugtracker#2140]
Description: 
              Anyone can summon Bazzalan, no matter the race, class. He can be summoned multiple times.

How it should work: 

              Only paladins with the quest should be able to summon him.

Source (you should point out proofs of your report, please give us some source): 

               I just finished RFC and we killed him 4 times.

**Comment by sinfer** [comment]
i think you mean Zelemar the Wrathful, not Bazzalan. But yes this is correct otherwise. Were there myself also and we were able to summon him even tho no paladins in our group.
