### ISSUE TITLE
Hunter Pet Happiness x2 rate?

### ISSUE THREAD

**Issue by paegan88** [SunwellWoW/Sunwell-TBC-Bugtracker#2142]
Description: It feels like hunter pets abandon too quickly and the happiness level deteriorates too quickly? Possibly set to 2x along with exp? 

How it works: 
Slower to drain happiness

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Lunasoll** [comment]
I can confirm. Happiness decreases very rapidly. Need to feed pet a lot more often to keep happiness at 125%. 

It decreases even faster when engaged in combat. And always falls below 125% when it dies. Happiness should decrease after a few deaths and if not fed for long time. 

Not after every single death even if constantly being fed.

**Comment by akrom23** [comment]
You're losing happiness points every 10 sec by 1125 points per hour (loyalty level: Rebelious).
Every death, you're losing 333 happiness points. If less than 333 points, your pet is unhappy.
If you tame a new pet, you got a basic 1050 happiness points. It means you're gonna lose your pet in 56 min if not fed.

**Comment by akrom23** [comment]
No response.
