### ISSUE TITLE
Authenticating

### ISSUE THREAD

**Issue by h1n1num1** [SunwellWoW/Sunwell-TBC-Bugtracker#2147]
Description: 
first of all i want to thank you for not giving up and trying hard for this server , weldone <3

but i have a problem here , i have 2 kind of internet, an adsl and a LTE/4g modem. everything is fine with adsl but with 4g modem it stuck on authenticating dont know why but in test server it was fine . what can i do ? do you still have things to do with it to get fixed ? i realy want to play with my 4g modem because it always gives me better ping and latency in game.

thanks again <3

**Comment by Azathothh** [comment]
Please try restarting your game client completely when you switch your internet connection, if it won't help try unlocking port 8087 on your modem. Sounds like it's problem related to your settings.

**Comment by h1n1num1** [comment]
i have done it , still doesnt works

**Comment by h1n1num1** [comment]
the best internet for gaming in my country is that lte modem and all of my friends only have that modem and they couldnt even connect here once to create their characters , im sure atleast 1k ppl having the same problem right now in my country and dont know what to do. and im sure you can fix it and its server side because we can join all other tbc server right now with that internet only here it doesnt work also it was okay here on the test realm. please help us out <3
