### ISSUE TITLE
Dar'khan's Lieutenants

### ISSUE THREAD

**Issue by Kardes1192** [SunwellWoW/Sunwell-TBC-Bugtracker#2148]
Description: 
Very long time for respawn mobs for q.

How it works: 
Long time waiting.

How it should work: 
I think its should be faster

Source (you should point out proofs of your report, please give us some source): 
Im on that quest and waiting 20 minutes for 1 mob

**Comment by Dootz** [comment]
will be reduced to 1 minute from 5

**Comment by Dootz** [comment]
fixed, live on server. Thank you for report.
