### ISSUE TITLE
Guild has been deleted

### ISSUE THREAD

**Issue by anmisyeah** [SunwellWoW/Sunwell-TBC-Bugtracker#2150]
Description: 

I have created a guild and then the server has been disconnected. And now my guild is disappeared. What should i do and where is my money? ))))0))
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dschafar** [comment]
Same happened to us. We've created a guild with a bunch of members. Server crashes - after reconnecting the guild was gone. No Petition in the inventory and the money as well as all the signed people gone.

Would be nice if you guys can restore it the way it was.

**Comment by harsunwell** [comment]
It happened to me too. The difference is, guild members are still there, I as the guild master am the only one who can't see anything about the guild

**Comment by Dschafar** [comment]
Hmm.. Our Guild is completely gone and lost/deleted. Nothing left. As if it never happened.

**Comment by harsunwell** [comment]
My issue is worse because guild members are there and the guild name exists. I wish it was gone totally so i would just make a new one. As guild master I can't leave because there is nothing to leave. I can read the guild chat of others, I can't write anything. Opened a ticket about it :/

**Comment by anmisyeah** [comment]
Im create guild again. And now im Guild Master and now a cant see my own guild and i cant write in guild chat

**Comment by harsunwell** [comment]
Additional info: It is not fixed with this update but i have my hopes :)

**Comment by Dschafar** [comment]
good to know, was on my way to create a new one but i'll wait now..

**Comment by Dschafar** [comment]
good to know, was on my way to create a new one but i'll wait now..

**Comment by harsunwell** [comment]
The issue closed but it is not fixed yet

**Comment by Azathothh** [comment]
It's fixed, but few old guilds have problem which can be fixed in-game by gm. Please open ticket in-game with info about your issue, guild name and nick of player that was guild master
