### ISSUE TITLE
[Quest] [Westfall] Captain Sanders' Hidden Treasure (Part 4)

### ISSUE THREAD

**Issue by Tommimz** [SunwellWoW/Sunwell-TBC-Bugtracker#2151]
Description: 
You can turn in the last part of "Captain Sander's Hidden Treasure" even if you can't carry all four quest rewards, e.g. bags are full.

How it works: 
Have your bags full and turn in the quest.

How it should work: 
As common, you shouldn't be able to turn in quests which reward items when your bags are full or not empty enough.

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?quest=140
![wowscrnshot_120218_134450](https://user-images.githubusercontent.com/45535190/49340107-b4b40480-f63b-11e8-8bbe-1859469bee33.jpg)

As you can see in the logs in green color, I only really received the first two quest rewards, Silver Bar and Shirt, as my bags were full at the time. The latter two, Sash and Booty Bag, "vanished".
Please ignore the two empty spots in my bag. I deleted my conjured water and food afterwards in hopes if I open the chest again I would receive the missing rewards. It didn't work.

**Comment by Foosiq** [comment]
Hello, Is it supposed that this series of Quests leaves Quest Items about Clues from particular Quest in my Bag ?
