### ISSUE TITLE
 Entangling Roots some time is not canceling

### ISSUE THREAD

**Issue by ozymanias** [SunwellWoW/Sunwell-TBC-Bugtracker#2152]
Description: Entangling Roots some time is not canceling by moonfire

How it works: sometime when i cast moonfire on moob and he has debuf from that and next i cast entangling roots then i can spam moonfire and that not canceling roots effects.
i try other speels and for example wrath is canceling roots almost on first shot.

How it should work: any damage should cancel roots 

Source (you should point out proofs of your report, please give us some source): spell descripction

123

**Comment by sinfer** [comment]
isnt it like fear that dmg MAY interrupt the effect?

**Comment by ozymanias** [comment]
yea it is, but with other spells it's more less likely to cancel that and that is strange. its could be mine perspective tho.

**Comment by akrom23** [comment]
@ozymanias Still happens? Need more info/screenshots.

**Comment by akrom23** [comment]
@ozymanias You have to do a specific amount of damage to your target.
Target with 10 level - you need to do 150 single damage.
Target with 50  level - you need to do 1150 single damage.
Target with 70 level - you need to do 1650 single damage.
