### ISSUE TITLE
(The Barrens - NPC) Mad Magglish

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#2153]
Description: 
Mad Magglish is not spawned inside the cavern Wailing Times (Not in the instance, but outside)

How it works: 
There is no recorded spawn of Mad Magglish

How it should work: 
Mad Magglish should be spawned at 46 , 35  near a campfire

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?npc=3655
https://www.wowhead.com/npc=3655/mad-magglish#comments
https://www.youtube.com/watch?v=VMj4GF9f7U0

**Comment by Dootz** [comment]
fixed, live on server. Thank you for report.
