### ISSUE TITLE
[Quest] [Westfall] Kalven's Tower

### ISSUE THREAD

**Issue by tanksterr** [SunwellWoW/Sunwell-TBC-Bugtracker#2155]
Description:  Even with the defias tower key, the chest containing kalvens journal is still unable to be opened.

How it works: Even with the defias tower key the duskwook chest is still unable to be opened

How it should work: Having the defias tower key should allow you to open the duskwood chest

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=Ltebm06-x_8

**Comment by Dootz** [comment]
temp fix will be put in place. You'll be able to open chest without key, but since key is one of quest objectives it is required to get it aswell.

**Comment by Dootz** [comment]
temp fix implemented on server. Thank you for report
