### ISSUE TITLE
Shaman Earth Shock not interrupting Spells

### ISSUE THREAD

**Issue by Dschafar** [SunwellWoW/Sunwell-TBC-Bugtracker#2156]
Description: 
Casting Earthshock on Bristleback Thornweaver

How it works: 
The Thornweaver is casting Roots and the Geomants Flamestrike; used Earthshock to interrupt them but it is not working.
It only works when they use offensive/dmg spells like fireball, those can be interrupted, but not cc/aoe dmg spells

How it should work: 
It should interrupt them and forbid them from using magic of this kind for 2 seconds (like the tooltip says)

Source (you should point out proofs of your report, please give us some source): 
look into the tooltip of earthshock

**Comment by FrauHolle86** [comment]
still not working properly
