### ISSUE TITLE
Harvest Golems in Moonbrook drop Khadgar's Whisker

### ISSUE THREAD

**Issue by Yavannie** [SunwellWoW/Sunwell-TBC-Bugtracker#2157]
Description: Harvest Golems near Moonbrook, Westfall drop the high level herb Khadgar's Whisker.

How it works: As above. Out of four killed, all four dropped Khadgar's Whisker.

How it should work: I think these are meant to be Hops, which share the same icon as Khadgar's Whisker. I was killing the golems to farm Hops, but none have dropped.

Source (you should point out proofs of your report, please give us some source): Character Istapp on Alliance side - the herbs are in my bag.
![wowscrnshot_120218_154132](https://user-images.githubusercontent.com/45537101/49341090-e54e6b00-f648-11e8-94d9-48438139ba75.jpg)

**Comment by Dootz** [comment]
fixed, live on server. Thank you for report.
