### ISSUE TITLE
Quest bug [What we don't know...] 

### ISSUE THREAD

**Issue by Jonatantwn** [SunwellWoW/Sunwell-TBC-Bugtracker#2158]
Description: 
The NPC does not give you the needed buff to interact with Blood Elf NPC.

How it works: 
Questgiver is supposed to give you a buff, he doesnt.

How it should work: 
He should give you a buff.

Source (you should point out proofs of your report, please give us some source): 
Me and several other players had the same issue, the NPC does the "cast" emote, but nothing happens

**Comment by Jugixor** [comment]
This is still not working. Exarch Admetius does not give the buff required to speak to Captured Sunhawk Agent

**Comment by vitor210** [comment]
Wanna add that the NPC that should give you the debuff allows you to complete the mission but doesn't give any follow up which proves that he doesn't in fact completes the quest for you

**Comment by Tundra28** [comment]
PLz FIX this! This gives a really nice reward for starters on alliance side!

**Comment by Dootz** [comment]
will be fixed today with next restart
