### ISSUE TITLE
[Quest-Vanilla] Book of the Ancients 6027

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#2160]
Description: 

How it works: 
Once clicking on the Serpent Statue, nothing happens

How it should work: 
https://www.youtube.com/watch?v=65nys_0MQ-I

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?quest=6027

**Comment by ninc** [comment]
Same issue. No mob spawn when clicking.
![wowscrnshot_120218_180950](https://user-images.githubusercontent.com/657190/49343290-c068f080-f666-11e8-88be-acdf472887db.jpg)
![wowscrnshot_120218_180953](https://user-images.githubusercontent.com/657190/49343291-c068f080-f666-11e8-9d5b-0dc8ece5841b.jpg)
