### ISSUE TITLE
Quest: Compendium of the Fallen - unobtainable

### ISSUE THREAD

**Issue by Xymos** [SunwellWoW/Sunwell-TBC-Bugtracker#2161]
Description: 
The quest http://db.hellfire-tbc.com/?quest=1049 is unobtainable, because Sage Truthseeker doesn't give it to you

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Xymos** [comment]
Still not working.
I deleted cache, no changes.

**Comment by Dootz** [comment]
Requirement: Level 28

**Comment by TheGreyMouser** [comment]
/quest=1049/compendium-of-the-fallen
Can obtain quest, but cannot 'loot' quest item (book) in book shelf.
