### ISSUE TITLE
Cant feed my pet

### ISSUE THREAD

**Issue by Jekenius** [SunwellWoW/Sunwell-TBC-Bugtracker#2162]
Description: My boar dont want to eat bread and fruit, but he should like that.

How it works: Pet dont like meals it should like.

How it should work: Pet should like these meals.

Source (you should point out proofs of your report, please give us some source): Tried both apples and bread in my bags, didnt check other types of food.
![wowscrnshot_120218_220729](https://user-images.githubusercontent.com/45003723/49341484-8d335b00-f680-11e8-8161-3f292c186965.jpg)

**Comment by ujellyx** [comment]
I also tamed a boar, but it works fine. He eats bread, fruits (apples) etc.

**Comment by akrom23** [comment]
Cannot reproduce.
