### ISSUE TITLE
Quest:Return to Krog

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#2163]
Description: 
This Q is missing from the game, it should be a followup of quest The Black Shield

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by NickBrah** [comment]
it is not missing, it is available from TB npc = "Mosarn"

the quest is a follow-on from the acidic venom sacs

[proof here](https://i.imgur.com/tos6COw.jpg)

**Comment by Dootz** [comment]
can confirm that it's not correct right now. it should be available after https://www.wowhead.com/quest=1276/deprecated-the-black-shield . Thank you for report.

**Comment by Dootz** [comment]
fixed, live on server. Thank you for report.
