### ISSUE TITLE
Improved Blessing of Might providing improper Attack Power

### ISSUE THREAD

**Issue by Hapsterchap** [SunwellWoW/Sunwell-TBC-Bugtracker#2169]
Description: 
Retribution Talent 'Improved Blessing of Might' doesn't seem to provide an increase to Attack Power like it says it does in the tooltip.

How it works: 
Taking the talent doesn't increase the Attack Power bonus of the ability Blessing of Might. (It's still a 20 AP bonus)

How it should work: 
The Talent should provide a 4% increase to Attack Power per rank. Therefore, with rank 1, I should receive a 0.8% increase to my Rank 1 Blessing of Might (4% of 20 = 0.8%). I asked Dredd if the final sum of calculations like these are rounded down or up and neither of us knew. So reporting it anyway in case it's a bug with either problem (calculations or talent function).

Source (you should point out proofs of your report, please give us some source): 
Talent - https://i.imgur.com/fRDFE4j.png
Buff - https://i.imgur.com/oYGNHtO.png
Stats - https://i.imgur.com/AXYasBY.png

**Comment by Hapsterchap** [comment]
Just got Rank 2 Improved Blessing of Might (which provides a 1.6 AP bonus to Blessing of Might at Rank 1) and it does seem the the percentage buff sum scales down, as I have only 1 AP bonus to my BoM. Might be intended, but I did notice the tooltip for the buff doesn't note that increase in AP, but the stat panel and spell toolltip do.

**Comment by Azathothh** [comment]
4% from 20AP = 0,8AP  - it's rounded down , so you don't see any difference on rank 1 BoM with 1/5 imp BoM
Tooltips for the buffs are not updated with talents and it was same on retail - it's just how client is made.
