### ISSUE TITLE
Guild has been deleted

### ISSUE THREAD

**Issue by Dschafar** [SunwellWoW/Sunwell-TBC-Bugtracker#2170]
Description: 
We've created a guild with a bunch of members. Server crashes - after reconnecting the guild was gone. No Petition in the inventory and the money as well as all the signed people gone.

How it works: 

How it should work: 
Would be nice if you guys can restore it the way it was.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2150
