### ISSUE TITLE
Neutral mobs

### ISSUE THREAD

**Issue by Pizzle93** [SunwellWoW/Sunwell-TBC-Bugtracker#218]
Decription: 
Neutral mobs attack when you right click even if you don't attack (out of melee range)

How it works: 
Neutral mobs attack when you right click even if you don't attack (out of melee range)

How it should work: 
Neutral mobs should only attack when you have attacked them

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Have you tried different neutral mobs? Which one attacked you?
I've found only Mana Wyrms working this way.

**Comment by Pizzle93** [comment]
It was the level 1-2 wolves around Northshire Abbey. Was a while ago so will recheck when home from work

Sent from my iPhone

On 6 Sep 2018, at 15:30, Azathothh <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried different neutral mobs? Which one attacked you?
I've found only Mana Wyrms working this way.

**Comment by Azathothh** [comment]
Yep, they still attack when autoattack is turned on
Young Wolf id: 299
Timber Wolf id: 69
(Kobold Vermin and Kobold Worker in same area are fine)
