### ISSUE TITLE
Moonglade bubbly fissures not working

### ISSUE THREAD

**Issue by 0vertime** [SunwellWoW/Sunwell-TBC-Bugtracker#2182]
The bubbly fissures in the Moonglade lake are not giving breath back.

**Comment by Truckanuck** [comment]
The fissures in Desolace don't work either.  Breath should be restored and timer should not show while swimming above them

**Comment by Trentone** [comment]
Compiled list of Bubbly-Fissure-related fixes.
Check if you still need certain parts of fixes before applying.

[17823.txt](https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/files/2935794/17823.txt)
[9856.txt](https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/files/2935795/9856.txt)
[9899.txt](https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/files/2935796/9899.txt)

Object id 177524 was confirmed to give air by information gathered from WoWHead comments. Unfortunately, can't find those now, but i remember for certain that there were at least 2 cases described in comments which said coordinates of Bubbly Fissures that gave air, and at the server the object at these coordinates is 177524.
