### ISSUE TITLE
pet follow

### ISSUE THREAD

**Issue by fetjke** [SunwellWoW/Sunwell-TBC-Bugtracker#2183]
Description: 
warclock's pet (imp so far) doesnt follow properly

How it works: 
imp just stops after combat

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Do you have any video? Just seen plenty of locks with their Imps that follow their master normally :o

**Comment by fetjke** [comment]
dont have any video. ppl spam in global about warlock's imp. after attacking he doesnt follow the master a dissmising

**Comment by Merdir123** [comment]
yeah, it happens to me too
