### ISSUE TITLE
Monsters in Ashenvale dropping way too high level gear

### ISSUE THREAD

**Issue by samimie** [SunwellWoW/Sunwell-TBC-Bugtracker#2184]
Description: 
While questing in Ashenvale the lvl 20 nagas at zoram strand dropped me a lvl 34 mail headpiece. Likewise the lvl 24-26 thistlefur avengers and shamans in thistlefur village dropped a lvl 36 rare leather chestpiece.

How it works: 
lvl 20 monsters are dropping lvl 30 gear.

How it should work: 
They shouldnt be dropping gear this high level.

Source (you should point out proofs of your report, please give us some source): 
![2018-12-02 1](https://user-images.githubusercontent.com/27886837/49342499-d83f7500-f664-11e8-9e32-178e30a68991.png)
![2018-12-02](https://user-images.githubusercontent.com/27886837/49342500-d83f7500-f664-11e8-8543-f55372e71649.png)

**Comment by Dootz** [comment]
fixed, thank you for report
