### ISSUE TITLE
[Vanilla-Quest Giver] Private Thorsen

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#2185]
Description: 

How it works: 
Private Thorsen has question mark above him, when he's inside the camp, should only offer it when patrolling.

How it should work: 
Private Thorsen should not show question mark above him when inside of the camp according to https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/155
He should start his patrolling RP every 10-15 minuts.

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?quest=215

**Comment by ninc** [comment]
I can see the same issue.

![wowscrnshot_120218_122031](https://user-images.githubusercontent.com/657190/49343296-dd9dbf00-f666-11e8-9ca9-a00868712965.jpg)

**Comment by ZackForester** [comment]
Encountered this same behavior today when trying to turn in the quest Supplies to Private Thorsen. With quest in log and quest item in bag, NPC has no quest dialogue options.

![image](https://user-images.githubusercontent.com/3096422/49365504-05b40f00-f6b5-11e8-8e0d-0a45e35bac8f.png)

**Comment by ghost** [comment]
Private Thorsen seems not to start his patrolling RP script.

**Comment by ghost** [comment]
issue persists

**Comment by ghost** [comment]
cannot deliver or start quests that he gives
