### ISSUE TITLE
Scalding Elemental immun

### ISSUE THREAD

**Issue by Dschafar** [SunwellWoW/Sunwell-TBC-Bugtracker#2187]
Description: 
Scalding (water) Elemental in Thousand Needles stun & slow immun.

How it works: 
Earthbindtotem does not work, War Stomp Tauren Racial does not work.

How it should work: 
Should both be working on them.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dschafar** [comment]
EDIT: All Elements (Air etc.) are immun to Earthbindtotem-slow and War Stomp.

**Comment by Wojtyas** [comment]
Fixed & implemented.
