### ISSUE TITLE
Powering Our Defenses Quest

### ISSUE THREAD

**Issue by Hapsterchap** [SunwellWoW/Sunwell-TBC-Bugtracker#2188]
Description: 
Quest doesn't function as intended.

How it works: 
You place down the Infused Crystal item, and the mobs spawn, but they just stand where they spawn without moving to attack the crystal.

How it should work: 
The mobs should spawn and move to attack the Infused Crystal, or aggroing on the player if they attack the mobs.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120218_172032](https://user-images.githubusercontent.com/45538611/49342775-4e3cdf80-f657-11e8-858e-70243efa872a.jpg)

**Comment by ZuyPan** [comment]
Can't get Infused Crystal placed no matter where I am around the runestone.
I waited there for a while and it seems no one can place it correctly.
![unnamed](https://user-images.githubusercontent.com/45574338/49397401-c086f000-f73b-11e8-8511-99352f0ea5ca.jpg)
