### ISSUE TITLE
Quest rewards

### ISSUE THREAD

**Issue by Bakster15** [SunwellWoW/Sunwell-TBC-Bugtracker#2190]
Description: 
Quest rewards gets deleted if your bags are full when you complete them.

How it works: 

How it should work: 
It should deny you to complete the quest untill you have free bag space.

Source (you should point out proofs of your report, please give us some source): 
Any quest completed with full bags should show the same result.

**Comment by Dootz** [comment]
Hi, thank you for report. Because it was already reported I'll close this ticket.
