### ISSUE TITLE
Shaman Clearcasting

### ISSUE THREAD

**Issue by smkrus** [SunwellWoW/Sunwell-TBC-Bugtracker#2191]
Description: 
Shaman Clearcasting consumed by non spellcasts

How it works: 
Shaman Clearcasting consumed by searing totem bolts / lightning shield damage / maybe other things

How it should work: 
Shaman Clearcasting should be consumed on damage spell casts

Source (you should point out proofs of your report, please give us some source): 
n/a

**Comment by Tundra28** [comment]
Not only that, but also not 2 charges.. only 1 charge

**Comment by Gintonicfin** [comment]
Searing totem and melee hits eat up charges
