### ISSUE TITLE
[Warlock] Shadow Embrace no spell timer

### ISSUE THREAD

**Issue by ninc** [SunwellWoW/Sunwell-TBC-Bugtracker#2192]
Description: 

How it works: 
When a warlock puts a dot on me Shadow Embrace is applied. However it stays on after all the dots have expired without any timer.

How it should work: 
It should expire with the dots.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120218_105813](https://user-images.githubusercontent.com/657190/49343239-ea6de300-f665-11e8-96d7-56d55385daf2.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented. It remain on target till spell which applied this debuff is still on.
It will vanish when Corruption, Curse of Agony, Siphon Life or Seed of Corruption fades.
