### ISSUE TITLE
Druid Hots cant stack

### ISSUE THREAD

**Issue by absdr** [SunwellWoW/Sunwell-TBC-Bugtracker#2193]
Description: 
Driuds should be able to stack Hots on one Target, like 5 druids = 5 lifebloom on one target.

How it works: 
Driuds cant stack the Hots on one Target

How it should work: 
One target can have all hots from every Druid, not only from one.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented.
