### ISSUE TITLE
Mail from AH doesnt spawn the icon next to minimap

### ISSUE THREAD

**Issue by sinfer** [SunwellWoW/Sunwell-TBC-Bugtracker#2194]
Description: Mail from AH doesnt spawn the icon next to minimap

How it works: Mail from AH is "read" even tho it is not

How it should work: Mail should stay unread so long until you read it. And the icon should spawn next to minimap. Picture below was taken before i read those mails of course.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120218_200824](https://user-images.githubusercontent.com/45524181/49343245-56ece000-f66e-11e8-98fb-576ade65b118.jpg)

**Comment by siof** [comment]
#2134
