### ISSUE TITLE
Herb Spawn rates are too low!

### ISSUE THREAD

**Issue by Tundra28** [SunwellWoW/Sunwell-TBC-Bugtracker#2197]
Description: 
Herb Spawn rate should be all around azure mist and blood mist isle.

How it works: 
Spawn of peacebloom, silverleaf, earthroot

How it should work: 
Spawn faster

Source (you should point out proofs of your report, please give us some source): 
Not a single silver leaft colected , at lvl 19 now

**Comment by molvanja** [comment]
I think not only respawn rates, but also spawn frequency. I ran all the way ON FOOT from The Sepulcher to Thunder Bluff to learn staves, WITH the intention to collect herbs on the way, and all i got was ONE SINGLE Silverleaf.

**Comment by SunwellTracker** [comment]
Fixed.

**Comment by nimeral** [comment]
My impression is, it's _not_ fixed. Mining nodes seem fine but not herbs. Someone in global reported having 15 herbalism and 225 mining. I see veins more often than herbs while tracking herbs.
