### ISSUE TITLE
Cube without texture in wetlands

### ISSUE THREAD

**Issue by ninc** [SunwellWoW/Sunwell-TBC-Bugtracker#2199]
Description: 

How it works: 
A cube with no texture on the road in wetlands.

How it should work: 
Removed or should have a texture.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120218_091101](https://user-images.githubusercontent.com/657190/49343330-4127ec80-f667-11e8-8c48-4ec875629324.jpg)

**Comment by 0vertime** [comment]
Saw few of these in Arathi Basin.

**Comment by Dootz** [comment]
Hi, this issue was already reported. I'll close this report.
