### ISSUE TITLE
[Blood Elf][Quest]The Shrine of Dath'Remar

### ISSUE THREAD

**Issue by dredd-sunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#22]
Decription:  Quest 8345 should be available at the same time with 8330 (same requirements).

**Comment by Kokaina** [comment]
Fixed and implemented.

**Comment by cs-daniel** [comment]
Couldn't accept neither of these quests as a blood elf.

**Comment by Dootz** [comment]
ok, i'll check it. thank for report.

**Comment by qtong** [comment]
Still wasnt unable to pick up the quest until lvl 6. It should be able to be picked up at lvl 2 without any preq

**Comment by Wojtyas** [comment]
Level required changed to 2 properly but tt looks like q:8330 still counts as prequest for q:8345.
