### ISSUE TITLE
Murkblood Invaders in Nagrand not patrolling

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#220]
Description: They remain stationary

How it works: Two sets of them are spawning, one each at 38,27 and 32,58

How it should work: There should be one set alive at a time, and they should patrol around the zone on the roads as the video below shows.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/tt7ONVVg9rw?t=17s

**Comment by Lonoss** [comment]
> There should be one set alive at a time

http://db.hellfire-tbc.com/?npc=18238
https://db.excalibur.ws/?npc=18238
6 NPC total

Comment from wowhead 3.0.8 patch, but I don't think it has been changed:
They are found just outside the Horde and Alliance' respective towns in Nagrand, and drop the Murkblood Invasion Plans, which start up a quest chain for Mag'har/Kurenai.

**Comment by notsofamous** [comment]
They now patrol but only 1 in each pack does it properly. The other 2 keep running away for a few yards before walking back to their buddy

https://i.gyazo.com/a266a80d5358dd550fcf386c14238cae.png
https://i.gyazo.com/9d08009c5633d7927b2326ad7f6c7e1b.png
https://i.gyazo.com/4a79a0302ab6a1c1ccc5ed336e0384f7.png

**Comment by Kokaina** [comment]
Fixed.

**Comment by notsofamous** [comment]
They are patrolling now but they are very... intimate...

![Image](https://i.gyazo.com/832b11ba09155601b61aa22e81d9418f.png)
