### ISSUE TITLE
[Shaman] Shamanistic Focus + Totem 

### ISSUE THREAD

**Issue by RimWin** [SunwellWoW/Sunwell-TBC-Bugtracker#2204]
Description: When i attack a mob with all of my force and i even crit once in my life + get the buff {Shamanistic Focus), right before i can hit my Earthshock with 60% reduced mana cost, my Searing Totem removes the buff

How it works: Searing Totem removes Shamanistic Focus when it hit

How it should work: Searing Totem shouldnt remove Shamanistic Focus

Source (you should point out proofs of your report, please give us some source): Shamanistic Focus says reduces the mana cost of your next Shock spell by 60%

**Comment by blackwife** [comment]
Should add that this bug also affects Elemental talent tree procs like the Clearcasting buff.

**Comment by strictmage** [comment]
There is a bug that uses the proc of shamantic focus when using a non shock spell (heal) which should not work that way. The proc should be only used when you cast a "shock", not a healing wave.

**Comment by AndrewScottJester** [comment]
I'm almost positive it is only searing totem that wastes the proc, i stopped using searing and it is not happening anymore

**Comment by Wojtyas** [comment]
Reported here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2048
