### ISSUE TITLE
Guild Master kicked after restart

### ISSUE THREAD

**Issue by pickamachuu** [SunwellWoW/Sunwell-TBC-Bugtracker#2205]
Description: 
Prior to most recent restart we had guild created with members. Upon server restarting Guild Master was kicked from guild and now we have no Guild Master rank or ability to promote someone to the rank.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Ogisa22** [comment]
Same happened to me

**Comment by Dennyks** [comment]
Yeah same happened to me, just got kicked out of my guild and I was the guild master. The guild still exists without a guild master now >.< PLEASE HELP

**Comment by lohkiiodin** [comment]
Same thing here, kicked from the guild I created. We still have officers and was able to be invited back, but no GM

**Comment by anmisyeah** [comment]
Yeah same happend to me, just got kicked out of my guild and I was the guild master. The guild still exists without a guild master now.

**Comment by Ogisa22** [comment]
And other people got kicked too not only GM

**Comment by Dennyks** [comment]
Update: (After restart and after getting kicked from original guild as GM) I went on a different character  to make another guild, made the guild then made sure I was alone in the guild and then logged out and back in. I was kicked from the guild just from relogging and when I tried to remake the guild with the same name it says "There's already a guild with that name" even tho I made sure to be the only one in the guild before I relogged.

**Comment by jayeb50** [comment]
Same here.  Opened ticket in game as well.  Was able to be reinvited to the guild by other members, however nobody is GM in my guild now.

Almost 24 hours later, when will this be fixed?  Guild is sitting with no GM and not fully set up. #
