### ISSUE TITLE
Loot System

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#2206]
Description: 
Party doing quest....If one member of the party leaves after looting a quest item from a mob and others didnt manage to loot that before he left, item is no longer available for looting

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
I think it's fine. The mob was killed when you were in group with the killer. Killer left the group, so you are not eligible to loot that.
You are not the killer of this mob.
You are not in the killer's group (when you loot corpse).

**Comment by xethra89** [comment]
@akrom23 that's not how it's supposed to work. If you are eligible to loot, regardless of whether the person leaves or not, you should be able to loot the item still. 

Additionally (probably should be a separate bug report), if someone tags a mob that is needed for a quest item drop (loot x mob's head) before you are in a party, then you get invited, the mob still is gray to you and you are unable to loot the quest item. On the flip side, for kill quests, if you do the same thing... tag before grouped, then group up, the person who joins the group DOES get credit for kill quests. It's only with quest drop items.

**Comment by akrom23** [comment]
Okay.
