### ISSUE TITLE
Druid Cat From

### ISSUE THREAD

**Issue by Rebornerka** [SunwellWoW/Sunwell-TBC-Bugtracker#2208]
Description: 
Spells: Claw and Ferocious Bite

How it works: 
Claw when dodge or parry gain (40energy +return around 20-30)
Ferocious Bite (return 35 energy after cast)

How it should work: 
Claw must not return 40 energy.
Ferocious bite must not return 35 energy.

Source (you should point out proofs of your report, please give us some source):

**Comment by Kittykatreporter** [comment]
Can you provide ANY source that it should work that way? Iirc all energy-based abilities had a 80%(?) refund on miss in late tbc.  I will try to find info about it from some trustworthy source.

edit: Actually, after thinking it through, im not so sure about FB, but still claw/shred/rake should work that way i think, similar like for rogues with exception to finishers cuz they have talent for that

**Comment by Rebornerka** [comment]
maybe not,but i guess when your 40 energycost ability parry,u gain 70
energy it's not ok

вт, 4 дек. 2018 г. в 19:06, whiskas <notifications@github.com>:

**Comment by akrom23** [comment]
Claw has special attribute, so it should refund energy on dodge (80%) and parry (20%).
Ferocious Bite works fine - does not refund energy on dodge/parry.
