### ISSUE TITLE
Got kicked out of guild and I was the guild master. PLEASE HELP

### ISSUE THREAD

**Issue by Dennyks** [SunwellWoW/Sunwell-TBC-Bugtracker#2209]
Description: Made a new guild before the server restart and I was just finished setting up all the roles and guild information. I invited a lot people and as the server restart I logged back in after to find out I was kicked from the guild, I asked for someone in the guild to invite me and now the guild exists without a guild master. HELP.
guild name: "JFK didnt LoS"
Character name which was the GM: Dennyks

How it works: GM KICKED OUT OF GUILD BUT GUILD STILL EXISTS

How it should work: GM SHOULD NOT BE KICKED AND HOW CAN A GUILD EXIST WITHOUT A GM

Source (you should point out proofs of your report, please give us some source): 
"JFK didnt LoS" has no guild master currently >.<

**Comment by Dootz** [comment]
Hi,
this issue was already reported here:
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2205
