### ISSUE TITLE
Changing target while shooting wand doesn't switch attacking target

### ISSUE THREAD

**Issue by tacotal** [SunwellWoW/Sunwell-TBC-Bugtracker#2211]
Description: 
While attacking with my wand, I noticed that when I target A and start shooting my wand, when I target B, my wand keeps shooting on target A.

How it works: 
While attacking with my wand, I noticed that when I target A and start shooting my wand, when I target B, my wand keeps shooting on target A.

How it should work: 
When you change target, your wand should change target as well (I target A, shoot it, then target B, my wand should be shooting target B).

Source (you should point out proofs of your report, please give us some source):

**Comment by grand-lotus-iroh** [comment]
+1

came here to report the exact same thing. please make this ultra super high priority fix. i should be able to TAB or left click mob while wanding another mob to keep wanding it down.

**Comment by grand-lotus-iroh** [comment]
gentle bump / nudge - you tink this will be fixed soon? it actually effects gameplay HUGE...

**Comment by grand-lotus-iroh** [comment]
gentle bump / nudge
