### ISSUE TITLE
[spell] [warrior] [mob] Heroic Strike - mob INVALID TARGET (picture)

### ISSUE THREAD

**Issue by sicknot1** [SunwellWoW/Sunwell-TBC-Bugtracker#2212]
Description: can't use heroic strike mob =prowler is invalid target

How it works:   can't use heroic strike mob =prowler is invalid target

How it should work: Should able to use Heroic Strike

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120218_161710](https://user-images.githubusercontent.com/35937937/49343784-13827980-f64e-11e8-9301-25df9e2ba42e.jpg)
![wowscrnshot_120218_161724](https://user-images.githubusercontent.com/35937937/49343785-13827980-f64e-11e8-8147-360a60f35a30.jpg)

**Comment by akrom23** [comment]
Cannot reproduce it.
