### ISSUE TITLE
Missing Spell Batching: damage and healing data processment

### ISSUE THREAD

**Issue by ga-felix** [SunwellWoW/Sunwell-TBC-Bugtracker#2214]
Description: There's a core mechanic system missing on the server.

**How it works**: All damage and healing is counted instantly.

**How it should work**: **All damage and healing should be processed in batches. This would, for instance, prevent lethal damage sometimes.** Let me give a full example:

If a 2 % health character is with Rejuvenation effect and Bleeding, the healing and damage would be processed at the same batch, nullifying each other and saving the character from death. (For instance, if Rejuvenation heals 200 and Bleeding deals 200 damage, **the server should read: +200 health points - 200 health points = 0 => The character HP would stay 2%**).

In the current processment system, **if Rejuvenation procs first, the character would survive, however if Bleeding procs first, the character would die**.

**Source** (you should point out proofs of your report, please give us some source): 

Actually, there's no printscreen or video that could proof this system is missing, however If you compare retail gameplay on TBC and Sunwell server you will see the difference.

There's a video explaining what this system is and how It works: https://www.youtube.com/watch?v=3xRWmNA8QLY

**Note**: This system is very important to PvP balancement and even PvE wipe situations so keep in mind: this is a real problem that should be fixed.

All older expansions had this system called "Spell Batching".

**Comment by Mewmewww** [comment]
you'll only find spell queue on Netherwing. Sunwell team doesn't want to implement it.

**Comment by Wojtyas** [comment]
We won't implement that.
