### ISSUE TITLE
Pet "reaction" to commands not working properly

### ISSUE THREAD

**Issue by Dollparts** [SunwellWoW/Sunwell-TBC-Bugtracker#2215]
Description: Pet currently adheres to global cooldown.

How it works: Pet "passive" "attack" etc commands trigger a pet global cooldown.. Making it much longer to switch targets with pets than it should be.
When attacking a target with pet, people use a macro to switch it's target, usually a button you press twice quickly to make the pet passive then commanding to attack a new target taking around 0.2 seconds..

Currently pet's command global cooldown stops this,. takes 2 seconds to change target (Which is ridiculous)

How it should work: Pet should not have a global cooldown on targetting functions or "stance" changing (passive, attack, aggressive, defensive).

Source (you should point out proofs of your report, please give us some source): 

Literally every hunter video ever made is source material for this... pick one.

**Comment by Dollparts** [comment]
Still not fixed.

**Comment by akrom23** [comment]
@Dollparts Show some proofs, because I don't know what are talking about.
Also, show me the macro.

**Comment by akrom23** [comment]
No response.
