### ISSUE TITLE
[NPC] Sognar Cliffbeard

### ISSUE THREAD

**Issue by TheRealestMcCoy** [SunwellWoW/Sunwell-TBC-Bugtracker#2216]
Description: 
He is not in Ironforge.
I have ran all around Military Ward doing /target Sognar Cliffbeard and yet to target him.
How it works: 
Could not locate

How it should work: 
He should be walking around the Military Ward in Ironforge.

Source (you should point out proofs of your report, please give us some source): 
https://tbc-twinhead.twinstar.cz/?npc=5124
http://wowwiki.wikia.com/wiki/Sognar_Cliffbeard
https://www.wowhead.com/npc=5124/sognar-cliffbeard

**Comment by Dootz** [comment]
He should be in correct spot right now
