### ISSUE TITLE
Disenchanting & full inventory

### ISSUE THREAD

**Issue by tacotal** [SunwellWoW/Sunwell-TBC-Bugtracker#2217]
Description: 
I disenchanted an item and my inventory was full. I canceled the loot window and my item was gone and I didn't get the dust.

How it works: 
When you disenchant an item and your inventory is full, you lose the item and you don't get the dust.

How it should work: 
When you disenchant an item and your inventory is full, you should keep the item and not get the dust after canceling the loot window.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@tacotal 
https://wow.gamepedia.com/Disenchanting

> Do not disenchant from a full inventory! The disenchanted item will still occupy a space and you won't be able to pick up any materials unless you already have a partial stack.

**Comment by tacotal** [comment]
> @akrom23
> https://wow.gamepedia.com/Disenchanting
> 
> > Do not disenchant from a full inventory! The disenchanted item will still occupy a space and you won't be able to pick up any materials unless you already have a partial stack.

After discussing with my friends, I believe I was wrong on how it should be. However, we still believe the way it works on Nightbane is not quite right. Here is a thread on the official wow forums about it being a bug: https://us.battle.net/forums/en/wow/topic/2456907538

Now I'm not 100% sure as to what the official system should be. However, I believe it would be one of the two options below:
1. When trying to close the window, you should be prevented to do so and you should get a message saying "Inventory is full" (this is how it is on most private servers I've been on, but that does not mean it's the right way).
2. You should be able to close the window and destroy the item, but the mats you should've received are sent by mail.

Regarding the post you linked, while it indeed somewhat contradicts what I said in the first place, it does not say that both the item and the mats will disappear if you close the loot window and therefore, does not invalidate the 2 options I've listed in this reply.

I can't guarantee that I have the correct answer, because I thought I knew how it was on retail and obviously I wasn't quite right. However, everyone I've talked to says the way it is on Nightbane is not exactly how it should be. I think it'd be interesting to have other players' opinion on the issue.

Hopefully this reply helps!

**Comment by akrom23** [comment]
It does.

**Comment by akrom23** [comment]
https://github.com/TrinityCore/TrinityCore/issues/12116

> On retail the disenchanted item disappears.

**Comment by akrom23** [comment]
No response. Closed.
