### ISSUE TITLE
[Priest] downranked SWP gain full spellpower coefficient

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#222]
Decription: bonus spell damage applying equally to all SWP ranks

How it works: With 1060 spell power (no talents), rank 1 SWP deals 201 every 3 seconds (5 without SP) while rank 10 deals 402 every 3 seconds (206 without SP)

How it should work: Given that rank 1 SWP such a low level spell we can use the formula in the link below to see it should be dealing ~57 damage every 3 seconds

Source (you should point out proofs of your report, please give us some source): 
http://wow.allakhazam.com/wiki/spell_coefficient_(wow)

**Comment by akrom23** [comment]
Works good for me.
@babno Could you test it again?

**Comment by babno** [comment]
https://i.imgur.com/qeATG5Y.png The first tic is from rank 10 SWP which without SP does 206 a tic and with SP does 328, a gain of 122. The 2nd and 3rd tics are from rank 1 SWP which without SP does 5 a tic and with SP does 127, a gain of 122. I tested this on 11/27 at 10:03am EST time.

**Comment by akrom23** [comment]
70 lvl preist vs 54 lvl mob:
https://imgur.com/a/r3N6Unv

**Comment by babno** [comment]
That's not related to the issue. I'm talking about rank 1 SWP that without spell power does 5 damage gaining a full measure of spell power when it should not.

**Comment by akrom23** [comment]
I checked every rank with and w/o spell power - works fine.
Could you record a video?

**Comment by babno** [comment]
My recording software isn't working for some reason. Can you provide a screen shot of a rank 1 SWP doing the correct damage while having significant sp? https://i.imgur.com/f59sBrw.jpg

**Comment by akrom23** [comment]
Don't look at tooltip - it't not scaled with your spell power.

**Comment by babno** [comment]
The tooltip was just to prove it was indeed rank 1 SWP that I used and is doing way too much damage at 127 a tic when it should probably be in the 30-40 range.

**Comment by akrom23** [comment]
Yeah, now I see something is wrong here. Will look into it, Thx a lot ;)
