### ISSUE TITLE
[CORE] Can't loot: looteable Items are RED 

### ISSUE THREAD

**Issue by sicknot1** [SunwellWoW/Sunwell-TBC-Bugtracker#2221]
Description:  Can't loot: looteable Items are RED 

How it works: when looting while in party some items will be in red and i won't be able to loot them, while the other player on my party can.

How it should work: Able to loot or IF partymember looted it before stop showing loot thats no longer there as red
![wowscrnshot_120218_143449](https://user-images.githubusercontent.com/35937937/49344515-277ea900-f657-11e8-97f5-1b0fe846f427.jpg)
![Uploading WoWScrnShot_120218_155056.jpg…]()

Source (you should point out proofs of your report, please give us some source): 

123

**Comment by sicknot1** [comment]
Continued Issue: When you party with someone whos already hitting the quest mob. You can't loot it after

**Comment by Mikov1605** [comment]
Actually, the red says that loot belongs to someone. Example: 5 man group, you do deadmines. Every 5th mob drop belongs To You. Other players that open it, have it on red, to not steal it. Exceptions: quest items, money, green and better items. Cloths etc must work like that, To prevent situations in which one player Just shift-opens all mobs and gets all cloths etc.

**Comment by Mikov1605** [comment]
The comment You made is also wrong, because it does work on mobs that SHOULD drop an q Item for all (paw from hogger) . You're example is probably gold dust or large candle

**Comment by Mikov1605** [comment]
Which should drop only for 1 person

**Comment by Mikov1605** [comment]
Closeable, dear gms ;)

**Comment by sicknot1** [comment]
123
