### ISSUE TITLE
Gold seller

### ISSUE THREAD

**Issue by h1n1num1** [SunwellWoW/Sunwell-TBC-Bugtracker#2223]
Description: Rhodandra

https://pasteboard.co/HPUQpwq.jpg

enjoy :)

**Comment by Dootz** [comment]
Thank you :D

**Comment by Azathothh** [comment]
Thanks for your report, but please use ticket system in-game for that :)
You can find it here:
![obraz](https://user-images.githubusercontent.com/37483678/49344821-6d9a3380-f67c-11e8-97d0-a03389e7670e.png)

edit: link with proof in ticket is fine as well :)

**Comment by h1n1num1** [comment]
i did use ticket system once but you said we need proof so im here with screenshots :)
im gonna use ticket again

**Comment by h1n1num1** [comment]
np dootz <3
