### ISSUE TITLE
heroic strike

### ISSUE THREAD

**Issue by antikiller69** [SunwellWoW/Sunwell-TBC-Bugtracker#2224]
Description: heroic strike doesnt work when not facing the opponent

How it works: heroic stike adds dmg to autoattack

How it should work: u should be able to use heroic strike when running away to have charge attack ready when u get in range of the mob, atm u cant precast heroic strike if u are not facing the enemy

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Client files specify that you have to face the caster and im gonna believe the client files.
Do you have any proof that you should be able to queue HS without facing the caster?

**Comment by akrom23** [comment]
@antikiller69 Any news?

**Comment by akrom23** [comment]
No response. Closed.
