### ISSUE TITLE
Roll bug

### ISSUE THREAD

**Issue by xilandir** [SunwellWoW/Sunwell-TBC-Bugtracker#2227]
Description: I rolled higest on a loot roll, didnt get the item, warrior rolled lower and got it

How it works: 
IDK

How it should work: 
I should have that beauty in my inventory now! =D

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/OtjGBTq screenshot i made    =>123<=
![roll bug](https://user-images.githubusercontent.com/45543826/49345110-96bcc300-f680-11e8-9977-686c3a188fbb.png)

**Comment by Azathothh** [comment]
You've had 1 free slot in bags all the time? Or maybe made it after boss was killed/loot was opened/you've clicked on need/roll ended ?

**Comment by xilandir** [comment]
I can't say that i'm 100% sure i had an open spot the entire time. But
usually i try to keep at least one spot open, as the corpses despawn super
fast so i dont "lose" the item while making space.
Hope this information was worth any

-Xilandir
---------- Forwarded message ---------

**Comment by Jseay1313** [comment]
Even if he had a full inventory, that's not how the method works. He would still win with the highest roll and the item would stay on the bosses corpse until it's relooted.

**Comment by SunwellTracker** [comment]
Fix will be implemented after the restart.
