### ISSUE TITLE
[Hunter Pet] Daze

### ISSUE THREAD

**Issue by TheRealestMcCoy** [SunwellWoW/Sunwell-TBC-Bugtracker#2228]
Description: 
The hunter pet seems to be getting dazed from being infront of as target

How it works: 
Pet being dazed in front

How it should work: 
He should not be dazed facing the target

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/d5ca2fdf62da51aa2548cb0e5e0e2c91

**Comment by akrom23** [comment]
Cannot reproduce it.
