### ISSUE TITLE
Killing kolkar in desolace give no rep

### ISSUE THREAD

**Issue by jockeboschko** [SunwellWoW/Sunwell-TBC-Bugtracker#2229]
Description: 
Killing kolkar in desolace give no rep

How it works: 

Killing kolkar in desolace give no rep
How it should work: 

should give rep
Source (you should point out proofs of your report, please give us some source):

**Comment by Sabre142** [comment]
That's because you need to kill either Magram or Gelkis centaur.

**Comment by jockeboschko** [comment]
ture
