### ISSUE TITLE
Skeletons  are cubes in the client

### ISSUE THREAD

**Issue by dadkinse** [SunwellWoW/Sunwell-TBC-Bugtracker#2230]
Description: 
When a skeleton was supposed to be on the ground (in deadmines) a cube appeared the moment the person released spirit.

How it works: 
person releases in deadmines and a box appears

How it should work: 
a skeleton should appear

Source (you should point out proofs of your report, please give us some source): 
Not sure what to put here. Experience. I did it.

**Comment by dadkinse** [comment]
seems to be nightelf skeletons only

**Comment by Wojtyas** [comment]
Fixed & implemented.
