### ISSUE TITLE
Improved aspect of the Hawk

### ISSUE THREAD

**Issue by Volkyte** [SunwellWoW/Sunwell-TBC-Bugtracker#2236]
Description: 
Improved aspect of the hawk excessive proc

How it works: 
i gives 10% chance to proc and increase autoattack of shots speed by 10% (capped) but it procs EVERY shot almost (rate somewhere enar 80% instead of 10% at 1 point talent only)

How it should work: 
10% proc rate at any rank should be given as per tooltip

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Improved_Aspect_of_the_Hawk
this is how the original is suposed to work

**Comment by ujellyx** [comment]
For me it doesn't proc that often actually...

**Comment by TheRealestMcCoy** [comment]
I have to kinda agree and disagree with both of you. At lower levers it seemed to hardly proc ever. As i got higher in level the procs seemed better. I am only 38 if you are higher than that Asher IDK yet.  I do only have 1 point in it as well. Which is only 10%.

Now keep in mind it depends on the haste.

**Comment by YoshGit** [comment]
When testing in the PTR IAotH had the expected uptime, but I cant say anything about lower levels.

**Comment by akrom23** [comment]
Works fine.
