### ISSUE TITLE
Permafrost+Imp Blizzard

### ISSUE THREAD

**Issue by Tentto** [SunwellWoW/Sunwell-TBC-Bugtracker#2237]
Description: 
Permafrost talent not being applied properly

How it works: 
Permafrost and Imp. Blizzard isn't stacking. It seems like the only slow being applied is the one gained from the Imp Blizzard talent.

How it should work: 
Permafrost and Improved Blizzard should stack, greatly reducing enemy speed.

Source (you should point out proofs of your report, please give us some source): 
Common knowledge.

**Comment by akrom23** [comment]
Works fine.
![asdasd](https://user-images.githubusercontent.com/1035215/50168768-79c4f880-02ec-11e9-96c8-21675c61acfb.jpg)
Duration of Chill effect is increased up to 4.5 sec
And in chat you see auras applied on the mob.

**Comment by akrom23** [comment]
No response. Closed.
