### ISSUE TITLE
Rogue backstab

### ISSUE THREAD

**Issue by Naanemthe** [SunwellWoW/Sunwell-TBC-Bugtracker#2238]
Description: 

Backstab is possible to be done from the front of the mobs when you step back and forth
How it works: 
Backstab is possible to be done from the front of the mobs when you step back and forth

How it should work: 
Backstab is possible to be done from the front of the mobs when you step back and forth

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@Naanemthe Needs a video or screenshots.

**Comment by Ad0naj** [comment]
It's just a vanilla private servers bug caused by server latency. Basically the server is responding as if the mob is not facing you (due to your latency) when in reality they are.

**Comment by Nadiirr** [comment]
https://streamable.com/7p2s7

It is possible.

**Comment by Gelori** [comment]
Lol or he has a very low latency - less than 30 ms or he doesn't do it right. Anyway it is a PS scene bug.

**Comment by aakyed** [comment]
Its perfectly doable like on most Pservers. I don't know if it is supposed to happen but this report is useless.

**Comment by aakyed** [comment]
I think that the report is not clear. The bug is in fact that backstabbing from the front is possible. And apparently this was never possible during Vanilla. It is a common bug on most Pservers. 
https://www.reddit.com/r/classicwow/comments/8v0s31/will_backstabbing_from_the_front_be_doable_on/

**Comment by Wockz** [comment]
You can also Mutlilate from the front using this bug.

**Comment by Ad0naj** [comment]
> https://streamable.com/7p2s7
> 
> It is possible.

but it shouldn't.
