### ISSUE TITLE
Judgement not doing damage sometimes

### ISSUE THREAD

**Issue by CreybeN** [SunwellWoW/Sunwell-TBC-Bugtracker#2240]
Description: Judgement not doing damage sometimes

How it works: sometimes when you judge seal of command it makes no damage, no resist message or anything, just dont do damage

How it should work: doing damage xD

Source (you should point out proofs of your report, please give us some source):

**Comment by CreybeN** [comment]
so annoying, pls fix it fast

**Comment by xethra89** [comment]
I can confirm, it's hard to recreate since it's not consistant. I primarily see it when I cast HoJ then Judgement immediately after. 

The major issue is there's nothing even in the combat log, it just doesn't even register.

**Comment by Taolos** [comment]
I can confirm too and Xethra is right, nothing in the combat log :/

**Comment by MVMnn** [comment]
Please prioritize this bug, its pretty annoying

**Comment by Testimonia** [comment]
confirmed

**Comment by Testimonia** [comment]
confirmed

**Comment by Felynda** [comment]
Still happening today, happens on Repentance and Hammer of Justice aswell. Gamebreaking in pvp happens atleast 2-3 times per battleground.

Spells go on cooldown but nothing happens, no resist and no grounding totem were up

**Comment by akrom23** [comment]
Anyone got some screenshots with combat log?

**Comment by xethra89** [comment]
That's the problem, it doesnt even register in combat log. 

I've not been playing ret though since leveling so cannot confirm or deny whether it is still occuring.

**Comment by akrom23** [comment]
Yeah, I know, but i still want it.

**Comment by akrom23** [comment]
@CreybeN @xethra89 @MVMnn @Testimonia I'm still waiting for the screenshots.

**Comment by xethra89** [comment]
What do you want me to do? Screenshot nothing? I dont know how to get you evidence when I said it doesn't even show in the combat log when this happens. I've tried to figure out how to consistantly reproduce it but no luck. It just randomly happened from time to time.

Judge command, judgement goes on cooldown. 
No damage at all, and no messages saying 'resist' or anything.
Check combat log, it shows nothing either. 

Either way, I dont play ret at all so cba. And creyben(OP) quit the server months ago. 

I'm more interested in SSC fixes than this.
