### ISSUE TITLE
Fix Website Dropdown Login

### ISSUE THREAD

**Issue by grand-lotus-iroh** [SunwellWoW/Sunwell-TBC-Bugtracker#2241]
There is no TBC dropdown option on website. Please remove the dropdown or update inline website login form.

![image](https://user-images.githubusercontent.com/1291364/49346279-f8b80100-f65d-11e8-9a25-65a2d31748e3.png)

**Comment by SunwellTracker** [comment]
We know about it. There is no shop and donations system for Nightbane yet.

**Comment by grand-lotus-iroh** [comment]
If you know about, than fix it?
Just add a dropdown that does a redirect on login action to https://www.sunwell.pl/

Nobody said anything about a shop or donation.. no idea what you are talking about. Is that what the other dropdowns do? Why am I logging into website for a TBC account I made using a dropdown server that is not relevent to my account? I get it.. to a degree.

**Comment by SunwellTracker** [comment]
This sessions are directly related to the store. When it comes to using website without donation/store system there is no difference if you're on Feronis/Angrathar or Nightbane.

**Comment by SunwellTracker** [comment]
But okay, we'll do it.

**Comment by grand-lotus-iroh** [comment]
Can you please alphabetize or make it so that your most popular server is "default" selected as dropdown? Remove "Choose realm" or make it so if someone doesn't even select a box they can still login. It's good useability to respect people's clicks and not waste time.

just make it so 

```
<option value="5">Nightbane</option>
```

is at the very top or make it default -- https://stackoverflow.com/questions/3518002/how-can-i-set-the-default-value-for-an-html-select-element
