### ISSUE TITLE
Shadowpriest

### ISSUE THREAD

**Issue by madcowzor** [SunwellWoW/Sunwell-TBC-Bugtracker#2243]
Description: Shadow weaving

How it works:  sometimes stacks up to 10% shadowdmg on target sometimes stops on 2-3 stacks and falls off even with 5/5 talents.

How it should work:  should stack to 10% and stay there as long as refreshed.

Source (you should point out proofs of your report, please give us some source):

**Comment by SunwellTracker** [comment]
Could you provide some screens or videos? Becuase it works fine while testing it.
