### ISSUE TITLE
Icy Veins

### ISSUE THREAD

**Issue by lolproxoxo** [SunwellWoW/Sunwell-TBC-Bugtracker#2244]
Description: 
Does not avoid interruption from attacks while spellcasting

How it works: 

Does not avoid interruption from attacks while spellcasting
How it should work: 

Have to avoid interruption from attacks while spellcasting
Source (you should point out proofs of your report, please give us some source): 
spell discription

**Comment by akrom23** [comment]
@lolproxoxo It looks good to me.

**Comment by Jazo420** [comment]
it works 100% fine, i dont understand how is this high priority, the guy who wrote this clearly has no idea how the spells should work.

it doesnt stop you from being interrupted, it just stops your cast from being pushed back from attacks, which is does.

proof: https://puu.sh/Chwhi/37f7634884.mp4

now can we please prioritize the more important issues for mages like cone of cold being completely broken and never hitting things where its supposed to?
i reported it here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2335

thanks
