### ISSUE TITLE
Warlock drain soul not providing talent effect

### ISSUE THREAD

**Issue by oayllon-bf** [SunwellWoW/Sunwell-TBC-Bugtracker#2245]
Description: 

After investing points in improved drain soul , noticed that sometimes i wasnt getting the mana back (targets where valid and provided xp). This happened when in party
How it works: 
Spec improved drain soul and use it when killing a valid mob in party. I think that if the damage that kills the mob isnt yours, you dont get the desired effect.

How it should work: 

effect should always apply on valid mobs that die.

Source (you should point out proofs of your report, please give us some source):

**Comment by ZaoQ** [comment]
Talent works perfectly, as it says if the target is killed **by you**

**Comment by Wojtyas** [comment]
![image](https://user-images.githubusercontent.com/22802214/49393681-40a85800-f732-11e8-9351-10a6e6a476a5.png)
