### ISSUE TITLE
warlock drain soul

### ISSUE THREAD

**Issue by h1n1num1** [SunwellWoW/Sunwell-TBC-Bugtracker#2246]
Description: warlock drain soul should give 1 soul shard every time you kill a mob with it but here its not giving all the times
this is what exactly spell information says : **if the target dies while being drained and yield exprience or honor, the caster gains a soul shard.

so its not a base on a chance it should give soul shard always when you kill a mob.
thanks <3

**Comment by ZackForester** [comment]
Drain Soul doesn't give you shards for mobs that are gray to you or lower nor does it give shards for mobs that have been tagged by someone not in your group.

**Comment by h1n1num1** [comment]
are you kidding me zack ? you think that i dont know that after playin warlock 8 years of my life ? and i wrote it there my self in spell information , the thing is sometimes the unit that yield exp wont give soulshard. 
god's sake.

**Comment by akrom23** [comment]
Cannot reproduce it.
