### ISSUE TITLE
Dire Maul - West

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#225]
### **TO DO:**

- [ ] 1. When Arcane Aberration dies it should cast Mana Burn spell (22936).
**EDIT: When Arcane Aberration casts Mana Burn spell there should be arcane explosion animation. 2:10**
https://www.youtube.com/watch?v=jvDYRhwVgYo
- [ ] 2. Once players start to melee Mana Remnants they should Blink (14514) away. For now they use Blink to get closer to players instead of avoiding them.
- [ ] 3. Illyanna Ravenoak's Concussive Shot spell (22914) should have 50% chance to stun target and apply Improved Concussive Shot (22915). Looks like its 100% chance to apply stun.
- [ ] 4. Looks like Illyanna Ravenoak doesn't use Arcane Blast spell (22940). 
_Why would she do that? Nothing about it on wowhead, wowwiki and others_
**EDIT: https://classicdb.ch/?npc=11488#abilities + http://db.hellfire-tbc.com/?npc=11488#abilities but hard to find notice it on video**
- [ ] 5. Illyanna Ravenoak should use Volley spell (22908) only when there are at least two players in spell radius.
- [ ] 6. Arcane Feedback (14400) doesn't use his Lightning Shield spell (15507). Probably because Arcane Feedback is immune to nature spell.
**EDIT: Still doesn't use it**
![image](https://user-images.githubusercontent.com/22802214/44810802-2e6acb00-abd3-11e8-8cea-174a36511b87.png)
- [ ] 7. Spawned Cadaverous Worms are hostile while should be neutral and don't have random movements while they should.
**EDIT: Still hostile and start to attack players immediately after spawn**
- [ ] 8. Gob Treasure of the Shen'dralar chest (80095) should be able to interact only with players who are on 7877 quest.
- [x] 9. When all of 5 pylons and prison are activated. Those 18 Highborne Summoners (11466) standing inside prison in circle should start to attack boss and fight with him. There also should be yell:
"The demon is loose! Quickly we must restrain him!"
**EDIT#2: Prison breaks in proper way + yell is present as well, but npcs are still standing on their place**

### **DONE:**

- [x] 1. Ironbark the Redeemed (14241) shouldn't be here at all. This NPC is related to Dire Maul - East raport.
![image](https://user-images.githubusercontent.com/22802214/44719965-62f06100-aac5-11e8-82c8-99c2be4b77ad.png)
- [x] 2. Petrified Treant (11458) should use his Harden Skin spell (22693) more often.
- [x] 3. Ironbark Protectors (11459) paths have to be changed in Capital Gardens location.
- [x] 4. There should be much more Ironbark Protectors walking on pavement around Capital Gardens (around 8 units).
- [x] 5. Petrified Guardian (14303) should refresh his Thorns  spell (22696) buff once faded or dispelled.
- [x] 6. There should be no Warpwood Crushers (13021) in Capital Gardens (guids: 84266, 84267).
- [x] 7. There should be no Warpwood Tanglers (11464) in Capital Gardens (guids: 84271, 84272, 84273).
- [x] 8. There should be no Warpwood Treants (11462) in Capital Gardens (guids: 84274, 84275).
- [x] 9. There should be no Warpwood Stompers (11465) in Capital Gardens (guids: 84268, 84270).
- [x] 10. Petrified Treants and Petrified Guardians should have random movements.
- [x] 11. There should be much more packs of Petrified Treants and Petrified Guardians in Capital Gardens location. Best to show it in-game.
- [x] 12. In entire Dire Maul - West there are missing 5 game objects named DireMaulCrystalGenerators. Those gobs suppose to open Immol'thar's prison once all of them are activated. For now boss is not in prison and gobs are removed. I will put every gob's ID and .GPS below:
- **First Crystal:**
29743 (Entry: 177259) - [Doodad_DireMaulCrystalGenerator01 X:12.941300 Y:277.931000 Z:-8.932900 MapId:429] 
![image](https://user-images.githubusercontent.com/22802214/44721982-e4e38880-aacb-11e8-8530-845bed1737dc.png)
- **Second Crystal:**
29744 (Entry: 177257) - [Doodad_DireMaulCrystalGenerator02 X:-92.345596 Y:442.670013 Z:28.547001 MapId:429]
![image](https://user-images.githubusercontent.com/22802214/44722230-bade9600-aacc-11e8-8632-d9d90790b2f0.png)
- **Third Crystal:**
29742 (Entry: 177258) - [Doodad_DireMaulCrystalGenerator03 X:121.222000 Y:429.092010 Z:28.454800 MapId:429] 
![image](https://user-images.githubusercontent.com/22802214/44722275-e19ccc80-aacc-11e8-8c93-4fbb8a8f042f.png)
- **Fourth Crystal:**
29746 (Entry: 179505) - [Doodad_DireMaulCrystalGenerator05 X:-155.432999 Y:734.166016 Z:-24.621599 MapId:429]
![image](https://user-images.githubusercontent.com/22802214/44722498-83bcb480-aacd-11e8-9d7a-eaf0ac15c3c6.png)
- **Fifth Crystal:**
29745 (Entry: 179504) - [Doodad_DireMaulCrystalGenerator04 X:78.138702 Y:737.401978 Z:-24.621599 MapId:429] 
![image](https://user-images.githubusercontent.com/22802214/44722535-a18a1980-aacd-11e8-9038-47954bbbfd1c.png)
- [x] 13. There should be no perm spawns of Mana Burst npcs (id 14397) (guids: 84231, 84234, 84230, 84225, 84224, 84223, 84229, 84227, 84218, 84217, 84216, 84215, 84214).
- [x] 14. As you can see in figures above, there should be equal amount (4) of Arcane Aberrations (11480) and Mana Remnants (11483) around every of pylon. For now in gobs spots there are some various creatures, besides there are no pylons hehe.
- [x] 15. There should be Shen'dralar Wisps (14361) spawns randomly in entire Capital Gardens, Court of the Highborne, Prison of Immol'thar and The Athenaeum locations.
- [x] 16. Ancient Equine Spirit should have random movements.
- [x] 17. There should be several Eldreth Spectres (11473) patrolling balcony in Court of the Highborne before we enter it.
- [x] 18. There should be plenty of Eldreth Phantasms (11475), Eldreth Spirits (11472) and Eldreth Apparitions (11471) in Court of the Highborne building hanging around with random movements. We have 0 of them.
![image](https://user-images.githubusercontent.com/22802214/44724683-b8cc0580-aad3-11e8-9031-50188d9ae0a5.png)
- [x] 19. Eldreth Apparition shouldn't focus on melee when it has mana and may cast spells.
- [x] 20. Looks like Eldreth Phantasm doesn't use his Shrink spell (15802).
- [x] 21. There shouldn't be Skeletal Highbornes (11476) and Rotting Highbornes (11477) in Court of the Highborne inside the building. They should spawn on the roof.
- [x] 22. Magister Kalendris (11487) position and orientation should be as presented by gps on picture below.
![image](https://user-images.githubusercontent.com/22802214/44726065-275e9280-aad7-11e8-908f-f6d80c0509da.png)
- [x] 23. Magister Kalendris also have Dark Channeling aura (21157) or some other extra visual while kneeling.
![image](https://user-images.githubusercontent.com/22802214/44726301-bb305e80-aad7-11e8-86d3-08869931e2c3.png)
- [x] 24. Magister Kalendris dropped only common items. Not sure about that but he's boss and has some rare items in loottable so maybe its better to check.
- [x] 25. There should be no Eldreth Apparitions, Eldreth Spirits and Eldreth Phantasms on Court of the Highborne roof.
- [x] 26. On Court of the Highborne roof there should be several mixed packs of creatures combined of: Eldreth Seether (11469), Eldreth Darter (14398), Eldreth Sorcerer (11470), Skeletal Highborne, Rotting Highborne.
- [x] 27. Eldreth Seether should use his Crimson Fury spell (16843) more often.
- [x] 28. There should be like 3 Eldreth Spectres patrolling roof of the Court of the Highborne location.
- [x] 29. Illyanna Ravenoak should act as a hunter. She must try to keep distance from players as possible. For now she runs to players and attack by melee.
- [x] 30. Illaynna Ravenoak probably doesn't use her Multi-Shot spell (14290). She should use it when spell will reach at least 2 targets.
- [x] 31. Looks like Ferra (Illyanna Ravenoak's pet) doesn't use Charge spell 22911). It should use it on pull and everytime when it's target is in required distance.
- [x] 32. There should be no Shen'dralar Zealots (14369) on the roof of Court of the Highborne (guids: 84373, 84374, 84371).
- [x] 33. Tendris Warpwood (11489) stays in wrong position and orientation. Proper on gps screen.
![image](https://user-images.githubusercontent.com/22802214/44729411-0b5eef00-aadf-11e8-8543-09892274569f.png)
- [x] 34. When we pull Tendris Warpwood there should be yell:
"Tendris Warpwood yells: You do not belong here! Ancients, rise up against these intruders!"
- [x] 35. With Tendris' yell he should pull every living Ironbark Protectors (11459) in Capital Gardens location. They should come here and fight with players.
- [x] 36. There should be 2x Eldreth Spectres and 2x Eldreth Phantasms patrolling path between Court of the Highborne and Prison of Immol'thar.
- [x] 37. In Prison of Immol'thar location there are several permanent spawns that shouldn't be present (i will note with guids): Dread Guards (84242, 84241), Dreadsteed Spirits (56956, 84384), Xorothian Imp (56953), Eye of Immol'thar (56957), Eldreth Phantasm (56955), Eldreth Spectre (56954), Highborne Summoner (56952) and Lord Hel'nurath (56803). Most of mentioned creatures should be summoned during Dreadsteed of Xoroth quest. All of them are randomly added.
- [x] 38. Beside Arcane Aberration and Mana Remnants that should appear here next to pylons we should add several creatures:
- 4 packs of: 1x Arcane Torrent (14399) and 4x Arcane Feedbacks (14400). They should hanging around prison as formation.
- 3x Resiudal Monstrosity (11484) that are moving in circle around the boss prison.
- 18x Highborne Summoners (11466) that are standing inside the prison and fill every wall gap like on screen below.
![image](https://user-images.githubusercontent.com/22802214/44730904-50385500-aae2-11e8-81c8-a4306e47028d.png)
- [x] 39. Arcane Torrent (14399) should use his Forked Lightning spell (22945) more often.
- [x] 40. Arcane Feedback's Lightning Shield buff should be refreshed when faded or dispelled.
- [x] 41. When Residual Monstrosity dies he spawns few Mana Bursts (14397). They should start to attack players immediately.
- [x] 42. Highborne Summoners shouldn't use Frost Nova spell (15063) when there are no players around them.
- [x] 43. Prince Tortheldrin stays in wrong position. On screen is correct one:
![image](https://user-images.githubusercontent.com/22802214/44733930-ebccc400-aae8-11e8-8655-3a27e0d6552a.png)
- [x] 44. Prince should cast his Counterspell (20537) on player who is casting spell indeed.
- [x] 45. In The Athenaeum location there should be much more Highborne Summoners (neutral this time) and Shen'dralar Zaelots hanging around from bookcase to bookcase.
- [x] 46. The Prince's Chest gob:
 [21 - (The Prince's Chest X:139.059998 Y:625.018982 Z:-27.937599 MapId: 429)] 
should be in other place: 
6 (Entry: 179545) - [The Prince's Chest X:116.135002 Y:638.835999 Z:-48.466999 MapId:429]
- [x] 47. Mana Remnant should be more focused on casting Chain Lightning (15659) instead of chasing players and hit them by melee. As long as they keep distance its fine.
- [x] 48. Shen'dralar Wisps should have random movements.
- [x] 49. Magister Kalendris (11487) should be in kneel position before pull or when he's back to his place after evade.
_He casts something after 10 seconds out-of-combat so i linked kneel with it, so just wait 10 seconds after ptr update_
- [x] 50. Looks like Magister Kalendris doesn't use his Dominate Mind spell (7645).
_Random target not tank_
- [x] 51. Eldreth Phantasm shouldn't refresh Call of the Grave (17831) debuff on target who already have it.
- [x] 52. Looks like Eldreth Apparition doesn't use his Cone of Cold spell (15244).
_There's 50% chance that he'll use it every 15-25seconds_
- [x] 53. Magister Kalendris should use Shadowform spell (22917) when he is at 50% hp. He used it once pulled.
- [x] 54. Magister Kalendris' Mind Blast spell is probably wrong rank/id. It should hit harder. This should be correct one: 17287
- [x] 55. All creatures on the roof of Court of the Highborne should be friendly to each other. For now almost every of them are fightning to each other including boss Illyanna Ravenoak.
- [x] 56. Looks like Eldreth Spectre (11473) doesn't use his Dispel Magic spell (17201). He should cast it on himself and his allies.
- [x] 57. Eldreth Spectre should cast Dark Offering spell (7154) **only** on his allies.
- [x] 58. When Rotting Highborne dies, it should spawn 3-4 Cadaverous Worms (14370). They should act like critters with random movements and be neutral when spawned. Once they took any damage from players they should start to attack in group.
- [x] 59. Eldreth Darter should cast Power Word: Shield spell on his allies as well.
- [x] 60. Cadaverous Worm hp is incorrect. They should have 750 hp while they have 31 hp.
- [x] 61. Cadaverous Worm melee damage is incorrect. They should melee for 368 - 417 while they hit around ~150.
- [x] 62. Tsu'zee (11467) should be rare spawn boss with app. ~20% chance to appear in dungeon. For now she's removed from game.
- [x] 63. Illyanna Ravenoak (11488) should patrol half of the roof on Court of the Highborne location. For now she stays in place.
- [x] 64. Illyanna Ravenoak should always walk with her pet - Ferra (14308) right next to her. For now they stay separated.
- [x] 65. There should be dialogue option with Shen'dralar Ancient (14358). It work on Angrathar perfectly.
- [x] 66. With Tendris Warpwood's death there should be emote:
"Ancient Equine Spirit breaks free of its spectral bonds with a tremendous crash of thunder!"
Ancient Equine Spirit npc should appear with extra thunder visual. For now he's present entire time.
- [x] 67. Ancient Equine Spirit (14566) shouldn't be present entire time. He should spawn with some extra thunder visuals after Tendris Warpwood (11489) boss is defeated.
- [x] 68. Looks like Highborne Summoner (11466) doesn't use his Fire Blast spell (13341).
- [x] 69. Immol'thar is moving extremely fast.
- [x] 70. Highborne Summoners (11466) around Immol'thar should be hostile to players.
- [x] 71. Eye of Immol'thar (14396) should start to attack random player immediately after spawn.
- [x] 72. Eye of Immol'thar should chase one player entire time it is alive. Eye shouldn't be tauntable.
- [x] 73. Eye of Immol'thar melee hits players for around 1k while it should for 349 - 384.
- [x] 74. After Immol'thar is dead there shoul be yell:
"Prince Tortheldrin yells: Who dares disrupt the sanctity of Eldre'Thalas? Face me, cowards!"
Right now he yells that when we pull him which is incorrect.
- [x] 75. Prince Tortheldrin (11486) should become hostile only after yell from point 38. Normally (when Immol'thar is alive) he should stay neutral and have some dialogues with players.
- [x] 76. DireMaulCrystalGenerators gobs (80179, 80180, 80176, 80178, 80177) are extremely small.
- [x] 77. This doors are to huge, should be replaced by smaller one + they are rotated. Doors which are in use on Angrathar:
29751 (Entry: 177221) - [Door X:50.586300 Y:501.941010 Z:-23.149900 MapId:429]
![image](https://user-images.githubusercontent.com/22802214/44812317-39275f00-abd7-11e8-91b9-1c3bfb9f7797.png)
- [x] 78. Door gob 80189 are rotated in weird position. They should stay closed till player with Crescent Key (18249) will open them.
![image](https://user-images.githubusercontent.com/22802214/44811812-de413800-abd5-11e8-8700-a99a9c926ce9.png)
- [x] 79. After Prince uses his Arcane Blast spell (22920) he should reset his threatlist.
- [x] 80. Prince's Summon spell (22995) doesn't work in proper way. He uses it time to time and it should summon targeted player on his feet. For now I can't even realize if he does it or no.
**EDIT: Since Angrathar port it looks like he doesn't use it at all.**
- [x] 81. Prince's Whirlwind spell seems to be wrong. He should use 15589.
- [x] 82. Petrified Guardians doesn't use Regrowth spell (22695). He also cast it on his allies.
**EDIT: Still doesn't use it**
- [x] 83. Once all of 8 creatures around of pylon are dead, the crystal should activate by its own. For now crystals don't activate.
**EDIT: I've killed all 8 creatures but crystal is still activated. Also there is weird npc below this gob who shouldnt be there**
![image](https://user-images.githubusercontent.com/22802214/45621041-3950a700-ba7f-11e8-9b67-b90d20808751.png)
- [x] 84. Eldreth Darters (14398) should have random movements.
- [x] 85. Looks like Tsu'zee doesn't use her Blind spell (21060). She should cast it on random player (not tank).
**EDIT: Now she doesn't use any of her spells. Sinister Strike (15581), Gouge (12540), Dual Wield (674) and Blind (21060).
- [x] 86. Shen'dralar Wisps (14361) shouldn't be targettable by players.
- [x] 87. Creatures around crystals should be linked with threat.
- [x] 88. There is no interaction with Prince Tortheldrin when he's neutral. There should be text:
![image](https://user-images.githubusercontent.com/22802214/45622759-6dc76180-ba85-11e8-8414-adadb8a7b19d.png)
- [x] 89. When all of crystals pylons (from point 2) are activated Prison gob should activate too giving acces to enter inner circle in Prison of Immol'thar location. I believe prison gob was removed like others and hope its correct one:
29747 (Entry: 179503) - [Doodad_DireMaulBossForceField01 X:-38.965099 Y:813.708984 Z:-27.317801 MapId:429]
**EDIT: When I actviated all of crystals by command the barrier didn't vanish**
- [x] 90. There is weird npc below first crystal lul. He attacks players. He shouldn't be there from players pov. He seems to be only below first crystal.
![image](https://user-images.githubusercontent.com/22802214/45751043-6e8cfe80-bc11-11e8-8890-6113bca664bd.png)
- [x] 91. Every creature in The Anthenaeum should have "House of Shen'dralar" text below its name except Prince Tortheldrin.
**EDIT#3: Still no titles**
- [x] 92. Prince Toltheldrin should have "Ruler of the Shen'dralar" text below his name.
**EDIT#3: Still no title**

**Comment by Kokaina** [comment]
Updated.

**Comment by Kokaina** [comment]
Updated.

**Comment by Kokaina** [comment]
updated.
