### ISSUE TITLE
Weapon Skill

### ISSUE THREAD

**Issue by Saaye** [SunwellWoW/Sunwell-TBC-Bugtracker#2255]
Description: 
Just bought a new weapon from AH which meant i had 1/130 skill, its leveling up super slow, i just did 23 counted attacks against a lvl 18 orc (i am level 26) and only 1 skill level, i went from 30/130 to 31/130 i currently am struggling to kill grey monsters because i cant level this axe up its going to take me hours to get to were its usefull

How it works: 
Currently levels up super super slow 

How it should work: 
Gain skill levels more often even when miss/parry/dodge/hit

Source (you should point out proofs of your report, please give us some source):

**Comment by babno** [comment]
To give some more detail to this, let MS be your maximum skill, so for example at level 30 MS = 150. From levels 1=>(MS-40) it should be a 100% chance per swing to grant a skill. (MS-40)=>(MS-20) should be 50% per swing. (MS-20)=>(MS-10) should be 25%. (MS-10)=>(MS-5) should be 10%. (MS-5)=>MS should be around 1-2%. These percentages increase with int however I am not sure by how much.

**Comment by koostosh** [comment]
No proofs no fix

**Comment by babno** [comment]
@koostosh you should ask for proof before closing. This is such a basic feature that is common knowledge OP probably didn't think he needed to supply sources. 
https://wowwiki.fandom.com/wiki/Weapon_skill

**Comment by babno** [comment]
I'll also note that I googled "weapon skillup formula wow tbc" and that was literally the first link. Feel free to lookup things yourself from time to time
