### ISSUE TITLE
Parry (and like effects) seem to not allow Weapon Skill Ups

### ISSUE THREAD

**Issue by chidyco** [SunwellWoW/Sunwell-TBC-Bugtracker#2259]
Description: 
Got a new dagger, 1/100 skill, it is only lvling up when i 'miss'. Mob is parrying most attacks (maybe that is a problem too), and skill ups never happen on a parry.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by chidyco** [comment]
It may not just be parries. Weapon skill ups are far too low, no matter what the attack is.

**Comment by akrom23** [comment]
No detailed info - your level, mob's level, your stats.
Weapon skills are updated on hit/miss/resist only.
Closed.
