### ISSUE TITLE
Leeway - Melee and Spells 

### ISSUE THREAD

**Issue by SuddenDeath** [SunwellWoW/Sunwell-TBC-Bugtracker#226]
The Problem:
Currently there is no "moving range leeway" for ranged spells, melee spells & auto-attack.
Video I made: https://www.youtube.com/watch?v=5YzXpKaGCe8

How it should work:
When conditions are met, server should allow +2.66 yards to your ranged spells, melee spells & auto-attack.

Conditions:
You and your target must both be moving, you both also has to be moving with a "running animation", meaning both of you has to move > 0.7 of normal movement speed(this is where your character switch from walking to running animation).

Examples:
Use Curse of Exhaustion on target, target is now at 0.7 of normal movement speed, target starts walking.
Use Curse of Exhaustion on target which has a 8% increased movement speed boot enchant, target is now at 0.76 of normal movement speed, target will still be "running".

Proof:
How it's calculated in the 2.4.3 client: http://i.imgur.com/PxKWgdQ.png

Videos of this mechanic:
Retail: https://youtu.be/_DgUcqXwtwk?t=2m
Other server: https://www.youtube.com/watch?v=L8WhIo1l8Aw

How to reproduce: Mimic what is done in the videos.

**Comment by Riztazz** [comment]
Please test again, should be fixed now

**Comment by Riztazz** [comment]
How come? as far as i can see it does work
https://youtu.be/qCBzmhq3UgQ

**Comment by SuddenDeath** [comment]
I haven't re-tested it but in that video of yours @Riztazz it looks like auto-attack doesn't get increased range?

**Comment by Riztazz** [comment]
Im pretty sure melee leeway doesnt work for white attacks, its just for spells

**Comment by SuddenDeath** [comment]
@Riztazz incorrect. 
It works for auto-attacks as well. This exact mechanic is present even on retail today and works for auto-attacks as well. 

Can also be seen very clearly in this wotlk video: https://www.youtube.com/watch?v=jVdxrFnAfB0&feature=youtu.be&t=10m31s

**Comment by notsofamous** [comment]
video from retail showing that leeway works for white hits: https://www.youtube.com/watch?v=_DgUcqXwtwk&feature=youtu.be&t=2m

video from corecraft showing the same: https://www.youtube.com/watch?v=L8WhIo1l8Aw

retail vanilla vid: https://www.youtube.com/watch?v=6oiIy5j5oUA&feature=youtu.be&t=369

https://github.com/Looking4Group/L4G_Core/issues/3528

**Comment by Riztazz** [comment]
ok

**Comment by Nadiirr** [comment]
Working <3

**Comment by SuddenDeath** [comment]
@Riztazz @akrom23 
Found something interesting in regards to this, definite proof of how it should work: https://www.wowhead.com/bluetracker?topic=13087818929#135929566858

> Melee attack: MAX(5, SourceCombatReach + TargetCombatReach + 4/3) + IfSourceAndTargetAreRunning(8/3)
Ranged attack: SourceCombatReach + TargetCombatReach + AttackRange + IfSourceAndTargetAreRunning(2)
AoE: TargetCombatReach + AttackRadius + IfSourceIsRunning(2)

**Comment by SuddenDeath** [comment]
and `IsRunning` would mean running, aka not when you're walking(>30% slow).
