### ISSUE TITLE
Shamanistic focus talen bug

### ISSUE THREAD

**Issue by Kiizhan** [SunwellWoW/Sunwell-TBC-Bugtracker#2260]
Description: 
So when you get the focused state from the Shamanistic focus talent, if you auto attack before you use the effect (shock) the effect disappears. This is a huge deal to us shamans and needs to be fixed. 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by runt481** [comment]
Shamanistic Focus seems to be consumed by each attack from a Searing Totem as well.

**Comment by chidyco** [comment]
+1 on this, pretty bad bug.

**Comment by dogshep-zz** [comment]
Confirmed as well

**Comment by Wojtyas** [comment]
Reported here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2048

**Comment by Shadowkill22** [comment]
Guys it is most importnat talent in enhancement tree, could you please fix that ?

The issue is ONLY the fire totem which one is probably consider as shock, so ONLY autoattack of Fire totem is actually consuming this talent.
