### ISSUE TITLE
[NPC] Private Hendel Missing

### ISSUE THREAD

**Issue by Nadiirr** [SunwellWoW/Sunwell-TBC-Bugtracker#2264]
Private Hendel is missing.

Invisible to players & GM's. 

.respawn in the area does not work to spawn him.

possible it has to do with the quest he has.
http://db.hellfire-tbc.com/?quest=1324

**Comment by Nadiirr** [comment]
Same issue happening with NPC - Ringo
Shows he is spawned. Invisible to players and GM's - .respawn in the area does not spawn him.

**Comment by Wojtyas** [comment]
Added.
