### ISSUE TITLE
Willix the Importer

### ISSUE THREAD

**Issue by Adrestiah** [SunwellWoW/Sunwell-TBC-Bugtracker#2265]
Description: Willix  (id 2, guid 1259) Does not allow players to turn in the quest, upon completion of his escort he despawns

How it works: Willix  (id 2, guid 1259) Does not allow players to turn in the quest, upon completion of his escort he despawns

How it should work: Willix (id 2, guid 1259) should be present just before Razorfen Kraul entrance for those people who escorted him in RFK dungeon. If they have [Willix the Importer - 1144] quest completed then he should stay there. 

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
I am not sure even if it completes for everyone

**Comment by AIRewan** [comment]
can be done for all party member
turn in should be after the escort at the dungeon gate (inside) before he disappears. q done, he thanks and leave without reward T_T

**Comment by Alkimor** [comment]
Don't work. Up!
