### ISSUE TITLE
[Spell/Talent] Shamanistic Focus - Healing Wave - Lesser Healing Wave - Searing Totem

### ISSUE THREAD

**Issue by codey07** [SunwellWoW/Sunwell-TBC-Bugtracker#2266]
Description: 
Shamanistic focus is consumed by multiple different spells.  123

How it works: 
When you get the proc shamanistic focus from getting a crit, your next shock spell has it's mana cost reduced by 60%. Searing totem casting fireball and hitting the target consumes shamanistic focus. Healing wave and lesser healing wave consume shamanistic focus. Lightning Shield proc also consumes it.

How it should work: 
When you get the proc shamanistic focus from getting a crit, your next shock spell has it's mana cost reduced by 60%

Source (you should point out proofs of your report, please give us some source): In game, using the talent. near 100% reproduction 123

**Comment by Wojtyas** [comment]
Already in work. https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2260
