### ISSUE TITLE
[Mob] Goretusk spawning in tree

### ISSUE THREAD

**Issue by dogshep-zz** [SunwellWoW/Sunwell-TBC-Bugtracker#2267]
Description: Goreturk spawned in tree at 14.9,49.8 Redridge Mountains

How it works: Spawns in tree, sometimes unable to loot

How it should work: Should not spawn in tree. On top maybe... but not in!

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Can't find this boar :( Next time put ss please.

**Comment by Dootz** [comment]
i found it :)
