### ISSUE TITLE
[Minor] Item 'Volunteers Boots' not disenchantable.

### ISSUE THREAD

**Issue by b00marrows** [SunwellWoW/Sunwell-TBC-Bugtracker#2268]
The item 'Volunteers Boots' (obtained from a Blood Elf quest) are not disenchantable, see attachment.
![nope](https://user-images.githubusercontent.com/45547399/49348741-18234e00-f69f-11e8-891b-ebfe09951326.png)

**Comment by Zamesi** [comment]
I believe reputation items are not supposed to be disenchantable. If they were, one would have unlimited supply of enchant mats, thus ruining the economy of said mats or perhaps the whole server. Correct me if I'm wrong.

**Comment by b00marrows** [comment]
Yup, seem to be correct. Tho i don't remember it coming from a repeatable quest..
That's what i get fort having a 2AM giggle at whats usually a buggy number (65535) haha... now how do i close this...
