### ISSUE TITLE
[Shaman][Spell] Stormstrike and Flurry

### ISSUE THREAD

**Issue by codey07** [SunwellWoW/Sunwell-TBC-Bugtracker#2270]
Description: 
Stormstrike consumes stacks of Flurry
How it works: 
If you have flurry from a crit, stormstrike will consume 2 stacks of flurry if it hits the target, and 1 stack of flurry if it parries.

How it should work: 
Only auto attacks should consume Flurry

Source (you should point out proofs of your report, please give us some source): 
Playing and stormstrike consumes flurry stacks 100% of the time

**Comment by Riztazz** [comment]
Can we get some proof on that? Client files specify that auto attacks and spells that use melee weapon should trigger flurry
![image](https://user-images.githubusercontent.com/16348711/49592319-12648b80-f971-11e8-994b-3e3826acdd31.png)

**Comment by akrom23** [comment]
@codey07 Any news?

**Comment by Ad0naj** [comment]
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/137804-guide-enhancment-shaman.html
Stormstrike provides two major benefits to the Enhancement Shaman - it is capable of producing Windfury procs, and it will proc, but not consume, Flurry
https://noob-club.ru/index.php?topic=342.0
Штормстрайк дает энханс шаману два главных преимущества: с него может прокнуть виндфури, а также Flurry. Штормстрайк не использует «заряд» Flurry.(you can google translate it)
Btw it's 3.0+ guide idk if it helps.

**Comment by FrauHolle86** [comment]
- same goes for WF proccs --> they are not allowed to consume Flurry
- not sure if they do atm, but since you define it with "Successfull attack by Spell that use meele weapon"... just wanted to add this comment =)) cheers

**Comment by akrom23** [comment]
Cannot reproduce it.

3 stacks of Flurry:
![wowscrnshot_010219_111344](https://user-images.githubusercontent.com/1035215/50587812-b7468b80-0e7f-11e9-9923-f75f7d077f79.jpg)

2 stacks of Flurry afer use Stormstrike (1 stack consued by melee - look at combat log):
![wowscrnshot_010219_111351](https://user-images.githubusercontent.com/1035215/50587828-c7f70180-0e7f-11e9-97b5-13276876b637.jpg)

**Comment by FrauHolle86** [comment]
after 30min of testing and checking combat logs, i wasn't able to find any issues with flurry - for me, neither WF proccs nor Stormstrike were consuming Flurry stacks
