### ISSUE TITLE
Barrens Stealth Mobs

### ISSUE THREAD

**Issue by crystalfiction** [SunwellWoW/Sunwell-TBC-Bugtracker#2273]
Not sure if this was purposeful, but mobs with stealth I have encountered in the barrens aren't invisible, but just really faded out. I remember stealthed mobs to be impossible to see, but these are slightly visible.

**Comment by Dootz** [comment]
Hi, not all of them but some certainly should be just faded out.

**Comment by crystalfiction** [comment]
Alright, just making sure!
