### ISSUE TITLE
[Herb] Location in tree

### ISSUE THREAD

**Issue by dogshep-zz** [SunwellWoW/Sunwell-TBC-Bugtracker#2274]
Description: Location at 67.4,40.6 in Redridge is Peacebloom spawn in tree

How it works: In tree

How it should work: Not in tree

Source (you should point out proofs of your report, please give us some source): 

123

**Comment by Trentone** [comment]
Will copy my comment from here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2722:
"I have some work done on this matter. An algorithm to detect bugged spawns of creatures and GOs. PM me when you're gonna work on this."
