### ISSUE TITLE
Paladin Talent don't work.

### ISSUE THREAD

**Issue by ZeuzzzZz** [SunwellWoW/Sunwell-TBC-Bugtracker#2276]
Description: 
Paladin talent: Improved Seal of the Crusader 3/3.

How it works: 
Not giving a 3% undispellable (red) debuff on the target whenever you unseal it.

How it should work: 
It should give a 3%  crit buff on the target for everyone whom hit the mob! This is the only thing u want a retri paladin in your guild for.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/49378741-a3d3c380-f70d-11e8-9386-7020bd849a81.png)
Above you can see that debuff without Improved Seal of the Crusader - SPELL_AURA_MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE, amount: 0, base amount: 0

below is same debuff with 3/3 Improved Seal of the Crusader -
SPELL_AURA_MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE, amount: 3, base amount: 3
it's one debuff with 2 effects - no 2 debuffs with different effects

https://youtu.be/UyooXkH6mT8?t=25
