### ISSUE TITLE
Serpentbloom quest

### ISSUE THREAD

**Issue by sinfer** [SunwellWoW/Sunwell-TBC-Bugtracker#2277]
Description: Serpentbloom quest tricking you

How it works: When trying to gather Serpentbloom, it has only 1 VERY small spot where you can interact with it

How it should work: Aim anywhere at the flower and you can gather it.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Object is to small to CLICK on it, so its almost impossible. Should be larger "hitbox" of gob lol.
