### ISSUE TITLE
pet cant learn growl (rank 1)

### ISSUE THREAD

**Issue by queffsie** [SunwellWoW/Sunwell-TBC-Bugtracker#2278]
Description: 
Growl doesnt appear in the pet bar and cannot be found in the pet spellbook, also cant be taught at pet trainer, however rank 2 and 3 (and so on) I can see at the pet trainer

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
![obraz](https://user-images.githubusercontent.com/48881/49361738-ecbf5400-f6dc-11e8-8a1d-df0e23048b12.png)
Did you finish the whole Hunter quest line? If so, which race is your character?

**Comment by queffsie** [comment]
Yes, i finished the whole lvl 10 hunter quest line. As a Night elf. Still no growl.

**Comment by queffsie** [comment]
The final step of that quest line is "Training the beast", correct?
