### ISSUE TITLE
Lack of forgiveness for spells with cast time 

### ISSUE THREAD

**Issue by SuddenDeath** [SunwellWoW/Sunwell-TBC-Bugtracker#228]
The Problem: There is no/or wrong "forgiveness" range for spells with cast time when target runs out of range.

How it should work: After having started a spell cast, and target only runs a few yards out of range when then spell cast finish, then spell should still go through.

Channeling spells should have around 10 yards forgiveness range, normal spell forgiveness range should be about half of that.

How to reproduce: https://www.youtube.com/watch?v=EHgVdzshZmM

Proof:
https://youtu.be/YiGFcmohUcc?t=7m9s (spell goes through after shadowstep & out of range)

http://www.warcraftmovies.com/movieview.php?id=78449
@-12.38 or 11:30 on the bar(weird player)(cyclone on warlock, watch actionbar range)

**Comment by Riztazz** [comment]
Please test again, should be fixed after recent changes

**Comment by notsofamous** [comment]
Working
