### ISSUE TITLE
Suspicious hoofprints, Theramore Guard Badge and Black shield

### ISSUE THREAD

**Issue by jockeboschko** [SunwellWoW/Sunwell-TBC-Bugtracker#2280]
Description: 
Objects are not interactable but does not give a quest. 

How it works: 
Doesnt give quest

How it should work: 
Should give quest

Source (you should point out proofs of your report, please give us some source): 
https://vanilla-twinhead.twinstar.cz/?quest=1268#comments
https://vanilla-twinhead.twinstar.cz/?quest=1323
https://vanilla-twinhead.twinstar.cz/?quest=1269

123

**Comment by jockeboschko** [comment]
Actually you just cant pick em up before doing the quest Inspecting the ruins

**Comment by Wojtyas** [comment]
_Objects are not interactable but does not give a quest._
I dont get it, so they are interactable before u do prequest or not?

**Comment by Dootz** [comment]
yup , that's correct. Right now you need to complete "Inspecting the ruins" before you can take those quests. It 'll be changed.

**Comment by jockeboschko** [comment]
123
