### ISSUE TITLE
Horace Adler (Alliance Mage Trainer - Theramore) missing

### ISSUE THREAD

**Issue by LezChap** [SunwellWoW/Sunwell-TBC-Bugtracker#2283]
Description: 
Horace Adler, the Alliance Mage Class Trainer located in Theramore at the top of the tower is missing.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Horace_Alder

The Portal Trainer, implemented in the same patch, is there, but Horace isn't.

123

**Comment by Wojtyas** [comment]
Will be added in 2.4 content.
