### ISSUE TITLE
[QUEST] warrior's quest Death-tooth Jack 

### ISSUE THREAD

**Issue by Vizioner** [SunwellWoW/Sunwell-TBC-Bugtracker#2285]
Description: I cannot obtain a quest item form the strongbox 

How it works: 
When i killed boss, i took death's-tooth key form his corpse, problem appears when i try to open strongbox with this key. When i opened box, my key dissapear and loot doesnt show. So i cant loot this badge and cant complete this warrior quest. I meet 2 other ppl who had the same issue with this quest.  I abbadonded quest and took it again,  but it didnt help at all.

How it should work: 

I should be able to loot this strongbox when i open strongbox with key. 
Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2159
