### ISSUE TITLE
Fishing pools despawn after only one catch

### ISSUE THREAD

**Issue by RPAncap** [SunwellWoW/Sunwell-TBC-Bugtracker#2286]
Description: 
Everytime you fish from a pool it despawns.

How it works: 
Everytime you fish from a pool it despawns. So you only get one catch from a pool.

How it should work: 
You should be able to catch 2-4 fishes from a pool.

Source (you should point out proofs of your report, please give us some source): 
Easily reproducible - just go to any fishing pool and try it.

123

**Comment by frosten73** [comment]
confirmed this
on retail usually you catch 4-6 fish from school , but now only one

**Comment by nimeral** [comment]
Can confirm.

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2369

**Comment by RPAncap** [comment]
How is this marked as duplicate when I reported it day earlier than the other thread ? ;-) Shouldnt it be the other way around ?;-)

**Comment by Wojtyas** [comment]
Actually u're right but looks like dev opened 2nd report as first ;p

**Comment by RPAncap** [comment]
123
