### ISSUE TITLE
warlock stack

### ISSUE THREAD

**Issue by magicborne** [SunwellWoW/Sunwell-TBC-Bugtracker#2289]
Description: 
If there is more than 1 warlock use curse of agony or siphons life to the target,  only the first one applies, the others are not.

How it works: 
as the above

How it should work: 

all debuffs should apply to the target, so if 2 lock, then 2 curse of agony and 2 siphon life and so on.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Probably same or similar issue as here: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2193

**Comment by notsofamous** [comment]
Nothing stacks right now, any duplicate from buffs/debuffs are removed. Meaning druid HoTs don't stack, any dot (such as Moonfire, Shadow Word: Pain, Curse of Agony, Rend etc)
