### ISSUE TITLE
[NPC] Grimbooze Thunderbrew missing

### ISSUE THREAD

**Issue by ladym95** [SunwellWoW/Sunwell-TBC-Bugtracker#2290]
Decription: Grimbooze Thunderbrew is supposed to be on the Dagger Hills

How it works:  Grimbooze is missing, not on his camp

How it should work: supposed to be able to find Grimbooze Thunderbrew on his campto do quest.

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/npc=239/grimbooze-thunderbrew
![screenshot 29](https://user-images.githubusercontent.com/45559268/49368376-1a2df100-f721-11e8-8c39-dc267eebf84d.png)

**Comment by Wojtyas** [comment]
Added.
