### ISSUE TITLE
Prospecting

### ISSUE THREAD

**Issue by Notadruid** [SunwellWoW/Sunwell-TBC-Bugtracker#2292]
Description: skill is not working corectly

How it works: destroy all ores in stack and don't give gems

How it should work: destroy only 5 ores and give gems

Source (you should point out proofs of your report, please give us some source): https://tbc-twinhead.twinstar.cz/?spell=31252

**Comment by bhe0** [comment]
+1, this bug is repeatable every time. Prospecting is impossible to yield gems or JC levels until this is fixed.
