### ISSUE TITLE
[Ghostlands] 4-5 * [NPC]Shadowpine Oracle#16343 missing patrols at Amani Catacombs

### ISSUE THREAD

**Issue by Tenoutoften** [SunwellWoW/Sunwell-TBC-Bugtracker#2293]
**Description**: 
Location for this place is around the Amani Catacombs ~58, 25

**1st patrol:**
A [[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle) is not patrolling, the specific NPC I talk about is this one: 
![1](https://user-images.githubusercontent.com/34839199/49370326-2059a880-f6f4-11e8-8ceb-6c9cfe0ac404.jpg)

It can be seen patrolling to the right [here](https://youtu.be/Yd4y1gpRRaY?t=58) video is from a later patch of the game, but Ghostlands remained unchanged - it suppose to go around the cauldron and back down the road, and up the road and around the caldruon.

----

**2nd patrol:**
Inside the temple/cave is another [[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle) not patrolling but just hanging around
![2](https://user-images.githubusercontent.com/34839199/49370455-73336000-f6f4-11e8-9c48-6ebcbc187c99.jpg)

Can be seen patrolling [here](https://youtu.be/Yd4y1gpRRaY?t=134)

---

**3rd patrol:**
[[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle) not patrolling can be seen here: 
![3](https://user-images.githubusercontent.com/34839199/49370503-9b22c380-f6f4-11e8-8a78-e48031dbb830.png)

And as you can see on the video it is missing from it's spot, because it is patrolling the room behind it(can be seen [here](https://youtu.be/Yd4y1gpRRaY?t=148)), it can also been [here](https://youtu.be/45tFZB-2jwY?t=1)

---

**4th & 5th patrol:**
[[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle) at the road to the back entrance at 67, 27. At this road there is two different [[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle) stacked on top of each other at two places:
![4](https://user-images.githubusercontent.com/34839199/49370687-3ae05180-f6f5-11e8-8f82-cddc2e479fa8.png)
![5](https://user-images.githubusercontent.com/34839199/49370737-66fbd280-f6f5-11e8-949b-acddab01cbe6.jpg)
As can be seen [here](https://youtu.be/LSBN7vmkYZY?t=231) there is nothing stacked on top of each other strongly indicating further patrols.

Potentially the one in the path of the escort quest should be removed: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2298
A [[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle) that spawns through the quest is not spawning, while this spot has two of them instead of 1.

---

**Expected behaviour**: 
I expect the first [[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle) to patrol up and down the road and around the cauldron.

I expect the second [[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle) to patrol around the room and the hallway inside the chamber.

I also expect a third [[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle) to be patrolling this place

Most likely one or two [[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle) are suppose to patrol the back entrance road.

How it works: 
Currently there is zero [[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle)

How it should work: 
There should be 5 [[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle) patrols.

Source (you should point out proofs of your report, please give us some source): 
* [here](https://youtu.be/Yd4y1gpRRaY?t=58)
* [here](https://youtu.be/Yd4y1gpRRaY?t=134)
* [here](https://youtu.be/Yd4y1gpRRaY?t=148)
* [here](https://youtu.be/45tFZB-2jwY?t=1)
* [here](https://youtu.be/LSBN7vmkYZY?t=231)

**Comment by Wojtyas** [comment]
Let's move all issues to one report considering those tombs.
#2302
