### ISSUE TITLE
Private Thorsen STV rebel camp alliance

### ISSUE THREAD

**Issue by jonahsands** [SunwellWoW/Sunwell-TBC-Bugtracker#2294]
Description: 
Private Thorsen not working correctly and dredd did not want to assist me with this ingame and made me do some kind of ticket here

How it works: 
When i speak to him i get him to say "This is dangerous place, Humanrogue. Be careful around here."

How it should work: 
I should be able to turn in my quests and maybe get new quests? But again ofc i might be wrong.

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/a976790399603aaf63efa0bb567cc062

**Comment by Dootz** [comment]
Hi, i'm sorry about that. Private Thorsen should start a patrol every 5-10 minutes. While on patrol he'll be ambushed. If you save him he'll offer a quest. I'll change it so it will be possible to interact with him when he's in camp.
