### ISSUE TITLE
Guild

### ISSUE THREAD

**Issue by moeri666** [SunwellWoW/Sunwell-TBC-Bugtracker#2295]
Description: guild problems

How it works: Every time I go into the game, I disappear from the guild.

How it should work: After entering the game the character must be in the guild

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Probably today it will be fixed.
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2304
