### ISSUE TITLE
Class quests reward no experience

### ISSUE THREAD

**Issue by Aeded** [SunwellWoW/Sunwell-TBC-Bugtracker#2296]
Description: 
Shaman class quests reward no experience, noticed this while doing Call of Water quest line. None of the quest gave experience.

How it works: 
Quest do not reward experince

How it should work: 
All class quest should reward experience equal to the experience rewarded for ordinary quest at given level.

Source (you should point out proofs of your report, please give us some source):

**Comment by MVMnn** [comment]
Its not only shaman - paladin quests also, and probably other classes too.
You should add more priority labels to this - its pretty dissapointing to go through class quests without exp rewards.

**Comment by nimeral** [comment]
Can confirm as a druid.

**Comment by nimeral** [comment]
Did my Trial of the Sea Lion and can say that the bug is present as of today.

**Comment by Wojtyas** [comment]
Probably got fixed with some core changes.

**Comment by nimeral** [comment]
Still bugged - Trial of the Lake (Horde) rewards zero experience, and I'm afraid it'll be the same with Trial of the Sea Lion...
