### ISSUE TITLE
First aid debuff

### ISSUE THREAD

**Issue by Aeded** [SunwellWoW/Sunwell-TBC-Bugtracker#2297]
Description: 
When you cast first aid (any bandage) on friendly player, he recieves two "recently bandaged" debuffs instead of only one. 
Also first aid has unlimited channeling range. If rogue sprints away while im channeling first aid, it still works at 40yd+

How it works: 
First aid on other players gives them two recently bandaged debuffs insted of one
First aid channeling range is unlimited

How it should work: 
First aid should give only one debuff all the time
First aid channeling should break if target runs out of the range that is required to use the bandage.

Source (you should point out proofs of your report, please give us some source):

**Comment by ahlens** [comment]
Here is a screenshot showing that I've received double FA debuff when one of the party members was trying to use bandages on me.

![wowscrnshot_120518_091151](https://user-images.githubusercontent.com/23612673/50033246-ec398e00-fff7-11e8-801b-29408fbf4160.jpg)

**Comment by koostosh** [comment]
Could not reproduce.
