### ISSUE TITLE
[Ghostlands][NPC]Shadowpine Oracle#16343 should run towards their target on agro and during combat rather than walking

### ISSUE THREAD

**Issue by Tenoutoften** [SunwellWoW/Sunwell-TBC-Bugtracker#2298]
Description: 
[[NPC]Shadowpine Oracle#16343](https://www.wowhead.com/npc=16343/shadowpine-oracle) are currently stuck in walk speed.
Can be seen [here]

How it works: 
Currently walk towards you when aggro-ed, can be seen [here](https://www.youtube.com/watch?v=LBhVTQxg1AM&feature=youtu.be) 

How it should work: 
They should be running towards you on agro, can be seen [here](https://youtu.be/Yd4y1gpRRaY?t=153)

Source (you should point out proofs of your report, please give us some source): 
Retail proof [here](https://youtu.be/Yd4y1gpRRaY?t=153)

**Comment by Wojtyas** [comment]
Let's move all issues to one report considering those tombs.
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2302

**Comment by Tenoutoften** [comment]
Alright let's do that
