### ISSUE TITLE
Pets in party

### ISSUE THREAD

**Issue by Aeded** [SunwellWoW/Sunwell-TBC-Bugtracker#2299]
Description: 
Party members pets are not viewed as party members (the name colour is not light blue as for other party members, but rather dark blue, as for other non-party players)

How it works: 
party auras are not affecting the pets (tested with stoneskin totem&warlock pet)

How it should work: 
Pets and all other units that are owned by party members should be party members themselves and should recieve party auras.

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
![obraz](https://user-images.githubusercontent.com/48881/50384574-c0d53400-06c6-11e9-84a7-bc14f3f8dd1f.png)
