### ISSUE TITLE
Charge face mechanic

### ISSUE THREAD

**Issue by SuddenDeath** [SunwellWoW/Sunwell-TBC-Bugtracker#230]
The Problem: Currently there is no additional mechanic in place that makes you face the target after a charge.

How it should work: You should always face the player you charged when the charge comes to a stop.

Proof:
https://youtu.be/4JnQaXSHzEE?t=12m19s
https://youtu.be/GYUbaSCjCTU?t=1m7s
https://youtu.be/cyGOAFV0SkE?t=17m20s (gnome charge)
https://youtu.be/cyGOAFV0SkE?t=16m31s (gnome charge)

**Comment by Nadiirr** [comment]
Working <3
