### ISSUE TITLE
Guild Issue

### ISSUE THREAD

**Issue by Aathma** [SunwellWoW/Sunwell-TBC-Bugtracker#2304]
Description: 
Everytime I logout of my Draenei Paladin Aathma, I am removed from my guild, Same for another who is a Draenei Shaman named Kyuss.

It doesn't happen on my other characters at all.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by SunwellTracker** [comment]
We're working on it. This bug is caused by the mess in database. We'll fix it today.

**Comment by Dennyks** [comment]
"We'll fix it today."   Is it fixed yet?

**Comment by SunwellTracker** [comment]
It's already fixed.

**Comment by nimeral** [comment]
The bug still exists, a char was removed from my guild yesterday while I know for sure they didn't quit (we're in the same room irl). Didn't happen today though. Char's name is Rusali if it helps.
