### ISSUE TITLE
AH Bidded gold is not returning back if you buyout same position

### ISSUE THREAD

**Issue by netherneth** [SunwellWoW/Sunwell-TBC-Bugtracker#2306]
Description: AH Bidded gold is not returning back if you buyout same position

How it works: If you bid and then buyout the same position on AH you dont get back your bidded gold

How it should work: You should get back the gold you bidded. 

Source (you should point out proofs of your report, please give us some source): Accidentally bidded on a gun and then bought it out - did not recieve the bidded gold. No screenshots but you can check gold logs, charname = Dzen (horde)

**Comment by akrom23** [comment]
There is actually no bug here.
When you buyout, then your payment is reduced by your last bid. Check your gold.

**Comment by netherneth** [comment]
Yeah I checked my gold so I spent double the amount

**Comment by akrom23** [comment]
So next time when you bid and then buyout something, give me 2 screenshots of your gold: before buyout, and after that.
