### ISSUE TITLE
Priest Bug Stamina

### ISSUE THREAD

**Issue by groveunder** [SunwellWoW/Sunwell-TBC-Bugtracker#2307]
Description: 
Stamina buff. When at 100% hp with the stamina buff. And reapplying It causes you to lose HP. 

How it works: 
Whilst already having  Power word Fortitude on self and at 100% hp, And re-casting it, you lose hp as if you get the buff for the first time again.

How it should work: 
Hp should stay at 100% HP if you already have the buff.

Source (you should point out proofs of your report, please give us some source): 
No source. I know its not meant to do that reee.

**Comment by grand-lotus-iroh** [comment]
My priest fort buff has 30% and when I "reapply" a fort onto others who have same rank, they get more stamina and lose life. Perhaps update the active buff tooltip on players too if a "30% improved fort" is on them. Instead of 8 Stamina it would say 10 Stamina for example (rank 2).

**Comment by groveunder** [comment]
Still doing it.

**Comment by akrom23** [comment]
#2102.
