### ISSUE TITLE
Warsong spells not working

### ISSUE THREAD

**Issue by Druidsniffer** [SunwellWoW/Sunwell-TBC-Bugtracker#2313]
Description: 
Playing Warsong as Alliance, placing any spell on Horde i get the message "invalid target" 

How it works: 
Placing a spell prints message "invalid target" 

How it should work: 
Placing a spell should kill a lot of hordes.

Source (you should point out proofs of your report, please give us some source):

**Comment by netherneth** [comment]
Looks like your ALT is stucked and each spell is trying to be selfcasted

**Comment by Druidsniffer** [comment]
Correct. Chips. reminds me of that what has no life. Classic BTC. :) Case closed.
