### ISSUE TITLE
Entangling root

### ISSUE THREAD

**Issue by Lillkillen91** [SunwellWoW/Sunwell-TBC-Bugtracker#2314]
Description:  Entangling root does not work inside caves etc

How it works: it says: only works outdoors

How it should work: should be able to root inside caves

![wowscrnshot_120318_161754](https://user-images.githubusercontent.com/45567626/49382996-092cb200-f718-11e8-96b5-b52c85c169c2.jpg)

**Comment by Notadruid** [comment]
Read skill tip, lul

**Comment by Wojtyas** [comment]
![image](https://user-images.githubusercontent.com/22802214/49385197-27e17780-f71d-11e8-8808-f951eb4356ef.png)
