### ISSUE TITLE
Zangamarsh quest npc 

### ISSUE THREAD

**Issue by xrewz** [SunwellWoW/Sunwell-TBC-Bugtracker#2317]
Description:  quest npc bugs out after you turn in quest Back the mushrooms

How it works:  you cant talk to her after someone turn in quest

How it should work: 
you should be able to talk to her.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
One specific npc or all of them? More details please.

**Comment by xrewz** [comment]
My bad forgot to put npc name in:D Watcher Leesa'oh is her name

**Comment by Wojtyas** [comment]
Looks like Dootz already figured out what u meant :P cheers
