### ISSUE TITLE
Wound poison ignores nature resistance

### ISSUE THREAD

**Issue by SuddenDeath** [SunwellWoW/Sunwell-TBC-Bugtracker#232]
The Problem: Wound poison ignores nature resistance

How it should work: It's a nature spell and should follow the resistance formulas as seen in proof below.

How to reproduce: get a demo lock with a felhunter and spam shiv on it with wound poison on your OH wep.

Proof:
http://wow.gamepedia.com/index.php?title=Nature_resistance&oldid=1416422
http://wow.gamepedia.com/index.php?title=Resistance&oldid=1603715

**Comment by SuddenDeath** [comment]
Should not be able to partially resist.
It does direct damage and applies a healing reduction debuff.

http://wowwiki.wikia.com/wiki/Binary_spell?oldid=1432574

**Comment by akrom23** [comment]
@SuddenDeath 
I don't understand.

> The Problem: Wound poison ignores nature resistance

vs

> Should not be able to partially resist.

**Comment by akrom23** [comment]
Not respond - closed.
