### ISSUE TITLE
The Bestial Wrath! ~prio to fix it~

### ISSUE THREAD

**Issue by Carneyy** [SunwellWoW/Sunwell-TBC-Bugtracker#2322]
Description: 
Whenever attack mob and meanwhile use Bestial Wrath target aggro you. Doesn't matter if you make dmg or let your pet make mob will go on you after you use BW.

How it works: 
Reset aggro after you use Bestial Wrath. Was fine before last spell in hunter tree.

How it should work: 
No break aggro of mobs, give extra dmg and reduce spell mana costs. 

Source (you should point out proofs of your report, please give us some source): 
[CLICK](https://imgur.com/a/p5nCb6O)

**Comment by headshot420** [comment]
this bug is very very frustrating, will get even more frustrating when people starting doing dungeons.
