### ISSUE TITLE
Pickpocket in party

### ISSUE THREAD

**Issue by Naanemthe** [SunwellWoW/Sunwell-TBC-Bugtracker#2323]
Description: 

Pickpocket in party makes loot shared among the group
How it works: 
Pickpocket in party makes loot shared among the group

How it should work: 

No shared loot with the group when pick pocketing.
Source (you should point out proofs of your report, please give us some source):

**Comment by yairomi** [comment]
Can confirm, pick pocketed loot shouldn't be shared with others.
