### ISSUE TITLE
Hunter Auto Shot getting delay after every swing

### ISSUE THREAD

**Issue by primeropein** [SunwellWoW/Sunwell-TBC-Bugtracker#2326]
Description: 
After every auto shot cast there is a small hole between the autos where the hunter does nothing for 0,1-0,2 sec , Im not talking about the 0,5 sec fire animation, but after that

How it works: 
If u simply just auto on a dummy there is small holes between every auto.

How it should work: 

When u simply just auto a dummy there should be no holes in ur autos
Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/ed9HblL

**Comment by primeropein** [comment]
Seems to be even bigger gaps in MS spikes, looks like MS is affecting it, which shouldnt happen

**Comment by Lunasoll** [comment]
Also, when hunter moves between auto shot swings, there is a delay as well.

**Comment by primeropein** [comment]
Well ur char is supposed to have 0,5 sec delay after movement if the swing is rdy, cause Auto Animation requires 0,5 sec

**Comment by MiekZer** [comment]
I confirm that issue with me too.
I'm sometimes having gap after auto shot. Sometimes not.
This breaks hunter dynamic a lot.

**Comment by primeropein** [comment]
Well esp adding into that steady shot haste scaling formula doesnt work either ,(see https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2894 )
hunters are gonna have bad time

**Comment by MiekZer** [comment]
Also during this gap the spell queue doesn't apply (as it ~applies (not without trouble) during the autoshot 0.5s cast) so that totally break the rotation sometimes.

**Comment by MiekZer** [comment]
Quick question for the op we were wondering what's the addon you use to get this graphic

**Comment by MiekZer** [comment]
Still not fixed. It also mess the opening since the autoshot is not starting (maybe due to same problem or not). If you spam steady at the opening it's supposed to start your autoshot timer right after the first steady shot aka when you start combat and queue your second steady shot. Actually not the case so you have to wait for your autoshot to start in order to start your rotation.

OH and btw shots are still not queued correctly during autoshot shooting animation.

**Comment by Jonsbe** [comment]
Yeap still not fixed. Also would love @primeropein to tell that autoshot addon

**Comment by akrom23** [comment]
To be honest - I really dont know what delay you're talking about. I tested that and don't observed weird delays. Could anybody provide video?

**Comment by akrom23** [comment]
Any news here? Give me more screenshots or explain exactly, what does not work.

**Comment by akrom23** [comment]
@primeropein @MiekZer @Jonsbe News?
