### ISSUE TITLE
Quest: Thunderbrew Lager does not require Hops to complete

### ISSUE THREAD

**Issue by Magnive** [SunwellWoW/Sunwell-TBC-Bugtracker#2327]
Description: 
The repeatable quest Thunderbrew Lager has no requirements for completing it. 

How it works: 
The quest can instantly be accepted without even requiring any Hops in your inventory. A friend of mine tested it with 5+ Hops in his inventory and could complete the quest any number of times without any hops being subtracted.

How it should work: 
The quest should require 5 Hops.

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Thunderbrew_Lager

**Comment by Wojtyas** [comment]
Will be implemented with next restart.
