### ISSUE TITLE
Thunderbrew hops not required to get item

### ISSUE THREAD

**Issue by Olivern8** [SunwellWoW/Sunwell-TBC-Bugtracker#2328]
Description:
The repeatable quest Thunderbrew Lager has no requirements for completing it.

How it works:
The quest can instantly be accepted without even requiring any Hops in your inventory. For the test, I had 7 inside my inventory, and I managed to acquire 10 of the Lagers. Given that they sell for around 1 silver to vendor, someone could, in theory, make money off this. A friend of mine tested this without having hops in his inventory.

How it should work:
The quest should require hops as an item in inventory.

Source (you should point out proofs of your report, please give us some source):
123
![wowscrnshot_120318_182618](https://user-images.githubusercontent.com/45572868/49393634-beb43100-f729-11e8-9598-d63b9eb5792a.jpg)
![wowscrnshot_120318_182624](https://user-images.githubusercontent.com/45572868/49393642-c378e500-f729-11e8-872f-b571b7c07b55.jpg)
![wowscrnshot_120318_182627](https://user-images.githubusercontent.com/45572868/49393657-c7a50280-f729-11e8-8073-f9913d5c1061.jpg)

**Comment by ujellyx** [comment]
confirm

**Comment by Wojtyas** [comment]
Will be implemented with next restart.
