### ISSUE TITLE
Mallet of Zul'Farak

### ISSUE THREAD

**Issue by RPAncap** [SunwellWoW/Sunwell-TBC-Bugtracker#2329]
Description: 
The part where you enchant your mallet on the portal doesnt work. It doesnt register. So you cant use it to summon the boss in Zul Farak.

How it works: 
The part where you enchant your mallet on the portal doesnt work. It doesnt register. So you cant use it to summon the boss in Zul Farak.

How it should work: 
You should be able to enchant the mallet.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120318_194107](https://user-images.githubusercontent.com/44553524/49394393-09d34180-f734-11e8-864f-8c59784eda21.jpg)

**Comment by Wojtyas** [comment]
Damn dude you should repair ur gear.

Area location is requirement should be corrected, item cannot be used while should be.
![image](https://user-images.githubusercontent.com/22802214/49395435-c928f780-f736-11e8-881e-5c6ba5d1ed89.png)
