### ISSUE TITLE
Mob leashing

### ISSUE THREAD

**Issue by SuddenDeath** [SunwellWoW/Sunwell-TBC-Bugtracker#233]
How it should work: There should be a set distance, but the mob should also take into account any direct damage/threat that has been dealt to the mob within the last X seconds before it resets.

Currently on retail that time is 10 seconds, and was most likely the same in TBC.

Basically this is what makes kiting mobs possible.

How to reproduce:
Video I recorded: https://www.youtube.com/watch?v=2lmjIJjLr_c

Proof:
https://youtu.be/y83l9eK8OJs?t=12s
original source: http://www.warcraftmovies.com/movieview.php?id=78629

**Comment by Wojtyas** [comment]
Fixed & implemented.
