### ISSUE TITLE
Ritual Of Summoning

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#2331]
Description: You currently cannot summon people inside your instance or raid ID

How it works: Summon a player inside an instance, lose the shard, no summon.

How it should work: You should be able to summon people ALREADY INSIDE your instance, currently you cannot

Source (you should point out proofs of your report, please give us some source): http://wowwiki.wikia.com/wiki/Ritual_of_Summoning Everything you've listed about being able to summon people in instances is indicative of the player receiving the summon being outside of the instance, whatever fix was made is also preventing you from summoning people already inside your instance, this is how people were able to join raids late and get summoned to the raid and avoid roaming pather respawns in MC or AQ20 and Kara god bless.

**Comment by Wojtyas** [comment]
Accordin to below wowhead comment I highly doubt:
_Can't be used in Zul'aman as of patch 2.4.2, strangely. Can be annoying when someone accidentally runs back after dying to Jan'alai and forgets the scouts have a fast respawn timer._

Do you have any screen/video/comments or something that will prove ur words?

**Comment by Jseay1313** [comment]
https://web.archive.org/web/20070312154911/http://www.wowwiki.com/Ritual_of_Summoning

**Comment by Jseay1313** [comment]
A Warlock (with two party members standing with the Warlock to assist - this always applies except when using a Meeting Stone), can summon from anywhere in Azeroth and all but one zone in Outland to wherever the Warlock is in Outland or Azeroth. A Warlock can also summon any character from anywhere in the specific instance he is in to himself.

A Warlock cannot summon a person from the world map to the inside of an instance or summon a person out of an instance to the world map.

**Comment by Jseay1313** [comment]
https://forum.nostalrius.org/viewtopic.php?f=40&t=11842

**Comment by Jseay1313** [comment]
https://alt.games.warcraft.narkive.com/XWfAAVC9/warlock-summons-inside-of-instances

**Comment by Jseay1313** [comment]
Summoning

    The meeting stone has largely replaced the need for a warlock to summon party/raid members to the major instances. However, occasionally, summons are used inside instances to bring latecomers to the party, or outside instances if there are a lot of monsters between the meeting stone and instance entrance. NOTE: As of patch 2.4, warlocks can now summon persons outside of instances INTO the instance. This makes the spell invaluable should you lose a party member mid-instance and need a replacement. You no longer need to send a group to the meeting stone if you have a warlock in the group. Zul'Aman is the only exception to this rule.

Clearly states OUTSIDE of the instance, from https://wow.gamepedia.com/Warlock_instance_grouping_guide

**Comment by Jseay1313** [comment]
WoW Icon update.png Patch 1.1.0 (2004-11-07): Target of summoning ritual must already be in the same instance if caster is in an instance. 

https://wow.gamepedia.com/Ritual_of_Summoning

**Comment by Wojtyas** [comment]
fair enough pal :D

**Comment by jockeboschko** [comment]
"Ritual of Summoning can be used to summon players into instances if they meet the instance requirements."

http://wowwiki.wikia.com/wiki/Patch_2.4.0



Should be able to summon people inside from wherever in world not just inside to inside instances.

**Comment by ZaoQ** [comment]
Can you guys fix this issue and make warlocks great again?

**Comment by Afgann** [comment]
@ZaoQ There were some problems with the fix, i'll try to correct them soon.

**Comment by Trolltilla** [comment]
Still not working

**Comment by GeorgieTragnar** [comment]
currently you can summon players that are already inside the instance, and those that are outside you can't
