### ISSUE TITLE
Cone of Cold spell cone is too small

### ISSUE THREAD

**Issue by Jazo420** [SunwellWoW/Sunwell-TBC-Bugtracker#2335]
Description: 
The Mage ability: Cone of Cold has a much smaller than intended spell cone.

How it works: 
It only hits things directly infront of you and sometimes not even that, it has a mind of its own

How it should work: 
It should have a very wide cone, not sure how wide but much bigger than what the server has already.

Source (you should point out proofs of your report, please give us some source): 
I clipped the issue right here 
https://puu.sh/CbRnx/ba929786ae.mp4

**Comment by vititus** [comment]
yes please.. fix this!

**Comment by vititus** [comment]
how has this not been looked into yet?


push.

**Comment by akrom23** [comment]
https://wow.gamepedia.com/index.php?title=Cone_of_Cold&oldid=1432387

> The area of effect is a 90 degree arc region

Seems to work good now.
