### ISSUE TITLE
[Shaman] Elemental Focus

### ISSUE THREAD

**Issue by Aeded** [SunwellWoW/Sunwell-TBC-Bugtracker#2336]
Description: 
Elemental Focus talent doesnt work as it should.

How it works: 
1. Elemental focus stack gets consumed when spell hits, rather than when spell is casted
2. Elemental focus stack gets consumed by other demaging spells that are not supposed to consume this buff (eg. searing totem)
3. Elemental focus stack gets consumed by mana free spell. (Overload procs) (Didnt test, but judging by the quality of this server it is probably bugged too)

How it should work: 
1. Elemental focus should be consumed on succesful spell cast, not hit.
2&3. Elemental focus stacks should be consumed only by shocks and lightning spells that cost mana (are not mana-free procs from overload or mana free attacks from totems)

Now more of a global thingy bonus bug (couldnt test yet, just assume its bugged):
Spell cast "parameters" (mana cost, spell dmg, crit, etc..) should be checked upon succesful spell cast, not at the begining of casting. That means if you gain elemental focus mid-cast, it should work for the current cast aswell. 

Source (you should point out proofs of your report, please give us some source): 
watch any ele vid from retail..

**Comment by Wojtyas** [comment]
Already reported pal, will be fixed soon.

**Comment by Aeded** [comment]
Same title doesnt mean same content of report, by the way..
