### ISSUE TITLE
Watcher Leesa'oh

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2339]
Description: Watcher Leesa'oh in Zangarmarsh

How it works: Watcher Leesa'oh bugs out after you hand out 15 mushrooms to her and she does her RP walk so nobody can turn in quests to her.

How it should work: You can deliver quests to her after she did her RP walk

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
I believe Dootz already fixed it here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2317
will be on realm soon

**Comment by Avishai97** [comment]
ok cool
