### ISSUE TITLE
use of 100% ground mount avaiable for lvl 14?

### ISSUE THREAD

**Issue by klipeta** [SunwellWoW/Sunwell-TBC-Bugtracker#2340]
Description: mount question

How it works: 

How it should work: 
arent 100% mounts avaiable from lvl 60?
![wowscrnshot_120318_232210](https://user-images.githubusercontent.com/45576517/49403939-b9211000-f756-11e8-85e5-d12bd9c0defd.jpg)
![wowscrnshot_120318_235242](https://user-images.githubusercontent.com/45576517/49403941-b9211000-f756-11e8-8d13-815dca0544f3.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by SunwellTracker** [comment]
It was quest item, not mount.
