### ISSUE TITLE
Pet doesnt use any special abilities

### ISSUE THREAD

**Issue by pawlica12** [SunwellWoW/Sunwell-TBC-Bugtracker#2342]
Description: 
Title says it all, my pet after a servers crash has permamently stopped using any of his abilities. All he can do is autoattack and move.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Even after dismissing and calling back?

**Comment by YoshGit** [comment]
Had issues with this - I think their pet abilities are unlearned. Going into pet training and reteaching abilities fixed this.

**Comment by pawlica12** [comment]
> 
> 
> Even after dismissing and calling back?

Yes, i tried everything

**Comment by pawlica12** [comment]
> 
> 
> Had issues with this - I think their pet abilities are unlearned. Going into pet training and reteaching abilities fixed this.

This worked, lol, sounds ridiculous but why the abbilites got even unlearnt at the first place, lel
