### ISSUE TITLE
Pet problem

### ISSUE THREAD

**Issue by Huntthehorde** [SunwellWoW/Sunwell-TBC-Bugtracker#2349]
Description: 
Whenever i revive my pet, the pets action bar disappears. 
How it works: 
my pets action bar does not appear upon revival.
How it should work: 
my pets action bar should appear as i revive my pet.
Source (you should point out proofs of your report, please give us some source): 
WoW Hunter, so hands on experience, primary source, me.

**Comment by TheRealestMcCoy** [comment]
I use Elvui. I have yet to see this problem. If you have a adodn it may be your addon or something in default ui if you dont.
