### ISSUE TITLE
spam auto chat text channel change when flying

### ISSUE THREAD

**Issue by grand-lotus-iroh** [SunwellWoW/Sunwell-TBC-Bugtracker#2353]
When I fly from Westfall to Lakeshire...

![image](https://user-images.githubusercontent.com/1291364/49408387-0aff7100-f72a-11e8-879f-58a93af87e2b.png)

**Comment by sinfer** [comment]
thats because the FP flies on the border of Duskwood & Elwynn. Think it happends only if you fly to redridge from westfall? Not a bug imo.

**Comment by TheRealestMcCoy** [comment]
thats normal even on retail today

**Comment by grand-lotus-iroh** [comment]
i've only ever played private servers, never retail, and i've never seen this auto channel change spam.

cheers
