### ISSUE TITLE
Sparkleshell Tortoise (Lightning Shield) Thousand Needles Salt Flats

### ISSUE THREAD

**Issue by Tyton89** [SunwellWoW/Sunwell-TBC-Bugtracker#2354]
Description: All tortoise mobs in Thousand needles have a ridiculous buff that makes them nearly unkillable doing 8-9 damage return on every attack done to them

How it works: They don't have this buff

How it should work: They act like a normal turtle

Source (you should point out proofs of your report, please give us some source): 
Sparkleshell Snapper's Lightning Hide reflects 9 Nature damage to (X)

**Comment by Wojtyas** [comment]
They should reflect 1x proc each player's hit but it seems to proc x8-10 :o
![image](https://user-images.githubusercontent.com/22802214/49434341-48104580-f7b4-11e8-8401-a64d4f7ea21a.png)
