### ISSUE TITLE
Protection paladin talent: Anticipation bug

### ISSUE THREAD

**Issue by nirvanahh** [SunwellWoW/Sunwell-TBC-Bugtracker#2356]
Description: 
The talent increases defense by 4 points for every 1 talent point to a maximum of five talent points 4x(5) for a maximum of +20 defense

How it works: 
the talent in game is currently only increasing your maximum defense stat, and not your current defense stat. For example my character has 120 defense total and the skill is at 120/120 right now. When I add the talent points my defense changes to 120/124 or 120/128 and not 124/124 or 128/128

How it should work: 
When you add the talent points into anticipation, both the base skill level and the max skill level should be boosted by 4 points per talent level to a maximum of +20 defense skill. For example if my character would normally have 120 defense at their level and 120/120 is my current skill max, then with the talent maxed at five points my defense stat should be 140/140 

Source (you should point out proofs of your report, please give us some source): 
![anticipation](https://user-images.githubusercontent.com/45579456/49410829-32573d80-f72c-11e8-922c-35b91befb0da.PNG)

**Comment by xethra89** [comment]
[2130](https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2130) Bug report already created, but this one does have a screenshot demonstrating the issue.
