### ISSUE TITLE
Lockboxes

### ISSUE THREAD

**Issue by blizzy1997** [SunwellWoW/Sunwell-TBC-Bugtracker#2361]
Description: 
had a lockbox unlocked and when i opened it. i got nothing not even an empty loot box 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, some of it went live. If you still have a lockbox that have empty loot please let me know which one.

**Comment by Phildo9** [comment]
Not resolved, issue still occurred with Eternium Lockbox and Mithril Lockbox. I have other lockboxes too but don't really feel like continuing to loose them just for testing. Wasted 2 Arcanite Keys already :(

**Comment by Dootz** [comment]
Eternium Lockbox and Mithril Lockbox will drop something always from next update. I'll try to go over other lockboxes this week.

**Comment by pinkisnotgay** [comment]
@Dootz Thorium Lockboxes broken aswell
