### ISSUE TITLE
Blade's Edge Mountains Quest: What Came First, the Drake or the Egg?

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2367]
Description: Quest in BEM

How it works: When you click eggs they don't spawn dragons

How it should work: When you click eggs they spawn dragons

Source (you should point out proofs of your report, please give us some source):

**Comment by Swiplington** [comment]
Yep doesn't work

**Comment by rychersky** [comment]
Still not working as of December 12.

**Comment by ryosuki** [comment]
bump - not working dec 22

**Comment by blackabbath** [comment]
doesn't work 26/12

**Comment by dzigibau1** [comment]
doesn't work 03.01.2019.

**Comment by Clanatk** [comment]
I also have this issue.

**Comment by Dootz** [comment]
fixed
