### ISSUE TITLE
Blade's Edge Mountains Quest: Fire At Will!

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2368]
Description: Quest in Blade's Edge Mountains

How it works: When you use Naturalized Ammuniton on the Fel Cannons it just says "You have no target"

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
123

**Comment by Avishai97** [comment]
Kinda high priority imo as the followup gives preraid bis loot

**Comment by Bzmode** [comment]
still bugged as of now

**Comment by NoCandy** [comment]
Still bugged gives good reward so its sucks that you have to skip it.

**Comment by MarcusStu** [comment]
Still bugged as of today. https://i.imgur.com/YY2S1tP.png

**Comment by codey07** [comment]
gives very important prebis necklace for many specs

**Comment by ZaoQ** [comment]
still bugged

**Comment by Dootz** [comment]
Will be fixed with next server update.
