### ISSUE TITLE
Fishing school

### ISSUE THREAD

**Issue by oldcobb** [SunwellWoW/Sunwell-TBC-Bugtracker#2369]
Description: fishing school loot

How it works: fishing in any school only allows you to catch exactly 1 (fish) item. You can never catch more then 1 item (fish).

How it should work: fishing in a school should allow you to catch multiple items (fish). This should be from 1 to 5? 

Source (you should point out proofs of your report, please give us some source):

**Comment by Seductive99** [comment]
I can confirm this bug, for a source go to steamwheedle port or even Ratchet I believe. Fish at any of the pools whether its a wreckage or a school of fish. You will as far as I remember ALWAYS only catch one fish/item.

**Comment by Bawzillex** [comment]
Im fishing for 3 days now and every single pool in any area got this bug. Pls fix it this makes fishing almost dead speacially if u want the fishes for alchemy.

**Comment by Paroof** [comment]
confirmed - when You open loot window while fishing from schools or derbis You can loot only one item and then the window still shows the item that is impossible to loot tho.
![wowscrnshot_120418_170519](https://user-images.githubusercontent.com/26213381/49455520-9f7bd900-f7e7-11e8-867c-ec6f2b02ec04.jpg)

**Comment by frosten73** [comment]
https://legacy-wow.com/fishing-guide-pools-and-wreckage/ this is guide about fishing in schools
3-6 fish from pool, not one

**Comment by Darrgoth** [comment]
Fix this please asap! It's a game breaking fishing bug!

**Comment by Dootz** [comment]
Will be fixed with next server update. Could you please leave feedback after change is implemented if its working as expected now? I'll give an update once it will go live.

**Comment by Bawzillex** [comment]
Normal fish pools work now. 
The wreck pools ( which are the fun ones ) are still bugged and gives only 1 chest.
The random fishing interupption is still in the game too.

**Comment by frosten73** [comment]
i check now in tanaris
its working bad now ;D
From cast i catch 2x fish from school firefin/eel . But pool out after 1 catch of fish. 
It is necessary that in each school/wreck it was possible to throw a fishing rod and catch 3-6 fish/chests. But catch one fish per attempt.

**Comment by Seductive99** [comment]
Just checked it out in Tanaris, the pools now have a chance to give multiple items however it does so by giving you them with 1 looting of the pool, the pool then disappears, this was not how it used to work on retail where you always received 1 item per looting, but had multiple looting attempts per pool.

Also the Mithril Bound Trunk wreckages do not allow multiple looting of the trunks from what I was able to tell.

**Comment by RPAncap** [comment]
The way it is supposed to work is that you catch 1 fish per cast. And the pool will despawn after like 3-5 catches. You are not supposed to get 3 fishes per one cast. How it currently works after the fix. 

Also as other guy said - you still only loot one box from floating wreckage.,

**Comment by Dootz** [comment]
should be fixed now. Although you still may receive multiple fishes per cast. We'll change it with next restart.
