### ISSUE TITLE
What we don't know...

### ISSUE THREAD

**Issue by Purre2** [SunwellWoW/Sunwell-TBC-Bugtracker#2370]
Description: 
One of the final quests in Blood Watch, to get the Tabard of the Hand etc

How it works: 
He doesn't transform you into a Blood Elf 

How it should work: 
He will turn you into a Blood Elf, so you can talk to the prisoner at Blood Watch.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2158
