### ISSUE TITLE
[Recipe: Transmute Primal Might]

### ISSUE THREAD

**Issue by xrewz** [SunwellWoW/Sunwell-TBC-Bugtracker#2372]
Description:  [Recipe: Transmute Primal Might] recipe seems to be spawning a bit to fast. 

How it works: 
recipe seem to be spawning every hour.

How it should work:  Im pretty sure the respawn timer should be somewhere between 4-12 hours. All i know for sure is that 1 hour is to fast.

Source (you should point out proofs of your report, please give us some source):  http://wowwiki.wikia.com/wiki/Limited_quantity_recipes 
Only decent source out there. Several= around 6

**Comment by xrewz** [comment]
Would be nice if this was fixed before shop goes live. otherwise half server gonna have it in no time.

**Comment by Denziz** [comment]
I agree, this seems kind of broken, I believe 6 hours seems legit and would be a good timer on the respawn.

Kind regards from Siegehardt.

**Comment by Zeeldax** [comment]
Totally agree with this! Having 1 hour respawn is just to fast, I believe it was around 6-12 hours on retail and that´s what it should be on sunwell as well.

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.

**Comment by jrydin** [comment]
still seems to be on 1h cooldown? is the fix implemented?
