### ISSUE TITLE
Blackout cannot be triggered by shadowguard

### ISSUE THREAD

**Issue by ymli1989** [SunwellWoW/Sunwell-TBC-Bugtracker#2373]
Description: 
Blackout (priest shadow talent) cannot be triggered by shadowguard (troll priest's skill)

How it works: 
It seems Blackout cannot be triggered by shadowguard ( tried nearly 50 times).

How it should work: 
Blackout should be triggered at 10% chance by each damage done caused by shadowguard.

Source (you should point out proofs of your report, please give us some source):

**Comment by SunwellTracker** [comment]
Please show us some video or provide calculations.

**Comment by ymli1989** [comment]
Should have 10% chance triggered by each damage done by shadow guard but never saw. And I have tried hundred times when I am leveling. 
The calculation: 
The probability of that due to my luckless = 0.9^100（at least 100 times）= 0.0073%，
So it is a bug at probability （at least）of 99.9927%.
Calculation done.
