### ISSUE TITLE
Wyrmcult Zealot / Scout

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2374]
Description: Mobs in BEM

How it works: 
They cast Fireball
They keep patroling while in combat

How it should work: Don't think they should hehe

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
- [ ] remove Fireball spell.
- [ ] still patrolling in combat (core)
