### ISSUE TITLE
Slam resets auto attack timer.

### ISSUE THREAD

**Issue by gremlin93** [SunwellWoW/Sunwell-TBC-Bugtracker#2378]
Description: Warrior skill slam resets auto attack timer.

How it works: 
I have a weapon speed of 3.3 and when i auto attack and then cast slam, when the slam ends i have to wait 3.3 seconds until the next auto attack. This problem repeats with all weapons i have used so far.

How it should work: 
I do an auto attack and cast slam. Now with a weapon speed of 3.3 i should have to wait only 1.8 seconds until the next auto attack. 

Source (you should point out proofs of your report, please give us some source):  Ehhh... common sense? :S not trying to be sassy :D

**Comment by Hapsterchap** [comment]
I believe this is a feature back in TBC. Hence why warriors would have to wait until they auto to cast Slam. You can find people talking about it in various guides for warrior and such back from TBC :)

**Comment by Azathothh** [comment]
That's how it was during TBC. Common sense isn't best source for that expansion :P
Patch 3.0.2 (14-Oct-2008): Slam now suspends the weapon swing timer rather than resetting it.
