### ISSUE TITLE
No JC trainer in TB

### ISSUE THREAD

**Issue by peanutboobs** [SunwellWoW/Sunwell-TBC-Bugtracker#2379]
Description: 
the Jewelcrafting trainer in TB is missing

How it works: 
there isnt one

How it should work: 
http://wowwiki.wikia.com/wiki/Nahari_Cloudchaser
http://wowwiki.wikia.com/wiki/Jewelcrafting_trainers
here it says there should be one

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Jewelcrafting_trainers

**Comment by Mikov1605** [comment]
He was added in cataclysm
Proof:
https://www.wowhead.com/npc=52657/nahari-cloudchaser

**Comment by peanutboobs** [comment]
well fuck me my bad sorry ^^
________________________________
Fra: Mikov1605 <notifications@github.com>
Sendt: 4. december 2018 09:15
Til: SunwellWoW/Sunwell-TBC-Bugtracker
Cc: peanutboobs; Author
Emne: Re: [SunwellWoW/Sunwell-TBC-Bugtracker] No JC trainer in TB (#2379)


He was added in cataclysm
Proof:
https://www.wowhead.com/npc=52657/nahari-cloudchaser
