### ISSUE TITLE
[Subzone] Caverns of Time

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#238]
- [ ] Custodian of Time(GUID 0, entry 20129) spawns in the air. Walks through objects

- [ ] Time Warder(GUID 23441, entry 19918) should patrol around in the area outside durnholde

https://youtu.be/XR6muO4bUR0?t=7m1s

- [x] Time Watcher(GUID 23430, entry 19918) walks around in the air and patrols on the platform, should be flying in circles high up in the air. Not sure how many, but feels like there are too many right now.

- [ ] **Edit: still loads of Time Watchers hanging around that shouldn't be there. 
Time Watcher(GUID 23436/23438/23426/23440, entry 19918)**

https://youtu.be/XR6muO4bUR0?t=5m3s

- [ ] Missing Warden of Time at these cords: https://i.gyazo.com/d10536f664f66a7479ad70ab4101a1d8.png

https://youtu.be/XR6muO4bUR0?t=8m6s
https://youtu.be/XR6muO4bUR0?t=6m46s

- [ ] Missing conversation between Andormu(GUID 23450, entry 19932) and Nozari(GUID 23451, entry 19933). 

https://youtu.be/XR6muO4bUR0?t=8m18s

- [ ] Arazdomu(GUID 23454, entry 19936) should always be patrolling with Soridormi (GUID 68211, entry 19935)
https://www.wowhead.com/npc=19936/arazmodu#comments:id=245562:reply=31193

- [ ] Soridormi (GUID 68211, entry 19935) should sometimes enter a spectral faerie dragon form, unknown trigger?
https://www.wowhead.com/npc=19935/soridormi#screenshots
https://youtu.be/XR6muO4bUR0?t=5m22s

- [ ] Custodian of Time (GUID 23462, entry 19950) outside of BM should be casting something on the Crocolisk she's standing in front of

https://youtu.be/XR6muO4bUR0?t=8m40s

- [ ] There should be a pair of custodian of time patrolling outside of durnholde, currently just 1 there doing nothing

https://youtu.be/XR6muO4bUR0?t=7m49s
https://youtu.be/-SEcxo58t6c?t=51s

- [ ] Missing error message for Old Hillsbrad. It should say "You must first complete the quest, "The Caverns of Time" before you may enter Old Hillsbrad."

https://youtu.be/XR6muO4bUR0?t=8m5s

- [ ] Wrong error message for Black Morass. It should say "You must first save Thrall in Old Hillsbrad by helping him escape from Durnholde Keep before you may enter the Black Morass.". Current Message: "You can't enter Black Morass until you rescue Thrall from Durnholde Keep."

https://youtu.be/XR6muO4bUR0?t=9m

- [ ] 'The Caverns of Time' quest (10277) should work like this according to wowhead comments:
You don't have to stay near the custodian that walks around, you should get credit for the quest as long as you are near her when the tour is finished (at the original quest giver). Currently she despawns if you get too far away from her and you do not get a 'failed' tag in your quest log. The debuff for this quest (Custodian of Time, 34877) does not work. This is in place to prevent you from spam summoning them as you don't have to follow the NPC.

https://www.wowhead.com/quest=10277/the-caverns-of-time#comments

Can't find any info about the 2 Custodians standing outside of the collapsing portal (future strat portal), but they probably should not be just standing there.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=XR6muO4bUR0
https://www.youtube.com/watch?v=-SEcxo58t6c

**Comment by Azathothh** [comment]
> Time Warder(GUID 23441, entry 19918) should patrol around in the area outside durnholde
https://youtu.be/XR6muO4bUR0?t=7m1s

It's actually Time Watcher with Time Cloak spell id 34699 
There's also  34702 - Time Cloak which turns them to wisps - which happens when they fly down and go to Hyjal portal. I've been reading that they should turn to crocolisks when going to BM portal, but couldn't find any video or even spell which does that :(

**Comment by notsofamous** [comment]
@Azathothh  NPCs with Time Cloak are swimming in the air instead of walking on the ground
