### ISSUE TITLE
Recover the Cargo!

### ISSUE THREAD

**Issue by Daubeny** [SunwellWoW/Sunwell-TBC-Bugtracker#2380]
Description: 
Quest  [Recover the Cargo!] Can only loot 5/6 salvaged cargo when trying to loot 6th piece it says "requires shipwreck debris" even tho i'm standing in it

How it works: 
When looting 5th cargo it despawns

How it should work: 
should be able  to loot 6/6

Source (you should point out proofs of your report, please give us some source): 
Tried it twice and abandoned it and tried again didn't work

**Comment by jrydin** [comment]
worked fine days ago, weird

**Comment by EdzBrz** [comment]
The spawn rate for the cargo however is forever, not sure this is intended.
