### ISSUE TITLE
Ring of Blood

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2384]
Description: Quest chain in Nagrand

How it works: Bosses are kitable, last boss doesn't spawn

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Mikov1605** [comment]
Last boss is the ogre standing next to questgiver. He isn't spawning at the ring. He should be at the q giver and respawn there too after being killed (7 min timer). Mogor is his name
