### ISSUE TITLE
[Quest] Book of the Acients - Ranazjar Isle (Desolance)

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#2388]
Description: 
its chain Quest, on some part of it you have to summon the Naga boss by Places gem in Naga statue.
But the problem is... there is no action there, you can do nothin with this gem.

How it works: 

How it should work: 
Player shoud be able to put gem on statue to summon boss.

Source (you should point out proofs of your report, please give us some source): 

![wowscrnshot_120318_142141](https://user-images.githubusercontent.com/43553985/49430228-c1a33600-f7aa-11e8-9433-0a5e1dd9b66d.jpg)

**Comment by Wojtyas** [comment]
Already reported.
