### ISSUE TITLE
Rare Mob: Voidhunter Yar maybe not spawning

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2389]
Description: Rare mobs: We have seen all rare mobs from hellfire to blade's edge except Voidhunter Yar, checked every step he is supposed to be able to be at, maybe he doesn't spawn?

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Added, he needs patrol.
