### ISSUE TITLE
Hellfire Ramparts - all dungeon's path is freaky

### ISSUE THREAD

**Issue by worugru** [SunwellWoW/Sunwell-TBC-Bugtracker#239]
Decription: 
All the dungeon have really weird pathing issues.

How it works: 
Paths that mobs run to player when they are agrod is quite weird on some parts of the dungeon. Also some mobs do go underground, I could not find them in the middle of the floor but I was able to target mobs that are underground and they just poped on my face when I got in agro range. One of them being the first patrol that comes between the first two mobs at dungeon.

How it should work: 
..

Source :
https://streamable.com/9rvyy  (just charging literally the first mob, look at the path of the charge)

**Comment by Nadiirr** [comment]
I tested this today and it appears fixed.
