### ISSUE TITLE
Prairie Wolf Alpha Odd Loot Table

### ISSUE THREAD

**Issue by Hapsterchap** [SunwellWoW/Sunwell-TBC-Bugtracker#2390]
Description: 
Prairie Wolf Alpha's in Mulgore drop excessive amounts of the same item.

How it works: 
They drop lots of Pioneer Belts, Warrior's Bracers and Journeyman's Cloaks. Out of the 10 I killed, I received 11 items.

How it should work: 
I don't think they're supposed to drop this much gear.

Source (you should point out proofs of your report, please give us some source): 
Using the addon MobInfo2 to track drop rates.
https://i.imgur.com/aNsRsf6.png
https://i.imgur.com/13RRkys.png
https://i.imgur.com/I0fAiMl.png

**Comment by Hapsterchap** [comment]
I also noticed this happening with the Thunder Lizards in Thunder Ridge, Durotar. They dropped excessive amounts of Burnt Leather Boots. Didn't get a screenshot though

**Comment by Wojtyas** [comment]
Still drop high amount of mentioned items.

**Comment by ZackForester** [comment]
So much for 1x loot.

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.

**Comment by Dootz** [comment]
please verify @Wojtyas  :)
