### ISSUE TITLE
[Engineering] Target Dummy doesnt drop any items

### ISSUE THREAD

**Issue by RPAncap** [SunwellWoW/Sunwell-TBC-Bugtracker#2393]
Description: 
Target dummies made by engineering are supposed to drop items when killed - so you can recoup some of the cost - it also has a chance to drop a Fused Wiring - an item that used in many important vannila recipes - the only other way to farm them is very low drop chance from several mobs or running gnomeregan.

How it works: 
They dont drop anything.

How it should work: 
They should drop stuff.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=4366/target-dummy#comments

**Comment by Wojtyas** [comment]
Still can't loot Target Dummy (2673).

**Comment by RPAncap** [comment]
Still doesnt work.

**Comment by RPAncap** [comment]
Still doesnt work.

**Comment by Proseccobabe** [comment]
Still nothing, they should also not run after you.
