### ISSUE TITLE
[Zangarmarsh][Zabra'jin] Quests are not obtainable at level 61

### ISSUE THREAD

**Issue by dicelol** [SunwellWoW/Sunwell-TBC-Bugtracker#2394]
Description: 
Quests in Zabra'jin in Zangarmarsh are not obtainable at level 61.

How it works: 
Quests in Zabra'jin are not obtainable at level 61.

How it should work: 
Quests in Zabra'jin should be obtainable at level 60 for horde.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Quest:WANTED:_Boss_Grog%27ak

**Comment by Wojtyas** [comment]
Fixed & implemented.
