### ISSUE TITLE
[Dangerous]Strange thing on sunwell, ALERT

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#2395]
Just saw something like that
![image](https://user-images.githubusercontent.com/43579401/49438591-2072aa80-f7bf-11e8-996f-8efd7192071f.png)
got there, nothing happened, and i didnt became those 1000 sc. i changed my password fast.
I dont think its yours , dear Admins.
Some kind of spam/hacker done it

**Comment by Mikov1605** [comment]
he got banned, thanks

**Comment by Wojtyas** [comment]
We will ban every kind of this behaviour.
