### ISSUE TITLE
Hunter Viper Sting doesnt drain mana

### ISSUE THREAD

**Issue by Butterfly1298** [SunwellWoW/Sunwell-TBC-Bugtracker#2400]
Description: 

How it works: 
Viper Sting doesnt drain mana enemy

How it should work: 
Viper Sting should drain mana from Enemy

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Works fine to me.
@Butterfly1298 Needs a confirmation or screenshot if doesn't work in your case.

**Comment by pivke** [comment]
I can confirm that this spell does not work, I got no mana at all from this spell.

**Comment by akrom23** [comment]
@pivke Screenshots please.

**Comment by pivke** [comment]
https://i.imgur.com/TPrXmb9.jpg)
https://i.imgur.com/JoufMFn.jpg

Img 1 - Viper Sting cast, 14 mana left.
Img 2 - Viper Sting expired. 104 mana. (passive mana regen)
Should have gained 616 mana from Viper Sting. So I got Zero mana from that spell. 

Though my friends have said that Viper sting has worked when a hunter used it in PVP.

**Comment by akrom23** [comment]
Well, I see this mob do not have mana.

**Comment by pivke** [comment]
Forgive me, you are correct, tried on a different mob and it showed in the log that it drained.
