### ISSUE TITLE
[NPC] Venture Co Enforcer - Buff stacking

### ISSUE THREAD

**Issue by Talir-Shogun** [SunwellWoW/Sunwell-TBC-Bugtracker#2401]
Description: The NPCs in the Boulder Lode Mine stack 5-6 buffs on each other.

How it works: Buff all npcs around

How it should work: Should buff only self

![wowscrnshot_120418_132650](https://user-images.githubusercontent.com/45596181/49442725-a9431380-f7ca-11e8-91c4-f4caa594b036.jpg)

Source (you should point out proofs of your report, please give us some source): screenshot

**Comment by Wojtyas** [comment]
Still present.

![image](https://user-images.githubusercontent.com/22802214/49526759-ce11b680-f8b0-11e8-9f79-419202ea0a9b.png)
