### ISSUE TITLE
Hunter - Feign Death

### ISSUE THREAD

**Issue by Butterfly1298** [SunwellWoW/Sunwell-TBC-Bugtracker#2402]
Description: 
Enemy doesnt lose me out of target. Pets and Player doesnt.  (PVP)

How it works: 

Enemy doesnt lose me out of target (PVP)

How it should work: 

They should lose the hunter in the target for a second and casts/attacks will be interupted

Source (you should point out proofs of your report, please give us some source):

**Comment by headshot420** [comment]
it works for me, if you are dueling someone and he is in your party, FD  won't work, that is a retail bug. not sure if that is what your issue is though.

**Comment by Butterfly1298** [comment]
So other Hunter or Warlock Pets lose you out of target and even the player? Even when I was dead they stayed and didnt went back to the owner in PvP.

**Comment by headshot420** [comment]
@Butterfly1298  if you are an Alliance player and you duel another Alliance player, if you are in a party with that player you are dueling, feign death will not work. If you are Alliance and you are fighting horde, Feign death will make the enemy lose you as target.

are you fighting opposite faction ? or friendly faction?

**Comment by Butterfly1298** [comment]
I dont mean a duel. I mean when I PVP Alliance VS Horde.

Other Faction.

**Comment by headshot420** [comment]
oh ok, sorry bout that, it seems to work for me, but I'll keep an eye out for it.

**Comment by Butterfly1298** [comment]
thank you

**Comment by Butterfly1298** [comment]
Works now. Dunno why, but it works now! It interrupt the enemy cast

**Comment by baade123** [comment]
pets should stop attacking u when u FD but they dont
