### ISSUE TITLE
Hunter - Display Bug

### ISSUE THREAD

**Issue by Butterfly1298** [SunwellWoW/Sunwell-TBC-Bugtracker#2404]
Description: 

How it works: 

When you change the Aspect from Cheetah to others there is still the symbol of the cheetah aspect

How it should work: 

Well the Symbol should change to the aspect you actually have

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Screen buddy?

**Comment by Butterfly1298** [comment]
Yes. On the upper right corner, you see the bug, but when you have Xperl like me, it shows it right under the Characters Healthbar

**Comment by Butterfly1298** [comment]
How can I add screens in here? Dunno

**Comment by Butterfly1298** [comment]
![wowscrnshot_120418_160216](https://user-images.githubusercontent.com/45596170/49450861-3479d480-f7de-11e8-8f6e-3b9b5c7eee24.jpg)
![wowscrnshot_120418_160225](https://user-images.githubusercontent.com/45596170/49450862-3479d480-f7de-11e8-89ed-fd8bad4a4715.jpg)
![wowscrnshot_120418_160235](https://user-images.githubusercontent.com/45596170/49450864-35126b00-f7de-11e8-9b0c-446ac987c59f.jpg)
![wowscrnshot_120418_160238](https://user-images.githubusercontent.com/45596170/49450865-35126b00-f7de-11e8-8f52-ba027c0ce33e.jpg)

**Comment by Butterfly1298** [comment]
nvm

**Comment by Azathothh** [comment]
Works perfectly fine for me, must be your addon issue, please try again without an addon
