### ISSUE TITLE
[Reputation/Quest] Stolen Silver

### ISSUE THREAD

**Issue by Talir-Shogun** [SunwellWoW/Sunwell-TBC-Bugtracker#2405]
Description: I did quest Stolen Silver in Barrens. It awarded 250 rep with Orgrimmar but I also become friendly with Silvermoon. Not sure if it's intended, quest bug or a more general reputation bug.

How it works: Received 250 reputation with Orgrimmar but also become friendly with Silvermoon

How it should work: Silvermoon rep should not be influenced by Orgrimmar rep gain

![wowscrnshot_120418_123943](https://user-images.githubusercontent.com/45596181/49443333-769a1a80-f7cc-11e8-9488-50a4a7c4ea22.jpg)

Source (you should point out proofs of your report, please give us some source): screenshot

**Comment by Wojtyas** [comment]
Blackrock Summoner (4463) 545 hp, his Imp Minion (12922) 718 hp.

**Comment by Wojtyas** [comment]
There is always small % of rep added to other faction upon completing quest.
