### ISSUE TITLE
Thrash attacks can proc thrash

### ISSUE THREAD

**Issue by KimmoKM** [SunwellWoW/Sunwell-TBC-Bugtracker#2408]
Description: 
A number of mobs in WoW have various versions of ability Thrash (http://db.hellfire-tbc.com/?search=thrash#spells) that gives extra swings.

How it works: 
The extra attacks gained can proc Thrash additional times, resulting targets being hit 6, 9 or even more times.

![2018-12-04-151450_1920x1080_scrot](https://user-images.githubusercontent.com/1533992/49444351-8d923a00-f7d7-11e8-9576-f64b2e475635.png)

How it should work: 
Thrash shouldn't proc from its own attacks. Moreover, the proc chance seems uncharacteristically high, although that's not something I'm prepared to investigate right now.

**Comment by Wojtyas** [comment]
Indeed thrash should give only two more extra swings.
