### ISSUE TITLE
Elemental focus bug

### ISSUE THREAD

**Issue by Ellendir80** [SunwellWoW/Sunwell-TBC-Bugtracker#2410]
Description: It should reduce the mana cost of your next 2 offensive abilities by 40% after landing a spell critical strike with fire nature or lighting spell.

How it works: If you are bing hit by a mob after getting ELEMENTAL FOCUS Proc and you are casting new spell without it being fully casted BOTH STACKS of ELEMENTAL FOCUS go away (go wasted).

How it should work: The 2x Stacks should disappear only after timing of the buff is over or after you cast 2x spells.

Source (you should point out proofs of your report, please give us some source): Best would be for GM to test this with a mob hitting him and the proc being on a few times to see for himself. Thanks

**Comment by Azathothh** [comment]
#2137  #2336 #2284
