### ISSUE TITLE
Netherstorm Quest: Shutting Down Manaforge B'naar

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2411]
Description: Quest in Netherstorm

How it works: Only the people clicking the Manaforge gets credit when its done.

How it should work: Everyone in group gets credit.

Source (you should point out proofs of your report, please give us some source):

**Comment by Avishai97** [comment]
NOT ONLY B'NAAR
ALSO DURO AND ARA

**Comment by Wojtyas** [comment]
Fixed & implemented.
