### ISSUE TITLE
Netherstorm Quest: Dr Boom

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2413]
Description: Quest in Netherstorm to kill a boss

How it works: When you try to throw bomb on the boss nothing happens

How it should work: When you try to throw a bomb on the boss a bomb is thrown at the boss

Source (you should point out proofs of your report, please give us some source):

**Comment by Fuzedknight** [comment]
Can confirm it's broken, item Boom's Doom cannot be used ever even when directly in his face.
