### ISSUE TITLE
Thrall - Orgrimmar spamming his line

### ISSUE THREAD

**Issue by WillowWisp** [SunwellWoW/Sunwell-TBC-Bugtracker#2414]
### Description: 
The chat is filled with his line

### How it works: 
He's spamming his line

### How it should work: 
He should only say it once (I guess?)

### Source (you should point out proofs of your report, please give us some source): 
[https://imgur.com/a/ft3tbeH](url)

**Comment by Wojtyas** [comment]
Temporary fixed. Probably some quest emote remains after qc.

![image](https://user-images.githubusercontent.com/22802214/49450056-81f54200-f7dc-11e8-8acd-80c4f7ee7001.png)
