### ISSUE TITLE
[Rogue] Talent Surprise Attacks not working

### ISSUE THREAD

**Issue by Sollmyr** [SunwellWoW/Sunwell-TBC-Bugtracker#2415]
Description: 
Talent Surprise Attacks is not working correctly. It states that your finishing moves can no longer be dodged. This is not the case on the server.

How it works: 
https://i.imgur.com/5wYQ7lm.jpg
As you can clearly see in the combat log, Eviscerate was dodged by a mob while the talent was active.

How it should work: 
The finishing moves should not be dodged,

Source (you should point out proofs of your report, please give us some source):

**Comment by ghost** [comment]
Confirmed this is not working.

https://gyazo.com/8a50339856f31f1fddbee5356d562b36

**Comment by EdzBrz** [comment]
![wowscrnshot_120718_202827](https://user-images.githubusercontent.com/1191714/49668548-d6a7ef80-fa5e-11e8-95af-13ef8d97783f.jpg)

See combat log.

**Comment by lino7** [comment]
Bug still in game why closed?
![3232](https://user-images.githubusercontent.com/48138230/53665753-fc671e00-3c74-11e9-9b83-cfaa3bd92bd9.jpg)
