### ISSUE TITLE
Hunter pet dissapeared

### ISSUE THREAD

**Issue by queffsie** [SunwellWoW/Sunwell-TBC-Bugtracker#2417]
Description: 
Whilst questing I and my pet died. When I tried to revive the pet, it said that I dont have a pet. 

How it works: 
As above

How it should work: 
I should be able to revive my pet again. His loyalty was level 5

Source (you should point out proofs of your report, please give us some source):

**Comment by xethra89** [comment]
Call your pet again, then revive it. You can only revive a pet if it is active. So if your pet is dismissed due to out of range/you died, you cannot revive it. This is not a bug. 

What is possibly a bug is the fact the pet dismissing, but would need to test it myself.
