### ISSUE TITLE
SW:P on a target already in combat doesn't put you in combat

### ISSUE THREAD

**Issue by Ghettomagus** [SunwellWoW/Sunwell-TBC-Bugtracker#2418]
Description: Using Shadow Word: Pain (possibly other dots as well, dont know cant try.) on a target that is already in combat with another player doesn't put the priest in combat.

How it works: ^

How it should work: Casting a spell on an enemy should put you in combat

Source (you should point out proofs of your report, please give us some source): My dad is blizzard.

**Comment by akrom23** [comment]
Combat starts with 1. tick.
