### ISSUE TITLE
Quest: Kodo Roundup, All kodos are already tamed 123

### ISSUE THREAD

**Issue by eldewall** [SunwellWoW/Sunwell-TBC-Bugtracker#2419]
Description: 
Quest: Kodo Roundup

How it works: 
All Kodos are already tamed

How it should work: 
Should be Kodos that is not already Tamed (Ancient, Aged etc)

Source (you should point out proofs of your report, please give us some source): 

![wowscrnshot_120418_164750](https://user-images.githubusercontent.com/87705/49454019-94737980-f7e4-11e8-94b7-e46d60bfa07f.jpg)

**Comment by Wojtyas** [comment]
Same script issue like in other cases - npcs don't return to their normal state.

**Comment by Wojtyas** [comment]
Fixed & implemented.
