### ISSUE TITLE
Hunter - Pets dont lvl their Spells

### ISSUE THREAD

**Issue by Butterfly1298** [SunwellWoW/Sunwell-TBC-Bugtracker#2420]
Description: 
I have got my Ravager since lvl 9 but its Ranks doesnt went up. Bite Rank 2 - Gore Rank 2.  He is lvl 35 and should have grown in talent.

How it works: 

They stay on the level since you tamed it.

How it should work: 

Normally it should level up some level.

Source (you should point out proofs of your report, please give us some source):

**Comment by xethra89** [comment]
You have to tame pets with the next ranks of those abilities to allow you to train your pet the next levels. 

http://web.archive.org/web/20070408161247/http://petopia.brashendeavors.net/index.shtml

Browse through that website for more information.
