### ISSUE TITLE
Fear doesn't break on damage

### ISSUE THREAD

**Issue by Swiplington** [SunwellWoW/Sunwell-TBC-Bugtracker#2424]
Description: 
Fear doesn't break on damage

How it works: 
Warlock fears you, his friends and himself nuke you, fear never breaks so its a 8 second stun

How it should work: 
Fear should have a chance to break on damage

Source (you should point out proofs of your report, please give us some source): 

Getting fucked by warlocks over and over with no counter play

123

**Comment by Khryx** [comment]
Ya this need to be fixed asap, thanks

**Comment by Wojtyas** [comment]
With what kind of damage did u put on feared target? direct/dot? what is in pvp or on creature? and what rank of fear did u use?

azathothh edit:  please mention as well levels of your characters

**Comment by Swiplington** [comment]
Any damage, ive been hit my dots, direct spells, mobs, pala/warr melees. it doenst rly matter.

It affects both pvp and creatures. 

I've noticed it since level 20ish and is still happening at level 50 so i guess that answers the levels/skill rankings

**Comment by pleasse** [comment]
yeh this need a asap fix there must be some kind of damage threshold!!!!!!! i have tried to google for some info but i cant find any specific info, how ever fear is not a "stun" it needs to break, i think its around like 10-20%hp could be more because they did nerf fear threshold in wotlk but i literally been killed in fears not "Ok", finding info about the numbers seems hard tho. and in retail it was kinda rng could break early aswell. either way the fear has to break or there gonna be alot of mad people.

**Comment by Jseay1313** [comment]
still a thing, people getting beat on by 4-5 players a pet and a mob and lasting the entire duration of a psychic scream or fear

**Comment by sippycupmcjr** [comment]
If you are below level 60 then this is (probably) blizzlike.

Check:
http://wowwiki.wikia.com/wiki/Fear_effect
http://wowwiki.wikia.com/wiki/Fear

Most notably:
[From TBC] Patch 2.1.0 (22-May-2007): "Chance to break crowd control from damage: The increased chance for a spell to break from taking a critical strike has been removed. Instead, **all targets over level 60 have a slightly larger chance to break out of crowd-controlling effects when they take damage**."
[From WotLK] 3.1.0 (14-Apr-2009): The damage threshold to break early has been significantly reduced.

**Comment by pleasse** [comment]
yeh, it might be like that on lower levels, i remember fear was obnoxious,
its sad that there is zero info about the actual numbers of thresholds...
as stated in .3.1.0 wotlk patch it was nerfed significantly. i was trying
to find random tbc pvp vids from retail, sadly its hard to find consistent
footage, but it seems at 70 that the threshold was 10-30%, but i have not
bothered to do more digging about it. specific numbers seem to be hidden by
blizzard for some dumb reason x(

even in the 3.1.0 patch notes there is no mention about numbers "The damage
threshold to break early has been significantly reduced." i dont get it

Den tors 6 dec. 2018 kl 23:14 skrev sippycupmcjr <notifications@github.com>:

**Comment by pleasse** [comment]
i remember fear was super broken, even at lvl 70 it might just be that fear
under lvl 60-70 is busted as hell #vanilla no changes >.>

Den tors 6 dec. 2018 kl 19:09 skrev Jseay1313 <notifications@github.com>:

**Comment by Jseay1313** [comment]
Just did Blood Furnance last night and the zone was an absolute joke with fear. The damage was not breaking howl of terror or regular fear, and the feared mobs could run through other mobs and would not agro them. Please fix this, its absolutely trivializing these normal outland dungeons

**Comment by akrom23** [comment]
It depends on 2 factors:

- target's level
- damage

If fear is apllied on creature, than your chance to break is three times as small.
If you attack by DOT, than your chance to break is twice as small.

**Comment by akrom23** [comment]
The formula has been changed. Please, test it again after update.

**Comment by baade123** [comment]
I came here to QQ / write report on it but its already been done- plz fix asap

**Comment by Wojtyas** [comment]
Ok, with realm update few minutes ago we have changed fear break formula. It's minor change but probably will solve it, please gimme feedback here ;)
@baade123 @Jseay1313 @pleasse @sippycupmcjr @Swiplington @Khryx

**Comment by Wojtyas** [comment]
Looks fine, feel free to re-open if needed.
