### ISSUE TITLE
Priest hots and dots dont stack

### ISSUE THREAD

**Issue by darknessangelo** [SunwellWoW/Sunwell-TBC-Bugtracker#2425]
Description: 
Any of priset hots or dots dont stack on friendly or enemy target. It seems to be a global problem, not only for priests.

How it works: 
Its impossible to apply same hot or dot on one target from same class.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by joao-fidalgo** [comment]
HoT's shouldn't stack. The only HoT you can stack is Lifebloom.

**Comment by SunwellTracker** [comment]
The bug is on the testing phase. Will be implemented tomorrow.

**Comment by Azathothh** [comment]
Should be fixed now, if you'll notice anything stacking/not stacking in a wrong way please report it in new topic with as many informations as possible.
