### ISSUE TITLE
Hunter Pets become attackable after Shadowmeld

### ISSUE THREAD

**Issue by bhe0** [SunwellWoW/Sunwell-TBC-Bugtracker#2426]
Description: Night Elves who Shadowmeld will turn their pet unfriendly towards allied, non-party players, and the pet can be attacked (and killed) as if it were a normal mob. 

How it works: After Shadowmeld is used, the pet becomes attackable by friendly players who are not in your party. The pet isn’t aggressive but will have a red nameplate, players attacking the pet will also remain friendly towards the Hunter. However, if the pet is in Prowl while the Hunter is in Shadowmeld, then all is normal. 

How it should work: Night Elf Shadowmelds and the pet remains friendly towards allied players.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
#2300
