### ISSUE TITLE
Sitting does not guarantee a crit

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#243]
Decription: Sitting does not guarantee a crit

How it works: Sitting does not guarantee a crit

How it should work: If struck with a physical ability while sitting there should be a 100% chance of crit

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Please re-test after PTR update

**Comment by babno** [comment]
confirmed fixed
