### ISSUE TITLE
What We Don't Know...

### ISSUE THREAD

**Issue by daffake31011** [SunwellWoW/Sunwell-TBC-Bugtracker#2430]
Description: 

How it works: When you take this , nothing happened and you cant complete it.

How it should work: You accept quest, you get turned into blood elf, you get info and then you turn it in.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2158
