### ISSUE TITLE
Corki(nagrand)

### ISSUE THREAD

**Issue by Bzmode** [SunwellWoW/Sunwell-TBC-Bugtracker#2433]
Description: Is missing from his initial spot in the cage in burning blade ruins
 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Bzmode** [comment]
GM had to come in and force spawn him

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2431
