### ISSUE TITLE
[Quest] Rise! Obsidion!

### ISSUE THREAD

**Issue by Haradokz** [SunwellWoW/Sunwell-TBC-Bugtracker#2435]
Description: 

Quest in searing Gorge.

How it works: 

When you accept the quest nothing happens the event does not begin.

How it should work: 

When you accept the quest an even should begin and Obsidion and Lathoric the Black are killable.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented.

**Comment by Haradokz** [comment]
123
