### ISSUE TITLE
Base Critical Chance is incorrect for most(all) classes

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#2436]
Description: The base crit chance should be 5% for all classes/races, currently many classes are starting with either above or below 5% crit.

How it works: Level 1 character of nearly any class/race has incorrect base crit chance.

How it should work: 5% across the board, this is melee crit chance, not spell.

Source (you should point out proofs of your report, please give us some source): https://wow.gamepedia.com/Base_attributes
Crit

Players have 5% base crit for all classes, races, and levels

**Comment by akrom23** [comment]
Maybe some proofs or screeshots? You did some tests?

**Comment by akrom23** [comment]
No response.
