### ISSUE TITLE
+Weapon Damage Enchants working in Cat/Bear form.

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#2438]
Description: +weapon damage enchants are giving a damage bonus to druids in their shapeshift forms despite not gaining benefit from proc or + damage enchants in shapeshift form. Weapon stones probably work as well since they are under the same type of application to the weapon, and should also not benefit from + damage.

+weapon damage on actual equipment SHOULD work, so when fixing this keep in mind that +weapon damage stat from rings/trinkets does work for feral druids.

How it works: Currently cat/bear druids are gaining bonus damage from these enchants

How it should work: Only stat enchants should work on a druids weapon, no procs, no weapon damage, +9 weapon damage to a feral druid weapon is the equivalent to about 220 strength and is quite a huge unintended buff to their damage

Source (you should point out proofs of your report, please give us some source): https://forum.elysium-project.org/topic/22901-weapon-dmg-enchant-working-in-shapeshift/

https://www.wowhead.com/forums&topic=122891

https://vanilla-twinhead.twinstar.cz/?issue=7647

https://www.reddit.com/r/Nostalrius/comments/5do0iu/question_on_druid_and_weapon_enchants/

**Comment by babno** [comment]
Those sources are largely for vanilla, though the wowhead does have a comment supporting the idea that it is working correctly. As I recall weapon damage does work in forms, it is only proccing enchants like crusader or mongoose which do not.

**Comment by Jseay1313** [comment]
Weapon damage never worked, appreciate your input, multiple google responses showing it did not work until Cataclysm. The mechanics of the game largely did not change from tbc to vanilla, again + 17 weapon damage from stones and enchants are the equivalent of over 220 strength (and more) at 70, why would they ever intend on these enchants to be the equivalent of 5-6 pieces of gear?

**Comment by Jseay1313** [comment]
https://www.reddit.com/r/classicwow/comments/8ln449/how_does_a_druids_weapon_affect_feral_damage/

Again, a post for classic, but weapon damage should not work as mentioned because in TBC you're still using your claws. Weapon damage only started working when weapon skill started working for feral druids.

**Comment by Jseay1313** [comment]
https://legacy-wow.com/druid-feral-level-70/ Mentions nothing about weapon damage, which would be infinitely better than +35 agi for damage and threat.

**Comment by babno** [comment]
"+ 17 weapon damage from stones and enchants are the equivalent of over 220 strength (and more) at 70, why would they ever intend on these enchants to be the equivalent of 5-6 pieces of gear?"

Firstly you're mixing up strength and ap. 14ap=1dps, 14x17=238 ap. So is this item somehow 24 items then? https://tbc-twinhead.twinstar.cz/?item=28658. As to your new link, 17 damage for a tank druid is much worse than kitty since bears only attack every 2.5 seconds, meaning it's worth less than 100ap. Agi also gives armor and dodge in addition to the crit.

**Comment by Jseay1313** [comment]
ok so, in unequipping a dense triangle mace, which is 10 strength, the druid is losing only 1 top end damage, so when you you look at it in that manner, the druid is gaining 170 strength (+/- a few) from just a weapon stone and enchant. No other class benefits nearly as much from any enchant and stone in the game. Regardless of the math behind it, it's incorrect, a druids weapon is his claws, he gains no benefit other than stats. 

https://www.wowhead.com/forums&topic=142010

Even the second comment here from 2010 hints at it being a mechanic prior to blizzard changing it, damage on your weapon should in no way or form correlate to your actual damage.

https://www.wowhead.com/forums&topic=4205

To further emphasize on this, at the bottom +70 attack power is mentioned as the alternative to +35 agility in 2007, if weapon damage was even a thing you don't think the thousands of minds at wowhead and elitistjerks would've done this math? Because just from the enchant alone using your math, +9 weapon damage would be 126 AP.

**Comment by Jseay1313** [comment]
http://thedruidsgrove.org/archive/wow/t-12335.html this should settle it

**Comment by babno** [comment]
From your link "ferals get the benefits of Superior Impact" That does seem to settle it. It is working correctly. Seriously though all that is is one person thinking it does work and another thinking it doesn't.

Re your above post. Weapon damage rounds, you probably went from like 45.8(46)=>47.2(47). 14ap (7 strength before buffs and talents) is 1 damage in cat.

"No other class benefits nearly as much from any enchant and stone" 
IF that's true (remember a druids damage is 30-40% bleeds which gain nothing from that but do gain from ap, and they also forgo an enchant useful for tanking), so? Priests gain more from spirit than other healers. Paladins gain more from crit. Ferals gain not just less but zero benefit from weapon damage vs other melee. Different classes are different, and that's a large reason why people would rather play tbc than retail.

"it's incorrect, a druids weapon is his claws"
You know what else doesn't make sense? People complaining about a fantasy game not making sense. Or is it fine to ride a dragon, instantly stuff said dragon in your bag in the same space a feather takes up, plummet towards the ground but turn into a bear and feral charge a rabbit to avoid death, but as soon as you hit the rabbit for 9 more damage your immersion is broken? Even within the blizzard universe plenty of things don't make sense, like undead targeting spells (exorcism, shackle, etc) being unable to target undead players, or deep wounds doing the same regardless of 3k crit or 300 crit.

https://www.wowhead.com/forums&topic=142010
Nice wrath link. Not sure how it's supposed to be related anyways though. He's talking about base weapon damage which noone disputes is useless.

"+9 weapon damage would be 126 AP." Only for whites and shred, it doesn't help bleeds or ferocious bite which ends up being around half the druids damage. Plus the uselessness of it for bear I would rather take agi or ap as well.

**Comment by babno** [comment]
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/137778-guide-feral-druid.html

While it suggests 35 agi for a weapon enchant (as I would also) it does say weapon damage enchant on rings is superior. Weapon damage is weapon damage wherever it's enchanted.

**Comment by Jseay1313** [comment]
Yes it has always been known that weapon damage on rings and trinkets work for druids, as mentioned on my first post. That's why even in vanilla the best in slot ring for feral was from the Cenarion Circle quest/faction reward, and also why one of the best feral pieces in all of TBC from Ogrila has weapon damage.

It's not about "it being a fantasy game" that's literally the word for word verbatim direct from Blizzard quote on Druids and their weapon skills, and why you don't gain two hand maces from attacking with your claw. I get it dude you want it to work, it's just not the case. There are multiple posts here from vanilla, tbc, and wrath backing up my statement what more is there to argue, it's not some dick swinging fest at this point just trying to fix the game.

**Comment by Jseay1313** [comment]
Weapon damage is not weapon damage wherever it's enchanted, again, weapon damage on armor has no correlation to using your claws, i.e why weapons were nothing but stack sticks for druids and no procs or non stat enchants worked until WOTLK.

**Comment by Jseay1313** [comment]
http://vanilla-wow.wikia.com/wiki/Druid there, I don't know why this wasnt found earlier. 

Weapons with a "Chance on hit" effect as well as "Chance on hit" enchants such as Enchant Weapon - Crusader and Enchant Weapon - Lifestealing will now proc. "Chance on hit" effects built into armor pieces (as opposed to weapons), such as the Shattered Sun Pendant of Might's proc also work as of 3.02.
Weapon DPS and weapon +damage enchants have no effect, however, armor enchants such as the Enchant Ring - Striking enchant, and armor pieces such as the Crystalforged Trinket that boost weapon damage do work. The bonus damage from Weightstones and Sharpening Stones also does work. Weapon enchants that boost stats such as Attack Power and Agility rather than weapon damage also work. 
Items with an "Equip: When hit ..." do work in forms. Some examples of these items are the Naglering and Darkmoon Card: Wrath's damage, Green Whelp Armor sleep and Shattered Sun Pendant of Resolve proc.

**Comment by Jseay1313** [comment]
This states that in 3..0.2 druid weapons were finally able to proc effects like crusader but still not benefit from +weapon damage, and it also mentions the trinket and armor +weapon damage as mentioned. So you'll have to wait until WOTLK to get that +weapon damage friend god bless.

**Comment by mjk6994** [comment]
I signed up for Github just to say you're a retard.

**Comment by Jseay1313** [comment]
Thanks pal, glad i could help do my part for the community. God bless you

**Comment by baade123** [comment]
can confirm that weapon stones should benefit feral druids- read any feral druid guide/video from retail TBC and u will see them recommend stones/ have stone buff on :)

**Comment by Aledati** [comment]
Weapon stones should work on feral druids, thats basic temporary weapon enchant for feral druids in raids. Trinket with bonus damage should work on feral druids same as weapon enchants. I dont know why people claim something which they have no clue.
I played feral druid in retail and just to be clear trinket from ogrilla reputation reward was one of the best trinkets for feral druids. Temporary enchant +12 weapon dmg and +14crit rating were used and were working.

**Comment by Aledati** [comment]
One more thing, you are saying that 9 weapone damage is equel to 220 strenght....why you say such stupid things???? Why ??? Can you first search some data before you say something this stupid? 
For feral druids:
1 str = 2.2 AP
12 AP = 1 weapon dmg
9 weapon dmg = 108 AP
9 weapon dmg = 49 strenght

And also attack power you can not compare between feral druids and rogues/hunters.
3k AP rogue/hunter is equel to 6k AP feral druid.
Feral druids needs a lot of AP to have good dmg.
Did you ever ask yourself why druids have staves with +1200 AP??

Admins, please do not consider this stupid bug reports from people who dont know basics about druids and they want to change/ruin something on server.
For those people I can not finish Seer Udalo quest cuz some stupid ppl claimed it should be only in Heroic mode....yeah 67 lvl quest for heroic mode. Return that on Normal mode please.
One more time, ignore this report, do not ruin this benefit for feral druids.

**Comment by notsofamous** [comment]
Patch 2.4: Weightstones and Sharpening Stones: The bonus damage from these temporary enchantments now works while shapeshifted. 

So yes, druids should benefit from these.
http://wowwiki.wikia.com/wiki/Patch_2.4.0

**Comment by akrom23** [comment]
So - who is the winner? :)

**Comment by babno** [comment]
We have official patch notes saying it works, so I'd go with that.

**Comment by akrom23** [comment]
There is no bug?

**Comment by babno** [comment]
Correct. Close this thread down and focus on other bugs. My personal preference would be fixing spiritual attunement, but I may be biased :P
