### ISSUE TITLE
Thorns aura stacking

### ISSUE THREAD

**Issue by KimmoKM** [SunwellWoW/Sunwell-TBC-Bugtracker#2439]
![2018-12-04-205252_1920x1080_scrot](https://user-images.githubusercontent.com/1533992/49465589-a7974100-f806-11e8-90d6-c266cab641c8.png)
Description: 
A number of mobs (such as Helboars in HFP and Turtles in Shimmering Flats) return thorns damage to melee attackers. However, on private servers they have a habit of doing double, triple or even greater return damage.

How it works: 
I believe I figured this out: upon being pulled, the mobs cast an invisible thorns aura on themselves, and it stacks. Mobs that are rarely killed but are regularly pulled by passerbys may get insane thorns stacks. Might not be the case - I lack the means to test this easily, in that case thorns damage is bugged in some other manner.

**Comment by SunwellTracker** [comment]
Testing phase.

**Comment by Wojtyas** [comment]
There are still 3x procs instead of 1.
Same case as https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2354

**Comment by simroman** [comment]
![wowscrnshot_122118_191541](https://user-images.githubusercontent.com/45226078/50357181-56e94d00-0555-11e9-8878-52427f28c38b.jpg)
![Uploading WoWScrnShot_122018_215624.jpg…]()
