### ISSUE TITLE
Fishing issue

### ISSUE THREAD

**Issue by Hnidka** [SunwellWoW/Sunwell-TBC-Bugtracker#244]
Decription: Fishing hooks doesn't dissapear

How it works: 
![wowscrnshot_082918_122636](https://user-images.githubusercontent.com/42386888/44782405-6d732f00-ab87-11e8-9285-8f012ab788c9.jpg)

How it should work: They should dissapear after u catch fish or fail

**Comment by Nadiirr** [comment]
Can't Reproduce / Fixed

**Comment by SlyFoxUK** [comment]
I just found this today right after i learned the loot from fishing was now fixed.

[https://imgur.com/a/PKg7RE9](url)

**Comment by brabideau** [comment]
I'm seeing the same bug.

![image](https://user-images.githubusercontent.com/10421239/49313676-4b01f200-f4a5-11e8-9b9a-852d01516049.png)
