### ISSUE TITLE
Turning in "Bartolo's Yeti Fur Cloak"

### ISSUE THREAD

**Issue by recreantus** [SunwellWoW/Sunwell-TBC-Bugtracker#2441]
Description: 
Quest in Hillsbrad Foothills, Southshore

How it works: 
Cannot complete the quest after gathering all the materials.

How it should work: 
You're supposed to gather the 4 materials and then simply turn it in, but does not work. Nothing happens when you click "Continue".

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/9987ebd8fdf1098619e0230b736a9339

**Comment by xethra89** [comment]
I've seen this issue on multiple private servers (Vanilla / TBC). I don't know the cause of the bug, but I know a workaround. Take the items require for your quest and put them in your bank, then take them back out. After doing so, you'll be able to turnin the quest. It's annoying, but that's the only work around without abandoning and collecting the quest items again.

**Comment by Swiplington** [comment]
Abandon quest and picking it back up fixes the issue
