### ISSUE TITLE
Mana Regen

### ISSUE THREAD

**Issue by goretek** [SunwellWoW/Sunwell-TBC-Bugtracker#2443]
Description: There is a problem with mana regeneration. After 5 sec rule (while not casting) it should give more mana per tick. Just look at spirit stat description cast some spells and count amount mana gained while not casting. Tried this on shaman and druid at the same level of gear and stats. Same thing. Then i tried on different server and regen while not casting was more than twice as much i got hier.  

How it works: Lev 14 shaman with spirit at 38 is getting only 9 mana per tick. Description of spirit says it should be 24.

How it should work: Lev 13 shaman with spirit at 35 is getting 24 per tick (different server)

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
Tooltip says: 
![obraz](https://user-images.githubusercontent.com/48881/49471902-60ad4980-f80e-11e8-8984-a6958f6a7435.png)

24 mana every **5s**

but mana regen ticks every 2s ( which is correct ), so mana gained per tick should be: **( 24 / 5s ) * 2s = 9.6** ~~9 mana per 2s

**Comment by amarathTESTER** [comment]
I didn't do the math but im guessing you also did not. 

Here is the formula in 2.4:
MP5 = 5 * (0.001 + sqrt(Int) * Spirit * Base_Regen)

Ticks occur every 2 s. 
So then 2* MP5/5 = tick rate.    I currently have 33 mp5 (oocb) that should be 13.5 mana a tick. i am getting 13s (i probably have like 32.6 mp5) .

Working fine.

https://web.archive.org/web/20080517165657/http://www.wowwiki.com:80/Formulas:Mana_Regen


Evidence https://web.archive.org/web/20080521131242/http://www.wowwiki.com/Spirit
