### ISSUE TITLE
Fishing Not Working

### ISSUE THREAD

**Issue by Knitless** [SunwellWoW/Sunwell-TBC-Bugtracker#2444]
Description: When fishing, it ends early with "No Fish Are Hooked"

How it works: Do not click on the bauble, and it ends saying that "No Fish Are Hooked" with various lengths of the timer still left (sometimes immediately).

How it should work: It should wait until timer is done or you click to cancel the fishing.

**Comment by brabideau** [comment]
If this is the same bug I'm seeing, it seems to be an issue where your cast is linked to the wrong bobber.

How to reproduce:

1. Fish until your fish gets away.
2. Immediately re-cast fishing, before the first bobber despawns.
3. Second cast will end with "no fish are hooked" when the first bobber despawns.
4. Cast a third time before the second bobber despawns. Shortly after the second bobber bobs, and the third (current) cast will be terminated with "no fish are hooked"

You can break the cycle by waiting until all bobbers are completely gone before re-casting. I haven't found a workaround yet to prevent it from happening in the first place.

**Comment by akrom23** [comment]
@Knitless When your bobber splashes, you have 5 sec to click on it - otherwise this error will be sent. This is how it works in "normal conditions".

**Comment by Knitless** [comment]
@brabideau Okay, I will try that. Thank you!
@akrom23 it was disappearing almost immediately most of the time. It wasn't a problem of it disappearing after the timer bar ran out.

**Comment by RPAncap** [comment]
Can confirm - I can post a short video showing it if you are interested.

**Comment by Wojtyas** [comment]
Okey we will focus here.

**Comment by SunwellTracker** [comment]
@RPAncap please show us the video.

**Comment by RPAncap** [comment]
https://www.youtube.com/watch?v=u9UNnx_V35Q&feature=youtu.be

What happens is - that sometimes you will get "No fish are hooked." after very short time (no fish are hooked should only happen if you missed your fish). And your bobber will remain in the water. You then proceed to recast and second bobber will appear. You then have 2 bobbers in the water - well watch the video.  When there are two bobbers you have basically no chance to catch a fish .... you have to recast few times so both will dissappear.

**Comment by SunwellTracker** [comment]
Thank yaa!
