### ISSUE TITLE
[Quest]The Missing Diplomat (Last part, dustwallow)

### ISSUE THREAD

**Issue by elrufa** [SunwellWoW/Sunwell-TBC-Bugtracker#2447]
Description: 
I'm unable to hand in the last quest in the 'The Missing Diplomat' quest chain.

How it works: 
After the second last quest in the chain: https://classicdb.ch/?quest=1324 is completed both Jaina and Archmage Tervosh appears. When I handed in the quest I got no follow-up to complete the chain and recieve the last reward (1,3g and "Jaina's Signet Ring"). Jaina has a yellow '?' to mark that she has a quest ready hand in, but when I speak to her I can do nothing, only read her regular dialogue. Archmage Tervosh for some reason has a blue "daily/repeatable" '?' and shows me the completion dialogue for the last part (Even though I don't even have it in my quest log anymore), including the reward, but I'm unable to press "complete quest".

How it should work: 
Archmage Tervosh should give you a quest to speak to Jaina to finish the chain and receive the reward. Additionally, quest text is missing from the completion of the last quest.

Source (you should point out proofs of your report, please give us some source): 
Here is a video of my current state: https://streamable.com/p4ji9
Here's how it should be: https://www.youtube.com/watch?v=1nlDIXYygio&feature=youtu.be&t=629
Extra source from actual vanilla video (horrible quality, but confirms the above): https://www.youtube.com/watch?v=DjLvJElJP6U

Additional details:
Since I believe it may not be bugged for everyone (another guy claimed to have completed the quest without problems) I'll state what I've done to better troubleshoot.
At the Wetlands part (https://classicdb.ch/?quest=1249) I had to abandon the quest and retake it since I never followed the NPC outside. Afterwards when I spoke to a GM about this issue he/she told me that I had two parts of the chain marked as not completed. One was (I believe?) the quest just after this one (https://classicdb.ch/?quest=1250) and the other was the last part. The GM added the quest to my questlog and told me to complete it as it would possible fix my issue. I did this and returned to Jaina and Tervosh, but I still had the same issue. Character name: Pro

123

**Comment by ghost** [comment]
I have managed to reproduce this bug on one of my PTR characters.
Take quest http://db.darkwizard.pl/?quest=1324 and complete it & turn it in.
Go near Lady Jaina Proudmoore (Dustwallow Marsh) and relog, after logging back in, I am unable to take http://db.darkwizard.pl/?quest=1267 ,even thought I'm seeing the "?" mark above and I am unable to press "Complete Quest"
