### ISSUE TITLE
Lava

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#245]
Decription: Players who swim in lava take no damage.

How it works: As above.

How it should work: Swimming players should take around 600 fire damage every 2 seconds they spend in lava.
![image](https://user-images.githubusercontent.com/22802214/44788636-e4fe8980-ab9a-11e8-9241-6f02c834ae6f.png)

Source (you should point out proofs of your report, please give us some source):
"Originally, lava would deal 603 to 604 damage every 2 seconds submerged."

**Comment by akrom23** [comment]
Wpisz .gps i wklej tutaj obrazek.

**Comment by akrom23** [comment]
Type ingame ```.gps``` and paste the pic.

**Comment by Kokaina** [comment]
![image](https://user-images.githubusercontent.com/22802214/44816839-b062f000-abe3-11e8-8f70-c91c8f963657.png)
