### ISSUE TITLE
Shaman Elemental Mastery

### ISSUE THREAD

**Issue by shamylee** [SunwellWoW/Sunwell-TBC-Bugtracker#2450]
#shaman

How it works: Elemental Mastery buff is disappearing after fire totems damage, lightning shield damage, and some other mysterious ways and it's not always a critical as it should be.
EDIT: Flame Shock ticks and totem deployment are removing the buff too.

How it should work: Elemental Mastery buff should only disappear after fire, earth and frost shock,lightning bolt and chain lightning spell damage with 100% critical.

Source (you should point out proofs of your report, please give us some source):

**Comment by nennx** [comment]
Basically, anything that you can do eats the elemental mastery buff.
