### ISSUE TITLE
warlock pet sees through shadowmeld

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#2451]
Description: 
was running away from warlock. went to shadowmeld eat/ and his pet ran straight to where i was hiding, 1 foot away from me, but did not attack, but clearly gave up my location. 

How it works: 

How it should work: 
should reset like a vanish unless pet is in range of seeing me through stealth, after which case it would attack me. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Already reported here - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2426
Will be fixed soon.
