### ISSUE TITLE
Quest: Hunt for Yenniku fails to complete, have 31 bloodscap tusks

### ISSUE THREAD

**Issue by eldewall** [SunwellWoW/Sunwell-TBC-Bugtracker#2452]
Description: 

I have 31 bloodscalp tusks in my inventory, i also have the Cyclonian quest active as a warrior

How it works: 

Cannot complete quest

How it should work: 
No idea, but i feel like this should work?

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120418_224229](https://user-images.githubusercontent.com/87705/49474972-4f683b00-f816-11e8-81ad-8ba2f497db29.jpg)

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2441

Hi, we are awere o this issue. Right now there are two possible solutions metioned in issue linked above.
