### ISSUE TITLE
Antonio Perelli NPC Walkroute

### ISSUE THREAD

**Issue by Josephienvandermeersch** [SunwellWoW/Sunwell-TBC-Bugtracker#2453]
Description: 
Antonio Perelli in Elwynn just walks through Trees and buildings, not following the road.

How it works: 
Straight line no Road

How it should work: 
Following Road

Source (you should point out proofs of your report, please give us some source): 
Just Follow him in Elwynn its easy to Spot. 
![wowscrnshot_120418_225912](https://user-images.githubusercontent.com/24510505/49475727-44160f00-f818-11e8-967b-7d66decdb057.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented.
