### ISSUE TITLE
Feign Death, Aspect of the Cheetah

### ISSUE THREAD

**Issue by aspectslul** [SunwellWoW/Sunwell-TBC-Bugtracker#2454]
Description: 
Spells costs MANA!!!!!!!!!! in description of these spells is ONLY "INSTANT CAST" NO MANA !!!!

How it works: 
SPELL WITHOUT MANA !!!!!!!!!!!!!!!!!

How it should work: 
YOU INSTANTLY CLICK ON THIS 0 MANA SPELL 

Source (you should point out proofs of your report, please give us some source): 
try this on your fix server you will see........

**Comment by Wojtyas** [comment]
I don't understand. Feel free to reopen if needed or contact me via Discord - Koka#2143

![image](https://user-images.githubusercontent.com/22802214/49477580-a3c2e900-f81d-11e8-93d3-70938c8fc31f.png)

**Comment by aspectslul** [comment]
contacted u via dc, my fault sorry have a nice day! :D
