### ISSUE TITLE
Warlock: Improved Drain Soul

### ISSUE THREAD

**Issue by Qnkad** [SunwellWoW/Sunwell-TBC-Bugtracker#2455]
Description: 
Tested the Talent in the Affliction Tree in different scenarios. With pet, without pet and only dot ticking during casting drain soul. I never got a buff or my "mana regen" in character window changed.

How it works: 
Doesnt seem to work at all.

How it should work: 
You should get back the amount of mana in the tooltip after killing a monster while draining it off with Drain Soul.

Source (you should point out proofs of your report, please give us some source): 
Ingame tests.

**Comment by Wojtyas** [comment]
Already reported here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2073
will be fixed soon for sure.
