### ISSUE TITLE
Netherstorm npc Withered Corpse

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2456]
Description: 

How it works: When you walk over them they don't spawn adds and disappear

How it should work: When you walk over them they  spawn adds and disappear

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented.

**Comment by mintnb** [comment]
These trigger from a mile away. Even people on top of the mountain cause the parasites to spawn. I remember this place being nasty on retail but it's nuts here.
