### ISSUE TITLE
Questobject already being used

### ISSUE THREAD

**Issue by Sheezhyn** [SunwellWoW/Sunwell-TBC-Bugtracker#2458]
Description: Problem was encountered throughout the whole content so far. To avoid the problem get closer to the questobject - see below

How it works: Upon interacting/gathering (with) questobjects that just became "gatherable"(range true), the following message is being produced:"That is already being used.". The item doesnt become 'gatherable" again and stays bugged.

How it should work: Upon reaching the accquired range to gather a questobject, it shouldn't become inaccessible 

Source: For example the Alliance quest:"Kurzen's Mystery" - Object:"The Fourth Troll Legend" 
Link: https://imgur.com/d0cpxVs

**Comment by Dootz** [comment]
Hi, we are aware of this issue. It will be fixed with next server update.
