### ISSUE TITLE
[Quest]Shy-rotam

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#2460]
Description: 
Doing this quest in a party results in that only a player who laid the meat can finish the quest

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by RobGFour** [comment]
Still does this

**Comment by Wojtyas** [comment]
Also https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2717

**Comment by Dootz** [comment]
will be fixed with next server update
