### ISSUE TITLE
shaman talent shamanistic focus

### ISSUE THREAD

**Issue by arkigodx** [SunwellWoW/Sunwell-TBC-Bugtracker#2462]
Description: 

shamanistic focus buff is getting eaten by any elemental damage(flametongue, searing totem)
How it works: 

How it should work: 
should only be proced by shocks

Source (you should point out proofs of your report, please give us some source): 
shouldn't be needed

**Comment by Wojtyas** [comment]
Already reported here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2048
Will be fixed soon.
