### ISSUE TITLE
[Warlock] Spells, different ranks, overwrite

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#2463]
Description: 
Two warlocks(56,52lvl) in a party ... they have different ranks of the spells ie Corruption, Drain Life, the higher ranks overwrite the lower ranks of the other player... casting lower rank of drain life results in channeling but doing no dmg no heal,only animation

How it works: 
Dots/spells of both warlocks should be applied

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by SunwellTracker** [comment]
We know about this bug. Fix is already done. Implementation - tomorrow.
