### ISSUE TITLE
[Shaman][Talent] Elemental Focus

### ISSUE THREAD

**Issue by pandzordox** [SunwellWoW/Sunwell-TBC-Bugtracker#2465]
**Description:** 
Buff from talent Elemental Focus doesn't work as description sugests,

**How it works:** 
Give a mana discount for 1st spell after crit.

**How it should work:** 
Give mana discount for two next spells after crit.

**Proof:** 
![proof](https://user-images.githubusercontent.com/45611635/49481301-9d873980-f82a-11e8-8e98-cae0e0f93201.png)

**Comment by Wojtyas** [comment]
Already reported here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2129
Will be fixed soon.
