### ISSUE TITLE
Heart of the wild AP

### ISSUE THREAD

**Issue by Macdog2202** [SunwellWoW/Sunwell-TBC-Bugtracker#2466]
Description: 
AP dident increase in cat form after choosing talent
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Aledati** [comment]
I just lvl-ed up and added Heart of the wild talent point while watching character stats, and I can confirm that Heart of the wild talent point does not working.
Please fix this soon, this talent is important one for druids and atm we all have spared 5 talent points on one which is not working...

**Comment by akrom23** [comment]
Works fine.
Without talent:
![wowscrnshot_011019_171742](https://user-images.githubusercontent.com/1035215/50981632-b8209280-14fb-11e9-8fd6-e3c65fc1c11e.jpg)

With talent:
![wowscrnshot_011019_171730](https://user-images.githubusercontent.com/1035215/50981642-bc4cb000-14fb-11e9-8cc2-bc8571807fdd.jpg)
