### ISSUE TITLE
Pet exp not working properly in party

### ISSUE THREAD

**Issue by primeropein** [SunwellWoW/Sunwell-TBC-Bugtracker#2467]
Description: 
Pets get almost to none exp when in party with others
I tamed my current pet at lvl 13 , it was always same lvl as me (or 1 lvl behind but would always lvl up 4-5 mobs later) , now that i joined my buddiesi n question together, my pet is lvl 47 while im lvl 55 :O

How it works: 
When u join party your pet gain sooo little exp 

How it should work: 
Pet should not get deducted exp cause of party

Source (you should point out proofs of your report, please give us some source): 
Well not sure how to prove it really , just how the server acts

**Comment by ujellyx** [comment]
I doubt it's really related to group exp, as the same behavior can be seen while leveling solo. #2376

**Comment by primeropein** [comment]
Well it is , now I got a new pet and I dont play in party anymore and I dont experience it
