### ISSUE TITLE
[Quest] Trial and Error

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#2469]
**Description:** 

**How it works:** 
You do not get any wands from the quest bag.

**How it should work:** 
You should receive the wands in the bag you get from accepting the quest.

**Source (you should point out proofs of your report, please give us some source):** 
http://db.hellfire-tbc.com/?quest=10566

**Comment by notsofamous** [comment]
Also the crystals http://db.hellfire-tbc.com/?item=30655 needed for the quest does not drop.

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
