### ISSUE TITLE
Shadowmoon Valley Quest: Thwart the Dark Conclave

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2470]
Description: Quest in SMV

How it works: After you finish the quest you can't deliver it to the quest npc

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Fuzedknight** [comment]
Confirmed it cannot be turned in after completion.
https://puu.sh/Cd63P/d82c8e6a3b.png

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
