### ISSUE TITLE
[Warlock][Spell] Enslave Demon

### ISSUE THREAD

**Issue by Mirlmunir** [SunwellWoW/Sunwell-TBC-Bugtracker#2471]
Description:  Enslave demon target and follow you like a Pet.

How it works: https://plays.tv/video/5c0735dfc0f2a8b1ed/enslave-demo-issue-for-every-demon-in-the-game-

How it should work: After enslave the Demon, he /follow - /stay where i want but here he is stuck and don't move so it's really bad.

Source:  My Trainer class.

**Comment by ZaoQ** [comment]
This is very iritating, pls some priority to it, infernal report inc

**Comment by Mirlmunir** [comment]
When we use Mount, don't forget to add the same speed when the Demon /follow the player or let them disepair and respawn like my Felguard/Imp etc...

**Comment by akrom23** [comment]
Cannot reproduce it.
