### ISSUE TITLE
[Quest]Gadgetzan Water Survey

### ISSUE THREAD

**Issue by TheRealestMcCoy** [SunwellWoW/Sunwell-TBC-Bugtracker#2473]
Description: 
Use the untapped dowsing widget near the pool of water by Sandsorrow Watch. 
Once the widget is used 2 adds should spawn. 
Centipaar Tunnler Currently have a hostile flag state but are a neutral frames.

How it works: 
Adds stack up

How it should work: 
If the adds arent killed they should despawn if left and no one kills them if not you end up with a crap load. Currently they do not it seems. 
https://gyazo.com/1dba2e5e99a68f66f5aac42f62ef577a
https://gyazo.com/2e0a8916900f4eb286f05bca873f99b5

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=992/gadgetzan-water-survey

**Comment by Jseay1313** [comment]
They do currently despawn, not sure the exact timer but saw 6 of them despawn infront of me while doing it. Regardless they should not stack up

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
