### ISSUE TITLE
Hellfire Quest (Cruel Taskmaster)

### ISSUE THREAD

**Issue by thearmo** [SunwellWoW/Sunwell-TBC-Bugtracker#2475]
Description: Illadari Taskmaster at Ruins of Sha'naar with 2 mobs near him.

How it works:  When you kill the taskmaster, the workers turn yellow and chase you pretending to attack you but never actually hit you. Puts you in combat until you kill the mob. Will also chase you around the map until dead

How it should work: The mobs turn neutral after killing the taskmaster and should run away not putting you in combat

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
