### ISSUE TITLE
[Zone] Zangarmarsh WoW crash

### ISSUE THREAD

**Issue by codey07** [SunwellWoW/Sunwell-TBC-Bugtracker#2476]
Description: 
In the following screenshots i will show you where the wow error happens. This has happened to multiple people 

How it works: 
Upon entering the cave, you have a 10 second window of being able to get in before crashing. Upon standing where I am in the screenshots, you will crash. If you have a crappy PC (long load times) you could get stuck in an endless crash loop

How it should work: 

Wow doesnt crash
Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/iQFweEZ

**Comment by thearmo** [comment]
+1 had it happen to me as well. specific locations within the cave caused it
