### ISSUE TITLE
Druid: Can't cast spells while in travel form without manually shifting out of form

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#2477]
Description: Currently you are unable to cast certain spells (rejuvenation) without first shifting out of travel form, the game should automatically unshift you as it does for other spells

How it works:  Press travel form,, press rejuvenation, it tells you YOU CANNOT ATTACK THAT TARGET

How it should work: It should unshift me from travel form and cast rejuvenation

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/2mnMucX

**Comment by Jseay1313** [comment]
just to clarify more, casting a spell while shapeshifted works the same as casting a spell while mounted, in Vanilla you had to have the ezdismount addon, but tbc fixes the problem with an option in the interface, most every other spell works and properly unshifts you, rejuvenation and lifebloom do not

**Comment by Moobe123** [comment]
To add to this and explain a bit more, ´while in travel form the game is trying to cast spells from the cat/bear actionbars. So if I have moonfire on 1 in human form, and mangle on 1 in catform, the game is trying to cast mangle while in travel form.

**Comment by Moobe123** [comment]
Since I removed an addon related to keypresses it's working for me. Meaning addons like "Speedyactions" and "snowfall keypress" could be the thing causing this issue.

**Comment by akrom23** [comment]
Works fine.
