### ISSUE TITLE
[NPC] Shattered Sun Mobs

### ISSUE THREAD

**Issue by terk69** [SunwellWoW/Sunwell-TBC-Bugtracker#2478]
Description: 
I know this is not a bug, but these mobs were not implemented in the early stages of TBC. It ruins immersion when they are present in Shattrath City. Please remove NPC connected with higher patching.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Shattered_Sun_Offensive

**Comment by Wojtyas** [comment]
Done.
