### ISSUE TITLE
[Zone] [Azuremyst Isle]

### ISSUE THREAD

**Issue by Hnidka** [SunwellWoW/Sunwell-TBC-Bugtracker#248]
### **DONE:**

- [x]  **All Azuremyst Isle NPCs deal low dmg (spells,psychical)**.... i show some examples

- [x]  NPC -Volatile Mutation - Guid 57278 , Entry 16516
http://db.hellfire-tbc.com/?npc=16516
His dmg is too low (1) should be (2 - 3)

- [x] NPC - Moongraze Stag - Guid 61368 , Entry 17200 
http://db.hellfire-tbc.com/?npc=17200
His dmg is too low (2-7) should be (6 - 10)

- [x] NPC - Root Trapper - Guid 61067 , Entry 17196 
http://db.hellfire-tbc.com/?npc=17196
His dmg is too low (2-7) should be (6 - 10)

- [x]  NPC - Moongraze Buck - Guid 61508 , Entry 17201
http://db.hellfire-tbc.com/?npc=17201#abilities
His dmg is too low (2-7) should be (8 - 12)

- [x]  NPC - Aberrant Owlbeast - Guid 60749 , Entry 17187
http://db.hellfire-tbc.com/?npc=17187#abilities
His Moonfire deal 5 dmg should be 7-10 

- [x]  NPC - Siltfin Oracle - Guid 60890 , Entry 17191
http://db.hellfire-tbc.com/?npc=17191#abilities
His Wrath deal 7 dmg should be (14-18) 

- [x]  NPC - Root Trapper - Guid 61067 , Entry 17196 
http://db.hellfire-tbc.com/?npc=17196
His dmg is too low (2-7) should be (6 - 10)

...................................................................................................................................................................................................................

- [x]  Bugged NPCs "murlock zone" Guid 60892 , Entry 17191 they should be even on land but they are stucked in water 
![wowscrnshot_082918_144222](https://user-images.githubusercontent.com/42386888/44788427-4c680980-ab9a-11e8-8673-97ccdf212787.jpg)
![wowscrnshot_082918_144155](https://user-images.githubusercontent.com/42386888/44788436-568a0800-ab9a-11e8-9f33-805aa99c9558.jpg)

- [x]  NPC - Murgurgula - Guid 62989 , Entry 17475
http://db.hellfire-tbc.com/?npc=17475#abilities
Does not use ability: Thrash

- [x]  NPC - Root Thresher - Guid 61141 , Entry 17197
http://db.hellfire-tbc.com/?npc=17197#abilities
Does not use ability: Thrash

- [x]  Stillpine Hold - too many mobs here ? seems like every spawn for 1 mob has 3 mobs
![wowscrnshot_082918_153335](https://user-images.githubusercontent.com/42386888/44791281-8dafe780-aba1-11e8-82a3-8ba1b83d50fb.jpg)
- [x] 1. There shouldn't be so many Stillpine Defenders (17432) right before Stillpine Hold entrance.
![image](https://user-images.githubusercontent.com/22802214/44989080-068db580-af8d-11e8-803d-871a86c39577.png)
- [x] 2. High Chief Stillpine (17440), Parkat Steelfur (17446), Moordo (17442), Chieftain Oomooroo (17448), The Kurken (17447) and Gurf (17441) shouldn't have random movements.
**I dunno why but really a lot of npcs have random movements.**
- [x] 4. There should be no perm spawns of Stillpine Raiders (17495).
- [x] 1. Kurz the Revelator (17443), High Chief Stillpine and Stillpine the Younger (17445) have their texts missing.
**EDIT: High Chief Stillpine still has his text missing**
- [x] 2. There should be outro event missing after Chieftain Oomooroo (9573) quest completion. Plenty of Stillpine Riders should spawn and charge Stillpine Hold after Stillpine the Younger yell.
![image](https://user-images.githubusercontent.com/22802214/44989442-2a053000-af8e-11e8-8202-93e7c1544938.png)
Event starts at 2:20 - https://www.youtube.com/watch?v=X0rOTmqzKmg
**EDIT: Add something extra when Riders are inside cave ;D**

**Comment by Hnidka** [comment]
About that low dmg... my “should be” values are incorect i will rewrite it today...

**Comment by Hnidka** [comment]
done

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
Well done.
