### ISSUE TITLE
Drain Schematics

### ISSUE THREAD

**Issue by Nadiirr** [SunwellWoW/Sunwell-TBC-Bugtracker#2480]
Item appears not to drop.

http://db.hellfire-tbc.com/?item=24330#dropped-by

Player killed 70+
I killed 20+ of the 9% drop rate.

**Comment by neheri** [comment]
I did that quest on beta and it dropped from 5th+ mob. Had no problem with quests in zanga whatsoever.

**Comment by Nadiirr** [comment]
Closing for now as I’ve had other people tell me it works also. Rng is no fun :)
