### ISSUE TITLE
Drop rates in Blasted Lands

### ISSUE THREAD

**Issue by dgasen** [SunwellWoW/Sunwell-TBC-Bugtracker#2483]
Description: 
 [Vulture's Vigor] [The Decisive Striker] [The Basilisk's Bite]

How it works: 
Mob. Black slayer. Should drop quest items. It does not 

How it should work: 
It should drop quest items.

Source (you should point out proofs of your report, please give us some source): 
By experienc'ing the quest!

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
