### ISSUE TITLE
Hunter Pet bar

### ISSUE THREAD

**Issue by Darrgoth** [SunwellWoW/Sunwell-TBC-Bugtracker#2484]
Description: 
Whenever you raise your pet the hunter pet bar never shows up you have to dismiss your pet everytime and then recall it out to get the hotbar to show up again, really really annoying.

**Comment by ZeuzzzZz** [comment]
+

**Comment by akrom23** [comment]
@Darrgoth Cannot reproduce it.

**Comment by Khazro** [comment]
This issue is still happening. Only happens when you have to revive/resurrect pet. The pet bar completely disappears and you have to dismiss pet and call it again to make it show up again.

**Comment by Darrgoth** [comment]
Actually there is a fix I've found if you sick your pet I think or make it return to you using ctrl + 1 I think it fixes it. or something like that. worked for me while I was playing. 
    On Friday, February 22, 2019, 3:02:04 PM EST, Khazro <notifications@github.com> wrote:  
 
 
This issue is still happening. Only happens when you have to revive/resurrect pet. The pet bar completely disappears and you have to dismiss pet and call it again to make it show up again.
