### ISSUE TITLE
[Quest] Are We There, Yeti? (part 3)

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#2488]
Description: 
There is no interaction with either of those 3 NPC who u are supposed to scare.

How it works: 

How it should work: 
Interaction with texts in the source link

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Quest:Are_We_There,_Yeti%3F_(3)

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
