### ISSUE TITLE
Ferocious Bite not working properly

### ISSUE THREAD

**Issue by Aledati** [SunwellWoW/Sunwell-TBC-Bugtracker#2489]
Description: 
Finishing move of druid in cat form called ferocious bit is not working properly.

How it works: 
Ferocious Bite not using rest of energy for converting energy into bonus damage.

How it should work: 
Finishing move that causes damage per combo point and converts each extra point of energy into 1.5 additional damage.
Using this spell cat uses all available energy for this move.

Source (you should point out proofs of your report, please give us some source): 
I believe its not needed, description of spell is enough.

**Comment by baade123** [comment]
also noticed this and was about to post it

**Comment by Jseay1313** [comment]
It also refunds 35 energy every time it lands, lot of feral/energy bugs atm. Nice find though.

**Comment by Macnjacks** [comment]
It also appears to not be doing it's initial damage either on top of the extra energy.

**Comment by akrom23** [comment]
Damage is fine. Only energy is not consumed properly.
