### ISSUE TITLE
[Paladin] Blessing of Freedom not granting immunity to spells that are mid-air

### ISSUE THREAD

**Issue by Pikseh** [SunwellWoW/Sunwell-TBC-Bugtracker#2490]
Description: Blessing of Freedom does not grant immunity to spells with slowing effects, if the spell is mid-air when the blessing is placed.

How it works: Blessing of Freedom removes slowing and immobilizing effects as well and granting immunity to those effects while under the effect of the blessing, except if a spell has been cast at you and is mid-air when you place the blessing (like Frost Bolt being mid-air towards you). In that case, the slowing effect applies, but no future effects can apply.

How it should work: Even spells that are mid-air should not be able to slow or immobilize you.

Source (you should point out proofs of your report, please give us some source): I didn't get a picture of this happening, sadly, if it's required then I'll try to replicate it. But the description of Blessing of Freedom is pretty straight forward.

**Comment by ZaoQ** [comment]
You should find some source, if u dont i would assume it behaves the same way like Cloak of Shadows, it also does not resist mid-air spells which is correct.

Edit: I just asked Xaryu :) it should work like it works now.

**Comment by MVMnn** [comment]
It should grant immune to any slow effects - doenst matter when cast was - if you cast frostbolt and paladin will use divine shield paladin will take no damage - why the hell it should be different here?!

**Comment by Pikseh** [comment]
@ZaoQ The major difference between BoF and CoS is that if you get hit by the slowing ability, say Concussive Shot, and then use BoF, then the slow is removed, but the same is not true for CoS, since the effect is a physical debuff and not a magical one. With CoS you can get "punished" for using the ability too late, but that should not be the same for BoF: Once you use it, you are immune to any slowing and immobilizing effects for its full duration. You still take the full Frost Bolt damage, if Frost Bolt was cast, but your character is incapable of having its movement speed reduced, so the slow mechanic would never apply.

**Comment by ZaoQ** [comment]
It does matter when it is cast, Divine shield is quite an exception in many ways, like absorbing fall dmg, drowning dmg etc

**Comment by Pikseh** [comment]
Are you seriously arguing, that a buff which says "Immune to movement impairing effects." does not make you immune to movement impairing effects? Because that's really what it sounds like you're saying. If I waited for the Frost Bolt to hit me, and then used BoF, then the effect is the same as if I used it before FB hit me: I take the full damage, but I'm not slowed. BoF and CoS work very differently in that regard.

**Comment by ZaoQ** [comment]
well prove me wrong in any video/chat discussion
also i found: https://wow.gamepedia.com/index.php?title=Blessing_of_Freedom&oldid=1089841 with ''This ability will not remove the Daze effect caused by running from mobs, or a hunter's  [Concussive Shot] effect.''

**Comment by crazzord** [comment]
i messaged hydra and he said it should not work like that, prove me wrong
what is this?
how do you ASSUME it works same as CoS? it gives you 90% chance to resist spells this gives you IMMUNITY how do you ASSUME that its the same mechanic????

**Comment by 13last** [comment]
Freedom should be removing Frostbolt's slow and it is not, it is clearly a bug, especially at level 70 pvp its going to be huge.

And for you all of you saying its not true, the spell clearly states granting immunity to movement impairing effects, and guess what frostbolt slow is? So yes this is a bug that needs to be fixed.

**Comment by Testimonia** [comment]
This IS BUGGED, doesnt matter how you state it. if you get immune to something there is nothing you could talk around it
