### ISSUE TITLE
Drowing in aquatic form

### ISSUE THREAD

**Issue by Aledati** [SunwellWoW/Sunwell-TBC-Bugtracker#2492]
Description: 
Druid's aquatic form has issue with possible drowing while in aquatic form

How it works: 
After swiming in any other form except aquatic form there is time after which your character starts taking damage from drowing. In that period while druid is drowing if you change form in aquatic form drowing is not stopped and you actually die from drowing.

How it should work: 
While drowing changing any form into aquatic form drowing should be canceled completely and time of new drowing should be restarted immediately.

Source (you should point out proofs of your report, please give us some source):

**Comment by Jseay1313** [comment]
confirm you should be able to shift into aquatic form at any point and have enduring breath, even if already drowning

**Comment by akrom23** [comment]
@Aledati Cannot reproduce. After change to aquatic form, damage from drowning is cancelled and breath bar is reset.

**Comment by akrom23** [comment]
No response.
