### ISSUE TITLE
[Paladin] Seal of Command partial resists

### ISSUE THREAD

**Issue by Pikseh** [SunwellWoW/Sunwell-TBC-Bugtracker#2493]
Description: Seal of Command procs sometimes partially resist. Holy damage is based on a binary resist system, where holy damage is either not resisted at all, or all the damage is resisted completely. Not sure if this also applies to other sources of holy damage.

How it works: See description and combat logs of attached picture.

How it should work: See description.
![wowscrnshot_120518_092223](https://user-images.githubusercontent.com/3406509/49503390-a6eac300-f877-11e8-9dc8-36a38492c704.jpg)

Source (you should point out proofs of your report, please give us some source): https://wow.gamepedia.com/Resistance This link shows how reductions to spell damage is calculated using resistances. Since there are not resistance stats to holy damage, holy damage cannot be partially resisted, and can instead only roll the full hit or full resist roll (which would be the same as "missing" the spell).

**Comment by MVMnn** [comment]
Can confirm this, happened to me also.

**Comment by chme3921** [comment]
SoC is unique in the sense that it can glance like other melee abilities, so these partial resists are actually SoC glancing. Showing as a resist is just how the TBC combat log handles it.

**Comment by xethra89** [comment]
Seal of command can show resist yes, but consecration should not have resistance. You can see it in the last entry. 

Consecration being partially resisted is a bug.

**Comment by Pikseh** [comment]
@chme3921 I find this hard to believe since glancing blows only happen on white attacks, not on abilities, see the link for glancing blows:

http://wowwiki.wikia.com/wiki/Glancing_blow

> Glancing blows are combat events that can occur when fighting a mob of equal or higher level.

>These occur only on white damage...

**Comment by xethra89** [comment]
@Pikseh "WoW Icon update.png Patch 1.3.0 (2005-03-07): The damage effects can now be resisted instead of dodged, blocked, or parried. " 

Source: https://wow.gamepedia.com/Seal_of_Command

**Comment by Pikseh** [comment]
True xethra89, didn't even notice that. Obviously there are some issues with how holy damage is handled in the system then, and not just SoC. I still believe that my argument regarding Glancing Blows and special abilities stand, though, and as such it should not be able to resist/glance part of the damage. Even if it was a glancing blow, it should reduce it by more than 24% (21/(66+21)), since glancing blows reduce between 30% and 40% damage, so it can't be a glancing in any case.

**Comment by Pikseh** [comment]
@xethra89 It says nothing about partial resists. There are de facto no holy resistance in the game, so partial resists are impossible, and even if it was the case, then it would apply to all sources of holy damage, not just SoC and Cons, which was certainly not the case on live servers back then.

**Comment by xethra89** [comment]
"Magic-damage melee special attacks

Some monsters also have melee "specials" (the equivalent of yellow-damage attacks done by players) that do magic damage. For example, the Crystal Strike ability of the Erratic Sentries on the Isle of Quel'Danas inflicts Arcane damage, but is resolved as an ordinary melee special attack—it can miss, be dodged, be parried, and be blocked, and does double damage on a crit. The only difference between how a magic-damage melee special attack, and an ordinary physical damage melee special attack, is resolved is that if the target has any resistance to that school of magic, the same check is made to see if the damage is partially resisted as would happen from a spell.

A few player abilities, such as a paladin's Seal of Command, are likewise resolved as yellow-damage melee attacks that deal non-physical damage. The odds of the various attack results occurring with one of these attacks are determined the same as for physical melee attacks—the base chances are determined by the player's Weapon Skill with the wielded weapon, the miss chance is reduced by the player's Hit Rating, the chance to be dodged and parried is reduced by the player's Expertise, and the chance to crit is increased by the player's Agility and Crit Rating."

http://wowwiki.wikia.com/wiki/Attack_table

As I said before, SoC is correct in doing so. Consecration, Seal of Righteous, Judgement of Righteous, Retribution Aura etc. all should not be partially resisted. It should be hit or not hit, binary (taking mob level and etc).

**Comment by xethra89** [comment]
Although doing some more digging, Shiro (Corecraft's maker) made this post https://github.com/ccshiro/cc-buglist/issues/1177#issuecomment-133750697

**Comment by Pikseh** [comment]
Please explain to me exactly what makes you believe that SoC should be able to partially resist, while other sources of holy damage should not be able to partially resist.

**Comment by xethra89** [comment]
There's a lot reports pertaining to Seal of Command and partial resists, I don't have the time to compile everything at the moment (I'm at work) so will just link this last one for now. 

https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2705#issuecomment-16786893

"http://elitistjerks.com/f15/t9673-paladin_seal_mechanics/p2/#post280398
I even took a screenshot of my combat log of a seal of command proc being both parried and partially resisted within a few swings."

**Comment by Pikseh** [comment]
I'm not saying that it should not be able to be blocked, dodged or parried, I'm saying that since there are no means of gaining holy resistance in the game, and since it is a special attack (not white hit), it should not be able to partially resist or glance.

**Comment by pinkisnotgay** [comment]
Anyone else noticed that sometimes if you do a Judgement to fast after melee swing nothing happens and Judgement littelary disappears, without doing any dmg?

**Comment by xethra89** [comment]
@pinkisnotgay

That has been reported here. 

https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2240

**Comment by akrom23** [comment]
https://wow.gamepedia.com/Holy_resistance

> It only exists against PvE targets of a higher level

https://forum.nostalrius.org/viewtopic.php?f=5&t=36395#p255304

> How it suppose to work : only higher levels should partial resist , holy resist should not exist.

Mobs can partially resist holy spells.

**Comment by Devrak** [comment]
For each level the mob is higher than you it gains 8 non-removable-mitigatable resistance to all schools of magic ( inc holy ) you could call it a game mehanic since its not affected by anything and you can not get rid of it by any means 

Seal of Command is non binary type of spell as it contains no extra component so its subject to beeing partially resisted when used against pve opponents of higher level When you attack them there will be a ultra low chance of 75% partial resist a very low chance of 50% partial resist and low chance of 25% partial resist.

**Comment by akrom23** [comment]
So this report is invalid?

**Comment by Devrak** [comment]
Needs some additional testing as you cant see hes level in that screenshot if i have time ill test it later today

**Comment by Devrak** [comment]
I do not get any partial resists on mobs of lower level can close this and #2601
