### ISSUE TITLE
Primal Might recipe

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2497]
Description: Recipe to craft Primal Might

How it works: Respawn timer 1 hour

How it should work: Respawn timer should be noticably longer than 1 hour for sure

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Already reported https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2372
Will be fixed soon.
