### ISSUE TITLE
Zangarmarsh: Swamp Gas

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2499]
Description: Motes

How it works: Gives 3-5 Mote of Life

How it should work: Gives 3-5 Mote of Water

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Was giving Motes of Life back in 2.0 content

**Comment by Shadowkill22** [comment]
Funny thing, ok that is true, but for example: Necklace of the Deep comes with patch 2.1 and yesterday I have seen him in AH. :)

Edit: Also on patch 2.0 all gases have been giving 1-3 motes not 3-5 like it is now :) they have increase that with change of water ones :)
