### ISSUE TITLE
[Blood Elf][NPC] Arcane Wraith, Tainted Arcane Wraith

### ISSUE THREAD

**Issue by dredd-sunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#25]
Decription: NPC ID 15273, 15298 have missing waypoints, retail sniffing required (it didn't change since tbc).

Also, NPC 15298 should ocassionally cast 25603 (slow) on players, NPC 15273 should occasionally cast 37361 (arcane bolt)

**Comment by Kokaina** [comment]
Fixed and implemented.
