### ISSUE TITLE
[Item] Wolfshead Helm, 8345

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#250]
Decription: 

How it works: 
Only gives rage, never energy when you shapeshift into cat form

How it should work: 
Should give energy/rage when you shapeshift into cat/bear

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?item=8345

**Comment by baade123** [comment]
oof was going to write this one up

**Comment by notsofamous** [comment]
Doesn't give either rage or energy now.

**Comment by Kokaina** [comment]
Probably after @lukaasm auras merge.

**Comment by notsofamous** [comment]
Still doesn't work

**Comment by lukaasm** [comment]
ok, now should be really fixed
https://streamable.com/4jhze

15 rage after a change into Bear
60 after a change into Cat

**Comment by notsofamous** [comment]
Works!
