### ISSUE TITLE
[NPC]Captain "Stash" Torgoley

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#2503]
Description: 
NPC is missing

How it works: 
![wowscrnshot_120518_120729](https://user-images.githubusercontent.com/43579401/49510891-e3bfb580-f889-11e8-8539-526f8ff63716.jpg)
Ship has no captain

How it should work: 
There should stay this NPC

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Captain_%22Stash%22_Torgoley

**Comment by Dootz** [comment]
he can be found in his cabin below deck
