### ISSUE TITLE
Update Website Armory

### ISSUE THREAD

**Issue by grand-lotus-iroh** [SunwellWoW/Sunwell-TBC-Bugtracker#2506]
May you please update the TBC Armory so it works properly? I think it would be neat if I could stalk my friends while I'm not at the PC and see what kind of updates they've done. It looks like some data is being pulled into website but not correct data.

https://www.sunwell.pl/armory/Nightbane/Zeus

Maybe it's just wonky though....

https://www.sunwell.pl/armory/Angrathar/Cain
https://www.sunwell.pl/armory/Nightbane/Cain

**Comment by SunwellTracker** [comment]
It's not priority right now, however devs are working on that. It's not the bug regarding the gameplay.

**Comment by grand-lotus-iroh** [comment]
Can you please make it priority and add feature?
