### ISSUE TITLE
Elemental Shaman talents

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2508]
Description: A few talents not working properly

How it works: 
Elemental Focus seems to only soak one ability, should soak two.
Elemental Mastery gets soaked by any spell you use, or if an enemy hit you and proc your Water Shield, also lightning overload procs soak the buff.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Already reported. Will be fixed soon.
