### ISSUE TITLE
Dire Maul - North

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#251]
### **TO DO:**

- [ ] 1. Several Gordok Brutes and Gordok Mage-Lordes who have stationary position should sit. 
**EDIT#2: ~35 will stand and ~25 will sit**
- [x] 2. Gordok Courtyard Door (80184) shouldn't be opened. They should stay closed till someone opens them by Gordok Courtyard Key item (18266). For now there is no key requirement.
**EDIT: U can open them using the Key right now but the doors are still closed after use**
- [x] 3. Looks like Guard Fengus (14321) doesn't use Knock Away spell (10101).
**EDIT#2: Now he doesn't use it at all**
- [ ] 4. Netherwalkers (14389) hit for around 1.1-1.2k while they should for 790-939.
- [ ] 5. Knot Thimblejack misses Free Knot! quest. We should be able to complete this quest as we wish giving to him Gordok Shackle Key (18250). After that Knot should run from building and vanish in the entrance. Works good on Angrathar as well.
**EDIT: Npc still doesn't offer it**
- [x] 6. Gordok Inner Door gob (80190) are rotated in weird way. They should stay closed until someone will open them using Gordok Inner Door Key (18268).
**EDIT#2: same thing as gordok coutyard door**
![image](https://user-images.githubusercontent.com/22802214/44801759-35d1aa80-abba-11e8-8f93-5b59c6157fed.png)
- [x] 7. While we have Gordok Ogre Suit aura (22736) then Captain Kromcrush (14325) should be friendly npc with dialogue option. For now he stays hostile.
**EDIT: Still hostile**
![image](https://user-images.githubusercontent.com/22802214/44801866-8517db00-abba-11e8-8b60-6dec4a5fc730.png)
- [x] 8. Captain Kromcrush (14325) should use Call Reavers spell (22860) when he's at 50% hp. For now he uses that around 80%.
**EDIT#2: He still summons them around 75-80% hp and they have guids 1 and 2. They don't disappear after evade**
- [x] 9. Gordok Spirits (11446) shouldn't react when attacking them.
"These guys are in the King's room, behind him spread out against the curved wall. They will not attack or even turn around to face you so you can use them for PTR testing of dps cycles and procrates."
- [x] 10. Looks like Gordok Captain (11445) doesn't use Fear spell (12096).
**EDIT: Still doesn't use it**
- [x] 11. Gordok Mastiff just before King Gordok should have random movements. Guids: 248087, 248088, 248083, 248084, 248085, 248086, 248090, 248091, 248089.
- [x] 12. King Gordok and Cho'Rush the Observer should be linked with threat.
- [x] 13. Spawned Mizzle the Crafty is spamming his one emote once appeared. He finishes this spam after he stops his walk.
![image](https://user-images.githubusercontent.com/22802214/45809120-bb331100-bcc7-11e8-9bc5-835a85f9f4cd.png)
- [ ] 14. After Mizzle the Crafty gave me King of the Gordok buff (22799) all Gordok Spirits started to attack me. More funny is that they are friendly now but still chase me.
![image](https://user-images.githubusercontent.com/22802214/45809254-03eaca00-bcc8-11e8-8d96-71edcaea6908.png)
- [ ] 15. With King of the Gordok aura (22799) ALL ogres in Dire Maul North side should be friendly to us. For now they stay hostile.
**EDIT: Ok they are friendly but they are still attacking players with this aura. More weird is thing that when I got this aura I pulled entire ogres in whole instance. Just noticed that when Mizzle puts aura on players he forces ogres to attack us**
![image](https://user-images.githubusercontent.com/22802214/45809410-5deb8f80-bcc8-11e8-9288-b3aa42299a4d.png)
- [ ] 16. After we become the king Cho'Rush the Observer should have be able to talk with us with some text:
![image](https://user-images.githubusercontent.com/22802214/44804048-88ae6080-abc0-11e8-8606-adf3d7bf6243.png)
- [ ] 17. After we have King of the Gormok aura Cho'Rush the Observer has new text:
**EDIT: We can't talk with this ogre once he's friendly**
![image](https://user-images.githubusercontent.com/22802214/44804083-9cf25d80-abc0-11e8-9f6d-8e531e2eeb86.png)
- [ ] 18. After we have King of the Gormok aura, Mizzle the Crafty will have next 2 dialogues about Tribute:
**EDIT: Actually he has those 2 dialogues but he doesn't spawn chest after that**
![image](https://user-images.githubusercontent.com/22802214/44804123-bd221c80-abc0-11e8-87ea-b0bd658c9d50.png)
- [ ] 19. Mizzle the Crafty dialogues order:
![image](https://user-images.githubusercontent.com/22802214/44804289-33268380-abc1-11e8-825a-b4d9f829d144.png)
0 (Entry: 179564) - [Gordok Tribute X:808.369995 Y:482.127991 Z:37.318199 MapId:429]
- [ ] 20. Gordok Tribute gob loottables need to be checked. Loot depends up how many bosses we killed.
- [ ] 21. In addition, if our character is at 63lvl or below we can dialogue with every of bosses we skipped (Guards) in order to get buffs. After dialogue they will buff us (id on screen):
![image](https://user-images.githubusercontent.com/22802214/44805341-38390200-abc4-11e8-9721-b328ffd02937.png)
- [ ] 22. After we have King of the Gordok buff, Captain Kromcrush should offer us a quest Unfinished Gordok Business after short dialogue:
**EDIT: He offers that even w/o dialogues**
![image](https://user-images.githubusercontent.com/22802214/44804796-c0b6a300-abc2-11e8-84e1-0a8de4796701.png)

### **DONE:**

- [x] 1. Carrion Swarmer (13096) should use his Venom Sting spell (5416) more often.
- [x] 2. Carrion Swarmers have 1 model at this moment (13096). They should have 3 models in total and every mob should have random one (13096, 13097, 13111).
- [x] 3. Gordok Brute (11441) shouldn't use Backhand spell.
- [x] 4. Gordok Mage-Lord (11444) doesn't use three of his spells: Polymorph (13323), Flame Blast (14145) and Bloodlust (16170). Bloodlust should be casted on his nearby Gordok Brutes.
- [x] 5. Gordok Mastiffs (13036) that are not in formation with some ogres should have random movements. Guids: 248155, 248094, 248095, 248096, 248093, 248137, 248135, 248136, 248186, 248138, 248100, 248098, 248099, 248171, 248097, 248163, 248106, 248164, 248108, 248107, 248101, 248132, 248131, 248179, 248180.
- [x] 6. Guard Mol'dar (14326) has random movements while he shouldn't. He should have path similar to present on screen.
![image](https://user-images.githubusercontent.com/22802214/44797117-b4c0e600-abae-11e8-9cd0-f311866fc685.png)
- [x] 7. Guard Mol'dar should use his Shield Charge spell (15749) on random player.
- [x] 8. This one Gordok Brute (guid 247704) should stay where I put him. GPS on screen.
![image](https://user-images.githubusercontent.com/22802214/44798441-ca83da80-abb1-11e8-8b6c-f871c4a446b4.png)
- [x] 9. Those two Gordok Brutes (guids 247729, 247732) should have paths around inner circle. One of them should walk clockwise and second anticlockwise.
![image](https://user-images.githubusercontent.com/22802214/44798536-074fd180-abb2-11e8-8025-e482d28bd828.png)
- [x] 10. Stomper Kreeg (14322) misses three quotes during fight:
- I'll crush you!
- Me smash! You die!
- Raaar!!! Me smash <race>!
- [x] 11. Guard Fengus should use his Shield Charge spell (15749) on random player.
- [x] 12. Gordok Courtyard Door gob (80184) are rotated in weird way. They should stay closed until someone will open them using Gordok Courtyard Key (18266).
![image](https://user-images.githubusercontent.com/22802214/44798891-f18edc00-abb2-11e8-8c5f-c7c1871f3267.png)
- [x] 13. Wandering Eye of Kilrogg (14386) has 60lvl and 305 hp. It should has 55lvl and 4108 hp.
- [x] 14. Netherwalkers (14389) have 5544 hp. They should have 9176 hp.
- [x] 15. Guard Slip'kik (14323) is moving to fast.
- [x] 16. Guard Slip'kik should use his Shield Charge spell (15749) on random player.
- [x] 17. Knot Thimblejack shouldn't have Train option at all.
- [x] 18. Door gob (80188) is rotated as well.
![image](https://user-images.githubusercontent.com/22802214/44805740-56533200-abc5-11e8-8b22-5327787ded5f.png)
- [x] 19. Looks like Guard Mol'dar doesn't use Knock Away spell (10101).
**EDIT: Funniest thing ive seen today. He uses that spell but he's getting knocked away instead of targeted player**
- [x] 20. Gordok Mage-Lords (11444) are moving to fast.
- [x] 21. Netherwalkers spawned from Summon Netherwalker spell (22876) should disappear after 30 seconds from losing combat.
- [x] 22. Spawned Netherwalkers (14389) should start to attack players once summoned.
- [x] 23. A Broken Trap (1193) quest should be able to do on every Dire Maul enter. I did it on my previous run and I can't repeat it now while this quest should be able to pickup/complete on every run.
- [x] 24. Looks like Guard Slip'kik (14323) doesn't use Knock Away spell (10101).
**EDIT: Same thing as with Guard Mol'dar**
- [x] 25. Knot Thimblejack (14338) misses should have dialogue option, for now he says nothing. He has good dialogues on Angrathar:
![image](https://user-images.githubusercontent.com/22802214/44800907-ebe7c500-abb7-11e8-8c3a-9a3d127af2c3.png)
- [x] 26. Knot should offer us The Gordok Ogre Suit quest (5518). After it's completed he should start to offer us 5519 quest as repeatable q. For now he offers us 5519q w/o prequest as long as we don't free him by Free Knot! quest.
- [x] 27. Looks like Captain Kromcrush doesn't use his Frightening Shout spell (19134).
- [x] 28. Cho'Rush the Observer (14324) should be hostile till King Gordok (11501) is alive. For now he's friendly but suppose to be only if we kill King Gordok before him.
- [x] 29. After King Gordok is dead, Cho'Rush the Observer sits on ground and yells:
"The king is dead - OH NOES! Summon Mizzle da Crafty! He knows what to do next!"
That works fine except summoned Mizzle the Crafty (14353) shows up but doesn't continue outro event.  He should run to us and say few words. After that he should be able to talk and after short dialogue he will cast King of the Gordok buff (22799).
![image](https://user-images.githubusercontent.com/22802214/44803829-de363d80-abbf-11e8-9306-d4e087022cac.png)

**Comment by Kokaina** [comment]
Updated.

**Comment by Kokaina** [comment]
Updated.
