### ISSUE TITLE
[Quest][Event] King of the Foulweald

### ISSUE THREAD

**Issue by MayGyver** [SunwellWoW/Sunwell-TBC-Bugtracker#2513]
Description:  There is too many mobs and they are spawning too fast, its impossible to complete it solo, even with 5man group is very hard.

How it works: Works fine but too fast spawn and too many mobs spawning.

How it should work: Less mobs and less frequently.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
