### ISSUE TITLE
[Hunter] Changing targets during combat - Auto Shot stays on old target

### ISSUE THREAD

**Issue by ujellyx** [SunwellWoW/Sunwell-TBC-Bugtracker#2517]
Description: 
Right now, once you queued Auto Shot as a Hunter, the Auto Shot will continue on the same target, even if you change target, use abilities on the new target or even command "/cast Auto Shot" on a new target. The only way to force Auto Shot to the new target is to stop the Auto Shot and re-use it.

How it works: 
See above. Auto Shot somehow is stuck to one target, once used.

How it should work: 
Auto Shot should change the target as soon as you change a target. The "swing/shot"-timer continues and doesn't start from scratch after switching a target.

Source (you should point out proofs of your report, please give us some source):

**Comment by TheRealestMcCoy** [comment]
Confimed had this happen to me

**Comment by grand-lotus-iroh** [comment]
I too just noticed this also has error with hunter Auto Shoot

**Comment by alexnxs** [comment]
can confirm this as well

**Comment by primeropein** [comment]
confirm, also in addition to this, of the rare times it ACTUALLY swaps, u have to wait for almost 1-2 sec sometimes before that char shoots

**Comment by grand-lotus-iroh** [comment]
Both hunter and priest are unplayable b/c of this bug. Not being able to 
auto swap target makes the class half-as-fun...

**Comment by akrom23** [comment]
#2211
