### ISSUE TITLE
Psychic Scream not breaking

### ISSUE THREAD

**Issue by 0vertime** [SunwellWoW/Sunwell-TBC-Bugtracker#2518]
Description: 
On multiple occassions in pvp I have been aoe feared by priest spell Psychic Scream while having full dots from warlock, priest and a melee hitting me constantly.

How it works: 
It does not break from anything. Always full duration.

How it should work: 
It should have chance to break. Missing pulse or something.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
What's ur level?

**Comment by 0vertime** [comment]
Around STV levels.

**Comment by BronzeJukes** [comment]
Same with Fear i think

**Comment by sippycupmcjr** [comment]
If you are below level 60 then this is (probably) blizzlike. 

Check:
http://wowwiki.wikia.com/wiki/Fear_effect
http://wowwiki.wikia.com/wiki/Fear

Most notably: 
[From TBC] Patch 2.1.0 (22-May-2007): "Chance to break crowd control from damage: The increased chance for a spell to break from taking a critical strike has been removed. Instead, **all targets over level 60 have a slightly larger chance to break out of crowd-controlling effects when they take damage**."
[From WotLK] 3.1.0 (14-Apr-2009): The damage threshold to break early has been significantly reduced.

**Comment by 0vertime** [comment]
Generally spells emulated on 2.4.3 have been set to patch 2.4.3 to my knowledge. Only the content of items, unlocks, raids, dungeons and such have been manually emulated for progression.

**Comment by Wojtyas** [comment]
Moved to https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2424
