### ISSUE TITLE
The Slave Pens

### ISSUE THREAD

**Issue by Lonoss** [SunwellWoW/Sunwell-TBC-Bugtracker#252]
All listed issues are on both mode (norm/hero).
Additionally melee damage on heroic is a bit to low, but it's problem of 80-90% of mobs. So as a suggestion to boost up (20-30%) all mobs and then we can adjust it. Just melee dmg (spell are fine)

- [x] Patrolling NPC are not linked and they walking randomly instead going in group of 3.
Some of them are in textures (at least one)
Entry: 17816 and 178817
https://imgur.com/a/DyF532E

- [x] NPC - Bogstrok Entry: 17816
http://db.hellfire-tbc.com/?npc=17816#abilities
They freezing in place. Probably after using his ability or textures error.
https://imgur.com/a/PTbTKR1

- [x] NPC - Coilfang Champion Entry: 17957
http://db.hellfire-tbc.com/?npc=17957#abilities
Same as Bogstrok freezing with no reason.

- [x] NPC - Coilfang Enchantres Entry: 17961
http://wowwiki.wikia.com/wiki/Coilfang_Enchantress
Does not use ability: Domination, or use it one time on start fight

- [x] NPC - Coilfang Technician Entry: 17940
https://www.wowhead.com/npc=17940/coilfang-technician#abilities
Does not use ability: Blizard

- [x] Patroling mobs behind Mennu the Betrayer are not linked. Coilfang Technician (17940), Coilfang Defender (17958), Coilfang Colaborator (17962)
All of them are walking separatly instad of groups. Some of them even just stand still, instead of walking. Almost all of them have some problem with patrolling.
Whats more intersting one of the mobs can get agro from group under, as on SS.
https://imgur.com/a/2YIvGdA
Other example.
https://imgur.com/a/DbMe70n
https://imgur.com/a/mbBM2ph

- [x] NPC - Coilfang Scale-Healer Entry: 21126
http://db.hellfire-tbc.com/?npc=21126#abilities
She cast Power Word: Shield on enemy instead on himself. Plus, it looks on buff like a poison.
When start to cast his heal ability can't finish it. As a result he just standing and casting.

- [x] Missing NPC before last boss
Should be group of 3 and 4 Bogstrok patrolling, but its only 3 randomly walking (not linked).
https://imgur.com/a/MO08wg5

- [x] Event with Naturalist Bite Entry: 17893
Doesn't work. On hero he stand without cage.
https://imgur.com/a/AVxoTnN

- [x] NPC - Coilfang Collaborator Entry: 17962
http://db.hellfire-tbc.com/?npc=19903#abilities
Does not use ability: Revenge

- [x] NPC - Quagmirran Entry: 17942
http://db.hellfire-tbc.com/?npc=19894
You can freeze him and attack with range, he will just use spell. Probably he can't go out of water.
https://imgur.com/a/LV4o5Yp

**Comment by Riztazz** [comment]
closed by b955867a74c0f315a663d1a9f82512e77d761cd5 and 25ae8343fa419ca19306624c353e2520bd6b8bfe

**Comment by Silroth** [comment]
- Weeder Greenthumb missing dialogue text which should be: 
<it appears (missing text here, prob his name or "tauren druid") was killed quick and clean while trying to escape Slave Pens>

- Naturalist Bite after you free him from the cage one of the spawned Coilfang Champions should yell: "Intrudersss with the prissoner! Kill them!!!"
After you defeat the Naga he goes back into the cage and dialogue option isnt available anymore, he should move a bit further from the cage and look in direction of Quagmirran and have following dialogue text and option available:

"Uh oh! It would appear that all of the noise you've been making has attracted some unwanted attention!
Now that the rude interruption is over, as I was saying, Quagmirran is nearby!
As promised, I can fortify you with a magical boon that should aid you in your fight with him."
Dialogue option should be: "Naturalist, please grant me your boon" after which he should buff the player with Mark of the Bite (Spell ID 34906) which stacks with all other Nature resistance spells/abilities such as shaman totem, MotW, hunter's Aspect of the Wild etc
