### ISSUE TITLE
Hunter Pets - Spells missing

### ISSUE THREAD

**Issue by johan-nordstrom** [SunwellWoW/Sunwell-TBC-Bugtracker#2520]
Description: First i could not see growl in my pet bar. So i decided to unlearn my skills and learn them again. Now i do not have a tab in my spellbook for my pets.

How it works: Do not have a tab in my spellbook for pets.

How it should work: Spells for pets should be shown in spellbook.

Source (you should point out proofs of your report, please give us some source): Try taming a bear as a hunter, then learn growl and see if it appears on pet bar.

**Comment by akrom23** [comment]
Just relog and open again Beast Training.
