### ISSUE TITLE
[Quest] A King's Tribute (Quest ID: 689) - Granite Nodes drop cloth

### ISSUE THREAD

**Issue by westerngee** [SunwellWoW/Sunwell-TBC-Bugtracker#2521]
Description: The Granite Nodes (Object ID: 2714) additionally drop Wool and sometimes even Silk Cloth. 

How it works: 
You right-click them and then loot.

How it should work: 
They really should not because they are quest related mining nodes and don't do that on other Private Servers and didn't do that in retail either.

123

Source: 
![wowscrnshot_120518_172545](https://user-images.githubusercontent.com/39277340/49528526-60678980-f8b4-11e8-93f9-a12cc532802e.jpg)

**Comment by westerngee** [comment]
123

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
