### ISSUE TITLE
[Core][General]Water/land problem with raptor

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#2524]
Description: 
While attacking this mob, he didnt came to me, because i was in water. After comming out from the water, he came. He left combat when unattacked when i was in the water

How it works: 
![image](https://user-images.githubusercontent.com/43579401/49532763-8e050080-f8bd-11e8-9337-9dedb44b115d.png)

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Probably he has no inhibit_water flag. Some beasts shouldn't chase players to water and stay only on ground/land. Do you have a proofs that raports should chase players in water as well?

**Comment by Dootz** [comment]
@Wojtyas  
![obraz](https://user-images.githubusercontent.com/25490436/49539828-d842ad80-f8ce-11e8-9fa9-4341d2ffd977.png)

**Comment by Mikov1605** [comment]
its a swamp, u cant swim in the water. It should be counted as normal ground ;) They wont swim in it. Thats why its a bug
