### ISSUE TITLE
Debuff dispel mechanics

### ISSUE THREAD

**Issue by SuddenDeath** [SunwellWoW/Sunwell-TBC-Bugtracker#253]
Decription: Debuff dispel mechanics are incorrect.

How it currently works: 
Example:
Cast dispel/Devour magic on target with 5x charge of winter's chill debuff + polymorph.
Currently it's a 1/6 chance to remove polymorph.

Cast abolish/cure poison on target with 5x wound poison + 1x crippling poison
Currently it's a 1/6 chance to remove crippling poison

How it should work: 
A debuff with multiple charges such as winter's chill or wound poison should still count as 1 debuff.
Should be a 50% chance to remove crippling poison and 50% chance to remove 1 charge of wound poison.

Source (you should point out proofs of your report, please give us some source): 
http://www.arenajunkies.com/topic/34707-spell-pen-is-absolutely-worthless/#entry311213
http://www.arenajunkies.com/topic/114054-do-you-stack-winters-chill-vs-warlocks/#entry1589618
http://www.arenajunkies.com/topic/140581-blizzard-winters-chill-5-stacks-at-once/page-4#entry2097447
http://www.arenajunkies.com/topic/32697-why-does-devour-always-get-the-sheep/

Videos will unlikely be able to prove/disprove this because of the rng factor.

**Comment by lukaasm** [comment]
Closing, if something more pops out, ping me
