### ISSUE TITLE
First Aid 

### ISSUE THREAD

**Issue by lilAct** [SunwellWoW/Sunwell-TBC-Bugtracker#2531]
Description: No Skill Ups

How it works: When making bandages im no longer getting any skill ups

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/49541717-ecd57480-f8d3-11e8-995b-c571dea10c07.png)
works fine for me - probably you've reached max skill and need to learn higher level of First Aid - if that's not the case please add more informations + screenshot with First Aid window opened

**Comment by lilAct** [comment]
![](https://i.gyazo.com/e312b1cfeac9abcbc5bded82595ced7b.jpg)
uhm this seems off? *and there was another under but chat window not big enough

**Comment by Azathothh** [comment]
Your Linen Bandage recipe is already "gray" - which means that you've got 0% to gain skill for using this recipe. In order to get higher level of first aid you must learn more recipes from First Aid Trainer.
