### ISSUE TITLE
Cat form - changing indoor/outdoor movement speed

### ISSUE THREAD

**Issue by Aledati** [SunwellWoW/Sunwell-TBC-Bugtracker#2534]
Description: 
Cat form - changing idoor/outdoor movement speed (30% outdoor, 0%indoor)

How it works: 
When cat step indoor zone and moves out of it in outdoor zone, movement speed doesnt change to 30% regarding talent Feral Swiftness.
In oposite, when cat go from outdoor zone in to indoor zone movement speed decrease, I mean you loose that 30% bonus from talent which works only in outdoor zone, and this works properly.

How it should work: 
Movement speed in cat form should be changed (increased for 30%) once cat leaves indoor zone.
This should happen without changing shifts, as its needed at the moment on server.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
#2093.
