### ISSUE TITLE
Raze Direhorn Post! Quest is bugged

### ISSUE THREAD

**Issue by Valvie** [SunwellWoW/Sunwell-TBC-Bugtracker#2538]
Description:  I cannot use the torch next to the tent

How it works: You cannot use the torches near the tents. It says "Requires Grimtotem Tent"

How it should work:  You run up to the tent, use the item, and the tent gets lit on fire.

Source (you should point out proofs of your report, please give us some source):  https://www.youtube.com/watch?v=YOYwyIJlAvE

**Comment by Dootz** [comment]
Hi, did it happen for all tents? Or only one specific? I just so 3 players completing this quest. In East tent you just need to go a little bit deeper into tent.

**Comment by Valvie** [comment]
Yes sorry i was following that youtube video and they did it outside the tents
Works fine deep inside the tents
