### ISSUE TITLE
[Quest][NPC]What we don't know....

### ISSUE THREAD

**Issue by ThreadripperPL** [SunwellWoW/Sunwell-TBC-Bugtracker#2539]
Description: 
Exarch Admetius didn't buffing me a spell Exarch's Enchantment during accepeted a quest.

How it works: 
Captured Sunhawk Agent can't to complete quest without buff Exarch's Enchantment as Disguised as a blood elf.

How it should work: 
Exarch Admetius during accepted a quest buffing me Exarch's Enchantment. Speak to a Captured Sunhawk Agent at Blood Watch and recover Sunhawk Information. Return to Exarch Admetius when the task is complete.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Quest:What_We_Don%27t_Know...

**Comment by Dootz** [comment]
Hi, thank you for report. However it was already reported several times. I'll close this report.
