### ISSUE TITLE
naladu chain is broken

### ISSUE THREAD

**Issue by jockeboschko** [SunwellWoW/Sunwell-TBC-Bugtracker#2540]
Description: 
so doing this chain quest http://fax.dating-mir.com/quest=10403/naladu is impossible without gm interference. Akoru and aylaan are getting killed by arzeth and you cant start the chain. 

How it works: 

so doing this chain quest http://fax.dating-mir.com/quest=10403/naladu is impossible without gm interference. Akoru and aylaan are getting killed by arzeth and you cant start the chain.
How it should work: 

Naladu is spawned a little to the front of his hut when he should be inside it. Arzeth seems to path to the sides alot. He should just path in the middle
Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
