### ISSUE TITLE
The Flesh Lies Cave

### ISSUE THREAD

**Issue by Fuzedknight** [SunwellWoW/Sunwell-TBC-Bugtracker#2541]
Description: The mob overspawning with this quest at Manaforge Ultris in Netherstorm is outrageous, there are 4+ mobs spawned inside each other. Every time you pull something you get 6+ of the enemies making the cave and the quest completely impossible solo. (not a group quest)
https://puu.sh/CcYyf/822e54e242.png

Edit: It also seems like the corpses that spawn the fleshbeasts are triggering even on the mountain above the cave causing more spawns in the cluster cave.
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Fuzedknight** [comment]
It looks like it got even worse since I initially reported it, decided to have a look inside.
https://puu.sh/Ceeok/4a859253c7.png

**Comment by thearmo** [comment]
Can confirm. Seems there is more mobs and the aggro radius is even bugged. I aggro mobs inside the cave when I am on the mountain on top of it right near Manaforge Ultris.

**Comment by dovadx** [comment]
It is impossible to be able to burn these before a corpse pops and spawns a fleshling, it should spawn oone if you sit ontop of it just like the trash mobs in Arcatraz, but they spawn before you even get a chance to get near enough to use the q-item.

**Comment by Dootz** [comment]
range will be decreased with next server update. Thank you for report.

**Comment by bigripper** [comment]
Looks like it never got fixed?

**Comment by zefurr** [comment]
Issue persists, seems a few corpses (saw 20-30%) can be burned by taking baby-steps closer until the flamethrower is in range, but most will spawn a mutant before you can burn it

And as has been said, it seems like there's no Z axis check for the proximity

Managed to complete the quest by waiting on the respawn of a couple Withered Corpses that I was consistently able to burn by baby-step method

**Comment by 0vertime** [comment]
The corpses agro in AoE link of around 20-40 yd, through walls even. Also the combat stays on you so if you sprint around the cave, every corpse will activate.
