### ISSUE TITLE
Shamanistic focus

### ISSUE THREAD

**Issue by Wobbey291** [SunwellWoW/Sunwell-TBC-Bugtracker#2543]
Description: 
Shamanistic focus does not proc or is consume by something other than a shock spell.

How it works: 

Shamanistic focus does not always proc on a melee crit when it should.
When it does, the buff may not be applied and even if it is the buff is consumed by either flame shock dot ticks or melee hits.

How it should work: 

It should always proc on a melee crit AND should only be consumed by casting another shock spell.

Source (you should point out proofs of your report, please give us some source): 

My enhance shaman that wants to save 60% mana on his shock spells

**Comment by Wojtyas** [comment]
Already reported, will be fixed soon.
