### ISSUE TITLE
Black Dragonflight Molt

### ISSUE THREAD

**Issue by Elefant0n** [SunwellWoW/Sunwell-TBC-Bugtracker#2545]
Description: Advised by gm, I'm reporting a missing item from the "Hoard of the Black Dragonflight"
I did not receive this item when opening the bag.

How it works: Opened "Hoard of the Black Dragonflight" but did not receive the item!

How it should work: What i can find about the item it's a 89% drop rate and leads up to the BRD quest.
But i'm pretty sure it's supposed to be 100%

Source (you should point out proofs of your report, please give us some source): 
https://tbc-twinhead.twinstar.cz/?item=10575#contained-in-item

Best Regards, Sqwatter.

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
