### ISSUE TITLE
[Warrior] execute performes an interupt

### ISSUE THREAD

**Issue by Rattacrash** [SunwellWoW/Sunwell-TBC-Bugtracker#2547]
Description: 
execute performs an interupt, thats stops other abilitys cueued from been casted, even if not all conditions that r needed to perform an execute r forfilled, it pretty much behaves like a "stop casting"-macro-function

How it works: 
if u cast an heroic strike and the autoswing timer is not up yet, the UI shows that an heroic strike is going to be performed as soon as the swingtimer is up, if u now press the button for execute, even tho an execute wouldnt be possible at this moment, the queued heroic strike is canceled, my UI even tells me for a split second that an "interrupt" had been performed

How it should work: 
this is absolutly not what execute should be doing, it is impossible to write an execute/heroic strike macro, if execute is behaving like this

Source (you should point out proofs of your report, please give us some source):

**Comment by Robin-Combeau** [comment]
can confirm, happens 100% of the time.
