### ISSUE TITLE
Forge Camp: Mageddon

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#2548]
Description: 
Forgefiend Razorsaw does not drop his head 100% of the time

How it works: 
Forgefiend Razorsaw does not drop his head 100% of the time

How it should work: 
should drop 100% of the time

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
weird, it have 100% drop chance. I've killed him 20+ times and he always dropped head

**Comment by badmannerkid** [comment]
i had a similar issue with Grillok "Darkeye" as well. Coudln't loot his eyepath for the quest of the same name. I had to relog
