### ISSUE TITLE
Hunter Pet not using abilities

### ISSUE THREAD

**Issue by finalhonor** [SunwellWoW/Sunwell-TBC-Bugtracker#2550]
[Hunter] Oledirtybast 24, My pet Ghostface (Gost cat from darkshore) will not use Claw bite or Growl even though they are trained to the pet. All spells are on pet bar and enabled but pet will not do anything but auto attack. When I dismiss the pet and recall it growl is no longer enabled on the bar and manually clicking any of the abilities does nothing. Also I noticed that the tab for pet abilities is not there where it should be when open my character abilities (default P)

Things I've tried:

Dismiss pet and recall
Restart game completely
Disable all addons
Delete cache and wtf

**Comment by ujellyx** [comment]
Do you have any addons related to action bars or pets?

**Comment by finalhonor** [comment]
As stated above i disabled all addons and its still doing it

**Comment by akrom23** [comment]
Works fine.
