### ISSUE TITLE
Mooncloth is acting as if it has a CD despite the interface showing it does not

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#2551]
Description: In TBC the cooldown on mooncloth is removed, yet on Sunwell despite the interface not showing a cooldown you are only allowed to make one.

How it works:  Hidden cooldown prevents you from making multiple mooncloth

How it should work: Unlimited mooncloth in tbc

Source (you should point out proofs of your report, please give us some source): 
Patch changes

TBC Patch 2.4.3 (patch date::2008-07-15): Purifying Mooncloth cooldown was removed. Before the patch the procedure can only be performed once every 92 hours (3 days, 20 hours). 

http://et.worldofwarcraft.wikia.com/wiki/Mooncloth

**Comment by Mikov1605** [comment]
so it has no CD since Sunwell. We're currently at Karazan, so yeah, its intended to have a nearly 4 days cd
