### ISSUE TITLE
Paladin Blessings 

### ISSUE THREAD

**Issue by Adrestiah** [SunwellWoW/Sunwell-TBC-Bugtracker#2552]
Description:  Paladin blessings stack.

How it works:  If a paladin buffs greater blessing of might and another paladin buffs blessing of might these buffs will stack. 

How it should work: The buffs should not stack and greater blessing of might shouldn't be over ridden by blessing of might. 

Source (you should point out proofs of your report, please give us some source):

**Comment by fakelort** [comment]
This doesn't seem fixed. I just had a greater blessing of wisdom and a regular blessing of wisdom on at once. Not sure if it was different ranks
