### ISSUE TITLE
[Quest] Redemption (5742)

### ISSUE THREAD

**Issue by kachnicka** [SunwellWoW/Sunwell-TBC-Bugtracker#2553]
Description:
Can't complete the quest.

How it works: 
You take quest, no dialogue bubbles to hear the story appears.

How it should work: 
Dialogue menu should appear after taking the quest.

Source (you should point out proofs of your report, please give us some source): 
Obvious, also old comments on https://www.wowhead.com/quest=5742/redemption#comments

**Comment by Dootz** [comment]
It's my favorite quest because people don't read  description and think it's broken. You need to /sit to be able to listen to his story :D

**Comment by kachnicka** [comment]
![image](https://user-images.githubusercontent.com/10644702/49550762-03d49080-f8ed-11e8-8c7d-45f44f21e06a.png)

Not really that obvious tho :x

**Comment by Dootz** [comment]
If you talk to Tirion and select this quest he'll tell you what to do :D

![obraz](https://user-images.githubusercontent.com/25490436/49551443-865e4f80-f8ef-11e8-92dc-1e4aca8739af.png)
