### ISSUE TITLE
Lard lost his lunch (49H hinterlands quest)

### ISSUE THREAD

**Issue by deftelite** [SunwellWoW/Sunwell-TBC-Bugtracker#2554]
Description: 
(49H quest) Lard lost his lunch is not working properly.

How it works: 
When the basket is looted 3 kidnappers spawn and immediately aggro the person.  They do not despawn when the character who loots the basket dies.  

How it should work: 
When the basket spawns 2 kidnappers should spawn and immediately aggro the person.  The kidnappers should despawn if whoever looted the basket (or group) dies.  As it currently stands the quest can be "started" multiple times resulting in large numbers of the kidnappers spawning in that location.  

Source (you should point out proofs of your report, please give us some source): 
As of patch 2.4.3, interacting with Lard's lunch only spawns 2 vilebranch kidnappers. (wowhead: https://www.wowhead.com/quest=7840/lard-lost-his-lunch#comments)
Many elite creatures and quests in the level 1-60 experience have been changed to accommodate solo play. (patch notes for 2.3.0) (http://wowwiki.wikia.com/wiki/Patch_2.3.0)  
Unfortunately I could not find it directly referenced in any patch notes, but 2.3.0 was a big change patch with solo questing in vanilla zones.

**Comment by Dootz** [comment]
fixed & implemented
