### ISSUE TITLE
Inspiring Presence (Draenei)

### ISSUE THREAD

**Issue by s2nratio** [SunwellWoW/Sunwell-TBC-Bugtracker#2555]
Description: 
Inspiring Presence can be removed but it should be always up

How it works: 
If you accidentally right click Inspiring Presence in your Buff Bar the racial passive is gone - no chance to rebuff it until you relog. 

How it should work: 
Racial passives should not be removable

Source (you should point out proofs of your report, please give us some source): 
It's easily reproduceable, i only tried the caster version of inspiring presence though.

**Comment by TheRealestMcCoy** [comment]
Heroic Presence does the same thing
