### ISSUE TITLE
[Mobs] Issues / Scripts

### ISSUE THREAD

**Issue by Penthax** [SunwellWoW/Sunwell-TBC-Bugtracker#2556]
**Description:** Mobs Issues / Scripts - My English is not the best.

(1) -Mobs Spam there Spells without an intern Cooldown.
(2) -Mobs still casting there Spells while stunned
(3) -Mobs are still walking around few times when they got CC.
(4) -Mobs are not facing you correctly..they just still walking around and throw Spells on you.

**How it works:** 

(1)- Mobs spamming Disarm on me, as Example " Ungoro - Tar Creeper Mobs" iam always disarmed.
(2)- Mobs still can Disarm me while they are Stunned " Ungoro - Tar Creeper Mobs" works maybe on other Mobs aswell.
(3)- Saw some Mobs cc´d with Icetrap but still running aroung.
(4)- Mobs are not facing you correctly..they just still walking around and throw Spells on you.

**How it should work:** 

(1) -Mobs dont Spam Spells like Disarm as example.
(2) -Mobs cant casting or throwing Debuffs on a Player while stunned.
(3) -Mobs are not eligible to walk while CC (Icetrap)
(4) -Mobs are not facing you correctly, if you LoS them they come to you. if not they stand still and casting Spells on you

Source (you should point out proofs of your report, please give us some source):

**Comment by Penthax** [comment]
Looks like some Mobs have strange Issues too
I got like oneshotted in Ungoro from "Elder Diemetradon´s"

https://gyazo.com/c1c8617443a83871298648ac59d9116a
https://gyazo.com/7d253094049401751293dfc3b5d4e5f0

- This happen in like 1 second (x3 on same Mob)

**Comment by sadfx** [comment]
Pterrordax in Un'goro fear way too often as well.. 50% uptime

**Comment by sadfx** [comment]
I was killed by a Pterrordax that hit me 4 times in one swing as well

**Comment by rychersky** [comment]
Frenzied Pterrordax's melee swing hits Terrez for 79 Physical. 
Frenzied Pterrordax's melee swing hits Terrez for 72 Physical. 
Frenzied Pterrordax's melee swing hits Terrez for 76 Physical. 
Frenzied Pterrordax's melee swing hits Terrez for 74 Physical. 
Frenzied Pterrordax's melee swing hits Terrez for 76 Physical. 
Terrez's Slam hits Frenzied Pterrordax for 263 Physical. 
Frenzied Pterrordax's melee swing hits Terrez for 79 Physical. 
Frenzied Pterrordax's melee swing hits Terrez for 78 Physical. 
Frenzied Pterrordax's melee swing hits Terrez for 68 Physical. 
Terrez's melee swing hits Frenzied Pterrordax for 194 Physical. 
Terrez's Slam hits Frenzied Pterrordax for 273 Physical. 
Frenzied Pterrordax's melee swing hits Terrez for 76 Physical. 
Frenzied Pterrordax's melee swing hits Terrez for 81 Physical. 
Frenzied Pterrordax's melee swing hits Terrez for 71 Physical. 

Yea this is a little ridiculous.
