### ISSUE TITLE
Prowl breaks Eyes of the Beast

### ISSUE THREAD

**Issue by bhe0** [SunwellWoW/Sunwell-TBC-Bugtracker#2558]
Description: Using Prowl in Eyes of The Beast causes loss of control.

How it works: Using Prowl while in Eyes of the Beast causes loss of control. Upon using Prowl it "switches" the pet with a stealthed model and you can no longer move as the pet. 

How it should work: Eyes of the Beast lets a Hunter control their pet for one minute and are able to use any of the pet's spells, including Dash and Prowl. 

Edit: Adding on to say that using Dash will also break Prowl, which also should not happen. 

Source (you should point out proofs of your report, please give us some source):  https://streamable.com/49c9z

**Comment by akrom23** [comment]
@bhe0 Cannot reproduce it.
