### ISSUE TITLE
Mage Blink doesn't work on Inclines

### ISSUE THREAD

**Issue by RarecandyMage** [SunwellWoW/Sunwell-TBC-Bugtracker#2559]
Description: Mage blink incline issue

How it works: Running up the ramps next to the bank in Undercity, unable to blink up the ramps.  A tunnel in Hillsbrad Foothills, was unable to blink up a slightly inclined ramp.

How it should work: Character should blink up ramps 20 yards 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
#2608  #1584 #898
