### ISSUE TITLE
Rogue vanish/stealth glitch with pet

### ISSUE THREAD

**Issue by Kalisss** [SunwellWoW/Sunwell-TBC-Bugtracker#2562]
Description: 
There is a bug in the interaction with the vanish/stealth and hunter pet (not sure about other classes with pet).

How it works: 
When a hunter sends a pet on you and you vanish, the pet still follows you where you go (while still vanished) but cant attack.

Same goes for regular stealth. Hunter sends pet on you but lets say you can get a small distance so pet doesnt hit you so you get out of combat, you go stealth but pet still follows you.

How it should work: 
After stealth/vanish, pet should return to hunter.

Source (you should point out proofs of your report, please give us some source):

**Comment by ghost** [comment]
Addition: After vanishing, stealth will sometimes fade without reason, even if you take zero damage, or have a debuff to reveal.

**Comment by akrom23** [comment]
@Kalisss Cannot reproduce it. Give me some screenshots.

**Comment by Kalisss** [comment]
@akrom23 Screenshots kinda dont show anything but I will tell you exactly what to do. Duel a hunter with pet, let him send it on you to attack you (you get combat). Gouge him, run away from him, once the gouge ends, pet will start running towards you and as soon as the combat drops, go in stealth. The result will be you will be in stealth while pet not attacking you but following you.

Tried the same just without combat at all. Just start duel with hunter. Run away a bit (not in combat still), let him send the pet on you and before the pet reaches you to put you in the combat, go in stealth and the result should be the same.

Just tried it now with my 52 lvl rogue and 60 hunter. He couldnt see me but pet followed me. (I dont think it depends on the level of the players).

Same goes for Vanish.

**Comment by Kalisss** [comment]
![wowscrnshot_120718_100755](https://user-images.githubusercontent.com/45643801/49638770-82265500-fa09-11e8-9de3-70aad2f1b04b.jpg)
![wowscrnshot_120718_100758](https://user-images.githubusercontent.com/45643801/49638771-82265500-fa09-11e8-9395-f1532c14852f.jpg)

**Comment by akrom23** [comment]
@Kalisss Thanks for a detailed report. I'll try it.

**Comment by akrom23** [comment]
I think that the pet's level is high enough to detect your stelath - that's why he's still following you. 
I can reproduce it, but when pet detects my stealth, always attack me.
You use vanish rank 3 and stealth rank 4?

**Comment by Kalisss** [comment]
@akrom23 Hmm I tried it now and lower lvls pets come back and its fine. But I've seen some hunters as well complaining about that. Anyway even if it is higher pet lvl and he detects me, he doesnt attack as you can see on the screenshots. Have you tried that as well?

**Comment by akrom23** [comment]
Nope - pet always attacked me. Maybe record a video, where I can see everything?

**Comment by ghost** [comment]
@akrom23 Send pet to attack from a slight distance, rogue will be left out of combat to use stealth. When stealth is cast the pet will continue to chase until he hits the target, even if the pet is 10+yd away.

**Comment by Kalisss** [comment]
@moonsti That is exactly what happened for me as well. In STV i think I was like 35 and enemy hunter 36 and pet was chasing me not attacking while I was in the stealth.

Same happened to me when I was 52 and enemy hunter 60.

But with lower level - pet 58, me 60, pet just returns.

I think it has to do something with stealth detection (if you stealth from far distance, pet will return since it is not able to detect you, if you stealth closer and it detects you, it will follow you). Then ofc the higher level, the further pet can be to spot you.

Nevertheless the pet is still not attacking you even if it can detect you but instead just follows.

**Comment by akrom23** [comment]
Nopre. Guys, I need a video. Tried a trillion times and still nothing. I guess I'm a noob and don't know what to do :/

**Comment by akrom23** [comment]
Any news here?

**Comment by akrom23** [comment]
No reponse.
