### ISSUE TITLE
[Item] A Mysterious Tome / [Quest] Decipher the Tome

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#2565]
Description:  / How it works: 
- feels like "A Mysterious Tome" is not implemented into the game?
- killed like 50 of these mobs

How it should work: 
- while killing mobs in Hellfire Expedition Armory, "A Mysterious Tome" should drop to start the Quest-Chain "Decipher the Tome"

123

**Comment by waterloorick** [comment]
I got it on my 15th Unyielding Knight. I killed a hundred of the others. Other databases show that the Knights are at 12% drop

**Comment by trevorjk** [comment]
drop rate on th is aint right, i killed so many

**Comment by Dootz** [comment]
I'll increase it a bit.

**Comment by FrauHolle86** [comment]
it should drop within the first few mobs, if you've never done the quest chain or dont have the item in your inventory at this moment

**Comment by Dootz** [comment]
fixed & implemented
