### ISSUE TITLE
  [Professions] Enchanting - disenchanting huge issue

### ISSUE THREAD

**Issue by Ghostrider1996** [SunwellWoW/Sunwell-TBC-Bugtracker#2566]
Description: 
There is something wrong with enchanting when i try to disenchant a crafted wand from same profession named <''Lesser Magic Wand''> it says that i must get 65535 number of skill to be able to disenchant the wand

How it works: 
it required 65535 skills for 5 lvl green item, which is insane

How it should work: 
Green items from that lvl usually required 25 skills

Source (you should point out proofs of your report, please give us some source):

**Comment by ghost** [comment]
The error message is incorrect; however, you can't disenchant wands.

**Comment by tihiniko** [comment]
Yeah, you were never supposed to DE crafted wands (They give the mats needed to craft, even sometimes double). However I can't seem to DE blacksmithing items! That should for sure be possible
