### ISSUE TITLE
The end of the Deserters

### ISSUE THREAD

**Issue by Moenguten** [SunwellWoW/Sunwell-TBC-Bugtracker#2567]
Description: 
https://www.wowhead.com/npc=23941/gavis-greyshield#comments

How it works: 
Questmob does not spawn

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
- [ ] Also: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2819

**Comment by ghost** [comment]
NPC 30775 Gavis Greyshield, once player completes quest, NPC will still attack the player and follow him. NPC will not return to his original spot and cannot be killed.

Once player attacks him (takes him to 10) and goes friendly (quest complete), he should not enter in combat with player again.

https://imgur.com/a/Z5I6uGR (Here, the NPC followed this player untill killed him and remained there)
