### ISSUE TITLE
[Priest][Shaman] Dispel/Purge

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#257]
Decription: 
They are binary spells and therefor either removes 2 magic effects (with rank2 of the spell) or is completely resisted

How it works: 
Dispel and purge can be partially resisted

How it should work: 
Dispel and purge should not be partially resisted

Source (you should point out proofs of your report, please give us some source): 
https://i.gyazo.com/202fe581391a1f79cd40fe0648cbfbde.png
Google 'purge partial resist', no wow results, it has never happened.

**Comment by akrom23** [comment]
@notsofamous 
Canot reproduce now.

**Comment by notsofamous** [comment]
Seems to work now.
