### ISSUE TITLE
[NPC] Dreghood Elders 

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#2570]
Description: 
npc=20679, npc=20677, npc=20678 all need to be respawned, they're not spawning after they disappear when you "Free" them for the quest "Dreghood Elders" http://db.hellfire-tbc.com/?quest=10368

How it works: 
npc=20679, npc=20677, npc=20678 all need to be respawned, they're not spawning after they disappear when you "Free" them for the quest "Dreghood Elders" http://db.hellfire-tbc.com/?quest=10368

Their respawn timer is way too long, people can't get credit after someone else "frees" them because they disappear and don't reappear for 10+ mins

How it should work: 
Theyt should reappear as jailed so other people can free them for credit on the quest more frequently

Source (you should point out proofs of your report, please give us some source):

**Comment by neheri** [comment]
Please increase their spawn rate, not it seems to be 30 minutes and a lot of people are camping each elder all the time...

**Comment by neheri** [comment]
In addition to them not respawning for huge amount of time, I was lucky to be there when server crashed and I noticed that sometimes there are multiple NPCs spawned.

![wowscrnshot_121018_074153](https://user-images.githubusercontent.com/37372869/49715139-bc813380-fc4f-11e8-83a3-fe2fee2b69ff.jpg)
