### ISSUE TITLE
Hunter's Pet Abilities being 66% blocked every hit.

### ISSUE THREAD

**Issue by nexualhd** [SunwellWoW/Sunwell-TBC-Bugtracker#2571]
Description: Hunter's pet's special abilites (specifically "Claw"). A rank 5 claw is supposed to hit for 21-29 damage, baseline. It's currently hitting for 7-10dmg each swing on mobs. I checked the combat log, and I found that of the 30 damage the claw is doing, 20 of it is getting blocked. I think this is clearly a bug, as all mobs shouldn't be negating 66%+ of your pets DPS.
![blocked](https://user-images.githubusercontent.com/45645081/49556033-155b6f80-f8d0-11e8-8241-dffd391f1a69.png)

How it works: Pet's special abilities (Claw, for example) are getting blocked for over 2/3s of their damage by mobs

How it should work: I'd have to guess the numbers should be around 1/4th to 1/3 dmg reduction to be in line with retail.

Source (you should point out proofs of your report, please give us some source): Just use a hunter's pet with claw to attack a mob, and observe the combat log. The majority of the damage will be mitigated.

**Comment by Iperyth** [comment]
It does not only work for special attacks, most mobs block both skill shots and normal shots (as well as pet's ones).
Example:
![wowscrnshot_120618_125041](https://user-images.githubusercontent.com/45659353/49582946-e89e6b00-f956-11e8-91a4-5631368c0af2.jpg)

**Comment by ujellyx** [comment]
What level is your pet and what level were the opponents? For me my pet hit's 90% of his Claw ability, no blocks.

**Comment by Iperyth** [comment]
Level difference has nothing to do with ability to block. Also, you should never block ranged attacks.

**Comment by ujellyx** [comment]
Ranged attacks can also be blocked. (see wowwiki)

**Comment by YoshGit** [comment]
#1631
