### ISSUE TITLE
[Quest] Arelion's Mistress

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#2572]
Description: 
Arelion's Mistress respawn timer is ~10 min. Might want to reduce this considering the amount of people in the zone. A lot of important quest NPCs have too long of respawn for such population. Also, when she reaches her "Discreet Location" she just disappears

How it works: 
Arelion's Mistress respawn timer is ~10 min. Might want to reduce this considering the amount of people in the zone. A lot of important quest NPCs have too long of respawn for such population. Also, when she reaches her "Discreet Location" she just disappears

How it should work: 
might wanna have a quicker respawn for this population of players. also, she shouldn't despawn after she reaches her "discreet location". should be able to use Carinda's Scroll of Retribution once she reaches that location

Source (you should point out proofs of your report, please give us some source): 

Verify: 123

**Comment by Piootrek** [comment]
Don't disappear for me and she has 5 minutes respawn timer.
