### ISSUE TITLE
Slow fall Bug

### ISSUE THREAD

**Issue by Caulist** [SunwellWoW/Sunwell-TBC-Bugtracker#2573]
Description: 
When casting slow fall on a group member it self casts instead

How it works: 
Cast slowfall with party member targeted and it will cast on yourself

How it should work: 
Slow fall should be cast on party member

Source (you should point out proofs of your report, please give us some source): 
I am a mage trying to cast it on a friend, I don't really know how to provide anymore proof

**Comment by doomnyx** [comment]
I know how to provide proof.

https://www.wowhead.com/spell=130/slow-fall#comments:id=503899

/clap, report invalid.
