### ISSUE TITLE
Deranged Boars in Hellfire and INSANE thorns

### ISSUE THREAD

**Issue by waterloorick** [SunwellWoW/Sunwell-TBC-Bugtracker#2574]
Description: The boars have varying thorns all the way up to 300!!! It seems there are multiple hits.

How it works: 1 hit = 1 proc of thorns

How it should work: 

Source (you should point out proofs of your report, please give us some source): Picture https://imgur.com/a/rW3FUqP

**Comment by Wojtyas** [comment]
Already reported https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2439
