### ISSUE TITLE
City of Light Bugged(Shattrath intro quest) 

### ISSUE THREAD

**Issue by Swiplington** [SunwellWoW/Sunwell-TBC-Bugtracker#2576]
Description: Picked up quest as normal, but fell off the side of the balcony, ghost disappeared and when i went to abandon and pick up the quest he never spawned so now im stuck on the intro quest. Which means i cant start shattrath

https://www.wowhead.com/quest=10211/city-of-light

How it works: 
 read above

How it should work: 
Ghost should pop up again after picking up the quest again

Source (you should point out proofs of your report, please give us some source): 
Personal experience.

**Comment by Swiplington** [comment]
Flying out and into the city fixes it

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2708
