### ISSUE TITLE
[Shaman] Totems

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#258]
- [x] 1. They spawn too close to the character
On Sunwell: https://i.gyazo.com/79d601656cf34ed7308da56296c6743a.jpg
How it should be: https://www.engadget.com/2009/09/03/new-shaman-totems-in-the-expansion/
https://wow.gamepedia.com/Shaman_totem

- [x] 2. Removed.

- [x] 3. Mana Tide does not ignore LoS, it **should** just like all other friendly totems.

**Edit: Think you misunderstood. Mana Tide **should** ignore LoS, but it doesn't. Video: https://i.gyazo.com/aefd55bf96a544ce8f8d85066ab396ac.mp4**

- [x] 4. You should not be able to cast any friendly buff on totems or be able to heal them. Should display an "immune" message if you attempt this. Currently you can heal and cast any buff on them. (It doesn't benefit from any buff currently, though)

**Edit: Try to google "buffing (or healing) shaman totem wow" there are zero instances where this occured on retail, you will not find anything relevant. If you ever engaged a shaman who used Fire Elemental Totem you would always kill the totem rather than the elemental because the totem couldn't be healed while the elemental could. If this was a thing you could just put Earth Shield on the totem to protect it from being killed.
Source: my 350 days /played as a shaman in TBC/Wotlk/Cata** 

- [x] 5. Totems should cause no threat, currently totems like healing stream and mana spring cause huge amounts of threat. The only totem that should cause threat is stoneclaw.

**Edit: Video of Mana Spring Totem getting aggro: https://i.gyazo.com/0bbf0a888234867584bc5a8f87dd8888.mp4**

- [x] 6.  Casting a new totem while one is already active of the same kind will despawn the current one (correct), but the new one won't spawn. Example: Mana Spring Totem is active, if you cast a different water totem it will only spawn for a millisecond. Video: https://i.gyazo.com/5bbd63123755ce06d8f4c0cb17e66fd6.mp4

**Comment by notsofamous** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2129
https://github.com/Looking4Group/L4G_Core/issues/402

**Comment by akrom23** [comment]
2. Is not a bug. You linked video to wotlk server. On wotlk this spell works differently.
https://wow.gamepedia.com/index.php?title=Healing_Stream_Totem&oldid=1055694

> Applies **a buff** to party members which restores XX health every 2 seconds, scaling with the caster's bonus healing value at the time of the casting.

**Comment by akrom23** [comment]
> You should not be able to cast any friendly buff on totems or be able to heal them. Should display an "immune" message if you attempt this. Currently you can heal and cast any buff on them. (It doesn't benefit from any buff currently, though)

Source?

**Comment by akrom23** [comment]
4. Again - cannot reproduce.

**Comment by notsofamous** [comment]
Updated.

**Comment by akrom23** [comment]
> 4. You should not be able to cast any friendly buff on totems or be able to heal them. Should display an "immune" message if you attempt this. Currently you can heal and cast any buff on them. (It doesn't benefit from any buff currently, though)
Edit: Try to google "buffing (or healing) shaman totem wow" there are zero instances where this occured on retail, you will not find anything relevant. If you ever engaged a shaman who used Fire Elemental Totem you would always kill the totem rather than the elemental because the totem couldn't be healed while the elemental could. If this was a thing you could just put Earth Shield on the totem to protect it from being killed.
Source: my 350 days /played as a shaman in TBC/Wotlk/Cata

So totem should be immune to all positive spells - healings/buffs etc?

**Comment by notsofamous** [comment]
Yes, and I know some servers have issues with Chain Heal jumping to the totems. Couldn't reproduce it here but it's something to keep in mind. Chain Heal and Prayer of Mending should ignore them as targets.

**Comment by akrom23** [comment]
Okay.
