### ISSUE TITLE
Timbermaw Hold Quest Receiver Bug

### ISSUE THREAD

**Issue by DeepHook123** [SunwellWoW/Sunwell-TBC-Bugtracker#2582]
Description: 
This bug occurred when attempting to complete the Deadwood Ritual Totem quest obtained from a quest item in Felwood. The quest requires you to achieve neutral or greater reputation with Timbermaw Hold and to speak with Kernda in Timbermaw Hold.

How it works: 
When achieving neutral rep, Timbermaw Hold toggles "At War" off in the reputation screen. However, Kernda is not interact-able by the player. The player must go to the reputation page and toggle "At War" on and then off.  Kernda then can be interacted with to turn in the quest.

How it should work: 
Kernda should be interact-able by the player once neutral or greater reputation is achieved without further changes to reputation. It is also possible that this will occur with other Timbermaw Hold/Faction Reputation quest receivers, but this has not been tested. 

Source (you should point out proofs of your report, please give us some source): 
Player interaction (Holyspells) with quest giver around 0500 server time, assisted and resolved by GM Adrestia.

**Comment by Macnjacks** [comment]
Any clue when this will be fixed?

**Comment by DeepHook123** [comment]
No clue, Hasn't been assigned to anyone. Have you been able to interact with Timbermaw quest receivers in Felwood/Wintersprings? I haven't interacted with Timbermaw Reputation since logging this bug.

**Comment by Macnjacks** [comment]
I just tried to turn in the quest to Kernda for the 2 looted items, no luck.

**Comment by DeepHook123** [comment]
Did you toggle "At War" on and then off after reaching neutral reputation with the Timbermaw Hold?

**Comment by Macnjacks** [comment]
I just did and it seemed to fix it.
