### ISSUE TITLE
[NPC][Movement] Many NPCs walk instead of run

### ISSUE THREAD

**Issue by fakelort** [SunwellWoW/Sunwell-TBC-Bugtracker#2588]
Description: 
Many NPCs walk instead of run. 

How it works: 
Many NPCs move increadible slow, you can kite mobs in between spells/weapon swings without taking any damage.

How it should work: 
You should not be able to run faster than NPCs on regular run speed. 

Source (you should point out proofs of your report, please give us some source): 
Bonechewer Scavangers is one example.

**Comment by Aledati** [comment]
Yes this happens im almost each zone but not for all mobs.

**Comment by Wojtyas** [comment]
Already reported, hope it will be done soon.
