### ISSUE TITLE
Khorium Vein

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2589]
Description: Mining node in Outlands

How it works: Currently doesn't have a chance to drop Mote of Fire it seems

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Bzmode** [comment]
Should also only have 1 up in each zone at a time. way too common

**Comment by Dootz** [comment]
fixed & implemented
