### ISSUE TITLE
 [Winterfall Ritual Totem]

### ISSUE THREAD

**Issue by dgasen** [SunwellWoW/Sunwell-TBC-Bugtracker#2590]
Description: 

I am neutral with timbermaw faction. But i cant still interact with the npc.

How it works: 

NPC has yellow ?
But i cant interact with it.

How it should work: 

I should be able to interact with the npc when i am neutral with the faction.

Source (you should point out proofs of your report, please give us some source):

**Comment by dgasen** [comment]
also this quest.  [Deadwood Ritual Totem]

Somehow i cant interact as i should be able to. I am neutral!!

**Comment by ZaoQ** [comment]
Guys, go to rep tab of your character and mark/unmark at war

it was already posted here

**Comment by Dootz** [comment]
Hi, that's exactly what you need to do. Thank you @ZaoQ for helping others.
