### ISSUE TITLE
Scorchscale Drake

### ISSUE THREAD

**Issue by F0zeNN** [SunwellWoW/Sunwell-TBC-Bugtracker#2591]
Description: There is a bugged Scorchscale Drake (npc=23687) whos just sit on the ground

How it works: Hes flying on the ground and does not move

How it should work: He should fly and he should move

Source (you should point out proofs of your report, please give us some source): Forgot to screenshot but if you will look in dustswallow marsh there is. But its only there atm

**Comment by Dootz** [comment]
fixed & implemented
