### ISSUE TITLE
Hunter - Pets dont get their proper Spells

### ISSUE THREAD

**Issue by Butterfly1298** [SunwellWoW/Sunwell-TBC-Bugtracker#2593]
Description: 

Hey Hey, since last time I tried a higher leveled Beast to tame. Now I have my Brooken Tooth on lvl 37 tamed, BUT it only have Dash Rank 1 and also Bite Rank 2. Growl is trained by the Pettrainer. 

Level 37 is supposed to have Bite Rank 5:

https://www.telegamez.de/pet-guide-fuer-jaeger.html

I know this Site is on german, but it says:

"Biss Rang 5 (40-48 Schaden, Tier lvl 32"

Which means: Bite Rank 5 40-48 Dmg, Level of the Pet had to be 32 to get this rank.

Brooken Tooth was lvl 37 so he had to at least rank level 5. So there is a big Problem with this at all!
![wowscrnshot_120618_091224](https://user-images.githubusercontent.com/45596170/49570609-6a7e9c00-f937-11e8-942d-702b94c85628.jpg)
![wowscrnshot_120618_091228](https://user-images.githubusercontent.com/45596170/49570610-6a7e9c00-f937-11e8-998f-b59e0471d47f.jpg)

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
Not bugged. Broken Tooth only learns Dash Rank 1.
See:

http://web.archive.org/web/20070329054221/http://petopia.brashendeavors.net:80/html/mobs/mob_brokentooth.shtml

You can even see the german link you posted. At "Biss Rang 5" there is no Broken Tooth to be found.

**Comment by Butterfly1298** [comment]
Read your link on the right side:

"Learns: Bite, Claw, Cower, Dash, Growl, Prowl " My Brooken Tooth actually dont learn anything!

**Comment by ujellyx** [comment]
> Read your link on the right side:
> 
> "Learns: Bite, Claw, Cower, Dash, Growl, Prowl " My Brooken Tooth actually dont learn anything!

That just means, that you can teach him these kinds of abilities, since he's from the cat-family. Not that you learn them from him.

**Comment by Butterfly1298** [comment]
But I CANT teach him anything! Because I cant learn these spells by the pettrainer.

Or I have to tame like 40000 Mobs till I get all the ranks to give it to my Brooken Tooth? Sorry, never heard of that. Never ever.

**Comment by ujellyx** [comment]
> But I CANT teach him anything! Because I cant learn these spells by the pettrainer.
> 
> Or I have to tame like 40000 Mobs till I get all the ranks to give it to my Brooken Tooth? Sorry, never heard of that. Never ever.

Exactly. You have to tame the specific pets, that already have the specific abilities, use them a few times and then you can teach these spells to your other compatible pets. That's just how it works in Vanilla and TBC.

**Comment by Butterfly1298** [comment]
Gonna try it out.
