### ISSUE TITLE
Howl of Terror & Release Spirit

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#2594]
Description: Howl of Terror causes character to permanently dead, when already dead.

How it works: 
Die when Howl of Terror is affecting player (happened twice in Searing Gorge). Player releases spirit and is stuck dead on the ground with, "Release Spirit" button. If you click the button, nothing happens. You cannot move. If you re-log you will only get about 5 seconds of movement until you "die" again.

How it should work: You shouldn't be dead, when already dead.

Source (you should point out proofs of your report, please give us some source): 
![942cd89fe7133e5e828fc164c52caf96](https://user-images.githubusercontent.com/15868285/49570715-42b61680-f8ec-11e8-9ed6-2adb5f4ed71d.jpg)

**Comment by Azathothh** [comment]
It's not related to Howl of Terror but Lifestone - already reported to devs and soon will be fixed
