### ISSUE TITLE
Unkor NPC for quest Don't Kill the Fat One is not spawning at all

### ISSUE THREAD

**Issue by estenv** [SunwellWoW/Sunwell-TBC-Bugtracker#2595]
Description: 
Unkor (http://db.hellfire-tbc.com/?npc=18262) is not spawning at all. Quest NPC for http://db.hellfire-tbc.com/?quest=9889. Waited for 30mins and he never spawned.

How it works: 
Unkor never respawns (someone probably killed him).

How it should work: 
Unkor should respawn in 5mins like the other mobs around.

Source (you should point out proofs of your report, please give us some source): 
N/A

**Comment by estenv** [comment]
Okay after 30mins of waiting he came RUNNING from the north. He didnt respawn, he had been teleported somewhere and ran back.

This should still be investigated because I can only imagine something in the scripts caused him to be misplaced, and this is part of the main quest chain of nagrand so skipping it is not really an option (leads to 20+ quests)

**Comment by Zarant** [comment]
I've waited for over an 1 hour and nothing... He's just not there

**Comment by Zarant** [comment]
Okay, I think I found the culprit, just did it after a server restart, whenever he turns friendly he starts following whoever was at the top of his threat table. 
Which means that issue #1952 is not really fixed.

**Comment by 0vertime** [comment]
This is blocking the quest chain :\
