### ISSUE TITLE
Tanaris Mithril Vein

### ISSUE THREAD

**Issue by Krakers123** [SunwellWoW/Sunwell-TBC-Bugtracker#2597]
Description: 
Tanaris is missing mithril vein spawns.

How it works: 
There's shit ton of thorium but not a single mithril vein as far as i've noticed.

How it should work: 
There should be a lot of mithril in Tanaris.

Source (you should point out proofs of your report, please give us some source): 
https://tbc-twinhead.twinstar.cz/?object=2040

**Comment by Dootz** [comment]
Fixed & implemented, thank you for report.
