### ISSUE TITLE
Libram of Saints Departed

### ISSUE THREAD

**Issue by leylandpaladin** [SunwellWoW/Sunwell-TBC-Bugtracker#2598]
Description: 

Libram should heal u for 41 to 49 health when u use judegement

How it works: 

It's not healing at all

How it should work: 

It should heal for 41 to 49  when u use judgement

Source (you should point out proofs of your report, please give us some source): 

http://wowwiki.wikia.com/wiki/Libram_of_Saints_Departed

123

**Comment by jketring6** [comment]
I can confirm that it is still not healing as of 12/12/18
![wowscrnshot_121218_210548](https://user-images.githubusercontent.com/34728229/49917088-95468400-fe52-11e8-8382-eae08f64b935.jpg)

**Comment by marfiljamrockz** [comment]
still not healing as of 25/12/18
![wowscrnshot_122518_154153](https://user-images.githubusercontent.com/46138324/50426458-c912a800-085b-11e9-9d27-3df372942da2.jpg)
