### ISSUE TITLE
Blackrock Depths - Part 1: Lower City

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#260]
### **TO DO:**
- [x] 1. Some of Anvilrage Guardsmans (8891) should yell once pulled. It's time to time yell and not every of them do it:
"Anvilrage Guardsman yells: You can't hide from us. Prepare to burn!"
- [ ] 2. Those four npcs present or screen are pulling through closed doors. They should pull once the doors are opened. Creature guids: 45895, 45890, 91102, 47809.
Doors: 15380 - Supply Room Door
![image](https://user-images.githubusercontent.com/22802214/44820093-bb238200-abef-11e8-957b-f32afefdd384.png)
- [x] 3. What is Going On? (3982) quest doesn't work. There is no event where we have to protect Commander Gor'shak (9020). Riztazz rewritten this quest on Angrathar.
- [ ] 4. Looks like High Interrogator Gerstahn's (9018) Shadow Shield spell (22417) doesn't reflect shadow damange to melee attackers.
- [x] 5. Lord Roccor (9025) melee hits for app. 420-500 while he should 476-564.
**EDIT: Now he hits for ~950**
- [x] 6. Looks like Houndmaster Grebmar (9319) doesn't use his Bloodlust spell (21049). He should cast it on nearby Bloodhound time to time.
**EDIT: He casts it on himself instead of on hounds.**
- [ ] 7. Ok'thor the Breaker (9030) should keep staff in hands.
- [x] 8. Arena Spectators (8916) should become friendly after you complete the Ring of the Law event - when Arena Gate 03 (15295) opens/activates.
- [x] 9. Anvilrage Medic (8894) should use Power Word: Fortitude spell (13864) on himself and nearby friendly creatures.
**EDIT: Three issues:**
**- they use it only on themself**
**- they're refreshing it when they have buff already**
**- they should cast it also when out of combat**
- [x] 10. Twilight Emissary (8913) interrupts his own Blizzard spell channel.
- [x] 11. Fireguard Destroyer melee hits with 270-330 fire damage while he should for 474 - 564 fire damage.
**EDIT: Now he hits for around ~1k**
- [x] 12. Pyromancer Loregrain (9024) shouldn't summon new Scorching Totem (15038) when there is one active.
- [x] 13. Pyromancer Loregrain should more focus on castin Molten Blast spell (15095) and spread Flame Shock spell (15616) through party players.
**EDIT: He still casts Flame Shock spell only time to time while he should do it really often, actually if there is someone w/o FS debuff he should refresh it.**
- [x] 14. Those four Warbringer Constructs (id 8905; guids: 274125, 274097, 274023, 274197) should have perm Stoned aura (10255) and shouldn't never pull or react.
**EDIT: Without changes.**
![image](https://user-images.githubusercontent.com/22802214/45167135-cb8fba00-b1f8-11e8-9020-a67b62aea444.png)
- [ ] 15. Looks like Verek (9042) doesn't use his spells: Thrash (3391) and Curse of Blood (15042).
**EDIT: He tries to use curse of blood spell but seems like its not working ;p**
- [ ] 16. Fineous Darkvire's Devotion Aura (8258) should also be applied on Warbringer Constructs (8905). Or maybe he doesn't see them as allies? Well he should :P 
- [x] 17. Doomforge Craftsman (8897) should use his Rebuild spell (13951) on Warbringer Constructs if they have below 50% hp.
**EDIT: Still doesn't use it.**
- [x] 18. Spawn of Bael'Gar (9436) should start to attack players immediately after spawned.
- [x] 19. Spawn of Bael'Gar (9436) should disappear after 30 second when losing combat.
- [x] 20. There are 12x Relic Coffer Doors gobs in game. When all of them are opened/activated boss Watchman Doomgrip (9476) should be summoned in place on gps.
![image](https://user-images.githubusercontent.com/22802214/44825210-d307ff80-ac09-11e8-95d7-39d1cb0cbdca.png)
- [x] 21. When Watchman Doomgrip dies, gob Secret Door (43094) should open/activate.
**EDIT: It doesn't open.**
- [ ] 22. Secret Safe gob (43137) should be able to pick up by players who have The Heart of the Mountain (4123) quest. This gob should contain item The Heart of the Mountain (11309) and some rares.
- [x] 23. Kharan Mighthammer (9021) shouldn't offer quest Kharan's Tale (4342) if pre-quest Kharan Mighthammer (4341) quest isn't done.
### **DONE:**

- [x] 1. Shadowforge Gate object should be here which requires Shadowforge Key (11000) to open.
![image](https://user-images.githubusercontent.com/22802214/44820902-4eaa8200-abf3-11e8-9bad-aebc9b2f5b5a.png)
- [x] 2. Anvilrage Guardsman should use his Sunder Armor spell (30901) more often.
- [x] 3. Looks like Twilight's Hammer Torturer (8912) doesn't use his Wracking Pains spell (13619).
- [x] 4. Anvilrage Footman's (8892) Kick spell (29560) should be casted when his target is casting spell indeed.
- [x] 5. Looks like Ok'thor the Breaker doesn't use his spells: Arcane Bolt (15254), Arcane Explosion (15453) and Slow (13747).
- [x] 6. Looks like Twilight Emissary doesn't use his spells: Fury of Ragnaros (15288), Arcane Bolt (13748).
- [x] 7. Twilight Bodyguard (8914) shouldn't use Fury of Ragnaros spell (15288).
- [x] 8. Fireguard Destroyer (8911) shouldn't use Fireball spell.
- [x] 9. Looks like Bloodhound Mastiff (8922) doesn't use his Ravenous Claw spell (15608).
- [x] 10. A Crumpled Up Note (11446) item shouldn't be able to see in loot by horde players. This item should be able to drop only for alliance players who has done Abandoned Hope (4242) quest.
- [x] 11, Verek and Warder Stilgiss (9041) should be formation with linked threat.
- [x] 12. Fineous Darkvire (9056) seems to doing damage to himself somehow... combat log doesn't show it but his hp is decreasing when I do totally nothing.
- [x] 13. Fineous Darkvire should cast his Holy Light spell (15493) and Seal of Reckoning spell (15346) on his allies as well.
- [x] 14. Looks like Fineous Darkvire doesn't use his Holy Strike spell (13953).
- [x] 15. Fineous Darkvire's Kick spell (11978) should be casted when his target is casting spell indeed.
- [x] 16. Looks like Watchman Doomgrip doesn't use his two spells: Sunder Armor (11971) and Drink Healing Potion (15504).

**Comment by Kokaina** [comment]
List updated.
