### ISSUE TITLE
Seal of Blood self damage goes through immunity

### ISSUE THREAD

**Issue by NeonicSupersonic** [SunwellWoW/Sunwell-TBC-Bugtracker#2600]
Description: 
Seal of Blood self damage goes through immunity
How it works: 
Seal of Blood self damage goes through immunity
How it should work: 
Immunities should prevent any and all forms of damage. Divine shield in particular should make paladin flat out immune to everything but divine intervention instant death mechanic. I also believe this mechanic bug exsisted on ptr gruul (since his shatter counts/should count as self damage), cant proof for obvious reasons.
Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120618_130246](https://user-images.githubusercontent.com/45077198/49576909-58acf100-f957-11e8-8efe-f5b8e8666533.jpg)
log in left top corner

**Comment by roopeh** [comment]
Invalid. Seal of Blood self damage should actually go through Divine Shield.
"[Blessing of Sanctuary] will not mitigate backlash damage caused by this seal. Neither will  [Divine Shield] make you immune to this damage"
source https://wow.gamepedia.com/index.php?title=Seal_of_Blood&oldid=1607212
