### ISSUE TITLE
Holy Resistance

### ISSUE THREAD

**Issue by MVMnn** [SunwellWoW/Sunwell-TBC-Bugtracker#2601]
Description: 
Creatures will sometimes resist holy-dmg abilities like paladins retribution aura or consecration or holy seal dmg or priests smite.

How it works: 
Holy spells are partially resistable.

How it should work: 
There should not be partial resist its either resisted or deal full dmg.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Holy_resistance

**Comment by doomnyx** [comment]
https://youtu.be/ovhRqAxnXqg

Partial SoC due to level difference vs boss. Check on mobs of the same level as you.

**Comment by MVMnn** [comment]
Did you saw that i adressed soc? Nope, and i did expirienced partial resist with Green level mobs. 123

**Comment by MVMnn** [comment]
This issue is not about soc, cmon. Consecration for example or retri aura can be partially resisted which is NOT correct.

**Comment by akrom23** [comment]
Mobs can resist holy.
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2493#issuecomment-458520315
Send some pics.
