### ISSUE TITLE
Quest follow-up requirements

### ISSUE THREAD

**Issue by KimmoKM** [SunwellWoW/Sunwell-TBC-Bugtracker#2603]
In retail, follow-up quests were unconditionally available (e.g. level 28 player could have level 43 quest in Big Game Hunter). Right now, players are often locked out of follow-ups, having to backtrack, making it seem as though there's a lot of quests missing and making leveling a lot more annoying than it needs to be. Examples of these quests include Return to Sha'tari Base Camp (after Terokkantula) and Cannons of Rage (after Forge Camp: Mageddon), but since quest progression is generally kinda fucked (such as quest to kill normal Daggerfen mobs not becoming available until you've done WANTED: Chieftain Mummaki), you might want to do a systematic review of quest progression and level requirements, at least for Outland quests because that's where it's the most annoying.

In addition, I don't know what the reason is, but there's just not enough experience. Folks have had to resort to grinding despite 100%ing Outland zones. Not gonna make an additional report because I don't know where the trouble is exactly, but if you were to review quest progression, you might catch something related to this in the meanwhile.

**Comment by Dootz** [comment]
Ok thank you, we'll look into it.
