### ISSUE TITLE
Blood Red Key, Felwood

### ISSUE THREAD

**Issue by Elefant0n** [SunwellWoW/Sunwell-TBC-Bugtracker#2604]
Description:  [Rescue From Jaedenar] is broken, Quest from the Blood Red Key.

How it works: She gets stuck right before picking up her equipment!

How it should work: She picks up her equipment and then you escort her out.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120618_121709](https://user-images.githubusercontent.com/37458988/49581017-df120480-f950-11e8-92d3-57309a30e6e9.jpg)

**Comment by Dootz** [comment]
Fixed & implemented, thank you for report.
