### ISSUE TITLE
[Rogue] Vanish doesn't work while stealthed

### ISSUE THREAD

**Issue by Leiffis** [SunwellWoW/Sunwell-TBC-Bugtracker#2605]
Description: Vanish doesn't work while stealthed. This means you can't escape mobs that spot you in stealth and you can't "prevanish" in PvP.

How it works: Using vanish while stealthed doesn't give rogue the improved stealth effect from vanish ability that should last a moment.

How it should work: The improved stealth effect from vanish should apply even when rogue uses vanish in stealth stance.

Source (you should point out proofs of your report, please give us some source): tested it few times

**Comment by smlk87** [comment]
AGREE

**Comment by Foosiq** [comment]
To have some proofs, [video](https://youtu.be/oBZ9or2E3-Y?t=97) from AT, just watch those few seconds I prepared for you. You can clearly see that he can for example use his mount after using Vanish.

Or another [one](https://youtu.be/14sFYHIKpX0?t=382) from Retail where u can see (at 6min 26sec) from his scrolling combat text "Leaving Combat" after using vanish.

**Comment by smlk87** [comment]
hello can we talk in game or disco?


Στις Παρ, 7 Δεκ 2018 στις 3:29 μ.μ., ο/η Andrej Dzilský <
notifications@github.com> έγραψε:

**Comment by smlk87** [comment]
the vanish bug is Basic .
vanish is basic skill for rogues .and somethink new peped for me again .
last time when i vanish the bar didnt changed to stealth
it apprier the same

Στις Παρ, 7 Δεκ 2018 στις 4:51 μ.μ., ο/η Smlk Sm <smolikas1987@gmail.com>
έγραψε:
