### ISSUE TITLE
Frostbolt/cone of colt/frostnova

### ISSUE THREAD

**Issue by hyxgod** [SunwellWoW/Sunwell-TBC-Bugtracker#2607]
Description: 
The slow of spells sometimes doesnt get applied even tho the spell hits

How it works: 
sometimes targets resist the slow effekt but not the dmg effekt of; fbolt,coneofcold,frostnova etc.

How it should work: 
if the spell hits, it should be applied 100%

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
You are wrong. Slow effect can be resisted (e.g. target was immuned or got high resist to slow), but the damage will occur.
