### ISSUE TITLE
Mage blink.

### ISSUE THREAD

**Issue by hyxgod** [SunwellWoW/Sunwell-TBC-Bugtracker#2608]
Description: 
Blink gets stuck on ground clutter all the time

How it works: 
when you blink you get stuck in same place unless the ground is flat. i hope it gets fixed atleast in arenas. and when you example: Jump off blade's edge arena BRIDGE you should be able to blink back on bridge mid-air.
How it should work: 
You should blink away even tho its groundclutter and you should be able to jump & blink at same time instead of getting stuck

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
#1584 #898
