### ISSUE TITLE
fishing skill issue

### ISSUE THREAD

**Issue by wolfera88** [SunwellWoW/Sunwell-TBC-Bugtracker#2609]
Description: 
im at ~160 skill atm, fishing in BB and Desolace, but gaining no skill at all, or around 5 skill / hour max. i dont think this is normal.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Shadowkill22** [comment]
http://et.worldofwarcraft.wikia.com/wiki/Fishing
