### ISSUE TITLE
[Hunter] Pets keep breaking freezing traps

### ISSUE THREAD

**Issue by fishworld** [SunwellWoW/Sunwell-TBC-Bugtracker#2613]
Description: 

Targets that successfully are trapped by freezing traps constantly gets broken by your pet. Even though the pet is set on defensive/passive, it should stop attack a target that has been trapped by freezing trap and only attack when/if you command it to. You can come around this by making a macro and have the pet stop attacking when you place a trap, but it's not always convenient because sometimes you place a trap in advance and attack the enemy, when he/she later runs into the trap the pet breaks it.
 
How it works: 

If you trap an enemy using freezing trap and your pet is set to defensive/passive, it will attack it anyway. 

How it should work: 

The pet should automatically stop attack when an enemy is trapped by freezing trap. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Lunasoll** [comment]
I can confirm. Pets break freezing trap if not on passive. I am not sure if this is how it actually worked in TBC.

**Comment by fishworld** [comment]
I don't have the time to search for youtube videos but I am very certain it was so. Not that Netherwing (Atlantiss) reflects retail, but there it works as intended. I have also never seen this bug before on private servers.
