### ISSUE TITLE
[Warrior] Battle shout

### ISSUE THREAD

**Issue by swordyxtwo** [SunwellWoW/Sunwell-TBC-Bugtracker#2615]
Description: 
Multiple ranks of Battle shout can stack

How it works: 
I grouped up with a lower level warrior, and we could have 2 battle shouts active (different rank)

How it should work: 
The stronger buff should overwrite the weaker, and casting the weaker should have no effect

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Okey, moved to crits.
