### ISSUE TITLE
Rogue vanish/stealth combat bug

### ISSUE THREAD

**Issue by smlk87** [SunwellWoW/Sunwell-TBC-Bugtracker#2616]
Description: stealth problems out of combat + vanish 

How it works: out of comabt i CANT go in stealth + when i use vanish and i go out of combat then i have the same problem ,CAnt enter stealth.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Probably same thing as here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2602
Will be fixed soon.
