### ISSUE TITLE
Ground Totem unreliable

### ISSUE THREAD

**Issue by Arom** [SunwellWoW/Sunwell-TBC-Bugtracker#2617]
Description: 

Grounding totem seems unreliable, seems very random.

How it works: 

When your target is casting a spell on you, placing the Ground Totem before the cast is finished makes no difference, grounding totem is ignored.

How it should work: 

Grounding totem check should be performed when the cast is actually finished.

Source (you should point out proofs of your report, please give us some source):

**Comment by FrauHolle86** [comment]
jeah had the same feeling while leveling up to 60+ last few days.... grounding totem works better then before but is still unreliable. also next to the fact, that the totem does not work perfect, it feels like a lot of spells are not scripted as "spells which should go into grounding" --> its also a spell issue

**Comment by Aeded** [comment]
![wowscrnshot_120818_103942](https://user-images.githubusercontent.com/45561230/49686649-c8f27880-faf7-11e8-9421-f119fc14216d.jpg)
![wowscrnshot_120618_021122](https://user-images.githubusercontent.com/45561230/49686650-c98b0f00-faf7-11e8-83e4-6d6dbdf07104.jpg)

**Comment by akrom23** [comment]
#3022
