### ISSUE TITLE
[Core] Wounded mobs should move slightly slower

### ISSUE THREAD

**Issue by Zarant** [SunwellWoW/Sunwell-TBC-Bugtracker#2621]
Non-boss npcs are supposed to move slightly slower whenever they are below ~10% hp, this should apply to all npcs including elites and 5 man bosses.

Proof:

https://www.youtube.com/watch?v=3LE4VI5fJwE
At 7:30 you can see both mobs running at the same speed, later at 8:13 you can see both mobs again, one of them wounded running slightly slower

https://www.youtube.com/watch?v=3O_pNDc73MM
at 7:00 the mage is barely able to outrun the dragon, at 9:57 you can see that the player is easily able to outrun the npc

https://www.youtube.com/watch?v=NbHkXttoowE 8:17
https://www.youtube.com/watch?v=dXE_RR5XzE8 15:25

This next video you can observe the same behavior and you can notice that this mechanic kicks in when the npc gets to about 10% hp:
https://www.youtube.com/watch?v=fZTIdqj6B5c
12:22
13:22
15:51
17:43

This next clip is from joana's speed run:
https://www.youtube.com/watch?v=SwLjJH8LXfc 19:22

And here is a video from the first boss in SP heroic, notice he starts to slow down at the very end when he is about to die:
 https://www.youtube.com/watch?v=0i0u511mT_g

You can see additional research here: https://vanilla-twinhead.twinstar.cz/?issue=3854
There, someone tested this particular mechanic on retail wow and found out that mobs will move progressively slower as their hp go down:
15-10% hp = 70% move speed
10-5% hp = 60% move speed
5-0% hp = 50% move speed

**Comment by ZaoQ** [comment]
Very well done, sir
