### ISSUE TITLE
[Core] Elite mobs are moving way too fast

### ISSUE THREAD

**Issue by Zarant** [SunwellWoW/Sunwell-TBC-Bugtracker#2623]
Elite mobs shouldn't move faster than normal creatures.
Proof:
https://www.youtube.com/watch?v=ZzLs1Awfiyk - hunter is able to outrun uvuros without cheetah
https://www.youtube.com/watch?v=olHCy4QEc58 - teremus the devourer - kiting with cheetah
https://www.youtube.com/watch?v=UcuX2ap0B6E - kiting razorgore adds

However, massive units do move faster.
https://www.youtube.com/watch?v=ToTjoXbipoU - Anacrhonos moves fairly fast
https://www.youtube.com/watch?v=0xC8wqDmxgs - Fel reaver also moves faster than most mobs, on this clip a guy used an engineering gadget to seize control of the unit in question.

At the moment all elite mobs run faster than 130% speed.

**Comment by Zarant** [comment]
One more source: https://www.youtube.com/watch?v=xhh1bW-5QDo
This clip shows a hunter soloing the first boss in heroic durnhold, he can clearly outrun the boss with aspect of the cheetah

**Comment by Dootz** [comment]
fixed & implemented
