### ISSUE TITLE
Mobs disapearing to fast (skinning issue)

### ISSUE THREAD

**Issue by Aledati** [SunwellWoW/Sunwell-TBC-Bugtracker#2624]
Description: 
After mobs getting killed its corpes disapear way to fast, less than 1min.

How it works: 
After mobs getting killed its corpes disapear way to fast. If you pull two mobs and kill one by one, the first mobs you kill will dispear before you kill other one. This is issue for skinners. 

How it should work: 
Corpes should not disapear this fast, I believe it should stay minimum 3 mins or even more.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Correlated with dynamic respawn :( will be disabled soon.
