### ISSUE TITLE
Tar Lord & Tar Beast spam disarm

### ISSUE THREAD

**Issue by 0vertime** [SunwellWoW/Sunwell-TBC-Bugtracker#2628]
Currently both Tar Lord and Tar Beast spam their disarm spell Sticky Tar with no cooldown.

Tar Lord npc=6519
Tar Beast npc=6517
Sticky Tar spell=14178

It should have 10% chance to proc on their hit, not 100% cast spell with no cooldown.

**Comment by Tyton89** [comment]
Still, no fix 2 days later making this quest nearly impossible for any melee class.
