### ISSUE TITLE
Rogue bugs: Shadow step, throwing wep speed, distract 

### ISSUE THREAD

**Issue by adamdmorgan25** [SunwellWoW/Sunwell-TBC-Bugtracker#263]
Decription: 
Shadow step: Attempts to step through the shadows and reappear behind your enemy and increases movement speed by 70% for 3 seconds. The damage of your next ability is increased by 20% and the threat caused is reduced by 50%. lasts 10 seconds.
How it works: 
and so far on the PTR is seems to put you in a random direction.

How it should work: 
it should teleport you behind the target ~1 or 2 yrds behind them.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Seems to work fine.
@adamdmorgan25 Could you repeat you test?

**Comment by Wojtyas** [comment]
Fixed & implemented.
