### ISSUE TITLE
Transmute: Arcanite

### ISSUE THREAD

**Issue by Lollyshop** [SunwellWoW/Sunwell-TBC-Bugtracker#2632]
Description: 
When you transmute Arcanite you get a 23 hours cd

How it works: 

How it should work: 

There shouldnt be a CD for it in TBC
Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120618_203806](https://user-images.githubusercontent.com/45670657/49607787-4c488880-f997-11e8-97df-fbefb35943a4.jpg)

https://www.wowhead.com/spell=17187/transmute-arcanite#comments

**Comment by Wojtyas** [comment]
Removed cd came with 2.4 but we implemented patch changes so it will have cd till Sunwell Plateau content. Even 2nd comment in ur link says it has cd.
++
![image](https://user-images.githubusercontent.com/22802214/49609425-c8dd6600-f99b-11e8-9dd1-062e09b77c8c.png)

**Comment by Azathothh** [comment]
By marcusdds (2,373 –  11·29)  on 2007/06/06 (Patch 2.1.1)
As of 2.1, the cooldown is 23 hours.

Zarkath on 2008/03/25 (Patch 2.4.0)
To clarify this: With Patch 2.4 the cooldown will be removed completely.

Comments on wowhead - link that you've posted
