### ISSUE TITLE
Nature's Grace Consumed by Everything

### ISSUE THREAD

**Issue by fantom8** [SunwellWoW/Sunwell-TBC-Bugtracker#2633]
Description: 
The Druid talent Nature's Grace is consumed by instant cast spells and even sitting down to drink/eat.

How it works: 
The buff you get on crits that reduces the cast time of your next spell is removed when you use any spell, not just a spell with a cast time.

How it should work: 
The buff should be consumed when you finish casting a spell with a cast time, not when you use an instant cast spell or sit down to drink.

Source (you should point out proofs of your report, please give us some source): 
Crit on a spell in game on a character with the Nature's Grace talent and then use an instant cast or sit down to drink,

**Comment by Jseay1313** [comment]
they fixed this on the beta not entirely sure how this is broken again

**Comment by fantom8** [comment]
Even activating a trinket consumes Nature's Grace at the moment
