### ISSUE TITLE
[Mob] Guard Mol'dar 

### ISSUE THREAD

**Issue by Carneyy** [SunwellWoW/Sunwell-TBC-Bugtracker#2639]
Description: 
https://db.excalibur.ws/?npc=14326#drop
Checked 2 times, 0 boss loot drop after tests. Just key.

How it works: 
Drop just key without boss items.

How it should work: 
Drop loot table items. (https://db.excalibur.ws/?npc=14326#drop)

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/Ju9SrJW

**Comment by Dootz** [comment]
fixed & implemented
