### ISSUE TITLE
Rogue issues: Throwing wep/discract

### ISSUE THREAD

**Issue by adamdmorgan25** [SunwellWoW/Sunwell-TBC-Bugtracker#264]
Decription: 

Throws a distraction, attracting the attention of all nearby monsters for 10 seconds. Usable while stealthed.

How it works:  it generally works alright, but its supposed to also work in combat in pvp if im not mistaken

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
What was said above, shouldnt work in combat
