### ISSUE TITLE
[Mob] Carrion Swarmer - wrong loot table (skining)!

### ISSUE THREAD

**Issue by Carneyy** [SunwellWoW/Sunwell-TBC-Bugtracker#2640]
Description: 
Carrion Swarmer after skining supposed to drop eather Rugged Leather or Rugged Hide. 

How it works: 
What he drop is basic Light Leather, Ruined Leather Scraps, Light Hide!

How it should work: 
Should drop after skining Rugged Leather or Rugged Hide. 

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/L5IAAmq

**Comment by Dootz** [comment]
fixed & implemented
