### ISSUE TITLE
Aspect of The Pack not working for party members

### ISSUE THREAD

**Issue by panick69** [SunwellWoW/Sunwell-TBC-Bugtracker#2641]
Description: 
when in a party the aspect of the pack buff does not apply to party members within 30 yards

How it works:
when i apply the aspect i get the buff but no one else in my party gets it

How it should work:
if anyone is in a group or raid with me that is within 30yarcs of me should get the aspect of the pack buff

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120618_130352](https://user-images.githubusercontent.com/45672195/49611864-c78a4a00-f957-11e8-8582-7a1d270b9869.jpg)

**Comment by akrom23** [comment]
Looks good to me.
@panick69 The second player had any other buff modifying speed?

**Comment by sulowitch** [comment]
![wowscrnshot_121818_134037](https://user-images.githubusercontent.com/28542140/50155477-728df280-02cc-11e9-8854-1db98068f8ad.jpg)
you can see aspect icon on nameplates. it is working.

**Comment by Jonsbe** [comment]
Working as intended for me here aswell.

**Comment by babno** [comment]
@panick69 when your party member is a significantly lower level than you they may not get higher level aura effects just like you can't do high rank buffs on low levels. Working as intended.
