### ISSUE TITLE
[Warlock] Unending Breath stacking 

### ISSUE THREAD

**Issue by Vynora** [SunwellWoW/Sunwell-TBC-Bugtracker#2642]
Description: Unending breath stacking 

How it works: currently the warlock buff unending breath is stacking from different warlock
![capture](https://user-images.githubusercontent.com/45545782/49611801-fe398200-f9a2-11e8-80b2-bd686bb85d33.PNG)

How it should work: it should not stack

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Thanks, moved to stacking list.
