### ISSUE TITLE
Mining Nodes

### ISSUE THREAD

**Issue by MangosNight** [SunwellWoW/Sunwell-TBC-Bugtracker#2643]
Description: 
Mining Nodes spawn way too fast and they are everytime on the same spot

How it works: 
Mining nodes respawn timer is 6minutes and there is no randomize in it so they are all at the spots the spawned before. This is critycal for Outland since mats price will fall in the celler soon.

How it should work: 
Mining nodes should take way longer between 15min -30 time to respawn and they shouldnt be always at the same spots.

Source (you should point out proofs of your report, please give us some source): 
Basicly every Miner in Outland will tell you the same

**Comment by SunwellTracker** [comment]
_How it should work:
Mining nodes should take way longer between 15min -30 time to respawn and they shouldnt be always at the same spots._

Could you give us a source?

**Comment by Avishai97** [comment]
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/46743501 comments from 10 years ago suggest it can be from a few seconds to maybe an hour or more, right now its static 6 minute and always the same node, nothing random at all

**Comment by nimeral** [comment]
Mining nodes seem fine or overspawning, herbs seem underspawning. Someone in global reported having 15 herbalism and 225 mining. I see veins more often than herbs while tracking herbs.

**Comment by Avishai97** [comment]
https://gyazo.com/c12c4328767224f86c01932924e1d291
Primal Earth is already down this far on AH and there are 20x 70 online on alliance, you have 50+ primal earth before you ding 70 if you mine from 60-70 1x lvling speed

**Comment by Avishai97** [comment]
Can't blame goldsellers for ruining the economy when the economy is ruined by the server itself when it comes to mining spawns.
