### ISSUE TITLE
Quest - The Corpulent One

### ISSUE THREAD

**Issue by shamylee** [SunwellWoW/Sunwell-TBC-Bugtracker#2645]
How it works: The  Borelgore is 61 level in 53-60 level zone and he hits for about 500-600 normal damage with 30% armor reduction every second plus special attacks which is way too much. 

How it should work: The quest should be soloable by any class in the level zone range.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed & implemented
