### ISSUE TITLE
Skinning Lvl 55-56 Dredge Striker gives Light leather

### ISSUE THREAD

**Issue by 0vertime** [SunwellWoW/Sunwell-TBC-Bugtracker#2646]
How it works: 
Gives Light Leather & Ruined Leather Scraps.

How it should work: 
Should give Rugged Leather & Rugged Hide.

**Comment by Valmere** [comment]
ahahaahaha this a simple db fix all you gotta do is reload tables

hahaha how is it not "live" after 48 hours ahahahah

**Comment by Dootz** [comment]
fixed. Applied on live.
