### ISSUE TITLE
Thrown weapons cast instantly

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#265]
Decription: Throw 5-30 yd range 0.5 sec cast

How it works: It instantly throws with no wind up time

How it should work: you should have to remain stationary for .5 seconds until the throw occurs

Source (you should point out proofs of your report, please give us some source):

**Comment by notsofamous** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2538
