### ISSUE TITLE
Revantusk Village Inn - Hinterlands

### ISSUE THREAD

**Issue by shamylee** [SunwellWoW/Sunwell-TBC-Bugtracker#2650]
Description:Your character is not resting in the whole Revantusk Village Inn in the Hinterlands, only in the small part of it.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Already reported https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2618
