### ISSUE TITLE
Quest - Duskwing, Oh How I Hate Thee...

### ISSUE THREAD

**Issue by shamylee** [SunwellWoW/Sunwell-TBC-Bugtracker#2651]
How it works: Duskwing Bat NPC have 18.5k of hp instead of 5k-6k i think and hits for 500-600 normal damage with 30% armor reduction every second.

How it should work: The quest should be soloable by any class in the level range zone.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
