### ISSUE TITLE
What the Soul Sees

### ISSUE THREAD

**Issue by Mikju1** [SunwellWoW/Sunwell-TBC-Bugtracker#2656]
Description: Ancient Orc Ancestors not spawning

How it works:  There was only 1 Ancient Orc Ancestors in whole area and not spawning for long time

How it should work: Spot north side of Oshu'gun should be full of Ancient Orc Ancestors and respawn after they are killed for quest

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
