### ISSUE TITLE
Enraged Fire Spirit / Mote of Fire

### ISSUE THREAD

**Issue by Gamergamergamer1** [SunwellWoW/Sunwell-TBC-Bugtracker#2658]
Description: 
Enraged Fire Spirit npc=21061 drop way to less Mote of Fireitem=22574

How it works: 
Drop chance is around 8-9% way too low

How it should work: 
Drop chance should be 26%

Source (you should point out proofs of your report, please give us some source): 
https://tbc-twinhead.twinstar.cz/?npc=21061

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
