### ISSUE TITLE
Felwood Quest - Rescue From Jaedenar

### ISSUE THREAD

**Issue by Kamwi** [SunwellWoW/Sunwell-TBC-Bugtracker#2659]
Description: The NPC goes deeper into the cave and stops at a tent.

How it works: After you accept the quest the NPC runs deeper into the cave instead of running out like on other servers and she stops at a tent without any intent to move further.

How it should work: The NPC should move in the other direction and leave the cave and let the player get credit for the quest

Source (you should point out proofs of your report, please give us some source): I already left the cave so I wont be able to include any proof with that but I can give you a link to how it should look like https://www.youtube.com/watch?v=V3dId_-OLwU

**Comment by Dootz** [comment]
https://www.youtube.com/watch?v=QvCM_NdHnxg
http://wowwiki.wikia.com/wiki/Quest:Rescue_From_Jaedenar
_You escort Arko'narin down to the (first) room split with a slime-filled pool. When Arko'narin reaches the **pit circled with candles**, she notes that some dark ritual must be going on_

> > Kamwi wrote:
> 
> _After you accept the quest the NPC runs deeper into the cave instead of running out like on other servers and she stops at a tent without any intent to move further._

Seems like other servers implemented it the easy way. Works as expected.
