### ISSUE TITLE
[Item] Grimtotem Key

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#2660]
Description: 
The key can be dropped from the Grimtotems (in dustwallow) at all times

How it works: 
Description

How it should work: 

Should be lootable only during active q"Prisoners of the Grimtotem"
Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed & implemented. Thank you for report.
