### ISSUE TITLE
Blasted Lands- Bloodmages Drazial and Lynnore

### ISSUE THREAD

**Issue by RafricanzZ** [SunwellWoW/Sunwell-TBC-Bugtracker#2661]
Description: 
The quests that ive done can't be finished, because the NPC stays with gray ? icon, even with items in my bag.

Quests bugged:
Vulture's Vigor + A Boar's Vitality, cant' finish both.

How it works: 
Should turn the ? icon to yellow and accept the items dropped from the quest mobs at its targetted goal.
Vulture Gizzard: 10/10
Snickerfang Jowl: 2/2
(for Vulture's Vigor)

and the same for the other quest.

Source (you should point out proofs of your report, please give us some source): 

![proof](https://user-images.githubusercontent.com/45674210/49617775-d996d780-f9ad-11e8-86db-78daf316b748.png)

**Comment by Mikov1605** [comment]
It was a common bug, a blizz one, with quest items that can be looted w/o q(like scorpok pincer)
Just abandon and accept this q again

**Comment by Dootz** [comment]
Unfortunately that's true. It was reported already few times and we are looking into it. I'll close this report as there is one main issue for it right now.
