### ISSUE TITLE
Judgment +seal of crusader not working [no dmg]

### ISSUE THREAD

**Issue by Anzark** [SunwellWoW/Sunwell-TBC-Bugtracker#2662]
**Palading Judgment won't work with Seal of the Crusader**.
There is no damage, no resist, nothing.

It seems to work fine with Seal of the righteousness.

**Comment by 13last** [comment]
Seal of Crusader does not do damage just leaves a debuff that target takes more holy damage and I play a pally and checked, it works fine, can you elaborate what you mean?
