### ISSUE TITLE
[Loot]Group Loot

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#2663]
Description: 
I Just was on Uldaman. A shammy needed a rare cloth chest from a Boss (grimlok), on group Loot. He even had a better One, and Just took it for gold.

How it works: 
Description

How it should work: 

Its a suggestion, but make cloth for cloths only needable on group Loot. Same for other armor classes. Like on wrath. Prevent ninja looting, we cant trade the Item after its won, its binds when picked up
Source (you should point out proofs of your report, please give us some source):

**Comment by Mikov1605** [comment]
I talk about instance Loot only

**Comment by ZeuzzzZz** [comment]
no please.

**Comment by Jseay1313** [comment]
lol

**Comment by Mikov1605** [comment]
i bet Zeuzzz is one of those who need on everything just to sell it ;)

**Comment by doomnyx** [comment]
Dude, playing wotlk is different, default loot system when entering party is 'need before greed', you have such an option on tbc, but loot system is set to 'group loot' normally.

Do not try to make this place a custom server bcoz somebody rolls items in the way that you dont like.

**Comment by doomnyx** [comment]
Dude, playing wotlk is different, default loot system when entering party is 'need before greed' , you have such an option on tbc, but loot system is set to 'group loot' normally.

It is not a bug.

**Comment by Mikov1605** [comment]
You mean i should support ninja looting? ;)

**Comment by doomnyx** [comment]
Setup your own grps and force loot system u want, are u retarded?

**Comment by akrom23** [comment]
This is bugtracker.
