### ISSUE TITLE
[Warlock][Spell] Inferno

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#2667]
Description: 
There is quite a lot of things to fix, and modify considering Infernal and I will edit and add those things in the near future but for now...  First Inferno is useless because of a related bug with Enslave spell, so i would like to urge devs to look at that first. Second, the previous bug report considering Inferno says: ''Casting this spell should dismiss current minion automatically.'' and it is marked as fixed but it is not fixed, you still cant cast this spell if you have a summoned minion. Third, Inferno does not stun.

123

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
The hell.. it worked...
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1811

**Comment by akrom23** [comment]
#3905
