### ISSUE TITLE
[Warrior] [Spell] Execute

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#2668]
**Description:** 
Sometimes, when you hit execute the ability will not go off. It will although still proc the GCD, restricting you from casting a different spell instead

**How it works:** 
Cast execute on a mob after hitting a different ability, and the execute cast will not go off and the damage will not be done to the mob. The GCD from hitting the execute ability will still go off though. Execute fails to cast but casting the ability will still proc a GCD. This bug takes a lot of time to replicate

**How it should work:** 
Execute should cast every time, if the mob is under 20% hp and you have the available amount of rage to cast it

**Source (you should point out proofs of your report, please give us some source):**

**Comment by neheri** [comment]
I've also noticed that. If you use execute nothing happens beside GCD. There's no hit, no miss and as far as I remember no rage taken, it just fails.

**Comment by Heftyarms** [comment]
Bump. Was about to make a post then saw you posted it. It's as if the Execute ability just "Wiffs", it'll consume the rage but do no dmg and isn't tracked in combat log for ever being used.
