### ISSUE TITLE
[Quest] Oronu the Elder

### ISSUE THREAD

**Issue by Trolltilla** [SunwellWoW/Sunwell-TBC-Bugtracker#2670]
Description: 

Oronu the Elder doesn't drop the quest item orders from akama or at least it's not 100%

How it works: 

Oronu the Elder doesn't drop the quest item orders from akama or at least it's not 100%

How it should work: 

Should drop orders from akama every time

Source (you should point out proofs of your report, please give us some source):

**Comment by Swiplington** [comment]
Can confirm, just killed him.. no drop

**Comment by babno** [comment]
Confirming as well, still not dropping
