### ISSUE TITLE
[Hunter][Spell] Arcane shot rank 6

### ISSUE THREAD

**Issue by Zarant** [SunwellWoW/Sunwell-TBC-Bugtracker#2672]
https://i.imgur.com/N06k4cZ.png

As the tooltip reads, it should remove 1 magical effect from the target, right now only rank 7 and above are capable of dispelling magical effects.

**Comment by kinglobster** [comment]
this is weird, my rank6 dispels without any problems

**Comment by kinglobster** [comment]
this can be closed as everything is working as intended https://imgur.com/a/CMpx7PB
