### ISSUE TITLE
Recipe: Elixier of Major Agility Missing

### ISSUE THREAD

**Issue by Lollyshop** [SunwellWoW/Sunwell-TBC-Bugtracker#2673]
Description: 

The Recipe: Elixier of Major Agility is missing at the Thrallmar Quartermaster 
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Recipe:_Elixir_of_Major_Agility_(Horde)

**Comment by Wojtyas** [comment]
Added.
