### ISSUE TITLE
[Paladin][Spell] Seal of Justice

### ISSUE THREAD

**Issue by BonzoTiger** [SunwellWoW/Sunwell-TBC-Bugtracker#2674]
Description: 
Does not slow down after use Judgement.
How it works: 
Does not reduce the speed of movement

How it should work:
Reduce the speed of movement

**Comment by ZeuzzzZz** [comment]
good thing i didnt train this spell then

**Comment by babno** [comment]
To clarify it should set the maximum speed of the target to 100%, basically nullifying things like mount speed or sprint. They can suffer additional movement impairing effects to reduce their speed further. Do note when testing this isn't exactly a movement impairing effect as druids can't shift out of it, blessing of freedom and escape artist don't work, etc.

**Comment by akrom23** [comment]
Works fine to me. Tested on mob with speed buf and player on mount.
@BonzoTiger Needs more info.

**Comment by Atrecom** [comment]
Watch addon`s speed increased with 15% from ret talents.
Druid just ran away from me 2 mins ago .... test it in pvp
![1](https://user-images.githubusercontent.com/44858756/50054882-2e79e100-0158-11e9-83e4-5c5a867da2ac.jpg)

**Comment by Atrecom** [comment]
1

**Comment by Atrecom** [comment]
> Works fine to me. Tested on mob with speed buf and player on mount.
> @BonzoTiger Needs more info.

**Comment by leylandpaladin** [comment]
I'm here to make it clear, rank 1 not limiting movement speed, but rank 2 does. thats how it should work, so   ablitiy working fine.

**Comment by Atrecom** [comment]
why close? every1 want to fix low lvl questm but not a spell. not fair. #fix_for_twinks

**Comment by leylandpaladin** [comment]
@Atrecom Rank 1 not supposted to limit speed at all. Thats how it was on retail during tbc.

**Comment by Atrecom** [comment]
> @Atrecom Rank 1 not supposted to limit speed at all. Thats how it was on retail during tbc.

Why not? so description is wrong?
![1](https://user-images.githubusercontent.com/44858756/50173487-b56dbb80-0308-11e9-9b41-6836d51598bb.jpg)
![2](https://user-images.githubusercontent.com/44858756/50173515-c9192200-0308-11e9-958f-2fc28b47b4a2.jpg)
