### ISSUE TITLE
Bonus healing / spell damage items

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2676]
Description: Items duplicate spell dmg

How it works: 
https://gyazo.com/bb384254dcf572d9ea355a52bab095fe 76 spell damage
https://gyazo.com/f6b2b44a173daed5bbe393c7936890a9
https://gyazo.com/73567a33a42a6a8079fba8dc9faa7186

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Moved to prio topic.
