### ISSUE TITLE
Loot Box Empty?

### ISSUE THREAD

**Issue by Chipperduck** [SunwellWoW/Sunwell-TBC-Bugtracker#2678]
Description: I had a rogue open 2 Loot Boxes for me, and they were both completely empty.
I'm not entirely sure how that is possible, but when I right clicked them to open them, nothing. 

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/e1428c5b1b89f0a77708ef19f443c239

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2361
