### ISSUE TITLE
Guardians of the Altar[Quest] - not scripted

### ISSUE THREAD

**Issue by LezChap** [SunwellWoW/Sunwell-TBC-Bugtracker#2681]
Description: 
Escort mob in quest is not scripted.  http://db.darkwizard.pl/?quest=4901

How it works: 
Start quest, NPC doesn't move or do anything.

How it should work: 
NPC should path up and complete quest at the end.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3447
