### ISSUE TITLE
Gah'zilla questline bugged

### ISSUE THREAD

**Issue by Rasnia** [SunwellWoW/Sunwell-TBC-Bugtracker#2682]
Description:  Gah'zilla's questline

How it works:  Ringing the gong and wiping will clear Gah'zilla from his summon and not able to resummon him again

How it should work:  When Gah'zilla is summoned he should stay active untill killed

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Should be perm spawned on instance after its summoned.
