### ISSUE TITLE
Priest Renew not stacking.

### ISSUE THREAD

**Issue by CodyMueller** [SunwellWoW/Sunwell-TBC-Bugtracker#2685]
Description: Two Priests attempt to cast renew (same rank) on a friendly target/player. they rewrite eachother they are not stacking. I assume this could be an issue with ALL hots currently.

How it works: If multiple preists wanted to apply HoTs (in this case renew) to a target/player only 1 of them show up. Multiple hots of the same type are not stacking. Only 1 renew heals the target.

How it should work: If multiple priests wanted to apply multiple renews to a tank or friendly target they would all apply successfully and all 5 would heal the target.

Source (you should point out proofs of your report, please give us some source): Just get two priests together and try to get them to renew eachother.

**Comment by Wojtyas** [comment]
Yep, we are familiar with that. Will be implemented probably tommorow.
