### ISSUE TITLE
hunters mark does not show rogues in stealth

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#2686]
Description: 
hunters mark does not show rogues in stealth

How it works: 
hunters mark does not show rogues in stealth

How it should work: 
hunters mark should show rogues in stealth

Source (you should point out proofs of your report, please give us some source): 
No pics because when rogue stealthes u cannot see them XD

**Comment by Valesisback** [comment]
Lmao, it doesn't matter stealth is so bug you can see them without hunter's mark. Don't complain.

**Comment by baade123** [comment]
This isnt a forum post where ppl QQ you dummy, its a bug tracker for
REPORTING BUGS so they can GET FIXED lol plz be constructive.

**Comment by Butterfly1298** [comment]
I have the same Problem. I dont see Rogues in Stealth.

**Comment by akrom23** [comment]
![wowscrnshot_011919_170626](https://user-images.githubusercontent.com/1035215/51429235-0117cb80-1c0d-11e9-89c9-e7578d2c71d3.jpg)

Works fine.
Vanish removes it.
