### ISSUE TITLE
[paladin] two-handed weapon specialization 123

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#2687]
Description: The paladin talent two-handed weapon specialization increases damage by 2% per point when weilding a 2h.

How it works: It applies to 1 handers as well as 2 handers.

How it should work: Only work when using a 2h.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Everything works fine here.
