### ISSUE TITLE
Fear all kinds

### ISSUE THREAD

**Issue by Raikaa** [SunwellWoW/Sunwell-TBC-Bugtracker#2689]
Description: 

Damage don't cancel the effect but should
How it works: 
Damage don't cancel the effect but should

How it should work: 

effect should be cancel after damage
Source (you should point out proofs of your report, please give us some source):

**Comment by doomnyx** [comment]
http://wowwiki.wikia.com/wiki/Fear_effect?oldid=1550231

It only has a chance of cancelling on damage and on heartbeat, and there is a damage treshhold that definitely should.

Leveling warlock myself I would say it works correctly, minion attacks were able to cancel fear normally.

**Comment by Wojtyas** [comment]
Moved to https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2424
