### ISSUE TITLE
Bring Me Another Shrubbery!

### ISSUE THREAD

**Issue by Adrestiah** [SunwellWoW/Sunwell-TBC-Bugtracker#2691]
Description: Bring Me Another Shrubbery! (Quest 9714) is currently nearly impossible to do

How it works: The quest item item 24246/sanguine hibiscus only has 1 spawn point in underbog. 

How it should work: The quest item should have 13 locations.

Source (you should point out proofs of your report, please give us some source):  here's the wow head for the item. There is a comment that shows the spawn locations https://www.wowhead.com/item=24246/sanguine-hibiscus#comments

**Comment by zapsuu** [comment]
Only 1 spot for Sanguine. On the way to first boss should be around 6-7 Hibiscus.
