### ISSUE TITLE
Roots

### ISSUE THREAD

**Issue by Raikaa** [SunwellWoW/Sunwell-TBC-Bugtracker#2692]
Description: 

Damage don't cancel the effect but should
How it works: 
Damage don't cancel the effect but should

How it should work: 
Damage should cancel the effect

Source (you should point out proofs of your report, please give us some source):

**Comment by Jseay1313** [comment]
I've had direct damage and dot ticks break my root (druid) multiple times

**Comment by Wojtyas** [comment]
Tried to reproduce but dmg actually break my roots. Any video/proofs?

**Comment by username-is-not-taken** [comment]
It does indeed seem like it does not break as easily as it should. 

![roots](https://user-images.githubusercontent.com/45629295/50347881-74a7b980-0537-11e9-98d2-563e669546ad.png)

**Comment by akrom23** [comment]
Fix
