### ISSUE TITLE
Vanish

### ISSUE THREAD

**Issue by Raikaa** [SunwellWoW/Sunwell-TBC-Bugtracker#2693]
Description: 

When u vanish in combat you can't go in stealth again without combat
How it works: 
When u vanish in combat you can't go in stealth again without combat

How it should work: 

Vanish should cancel combat and give a change to go in stealth if not in combat
Source (you should point out proofs of your report, please give us some source):

**Comment by FooSoSe** [comment]
To have some proofs, [video](https://youtu.be/oBZ9or2E3-Y?t=97) from AT, just watch those few seconds I prepared for you. You can clearly see that he can for example use his mount after using Vanish.

Or another [one](https://youtu.be/14sFYHIKpX0?t=382) from Retail where u can see from his scrolling combat text "Leaving Combat" after using vanish.

**Comment by Foosiq** [comment]
Duplicate of https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2605, you should check if someone didn't reported it first.
