### ISSUE TITLE
Pets vs invisible enemy

### ISSUE THREAD

**Issue by Raikaa** [SunwellWoW/Sunwell-TBC-Bugtracker#2694]
Description: 

Pets follow invisible enemy showing his location, they should cancel autoatack and back to follow owner commands.
How it works: 
Pets follow invisible enemy showing his location, they should cancel autoatack and back to follow owner commands.

How it should work: 
Pets should back to owner commands when enemy went to stealth

Source (you should point out proofs of your report, please give us some source): 

SuddenDeath*
This was the case for most of TBC but changed in 2.4.3, undocumented.
http://www.arenajunkies.com/topic/29167-hidden-pet-nerf/
http://www.arenajunkies.com/topic/29172-hidden-hunter-nerfbug-fix-in-243/
Those threads created day after release of patch 2.4.3, yet nothing about it in the 2.4.3 patch notes.
Many changes like these were undocumented.
Conclusion: Pets should NOT chase targets that enter stealth.

**Comment by sadfx** [comment]
No source --> High Priority OMEGALUL

**Comment by akrom23** [comment]
Cannot reproduce it.
