### ISSUE TITLE
[Mob] Frenzied Pterrordax, Un'goro Crater

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#2697]
Description: 
This mob makes 6 or 7 attacks during one second

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Penthax** [comment]
Reported already.

**Comment by ZaoQ** [comment]
oh, didnt see

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2556
