### ISSUE TITLE
Mob spawning in Quests

### ISSUE THREAD

**Issue by Draknosh** [SunwellWoW/Sunwell-TBC-Bugtracker#2698]
Description: 
There are certain Quests that you are supposed to spawn mobs yourself. 

How it works: 
Those quests doesn't seem to despawn from the last player.
It ends up being 10 on the same mob standing on each other and the quest is pretty much undoable.

How it should work: 
The mobs should despawn after a while so the next player can do it if the first player left any mobs.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, could you give us an example of such quest?

**Comment by Dootz** [comment]
close due to no reaction
