### ISSUE TITLE
Druid: Balance: Nature's Grace

### ISSUE THREAD

**Issue by Unfairy** [SunwellWoW/Sunwell-TBC-Bugtracker#27]
Decription: 
Nature's Grace buff / icon not disappearing after spell cast

How it works: 
After you spell crit, you get the buff that decrease your spell cast for 0.5 sec. After your spell HIT the target, buff with icon will disappear. It allows to cast you 2 wrath with reduced spell casting time which isnt supposed to be. If it's just icon problem - that's still confusing people and not supposed to be.

How it should work: 
After you spell crit, you get the buff that decrease your spell cast for 0.5 sec. After your spell CAST that buff with icon will disappear.

Source (you should point out proofs of your report, please give us some source): 
In game test.

**Comment by akrom23** [comment]
Won't be fixed now. Proc system triggers only when you hit target.
