### ISSUE TITLE
Mote droprates in Elemental Plateau is extremely low

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#2702]
Description: 

How it works: 
It seems to have a droprate between 15-20%

How it should work: 
They should have a droprate of 35%, check link below source.

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?npc=22311

**Comment by Fuzedknight** [comment]
Isn't this a private server DB? It could be wrong on their server

**Comment by doomnyx** [comment]
https://www.wowhead.com/npc=22311/raging-fire-soul#comments:id=325550
