### ISSUE TITLE
[Druid] Improved Leader of the Pack

### ISSUE THREAD

**Issue by tuerpisch** [SunwellWoW/Sunwell-TBC-Bugtracker#2703]
How it works: the talent doesn't work, has no effect at all

How it should work: Your Leader of the Pack ability also causes affected targets to have a 100% chance to heal themselves for 4% of their total health when they critically hit with a melee or ranged attack. The healing effect cannot occur more than once every 6 sec.

Source (you should point out proofs of your report, please give us some source): https://tbc-twinhead.twinstar.cz/?spell=34300

edit: ally ne

**Comment by notsofamous** [comment]
Works fine for me

![Image](https://i.gyazo.com/9ca8e3b59fd2948892fdeb47e328421b.png)

**Comment by tuerpisch** [comment]
I dont use this addon, but i can't find any heal of improved leader of the pack in my combat log!?

**Comment by Jseay1313** [comment]
Works fine for me as well, procs constantly.
