### ISSUE TITLE
[Druid] Breathing in Cat Form

### ISSUE THREAD

**Issue by tuerpisch** [SunwellWoW/Sunwell-TBC-Bugtracker#2704]
Description: druids have to jump out of the water when being in cat to refill their oxygen

How it works: your breath/oxygen doesn't refill when you are (or are swimming) on the surface. it works when you switch form back to normal. but shape shifting is bugged

How it should work: when you get to the surface or swim, you should refill automatically.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Works fine.
