### ISSUE TITLE
Scarlet Monastery Armory: Herod

### ISSUE THREAD

**Issue by tuerpisch** [SunwellWoW/Sunwell-TBC-Bugtracker#2705]
Description: When fighting him, right after the start 10-20 mobs getting pulled from everywhere, they spawn right in the beginning

How it works: the spawn too early

How it should work: they should spawn after he is dead

Source (you should point out proofs of your report, please give us some source): https://wow.gamepedia.com/Herod

**Comment by Dootz** [comment]
Are you sure there were https://www.wowhead.com/npc=6575/scarlet-trainee and not regular crusaders? 4 crusaders are spawned behind Herod's door where conbat starts. Maybe someone from your group pulled this group. Scarlet Trainees should spawn only after Herod was killed.

**Comment by Dootz** [comment]
nevertheless i've added something to prevent them from spawning while herod is alive

**Comment by tuerpisch** [comment]
hey, thanks for your fix
we made a ticket and a gm helped us on this run to finish the boss
maybe he also could confirm this (Adrestia was his name)

**Comment by waterloorick** [comment]
This happened to us and they are 5 Scarlet Crusaders. Mage kited.

**Comment by Dootz** [comment]
should be fixed on live now.
