### ISSUE TITLE
Hellfire - Zeth Gor

### ISSUE THREAD

**Issue by Penthax** [SunwellWoW/Sunwell-TBC-Bugtracker#2706]
Description: 
- Orc Cast  "Fear" is not a Debuff. Its an Buff and you are able to click it off.

How it works: 

- Orc Cast  "Fear" is not a Debuff

How it should work: 

Fear is always a Debuff and you cant click it off.

**Comment by Dootz** [comment]
Fixed & implemented, thank you for report.
