### ISSUE TITLE
Twilight of the Dawn Runner

### ISSUE THREAD

**Issue by fabybaith** [SunwellWoW/Sunwell-TBC-Bugtracker#2707]
Description: The Dawn Runner Cargo that you're suppose to loot won't let us loot the item.

How it works: You click the box and get no item.

How it should work: You should get item after clicking the box after the cast time is done.

Source (you should point out proofs of your report, please give us some source): 
![qqqqqqqq](https://user-images.githubusercontent.com/45683846/49639824-d5c08080-f9c0-11e8-85e1-44b9d039ea8c.PNG)

**Comment by neheri** [comment]
Would also be nice to increase spawn rate because at the moment there are always 5+ people waiting to loot it.

**Comment by Dootz** [comment]
Fixed & implemented, thank you for report.
