### ISSUE TITLE
Demons of Arklon Ruins in Netherstorm

### ISSUE THREAD

**Issue by Ragemaniacc** [SunwellWoW/Sunwell-TBC-Bugtracker#2710]
Description: The demons in Arklon Ruins never drop Mote of Shadows(I've killed around 150 of npc:s in question).

How it works: Mote of Shadows never drop.

How it should work: Drop rate should be around 24% according to https://tbc-twinhead.twinstar.cz/?npc=19853

Source (you should point out proofs of your report, please give us some source): https://tbc-twinhead.twinstar.cz/?npc=19853

**Comment by Dootz** [comment]
Fixed & implemented, thank you for report.
