### ISSUE TITLE
Thorium settings

### ISSUE THREAD

**Issue by Kamil-Radzyminski** [SunwellWoW/Sunwell-TBC-Bugtracker#2712]
Description: Thorium setting skill/recipe is bugged. It's taking 3 bars for each setting, like it shouldn't. Is clearly wrote that it needs 1 bar for 1 setting. 

How it works:  it's taking 3 thorium bars for 1 setting made 

How it should work:  1 thorium = 1 setting, like in recipe reagents

Source (you should point out proofs of your report, please give us some source):  No more gold for making 1 settings for 3 thorium and record...

**Comment by Kamil-Radzyminski** [comment]
Like u can see everywhere is said that needs 1 bar for each:   https://tbc-twinhead.twinstar.cz/?item=21752#created-by

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2519

**Comment by Reykjavikshore** [comment]
still bugged i cannot create this even i have mats for it

**Comment by Wojtyas** [comment]
@Reykjavikshore did u read my comment here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2519 ?
