### ISSUE TITLE
[Paladin] [Improved Righteous Fury]

### ISSUE THREAD

**Issue by bindles1** [SunwellWoW/Sunwell-TBC-Bugtracker#2714]
Description: 
Paladin protection talent row 3 col 2
Reduce all dmg taken by 6%

How it works: 
Doesnt reduce any dmg

How it should work: 
Should reduce all imcomming dmg by 6%?

Source (you should point out proofs of your report, please give us some source):

**Comment by Bzmode** [comment]
yuge bug hopefully fixed before kara

**Comment by akrom23** [comment]
Tested against paladin:
- without talent:
![wowscrnshot_122818_203359](https://user-images.githubusercontent.com/1035215/50526137-549c6b00-0ae0-11e9-8c92-566101da97e9.jpg)


- with talent:
![wowscrnshot_122818_203036](https://user-images.githubusercontent.com/1035215/50526140-59f9b580-0ae0-11e9-974c-e2aef6e677c5.jpg)


Seems to work.
