### ISSUE TITLE
[Q] [SMV] The Art of Fel Reaver Maintenance broken

### ISSUE THREAD

**Issue by NoCandy** [SunwellWoW/Sunwell-TBC-Bugtracker#2715]
Description: The Art of Fel Reaver Maintenance quest can be completed since server doesn't spawn doctors strongbox also its completly devoid of mobs.

How it works:  Doctors strongbox is missing. Devoid of mobs except doctor.

How it should work: Doctors strongbox should spawn also the area should be stacked with infernals.

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=xZdgCqt6a8w

**Comment by Dootz** [comment]
Chest can be found at 39.4 19.5 if you are using some kind of map addon. If you don't it's on the right side next to laboratory table. I'll move doctor there too to make it easier to locate
