### ISSUE TITLE
Crafting Thorium settings bug 

### ISSUE THREAD

**Issue by Reykjavikshore** [SunwellWoW/Sunwell-TBC-Bugtracker#2716]
How it works: 
i cannot create thorium setings from jc its a red title item not ready yet
i try to increase jc and after some creating items character stop and now i cannot do it one more time, i make relog reload and delete cashe

How it should work: 
i should make it i need it to hit 300 jc
![wowscrnshot_120718_125550](https://user-images.githubusercontent.com/44321901/49649003-ba389280-fa1f-11e8-87e4-534f0c272121.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2519

**Comment by Reykjavikshore** [comment]
123
