### ISSUE TITLE
Shy-Rotam quest bug

### ISSUE THREAD

**Issue by Madeska1** [SunwellWoW/Sunwell-TBC-Bugtracker#2717]
Description: We cant valid Shy rotam quest

How it works: Doesnt work

How it should work: Valid quest

Source (you should point out proofs of your report, please give us some source): I am doing this quest

**Comment by Wojtyas** [comment]
Moved to https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2460
