### ISSUE TITLE
Shoot animation

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#272]
There is no bullet/arrow (maybe wand as well - havent checked) animation when creatures are shooting with normal ranged attack at all.
Ranged special abilities have their animations and they are pretty nice visible but when creatures are shooting with clear auto-attack the only way to realize it is changelog and decreasing hp.

**Comment by lukaasm** [comment]
> @Riztazz 
> ok mam
> tzn 'mam'
> https://wowdev.wiki/DB/SpellVisualKit
> 18     m_charProc    Integer[4]   Known value "17" reference to item_entry in column 26, example spell - 58493(mohawk grenade), point to item 43486 (Mohawk Mask)
> to gdzies jest ale nie wiem czy stricte w dc
> dbc
> to jest wlasnie na pewno ammo
> ammo oraz missile data w razie czego

**Comment by Riztazz** [comment]
22:03 <%Shauren> Killerwife: alright short summary

22:04 < Killerwife> *grabs popcorn

22:05 <%Shauren> if (spellVisual->MissileModel == -4 || spellVisual->MissileModel == -5) { use ONLY ammo provided in packet }

22:05 < Killerwife> thats some sick named idb

22:05 <%Shauren> if (anything else && no model specified) { fallback to ammo provided in packet }

22:06 <%Shauren> MissileModel -1 to -3 tries to grab it from casters equipped weapon

22:06 <%Shauren> anything else in that column refers to SpellVisualEffectName.dbc

22:07 <%Shauren> if still no model is loaded -> use "Spells\ErrorCube.mdx"

22:08 < Killerwife> yeah we found the errorcube thingy

22:08 < Killerwife> yeah we found the errorcube thingy

22:08 < Killerwife> one thing to clarify

22:08 < Killerwife>  if (anything else && no model specified), by anything else you mean what

22:08 < Killerwife> and which model specified

22:08 <%Shauren> anything else means literally any other missile model source

22:10 <%Shauren> fyi, spell 29436 has SpellVisual id 8846

22:10 <%Shauren> and that in turn has MissileModel = -5

22:10 < Killerwife> yes, it has -5

22:10 < Killerwife> i just checked it

22:10 < Chipzz> Shauren: but uhm, any idea why TC has more types than upstream WoW? seems kinda strange. Did you add your own stuff or did blizzard just remove things?

22:10 <%Shauren> oh and also HasMissile must be 1 ofc

22:11 <%Shauren> aaaaaand another stupid thing, you will need to have some logic for displayid selection

22:11 <%Shauren> sometimes its just a custom display unrelated to whatever weapon is equipped and its not found in any dbc

22:12 <%Shauren> db table or hardcode it
