### ISSUE TITLE
[NPC] Centipaar Stinger double attack

### ISSUE THREAD

**Issue by rychersky** [SunwellWoW/Sunwell-TBC-Bugtracker#2721]
![wowscrnshot_120718_075708](https://user-images.githubusercontent.com/45608488/49654744-e808e180-f9f5-11e8-911e-c82298cc81b5.jpg)

Description: Centipaar Stingers in Tanaris seem to be doing 2 attacks every auto attack. Not sure if this is intended or not but it makes them much, much more dangerous at their level.

**Comment by Wojtyas** [comment]
Probably Thrash spell http://db.hellfire-tbc.com/?npc=5456#abilities
