### ISSUE TITLE
Paladin quests doesnt reward any XP

### ISSUE THREAD

**Issue by nessum** [SunwellWoW/Sunwell-TBC-Bugtracker#2725]
Description: 
Just from own experience ,Paladin quests gives no experiance. Saw that #1471 and #2296 has the same issue, just that #2296 is shaman (or maybe all)

How it works: 
https://classicdb.ch/?quest=1654 "The Test of Righteousness" quest for example. I recieved no XP from it, but i still got the items so i got that going on form me!

How it should work: 
Checking https://classicdb.ch/?quest=1654 it gives "260 xp" But since this is not the only report about this i assume all classquests have the same problem

Source (you should point out proofs of your report, please give us some source): 
Didnt take any printscreens, i will update the ticket next time i do a classquest with a printscreen

**Comment by Wojtyas** [comment]
Related to: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2296
