### ISSUE TITLE
Scarlet Monastery Armory Herod bug

### ISSUE THREAD

**Issue by Klynxd** [SunwellWoW/Sunwell-TBC-Bugtracker#2726]
Description: 
He spawns 4 elites when the encounter starts.

How it works: 
4 Elites spawn when the encounter starts.

How it should work: 
After Herod is killed x amount of non elites should spawn

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
>  Herod when Herod is aggroed 4 Scarlet Champions should spawn outside his room near Herod's Door (this was added to prevent players from pulling him outside his room),

**Comment by mjk6994** [comment]
Yes outside. Not inside that you must fight WHILE fighting Herod. @Dootz
