### ISSUE TITLE
Quest: Cuergo's Gold

### ISSUE THREAD

**Issue by Bakster15** [SunwellWoW/Sunwell-TBC-Bugtracker#2729]
Description: 
The quest doesn't give ANY Experience. And the chest is filled with trash. But that might be intended,

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Jseay1313** [comment]
https://www.wowhead.com/quest=2882/cuergos-gold this quest has never given exp 


 2007/05/04 (Patch 2.0.12)The  Inconspicious Landmark is located at 53.1 , 95.9 and you right click on  it to 'summon' 5 pirates. Move out of the way as they run towards the  mark and a box will appear, you need a key to open this box and they  drop off one of the pirates.After running to the landmark, they  will run back to a certain location, there you can draw the mobs 3 at a  time or 2 at a time depending on your luck. This quest doesn't give any  exp. | By Kaena (1,426 –  1·21)  on 2007/05/04 (Patch 2.0.12) |   |  
-- | -- | -- | -- | --
By Kaena (1,426 –  1·21)  on 2007/05/04 (Patch 2.0.12) |   |
