### ISSUE TITLE
No loot in mobs (Netherstorm dungs, possibly others)

### ISSUE THREAD

**Issue by angton** [SunwellWoW/Sunwell-TBC-Bugtracker#273]
Decription: Very few mobs and bosses (~2 mobs per full instance clear) could be looted.

How it works: An extremely small amount of mobs could be looted in Mechanaar. At most 3 mobs per full instance clear. The unlootable mobs doesn't give the option to click for loot (the bag icon on cursor). This behaviour was also present in Arcatraz and Botanica. Did not test more dungeons yet, but could also be present in others.

How it should work: Pretty much every mob should drop something.

Source (you should point out proofs of your report, please give us some source): Pretty sure a majority of mobs should drop money/random stuff. Not sure I need to drop source for this.

**Comment by Kokaina** [comment]
Fixed.
