### ISSUE TITLE
stunresist doesnt work

### ISSUE THREAD

**Issue by antikiller69** [SunwellWoW/Sunwell-TBC-Bugtracker#2730]
Description: orc racial and warrior racial stun resist doesnt seem to work, close to 50 lvl and resisted 0 stun

How it works: resist stun

How it should work: resist stun

Source (you should point out proofs of your report, please give us some source):

**Comment by Jseay1313** [comment]
should probably show some evidence of this, I've seen quite a few resists opening with pounce against orcs and players in general in pvp

**Comment by Wojtyas** [comment]
Yei, some proofs pal?

**Comment by mjk6994** [comment]
What's he gonna do, post a screenshot of every stun not resisted? lmao

**Comment by akrom23** [comment]
No response. Closed.
