### ISSUE TITLE
Hunter pet death and happiness

### ISSUE THREAD

**Issue by 4yk4u** [SunwellWoW/Sunwell-TBC-Bugtracker#2733]
Description: 
If my pet dies and the corpse disappears it counts as a second death making it unhappy 75% dmg.

How it works: 

How it should work: 
It usually has to lose some happiness on death but not if the corpse disappears.

Source (you should point out proofs of your report, please give us some source):

**Comment by TheRealestMcCoy** [comment]
I have noticed this as well. If it dies it loses 1 level of happiness. I have tried to rez it but it would disappear so i would have to resummon it with only 1 level of happiness. 

if i can rez before desapwn it ill still be at level 2 happiness

**Comment by mintnb** [comment]
Seems it is still broken.
