### ISSUE TITLE
Timbermaw Hold reputation rewards

### ISSUE THREAD

**Issue by 0vertime** [SunwellWoW/Sunwell-TBC-Bugtracker#2741]
Description: 
https://i.imgur.com/eY0m4Fb.png

How it works: 
Furbolg Medicine Pouch & Furbolg Medicine Totem do not require Honored reputation currently.

How it should work: 
Furbolg Medicine Pouch & Furbolg Medicine Totem should require Honored reputation to purchase.

Source (you should point out proofs of your report, please give us some source): 
https://i.imgur.com/Evec7TK.png

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
