### ISSUE TITLE
Ferocious Bite not working properly.

### ISSUE THREAD

**Issue by Swiplington** [SunwellWoW/Sunwell-TBC-Bugtracker#2744]
Description: 
Ferocious bite has 2 issues that arent working properly

How it works: 
When using Ferocious Bite it should add all extra energy above 35 (the base cost of the spell) as extra damage, It never does this and just consumes 35 energy without any extra damage.

Second problem is when Ferocious Bite misses, gets dodged/parried/blocked etc. It should refund the energy cost but this never happens.

How it should work: 

Bite should add all energy above the base cost as extra damage, and it should refund all 35 energy when it doesn't succesfully land.

Source (you should point out proofs of your report, please give us some source): 

level 65 druid, noticed it since i first got the ability around level 17

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2489
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2472
One is already solved but not live yet.
