### ISSUE TITLE
Druid combo builders refund too much energy on miss.

### ISSUE THREAD

**Issue by Swiplington** [SunwellWoW/Sunwell-TBC-Bugtracker#2745]
Description: 
Druid combo builders refund too much energy

How it works: 
When Mangle/Claw/Rake doesn't succesfully land it refunds its base cost (which is normal) but then adds another refund.

How it should work: 
The refund should be 1x not 2x

Source (you should point out proofs of your report, please give us some source): 
level 65 druid

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2472
