### ISSUE TITLE
Stealth Distance

### ISSUE THREAD

**Issue by Pieze87** [SunwellWoW/Sunwell-TBC-Bugtracker#2747]
Description: 
Stealth is being seen through 10 + feet away from the mob. It should not be able to detect stealth that far from it.  As well as stealth bugging after vanishes. If you vanish your stealth will bug out and not work.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
No info about levels, mob, stealth rank. Closed.

**Comment by Pieze87** [comment]
Lol, only over a month since the ticket was submitted with no follow up at
all. Well done. No wonder people are leaving your server.

**Comment by akrom23** [comment]
So you just could give needed info and then maybe I will be able to fix it.

**Comment by Pieze87** [comment]
again that was over a month ago. it was serveral ranks of stealth and
people and mobs of same level and lesser were able to see you within 10 -15
yards.  so id start with rank 2 and 3 and go from there.

**Comment by akrom23** [comment]
I believe it works fine now. Please, test it again.
