### ISSUE TITLE
Cat form movement speed isn't working properly

### ISSUE THREAD

**Issue by Swiplington** [SunwellWoW/Sunwell-TBC-Bugtracker#2748]
Description: 
Cat form retains it's movement speed form the moment it was cast.

How it works: 
If you go in Cat form outside you get the 30% extra movement speed from the talent Feral Swiftness, when u walk inside a building/cave you keep the 30% movement speed for as long as you stay in Cat form.

It also works vice versa, if cast inside you get 0% extra movement speed and when you walk outside you don't get the extra 30% untill you shapeshift into Cat Form again.

How it should work: 

Cat form should automaticly give/reduce movement speed when walking in/outside a building or cave.

Source (you should point out proofs of your report, please give us some source): 
levle 65 druid

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2534
