### ISSUE TITLE
[WARLOCK] Howl of Terror

### ISSUE THREAD

**Issue by Qnkad** [SunwellWoW/Sunwell-TBC-Bugtracker#2749]
Description: 
Howl of Terror shouldnt be affected by Grounding Totem when im right. I could only test it once in World PvP but it seemed like Howl doesnt have effect with grounding totem up. You should test it yourself tho!

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Cannot reproduce it.
