### ISSUE TITLE
Defender Zaibach and Defender Sorli are stack on each other

### ISSUE THREAD

**Issue by kieran1188** [SunwellWoW/Sunwell-TBC-Bugtracker#2750]
Defender Zaibach(npc=18031) and Defender Sorli(npc=18024) are stack on each other.

![wowscrnshot_120718_184951](https://user-images.githubusercontent.com/38033595/49666988-8d04d800-fa51-11e8-93e5-4e0c07a2e1d6.jpg)

I have check wow-head and i have found the coords for their correct position 

Coords

https://www.wowhead.com/npc=18024/defender-sorli - 55.6/52.3
https://www.wowhead.com/npc=18031/defender-zaibach - 55.4/52.6

**Comment by Dootz** [comment]
Fixed & implemented, thank you for report.
