### ISSUE TITLE
[Priest] [Spell] Mind Flay

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#2754]
Description: 
Mind Flay works as a slow, so when a higher slow percent debuff is already on the target the Mind Flay will not do any damage

How it works: 
A stronger slow effect is on the target, the priest attempts to cast mind flay and the mind flay will be cast but will not do any damage and will not put the mindflay debuff or slow on the target. I believe it says "a stronger spell is present?"

How it should work: 
Mind flay should be cast regardless of what other slows are present on the target, and should do damage to the target as well

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
can confirm, the damage part should always work, regardless of other slow-debuffs on the target.

**Comment by akrom23** [comment]
![wowscrnshot_011919_173738](https://user-images.githubusercontent.com/1035215/51429664-f19a8180-1c10-11e9-8da0-eb30577fe66f.jpg)
Works fine.
