### ISSUE TITLE
Elite pack spawning when pulling Herod

### ISSUE THREAD

**Issue by Mallekito** [SunwellWoW/Sunwell-TBC-Bugtracker#2759]
Description: 

An elite pack is spawning right behind the door, after you pull Herod in Scarlet Monastery: Armory
How it works: 

How it should work: 
Not spawn

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
From what I remember it was set-up this way intentionally

**Comment by Mallekito** [comment]
It wasnt. The mobs never spawned there. And it blocks the way out of it. On retail i remember that it was not that way. and on every other vanilla private, they never spawned.
________________________________
De: Chris <notifications@github.com>
Enviado: sexta-feira, 7 de dezembro de 2018 20:26
Para: SunwellWoW/Sunwell-TBC-Bugtracker
Cc: Mallekito; Author
Assunto: Re: [SunwellWoW/Sunwell-TBC-Bugtracker] Elite pack spawning when pulling Herod (#2759)


From what I remember it was set-up this way intentionally

**Comment by mjk6994** [comment]
This is 100% Unintentional. No mobs spawned during the fight, after death non elite trainees spawned.  
https://www.youtube.com/watch?v=eGzTX9eUwl4

**Comment by Mallekito** [comment]
I know that the non elite trainees spawn. i am saying that 3 ELITES spawn near the door when u start Herod. That's the bug
________________________________
De: mjk6994 <notifications@github.com>
Enviado: domingo, 9 de dezembro de 2018 21:28
Para: SunwellWoW/Sunwell-TBC-Bugtracker
Cc: Mallekito; Author
Assunto: Re: [SunwellWoW/Sunwell-TBC-Bugtracker] Elite pack spawning when pulling Herod (#2759)


This is 100% Unintentional. No mobs spawned during the fight, after death non elite trainees spawned.
https://www.youtube.com/watch?v=eGzTX9eUwl4

**Comment by mjk6994** [comment]
u n I n t e n d e d
