### ISSUE TITLE
[NPC] Battlemasters in Shattrath

### ISSUE THREAD

**Issue by Dolamor** [SunwellWoW/Sunwell-TBC-Bugtracker#276]
Description: 
Some time ago they were added by command .npc add <id> (there were no NPCs except Warbringer I guess) but .npc add command doesn't add them permanently into database (as Graal stated).

How it works: 
On the actual TBC realm there will be no NPCs in this place? 
There's also a duplicated AB Battlemaster which can't be removed with .npc delete as it crashes the PTR.

How it should work: 
There should be all 5 of them in order from left to right:
WSG Battlemaster (id 20269)
AV Battlemaster (id 20276)
Horde Warbringer (id 15350)
AB Warbringer (id 20274)
EotS Warbringer (id 20384)

https://imgur.com/a/7btDaOJ

**Comment by notsofamous** [comment]
https://i.gyazo.com/eb72bf7245783df1d8380801ff406796.png

Found this from retail how they should be positioned
