### ISSUE TITLE
Mobs Hitting Multiple Times In One Hit

### ISSUE THREAD

**Issue by Heftyarms** [SunwellWoW/Sunwell-TBC-Bugtracker#2761]
Description: 
While attacking various different mobs, noticed the mobs will attack as if they had a Windfury proc. Such as the mob will hit you but its more like a triple hit. I've actually seen mobs triple/quad/5/6/7 time hit in one swing CD. 

How it works: 
It happens on occasion, but I've noticed many mobs doing this. Example of some mobs that do this, Defias Knuckduster in Westfall, and the Frenzied Pterrordax in Un'Goro has done this as well. Many of mobs are doing the same thing, maybe the system is wonky.

How it should work: 
Some mobs have fixed Weapon Swing timer, or skills that allow multiple hits. In this case, it seems the weapon swing timer is way off. It should be normalized and allow the swings to happen on CD rather than skip and apply the next swing together.

Source (you should point out proofs of your report, please give us some source):

**Comment by 0vertime** [comment]
Frenzied Pterrordax has Thrash but I noticed it can hit 5 times a second sometimes.

**Comment by Fuzedknight** [comment]
This isn't a bug it's a monster mechanic called Thrash that gives them 2 additional swings like Windfury. Some of them have it, though it shouldn't be able to proc off itself like 0vertime experienced.
