### ISSUE TITLE
Hunter pet disappear upon taming another pet

### ISSUE THREAD

**Issue by Baeyz** [SunwellWoW/Sunwell-TBC-Bugtracker#2762]
Description: 
Dismissing current pet and trying to tame another pet will cause your current pet to disappear.

How it works: 
Dismissing current pet and trying to tame another pet will cause your current pet to disappear.

How it should work: 
It should either 1. Not allow you to tame a beast with a pet dismissed. 2. Return the current pet to stable.

Source (you should point out proofs of your report, please give us some source):

**Comment by Lunasoll** [comment]
As far as I know, it shouldn't allow to tame another pet at all if you have one out or dismissed. There was no such thing as returning current pet to stable, it had to be done manually first before going to tame a new one.
