### ISSUE TITLE
[Quest] Fel Reavers, No thanks

### ISSUE THREAD

**Issue by puggless** [SunwellWoW/Sunwell-TBC-Bugtracker#2763]
Description: Quest Fel Reavers, No thanks

How it works: Gan'arg Mekgineers do not drop Condensed Nether Gas

How it should work: Gan'arg Mekgineers should drop Condensed Nether Gas

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Fixed & implemented, thank you for report.
