### ISSUE TITLE
[NPC] Tamed Ravager

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#2764]
Description: The Mag'har Hunter's pet, Tamed Ravager does not disappear when the owner dies.

How it works: The Mag'har Hunter's pet, Tamed Ravager does not disappear when the owner dies.
When the Hunter Respawns, so does the Tamed Ravager, leaving two ravagers. See image.

![image](https://user-images.githubusercontent.com/15868285/49673552-af7ffc80-fa23-11e8-89b4-873ad4c370fb.png)

How it should work: The pet should disappear when the owner dies, and damage is not taken.

Source (you should point out proofs of your report, please give us some source):

**Comment by Piootrek** [comment]
I just checked and pet disappear correctly.
