### ISSUE TITLE
[Quest] The Exorcism of Colonel Jules (cannot be turned in)

### ISSUE THREAD

**Issue by Lunasoll** [SunwellWoW/Sunwell-TBC-Bugtracker#2767]
**Description:** 
This is the final part of the quest when Colonel Jules gets exorcized. 

When quest accepted, NPC (Assistant Klatu) gives a quest item called Ritual Prayer Beats (which can be used either heal friendly NPCs or kill hostile ones). 

**How it works:** 
Upon completion of the exorcism, the quest cannot be handed in, because the NPC acts as if you don't have Ritual Prayer Beats in your bag even though it is in the bag. Therefore, the quest cannot be turned in, even though it shows 'completed' in the quest log. 

**How it should work:** 
Players should be able to turn in the quest after its completion.

**Comment by popalexandrudan** [comment]
if you click the colonel after the ritual finishes, it will work )

**Comment by Dootz** [comment]
Exaclty. That's how it's supposed to work. You need to click on Colonel once he "lands" on bed.

**Comment by Lunasoll** [comment]
yeah sorry my fault. It worked.
