### ISSUE TITLE
Fishing Nodes

### ISSUE THREAD

**Issue by AshhSunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#2770]
Description:  All fishing nodes I have fished in only produced 1 fish then despawned. 

How it works: Fishing nodes like Pure Water nodes in Nagrand aren't even appearing & the fish nodes like Icefin Bluefish pool only give you one fish before despawning, they should allow you to get 3-4 casts out of them before despawning

How it should work: You should be able to fish 3-4 times before a pool despawns & certain pools like Pure Water nodes should be spawned in Nagrand Lake

Source (you should point out proofs of your report, please give us some source):  https://tbc-twinhead.twinstar.cz/?object=182951
Look in Nagrand there are NONE in the lake where there are usually 5+ spawn points

**Comment by Shadowkill22** [comment]
I am farming and what I can see, is that on every place of every nod is some kind of "chance", what node will spawn like the next one.

**Comment by Shadowkill22** [comment]
There is thing with that. that Pure water have the same place like classic fish nodes. Then there is happening that, when is spawning new ones, so there is most probably rolling between 2 fish nodes and pure water which one will be the next one. Don´t know if it should work like this. :)

And another bug that it is giving every single time only 1 mote of water, should be 1-2 every single try.

https://tbc-twinhead.twinstar.cz/?object=182951

http://rpgtutorwowgoldguide.com/gathering-guides/nagrand-fishing-route-for-primal-water/

**Comment by SlizeTBC** [comment]
"There is thing with that. that Pure water have the same place like classic fish nodes. Then there is happening that, when is spawning new ones, so there is most probably rolling between 2 fish nodes and pure water which one will be the next one."

Def. a bug.
