### ISSUE TITLE
[Blacksting's Bane - Zangarmarsh]

### ISSUE THREAD

**Issue by Gryma** [SunwellWoW/Sunwell-TBC-Bugtracker#2775]
Description: Need to kill Blacksting and take on his corpse "Blacksting's Stinger".

After four times, he doesn't give me item quest (tried with an another player, same bug as me). But, some player obtain item quest. After 6 tries, finally get it. I think item doesn't drop at 100%.

Quest : http://db.darkwizard.pl/?quest=9896
Mob : http://db.darkwizard.pl/?npc=18283
Item : http://db.darkwizard.pl/?quest=9896

**Comment by Dootz** [comment]
currently it has 80% drop chance.  Will be increased to 100%.

**Comment by Dootz** [comment]
Fixed & implemented, thank you for report.
