### ISSUE TITLE
Trinkets block each other

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#2778]
Description: / How it works: 
- [Item] ancient draenei war talisman
- [Item] bladefists breadth 
- if i use 1 of the item above, the other item will be unavalible for 90sec
- both items block each other somehow

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![grafik](https://user-images.githubusercontent.com/45068171/49677568-c6ecd300-fa7f-11e8-86a2-424f95c5e9ea.png)

**Comment by Azathothh** [comment]
#2802
