### ISSUE TITLE
Silithus - Silithyst Geyser BUG

### ISSUE THREAD

**Issue by syphex97** [SunwellWoW/Sunwell-TBC-Bugtracker#2782]
Description: 
The Silithyst Geysers in Silithus is clickable however  an orange aura called Silithyst should surround you and if you go to your factions camp and turn it into the gnome machine it should give you rewards, ur faction points in the zone but as well if you have the quest  [Scouring the Desert] should be completed.

This quest however is not complete able since the Geysers doesnt work. 

How it works: 
Clicking a Silithyst Geyser does nothing other than it disappears.

How it should work: 
Clicking a Silithyst Geysers should give you an orange aura called Silithyst & the geyser disappears from the ground.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/object=181598/silithyst-geyser - First Comment was made 2007 which was during TBC

**Comment by Sabre142** [comment]
#1138
