### ISSUE TITLE
[Warlock][Spell][Pet] Lesser Invisibility

### ISSUE THREAD

**Issue by Sunwellscriptinglul** [SunwellWoW/Sunwell-TBC-Bugtracker#2783]
Description: After https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1816 "fix" Succubus breaks "Lesser Invisibility" whenever you send her to /pettattack, making it impossible to properly position her for Seduction while she's under the effect of invisibility, that SHOULD NOT HAPPEN.

How it works: 
1)Use Lesser Invisibility;
2)Send Succubus to target with /petattack;
3)She will break out of invisibility immediately without casting any spells or actually autoattacking.

How it should work: "Lesser Inivisbility" should not break UNLESS:
1)Succubus has been damaged;
2)Succubus has used any of her abillities (Lash Of Pain, Soothing Kiss, Seduction);
3)Succubus has autoattacked.

Source (you should point out proofs of your report, please give us some source): 
1)https://www.youtube.com/watch?v=jODr_Bvv3hY 12:47 warlock sends Succubus on paladin and she doesn't break invis UNTIL she casts Seduction.
2)https://www.youtube.com/watch?v=07La00KaV0U 0:22 same thing, Succubus doesn't break out until Seduction cast.
3)https://www.youtube.com/watch?v=dCEr2VA755k 6:53 warlock sends Succubus to the other lock with /petattack and when she's close he presses Seduction, sucubbus doesn't break out of invis until that moment.
4)https://www.youtube.com/watch?v=Usyb821NVuo 11:57 warlock sends pet to autoattack hunter, Lesser Invisibility doesn't break until the very moment she hits. Later at 13:18 he sends pet at hunter, invisibility breaks as soon as she uses "Soothing Kiss".

P.S. Please stop considering WoWwiki as a "reliable source" without any video proofs - it can be edited and may contain misinformation.

**Comment by Wojtyas** [comment]
Moved to https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2626

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3434
