### ISSUE TITLE
Ressing spell not working

### ISSUE THREAD

**Issue by rafail-stankov** [SunwellWoW/Sunwell-TBC-Bugtracker#2785]
Description: 
Short story:
I tried to ress a friend of mine who was dead in Arathi Highlands and it didn't work.

Long story:
We were doing the quest Trol'kalar in Arathi Highlands. We were in Stromgrade Keep next to the chapel with the tomb. I was behind the "wall" of the graveyard whereas my friend died in front of the chapel. I'm saying "wall" because it's not solid and I can cast the spell through it. My ressing spell rank is level 1 (priest). The spell did cast successfully. My mana got burned but nothing happend. No light appeared on his body and he didn't get the chance to accept the ress. We also tried after he released - same. I don't know what causes it .. I just thought it's useful to let you know.

How it works: 
Nothing happens. Mana is spent though.

How it should work: 
He should see the "accept" and "release spirit" pannel.

Source (you should point out proofs of your report, please give us some source): 
I was actually recording it but it's quite a long video so if you really need to see it I will send you cuts of the video.

**Comment by koostosh** [comment]
Could not reproduce, please reopen if it happens again
