### ISSUE TITLE
Starving Hellboar

### ISSUE THREAD

**Issue by Mansgroll** [SunwellWoW/Sunwell-TBC-Bugtracker#2786]
Description: 
The "thorns" ability that these Hellboars have is stacking on each hit

How it works: 
It stacks, it hit once, then twice, then thrice and so on

How it should work: 
It should tick 1 time everytime it gets a melee hit 
![starving hellboar](https://user-images.githubusercontent.com/40536253/49678722-affdaf00-fa86-11e8-9fb2-85b2c376a721.png)

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Already reported https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2439
