### ISSUE TITLE
Auction house is weird

### ISSUE THREAD

**Issue by jockeboschko** [SunwellWoW/Sunwell-TBC-Bugtracker#2788]
Description: 
So there is something wonky with how the AH orders items.

How it works: 
Second page https://gyazo.com/5fe5086845bec65073342d6b08cc4ebc
Third page https://gyazo.com/46109836013f7faffa7dabd2c53a290c
first page is usually the most expensive and then it goes lower by page
How it should work: 
I dont know but it should be reversed

Source (you should point out proofs of your report, please give us some source):

**Comment by BIGCHESTDAY** [comment]
LOL you can click the last tab near the price and fix this XDDDDDDDD

**Comment by jockeboschko** [comment]
that u can not. It just sorts the page not the pages if u catch my drift
