### ISSUE TITLE
Defence Rating Warrior 

### ISSUE THREAD

**Issue by Montrey88** [SunwellWoW/Sunwell-TBC-Bugtracker#2789]
Description: 
Talents 
Anticipation Doesnt Work Proper cant level defence rating more.
How it works: 

95/120
How it should work: 
120/120 cant level more... 
![1](https://user-images.githubusercontent.com/45702675/49679545-77f96a80-fa8c-11e8-9330-399e9e27be8f.jpg)
![2](https://user-images.githubusercontent.com/45702675/49679548-7e87e200-fa8c-11e8-8f5c-02ed50b43b0c.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Montrey88** [comment]
Just Dinged to lvl 20.  So i can max my defence rating to 100 nothing more... 100/120 shoyld be 120/120

**Comment by goldeNjo3** [comment]
Yes, the talent is not working
