### ISSUE TITLE
Warlock Talent not Working 

### ISSUE THREAD

**Issue by Espranty** [SunwellWoW/Sunwell-TBC-Bugtracker#2795]
Description: 
Talent called Demonic Knowledge, doesnt work, i see the buff on my pet  , but not on myself, and tested swapping pets /relogging /Mounting and Dis-mounting , Spell damage is still the same, so its bugged

How it works: 
Should increase spell damage by 12% of pet's stamina+intellect .

How it should work: 
Should increase spell damage by 12% of pet's stamina+intellect 

Source (you should point out proofs of your report, please give us some source):

**Comment by SunwellTracker** [comment]
We know. Talent will be fixed today or on Sunday. We've already got a report concerning this bug.
