### ISSUE TITLE
death coil not working correctly

### ISSUE THREAD

**Issue by Espranty** [SunwellWoW/Sunwell-TBC-Bugtracker#2797]
Description: 
Death coil is a 3 seconds Disorient /Fear-type ability for locks ..
the problem here is , when u cast death coil on a target > Any damage at all (Physical /Dots /Anything) will break the effect from continuing its full duration ... which is not correct

How it works: 
Dot any target (Bleed /Dot /anything) > Cast death coil > Watch as it Breaks in 0.5 sec or on first damage the target takes .

How it should work: 
Death Coil Should not be Broken by damage .... its a Fear /Spell that Should Disorient the target for the Full duration regardless of damage taken .

Source (you should point out proofs of your report, please give us some source):

**Comment by obvsly** [comment]
Came here to report this exact bug. It should not be breaking early from damage.

**Comment by jowns** [comment]
Yes, Death Coil is broken and breaks from damage. Fix this please!

**Comment by tacotal** [comment]
My friends have confirmed this bug as well. Unlike fear, Death Coil should not break.
