### ISSUE TITLE
Warlock fear 2x Specific issues

### ISSUE THREAD

**Issue by Espranty** [SunwellWoW/Sunwell-TBC-Bugtracker#2798]
Description: 
1- The feared target will run to the End of the earth if the (Random run path while feared) stacked to push him into a straight-ish path ....

they will run 50+ yards away from where u feared them , which is Totally not right (i played lock in TBC /WoTLK Retail)

2- Also mobs seem to be Super freaken FAST when they are feared .. which is also not Right.

How it works: 
Fear a target multiple times and see the 2x issues

How it should work: 
Feared mobs should wonder within range , at least not as far as 40+ yards away.
Feared mobs should still Run at their respective Normal speed.

Source (you should point out proofs of your report, please give us some source):

**Comment by Silroth** [comment]
Feared mobs/players should run at 25% increased speed not normal speed.

**Comment by ujellyx** [comment]
Also: Fear doesn't break from damage, like it should. There seems to be no damage threshold (unless it's already fixed...)

**Comment by Testimonia** [comment]
how is fear still bugged...... still doesnt break on dmg.. raids are out you can basicaly fear mobs to death gg

**Comment by ujellyx** [comment]
yeah... and they are gonna start the pvp season tomorrow with these kinds of big class bugs... wow.
