### ISSUE TITLE
Priest: Mind Control bug

### ISSUE THREAD

**Issue by Unfairy** [SunwellWoW/Sunwell-TBC-Bugtracker#28]
Decription: 
Priest's Mind Controlled mob's spells damage scaling bug.

How it works: 
Priest Mind control caster mob. Mob's spells damage getting scaled with Priests spell damage.

How it should work: 
Priest Mind control caster mob. Mob's spells damage staying the same and not dependant on Priest's spell damage

Source (you should point out proofs of your report, please give us some source): 
In game test. Tested on Blasted Lands' Ogre mage. Tested on Strangethorn Valley Ogre Shaman.

**Comment by Camarila** [comment]
Would like to add that what does work:
The spell itself works on a target.
A mind controll buff is gained.
A player is interrupted if dead or an interruption spell is used. i.e silence.
A mind controlled target is moving and auto attacking.

What doesn't work: 
A target doesn't have any spells on it's bar other than the auto attack.

**Comment by siof** [comment]
@Camarila: it's probably database bug. Spells available on bar are stored for each creature in database. If creature don't have any spells set then only auto attack will be visible on bar.

**Comment by akrom23** [comment]
Cannot reproduce.

**Comment by akrom23** [comment]
No response - closed.
