### ISSUE TITLE
Trall NPC in nagrand is invisible

### ISSUE THREAD

**Issue by popcorn16** [SunwellWoW/Sunwell-TBC-Bugtracker#2800]
Description: 
Thrall NPC walking around in Garadar in Nagrand is not visible. Only his hammer is.

How it works: 
Invisible

How it should work: 
Visible :P
![wowscrnshot_120818_035404](https://user-images.githubusercontent.com/45704143/49681130-eba37380-fa9c-11e8-873c-b035792b8d47.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
@Wojtyas please verify after update

**Comment by Wojtyas** [comment]
OK BRO

**Comment by Dootz** [comment]
implemented on live, please retest

**Comment by popcorn16** [comment]
Still invisible 
![wowscrnshot_120918_131838](https://user-images.githubusercontent.com/45704143/49697223-fd783a00-fbb4-11e8-81b0-5049e3130171.jpg)

**Comment by Wojtyas** [comment]
Visible... :)
