### ISSUE TITLE
[npc] 3678

### ISSUE THREAD

**Issue by dredd-sunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#2801]
Description: npc 3678 is generating far too much threat

How it works: Disciple of Naralex generates so much threat it's impossible to take aggro from him, and he dies.

How it should work: 3678 shouldn't generate so much threat and it should be easy to take aggro from him and escort him safely

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
