### ISSUE TITLE
Trinket "use" chaining

### ISSUE THREAD

**Issue by smkrus** [SunwellWoW/Sunwell-TBC-Bugtracker#2802]
Description: 
Cannot chain "uses" of 2 trinkets after shared 15s CD
http://db.hellfire-tbc.com/?item=31617
http://db.hellfire-tbc.com/?item=28041

How it works: 
Correctly displays 15s CD on the 2nd afer using the 1st
Does not allow use of 2nd trinket until after 1st completes full CD

How it should work: 
Should allow chain trinket "use" after shared 15s CD

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=31617/ancient-draenei-war-talisman#comments
This is great in additon to http://www.wowhead.com/?item=28041! I can use one on nearly every mob and it increases my dps pretty good. Don't know any better trinkets than these two before lvl 70.

This item does not share it's full cooldown with other similar items of this type, only time the buff it gives is on. It means you can use one of them after another, but their effect cannot be stacked.

**Comment by Patiarchus** [comment]
Same Problem from me - Thanks for report !

**Comment by Azathothh** [comment]
same with https://db.darkwizard.pl/?item=31615 and https://db.darkwizard.pl/?item=28040

**Comment by Kuikku** [comment]
Same thing with Scyers revered trinket and Shatar revered trinket. Both buffs name is "spell power" and gives same amount of spellpower/healing.
