### ISSUE TITLE
Aaron Hollman restock timer to high

### ISSUE THREAD

**Issue by Poonage** [SunwellWoW/Sunwell-TBC-Bugtracker#2803]
Description:  Limited blacksmith patterns having 12 hour restock timer..

How it works:  12 hours to restock items on npc Aaron Hollman

How it should work: Reduced restock time

Source (you should point out proofs of your report, please give us some source): Spoke to GM tide who agreed it may be to high and to make a post here.

**Comment by Wojtyas** [comment]
Any proof it should be lower?

**Comment by Poonage** [comment]
As i said to tide last night, Maybe the 12hr respawn is " blizzlike " and other private servers have just adjusted it based on population.

**Comment by Poonage** [comment]
May i ask what the fix will be? thanks

**Comment by Dootz** [comment]
it was changed to 15 minutes
