### ISSUE TITLE
Failing quest after completing it - Escort

### ISSUE THREAD

**Issue by northdalewiz** [SunwellWoW/Sunwell-TBC-Bugtracker#2804]
Description: Quest: Escape from the Firewing point!
After you finish escorting her, turn in the quest, she can still die on her way to the city, which causes the quest to be failed. 
I've got a game message: "Quest Escape from the Firewing point! failed".
Not only is it a game message bug, but I also could pick up the quest again, even though I finished it
How it works: You escort the girl from the firewing point. She dies somewhere on her way to the city and the non-existing quest is failed. You can pick up the quest again.

How it should work: It shouldn't be possible to fail a quest after completing it. It's a chain bug I think that causes you to be able to pick up the quest again even though it's non repetable.

Source (you should point out proofs of your report, please give us some source): 
I've done the quest 2times.

**Comment by notsofamous** [comment]
It happens because she spawns back in her cage and is instantly killed by the guards there.
I reported it here: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/311

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
