### ISSUE TITLE
No loot from rares

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2807]
Description: 
Rare mobs do not have loot.

How it works: 
No loot on rare mobs.

How it should work: 
Blues and greens, as well as various other items should be on rares.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
How many rares have u killed? :v:

**Comment by Nelthalor** [comment]
I think it might be a case by case issue from them instantly respawning, but for the loot I had killed the one near the front of the Fallow Sanctuary camp in Swamp of Sorrows roughly 3-5 times with no loot at all (I can help show you if you want). I killed a rare in Redridge and no loot, as well as a different rare in Swamp of Sorrows from the one near the front of the Broken. I believe I killed one in Wetlands (not 100% sure) as well that did not give loot. I do not think there are others but I could be wrong.
