### ISSUE TITLE
Rares have normal mob respawn time

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2808]
Description: 
Rare mobs respawn as if they were a normal mob.

How it works: 
Rare mobs respawn as if they were a normal mob.

How it should work: 
Rare mobs should have extremely long downtime.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
I see most of rare have 1.5h - 12h respawn time (depending on creature). Could you give me name of rare mob u killed?

**Comment by Nelthalor** [comment]
I believe that the Lost One Chieftan and the Lost One Cook are like that, I know the Chieftan was respawning constantly and either had no loot or just copper. I saw the Cook up right away once but I avoided him because he's surrounded by a lot of mobs.

**Comment by Nelthalor** [comment]
Thanks for fixing :)

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
