### ISSUE TITLE
Dustwallow spawns are really lackluster

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2809]
Description: 
Dustwallow spawns are really lackluster, probably the lowest in the zone. With how much xp the quests give from tbc (pretty much 2 quest hubs added with their tbc quest hub design in place, which makes the zone almost required for very quick and easy levels).

How it works: 
Really low, very few spawns in high peak locations all times of the day.

How it should work: 
Increased like other zones.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Dynamic respawn has been disabled.
