### ISSUE TITLE
Interrupts with Spell school lockdowns do not lockdown if performed on npc

### ISSUE THREAD

**Issue by worugru** [SunwellWoW/Sunwell-TBC-Bugtracker#281]
Decription: 
Any interrupt spell with "prevents any spell in that school from being cast for XX sec."  does not prevent anything when used on npcs

How it works: 
The cast of the npc gets interrupted, but npc starts to cast again right after it. Tried it with kick, shieldbash and counterspell, all the same result. But they do lock the school down if performed on a player.

How it should work: 
It should prevent the spells from same school to be casted for the duration that is written in tooltip.

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/kkvcl

**Comment by akrom23** [comment]
Can be closed?
