### ISSUE TITLE
Badlands 

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2810]
Description: 
Not the most high traffic zone, but the spawn rates are really slow and sometimes feel slower than they are supposed to.

How it works: 
Really low, very few spawns in high peak locations all times of the day.

How it should work: 
Increased like other zones.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Dynamic respawn has been disabled.
