### ISSUE TITLE
Stonemaul Ruins seems to have lower respawn time than usual

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2811]
Description: 
Stonemaul Ruins seems to have lower respawn time than usual, something feels off.

How it works: 
Really slow respawn, usually 3-5 people from either faction packed there.

How it should work: 
Increased respawn times.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Dynamic respawn has been disabled.
