### ISSUE TITLE
Sometimes execute doesn't do damage

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2815]
Description: 
When I spam execute before getting the rage, sometimes it will consume the rage after I get enough and it will not show any dodge, parry, miss, or hit.

How it works: 
Execute sometimes doesn't deal damage, somewhat rare.

How it should work: 
Execute should always at least swing when used.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2668
