### ISSUE TITLE
[Paladin][Blessings] Greater and small blessing at once

### ISSUE THREAD

**Issue by fakelort** [SunwellWoW/Sunwell-TBC-Bugtracker#2816]
Description: 
Greater blessing stacks with regular blessing, not sure if the ranks was different so may be related to #2552 

How it works: 
I had both a greater and a regular blessing of wisdom.

How it should work: 
Only one should be possible to have.

Source (you should point out proofs of your report, please give us some source): 
Blessing of wisdom. Didn't try other blessings

**Comment by Wojtyas** [comment]
Already fixed but not live yet.
