### ISSUE TITLE
[NPC] Burning Blade Bruiser and Crusher

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#2818]
Description: Burning Blade Bruiser and Crusher apply Bruise debuffs on themselves instead of their target.

How it works: 

How it should work: Should work like a standard debuff on enemy.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
