### ISSUE TITLE
[The End of the Deserters] does not give credit when the npcs attack you

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2819]
Description: 
[The End of the Deserters] Theramore quest does not give credit when the npcs attack you instead of any other option.

How it works: 
You do not get credit when the NPC's become hostile.

How it should work: 
You get credit when you defeat them.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Moved to https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2567
