### ISSUE TITLE
[Hunter][Pets][Spell] Cower

### ISSUE THREAD

**Issue by sulowitch** [SunwellWoW/Sunwell-TBC-Bugtracker#2825]
Description: Hunter pet is using Cower skill even if it is disabled.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/ZDvGhaK

**Comment by akrom23** [comment]
@sulowitch Cannot reproduce it.

**Comment by akrom23** [comment]
No response.
