### ISSUE TITLE
[NPC] Missing Bow vendor Undercity Ebigail Sawyer

### ISSUE THREAD

**Issue by HaAdam1** [SunwellWoW/Sunwell-TBC-Bugtracker#2833]
Description: Abigail Sawyer <Bow Merchant> missing from Undercity spawn location.

How it works: NPC doesn't exist.

How it should work: NPC should exist.

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/oH0WPVW
http://wowwiki.wikia.com/wiki/Abigail_Sawyer
https://www.wowhead.com/npc=4604/abigail-sawyer

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
