### ISSUE TITLE
[Warlock] Shadow Embrace

### ISSUE THREAD

**Issue by Aeded** [SunwellWoW/Sunwell-TBC-Bugtracker#2834]
How it works: 
1. Shadow Embrace debuff does not wear off when dots disapper
![wowscrnshot_120418_183030](https://user-images.githubusercontent.com/45561230/49686604-15898400-faf7-11e8-83b9-f1b074d385b7.jpg)

How it should work: 
1. Shadow embrace should wear off immidiately when there are no active debufs that apply it.

Source (you should point out proofs of your report, please give us some source): 
Common knownledge

**Comment by Wojtyas** [comment]
Fix on way
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2735
