### ISSUE TITLE
Can't apply judgements on multiple mobs

### ISSUE THREAD

**Issue by Felynda** [SunwellWoW/Sunwell-TBC-Bugtracker#2838]
Description: 
When casting judgement of justice/light/wisdom/crusader the debuff goes onto the mob. Then you cast judgement on a second mob and the debuff dissapears off the first.

How it works: 
Pull 2 or more mobs
cast judgement on mob 1
wait cd
cast judgement on mob 2
observe mob 1 having lost the debuff

How it should work: 
Both mobs should have the debuff

Source (you should point out proofs of your report, please give us some source):

**Comment by Felynda** [comment]
BUMP still bugged over a month later

**Comment by akrom23** [comment]
Just read the tooltip:

> Only one Judgement per Paladin can be active at any one time.
