### ISSUE TITLE
Sunken Temple

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#284]
### **TO DO:**

- [x] 1. Veyzhak the Cannibal (5399) has AI missing. He doesn't use any of his spells: Enrage (8599) and Rend (43246). He also should have Dual Wield passive aura (674).
- [x] 2. Veyzhak the Cannibal stays in wrong position. Correct ones on screen:
![image](https://user-images.githubusercontent.com/22802214/44948559-be9d5000-ae1f-11e8-8324-879acc9e8919.png)
- [ ] 3. Zekkis (5400) has missing weapon. He should keep spear in his hands.
- [ ] 4. Everytime we'll try activate Atal'ai Statue in wrong older, gob should punish player and cast spell on him.
**S:** gob 27898 can't punish player cuz it's first gob in line.
**N:** gob 27899 should cast Dark Energy spell (18948)
**SW:** gob 28111 should cast Flame of Hakkar spell (12354)
**SE:** gob 28112 should cast Atal'ai Poison spell (18949)
**NW:** gob 28113 should cast Dark Energy spell (18948)
**NE:** gob 28114 should cast Flame of Hakkar spell (12354)
For now they don't cast spells on players when they try to activate them in wrong order.
- [ ] 5. When all of Atal'ai Statues gobs are activated there should spawn Idol of Hakkar gob (id 148838) in the middle of the room. For now it doesn't happen.
**EDIT: Gob is to small and doens't stay in the middle of the room**
![image](https://user-images.githubusercontent.com/22802214/44947989-f99a8600-ae15-11e8-92ff-cf8edee53adb.png)
- [x] 6. When Atal'alarion is pulled he yells something weird sentence lol. Probably he speaks trollish or orcish (dunno). Anyway he should speak common language. Yell sentence:
"I'll feast on your bones!"
- [x] 7. Altar of Hakkar (11922) has no interaction with players. It should have text and dialogue. After players talk with it (by dialogue) it should spawn small gobs (green lights) over Atal'ai Statues to show proper order of activation. Dialogue option should appear only for players who have done Into the Depths (3446) quest.
![image](https://user-images.githubusercontent.com/22802214/44948046-de7c4600-ae16-11e8-9f1d-772c0b202091.png)
- [ ] 8. Slime Maggot (8311) should start to attack players if we pull something near them. They will become hostile and attack players, though they are neutral. They don't attack now.
- [ ] 9. Looks like Unliving Atal'ai (5267) doesn't use his Thrash spell (3391).
- [ ] 10. Atal'ai Witch Doctor (5259) interrupts his Lighting Bolt (9532) casts by casting other spells.
- [ ] 11. Atal'ai Slave (8318) should be immune to all curse spells.
- [ ] 12. Atal'ai Corpse Eater (5270) uses his Atal'ai Corpse Eat (12134) but it should work differently.
When he's about to cast that spell he should run over some dead body and cast it there. For now he eats corpses when there are no corpses below him. There is also wrong spell animation, during that spell he should grab this corpses but for know npc just kneel. It should look exactly like undead's Cannibalize spell (20577).
![image](https://user-images.githubusercontent.com/22802214/44948364-9bbd6c80-ae1c-11e8-8984-21b2eb9f861d.png)
At 0:25 u can see proper animation of spell.
https://www.youtube.com/watch?v=FdSRJt8BmzU
- [x] 13. All of those troll minibosses should have green cast animation when they are out of combat and stay on their positions:
**EDIT: Mijan doesn't have Green Channeling aura (13540)**
![image](https://user-images.githubusercontent.com/22802214/44948686-5d2ab080-ae22-11e8-94d9-3d7accf32ea5.png)
- [ ] 14. Atal'ai Totem (8510) should have 920 health, for now it has 90 health.
- [ ] 15. Zolo (5712) shouldn't use Atal'ai Skeleton Totem spell (12506) if there is Atal'ai Totem (8510) spawned.
- [ ] 16. For now, Atal'ai Totem can't spawn more Atal'ai Skeletons when there is one spawned already. Totem should continue spawn more Skeletons even if there are any skeletons alive.
- [ ] 17. Hukku's Guardians spells (12790) summons only Hukku's Voidwalker (8656). This spell should summon Hukku's Voidwalker (8656) + Hukku's Imp (8657) + Hukku's Succubus (8658) simultaneously.
- [ ] 18. Spawned Hukku's minions should start to attack players immediately.
- [ ] 19. Hukku's Imp (8658) interrupts his Fire Shield spell (11770) by casting Firebolts (11762).
- [ ] 20. Hukku's Succubus (8657) should use her Lash of Pain spell (11779) more often.
- [ ] 21. Hukku's Imp and Hukku's Succubus should start to attack players once spawned.
- [ ] 22. Looks like Hukku's Succubus doesn't use her Seduction spell (6358).
- [ ] 23. Looks like Nightmare Whelp (8319) doesn't use his Acid Spit spell (15653). Pss, it requires mana while creature doesn't have it.
- [x] 24. Looks like Nightmare Wyrmkin (5280) doesn't use his (Sleep) 12098 spell.
- [ ] 25. Nightmare Wyrmkin has weird autoattack animation while casting Acid Spit spell (15633).
- [ ] 26. Spawned Atal'ai Deathwalker's Spirit should start to attack players immediately.
- [ ] 27. Atal'ai Deathwalker's Spirit hits for around 1k while he should for 411 - 488.
- [ ] 28. Looks like Ogom the Wretched doesn't use his Shadow Word: Pain spell (11639).
- [ ] 29. Jammal'an shouldn't cast Earthgrab Totem (8376) if there is one active.
- [ ] 30. Hex of Jammal'an spell (12480) is quite broken. When player is transformed (has 12480 debuff) he should be friendly to Jammal'an+Ogon and hostile to other party members. While transformed player should act like mind controlled and has no control over his character. Transformed player should chase party members and hits them by melee, while transformed player moves with 50% movement speed but hits for around 1000 melee damage.
- [ ] 31. Spawned Weaver (5720) and Dreamscythe (5721) have no paths. They should move around inner circle where spawned.
- [ ] 32. Weaver and Dreamscythe should have pull formation.
- [ ] 33. Dreamscythe should be hostile.
- [ ] 34. Dreamscythe uses wrong spell: he should use Corrosive Acid Breath (16359) instead of normal Acid Breath.
- [ ] 35. When player is about to complete The Essence of Eranikus (3373) quest there should be question mark above Essence Font gob (14724).
- [ ] 36. Malfurion Stormrage (15362) should spawn after Eranikus is dead.
- [ ] 37. Shade of Eranikus should have "sleep" animation when Jammal'an the Prophet is alive. Also he should be attackable only after the prophet is dead.
- [ ] 38. Avatar of Hakkar event doesn't work. We can't start the event using Yeh'kinya's Scroll (10818) nor Egg of Hakkar (10465) items.
**EDIT: Several issues**
**- Eternal Flames gobs are activated before event starts**
**- Spawns don't attack players**
**- No combat during entire event at all**
**- Doors gobs are still closed after event**
**- Nightmare Suppressors (8497) walk to fast.**
**- One gob is missing, big green star beneath the boss**
**- There is one kind of waves missing, no Hakkari Minions (8437) at all**
**- After p1 when boss should appear nothing happens**
Entire event is recorded here: https://www.youtube.com/watch?v=44e3dJysjfk&t=37s
- [ ] 39. Morphaz (5719) has his path missing. He should move similar to Hazzas.
- [ ] 40. When we pull Shade of Eranikus (5709) his children should pull as well (if alive): Weaver (5720), Dreamscythe (5721), Morphaz (5719) and Hazzas (5722).
- [ ] 41. Weaver and Dreamscythe don't spawn after Jammal's death at all.

### **DONE:**

- [x] 1. Murk Slitherer (5224) doesn't use his Poison spell (13518).
- [x] 2. Fungal Ooze (5235) doesn't use his Venom Spit spell (6917).
- [x] 3. Cursed Atal'ai (5243) doesn't use his Call of the Grave spell (12020).
- [x] 4. Atal'ai Priest (5269) should refresh his Shadow Shield buff (31976) once faded or dispelled.
- [x] 5. Atal'ai Priest interrupts his own Shadow Bolt (9613) cast by casting Heal (11642) spell.
- [x] 6. Kazkaz the Unholy (5401) doesn't use any of his spells: Dominate Mind (7645), Shadow Bolt Volley (14887) and Shadow Word: Pain (11639).
- [x] 7. There is Veyzhak the Cannibal (5399) missing in gps location. It's rare spawn and should have 12h respawn time. For now he's not present in game.
![image](https://user-images.githubusercontent.com/22802214/44948559-be9d5000-ae1f-11e8-8324-879acc9e8919.png)
- [x] 8. Deep Lurkers (8384) are moving extremely fast.
- [x] 9. Deep Lurker should use his Trample spell (5568) more often.
- [x] 10. Saturated Ooze (5228) should use his Summon Oozeling spell (12250) more often, even if there is already spawned Oozeling (8257) around.
- [x] 11. Spawned Oozeling (8257) should start to attack players immediately.
- [x] 12. There should be no perm spawns of Oozelings.
- [x] 13. Atal'alarion (8580) should cast his Sweeping Slam spell (12887) at least 3 seconds after Ground Tremor (6524) casts.
- [x] 14. Atal'alarion is moving to fast.
- [x] 15. Spawn of Hakkar (5708) should use his Acid of Hakkar spell (12280) every 5-8 seconds.
- [x] 16. Hakkari Frostwing (5291) is moving to fast.
- [x] 17. There is Hukku (5715) mini-boss missing in dungeon. He should stay in gps location:
![image](https://user-images.githubusercontent.com/22802214/44948516-e93ad900-ae1e-11e8-883c-dff3a68a6dfc.png)
- [x] 18. Looks like Gasher (5713) doesn't use his Strike spell (15580). He should use it every 3 seconds since its his only ability.
- [x] 19. Spawned Atal'ai Skeleton (8324) should start to attack players immediately.
- [x] 20. Mijan (5717) should cast Thorn Aura spell (8148) once pulled.
- [x] 21. Hukku (5715) shoul cast his Hukku's Guardians spell (12790) once pulled. For now he casts it even when out of combat.
- [x] 22. There should be no perm spawns of Nightmare Suppressors (8497).
- [x] 23. Atal'ai Deathwalker (5271) shouldn't refresh his Shadow Word: Pain spell (11639) on target who already has it.
- [x] 24. Looks like Atal'ai Deathwalker doesn't use his Fear spell (12096).
- [x] 25. When Atal'ai Deathwalker dies he should cast Summon Atal'ai Deathwalker's Spirit (12095).
- [x] 26. Atal'ai Deathwalker's Spirit (8317) should be immune to any damage.
- [x] 27. Atal'ai Deathwalker's Spirit should move really slowly since they should be kited, like 50% of players speed.
- [x] 28. Jammal'an the Prophet (5710) and Ogom the Wretched (5711) should be in pull formation.
- [x] 29. Jammal'an the Prophet should cast his Healing Wave spell (12492) also on Ogom the Wretched.
- [x] 30. Jammal'an should have yell quote at 10% of his hp:
"Jammal'an the Prophet yells: Hakkar shall live again!"
- [x] 31. Hazzas (5722) is moving to fast.
- [x] 32. Shade of Eranikus (5709) shouldn't cast Deep Slumber spell (12890) on target who is tanking him.
- [x] 33. There is  Zekkis (5400) npc missing in gps location. It's rare spawn and should have 12h respawn time. For now he's not present in game. He has also no weapon while he should keep spear in his hands.
![image](https://user-images.githubusercontent.com/22802214/44949345-d977c080-ae2f-11e8-8e78-b43ab8812296.png)
![image](https://user-images.githubusercontent.com/22802214/44949353-f1e7db00-ae2f-11e8-9493-677d504e3f19.png)
- [x] 34. Zekkis should be hostile creature. Zekkis doesn't use both his spells: Curse of Blood (8282) and Contagion of Rot (7102).
- [x] 35. Atal'ai Statues gobs should be activated in specific order, otherwise they should punish players instead of activate. For now we can activate all gobs no matter about succession. Order is pre-established and should follow: 
**South -> North -> South-West-> South-East -> North-West -> North-East**
![image](https://user-images.githubusercontent.com/22802214/44947913-abd14e00-ae14-11e8-8530-3f222dbc07cd.png)
- [x] 36. Atal'alarion (8580) boss should also spawn with Idol of Hakkar gob, of now this boss is perm spawned.
- [x] 37. When Atal'alarion is spawned he should yell:
"My banishment has ended, let the blood flow!"
- [x] 38. There should be only 1 Spawns of Hakkar who patrolls the corridor. For now there are two of them.
 _there are two spawns in every database (LH, sunwell, etc)_
- [x] 39. Forcefield gob (269073) should disappear after all of 6 troll minibosses are dead: 5712, 5713, 5714, 5715, 5716 and 5717. For now there are only 5 minibosses so its hard to check it.
- [x] 40. When Forcefield disappears there should be yell:
"Jammal'an the Prophet yells: The shield be down! Rise up Atal'ai! Rise up!"

**Comment by Kokaina** [comment]
Updated.

**Comment by wilczakadam** [comment]
Currently the instance is impossible to complete. When you jump down to the area with dragonkin (from where you can go towards Jammal'an and Shade of Eranikus) you get randomly hit by invisible mob or something for a lot of damage (you take damage and nothing is visible in combat log) and you randomly get Acid Breath dot on you aswell. Dreamscythe yells something even though you are far away from him, so I assume it might be related to him? Anyways this instance is completely broken beacause of that and you can't complete it because the "invisible mob" nukes down everyone eventually.

**Comment by Wojtyas** [comment]
Dreamscythe won't hit invisible players.

**Comment by Iperyth** [comment]
When you finish The Essence of Eranikus quest and get trinket, you should be able to get next part in cave in Swamp of Sorrows once you equip this trinket. It doesn't appear.
