### ISSUE TITLE
PvP: Blind/6CP KidneyShot into Stealth not possible.

### ISSUE THREAD

**Issue by SlizeTBC** [SunwellWoW/Sunwell-TBC-Bugtracker#2843]
Description: Combat Bug in PvP when Blinding my Enemy or using 6 Combo Points Kidney Shot.

How it works: Easiest way to reset fight is Blinding the Enemy and go Stealth again, somehow it doesnt work sometimes. Same with a Kidney Shot that lasts 6 seconds. There should be a small window to go Stealth again, but it seems that u stay in Combat like when Blinding the Enemy. 

How it should work: As a Rogue you should be able to reset the fight and leave Combat while using Blind or 6 sec Kidney Shot.

**Comment by akrom23** [comment]
@SlizeTBC Any screenshots/proofs?

**Comment by akrom23** [comment]
No response.
