### ISSUE TITLE
Honor Hold Favor - increased reputation gain doesnt work

### ISSUE THREAD

**Issue by RPAncap** [SunwellWoW/Sunwell-TBC-Bugtracker#2847]
Description: 
In honor hold you can buy item alled Honor Hold Favor that will give you 30 minute buff that increases rep gain in hellfire peninsula and hellfire citadel by 25% and experience gain by 5%.

I wasnt able to test it in hellfire peninsula but the rep gain doesnt work in dungeons - atleast in Ramparts.
I am getting the same rep for killing with or without the buff.

How it should work: 
You should get 25% more rep.

Source (you should point out proofs of your report, please give us some source): 
Here are two screenshots showing rep gain with and without buff.
![wowscrnshot_120818_153727](https://user-images.githubusercontent.com/44553524/49687527-77041f80-fb04-11e8-8413-0a22af750fc0.jpg)
![wowscrnshot_120818_155911](https://user-images.githubusercontent.com/44553524/49687529-79667980-fb04-11e8-9406-33e5bf5a1426.jpg)

**Comment by notsofamous** [comment]
same with thrallmar's favor

**Comment by Elefant0n** [comment]
Bump, Fix this ASAP please.
