### ISSUE TITLE
Defender Ashoon and Defender Ursi stack on each other

### ISSUE THREAD

**Issue by kieran1188** [SunwellWoW/Sunwell-TBC-Bugtracker#2850]
Defender Ashoon( npc=18032) and Defender Ursi (npc=18022) are stack on each other/

I have check wow-head and i have found the coords for their correct position

Coords

https://www.wowhead.com/npc=18032 - Defender Ashoon - 55.2/52.2
https://www.wowhead.com/npc=18022 - Defender Ursi - 55.2/52.4

![wowscrnshot_120818_152519](https://user-images.githubusercontent.com/38033595/49687650-fb06d900-fafd-11e8-90df-3636be745c54.jpg)

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
