### ISSUE TITLE
Nodes/Herbs in dungeons

### ISSUE THREAD

**Issue by mintnb** [SunwellWoW/Sunwell-TBC-Bugtracker#2851]
Description: 
Last night I did a quick Slave Pens normal. While clearing the dungeon the rich adamantite nodes respawned few times. They are supposed to be either one per dungeon or on long enough cd that abuse is prevented. Same issue applies to herbs there.
P.S.: I have noticed that the nodes in Outland spawn way too often. Also Khorium nodes are supposed to be rare form of the other nodes and appear randomly on their location like gold/silver/truesilver ones.

**Comment by Avishai97** [comment]
Primal Earth is on 2 gold before most people ding 70 if that isn't proof enough that there is too much nodes in Outland i don't know what is

**Comment by 0vertime** [comment]
They shouldn't respawn.

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
