### ISSUE TITLE
Argent Dawn reputation rewards

### ISSUE THREAD

**Issue by 0vertime** [SunwellWoW/Sunwell-TBC-Bugtracker#2855]
**Description:** 
Argent Dawn reputation quartermaster is selling some items without requirements.

**How it works:** 
Currently you can buy without reputation requirement:
- Flame Mantle of the Dawn
- Frost Mantle of the Dawn
- Arcane Mantle of the Dawn
- Nature Mantle of the Dawn
- Shadow Mantle of the Dawn
- Chromatic Mantle of the Dawn

**How it should work:** 
Following reputation requirement should be in effect:
- Flame Mantle of the Dawn (Revered)
- Frost Mantle of the Dawn (Revered)
- Arcane Mantle of the Dawn (Revered)
- Nature Mantle of the Dawn (Revered)
- Shadow Mantle of the Dawn (Revered)
- Chromatic Mantle of the Dawn (Exalted)

**Source:** 
https://i.imgur.com/rYkjXd2.png

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
