### ISSUE TITLE
Mote of fire from mining

### ISSUE THREAD

**Issue by frittfaen** [SunwellWoW/Sunwell-TBC-Bugtracker#2857]
Description: 

Seems to drop way to much from mining 
How it works: 
1-2 often every ore, and ores are plenty, so this fucke economy. 

How it should work: 
should be way lower, not sure exactely, maybe 5%

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
