### ISSUE TITLE
Items Sold Out that shouldn't be

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2860]
Description: 
There are multiple food items on Inkeeper Shyria in Feathermoon Stronghold in Feralas that are sold out. I could be wrong, but I do not believe these items are supposed to be able to sell out.

How it works: 
Food sold out.

How it should work: 
Shouldn't sell out.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/1epqK7d

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
