### ISSUE TITLE
Valentine's Event Items for sale from Inkeepers

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2862]
Description: 
I've noticed some Inkeepers sell the cologne and perfume items for the Valentine's event. I know this is common on private servers, it was even on Elysium.

How it works: 
Holiday items for sale year round.

How it should work: 
The items should only available during the event.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/IOJbhOf

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
