### ISSUE TITLE
[Normal] Broggok Poison Cloud

### ISSUE THREAD

**Issue by nennx** [SunwellWoW/Sunwell-TBC-Bugtracker#2866]
Description: Broggok's poison cloud is initially invisible and has large radius

How it works: When Broggok's poison clouds first spawns the radius seems to be larger than it should be and cannot be seen. 

How it should work: The poison cloud should start small and increase in size and be visible.

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=w2aSJlB0ZLs is a retail video. Its hard to prove the radius is large on spawn though since its invisible on this server.

**Comment by nennx** [comment]
Seems similar to https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/649 

In my opinion, the radius on the fire seemed excessive when they were invisible as well, but I can't really prove it.

**Comment by Wojtyas** [comment]
Fixed, will be implemented with next update.
