### ISSUE TITLE
Sometimes using food just consumes it and doesn't give you the eating buff.

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2869]
Description: 
Sometimes using food just consumes it and doesn't give you the eating buff. I can upload a video later today.

How it works: 
Sometimes using food just consumes it and doesn't give you the eating buff.

How it should work: 
You should always get a food buff when you use it and stand still.

Source (you should point out proofs of your report, please give us some source):

**Comment by Nelthalor** [comment]
I think I used nvidia shadowplay on a couple instances earlier, I will try to upload it later.

**Comment by koostosh** [comment]
Could not reproduce.
