### ISSUE TITLE
Mobs in sunwell get right under me when I attack

### ISSUE THREAD

**Issue by leahnie956** [SunwellWoW/Sunwell-TBC-Bugtracker#287]
Decription: 

Mobs in sunwell get right on under me when I attack
How it works: 
keep a little distance away

How it should work: 
keep a little distance away

Source (you should point out proofs of your report, please give us some source): 
![snsrtnsrn](https://user-images.githubusercontent.com/25886407/44959782-14bed180-aeba-11e8-95c9-454c62f1e006.jpg)

**Comment by Kokaina** [comment]
I believe Lukaasm was working on that in recent days. Soon, he should finish enemies positioning around player.

**Comment by Nadiirr** [comment]
This was fixed. Please retest.
