### ISSUE TITLE
Skinning doesnt give item

### ISSUE THREAD

**Issue by someweirdhuman** [SunwellWoW/Sunwell-TBC-Bugtracker#2870]
Description: 
Skinning doesnt give item

How it works: 
When you shift skin mob (auto loot) and your inventory is full item wont be given to you, and you wont be able to skin or loot the item again, it will disappear.

How it should work: 
Skin mob, loot item -> error, inventory is full. Throw something away skin/loot mob again

Source (you should point out proofs of your report, please give us some source): 

edit: tried to repeat it, couldnt do it consistently

**Comment by neheri** [comment]
It's bugged now. You can get multiple skinning skills from a single mob. 

1. Skin a mob.
2. Don't loot the skin.
3. Skin it again.

Abusable
