### ISSUE TITLE
Prayer of Fortitude not buffing pets

### ISSUE THREAD

**Issue by imchaotic** [SunwellWoW/Sunwell-TBC-Bugtracker#2871]
Description: 
Casting Prayer of Fortitude on a party member does not buff hunter pets. Even casting directly on the pets does not give the pets buffs.

How it works: 
Buff any member of a group (including pets) with Prayer of Fortitude, Prayer of Spirit, or Prayer of Shadow Protection, and hunter pets in that group do not get the buffs. More so, if a hunter pet is the target, nobody in the group gets buffed AND the hunter pet does not get bufffed. I cannot find a way to make hunter pets get the group buffs.

How it should work: 
Buff any member of a group (including pets) with Prayer of Fortitude, Prayer of Spirit, or Prayer of Shadow Protection, and all members of that group and all pets in that group should be buffed.

Source (you should point out proofs of your report, please give us some source): 
Broken for Hunters:
https://youtu.be/NBb1pqvSy3Y

Works for Warlocks:
https://youtu.be/cgwFwkWn5gE

**Comment by akrom23** [comment]
You cannot buff pet with this kind of aura. This is protection from doubled stamina: once from buff and second from owner's scaling bonus.
