### ISSUE TITLE
Murkblood Scavengers aren't spawning

### ISSUE THREAD

**Issue by waterloorick** [SunwellWoW/Sunwell-TBC-Bugtracker#2875]
Description: There is one spot where they spawn

How it works: 

How it should work: They spawn through the village and not just on the circle

Source (you should point out proofs of your report, please give us some source):

**Comment by waterloorick** [comment]
A video https://www.youtube.com/watch?v=KyHcL0w-MRk

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
