### ISSUE TITLE
Chen's Empty keg

### ISSUE THREAD

**Issue by apachesa** [SunwellWoW/Sunwell-TBC-Bugtracker#2876]
Description: 
Chen's empty keg

How it works: 
Loot the keg. Doesn't recieve item

How it should work: 
You should get the item

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/QbTgxCZ

**Comment by Dootz** [comment]
Works fine for me. Can look item without problems, then it despawns and respawns after 10 seconds.
