### ISSUE TITLE
Middle Banker in Ironforge missing

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2877]
Description: 
Middle Banker in Ironforge missing, I have noticed they have been gone for a couple of days.

How it works: 
Middle Banker in Ironforge missing.

How it should work: 
Should be there.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/YUgWgBE

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.

**Comment by Nelthalor** [comment]
No problem :)
