### ISSUE TITLE
Can't cast spells from travel form//Incorrect response error

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#2880]
Description: When casting rejuvenation from travel form, the game tells you "you cannot attack that target" instead of shifting out to cast the spell on yourself.

How it works: When casting rejuvenation from travel form, the game tells you "you cannot attack that target" instead of shifting out to cast the spell on yourself.

How it should work: It should perform like a dismount, the game should unshift you and cast the spell, I bet lifebloom has the same issue.

Source (you should point out proofs of your report, please give us some source): There is a built in auto dismount in tbc, every other spell works in this form to cast excluding rejuv (and lifebloom).

**Comment by akrom23** [comment]
Works fine.
