### ISSUE TITLE
Corrupted Sabers

### ISSUE THREAD

**Issue by aDegn** [SunwellWoW/Sunwell-TBC-Bugtracker#2885]
Description: 
Cat should follow me back and let me release it to complete quest.

How it works: 
Cat follows me back but I cant complete quest
How it should work: 

Cat follows me back and I click it to complete quest
Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120818_222650](https://user-images.githubusercontent.com/45721681/49690894-653c6f80-fb38-11e8-870c-2f438e9e582e.jpg)

**Comment by Azathothh** [comment]
#885
