### ISSUE TITLE
Resetting talents does not make passives active when you spend talent points.

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2886]
Description: 
Resetting talents does not make passives active when you spend talent points. 

How it works: 
I relearned my talents and the 5% crit from Fury is not appearing on my character pane.

How it should work: 
Your talent passives should always be working.

Source (you should point out proofs of your report, please give us some source):

**Comment by Nelthalor** [comment]
I relogged to see if that would fix it, and no. Then I exited and got back in and it's still missing.

**Comment by Nelthalor** [comment]
It randomly activated when I was walking from Feathermoon Stronghold to the naga island south of there. But closing the game and phasing from the boat across the continents did not cause it to activate.

**Comment by Nelthalor** [comment]
I think it is a bug for Cruelty. It did the same issue the next time I reset talents, but Deflection did not.

**Comment by akrom23** [comment]
Works fine.
