### ISSUE TITLE
Quest Shutting DownManaforge Duro cant be accepted

### ISSUE THREAD

**Issue by philippe284** [SunwellWoW/Sunwell-TBC-Bugtracker#2887]
Description: 
After finishing the previous Quest, the followup quest called: Shutting Down Manaforg Duro, cant be found or accepted. (Aldor)

How it works: 
After turning the previous quest in, the followup quest doesnt appear

How it should work: 
The followup queest should appear

Source (you should point out proofs of your report, please give us some source): 
I talked to tide about it and we couldt figure out where the problem is

**Comment by JuhaLintunen** [comment]
I had the same issue, and found out that you need a prequest from Aldor bank in Shattrath, do that quest line, and you will get Manaforge Duroo quest a little later :)
