### ISSUE TITLE
Netherstorm: dimensius the all-devouring

### ISSUE THREAD

**Issue by thearmo** [SunwellWoW/Sunwell-TBC-Bugtracker#2888]
Description: After killing the boss, me and my group did not get any credit

How it works: killed the boss but no credit and nothing happened

How it should work: kill the boss and get credit

Source (you should point out proofs of your report, please give us some source):

**Comment by JuhaLintunen** [comment]
You did too little damage to the mob, cause the NPCs were helping you probably. Need to do half of the mob's health in order to get credit, can confirm.
