### ISSUE TITLE
Automatically retrieved item

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#289]
Decription: 
When an item is automatically retrieved it's sent to a player through the mail. If it's a BoP item they player cannot retrieve it.

How it works: 
When you click on the item it gives an error stating "That item doesn't belong to you."

How it should work: 
You should still be able to retrieve BoP items through the mail.

Source (you should point out proofs of your report, please give us some source):

**Comment by Nadiirr** [comment]
Same as #524 
Closing.
