### ISSUE TITLE
[NPC] Antu'sul

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#2890]
Description: 

Mob spawns 6-8 basilisks at once
How it works: 
Descripton

How it should work: 
He should have one summoned before the fight, and summon next one every 15 sec. He is unkillable with 6 spawning at once

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.
