### ISSUE TITLE
Tar Beast/Creeper disarm Spam

### ISSUE THREAD

**Issue by Bakster15** [SunwellWoW/Sunwell-TBC-Bugtracker#2892]
Description: 
Whenever the disarm falls off it's reapplied instantly. By the same mob.

How it works: 
100% disarm 24/7

How it should work: 
It should disarm a lot less frequently.

Source (you should point out proofs of your report, please give us some source):

**Comment by 0vertime** [comment]
#2628

**Comment by Nabis1** [comment]
Still spam 24/7 Disarm
