### ISSUE TITLE
Steady Shot not scaling from attack speed properly

### ISSUE THREAD

**Issue by primeropein** [SunwellWoW/Sunwell-TBC-Bugtracker#2894]
Description: 
Steady shot is not scaling properly with ranged attack speed

How it works: 
The base cast time for Steady Shot is 1,5 when Quiver (15%) + Talent (20%) it get 1,224

How it should work: 
The base time 1,5 should be divided by the quiver and the talent %, so the formula would look like this for this certain situation
1,5/1,2 = X (Your attackspeed with talent ONLY) Then X/1,15 (Quiver AND Talent) Which should give u the Steady Shot speed of 1,0869.... 

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Steady_Shot
You can see here even those they changed to base attack speed of the Steady Shot to 2 sec , the formula they use is still the same, Also if u have the TBC spreadsheet it also shows you that this is the way both Auto Shot speed (which ironicly you have using this formula already) And Steady Shot cast time should be.

**Comment by mintnb** [comment]
Steady shot should benefit from the serpent's swiftness talent in the bm tree as well

**Comment by primeropein** [comment]
Well the 20 % im writing about is the talent serpent swiftness

**Comment by akrom23** [comment]
@primeropein This is the formula:
Base cast time is 1 sec.
With Quiver (10%) - it's 0,9 sec
With Quiver nad Talent 5/5 (20%) - it's 0,75 sec.

Then the extra 0.5 sec is added - so it's 1,25 sec.

**Comment by primeropein** [comment]
@akrom23 that is wrong
Base Cast Time of Steady is 1,5 sec
Wrath of the Lich King Patch 3.0.2 (2008-10-14):
Now uses ammo. In result, its bonus damage has been slightly reduced. Players can notice a damage increase based upon what ammo they use.
Now has a 2.0 cast time, up from 1.5.
https://wow.gamepedia.com/Steady_Shot
Which means in TBC it had 1,5 and in Wotlk it got 2

Quiver (ammo pouch) is 15 % when u have the best one http://db.hellfire-tbc.com/?item=29143
The talent is 20%
And as u can read on the Wiki the formula for steady shot goes like this
1,5/(1+x) = y
x= Haste increase
y= Cast time
For every new X you need to do the equation again
Proof: http://wowwiki.wikia.com/wiki/Steady_Shot READ THE FORMULA PLEASE
https://imgur.com/a/Gw8uaKb
ALSO proof from Cheekys Spreadsheet which is BLIZZLIKE TBC:
https://imgur.com/a/dBJzd1O

ALSO proof from Warmane (Yes private server but was flawless hunter wise) ALSO pay attention to the Auto Swing while ure at it as "Hunter Auto Shot getting delay after every swing #2326" is also shown here
0 Haste
1,5 Base
Quiver 15%
Talent 20%
https://youtu.be/2TO3W1yQnQQ

So in this example you start with steady shot base which we can confirm is 1,5. You then add the talent first which is 20% and if we use the formula above.
1,5/(1+0,2) = 1,25 --- the 0,2 equals to 20%
THEN you add the quiver to ur new cast speed which would give u:
1,25/(1+0,15)=1,0869565217391304347826086956522

Please this is GAME BREAKING im giving you all the proof here this has to fixed soon 
OBS the 0,5 sec timer from auto does NOT effect your steady shot cast time there is NO 0,5 + on steady shot cast time, I have no idea where u got that from
If you still dont understand this then please add me on discord so we can talk about this, really need to fix this.  Cheqi#1506

**Comment by primeropein** [comment]
Even more proof : https://www.youtube.com/watch?v=BT270SIJtLY retail hunter showing his Steady shot is at approx 1 sec cast time as BM without any haste effect , and there is not many items that gives haste that would make it to go to 1,25 to 1.

**Comment by Zarant** [comment]
Just use cheeky's spreadsheet as a reference, go to the shot rotation tab and see the formula they used for steady shot cast time:
https://web.archive.org/web/20081004051530/http://elitistjerks.com:80/f31/t9816-hunter_spreadsheets_--_development/
I don't believe the EJ neckbeards from 2007-2008 would get that formula wrong.

A small snippet of the spreadsheet calculations using a 3.0 speed weapon, standard BM spec and no haste from gear:
![cs1](https://user-images.githubusercontent.com/26726709/49939619-7bde2000-fec4-11e8-832a-4f2dcd9589b7.png)

Total haste = 1.15*1.20 = 1.38
Steady cast time = 1.5/1.38 = 1.09

**Comment by Jonsbe** [comment]
No questions needed, just fix this and autoshot being lagged by ms to server<3

**Comment by MiekZer** [comment]
"Then the extra 0.5 sec is added - so it's 1,25 sec."
What the fuck is this +0.5s added. Did you ever fucking played TBC on any fucking well scripted private server because obviously you didn't even play it on retail.

**Comment by akrom23** [comment]
@MiekZer I just wrote what is in the code right now.

**Comment by MiekZer** [comment]
Then your code is wrong. End of the discussion.

**Comment by YoshGit** [comment]
Any word on this? Seems like the fix for this critical hunter bug should be pretty simple.

**Comment by akrom23** [comment]
@MiekZer It's not my code - this formula is used by many emulators.
