### ISSUE TITLE
Netherstorm: Electro-shock goodness!

### ISSUE THREAD

**Issue by thearmo** [SunwellWoW/Sunwell-TBC-Bugtracker#2896]
Description: When you use the potion the quest gave you, it zaps the target making him weaker and it is supposed to split the target into around 8 mobs but instead it just zaps the 1 target and makes him weaker, meaning you have to kill 30 mobs instead of zapping 5 mobs and finishing the quest quicker.

How it works: zap the target with attacks, weakening 1 mob and killing him for credit.

How it should work: zap the target with attacks, weakening 1 mob and splitting it into about 6-8 little mobs which all give you credit.

Source (you should point out proofs of your report, please give us some source):

**Comment by netherneth** [comment]
can confirm this one. killing 60 mobs instead of 10 is annoying

**Comment by ZaoQ** [comment]
Still doesnt work

**Comment by AWIDIUS** [comment]
Still bugged

**Comment by rychersky** [comment]
Still bugged, should be spawning 7-10 small globlues per large ooze; is only spawning 1.

https://www.wowhead.com/npc=20806/seeping-sludge-globule#comments

Also, you are kept in combat after killing these until you run a certain distance away. The combat status will toggle on and off while this is occurring, going back and forth every half second.
