### ISSUE TITLE
Entangling roots should NOT share DR with feral charge

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#2897]
Description: 
Feral charge is sharing DR with entangling roots

How it works: 
the issue is that the immobilize from Feral Charge is in the wrong diminishing returns category. It's currently in the "controlled root" category together with entangling roots and things such as frost nova

How it should work: 
They should be on seperate DR's

Source (you should point out proofs of your report, please give us some source): 
http://www.youtube.com/watch?v=hS82JzE6F0I&feature=player_detailpage#t=351s

05:55 the rogue gets rooted by Nature's Grasp and now has controlled root DR for 15 seconds. at
06:00 the druid feral charges and applies Feral Charge immobilize debuff, at
06:04 the debuff fades. Which means even though the rogue still had Controlled Root Dr for 10 more seconds when the immobilize was applied the immobilize was still full duration. Clearly they are on different DRs.

**Comment by Klimpb** [comment]
Feral charge is its separate thing, it doesn't DR with anything, not even with itself.
Proof: 
https://youtu.be/PYWw7e97bmw?t=854
https://youtu.be/PYWw7e97bmw?t=1386
https://youtu.be/PYWw7e97bmw?t=1607

Conclusion: feral charge should not belong in any DR category at all, should also not DR with itself.

**Comment by Klimpb** [comment]
@Dootz

**Comment by Dootz** [comment]
yeah I know. I try do do my own reseach before fixing things :) . should be fixed & live now

**Comment by Wojtyas** [comment]
Fixed & implemented.

**Comment by baade123** [comment]
feral charge is now breaking on damage.... yikes
