### ISSUE TITLE
Rogue: Slice and Dice

### ISSUE THREAD

**Issue by VashetSunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#29]
Decription: 
Slice and Dice 

How it works: 
23% attack speed increase

How it should work: 
Tool tip reads 30% increased attack speed

Source (you should point out proofs of your report, please give us some source): 
Tested with unarmed 2.00 speed lowered to 1.54. Shard of azzinoth 1.9 to 1.46 and vengeful glad shanker 1.8 to 1.38, warglaive of azzinoth 2.8 to 2.15

**Comment by akrom23** [comment]
Tested and works good.
