### ISSUE TITLE
[NPC] Attack animations

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#290]
No NPC currently uses their weapon when they fight. They hit with their fists and sheaths/unsheaths their weapon between each hit. The only exeption is faction guards, like the ones guarding cities or quest hubs. They still use their fists but don't sheath their weapons between each hit. 

Stormwind guard:
https://i.gyazo.com/4eeb875c9d6dc39ac127d842238f47a2.mp4
Dual wield mob:
https://i.gyazo.com/f754bb0f8d00a808b12c7dc0886d12e3.mp4
2h mob:
https://i.gyazo.com/01155ecca133c9992d390224dc1007a4.mp4

**Comment by Kokaina** [comment]
I was about to post it :P Discovered that on brd:

- [ ] 1. Ambassador Flamelash (9156) has quite weird behaviour. During time between his autoattacks his weapon disappears but when he's about to hit it appears. Screens below.

**EDIT: Seems to be core bug. Just realized many of creatures act like that.**

![image](https://user-images.githubusercontent.com/22802214/44909382-63843400-ad1f-11e8-886a-389c5d090501.png)
![image](https://user-images.githubusercontent.com/22802214/44909397-73037d00-ad1f-11e8-94ab-6708b36c7bc0.png)

**Comment by Kokaina** [comment]
Seems to work after recent updates.
