### ISSUE TITLE
Ressurection Sickness Durability

### ISSUE THREAD

**Issue by Bakster15** [SunwellWoW/Sunwell-TBC-Bugtracker#2900]
Description: 
All items in my bag lost 25% durability from Ress Sickness. Including two rare weapons I looted earlier which I never wore and are still BOE. 

How it works: 
All gear in bag looses durability. Including BOE's.

How it should work: 
All equipped gear should loose 25% durabillity

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/45540647/49691672-e3544280-fb47-11e8-8a39-ce7a7113e749.png)

**Comment by ghost** [comment]
>>Spirit Healers are able to resurrect players at the cost of 25% durability loss to all items (both equipped and in inventory) at the graveyard where they are found.

http://wowwiki.wikia.com/wiki/Spirit_Healer?oldid=2509921

Also ingame...

![image](https://user-images.githubusercontent.com/1936487/49691921-e719a200-fb12-11e8-8458-a12b77f3e54c.png)

**Comment by Gelori** [comment]
works as intended
