### ISSUE TITLE
[item][disenchant] Unable to disenchant 

### ISSUE THREAD

**Issue by Zamesi** [SunwellWoW/Sunwell-TBC-Bugtracker#2902]
Description: 
Unable to disenchant crafted items that should be disenchantable

How it works: 
Items Rough Bronze Boots and Runed Copper Belt can not be disenchanted.

How it should work: 
They should be disenchantable.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120918_013737](https://user-images.githubusercontent.com/45551496/49691834-cfaed900-fb53-11e8-9c21-869e6c1bf9a7.jpg)
![wowscrnshot_120918_013732](https://user-images.githubusercontent.com/45551496/49691835-cfaed900-fb53-11e8-83b6-999362b0d95d.jpg)

**Comment by Zamesi** [comment]
Found one more: Rough Bronze Shoulders
![wowscrnshot_120918_115209](https://user-images.githubusercontent.com/45551496/49695827-4c1fd700-fba9-11e8-80c0-d1663207374a.jpg)

**Comment by Zamesi** [comment]
oops closed it by accident because I'm new to Git, sry :)

**Comment by Zamesi** [comment]
Tried to delete cache and disable addons with no effect. Also
found one more. Also dug out those item id:s for you:
6350
2857
3480
2866
![wowscrnshot_120918_185638](https://user-images.githubusercontent.com/45551496/49700393-75ab2380-fbe6-11e8-8ba1-c8acbb75097b.jpg)

**Comment by akrom23** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2479
