### ISSUE TITLE
Mage Abilities CoC and Clear Casting

### ISSUE THREAD

**Issue by sabo92** [SunwellWoW/Sunwell-TBC-Bugtracker#2904]
Description: Cone of Cold and clear casting

How it works: 
Cone of Cold - sometimes it do not hit the target in front of you. 

While doing Blizzard with a clear casting proc up, You need to move your char in any direction to make the Free cast go off, els it worn't trigger the clear casting fra the arcane talent.

How it should work: 

CoC should hit targets you are facing.

Blizzard should trigger the clear casting from the arcane talent tree even IT is up, even og tour are standing still casting.

Source (you should point out proofs of your report, please give us some source): Works like that all expansions.

**Comment by mechanical998** [comment]
Yes, I faced the same issues. I played mages all the time, and realized the same CoC issue that won't hit the mobs in front of u all the time especially when you doing CoC aoe grinding which is really annoying.

**Comment by mechanical998** [comment]
If CoC not fixed, the Cone of Cold is almost a trash spell, which will be removed from tab.

**Comment by akrom23** [comment]
Keep in mind:
https://wow.gamepedia.com/index.php?title=Cone_of_Cold&oldid=1432387

> The area of effect is a 90 degree arc region

``
While doing Blizzard with a clear casting proc up, You need to move your char in any direction to make the Free cast go off, els it worn't trigger the clear casting fra the arcane talent.
``
Cannot reproduce it.

**Comment by akrom23** [comment]
No response.
