### ISSUE TITLE
Nekrum Gutchewer

### ISSUE THREAD

**Issue by Vartonis** [SunwellWoW/Sunwell-TBC-Bugtracker#2906]
Description:  Nekrum Gutchewr doesn't drop any loot

How it works: He currently drops no boss loot, and he should. In ZF

How it should work: He should have a loot table. 

Source (you should point out proofs of your report, please give us some source): http://classicdb.ch/?npc=7796

**Comment by babno** [comment]
Also doesn't drop the quest item Nekrum's medalion
