### ISSUE TITLE
Blind is a physical debuff, should be poison

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#2908]
Description: blind is a physical debuff

How it should work: should be poison and therefor removable via cleanse, abolish, stoneform, etc.

Source (you should point out proofs of your report, please give us some source): https://wow.gamepedia.com/Blind

**Comment by TheRealestMcCoy** [comment]
Patch 2.3.0 (2007-11-13): Blind is now a physical (no longer a poison) attack. [Reagent] requirement removed. Now shares the same diminish category as  [Cyclone] and is now diminished in PvE as well as PvP. 
Previously blind was a nature attack like poison.  [Blinding Powder] is now a Grey-quality item ("vendor trash") which can sometimes be found in lockboxes obtained through Pickpocketing. There is a tooltip on the item that explains why Blind no longer needs a Reagent: "Once favored by rogues as a blinding agent, it was abandoned for more readily available resources... like dirt."

**Comment by babno** [comment]
Yes, and as a progressive server it should eventually be a physical debuff but for now we're in 2.0 and it should be poison for the first seasons of arena just as it was in retail.

**Comment by kinglobster** [comment]
yes its progressive server give items with 2.0 values, how about no. close this clowny ticket smh

**Comment by babno** [comment]
So because they jumped forward one patch for items is reason to jump forward 3 patches/more than a year for blind? And pve gear isn't really a good comparison to a class ability.

**Comment by ZaoQ** [comment]
You could also cast two ice blocks in a row, wanna implement that too?

**Comment by babno** [comment]
@ZaoQ Yes, I do until 2.1 when hypothermia was added.

**Comment by SunwellTracker** [comment]
We're on 2.4.3 talents/spells patch.
