### ISSUE TITLE
[Druid] Nature's Swiftness

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#291]
Decription: 
Nature's Swiftness is currently consumed on spell hit rather than spell cast.

How it works: 
If you cast a spell with a travel time like Wrath it won't be consumed until it hits the target.

How it should work: 
It should be consumed immediately after the spell is cast.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/hYh7Cvcdr9k?t=1m28s

**Comment by Patrulek** [comment]
It's only visual bug. Same as #27
