### ISSUE TITLE
Nexus-King Salhadaar

### ISSUE THREAD

**Issue by Moobe123** [SunwellWoW/Sunwell-TBC-Bugtracker#2910]
Description: Nexus-King Salhadaar quest

How it works: 
Nothing happends when you are using the orbs

How it should work: 
When activating the orbs the boss should brake free and start the encounter

Source (you should point out proofs of your report, please give us some source): 
Reference; https://www.youtube.com/watch?v=v98n3AvORfc

**Comment by Kanibar** [comment]
Can confirm, having the same issue

**Comment by Xymos** [comment]
Still not working. This is an important quest. Fix please...

**Comment by Azathothh** [comment]
Can be completed, but have some issues. https://www.youtube.com/watch?v=HvPQjQZ707g
There are no visual effects showing which force field is active - also we can engage Salhadaar by using Protectorate Disruptor 3 times even in same place (no matter near which object we're standing)
