### ISSUE TITLE
[Hunter] Improved Mend Pet not removing debuffs

### ISSUE THREAD

**Issue by Piglover88** [SunwellWoW/Sunwell-TBC-Bugtracker#2913]
Description: 
Hunter talent Improved Mend Pet is not removing debuffs properly. You can test this easily in Western Plaguelands at Gharron's Withering where they debuff your pet. The system message says it's removed, you can see the effect proc on the pet but the debuff is still there.

How it works: 
Pet debuffs not always cleared from Improved Mend Pet

How it should work: 
Debuffs should be removed when it procs.
![wowscrnshot_120818_185500](https://user-images.githubusercontent.com/45605745/49692037-f6521d00-fb1d-11e8-9108-528f6696e12c.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by TheRealestMcCoy** [comment]
Currently i see 2 stacks did it have 3 it does not clear all the stacks its 1 at a time.

**Comment by Piglover88** [comment]
It had 2 stacks

**Comment by akrom23** [comment]
Works fine.
![wowscrnshot_012219_140659](https://user-images.githubusercontent.com/1035215/51537491-07958580-1e4f-11e9-8021-d922adca7144.jpg)
