### ISSUE TITLE
Inner focus 

### ISSUE THREAD

**Issue by dadkinse** [SunwellWoW/Sunwell-TBC-Bugtracker#2915]
Description: 
As soon as you use inner focus and you cast a spell you want to, the inner focus is greyed out and never go out of cooldown. The buff goes away but you cannot cast the spell again. When you relog, it fixes the issue.

How it works: 
See description

How it should work: 
You should be able to cast it again after cooldown

Source (you should point out proofs of your report, please give us some source): 
![billede](https://user-images.githubusercontent.com/21084363/49692167-2d432580-fb54-11e8-9d7d-e9e7c840ecd3.png)

**Comment by Gotemniggadro** [comment]
This is a thing

**Comment by akrom23** [comment]
@Dadeerh What spell did you cast? Some macro?

**Comment by akrom23** [comment]
No response.
