### ISSUE TITLE
[Quest] Deadwood Ritual Totem bugged

### ISSUE THREAD

**Issue by Piglover88** [SunwellWoW/Sunwell-TBC-Bugtracker#2924]
Description: 
Once you get the quest from the drop you can't turn it in even when you have the appropriate rep.

How it works: 
Once you accept the quest and go to the NPC your cursor still has a sword icon over it even when you have the appropriate rep. You can't tell in the screenshot because the cursor disappears but the mob is considered "attackable" making it impossible to turn in the quest.

How it should work: 
https://www.wowhead.com/quest=8470/deadwood-ritual-totem

![wowscrnshot_120818_214004](https://user-images.githubusercontent.com/45605745/49692949-88fdb680-fb34-11e8-8df9-2bc18371c677.jpg)

**Comment by 0vertime** [comment]
Click "at war" twice.

**Comment by Piglover88** [comment]
Damn good catch there I didn't even realize that hah
