### ISSUE TITLE
Thorim Settings

### ISSUE THREAD

**Issue by janexlolz** [SunwellWoW/Sunwell-TBC-Bugtracker#2925]
Description: JC Thorium Settings

How it works:  Consumes 3 thorium bars to craft,

How it should work: Should consume just 1 thorium bar.

Source (you should point out proofs of your report, please give us some source):

**Comment by jbwilson11** [comment]
This is a duplicate of https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2519
