### ISSUE TITLE
fenzied pterrordax and pterrordax in ungoro hit 6 times in 1 hit

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2932]
Description: 
fenzied pterrordax and pterrordax in ungoro hit 6 times in 1 hit

How it works: 
fenzied pterrordax and pterrordax in ungoro hit 6 times in 1 hit

How it should work: 
Shouldn't hit so many times.

Source (you should point out proofs of your report, please give us some source):

**Comment by ZaoQ** [comment]
Already reported

**Comment by Nelthalor** [comment]
I just report what I or my guildies find (since most of them complain and don't report).
