### ISSUE TITLE
Pet Defensive Stance

### ISSUE THREAD

**Issue by tjmitchell1** [SunwellWoW/Sunwell-TBC-Bugtracker#2938]
Description: 
The Defensive "posture" for hunter pets (and most likely warlock pets as well) is not working properly. in two ways:
1. Once a mob aggros the player, the pet will instantly attempt to attack the target, not wait on the mob to hit the player.

How it works: 
1. The pet attacks mobs aggroed to the player too early.

How it should work: 
1. The pet should only attack mobs once the player (or it) is dealt damage.

Source (you should point out proofs of your report, please give us some source): 
1. On wowwiki: "A pet in defensive mode will NOT attack a mob simply for aggroing on its master. The mob must hit (or attempt to hit) its master before the pet will attack, unless it is ordered to attack."

**Comment by Zamesi** [comment]
Came here  to report this. I am also certain pets on defensive are supposed to engage only when damage is dealt to it or it's owner. Pet aggro is also not triggered by dodges, misses and parries. I am not sure about full resists, but it would make sense that those don't trigger it either.
