### ISSUE TITLE
sanc aura decreasing damage

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#2939]
This is a bit convoluted so sorry if confusing. I am a ret paladin with 2h spec, so my char sheet damage says I have a 106% modifier, which goes to 108% if I have my improved sanctity aura up. I was recently in a group with a higher level ret paladin who did not have improved sanctity, and his overwrote mine (probably because the higher level).

Now what was weird was my damage went DOWN to 105%. If I ranged the aura it went back to 106 (108 if I had sanc on). This happened regardless of what aura I had on, and if he switched from sanc to another aura then my damage would go up as well.

**Comment by Delfury** [comment]
You lost 1% of your 2-h bonus when under his Sanctity Aura?

**Comment by babno** [comment]
Correct

**Comment by akrom23** [comment]
I don't see a bug here. Just tell me him to turn off his aura.
The first casted aura will be applied on group members and it's not overriden because of paladin's level.
If you cancel your improved aura then his aura is applied.

**Comment by babno** [comment]
Upon reflection I don't think me being a ret with improved sanc aura was relevant.

Let's say you as a random rogue/warrior/whatever deal 100 damage every weapon hit by yourself. Suddenly a paladin with unimproved ret aura joins the group, and now you are dealing 99 damage every weapon hit, because his sanc aura reduces your damage.

**Comment by akrom23** [comment]
This aura (even unimproved) DO NOT reduce damage - I don't know what you're talking about.

**Comment by babno** [comment]
It certainly isn't supposed to, though at the time of writing this bug report it did. I haven't seen it since though it's rare indeed to find people with just unimproved sanc aura.

**Comment by akrom23** [comment]
I tested locally and it worked fine.
