### ISSUE TITLE
Hunter Pet Trainer will not unlearn your pets' abilities

### ISSUE THREAD

**Issue by whitestar87** [SunwellWoW/Sunwell-TBC-Bugtracker#2940]
Description: 
Pet trainers do not offer the option to unlearn your pets abilities.

How it works: 
when interacting with a pet trainer they would have a dialogue option to unlearn your current pets abilities, allowing you to reteach them from the pet training window.

How it should work: 
It cost a fee but you could respec your pet if you wanted to switch his abilities.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/forums&topic=10283

Wowhead comment from patch 2.2.3 saying pet trainers could unlearn your pets abilities

**Comment by TheRealestMcCoy** [comment]
https://gyazo.com/b37b972350f77b13fae98d7b16135d86
https://gyazo.com/d8867e20b965556376c1dc8ec27cca12

Unlearn pet talents requires pet to be out 

If your pet is out and the trainer does not offer it to you it may be only NPC specific.
