### ISSUE TITLE
creazy damage in BF 3rd boss

### ISSUE THREAD

**Issue by jackychengjie** [SunwellWoW/Sunwell-TBC-Bugtracker#2944]
Description: 
we try to kill 3rd boss but the posion dot is 600 damage per jump it's impossible to heal with 60 or 61 healer

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by fakelort** [comment]
I healed that as a ret paladin, the damage is not that bad you probably just stood in the poison on the ground

**Comment by jackychengjie** [comment]
I am 100% no one stand in the circle yo we are not noob if u don’t want to fix it don’t bother it

发自我的 iPhone

在 2018年12月9日，上午1:28，fakelort <notifications@github.com<mailto:notifications@github.com>> 写道：


I healed that as a ret paladin, the damage is not that bad you probably just stood in the poison on the ground

**Comment by Piglover88** [comment]
If you're going to open a bug report fill in all the information for the Devs. You've done nothing to provide substance to this issue.

**Comment by jackychengjie** [comment]
I said the 3rd bf boss poison debuff 600 damage per jump how can I more clear the situation?

发自我的 iPhone

在 2018年12月9日，上午9:29，Piglover88 <notifications@github.com<mailto:notifications@github.com>> 写道：


If you're going to open a bug report fill in all the information for the Devs. You've done nothing to provide substance to this issue.

**Comment by jackychengjie** [comment]
BTW it's nightbane server

**Comment by MiekZer** [comment]
Looks like you played too much on warmane lel. Dude I clearly remember this boss during retail and the tactics was always to keep 1 add cced while we lose our debuffs. The point I may agree is that I think the actual normal debuff has the heroic value but even in normal I remember this boss shadow bolts hiting really hard. That's also why you have a buff on a corner or the room if I remember correctly. Dunno if the buff is implemented in this serv.

**Comment by jackychengjie** [comment]
It’s just nomal and the debuff said every jump is 300 but it’s 600 for real damage

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: MiekZer <notifications@github.com>
发送时间: Sunday, December 9, 2018 1:58:25 PM
收件人: SunwellWoW/Sunwell-TBC-Bugtracker
抄送: jackychengjie; Author
主题: Re: [SunwellWoW/Sunwell-TBC-Bugtracker] creazy damage in BF 3rd boss (#2944)


Looks like you played too much on warmane lel. Dude I clearly remember this boss during retail and the tactics was always to keep 1 add cced while we lose our debuffs. The point I may agree is that I think the actual normal debuff has the heroic value but even in normal I remember this boss shadow bolts hiting really hard. That's also why you have a buff on a corner or the room if I remember correctly. Dunno if the buff is implemented in this serv.

―

**Comment by jackychengjie** [comment]
It’s BF u blind

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: MiekZer <notifications@github.com>
发送时间: Sunday, December 9, 2018 1:58:25 PM
收件人: SunwellWoW/Sunwell-TBC-Bugtracker
抄送: jackychengjie; Author
主题: Re: [SunwellWoW/Sunwell-TBC-Bugtracker] creazy damage in BF 3rd boss (#2944)


Looks like you played too much on warmane lel. Dude I clearly remember this boss during retail and the tactics was always to keep 1 add cced while we lose our debuffs. The point I may agree is that I think the actual normal debuff has the heroic value but even in normal I remember this boss shadow bolts hiting really hard. That's also why you have a buff on a corner or the room if I remember correctly. Dunno if the buff is implemented in this serv.

―

**Comment by jackychengjie** [comment]
If u don’t know what it is go into BF and check the damage I don’t want to be given something “I think” or “ I believe” shit any more

Thank you

发自我的 iPhone

在 2018年12月9日，下午1:58，MiekZer <notifications@github.com<mailto:notifications@github.com>> 写道：


Looks like you played too much on warmane lel. Dude I clearly remember this boss during retail and the tactics was always to keep 1 add cced while we lose our debuffs. The point I may agree is that I think the actual normal debuff has the heroic value but even in normal I remember this boss shadow bolts hiting really hard. That's also why you have a buff on a corner or the room if I remember correctly. Dunno if the buff is implemented in this serv.
