### ISSUE TITLE
[Warlock][Spell] Seed of Corruption

### ISSUE THREAD

**Issue by Mirlmunir** [SunwellWoW/Sunwell-TBC-Bugtracker#2945]
Description:  Imbeds a demon seed in the enemy target, causing blabla over 18sec. 
When the target takes 1044 total damage or **DIES** the seed inflict 1110 to blabla to all other ennemies within 15 yards of the target.

How it works:  https://plays.tv/video/5c0cd116184398a18f/seed-of-corruption-issue-
1/5 seeds explodes when target dies, I didn't test yet if they explodes after I inflict some damage but this result to so much lost DPS in dungeon & Raid. 
How many time a warlock wanna cast seed vs a huge pack of mobs in dungeon and don't explodes because of that.

How it should work: Like my tooltip say ingame https://puu.sh/CeRez/ded46719f2.png 

Source (you should point out proofs of your report, please give us some source): https://puu.sh/CeRez/ded46719f2.png

**Comment by jowns** [comment]
Yes broken when mobs dies. Fix seed and demonic knowledge please!

**Comment by Shards2k3** [comment]
God yes PLEASE fix this. It helps farming lower level mobs and it's crippling me.
