### ISSUE TITLE
Engineering Goggles

### ISSUE THREAD

**Issue by Columbia24** [SunwellWoW/Sunwell-TBC-Bugtracker#2946]
Description: At engineering skill level 350 there should be a recipe available from the engineering trainer to craft a head slot goggle that pertains to your armor type. The recipe or availability of being able to train the goggles is unavailable from trainers. As a warlock, I am unable to train "Destruction Holo-Gogs" even thought I meet the requirements. In fact, no goggles appear to be available from the trainer in Thrallmar whatsoever

How it works: At level 350 engineering, learn epic recipe for the head slot.

How it should work: There should be a trainable recipe.

<img width="618" alt="screen shot 2018-12-09 at 3 52 55 am" src="https://user-images.githubusercontent.com/45651797/49695243-1c031480-fb66-11e8-88be-9de798072c24.png">

<img width="449" alt="screen shot 2018-12-09 at 3 52 47 am" src="https://user-images.githubusercontent.com/45651797/49695244-1efe0500-fb66-11e8-9455-ff7a8e230c59.png">

<img width="403" alt="screen shot 2018-12-09 at 3 52 22 am" src="https://user-images.githubusercontent.com/45651797/49695245-21605f00-fb66-11e8-8cfc-a58a403d49e2.png">

Source (you should point out proofs of your report, please give us some source):

**Comment by notsofamous** [comment]
Added in 2.1, shouldn't be available.
