### ISSUE TITLE
Blood Furnace Reputation gain

### ISSUE THREAD

**Issue by RPAncap** [SunwellWoW/Sunwell-TBC-Bugtracker#2947]
Description: 
You should be able to farm reputation in Blood Furnace until you are Honored.

How it works: 
You currently only get 1 REP from any trash kill in Blood Furnace. 

How it should work: 
You should get 5 for elite and 3 for non-elite. The same as you do in Hellfire Ramparts.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120818_215846](https://user-images.githubusercontent.com/44553524/49695591-bb8fc980-fb9d-11e8-8fdc-6cf248c4e7b6.jpg)

**Comment by Altgreen** [comment]
10 days ! still not fixed ? Core instance ...

**Comment by Trentone** [comment]
Can confirm this is not normal. Don't know if it is fixed on live Sunwell at the moment.
