### ISSUE TITLE
Hunter talent Rapid Killing

### ISSUE THREAD

**Issue by Slykz** [SunwellWoW/Sunwell-TBC-Bugtracker#2948]
Description: 

The Hunter talent Rapid killing doesn't provide the 20 second damage buff on next spell if another persons deals the last damage in a kill. If you kill 99% of the monster and another player deals the last 1% it doesn't provide the buff.

This happens if the player is not in your party aswell as being in your party.

How it works: 

it gives buff based on the player getting a killing blow on a monster rather than receving experience for it.

How it should work: 

It should provide the buff aslong as you receive experience, and not based on you getting the final hit.

Source (you should point out proofs of your report, please give us some source): 

Testing ingame.

**Comment by tjmitchell1** [comment]
Those types of skills almost always require the killing blow.

**Comment by alucardcsn** [comment]
This ability is not working properly, it only works if PET kills the monster and even so the spells do not benefit from the buff
