### ISSUE TITLE
Rain of fire

### ISSUE THREAD

**Issue by Pizzle93** [SunwellWoW/Sunwell-TBC-Bugtracker#295]
Decription: 
Rain of fire only damaging one engaged target (and sometimes none), and that target doesn't need to be within the spell's area (could be fighting 2 melee npcs and 1 caster. The caster is far away and I cast rain of fire on the 2 melees, only the caster takes damage)

How it works: 
See above

How it should work: 
Should damage all in the area

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC/commit/36a026be008d0f129eb743aaad217cca386989bd
