### ISSUE TITLE
[Critical] 3x rate are giving 3x reputation

### ISSUE THREAD

**Issue by Reflekz** [SunwellWoW/Sunwell-TBC-Bugtracker#2950]
Description: 
The 3x boost from shop also gives 3x rep

How it works: ^

How it should work: 
3x boost should not give 3x rep.

Source (you should point out proofs of your report, please give us some source): 
i dont have premium so i dont have source ..

**Comment by nimeral** [comment]
How do you know it's true then?

Worth double-checking of course, would be absolutely gamebreaking.

**Comment by Reflekz** [comment]
Thats my point.

They NEED to check .

If it isnt , then it isnt.

**Comment by nimeral** [comment]
I mean, did someone trigger your suspicions at least? : ) It would be more convincing if you provide a chat screenshot or something.

**Comment by Wojtyas** [comment]
It doesn't work like this...
