### ISSUE TITLE
Seed of corruption

### ISSUE THREAD

**Issue by Pizzle93** [SunwellWoW/Sunwell-TBC-Bugtracker#296]
Decription: 
Does nothing on death or explosion trigger

How it works: 
See above

How it should work: 
Should damage all in an area on explosion

Source (you should point out proofs of your report, please give us some source):

**Comment by Patrulek** [comment]
Ok, i want to add something else:
- Seed of Corruption ignore LoS but shouldnt
- Seed of Corruption explosion damage doesn't trigger Seed of Corruption on another target (other aoe does)
