### ISSUE TITLE
Fire sources have too large hit range

### ISSUE THREAD

**Issue by Talimar** [SunwellWoW/Sunwell-TBC-Bugtracker#2961]
Description: 
Fire sources have too large hit range

How it works: 
Braziers, campfires etc. hit you from too far away. 
This is extremely annoying when stealthing around camps with fires everywhere.

Also I believe the damage is supposed to scale with level, 10 damage on a fresh char is quite high, but I can't say for sure. 
Either way, the range is the real problem.

How it should work: 
It shouldn't hit you unless you are basically touching it.

Source (you should point out proofs of your report, please give us some source): 
https://i.imgur.com/LBcmG69.jpg

**Comment by Nabis1** [comment]
yea its so annoying as char with stealth.

**Comment by sadfx** [comment]
You also get destealthed without even taking dmg sometimes
