### ISSUE TITLE
Inner Focus does not reduce the manacost of Mind Blast 

### ISSUE THREAD

**Issue by DomenikIrrgang** [SunwellWoW/Sunwell-TBC-Bugtracker#2964]
Description: 
When Inner Focus is activated and Mind Blast cast Mana is still subtracted.

How it works: 
See Description.

How it should work: 
No Mana should be spend.

Source (you should point out proofs of your report, please give us some source): 
Spelltooltip

**Comment by groveunder** [comment]
Also like to note, that I also think the Crit % on inner focus may not be applying. With only 10% static, 12% Talents and + inner focus, 25% = Totaling 42% Crit potential on a Mindblast, I'm hardly seeing a Critical from my Mind blast when using inner focus. Could be UNLUCKY, doubt it. Played Shadowpriests on TBC for quite some time.

**Comment by DomenikIrrgang** [comment]
seems to have been fixed in the build last night
