### ISSUE TITLE
[Quest] Recover the Key!

### ISSUE THREAD

**Issue by Rela09** [SunwellWoW/Sunwell-TBC-Bugtracker#2965]
Description: Quest works fine, but after turning it in you are able to pick it up again.
![b1cd69d626f41560b70ae2148eff9384](https://user-images.githubusercontent.com/45735876/49699005-f14ba700-fbcb-11e8-81a3-630f5974ff08.png)

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
It's a repeatable quest.
