### ISSUE TITLE
Bloodgem Crystals

### ISSUE THREAD

**Issue by jowns** [SunwellWoW/Sunwell-TBC-Bugtracker#2966]
Description: 
Quest: Bloodgem Crystals in Netherstorm (scryer quest) broken. Ive tried with over 4 shards and always same buged out thing.

How it works: 
When you use the shard near a bloodgem it just consumes the item and does nothing.

How it should work: 
It should siphon the bloodgem and you then get credit to the quest.

**Comment by Kanibar** [comment]
Can confirm, just had the same bug

**Comment by Kanibar** [comment]
https://www.youtube.com/watch?v=uY2VWCcqEAE

**Comment by Mansgroll** [comment]
Can Confirm aswell.. It wont channel. It just ticks for a second a then interrupts, and bloodgem dissapears

**Comment by Jseay1313** [comment]
please fix this so we can do scryer quests

**Comment by Dootz** [comment]
will be ready for tomorrow's update.

**Comment by ZaoQ** [comment]
Still bugged

**Comment by Sapphire18** [comment]
still not working

**Comment by Azathothh** [comment]
currently channeling is being interrupted if player isn't looking exactly at a crystal (so character have to turn around a bit), worked fine when i was facing the siphoned crystal (no turn at the beginning of channel)

**Comment by PeroFuse** [comment]
Still bugged

**Comment by Reflekz** [comment]
still bugged , looking at the crystal works , but this is very inconvenient (when you don't know)
