### ISSUE TITLE
Warlock Enslave demon

### ISSUE THREAD

**Issue by Sheskas** [SunwellWoW/Sunwell-TBC-Bugtracker#2967]
Description: 
Pet not following after being enslaved.

How it works: 
Pet not following.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by ZaoQ** [comment]
Already reported, still not assigned...

**Comment by Gelori** [comment]
enslave doesnt work for any demon in 1 lvl -> 57 lvl bracket.... demon is enslaved, but doesn't move or do anything

**Comment by Kamil-Radzyminski** [comment]
Is anybody trying to repair this? Please guys, that's a terrible bug!

**Comment by Demolla** [comment]
https://www.youtube.com/watch?v=H9PdjM_7xXM

Video from 8 years ago. Shows how Enslave Demon should work. You cast Enslave Demon > Pets automatically follows you > You can actually Control the demon.

Right now if you enslave demon it only stay where you enslaved it...

**Comment by jockeboschko** [comment]
bump for fix.
