### ISSUE TITLE
Hellfire

### ISSUE THREAD

**Issue by Pizzle93** [SunwellWoW/Sunwell-TBC-Bugtracker#297]
Decription: 
Hellfire warlock spell doesn't damage enemies (only damages yourself)

How it works: 
See above

How it should work: 
Should damage all nearby enemies

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC/commit/36a026be008d0f129eb743aaad217cca386989bd
