### ISSUE TITLE
AFK spam in chat

### ISSUE THREAD

**Issue by Floshizzle123** [SunwellWoW/Sunwell-TBC-Bugtracker#2970]
Description: 
I am getting spammed with notifications in chat (yellow text) about people on my friendlist being afk, and it's very often.

How it works: 
see above

How it should work: 
not as above
![afkbug](https://user-images.githubusercontent.com/45533750/49699273-6b315f80-fbcf-11e8-9366-b416b08e3984.png)

Source (you should point out proofs of your report, please give us some source): 
Screenshot with arrow attached

**Comment by ujellyx** [comment]
That's Carbonite's fault iirc.
