### ISSUE TITLE
crippling poison

### ISSUE THREAD

**Issue by Karasique123** [SunwellWoW/Sunwell-TBC-Bugtracker#2976]
Description: 
No crippling poison, and poisons icon in spell book

How it works: 
There must be poison icon like other professions

How it should work: 
http://prntscr.com/lr8az8 how its must look like

Source (you should point out proofs of your report, please give us some source): 
How its on me 
![wow_2018-12-09_19-02-13](https://user-images.githubusercontent.com/45736048/49699687-611a5b80-fbe5-11e8-8f90-b254b02cb743.png)
![wow_2018-12-09_19-04-53](https://user-images.githubusercontent.com/45736048/49699691-65df0f80-fbe5-11e8-842d-9abf45629599.png)

**Comment by sadfx** [comment]
You have to complete the quest
