### ISSUE TITLE
[Spell] Frozen nova & similar spells

### ISSUE THREAD

**Issue by syphex97** [SunwellWoW/Sunwell-TBC-Bugtracker#2977]
Description: 
In pvp if a mage freezes you with their nova it will last the full duration, its supposed to break after like 2 hits or so in pvp but it doesn't, i saw this being a issue since early on but decided to not speak up about it since i thought it could just be a coincidence, now i'm sure its not.

**Death Coil** works the same

I had a mage who froze me right now and it lasted through the full duration of 3 meele hitting me, then the mage casting spells and the hunter shooting projectiles with his pet hitting me for 8 seconds.

How it works: 
Frozen nova doesnt break or it breaks very rarley (Apparently it works like it should on npc's)

How it should work: 
Frozen nova Should break in PvP when the target get's hit.

Source (you should point out proofs of your report, please give us some source): 
There was no threads or posts about this being a issue back in TBC, if it were there would be complaints made about it. Therefore im unable to find anything to prove it.

**Comment by vititus** [comment]
what do you mean with death coil works the same?

death coil doesnt break on dmg

**Comment by syphex97** [comment]
> what do you mean with death coil works the same?
> 
> death coil doesnt break on dmg

Yeah it doesnt break on damage. or can't be dispelled by my abilities as a warrior that makes me immune to fears

**Comment by ujellyx** [comment]
Frozen Nova does break on damage here...

**Comment by syphex97** [comment]
> Frozen Nova does break on damage here...

I've had several mages say the same. Its effected in pvp, I've seen it work in pve

**Comment by vititus** [comment]
> > what do you mean with death coil works the same?
> > death coil doesnt break on dmg
> 
> Yeah it doesnt break on damage. or can't be dispelled by my abilities as a warrior that makes me immune to fears

because it's not a fear.


and nova does break on dmg.

**Comment by akrom23** [comment]
Just checked and works fine.
