### ISSUE TITLE
Arazzius the cruel doesnt spawn

### ISSUE THREAD

**Issue by johnpettersson** [SunwellWoW/Sunwell-TBC-Bugtracker#2982]
Description: 
Been waiting around for atleast 40 minutes now, 

How it works: 
Never spawns

How it should work: 
Spawntime in, 5-8 minutes?

**Comment by Dootz** [comment]
Hi, he's spawned in-game but was probably kite'ed away. He's there right now. Probably shouldn't happen. I'll prepare something to keep him in place :)
