### ISSUE TITLE
Pets proceeding to chase their target despite the target stealthing/vanishing

### ISSUE THREAD

**Issue by Avizurax** [SunwellWoW/Sunwell-TBC-Bugtracker#2984]
Description: 
Pets proceeding to chase their target despite the target stealthing/vanishing

How it works: 
Pets proceeding to chase their target despite the target stealthing/vanishing

How it should work: 

It should stop chasing when someone goes stealth.
Source (you should point out proofs of your report, please give us some source): 
no idea how to proof it, but its a very known thing haha, pets should stop chasing as soon as someone vanish or enter stealth

**Comment by sadfx** [comment]
> no idea how to proof it, but its a very known thing haha, pets should stop chasing as soon as someone vanish or enter stealth

Pets definitely chased players who stealthed in Vanilla, and I believe this is true for BC as well. Find proof of the contrary / don't make reports..

**Comment by Klimpb** [comment]
This was the case for most of TBC but changed in 2.4.3, undocumented.

http://www.arenajunkies.com/topic/29167-hidden-pet-nerf/
http://www.arenajunkies.com/topic/29172-hidden-hunter-nerfbug-fix-in-243/

Those threads created day after release of patch 2.4.3, yet nothing about it in the 2.4.3 patch notes.
Many changes like these were undocumented. 

Conclusion: Pets should NOT chase targets that enter stealth.

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2694
