### ISSUE TITLE
Stealth occasionally being put on an infinite cooldown after vanish has been used, can only be fixed by either relogging or vanishing again once it comes back up

### ISSUE THREAD

**Issue by Avizurax** [SunwellWoW/Sunwell-TBC-Bugtracker#2985]
Description: 
Stealth occasionally being put on an infinite cooldown after vanish has been used, can only be fixed by either relogging or vanishing again once it comes back up

How it works: 

Stealth occasionally being put on an infinite cooldown after vanish has been used, can only be fixed by either relogging or vanishing again once it comes back up

How it should work: 

it shouldn't go on CD.
Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@Avizurax Dou you have any screenshots of your combat log?

**Comment by Trentone** [comment]
@akrom23 This happens when stealth or vanish is used right at the moment when someone kills you. This is one and only reason for such behaviour that I know.

**Comment by akrom23** [comment]
@Trentone I tried but with no result.
