### ISSUE TITLE
Elemental Focus

### ISSUE THREAD

**Issue by Jhep1903** [SunwellWoW/Sunwell-TBC-Bugtracker#2986]
Description: Elemental Focus for Shaman only reducing 1 spell

How it works: 
One spell consumes the buff

How it should work: 
Should have 2 reduced mana spells

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2129
