### ISSUE TITLE
Rogues in Blood Furnace not stealthed

### ISSUE THREAD

**Issue by dadkinse** [SunwellWoW/Sunwell-TBC-Bugtracker#2993]
Description: 
On the stairs and throughout the dungeon there are rogues. They should be in stealth, but they are not.

How it works: 
The rogues are clearly visible

How it should work: 
They should be stealthed

Source (you should point out proofs of your report, please give us some source): 
![billede](https://user-images.githubusercontent.com/21084363/49700693-86f23100-fbe2-11e8-838e-4aeaa710ea36.png)

**Comment by Dootz** [comment]
seems to be working fine both locally and on live. Even after evade they return to stealth.

**Comment by Josephienvandermeersch** [comment]
Still not in stealth
