### ISSUE TITLE
Multiple Feral Druid Bugs. ZZZZZZ BIG ZZZZZ

### ISSUE THREAD

**Issue by mjk6994** [SunwellWoW/Sunwell-TBC-Bugtracker#2995]
Description: Omen of Clarity does not proc in any Shapeshifted form. Heart of the Wild Does not give Attack Power in Cat Form.

How it works: It doesn't. 

How it should work: It should proc? It should give attack power in cat form? xd

Source (you should point out proofs of your report, please give us some source): Ask any Feral, + 10+ hours of having it without procing a single time.

**Comment by notsofamous** [comment]
Omen of Clarity works fine for me, heart of the wild also seems to work fine. Could you post screenshots of your attack power in cat form with and without the talent?

**Comment by mjk6994** [comment]
Ill post a screen shot of me wasting a talent point next level. Regarding Omen, post a pic of it proccing because i cant post a pic of it not lol.

**Comment by 0vertime** [comment]
Heart of the Wild gave me AP the last time I checked it, but you have to refresh cat form to see the effect.
Omen of Clarity proc: https://i.imgur.com/IivyjjV.jpg - It does feel like really low chance.

**Comment by mjk6994** [comment]
It appears that Heart of the Wild has been fixed. I still have yet to see a proc on Omen however, I just may be -super- unlucky.

**Comment by Wojtyas** [comment]
We didnt't change anything here...
Feel free to reopen if needed. Maybe its just lack of proc sound?
