### ISSUE TITLE
[Druid] Tauren Combat Reach in Druid Forms

### ISSUE THREAD

**Issue by sadfx** [SunwellWoW/Sunwell-TBC-Bugtracker#2997]
Description: Tauren Druids have their Tauren combat reach in forms

How it works: Taurens have a greater combat reach / hitbox (works both ways, Taurens can hit or be hit from farther away)

How it should work: When you shapeshift you lose your Tauren combat reach

Source (you should point out proofs of your report, please give us some source): This 1.12 bug report shows how it's wrong https://github.com/LightsHope/issues/issues/332

As a sidenote: I believe Orb of Deceptioning into a Tauren won't give you the Tauren combat reach on Sunwell either even though it should

**Comment by baade123** [comment]
pvp diff than pve

**Comment by akrom23** [comment]
Nope. Works good.
