### ISSUE TITLE
Honorable kill(HK:"Rank") not being displayed.

### ISSUE THREAD

**Issue by Klimpb** [SunwellWoW/Sunwell-TBC-Bugtracker#2998]
Description: When you kill an enemy player that grants honor, the floating text of "HK:"Rank"" is currently not being displayed at all, 

How it works: Not being visible

How it should work: Should be displayed.

**Comment by akrom23** [comment]
Works fine.
![wowscrnshot_011419_143731](https://user-images.githubusercontent.com/1035215/51115950-f5da2f80-1809-11e9-90cf-62b0143db684.jpg)
