### ISSUE TITLE
[Spells] Duplicated auras

### ISSUE THREAD

**Issue by Azathothh** [SunwellWoW/Sunwell-TBC-Bugtracker#3]
Decription: 
Most of the auras are duplicated - giving same effect twice. It may interfere with class tests.

How it works:  For example Arcane Affinity is doubled - and it gives +10enchanting skill twice instead of once. Also while casting buffs we can see in combatlog that it's applied multiple times.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/BeJuBxV  - it's not only related to blood elf racials,but other auras as well

**Comment by Kokaina** [comment]
BIG BUG

**Comment by Kokaina** [comment]
Fixed.
