### ISSUE TITLE
Rogue: Sap Issue

### ISSUE THREAD

**Issue by VashetSunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#30]
Decription: 
Sap is not functioning as intended

How it works: 
Sapped targets are able to auto attack briefly after revealing the rogue from stealth (This occurred when I sapped mobs and then stood right in front of them in melee range.)

How it should work: 
Sapped targets should not be able to perform any action for the duration of the spell.

Source (you should point out proofs of your report, please give us some source): 
Tested on mobs in shadowmoon valley.

**Comment by akrom23** [comment]
Cannot reproduce.
