### ISSUE TITLE
Shamanistic Focus

### ISSUE THREAD

**Issue by Meteor23** [SunwellWoW/Sunwell-TBC-Bugtracker#3003]
Description: issue with this current spell, not working properly, enha sham can´t be effective with this issue

How it works: everytime when i crit and Shamanistic Focus appear, fire searing totem or healing spell or nature spell such as Lightning Bolt consumes it 

How it should work: only Shocks should be able to consume it with effect of -60% mana of using shock when this effect is up

Source (you should point out proofs of your report, please give us some source):

**Comment by ahlens** [comment]
Flame Shock tics consume it as well as I've heard from people.

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2048
