### ISSUE TITLE
[Hunter][Pet] Out of Combat Regen Lower Than It Should Be

### ISSUE THREAD

**Issue by Xithus** [SunwellWoW/Sunwell-TBC-Bugtracker#3006]
Description: The out of combat hunter pet regen is lower than it should be.

How it works: With your pet out go to the pet tab. Hover over their spirit and it will tell you how much health your pet should regen every second. Not sure if its both in and out of combat but out of combat is easiest to see.

How it should work: The amount per tic every second should match what it says when hovering over your pets spirit. Currently on my 32 pet its about half. Tooltip says 25 every second, but it's only regenning 11 a tic.

Source (you should point out proofs of your report, please give us some source): Hover of pets spirit to get correct regen amount and compare to actual out of combat regen.

**Comment by ozzmann** [comment]
Very annoying issue indeed!

**Comment by Xithus** [comment]
Looks like it's the other way now.

Tooltip hovering over pets spirit says pet should be getting 53 out of combat regen but it's actually getting 76.
