### ISSUE TITLE
"Tame pet" level ups.

### ISSUE THREAD

**Issue by Dollparts** [SunwellWoW/Sunwell-TBC-Bugtracker#3009]
Description: 
When level 65-70, taming a pet lower level is supposed to boost the pet to within 5 levels of you. Currently not working.

How it works: 
at level 70, taming a low level beast (For example, a level 19 cat), should level that cat to level 65 immediately. Currently it's staying level 19. (Works for any level)

How it should work: 
Pets should level up to within 5 levels of your level. So for level 70, pets level automatically to 65 unless they are tamed at a level higher than 65.

Source (you should point out proofs of your report, please give us some source): 
Every hunter taming video in existence.

**Comment by Xithus** [comment]
Would be nice but that change didn't happen till wolk.
