### ISSUE TITLE
Quest "The Hand of Gul'dan"

### ISSUE THREAD

**Issue by netherneth** [SunwellWoW/Sunwell-TBC-Bugtracker#3012]
Description: 
The NPC simply does not give the quest. It doesnt require any prequest so It seems like a bug

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=10681/the-hand-of-guldan#comments

**Comment by Wojtyas** [comment]
Will be available tommorow morning as we announced.

**Comment by netherneth** [comment]
But the attunements quest are Trials of naaru?
