### ISSUE TITLE
bodyguard for hire (stop closing) 

### ISSUE THREAD

**Issue by bonesylaz** [SunwellWoW/Sunwell-TBC-Bugtracker#3014]
Description: 2nd escort quest in desolace.

How it works: escort quest with the 2 kodo. 

How it should work: should work as an escort. 

Source (you should point out proofs of your report, please give us some source): the proof has been pointed out twice. stop closing it and fix it.

**Comment by nimeral** [comment]
There's an open report https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2010.

And a closed duplicate report https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2988.

Here goes another duplicate report.
