### ISSUE TITLE
[Blade's Edge Mountains][Quests][Horde] - Showdown

### ISSUE THREAD

**Issue by Sherbaderb** [SunwellWoW/Sunwell-TBC-Bugtracker#3015]
Description: 
Went to Alter to summon Goc, used horn and then Goc and Rexxar just stand around, no RP, Goc is unattackable and passive. Cannot complete quest.

How it works: 
NPC's stand around and do nothing...

Despawn after ~5 minutes of standing around doing nothing. Cant aggro Goc, can't do anything with them.

How it should work: 
Found this Youtube video from 2013 that seems to have the proper RP and play for Horde.

https://www.youtube.com/watch?v=6EWPf_VaQbY

Thanks.

**Comment by Azathothh** [comment]
"Requires altar of Goc and that Goc has not been summoned" - horn can be used even when one Goc is already summoned - which results in multiple events at same time
