### ISSUE TITLE
Shattered Halls Bugs (Normal)

### ISSUE THREAD

**Issue by Fuzedknight** [SunwellWoW/Sunwell-TBC-Bugtracker#3017]
Description: Most voice lines aren't playing only the text /yells show up.

Some packs are not linked to aggro together and can have 3/5 mobs in the pull be aggro'd.

Shattered Hand Legionnaire's should be immune to CC, they should also call for reinforcements if an ally of theirs dies and they are still alive as shown in this video. The video also shows more missing RP events of the fighters lining up. https://www.youtube.com/watch?v=z2pZgpA1cjU&t=5m32s

Grand Warlock Nethekurse is not instantly aggroing upon killing all of the Converts as shown here. https://www.youtube.com/watch?v=z2pZgpA1cjU&t=12m50s

The gauntlet event is not functioning properly, the Shattered Hand Scout should run away for RP purposes. The archers are not shooting their bows causing flame effects and instead the flame is just there to begin with. The enemies that come at you should also move up and make a formation instead of instantly aggroing in a huge pack. There should also be 2 enemies that spawn constantly and attack you from the end of the gauntlet for the entire duration that the Archers remain NOT in combat. All of the roleplay involved with this event are also missing. Shown in this video: https://www.youtube.com/watch?v=4VFpnpn4_ng&t=1m0s

The Shattered Hand Gladiators should NOT be able to kill each other.
https://puu.sh/Cfaqv/13b7d76726.png

All of the Houndmaster + 2 wolf packs are NOT patrolling and instead standing still except for the very first pack.

Non-elite Ooze seem to deal too little damage, my Blessing of Sanctuary reduced it all the way to 1.

Many of the Assassins were NOT invisible on my first run of this dungeon but all were on the second, I can't explain why.

Shattered Hand Savage spams enrage emote constantly flooding the chat box.

These two enemies should be sleeping in their bunks not standing.
https://puu.sh/CfagF/5d8c5f4be4.png

This training dummy is spam zapping itself for some reason.
https://puu.sh/CfaVg/f2b278509b.png

Warchief Kargath Bladefist seems to deal too little damage and the adds are spawning too infrequently.

**Comment by Wojtyas** [comment]
Riztazz will correct a lot of SH stuff on days. Moved to massive topic.
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/157

**Comment by Fuzedknight** [comment]
Just curious what does "on days" mean? My bad for not seeing the large topic. I do think dungeons should take priority before everyone farms the easy versions of them for all the gear.
