### ISSUE TITLE
[Warrior] Cleave doesn't hit multiple mobs

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#302]
Decription: cleave only hits 1 mob

How it works: cleave only hits 1 mob

How it should work: cleave should hit multiple mobs

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC/commit/36a026be008d0f129eb743aaad217cca386989bd
