### ISSUE TITLE
Mining & Mote of Fire

### ISSUE THREAD

**Issue by mintnb** [SunwellWoW/Sunwell-TBC-Bugtracker#3020]
For the past day or two Motes of Fire have been missing from nodes in Outland. They used to drop quite often along with the Motes of Earth but not anymore. I haven't gotten a single one all day today.

**Comment by Bzmode** [comment]
They were nerfed without evidence because people thought they were too common when in actuality mine are respawning way too quickly(6 minutes) and always on the same spots instead of pooled spawning like how it was in retail.

**Comment by mintnb** [comment]
Then Mote of Earth makes sense to be nerfed too. I have gathered nearly 50 of those already.
Having nodes respawn time increased and their regular drops normalized is much more on point.

**Comment by mintnb** [comment]
Note: I have played retail TBC.. from what I remember fire to earth from mining was rougly 1:2 ratio. This is to be confirmed before implementing though.

**Comment by nimeral** [comment]
Please fix mining nodes spawn (too fast/not random) before it harms the economy too much.

I'm pretty sure that herbalism is broken but in the opposite direction, as in https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2197, but it's quite impossible to prove... So please just make sure mining and herbalism are "equal".
