### ISSUE TITLE
Shaman Elemental Mastery not working

### ISSUE THREAD

**Issue by Tarcaul** [SunwellWoW/Sunwell-TBC-Bugtracker#3021]
Description: 
Elemental Mastery talent to guarantee a 100% crit on next frost, fire, or nature spell is not criting but consumes the buff.

How it works: 
If you cast a spell, followed by elemental mastery, then cast another while one spell is in mid-air it does not proc.

How it should work: 
It should proc.

Source (you should point out proofs of your report, please give us some source): 

Don't have a screenshot of a mid air spell, nor do I have video to show. Please fix.

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2450
Will be fixed today/tommorow.
