### ISSUE TITLE
Grounding Totem

### ISSUE THREAD

**Issue by Tarcaul** [SunwellWoW/Sunwell-TBC-Bugtracker#3022]
Description: 
Grounding totem is supposed to consume a targeted spell and redirect it from the player to the totem.

How it works: 
It doesn't absorb the spell, sometimes it does when its laid down for 2-3 seconds prior to the spell. 

How it should work: 
It should absorb the spell immediately after being dropped.

Source (you should point out proofs of your report, please give us some source): 
I don't have video proof running nor do I have a screen shot of mid-combat spells.

**Comment by smkrus** [comment]
Grounding Totem must also be in LoS + range of the spell's source to work as well.
I think only the shaman or party member must be in range of the totem instead.

**Comment by FrauHolle86** [comment]
still not working properly -.-
