### ISSUE TITLE
elemental focus

### ISSUE THREAD

**Issue by Tarcaul** [SunwellWoW/Sunwell-TBC-Bugtracker#3024]
Description: 
Elemental focus has 2 charges to reduce a spell cost by 40%. Lightning Bolt, CL, or any shock spell consumes BOTH charges.

How it works: 
Buff is completely consumed after 1 cast.

How it should work: 
Buff should be completely consumed after 2 casts. 

Source (you should point out proofs of your report, please give us some source):  
Thats how the talent works, it say TWO (2) casts, not one.

**Comment by Wojtyas** [comment]
Will be fixed soon
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2129
