### ISSUE TITLE
Talbuk Sire Talbuk Doe  [Creatures of the Eco-Domes]

### ISSUE THREAD

**Issue by MrTide** [SunwellWoW/Sunwell-TBC-Bugtracker#3025]
Description: 
90% of These creatures are missing UI teleporting instead of moving ETC .. they are also part of quests 

How it works: 
 [Creatures of the Eco-Domes] can't be done creatures are missing UI
Seems like they lose UI and teleport around after using **quest item on them**
How it should work: 
they should have UI and be part of the quests they are meant to be

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_121018_062618](https://user-images.githubusercontent.com/36106057/49708370-a1f58d00-fc44-11e8-8b70-18045a841d5d.jpg)

**Comment by Wojtyas** [comment]
Works fine for me, just checked on Nightbane.

![image](https://user-images.githubusercontent.com/22802214/49731765-ae95d780-fc7c-11e8-9275-8e05b2277a32.png)

**Comment by MrTide** [comment]
Not all of them 
they bug out after using the quest item on them
they just lose everything

**Graal: ok got it**

**Comment by Wojtyas** [comment]
Still not working

**Comment by waterloorick** [comment]
Still not working. they cannot be interacted with.

**Comment by Dootz** [comment]
will be fixed with next server restart
