### ISSUE TITLE
Elemental mastery in macro

### ISSUE THREAD

**Issue by Doz-o** [SunwellWoW/Sunwell-TBC-Bugtracker#3028]
Description: When i use elemental mastery in macro it gets used and goes away without a spell cast. When i use elemental mastery by itself i spam click and it does not go away.

macro
/cast Elemental Mastery
/use Vengeance of the Illidari
/use Blood Fury(Racial)

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Doz-o** [comment]
When i changed elemental mastery to the last spell in sequence it now works fine

**Comment by Avishai97** [comment]
the issue is that elemental mastery gets consumed upon clicking any spell, item, whatever

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2450
Will be fixed today/tommorow.
