### ISSUE TITLE
[Warrior] sweeping strikes damage calculated differently and not triggering off WW

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#303]
Decription: secondary target numbers are different from primary,

How it works: It looks like it might be being mitigated by different armor amounts. However I noticed that while fighting 2 mobs of the same name and level that the secondary target is always hit for exactly 1 damage less. On different mobs the damage variance is greater. It will only trigger once when you WW regardless of how many targets are hit

How it should work: The damage should be exactly the same with no chance to miss, crit, dodge, parry, or block. There should be 1 charge used per target hit with WW.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Off WW should be fixed.
