### ISSUE TITLE
ferocious bite not showing in combat log on killing blow 

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#3031]
Description: 
it does not show in combat log

How it works: 
maybe its all killing blows??
said "failed""
How it should work: 
should show damage

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2999
