### ISSUE TITLE
ramparts

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#3033]
Description: 
Nazan boss encounter, loot chest dissappers too fast.

How it works: 
Npc's in dungeons shoulnt respawn after 4 mins - and the loot chest after nazan dies shoulnt despawn after like 30 sek

How it should work: 
Imagine, 2 people die in fire on Nazan, they run in again as theres no ress avalible, both quest NPC are gone so they have to run it again, and the other people of the group wait for them to come in to loot chest, which didnt show or dissaperd after 30 sek of killing Nazan.

Source (you should point out proofs of your report, please give us some source): 
Reportet it yesterday ingame aswell.

**Comment by Wojtyas** [comment]
Already implemented, corpse delay timer set to normal state.
