### ISSUE TITLE
Inner focus Priest

### ISSUE THREAD

**Issue by groveunder** [SunwellWoW/Sunwell-TBC-Bugtracker#3034]
Description: 
Casting Inner focus on priest class, and using spell Mind blast. Does not reduce mana cost like it should.
Troll Priest.
How it works: 
Casting inner focus then mind blast, causes you to lose mana.

How it should work: 
Should not lose mana.

Source (you should point out proofs of your report, please give us some source):

**Comment by groveunder** [comment]
Also like to note, that I also think the Crit % on inner focus may not be applying. With only 10% static, 12% Talents and + inner focus, 25% = Totaling 42% Crit potential on a Mindblast, I'm hardly seeing a Critical from my Mind blast when using inner focus. Could be UNLUCKY, doubt it. Played Shadowpriests on TBC for quite some time.

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2964
