### ISSUE TITLE
Amulet of the Moon

### ISSUE THREAD

**Issue by sinfer** [SunwellWoW/Sunwell-TBC-Bugtracker#3037]
Description: Vendor value of this amulet

How it works: Shows that vendor value is 1copper but when sold buyback value is shown correctly

How it should work: Show vendor value correctly before selling

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_121018_101853](https://user-images.githubusercontent.com/45524181/49719305-70d98480-fc65-11e8-9196-15425b4b63fd.jpg)

**Comment by Wojtyas** [comment]
Moved to https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3038
