### ISSUE TITLE
[Warlock] spell "Curse of the Elements" tooltip bug?

### ISSUE THREAD

**Issue by popcorn16** [SunwellWoW/Sunwell-TBC-Bugtracker#3039]
Description: 
"Curse of the Elements" which gives a standard 10% increased arcane, fire and shadow dmg + 3/3 points in "Malediction" is 13% increased damage. The debuff on targets with the Curse shows 10% though. Not sure if this is a tooltip bug or if it's the talent not working properly.
![wowscrnshot_121018_100921](https://user-images.githubusercontent.com/45704143/49722038-0a079b80-fc64-11e8-9df9-cc66e910d191.jpg)
![wowscrnshot_121018_100922](https://user-images.githubusercontent.com/45704143/49722039-0a079b80-fc64-11e8-8f56-67f3eee8f0ed.jpg)
![wowscrnshot_121018_100933](https://user-images.githubusercontent.com/45704143/49722041-0a079b80-fc64-11e8-8030-3cef4b6c7cbc.jpg)

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by notsofamous** [comment]
Talented spells don't update their tooltips when they are applied as a buff/debuff. This is an issue with vanilla/TBC clients that cannot be fixed.
