### ISSUE TITLE
[Warlock] succubus seduction always lasts 3-4 seconds

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#304]
Decription: seduction always ends too soon

How it works: tested ~40 times, always lasts 2-4 seconds

How it should work: it should normally last 15 seconds on mobs (10 seconds pvp with DR) with the occasional early break.

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
//NOTE from other issue: check for "Your pet is out of range"

**Comment by babno** [comment]
It's in range, it successfully casts and the mob is seduced, it just breaks after 2-4 seconds.

**Comment by akrom23** [comment]
Fixed.
