### ISSUE TITLE
[Quest] Triage!

### ISSUE THREAD

**Issue by vilzu** [SunwellWoW/Sunwell-TBC-Bugtracker#3044]
Description: Quest Triage! doestn't work. Event isn't starting at all, and injured soldiers aren't in beds.

How it works: Event isn't starting at all, and injured soldiers aren't in beds. So you cannot complete quest and proceed on first aid training.

How it should work: There should be injured soldiers in the beds, and event should start for your to save them.

Source (you should point out proofs of your report, please give us some source): 
https://tbc-twinhead.twinstar.cz/?quest=6622

**Comment by neheri** [comment]
Worked 100% fine for me 2 days ago. After like 30 seconds injured, badly injured and criticaly injured soldiers begun to spawn in beds, I had to target them and use bandage in order to heal them so it was working as intended.

**Comment by Wojtyas** [comment]
Works fine for me as well, just did it on Nightbane.

![image](https://user-images.githubusercontent.com/22802214/49730843-e4858c80-fc79-11e8-8dbf-cf816bd79fab.png)
