### ISSUE TITLE
[Terokkar Forest] Cant use translocator when dead

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#3045]
Description: Cant use the translocator at firewing point while dead, preventing you from getting corpse

How it works: Cant use the translocator at firewing point while dead, preventing you from getting corpse

How it should work: Player should be able to interact with translocators throughout the world while dead.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Moved to https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2305
