### ISSUE TITLE
Hound of Culuthas / Mote of Shadow

### ISSUE THREAD

**Issue by Shmilowitz** [SunwellWoW/Sunwell-TBC-Bugtracker#3047]
Description: 
> Hound of Culuthas/Eye of Culuthas in Netherstorm are suppose to be the go-to farm area for mote of shadow.

How it works: 
> It doesn't drop any mote of shadows.

How it should work: 
> It should drop mote of shadow. 

Source (you should point out proofs of your report, please give us some source): 
> https://db.excalibur.ws/?item=22577 (Mote of shadow database drop table)

**Comment by Shmilowitz** [comment]
I can see that you pushed the fix to live, but only fixed "Hound of Culuthas" and not "Eye of Culuthas". The eyes still have an empty loot table. Same source as previously mentioned.

**Comment by Dootz** [comment]
kk, i'll re-check
