### ISSUE TITLE
The Final Code [Translocator]

### ISSUE THREAD

**Issue by mchayes** [SunwellWoW/Sunwell-TBC-Bugtracker#3048]
Description: When you teleport up into the tower and die you are unable to get back up there in ghost form. ATM opposing factions are just ganking there meaning people need to spirit ress all day.

How it works: Trying to use the translocation device in ghost form results in "You can not do that when you are dead"

How it should work: iirc, you should be able to recover your corpse by way of these types of quests and teleport devices. 

Source (you should point out proofs of your report, please give us some source): The Final Code - Translocator.

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3045
