### ISSUE TITLE
[Mage][Spell][Mechanic] Absorb priority Fire/Frost Ward

### ISSUE THREAD

**Issue by Ibuprofeno** [SunwellWoW/Sunwell-TBC-Bugtracker#3050]
Description: 
Other shield get consumed before fire/frost ward when being damaged by their elements.

How it works: 
Ice Barrier will break before Fire ward when being damaged by fire spells.

How it should work: 
Fire/frost ward should take priority when being damaged by their element.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@Ibuprofeno Source of this priority mechanic?

**Comment by Ibuprofeno** [comment]
could only find https://eu.battle.net/forums/en/wow/topic/4940486396 after a quick search will try to look up an old report of mine on some bugtracker where I posted a source

**Comment by akrom23** [comment]
Okay. Waiting.

**Comment by Ibuprofeno** [comment]
It seems like my Angrathar issue for this was deleted (it got fixed fairly quickly) will have to use some vid (that I still have to look up because try to find a scenario from a retail vid in which: 
frost/fire/shadow ward is applied AFTER ice barrier [to prove it's not the standard cast order prio] and ice barrier breaks first on the ward type of damage 
gets as source since this is a mechanic that won't be listed in any change log ((absorb prio only changed from cast order to duration after wotlk, only change prior to that was in 1.11.0 to give ice barrier prio over mana shield))

It should honestly just make sense because otherwise warding improving talents would be useless if the dmg isn't absorbed by the warding first (ie: frost/fire ward reflects would never proc if another active shield was casted before the warding)

**Comment by akrom23** [comment]
Alright.
