### ISSUE TITLE
[Core] Kicked from group on logout

### ISSUE THREAD

**Issue by zkillertheman** [SunwellWoW/Sunwell-TBC-Bugtracker#3052]
Description: If in a group and you logout you will get kicked and sometimes when you log back on you are unable to be inviated again, says your still in a group

How it should work: You should stay in the group until kicked or leaving...

Source (you should point out proofs of your report, please give us some source):

**Comment by zkillertheman** [comment]
after some testing it seems to only be happening if logged out instantly, in a rested zone

**Comment by zkillertheman** [comment]
This also randomly happens if you dc, for the group it looks like you're simply "offline" but you get kicked when you log back in and have to be invited back, this will also not transfer group lead. So if the leader gets this bug you need to redo a dungeon. Happened for me in SL today.

**Comment by Gelori** [comment]
#3536 - here is more complete explanation of Group issues! ref to it
