### ISSUE TITLE
Warrior Heroic Strike

### ISSUE THREAD

**Issue by icarovps** [SunwellWoW/Sunwell-TBC-Bugtracker#3057]
Description: 
Heroic Strike does not have the damage it should

How it works:
The damage is calculated with white swing + fixed damage (My is 48-65 + 44 fixed damage). 

How it should work: 
Total damage was to be between 92 and 109. But my damage is about 67-72.

Source (you should point out proofs of your report, please give us some source): 

![wowscrnshot_121018_113204](https://user-images.githubusercontent.com/39803279/49735756-4ee4ff80-fc6f-11e8-9ec5-2340c6372981.jpg)
![wowscrnshot_121018_113224](https://user-images.githubusercontent.com/39803279/49735758-4ee4ff80-fc6f-11e8-9825-c763d151b8e7.jpg)
![wowscrnshot_121018_113227](https://user-images.githubusercontent.com/39803279/49735760-4ee4ff80-fc6f-11e8-89fe-d18421c1a02c.jpg)

**Comment by neheri** [comment]
The addon just probably doesn't take enemies' armor into consideration. I've been leveling a warrior myself and it's a huge difference in between attacking casters and melee NPCs. It's even noticable if you compare damage done to beasts and humanoids.

**Comment by icarovps** [comment]
The minimum armor needed to reduce damage sufficiently is about 1000. In one worg? Its high, I think, because i have 1.2k with shield...

**Comment by icarovps** [comment]
![image](https://user-images.githubusercontent.com/39803279/49737460-18f64a00-fc74-11e8-8c66-b2ca5ffaaef2.png)

**Comment by neheri** [comment]
You can try testing against other player in a duel with no items equipped, just make sure enemy has 0 armor.

**Comment by akrom23** [comment]
Armor Mitigation.
