### ISSUE TITLE
Mobs in Bash'ir Landing

### ISSUE THREAD

**Issue by popalexandrudan** [SunwellWoW/Sunwell-TBC-Bugtracker#3061]
Description: 
After farming 2000+ mobs in bash'ir landing i only got 4 green drops and 1 blue. No depleted items.
So i.m opening this ticket to make sure the drops are not bugged
Not even grey items drop so much.
mobs:
Bash'ir Raider
Bash'ir Arcanist
Unbound Etereal
Lightning Wasp

How it works: 
Low drop rate

How it should work: 
Higher drop rate since they are 70-73.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Well, its intended... Ogri'la stuff and drop will be added with Black Temple content.
