### ISSUE TITLE
[Mobs] Talbulk Doe - Netherstorm

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#3064]
Description: / How it works: 

- mobs are / becoming untargetable and bugg out
- might havt to to with the Quest, where you have to put them to sleep

Source (you should point out proofs of your report, please give us some source): 

![grafik](https://user-images.githubusercontent.com/45068171/49738981-0cccb580-fc91-11e8-8098-714fb9d9562c.png)

![grafik](https://user-images.githubusercontent.com/45068171/49739006-19e9a480-fc91-11e8-9dd7-2971dfafcbb4.png)

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3025
