### ISSUE TITLE
[Druid] Clearcasting in Bear Form

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#3065]
There's something strange going on with the clearcasting you get in Bear Form. Sometimes you cannot use a any spell because you don't have enough rage for it, even if you have clearcasting up. When you have sufficient rage for the spell you can use it and no rage is consumed and the clearcasting is removed.

I think it might be because you have enough rage for the spell and then a maul that was already queued is used and your rage drops below the needed amount for a spell and it bugs out.

**Comment by akrom23** [comment]
Cannot reproduce. I am always able to cast spell with no rage and with Clearcasting aura.
@notsofamous Some video?

**Comment by akrom23** [comment]
No response.
