### ISSUE TITLE
Summoned NPCs

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#3066]
Summoned NPCs turn hostile for no reason, you can still interact with them but you can also attack.

Examples: Shattrath Escort elemental, kor'kron flare gun, the cenarion druid at death's door in BEM.

**Comment by notsofamous** [comment]
![Image](https://i.gyazo.com/297672200ad9fd524b3cdbb184f89512.jpg)
![Image](https://i.gyazo.com/2fd456956ea7667d48e48643b47a6141.jpg)

**Comment by akrom23** [comment]
@notsofamous: Still happens?
