### ISSUE TITLE
[Dungeon] Mechanar boss Nethermancer Sepethrea

### ISSUE THREAD

**Issue by codey07** [SunwellWoW/Sunwell-TBC-Bugtracker#3067]
Description:  Adds are too quick

How it works:  Fire elementals run too fast and player cannot out run them making fight near impossible with appropriate gear levels.

How it should work: The fire elementals spawned by the necromancer should be running at a speed that can be outrun by a player

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=YTv9ngC5rsk
https://www.youtube.com/watch?v=6B518EQiyiI  (video from TBC)

**Comment by Wojtyas** [comment]
Already included in https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1797
Will be done asap.
