### ISSUE TITLE
[Critical] Relog issues

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#307]
Everytime you relog your skills (weapon, professions, defence etc) are reset to 1 and your HP/mana is reset to 1.

**Comment by Kokaina** [comment]
Spells and items may be reset (disappear) as well.

**Comment by Kokaina** [comment]
Update:
Everytime we rlg our profession skills are reset and .unlearned spells are still present.

**Comment by notsofamous** [comment]
Profession skills still reset to 1 after relog.

**Comment by akrom23** [comment]
For me, it works fine with mining and blacksmithing.
Maybe just tell me step by step how to reproduce it.

**Comment by Nadiirr** [comment]
@notsofamous 
About professions:
When you use .setskill to level up a profession then it does not save.
When professions are learned correctly they save correctly.

**Comment by Nadiirr** [comment]
Verified it only happens when using the .setskill command.

Going to close it because people won't encounter this issue. Only GM's And GM's don't need professions.
