### ISSUE TITLE
Thorium Settings

### ISSUE THREAD

**Issue by Rethik64** [SunwellWoW/Sunwell-TBC-Bugtracker#3072]
Description:  Materials Used to craft Said recipe is Greater than the intended ammount.

How it works: When you Craft Thorium Settings, It takes 3 Bars for every 1 Thorium Setting.

How it should work: The Cost should Be 1 Bar for every 1 Thorium Setting.

Source (you should point out proofs of your report, please give us some source): I believe you can see logs on my character "Rethik Human warlock".

**Comment by jbwilson11** [comment]
Duplicate of https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2519
