### ISSUE TITLE
Demoralizing shout target debuff tooltip

### ISSUE THREAD

**Issue by elaegw** [SunwellWoW/Sunwell-TBC-Bugtracker#3073]
Description:
With improved demoralizing shout talent, it adds 40%. Maybe the tooltip just writes the basic amount while it applies the correct amount ? thought you guys might want to check that out
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![demoshout1](https://user-images.githubusercontent.com/45734837/49745383-bc585680-fc96-11e8-915d-2a752e6d2d29.png)
![demoshout2](https://user-images.githubusercontent.com/45734837/49745403-c712eb80-fc96-11e8-9602-d93798dc8fd8.png)

**Comment by Wojtyas** [comment]
Tooltip won't change, its not a bug but how it worked back in TBC expansion.
