### ISSUE TITLE
The Cipher of Damnation - Ar'tor's Charge (quest)

### ISSUE THREAD

**Issue by dovadx** [SunwellWoW/Sunwell-TBC-Bugtracker#3075]
Description: 
This quest should be done by having the NPC run alongside you RP'ing and killing adds with you eventually spawning the eye mob after having killed enough adds deeper into the demon camp.

How it works: 
NPC sits still, you having to drag mobs close to him to even make him move and even then he doesn't continue on doing the quest as intended

How it should work: 
You run alongside the NPC killing adds and the eye spawns after having killed a demon

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
seems like there is also no loot

**Comment by Pizzle93** [comment]
Seems like the mob doesn't spawn (or way too infrequently to be doable)

**Comment by Sabre142** [comment]
Currently seems uncompleteble.
