### ISSUE TITLE
Bloodlust overriding Icy veins / Not stacking

### ISSUE THREAD

**Issue by dovadx** [SunwellWoW/Sunwell-TBC-Bugtracker#3077]
Description: 
When using the Mage CD Icy Veins and having a shaman cast Bloodlust, Icy Veins gets overriden and other way around if you cast Icy veins after Bloodlust is active it doesn't work.

How it works: 
Icy veins gets overriden by BL

How it should work: 
Both should stack and not override each other

Source (you should point out proofs of your report, please give us some source): 
https://clips.twitch.tv/SweetEvilReindeerHassanChop
Clip shows the bug

**Comment by Exander1** [comment]
This should be a priority fix.
