### ISSUE TITLE
[Warlock][Hunter] Pet gets dismissed after relog

### ISSUE THREAD

**Issue by Lunasoll** [SunwellWoW/Sunwell-TBC-Bugtracker#3078]
Description: 
When restarting the client, and logging back to the character, pet does not stay. Has to be resummoned/recalled. 

It's not as annoying for hunters as for warlocks because they have to spend a shard to resummon a demon. 

How it works: 
Pet does not remain summoned after every relog/restart. 

How it should work: 
Pet should remain summoned after every relog/restart. 

Source (you should point out proofs of your report, please give us some source):

**Comment by babno** [comment]
Slight clarification, in that the soul shard is at least refunded, so you'll never be unable to summon your pet, though between the 10 second cast time and large chunk of mana still definitely very annoying, and potentially deadly if you got DCd in a hostile mob area.

**Comment by Lunasoll** [comment]
> Slight clarification, in that the soul shard is at least refunded, so you'll never be unable to summon your pet, though between the 10 second cast time and large chunk of mana still definitely very annoying, and potentially deadly if you got DCd in a hostile mob area.

Yes it does get refunded. Pet also despawns when going in or out of the SW mage tower room with portal trainers. There are other cases, but I am not 100% sure. I will add here if I encounter them again.
