### ISSUE TITLE
[Area] Access Shaft Zeon and surroundings - Netherstorm (EDIT)

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#3079]
Description: / How it works: 

- while questing next to Manaforge Ultris way up the hill, Paracitic Fleshbeasts are popping out of the ground randomly (no i am not even close to Withered Corpse (blood elfs))
- they aggro from the cave Access Shaft Zeon whyever (Coordinates 60.40)

- when in the cave itself, the Quest "The Flesh Lies..." cant be done due to the Withered Corpse are "invalid targets" - also the trigger range of the mobs coming out of the Withered Corpse is way to big
- when walking deeper into the cave and not beeing close to any kind of Withered Corpse, random mobs coming from everywhere from time to time (dont care about LOS or anything) and just hunt you down --> questing within the cave becomes impossible

Source (you should point out proofs of your report, please give us some source): 

![grafik](https://user-images.githubusercontent.com/45068171/49747168-15c68280-fca3-11e8-958d-3d86f71148f0.png)

![grafik](https://user-images.githubusercontent.com/45068171/49747184-1fe88100-fca3-11e8-9e7c-6bbd0b4d3e0d.png)

**Comment by Wojtyas** [comment]
They appear once u walk over Withered Corpse (blood elfs) on ground.

**Comment by FrauHolle86** [comment]
edit, see above --> should be reopened, cheers

**Comment by ZaoQ** [comment]
Please reopen, the situation is described perfectly
