### ISSUE TITLE
Mana Spring Totem 

### ISSUE THREAD

**Issue by sinfer** [SunwellWoW/Sunwell-TBC-Bugtracker#3086]
Description: Mana Spring Totem's mp5 doesnt show in character panel

How it works: Description.

How it should work: It should show the amount of mp5 which comes from the totem
![wowscrnshot_121018_202736](https://user-images.githubusercontent.com/45524181/49752865-4fef4e80-fcba-11e8-9e15-6e194bbd7bdb.jpg)
![wowscrnshot_121018_202743](https://user-images.githubusercontent.com/45524181/49752879-554c9900-fcba-11e8-9938-2409d6a29cbd.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by SunwellTracker** [comment]
Please provide some sources.

**Comment by sinfer** [comment]
Didnt i with the pics? It doesnt show the increase of mp5 in character panel when totem is laid down. Check the pics, on upper there are no totem, above there are
