### ISSUE TITLE
[Zone] Shattrath 

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#309]
**Remove NPCs:**

Added in 2.1:

- [x] Yuula and her Skyguard Nether Ray

- [x] Grok

- [x] Quest: "Speak with the Ogre" from V'eru

Added in 2.2

- [x] High Exarch Commodus (removed in 2.4)
https://wow.gamepedia.com/High_Exarch_Commodus

- [x] Investigator Asric

Added in 2.3:

- [x] Wind Trader Zhareem

- [x] Nether-Stalker Mah'duun

- [x] Quest: "Oooh, Shinies!" from Griftah

Added in 2.4:

- [x] General Tiras'alan 

- [x] Anwehu 

- [ ] Lord Torvos

- [x] Zephyr

- [x] Captain Dranarus (replace with Seasoned Vindicator)

- [x] Whirligig Wafflefry

- [x] Commander Steele

- [x] Quest "Duty Calls" from Dathris Sunstriker

**Move NPCs**

- [x] G'eras() and accomapning G'eras Vindicators () to pre 2.4 position: 
![image](https://wow.zamimg.com/uploads/screenshots/normal/2029-geras.jpg)

- [x] V'eru () to pre 2.4 position: 
![image](https://wow.zamimg.com/uploads/screenshots/normal/15466-veru.jpg)

- [x] Horde BG masters to these positions: 
![image](https://i.gyazo.com/eb72bf7245783df1d8380801ff406796.png)

**Replace NPCs**

- [x] Shattered Sun Marksman with Aldor Marksman/Veteran Vindicator
https://wow.gamepedia.com/Veteran_Vindicator

- [x] Shattered Sun Trainee with Aldor Neophyte

- [x] Shattered Sun Veteran with Seasoned Vindicator

- [x] Shattered Sun Cleric with Aldor Marksman

- [x] Shattered Sun Magi with Aldor Anchorite

**Misc:** 

- [x] Remove 2.3 and 2.4 badge gear from G'eras.

- [x] Missing Braziers: 
To the left behind G'eras 
![image](https://i.gyazo.com/e1ff301fe21d53a2da7e2f04cb98b102.png)
Next to A'dal (to the left in screenshot) 
![image](https://i.gyazo.com/6005960f56bcc33e429d67015845daf2.jpg)
Aldor Rise
![image](https://i.gyazo.com/20a0b4ecef3c2abbf6a1ca5d02a85d0f.png)
![image](https://i.gyazo.com/4a6a39d48cb369fc050976cdb2e64645.png)
Scryer Tier
![image](https://i.gyazo.com/d065eb1f3ab80c0b44d8e0d884cc5a10.png)

- [x] Remove sunwell map under A'dal

- [x] Grand Anchorite Almonen has the wrong gear.

Pre 2.4 (Aldor faction):
https://wow.zamimg.com/uploads/screenshots/normal/37635-grand-anchorite-almonen.jpg
Post 2.4 (Shattered Sun Offensive faction):
https://wow.zamimg.com/uploads/screenshots/normal/72229-grand-anchorite-almonen-grand-anchorite-almonen-in-patch-2-4.jpg

- Missing RP event with Grand Anchorite Almonen. He should sometimes summon lots of Aldor mobs to a'dal. They sit down in a cone formation while he says this speach:

> In accordance with my divine calling, I must share these revealed truths to all who would hear.
> It has been made known to me that inside each of us, the Light resides...
> ...that it is a gift, given freely to all naturally born beings.
> It manifests itself as a feeling, small at first and easily ignored, that confirms truths and subtly prods one to do good.
> Simple kindnesses, charitable deeds, service to those in need. These are all fruits of the Light.
> It rewards those who heed its promptings with blessings, both seen and unseen.
> Personal reservoirs of hope and faith are strengthened, and one's capacity for greater light increases.
> Over the course of time, through obedience to the Light's guidance, one becomes more sensitive to its voice, and its power.
> Great is the healing and blessing power of the Light's most diligent followers.
> Sadly, there are those who wander through mortality in defiance of the Light.
> From these the Light withdraws, until only darkness remains.
> Where there is no light, despair, loathing and rage thrive.
> We are born into a perilous age, where the forces of darkness are determined to bring about our destruction.
> These are the times to find yourselves in unison with the Light.
> Hear my words, and let the Light inside of you confirm the truth of them.
> Embrace the light that is in you, my friends! Deny yourself all darkness...
> We must endure these trying times faithfully, and one day we will find ourselves victorious.
> By the naaru, may it be so.

2.4:
![Image](https://i.gyazo.com/660b391d45ee50279c501aeff986490f.png)
pre 2.4:
![Image](https://i.gyazo.com/e59bd2c1e510a7f3cfd0bda291588784.png)
![Image](https://i.gyazo.com/182c03f948a7948bc0b3e537aae1d285.png)
Noticable in the start of the video:
https://youtu.be/I8Kn7vUr_GQ

https://wow.gamepedia.com/Grand_Anchorite_Almonen
https://www.wowhead.com/npc=19216/grand-anchorite-almonen#comments

- [x] Remove these pillars where BG weekend NPCs spawn: 
![image](https://i.gyazo.com/c5ffffb3254c8d28b180127a63445ef5.png)

- [ ] Remove all of this: 
![image](https://i.gyazo.com/f883b2b4448be7eaa9c7adc49f539355.png)

- [x] Missing Haggard War Veteran at these cords:
![Image](https://i.gyazo.com/9e3627b0ae0a617fab43575f1e2b50c3.png)

He should say "Haggard War Veteran says: Khadgar himself is showing you around? You must have made a good impression, <name>." whenever someone doing City of Light quest passes him.

https://wow.gamepedia.com/Khadgar%27s_Servant

- [x] Mag'har Refugee and Orc Refugee faceplanting in lower city: 
![image](https://i.gyazo.com/943babea827e5b7d8958ec818d0c4e89.png)

- [x] Mob falling through the floor:
![image](https://i.gyazo.com/1770885d0146c6e08f63980b5dc910b6.jpg)

- [ ] Sporeling Refugee (GUID 68526/68525, entry 19155) should be patrolling together through lower city

- [ ] Lost One Refugee (GUID 68558/68558, entry 19162) should be patrolling together through lower city

- [ ] Khadgar should sometimes say: "Don't burden A'dal with mundane questions, (race). This being's will is all that keeps our enemies from crushing this city." when you interact with a'dal

- [ ] Alliance missing BG masters

- [ ] Weekend specific BG masters can be attacked and killed.

- [ ] Losing Gracefully quest RP missing:

https://wow.gamepedia.com/Losing_Gracefully
https://www.youtube.com/watch?v=vteHbRWZ0Ts

- [x] Remove these projectors for daily normal/HC dungeon 
![image](https://i.gyazo.com/21dce5c2f7938cc57c95d07a4512e440.png)

- [ ] Avatar of Terokk hits weak, should be 700-900 on plate. Currently 500-700 on leather
https://www.wowhead.com/npc=22375/avatar-of-terokk#comments

- [ ] Cro Threadstrong (entry 19196) only yells one thing, he should have multiple lines that changes depending on the patch.
http://wowwiki.wikia.com/wiki/Cro_Threadstrong

- [x] Griftah (entry 19227) bugged /say 
![image](https://i.gyazo.com/9e959662382c88b4d285cde4628485ca.png) 

- [ ] These lights are seasonal (midsummer)
![image](https://i.gyazo.com/2341c6f113eb1f47d289bb85220c92b8.png)

- [ ] Anchorite Nindumen should not be walking around. He should be standing still at these cords:
![Image](https://i.gyazo.com/10ca2cba5d74971791ef1c9d450e1155.png)

- [ ] Mounted Neophyte (GUID 69136/69137/69138/69139, entry 19390) 
![image](https://i.gyazo.com/88ef26b39c30cd5cc1461f01b14dea21.png)
![image](https://i.gyazo.com/dae47ce4ee14b6848b3520ca0019548c.png)

All of these mobs should spawn in at the aldor elevator and walk towards Harbringer Erothem.
There should be some RP: https://youtu.be/FqVsZ4RDiCY?t=1m39s
Couldn't find the quotes.
After lining up in front of him the head off towards the tunnel to nagrand. They despawn when they reach the end of the tunnel?

They are seen here: https://www.youtube.com/watch?v=UESp7CNqzSI

After they have moved away Harbinger Erothem will walk up the stairs into the building and this event plays out:

https://youtu.be/gnSY3_nU-tw?t=4m7s

Quotes:

Harbinger Erothem says: Anchorite Nindumen, I have a request to make of you.
Anchorite Nindumen says: Of course, my friend. How may I be of service to you?
Harbinger Erothem says: We've just sent another inexperienced squad into Nagrand. Might you offer a prayer for them?
Anchorite Nindumen says: A noble request. It would be an honor, Erothem.

All the Anchorite Attendants kneel as Anchorite Nindumen and Harbinger Erothem reposition themselves.

Anchorite Nindumen proceeds to say:
    My friends, please join me in humble supplication to the Light.
    Light that we embrace, we beseech thee...
    Into our struggle against the darkness we have sent our children.
    Please bless and protect them, and grant them success over those who seek to do us harm...
    Continue to bless this, our ancient home, we bed.
    Bless us with tolerance for our elven visitors.
    By the Naaru, may it be so. 

Harbinger Erothem says: May it be so. (while starting to stand up)
All Anchorite Attendants stand up, a few of them says "May it be so."

Harbinger Erothem and Anchorite Nindumen move back to their regular positions.

- [ ] Harbinger Haronem (entry 19472) has wrong gear.
2.0: 
![image](https://wow.zamimg.com/uploads/screenshots/normal/15803-harbinger-haronem.jpg)
2.4:
![image](https://wow.zamimg.com/uploads/screenshots/normal/72202-harbinger-haronem-new-skin-with-2-4.jpg)

https://wow.gamepedia.com/Harbinger_Argomen
https://www.wowhead.com/npc=19475/harbinger-haronem#screenshots

- [ ] Neophyte Nemarn should sometimes spawn in near the elevator towards scryers tier, walk to Harbringer Argomen(?) and has a conversation:

    Neophyte Nemarn says: As you command, sir.
    Neophyte Nemarn says: My apologies, sir. I wish I had more to report.
    Neophyte Nemarn says: Sir, I am here to deliver my report from the Scryer's Tier.
    Neophyte Nemarn says: Sir, it's impossible to read anything into their actions.
    Neophyte Nemarn says: Their movements are totally chaotic, as if they themselves know not what they are about.

I was not able to find the other side of the conversation.
https://wow.gamepedia.com/Neophyte_Nemarn

- [ ] Peacekeeper Jadaar should stand next to Griftah. 

- He is missing gossip when you talk to him. "There have been some complaints filed about this... individual. I'm told he's something of a shady character. I am here to determine whether or not this business of his is legitimate... and take action if it proves otherwise."

- Missing RP with Griftah;

From his conversations with Griftah:

    Griftah says: Dangerous out there, innit? Know what ya need? Protection. I can help ya defy death itself! Ya wear this madstone 'round yer neck, see, and then ya be able to come back if ya find yerself in the spirit world! Just a quick jaunt to yer corpse and up ya come, fresh and new! 
    Peacekeeper Jadaar says: You cannot possibly be suggesting that these baubles of yours hold sway over the very fabric of life itself! 
    Griftah says: Ya wanna find out?! 
    Peacekeeper Jadaar says: ...was that a THREAT?! 
    Griftah says: Ah... uh... nah. 

    Griftah says: Hey! Hey, <race>! I be havin' just the thing for ya. Ya ever see a tikbalang? Frightenin' creatures. Prone to stealin' ya away. What ya need is one of my tikbalang wards. Guaranteed to ward all tikbalangs! 
    Peacekeeper Jadaar says: I've never heard of a tikbalang in my life. In fact, the Scryers tell me they can't find a single mention in one of their libraries. 
    Griftah says: Look, man, they didn't live to be writin' about it, okay? 

    Griftah says: Look over here, <class>! I got something for ya. Just what ya need! It's soap, right.. and it's on a rope! No offense, man, but yer a little ripe, know what I'm sayin'? 
    Peacekeeper Jadaar says: Are you insulting our citizens? 
    Griftah says: It's the truth, man. Can't ya smell that? 
    Peacekeeper Jadaar sniffs the air and frowns. He glances over his shoulder. 
    Peacekeeper Jadaar says: That... odor is from Tobias, I believe. 
    Griftah’s frustrated frown disappears into a sly look. 
    Griftah says: ... do ya think he be buyin' soap on a roap, mebbe? 
    Peacekeeper Jadaar rolls his eyes. 

    Griftah says: C'mere, <race>. Ya don't want to be riskin' yerself in a dungeon, do ya? Filthy work, and for what? Some worthless trinket? Nah, what ya need be one of my amulets. Guaranteed to work! 
    Peacekeeper Jadaar says: Truly? "Guaranteed?" We'll have to sit down and talk at length about this "guarantee" of yours, merchant. 

![Image](https://wow.zamimg.com/uploads/screenshots/normal/27414-griftah-griftah-conversation-hilarious.jpg)

- Griftah should do emote animations if you /wave and /no at him.
https://www.wowhead.com/npc=19227/griftah#comments:id=200955

http://wowwiki.wikia.com/wiki/Peacekeeper_Jadaar
http://wowwiki.wikia.com/wiki/Griftah

### **World's End Tavern**

- [ ] Lots of Midsummer festival items that shouldn't be there.
![Image](https://i.gyazo.com/650d0cd25c282c2375fb83ddc1a0b8f5.jpg)

- [ ] Missing stand up RP.

Albert Quarksprocket should say the following right before Perry goes on stage; "Thank you all for coming tonight. Now put your hands together to welcome Shattrath's best, Perry Gatner."

And; "Perry Gatner! What an Act! The cantina is open all night long, so please, stay and enjoy yourselves!", after his show is over.

Read link for all the info you need.
http://wowwiki.wikia.com/wiki/Perry_Gatner

- [ ] Ezekiel sometimes forgot his path and runs through walls in centre of shatt.

- [ ] Lonika Stillblade missing random /say 

-    /s Never leave home without ample supplies of flash powder, especially when working with others. I guarantee someone will run out every time.
    /s When the choice comes down to handing out materials or letting the poor sap die, I help... most of the time.
-   /s Swords, claws, daggers, of course -- I've trained rogues in the use of them all. Now maces, I won't touch maces and I won't instruct any rogue who gets it in his head to wield one.
    /s There's nothing stealthy about a mace. You're in for a noisy kill and a long cleanup if you go that route.
-   /s When I first set up my rogue academy in Shattrath, it wasn't nearly this crowded. Then, the refugees started flooding in and the naaru needed very available building to house them.
  /s I've closed the doors to my academy for now, but it's not permanent. I'll find a new place to set up.
  /s Then, a new generation of rogues will learn such staples as the gouge'n'grin, combat looting, and blaming someone else for breaking polymorph. And who can forget the central rule of roguery --- real rogues don't feint.
-   /s My early classes are always filled with bright-eyed young lads. Few make it past the first test, though.
   /s I've given up on shouting 'when I yell vanish, you need to vanish.' They never listen. Now, the test simply kills the inept.
-   /s The trick to using evasion is realizing that the best fifteen seconds of your life are often the last. 

http://wowwiki.wikia.com/wiki/Lonika_Stillblade
https://www.wowhead.com/npc=22442/lonika-stillblade#comments

- [ ] Kylene should not be a cooking trainer until 2.3, should respond to emotes:

    /applaud or /bow (She will respond with the /curtsey emote.)
    /dance (She will respond with the /dance emote.)
    /flex (She will respond with the /laugh emote.)
    /kiss (She will respond with the /shy emote.)
    /rude (She will respond with the /rude emote, and a chat message saying "Kylene returns the rude gesture to <name>.")
    /shy (She will respond with the /kiss emote.)
    /wave (She will respond with either "What's your poison, <boy/girl>?" or "What can I get you today, <race>?") 

http://wowwiki.wikia.com/wiki/Kylene

- [ ] Leatei and Kylene should walk around and sometimes dance with each other. Currently they walk all over the furniture and dance everytime they stop moving.

https://www.wowhead.com/npc=19064/leatei#comments

- [x] Raliq the Drunk should be friendly

- [ ] Arcanist Savan wrong location, he should be in scryer's tier, currently in world's end taven
https://www.wowhead.com/npc=23272/arcanist-savan#comments
http://wowwiki.wikia.com/wiki/Arcanist_Savan

**Comment by Silroth** [comment]
Nether-Stalker Mah'duun and Wind Trader Zhareem were added in 2.3, there is no proper reason to remove them as they give incentive to people to do lvl 70 dungeons and heroics.

Zephyr removal of this NPC also has no proper reason, for her to teleport people to Caverns of Time people need to have Revered reputation with Keepers of Time, her presence there doesnt have any huge impact on gameplay unlike 2.4 badge vendors for example.

**Comment by notsofamous** [comment]
I don't think people would need more motivation to do heroics and dungeons in the beginning. They need rep, attunements, items, primal nether and help out guildies. IMO it would just backfire as people would gear quicker and end up doing less dungeons because of it.

Zephyr could stay in game as it's just a quality of life thing.

**Comment by Silroth** [comment]
They could just change the reward from daily dungeon/heroic to normal gold and the problem would be fixed without having impact on the characters gearing up.

**Comment by notsofamous** [comment]
Corecraft video from aldor rise: https://www.youtube.com/watch?v=Cjsr0Gf7zmc&feature=youtu.be
Changes/improvements done on hellfire2 (free code): https://github.com/Looking4Group/L4G_Core/issues/441

**Comment by notsofamous** [comment]
https://github.com/Looking4Group/L4G_Core/issues/441

**Comment by Evolvee** [comment]
nice netherwing screenshot u got there xd
