### ISSUE TITLE
[Paladin][Spell] Seal of Command//Vengeance Talent

### ISSUE THREAD

**Issue by Testimonia** [SunwellWoW/Sunwell-TBC-Bugtracker#3092]
Description: 
Seal of Command swing crits does not trigger Vengeance

How it works: 
If you crit with Seal of Command swing (not Judgement), Vengeance doesnt  trigger

How it should work: 
Vengeance should trigger from Seal of Command swing crit

Source (you should point out proofs of your report, please give us some source): 
Patch 1.11.0 (2006-06-20):
Clarified tooltip.
Seal of Command critical hits can now trigger Vengeance.
Since Patch 1.11, Seal of Command proc will have approximately 0.5 second delay before the animation begins and the Holy damage is incurred, instead of having the proc occur instantly with the swing of the attack. This is considered a good change, since if the normal swing is a critical strike and Vengeance is triggered, the Seal of Command proc will be affected by the buff.

So, it should trigger, and scale with, vengeance.

**Comment by akrom23** [comment]
Seal of Command does trigger Vengeance and scale with it - just tested.
![wowscrnshot_121518_142228](https://user-images.githubusercontent.com/1035215/50043528-01550200-0076-11e9-861a-7e623451eb27.jpg)


@Testimonia Needs more info.

**Comment by Testimonia** [comment]
i play holy since saturday so i cant say to 100% but i think it does, i remeber it worked after the server fix on friday or when it was.
