### ISSUE TITLE
Torch of retribution not changeable in combat

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#3094]
You need to equip https://classicdb.ch/?item=10515 to complete a quest, however you cannot do it in combat, nor can you equip a weapon in combat if you are currently wielding the torch.

**Comment by akrom23** [comment]
This item is considered as q item, not a weapon.
@babno Got some proofs?

**Comment by babno** [comment]
It's both a quest item and a weapon, like the shadowmoon valley goggles or the Monogrammed Sash are quest items that are also gear. 

https://classicdb.ch/?item=10515#comments

It takes up both weapon slots as a two handed weapon, you attack with it with it's unique .5 second attack speed which deals damage and raises unarmed skill (since needed to be usable by all classes).

**Comment by babno** [comment]
Side note I'd greatly prefer the critical issue of #4090 is addressed before this.
