### ISSUE TITLE
Quest: Showdown - Goc cannot be attacked

### ISSUE THREAD

**Issue by Xymos** [SunwellWoW/Sunwell-TBC-Bugtracker#3095]
The Quest: http://db.hellfire-tbc.com/?quest=10742

When you use Rexxar's Battle Horn to start the fight, nothing happens.
Unable to complete the quest, Goc cannot be attacked.

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3015
