### ISSUE TITLE
Early herbs are too few.

### ISSUE THREAD

**Issue by Knitless** [SunwellWoW/Sunwell-TBC-Bugtracker#3096]
I don't know about later herbs, but early herbs are way too few. Having herbalism, I see 50:1 mines to herbs. No one is able to pick herbs on this server. Mining nodes come back fast and are everywhere, but there is no way to keep up with herbalism, and you have to spend hours and hours getting to 100.

There was a previous issue multiple days ago, and it was marked resolved. This is not resolved at all. There are way too few herbs. They need to come back faster and be more frequent.

**Comment by badmannerkid** [comment]
herbs in outland are very few as well, i'd say same ratio as mine to herbs in early zones. worth looking at outland as well
