### ISSUE TITLE
[Quest] Frankly, It Makes No Sense...

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#3106]
Description: / How it works: 

- clicking the control units is not doing anything --> cant control one of the scorpions
- the one in the middle is even untargetable
- quest cant be done?

Source (you should point out proofs of your report, please give us some source): 

![grafik](https://user-images.githubusercontent.com/45068171/49766496-c2b9f300-fcd5-11e8-85ca-6b94b7620759.png)

**Comment by FrauHolle86** [comment]
edit, see above

**Comment by Dootz** [comment]
fixed, live
