### ISSUE TITLE
Mobs Use Mana Drain/Burn vs Classes without Mana

### ISSUE THREAD

**Issue by OMEGALULW** [SunwellWoW/Sunwell-TBC-Bugtracker#3111]
Description: Mobs like the Marshfang Ripper in Zangarmarsh cast "Drain Mana" vs non-Mana classes.

How it works: ^

How it should work: Mobs shouldn't Mana Drain / Burn when the player has no mana

Source (you should point out proofs of your report, please give us some source): I'm sure one could be found, a lvling video of a rogue of warrior in the shimmering flats fighting basilisks with mana burn perhaps, but "it makes no sense" is good enough for now lol

**Comment by koostosh** [comment]
> but "it makes no sense" is good enough for now lol

no, lol
