### ISSUE TITLE
Silence, priest shadow tree.

### ISSUE THREAD

**Issue by Ethugx** [SunwellWoW/Sunwell-TBC-Bugtracker#3112]
Description: 
Silence from the priest shadow tree is not correctly gaining 20% range from Shadow Reach talent.

How it works: 
Silence gets 0% range and is stuck at 24 yards.

How it should work: 
Silence Should gain 20% range from Shadow Reach talent and be 30 yards.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Works fine.
0.2 * 20 + 20 = 24.
