### ISSUE TITLE
ROGUE kick

### ISSUE THREAD

**Issue by Josephienvandermeersch** [SunwellWoW/Sunwell-TBC-Bugtracker#3113]
Description:  Rogue kick does not always work to interrupt the caster even tho it does damage so it didnt miss.

How it works: 
Kick no interrupt 30% of the time. Still does dmg.

How it should work: 
If it doesn't miss it should always Interrupt.

Source (you should point out proofs of your report, please give us some source): 
This thing is way to random to screenshot or video.

**Comment by akrom23** [comment]
@Josephienvandermeersch Still needs screenshot with combat log.

**Comment by akrom23** [comment]
No response.
