### ISSUE TITLE
Ethereal Soul Trader Pet -  Cannot sell items to Soul Trader. 

### ISSUE THREAD

**Issue by orlow1ar** [SunwellWoW/Sunwell-TBC-Bugtracker#3115]
Description: 
Says: You cannot sell items to this vendor, Should be able to sell items to it.

How it works: 
Not allowed to sell items to vendor.

How it should work: 
Pet should buy items from players. 

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/22646050/49767357-27f5f000-fca6-11e8-925f-8990ef8aeed9.png)

**Comment by Jseay1313** [comment]
https://www.wowhead.com/npc=27914/ethereal-soul-trader#comments

multiple comments on here that say you cant sell to him, including ones as early as 3.0 and as late as 5.7, nothing in the patch notes ever suggest that changes either.

**Comment by Aloise3** [comment]
It still goes against the description on the shop which is not okay.
