### ISSUE TITLE
Carrot on a stick - Druid Flight Form

### ISSUE THREAD

**Issue by KayleeFrye1** [SunwellWoW/Sunwell-TBC-Bugtracker#3116]
Description: 
Carrot on a stick doesn't give any movement increase in flight form

How it works: 
0% increase

How it should work: 
3% increase

Source (you should point out proofs of your report, please give us some source): 
https://puu.sh/CfF9z/7b3a0b6532.jpg

**Comment by sinfer** [comment]
Shouldnt it affect only mount speed and not forms? By what you are saying here it should affect travel form and ghost wolf also.

**Comment by zkillertheman** [comment]
It should NOT work, there's a special trinket you get when you complete the 280% flightform quest that is specifically designed to work with flightform, this is a from not a mount.

**Comment by KayleeFrye1** [comment]
Flight Form is a mount- and it should work as it has always done before

**Comment by notsofamous** [comment]
It shouldn't, druids have a special trinket to increase their flight form speed.

**Comment by sinfer** [comment]
You dont mount on form, do you?
