### ISSUE TITLE
Untargetable Corpses chasing and attacking

### ISSUE THREAD

**Issue by VelvHammer** [SunwellWoW/Sunwell-TBC-Bugtracker#3117]
Description: In Terokkar Forest inside Tomb of Lights we fould some dead corpses that were untargetable which started chasing us and attacking us with no de-aggro range.

How it works: Walk to the farthest back room and look for corpses of draenei they will attack you and move when you get close.

How it should work: Shouldn't do anything.

Source (you should point out proofs of your report, please give us some source):

**Comment by username-is-not-taken** [comment]
This happened to me as well today. It's inside tomb of lights as mentioned (47,54 in terokkar) and it revolves around the quest "The vengeful harbinger".

Screens:
![vengefulharbinger1](https://user-images.githubusercontent.com/45629295/50160387-82f89a00-02d9-11e9-8ee6-4fd56e23cdf0.jpg)

![vengefulharbinger2](https://user-images.githubusercontent.com/45629295/50160389-85f38a80-02d9-11e9-887f-9ea2aee442c0.jpg)
~30 minutes later - still there


And the combat log confirming it's the quest mob:

![vengefulharbinger3](https://user-images.githubusercontent.com/45629295/50160412-9572d380-02d9-11e9-8fb1-8ce8f0b7d48c.png)
