### ISSUE TITLE
[Quest] The Fel and the Furious

### ISSUE THREAD

**Issue by FrauHolle86** [SunwellWoW/Sunwell-TBC-Bugtracker#3118]
Description: / How it works: 

- Control Console cant be used / cant be clicked
- i started running around and killing Infernals by "right clicking" on them
- but thats obviously not how the quest should work =))

**Comment by ghost** [comment]
Causes game to crash as well.

**Comment by doomnyx** [comment]
cannot access the console, quest cannot be completed.

**Comment by username-is-not-taken** [comment]
Still not working - clicking on the console gives a debuff called "fatal attraction" which disappears after one second. Error message displayed on the screen is "you have no target."
