### ISSUE TITLE
Evil Draws Near quest bug

### ISSUE THREAD

**Issue by VelvHammer** [SunwellWoW/Sunwell-TBC-Bugtracker#3119]
Description: Unable to turn in the quest "Evil Draws Near" quest in Terokkar. Quest says complete but quest giver still has the silver question mark above head.

How it works: Not accepting quest when completed

How it should work: Accept quest when completed

Source (you should point out proofs of your report, please give us some source): 
![bugged](https://user-images.githubusercontent.com/45774868/49768834-bae55900-fcab-11e8-8a01-92bd8114fba1.png)

**Comment by Azathothh** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2757
