### ISSUE TITLE
Delete this forgot we're technically in 2.4.3 and not a fresh 2.0

### ISSUE THREAD

**Issue by Meekuh** [SunwellWoW/Sunwell-TBC-Bugtracker#3120]
Description: Priest Fear Ward(delete this forgot we're technically in patch 2.4.3)

How it works: All Alliance priests get fearward, i dont know if horde are getting it aswell, im hoping not

How it should work: Only dwarf priests should be getting fearward

Source (you should point out proofs of your report, please give us some source):

**Comment by jockeboschko** [comment]
just close
