### ISSUE TITLE
Nethermine Ravager missing

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#3121]
Description: Nethermine Ravager missing in SMV

How it works: no mobs in the area

How it should work: mobs in the area. Important for hunters so they can tame a 70 ravager.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/npc=23326/nethermine-ravager

**Comment by Silroth** [comment]
They are not tameable until 2.2 patch.

**Comment by MiekZer** [comment]
We're supposed to be 2.4.3
