### ISSUE TITLE
[ITEM] Necklace of the Deep 2.1 patch item

### ISSUE THREAD

**Issue by lorderheller** [SunwellWoW/Sunwell-TBC-Bugtracker#3122]
**Description:** Necklace of the deep is 2.1 item, and is available at the moment.

**How it works:**  Should not be available.

**How it should work:**  https://www.wowhead.com/item=32508/necklace-of-the-deep Added in patch 2.1.0.6624

**Source (you should point out proofs of your report, please give us some source):** 

https://www.wowhead.com/item=32508/necklace-of-the-deep Added in patch 2.1.0.6624

**Comment by MadderThenMad** [comment]
Also all Apexis items...

https://www.wowhead.com/item=32655/crystalweave-bracers

**Comment by lorderheller** [comment]
BUMP. All post 2.1 items in easy-to-access post.

https://github.com/ccshiro/cc-buglist/issues/1046

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4085
