### ISSUE TITLE
plans: ragesteel shoulders not in loot table

### ISSUE THREAD

**Issue by ghertruda** [SunwellWoW/Sunwell-TBC-Bugtracker#3123]
Description: I have farmed about 300 elementals in Shadowmoon valley: Enraged Air/Water/Fire/Earth Spirit and none of them dropped the ragesteel shoulders pattern(preraid bis for warriors), i have a big suspision that it is missing in a loot table, because the drop % is the same as Ragesteel gauntlets and those dropped in about 50 kills.

How it works: Doesnt show any sign of ragesteel shoulders pattern existing

How it should work: It should have 0,5% dropchance from water and air spirits, and 1% from fire and earth spirits.

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?item=33174

**Comment by notsofamous** [comment]
Was added in a later patch

**Comment by ghertruda** [comment]
so were khorium pants and those are ingame

**Comment by Kiszh** [comment]
It seems there are other items that were added later on the loot tables though and the loot is upgraded as it were in 2.1. Shouldn't it be either everything is there or everything is removed? Not half in half out.

**Comment by leylandpaladin** [comment]
Killed over 150 elementals trying to get this recipe, but no drop, so can confirm.

Yes it was added in 2.1 but tons of items are in game and being used by players (felsteel tank set for example). 

This item is preraid bis for arms/fury warriors and retribution paladins.

**Comment by foxxhound** [comment]
Bump

**Comment by naevys** [comment]
The pattern for these was added in Patch 2.2.0

https://wowwiki.fandom.com/wiki/Ragesteel_Shoulders#Notes
https://wowwiki.fandom.com/wiki/Patch_2.2.0#Blacksmithing
