### ISSUE TITLE
Ringo for A Little Help From My Friends runs too far for mobs

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#3126]
Description: 
Ringo for A Little Help From My Friends runs too far for mobs

How it works: 
He goes like 80 yards to fight some mobs.

How it should work: 
Shouldn't be running so far away.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1166
