### ISSUE TITLE
Wand / Shoot: Changing target while shooting = Broken

### ISSUE THREAD

**Issue by grand-lotus-iroh** [SunwellWoW/Sunwell-TBC-Bugtracker#3130]
How it works:
While attacking with my wand, I noticed that when I target A and start shooting my wand, when I target B, my wand keeps shooting on target A.

How it should work:
When you change target, your wand should change target as well (I target A, shoot it, then target B, my wand should be shooting target B).

**Comment by ujellyx** [comment]
The same thing is happening with Auto Shot on a Hunter. Guess this also happens with melee-classes. Reported like a week ago - still not fixed :( #2517

**Comment by grand-lotus-iroh** [comment]
Status update please? Can you please fix this? ETA>?
