### ISSUE TITLE
Alchemy Mastery Respeccing incorrect.

### ISSUE THREAD

**Issue by puggless** [SunwellWoW/Sunwell-TBC-Bugtracker#3136]
Description: After completing any given alchemy mastery (Elixir, Potion or Transmute) you should be able to unlearn the specialization for 150g, then retrain a different new mastery for free. 

How it works: Once you unlearn a mastery the three NPC's instead give the intro quest for the mastery. 

How it should work: After completing any given alchemy mastery (Elixir, Potion or Transmute) you should be able to unlearn the specialization for 150g, then any of the three NPC's should give you a dialogue option to learn the new specialization for free. 

NPC's in question
https://www.wowhead.com/npc=22427/zarevhi
https://www.wowhead.com/npc=17909/lauranna-tharwell
https://www.wowhead.com/npc=19052/lorokeem
Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/FMTopGJ
https://imgur.com/a/g5qdoGq

**Comment by MiekZer** [comment]
Quick question for the op cause I didn't understand the issue but interestes:
So we can all learn a cheap mastery then spend 150g to learn the transmutation mastery for free?? Or do we have to give him primal might?

**Comment by notsofamous** [comment]
I don't think this is accurate. Do you have any source for this?

**Comment by puggless** [comment]
> Quick question for the op cause I didn't understand the issue but interestes:
> So we can all learn a cheap mastery then spend 150g to learn the transmutation mastery for free?? Or do we have to give him primal might?

Yes you should be able to do either of the cheaper quests (potion/elixir) than respec for 150g into transmute. This is how it was on blizzard servers. 

> I don't think this is accurate. Do you have any source for this?

It is. I played during retail TBC and did this. This was the intended mechanic. The transmute mastery quest is specifically meant to be a noob trap. 

See comments
https://www.wowhead.com/quest=10899/master-of-transmutation#comments
https://www.wowhead.com/forums&topic=33627
https://www.mmo-champion.com/threads/646398-Alchemy-Change-specialization

**Comment by Hahahahahahahahahahahahahahahahahahah** [comment]
#3201
