### ISSUE TITLE
[Shaman][Spell] Windfury 

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#3138]
Description: 
Windfury weapon does not appear to have an internal cooldown of 3s. Doesn't appear to have an internal cooldown at all

How it works: 
Windfury weapon is proccing constantly, worth testing but it clearly doesn't have an internal cooldown at all. Hopefully the shamans aren't too angry about me reporting this

How it should work: 
Windfury should have a 3s internal cooldown for each weapon applied

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Windfury_Weapon

**Comment by Jseay1313** [comment]
nice find, I guess this explains a lot on why meters with a shaman in group have been massive

**Comment by akrom23** [comment]
@badmannerkid Can't confirm. Just observed my combat log and both Windfury Attacks had at least 3 sec cooldown.

**Comment by Kentamentiu** [comment]
You can use different ranks on offhand/mainhand and get separate cds. Other than that, I haven't noticed the cd not working.

**Comment by Aftershokx** [comment]
https://blue.mmo-champion.com/topic/18050-tbc-enhancement-shaman-faq/ 
Wf does have 3s icd

**Comment by Aftershokx** [comment]
Also if u can use other ranks of wf on other weapon and its providing bonus chance - its also a bug https://wow.gamepedia.com/windfury_weapon patch 2.1 update

**Comment by StylerTyler** [comment]
fake news

**Comment by Robin-Combeau** [comment]
I searched a bit and there is a few posts like this one wowhead forum on 2.4.3 and previous versions : 
- https://www.wowhead.com/forums&topic=33843 : Comments here from 2.4.3 states that : "once it procs, it cannot proc again for at least 3 seconds."

Don't know if that's not already the case on sunwell server tho.

**Comment by FrauHolle86** [comment]
the guide provided by Aftershokx is pretty clear....

- we are in patch 2.0.3 atm
- the issue is, that WF5 on MH and OH proccs all the time --> inner 3sec CD is required
- which means, either MH nor OH can procc for 3sec after a WF procc (if u have WF5 on both weapons)
- if there is a conflict between MH & OH coz of same weapon speed, WF will procc on the MH
- in Patch 2.0.3 you can use WF5 on your MH and WF4 on your OH to work around the 3sec inner CD (MH and OH have a separat 3sec inner CD)
- with patch 2.1.0 (BT), this trick is no longer available and MH & OH share the same inner 3sec CD reguardless which WF rank you use

**Comment by akrom23** [comment]
![wowscrnshot_122818_205407](https://user-images.githubusercontent.com/1035215/50526494-bc53b580-0ae2-11e9-86e3-f8f02a0c6cea.jpg)
Same rank on both weapons - at least 3 sec cd.

![wowscrnshot_122818_205632](https://user-images.githubusercontent.com/1035215/50526552-13f22100-0ae3-11e9-9c1d-2996bc22a846.jpg)
Different rank - still the same.

Just give me your combat logs.

**Comment by FrauHolle86** [comment]
![wf procc1](https://user-images.githubusercontent.com/45068171/50528190-16597880-0aed-11e9-8ee5-f082e5977c31.jpg)
![wf procc2](https://user-images.githubusercontent.com/45068171/50528191-16597880-0aed-11e9-8453-01cd84acdd8f.jpg)
![wf procc3](https://user-images.githubusercontent.com/45068171/50528192-16597880-0aed-11e9-9f9b-e2e3456d453f.jpg)

these are all with WF5 on both weapons... after short term testing, i had WF proccs within 2sec apart but not lower... i will keep an eye on it tho...

**Comment by FrauHolle86** [comment]
also i would like to raise the question: WF proccs can be dodged and parried, even if you are style hitcapped? does it only count for "misses"? plz educate me =)

![wf dodged](https://user-images.githubusercontent.com/45068171/50528314-e5c60e80-0aed-11e9-8cae-f907b0c5dd09.jpeg)

**Comment by akrom23** [comment]
@FrauHolle86 I don't see melee attacks.
And what about yur talents? Got something that improve widfury weapon?

**Comment by FrauHolle86** [comment]
hi, ive the standard Enh specc 2/45/14 with improved WF damage

![grafik](https://user-images.githubusercontent.com/45068171/50598046-cfcb9b80-0ea9-11e9-9127-27295730496c.png)

do u need to see the meele attacks regarding "WF proccs" or regarding "WF can be dodged"? i disabled meele attacks in order to get a better overview of WF proccs in these pictures

**Comment by akrom23** [comment]
WF proccs.
Could you send me your talents tree?
Tested on local server for 30 minutes - still works fine.

**Comment by FrauHolle86** [comment]
talent tree:

![grafik](https://user-images.githubusercontent.com/45068171/50605319-4c6a7400-0ec2-11e9-880c-fe08e228f920.png)


is the inner CD getting reduced by any kind of haste like Bloodlust / Flurry / HastePotions / Drums etc?
or maybe it is just an issue with the combat log timers? or an issue in coding with recognizing milliseconds - so there is only "2 sec" and "3 sec" but nothing in between?
tested 30min..... sometimes i got WF proccs 2sec apart from each other (every 4-7th mob), but never less then 2sec.

![grafik](https://user-images.githubusercontent.com/45068171/50606925-bafe0080-0ec7-11e9-8b7c-b24a8523973c.png)

![wf procc 2](https://user-images.githubusercontent.com/45068171/50607225-be45bc00-0ec8-11e9-9eb8-5e129c3aa72c.png)

**Comment by akrom23** [comment]
Combat log does not show miliseconds.
Cooldowns are stored in seconds.

**Comment by akrom23** [comment]
Tested with your build for 30 min - still nothing - works fine on local server.
Maybe we'll need some kind of addon to see if combat log lies about that timestamps.

**Comment by FrauHolle86** [comment]
hmm... what is the time between MH and OH hitting a mob (with same weapon speed)? imo there should be no delay inbetween - they should hit exactly at the same time... so the OH is not eating up to many WF proccs from the MH.

but as it seems, there is a delay right now integrated?
Screenshot 1:
- 19:41:04 and 19:41:05 [Meele Swing]

Screenshot 2:
- 19:53:24 and 19:53:25 [Meele Swing]
- 19:53:26 and 19:53:27 [Meele Swing]

**Comment by akrom23** [comment]
@FrauHolle86 
On the second screenshot I see melee swing done in 19:53:22, windfury done in 19:53:23 and next windfury done in 19:53:25. So combat log somehow displayed wrong the first windfury attacks - melee done in 19:53:22, so the next windfury could be done in 19:53:25 - that's okay.
I think that's problem with combat log or it was a lag.

Windfury Weapon proc from the main hand (if not missed).

**Comment by FrauHolle86** [comment]
- imo [19:53:23 - Stormstrike] triggered the WF procc at 19:53:23, not the meele swing before at 19:53:22
- i think 1 big issue is, that there is a delay between MH and OH hitting the mob (see post above)
- if you check Screenshot 1, u can see that the first WF procc is getting triggered by a meele swing at 19:41:00 and the second WF procc is getting triggered right after with the next meele swing (ignore Stormstrike). these weapons got a 2.7sec speed & with Flurry even faster --> there is no way WF should get triggered within 2 meele swings, unless there is a delay between MH and OH
- e.g. MH hits the mob and triggers WF. OH hits the mob ~0.3sec after that. MH hits mob ~2.7sec after the first hit. OH hits mob 3sec after the first hit and triggers WF again

**Comment by akrom23** [comment]
I think that flurry buff changed your weapon speed - that's why WF proc faster.
