### ISSUE TITLE
[Zone] [Eversong Woods] 

### ISSUE THREAD

**Issue by Piootrek** [SunwellWoW/Sunwell-TBC-Bugtracker#314]
### **TO DO:**

- [x] 1. Tained Arcane Wraith (15298) chase players but doesn't melee them.
_? works fine for me_
- [x] 2. NPC 15298 - Tainted Arcane Wraith doesn't use spell Slow (http://db.hellfire-tbc.com/?npc=15298#abilities)
_? works fine for me_ :(
**EDIT: Still doesn't cast it**
- [x] 3. NPC 15668 - Grimscale Murloc doesn't use spell Fear (http://db.hellfire-tbc.com/?npc=15668#abilities)
**EDIT: They cast this Fear spell on themselves instead of on players**
- [x] 4. NPC 15648 - Manawraith doesn't use spell Arcane Residue (http://db.hellfire-tbc.com/?npc=15648#abilities)
**EDIT: It dies with appropriate emote but there is no buff on players**
- [x] 5. NPC 15669 - Grimscale Oracle's Flash Heal heals too litle (4) (http://db.hellfire-tbc.com/?npc=15669#abilities)
**EDIT: Still heals for 4.**
- [x] 6. NPC 16294 - Aldaron the Reckless Fireball does too low damage(3-4) (http://db.hellfire-tbc.com/?npc=16294#abilities)
**EDIT: No changes**
- [x] 7. NPC 15407 - Chieftain Zul'Marosh Cleave does too low damage(1) (http://db.hellfire-tbc.com/?npc=15407#abilities)
**EDIT: No changes, autoattacks for ~30, Cleave damage for 2.**
- [x] 8. NPC 15647 - Mana Stalker Moonfire does too low damage(2) (http://db.hellfire-tbc.com/?npc=15647#abilities)
**EDIT: Still hits for 2**
- [ ] 9. Quest 8490 Powering our Defenses - after completing quest stays in quest log as incomplete (visual bug only) (http://db.hellfire-tbc.com/?quest=8490)
### **DONE:**

- [x] 1. NPC 15649 - Feral Dragonhawk Hatcling doesn't use any spells (http://db.hellfire-tbc.com/?npc=15649#abilities)
- [x] 2. NPC 15650 - Crazed Dragonhawk doesn't use any spells (http://db.hellfire-tbc.com/?npc=15650#abilities)
- [x] 3. NPC 15294 - Feral Tender doesn't use spell Renew (http://db.hellfire-tbc.com/?npc=15294#abilities)
- [x] 4. Quest 8488 Unexpected Results - after quest NPC spams with completing quest infinitely (https://imgur.com/a/AwRHsBb) even after relog. Only killing NPC helps.

**Comment by Kokaina** [comment]
List updated.

**Comment by qtong** [comment]
NR 3 on to DO is still a problem
