### ISSUE TITLE
Jadefire Trickster

### ISSUE THREAD

**Issue by NineCorrupted** [SunwellWoW/Sunwell-TBC-Bugtracker#3140]
Description: 
Mind Control making me fall through the floor

How it works: 
He mind controls me and makes me run through the floor and fall to my death.

How it should work: 
Not making me fall through the floor lmao

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/45781199/49781328-c3935a80-fcbe-11e8-8cfb-5d1b07eb7b7f.png)

**Comment by Zamesi** [comment]
Same thing happened to me. 
Monster in question: http://db.darkwizard.pl/?npc=7107
Spell: http://db.darkwizard.pl/?spell=26079
Location: Felwood, northern part
![inkedwowscrnshot_121118_114619_li](https://user-images.githubusercontent.com/45551496/49792393-4bb74580-fd3b-11e8-9913-c63b7a50b01b.jpg)

**Comment by Mikov1605** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3249#issuecomment-447479979
Fixed
