### ISSUE TITLE
[Core][Reputation] Shattered Halls

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#3141]
Description: 
Shattered Halls currently does not reward enough reputation for full clearing the dungeon. It awards around 800 reputation on normal, with most mobs rewarding 6 rep per kill

How it works: 
Shattered Halls currently does not reward enough reputation for full clearing the dungeon. It awards around 800 reputation on normal, with most mobs rewarding 6 rep per kill

How it should work: 
Kills should reward 10-12 reputation each depending on the mob, not 6 reputation for some elite mobs. For reference, the lvl 61 mobs outside the instance award 5 reputation each until 2999/3000 Friendly.
A full clear of shattered halls normal should award you 1600 reputation for killing every mob/boss in the instance

Source (you should point out proofs of your report, please give us some source): 
http://www.tentonhammer.com/guides/hellfire-peninsula-reputation-guide-9f1b89af-7d14-47ea-a53f-c0612485d351

**Comment by badmannerkid** [comment]
#157

**Comment by badmannerkid** [comment]
#157

**Comment by ghertruda** [comment]
+1

**Comment by letsfixthis** [comment]
+1 HIgh Priority now!
