### ISSUE TITLE
shattered halls reputation gain (major time waste if not fixed)

### ISSUE THREAD

**Issue by ghertruda** [SunwellWoW/Sunwell-TBC-Bugtracker#3143]
Description: 
The reputation from shattered halls is bugged / decreased

How it works: 
reputation from a regular mob is 6 
![shh mob](https://user-images.githubusercontent.com/36400119/49782594-287a9f00-fd17-11e8-9f2c-be1ee78e3c39.png)
and reputation from bosses is 60 ![shh boss](https://user-images.githubusercontent.com/36400119/49782592-27497200-fd17-11e8-9ced-a2dfcd99dd8c.png)
How it should work: 
reputation from mobs should be 12 and reputation from bosses 150

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?npc=16594 example of a normal mob
http://db.darkwizard.pl/?npc=16807 example of boss

**Comment by Proseccobabe** [comment]
+1

**Comment by Jseay1313** [comment]
Just did 3 runs and got 12 rep per mob and 120 from bosses (not 150) not sure what the issue is with it being different, but even based on the boss rep its bugged in some form.

**Comment by siof** [comment]
#3141
