### ISSUE TITLE
Diss Enchanting

### ISSUE THREAD

**Issue by BestVallen** [SunwellWoW/Sunwell-TBC-Bugtracker#3145]
Description: 
Problem is few items. I have rough bronze cuirass, rough bronze shoulders and runed copper belt. This item is craft from Bs low lvl, and i cant diss it. At blizzlike i could diss any of green items. Its a bug cous rough bronze leggins can diss normally. Its same item of set.

How it works: 
Can't diss the item.

How it should work: 
I could easy diss it without any problem.

Source (you should point out proofs of your report, please give us some source):

**Comment by rajoe** [comment]
I second everything he said about that bug.
