### ISSUE TITLE
Conjured Manna Biscuit not acting as bread for pets

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#3148]
Should be breads for pet that can eat breads.
It's not the case actually.

**Comment by rajoe** [comment]
pets cannot be fed with conjured food

**Comment by tjmitchell1** [comment]
@rajoe Thats not true at all. from wowwiki: Pets that eat bread can eat food conjured by mages.

Thats been a thing since vanilla.

Played a hunter for 14 years.
