### ISSUE TITLE
Enchanting Limited Supply Formulas Restock [Enchanting skillup blocker]

### ISSUE THREAD

**Issue by MadderThenMad** [SunwellWoW/Sunwell-TBC-Bugtracker#3154]
Description: 

There is a number of recipes which according to wowhead and common logic have far to long respawn time (even in terms of blizzlike) - our population is far much more then blizzlike therafore formulas should respawn even faster.

How it works: 

https://www.wowhead.com/item=16243/formula-runed-arcanite-rod#comments
https://www.wowhead.com/item=25848/formula-runed-adamantite-rod
https://www.wowhead.com/npc=19663/madame-ruby -> (all of her limited supply enchanting recipes)

It seems like respawn time for those recipes is at least 2 hours yet according to comments on wowhead it should be at max 15 minutes. -> consider the fact that our realm has over 10k pop right now which is 3 times what TBC offered. All the Rod Formulas are enchanting skillup blockers (you cannot enchant without a correct rod).

How it should work: 

Restock times for those recipes should be no more then 15 minutes.

Source (you should point out proofs of your report, please give us some source):

**Comment by zapsuu** [comment]
Bump, it is really big problem. Atm on every restart server stay always around 10 ppl for this recipe. They camp to sell this recipe on ah or for enchanting.
