### ISSUE TITLE
[Druid] Shifting doesn't remove Frost Shock slow debuff.

### ISSUE THREAD

**Issue by rajoe** [SunwellWoW/Sunwell-TBC-Bugtracker#3157]
Description: I got attacked by an enemy shaman and when he Frost Shocked me I switched to Travel Form in order to get rid of the movement impairing debuff but it didn't go away. When I switched back to NE form it didn't remove the debuff either.

How it works: The movement impairing effect of Frost Shock persists upon shifting between NE and Travel forms.

How it should work: It should get removed.

Source :  https://www.wowhead.com/forums&topic=11060

**Comment by Amavas** [comment]
Well it doesn't break any movement imparing effect for now. Mage Frost Armor / Frostbolt / Frost Nova etc.

**Comment by Jeansapin** [comment]
Same for Concussive Shot, Earthbind Totem, some roots provided by npc, etc ... it's totally broken
