### ISSUE TITLE
Judgement of Justice target still being able to be feared

### ISSUE THREAD

**Issue by Gotemniggadro** [SunwellWoW/Sunwell-TBC-Bugtracker#3159]
Description: If you judge justice you can still fear the target

How it works: Judge justice the debuff clearly states that the target cannot be feared, but on here you can

How it should work: If someone judges justice on a something they're immune to fear

Source (you should point out proofs of your report, please give us some source): https://tbc-twinhead.twinstar.cz/?spell=31895

**Comment by Azathothh** [comment]
It's "preventing them from fleeing" not "making them immune to fear effects".
It means that mobs won't run away on low HP if this effect is active on them, but they still can be feared without any problem.

**Comment by Gotemniggadro** [comment]
You are wrong please look at the spell fear https://tbc-twinhead.twinstar.cz/?spell=6215

Mechanic 	fleeing

**Comment by Aeded** [comment]
You are both wrong actualy xd... You can fear targets that have judgement up, but the fear has no effect, you have the fear debuff and animation, but you can move your character normaly and cast spells.
Nice to see that this server has so knownledgable staff members.
