### ISSUE TITLE
Nova

### ISSUE THREAD

**Issue by Shatterz** [SunwellWoW/Sunwell-TBC-Bugtracker#3162]
Description: Nova bugged

How it works: 
- frost nova dmg going through but not snaring(if nova does not snare its dmg will not go through. Here it goes through but nothing happens. I think this is similar to the bug with sheep going of and then coming out 2 seconds after. Normally if this was vanilla server id chalk it up to heart beat resist but that is not in tbc so idk)

How it should work: 
Nova should either A resist or miss dealing no dmg and not snaring, or deal the damage and snare. The damage is being dished out but there is no snare.
Polymorph is breaking after 1-2 seconds which is not how it works in tbc

Source (you should point out proofs of your report, please give us some source): 
This is a frequent bug and can be duplicated.

**Comment by ujellyx** [comment]
/confirm
Frost Nova is a binary spell and should either be resisted fully or not at all (damage and snare).

**Comment by akrom23** [comment]
> Polymorph is breaking after 1-2 seconds which is not how it works in tbc

It's called heartbeat resist.

@Shatterz Cannot reproduce it.
Maybe your target resisted the root effect (e.g. got some auras that increasing resist chance)?

**Comment by akrom23** [comment]
No response.
