### ISSUE TITLE
Cone of Cold

### ISSUE THREAD

**Issue by Shatterz** [SunwellWoW/Sunwell-TBC-Bugtracker#3163]
Description: 
-FIX CONE OF COLD (Units arent hit by cone of cold. On a very well scripted  I could Spin my cone of gold 180 degrees and hit everything, on less scripted servers I would need to just stand still and make sure my character is directed face foward towards the mobs for it to connect. Both of these do not work so there is some kind of problem going on here)

How it works: 
Cone of cold is not registering mobs in front of them, or its sinking into the ground. Bottom line is its not hitting mobs in front of them

How it should work: 
An aoe frontal cone pointed directly in front of the caster pointed direction
Source (you should point out proofs of your report, please give us some source): 
this can be reproduced every single time you cast cone of cold.

**Comment by akrom23** [comment]
No.
https://wow.gamepedia.com/index.php?title=Cone_of_Cold&oldid=1432387
