### ISSUE TITLE
Black Morass - non-elite mobs resetting

### ISSUE THREAD

**Issue by Xymos** [SunwellWoW/Sunwell-TBC-Bugtracker#3166]
Inside Black Morass, the non-elites (jaguars and crocolisks) reset after a short while.
They're supposed to follow you around.

**Comment by notsofamous** [comment]
They dont like it when you stand in the water, also the pathing is really wonky if you have water between you and the mob when you pull it.

**Comment by leylandpaladin** [comment]
Can confirm, also they have problems passing the water. evading and it's makes almost impossible to farm them, very dissapointed

I mean AOE farm
