### ISSUE TITLE
[Warlock]Pets don't auto attack

### ISSUE THREAD

**Issue by Lunasoll** [SunwellWoW/Sunwell-TBC-Bugtracker#3169]
Description: 
Pets don't auto attack when casting offensive spell on a mob

How it works: 
If mob has aggro on someone else, and warlock casts a spell, then his pet will not start attacking (defensive stance enabled). However pet will attack only if mob attacks warlock. 

How it should work: 
Pet should start attacking automatically regardless if mob is attacking another player. 

Source (you should point out proofs of your report, please give us some source):

**Comment by jockeboschko** [comment]
Assist is not in the game i think you are forgetting how defensive stance worked
