### ISSUE TITLE
[Spell] Arcane Torrent

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#317]
Decription: 

How it works: 
Gives no mana when you use it (energy version works)

How it should work: 
You should gain 161 mana for each stack of Mana Tap that you have

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?spell=28730
https://www.wowhead.com/spell=28730/arcane-torrent#comments:id=208209

**Comment by akrom23** [comment]
Works, but only if you hit with silence effect. Is it blizzlike?
