### ISSUE TITLE
swing timer reset warrior

### ISSUE THREAD

**Issue by youawizard** [SunwellWoW/Sunwell-TBC-Bugtracker#3173]
Description: 
How it works:
https://gyazo.com/e545a68662148582f83fc004f125b17c

How it should work:
If you watch Auto-Attacks troughout the video you can see that switching Stance did not affect the Swing Timer, only switching weapons does.

Source (you should point out proofs of your report, please give us some source):
https://www.youtube.com/watch?v=oo_vcsdBKXc&t=2m00s

it's bugging on the fresh server!

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1995 ... ?
