### ISSUE TITLE
warrior kick pummel/shield basj

### ISSUE THREAD

**Issue by youawizard** [SunwellWoW/Sunwell-TBC-Bugtracker#3174]
Description: 

How it works: 
sometimes when i want to kick with a spell cast with pummel/shield bash it hit the target put doesn't interrupt it, or it interrupt the target put the target can cast back the same magic school right after the kick.

How it should work: 
you kick the caster, it interrupt the cast and he can't cast again during 4-6 sec the same magic school spell

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
There are some spells that can't be interrupted.
@youawizard You mean mobs or players?

**Comment by koostosh** [comment]
Some spells cannot be interrupted, some creatures can be immune to interrupts etc.
Nothing can be done without additional information.
