### ISSUE TITLE
Battle of the Crimson Watch

### ISSUE THREAD

**Issue by shagwellbug** [SunwellWoW/Sunwell-TBC-Bugtracker#3182]
Description: Quest

How it works: It only spawns one wave of mobs

How it should work: Should spawn several waves of mobs, atm it doesnt so you cannot complete the quest.

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=npuOzvyx2Zk

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2859
