### ISSUE TITLE
Quest: The Flesh Lies... - undoable

### ISSUE THREAD

**Issue by Xymos** [SunwellWoW/Sunwell-TBC-Bugtracker#3187]
Quest: http://db.hellfire-tbc.com/?quest=10345

Error: corpses disappear when you get close enough to burn them.
Quest is undoable this way

**Comment by zefurr** [comment]
it seems that sometimes the corpses can just barely be burned outside of the range that triggers their spawn, but it's very tight.

Depending on the difference in elevation, some corpses are in fact impossible to burn
