### ISSUE TITLE
Formation Movement

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#319]
Hi there,

We have two problems with formations:

1. When formation leader walks from point A to point B then its fine, we don't meet any issues here. Problem is with other npcs who are walking with leader in formation. Sometimes they speed up and run in random when leader reaches on of his path points. Afterwards they come back to leader like nothing happens.

2. Spawned pets/guardians with guid 0 don't want to walk with their masters when they have any pathing added. Random examples like: Defias Pirate+Defias Companion, Razorfen Hunter+Tamed Battleboar or Twilight Shadowmage+Voidwalker Minion

**Comment by lukaasm** [comment]
2. https://github.com/SunwellWoW/Sunwell-TBC/issues/64

**Comment by Wojtyas** [comment]
Fixed & implemented.
