### ISSUE TITLE
wl summon in dungeon

### ISSUE THREAD

**Issue by fetjke** [SunwellWoW/Sunwell-TBC-Bugtracker#3194]
Description: 
cant summon people inside just got a yeallow massage about it. waisting soul shard as well

How it works: 
got a yeallow massage that i cant summon ppl inside dung/raid

How it should work: 
i should be able to summon ppl inside dungeon/raid as a warlock!

Source (you should point out proofs of your report, please give us some source): 
dont want to make a screen. you 100% understand

**Comment by Josephienvandermeersch** [comment]
Confirms that this is broken
Can not summon person who is in the beginning of instance, Should be able to

**Comment by netherneth** [comment]
Patch 2.4.0 (25-Mar-2008): Ritual of Summoning can be used to summon players into instances if they meet the instance requirements.
Before this patch you could not summon people inside the instance from the outside.

**Comment by fetjke** [comment]
any feedback?

**Comment by badmannerkid** [comment]
we need a yes or no answer on this.

 this is a QoL change that should be lumped in with the likes of Guild Banks, level 30 mounts etc. It has no impact on itemization, and severely impacts raid environments across the board. Makes subbing people in and out of raids/instances a very tedious event. 

I wouldn't be against a vote for this but honestly, haven't been on a TBC server in the last 5 years that didn't have this implemented and it is very frustrating to say the least

**Comment by badmannerkid** [comment]
Afghann is working on implementing the fix, its causing some trouble. 

See #2331
