### ISSUE TITLE
[Dungeon] Arcatraz Linked Pulls

### ISSUE THREAD

**Issue by NeonicSupersonic** [SunwellWoW/Sunwell-TBC-Bugtracker#3197]
Description:
Arcatraz has some crucial mobs/packs linked for no reason which makes dungeon alot harder on normal and close to impossible on hc.

How it works: 
Three eredars 1x(https://wow.gamepedia.com/Eredar_Deathbringer) and 2x (https://wow.gamepedia.com/Eredar_Soul-Eater) are all linked. Double satyr packs 2x2(https://wow.gamepedia.com/Sargeron_Hellcaller/https://wow.gamepedia.com/Sargeron_Archer) also linked.

How it should work: 
Eredars should be pullable one by one. Satyrs should be pullablle 2 at the time.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_121118_204147](https://user-images.githubusercontent.com/45077198/49825552-c9a83a80-fd95-11e8-8e78-4d2880089688.jpg)
Meanwhile
https://youtu.be/mfNM4WEpPow?t=216
https://youtu.be/mfNM4WEpPow?t=508

**Comment by metalbaneb** [comment]
hope will be fixed soon, that pack is nearly imposible with paladin, a warrior can do with cds... but yeah

**Comment by rychersky** [comment]
Eredar pack is virtually impossible. We burned Bloodlust, Fire Elemental, Shield Wall, Last Stand, and Tranquility and managed to kill one before we died.
