### ISSUE TITLE
Rogue: Vanish bug

### ISSUE THREAD

**Issue by VashetSunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#32]
Decription: 
Vanish Combat and Threat bug

How it works: 
Vanish works inconsistently to drop combat and put you into stealth. Greater stealth buff applies every time though. If i vanished right as I was being attacked it would usually cause this to occur, though sometimes it just happened. Damage, DoTs, or debuffs on the target had no effect.

How it should work: 
Cause the rogue to drop combat, threat with aggro'd targets, enter stealth, and gain an increased stealth level buff.

Source (you should point out proofs of your report, please give us some source): 
I tried it on one, two, and three mob pulls in SMV (Ashtongue Workers and Shamans). In happened intermittently, but was most common on larger pulls.

**Comment by akrom23** [comment]
Cannot reproduce it. Need one more test.
