### ISSUE TITLE
Friendly Unit + AI issue

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#320]
NPCs that have some healing spells don't want to heal their allies gladly.

They heal them once per fight, but when their allies reach low hp again then they don't care at all. Sometimes happen also on themselfs, like they want to use only one healing spell cast on target pet fight.
Example: Holdout Medic (6392)[healer] + allies (6391, 6407) or Atal'ai Wtich Doctor (5259)[healer] + ally (5267)

It seems to work like that on every dungeon I visited.

**Comment by Riztazz** [comment]
give some examples please, it might be script specific

**Comment by Kokaina** [comment]
I gave.

**Comment by Riztazz** [comment]
It's not global issue, AI has been written like that, we need to fix those on script basis, i'll fix those reported in the issue but if you encounter creatures like that, please let me know in this ticket

**Comment by notsofamous** [comment]
Both cases in this report works.
