### ISSUE TITLE
Captain Tyralius

### ISSUE THREAD

**Issue by KayleeFrye1** [SunwellWoW/Sunwell-TBC-Bugtracker#3200]
Description: 
Release Captain Tyralius from his prison. 
Obtain key from the nearby warden.

How it works: 
Nothing happens when I try to use key!

How it should work: 
It should open when clicked (assuming obtained key)

Source (you should point out proofs of your report, please give us some source): 
https://puu.sh/Cg7im/e299be569c.jpg

**Comment by KayleeFrye1** [comment]
What can I try?
I've deleted key, quest, relogged, turned off all addons, waited 24 hours+
still can't release him

**Comment by Dootz** [comment]
I'll check again today and see what we can do.

**Comment by Noxx95** [comment]
Same problem.
tryed before and after server restart dont work.

**Comment by Azathothh** [comment]
This quest is working - if you can't do it, please clear your cache, it should help.
