### ISSUE TITLE
Racial of Trolls - Regeneration

### ISSUE THREAD

**Issue by skabury** [SunwellWoW/Sunwell-TBC-Bugtracker#3210]
Description: 

It simply does not work, there is no extra regeneration when you are out of combat and the little life that regenerates you when you are in combat.

How it works: 

Racial is not enabled

How it should work: 
Increases the regeneration rate of health by 10%. During the combat, 10% of the total health regency can follow.

Source (you should point out proofs of your report, please give us some source): 

https://wow.gamepedia.com/Regeneration_(racial)

https://www.wowhead.com/spell=20555/regeneration

https://www.wowdb.com/spells/20555-regeneration

**Comment by SalemSailor** [comment]
Also isn't working for me.

**Comment by akrom23** [comment]
Works good.
With racial:
- Out of combat: 35 health every tick
![wowscrnshot_011419_144517](https://user-images.githubusercontent.com/1035215/51116928-afd29b00-180c-11e9-9f3d-ee42de5942b7.jpg)
![wowscrnshot_011419_144519](https://user-images.githubusercontent.com/1035215/51116930-afd29b00-180c-11e9-9de0-5aae30dbb1c6.jpg)
![wowscrnshot_011419_144521](https://user-images.githubusercontent.com/1035215/51116931-afd29b00-180c-11e9-86a6-66dc877d77fc.jpg)
![wowscrnshot_011419_144523](https://user-images.githubusercontent.com/1035215/51116932-b06b3180-180c-11e9-80b6-55ba0b018dc3.jpg)

- In combat: 3 health every tick
![wowscrnshot_011419_144625](https://user-images.githubusercontent.com/1035215/51116936-b6611280-180c-11e9-88ce-bf4443c0a9e6.jpg)
![wowscrnshot_011419_144627](https://user-images.githubusercontent.com/1035215/51116937-b6f9a900-180c-11e9-8cff-0124f8313578.jpg)
![wowscrnshot_011419_144629](https://user-images.githubusercontent.com/1035215/51116940-b6f9a900-180c-11e9-9fe8-33f3fac49d23.jpg)
![wowscrnshot_011419_144631](https://user-images.githubusercontent.com/1035215/51116941-b7923f80-180c-11e9-8460-f6238a0277fd.jpg)


Without racial:
- Out of combat: 32 health every tick
![wowscrnshot_011419_144645](https://user-images.githubusercontent.com/1035215/51116951-be20b700-180c-11e9-9333-929e37fc8510.jpg)
![wowscrnshot_011419_144647](https://user-images.githubusercontent.com/1035215/51116952-beb94d80-180c-11e9-872a-cee5991205b4.jpg)
![wowscrnshot_011419_144649](https://user-images.githubusercontent.com/1035215/51116953-beb94d80-180c-11e9-84b2-3159c876b9a1.jpg)
![wowscrnshot_011419_144651](https://user-images.githubusercontent.com/1035215/51116954-beb94d80-180c-11e9-8ebd-4bb6e4c49247.jpg)

- In combat - health did not regenerate.
