### ISSUE TITLE
JC Thorium Settings bug

### ISSUE THREAD

**Issue by rafanito** [SunwellWoW/Sunwell-TBC-Bugtracker#3218]
Description: 
the option to craft the Thorium Settings of the jeweler's profession is bugged. To craft 1xThorium Settings, you need only 1xThorium Bar. In my situation, to craft 1xThorium Settings, the game needs 3xThorium Bar.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):  My character is called "Natokaknik"

**Comment by sinfer** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2519

**Comment by rafanito** [comment]
Even after deleting the cache, the problem still remains. Can I do anything else?

**Comment by Wojtyas** [comment]
Ehh, okey - we will revert it.
