### ISSUE TITLE
Player location in character choose panel

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#322]
No matter where I log out i have always "City" below my character name :(

It should display proper zone instead of that.

![image](https://user-images.githubusercontent.com/22802214/45216202-026cdb00-b2a0-11e8-9658-36c3d222e025.png)

**Comment by notsofamous** [comment]
Seems to work properly for me

**Comment by Kokaina** [comment]
Well... dunno what I did :D maybe after visit specific location it changes to that permanently

**Comment by Kokaina** [comment]
Ye lets close it, i had it at the beginning and i guess it got fixed later by repairing core xP
