### ISSUE TITLE
[Mining] Dark Iron Deposits

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#3222]
Description: 
Dark iron deposits missing 

How it works: 
No Dark Iron Deposits in the Burning Steppes

How it should work: 
Multiple veins in the Burning Steppes

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
There are only in Molten Core and Blackrock Depths for now, please compare bases. @Dootz
