### ISSUE TITLE
[NPC/Quest]Therylune's Escape Turn-in NPC

### ISSUE THREAD

**Issue by VocableWAZZAM** [SunwellWoW/Sunwell-TBC-Bugtracker#3224]
Description: The Turn-in NPC for Therylune's Escape does not spawn

How it works: The NPC to turn in Therylune's Escape either is out of bounds or does not spawn, either way it is not visible

How it should work: The NPC should spawn

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_121118_171309](https://user-images.githubusercontent.com/35873903/49838493-2bea4680-fd68-11e8-9c7f-1c24481bf14e.jpg)

**Comment by seki98** [comment]
The NPC runs too fast and get run into the mobs and disappear, if you cannot chase it fast enough.
