### ISSUE TITLE
The softnest wings

### ISSUE THREAD

**Issue by grejfrutek** [SunwellWoW/Sunwell-TBC-Bugtracker#3225]
Description: 4 working mobs

How it works: Most of mobs are unkillable

How it should work: There should be a lot of mobs to kill

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/FSKjPuz

**Comment by Wojtyas** [comment]
Because those flying units are not Mature Silkwings (21839) but Cosmetic Silkwings (21840).

@Dootz Please compare amount of 21839 to other bases and add more of them if its possible.
