### ISSUE TITLE
Priest Shadow form

### ISSUE THREAD

**Issue by groveunder** [SunwellWoW/Sunwell-TBC-Bugtracker#3229]
Description: 
Shadow form dis mounts you.

How it works: 
Casting Shadowform, causes you to dismount.

How it should work: 
You should be able too toggle shadowform on and off while mounted and running.

Source (you should point out proofs of your report, please give us some source):

**Comment by Solka777** [comment]
Cannot wait this to be fixed, thank you for reporting it as well

**Comment by groveunder** [comment]
BUMP

**Comment by username-is-not-taken** [comment]
As far as I know, you should only be able to deactivate shadowform without dismounting - not casting it. And google confirms this:

Patch 3.0.8 (2009-01-20): You can now shift into Shadowform while mounted or sitting.
http://wowwiki.wikia.com/wiki/Shadowform
