### ISSUE TITLE
Warp Splinter (Botanica)

### ISSUE THREAD

**Issue by Bzmode** [SunwellWoW/Sunwell-TBC-Bugtracker#3231]
how it works: Currently saplings are friendly and just move to the middle of the room.

how it should work: Saplings should be hostile and slowly move to attack players until a set timer when warp splinter consumes the ones still alive to heal him self.

https://www.youtube.com/watch?v=KGFrSMBMXzM

**Comment by Zarant** [comment]
Also, warp splinter's arcane volley is not supposed to hit pets:

Pay close attention to the pet frames, pets take damage from the stomp ability but not from arcane volley.
https://www.youtube.com/watch?v=UHpc21RZURE at the 27 second mark, normal mode
https://www.youtube.com/watch?v=L7pWoLhj3DE at the 43 second mark, heroic mode
