### ISSUE TITLE
[NPC] Zaxxis Insignia

### ISSUE THREAD

**Issue by rychersky** [SunwellWoW/Sunwell-TBC-Bugtracker#3232]
Description: Zaxxis Insignia from Zaxxis Raiders in Netherstorm seem to have a lower drop rate than normal. Wowhead shows it around 65-70% while I've gotten 1 in 10 kills so far.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=29209/zaxxis-insignia#comments

**Comment by Robin-Combeau** [comment]
Twinstar TBC database shows a 50% drop rate : https://tbc-twinhead.twinstar.cz/?item=29209

**Comment by Zarant** [comment]
http://web.archive.org/web/20081008110541/http://thottbot.com:80/i29209

55.7% chance with over 871000 kills, source from October 2008 (patch 2.4.3)

**Comment by Dootz** [comment]
It's currently at 50%, will be slightly increased with next update
