### ISSUE TITLE
Against the Legion quest blood not dropping from the Princesses

### ISSUE THREAD

**Issue by waterloorick** [SunwellWoW/Sunwell-TBC-Bugtracker#3233]
Description: Fleshly Draw Blood not Dropping and has a very high chance.

How it works: For the quest "Against the Legion" you are required to get an item from a Wrath Priestess. Right now, I have killed no less than 20 and no drop.

How it should work: Kill a princess, get the blood, summon the Avatar.

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/npc=18859/wrath-priestess

**Comment by liek0r** [comment]
It does drop.

**Comment by waterloorick** [comment]
How many did you kill to get it?

**Comment by Dootz** [comment]
Drop chance will be sligthly increased. Currently it's around 25%
