### ISSUE TITLE
Dalliah the Doomsayer (Arcatraz)

### ISSUE THREAD

**Issue by Bzmode** [SunwellWoW/Sunwell-TBC-Bugtracker#3234]
Description: 

How it works: Heal can't be kicked / counterspelled 

How it should work: Heal should be able to be kicked / counterspelled 

Source (you should point out proofs of your report, please give us some source):

**Comment by waterloorick** [comment]
We did it and it worked perfectly. I earth shocked it.

**Comment by zapsuu** [comment]
Feral charge doesn't work here (immune), but it should
https://www.wowhead.com/npc=20885/dalliah-the-doomsayer#comments:id=25185:reply=5133
https://www.wowhead.com/npc=20885/dalliah-the-doomsayer#comments:id=44120
