### ISSUE TITLE
Hourglass of the Unraveller doesnt proc for hunters

### ISSUE THREAD

**Issue by phantmpooper** [SunwellWoW/Sunwell-TBC-Bugtracker#3238]
Description: 
Hourglass of the Unraveller doesnt proc for hunters

How it works: 
doesnt proc

How it should work: 
should proc on crit

Source (you should point out proofs of your report, please give us some source):

**Comment by AshhSunwell** [comment]
It does proc for Hunters.

**Comment by Wojtyas** [comment]
It does.
![image](https://user-images.githubusercontent.com/22802214/49867151-d8c8d000-fe09-11e8-9025-569119e25f30.png)
