### ISSUE TITLE
[Item] Regal Protectorate doesnt heal

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#3239]
How it works: Regal Protectorate only increases your maximum health

How it should work: It should also increase your current health effectively being a heal for 900

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=28042/regal-protectorate#comments

**Comment by Wojtyas** [comment]
Should increase both - total health points and current health points by its amount.
