### ISSUE TITLE
[Warrior][Spell] Cleave and Heroic Strike Queuing

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#3241]
Description: 
When you have heroic strike or cleave queued for your next swing and you reduce your rage to under the required amount for the heroic strike or cleave, it will cancel both the cleave/heroic strike that is queued as well as the white swing that you should casted. 

How it works: 
When you have heroic strike or cleave queued for your next swing and you reduce your rage to under the required amount for the heroic strike or cleave, it will cancel both the cleave/heroic strike that is queued as well as the white swing that you should casted. You lose the auto attack and have to wait for another swing timer

How it should work: 
If you go under the required rage for a heroic strike or cleave whilst you have either spell queued, you should still get off an auto swing when the heroic strike or cleave are cancelled. Instead, you simply lose the auto attack and have to wait for another swing timer

Source (you should point out proofs of your report, please give us some source):

**Comment by MarcusStu** [comment]
I can confirm this. It's both a tps and dps loss..
