### ISSUE TITLE
invisibility potion adds 10 min cd to all potions

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#3245]
Description: 

How it works: 

How it should work: 
should be only 10 min on invis pots and maybe 2 min on mana pots / etc 

Source (you should point out proofs of your report, please give us some source):

**Comment by Zarant** [comment]
Source:
https://youtu.be/wcA8O_dRLy0?t=77
Invisibility potions should trigger the standard 2min cooldown on all other potions

**Comment by koostosh** [comment]
intended behavior as of 2.4.3 mechanic.
