### ISSUE TITLE
Ethereum Jailor

### ISSUE THREAD

**Issue by mchayes** [SunwellWoW/Sunwell-TBC-Bugtracker#3246]
Description: Ethereum Jailor is not dropping Ethereum Keys.

How it works: Killing a Jailor results in no key in the loot-table.

How it should work: Killing a Jailor should result with a key in the loot table.

Source (you should point out proofs of your report, please give us some source): 
Ethereum Jailor: http://db.hellfire-tbc.com/?npc=23008
Ethereum Prison Key: http://db.hellfire-tbc.com/?item=29460

**Comment by Elefant0n** [comment]
This should not be added until 2.0.1 btw.

**Comment by Zarant** [comment]
In order for the Ethereum keys to drop, you need to complete this quest first:
 https://www.wowhead.com/quest=10970/a-mission-of-mercy 
This particular quest got added to the game in patch 2.1

And so did the Ethereum Jailors themselves.

**Comment by Dootz** [comment]
Hi, @Zarant is correct. You need to complete A Mission of Mercy first.
