### ISSUE TITLE
[NPC]Jadefire Trickster

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#3249]
Description: 

THIS IS STILL OPEN, https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1086
How it works: 
Still open

How it should work: 
Please fix it ASAP, it is nearly imposibble to kill one trickster, as they use it very quick. Remove the ability if u cant fix it. Please, thanks :) 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, thank you for report. Temporary fix will be added with next update. (Ability will be removed from mob).

**Comment by Mikov1605** [comment]
Thank you 😍
