### ISSUE TITLE
[Hunter][Spell] Frost Trap

### ISSUE THREAD

**Issue by Patrulek** [SunwellWoW/Sunwell-TBC-Bugtracker#325]
Decription: 
1. Frost Trap somtimes has problems with refreshing when enemy get out of the area of trap and the get back to this area. I couldn't find what causes this effect. This is true for creatures and players. (screens as proof)
2. Minor bug in combat log (screen as proof)
3. I don't know if this really a bug, but when [Clever Traps](http://db.hellfire-tbc.com/?spell=19245) are 2/2, frost trap lasts for 39s (comparing to 30s normally). The problem is that when 30s will pass the visual of trap disappear and then appear again for the next 9s (need proof).

How it works: 
As in description.

How it should work: 
1. The slow effect should always refresh when enemy get into it.
2. It should be a human-readable string.
3. (need proof)

Source (you should point out proofs of your report, please give us some source): 
Screenshots.

![2018-09-07 20_23_29-greenshot](https://user-images.githubusercontent.com/7295272/45250876-d9e6ee80-b33c-11e8-824c-cc8cb5d0b1ad.png)
![2018-09-07 20_20_13-greenshot](https://user-images.githubusercontent.com/7295272/45250891-0e5aaa80-b33d-11e8-87b6-dec0dbcf6df5.png)
![2018-09-07 20_36_53-greenshot](https://user-images.githubusercontent.com/7295272/45250903-3fd37600-b33d-11e8-8e59-23e839b3a700.png)
![combatlog](https://user-images.githubusercontent.com/7295272/45250913-62658f00-b33d-11e8-9713-028f3541fe43.png)

**Comment by akrom23** [comment]
The 3rd is only visual clientside - nothing can do about it.

**Comment by akrom23** [comment]
@Patrulek Are you able to reproduce bug no.1 whenever you like?

**Comment by Patrulek** [comment]
@akrom23 
> I couldn't find what causes this effect. 

Im not. My first guess was with using abilities by enemies, the second with terrain but dont think either of this is a cause. I could do a more tests if you would tell me how this aura is applied and where should I look for reason at most. 
I also have compiled (but not configured yet) core from GH (~2014). If this is what youre basing on i could do some digging in code on my private realm if you would guide me a bit where this is implemented.

**Comment by Patrulek** [comment]
This could be also relating with combat, i did some testing yesterday and recorded that. Try to cut out some interesting frames tomorrow.

**Comment by Patrulek** [comment]
Ok, i found something what can be reproduced but it's not what the issue was about - still maybe this will be helpful. Frost trap with talents lasts for 39s, but cooldown is only 24s. Aura from old trap overwrites aura from the newer one. [Video as proof](https://streamable.com/nzork)

Ps. I think that issue should be still labeled as High Priority.

**Comment by akrom23** [comment]
@Patrulek It's very helpful :+1:

**Comment by akrom23** [comment]
The last issue described by @Patrulek fixed.
Let me know if the main issue from this report still occurs.

**Comment by Patrulek** [comment]
@akrom23 
> The last issue described by @Patrulek fixed.

Still happening.

**Comment by akrom23** [comment]
PTR not updated.

**Comment by Patrulek** [comment]
Couldn't repeat any of reported issues, but noticed another bug. When mob get out of the area trap, he's walking (instead of running) until player moves.

**Comment by akrom23** [comment]
@Patrulek Cannot reproduce the last one.

**Comment by Patrulek** [comment]
I'll check that later.

**Comment by Patrulek** [comment]
Seems to work correctly now.
