### ISSUE TITLE
[Warrior][Bug] hamstring/pummel/shieldbash being blocked

### ISSUE THREAD

**Issue by zenots** [SunwellWoW/Sunwell-TBC-Bugtracker#3251]
Description: enemy units are blocking attacks that should not be able to. Namely hamstring and pummel/shield bash are being blocked not only by enemy units that should not be able to block at all, but also by totems (they have 100% chance to block hamstring). Which greatly affects threat in the case of shield bash, and makes it impossible to destroy totems with hamstring which is important for PVP as well as for a lot of PVE situations.

How it works: Totems and enemy units without shields are blocking (with VERY HIGH chance) hamstring / pummel / shield bash (and probably every other ability with low damage values added to them).

How it should work: They should not be able to block

Source (you should point out proofs of your report, please give us some source): 
http://www.arenajunkies.com/topic/296284-efficiently-killing-totems/
https://www.wowhead.com/forums&topic=87799

**Comment by YoshGit** [comment]
#1631
