### ISSUE TITLE
Vampiric Embrace

### ISSUE THREAD

**Issue by emilasking** [SunwellWoW/Sunwell-TBC-Bugtracker#3260]
Description: 
When killing a mob with the Priest spell Vampiric Embrace on it, VE doesn't give HP back.

How it works:
If Mind Blast is the killing blow on a mob afflicted with VE, there is no HP returned.
Also tested with Mind Flay, dots such as Pain and Vampiric Touch.

How it should work: 
I think it should give HP back even if its the killing blow?

Source (you should point out proofs of your report, please give us some source): 
I haven't tested if Vampiric Touch and mana has the same issue, but worth checking out?

**Comment by SunwellTracker** [comment]
So please check out the bug and provide appropriate tests.

**Comment by groveunder** [comment]
To better clarify. Only the killing blow doesn't give mana or hp back. It should. So same with Vampiric touches mana regen from a KB move.

**Comment by fredriksvendsen** [comment]
Was just about to post this. Still an issue, mildly annoying while leveling.

**Comment by akrom23** [comment]
https://wow.gamepedia.com/Vampiric_Embrace

> This ability will no longer heal for damage caused when the target had no life remaining.
