### ISSUE TITLE
Did not receive quest reward

### ISSUE THREAD

**Issue by jonahsands** [SunwellWoW/Sunwell-TBC-Bugtracker#3263]
Description: 
i did Egg quest in nagrand where you have to go to the tree get that egg and kill one elite bird after that i went and turned the quest in chose reward i want got the XP but item was not in my bags i made ticket IG where i told name of the item and now i cant remember it anymore and it was good upgrade for me what to do now?

item name Delicate green poncho
charecter name Humanrogue
https://www.wowhead.com/quest=10111/bring-me-the-egg
Quest name Bring me the egg
How it works: 
^

How it should work: 
Pretty sure it should give me the item that i chose

Source (you should point out proofs of your report, please give us some source): 
Did not think i have to take picture or something as i made the GM ticket that i did not get any respond exept after couple of hours i saw mail in my mailbox...

**Comment by Dootz** [comment]
Hi,
unfortunately, we do not restore lost items. I've checked it and everything seems normal. Even when i had full bags it simply did not let me submit quest window and gave me error message "Your bags are full".
