### ISSUE TITLE
cuergo's gold

### ISSUE THREAD

**Issue by Emperorplum** [SunwellWoW/Sunwell-TBC-Bugtracker#3266]
Description: 

How it works: A few pirates should come to face you , you have to kill them for a quest item.

How it should work: 
60 mobs on top eachother spawn and wreck you

Source (you should point out proofs of your report, please give us some source):

**Comment by harsunwell** [comment]
![image](https://user-images.githubusercontent.com/45367078/49897620-c2516180-fe67-11e8-8450-13299b82d716.png)
