### ISSUE TITLE
Subtetly Rogue: Master of Subtetly

### ISSUE THREAD

**Issue by b4dassculture** [SunwellWoW/Sunwell-TBC-Bugtracker#3267]
Description: 
the talent: Master of Subtetly doesnt proc

How it works: nothing procs

How it should work:  after breaking stealth you should get a 6 seconds buff that increase your damage up to 10% if you got 3/3 points

Source (you should point out proofs of your report, please give us some source):  you can ask any rogue on subtetly

**Comment by akrom23** [comment]
Works good.
https://www.wowhead.com/spell=31223/master-of-subtlety#comments:id=63243
![wowscrnshot_122818_204605](https://user-images.githubusercontent.com/1035215/50526322-9bd72b80-0ae1-11e9-91ca-4800b087813f.jpg)
