### ISSUE TITLE
Zone: Mulgore

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#327]
### **TO DO:**
- [x] 1. Grull Hawkwind (2980), Brave Proudsnout (3210), Brave Lightninghorn (3211), Brave Running Wolf (3213), Brave Greathoof (3214), Harutt Thunderhorn (3059), Meela Dawnstrider (3062), Seer Ravenfeather (5888), Morin Cloudstalker (2988), Thurston Xane (3049), Father Cobb (3046), Hesuwa Thunderhorn (10086), Eye of the Storm Envoy (22015) have their texts missing.
- [x] 2. Mountain Cougars (2961) hits for 3-4 while they should for 5-7.
- [x] 3. Bristleback Battleboar (2954) doesn't gain movement speed from his Boar Charge buff (3385).
- [x] 4. Battleboar (2966) hits for 3-5 while it should for 7-9.
- [x] 5. Bristleback Quilboar (2952) hits for 3-5 while it should for 7-9.
- [x] 6. Bristleback Shaman's (2953) Lightning Bolt spell (9532) hit for 1 when it should for much more...
- [x] 7. Earth Sapta (1462) quest has it text missing.
- [x] 8. Earth Sapta (1462) is a quest in which we can retrieve Earth Sapta (6635) item when we lost one. This quest should be visible to shamans when they are on Call of Earth (1520) quest. For now it's possible to retrieve Earth Sapta item even when we don't need it (before first shaman quest). Shamans shouldn't be able to keep Earth Sapta (6635) item when they aren't on Call of Earth (1520) quest.
![image](https://user-images.githubusercontent.com/22802214/45252943-d4020500-b35e-11e8-8d00-ea0428e0aec1.png)
- [x] 9. When we are getting reward from Call of Earth (1520) quest, Minor Manifestation of Earth npc (5891) should also buff us with Rock Skin spell (8314).
- [x] 10. Kodo Matriarch (2974) doesn't use his Trample spell (5568).
- [x] 11. Kodo Calf (2972) doesn't use his Rushing Charge spell (6268).
- [x] 12. Kodo Bull (2973) doesn't use his Trample spell (5568).
- [ ] 13. Elder Plainstrider's (2957) Dust Cloud spell (7272) doesn't have any effect.
![image](https://user-images.githubusercontent.com/22802214/45253279-f434c280-b364-11e8-960f-80bd81e03284.png)
- [x] 14. Snagglespear (5786) doesn't use his Net spell (12024).
- [x] 15. Two issues with Kyle's Gone Missing! quest (11129):
- When we put Tender Strider Meat item (33009) on ground Kyle's Lunch gob (186265) spawns in air instead of on the ground.
- When Kyle the Frenzied (23616) is fed, it doesn't disappear when it changes to Kyle the Friendly (23622).
![image](https://user-images.githubusercontent.com/22802214/45253449-6f977380-b367-11e8-9a97-d87b21e9e8d6.png)
- [x] 16. When getting credit for Winterhoof Cleansing (754) quest I believe there should be some animation with Winterhoof Water Well gob (20333).
- [x] 17. Venture Co. Supervisor (2979) doesn't use his Battle Shout spell (6673). He should appiy this buff on himself and his allies (other Venture Co. npcs).
- [x] 18. Sister Hatelash (5785) doesn't use both her spells: Lightning Bolt (9532) and Lightning Barrier (6960). She should refresh Lightning Barrier buff even when out of combat.
- [x] 19. Arra'chea (3058) should have 5min respawn time. For now it has 1 min.
- [x] 20. Mazzranache (3068) should be rare spawn in Mulgore. For now he's not present in game.
- [x] 21. Mazzranache doesn't use both his skills: Deadly Poison (3583) and Rushing Charge (6268).
- [x] 22. Mazzranache should have around 5h 30min respawn timer. For now it has 5 min.
- [x] 23. Bael'dun Appraiser (2990) should use his Lesser Heal spell () on other Appraiser or Bael'dun Diggers (2989) as well.
- [x] 24. Check drop chance of Demon Scarred Cloak item (4854) from Ghost Howl npc (3056). Should be 89-90% drop chance but didn't drop twice in a row.
- [x] 25. Item Demon Scarred Cloa (4854) should start The Demon Scarred Cloak (770) quest. When player tries to begin it there is announce that "You are already on that quest" when player doesn't have it in questlog actually.
- [ ] 26. Quest Gathering Leather (768) should be available only for players who have Skinning profession.
- [x] 27. Earth Sapta (1462) quest should be repeatable when player looses his Earth Sapta item. It should be same as Fire Sapta quest (1464).

**Comment by Silroth** [comment]
- Bristleback Battleboar does not use Boar Charge.

- Palemane Skinner does not cast Rejuvenation.

- Palemane Tanner does not cast Wrath.

- Arra'chea does not use Head Butt.

- Galak Outrunner not using Shoot.
