### ISSUE TITLE
Dark Sorceress hit WAAAAY too hard

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#3270]
Description: 
Dark Sorceress hit WAAAAY too hard

How it works: 
ability hits over 2k

How it should work: 
like 400-600, not sure

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/JjBl6TP

**Comment by Dootz** [comment]
https://www.wowhead.com/npc=19947/darkcrest-sorceress#comments:id=41585

> When you see a rune below and a circle of ice around you, make sure you move. If you are caught in the circle, you are put in a chain for around 10 seconds and receive about 2,000 frost damage. Otherwise, they're very easy and soft.

It's blizzlike behavior and won't be changed.

**Comment by Nelthalor** [comment]
I apologise for being uninformed
