### ISSUE TITLE
[Druid] Nature's Grace still working incorrectly

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#3272]
Description: Despite the latest fixes, which did fix a large portion of natures grace, it is still working incorrectly. Nature's grace is not effecting the next spell cast when swapping between wrath and starfire, the buff should apply on the spell cast of wrath if it crits, not when the damage lands, allowing you to spam wrath or swap spells and still get the benefit. Currently if I crit a Wrath and get natures grace and immediately cast starfire after, the starfire will receive no reduced cast time and still consume the natures grace.

How it works: Crit with wrath then immediately cast starfire, no reduced cast time and buff is consumed.

How it should work: The game knows if the spell is a crit when it casts, and the buff should trigger prior to the wrath projectile landing. In no circumstance should natures grace be consumed without applying the buff.

Source (you should point out proofs of your report, please give us some source): Everyone knows how it should work, don't need a source.

**Comment by TheUnknown2520** [comment]
Confirmed bugged. This is a major issue for balance druids.

**Comment by lordazurescens** [comment]
confirmed still bugged. Should apply natures grace immediately after the cast finishes. not when the wrath hits the target.
