### ISSUE TITLE
City of Light quest

### ISSUE THREAD

**Issue by dajnfehr** [SunwellWoW/Sunwell-TBC-Bugtracker#3274]
Description: The Khadgar's Servant starts following me and I cant complete the quest, this has happend two times for me now, after the second stop it happends.

How it works: He stops showing me the way

How it should work: He should keep going and show me shattrath

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/1e915992aa4163b5384724f7dcd4fdea

**Comment by dajnfehr** [comment]
Edit, I abandoned the quest, took it again now he is just chilling with me at Khadgar

https://gyazo.com/1f9c9c187a9a02fe211190c19f82cbf1

**Comment by Dootz** [comment]
Hi thank you for report. If you wish to complete it right now please stand still until he starts moving alongside his path and it can be completed. I'll prepare fix for tomorrow's update.

**Comment by dajnfehr** [comment]
All right, cheers!
