### ISSUE TITLE
Remorseless Attacks Rogue Talent

### ISSUE THREAD

**Issue by roguestep16** [SunwellWoW/Sunwell-TBC-Bugtracker#3276]
Description: 
The Buff get not tirggerd if u kill a mob wich gives u XP, when u finish mob with a Style

How it works: 
When i kill a mob ( wich give xp ofc) with sinister strike or eviscerate the talent does not proc.
im am level 14 and i just tested this 2 spells so far. If i kill the mob with my auto attacks i got the talent proc every time.

How it should work: 
The talent should proc everytime i kill a mob with all kind of attacks.. if i get xp

Source (you should point out proofs of your report, please give us some source):

**Comment by b4dassculture** [comment]
yep, he is totally right

**Comment by za-x-az** [comment]
Can we have this looked at soon?
seems like a waste of talents points if it doesn't proc 50% of the time.
Here is prof
https://youtu.be/aAkcOOzFY28
