### ISSUE TITLE
Elemental Seaforium Charge

### ISSUE THREAD

**Issue by mintnb** [SunwellWoW/Sunwell-TBC-Bugtracker#3277]
The schematic is absent in both consortium quartermasters' inventory.

**Comment by mintnb** [comment]
When is it going to be implemented??

**Comment by Dootz** [comment]
with next server update. Which is supposed to happen in next one -two hours.

**Comment by mintnb** [comment]
Um... I just visited the vendor in Nagrand and the seaforium charge is indeed there, however, it is the actual item and not the schematic. The item sold should be https://db.excalibur.ws/?item=23874

**Comment by Dootz** [comment]
whoops :D We'll be fixed with next update then. Sorry about that :(
