### ISSUE TITLE
Defense Skill 370

### ISSUE THREAD

**Issue by Lahuntz** [SunwellWoW/Sunwell-TBC-Bugtracker#3279]
Description: 
Once you hit 70, you can cap you Defense in skills to 370. Its stuck on 365, doesnt get the last 5 skills.

How it works: 
You get +5 levels in all skills that you can skill up to per level you hit.

How it should work: 
Every level you hit, example you hit 68, then you can get defense skill 360, level 69 365, level 70 370. 

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/833a16089c5ba9204d5eabe4925edb26

**Comment by neheri** [comment]
When you hit lvl 70 you have 350 defense. It may be connected to a talent or gear.

**Comment by Lahuntz** [comment]
Ye you start with 350, talents give 20. That should be 370 then. But its stuck at 365.
