### ISSUE TITLE
Chain heal

### ISSUE THREAD

**Issue by Mashiroh** [SunwellWoW/Sunwell-TBC-Bugtracker#3281]
Description: Chain heal has a few broken interactions.

How it works:  It will randomly heal targets on this server whilst ignoring yourself. This bug can seriously ruin the value of having shamans in your raid, especially with the fact it chains to full health allies over injured ones, essentially wasting your whole chain heal and overhealing. 

How it should work: Chain heal should prioritize people with missing health, as well as be able to heal yourself if you're within range of the bouncing target. 

Source (you should point out proofs of your report, please give us some source): jumps to heal the 2 most injured nearby allies. There are many archived posts talking about it on shaman forums, and old 2.4.3 posts on wowhead speaking about how the bounces interact by healing the 2 most injured allies, not healing already full health allies.

**Comment by Wojtyas** [comment]
If you want chain heal to hit yourself, you have to cast it on yourself. otherwise it will ignore you. That how it worked on tbc. Agree with that it should jumps through lowest hp targets but caster is an exception. If you have those proofs it should jump to you please link them.

**Comment by Avishai97** [comment]
sup yall it's ya boi with the sources
https://gyazo.com/c30598b64db12c4adbe60c86df0d52bc
https://legacy-wow.com/tbc-shaman-guide/
I thought it felt weird when it didn't jump back to me aswell

**Comment by MiekZer** [comment]
When devs never played tbc...
http://web.archive.org/web/20080811083102/http://elitistjerks.com/f47/t24796-shaman_restoration/#Chain_Heal

> Chain Heal
> 
> Chain heal is the shaman's signature heal and the one that all the other healing classes wish they had. After healing the initial target, the healing effect will jump to the most damaged target (by absolute health) within range. Each jump reduces the healing done by 50%. The jump range of the spell is approximately 10-15 yards. If there are no targets in range below 100% it will not jump. **The heal can jump back to the shaman if they have taken damage.**
> 
> In many raids, chain heal will represent more than 90% of all healing. Shaman are often assigned to heal the raid, meaning healing everyone besides the main tank. Other times, the shaman will heal the raid by targeting the main tank and letting the chain heal bounce to melee or other raid members. The shaman's Chain Heal, along with a priest's Circle of Healing, are the best multi-target heals in the game.
> 
> Chain heal can crit on any (or all) of the three jumps. However, the healing done to the next target is based on the non-crit healing done. Crits from chain heal will proc Ancestral Fortitude.
> 
> It receives the following bonuses from +healing gear:
> 
> 71% + 36% + 18% = 125% with no talents
> 94% + 47% + 24% = 165% with Purification (+10%) and Improved Chain Heal (+20%)
> 
> Many shaman downrank Chain Heal to Rank 4 (and sometimes even Rank 3). Rank 4 gets the full benefit of your plus healing since it is learned at level 61 and is not subject to the down ranking penalty. By using Rank 4, you reduce your mana costs by 19% but lose only 10% of your healing power.
> 
> There is a known bug with Chain Heal. If Chain Heal jumps back to you on its first jump (the second heal), it will not jump to a third target. It is sometimes better to target yourself for the first heal to make sure it jumps to two other targets.
> 
> Shaman's Fire and Earth Elementals are not considered part of the party/raid/group. Therefore, chain heal will not bounce to Elementals if you first target a raid member for healing. However, if you first target an Elemental, chain heal will bounce to members of the raid
> 
> Many trinkets will proc based on a “direct healing spells.” Each jump of chain heal is considered a direct heal. A trinket such as [Fel Reaver's Piston] or [Eye of Gruul] can proc on any jump of chain heal.
> 
> Other trinkets proc based on “each spell cast.” In those cases, the jumps do not count as separate spells. For example, [Pendant of the Violet Eye]

**Comment by RealKlayton** [comment]
there is a huge difference between "jump back" and "heal self as well", Wojtyas said everything correctly, but can add for clarity, chain heal heals you under two conditions:
- you use yourself as primary target.
- you are within bouncing range of spells primary target and nobody else near primary target is lower then full.

Quoting the very same source:
_There is a known bug with Chain Heal. If Chain Heal jumps back to you on its first jump (the second heal), it will not jump to a third target. It is sometimes better to target yourself for the first heal to make sure it jumps to two other targets._

It doesn't bother you at all once you know it. Without this mechanic it would be a pain in the ass to heal melee group if the first bounce goes back to shammy, thus he is a low-priority target for chain heal.

**Comment by MiekZer** [comment]
Yeah so Wotjyas is completely wrong.
If you fullfill the conditions then it should heal you.
If you are far enough from melees it shouldn't go back to you since you're... you know... far enough so it would NOT be a pain in the ass to heal.

**Comment by RealKlayton** [comment]
just checked, its jumps back with the conditions, so what exactly is broken?
![default](https://user-images.githubusercontent.com/40548952/49953237-540fac00-ff06-11e8-80ef-2ab2a2152807.png)
![default](https://user-images.githubusercontent.com/40548952/49953258-64278b80-ff06-11e8-9752-b9cb31983830.png)

**Comment by Avishai97** [comment]
https://gyazo.com/5dd2b4cb2cf5b9a25fca90b39809bb1e

**Comment by Avishai97** [comment]
as u see i have taken damage on my shaman but the chain heal doesnt bounce back to me
fixpls

**Comment by Mashiroh** [comment]
There is an issue with how the chain heal bounces as well, if the target im healing is within range of my other targets and in LoS it should then dictate its LoS requirements from my target im casting the chain off of instead of myself. Currently if the other target im wanting to chain to is out of LoS of the shaman but not my initial chain healed target it will not properly bounce to them as its using my body as the anchor for the bounce and not the target that is getting the first application of chain heal.

**Comment by Mashiroh** [comment]
Chain heal also is jumping to totems..

**Comment by Mashiroh** [comment]
Not sure if im get a response to this thread about whats being changed, but the biggest issue, and top priority for chain heal needs to be it bounces to full health targets when there is other targets with missing HP values around, and the fact it jumps to totems. Those are both game breaking bugs that will ruin the power level of bringing a resto shaman over lets say a CoH priest.

**Comment by Mashiroh** [comment]
bump?

**Comment by Nghedi** [comment]
How can this still not be assigned, if it is high priority since a week and 
there is a month old bug report
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1875
with the same/similar issues?

**Comment by Mashiroh** [comment]
This seriously needs fixxed, its a core mechanic for shamans, and game breaking. Can post our raids logs from this week and show you the inconsistency of chain heal relative to logs from other servers with chain heal working properly.

**Comment by badmannerkid** [comment]
this is a big one, any reason why it hasn't been assigned yet?

**Comment by Nghedi** [comment]
There is a patch, since 4 days. and it is still not live? wtf?

**Comment by Nghedi** [comment]
It still does not bounce on the shaman. Which is pretty annoying.

**Comment by akrom23** [comment]
@Nghedi Screenshots with combat log or video, please.

**Comment by Avishai97** [comment]
It bounced back to me yesterday, so atleast it has worked.

**Comment by Nghedi** [comment]
Strange, at curator it didn't work at all. Since then (after i relogged) its working. You can close it.
Thank you.
