### ISSUE TITLE
Ferocious Bite is bugged

### ISSUE THREAD

**Issue by Dezington** [SunwellWoW/Sunwell-TBC-Bugtracker#3283]
Description: 

Ferocious bite consumes all the energy you have when you use it
How it works: 
Ferocious bite consumes all the energy you have when you use it

How it should work: 
Should only consume 35 energy

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
"Finishing move that causes damage per combo point **and converts each extra point of energy into 1.5 additional damage** "
source: tooltip
