### ISSUE TITLE
Rogue Blind

### ISSUE THREAD

**Issue by KayleeFrye1** [SunwellWoW/Sunwell-TBC-Bugtracker#3284]
Description: 
Blind vs druid Flight Form Bugged.

How it works: 
Blind REMOVED Flight Form and I fell to the ground.

How it should work: 
Blind shouldn't affect aerial mounts!

Source (you should point out proofs of your report, please give us some source): 
https://puu.sh/CgDwo/773ef99357.png

**Comment by Euphemistic** [comment]
It does this for every flying mount as well. Still not fixed.
