### ISSUE TITLE
Shadow Labyrint bugs

### ISSUE THREAD

**Issue by magicborne** [SunwellWoW/Sunwell-TBC-Bugtracker#3288]
1.  before first boss, there are orc warlocks around the column, if you attack 1, all 3 should come.   Instead,  if you attack one, only 1 or 2 comes.  never all 3.

2. At first boss, when you kill the last 2 column mobs,  they release the boss, and he should walks TOWARDS the middle of the room,. INSTEAD he walks down the corridor to the quest giver.

3. Before the 2nd boss, in the big room, when you attack 1 mob, the whole pack should come,  usually 4-5-6 mob,  instead, only 3 comes,  never all.

4. When the 2nd boss mind control you,  EVERYONE attacks the pets.  Warlock Pet, Hunter Pet, doesnt matter.  noone focus player, but pets.    Not tested without pets yet.

5. Skeletons give you full reputation.  They should not give at all,  or max 2.

6.  3rd boss when spawn voidwalkers,  they dont go towards the boss.  They go towards players, and just stand. Do nothing.

7. The room before Murmur there are rows,  if you attack 1 mob, all 4 should come,  instead only comes 1-2. never all.   

8.  There is no animation for Murmur, you dont see the beams towards the mobs. They just randomly die sometimes,  but sometimes, they does not die at all.

9.  Murmur does not cast spells,  like the sonic boom,   It just happens.

**Comment by Wojtyas** [comment]
On work.
Also https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2960

**Comment by RoDavid4** [comment]
point 4 is not working, the 2nd boss don't make players fight themselves
