### ISSUE TITLE
[Warrior][Spell] Death Wish and Enrage interaction

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#3292]
Description: 
If you have Death Wish active, and are specced into the Enrage talent of the fury tree, and you are hit with a crit to active Enrage: Enrage overwrites Death Wish and you lose the buff. This was occuring with 2/5 level of Enrage

How it works: 
If you have Death Wish active, and are specced into the Enrage talent of the fury tree, and you are hit with a crit to active Enrage: Enrage overwrites Death Wish and you lose the buff. This was occuring with 2/5 level of Enrage

How it should work: 
Death Wish and Enrage should stack

Source (you should point out proofs of your report, please give us some source):

**Comment by BIGCHESTDAY** [comment]
The Burning Crusade Patch 2.3.0 (2007-11-13): Moved this talent from Fury to Arms. 
The Burning Crusade Patch 2.2.0 (2007-09-25): Changed the effect of this talent from a debuff to a buff. 
The Burning Crusade Patch 2.1.0 (2007-05-22): Death Wish and Enrage effects no longer stack. 
The Burning Crusade Patch 2.0.1 (2006-12-05): Death Wish and Enrage no longer stack.

**Comment by BIGCHESTDAY** [comment]
https://wow.gamepedia.com/Death_Wish

**Comment by BIGCHESTDAY** [comment]
They should not stack

**Comment by badmannerkid** [comment]
you're right, thanks
