### ISSUE TITLE
[World][Bug] Bubbly Fissures not replenishing breath timer

### ISSUE THREAD

**Issue by mooviestar** [SunwellWoW/Sunwell-TBC-Bugtracker#3295]
Description: 
Bubbly Fissures in Desolace near Shadowprey Village not restoring breath

How it works: 
Swimming through the bubbles doesn't restore breath timer

How it should work: 
When swimming through bubbles should restore breath timer

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?object=177524 
https://imgur.com/a/rGETMMB

**Comment by Trentone** [comment]
Will consider https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2182 the first issue and post the fix there.
