### ISSUE TITLE
Soulstone

### ISSUE THREAD

**Issue by Cerrigan** [SunwellWoW/Sunwell-TBC-Bugtracker#3296]
Description: 
Ive had soulstone up just to makesure lvling is smooth but died 3 times now and noticed that i could only go to the graveyard and not activate my soulstone

How it works: 
no option to use soulstone when the spell is cast upon me

How it should work: 
given the option opon death to soul stone

Source (you should point out proofs of your report, please give us some source):

**Comment by nkumnberlin** [comment]
never had problems with it. Maybe the cooldown runned out before you died

**Comment by Cerrigan** [comment]
I just applied it and got ganked by a warrior and wasnt able to do anything so dont think ik ran out :)
