### ISSUE TITLE
Gorishi Stings - problem with loot

### ISSUE THREAD

**Issue by player6476871561** [SunwellWoW/Sunwell-TBC-Bugtracker#3297]
Description: 
There are in Un'Goro Crater that should loot item - Gorishi Sting - Gorishi Workers, Gorishi Wasps and Gorishi Stingers and others. 8 Gorishi Stings are needed for quest Bloodpetal Poison. 

How it works: 
These mobs just don't loot this item.

How it should work: 
Simply they should loot this item.

Source (you should point out proofs of your report, please give us some source): 
https://vanilla-twinhead.twinstar.cz/?item=22435 - what mobs should loot that item
I don't know what other proofs I can provide - I just didn't get any item after killing about 30-40 mobs.

**Comment by tuerpisch** [comment]
i did this quest a few days ago
it was working fine
but they have a really low drop rate

**Comment by Azathothh** [comment]
They drop it, but droprate is low - it's not a bug
