### ISSUE TITLE
The Dead Scar questgiver

### ISSUE THREAD

**Issue by shander2355** [SunwellWoW/Sunwell-TBC-Bugtracker#330]
Decription: 

How it works:  No skeleton waves are spawning

How it should work:  Skeleton waves should spawn in intervals which run towards the Eversong Rangers, which they then kill. 

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Eversong_Ranger

**Comment by Dootz** [comment]
thanks for report, will be fixed with next ptr update
