### ISSUE TITLE
[Paladin] Spiritual attunement doesn't trigger from greater heal

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#3300]
Description: Spiritual attunement doesn't give mana back from greater heal

How it works: https://imgur.com/a/yJwySu7

How it should work: Should get mana off of all heals

Source (you should point out proofs of your report, please give us some source):

**Comment by babno** [comment]
Another pic https://imgur.com/a/pFPAGEM

It looks like it's underperforming on direct heals but giving correct mana on hots. The initial regrowth of 1200 gives 67 when it should give 96, meaning it is giving ~5.5% instead of 8.

**Comment by pinkisnotgay** [comment]
Bumping this. Please fix, this bugs makes us prot palys drink every pack in a dungeon, due to lack of mana.

**Comment by babno** [comment]
Healing wave this time. https://imgur.com/a/kwlsHwt

It seems really random, I've had everything from 0 mana to some random amount to the correct amount. Hots are the only thing I've seen that consistently work well.

I wonder if it might be using a different max hp, maybe the casters? To explain I'll use the picture above as an example. I was at 6k hp prior to the heal, got the 4k heal, but since the caster (razavious) only has 6.9khp max, the spiritual attunement code thinks only 900 is effective healing thus I only get 90 mana even though the entire 4k heal was effective on me.

**Comment by lanki92** [comment]
I add my screenshot of problem.

https://imgur.com/a/6iwmLks

On screenshot you can see the first heal, which had bad formula for mana. 

Spiritual Attunement Rank 2

A passive ability that gives the Paladin mana when healed by other friendly targets' spells. The amount of mana gained is equal to 10% of the amount healed.

4256 heal * 0.1 = 425,6 => I can get 425 mana back, but I got only 326.

The second heal from healer doesnt trigger SA at all.

**Comment by akrom23** [comment]
More info:
#4090
