### ISSUE TITLE
[NPC] Eiin in Lower City missing patterns to sell

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#3303]
Description: Eiin the Specialty Tailoring Supplies vendor in Lower City is missing some patterns to sell. He should sell Pattern: Netherweave Robe and Pattern: Netherweave Tunic but he is not selling them. I was able to purchase these and see them in his merchant tab last night before the realm update.

How it works: ^

How it should work: He should sell these patterns and not be missing them completely.

Source (you should point out proofs of your report, please give us some source):

**Comment by MathiasWreder** [comment]
I feel the same way. Ive been checking this NPC since the update and the pattern has not been available since. Please fix so we can skill tailoring above 350.

**Comment by AshhSunwell** [comment]
Can confirm this, it it isn't on the Swamprat Post vendor either

**Comment by Adrestiah** [comment]
https://www.wowhead.com/item=21897/pattern-netherweave-tunic

This should be a pattern sold on the listed NPCs, though it seems to be missing on some of them. 
It is sold by the Silvermoon merchant.
