### ISSUE TITLE
Frankly, It makes no sense.

### ISSUE THREAD

**Issue by magicborne** [SunwellWoW/Sunwell-TBC-Bugtracker#3304]
Not working at all.

You click on the machine and nothing happens.

**Comment by Jeansapin** [comment]
What is that shitty report, can you just take a screenshot, or link something that you're talking about ?
Maybe a video from youtube to show how the quest should work ? https://www.youtube.com/watch?v=ebySnNcXSnU
Jesus christ ...

**Comment by magicborne** [comment]
Its not my job to provide information about how the quest should work.  They should know it by themself,  otherwise dont start running a tbc server.  Our job is to report if its not working, not teach them how to.

**Comment by Jeansapin** [comment]
It's probably something about respect, I don't know ...

**Comment by Azathothh** [comment]
#3106
