### ISSUE TITLE
[Instance] Broggok issues

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#3305]
Description: broggok, the 2nd boss, is severely bugged in several ways.

How it works: Firstly he builds threat on the healer while inactive. Thankfully you can taunt him. Much more importantly though is his poison clouds. They're either invisible or dealing damage far outside their visual radius. It's impossible to avoid the damage for melee and tank.

https://imgur.com/a/4u8fhbe

During this attempt the tank (waffles) literally never stopped moving, and was visually never in the poison cloud. However as you can see he was still taking massive damage from it. It's nearly impossible especially if you're melee heavy.

How it should work: Poison clouds should only deal damage within the visual radius.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed, will be implemented with next update.

**Comment by westerngee** [comment]
it still hasn't been fixed. had the same exact issue several times over the last few days
