### ISSUE TITLE
Problem with jewelcrafting

### ISSUE THREAD

**Issue by markopaun** [SunwellWoW/Sunwell-TBC-Bugtracker#3306]
Description: 
Hello there, I'm Svarog.
I'm having a problem with Thorium Settings. And I've lost 3 stacks of Thorium Bars for that bug.

How it works: 
It's taking 3 of Thorium Bars to make 1 Thorium Settings, even though it's saying that I need only 1 for it,

How it should work: 
I think it should be as it is written, 1 Thorium Bar for 1 Thorium Setting.

Source (you should point out proofs of your report, please give us some source):

**Comment by babno** [comment]
Out of curiosity, what happens if you try to make a setting with only 1 bar in inventory?

**Comment by markopaun** [comment]
It's staying that the item is not ready, if I'm not mistaken.

**Comment by ZhengSim** [comment]
It's intended. See https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2519
