### ISSUE TITLE
Auch Crypts

### ISSUE THREAD

**Issue by groveunder** [SunwellWoW/Sunwell-TBC-Bugtracker#3308]
Description: 
Combat bug after attacking the Yellow, non aggressive mobs. EVERYTIME.

How it works: 
If you were killing a pack of aggressive mobs, and a yellow-non, was nearby and got attacked, it would keep you in combat, after all are dead. Only way to reset it was running out of instance or logging out. Bit of a pain ay. Made the dungeon take at least another 20minutes than it should have.....

How it should work: 
Derp shouldn't be in combat.

Source (you should point out proofs of your report, please give us some source): 
World Of Warcraft . com

**Comment by Azathothh** [comment]
#3293 #3256
