### ISSUE TITLE
Jero'me dialogue

### ISSUE THREAD

**Issue by shander2355** [SunwellWoW/Sunwell-TBC-Bugtracker#331]
Decription: 

How it works:  Jero'me has the correct pathing while walking underneath the Silvermoon bridge. He has no dialogue, and he has the wrong greeting when talking to him. 

How it should work: He should ask to tell you a poem, he also should have some dialogue while walking around near Silvermoon. 

Source (you should point out proofs of your report, please give us some source): https://wow.gamepedia.com/Jero%27me

**Comment by Dootz** [comment]
will be fixed with next ptr update
