### ISSUE TITLE
[Druid][Moonkin Form] Built in mana restore on melee doesnt function

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#3311]
Description: Moonkins have a large chance to restore mana relative to attack power in moonkin form, this function does not work

How it works: Cannot gain mana via melees in moonkin form

How it should work: as the tooltip suggests, restoring mana, quite efficiently at that

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Works fine.
![wowscrnshot_011019_204743](https://user-images.githubusercontent.com/1035215/50993050-01330f80-1519-11e9-975a-101cadde6398.jpg)
