### ISSUE TITLE
Chain heal source

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#3312]
Description: It should be able to bounce back to the shaman if the shaman has taken damage

How it works: It can't bounce to or through the shaman if cast on another team member

How it should work:  It should be able to bounce back to the shaman if the shaman has taken damage

Source (you should point out proofs of your report, please give us some source):
 https://legacy-wow.com/tbc-shaman-guide/
https://gyazo.com/c30598b64db12c4adbe60c86df0d52bc
gyazo is from the website

**Comment by notsofamous** [comment]
This guide doesn't even know the jump range of chain heal, so I wouldn't trust it 100%. Need video evidence.

**Comment by Avishai97** [comment]
it's from 2008 and they sure as hell wouldn't type that chain heal can bounce back to the shaman if it couldn't, it's hard to make a miss like that seeing as this person who wrote the guide seems to know alot about the subject.

**Comment by notsofamous** [comment]
http://wowwiki.wikia.com/wiki/High_King_Maulgar guide from 2007 that states that Kiggler the Crazed's Arcane Shock has a DoT component, which isn't true.

A lot of information from this era isn't accurate beause it was written by people who didn't really know the mechanics properly. It might be true about chain heal, but a video link would be your best source for this.

**Comment by Avishai97** [comment]
https://youtu.be/9oQc0zg8Acc?t=101
The cast he is doing on the warrior does 3k healing and bounces back to him for 1.5k

**Comment by Avishai97** [comment]
https://gyazo.com/5dd2b4cb2cf5b9a25fca90b39809bb1e
this is how it works at the moment which is wrong, since I have taken damage it should bounce back

**Comment by Avishai97** [comment]
https://gyazo.com/874d74e667f3f5a94e13e3214be5ba9c
combat log

**Comment by Reflekz** [comment]
I've just started healing dungeons and noticed the same thing and was about top open a ticket in regards to it.

Shaman's Chain heal does not bounce on the caster itself unless the chain heal starts with the caster.

Example , you chain heal your teamate standing next to you and it will not heal you , which it should.
idk where you can find source of this , probly some video from back then.

**Comment by Avishai97** [comment]
http://wowwiki.wikia.com/wiki/Chain_Heal
Doesn't state any change from being unable to bounce back to the shaman, which it can in later patches for sure.

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3281
