### ISSUE TITLE
Lightning overload generating threat

### ISSUE THREAD

**Issue by thedonnager** [SunwellWoW/Sunwell-TBC-Bugtracker#3314]
Description: 
The talent proc generates threat

How it works: 
Should not be generating threat

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by waterloorick** [comment]
As we get more gear, this is becoming a serious problem. Especially in Heroics.

**Comment by akrom23** [comment]
Works fine.
Threat meters work bad with this talent.
