### ISSUE TITLE
[Druid] Cannot cast abilities in Flight or Travel form

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#3319]
Description: Cannot cast abilities in this form, as it is trying to cast spells from the cat and bear hotbars respectively

How it works: Shift into travel or Flight form, try to cast rejuv, moonfire, barkskin, anything. It will tell you you must be in cat form, or you must be in bear form, or you cannot attack that target.

How it should work: It should automatically unshift me from travel or flight and allow me to cast.

Source (you should point out proofs of your report, please give us some source):

**Comment by notsofamous** [comment]
https://i.gyazo.com/939e1430ba9b5ea1ed79f5a7377c65f2.mp4

works fine for me

**Comment by Moobe123** [comment]
Workes when you click yes, but if you use the bind it doesn't work. This issue is already posted.

**Comment by notsofamous** [comment]
works when I use bind also

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/50015874-f2b01180-ffc7-11e8-8809-21a7e5e3541e.png)
Make sure that you've got this enabled (i know it's not related to travel form, but check it just in case).
Please try doing it with all addons disabled (probably addon issue) and post some screens/video.

Works fine for me.

**Comment by Jseay1313** [comment]
So this was actually working yesterday as you mentioned. I was able to cast in travel and flight form. As of this most recent reset for Kara it stopped working again, included is a screenshot showing I have auto dismount enabled, second is a clip of it not working again.

https://imgur.com/a/MpOMFI5

https://www.youtube.com/watch?v=DOlVLwz6XtU&feature=youtu.be

**Comment by Jseay1313** [comment]
https://imgur.com/a/xEMZHyy

Trying to press shadowmeld in flight form giving me the must be in cat form error, so that seems to be the problem.

**Comment by Moobe123** [comment]
Since I removed an addon related to keypresses it's working for me. Meaning addons like "Speedyactions" and "snowfall keypress" could be the thing causing this issue.

**Comment by akrom23** [comment]
Works fine.
