### ISSUE TITLE
[Druid] Primal Fury talent not working

### ISSUE THREAD

**Issue by epsota** [SunwellWoW/Sunwell-TBC-Bugtracker#3326]
Description:  Rake and Claw crits are not adding additonal combo points. I have not tested to see if this talent is working in Bear form. This is a significant DPS loss for feral cats. This issue has been reported several times and closed, but is still not working: #1757 and #1281 

How it works:  Rake and Claw do not add an additional combo point, when they critical strike.

How it should work: With two points in Primal Fury every skill based crit should add an additional combo point.

Source (you should point out proofs of your report, please give us some source): 
Self tested: further testing required!

**Comment by ghost** [comment]
It seems to be working for me

**Comment by epsota** [comment]
@Torpis yup it is working again for me. It was not working an hour ago. not sure what changed but glad it is working again.
