### ISSUE TITLE
Bloodmaul Skirmisher

### ISSUE THREAD

**Issue by jockeboschko** [SunwellWoW/Sunwell-TBC-Bugtracker#3327]
Description: 
Kicks to often

How it works: 

Right now trying to kill these mobs with a caster i first get shadowlocked then firelocked instantly after. The only way not to get locked is for the mob to miss.
How it should work: 
There should be cooldown on kick or casters are gonna have a bad time.

Source (you should point out proofs of your report, please give us some source):

**Comment by sadfx** [comment]
Same mob also regains full HP when I tried to kill it with ranged attacks during its "Bloodmaul Rage" enrage type of spell (some weird evade bug perhaps)

**Comment by babno** [comment]
RE the heal, they have an ability to gain 20% of their hp. It's clearly bugged or is spammed to get to 100%

https://www.wowhead.com/npc=19948/bloodmaul-skirmisher#abilities
