### ISSUE TITLE
Druid can parry

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#3328]
Did you know that druid can parry?:> Even when he hasn't parry skill and with 0% parry chance?

I saw this only on low lvl mobs.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_121318_113532](https://user-images.githubusercontent.com/43937876/49942206-f1f27f00-fee4-11e8-8588-b2f274a085e2.jpg)
![wowscrnshot_121318_112057](https://user-images.githubusercontent.com/43937876/49942207-f28b1580-fee4-11e8-9cbf-821d8be2db27.jpg)

**Comment by dredd-sunwell** [comment]
You are right, druids shouldn't be able to parry. I suggest to stick to the bug-reporting pattern though:)
