### ISSUE TITLE
Hit-rating gems bugged?

### ISSUE THREAD

**Issue by Zorbakk** [SunwellWoW/Sunwell-TBC-Bugtracker#3329]
Description: 
I got an new pair of legs without hit rating. I bought 3 hit rating gems and put them on. As you can see in the video I dont get any hit rating from the actual legs. 

How it works: 
Does not give any hit

How it should work: 
Should give hit

Source (you should point out proofs of your report, please give us some source): 

https://youtu.be/7sLXNSIHTBc

**Comment by metavitaminbg** [comment]
You need to put gems with Spell hit rating, not ordinary hit rating.
