### ISSUE TITLE
Silvermoon RP

### ISSUE THREAD

**Issue by shander2355** [SunwellWoW/Sunwell-TBC-Bugtracker#333]
- [x] Gatewatcher Aendor when you walk into Silvermoon should give you some sort of dialogue. 
 https://wow.gamepedia.com/Gatewatcher_Aendor
 
 
- [x] Arcane Guardians throughout the city should have dialogue while walking about Silvermoon. Currently, from what I've seen they have none. 
 https://wow.gamepedia.com/Arcane_Guardian
 
 
- [ ] The Tauren Chieftans should emote cheer back when you cheer at them.
 https://www.wowhead.com/npc=23626/sig-nicious
 https://www.wowhead.com/npc=23619/bergrisst
 
- [x] There should be a scripted event in the Bazaar where Lyria Skystrider and Priest Ennas are explaining to the citizens of Silvermoon why they should trust the horde. 
http://wowwiki.wikia.com/wiki/Lyria_Skystrider
https://wow.gamepedia.com/Priest_Ennas
https://imgur.com/a/sqyXBYt
https://imgur.com/a/S2HHydQ

- [x] Conjurer Tyren in the Bazaar should occasionally cast Fireworks and Evocation while walking around.
- [x] https://wow.gamepedia.com/Conjurer_Tyren

- [x] Alot of random merchants and trainers throughout Silvermoon are simply just walking around when they shouldn't be.
 https://www.wowhead.com/npc=16637/welethelon#sells
 https://www.wowhead.com/npc=16691/noraelath
 https://www.wowhead.com/npc=16650/bithrus
 https://wow.gamepedia.com/Harene_Plainwalker

- [x] In Murder Row, in the rogue training area Instructor Cel should be teaching Trainee Alcor and Trainee Firea. Trainee Sinthar should be stealthing between dummies and casting abilities.
https://wow.gamepedia.com/Trainee_Alcor
https://wow.gamepedia.com/Trainee_Firea
https://wow.gamepedia.com/Cel
 https://wow.gamepedia.com/Trainee_Sinthar

- [x] Trayanise is not correctly chasing the robot around in the Court of the Sun.
 https://www.wowhead.com/npc=18230/trayanise
 
- [x] In Murder Row where the Warlock trainer's are located Blood Elf Warlocks should be channeling a green beam. Also, Keyanomir, at night time should be walking around with his succubus in Murder Row.
 https://imgur.com/a/wfrlFzU
  http://wowwiki.wikia.com/wiki/Keyanomir

- [x] Silvermoon City Guardians should salute back when you /salute them. They should also have unique emotes for paladins.x
https://wow.gamepedia.com/Silvermoon_City_Guardian

- [x] Blacksmiths in Silvermoon should occasionally hit the Anvil. They should also not be walking around aimlessly.
 https://imgur.com/a/n021KO4

- [x] Silvermoon Rangers and Farstriders should be either hitting the dummie with their bow or using a knife, they are just standing around right now.
 https://www.wowhead.com/npc=18147/silvermoon-ranger
 https://wow.gamepedia.com/Silvermoon_Farstrider

- [x] Ambassador Kelemar should be escorting the Horde Emissaries around Silvermoon as of right now they are just walking around in the The Royal Exchange. He should have certain dialogue when he escorts them to various places. 
https://www.wowhead.com/npc=18191/ambassador-kelemar#comments

- [x] Some of the Silvermoon City guardians are not patrolling correctly.

- [x] Champion Vranesh should not be just in front of the Royal Exchange he should be patrolling around Silvermoon.  He should also have unique emotes when around other guards.
https://www.wowhead.com/npc=18146/champion-vranesh#comments

 I understand that these are relatively very small issues in the grand scheme of things and these are not top priority over game mechanics, raids, etc. But these small details in Major Cities, etc differentiate a server from just being good to great. There may be other things I may have missed but these are the ones I've noticed the most.

**Comment by notsofamous** [comment]
- [x] Missing Battle Masters

![Image](https://i.gyazo.com/9cc4bf0accb49aae7b495a015cd3b51c.png)

https://youtu.be/9AmzyAZX6c8?t=236

- [x] Missing Paladin trainer

Retail:
![Image](https://i.gyazo.com/66a7cec5f987bccb9e5ee2b52f4bd7b4.png)

Sunwell:
![Image](https://i.gyazo.com/5e00abe734a9689d7aa73443a3807371.png)

https://youtu.be/9AmzyAZX6c8?t=216

- [ ] Missing conversations between Initiate Colin and Initiate Emeline

> Initiate Emeline: Our neighbors are positively laughable. Have u seen the way they turn up their noses at us?
Initiate Colin: I know what you mean... They whisper about us when they think we can't hear them. They'll get theirs.
Initiate Emeline: Still, the Blood Knights will endure through this loss. We have no other choice... We must find another source.

> Initiate Emeline: The rangers certainly have a high opinion of themselves.
Initiate Colin: Jealous, that's what they are. They're afraid to dedicate themselves to true power.

> Initiate Emeline: I'm quickly tiring of the haughty attitude I receive from those grubby bowslinger outside.
Initiate Colin: They simply fear what they cannot begin to understand.
or
Initiate Colin: Who do they think they are?

In 2.4 they get a new conversation

> Initiate Emeline: Matters are so uncertain now that the chamber below is empty...
Initiate Colin: Is... it true, what I've heard? That it was the Sun King Himself?
Initiate Emeline: It's gone. I can't believe it's gone. Who would have thought we'd be betrayed like this?
Initiate Colin: Lady Liadrin is bound to find a way. She must.

https://www.wowhead.com/npc=18174/initiate-colin#comments

- [ ] Prior to 2.4 M'uru was present in Silvermoon City

- He should be drained by 5 Blood Elf Magisters positioned around the room.
- Lord Solanar Bloodwrath should be removed (added in 2.4)
- Lady Liadrin should be moved here from Shattrath. (Positioned to the left in the room next to Magister Astalor Bloodsworn)

https://youtu.be/9AmzyAZX6c8?t=271

- [ ] Bithrus should be standing still, sometimes walk over and kneel at a box of fireworks. Should occationally shoot fireworks. 

> Periodically, Bithrus shoots off a firework for display. His reported repertoire is five different displays:
    Blue Firework
    Green Firework
    Purple Firework
    Red Streaks Firework
    Yellow Rose Firework


![Image](https://vignette.wikia.nocookie.net/wowwiki/images/f/fe/Bithrus.jpg/revision/latest?cb=20070120024759)
http://wowwiki.wikia.com/wiki/Bithrus
https://youtu.be/NKrscS5dNNM?t=99
https://www.wowhead.com/npc=16650/bithrus#abilities

- [ ] Harene Plainwalker should sometimes kneel down to "pick up" a flower.

![Image](https://wow.zamimg.com/uploads/screenshots/normal/85529-harene-plainwalker.jpg)

- [ ] Trainee Sinthar sometimes faces the wrong direction when attacking the dummy. He should also walk over to a different dummy and do a "use" animation.

> all he does is attack one of the target dummies and use the crafting animation on the other, always in stealth. Just an extra thing to look at in the rogue section.

https://www.wowhead.com/npc=18628/trainee-sinthar#comments

- [ ] Darlia walks on and inside tables.

- [ ] Keyanomir and his pet Nimrida should be standing next to the mailbox at these cords looking at each other: 
![Image](https://i.gyazo.com/893e56bb6b0517bc50911d798be57a05.png)
![Image](https://i.gyazo.com/93e5f4af75e2fcd85ca5a54a63146bcd.png)

Sometimes (maybe once pet hour) they will walk down to the warlock trainer and then back up again.

https://www.wowhead.com/npc=18231/keyanomir#screenshots
https://www.wowhead.com/npc=18232/nimrida#screenshots

- [ ] Sirigna'no should be standing still next to the table with gold on it. Occationally she will walk around the room and whip the gnomes.

> From time to time she take a walk around the room and whip the Leper Gnome Laborers that work there, first she walks over to the one in the cage then whip the rest of the working Leper gnomes then walks over to a resting one and whip him, by that he getts up and run over to a mana loom and starts to work. 

https://www.wowhead.com/npc=18730/sirignano#comments

- [x] Herald Amorlin missing gossip

- [x] Officer Dawning missing gossip

- [x] vendors Welethelon and Noraelath should be standing still.

- [x] Conjurer Tyren doesn't always have an animation when he casts evocation.

- [ ] Silvermoon Ranger all select their targets in a weird manner, they should be aiming at the closest target dummy.

- [x] Mirvedon should be facing the anvil when he's hammering.

- [ ] Bemarrin sometimes walks up on the anvil and forge.



### Videos:
https://youtu.be/NKrscS5dNNM
https://youtu.be/9AmzyAZX6c8
