### ISSUE TITLE
ferocious inspiration

### ISSUE THREAD

**Issue by jockeboschko** [SunwellWoW/Sunwell-TBC-Bugtracker#3332]
Description: 

The buff from BM hunter ferocious inspiration stacks
Atleast visually
How it works: 

The buff from BM hunter ferocious inspiration stacks
Atleast visually
How it should work: 

Should not stack
Source (you should point out proofs of your report, please give us some source):

**Comment by MiekZer** [comment]
https://www.wowhead.com/forums&topic=26477
K thx bye.
Should stack, it's how it was in tbc, and that's why we have hunters group with feral & enhancement
