### ISSUE TITLE
[NPC] Daga Ramba - Potion Vendor

### ISSUE THREAD

**Issue by GrandMarshal** [SunwellWoW/Sunwell-TBC-Bugtracker#3335]
Description: 
The Alchemy recipe vendor Daga Ramba doesn't sell the dreamless sleep potion recipe, this is currently blocking access to the Master of Potions alchemy specialization. It does not seem to be a stock issue as the other potions are properly displaying stock (grayed out when out of stock) but this one is completely missing from the vendor UI.

How it works: 
Daga Ramba sells only  [Recipe: Super Mana Potion] [Recipe: Elixir Major Defense] and [Recipe: Elixir of Camouflage]. With the [Recipe: Major Dreamless Sleep Potion] missing from his stock.

How it should work: 
He should also sell the [Recipe: Major Dreamless Sleep Potion] at limited stock.

Source (you should point out proofs of your report, please give us some source): 
[This comment on wowhead.com saying the recipe was added Jan the 31st in patch 2.0.6](https://www.wowhead.com/npc=19837/daga-ramba#comments:id=28727) (Note downvoted only because of the spelling error)

**Comment by NickBrah** [comment]
bump, this is important to fix because it's limited supply and there will be an artificial bottleneck preventing people from progressing their professions (the spawn timer) if not fixed soon.

**Comment by Zizzal** [comment]
Any update on this?

**Comment by danelmore** [comment]
Still not fixed. Strange that you can buy the potions in ah for almost 100g for 5.  Was apparently in at some point and removed.  Grate to whoever got it. They are rich, only need 50 people to buy 5 pots each and you got epic flying.

**Comment by Dootz** [comment]
Hi,sorry for delayed response. From what I can tell it can be bough on both sides.
