### ISSUE TITLE
Multi attacks from mobs

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#3336]
Description: 
Some mobs attack few times in 1 melee swing. They are mobs for quest, in dungeons. It could be also buff like thorns. Sometimes everything is okey and sometimes I got 7 swing for 250 dmg each, of every attack on pig in Hellfire made me 175 dmg from thorns.

How it works: 
Some mobs do 2-7 dmgs in one swing.

How it should work: 
Mobs should hits only once per swing.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120818_101312](https://user-images.githubusercontent.com/43937876/49953677-ee6bf180-fefe-11e8-9da3-9988e8010b40.jpg)
![wowscrnshot_120818_150439](https://user-images.githubusercontent.com/43937876/49953678-ee6bf180-fefe-11e8-8576-b21c3efd8169.jpg)
![wowscrnshot_121018_205028](https://user-images.githubusercontent.com/43937876/49953679-ef048800-fefe-11e8-8d15-35a8711c0350.jpg)
![wowscrnshot_121018_205032](https://user-images.githubusercontent.com/43937876/49953680-ef048800-fefe-11e8-832f-a012a904d570.jpg)
![wowscrnshot_120618_104816](https://user-images.githubusercontent.com/43937876/49953789-32f78d00-feff-11e8-895d-7c5f1f607dea.jpg)
![wowscrnshot_120618_104900](https://user-images.githubusercontent.com/43937876/49953791-32f78d00-feff-11e8-89e9-0df76e8685d1.jpg)

**Comment by Dootz** [comment]
Hi, it's due to ability "Trash" working incorrectly right now. Thank you for report, we'll look into it.
