### ISSUE TITLE
Warrior Fear breaks from ALL damage instead of chance to break on damage

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#3337]
Description: 
Warrior Fear breaks from ALL damage instead of chance to break on damage

How it works: 
There is a percent chance for all fears to break on damage. Warrior fear will instantly break from any amount of damage instantly every time. From pure damage or dots, doesnt matter.

How it should work: 
All fears, including warrior fear, should have a chance to break on damage not guaranteed removal even from dots.

Source (you should point out proofs of your report, please give us some source):

**Comment by sicknot1** [comment]
can confirm, example: there are a bunch of feralas ogres hitting you, you cast Intimidating Shout, fear applies to everyone, then you hit your main target again and it instantly breaks.

**Comment by gigin15** [comment]
Yup fear breaks instantly on any damage. Where they usually can take a hit or two before breaking
