### ISSUE TITLE
Patterns missing (reputation)

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#3344]
http://wowwiki.wikia.com/wiki/Pattern:_Netherscale_Ammo_Pouch_(Alliance) 
IS MISSING.

And I guess others are also missing.

**Comment by notsofamous** [comment]
Added in patch 2.3
https://www.wowhead.com/item=34106/netherscale-ammo-pouch

**Comment by Jseay1313** [comment]
Do you plan on adding these Dootz, if so there are other gem recipes and things missing that came out in 2.1 and 2.3 so - just curious i.e great dawnstone from 2.1

**Comment by netherneth** [comment]
> Added in patch 2.3
> https://www.wowhead.com/item=34106/netherscale-ammo-pouch

 Patch 2.0.3 (09-Jan-2007): Added  ???

**Comment by Dootz** [comment]
Hi, 
sorry for late response. As far as I know this pattern was removed intentionally and will be added with "patch 2.3"
