### ISSUE TITLE
Theramore deserter in feralas

### ISSUE THREAD

**Issue by sicknot1** [SunwellWoW/Sunwell-TBC-Bugtracker#3345]
Description: 
How it works: 
Picture CORDS: 37.0 33.1

How it should work: 
Theramore deserter shouldn't be here 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_121318_160743](https://user-images.githubusercontent.com/35937937/49961425-63382f00-fef1-11e8-91f9-7bc132b0e518.jpg)

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3602
