### ISSUE TITLE
(Dungeon) Slave pen's - Normal - mobs lvl 69

### ISSUE THREAD

**Issue by bakfull** [SunwellWoW/Sunwell-TBC-Bugtracker#3349]
Description: 
Mobs too high level
https://gyazo.com/c87a6fa25a4149289cce2b5d91241052
How it works: 

https://gyazo.com/c87a6fa25a4149289cce2b5d91241052
How it should work: 

Shouldnt be level 69 for sure
Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/c87a6fa25a4149289cce2b5d91241052

**Comment by bakfull** [comment]
Coilfang tempest is the mob that is higher level

**Comment by thebagholder** [comment]
There are also level 70 and 71 mobs in normal Slave Pens
