### ISSUE TITLE
Creature cast interrupting

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#335]
Hi,

Plenty of (dunno if all of them) casters interrupt their own casts and start to cast new spell. Most of them have several cast spells. If im not wrong it never happens when npc has only one spell to cast, but if it has more then it interrupts cast spell by casting another spell.

Example: "10647 Prince Raze - he does it every time. He casts Fireball then stops, start cast Fire Nova then stops, start to cast Charged Arcane Bolt and so on".

**Comment by lukaasm** [comment]
select * from creature_ai_scripts where ( action1_type=11 and action1_param2 & 1 ) OR ( action2_type=11 and action2_param2 & 1 ) OR ( action3_type=11 and action3_param2 & 1 );

~3 892 old EventAI entries which tells creature to cast and interrupt previous, should we mass change it?

**Comment by akrom23** [comment]
Need test!

**Comment by notsofamous** [comment]
Still interrupts his spell.
