### ISSUE TITLE
no rested state Stonebreaker Hold

### ISSUE THREAD

**Issue by Fearless83** [SunwellWoW/Sunwell-TBC-Bugtracker#3350]
Description: there´s no rested state in the inn and log off dosent work as it should be 

How it works: 
when i went to inn that zzz didnt come to my character portrait and if i log off it says in need to wait 20seconds.

How it should work: instantly when i go near innkeeper  i should be getting that zZz market to my portrait and able to log off also instantly 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_121318_220756](https://user-images.githubusercontent.com/45545356/49964860-3cdfb700-ff24-11e8-9bda-9ee5149d9600.jpg)

**Comment by akrom23** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1634
