### ISSUE TITLE
[Dungeon] Black Morass last boss not dropping enough loot in normal mode

### ISSUE THREAD

**Issue by Leiffis** [SunwellWoW/Sunwell-TBC-Bugtracker#3351]
Description:  Last boss (Aeonus) drops only 1 item instead of 2.

How it works: Aeonus drops 1 item

How it should work: Aeonus should drop 2 items

Source (you should point out proofs of your report, please give us some source):  There was another thread about this but it wasnt tagged or anything: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3129

**Comment by chme3921** [comment]
Figured it would be fixed with the fixes to BM today, but apparently not

**Comment by xrewz** [comment]
Done 50 runs and still no latros sword drop. This bugged drop rate is makeing this instance a nightmare for rogues trying to get their bis offhand.
