### ISSUE TITLE
[Quest] A Dip in the Moonwell

### ISSUE THREAD

**Issue by ahlens** [SunwellWoW/Sunwell-TBC-Bugtracker#3352]
**Description:** 
Currently, you are unable to leave "piloting mode" by any means. You have to wait 2 min untill it ends.

**How it should work:** 
You should be able to cancel "piloting mode" by right clicking buff icon.

Source (you should point out proofs of your report, please give us some source): 
[A Dip in the Moonwell](https://tbc-twinhead.twinstar.cz/?quest=9433)

**Comment by Azmoddan** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2740
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2125
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/908
@Dootz
It is being repeatedly reported, should be fixed quickly it is one of the easier and one the most often done quests in Thousand Needles.
