### ISSUE TITLE
Clicking Eggs for [What Came First, the Drake or the Egg?] does nothing

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#3353]
Description: 
Clicking Eggs for [What Came First, the Drake or the Egg?] does nothing

How it works: 
Clicking Eggs for [What Came First, the Drake or the Egg?] does nothing

How it should work: 
spawns adds

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
#2367
