### ISSUE TITLE
[Test Flight: Ruuan Weald] does NOT get completed after jump

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#3356]
Description: 
I did not get credit for [Test Flight: Ruuan Weald] after jumping and landing.

How it works: 
[Test Flight: Ruuan Weald] does NOT get completed after jump

How it should work: 
Completion after jump should be automatic.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/OsCjVYl

**Comment by Dootz** [comment]
Did you use https://www.wowhead.com/item=31124/nether-weather-vane while flying?
