### ISSUE TITLE
 [The Third Fleet] Quest not working or has too long waiting time idk?

### ISSUE THREAD

**Issue by Hjodienew99** [SunwellWoW/Sunwell-TBC-Bugtracker#3357]
Description:  [The Third Fleet] quest item that should be appearing in the basement of the 10.5 61.4 seems like not appering i waited like 10 min. i guess might be my bad

How it works: 
Item is not showing up

How it should work: 
If quest is working spawn time should be changed

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=288/the-third-fleet

**Comment by Azathothh** [comment]
You're supposed to buy it from vendors. Closest one is Innkeeper Helbrek.
Barrell in basement wasn't there during TBC
