### ISSUE TITLE
Victory Rush does not happen from Sweeping Strikes or Whirlwind damage

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#3358]
Description: 
Victory Rush does not happen from Sweeping Strikes or Whirlwind damage

How it works: 
Victory Rush does not happen from Sweeping Strikes or Whirlwind damage

How it should work: 
Should let me use Victory Rush after I kill anything that gives xp or honor in any way.

Source (you should point out proofs of your report, please give us some source):

**Comment by Nelthalor** [comment]
It shows that Victory Rush should be usable with MSBT addon as well when it doesnt let me use it.

**Comment by Nelthalor** [comment]
I just tested, its not that Whirlwind doesnt set it off. Just anything that is not primary target will not activate Victory Rush.

**Comment by Dewsch** [comment]
I believe it's deep wounds ticking that isn't triggering it.

**Comment by akrom23** [comment]
Tested - works good.
