### ISSUE TITLE
Druid Bugs

### ISSUE THREAD

**Issue by Rogvarok** [SunwellWoW/Sunwell-TBC-Bugtracker#3363]
Description: 
Omen of clarity not proccing clearcasting, and primal fury not granting additional combo points in cat form.

How it works: 
Omen of clarity doesnt proc at all, primal fury only granting 1 combo point on crit

How it should work: 
Omen of clarity should proc, and i should get two combo points per crit in cat form

Source (you should point out proofs of your report, please give us some source): 

![doesntwork1](https://user-images.githubusercontent.com/45863842/49978782-16b51980-ff1a-11e8-8968-67a259fabb5e.png)

Cannot post a picture of omen of clarity not proccing, because its not possible.

**Comment by Rogvarok** [comment]
Added comment : about 5 minutes after i posted this, the procs from clearcasting started coming back and combo points returned to normal as well? was this hotfixed or just an intermittent problem?

**Comment by Altgreen** [comment]
I had the same experience, yesterday it stopped working, then this morning it seemed to right itself and now it's broken again.
