### ISSUE TITLE
Battle of the Crimson Watch- No quest reward.

### ISSUE THREAD

**Issue by scotjamieson21** [SunwellWoW/Sunwell-TBC-Bugtracker#3364]
Description: 
Battle of Crimson watch, reward problem.
quest that is part of a chain in Shadowmoon Valley that leads to the acquirement of an illdrani tabard.
When i handed in the quest i was supposedly given"offering to the sha'tar" only to not be able to find it in my bags.

How it works: 
you hand the quest in, it gives you the ring and not the box.

How it should work: 
 it should give you the ring and the offering.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=10781/battle-of-the-crimson-watch

**Comment by Azathothh** [comment]
Problem happens if player have only 1 empty slot in bags, but quest rewards 2 or more items.
