### ISSUE TITLE
[Warrior] [Ability] Sweeping Strikes + Whirlwind

### ISSUE THREAD

**Issue by Rattacrash** [SunwellWoW/Sunwell-TBC-Bugtracker#3365]
Description: 
in a privious post about this topic that had been closed, a statemant was made that is wrong.
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/303
akrom23 is refering to a single post on the wowhead forum, and that post is wrong.
it is incredibly hard to find decent sources for solid inforamtion about this topic, the patchnotes of the live client and all otehr sources r very mushy. ill try my best to state my case and point out the error, in the hopes this issue can be resolved and the ability can be made to work as it was intended back on the live realm in 2007

How it works: 
while sweeping strikes is active only 1 sweeping strikes hit is done after performing a whirlwind attack, no matter how manny actual hits were done by that whirlwind

How it should work: 
each hit done by whirlwind needs to be considered as a "swing" i.E. doing whirlwind while dual wielding would end up in 8 swings performed (4 swings for the mainhand weapon, 4 swings for the offhand weapon) by that single attack ability. each of those swings if they hit the target should result in a sweeping strike hit of an additional target nearby and consume 1 sweeping strike charge for each hit performed. leaving the player with only 2 sweping strike charges if the sweeping strike was activated directly before a whirlwind that hit 4 targets with both weapons.
if whirlwind+sweepingstrike is performed with only weapon, be it just the mainhand weapon while wearing a shield in the offhand, or by a two-handed weapon, it would result in 4 hits on 4 targets, and should end up in 4 sweeping strikes beeing performed and only 4 of 10 sweeping strike charges beeing consumed

in the case of the [cleave]-atatck ability it is working correctly while cleave is hitting 2 targets, 2 sweeping strikes hits r performed. here again even tho cleave is 1 attack ability it is performing 2 swings and each of those swings result in a sweeping strikes hit and the cosumption of one sweeping strike charge for each of the hits

Source (you should point out proofs of your report, please give us some source): 
a video from the 2.3 ptr realm in the year 2007, the video was uploaded on youtube on Oct 14, 2007
https://www.youtube.com/watch?v=bWYyXMgmeFU
in this video u can see that the warrior is hitting 2 targets with whirlwind+sweepingstrikes which result in the whirlwind is performing 8 total hits on thsoe 2 targets. 2 hits for whirlwind mainhand hits and 2 hits for whirlwind offhand hits, resulting in 2 sweepingstrike mainhand hits and 2 sweeping strikes offhand hits.

in vanilla WoW sweeping strike was supposed to make an aadditional hit on a nearby target for each ATTACK, since all whirlwind and cleave hits were considered 1 attack, sweeping strike did 1 additional hit for both of theese abilitys.
in patch 2.3 this got changed to "swing" meaning that each hit performed resulted in an sweeping strike hit on an additional target.
https://wow.gamepedia.com/Sweeping_Strikes
"The Burning Crusade Patch 2.3.0 (2007-11-13):
Sweeping Strikes and  [Death Wish] have swapped locations in the talent trees.
Sweeping Strikes now lasts 10 seconds and affects your next 10 swings.
This ability now works correctly in all cases with shielded targets. 
Before the patch, the number of swings was 5."
it is important to note that this change from "attack" to "swing" is the entire point of my post, whirlwind is 1 atatck performing up to 4 swings with a single weapon or a two-handed weapon, or in case of dual wielding performing 8 swings 4 for the mainhand and 4 for the offhand. the games makes a huge diffrence between attacks and swings.

in this post in the elitistjerks-forum a person named Katreal states out some facts about sweeping strikes
https://web.archive.org/web/20130810120034/http://elitistjerks.com/f81/t22705-dps_compendium//
"... Especially since the changes to Sweeping Strikes and Whirlwind, warrior AoE is a formidable force when properly applied..."
"...it's best to time the first sweeping strikes usage of an AoE pull with enough rage to immediately deliver a whirlwind, as well as using any possible short duration cool downs, as SS offers the greatest damage amplification short of Recklessness for the ten swings that it is active..."

i hope that my sources verify my claim and help u guys change sweeping strikes to work in the same way as it had worked back in the day on the live realm

**Comment by ppach** [comment]
Can confirm that as it stands, the interaction between SS + WW is NOT working properly. This should have way higher priority as it has huge effects on Warrior DPS.

**Comment by ppach** [comment]
Bump

**Comment by Kiszh** [comment]
Are we getting any news on this? It's affecting warrior burst cleave quite heavily

**Comment by ppach** [comment]
Bump, please review this.

**Comment by ppach** [comment]
Bump, please review this.

**Comment by akrom23** [comment]
What about this:
https://hilbert.wordpress.com/sweeping-strikes-guide/
I know it's from vanilla.
https://youtu.be/Waq5Hgg7rZ4?t=28

I'm pretty sure it should hit only once per WW.

**Comment by koostosh** [comment]
I cannot find definitive proof that it should hit multiple targets with WW.
