### ISSUE TITLE
the flesh lies...

### ISSUE THREAD

**Issue by Kuikku** [SunwellWoW/Sunwell-TBC-Bugtracker#3368]
Description: 
Quest is impossible to complete.

How it works: 
WHen u get near Withered Corpse it disappears and spawns add who chases u till u die or kill it first.

How it should work: 
Go next to Withered corpse and blast it with Protectorate Igniter to get credit for the quest.

Source (you should point out proofs of your report, please give us some source): 
Go to test it yourself. Im pissed. This is like millionth bug quest im doing today

**Comment by bigripper** [comment]
Can confirm this quest is terribly bugged. Makes it to where you cant complete the other quests in the cave as well.
