### ISSUE TITLE
Harold's Rejuvenating Broach does not increase healing. [Item] [Druid] 

### ISSUE THREAD

**Issue by mjk6994** [SunwellWoW/Sunwell-TBC-Bugtracker#3369]
Description: Harold's Rejuvenating Broach does not increase healing of  rejuvenation at all.

How it works: Harold's Rejuvenating Broach does not increase healing of rejuvenation at all.

How it should work:  Harold's Rejuvenating Broach should increase healing of Rejuvenation BY UP TO 86. (meaning not necessarily 86, but more than 0.)

Source (you should point out proofs of your report, please give us some source): https://cdn.discordapp.com/attachments/432981313117618217/523009615898738698/unknown.png (With Broach)

https://cdn.discordapp.com/attachments/432981313117618217/523009702259326986/unknown.png (Without Broach)

**Comment by mjk6994** [comment]
bump

**Comment by pleasse** [comment]
x( not working

**Comment by mjk6994** [comment]
bump
