### ISSUE TITLE
[Warlock] [Ability] Deathcoil breaks 

### ISSUE THREAD

**Issue by hoborg87** [SunwellWoW/Sunwell-TBC-Bugtracker#3374]
Description: 
Deathcoil breaks

How it works: 
It is currently working as a 'fear' effect - % chance to break on damage, rarely lasting 50% of full duration

How it should work: 
As a "horror' effect - unbreakable for the full 3 seconds

Source (you should point out proofs of your report, please give us some source): 
Casting deathcoil with dots and a pet on target will break it every single time

**Comment by roguestep16** [comment]
how u wanna start arena season if nearly all classes got hughe bugs with talents and spells... thats crazy guys

**Comment by Ganker803** [comment]
Yea this is pretty broken.  

breaks every single time
