### ISSUE TITLE
Steam Vault Heroic - Coilfang Engineer

### ISSUE THREAD

**Issue by popalexandrudan** [SunwellWoW/Sunwell-TBC-Bugtracker#3378]
Description: 
He hits 4.5k 4.5k 4.5k sometimes 3 hits in less than 2 seconds vs capped defence.

How it works: 
He hits 4.5k 4.5k 4.5k 3 hits in less than 2 seconds

How it should work: 
Hit less.

Source (you should point out proofs of your report, please give us some source):

**Comment by xethra89** [comment]
Is it using Thrash? I'm unable to find whether or not that specific mob uses thrash though. 

http://wowwiki.wikia.com/wiki/Thrash

**Comment by Dootz** [comment]
No, from what i can tell he's not using thrash.
