### ISSUE TITLE
Profession inventory full bug.

### ISSUE THREAD

**Issue by Bakster15** [SunwellWoW/Sunwell-TBC-Bugtracker#3379]
Description: 
When your inventory is full and you're crafting items. You loose the materials and don't get the item OR skill. So basically the reagents just get deleted.

How it works: 
If you don't have inventory space for the stuff you create it keeps going and deletes the reagents/item without gaining any skill. Same problem as when you had no inventory and lost quest items because of it. (Hand in quest with 1-2 rewards. Only have 1 inventory space. =Loose one of the rewards. Old bug that was fixed. Same problem with crafting now.

How it should work: Should not use my Reagents if inventory is full and should instead cancel the crafting.

Source (you should point out proofs of your report, please give us some source):

**Comment by firngrod** [comment]
This also happens when trying to create an item with the unique property and of which you already have one.
