### ISSUE TITLE
Karazhan first boss

### ISSUE THREAD

**Issue by Daynar2018** [SunwellWoW/Sunwell-TBC-Bugtracker#338]
Decription: 
First boss dosent work correctly 

How it works: 
you can get horse to 1% and boss to 1% and they dont die

How it should work: 
At 25% on Midnight, the horse and it's owner, Attumen the Huntsman, will go togheter and get full health again

Source (you should point out proofs of your report, please give us some source): 
http://prntscr.com/ksezw1

**Comment by notsofamous** [comment]
Already reported here: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/178

**Comment by Riztazz** [comment]
duplicate
