### ISSUE TITLE
Xp convert to extra golds

### ISSUE THREAD

**Issue by Nautilusy** [SunwellWoW/Sunwell-TBC-Bugtracker#3381]
Description: 
    i found that when i got 70lv and doing quest, XP did not converted into gold. is that a bug or server setting? is that related to my purchase of experience boost?

How it works: 

How it should work: 
    Upon completion of quests，Experience converted into extra gold

Source (you should point out proofs of your report, please give us some source):

**Comment by xethra89** [comment]
It converts, it's just doesn't show it on the quest UI. It was reported here. You get the extra gold. https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3280

**Comment by Nautilusy** [comment]
> It converts, it's just doesn't show it on the quest UI. It was reported here. You get the extra gold. #3280

oh...thanks :D
