### ISSUE TITLE
Karazhan trash

### ISSUE THREAD

**Issue by Daynar2018** [SunwellWoW/Sunwell-TBC-Bugtracker#339]
Decription: 

Karazhan trash 
How it works: 

KARAZSHAN trash aggro range is to HUGE
How it should work: 

Source (you should point out proofs of your report, please give us some source): 
http://prntscr.com/ksf0zb

**Comment by notsofamous** [comment]
Looks normal to me. Standing on top of the stairs should aggro the pats (and any mobs they are close to when they aggro) and the first pack in the room.
