### ISSUE TITLE
Thrallmar reputation in Shattered Halls is broken (should be high prio)

### ISSUE THREAD

**Issue by waterloorick** [SunwellWoW/Sunwell-TBC-Bugtracker#3398]
Description: 6 rep per kill in Shattered Halls is broken

How it works: 

How it should work: 12 rep per kill in Shattered Halls. A regular Shattered Halls clear will yield around 1,640 reputation

Source (you should point out proofs of your report, please give us some source): http://wowwiki.wikia.com/wiki/Shattered_Halls

**Comment by xethra89** [comment]
Here's a video of killing mobs at the end of the run(right before last boss) giving 12 rep per kill. 

https://www.youtube.com/watch?v=sRZE71yPRoA (Normal)

and here's heroic, giving 16-17 rep a kill.

https://www.youtube.com/watch?v=z2pZgpA1cjU (Heroic)

**Comment by LezChap** [comment]
Possibly related to #2813 ?

**Comment by SunwellTracker** [comment]
Will be fixed tomorrow.
