### ISSUE TITLE
[Paladin] [Talent] Conviction doesn't apply +crit chance

### ISSUE THREAD

**Issue by F4play** [SunwellWoW/Sunwell-TBC-Bugtracker#34]
Decription: Retribution 3rd tier talent Conviction (ID#20117-20121) doesn't apply +crit chance to character

How it works: No additional crit chance added to character stats

How it should work: +1% crit per point

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Works for me fine, maybe u had no melee weapon equipped?

**Comment by Azathothh** [comment]
yeah, it's working - you either had no weapon equipped or too low weapon skill
