### ISSUE TITLE
[Quest] Arcane Disturbances & Restless Activity

### ISSUE THREAD

**Issue by Zarant** [SunwellWoW/Sunwell-TBC-Bugtracker#3401]
Currently both quests requires [Archmage Alturus](https://www.wowhead.com/quest=11216/archmage-alturus) gave by [Apprentice Tasserel](https://www.wowhead.com/npc=23948/apprentice-tasserel), however, this NPC and this particular quest were implemented much later in patch 2.3 (November 13, 2007).
The karazhan attunement quests never had a pre requisite. The breadcrumb quest got added much later in patch 2.3 to point new players into the right direction.

Proof:

Those 2 sources says that he was added in 2.3
https://wow.gamepedia.com/Apprentice_Tasserel
https://www.wowhead.com/npc=23948/apprentice-tasserel

If you dig through old databases, you wont find this NPC or this quest pre dating November 2007:
http://wowwiki.wikia.com/wiki/Apprentice_Tasserel?oldid=1030587 - Earliest entry in wowwiki (December 10th, 2007)
http://web.archive.org/web/20080108145453/http://thottbot.com:80/q11216
https://web.archive.org/web/20080406072905/http://wow.allakhazam.com:80/db/quest.html?wquest=11216
https://web.archive.org/web/20071211154934/http://www.wowhead.com:80/?quest=11216

**Comment by babno** [comment]
Adding more sources, as you can see there is no requirement for either of them
https://tbc-twinhead.twinstar.cz/?quest=9825
https://tbc-twinhead.twinstar.cz/?quest=9824
