### ISSUE TITLE
[Rogue] Surprise Attacks - Top tier Combat Rogue talent

### ISSUE THREAD

**Issue by Tyton89** [SunwellWoW/Sunwell-TBC-Bugtracker#3402]
Description: This final tier ability does not seem to work. I'm unsure if it's just the dodge less feature, or if it includes the damage coefficient as well. This ability clearly states that any move labeled as a "Finishing Move" should be undodgeable. Through personal experience I have noticed multiple occurrences where a mob will consistently dodge finishing moves, such as Rupture and Kidney Shot.

How it works: 
Mobs currently have a normal chance to dodge finishing moves even when over hit cap for special abilities, and I have even seen them dodge special abilities while you are behind the target.

How it should work:
The talent should remove any chance for your target to dodge the attack. You should still be able to Miss, or be partied, but this is specifically related to dodge which I've tracked in combat logs.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2415
