### ISSUE TITLE
Combat bug in Shattered Halls (can replicate)

### ISSUE THREAD

**Issue by waterloorick** [SunwellWoW/Sunwell-TBC-Bugtracker#3403]
Description: Stuck in combat from the 1st gauntlet until after 1st boss. (happened exact same way 2 runs in a row).

How it works: whenever you fight inside the 1st gauntlet (with sharpshooters) you get stuck in combat until after 1st boss and until you go up the next ramp.

How it should work: Not stuck in combat

Source (you should point out proofs of your report, please give us some source):

**Comment by Fuzedknight** [comment]
The problem is the Legionnaire spawning a Convert, it should be a Zealot. The convert is part of Nethekurse's event and thus causes his boss fight to trigger. But this is also bugged because after you kill 4 Nethekurse should instantly aggro you which he does not.

**Comment by rychersky** [comment]
We have no one attacking us. Ele shaman relogs and has no issues; out of combat. Resto shaman relogs and is dead in Hellfire Peninsula. Neat.
