### ISSUE TITLE
Illidari-Bane Shard - Trinket is 'not an equippable Item'

### ISSUE THREAD

**Issue by Optilasgar** [SunwellWoW/Sunwell-TBC-Bugtracker#3404]
Description: 
There is an Item Random drop in Shadowmoon Valley called 'Illidari-Bane Shard' ( https://puu.sh/ChEgH/2754e828a9.png ) 
This item is both capable of starting a Quest aswell as being used as a Trinket as long as you don't finish the Quest

How it works: 
It gives an error stating 'This item cannot be equipped.'

How it should work: 
This items should be equipable in either trinket slot

Source (you should point out proofs of your report, please give us some source): 
https://puu.sh/ChEgH/2754e828a9.png
If the item wasn't supposed to be equippable, why is it both marked 'Unique' aswell as have 2 'Equip' Effects?

**Comment by pinkisnotgay** [comment]
THANKS AFFGAN FOR FIXING THIS
