### ISSUE TITLE
Helboar Burning spikes massively over procs sometimes

### ISSUE THREAD

**Issue by wildsure** [SunwellWoW/Sunwell-TBC-Bugtracker#3408]
Description: 

How it works: 
Way too many hits from burning spikes when you hit helboar

How it should work: 
Just one hit

Source (you should point out proofs of your report, please give us some source): 
No proof - getting spiked down doesn't seem right
![image](https://user-images.githubusercontent.com/45885357/50028994-6878a500-ffe9-11e8-986c-4dddb5c6ed49.png)

**Comment by Wojtyas** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2439
