### ISSUE TITLE
karazhan secound boss

### ISSUE THREAD

**Issue by Daynar2018** [SunwellWoW/Sunwell-TBC-Bugtracker#341]
Decription: 

kz secound boss
How it works: 
all mobs from boss encouter are DOUBLE spawned

How it should work: 

should be one of kind these mobs spawned there
Source (you should point out proofs of your report, please give us some source): 
http://prntscr.com/ksf2tf

**Comment by notsofamous** [comment]
Already reported here: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/178

Please check previous reports using the search tool before making bug reports.

**Comment by Riztazz** [comment]
duplicate
