### ISSUE TITLE
syndicate thief who sleeps transports

### ISSUE THREAD

**Issue by Hjodienew99** [SunwellWoW/Sunwell-TBC-Bugtracker#3413]
Description: 

27.3 63.6 mob who looks like in sleep ( Zzz.. ) transports its locations
How it works: 

mob moves like transportation
How it should work: 

mob should stay where it is and shouldnt attack before getting attack
Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
I was not able to find mentioned npc. Furthermore, I don't see any syndicate thiefs with sleeping aura.
If someone sees him could you please provide a screenshot with his location?

**Comment by Hjodienew99** [comment]
He was in the left side of castles entence ( castle which includes boss
quest)

16 Ara 2018 Paz, saat 02:56 tarihinde Chris <notifications@github.com> şunu
yazdı:
