### ISSUE TITLE
Honor Gain at 70 is so low its unfeasible to buy pieces of pvp gear (Honorkills / BGs)

### ISSUE THREAD

**Issue by imagine999** [SunwellWoW/Sunwell-TBC-Bugtracker#3415]
Description: 
Whats going on with these honor gain values ?
Level 70 Honor kills give like 10-20 honor (first kill of the day on a player)
20honor for a arathi basin win at 70
40honor for a warsong gulch at 70 
Please I want to pvp but if youre gunna have 10-19 and 20-29 honorgain values from BGs at 70 its litteraly impossible to buy the pvp gear (each pieces of gear go for about 8 to 15k honor)
How it works: 
Honor Gain Values are incorrect (these values are from low level brackets)
How it should work: 
All honor gain and honor kills values at 70 need to be massively increased
A battleground win at 70 should be giving around 1-2k honor
First Honor Kills of the day on a player at 70 should be giving 100-300honor
Source (you should point out proofs of your report, please give us some source): 
https://cdn.discordapp.com/attachments/518126114795683842/522507587040575488/unknown.png

**Comment by notsofamous** [comment]
![Image](https://i.gyazo.com/e02ec16b95d2ca58881291b2e2494771.png)

Honor from BGs is accurate, the TBC honor grind is awful.
