### ISSUE TITLE
Thorium Setting consuming 3 Thorium bar instead of 1

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#3416]
https://www.wowhead.com/item=21752/thorium-setting

http://wowwiki.wikia.com/wiki/Thorium_Setting

Should consume 1 TBar. Actually consuming 3.

**Comment by MrTide** [comment]
Content difference .. its intended

**Comment by Wojtyas** [comment]
Will be changed back to 1x.
