### ISSUE TITLE
OHF heroic bosses sometimes give normal loot

### ISSUE THREAD

**Issue by Proseccobabe** [SunwellWoW/Sunwell-TBC-Bugtracker#3418]
Description: 
The loot in OHF heroic is mixed. Sometimes the bosses give loot from normal dungeon sometimes heroic.

How it works: 
Wrong loot

How it should work: 
Only heroic loot

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/5DPbQnx

**Comment by MarcusStu** [comment]
I can confirm this.
