### ISSUE TITLE
Seed of Corruption is not fixed. 

### ISSUE THREAD

**Issue by MrFunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#3419]
Description: 
Seed of corruption is still not exploding correctly. Its actually much worse than before the fix as it seems to now not explode after the damage threshold either.

How it works: 
Target with Seed of Corruption takes over 1044 total damage or Dies, but doesn't explode 100% of the time

How it should work: 
Target with Seed of Corruption takes over 1044 total damage or dies, explodes 100% of the time.

Source (you should point out proofs of your report, please give us some source): 
The spell tooltip and https://tbc-twinhead.twinstar.cz/?spell=27243

**Comment by Shards2k3** [comment]
Can confirm. Still not working.

**Comment by jowns** [comment]
Still buged ye. I can can out 4 seeds on different mobs, aoe them with a full rain of fire (2k dmg / target) & no seed exploding from it.
 Also doesnt work when multiple warlocks use it, they dont stack with others  (they should , new ones just put up a new seed debuff. So having 3 warlocks spam seed making no one of them ever exploding just renewing the same debuff over and over. It should only work like that when there is only one warlock. Debuff should stack with other warlocks

**Comment by ZaoQ** [comment]
Any progress on this one?

**Comment by akrom23** [comment]
Remember about this:
https://github.com/ccshiro/cc-buglist/issues/1920
This is the case?

**Comment by ZaoQ** [comment]
Not rly. sometimes seed doesnt proc at all no matter how much dmg was dealt, soc from 2 warlocks overwrites so only one is active, also sometimes when a target dies with seed on him, it doesnt proc.
