### ISSUE TITLE
Drums of Battle have a 1s hard cast and radius too small

### ISSUE THREAD

**Issue by whitestar87** [SunwellWoW/Sunwell-TBC-Bugtracker#3423]
Description: 
Drums of Battle have a 1sec cast bar.  The radius also appears to be quite small, less than 20 yards?

How it works: 
When activated, drums of battle have a 1 second cast bar and will not apply to party members who are not right on top of you.

How it should work: 
Drums of battle should be instant cast (though on the GCD), and should range 40 yards.

Source (you should point out proofs of your report, please give us some source): 
https://db.excalibur.ws/?spell=35476

Cast time Instant, 1.5sec GCD

**Comment by Wojtyas** [comment]
It's patch changes. It has 1s cast and 8y range.

**Comment by baade123** [comment]
reeee that sucks XD
