### ISSUE TITLE
jewelcrafting

### ISSUE THREAD

**Issue by itsuki993** [SunwellWoW/Sunwell-TBC-Bugtracker#3429]
Description: 

How it works: 
To create a thorium settings 3 thorium bars are used
How it should work: 
must use one thorium bar
https://www.wowhead.com/item=21752/thorium-setting

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_121518_131841](https://user-images.githubusercontent.com/45893064/50040796-04e38b80-006c-11e9-868c-08b2814f41b2.jpg)

**Comment by Wojtyas** [comment]
It's a patch change but will be reverted soon ;)
