### ISSUE TITLE
[Hunter][pet][spell] Warp

### ISSUE THREAD

**Issue by koioko2341** [SunwellWoW/Sunwell-TBC-Bugtracker#3430]
Description: 
The Pet spell does not do, what the discription says it does.

How it works: 
The the pet uses the ability, a blink effect occurs, and nothing else.

How it should work: 
The the pet uses the ability, a blink effect occurs, and at the same time the pet should teleport behind the enemy while having a buff that gives the pet 50% chance to avoid the next melee attack for 4 sec

Source (you should point out proofs of your report, please give us some source):

**Comment by schaumichan** [comment]
Hello 
I can also confirm that not everything works correctly with the spell "warp", I've tested a few things.

Spellid "Warp"   http://db.darkwizard.pl/?spell=35346

test conditions
- 30 yards to the mob
- the pet attacks first with the ability "warp"
- pet use his ability "warp" infight again

test 1: attack on neutral mobs (yellow)

- initial warp works right! The Warp Stalker teleports behind the mob and gets his aura.
- second one doesnt work correctly, the Warp Stalker doesnt teleport but he gets his aura.

test 2 attack on "aggressive" mob (red)

- initial warp doesnt work, the WarpStalker just ran to the mob and gets his aura.
- same like before doesnt work, he just get his aura

Tried several different extra things like freezing trap, same problem the pet runs to the mob no "warp"

For me, it looks like that "warp" is not running properly when the mob is infight. In case of the aggressive mobs it seems for me the mob enters the fight "earlier" then a neutral mob.
