### ISSUE TITLE
Nightbane coins

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#3432]
I've wrote to Piootrek, Graal, Cule about my nightbane coins reward for bug reports. Done it on disc, forum. My messages are being ignored or idk. Well i Just wanted some coins To afford exp boost, since i dont have a bank account to buy them. 
Please dont ignore me. Thanks. Account name is simply "mikov"

**Comment by akrom23** [comment]
Bugtracker is not valid place to write it.

**Comment by Mikov1605** [comment]
Well im being ignored everywhere else
