### ISSUE TITLE
Priest, Vampiric Touch

### ISSUE THREAD

**Issue by groveunder** [SunwellWoW/Sunwell-TBC-Bugtracker#3433]
Description: 
While in another group with a Shadow priest using VT, it does not stack, and gets over ridden by who ever casts it on the mob last.

How it works: 
While grouped with 2 shadow priests, only one Vampiric touch is being able to be cast on the mob.

How it should work: 
Vampiric touch should stack with other shadow priests.

Source (you should point out proofs of your report, please give us some source): 
played retail shadow priest.

**Comment by groveunder** [comment]
BUMP

**Comment by ellonija** [comment]
Vampiric Embrace isn't stacking either.

Exactly the same info/description as the Vampiric Touch bug.

**Comment by Pizzle93** [comment]
Can confirm still happening

**Comment by Hnidka** [comment]
Comfirming  still fucked up

**Comment by glaivesbae** [comment]
bump for fix plsssssssssssssssssssssssssssssssssssssssss

**Comment by groveunder** [comment]
Please fix asap. This is the only Class problem I can see in the issues, that full effects a class' dps rotation. Nothing else is like this. 
It makes it so un-enjoyable  to play while grouped with another shadow priest. PLEASE.

**Comment by glaivesbae** [comment]
please fixxxxxxxxxx <3
