### ISSUE TITLE
[Dungeon] [Shadow Labyrinth] rogue missing in tunnel to first boss

### ISSUE THREAD

**Issue by dadkinse** [SunwellWoW/Sunwell-TBC-Bugtracker#3435]
Description: 

How it works: 
There is no rogue in the tunnel to the first boss

How it should work: 
There should be a rogue

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, I've checked numerous videos from this dungeon and i haven't spotted "rogue" in the tunnel to the first boss. It seems that he's not supposed to be there. Here's an example: https://youtu.be/9xvDNa5jpzo?t=133 . I'll close this issue for now, but if someone can provide evidence that there should be rogue we can re-open and add it.
