### ISSUE TITLE
[Quest] To Catch A Thistlehead (TK chain quest)

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#3441]
Description: 
No event

How it works: 

How it should work: 
In the following video
Conversation in the second link

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=4lIdkwZ0wAk
https://wow.gamepedia.com/To_Catch_A_Thistlehead

**Comment by Kuikku** [comment]
stand on the end of the bridge and use q item

**Comment by Dootz** [comment]
yup, can confirm it works.

**Comment by ZaoQ** [comment]
i did use the item on the end of the bridge and saw others do that and that elite guardian is always friendly and no conversation happens so i dont know what u mean by saying it works.
