### ISSUE TITLE
Tempest Keep  2nd boss

### ISSUE THREAD

**Issue by Daynar2018** [SunwellWoW/Sunwell-TBC-Bugtracker#345]
Decription: 

boss
How it works: 
alar dont dont drop items

How it should work: 
http://prntscr.com/ksfxqf

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/46087305-56395880-c1aa-11e8-9310-eae07cb0c143.png)
When you kill something make sure that you don't use .die command - you won't see any loot after that.
