### ISSUE TITLE
Fix Seer Udalo.

### ISSUE THREAD

**Issue by mjk6994** [SunwellWoW/Sunwell-TBC-Bugtracker#3455]
Description: Should be in normal but isn't.

How it works: He should be in normal, but isn't because some idiot named Woj cried that he shouldn't be and you guys listened without confirming.

How it should work:  Don't listen to Woj. 

Source (you should point out proofs of your report, please give us some source): Don't need any since you guys blindly listen.

**Comment by 0vertime** [comment]
He should be in normal indeed, that's how I got it on retail. Even Atlas/AtlasLoot/AtlasQuest would mention if it was Heroic only.

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3318
