### ISSUE TITLE
Loch Crocolisk 

### ISSUE THREAD

**Issue by Yumajii** [SunwellWoW/Sunwell-TBC-Bugtracker#3458]
Description: 
They have the ability thrash which grants them 2 extra attacks. but they seems to sometimes spam it and do about 9 attacks in one second

How it works: 

How it should work: 
They should use the ability sometimes and get 2 extra attacks but should not be spammable 
![wowscrnshot_121518_210342](https://user-images.githubusercontent.com/45419499/50047010-b7880e00-00ad-11e9-852e-fe713c98e7f4.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2408
