### ISSUE TITLE
Shade of Aran

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#3459]
- [ ] Doesnt center himself before arcane explosion

- [ ] Slow sometimes isnt applied before arcane explosion

- [ ] doesn't cast his root ability

- [ ] ONE PLAYER RANDOMLY EXPLODES AFTER FLAME WREATH DURATION ENDS

- [ ] casts dragons breath during flame wreath

- [ ] blizzard ends after 1/3 of the duration

- [ ] he doesn't reset if you pull him out of the room

**Comment by jowns** [comment]
https://gyazo.com/7d1bcdfbd3e77167477cbe2ba3c8e106

the blizzard "mob" can aggro players. Its hidden but can aggro the healers and daze them the entire fight & giving spell pushbacks and that sort of things.

**Comment by Wojtyas** [comment]
Moved to massive topic.
