### ISSUE TITLE
Blessing of Light and Blessing of Sanctuary overwrite each other

### ISSUE THREAD

**Issue by Etainz** [SunwellWoW/Sunwell-TBC-Bugtracker#3464]
Description: Blessing of Light and Blessing of Sanctuary overwrite each other

How it works: Paladin A uses Blessing of Sanctuary on himself. Paladin B uses Blessing of Light on Paladin A. Blessing of Light removes Blessing of Sanctuary on Paladin A.

How it should work: Blessing of Light should only overwrite the casting paladin's blessing if there is one. Each paladin should be able to place a single blessing on each character. Paladin A in the example should end up with both Blessing of Light and Sanctuary, just like with other Blessings.

Source (you should point out proofs of your report, please give us some source): Every other blessing pairing.

**Comment by Testimonia** [comment]
confirmed

**Comment by NeonicSupersonic** [comment]
Fix it kinda big deal

**Comment by fakelort** [comment]
This should be really easy to fix and pretty game breaking...

**Comment by Devrak** [comment]
It is still bugged. ( bump )

**Comment by lordazurescens** [comment]
Still bugged and rewriting each other

**Comment by Devrak** [comment]
It is still bugged. ( bump )

**Comment by Devrak** [comment]
It is still bugged. ( bump )

**Comment by Devrak** [comment]
Thanks alot :+1:

**Comment by akrom23** [comment]
Next time, just tag me on critical issues.
