### ISSUE TITLE
 [Burning Legion Missive] [Ominous Letter] Blood elves cant accept quest

### ISSUE THREAD

**Issue by bindles1** [SunwellWoW/Sunwell-TBC-Bugtracker#3465]
Description: 
 [Burning Legion Missive] & [Ominous Letter]
2 quests in outland (hellfire) that is opened by letter to accept quest.

Says : That quest is not avaiable to your race.

How it works: 
That quest is not avaiable to your race.

How it should work: 
Should be able to accept the quest like any other player

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
can't confirm. Seems to be working fine. Message you provided is displayed only if you try to accept Alliance version of the quest. Which shouldn't happen. Did you get your Burning Legion Missive / Ominous Letter from Warbringer Arix'Amal & Vazruden?

**Comment by nokko404** [comment]
![image](https://user-images.githubusercontent.com/45911127/50051084-cac9c680-010b-11e9-957b-429be33c3c26.png)

I can confirm that horde can loot ally version of the Burning Legion Missive.
