### ISSUE TITLE
[Quest] [Item] Withered Basidium

### ISSUE THREAD

**Issue by zefurr** [SunwellWoW/Sunwell-TBC-Bugtracker#3467]
Description: 
Withered Basidium (which drops off of Withered Giants in Zangarmarsh, possibly other mobs) is dropping the Horde version for alliance players

How it works: 
 Withered Giants in Zangarmarsh (and possibly other mobs) drop the item "Withered Basidium". This item begins a quest. There is a Horde version and Alliance version of the quest. Currently the Horde version is dropping for alliance players, it offers a quest that cannot be accepted.

How it should work: 
The Alliance version of the item should drop for Alliance players, and enable them to accept the associated quest.

Source (you should point out proofs of your report, please give us some source): 
Horde version: http://db.hellfire-tbc.com/?quest=9828
Alliance version: http://db.hellfire-tbc.com/?quest=9827

**Comment by Azathothh** [comment]
I've got an alliance version while being in alliance without any problems - could you give more detail? Like your class/race, what kind of error you're getting when trying to use that item, etc.
![obraz](https://user-images.githubusercontent.com/37483678/50051473-411df700-0113-11e9-85c1-d14a1a2488bb.png)

**Comment by zefurr** [comment]
Dwarf Hunter

It offered me the quest (Horde version), when I press accept I get a message in the main chat window, text color yellow. Something to the effect of:

"Your race is not eligible for this quest."
or
"This quest is not available to your race."

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/50058930-07cfa080-0180-11e9-90b5-e89b155861a5.png)
alliance q item on dwarf hunter as well (40th kill)

**Comment by zefurr** [comment]
I will try and find the time to reproduce and make a video. When I was there (on a separate quest to kill Withered giants) I had the (horde) quest item dropping on over half the kills. Hopefully my luck stands.

You may close the issue if you desire. If you do, I will open a new issue should I manage to reproduce it.

**Comment by zefurr** [comment]
I went back and the correct Withered Basidium dropped for me.

Can't reproduce so I'll close the issue. Perhaps worth looking into the combination of the Withered Giant killing quest and the WIthered Basidium drops? I had many quests at the time though, so hard to say.
