### ISSUE TITLE
Most of the NPCs walk like a inch lower into the ground than they are supposed to

### ISSUE THREAD

**Issue by leahnie956** [SunwellWoW/Sunwell-TBC-Bugtracker#347]
Decription: 
When NPCs walk their feet go a little bit into the ground

How it works: 
Feet should be on top of the ground

How it should work: 
Feet should be on top of the ground

Source (you should point out proofs of your report, please give us some source): 
![ertnertnertn](https://user-images.githubusercontent.com/25886407/45270060-047c9880-b45e-11e8-8d43-6b72ac82f6e3.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented.
