### ISSUE TITLE
[Quest] Now that we're friends

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#3471]
Description: Incorrect requirements

How it works: https://imgur.com/a/V3HAYAZ

How it should work: Should need 6 enchantresses

Source (you should point out proofs of your report, please give us some source):

**Comment by LezChap** [comment]
The quest text is wrong.  It was 12 of each in 2.0, and went down to 6 Enchantress's in 2.4.  (Ref: https://www.wowhead.com/quest=9727/now-that-were-still-friends#comments:id=259499)

http://db.darkwizard.pl/?quest=9727 <--the quest in your database
