### ISSUE TITLE
Charge should work on targets that are behind non-LOS objects (i.e trees)

### ISSUE THREAD

**Issue by trevorjk** [SunwellWoW/Sunwell-TBC-Bugtracker#3472]
Description: You are supposed to be able to charge targets that are hiding behind non-LOS objects like trees or stumps in WSG.  If a caster is behind a tree for example, they can cast on a warrior.  The warrior should be able to cast charge on the caster thats hiding behind the tree.  Charge is supposed to path you around it.  Currently this does not work as you get an LoS error on the charge/intercept.

An easy way to ttest this is to find a mob at a tree and stand on the otherside of the tree.  It wont let you charge but you can shoot it with your ranged.

How it works:   Cant use charge around trees.

How it should work:  Charge should path around.

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=djttwIWb-2s
@ 3:10 stump
@ 3:40 for the broken cart

**Comment by Sippiey** [comment]
Fix please... being super abused in BGs and arenas by hunters etc. They shoot you but you cannot get to them.
