### ISSUE TITLE
Priest Vampiric Embrace

### ISSUE THREAD

**Issue by groveunder** [SunwellWoW/Sunwell-TBC-Bugtracker#3474]
Description: 
Vampiric Embrace gets over ridden if another shadow priest casts it.

How it works: 
2 shadow priests in a group. Vampiric Embrace gets taken off, and the other persons VE applies to you.

How it should work: 
It should only work for you if you APPLY it. You should not get the Health regen / Threat that is associated with VE from another priest.......

Source (you should point out proofs of your report, please give us some source): 
WoW

**Comment by groveunder** [comment]
Edit. you don't get the affects of the other priests VE. But it still gets overridden.

**Comment by akrom23** [comment]
Ii affect the whole party, so what's the difference which one is active?

**Comment by akrom23** [comment]
Works fine.
