### ISSUE TITLE
Divination: Gorefiend's Truncheon

### ISSUE THREAD

**Issue by mjk6994** [SunwellWoW/Sunwell-TBC-Bugtracker#3479]
Description: Noot F*ng dropping.

How it works: Supposed to be 100% drop.

How it should work: x Fking d?

Source (you should point out proofs of your report, please give us some source):  https://media.discordapp.net/attachments/432981313117618217/523730628181622784/unknown.png?width=1131&height=637

Literally been killing them for 1/2 hour. 13 kills later. Still no drop. How many damn bugs can there be. SUNWELL CORE AMIRITE

**Comment by mjk6994** [comment]
14th no drop. B L I Z Z L I K E

**Comment by Sunwellscriptinglul** [comment]
Still broken drop rate
