### ISSUE TITLE
Threat from Vampiric touch mana regen.

### ISSUE THREAD

**Issue by groveunder** [SunwellWoW/Sunwell-TBC-Bugtracker#3481]
Description: 

How it works: 
While engaged in a pack of mobs with VT, on , and a random patrolling mob walks into the group, I have had MANA regen from VT causing threat of mob to attack me, (while healer all the meanwhile is casting healing spells which should take agro above MANA REGEN). 

How it should work: 
Either, it should not cause any threat. Or the threat is bare minimal. As a Shadow priest threat is always an issue, so even if its the tinniest amount, it still adds up, and should be RECHECKED. 

Source (you should point out proofs of your report, please give us some source):

**Comment by glaivesbae** [comment]
can confirm, happened multiple times for myself
