### ISSUE TITLE
[warlock] Drain Life and Siphon Life overwrite

### ISSUE THREAD

**Issue by SasquatchFiesta** [SunwellWoW/Sunwell-TBC-Bugtracker#3482]
Description: 
2 warlocks in the same group, Drain Life and Siphon Life can't be on the same target from both warlocks.

How it works: 
If one warlock is Draining Life on a NPC, the other using it on that same NPC stops the other one draining life. Casting Siphon Life on a NPC that has Siphon Life from another warlock removes the other warlocks Siphon Life

How it should work: 
Multiple warlocks should be able to simultaneously drain life on the same NPC.
Multiple Siphon Lifes from multiple warlocks should be able to coexist on the same NPC

Source (you should point out proofs of your report, please give us some source): 
no sources, but noticed it in Shattered Halls on trash, two warlocks in group.

**Comment by jockeboschko** [comment]
also seed of corruption
