### ISSUE TITLE
[Dungeon] Murmur HC loot table

### ISSUE THREAD

**Issue by Stondis** [SunwellWoW/Sunwell-TBC-Bugtracker#3483]
Description:  Murmur drops wrong items on HC difficulty. Done it twice and both times he has dropped an epic belt from Harbringer Skyriss HC. Also doesnt drop normal loot on heroic.

How it works:  drops wrong items

How it should work:  he should drop his own loot

Source (you should point out proofs of your report, please give us some source): 

![kuva](https://user-images.githubusercontent.com/44775624/50051856-bf35ca00-0122-11e9-96c9-725880a41358.png)

**Comment by xethra89** [comment]
The belt used to drop from Murmur prior to patch 2.1. So depends on how the Sunwell team views loot as (2.0 or 2.4.3). 

https://wow.gamepedia.com/Belt_of_Depravity

The Burning Crusade Patch 2.1.0 (2007-05-22): No longer drops from Murmur in the Shadow Labyrinth.
