### ISSUE TITLE
Nightfin Soup Buff

### ISSUE THREAD

**Issue by AshhSunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#3484]
Description:  Nightfin soup gives a unique 8mp5 buff that stacks with food & raid buffs.

How it works: When using Nightfin Soup if you have a food buff it removes said buff & vice versa

How it should work: They should be individual buffs that do not overwrite one another

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=13931/nightfin-soup#comments

Read the comment from patch 2.2

**Comment by doomnyx** [comment]
https://www.wowhead.com/item=13931/nightfin-soup#comments:id=161753:reply=17067

Report seems invalid to me.

**Comment by AshhSunwell** [comment]
They are not the same buff, so they should not overwrite each other. They did not change this until 2.2.3 & we are emulating patch 2.0 correct?
