### ISSUE TITLE
[Quest - Against the Legion]

### ISSUE THREAD

**Issue by Gryma** [SunwellWoW/Sunwell-TBC-Bugtracker#3486]
Description: Speaking to Altruis to get 3 quests

How it works: When we completed the quest "Altruis" (in Aldor), we get only 2 quests, instead of 3. So, we cant finish the chain quest.

How it should work: Need pre-q "Altruis" to get the 3 quests

Source (you should point out proofs of your report, please give us some source): 
Pre-quest Aldor : https://www.wowhead.com/quest=10640/altruis
Quest "Against the Legion" : https://www.wowhead.com/quest=10641/against-the-legion

**Comment by Kuikku** [comment]
Can Confirm. Just tried to do this Qline and my progress stopped here. Cant get more than 2 quests from Altruis the Sufferer.

**Comment by Gryma** [comment]
Little edit : the third quest just appear after finish the chain quest about Forge Camp (final quest here : https://www.wowhead.com/quest=10011/forge-camp-annihilated).
