### ISSUE TITLE
Evil Draws Near [ QUEST ] 

### ISSUE THREAD

**Issue by Doomwalkerr** [SunwellWoW/Sunwell-TBC-Bugtracker#3487]
Description: 
Completed the quest, can't turn in

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_121618_130625](https://user-images.githubusercontent.com/35903205/50053330-a71a7680-0133-11e9-9588-dfe616752e68.jpg)
![wowscrnshot_121618_130632](https://user-images.githubusercontent.com/35903205/50053331-abdf2a80-0133-11e9-94cb-564e88784f03.jpg)

**Comment by Azathothh** [comment]
#2757
