### ISSUE TITLE
Chest Bug in BC instances

### ISSUE THREAD

**Issue by Bawzillex** [SunwellWoW/Sunwell-TBC-Bugtracker#3491]
Description:  Fel Iron and Adamantite chests in BC instances have a really buggy loot table. Sometimes there are 6 greens. sometimes the chest is emty or only holds 1 pot.

How it works:  sometimes empty, sometimes only 1 scroll or pot sometimes 10+ items in it

How it should work: On Retail they normally contain a small amount of money ( 1-3g) a guaranteed green and higher chance for blue boes and gems  ( also the blue ones) and some random pots and scrolls for that level.

Source (you should point out proofs of your report, please give us some source): 
while rep farming u opened minimum 40 chests and the difference is like night and day. just go there and open some u will find out fast

**Comment by RPAncap** [comment]
Kinda related : Currently, there are no chests in several HC dungeons. (For example shadow labyrinth) - they are there on normal.
