### ISSUE TITLE
Dungeons resetting after server restarts

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#3492]
Description: 

How it works: 

How it should work: 
You should just log on the same position in the dungeon you logged out and the dungeon should be in the state you left it, and not that you log on the start of the dungeon with mob reset.

Plus leader always gets kicked from the party. (normal and heroic diff)

This regards normal difficulty dungeons.

Source (you should point out proofs of your report, please give us some source):

**Comment by ZaoQ** [comment]
Didnt try the reset of normal dungeons part of the report but leader still gets kicked from the party if he relogs/logouts both in the dungeon or in the open world (before entrance ie.)

**Comment by akrom23** [comment]
@ZaoQ That's another bug reported here: #3536
