### ISSUE TITLE
Kyrai, Poison Regents vendor in Darnassus not selling Flash Powder

### ISSUE THREAD

**Issue by Letizoria** [SunwellWoW/Sunwell-TBC-Bugtracker#3496]
How it works: 
Not selling Flash Powder

How it should work: 
It should sell Flash Powder

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?npc=3561

**Comment by Dootz** [comment]
![obraz](https://user-images.githubusercontent.com/25490436/50059880-e5904f80-018c-11e9-8e8e-862f02c0bba9.png)

Works fine on live. Doesn't seem to disappear. Please add a comment if I missed something.
