### ISSUE TITLE
WARLOCK: Soulstone and Healthstone created are lost if bags are full

### ISSUE THREAD

**Issue by Gelori** [SunwellWoW/Sunwell-TBC-Bugtracker#3499]
Description: 
When creating Soulstone and Healthstone and if bags are full, the cast goes to the end, consuming mana and shard! 

How it works: 
When creating Soulstone and Healthstone and if bags are full, the cast goes to the end, consuming mana and soul shard! 

How it should work: 
If bags are Full, the error message "Can not carry anymore" will pop and cast shouldn't start!

Somehow must be related to 
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2171

**Comment by ZaoQ** [comment]
This happened to me while i was making Netherweave bag, mats consumed but no bag.

**Comment by Gelori** [comment]
@ZaoQ Check through bug tracker if their is already one reported bug for crafting, if not please report it with complete description and link to this issue ( just copy past the url to bug description). I think this is related!
