### ISSUE TITLE
[Paladin][Talent] Sanctified Seals doesn't increase Melee Crit%

### ISSUE THREAD

**Issue by F4play** [SunwellWoW/Sunwell-TBC-Bugtracker#35]
Decription: Sanctified Seals doesn't increase Melee Crit% (tier 7 ret talent)

How it works: Sanctified Seals doesn't increase Melee Crit%, only increases spell crit%

How it should work: Should increase both melee crit & spell crit percent (1% per talent point)

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
It's working, make sure that you're wearing weapon and got max weapon skill.
