### ISSUE TITLE
Random Combat bug that makes you randomly die.

### ISSUE THREAD

**Issue by syphex97** [SunwellWoW/Sunwell-TBC-Bugtracker#3502]
_Description: 
Apprently for some reason whenever i have 1-3k hp left i randomly die from nothing, there is nothing in the damage log other than the npc's hitting me and it doesnt even make up for my hp, it has already happened 3 times in Shadowmoon Valley.

I decided to record it and you can workout that its not supposed to randomly kill you like it does and whats wrong.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/EKp48yKVZnI

Pic of my combat log:
https://imgur.com/a/HKQPLsa_

**--Edit--
Actually i just realized last stand was activated and then went of cooldown at the exact timing. 
Pretty sure it isnt supposed to kill you off tho just like that when you run out of hp**

**Comment by akrom23** [comment]
https://wow.gamepedia.com/Last_Stand

> At the end of the duration, these hit points are removed

> Make sure to let the healers know you used it as a warning to keep your health up because the effect will end and the extra health will be gone in 15 seconds
