### ISSUE TITLE
[Spell][Spirit of Redemption] You can move in Spirit Form

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#3503]
Description: 
You are able to move while in priest Spirit Form

How it works: 
You are able to move while in priest Spirit Form
https://gyazo.com/91484ddd1cb5fd96744cc755a61bad12
How it should work: 
Priest should be locked in place while in Spirit Form

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Cannot reproduce.
@badmannerkid What about buffs/debuffs on you? What about your health? Happened only on this encounter?

**Comment by akrom23** [comment]
No response.
