### ISSUE TITLE
[Quest] Teleport This!

### ISSUE THREAD

**Issue by stewzor** [SunwellWoW/Sunwell-TBC-Bugtracker#3504]
**Description:** 
The Cyber-rage Forgelord's Detonate Teleporter ability to destroy the portal does not always work. Sometimes the Mind control will randomly break even within range. 

I managed to get the Western portal working after 3 tries but the Eastern and Central won't complete.

**How it works:** 
Use an interference rod on a Mo'arg at Forge Base: Gehenna to destroy a portal with their Detonate Teleporter ability.

**How it should work:** 
Using the Detonate Teleporter should within the Teleporters should give credit for the quest.

**Source (you should point out proofs of your report, please give us some source):** 

https://i.imgur.com/RdcXRPN.jpg (Screenshot taken at eastern portal.)

**Comment by Twistwarp** [comment]
I have gotten the quest to work if you jump and then use the ability of the The Cyber-rage Forgelord's Detonate Teleporter ability in the middle of the portal.
