### ISSUE TITLE
Sitting/standing visual

### ISSUE THREAD

**Issue by Azathothh** [SunwellWoW/Sunwell-TBC-Bugtracker#351]
Decription:  If player will logout while character is sitting and then login before his char is removed from world he will be visually sitting for other players whenever he doesn't move

How it works:  https://www.youtube.com/watch?v=aK8xVG9kXkU

How it should work: Well...char shouldn't appear as sitting to others when it's not sitting

**Comment by Azathothh** [comment]
May be related to https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/323

**Comment by Riztazz** [comment]
related https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/358

**Comment by akrom23** [comment]
#358
