### ISSUE TITLE
Digging up the Past Respawn timer for the Charred Bone Fragment - Broken

### ISSUE THREAD

**Issue by waterloorick** [SunwellWoW/Sunwell-TBC-Bugtracker#3512]
Description: Digging up the Past Respawn timer for the Charred Bone Fragment seen to be broken. The bone is there, but it cannot interact with it.

How it works: 

How it should work: It should be looted, despawn, then respawn within seconds.

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/quest=9680/digging-up-the-past#comments

**Comment by notsofamous** [comment]
Were you in a raid group when you tried to do it? You cannot loot quest items in a raid.

**Comment by waterloorick** [comment]
I was not.

**Comment by FrauHolle86** [comment]
![444](https://user-images.githubusercontent.com/45068171/50060792-a7992880-0198-11e9-9968-47c91b801ef0.png)
