### ISSUE TITLE
Blood fury ( orc racial - caster): generates agro when used

### ISSUE THREAD

**Issue by Gelori** [SunwellWoW/Sunwell-TBC-Bugtracker#3513]
Description: 
Blood fury (caster): generates agro when used

How it works: 
For example my demon is tanking 4 NPCs, one is focused by him, others were only pulled by pet, haven't suffered any damage from pet. If i use Blood Fury, all the pack ( 3 mobs) will run to me!

How it should work: 
![default](https://user-images.githubusercontent.com/36414797/50059735-97cf1380-019b-11e9-93d6-129eb565305d.png)

Blood fury - increased the caster spellpower my X for 15 seconds when used, reduce healing by 50%. 
No additional agro when used! Priest are not reagroing mobs when buffing staming right?

Source (you should point out proofs of your report, please give us some source): 
https://db.excalibur.ws/?spell=33702

**Comment by zefurr** [comment]
I've noticed similar behavior on other abilities.

Off the top of my head I believe Bestial Wrath and Rapid Fire do this.
