### ISSUE TITLE
Karazhan, partial bug report 

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#3518]
Description: 
- [ ] Arcane Anomaly - They should just drop to 1% hp and activates their mana shield, it should not be possible to IK them. 
_(By Corrodias (985 – 1·11) on 2007/07/06 (Patch 2.1.2) We tried blasting one of these guys with a high-damage spell (they take damage from the first attack you hit them with, before they can put up their mana shield). However, it only took him down to 1%, so we strongly suspect that they can't be killed by the first attack.)_

- [ ] Mana Feeder - These mobs are immune to most (but not all) magic effects in the game, including wands.
The Mana Feeders do not follow any discernable aggro rules and change their targets at random.
Both above mentioned issues dont work atm. You can wand them and they are aggroed by tank.

- [ ] Arcane Protector - They should be immune to snares and stuns. They are stunnable atm.

- [ ] Phantom Guest - They should give 3 rep. They now give 12(15).

- [ ] Curator - He looks like post-nerf boss. 
He is missing his prenerf ability Damage Shield: The curator has 90% Damage Shield always on except for Weaken phase and Enrage phase. Now he takes normal damage outside evocation phase. 

- [ ] Next, during evocation phase, the Curator does no damage and takes 250% damage from all attacks. It looks like it is post-nerf value 300% now. 

- [ ] Next, flares are doing dmg only to 2 targets, it should do dmg to all around them. 

- [ ] Next, it seems like he enters his Enrage phase on 15% he should enter it at 10%.

- [ ] Shade of Aran - missing this: Blizzard 1700/second, large AoE that moves slowly clockwise 360 degrees around the edge of his arena. The blizzard has a large area of effect, and it covers one side of the room. You will be hit by the Blizzard if you are meleeing him and on the side it's traveling on.

- [ ] At 40% HP, Nielas Aran summons 4 elite Water Elementals. They have **tons of HP**(maybe even more than Aran himself) but will despawn after 90 seconds. ... They have only 20k now (post-nerf value)

- [ ] Maiden of Virtue - Can be kicked, mind-numbing poison works on her delaying cast (i imagine curse of tongues would also work) This should not be possible.

- [ ] A bug aside ... [Rumsey Rum Black Label] overwrites ''Food buff''which its not supposed to, They stack together

**Comment by Wojtyas** [comment]
Moved to massive topic.

**Comment by ZaoQ** [comment]
Where is that?
