### ISSUE TITLE
Being dead issues

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#352]
### **TO DO:**

- [x] 1. When our Reincarnation isn't on CD shaman should be able to resurrect himself but after pushing button "Resurrection" there is info "Your target is dead" and whole Release Spirit panel disappears leaving player dead on ground.
1)
![image](https://user-images.githubusercontent.com/22802214/45301261-e15ef100-b510-11e8-8519-92097c145a0c.png)
2)
![image](https://user-images.githubusercontent.com/22802214/45301285-ec198600-b510-11e8-8d31-b1d565cf6bc7.png)
- [x] 2. When player is dead and push Release Spirit he's being teleported to nearby Spirit Healer. Teleportation seems to work (checked only in few places) but we can't talk with Spirit Healers (6491) at all, while we should be able to revive also here. After res via SH player should get Resurrection Sickness debuff (15007).
- [x] 3. After character being teleported to Spirit Healer and is literally dead it should have Ghost debuff (8326) till he grabs his body.
- [ ] 4. After player grabs his body once again after being dead, it should gain Honorless Target buff (2479).
- [x] 5. When "ghost" player is in 35 yards range to his body he should be able to resurrect himselft by panel. There is no panel right now.
- [x] 6. When player is "ghost" there should be arrow on minimap pointing where ur body is.

**Comment by akrom23** [comment]
@Kokaina ``4. After player grabs his body once again after being dead, it should gain Honorless Target buff (2479).``
Source?

**Comment by notsofamous** [comment]
- [ ] When you die inside an instance and corpse run, you can't run on water as a ghost (you should be able to). Example: dying in SSC and releasing, you won't be able to run on the water back to the instance.

**Comment by akrom23** [comment]
@notsofamous Class and race?

**Comment by Kokaina** [comment]
- [ ] Dead person should be able to walk on water.
