### ISSUE TITLE
[Warlock][Spell] Seed of Corruption Overwriting other Warlock's Seeds

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#3520]
Description: 
When two warlocks cast seed of corruption on same mob, Warlock A's SoC is overwritten by Warlock B's seed of corruption

How it works: 
When two warlocks cast seed of corruption on same mob, Warlock A's SoC is overwritten by Warlock B's seed of corruption

How it should work: 
Should be able to have multiple seeds on one mob

Source (you should point out proofs of your report, please give us some source):

**Comment by asphycsia** [comment]
https://www.warcraftmovies.com/movieview.php?id=134387

If you look at this video a 1:51 you can see 2 seeds on one of the little void spawns
