### ISSUE TITLE
Attumen the Huntsman just stands there.

### ISSUE THREAD

**Issue by orlow1ar** [SunwellWoW/Sunwell-TBC-Bugtracker#3521]
Description: 
Watch the damn video.

How it works: 
Attumen just stands still when dismounted. Will not die until returning to horse if killed before then.

How it should work: 
Anything but just standing there. 

Source (you should point out proofs of your report, please give us some source): 
https://clips.twitch.tv/PoorCrepuscularPancakeAMPEnergyCherry

**Comment by Wojtyas** [comment]
Moved to massive topic.
