### ISSUE TITLE
[NPC] [BEM] Wyrm from Beyond is visible when not on the appropriate quest and is targetable/attackable

### ISSUE THREAD

**Issue by blackwife** [SunwellWoW/Sunwell-TBC-Bugtracker#3522]
Description:  Wyrms from Beyond on the Singing Ridge have visible nameplates and can be attacked by players who are not on the relevant quest.

How it works: See description.

How it should work:  These should be invisible and not attackable by players who are not doing the quest.

Source (you should point out proofs of your report, please give us some source): 
Loads of 'em visible on the ridge.

**Comment by babno** [comment]
While now invisible and cannot be clicked on, they are targetable via tab and can be attacked. https://imgur.com/a/i7I5o2q
