### ISSUE TITLE
Slice and Dice

### ISSUE THREAD

**Issue by lettss** [SunwellWoW/Sunwell-TBC-Bugtracker#3523]
Description: it dosnt add like it should (cp = combo point.)(sec = is seconds on the buff you get)

How it works:  1 cp 13sec , 2 cp 17sec, 3 cp 21sec, 4 cp 25sec, 5 cp 30sec.

How it should work: 1 cp 9 sec, 2 cp 12sec, 3 cp 15sec, 4 cp 18sec, 5 cp 21sec.

Source (just try it out and you see it urself... no proof needed here rly...):

**Comment by Silroth** [comment]
Improved Slice and Dice talent at rank 3 increases duration by 45% so check if you put talent points into that because the numbers you mentioned match the 3/3 talent.
