### ISSUE TITLE
[Quest] Taken in the Night

### ISSUE THREAD

**Issue by 0vertime** [SunwellWoW/Sunwell-TBC-Bugtracker#3524]
**How it works:** 
Currently you don't always get credit for freeing the Sha'tar Warriors, sometimes the webs are just empty.
Can take up to hour or more to get this quest completed if there's no contest.

**How it should work:** 
Should be way easier quest to complete.

**Comment by Butterfly1298** [comment]
Yep! Same Problem

**Comment by Iperyth** [comment]
Looks like it happens when you hit it with ranged ability.

**Comment by 0vertime** [comment]
What I noticed that if you oneshot them, they don't work properly.
