### ISSUE TITLE
eviscerate

### ISSUE THREAD

**Issue by lettss** [SunwellWoW/Sunwell-TBC-Bugtracker#3525]
Description: eviscerate wrong dmg output

How it works: it dose to low damage compare to what it should if you read the talent itself

How it should work: fix it just ask some rogues ingame to try all talents becous so far i found 3 wrong with rogue

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Just checked Eviscerate rank 10 on a target with 0 armor and everything is fine.
Please give some more informations + screenshot with combat log
I guess that you didn't consider that armor reduce dmg you're dealing so it may be less than it's showing on tooltip
