### ISSUE TITLE
Rogue, stealth randomly broken even when standing still

### ISSUE THREAD

**Issue by mltzz** [SunwellWoW/Sunwell-TBC-Bugtracker#3530]
Description: 
Rogue, stealth randomly broken, even when standing still and not getting into combat or taking dmg. (seen the issue on gnome rogue) unsure if issue is gnome related or a general bug.

How it works: 
You press stealth and stand still, after xx amount of time, thats random, stealth breaks for no reason.

How it should work: 
You press stealth, and you stay stealthed... forever until combat or you press stealth again.

Source (you should point out proofs of your report, please give us some source): 
Cant give proof, you have to go into the game and replicate the issue with a gnome rogue.

**Comment by sadfx** [comment]
Yeah this happens a lot where I'm just running around and I get destealthed without doing anything

**Comment by akrom23** [comment]
@mltzz  @sadfx Got some screenshot with combatlog?

**Comment by mltzz** [comment]
@akrom23 will get you some screenshot once i get home.

**Comment by mltzz** [comment]
@akrom23 later than expected but here is the combat log

https://imgur.com/a/1puOKx7

**Comment by akrom23** [comment]
@mltzz @sadfx Still happens?
