### ISSUE TITLE
[Warlock]: Drain Life, Siphon Life and Death coil Generating Healing agro

### ISSUE THREAD

**Issue by Gelori** [SunwellWoW/Sunwell-TBC-Bugtracker#3533]
Description: 
Drain Life, Siphon Life and Death Coil Generating Healing agro.

How it works: 
Drain Life is generating 2 timea agro - first when damaging the mob, second time when "Healing" the master

How it should work: 
In Wow mechanic it is considered as Health Drain spells. They should not generate agro with healing. It is a stock core bug. Possible that items, like skullflame shield etc, are affected by same behavior.

Source (you should point out proofs of your report, please give us some source): 
Pull 2 mobs with pet, Drain life the attacked one, Second will instantly run to warlock.

Identic issue, like on archangel and vanilla Elysium:
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2102
https://github.com/elysium-project/classic-bug-tracker/issues/550

**Comment by nkumnberlin** [comment]
Yes. Please fix Its very annoying. But the same problem @GamersDistrict or LightsHope
