### ISSUE TITLE
[Priest][Spell] Vampiric Touch and Vampiric Embrace

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#3535]
Description: 
Shadow priests are overwriting eachothers Vampiric Touch and Vampiric Embrace abilities. Once Spriest A applies VT, if Spriest B applies VT B to the target, VT A will be removed. This happens with others spells like rupture, seed of corruption, etc.

How it works: 
Shadow priests are overwriting eachothers Vampiric Touch and Vampiric Embrace abilities. Once Spriest A applies VT, if Spriest B applies VT B to the target, VT A will be removed. This happens with others spells like rupture, seed of corruption, etc.

How it should work: 
Shoiuld be able to have multiple of the same spell on the target so long as the spells are from different palyers casting them

Source (you should point out proofs of your report, please give us some source):

**Comment by Gelori** [comment]
da fouq... raids are hard

**Comment by Gelori** [comment]
Duplicate with
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3433

**Comment by Hnidka** [comment]
yea duplicate but totally fucked up every dot overwriting the same dot RIP(i playa SP)
