### ISSUE TITLE
Number of issues with party

### ISSUE THREAD

**Issue by MadderThenMad** [SunwellWoW/Sunwell-TBC-Bugtracker#3536]
Description: 

On a server there is a number if widely known issues with a party logic:

1. Relog causes from time to time person to be thrown out of a party (dc also counts). The person is put into a strange state where party members can see person as a member of a party yet the person cannot write in a party chat not does it see any party interface. This also results in being thrown out of instance. Fixing this requires kicking person out of party and re inviting (the bigger problem is if a person was tped out to HS location). Happens in both open world and instances.

2. Players are sometimes being randomly thrown out of a party without leader action (big problem in instances). After speaking with guild mates on a discord this looks like something related with 1 and probably kind of a memory leak. There is a theory saying that leaving party does not always result in leaving a party (server bugs out) - now if you are/were in a kind of bugged party for yourself and you get invited to another party (but the people from old party still see you as a member - so you may be a member of 2 parties technically although unaware about it). Now all the people leave out of your old party you are going to be thrown out of your current party (this is just a theory which came as an explanation of what happend to me from another guild member - he also had something like this occur however both parties were guild ones therefore we had good insight into that. 

How it works: 
N/C

How it should work: 

N/C

Source (you should point out proofs of your report, please give us some source):

**Comment by Gelori** [comment]
Confirming the issue! Their was some really weird stuff with ONE Player being in the group with him self.
Screenshot:
![image](https://user-images.githubusercontent.com/36414797/50081393-69831f80-01ff-11e9-94a4-a90585ff4fbc.png)
It has been bugged out, when i was making him autofollow, basically playing from same IP Address.
Happened after server restart!
Even after clicking on "leave party" and the group was no more showed in Client interface, i couldn't invite him back. Getting "Already in group" error. 
I fixed it by using the lua script **/script LeaveParty()**

**Comment by Gelori** [comment]
#3052
This bug is on high priority, but it describes the issues only partially

**Comment by MarcusStu** [comment]
I can confirm that you need to kick a person because he cannot see his own party when relogging sometimes. Still glitched as of today. Also if you don't kick him and just reinvites him, even if he's visually in your party the member gets duplicated. [imgur picture showing double member](https://i.imgur.com/RIIC9Jw.jpg)
