### ISSUE TITLE
Wtb Link to "Massive Karazhan thread"

### ISSUE THREAD

**Issue by mjk6994** [SunwellWoW/Sunwell-TBC-Bugtracker#3542]
Description:  see above

How it works: see above

How it should work: see above

Source (you should point out proofs of your report, please give us some source): see above

**Comment by Wojtyas** [comment]
It's on Internal BT where only devs have access :( All important stuff is taken there. As we want to fix leftover issues from Kara quite quickly it was moved there to finish it even today.

**Comment by Wojtyas** [comment]
But I can show you how it looks for now!

![image](https://user-images.githubusercontent.com/22802214/50094046-870db480-0212-11e9-8fcc-b4d6121e0da9.png)

**Comment by Wojtyas** [comment]
But I can show you how this is looks like for now!

![image](https://user-images.githubusercontent.com/22802214/50094204-e79cf180-0212-11e9-9210-c53c391fa6b4.png)
