### ISSUE TITLE
Moroes Karazhan

### ISSUE THREAD

**Issue by xeall** [SunwellWoW/Sunwell-TBC-Bugtracker#3543]
Description:  We engage moroes and killed 3 adds and after that moroes goes for a healer and he kills him and hes stuck. I think he wanted to garrote the healer what dident work as a mechanic and after it he vanished quick and goes for him, kills him and gets stuck.

How it works:  he should go back on the tank or do something..

How it should work: He should be doing anything after that

Source (you should point out proofs of your report, please give us some source):  i have a clip of what happend https://www.twitch.tv/videos/350346318

**Comment by Wojtyas** [comment]
Moved to massive topic.
