### ISSUE TITLE
Horde quest in Shadowmoon Valley

### ISSUE THREAD

**Issue by RibGobbler2** [SunwellWoW/Sunwell-TBC-Bugtracker#3544]
Description: 
To Legion Hold (quest name)

How it works: 
When you pick a quest, you get a box (quest item) wich is used to disguise yourself and spy on Legion plans, thats all actually, but when i come back to turn in it, it sends me to alliance camp to turn in, not to horde npc. Only that is the problem, everything else works.

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
I can provide picture of Quest.

**Comment by Dootz** [comment]
Weird, can't reproduce it. Works fine for me :(

**Comment by Reflekz** [comment]
I'm on the alliance side , and its telling me to turn it in to Blood Guard Gulmok at shadowmoon village which is Horde camp.
Here is a SS.
![wowscrnshot_010619_031227](https://user-images.githubusercontent.com/44597439/50733258-f49d6880-1160-11e9-9517-ebbb24d6c0a8.jpg)

**Comment by RibGobbler2** [comment]
I gave up on that Quest, dont need it anymore, reeeee
Thx for feedback buddy, cheers.
