### ISSUE TITLE
More Shade of Aran issues.

### ISSUE THREAD

**Issue by xethra89** [SunwellWoW/Sunwell-TBC-Bugtracker#3547]
Description: 
Additional Shade of Aran issues not reported yet. 

- [ ] Shade of Aran's arcane missles are critting. They shouldn't. 

- [ ] Shade of Aran's flame wreath can still be triggered by pet movement. Pets should not trigger flame wreath. 

- [ ] (Duplicate) Just for reiteration and further explaination, Dragon's breath can trigger flame wreath if a certain type of behavior happens: 

If a player gets Dragon's Breathed and moves out of the debuff of flame wreath, then back in, it will trigger an explosion. 

See this clip - 
https://www.twitch.tv/proplays/clip/OptimisticInterestingClipzRedCoat?filter=clips&range=7d&sort=time

Note: If a player gets Dragon's Breathed and does not leave the area of the flame wreath, nothing happens (this is correct behavior). It's only when they leave the area on the ground and then walk back in it that triggers the explosion. 

 
How it works: 
Arcane Missles crit, they should not.
Pets trigger flame wreath, they should not.
Dragon's Breath can sometimes trigger flame wreath, it should not. 

How it should work: 
Arcane Missles should not crit. 
Pets trigger flame wreath, they should not.
Dragon's Breath can sometimes trigger flame wreath, it should not. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Moved to massive topic.
