### ISSUE TITLE
Rogue Assassination set bonus bugged

### ISSUE THREAD

**Issue by lordazurescens** [SunwellWoW/Sunwell-TBC-Bugtracker#3548]
Description: 
Immune cheap shots do not apply the two piece haste set bonus. 

How it works: 
When you cheap shot a stun immune mob. you don't get haste bonus.

How it should work: 
it should work just like kidney shot. you get the haste bonus from two piece when you use cheap shot.

Source (you should point out proofs of your report, please give us some source): 
Easily testable in game. kidney a boss. and cheap shot a boss with the two piece set equipped.

**Comment by akrom23** [comment]
Works fine.
