### ISSUE TITLE
Curator continues evocate during enrage [Karazhan]

### ISSUE THREAD

**Issue by xethra89** [SunwellWoW/Sunwell-TBC-Bugtracker#3552]
Description: When curator gets to 15%, he 'soft enrages' increasing his attack speed and hateful bolt cast rate. Curator will 'enrage' and gain the buffs, however he continues to evocate and continues to take extra damage. 

How it works: 
See above.

How it should work: 
When Curator reaches 15%, he should stop evocating and continue melee attacking/using hateful bolts. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Moved to massive topic.
