### ISSUE TITLE
[General][Mailbox] Mailbox messages duration is broken

### ISSUE THREAD

**Issue by Azmoddan** [SunwellWoW/Sunwell-TBC-Bugtracker#3553]
Description: 

Duration of mails kept on the mailbox is broken.

How it works: 

If you send a mail to another character it stays for 29-30 days in his mailbox, server restarts are possibly breaking the timer and it is changed to 2-3 days until automatic reply.

How it should work: 

If you send a mail to another character it should stay for the full duration or until it is replied, it shouldn't be determined by server restarts.

**Comment by Azmoddan** [comment]
It may not be the restarts but it might happen while reading the mail, it shortens its duration then.

**Comment by LezChap** [comment]
Opening/reading a message will change the duration it remains in your mailbox from 29days(+hours not visible by default ui) to 2days(+hours not visible by default ui)...the time remaining should not change when you read a message.
