### ISSUE TITLE
Blessing of Sanctuary and Greater Blessing of Sanctuary

### ISSUE THREAD

**Issue by Dusyagonemad** [SunwellWoW/Sunwell-TBC-Bugtracker#3558]
Description: 
Blessing of Sanctuary and Greater Blessing of Sanctuary scale with bonus spell damage.

How it works: 
Spd dramatically increases output damage by blessings. Like 150spd gives +60dmg.
(not sure, but Thorns, Imp's Fire Shield looks like scale too)

How it should work: 
Spd shouldn't increase damage by blessings.

Source (you should point out proofs of your report, please give us some source): 
http://paladin-guide.blogspot.com/2005/12/blessings.html
"Holy damage dealt from this bless isn’t influenced by +spell damage bonus on items."

**Comment by Delfury** [comment]
Blessing of Sanctuary doesn't deal damage...

**Comment by Dusyagonemad** [comment]
?

![50183587-9c263880-0323-11e9-8793-937d91e2f0dd](https://user-images.githubusercontent.com/43555289/50208500-61072200-0382-11e9-913d-5c7a00d369cb.jpg)
