### ISSUE TITLE
Improved Power/Prayer of Fort

### ISSUE THREAD

**Issue by Cowb0ySMURF** [SunwellWoW/Sunwell-TBC-Bugtracker#3559]
Description: It's not applying. The spell says +70 STA, the buff only gives 54.

How it works: 
Once points are put into the talent, the spell updates, but the buff itself does not.

How it should work: 
It should give 70. It's giving 54

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_121718_173604](https://user-images.githubusercontent.com/45952930/50120056-5df52000-0222-11e9-9c98-1d20446492c6.jpg)
![wowscrnshot_121718_173607](https://user-images.githubusercontent.com/45952930/50120057-5df52000-0222-11e9-8e9f-b37a2605afb2.jpg)

**Comment by Gamemechanicwow** [comment]
The bufftexts are static, and doesn't represent values altered by talents etc. This is a limitation of the client.

You can check on char info, that you get the proper amount of stamina.

**Comment by Wojtyas** [comment]
Yep, its client side feature and we can't change it. It increased proper amount of stamina but display will always show you stats w/o talent mod.
