### ISSUE TITLE
Combat Rogue 41 point talent Surprise Attacks

### ISSUE THREAD

**Issue by Feorblade** [SunwellWoW/Sunwell-TBC-Bugtracker#3560]
Description: 

As the talent says, "Your finishing moves can no longer be dodged" but finishers can still be dodged. Not sure if the 10% damage bonus also doesn't work
How it works: 
Finishing moves are still being dodged by mobs and players

How it should work: 

Finishing moves should not be able to be dodged
Source (you should point out proofs of your report, please give us some source): 
Read the talent

**Comment by Wojtyas** [comment]
By source/proof we mean that you should show us that someone actually dodged ur finishing move. Have any screen/video?

**Comment by Feorblade** [comment]
https://i.imgur.com/c4FkpEN.png

https://i.imgur.com/XhwWsfx.png

that work?

**Comment by Feorblade** [comment]
In case you need more data.

https://i.imgur.com/GSWdYWB.png

I'm HOPING the 10% damage buff works but I'm not exactly rich enough to test that by unspeccing combat then respeccing. So if you would kindly do that for me it would be greatly appreciated considering the dodge aspect clearly doesn't work

**Comment by luddeguuut** [comment]
Ye, my finnishers also gets dodged
