### ISSUE TITLE
Cabal Summoners - Shadow labs

### ISSUE THREAD

**Issue by Feorblade** [SunwellWoW/Sunwell-TBC-Bugtracker#3561]
Description: 

The Cabal summoner shadow bolts cannot be interrupted with kick
How it works: 

These mobs, specifically, continue to cast through interrupts.
How it should work: 

Interrupts should lock out their school and stop the cast
Source (you should point out proofs of your report, please give us some source):

**Comment by ZaoQ** [comment]
Also SB has very low dmg - 900 in hero instead of 2500

**Comment by ZaoQ** [comment]
500 in normal instead of 1,217 - 1,551
900 in hero instead of 2,591 - 2,896
