### ISSUE TITLE
[Quest] A little help from my friends (Un'goro ringo escort)

### ISSUE THREAD

**Issue by mooviestar** [SunwellWoW/Sunwell-TBC-Bugtracker#3562]
Description: 
At the last moment of the escort arriving near the turn in NPC, Ringo turned and locked his following to another npc that was chasing an alliance player. I could not get Ringo to follow me again. I had to aggro a  bloodpetal to cause the other npc to chase it toward the quest turn in NPC. 

How it works: 
Ringo started to follow another NPC rather than me

How it should work: 
Ringo should follow only me

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?quest=4491

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1166
