### ISSUE TITLE
Sporeggar and kurenaï reputations

### ISSUE THREAD

**Issue by Kuakertupu** [SunwellWoW/Sunwell-TBC-Bugtracker#3566]
Description: Can't up my sporeggar and kurenai reputations with mob slaying and questing. 

How it works: When i slain a mob that should give me some sporeggar or kurenai reputation or when i turn in a quest it gives me unfriedly reputation instead of lower it. I can't get neutral or friendly, it keeps resetting to unfriendly when i hit 3000 rep.

How it should work: It should lower unfriendly reputation to give me neutral then friendly rank on those reputations

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_121818_040358](https://user-images.githubusercontent.com/45856903/50129776-d982bb80-027a-11e9-8e33-22413c7732a4.jpg)
![Uploading WoWScrnShot_121818_040441.jpg…]()
![Uploading WoWScrnShot_121818_040523.jpg…]()

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/50160042-88091980-02d8-11e9-843f-d09d92bff8d2.png)
![obraz](https://user-images.githubusercontent.com/37483678/50160089-a96a0580-02d8-11e9-9ccf-f50c4c82455b.png)
That's how it works - your unfriendly reputation is growing and when you pass 3000/3000 it turns to neutral.
If you were hated with someone then it would turn to unfriendly first - i believe that's the case here
