### ISSUE TITLE
you can bop someone in cyclone

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#3567]
Description: 

bop on cyclone
How it works: 
bop through cyclone

How it should work: 
cyclone should stop all 

Source (you should point out proofs of your report, please give us some source):

**Comment by mjk6994** [comment]
are you implying that you can bop someone in a cyclone, or bop someone else as the pally in the cyclone?

**Comment by mjk6994** [comment]
Because you're supposed to be able to cast BoP/Blessings on other People while Cycloned. Just not supposed to be able to be BoPed while Cycloned, it caused it to go on CD and was immuned.

**Comment by baade123** [comment]
maybe they fixed it lol havent tested it since

**Comment by akrom23** [comment]
I don't understand this report. So cycloned target should be immuned or what?
BoP does not remove cyclone.
