### ISSUE TITLE
Shaman earth shock interupt

### ISSUE THREAD

**Issue by BronzeJukes** [SunwellWoW/Sunwell-TBC-Bugtracker#3568]
Description: 
Shamans Earth shock should be able to interupt spell casting, not always it does, have been inside shadow lab, i tried to interupt Shadow bolt, Heal, Fear, Summon something. Some was interupted some not. shocked mid casting so it should be good.

How it works: 
50/50 if it interupt.

How it should work: 
Interupt.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
I dunno if its creature issue or spell :o

**Comment by FrauHolle86** [comment]
still not working properly
