### ISSUE TITLE
Shaman, Totem of Wrath

### ISSUE THREAD

**Issue by BronzeJukes** [SunwellWoW/Sunwell-TBC-Bugtracker#3569]
Description: 
I don't know if this is bug or just not visble. when i put down my ToW, i can't see if i get any hit rating.

As it tell "Summons a Totem of Wrath with 5 health at the feet of the caster. The totem increases the chance to hit and critically strike with spells by 3% for all party members within 20 yards. Lasts **2min."
i dont see the 3% Hit increase in my hit rating. 

2.77 % hit before and after totem is set. 
dont know if its not visble or bugged?

How it works: 
![wowscrnshot_121818_055047](https://user-images.githubusercontent.com/45659742/50132788-1ce42680-0289-11e9-8a90-b0b34f83fc1f.jpg)
![wowscrnshot_121818_055057](https://user-images.githubusercontent.com/45659742/50132789-1ce42680-0289-11e9-9140-b5493a3777ce.jpg)

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
It's not shown in char sheet - blizz.
