### ISSUE TITLE
[Core/Spell] Meeting stone crash

### ISSUE THREAD

**Issue by Piootrek** [SunwellWoW/Sunwell-TBC-Bugtracker#357]
Using meeting stone crashes the server
http://db.hellfire-tbc.com/?spell=7720#abilities

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC/commit/a643cc01650bcb4d9b5cb7b276fac531bdd05b0e

**Comment by Riztazz** [comment]
Re-test required
