### ISSUE TITLE
Shaman, Temor Totem

### ISSUE THREAD

**Issue by BronzeJukes** [SunwellWoW/Sunwell-TBC-Bugtracker#3571]
Description: 
Temor Totem i am not sure about how this should work. but the totem is very slow to remove effects sometimes, i cant find any infomation about how the totem removes, if it pulses or works constantly or how long between the pulse. Sometimes when my grp gets feared, we can  stay feared for like 2-4sec without getting out immediately.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by SunwellTracker** [comment]
This is how Tremor Totem should work. Please make some reserach before writing a report.
