### ISSUE TITLE
Missing Cooking Recipe: Roast Raptor

### ISSUE THREAD

**Issue by cleffie** [SunwellWoW/Sunwell-TBC-Bugtracker#3573]
Description: 
Website and Add-on show I should be able to purchase the Recipe: Roast Raptor from certain vendors, but I have checked 2 out of the 4 vendors, i could not find it. 

How it works: 
Cannot find the recipe from vendors.

How it should work: 
Horde Vendors that sell that recipe:
Keena - Arathi Highlands
Nerrist - STV
Ogg'marr - Dustwallow Marsh
Vendor-Tron 1000 - Desolace

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=12228/recipe-roast-raptor

**Comment by ghost** [comment]
Can confirm, recipe is missing from Corporal Bluth, Hammon Karwn, Helenia Olden, Keena, Nerrist, Ogg'marr.
It can only be found on Vendor-Tron 1000 which is limited to (1) at the moment
