### ISSUE TITLE
Is Schematic: Adamantite arrow maker avaliable ? 

### ISSUE THREAD

**Issue by RPAncap** [SunwellWoW/Sunwell-TBC-Bugtracker#3575]
Description: 
Hey I know this is not a proper channel to ask this question, sorry for that. I just wanted to check if you can confirm that 
 https://www.wowhead.com/item=20475/adamantite-arrow-maker is avaliable in this patch (wowhead says added in 1.12.1) however adamantite shells are not avaliable. And this schematic has low drop rate from mob in netherstorm - So I want to check first before I start grinding :-)

**Comment by Wojtyas** [comment]
As far I know it's from 2.3 Zul'Aman patch, as comments in your link say.
