### ISSUE TITLE
[NPC]Broggok(normal) poison bolt

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#3576]
Description: 
Description says it should deal between 280 and 380 nature dmg(wont report poison cloud problem, u got it already reported)

How it works: 
It deals MUCH more dmg making the fight harder af. Its normall, not HC
![image](https://user-images.githubusercontent.com/43579401/50145815-af4cf000-02b2-11e9-85bc-90bf74076e10.png)

How it should work: 
Should deal dmg correctly with description or less(depending on player ressistances).

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Pre-nerf values?

**Comment by Mikov1605** [comment]
I just Remember it should deal around 250-300 per tick. On hc it deals 700-850
