### ISSUE TITLE
Tailoring pattern missing

### ISSUE THREAD

**Issue by dgasen** [SunwellWoW/Sunwell-TBC-Bugtracker#3577]
Description: 
The NPC 'Borto' in nagrand does not have the Pattern: Bolt of Soulcloth

How it works: 

He does not have the Pattern: Bolt of Soulcloth

How it should work: 

He should have the Pattern: Bolt of Soulcloth

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Added.

**Comment by sabo92** [comment]
Wojtyas this is still not to be found at the vendor's who should sell it
