### ISSUE TITLE
[Raid - Karazhan] [NPC - Netherspite][Spell - Nether Burn] Doesn't use spell

### ISSUE THREAD

**Issue by Cherryxo** [SunwellWoW/Sunwell-TBC-Bugtracker#3581]
Description: Netherspite should have an aura type spell that does aoe dmg to the raid

How it works: As of 17-12-18 Netherspite has no raid wide dmg in portal phase

How it should work: 
Nether Burn: Aura type spell (exactly as Baron Rivendare's and Lord Alexei Barov's), deals 1200 shadow damage every 5 seconds, affected by line of sight. This damage is resistible, so shadow resist buffs beforehand can negate much of it. Only active during Portal phase.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Netherspite

**Comment by Wojtyas** [comment]
Moved to massive thread.
