### ISSUE TITLE
The Arcatraz

### ISSUE THREAD

**Issue by Chillexn** [SunwellWoW/Sunwell-TBC-Bugtracker#3584]
Description:  Eredar Deathbringers all get chain pulled

How it works: 
When you try to pull one of the mobs all 3 mobs come at the same time. 
This results in whipe whithin 10 secounds

How it should work: 
You sould be able to pull them 1 by 1

Source (you should point out proofs of your report, please give us some source): 
My source is that my damd party disbanded since it basicly makes it impossible to clear.

**Comment by zapsuu** [comment]
Correct. They should pull 1 by 1, atm moment kill this trash is really hard.
