### ISSUE TITLE
Ghosts inside Sunken Temple

### ISSUE THREAD

**Issue by kattmat** [SunwellWoW/Sunwell-TBC-Bugtracker#3585]
Description: Ghost that spawn from trolls when they are killed

How it works: They spawn but they run at normal speed

How it should work: should be walking instead of running, no way you can kite them

Source (you should point out proofs of your report, please give us some source): well a image wont do much and I cant apply my video capture....

**Comment by BronzeJukes** [comment]
Same with Prophets in shattered halls
