### ISSUE TITLE
Hunter feign death transferring threat to pet

### ISSUE THREAD

**Issue by Jonsbe** [SunwellWoW/Sunwell-TBC-Bugtracker#3586]
Description: Hunter feign death transfers player threat made on mob to pet on group while on dungeon. 

How it works: Feign death and players threat on monster transfers to pet.

How it should work: Feign death drops all threat on player - doesnt transfer to pet. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Jonsbe** [comment]
Noted happens when in dungeon party, and feigning when you got agro from tank.

**Comment by Ironjudgment** [comment]
I've noticed that during dungeons my pet doesn't loose agro. I have todismiss my pet to not have any agro but on the next pack pet still gets cb bug, but it doesn't ahppen all the time.

**Comment by akrom23** [comment]
@Jonsbe @Ironjudgment Any news here? Still happens?
In code, there is no threat transfer.

**Comment by Jonsbe** [comment]
@akrom23 There is several shits happening with Feign death. First when raiding ex. prince in karazhan. Ill say things that happen that should not happen. Doing MD on tank popping aimed, arcane + multishot. MD goes fine, and if another hunter is doing md also your md wont do shit. You shouldnt be able to MD if MD is on tank already. Second when beign close to tanks threat you feign, threat drops on your Diamond threat meter or omen, but when asking others did your threat drop they say no. Ive tried going melee range and do 3-5s feign as in staying in ground looking pathetic, but when you pop up your threat will get back. We have 4 hunters raiding atm and every single hunter is complaining the same. Its like random generator does it work on some mobs, and if it fails it will always fail. When doing dungeons or trash mobs, you will send in your pet and start popping nice shots on the mob, you get agro since your godlike and then you feign, and mob should be start hitting second on threat, but nope, your glorious pet will be suddenly higher than the tank cos of the feign transfering your threat somehow to your pet. This rarely happens with raid bosses tho. Also another thing... on raid bosses when you get agro, you feign, even with 2x t4 set pieces feign resist not possible and also not visible thing showing it got resisted, your threat either drops or not (so boss will come and get you while you lay on ground pathetically OR boss will target the second on threat, but AS SOON AS you pop up, boss will just remember how badly it hates you and will come for your nice ass and pop it like a grape. Every single hunter does know these who raids, everyone. So just go ahead and make one and start raiding and you will see every single thing i just posted. 100%. Like every single hunter on my guild is saying these same things. Also the threat is bugged overally somehow since you CANNOT trust the threat meters (Diamond Threat Meter 1.7.0 - OR OMEN). In my opinion overally threat is bugged and effects also Feign death somehow. I've watched streams guilds doing TK and even him complains the threat meter is not trustable AS IT SHOULD BE and has been in retail (and other priv servers). I feel like shit when dps is killing raid since overagro and i was not even close to pull agro. Was watching the stream and there was encha shaman streaming, there was also another encha shaman with him raiding. The streamer is on threat meters like 5-6th, another encha shaman is 2-3rd, suddenly boss just whacks the streamer dead and goes back to boss, like what? ALSO when hunter pulls agro, and feigns and it works, boss just starts going after the third and forth etc agro and not back to second as it should be. GAAH feel like raging just by writing of all the possible bugs here. Rant out. Im Draylana ingame if you feel like talking about these.

**Comment by Jonsbe** [comment]
And if you want some material about these matters, please explain to me what you want and what you need and how you want me to show it to you. I will do it if these bugs are getting fixed. But just talk to any raiders.

**Comment by Ironjudgment** [comment]
any plans for target dummies being implemented? would allow us to test a massive amount of skills/talents/rotations etc

I made a post asking about target dummies but it was closed without giving a reason or explaining devs position on this

**Comment by Jonsbe** [comment]
@Ironjudgment nice points, but in my opinion wrong thread to post about this, keep in on the matter please.

**Comment by Jonsbe** [comment]
@akrom23 some screenshots on https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4081 about same matter.

**Comment by akrom23** [comment]
@Jonsbe Okay, thx

**Comment by MiekZer** [comment]
I just want to react on "boss going on 3rd/4th instead of 2nd on threat. (after killing the hunter)

If things are well scripted this is something that can happens.
When the boss is moving on the hunter if the tank is not moving from his position then he's considered in range. That means he must have 130%+ threat (and be first) to take aggro back when the hunter will dead. If someone closer to the boss (then considered as melee) has 110%~ threat but is third, then he will take aggro over the second on the threat meter who is in range with 120%~ threat.

**Comment by Jonsbe** [comment]
@MiekZer I know, but im talking about "obviously" when he goes after 3rd and 4rd when they are 50-90% threat compared to tank, so not the cases you're talking about.
