### ISSUE TITLE
NPC pathfinding Magister Aledis

### ISSUE THREAD

**Issue by N7Nosk** [SunwellWoW/Sunwell-TBC-Bugtracker#3587]
Description: 
NPC Flying

How it works: 
He is flying.
How it should work: 
He should walk on the ground

![wowscrnshot_121818_184218](https://user-images.githubusercontent.com/45974071/50165097-3b800700-02f5-11e9-8305-41be884e9acc.jpg)
![wowscrnshot_121818_184228](https://user-images.githubusercontent.com/45974071/50165098-3b800700-02f5-11e9-82c4-fa541107a20e.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by peanutcheese** [comment]
![image](https://user-images.githubusercontent.com/877201/50407976-a85a3c00-07e2-11e9-8684-806a53a554ba.png)

He's under ground now.
