### ISSUE TITLE
Imporved Power Word: Fortitude 2/2 Does not effect Power word: Fortitude

### ISSUE THREAD

**Issue by dgasen** [SunwellWoW/Sunwell-TBC-Bugtracker#3589]
Description: 

It seems that the talents chosen i Imporved Power Word: Fortitude does not affect the spell.

How it works: 

Spellbook tells the buff to increase stamina by 102.

In reality it does only increase stamina with 79.

How it should work: 

It should increase stamina by 102.

Source (you should point out proofs of your report, please give us some source):

**Comment by Martin-Dalgaard** [comment]
This is not true. Check your stamina on character.

Wow has always had tooltip without modifier.
