### ISSUE TITLE
[Leatherworking - Drums of Battle]

### ISSUE THREAD

**Issue by Gryma** [SunwellWoW/Sunwell-TBC-Bugtracker#3590]
Description: Increases haste on nearby party members by up to 32.  Lasts 30 sec.

How it works: When use it, only member in less 5 yards get it. 

How it should work: radius is 40 yards

Source (you should point out proofs of your report, please give us some source): 
https://db.excalibur.ws/?spell=35476

**Comment by Nicklastoft** [comment]
Confirmed that this is in fact working with around 5 or less yards, instead of 40 - seems like a simple enough fix

**Comment by koostosh** [comment]
It is decreased on purpose, before 2.3 patch range is 8yds.
