### ISSUE TITLE
[Hunter's pet skill] Avoidance

### ISSUE THREAD

**Issue by Iperyth** [SunwellWoW/Sunwell-TBC-Bugtracker#3592]
Description: 
Avoidance skill is not working on Area of Effect spells.

How it works: 
Avoidance skill doesn't give 50% dmg reduction from AoE spells and effects.

How it should work: 
Avoidance should give 50% dmg reduction for pet's incoming AoE damage.

Source (you should point out proofs of your report, please give us some source): 
![log2](https://user-images.githubusercontent.com/45659353/50174123-a4697e00-02f9-11e9-92dd-c9ed025f459d.PNG)
![log1](https://user-images.githubusercontent.com/45659353/50174125-a4697e00-02f9-11e9-8b0d-0240074362a6.PNG)

**Comment by mintnb** [comment]
Works for some sources and not others

**Comment by MiekZer** [comment]
Doesn't work on curator astral flares aoe
