### ISSUE TITLE
Nightmare seed

### ISSUE THREAD

**Issue by BIGCHESTDAY** [SunwellWoW/Sunwell-TBC-Bugtracker#3597]
Description: Nightmare seed does not drop period

How it works: https://wow.gamepedia.com/Nightmare_Seed

How it should work: 
Nightmare seed should be in the game https://wow.gamepedia.com/Nightmare_Seed

Source (you should point out proofs of your report, please give us some source):

**Comment by xethra89** [comment]
Yes, they do drop. Check the auction house. I've also personally picked multiple Nightmare Seeds from Nightmare Vine in SMV.

**Comment by Dootz** [comment]
can confirm it drops from Nightmare Vine
