### ISSUE TITLE
Movement in low-lying ceiling places

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#360]
When we are fightning with npcs, or we have a pet in space/room where ceiling is lower-lying then creatures like to "jump" into air and fly for some period of time. It looks like creatures recognize ceiling as a floor and they likely try to walk on it. Mostly happen in caves, basements or some narrow stairs.

High prio since many of low-lvl dungs have ceiling just above players heads and we launch those dungs soon! :fire:

**Comment by Azathothh** [comment]
Still can see it at beginning of Blackfathom Deeps (ceiling is really low there)
