### ISSUE TITLE
Spellstrike Set (Lesser Spell Blasting proc chance low)

### ISSUE THREAD

**Issue by zonk2** [SunwellWoW/Sunwell-TBC-Bugtracker#3600]
Description: 
It seems that the proc chance of the Set is too low. Please look into it.

How it works: 
It feels that the Proc is under 1%

How it should work: 
Proc should be atleast ~5%

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item-set=559/spellstrike-infusion#comments

**Comment by akrom23** [comment]
#1850
