### ISSUE TITLE
Hunterpets Bugged in sooo many ways

### ISSUE THREAD

**Issue by Hunterpetsneedfixasap** [SunwellWoW/Sunwell-TBC-Bugtracker#3604]
Description: 
Hunter pets have many buggs for example happines decreases 1 colour avery time his corpse spawn and hunter pets lose randomly all abilities passive and active and he doesnt get his points back.

How it works: 
1: Hunter pet dies it is insta yellow happinies if i dont revive him in next 20 sec his corpse despawns and i need to use call pet otherwise i cant revive it and after the call it is RED even if it was green when it died. Is also happens when i go differnt instances or portals with a dead pet.
2: Hunter pet loses ALL his passive and active abilites i learned him and he doesnt get his abilitie points back. so Hunter needs to respec hunter pet points to fix this. 

How it should work: 
1: Hunter pet dies it should lose some happines and not more happienes after it coprse is summoned. 
2: hunter pet should never lose abilites

Source (you should point out proofs of your report, please give us some source): 
50% hunter on server have this weird buggs PLS FIX TY

**Comment by akrom23** [comment]
> Hunter pet dies it is insta yellow happinies if i dont revive him in next 20 sec his corpse despawns and i need to use call pet otherwise i cant revive it and after the call it is RED even if it was green when it died. Is also happens when i go differnt instances or portals with a dead pet.

https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2142#issuecomment-460542394

> 2: Hunter pet loses ALL his passive and active abilites i learned him and he doesnt get his abilitie points back. so Hunter needs to respec hunter pet points to fix this.

I need more info about that - how to reproduce it.

**Comment by akrom23** [comment]
No response.
