### ISSUE TITLE
[Q] The Smallest Creatures

### ISSUE THREAD

**Issue by ItsFilko** [SunwellWoW/Sunwell-TBC-Bugtracker#3607]
Description: When controlling the Marmot you are frozen and unable to move, after cancelling control the only way to regain control of your character is to relog

How it works: After using the drums on the NPC you gain control, but are incapacitated and unable to move to complete the quest.

How it should work: You should gain control of the NPC and have to avoid/use abilities to get past Ogres in order to poison the beer kegs.

Source (you should point out proofs of your report, please give us some source):  https://youtu.be/CwOb-p_LvVk 

Video is unlisted, only use this link to access.

**Comment by wilczakadam** [comment]
confirmed, not able to complete the quest

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1593
