### ISSUE TITLE
Black morass, nothing is working 

### ISSUE THREAD

**Issue by Macdog2202** [SunwellWoW/Sunwell-TBC-Bugtracker#3608]
Description: 
Everything in black morass is bugged, Crocs evade in water, portals have same routine (should be random) mobs run directly to portal, cant be taunted. last boss evading until he attacks shield. and also only dropping 1 loot instead of normally 2x

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Gelori** [comment]
best!

**Comment by aspectslul** [comment]
NETHERWING GUYS NETHERWING IS ONLY WAY
