### ISSUE TITLE
Arcatraz Sentinels

### ISSUE THREAD

**Issue by lumbien** [SunwellWoW/Sunwell-TBC-Bugtracker#3613]
Description: Arcatraz Sentinel's Energy Discharge going off multiple times a second when it should be happening periodically on the first pull. Once you wipe and the mob resets it works as it should, but this causes a minimum of 3 or 4 wipes to get past this trash.

How it works: Energy Discharge on the first pull will one shot anyone nearby.

How it should work: Energy Discharge periodically goes off zapping a nearby target, 

Source (you should point out proofs of your report, please give us some source): 
![capture](https://user-images.githubusercontent.com/45579338/50195184-4342aa00-02fb-11e9-9c31-7a773f31c4fa.PNG)

**Comment by Eternae1** [comment]
This nearly makes the dungeon impossible unless you just blast them down and stun-lock or kite them. Pretty critical bug please work on this right away.
