### ISSUE TITLE
Inspiring Presence on Mage (Draenei Passive)

### ISSUE THREAD

**Issue by grand-lotus-iroh** [SunwellWoW/Sunwell-TBC-Bugtracker#3616]
+1% Hit passive buff does not appear on Mage.

Please fix ASAP.

**Comment by grand-lotus-iroh** [comment]
Status update please? Can you please fix this? ETA>?

**Comment by akrom23** [comment]
![wowscrnshot_011419_171958](https://user-images.githubusercontent.com/1035215/51125345-b539e080-1820-11e9-922f-40902e3dab88.jpg)
