### ISSUE TITLE
Unforgiven is not spawning in stratholme

### ISSUE THREAD

**Issue by Bezimienny95** [SunwellWoW/Sunwell-TBC-Bugtracker#362]
Decription: 
No Unforgiven spawn in stratholme

How it works: 
Nothing happens

How it should work: 
Moving close to closed gate in stratholme should spawn Unforgiven

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_091118_202843](https://user-images.githubusercontent.com/31216921/45379865-8f49c880-b601-11e8-959a-680c28b51280.jpg)

**Comment by Dootz** [comment]
duplicate: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/337
