### ISSUE TITLE
Black Morass trash mobs (spider/jaguars) completely broken.

### ISSUE THREAD

**Issue by Ethugx** [SunwellWoW/Sunwell-TBC-Bugtracker#3622]
Description: 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by neheri** [comment]
They seem to be afraid of water. If you have them pulled and step into even very shallow water they just evade.

Another thing that is bugged a lot is evade. Sometimes with enemy NPC in combat it just evades you. No need to move or do anything, they just suddenly decide to evade and that happens even in instances. Huge bug.
