### ISSUE TITLE
Druid Swingtimer Bear form

### ISSUE THREAD

**Issue by absdr** [SunwellWoW/Sunwell-TBC-Bugtracker#3624]
Description: 
If you switch to bear form an charge on the target the first hit needs like 2-3 seconds to hit the mob... 
Huge problem for pvp because you cant use ur bear stun until the first hit is done because of rage

How it works: 
If you switch to bear form an charge on the target the first hit needs like 2-3 seconds to hit the mob..

How it should work: 
If you switch to bear form an charge on a target, the first hit should come instant. 

Source (you should point out proofs of your report, please give us some source):

**Comment by baade123** [comment]
also noticed this
