### ISSUE TITLE
[Quest] Seek Out Ameer and A Mission of Mercy Unavailable

### ISSUE THREAD

**Issue by bimbley** [SunwellWoW/Sunwell-TBC-Bugtracker#3625]
Description: 
There is a chain quest in Netherstorm that is unavailable, and as a result:
1. Ethereum Prison Keys can never be obtained, removing both a viable way to farm Outland reputations and make gold
2. Yor, the boss in Heroic Mana Tombs, cannot be summoned, nor can the chain that involves his summoning.
The offering of this quest should actually be a very quick fix; it simply needs to have a prerequisite removed from the scripting. 

How it works: 
Protectorate Advisor Rahim does not offer the quest "Seek Out Ameer" to players who have accepted and/or completed ANY of the following quests: "A Mission of Mercy", "Escape from the Staging Grounds", "The Ethereum", or "Arconus the Insatiable". This is intended behavior, as "Seek Out Ameer" is intended to be a breadcrumbs quest for players who have not ever talked to Commander Ameer. I have not had the chance to test whether he offers "Seek Out Ameer" to players at Honored reputation with The Consortium who have NOT accepted and/or completed any quests from Commander Ameer. 

However, Commander Ameer does not offer the quest "A Mission of Mercy" to players who have not completed "Seek Out Ameer" because the server thinks "Seek Out Ameer" is a prerequisite quest. 

Ethereum Jailors only drop Ethereum Prison Keys if the quest "A Mission of Mercy" is completed, and as such, Ethereum Prison Keys cannot ever be obtained if the player completes any quests associated with Commander Ameer before reaching Honored reputation with The Consortium.

How it should work: 
1. At Honored reputation with The Consortium, Commander Ameer should offer the quest "A Mission of Mercy", regardless of the completion of "Seek Out Ameer". "Seek Out Ameer" is a breadcrumbs quest, not a prerequisite, and the issue is that, in the server's scripting, "Seek Out Ameer" is considered a prerequisite quest to "A Mission of Mercy". In order for "A Mission of Mercy" to be correctly offered, "Seek Out Ameer" MUST be removed as a prerequisite quest.

2. Additionally, one of two things should happen:
-If any of the quests "A Mission of Mercy", "The Ethereum", "Escape from the Staging Grounds", or "Arconus the Insatiable" has been accepted and/or completed, Protectorate Advisor Rahim should not offer "Seek Out Ameer". (This works correctly.)
-If no quests that start or end at Commander Ameer (listed above) have been accepted and/or completed, Protectorate Advisor Rahim should offer "Seek Out Ameer". (I have completed the quests from Commander Ameer and, as such, I cannot confirm or deny whether this works correctly.)

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=10969/seek-out-ameer#comments 
In this WoWhead comment chain for "Seek Out Ameer", you can see it confirmed that a player must be Honored with the Consortium and not have completed any quests from Commander Ameer in order for "Seek Out Ameer" to be offered.

https://www.wowhead.com/quest=10970/a-mission-of-mercy#comments
In this WoWhead comment chain for "A Mission of Mercy", the ONLY mentioned requirement aside from level is for a player to be Honored with The Consortium. This quest's availability SHOULD NOT be determined by the completion of "Seek Out Ameer".

**Comment by Zarant** [comment]
> The Consortium and Protectorate need your help! Players with Honored or higher reputation with the Consortium should seek out Protectorate Advisor Rahim at the Stormspire in Netherstorm or Commander Ameer at the Protectorate Watch Post in Netherstorm to get a briefing on the most recent nefarious activities of the Ethereum. 

http://wowwiki.wikia.com/wiki/Patch_2.1.0

Earliest entry of the said quest: http://web.archive.org/web/20070525084956/http://www.thottbot.com:80/q10970 - May 25, 2007 (patch 2.1)

**Comment by Dootz** [comment]
Hi, could you please check now? It should be available only with reputation requirement.

**Comment by Dootz** [comment]
should be fixed and available
