### ISSUE TITLE
Dont have permission to loot my own mob bug

### ISSUE THREAD

**Issue by Krys23** [SunwellWoW/Sunwell-TBC-Bugtracker#3629]
Description: 
As the title says

How it works: 
Every 1 out of 5 approx mobs wont let me loot says i dont have permission to loot my own mob.

How it should work: 
Its my mob i should be able to loot, and im not even in a party

Source (you should point out proofs of your report, please give us some source):

**Comment by Azmoddan** [comment]
Probably it isn't that you can't loot your own mob, because there is a chance a mob can drop nothing at all and it just the character's voice saying "That would be stealing", but there's nothing to loot.
