### ISSUE TITLE
Season_1_Arena_rewards

### ISSUE THREAD

**Issue by arkatik** [SunwellWoW/Sunwell-TBC-Bugtracker#3630]
Description: 

How it works: now Gladiator's Shoulder and Weps requires rating

How it should work: Season 1 Arena and Season 2 Arena awards should not require rating.
See price history on wowwiki

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Season_1_Arena_rewards#Item_Costs

**Comment by Azmoddan** [comment]
There is no information about requirements only about prices.

**Comment by arkatik** [comment]
> There is no information about requirements only about prices.

correct because the requirements start from season 3

http://wowwiki.wikia.com/wiki/Season_3_Arena_rewards#Item_Costs

**Comment by Azmoddan** [comment]
It looks clear now. Please then, next time add all important sources when reporting a bug.

**Comment by pleasse** [comment]
Season 3 Weapons require a personal rating and team rating of 1,850 to purchase, while shoulder slot items require 2,000. The chest, legs, hands, and head slot items do not require a rating to purchase.

though it was like 1550 chest 1600 legs head 1900 etc but that was wrath, unfortunate felt more rewarding to get pieces by having the rating for them, or to see others with shoulders/wep/head knowing they are more dedicated pvpers x( personally would not mind a req for arena items just abit reasonable so the noobs can get some items too :> anyway thats my opinion blizzlike was s3 req reee

**Comment by arkatik** [comment]
up
Season 1 Arena and Season 2 Arena awards should not require rating.
Season 3 shoulder 2000 rating, weapon 1850
Season 4 weapons have a personal rating requirement of 2050 for purchase. Season 4 shoulders require 2200 PR to be purchased. Head (1700), Chest (1600), Legs (1550).

**Comment by arkatik** [comment]
up

**Comment by dachdagger** [comment]
First people want to buy weapons, please fix this soon together with arena-items like offhand costing to maney points.
