### ISSUE TITLE
Hunter Snake trap poison/disease killing people after duel ends.

### ISSUE THREAD

**Issue by AshiyrHunter** [SunwellWoW/Sunwell-TBC-Bugtracker#3634]
Description: I place a Snake Trap during a duel and when the opponent gets to 1% health and loses the duel the poison that the snakes apply stays on them and they end up dying.

How it works:  This is an excellent question. You would have to dive deep into the certain species of snakes and the types of venom that they apply. I'm pretty sure it's Cobras. Always blame the Cobra.

How it should work: The Snake Trap should apply poisons and disease to the target enemy during a duel and once the duel is over, just as a duel with a warlock would end - the DOT(Damage Over Time) effect should end and the opponent should take no more damage.

Source: Personal knowledge from standing on top of people after duels. I'm not going to lie, I do love standing on top of corpses but this is just wrong. Thank you. <3

**Comment by Azmoddan** [comment]
This bug is rather popular. It worked this way on every WotLK server I've played, but is clearly not as it should work.
