### ISSUE TITLE
[Heroic] Slave Pens

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#3635]
Description: 
Mennu when going down the stairs he is not going but flying through them. 

Coilfang Scale-healer from the pack before the entrance to the tunnel leading to the last boss missing link to other mobs of that pack. It should pull all together.

One group of bogstroks in the chamber with the last boss respawns like in 15mins. So when u wipe on the last boss, they will respawn.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by deftelite** [comment]
Other improperly linked mobs: The 4 pack of bogstrock/greater bogstrock near rockmar the creackler should all be linked together.  

Additional error: when you release the night elf from the cage the naga that spawn spawn on top of him.  They should spawn at the entrance to the room and move up toward him.

**Comment by Mikov1605** [comment]
Same BUGS on normal
