### ISSUE TITLE
crashes in blade"s edge mountains

### ISSUE THREAD

**Issue by kaozin** [SunwellWoW/Sunwell-TBC-Bugtracker#3644]
Description: Stuck in Blades edge mountains Crashing constantly i cant log my character kao 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Laekoth** [comment]
the location is approx. 45, 73

**Comment by jbwilson11** [comment]
Duplicate of https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3643

I have a error-crash text file attached to issue 3643
