### ISSUE TITLE
Blade's edge mountain bridge crash

### ISSUE THREAD

**Issue by Buttram** [SunwellWoW/Sunwell-TBC-Bugtracker#3648]
Description: 
Blade's Edge Mountain bridge will crash your client

How it works: 
When you try to cross the bridge in the Blade's Edge Mountain the client will crash

How it should work: 
Be able to walk over the bridge without crash

Source (you should point out proofs of your report, please give us some source): 
me and everyone else who walks/fly over it crashes.

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3644
