### ISSUE TITLE
[NPC] Durn The Hungerer

### ISSUE THREAD

**Issue by TheKapral** [SunwellWoW/Sunwell-TBC-Bugtracker#365]
Decription: Durn got lazy

How it works: he stays on one place and doesnt move

How it should work: he should  walk around the white crystal thing

Source (you should point out proofs of your report, please give us some source): 
https://s19.postimg.cc/83fldpwhv/Wo_WScrn_Shot_091118_232237.jpg

**Comment by Dootz** [comment]
fixed, thanks for report
