### ISSUE TITLE
Unable to receive follow up quests (Shutting down Manaforges)

### ISSUE THREAD

**Issue by Tyton89** [SunwellWoW/Sunwell-TBC-Bugtracker#3650]
Description: I recently completed Shutting down Manaforge B'naar and upon turn in there was no follow up quest to continue the chain. I have the prerequisite amount of reputation with the Aldor faction, but the NPC will not offer a new quest.

How it works: There is currently no follow up quest, but I'm unsure if it's character specific or affecting more than just me.

How it should work: There should be a follow up quest to shutdown Manaforge Coruu

Source (you should point out proofs of your report, please give us some source): Checked various WoW quest information sites to guarantee I have all the prerequisites necessary to complete the chain.

**Comment by Dootz** [comment]
Did you completed "Measuring Warp Energies" from Exarch Orelis who is standing on the right of Anchorite Karja? If you did so, you should be able to pick up next quest after Manaforge B'naar which is "Shutting Down Manaforge Coruu". Next update should happen tomorrow morning.
