### ISSUE TITLE
All quest in Outland give the same EXP.ALL at levels and zones

### ISSUE THREAD

**Issue by lohanysarah** [SunwellWoW/Sunwell-TBC-Bugtracker#3651]
Description: 

hello ,is the exp from quest bug?,because all quest give me same exp on all zone and levels .dungeon quest (10k exp) elite quest (10k exp).normal quest (10 k  exp) .this is a bug o what?,this repeat all in outlands zone , i just stard at 58 and give 10 K as well now i am 61 in zangar and all quest give me only 10 K. and the experience bar asks in each level more and more experience, as it can be possible that a level 58 mission delivers that one of level 60 or 62? or that of the same as a dungeon mission.or a eleite mision is a was of time for all.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Xaximbo** [comment]
can confirm

**Comment by babno** [comment]
I've gotten 10k-16k from hellfire to blades edge. You just need a larger sample size.

**Comment by Xaximbo** [comment]
i don't know if it has been hotfixed but quests in zangarmarsh now give 10,2K,13k no longer 10K flat.
