### ISSUE TITLE
Resist cancels stealth

### ISSUE THREAD

**Issue by Kalisss** [SunwellWoW/Sunwell-TBC-Bugtracker#3652]
When I am in the stealth and cast Cloak of Shadows and lets say mage goes blizzard or arcane explosion, I resist but it still gets me out of stealth.

It should resist, we both get combat but it shouldnt pull me out of the stealth

**Comment by Azmoddan** [comment]
It is true.

http://wowwiki.wikia.com/wiki/Stealth
Patch 2.0.3 (09-Jan-2007): Resisted spells will no longer break "Stealth"/"Vanish".
