### ISSUE TITLE
[Druid] [Talent] - Mangle doesn't work

### ISSUE THREAD

**Issue by bleidas** [SunwellWoW/Sunwell-TBC-Bugtracker#3655]
Description: When attacked by Mangle a target should take 30% additional damage from Shred or bleed effects. 

How it works: With Mangle or without on the target the target takes the same amount of damage in bleeds.

How it should work: It should increase bleed damage on the target and Shred damage by 30% for 12 seconds.

Source (you should point out proofs of your report, please give us some source): Tested this on the server. You can do it too to see it doesn't work.

**Comment by Azmoddan** [comment]
Can anyone confirm it is not working properly?

**Comment by Kittykatreporter** [comment]
It does work properly for rip and rake. 

http://prntscr.com/lx5ywu

24 - 100
31 - x
3100/24 = 130 (well not exact but i guess it rounds up at some point durning calculations ) 

Please stop making false reports without testing shit properly...dont forget you have to reapply bleed to mangle have effect
