### ISSUE TITLE
drums of speed pattern not available

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#3662]
Description: 
drums of speed pattern not available

How it works: 
world drop pattern then -
vendor @ mag'har in patch 2.3 ?

How it should work: 
Added in patch 2.0.1.6180  (isnt that what patch were on OR? )

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=29718/pattern-drums-of-speed#comments

**Comment by Zarant** [comment]
> Drums of Speed and Drums of Restoration are no longer world drop recipes, and can now be obtained from the Mag'har and Kurenai faction vendors with revered standing. 

http://wowwiki.wikia.com/wiki/Patch_2.3.0

**Comment by baade123** [comment]
Yes... that would be exactly what i wrote in my report, rofl.

**Comment by baade123** [comment]
Let me be more clear, the pattern does not exist at vendor, or as a world drop. so either way (depending on what patch Dev's are trying to emulate) there is an issue.

**Comment by baade123** [comment]
also, quoting from the link Zarant posted, "Drums of Speed and Drums of Restoration are no longer world drop recipes, and can now be obtained from the Mag'har and Kurenai faction vendors with revered standing." (in 2.3 patch)

**Comment by baade123** [comment]
WTB FIX

**Comment by Dootz** [comment]
Hi, currently it have a small chance to drop Blackwind Sabercat and Talonsworn Forest-Rager
