### ISSUE TITLE
Non-stop Drop

### ISSUE THREAD

**Issue by lfylfylfy** [SunwellWoW/Sunwell-TBC-Bugtracker#3665]
Hello. My character is dropped from server and return backout. I am flying(taxi) on mount and can't use unstuck or Hearthstone. Help me with this problem
This bug in Felwood.
Alliance, nickname Flexfy.

**Comment by Azmoddan** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3659
@akrom23  @Piootrek

**Comment by akrom23** [comment]
Duplicate.
@lfylfylfy I suggest to make a ticket ingame or visit our discord channel.
