### ISSUE TITLE
Mounting on elevators does not work

### ISSUE THREAD

**Issue by username-is-not-taken** [SunwellWoW/Sunwell-TBC-Bugtracker#3666]
Description: 
Mounts cannot be casted when standing on an elevator.

How it should work: 
It should be like mounting anywhere outdoors.

Source (you should point out proofs of your report, please give us some source): 
![mount1](https://user-images.githubusercontent.com/45629295/50255929-4a011800-03f4-11e9-8059-e66525b1b755.png)

![mount2](https://user-images.githubusercontent.com/45629295/50255933-4cfc0880-03f4-11e9-9871-1dfd5fb14d54.png)

**Comment by FrauHolle86** [comment]
same goes for Zeppelins and Ships

**Comment by akrom23** [comment]
On ships you are not able to mount - I think this is blizzlike.
