### ISSUE TITLE
Felguards in Nagrand have a lot more HP than they are supposed to have.

### ISSUE THREAD

**Issue by username-is-not-taken** [SunwellWoW/Sunwell-TBC-Bugtracker#3667]
Description: 
The felguards in Forge camp: Hate, part of the quest "Buying time", have a lot more HP than they are supposed to. On this server they have around 55k, instead they should have around 32k.

Source (you should point out proofs of your report, please give us some source): 

![felguard](https://user-images.githubusercontent.com/45629295/50256101-fcd17600-03f4-11e9-9bce-98093b4670f7.png)

![felguard2](https://user-images.githubusercontent.com/45629295/50256104-0064fd00-03f5-11e9-8980-553a8d238d68.png)
http://wowwiki.wikia.com/wiki/Felguard_Legionnaire

**Comment by neheri** [comment]
HP values on wowwiki and wowhead are lowered by WoD stat squish.

**Comment by username-is-not-taken** [comment]
Well, if you look at gamepedia (https://wow.gamepedia.com/Felguard_Legionnaire) the values are the same and in the patch history it does not mention any changes in HP.

Also, if you look at wowhead for comments from the TBC era, you'll find this one among the highest rated comments:
"As a 66 Frost Mage, I could kill every monsters but the Legionnaires. They hit about 1,000 non-crit, **they have about 31,000hp** and they have an ability to make us jump. "
(https://www.wowhead.com/quest=9999/buying-time#comments)
