### ISSUE TITLE
Curator Keeping Astral Armor

### ISSUE THREAD

**Issue by sleepyx** [SunwellWoW/Sunwell-TBC-Bugtracker#3670]
Description: 
Curator was keeping Astral Armor during Evocation had a doom go off for 363 damage.

How it works: 
He is keeping up Astral Armor during Evocation.

How it should work: 
He should drop it and take the full 300% damage.

Source (you should point out proofs of your report, please give us some source):

**Comment by MiekZer** [comment]
He shouldn't even have an astral armor to begin with.
