### ISSUE TITLE
How much can you guys flop on this server? Gruuls HP is Incorrect.

### ISSUE THREAD

**Issue by mjk6994** [SunwellWoW/Sunwell-TBC-Bugtracker#3671]
Description:  Gruul has 5.7m Hp. Should have around 3.4m.

How it works:  This was changed around 2.07 far before 2.1

How it should work:  what patch are we SUPPOSEDLY playing on

Source (you should point out proofs of your report, please give us some source): Blue post here https://blue.mmo-champion.com/topic/67074-gruul-hotfixed/ 3/22/2007.
http://wowwiki.wikia.com/wiki/Patch_2.1.0 2.1 release 5/15/2007

**Comment by mjk6994** [comment]
what patch are we even playing on im so lost.

**Comment by mjk6994** [comment]
Actually better yet, nerf hp, or make hateful strike hit 3rd highest threat because (2007-05-24): "Gruul's hateful [sic] strike will now target the second highest on the threat list instead of the third highest.." Hp nerf was implemented before this.

**Comment by Wojtyas** [comment]
Prenerf value of health points is fine... 
https://github.com/Schaka/TBC-research/issues/20
https://www.gpforums.co.nz/threads/261279-Gruul-s-Lair-o-O
We just simply didn't implement this fix for Hurtful Strike cuz we see it too overdone.
