### ISSUE TITLE
Melee Range in PvP compared to Hunters Shooting Range!

### ISSUE THREAD

**Issue by Fladomir** [SunwellWoW/Sunwell-TBC-Bugtracker#3679]
Description: 
Melee Range in PvP and especialy Warrios 

How it works: 
Im a Hunter and Melees can hit me while im in Shooting range.

How it should work: 
Melees shouldnt hit u while u are at Shooting range with normal attacks.

Source (you should point out proofs of your report, please give us some source): 
Pretty much every hunter had the same experience in PvP

**Comment by Azmoddan** [comment]
If you're reporting a bug, do it as you should:
a) what's the hunter shooting range?
b) what's the melee attack range?

c) what should be the hunter shooting range?
d) what should be the melee attack range?
+proofs.

**Comment by akrom23** [comment]
@Fladomir Screenshots, please.

**Comment by ahlens** [comment]
I've noticed the same while I was chased by Alliance Druid in cat form (+30% ms) and I was running away in Travel Form (+40%). I'm pretty sure I was out of his range. I will try to record that next time but I think this issue is worthing taking a deeper look into it. 

My latency is 45ms so I assume that is not the issue.

**Comment by vititus** [comment]
that's because hunter's range is bugged and noone's acknowledging it whatsoever.

They don't have a deadzone..

**Comment by Fladomir** [comment]
Pls explane your logic @vititus i wanna know how your statement even makes any sense

**Comment by Ibuprofeno** [comment]
> 
> 
> that's because hunter's range is bugged and noone's acknowledging it whatsoever.
> 
> They don't have a deadzone..

deadzone was removed in 2.3

**Comment by vititus** [comment]
> > that's because hunter's range is bugged and noone's acknowledging it whatsoever.
> > They don't have a deadzone..
> 
> deadzone was removed in 2.3

Afaik we're playing on 2.24

**Comment by Ibuprofeno** [comment]
> 
> 
> > > that's because hunter's range is bugged and noone's acknowledging it whatsoever.
> > > They don't have a deadzone..
> > 
> > 
> > deadzone was removed in 2.3
> 
> Afaik we're playing on 2.24

2.4.3 client means 2.4.3 mechanics. 2.0 is the content we're playing-

**Comment by akrom23** [comment]
@Fladomir Any news here? Got screenshots?

**Comment by akrom23** [comment]
No response.
