### ISSUE TITLE
Pet Bug unknown issue

### ISSUE THREAD

**Issue by Fladomir** [SunwellWoW/Sunwell-TBC-Bugtracker#3681]
Description: 
My Pet bugs out sometimes, often when im doin Bgs when that happens my pet cant use any abilities anymore and is not found as *Pet* in your abiltiy spellbook. Your Pet is still outside and can attack passiv stay everything but his learned abilities, I Tried everyhing from changing pets relogging deleting your cache and wtf nothing works. Only thing that works is to learn every ability from your pet new. When im in a dungeon or in a Bg i cant just quit and learn everything new.

Im Using the Pink shiny Tiger from Winterfell, his abilities are Claw, Bite, Dash, and i tried Prowl and Taunt both in the same result.

Im the Hunter Maou on the Alliance side if any Questions about this bug are there on your Side.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Therip22** [comment]
https://www.twitch.tv/videos/351772306## here is a video do not ignore this literally a class breaking bug

**Comment by akrom23** [comment]
@Therip22 Could you re-upload?
@Fladomir Got some screenshots?

**Comment by akrom23** [comment]
No response.
