### ISSUE TITLE
Shade of Aran - Adds have insane HP

### ISSUE THREAD

**Issue by Djdave89** [SunwellWoW/Sunwell-TBC-Bugtracker#3682]
Description: Shade of Aran's Water eles have 2.56 MIllion HP

How it works: Spawn with too high of health

How it should work: Adds should only have around ~13k HP, They should be killable/CCed depending on your comp.

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Shade_of_Aran

**Comment by ibogdandx** [comment]
Aran's adds pre-nerf in 2.0 should be unkillable and have double the HP value of the boss. They should be CC'ed .
Later on 2,1 Kharazan was nerfed and adds had about 20k  hp.
Watch pre-nerf kills on youtube from 9 years ago and you will see absolutely no raid killed them , they got CC'ed
Gamepedia shows the nerfed version of Kharazan.
