### ISSUE TITLE
[Important] Ethereum Prisons

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#3684]
Description: 
Now either it will spawn a mob who can drop some pretty desent things (blue rings and good greens) or a faction guy will spawn and give you 500 rep with his faction.
There are the following factions:
*Cenarion Expedition
*Consortium
*Keepers of Time
*Lower City
*The Sha'tar
*Sporeggar

The mobs who can spawn will drop a Ethereum Prisoner I.D. Tag witch you can deliver at the camp north of where you are and get 250 Consortium rep.

How it works: 
Ethereum Prisons dont respawn, they should respawn aproximatelly after 1 min.
Any of the spawn faction guys dont give any rep.
After killing spawn mob, you can greed and need items(rares, greens, **ID Tag**, but they will **not** end up in your bag.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Laharl23** [comment]
Can confirm everything he is saying. The quest chain is basically stopped at the Prison ID part and we cannot progress.

**Comment by bimbley** [comment]
I don't want to try and steal your show I just want to add a couple things to make sure the issues are crystal clear - this is more than just an issue for a quest, it's an object intended to be farmable in the game as well.

When opening an Ethereum Prison, one of two things will happen:
1. A miniboss will spawn that drops blues/greens and an Ethereum Prisoner I.D. Tag - these drop correctly but the bosses despawn almost immediately and the loot disappears with them.
2. A prisoner from a certain faction (The Consortium, Keepers of Time, Cenarion Expedition, Sha'tar, Lower City, and Sporeggar) will spawn and give nothing to the player as ZaoQ stated above. This is wrong as well - they are supposed to give 500 reputation with their faction to all members of the group of the person who opened the prison.

So the issues and fixes are:
1. Prisons don't respawn except for on server restart, they need respawn timers.
2. The minibosses' bodies despawn too quickly for a party to realistically roll on the loot and when the bosses despawn they take the loot with them.
3. The prisoners from the reputations need to cast a spell on the person who opened the prison that gives a partywide 500 rep with the reputation they're associated with.

**Comment by nickycakes** [comment]
can confirm, no rep from faction spawns, prison orbs dont respawn, and cant loot the bosses in a group (not sure if it despawned too fast or simply bugged)

**Comment by zepirothh** [comment]
can the staff please say they working on it nad say when it will be fixed

**Comment by zepirothh** [comment]
and No one assigned to it reedicules

**Comment by Nadiirr** [comment]
Added high prio:
Important for this to work.

**Comment by bimbley** [comment]
Hoping someone can assign this or give some sort of update it has been 4 days since having high priority label and the quest chain itself has been bugged for the entirety of server being out, it should be a quite easy fix with just the 3 changes i listed above

**Comment by Twistwarp** [comment]
I know this is labled as fixed, but as far as i know the prisons went active in 2.1, as it should come with all the other 2.1 content.

**Comment by ZaoQ** [comment]
Respawn seems to be broken. Doesnt respawn

**Comment by Bugadin** [comment]
So... if it's fixed, why don't you apply it? 4 days now

**Comment by Dootz** [comment]
will be fixed with next server update
