### ISSUE TITLE
[Warrior][Slam] Doesn't Proc Windfury.

### ISSUE THREAD

**Issue by Heftyarms** [SunwellWoW/Sunwell-TBC-Bugtracker#3685]
Description: While using the ability Slam as a Warrior, you should be able to have a 20% chance to proc Windfury if Windfury totem buff is applied. While testing over 500 Slams, there was not a single proc of Windfury recorded.

How it works: While casting Slam ability, you should have a 20% chance to proc Windfury if Windfury totem buff is applied. Since Slam resets the auto swing timer, it counts as an auto attack which allows the proc chance of Windfury. Through many testing not a single proc was recorded or seen.

How it should work: When the warrior casts Slam, you will have a 20% chance to proc Windfury, if Windfury totem is applied. Since Slam resets the auto attack timer, its the same as a regular auto hit which can proc Windfury, but does not here.

Source (you should point out proofs of your report, please give us some source): 
Testing Slam in Karazhan, over 10 dungeons, 500+ Slams recorded have not proced Windfury once. Even saving up to 100 rage to spam Slam for forced proc, nothing was shown.

**Comment by Dusyagonemad** [comment]
Slam shouldn't proc WF.

https://blue.mmo-champion.com/topic/67506-windfury-totem-nerf-necessary/
blue post:
"With the release of The Burning Crusade, we had intended Windfury Totem to only work with normal auto-attacks and “on next swing” abilities such as Heroic Strike and Cleave. We uncovered the reason this fix did not work, and it was corrected with the Windfury Totem hotfix this week. **At this time, Slam is intended to not work with Windfury Totem. We have no plans to return it to working with Windfury Totem.**"

http://wowwiki.wikia.com/wiki/Windfury_Totem?oldid=1431588
"Also, the totem acts in the same manner as Sword Specialization: It will ONLY trigger on white (auto-attack) swings, and cannot trigger off itself. "

https://www.mmo-champion.com/threads/603849-sword-spec-and-windfury
"Slam does not proc Windfury."
