### ISSUE TITLE
Beast Lord 4 part not buffing pet

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#3688]
4 part giving 600arpen after KC is not buffing pet, it should gives arpen to the pet aswell.
His damages are not changing before arpen and after arpen buffs.

**Comment by primeropein** [comment]
No it should not give arpen to the pet

**Comment by YoshGit** [comment]
Pet should also receive arp as stated by the tooltip
