### ISSUE TITLE
NPC/creature and weapons during combat

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#369]
Decription: All NPCs/mobs that use weapons treat their weapons as if they are 1handed.

How it works: All NPCs/creatures that use weapons treat their weapons as if they are 1 handed, for example Bonechewer Destroyer that wields a 2h axe uses it in his main hand only.

How it should work: If NPC/creature is wielding a 2handed axe/sword/mace etc it should use both hands in same manner as players do. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Issue present only for dbc items missing from database, should be resolved for most items, please re-test creature presented in ticket after PTR update, closing

**Comment by Silroth** [comment]
Working properly now.
