### ISSUE TITLE
Mage Talent: Please fix Arcane Concentration proc chance for Arcane Missile ticks

### ISSUE THREAD

**Issue by grand-lotus-iroh** [SunwellWoW/Sunwell-TBC-Bugtracker#3691]
Channeling Arcane Missile **does not** proc Arcane Concentration Clearcasting state... it should. Each Arcane Missile bolt tick should have a 2% to 10% chance on spell hit to proc Arcane Concentration Clearcasting state.

Arcane Concentration Clearcasting state means your next spellcast will be 100% reduced mana (free spell). Please fix broken code.

**Comment by Dusyagonemad** [comment]
It should work at cast, not on each hit.

http://wowwiki.wikia.com/wiki/Arcane_Concentration?oldid=1432055
"Unlike "on spell hit" effects, Arcane Concentration cannot proc off each hit of an Arcane Missiles' bolt, but only off the initial hit of AM itself."

https://wow.gamepedia.com/Talk:Arcane_Missiles
"-Clearcasting can only proc on arcane missiles at the moment before the first missile where the mana is consumed, NOT on each missile individually."

You can see proc only on first hit here:
https://www.youtube.com/watch?v=c2RtyFh5TnE
