### ISSUE TITLE
Bestial Wrath when i dismount

### ISSUE THREAD

**Issue by LadyAlicja** [SunwellWoW/Sunwell-TBC-Bugtracker#3692]
Description: 
When i dismount i get bestial wrath bonus, but it dissapear after 3-4 sec (and dont take the cd)

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_122018_225502](https://user-images.githubusercontent.com/33720391/50313116-acb4eb00-04aa-11e9-8a9e-4b7d247d8db0.jpg)

**Comment by ozzmann** [comment]
Ive had the same problem alot.

**Comment by akrom23** [comment]
@Flowerlady @ozzmann Show me your combat log and auras on your pet.
I believe that you mounted under the effect of Bestial Wrath.

**Comment by akrom23** [comment]
No response.
