### ISSUE TITLE
Stoneclaw Totem is not working

### ISSUE THREAD

**Issue by ga-felix** [SunwellWoW/Sunwell-TBC-Bugtracker#3693]
Description: Stoneclaw Totem is not working

How it works: Stoneclaw Totem taunt animation shows up, however the enemy doesn't get taunted at all.

How it should work: Stoneclaw Totem should taunt the enemy to attack It and also when the enemy attacks Stoneclaw Totem there's a chance to the mob get stunned.

Source (you should point out proofs of your report, please give us some source): 
https://i.imgur.com/s9S5fv8.jpg

https://tbc-twinhead.twinstar.cz/?spell=5730

I tested many times and the Totem isn't working.

**Comment by notsofamous** [comment]
It's not an actual taunt like a warrior taunt. It just does a high amount of threat every time it pulses.

**Comment by ga-felix** [comment]
I tested It many times and It's bugged, for sure. In another experiment I didn't attack the mob and the totem was not able to get the aggro.

**Comment by akrom23** [comment]
Works fine.
