### ISSUE TITLE
Summoned by wrong faction.

### ISSUE THREAD

**Issue by zanthed1** [SunwellWoW/Sunwell-TBC-Bugtracker#3696]
Description: I was running up to the stone of Cenarion dungeons and I was targeted by an enemy faction player as his summon cast was ending (I assume) and received a summon from him. 

How it works: You can summon the enemy faction.

How it should work: You should not be able to summon the enemy faction.

Source (you should point out proofs of your report, please give us some source): Have not tried to replicate it and failed to take a screenshot because I'm a monkey. Should be able to replicate it by targeting someone in group and changing it.

**Comment by akrom23** [comment]
@zanthed1 Got any screenshot? More info?

**Comment by badmannerkid** [comment]
yeah, this can happen. ill get a video doing it if i remember.

can target an enemy faction while you've already casted summon on your ally faction. once the person clicks after you change target from ally to enemy the summon will go through on the enemy. pretty funny gank setup but def shouldn't be happening.

also you guys must make warlock summoning available in raids and dungeons, please
