### ISSUE TITLE
Pure Water Nodes Respawn Bugged

### ISSUE THREAD

**Issue by SlizeTBC** [SunwellWoW/Sunwell-TBC-Bugtracker#3697]
Description: After fishing Pure Water Nodes in Nagrand, normal Fish School's, like "Mudfisch School" appear instead of Pure Water again.

How it should work: Normally Pure Water should spawn over and over again instead of rotating with normal Fish Schools, making it rlly hard to farm Primal Water.

**Comment by AshhSunwell** [comment]
No they should not, it was only ever like this on servers like Warmane's Outland. Which caused a terribly flooded market. They should be a % to spawn after normal schools.

**Comment by Daniehwtf** [comment]
Ok, just modify "primal air" too, if dont want flooded market. But the people can farm "primal air" easy with enginer, and fishing is REALLY SHIT.  Only 4 spots for pure water for all ppl in server with bad respawn.

**Comment by notsofamous** [comment]
@Daniehwtf 

There are 20 spawns for pure water, respawn for fishing schools are 3-10 min. Engineering clouds have 1 hour respawn.

**Comment by SlizeTBC** [comment]
Yea you cant farm Primal Air that easily, Windy Clouds got 45min respawn timer.
