### ISSUE TITLE
[Hunter][Pets] Weird pet-water behaviour

### ISSUE THREAD

**Issue by TheKapral** [SunwellWoW/Sunwell-TBC-Bugtracker#370]
Decription: pet doesn't interract with water surface

How it works: pet doesn't want to go in the water/only gets out of water when player does/ doesn't want to attack targets unless they come out to the surface etc. More info in videos linked below.

Source YT links:
1. https://youtu.be/Zm1jR0FT6mM
2. https://youtu.be/LutQyF_isuU
3. https://youtu.be/qXr08rHGF2M
4. https://youtu.be/3dbxhvv08Xs

**Comment by TheKapral** [comment]
UPD
1. https://youtu.be/aKcMHFsds3Q
2. https://youtu.be/q0sunIfDIUk
3. https://youtu.be/aA6WaLH0LqM

**Comment by lukaasm** [comment]
Fix is not live on ptr yet

**Comment by akrom23** [comment]
@TheKapral Test now.

**Comment by TheKapral** [comment]
Works fine
