### ISSUE TITLE
Amplify Curse Bugged

### ISSUE THREAD

**Issue by Zombiejesus420** [SunwellWoW/Sunwell-TBC-Bugtracker#3701]
Description: 
I think amplify curse bugs out when used with CoA ive tried 50+ times to no avail please help

How it works: 
Amplify curse will cause Coa to always hit for 1044 even on lvl 1 mobs that shouldnt be resisting. 

How it should work:
Amplify curse should give a 50% damage increase to CoA

Source (you should point out proofs of your report, please give us some source):

**Comment by Gelori** [comment]
@Zombiejesus420 No screens, no proofs wtf is this? Detail please

**Comment by akrom23** [comment]
Tested - works okay.
