### ISSUE TITLE
Hunter pet abilities stop working after playing BG's

### ISSUE THREAD

**Issue by kinghunterx** [SunwellWoW/Sunwell-TBC-Bugtracker#3702]
Description: 
when you play bgs sometimes they bug your pet and it will never cast its abilities even if you click on them or have them on auto mode

How it works: 

when you play bgs sometimes they bug your pet and it will never cast its abilities even if you click on them or have them on auto mode

How it should work: 
they doesnt bug like this, and the only way to fix it is to reset your pet talents via pet trainer

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@kinghunterx Got some screenshots?

**Comment by akrom23** [comment]
#3604
#3681

**Comment by kinghunterx** [comment]
XD 2 months late nice developer, ye heres the ss: https://cdn.discordapp.com/attachments/357996396575588352/540656262757613608/video-1538732358.mp4

**Comment by akrom23** [comment]
No response.
