### ISSUE TITLE
Hula Girl Doll

### ISSUE THREAD

**Issue by mintnb** [SunwellWoW/Sunwell-TBC-Bugtracker#3703]
Griftah - a vendor in the Lower City of Shattrath doesn't seem to be selling the Hula Girl Doll.

**Comment by NeonicSupersonic** [comment]
Plx fix i need engi epic mount

**Comment by Dootz** [comment]
It will be added later when we reach patch 2.3

**Comment by RealSlyGuy** [comment]
It is still not there! Will this patch be coming soon? ^.^
