### ISSUE TITLE
[Druid] Swift Flight Form Quest not obtainable

### ISSUE THREAD

**Issue by JonasJacober** [SunwellWoW/Sunwell-TBC-Bugtracker#3704]
Description: Although riding skill 300 and lvl 70 was obtained, no trainer offers the Quest Morthis Whisperwing. (Every Druid trainer should)

How it works:  It doesnt.

How it should work:   Morthis Whisperwing is the start of the questline for the Druid Swift Flight Form. You need to have riding skill of 300 before you can receive this quest. Any druid trainer will offer you this quest once you meet the prerequisites. Loganaar, in Moonglade is the one most often referred to, though.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Swift_Flight_Form_quest_chain
http://wowwiki.wikia.com/wiki/Quest:Morthis_Whisperwing

**Comment by Azathothh** [comment]
Hello, it's not available yet because it was added in patch 2.1.0 - that's when we're planning to enable it.



http://wowwiki.wikia.com/wiki/Anzu
Patch 2.1.0 (22-May-2007): Added.
