### ISSUE TITLE
[Quest] Ethereum Secrets Uncompletable

### ISSUE THREAD

**Issue by bimbley** [SunwellWoW/Sunwell-TBC-Bugtracker#3705]
Description: 
The Ethereum Prisons that are required to open for the quest "Ethereum Secrets" (and also that are opened for reputation gains) DO NOT respawn.

How it works: 
When server restarts, Ethereum Prisons likely spawn, and once opened, they do not ever respawn.

How it should work: 
Ethereum prisons need to respawn ~3 minutes after being opened.

Source (you should point out proofs of your report, please give us some source):

**Comment by ZaoQ** [comment]
#3684 already reported by me :))

**Comment by MadderThenMad** [comment]
Actually this quest is should be available on this patch.
