### ISSUE TITLE
Rogue 41 point talent--Surprise Attacks

### ISSUE THREAD

**Issue by Feorblade** [SunwellWoW/Sunwell-TBC-Bugtracker#3706]
Description: 
Half of the 41 point talent isn't working for rogues. I haven't tested the portion which buffs damage because I don't have enough gold to do so but I'm hoping you guys will check the numbers for me and every other person playing rogue

How it works: 

Rogue finishing moves are being dodged by players / mobs
How it should work: 

The talent should prevent finishing moves from ever being dodged
Source (you should point out proofs of your report, please give us some source): 
 
Here's some screenshots I hope you find them useful.

https://i.imgur.com/FTcvx5b.png
https://i.imgur.com/FTcvx5b.png
https://imgur.com/XhwWsfx

**Comment by ZaoQ** [comment]
Still bugged guys
