### ISSUE TITLE
Quest Spectrecles

### ISSUE THREAD

**Issue by plankjirven** [SunwellWoW/Sunwell-TBC-Bugtracker#3709]
Description: 
Chief Apothecary Hildagard at Shadowmoon Village in Shadowmoon Valley wants you to slay 12 Shadowmoon Zealots. 

How it works: 
Equip the item Spectrecles and  you will be able to see the ghosts in shadowmoon village then you simply kill 12 of them. BUT as a hunter your pet wont help you kill them. So i have to kill them with melee.

How it should work: 
My pet should be able to help me kill them

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=10625/spectrecles

**Comment by doomnyx** [comment]
Same for warlock.

**Comment by Azathothh** [comment]
According to the comments on wowhead (link that you've posted) pets weren't able to see them during tbc - it was changed with wotlk.
If you have any proofs that pets should see them and help you - please add them.

**Comment by nickycakes** [comment]
@Azathothh according to a comment https://www.wowhead.com/item=30719/spectrecles#comments here, they were able to be replaced at least in 2.0.6
