### ISSUE TITLE
[Quest] Forge Camp: Annihilated

### ISSUE THREAD

**Issue by TheKapral** [SunwellWoW/Sunwell-TBC-Bugtracker#371]
Decription:  quest [[Forge Camp: Annihilated]](https://tbc-twinhead.twinstar.cz/?quest=10011) doesn't work

How it works: you get the quest item [[Fel Cannon Activator]](https://wotlk-twinhead.twinstar.cz/?item=25770)/[[Fel Cannon Activator]](https://wotlk-twinhead.twinstar.cz/?item=25771) and its says 'you have no target' when you attempt to use it

How it should work: you get the quest item [[Fel Cannon Activator]](https://wotlk-twinhead.twinstar.cz/?item=25770)/[[Fel Cannon Activator]](https://wotlk-twinhead.twinstar.cz/?item=25771) and use it on [[Fel Cannon:Hate]](https://s19.postimg.cc/rd48ej4gx/Wo_WScrn_Shot_091218_150747.jpg)/[[Fel Cannon:Fear]](https://s19.postimg.cc/mr8467dsx/Wo_WScrn_Shot_091218_152942.jpg) for it to blast the demon gate or whatever.

**Comment by notsofamous** [comment]
Duplicate: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/300
