### ISSUE TITLE
Righteous Fury Threat

### ISSUE THREAD

**Issue by Gamldor73** [SunwellWoW/Sunwell-TBC-Bugtracker#3713]
Description: 
Righteous Fury buff is displaying it's increasing holy threat generated by 60%. Tooltip shows 90%, also have imp RF

How it works: 
RF should be applying a base 90% holy dmg to threat coefficient. Currently showing 60%

How it should work: 
RF should be applying a base 90% holy dmg to threat coefficient, ontop of the additional threat generated for imp RF

Source (you should point out proofs of your report, please give us some source): 
![rf buff](https://user-images.githubusercontent.com/46053751/50353493-757c2380-0516-11e9-89ca-b7a483294c7e.PNG)

**Comment by Xithus** [comment]
Just saw this and can confirm. With 3/3 improved righteous fury the buff button when hovering over says increases by 90%, but when you buff yourself and hover over the buff at the top it just shows 60% like the above screen shot.

Not sure if its really 60% or just a tooltip issue, but needs to be verified either way.

**Comment by Mikov1605** [comment]
Worked like that on TBC. Example:
Frostbolt tooltip (with permafrost 10% movement decrease) - 50% slower
Basic frostbolt tooltip(w/o talent) - 40% 
If You hover over a enemy hit by frostbolt (both with or w/o talent) You see 40%, altough with talent the mob is rly moving 50% slower

If You hover over a BUFF/debuff, it shows the stats w/o any improvements. Dont worry, they actually work.
It is a Blizzard issue from TBC, was fixed on cata sadly
