### ISSUE TITLE
Rogue pickpocketing puts out of stealth!

### ISSUE THREAD

**Issue by blackabbath** [SunwellWoW/Sunwell-TBC-Bugtracker#3714]
Description: 
Often when rogue is stealthed and try to empty mobs pockets, it resists somehow and bring rogue out of stealth. Sometimes even mobs which are lower than 30 levels of me can see me from behind!!!

Really annoying thing, THIS SHOULDN'T BE!

How it works: 
https://gyazo.com/9ce91a71bd22ae39e6a00e7d6a42ebe4

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by ahlens** [comment]
I think it can be resisted by mobs.

There is a [comment from patch 3.1.3](https://www.wowhead.com/spell=921/pick-pocket#comments) by Xandyxr regarding your issue.
