### ISSUE TITLE
System messages spam

### ISSUE THREAD

**Issue by blackabbath** [SunwellWoW/Sunwell-TBC-Bugtracker#3716]
Description: 
Many messages like someone queued arena or joined it, battlegrounds begin are unnecessary - why whole realm should know about it? 
It's annoying, please, remove/hide them.

How it works: 
https://gyazo.com/21b30af5f7e2418a97c404351db15442

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Caydan** [comment]
Yes, it's pretty annoying. Please remove it or make it optional.

**Comment by Nghedi** [comment]
.acc bgann 
disables the announcements

**Comment by Azathothh** [comment]
Like Nghedi said you can enable/disable it with .acc bgann command

**Comment by blackabbath** [comment]
now it started to spam again and _.acc bgann_ doesn't work anymore 8(((
i got message _'There is no such subcommand'_

**Comment by Azathothh** [comment]
Hello.
We've changed these commands a bit so now arena announcements can be disabled, but bg announcements stay enabled if someone wants that.
 .pvpinfo arena - Allows to enable/disable arena announces display (account wide).
.pvpinfo bg - Allows to enable/disable battleground announces display (account wide).
