### ISSUE TITLE
Wind Serpent cant get Greater Blessings

### ISSUE THREAD

**Issue by primeropein** [SunwellWoW/Sunwell-TBC-Bugtracker#3718]
Description: 
Wind Serpent (Hunter pet) doesnt get greater blessings

How it works: 
When paladin casts greater blessing, nothing happens, Small ones does work

How it should work: 
Great blessings on wind serpents should count as warrior and all pets + warriors should get the buff

Source (you should point out proofs of your report, please give us some source): 
I dunno not gonna record a clip for this, just how it is

**Comment by primeropein** [comment]
PS greater DOES work with ravager

**Comment by akrom23** [comment]
Works fine.
@primeropein Send screenshots.

**Comment by akrom23** [comment]
No response.
