### ISSUE TITLE
[Hunter][Pets] Revive pet

### ISSUE THREAD

**Issue by TheKapral** [SunwellWoW/Sunwell-TBC-Bugtracker#372]
Decription: cannot revive pet

How it works: it doesn't.

How it should work: it should

Source (you should point out proofs of your report, please give us some source): 
1. https://s19.postimg.cc/b3e2bcr5f/Wo_WScrn_Shot_091218_153609.jpg
2. https://s19.postimg.cc/r1ms1i8ir/Wo_WScrn_Shot_091218_153611.jpg
3. https://s19.postimg.cc/i6lxr0elf/Wo_WScrn_Shot_091218_153629.jpg

**Comment by notsofamous** [comment]
duplicate: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/353

**Comment by Kokaina** [comment]
Duplicate.
