### ISSUE TITLE
Bugg in First Aid in spellbook

### ISSUE THREAD

**Issue by Nord11** [SunwellWoW/Sunwell-TBC-Bugtracker#3720]
Description: 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Nord11** [comment]
Good day! Studied first aid (Now i have skill 325), but in my spellbook 4 icons: primary, secondary and so... on to master. 
Can you  remove extra icons from the spellbook?
I try relog and delete cash, but it not help.
I can't write on forum...
I can't delete first aid.
I have screen shot can send on email adress ore watsup if it can.

Help plz.

**Comment by Nord11** [comment]
p.s. my nick in wow Nordwar

**Comment by dredd-sunwell** [comment]
This happens on many characters.

**Comment by Dootz** [comment]
Hi, do this issue persist? Some time ago we've removed some spells from players that shouldn't be learned.
