### ISSUE TITLE
Bubbly Fissures doesn't work

### ISSUE THREAD

**Issue by blackabbath** [SunwellWoW/Sunwell-TBC-Bugtracker#3723]
Description: 
Bubbly Fissures doesn't work around the world

How it works: 
Nothing happens

How it should work: 
When character swip up to a fissure, he can restore his breath for a while

Source (you should point out proofs of your report, please give us some source):

**Comment by blackabbath** [comment]
are you going to fix it?

**Comment by Trentone** [comment]
Will consider https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2182 the first issue and post the fix there.
