### ISSUE TITLE
Unable to complete Cuergo's Gold quest

### ISSUE THREAD

**Issue by blackabbath** [SunwellWoW/Sunwell-TBC-Bugtracker#3727]
Description: 
Unable to complete Cuergo's Gold quest

How it works: 
After activating quest object 'Inconspicious Landmark', a chest 'Pirate's Treasures!' appears nearby. That's all. Of course it can't be done.
https://i.gyazo.com/60229dab6ff5ecfd2ba9496da6e0d6ea.png

How it should work: 
When activating quest object 'Inconspicious Landmark' , bunch of mobs like Treasure Hunting Pirate, Treasure Hunting Swashbuckler, Treasure Hunting Buccaneer should appear and attack a character. When kill'em, 'Cuergo's Key' obtained. So you can use it on 'Pirate's Treasures!' and get reward.

Source (you should point out proofs of your report, please give us some source):

**Comment by babno** [comment]
They spawn up the hill, run towards the landmark, but will despawn if you dont run forward to meet and engage them.

**Comment by blackabbath** [comment]
quest doesn't work **as it should**

**Comment by babno** [comment]
I didn't say it did work as it should, but your description is inaccurate. An accurate description
1. Helps them diagnosis and fix the issue
2. Helps other people who are trying to do the quest.

**Comment by blackabbath** [comment]
i think you should to read, because my description of this bug is exceptional and there are nothing to add more. comlpete it if i'm wrong

**Comment by babno** [comment]
![image](https://user-images.githubusercontent.com/244626/51655864-7fa59d80-1f6c-11e9-8307-33e3e386740b.png)
