### ISSUE TITLE
Cooking Trainer in Shatt

### ISSUE THREAD

**Issue by AshhSunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#3735]
Description: Kylene the cooking trainer is missing the recipies Stewed Trout, Fisherman's Feast, & Hot Buttered Trout

How it works: She appears to be a trainer however she opens a vendor tab with alcohol. 

How it should work: She should be the same she is now, however she should open a NPC interaction page like normal trainers who are also vendors & she can train you those 3 recipes. 

Source (you should point out proofs of your report, please give us some source): https://wow.gamepedia.com/Kylene In patch 2.3 she was added as a cooking trainer who ONLY trained these 3

**Comment by dredd-sunwell** [comment]
We have 2.0 content

**Comment by AshhSunwell** [comment]
Okay do me & favor & remove that portal to CoT in Shatt. K thx. 2.0 btw

**Comment by AshhSunwell** [comment]
Oh also make Nightfin soup stack with Well Fed since it's 2.0 content
