### ISSUE TITLE
Feral charges immobilize breaks on damage...

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#3737]
Description: 
it breaks on damage

How it works: 
the immobilize feature breaks on almost any damage

How it should work: 
it should work like improved hamstring, and other immobilize effects and not break on damage, this is terrible for both pvp and pve. 

Source (you should point out proofs of your report, please give us some source): 
I think its pretty obviously broken but if the devs dont believe me I can go digging around for proofs >_>

**Comment by 0vertime** [comment]
Noticed this as well but forgot to report.
