### ISSUE TITLE
(Shaman) Grounding totem is broken [high priority, pvp impossible with that bug]

### ISSUE THREAD

**Issue by Mowmiojcze** [SunwellWoW/Sunwell-TBC-Bugtracker#3738]
Description: 
Grounding totem is broken and it seems be not working. Grounding totem is supposed to consume a targeted spell and redirect it from the player to the totem.

How it works: 
**In fact, Grounding totem doesn't consume any skill at all and it stands all the time upon my feet. Enemy can cast frostbolts one by one despite the grounding totem is standing next to me.**
 Hardly ever, but it happens that grounding will work properly (but hardly ever, mostly it doesnt work at all).
It's very painful, especially playing PVP. I cannot even protect myself against some poly or sillence from mage and other stuff.

How it should work: 

Grounding totem is supposed to redirect incoming harmful spell cast on a nearby party member to itself, destroying the totem.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
#3022
