### ISSUE TITLE
Rip (Feral)

### ISSUE THREAD

**Issue by Aftershokx** [SunwellWoW/Sunwell-TBC-Bugtracker#3741]
Description: 
Rip

How it works: 
damage doesn't increasing by attack power
https://imgur.com/uIEUUu4
https://imgur.com/UmnogCV

How it should work: 
Should add bonus damage

Source (you should point out proofs of your report, please give us some source):

**Comment by baade123** [comment]
yikes i d k how i didnt notice this either but i just tested and he is right

**Comment by Aftershokx** [comment]
WoW Icon 16x16 Patch 1.12.0 (22-Aug-2006): Lesser potency Rips will no longer overwrite greater potency ones. Attack Power is now factored in for Rip, at a rate of 6% AP per combo point from 1 to 4 combo points, and then 24% AP again for 5 combo points.
http://wowwiki.wikia.com/wiki/Rip

**Comment by mjk6994** [comment]
h e l l o?

**Comment by akrom23** [comment]
#4012
