### ISSUE TITLE
Too Many Chinks

### ISSUE THREAD

**Issue by AshiyrHunter** [SunwellWoW/Sunwell-TBC-Bugtracker#3744]
Description: There are too many Chinese cock suckers on this server.

How it works:  I just had 3 of them following me around everywhere, tagging mobs infront of me - NINJA SKINNING the mobs that I tagged. I reported this to GMs and they did absolutely nothing. Useless fucking punks.

How it should work: Harassment and ninja skinning should not be allowed as it's called GRIEFING and is a punishable offence on EVERY other decent private server.

Source (you should point out proofs of your report, please give us some source): The response I got from the very unprofessional GM was VIA ingame mail to "report it to the bug tracker" so here I am.......unbelievable.

**Comment by Azmoddan** [comment]
And ganking low-lvl players isn't called GRIEFING? Learn to play, be a man. There's nothing to report.
@Dootz 
@SunwellTracker

**Comment by AshiyrHunter** [comment]
This is far different than LOW LVL gankers you stunned cunt, this is SAME FACTION GRIEFING. When I can't even grind mobs because I have 3 chinese hunters running ahead of me tagging everything. THAT IS FAR FROM LOW LEVEL GANKING. Pull your fucking head out of your ass.

**Comment by grand-lotus-iroh** [comment]
+1 for humor - thanks for making everyone in my discord server laugh
