### ISSUE TITLE
Druid Feral Charge not interrupting

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#3746]
Should also interrupt, actually not the case or at least not the case on the whirlwind boss in arcatraz after her whirlwind she casts a heal, the charge is supposed to interrupt it, not working. So I guess the charge is not interrupting.

**Comment by baade123** [comment]
well i can confirm it interrupts  some stuff lol maybe not that tho ^_^

**Comment by zapsuu** [comment]
Few days ago when I was on this boss interrupt from feral charge works pretty well.
