### ISSUE TITLE
[Spell] Dismounting Blast etc

### ISSUE THREAD

**Issue by Dootz** [SunwellWoW/Sunwell-TBC-Bugtracker#375]
Decription: 

Doesn't dismount players.

How it works: 

NPC casts a spell on player on mount -> Player is not dismounted

How it should work: 

Should dismount player

Spell ID: for example  18396, 18395, 14890

**Comment by akrom23** [comment]
@notsofamous Give us some screenshots and .gps info about that.

**Comment by akrom23** [comment]
@notsofamous Already fixed. Not related to this one.

**Comment by notsofamous** [comment]
Works
