### ISSUE TITLE
 Pattern: Bolt of Soulcloth Missing

### ISSUE THREAD

**Issue by sabo92** [SunwellWoW/Sunwell-TBC-Bugtracker#3750]
Description:  The Pattern is not avaible at the vendor

How it works:  there is no pattern at the verdors who should sell it

How it should work:  It should be there the pattern

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?item=21894

**Comment by ZaoQ** [comment]
I bought one from Garadar vendor

**Comment by sabo92** [comment]
do you play horde ?

**Comment by ZaoQ** [comment]
yeah, i couldnt have bought it from Garadar vendor if i was alliance

**Comment by Azathothh** [comment]
Recipe added to Borto in Nagrand and Neii in Exodar (keep in mind it's limited supply)
