### ISSUE TITLE
Training points of pet for each lvl starting from the first

### ISSUE THREAD

**Issue by Holeheart** [SunwellWoW/Sunwell-TBC-Bugtracker#3752]
Description: 
Training points max should be lvl (70) x loyality lvl -1 (5) = 350 points. here if I tame lvl 25 pet, he loses 25 training points he could have.

How it works: 
tamed pets don't recive points for lvles they already are on.

How it should work: 
every pet should be able to recieve 350 of training points total.

Source (you should point out proofs of your report, please give us some source): 
http://et.worldofwarcraft.wikia.com/wiki/Training_point
quote: Maximum available training points are not affected by the level at which the pet was tamed.

**Comment by akrom23** [comment]
And where is the bug? You already quoted that 

> training points **are not affected** by the level

Only if you raise your pet's loyalty level, you will get this bonus.

If you want max training points, just go to pet trainer and reset talents.

**Comment by Holeheart** [comment]
yes. and that quote means that if u tame lvl 25 pet, the max points are not affected by -25 points the pet could have.

**Comment by Holeheart** [comment]
if u tame lvl 50 pet, and ur max training point total is 50 less, it is "affected" by lvl

**Comment by akrom23** [comment]
Just no.
https://www.wowhead.com/forums&topic=21067#p187086
https://forum.elysium-project.org/topic/55012-pets-training-points/?tab=comments#comment-441203
Formula is:

> (Level)*(Loyalty-1)

A new pet is on the lowest rank of loyalty, so pet have 0 TP (if have no default skills).
