### ISSUE TITLE
Rupture (Rogue)

### ISSUE THREAD

**Issue by Aftershokx** [SunwellWoW/Sunwell-TBC-Bugtracker#3753]
Description: 
Rupture does not stacking with AP

How it works: 
https://imgur.com/a/kYu69Pm
https://imgur.com/a/kEEiRqJ

How it should work: 
Should stack with AP

Source (you should point out proofs of your report, please give us some source):

**Comment by dredd-sunwell** [comment]
No proof?

**Comment by Aftershokx** [comment]
RuptureRank 7
Rupture
25 energy
Finishing move that causes damage over time, increased by your attack power. Lasts longer per combo point:1 point : 324 damage over 8 secs2 points: 460 damage over 10 secs3 points: 618 damage over 12 secs4 points: 798 damage over 14 secs5 points: 1000 damage over 16 secs
the formula is cp*0.24 AP if i remember correctly

**Comment by Aftershokx** [comment]
Formula for Rupture rank7:
1pt = Attack Power * 0.04 + 324
2pt = Attack Power * 0.10 + 460
3pt = Attack Power * 0.18 + 618
4pt = Attack Power * 0.21 + 798
5pt = Attack Power * 0.24 + 1000
https://www.wowhead.com/spell=1943/rupture#comments
