### ISSUE TITLE
Healing Focus

### ISSUE THREAD

**Issue by Niar91** [SunwellWoW/Sunwell-TBC-Bugtracker#3754]
Description:  During a Karazan clearn whenever a boss does some sort of AoE it's always a 100% push-back even with the talent, unsure if it should work that way but doubt when it comes to AoE damage. Had problems during Netherspite and Nightbane encounter. 

How it works: The talent should reduce the chance of push-backs on your healing spells by 70% when 5/5. 

How it should work: Like above, reduce the chances of being pushed back on your spells from any source of damage taken.

Source (you should point out proofs of your report, please give us some source): From the damage i've taken during Karazhan etc it has always been push-back damage even with the talent at 5/5.

**Comment by akrom23** [comment]
Only bugged with AoE damage?

**Comment by Niar91** [comment]
Feels like only AoE yes.

**Comment by akrom23** [comment]
Tell me what's your main healing spell that works bad here.

**Comment by Niar91** [comment]
All of them, Chain Heal, Lesser Healing wave, and Healing Wave, none recive the push-back benifits from the talent.

**Comment by akrom23** [comment]
Tested against druid's hurricane.
W/o talent:
![wowscrnshot_011819_101548](https://user-images.githubusercontent.com/1035215/51377153-7484e480-1b0a-11e9-9635-357f3b82c62f.jpg)
![wowscrnshot_011819_101549](https://user-images.githubusercontent.com/1035215/51377154-751d7b00-1b0a-11e9-8278-7f818d98d720.jpg)
![wowscrnshot_011819_101550](https://user-images.githubusercontent.com/1035215/51377155-751d7b00-1b0a-11e9-8c0d-44932efc626a.jpg)

With talent:
![wowscrnshot_011819_101627](https://user-images.githubusercontent.com/1035215/51377189-8bc3d200-1b0a-11e9-80f3-334581f49545.jpg)
![wowscrnshot_011819_101646](https://user-images.githubusercontent.com/1035215/51377190-8c5c6880-1b0a-11e9-944f-3507406ad11d.jpg)
![wowscrnshot_011819_101649](https://user-images.githubusercontent.com/1035215/51377191-8c5c6880-1b0a-11e9-92a0-932d37f6bc10.jpg)

Works fine.

**Comment by Niar91** [comment]
Didn't work at the Netherspite Encounter in Karazhan and soem other instances.

**Comment by akrom23** [comment]
With talent:
![wowscrnshot_011819_154635](https://user-images.githubusercontent.com/1035215/51393594-59c96480-1b38-11e9-90a4-9e842729a6c5.jpg)
![wowscrnshot_011819_154640](https://user-images.githubusercontent.com/1035215/51393595-59c96480-1b38-11e9-8adf-439f4ebd903f.jpg)
![wowscrnshot_011819_154645](https://user-images.githubusercontent.com/1035215/51393596-59c96480-1b38-11e9-8fba-a0a13c65d166.jpg)

**Comment by Niar91** [comment]
Strange, according to what i've seen with the talent 5/5 it was 100% push-back on any spell on AoE encounters.
