### ISSUE TITLE
my pet goteen lost

### ISSUE THREAD

**Issue by FreeGame123** [SunwellWoW/Sunwell-TBC-Bugtracker#3755]
Description: im svap pet in stable master and my second pet just goteen lost

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by FreeGame123** [comment]
i have pet dont Dismuiss my pet and try to swap with pet who stay in stable and this pet who stay in stable just go out.... im use relog /reload ui  and nothink now i have only 1 pet help me plsss. i need my pet

**Comment by dredd-sunwell** [comment]
It happens to some players
