### ISSUE TITLE
[Item] Recipe: Great Rage Potion is not being sold

### ISSUE THREAD

**Issue by nimeral** [SunwellWoW/Sunwell-TBC-Bugtracker#3760]
Description: Recipe: Great Rage Potion is not being sold

How it works: Ulthir in Darnassus does not sell Recipe: Great Rage Potion

How it should work: should be in stock

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/item=5643/recipe-great-rage-potion#comments

Might be a limited stock, but I checked a few times and it was never there. Don't think there're many people running around Darnassus, buying minor recipes

**Comment by Vaanx** [comment]
This needs fixed. The price of Gromsblood is through the roof making the only option to pay 2-3g per rage potion.
