### ISSUE TITLE
Snapshot for hunters

### ISSUE THREAD

**Issue by flapse32** [SunwellWoW/Sunwell-TBC-Bugtracker#3762]
Description: Basicly Trinket or Racial or Talents that multiply ur dmg by a %, will not work in the air or when its being casted while its up. So lets say trinket with AP is up and i cast Aimedshot/Autoshot/Steadyshot, and the AP boost is over when its in the air or middle of my cast. The AP buff will not work wich it should. Since snapshot is a thing in TBC.

How it works: Dosent snapshot aimedshot/Steady shot/ Autoshot

How it should work: It should just snapshot as i described earlier.

Source (you should point out proofs of your report, please give us some source): Dont have a source of this. But i know for a fact most classes on the server already have a working snapshot function but hunters dont.  Like shaman can cast earth shield with full SP gear on and it will give the bonus healing even when he change back the gear to lets say agility with 0 SP.

**Comment by akrom23** [comment]
I've never heard about it :)
Damage is calculated only once - on spell launch (when cast is over) - this is blizzlike.
About earth shield - amount of heal is already calculated on aura apply. This is not kind of snapshot - just a custom script :)

**Comment by flapse32** [comment]
But thats not true at all, when casting aimedshot with CD's/Trinket buff up and it ends while u casting it. it will land the dmg without any buffs if that makes sense. Snapshot is when you calculate the timing so when there is 1 sec left on your dmg multipliers  (Trinket/CD's) You cast a ability and it will do the dmg as if the trinket was up even tho it was not up when it lands. Snapshot was pretty common mechanic from vanilla to mop. It ended after that cus blizzard wanted to make the gameplay more simple.

**Comment by flapse32** [comment]
Also thats what my bug ticket is about, this dosent work for hunters. But it does work for other classes as you say the damage is calculated only once. but thats not the case for hunters. Will test it later again and see, but when i made the post it was 100% not working as it should.. (Edit: Still dosent work as it should)

**Comment by akrom23** [comment]
What CD's/Trinket you mean?
As I said: damage/heal and their multipliers are aplied on launch, not during cast.
Send some proofs.

**Comment by flapse32** [comment]
Close this one please :D
