### ISSUE TITLE
[Quest] Ally of the Netherwing

### ISSUE THREAD

**Issue by Optilasgar** [SunwellWoW/Sunwell-TBC-Bugtracker#3763]
Description: 
The Quest 'Ally of the Netherwing' is a followup to 'Zuluhead the Whacked'. The RP Option to be flown from Questgiver to Quest completion is missing.

How it works: 
You can take the Option and nothing happens. You need to manually go to where the quest completes.

How it should work: 
You should be flown by the Questgiver Dragon down to the Netherwing Fields, near  to where the Questchain started.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=mxw5YquVO3I

**Comment by dredd-sunwell** [comment]
It's not implemented yet

**Comment by Optilasgar** [comment]
The Quest is in Game, and it can be completed (i have done so). It is just that the RP mechanic is missing from the Quest
