### ISSUE TITLE
Mass dispell removes stealth!!!!

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#3764]
Description: 
MD removes stealth

How it works: 

How it should work: 
it should simply remove 1 magic effect, putting both parties in combat, but not removing stealth....

Source (you should point out proofs of your report, please give us some source):

**Comment by bimbley** [comment]
This is actually false. Mass dispel removes stealth IF a magic effect is removed. Otherwise it does not. 

https://www.wowhead.com/forums&topic=91216

**Comment by username-is-not-taken** [comment]
Bimbley: The post you are refering to is from patch 3.1.0, i.e. wotlk. Besides, I don't think it removed stealth in wotlk either.

In tbc, as far as I remember, it is as in the description: One magic effect gets debuffed, they are both put into combat, but stealth is not broken.

However, in the case of invisibility for mages, the invis should be broken.

From wowhead:

- _Can this de-stealth someone? I've seen more than once, priests using this to uncover a vanished rogue, etc. I may have not been paying close enough attention though, something else may have hit the rogue._

- _Dispelling a rogue wont destealth but it puts you in combat so you cant be sapped. Useful in some situations._

- _You cant get unstealthed by mass dispel, however priests often use this on blank spots hoping to hit you. The reason for this is that it will bring them into combat, thus removing the chance on a sap._

https://www.wowhead.com/spell=32375/mass-dispel#comments - 9th highest rated comment. 
Sure, it is from wotlk, but as far as I know it worked the same in tbc.


The wowwiki patch details says the same:

- _Patch 2.0.3 (09-Jan-2007): "Mass Dispel" will no longer cause stealthed Rogues and prowling Druids to lose stealth._

- _Patch 2.2.0 (25-Sep-2007): Has a chance to be resisted when dispelling immunity effects. This will be displayed in the combat log. In addition, it will no longer cause rogues and druids in Cat Form to lose Stealth. The flashing area graphic has been removed._

**Comment by baade123** [comment]
thx for doing some research. also i dont think the buffs in battlegrounds (rejuv buff, beserker buff, speed buff) should break stealth either :)

**Comment by Bugadin** [comment]
Any new? 12 days ago :/
