### ISSUE TITLE
High King Maulgar.

### ISSUE THREAD

**Issue by mjk6994** [SunwellWoW/Sunwell-TBC-Bugtracker#3767]
Description:  High King Maulgar is only dropping 2 pieces of loot. Happened this week and last.

How it works: ^

How it should work: Should be dropping 3-4.

Source (you should point out proofs of your report, please give us some source):  https://cdn.discordapp.com/attachments/432981313117618217/526236215905878016/unknown.png

Just killed him

**Comment by MadderThenMad** [comment]
Wrong patch for 3-4 pieces. It works as it should.
