### ISSUE TITLE
water walk  on shaman mount does not work... ghost wolf works though :P

### ISSUE THREAD

**Issue by grand-lotus-iroh** [SunwellWoW/Sunwell-TBC-Bugtracker#3768]
Mounting on Water with Waterwalk as Shaman does not work. I can cast Ghost WOlf and water walk on water but not on my mount.

**Comment by notsofamous** [comment]
it's not supposed to until patch 3.0

**Comment by Reflekz** [comment]
it changed in wotlk
http://wowwiki.wikia.com/wiki/Water_Walking
