### ISSUE TITLE
Undead spawn facing backwards

### ISSUE THREAD

**Issue by leahnie956** [SunwellWoW/Sunwell-TBC-Bugtracker#377]
Decription: 
Undead spawn facing backwards

How it works: 
should face forward

How it should work: 
should face forward

Source (you should point out proofs of your report, please give us some source): 
![etheah](https://user-images.githubusercontent.com/25886407/45461513-16ae3f00-b6c9-11e8-81a1-517753c23ba8.jpg)

**Comment by Nadiirr** [comment]
Same as #434 
Closing this one because other one has more info.
