### ISSUE TITLE
Hyakiss the Lurker loot (Karazhan)

### ISSUE THREAD

**Issue by deftelite** [SunwellWoW/Sunwell-TBC-Bugtracker#3771]
Description: 
Hyakiss the Lurker (animal boss) dropped no loot.

How it works: 
Hyakiss the Lurker currently drops no loot when killed.

How it should work: 
Hyakiss the Lurker should drop a randomly generated epic quality belt. (item level 115 with a random affix) 

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Hyakiss_the_Lurker

**Comment by zanthed1** [comment]
This happened again this week on Saturday 1/5. Ive had a ticket open with no response since then. Very frustrating to clear the entire quarter to get a boss with no loot.
