### ISSUE TITLE
[Critical][Quest]Creatures of the Eco-Domes

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#3775]
Description: 
They are all tagged, and dont move, arent attackable etc. ALSO, the quest item is usable on all mobs. Saw it on plant mobs in that Eco-Dome.

How it works: 
Tagging a talbuk makes him stay like that till the next restart, he becomes unattackable + other mobs can be tagged by that item, which doesnt give credit of course, but makes them unattackable and immune till next restart

How it should work: 
After bringing down A TALBUK to 20% or less, he should be tagable by the item. Then we just kill him and thats it. He respawns later, and again and again. NO OTHER CREATURES SHOULD BE ABLE to use the item on them.

Source (you should point out proofs of your report, please give us some source):

**Comment by Mikov1605** [comment]
showing what i meant, they dont move all the time, till next restart, same with talbuks. tagged talbuks should dissappear. IT makes the whole stormspire area FRIENDLY(no mobs to avoid etc)
![image](https://user-images.githubusercontent.com/43579401/50419521-7a501880-0831-11e9-8bf8-864b132394a7.png)

**Comment by Mikov1605** [comment]
Same with talbuks + all of those mobs stay in one point like robots. 
![image](https://user-images.githubusercontent.com/43579401/50421677-7678c200-0842-11e9-9eb5-d21f1bc0627e.png)

**Comment by neheri** [comment]
Today you can't even tag a mob under 20% health, it says The spell is not available to you.

**Comment by neheri** [comment]
![wowscrnshot_122618_191140](https://user-images.githubusercontent.com/37372869/50453608-1b2df900-0942-11e9-9271-5d2a70b2f131.jpg)

**Comment by neheri** [comment]
80% of NPCs are grayed out and don't even move. Can't be attacked or tagged:
![wowscrnshot_122618_191205](https://user-images.githubusercontent.com/37372869/50453615-326ce680-0942-11e9-97f6-14a3d776aa97.jpg)

**Comment by neheri** [comment]
After fix quest can be completed and they respawn quickly so that's nice. However mobs follow you while lying on the ground and don't move, more like teleport from place to place instantly.

**Comment by neheri** [comment]
In addition to that, if you have 2 mobs aggroed, only 1 of them is below 20% and you use quest item, it tags them both and you get 2 credits.
