### ISSUE TITLE
[Item] Keefer's Angelfish & Dezian Queenfish

### ISSUE THREAD

**Issue by ahlens** [SunwellWoW/Sunwell-TBC-Bugtracker#3776]
**Description:** 
During [Stranglethorn Fishing Extravaganza](https://www.wowhead.com/stranglethorn-fishing-extravaganza), I've managed to get two of [Keefer's Angelfish](https://www.wowhead.com/item=19805/keefers-angelfish#comments) and two of [Dezian Queenfish](https://www.wowhead.com/item=19806/dezian-queenfish) in 60 min run. 

**How it should work:** 
According to data from [WoW Head comments](https://www.wowhead.com/item=19806/dezian-queenfish#comments) drop chance should be around 0,25% for each special fish. I'm not sure if this data is correct, but the main point of my bug report is that the **drop chance is most likely too high.** Maybe you will have more information regarding that items.

I didn't catch the [Brownell's Blue Striped Racer](https://www.wowhead.com/item=19803/brownells-blue-striped-racer) so I can't speculate if this item drop rate is either correct or no.

**Comment by E1ectroShock** [comment]
> I didn't catch the Brownell's Blue Striped Racer so I can't speculate if this item drop rate is either correct or no.
Cought 2 of these but no others
So, u just was lucky
