### ISSUE TITLE
Avenger's shield bouncing to CCd mobs

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#3777]
Description: It will bounce and break mobs out of sap/sheep/etc.

How it should work: It should never bounce to a cc'd mob, it should only hit them if it's your primary target

**Comment by leylandpaladin** [comment]
Hi, I can approve this, constatly breaking CC with shield by myself. But i must say that avenger shield was like that on 2.4 patch, and we trying to pretend that we are playing on 2.0, I don't know how devs see this picture. Imo it should be patched.


Source:

http://wowwiki.wikia.com/wiki/Avenger%27s_Shield 
(see patch changes)

**Comment by wombo2u** [comment]
Avengers shield never ignored CCs until wrath prepatch. So it is completely blizzlike and no bug.

**Comment by babno** [comment]
We have the later versions of ice block, arcane shot, blind, etc so we should have the later version of avengers shield. Can’t pick and choose from different patches. @wombo2u

**Comment by babno** [comment]
@dredd-sunwell if this is not a bug are you therefor stating that blind, ice block, and arcane shot are currently bugged?

**Comment by babno** [comment]
@dredd-sunwell see #2908 where another mod says we on 2.4.3 talents/spells versions. As shown above shield was changed to not hit ccd targets in 2.4. Y’all need to get your story straight on this.
