### ISSUE TITLE
Lock summons do not work properly, this includes inside instanced. Cannot port from start of any dungeon/raid to inside of it.

### ISSUE THREAD

**Issue by Ethugx** [SunwellWoW/Sunwell-TBC-Bugtracker#3780]
Description: 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by zapsuu** [comment]
It should works only in Netherstorm and in TK dungeons (for attu)

**Comment by wombo2u** [comment]
Summoning inside instances is disabled until 2.4 as it was in retail. Also you cannot summon in netherstorm until 2.4.3

**Comment by wombo2u** [comment]
Summoning inside instances is disabled until 2.4 as it was in retail. Also you cannot summon in netherstorm until 2.4.3
