### ISSUE TITLE
Righteous Orb drops in Stratholme

### ISSUE THREAD

**Issue by mgperera** [SunwellWoW/Sunwell-TBC-Bugtracker#3782]
Description: The loot tables from Stratholme Living seem way off, ive done it around 7 times so far i didn't get a single orb form trash, when drop rate is around 3-5% from trash

How it works: drops crazy low amounts of righteous orbs, i've got countless blue but 0 orbs

How it should work: Drop righteous orb at 3-5%

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=12811/righteous-orb#dropped-by:0+1-10-9

**Comment by Devrak** [comment]
Its is ether invalid or fixed I have recently run strat live 2 times and on both occasions have seen small number of orbs drop
