### ISSUE TITLE
/Camp not taking out to Dungeon Entrance

### ISSUE THREAD

**Issue by mgperera** [SunwellWoW/Sunwell-TBC-Bugtracker#3785]
Description: /camp is a command that takes you out of dungeon to its entrance

How it works: when you do /camp after 20sec you're not ported out to dungeon entrance

How it should work: when you do /camp after 20sec you're ported out to dungeon entrance

Source (you should point out proofs of your report, please give us some source): 
common wow knowledge

**Comment by dredd-sunwell** [comment]
It shouldn't take you to dungeon entrence.
