### ISSUE TITLE
No CAP damage on AoE

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#3788]
Warlock seed can do up to 40k damage in one AoE.
Looks like you haven't scripted the area damage caps.
http://wowwiki.wikia.com/wiki/Area_damage_caps

**Comment by Avishai97** [comment]
doesn't it say as of patch 2.2 in the link even? we're currently in "2.0"

**Comment by Gustavsson** [comment]
If vendors proffesions etc is in 2.0 why make this change that comes in 2.2? Seems very inconsistent.
