### ISSUE TITLE
improved concentration aura doesn't reduce interrupt/silence effects

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#3797]
Description: It doesn't reduce the duration of interrupts/silence. Tested interrupts with pummel, kick, counterspell, spell lock, and feral charge. Silence tested with shadowpriest silence, spell lock, and improved counterspell. 

How it should work: Should reduce all by 30%

**Comment by akrom23** [comment]
Works fine.

W/o concentration aura on pally:
![wowscrnshot_013119_094052](https://user-images.githubusercontent.com/1035215/52042063-7f913900-253c-11e9-8ccb-23c3bc38e263.jpg)

With concentration and improved concentration aura on pally:
![wowscrnshot_013119_094140](https://user-images.githubusercontent.com/1035215/52042082-8c159180-253c-11e9-8f57-d238807f5185.jpg)

**Comment by babno** [comment]
Did you test lockouts as well as silence?

**Comment by akrom23** [comment]
Improved concentration aura reduces duration of these auras, not the duration of lockouts.

**Comment by babno** [comment]
![image](https://user-images.githubusercontent.com/244626/52071707-81b1c280-2551-11e9-982b-9b99519e5d54.png)

"reduces the duration of any silence or INTERRUPT effect"

**Comment by akrom23** [comment]
Alright - you are right :)
