### ISSUE TITLE
Mob Fanning

### ISSUE THREAD

**Issue by Nadiirr** [SunwellWoW/Sunwell-TBC-Bugtracker#380]
Decription: 
If a bunch of mobs are aggro'd they stay in one place on top of eachother.

How it should work: 
Mobs should Fan out in a circle around their target if they are standing on top of eachother. (Screenshot only suggests a half circle, but I think it's a full circle.)
![screenshot_78](https://user-images.githubusercontent.com/36300104/45482428-e4b9ce80-b702-11e8-95e1-6d71d02536b8.png)

**Comment by Nadiirr** [comment]
The end result is great, but currently it takes too long in my opinion for the mobs to get into the end result.

**Comment by lukaasm** [comment]
I will improve & tweak it later in the future when all critical stuff found is resolved :)

**Comment by Wojtyas** [comment]
It was designed in wotlk but anyway fixed & impemented.
So much wow.
