### ISSUE TITLE
[Quest]The Final Code

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#3802]
Description: 
The npc Sharth Voldoun didnt dropped quest Item while in a group (not raid).
For both of us
How it works: 

Description
How it should work: 

Should drop 100%, no matter if group or not. Only requirement is having quest The Final Code
Source (you should point out proofs of your report, please give us some source):

**Comment by Dewsch** [comment]
Confirmed - he didn't drop it for me either.  2 kills no code so far.

**Comment by bragex** [comment]
to me it seems like it only drops for horde, and not for alliance. I've seen 2 hordes doing the quest

**Comment by bragex** [comment]
Now waited until the whole RP stuff was done, and I finally got the quest drop.. 4th kill
