### ISSUE TITLE
[Quest] darkshore - Buzzbox 411

### ISSUE THREAD

**Issue by seki98** [SunwellWoW/Sunwell-TBC-Bugtracker#3807]
Description: 
I could not find the NPC's at where QuestHelper shows them.

How it works: 
Kill and loot NPC.

How it should work: 
Normal lootable NPC.

Source (you should point out proofs of your report, please give us some source): 
I could not find the NPC's at where *QuestHelper shows them.*

**Comment by nimeral** [comment]
The quest works, Darkshore Threshers are all along the off-shore, underwater. I think QuestHelper bugs are not to be reported here (if it's even a bug and not the NPCs being recently killed by someone).

**Comment by seki98** [comment]
> The quest works, Darkshore Threshers are all along the off-shore, underwater. I think QuestHelper bugs are not to be reported here (if it's even a bug and not the NPCs being recently killed by someone).

My fault then, feel free to close as `not a bug`. I could not find them anywhere where I expected them, but if you did, it is my bad indeed.
