### ISSUE TITLE
Omen of clarity druid talent

### ISSUE THREAD

**Issue by hughjaneus** [SunwellWoW/Sunwell-TBC-Bugtracker#3811]
Description:  I have not seen the proc once in a week since i have selected the talent

How it works: doesnt proc

How it should work: should grant me a free mana rage or energy skill

Source (you should point out proofs of your report, please give us some source):  tested it by attacking mobs and havent seen it

**Comment by ahlens** [comment]
Did you cast the buff on yourself?

**Comment by notsofamous** [comment]
the proc works fine, try getting a poweraura display for it and you'll notice it easier.

**Comment by Nicklastoft** [comment]
Omen of clarity procs the buff "clearcasting" when you attack while having buffed yourself with Omen of clarity.
Works just fine
