### ISSUE TITLE
Felsteel Set Doesn't Give Set Bonus

### ISSUE THREAD

**Issue by Myllz** [SunwellWoW/Sunwell-TBC-Bugtracker#3814]
Description: 
Wearing the 3 piece Felsteel set doesn't give the set bonus.

How it works: 
Nothing happens, no strength bonus is applied.

How it should work: 
Should give 25 strength to the character when all 3 pieces are worn.

Source (you should point out proofs of your report, please give us some source): 
I have all 3 pieces equipped. Character name Autosum. Have tried un-equipping/re-equipping pieces, logging, deleting cache, etc.

![image](https://user-images.githubusercontent.com/669814/50407568-788e4280-07a8-11e9-9f87-c540e6af1e90.png)

**Comment by YoshGit** [comment]
Do you have 350 BS like the tooltip requires?

**Comment by dredd-sunwell** [comment]
It doesnt work without 350bs

**Comment by Myllz** [comment]
Oops, didn't notice that. Nevermind! :)
