### ISSUE TITLE
Pendant of Triumph and Pendant of Dominance

### ISSUE THREAD

**Issue by arkatik** [SunwellWoW/Sunwell-TBC-Bugtracker#3815]
**How it works:**
they are not on sale

**How it should work:** 
Added in patch 2.0.1.6180 
http://wowwiki.wikia.com/wiki/Pendant_of_Triumph
https://www.wowhead.com/item=28244/pendant-of-triumph&spec=261#see-also

http://wowwiki.wikia.com/wiki/Pendant_of_Dominance
https://www.wowhead.com/item=28245/pendant-of-dominance

**PS: read this bug report and finally answer**
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3630

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed, live
