### ISSUE TITLE
[HIGH PRIORITY][General][Core]Cant ressurect in instance after i left group and logged out

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#3819]
Description: 
I left my dungeon group, while in ghost form. My corpse was in the instance(Sethek Halls norm). After logging in later(still in ghost form, intended) i cant enter the instance to ress my body, even the grave icon disappeared from it.

How it works: 
Cant ress in instance my corpse is in after leaving group in ghost form and logging out.

How it should work: 
If you died in an instance, no matter if you leave group, log out, you should be able to recover your corpse, even if you come 2 months later into the game.
NOTE: I made a simmiliar post, about the same bug in uldaman, and you ignored it :( 
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2699

PLEASE FIX IT, ITS RLY ANNOYING

Source (you should point out proofs of your report, please give us some source):

**Comment by Azmoddan** [comment]
True dat.

**Comment by akrom23** [comment]
Still happens?
Happens in open world?

**Comment by Wojtyas** [comment]
No reaction - seems it works now.
