### ISSUE TITLE
Horde PVP Vendor in Hall of Legends (OG) doesn't sell lvl 70 Necks

### ISSUE THREAD

**Issue by Optilasgar** [SunwellWoW/Sunwell-TBC-Bugtracker#3824]
Description: 
The NPC 'Brave Stonehide <Officer Accessories Quartermaster>' does not have an Option to buy PvP Necklaces but instead sells 2 different copies of the exact same PvP Cloaks.

How it works: 
http://puu.sh/CmXU6/a22cf19db2.jpg

How it should work: 
The Vendor should sell an equal quality PvP Necklace

Source (you should point out proofs of your report, please give us some source): 
http://puu.sh/CmXU6/a22cf19db2.jpg

**Comment by arkatik** [comment]
alliance too
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3815
