### ISSUE TITLE
Stasis Chambers of Bash'ir quest mob despawns, quest uncompletable till server restart

### ISSUE THREAD

**Issue by nickycakes** [SunwellWoW/Sunwell-TBC-Bugtracker#3829]
Description: 
During quest Stasis Chambers of Bash'ir, the elite mob can despawn, but the prison doesn't respawn, so there's no way to complete that quest, presumably until the server restarts.

How it works: 

Unlock the prison using quest item, elite mob spawns.  Elite mob despawned after that, but prison does not respawn, so there's no way to complete the quest.

How it should work: 

Elite mob doesn't randomly despawn.  Prison respawns after some time so other people can complete the quest without server restart.

Source (you should point out proofs of your report, please give us some source):

**Comment by MadderThenMad** [comment]
Confirming the issue this makes it almost impossible to complete Yor chain
