### ISSUE TITLE
Random objects ingame. Needs to be deleted.

### ISSUE THREAD

**Issue by Nadiirr** [SunwellWoW/Sunwell-TBC-Bugtracker#383]
Not sure if a GM spawned these in on just the PTR or if they will be in the live version as well:

They go all up the mountain.
![screenshot_80](https://user-images.githubusercontent.com/36300104/45484083-d91cd680-b707-11e8-8392-60426878eb28.png)

![screenshot_81](https://user-images.githubusercontent.com/36300104/45484078-d15d3200-b707-11e8-9599-b775367777c3.png)

**Comment by Riztazz** [comment]
could be related to some kind of event

**Comment by notsofamous** [comment]
Found more
![Image](https://i.gyazo.com/8b03556d10cfe111223049f70cbde0f4.jpg)
![Image](https://i.gyazo.com/9684fd0b70be09e2b1e2383aea0855cb.png)

**Comment by Dootz** [comment]
we decided to leave it for now as small "easter egg"
