### ISSUE TITLE
Hunter - Pet Revive - Petbar disappears

### ISSUE THREAD

**Issue by Butterfly1298** [SunwellWoW/Sunwell-TBC-Bugtracker#3830]
Description: 

Pet Revive - Statusbar disappears. When my Pet dies and I am reviving it, it revives, but I cant  see the Petbar anymore.

How it works: 

How it should work: 

Normally it should show the petbar without a problem after the revive. I have to Dismiss the Pet first and get it back with my pipe to see the petbar again. Thats annoying as a BM-Hunter!
Source (you should point out proofs of your report, please give us some source):

**Comment by nickycakes** [comment]
can confirm.  dismissing and then calling again brings it back though

**Comment by mintnb** [comment]
press ctrl+2
