### ISSUE TITLE
Fozruk not spawning after 1 hour.

### ISSUE THREAD

**Issue by waterloorick** [SunwellWoW/Sunwell-TBC-Bugtracker#3834]
Description: We finally asked for a GM and Peanut showed up and confirmed that Fozruk was not up after 1 hour.

How it works: Fozruk is not spawning.

How it should work: Fozruk should spawn after a short period of time. (2.3 it was 1 minute after kill)

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/npc=2611/fozruk#comments

**Comment by Dootz** [comment]
As of today he's live on server. Confusion here might have been caused by the fact that he's walking around with his group.
