### ISSUE TITLE
Blessing of Incineratus

### ISSUE THREAD

**Issue by Ramader** [SunwellWoW/Sunwell-TBC-Bugtracker#3835]
Description: Its the quest from the Throne of Elements to burn the huts

How it works: The player enters the hut, uses the torch...it goes on its short cooldown....no graphic of "the tent is on fire", no credit for the quest.

How it should work: When the torch is used, the tent is supposed to burn, and credit is supposed to be given.

**Comment by Dootz** [comment]
fixed, live
