### ISSUE TITLE
Undispelable buffs

### ISSUE THREAD

**Issue by username-is-not-taken** [SunwellWoW/Sunwell-TBC-Bugtracker#3841]
Description: 
A lot of mobs have buffs, or cast buffs on themselves once engaged, which cannot be removed. I can't remember all the mobs or which particular buffs that this happens to, but the screenshot serves as an example as well as the astromages (fire shields) inside Mechanar. The buffs are listed as debuffs and can therefore not be removed.

How it works: 
Non-dispelable magic buffs.

How it should work: 
They should be dispelable.

Source (you should point out proofs of your report, please give us some source): 

![asd](https://user-images.githubusercontent.com/45629295/50450234-e3688680-092c-11e9-9b7d-ba8c7486f32f.png)

**Comment by koostosh** [comment]
Could not reproduce, those buffs are dispelable without any problem.
