### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#3842]
You can currently fish anywhere with any skill, this shouldn't be possible. You should get a message saying that your skill is too low for a certain area if you try to fish there.

Here's a list of required skills for different zones (left) and the skill needed for no longer getting the "Your fish got away" message (right). I'm currently fishing in Zangarmash with 407 skill and getting fish escaping, this shouldn't be happening.
![Image](https://i.gyazo.com/94b4f86a8d56820dbe70fb1b84fecb8d.png)

*Note that instances and raids (Serpentshrine Cavern) aren't on this list but should require even higher skill than Terokkar highlands (Probably 475).

http://kmdguild.forumotion.com/t1-fishing-leveling-guide-1-375

**Comment by baade123** [comment]
i tried to fish in nagrand and could not catch anything >_> i dont know about that

**Comment by Ironjudgment** [comment]
I think you can fish anywhere but your chances of catching anything will be null. It will dispaly messages like 'Your fish got away!'.
