### ISSUE TITLE
High delay before leaving combat

### ISSUE THREAD

**Issue by blackabbath** [SunwellWoW/Sunwell-TBC-Bugtracker#3843]
Description: 
It's take around 5-7 seconds before leaving combat after kill some mob or just get aggroed. 
I see this issue Blade's Edge Mountains, It's pretty bad at least for a rogue.

How it works: 

How it should work: 
Should be out of the combat immediately after mob killed

Source (you should point out proofs of your report, please give us some source):

**Comment by Azmoddan** [comment]
Not a bug, combat timer in TBC was dynamic, up to 6,5 or 7 seconds.

**Comment by blackwife** [comment]
I haven't experienced any bug in this regard at all, however there are a number of NPCs that are erroneously flagged as PvP NPCs (like the Bloodmaul Ogres in BEM) and PvP NPCs/players have a long combat delay after death.

**Comment by blackabbath** [comment]
> Not a bug, combat timer in TBC was dynamic, up to 6,5 or 7 seconds.

sorry, but you trying to sell me **bullshit**. I played original TBC and never saw such issue.
btw, there is no problem anymore. i suppose it was due to a server high-load, so topic could be closed.
