### ISSUE TITLE
Slice and Dice is not working that well

### ISSUE THREAD

**Issue by XisldaRogue** [SunwellWoW/Sunwell-TBC-Bugtracker#3845]
Description: 
The ability Slice and Dice level 2 is not working properly . The speed increase is not applying as it should be. This affect greatly in the dps output of the rogue and also while leveling.

How it works: 
In first place, the ability in the buff section shows the Slice and Dice level 1 buff (which means it's 20% melee weapon increase ) while i do have the  Slice and Dice level 2 . Secondly , the buff is not increasing the correct amount of melee weapon speed of 30%( I'm fine if the tooltip is not showing correctly in the buff section of the screen but if it's not working on the actual mechanic)  . I can make sure this statement is correct because i used to play in another tbc server and also tested this skill  with a weapon of 2.70 speed. In Sunwell , the 2.70 weapon just lowers the speed to 2.25 with Slice and Dice level 2(30% increase melee atack speed) .

How it should work: 
While in the other server i play i did test the same situation with a weapon with 2.70 to make sure my test is not off, when i used the Slice and Dice level 2 the weapon speed dropped to 2.08.  So i did some maths with a calculator and turns out both are wrong as they should be but the Other server is closer to the actual number it should be so i believe it's a ingame mechanic to lower the actual effect. But 2.08 it's way close to the true value of the ability rather the 2.25 that occurs in sunwell

Source (you should point out proofs of your report, please give us some source): 
![sin titulo](https://user-images.githubusercontent.com/46169225/50456643-00e52280-0924-11e9-92e0-d476399dee80.png)
![2](https://user-images.githubusercontent.com/46169225/50457727-e3b45200-092b-11e9-9057-bb12ba22a818.png)

**Comment by kinglobster** [comment]
2,7 / 1,3 = 2,076~
2,7 / 1,2 = 2,25 

what is wrong with ur calculations?
