### ISSUE TITLE
Tempest Keep attunement (High Prio!)

### ISSUE THREAD

**Issue by ghertruda** [SunwellWoW/Sunwell-TBC-Bugtracker#3848]
Description: After killing maghteridon and completing the quest Trial of The Naaru: Magtheridon, you do not recieve a tempest key, that means you are unable to enter Tempest Keep after completing its attuenement quest.
This is a major issue regarding the T5 race, needs to be solved ASAP, hotfix for those that are champions of the naaru already could be mailing them the key

How it works: You do not  get the tempest key that lets you enter The Eye after completing the last attunement quest for it - https://www.wowhead.com/item=31704/the-tempest-key

How it should work: you complete Trial of The Naaru: Magtheridon and recieve title Champion of the naaru along with The tempest key

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_122718_001246](https://user-images.githubusercontent.com/36400119/50459516-331a7280-096c-11e9-8de8-6bdbc09ad3f2.jpg)
as you can see i have the champion of the naaru title but cannot enter tempest keep.

**Comment by Dootz** [comment]
should be fixed now. You will be able to enter tempest keep without key, only with completed quest.
