### ISSUE TITLE
Buff/Debuff stacking

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#385]
**Decription:** 
Debuffs with the same type of effect should overwrite each other and only keep the one with the strongest effect.

**How it works:** 
All debuffs are currently displayed on the target.

**How it should work:** 
There are 2 conditions and it should work the same as buffs do, example:
Condition one, how powerful it is:
If Player1 buff +8 stamina on Player1, Player2 can then buff +9 stamina on Player1 and the +8 stamina buff disappears. Player1 now cannot buff +8 stamina on himself again as a stronger spell is already applied.

Condition two, duration:
If both Player1 and Player2 have the same spell but it has different durations. Player1 buffs himself with +8 stamina with a 30 min duration. Player2 attempts to buff Player1 with +8 stamina with a 10 min duration. It fails because there's a more powerful spell already applied. HOWEVER, if he waits until there's only 9 min remaining on the 30 min buff, he can overwrite it because his spell is now more powerful.

_Power will always trump duration._

So translated into debuffs, let's take slows as an example:
Player1 applies crippling poison(70% slow) to Mob. Player2 casts frostbolt (40% slow) on Mob. Frostbolt does damage but no debuff is applied because there is already a stronger effect in place.

Player2 casts frostbolt (40% slow, 8 sec duration) on Mob, debuff is applied. Player1 applies crippling poison (70% slow, 2 sec duration), debuff is applied and frostbolt is removed.

This should be true with all types of debuffs with the same effect; 
Movement slow (Frostbolt, Hamstring, Crippling Poison, Cone of Cold etc) 
Casting speed slow (Mind Numbing Poison, Curse of Tongues etc)
Attack speed slow (Thunderclap, Thunderfury effect etc)
Healing reductions (Mortal Strike, Wound Poison etc)
Armor Reductions (Sunder Armor, Expose Armor etc)
Attack Power Reductions (Demoralizing Shout/Roar etc)
Snares (Frost Nova, Net etc)

However there are exceptions: 
Armor debuffs:
Faerie Fire, Sunder Armor/Expose Armor and Curse of Recklessness should all stack (Sunder and Expose don't stack with each other but will stack with the others.

Debuffs with a secondary effect should stay as a debuff even if there are more powerful spells, but the effects themselves should not stack:
Frost Armor (Slows movement and attackspeed)
Curse of Exhaustion (slows movement and has a hidden secondary effect, warlocks drain life (talented) heals more depending on warlock debuffs on the target) applied along with Crippling Poison here: https://www.youtube.com/watch?v=t8iiLNszJpU&feature=youtu.be&t=175

**Source (you should point out proofs of your report, please give us some source):** 
https://www.youtube.com/watch?v=462JFev7AE4
https://www.youtube.com/watch?v=t8iiLNszJpU&feature=youtu.be&t=175
http://web.archive.org/web/20071202181137/http://elitistjerks.com/498690-post35.html
http://web.archive.org/web/20081222181901/http://elitistjerks.com/f81/t22705-dps_compendium/

**Comment by nimeral** [comment]
Bump, still bugged.

IMO, it's an important issue to fix, can cause minor same-faction griefing and awkward conflicts - on BGs, or when simply buffing someone only to realize you've removed a better buff.

**Comment by SuddenDeath** [comment]
https://www.youtube.com/watch?v=a3yTchRq8Ls
@1:56 Cone of cold removes Frostbolt debuff
@7:55 Crippling removes Frostbolt debuff

https://youtu.be/8mNaTUiowTk?t=2m17s
@2:17 Crippling poison removes Hamstring

https://youtu.be/BzxapSKz3ck?t=6m3s
@6:03 Mortal strike removes Wound Poison

https://youtu.be/HC8_H1AiSHs?t=22m58s
@22:58 Orc Racial(Blood fury) removes 5x Wound Poison and makes him immune to gaining wound poison stacks for its duration.

This is indeed a very important mechanic.

**Comment by Wojtyas** [comment]
Still present after aura merge?

**Comment by doomnyx** [comment]
Can confirm, still present (tested with priest single and group buffs, scrolls).
While scrolls cannot stack with all those buffs, you are able to put rank1 buff from spell even if max rank is currently on target.

**Comment by nimeral** [comment]
Now it seems to be fixed - at least you can't overwrite MotW rank 2 with MotW rank 1.

But if you cast a lower ranked spell, it still costs mana. Should be "a more powerful spell is already active" message with fizzle sound.

**Comment by Klimpb** [comment]
Not fixed, hamstring still stacks with crippling poison, same with wound poison and mortal strike, same withj slows.

**Comment by akrom23** [comment]
@SuddenDeath Looks like you can apply both, but works only the strongest one. Same with mortal strike.

**Comment by Klimpb** [comment]
@akrom23 has big impact on pvp in many different situations.
If fixed:
slowed by magic effect -> crippling poison replace it -> remove poison -> no longer slowed.

Currently: 
slowed by magic effect -> crippling poison -> remove poison -> still slowed by magic.

**Comment by akrom23** [comment]
@SuddenDeath Could you tell me what kind of auras still stack but should not?
Crippling/Hamstring ->slow auras
Wound poison/mortal strike ->healing reduction

Any other?

**Comment by Klimpb** [comment]
@akrom23 It's in the original post of this but report:

> So translated into debuffs, let's take slows as an example:
Player1 applies crippling poison(70% slow) to Mob. Player2 casts frostbolt (40% slow) on Mob. Frostbolt does damage but no debuff is applied because there is already a stronger effect in place.

> Player2 casts frostbolt (40% slow, 8 sec duration) on Mob, debuff is applied. Player1 applies crippling poison (70% slow, 2 sec duration), debuff is applied and frostbolt is removed.

> This should be true with all types of debuffs with the same effect;
Movement slow (Frostbolt, Hamstring, Crippling Poison, Cone of Cold etc)
Casting speed slow (Mind Numbing Poison, Curse of Tongues etc)
Attack speed slow (Thunderclap, Thunderfury effect etc)
Healing reductions (Mortal Strike, Wound Poison etc)
Armor Reductions (Sunder Armor, Expose Armor etc)
Attack Power Reductions (Demoralizing Shout/Roar etc)
Snares (Frost Nova, Net etc)

> However there are exceptions:
Armor debuffs:
Faerie Fire, Sunder Armor/Expose Armor and Curse of Recklessness should all stack (Sunder and Expose don't stack with each other but will stack with the others.

> Debuffs with a secondary effect should stay as a debuff even if there are more powerful spells, but the effects themselves should not stack:
Frost Armor (Slows movement and attackspeed)
Curse of Exhaustion (slows movement and has a hidden secondary effect, warlocks drain life (talented) heals more depending on warlock debuffs on the target) applied along with Crippling Poison here: https://www.youtube.com/watch?v=t8iiLNszJpU&feature=youtu.be&t=175
