### ISSUE TITLE
Khorium lockboxes are always empty

### ISSUE THREAD

**Issue by Ahrimania** [SunwellWoW/Sunwell-TBC-Bugtracker#3851]
Description: 

Khorium lockboxes never contain any loot. None in the ones I have opened so far, and someone told me he opened 4 empty ones in a row as well.

Incidentally, lower-lvl boxes (sub 225 skill) are suspiciously often empty as well.

How it works: 

Khorium boxes are always empty. When you click to open them, they just disappear. This happens quite often to low-lvl boxes as well.

How it should work: 

Lockboxes should NEVER be empty. When you click an opened lockbox, it should always at least contain 1 green item.

Source (you should point out proofs of your report, please give us some source): 

- common sense
- this discussion on wowhead from 2011: https://www.wowhead.com/forums&topic=198234

"By badbee on 2011/12/05 at midnight (Patch 4.2.2)

I've found a lockbox inside of a lockbox before, not sure I ever had an empty one though."

"By Problimatic on 2011/12/05 at midnight (Patch 4.2.2)

Never had an empty one before..."

**Comment by Dootz** [comment]
fixed, live
