### ISSUE TITLE
[NPC] Myra Tyrngaarde <Bread Vendor> is missing from IF

### ISSUE THREAD

**Issue by Ahrimania** [SunwellWoW/Sunwell-TBC-Bugtracker#3852]
Description: 

Ironforge's finest distributor of dough is missing in action. #FreeMyra

How it works: 

Myra Tyrngaarde is currently not patrolling the area between the Ironforge bank and auction house.

How it should work: 

Myra Tyrngaarde should be patrolling the area between the Ironforge bank and auction house.

Source (you should point out proofs of your report, please give us some source): 

- Literally everyone who has ever walked out of the Ironforge auction house, looking for the nearest vendor to dump some trash on.

- "She walks around Ironforge selling her bread." - Gannondalf, 2007 (https://www.wowhead.com/npc=5109/myra-tyrngaarde#comments)

**Comment by Dootz** [comment]
fixed, live
