### ISSUE TITLE
Shadow Word: Death causes spell interruption before damage goes off, so it's impossible to SWD poly unless they are shielded.

### ISSUE THREAD

**Issue by Ethugx** [SunwellWoW/Sunwell-TBC-Bugtracker#3853]
Description: 

How it works: 
spell knockback goes off before dmg

How it should work: 
spell knockback goes off after dmg

Source (you should point out proofs of your report, please give us some source): 
brain

**Comment by Ibuprofeno** [comment]
Do you mean the dmg on your target or yourself? Because there's always been pushback and priests can SWD poly here

**Comment by akrom23** [comment]
Works fine.
