### ISSUE TITLE
keep getting a crit. error while on a flight path to shat, cleaned my catch still not working, stuck in flight path from bladesage to shat.

### ISSUE THREAD

**Issue by iamnotacow** [SunwellWoW/Sunwell-TBC-Bugtracker#3855]
Description: 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by iamnotacow** [comment]
it says something to do with addons and memory. I have no addons and cleand my catch.

**Comment by mintnb** [comment]
There is a teleport feature on the site. I used that to get myself out of a dungeon where similar error ocured.

**Comment by iamnotacow** [comment]
now i am swimming in the air above the great sea...... teleport on web site just bugs me out of a flight point in stormwind,

**Comment by iamnotacow** [comment]
ok now back in SW woot!

**Comment by Wojtyas** [comment]
Quite common issue nowadays, we are working on it.
