### ISSUE TITLE
[Q] Investigate the Amani catacombs

### ISSUE THREAD

**Issue by CEFab** [SunwellWoW/Sunwell-TBC-Bugtracker#3856]
Description: lvl 10-20 blood elf quest in tranquilien, Ghostlands

How it works: You run out of charges before you can end the quest

How it should work: You should have enough charges to burn all the mummies in the catacombs

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/sifAf14

**Comment by Dootz** [comment]
Hi, this item has 10 charges and they are only consumed when you click on Troll Remains. I was able to get credit for all 10 Troll Remains and complete quest without problem. 10 charges is default blizzlike value of charges for this quest. Somehow one of your charges was probably consumed without quest credit but i was not able to recreate it.

**Comment by Xithus** [comment]
Issues is there's at least 1 body in there you click on i know of that doesn't give credit but uses a charge. Also I believe if you have a body you already set fire too and it comes up available to click again it eats a charge without giving credit. 

The body i know that does it is (entering from the side facing the quest hub) its either the 2nd 3rd or 4th body that's on the right side that eats a charge without giving credit.
