### ISSUE TITLE
[Paladin] Libram of the Eternal Rest

### ISSUE THREAD

**Issue by gastroslim** [SunwellWoW/Sunwell-TBC-Bugtracker#3857]
Description: 
https://tbc-twinhead.twinstar.cz/?item=27917
Libram of the Eternal Rest does not add any consecration dmg

How it works: 
Consecration dmg (any rank) is same with or without the use of libram

How it should work: 
Libram should add 47 spell dmg to total spell dmg on consecration spell.

Source (you should point out proofs of your report, please give us some source):

**Comment by leylandpaladin** [comment]
Can confirm, libram doesnt give any consecration damage.
