### ISSUE TITLE
Karazhan[High Priority]

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#3858]
Description: 
Prince - You can kick his Shadow Nova, which you should not be able to.
Nightbane - You can kick his fear, which you should not be able to.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azmoddan** [comment]
That's true, melees would normally be obliged to run away, but it is not necessary as it is bugged now.

**Comment by runt481** [comment]
You're also able to kick Charred Earth and Smoldering Breath on Nightbane.
