### ISSUE TITLE
Cave pathing

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#386]
All caves that I've tested seem to work like this: https://i.gyazo.com/8a7f0214dff9236bb23147011446c47b.mp4

Mobs are going straight up into heaven.

**Comment by akrom23** [comment]
@notsofamous  Already fixed. Test after restart.

**Comment by Riztazz** [comment]
server restarted

**Comment by notsofamous** [comment]
Works
