### ISSUE TITLE
Phantom from mob in shethekk halls too fast

### ISSUE THREAD

**Issue by maseta9** [SunwellWoW/Sunwell-TBC-Bugtracker#3860]
Description: There's a mob in the normal shethekk halls instance that spawns a ghost when killed (I think the name of the mob is Shethekk Prophet), this ghost walks way faster than the average player and inflicts massive amounts of damage; the damage part is correct, the speed of the mob isn't supposed to be as quick as it is, in retail wow these ghosts move slower than players so they can escape certain death.

How it works: Mob dies, ghost spawns, ghost selects target and walks toward him at higher-than-usual speed, player gets killed with 0 chance of survival.

How it should work: Mob dies, ghost spawns, ghost selects target and walks toward him at slower-than-usual speed, player is threatened by an avoidable infliction of massive damage.

Source (you should point out proofs of your report, please give us some source): 

https://www.youtube.com/watch?v=N8IXQNilzw8 this is a video of a normal Shethekk Halls run in a retail server, please watch from second #22 and watch as the prophet dies he spawns the ghost which starts to slowly walk towards the casters.
I don't have any videos of my run to normal shethekk halls, but I can tell you I wiped about 14 times due to this bug, since it always targeted either me or our hunter and there was no way to outrun him, he walks very very fast!

**Comment by Dootz** [comment]
fixed, live
