### ISSUE TITLE
Spell - Arcane Missiles (Bug)

### ISSUE THREAD

**Issue by JorgeQualium** [SunwellWoW/Sunwell-TBC-Bugtracker#3866]
Description: 

How it works:
Sometimes (1 of 5 approximately), the spell 'Arcane Missiles' doesn't work, my character makes the gesture of launching the missiles, and it sounds like it's being casted, but it doesn't make any damage and also the visuals of the missiles don't appear either.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
#4005.
