### ISSUE TITLE
Serrated Blades

### ISSUE THREAD

**Issue by Thempest** [SunwellWoW/Sunwell-TBC-Bugtracker#3867]
Description: Serrated Blades talent (Subtlety rogue) seems not to work for Rupture (armor reduction seems OK).

How it works: Adding points to this talent does not increase Rupture dmg. Ability value in description is not increasing at all and dmg log is showing the same amount of dmg done before and after points spent on this talent.

How it should work: Serrated Blades talent (Subtlety rogue) should grant +30 % dmg on Rupture ability.

Source (you should point out proofs of your report, please give us some source):
![serrated blades](https://user-images.githubusercontent.com/46202390/50493975-e6dd3a00-0a20-11e9-9e19-2e34943de720.PNG)

**Comment by Splinterskul** [comment]
It also doesnt specify how much armor you are ignoring of your target which needs to be fixed too, if it is infact ignoring any armor that is. I really like playing a subtlety spec rogue, but this needs to be fixed please. :)

**Comment by akrom23** [comment]
Tooltip is clientside.

W/o talent:
![wowscrnshot_022119_105335](https://user-images.githubusercontent.com/1035215/53160203-c0262480-35c7-11e9-90c5-997e3fe62b70.jpg)

With talent:
![wowscrnshot_022119_105815](https://user-images.githubusercontent.com/1035215/53160212-c4ead880-35c7-11e9-9ff4-13de5e0ef5e0.jpg)
