### ISSUE TITLE
Line of sight

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#387]
There's currently no line of sight restrictions implemented.

Can attack mobs through a wall: https://i.gyazo.com/0e8f34e8a50027f17ad41057407ca704.mp4

Healing a mob through a wall: https://i.gyazo.com/e28a4751cd65f5a5eb2441ac1e9310d9.mp4

**Comment by akrom23** [comment]
Again, already fixed. Re-test.

**Comment by Riztazz** [comment]
PTR Updated, please test now ;p

**Comment by notsofamous** [comment]
Works
