### ISSUE TITLE
Elixir of Draenic Wisdom Not in game?

### ISSUE THREAD

**Issue by Spoohne** [SunwellWoW/Sunwell-TBC-Bugtracker#3870]
Description:  Elixir of Draenic Wisdom

https://www.wowhead.com/item=32067/

Should be trainable from profession trainer as of 2.0.12-- not available in game currently.

How it works: 
Cannot train the recipe for Draenic Wisdom in game.

How it should work: 
Should be able to train this recipe.

Source (you should point out proofs of your report, please give us some source): 
Comments here:
https://www.wowhead.com/item=32067/

Indicate how this was obtained as of patch 2.0 and on.

**Comment by arkatik** [comment]
**Added in patch 2.1.0.6624**

**Comment by Wojtyas** [comment]
I highly believe you are wrong. 2.0.12 comments are from people who were able to visit 2.1 beta.
Even in your link the second comment says:

zevrang on 2007/05/07 (**Patch 2.0.12**)
_I also think this **will be** the Guardian Elixir of choice for mages and possibly locks when flasks are not used. Elixir of Empowerment is an alternative, but as a raider you should have enough hit rating to minimize resisted spells._

Where guy from 2.0.12 clearly says that it WILL BE Guardian Elixir so its not available now.
