### ISSUE TITLE
[Quest]Flora of the Eco-Domes

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#3871]
Description: 
You can spam the Item on a plant mob and get whole quest credit.

How it works: 

You can use the q Item on one mob multiple times.
How it should work: 
You can use it once per mob.
Wowhead comment:
For those trying this quest during this decade, here's how to do it.
Target a Lasher. Don't attack yet. Use the Modulator to turn the Lasher into a Mutated Lasher.
Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2796
