### ISSUE TITLE
[Quest] [True Masters of the Light]

### ISSUE THREAD

**Issue by maddie1337** [SunwellWoW/Sunwell-TBC-Bugtracker#3873]
Description: 

Im currently doing my epic paladin mount quest, and i've got some problems with the stratholme part of the quest " [True Masters of the Light]". It wont complete. 
I'm supposed to burn the Church at the back intrance of Stratholme, and then the NPC inside should aggro me, but he doesnt. He just kneels there being friendly. 
Then mobs spawn outside (paladin ghosts), but nothing happens if i kill them. 
I've burned the church atleast 7 or 8 times now, and nothing helps. I even completed the quest you can pick up from him, which has nothing to do with the Paladin quest.
I hope you will adress this soon, as i saved for this mount for weeks, and now when i've payed/crafted my way there, i can't get my mount :(

How it works: 
NPC inside chuch wont aggro me when i burn the church.

How it should work: 
NPC should aggro me when i burn the church, then I'm supposed to kill the paladin ghosts outside, and then the quest should be completed.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=9737/true-masters-of-the-light

Regards Maddie / Nightbane

**Comment by Dootz** [comment]
fixed, live
