### ISSUE TITLE
Prayer of mending heal should pop if the damage that would kill you is less than the heal that would occur. It doesn't.

### ISSUE THREAD

**Issue by Ethugx** [SunwellWoW/Sunwell-TBC-Bugtracker#3874]
Description: 

How it works: 
you die with pom on you even tho the heal would save you

How it should work: 
heal should proc if it would save you, otherwise you should die

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@Ethugx Proofs? Tooltip says it clearly:

> the **next time** they **take** damage

It's not a shield - it's a heal taht occurs after the damage is dealt.

**Comment by akrom23** [comment]
No response.
