### ISSUE TITLE
Blessing of Freedom weird behavior

### ISSUE THREAD

**Issue by Sologrim** [SunwellWoW/Sunwell-TBC-Bugtracker#3878]
Description: 
Blessing of freedom should grant immunity to movement imparing effects. However I casted it being chased by mobs and got dazed nontheless! Got dazed under the effect of BoF! WTF!
StR
1, Pull a pack of mobs (of your level recommended)
2, Cast BoF

How it works: 
You get dazed.

How it should work: 
You should not get dazed.

Source (you should point out proofs of your report, please give us some source): 
![2018-12-28](https://user-images.githubusercontent.com/20763047/50507597-d95a9b00-0a86-11e9-90b9-39e0cc534060.png)

**Comment by Azathothh** [comment]
This ability will not remove the Daze effect caused by running from mobs, or a hunter's [Concussive Shot] effect.
That's how it's supposed to work.

**Comment by Sologrim** [comment]
remove mb not. but if you`re under the BoF effect, it should not be possible to slow you
otherwise it just makes no sense

**Comment by Azathothh** [comment]
Please provide any proofs if you're sure that it should be working like you're saying
