### ISSUE TITLE
AI issue

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#388]
**Decription:** 
Caster mob will not chase a player that is not in its LoS.

**How it works:** 
When aggroed the caster mob will just stand there and wait for you to come in his LoS.

**How it should work:** 

Pulling mob and running to LoS it: https://gyazo.com/265e8b3e57fe57f13ea0ec4549a7c091
Mob just stands there: https://i.gyazo.com/25b49c3e806d6c353dfc2de96f70ba58.mp4

The only way to get him to run down was for wait for him to go OOM.

**Source (you should point out proofs of your report, please give us some source):**

**Comment by nimeral** [comment]
I think it's still an issue, at least sometimes. I've killed some Gnarlpine Mystic, and they were only chasing me when I moved away - but not when I tried to LoS them, LoSing made them stuck. I think it's not a specific pathing issue, since Gnarlpine Warriors around behaved normally.

**Comment by nimeral** [comment]
Another example of bugged behaviour would be Stormscale Siren.

I pull her and LoS, she brainlags for a second and continues her patrol route, while losing HP from my Moonfire and being in combat. Sometimes, however, when I spent a bit more time in her LoS, she has followed me afterwards.

So yea it does seem like a global AI issue.

**Comment by Wojtyas** [comment]
It works in general but there are still some creatures that still ignore that fix. Probably better to report them one-to-one.
