### ISSUE TITLE
[Hunter][pet][spell][Scorpid Poison]

### ISSUE THREAD

**Issue by Zamesi** [SunwellWoW/Sunwell-TBC-Bugtracker#3880]
Description: Hunter pet spell Scorpid Poison rank 5 does not stack correctly.

How it works: After stacking to 5, it rolls back to 1 stack on new apply.

How it should work: When stacked to 5, new applies of the spell should hold the stack at 5, not roll it back to 1

Source (you should point out proofs of your report, please give us some source): "Stacks up to 5" not "Stacks up to 5 then rolls back to 1"

[smallvideclip.zip](https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/files/2714350/smallvideclip.zip)

**Comment by akrom23** [comment]
18 sec - The 5th stack applied.
29 sec - The 1. stack applied, because the last Scorpid Poison removed (10 sec duration).
There is no bug.
