### ISSUE TITLE
[Quest]To Legion Hold

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#3881]
Description: 
Upon aquiring that q, it immediately completes itself, and we can instant turn it in.

How it works: 
You actually just take the quest and instant turn it in, and thats it.

How it should work: 
https://www.wowhead.com/quest=10563/to-legion-hold

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed, live
