### ISSUE TITLE
[Quest]Hotter than Hell (Shattered Halls quest chain end)

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#3882]
Description: 
You can use the q item ANYWHERE in hellfire and it will give you credit

How it works: 
Description

How it should work: 
You should use the q item near a dead Fel Reaver body

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed, live
