### ISSUE TITLE
Stealth prevents interaction with BG objectives

### ISSUE THREAD

**Issue by Ahrimania** [SunwellWoW/Sunwell-TBC-Bugtracker#3883]
Description: 

Being in stealth prevents you from interacting with battleground objectives (flags/bases). You have to manually leave stealth to do so.

How it works: 

When you click a battleground objective while in stealth, you get a 'failed attempt' message. You have to manually leave stealth to interact with it.

How it should work: 

You should be able to interact with a battleground objective directly from stealth. Doing so should break stealth.

Source (you should point out proofs of your report, please give us some source): 

- This video: https://youtu.be/Sj3wFCrHn6E?t=167 (Notice him spam clicking the flag from a distance and while being in stealth. He picks up the flag as soon as he is in range, and it breaks stealth automatically).

- Hard to find another good source since this was a complete non-issue in retail. So why would anyone discuss it?

**Comment by Azmoddan** [comment]
True.

**Comment by akrom23** [comment]
This video is not from TBC.
