### ISSUE TITLE
'Extra' Battleground queues for players should disappear after committing to joining one.

### ISSUE THREAD

**Issue by Dorkazera** [SunwellWoW/Sunwell-TBC-Bugtracker#3886]
**Description:** 
When joining a Battleground, the extra queues stay for the player after committing to joining one. This encourages people to join a different BG that pops if the one that you are in is not in favor of your faction. This issue is causing the majority(90%+~) of BGs starting as (e.g) 10v1 in favor of 1 or the other faction and/or ending prematurely.

**How it works:** 
When joining a Battleground, the extra queues stay for the player after committing to joining one. This encourages people to join a different BG that pops if the one that you are in is not in favor of your faction. This issue is causing the majority(90%+ ) of BGs starting as (e.g) 10v1 in favor of 1 or the other faction and/or ending prematurely.

This is seriously affecting the PvP scene and people's motivation to play BGs.

**How it should work:** 
After committing to join a BG that popped, all the other queues to BGs should disappear.

**Source (you should point out proofs of your report, please give us some source):**

**Comment by nkumnberlin** [comment]
Yes. Please Fix this, its really annyoing. Did tonight around 10 games, all except two Arathi Basin games shut down cause of imbalanced playercount.

**Comment by Zelfie** [comment]
Can confirm similar results.
Most of my battlegrounds tonight have lasted until completion, but only because you can cap and win a 10v2 before the timeout. And when we finally do have a full roster battleground, half disappear because another queue has popped.

**Comment by Zelfie** [comment]
Bonus points if you introduce an AFK/deserter system. It's exhausting reporting the same person AFKing in every battleground all day and night.

**Comment by nkumnberlin** [comment]
BUMP @Dootz

**Comment by Dorkazera** [comment]
This is a top priority issue in my books for a healthy server, should be labeled as Critical..

**Comment by Zelfie** [comment]
How is this still a thing? This makes 90% of battlegrounds unplayable shitshows.

**Comment by mjk6994** [comment]
this is blizzlike tho? lol @akrom23

**Comment by akrom23** [comment]
``How it should work:``
``After committing to join a BG that popped, all the other queues to BGs should disappear.``
Please, make up your mind...

**Comment by swordyxtwo** [comment]
you guys understand it's a custome change? Why this has been changed without any rational proof that it "should actually be changed?"

I recall it didn't work like that ever - and it didn't fix the BG situation, the only BG being run now is wsg as it has the least people required and pops out the most (making any other bg virtually non-existent)
