### ISSUE TITLE
Shaman Talent "Unleashed Rage" procs threat and shouldn't.

### ISSUE THREAD

**Issue by runt481** [SunwellWoW/Sunwell-TBC-Bugtracker#3890]
Description: 
The Enhancement Shaman "Unleashed Rage" talent procs threat and it shouldn't in patch 2.4.3

How it works: 
Unleashed Rage procs threat per target that gains the buff on each application of the buff.

How it should work: 
Unleashed Rage should not proc additional threat.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Unleashed_Rage

This additional threat was patched out in 2.0.10. It should not exist in 2.4.3
Enhance shams already have a lot of threat problems in TBC without adding this into the mix.

**Comment by badmannerkid** [comment]
ah, this might be something to look at here. enh shaman threat is through the roof and this could have a big impact on things. that and their mana spring along with the bursty nature of the spec makes them think about twisting tranquil on Nightbane

**Comment by akrom23** [comment]
Works fine,
