### ISSUE TITLE
Honor Hold Favor - Does not work, Bump cuz no fix in 20 days.

### ISSUE THREAD

**Issue by Elefant0n** [SunwellWoW/Sunwell-TBC-Bugtracker#3892]
Description: Does not grant % rep gain.

How it works: Does not grant more rep when used while in SHH (Tested)
Have not tried Ramparts or Blood Furnace. 

How it should work: It should increase rep gain by 25%
Mobs currently give 12 rep per kill as non-human.
Should give 15.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed, live
