### ISSUE TITLE
[Spell] Aquatic Form

### ISSUE THREAD

**Issue by ahlens** [SunwellWoW/Sunwell-TBC-Bugtracker#3893]
**Description:** 
There is a minor low priority bug I found when you jump out of water surface in [Aquatic Form](https://www.wowhead.com/spell=1066/travel-form#comments)

**How it works:** 
If you jump out of the water while swimming, the Aquatic Form remains. The other problem is that Aquatic Form remains for about 1,5-2,0 sec when you jump into terrain. 

**How it should work:** 
You should be changed back to humanoid form everytime you left water.

In the [comment section](https://www.wowhead.com/spell=1066/travel-form#comments), you will find information about that.

**Comment by akrom23** [comment]
#1973.
