### ISSUE TITLE
Vanishing mont after log out

### ISSUE THREAD

**Issue by Longus90** [SunwellWoW/Sunwell-TBC-Bugtracker#3898]
Description: 
Hi I was directed with my isse to this site by GM. Yesterday I purchased my first mount and riding skill in Unded location. I was playing about 20 minutes more after this purchase, I log out and log in again today and the mount is gone, same as the riding skill. The gold I spent on it did not come back. Character name in the game is Vaala, hope you can help.

Thanks.

**Comment by commo2k** [comment]
Hello everyone

I have the same problem as Longus90.

Last night around 22 o'clock I bought my flight mount + ride.
Then I went to Orgimmer and learned a few talents. So on the whole I still played 10-15 minutes until I went offline.
So this morning I log into the game and it's all three away

Gold away
Mount away
Learn to ride away

Please help

Nightbane / Orc Hunter / Character name: Rocco
