### ISSUE TITLE
Disappeared item

### ISSUE THREAD

**Issue by Djoooe** [SunwellWoW/Sunwell-TBC-Bugtracker#3899]
Description: Disappeared item

I got and equipped Serpentcrest Life-Staff from The Steamvault and subsequently vendored my old staff. Later that evening, I suddenly had no weapon equipped. It had totally dissapeared.

Server: Nightbane
Faction: Horde
Character: Djoe

**Comment by firngrod** [comment]
I have had this happen with shoulders (Rothide Spaulders from Razorfen Downs).  They dropped, I equipped them and sold the old ones.  Then later, I noticed that I wasn't wearing shoulders.

Character:  Adder

Possibly, this is linked to #3903?

**Comment by viktormassaro** [comment]
I also have the same problem fridaynight. Took me and some mates like 4 hours to clear Karazhan.
I got the Hat from Opera event and equipped it and sold my Head from the ghost shadowmoonvalley chain.
The next day i sign in (saturday) my headslot is empty. the head totally disepeard.
So annoying that i sold the other head also so now im one items short.
Please help me out as fast as possible i done a ticket ingame too!
Server: Nightbane
Faction: Aliance
Character: Vilmen
