### ISSUE TITLE
[Paladin][Alliance][Quest][Bug] Ancient Equine Spirit - Active before killing boss

### ISSUE THREAD

**Issue by F4play** [SunwellWoW/Sunwell-TBC-Bugtracker#39]
Description: Ancient Equine Spirit mob is shown in Diremaul despite the boss Tendris Warpwood being alive. 

Quest ID: 7643
Mod ID: 14566

How it works: Ancient Equine Mob standing near alive boss unmoving

How it should work: Once Tendris Warpwood is slain the mob should wander around the area in DM.

Source (you should point out proofs of your report, please give us some source): 
https://sites.google.com/site/paladinwarhorseguide/

**Comment by Dootz** [comment]
fixed some time ago
