### ISSUE TITLE
[Instance] The blood furnace

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#390]
You can't see through laughing skull rogues stealth even with being a much higher level. Their poison also stacks to 10 and lasts 30 seconds, should be 5 stacks and 15 seconds 

https://www.wowhead.com/npc=17491/laughing-skull-rogue#comments

Broggok- the fel orc neophytes are untargetable for the first several seconds after being released, a,d they all enrage instantly. There should be 1 enrage at start and 1 more for each wave, ie wave 2 has 2 enrages wave 3 has 3, etc.

https://www.youtube.com/watch?v=YRo_n25_zkk

Keli'dan the breaker is not using his "come closer and burn" ability.

**Comment by Silroth** [comment]
Laughing Skull Rogue stealth is intended, if you know their location you can pull them out of stealth with AOE spells, their Poison can stack up to 10 times even the other comment from wowhead confirms it can stack atleast 6 times.

Post updates in current Blood Furnace thread so its easier to track all the changes or what needs to be fixed.

**Comment by Riztazz** [comment]
As far as poison goes its intended. second part will be fixed with next ptr update, closing
