### ISSUE TITLE
Azure Silk Cloak recipe

### ISSUE THREAD

**Issue by Braderman88** [SunwellWoW/Sunwell-TBC-Bugtracker#3902]
Description: 
Brienna Starglow in Thalanaar, Feralas should sell the tailoring recipe for Azure Silk Cloak on a limited supply basis. She appears not to. This is as per TBC wowwiki and other sources.

How it works: 
Currently there is no recipe nor is there a recipe grayed out like one would expect on a limited supply basis.

How it should work: 
One should be able to purchase the tailoring recipe Azure Silk Cloan from Brienna on a limited supply basis. 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_122918_112657](https://user-images.githubusercontent.com/44547519/50537817-d500b180-0b5c-11e9-90f6-79958a7b4cef.jpg)
![wowscrnshot_122918_112704](https://user-images.githubusercontent.com/44547519/50537820-da5dfc00-0b5c-11e9-8296-f8200b87162d.jpg)

**Comment by Dootz** [comment]
fixed, live
