### ISSUE TITLE
Inferno warlock spell problem

### ISSUE THREAD

**Issue by MILITZIANU** [SunwellWoW/Sunwell-TBC-Bugtracker#3905]
Description: 
when i summon him hes enslave but he don`t follow and do nothing + some spells are missing ....

How it works: 

How it should work: 
Inferno is a warlock AoE spell that summons an Infernal and requires an [Infernal Stone]. Once the Infernal is summoned, it will automatically be under the effects of [Enslave Demon] for one minute, after which it will die. Inferno has a cooldown period of ten minutes. The Infernal has a permanent [Demonic Immolation Passive] aura that breaks CC. In Alterac Valley players tend to over estimate the Infernal's strength and can be used as a rather effective distraction target.

Inferno has a 100% spell power coefficient. 

Source (you should point out proofs of your report, please give us some source): 
 i was talken with gm Sykvii and he told me to report the problem

**Comment by ZaoQ** [comment]
Infernal is enslaved for 5min after that he is released and able to be reenslaved, cd of the spell is 60min so no 1 min and no dying :D and no 10mins cd.

no idea why u closed my report and left this one :DD

**Comment by akrom23** [comment]
@ZaoQ Because it's the same.

**Comment by akrom23** [comment]
Everything from this report works fine except power coef.
Stun effect reported by @ZaoQ will be fixed.

**Comment by ZaoQ** [comment]
Also almost each of his stat is wrong
Faction: Demon
Health: 13,273
Damage: 521 - 570
Attack Speed: 2000 ms
Damage School: Physical
Armor: 6792

https://tbc-twinhead.twinstar.cz/?issue=4462 https://db.excalibur.ws/?npc=89

quite corresponds with each other
