### ISSUE TITLE
Azure Silk Gloves

### ISSUE THREAD

**Issue by HasieEST** [SunwellWoW/Sunwell-TBC-Bugtracker#3906]
Description: Missing Recipe on vendor

How it works: Currently at least on alliance side Wenna Silkbeard doesn't sell the recipe

How it should work: She should Sell Pattern: Azure Silk Gloves

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?npc=2679
[https://imgur.com/a/dN0a3Vq](url)

**Comment by Dootz** [comment]
fixed, live
