### ISSUE TITLE
Stop Arena/BG Queue Announcements!

### ISSUE THREAD

**Issue by Caydan** [SunwellWoW/Sunwell-TBC-Bugtracker#3909]
It makes no sense to announce arena queue joins. It is annoying especially while primetime! If I disable system messages in chat I won't be able to read other announcements or addon system messages anymore. Please make it optional! This arena announcement is helpful for maybe 100 players out of 5000!

**Comment by notsofamous** [comment]
.acc bgann 

That will turn it off. That being said... This is a bugtracker, opinions are better expressed on discord or the forums.
