### ISSUE TITLE
[Shaman] Improved Ghost Wolf consumes NS

### ISSUE THREAD

**Issue by Dorkazera** [SunwellWoW/Sunwell-TBC-Bugtracker#3912]
**Description:** 
Casting Ghost Wolf with  (2/2 Improved Ghost Wolf) talent consumes Nature's Swiftness.

**How it works:** 
Casting Ghost Wolf with  (2/2 Improved Ghost Wolf) talent consumes Nature's Swiftness.

**How it should work:** 
Casting Improved Ghost Wolf (2/2) should not consume Nature's Swiftness.

**Source (you should point out proofs of your report, please give us some source):**

**Comment by zmthc93** [comment]
feel like it did this on live as well
source: shaman 1 trick vanilla - wotlk
