### ISSUE TITLE
Mobs Have 100% Block Chance - BUMP ISSUE SINCE EARLY BETA

### ISSUE THREAD

**Issue by YoshGit** [SunwellWoW/Sunwell-TBC-Bugtracker#3917]
Description: 
Mobs that are higher level than you have 100% block chance - likely due to bug in weapon skill formulas. This is a major handicap to all physical classes, tanks and those who are leveling especially who are forced to hit from the front.

How it works: 
Attacking mobs of higher level from the front results in all attacks that aren’t dodged, parried, or crit to be blocked.

How it should work: 
Not all mobs can block and mobs that can should have a reasonable chance to block in line with dodge/parries when attacked from the front.

Source (you should point out proofs of your report, please give us some source): 
#1631

**Comment by Roarek** [comment]
This also occurs for hunter ranged attacks, on my end every single higher-level mob facing me will block exactly 36 damage from all my physical damage sources. This is not normal, especially for it to occur on every single shot.
