### ISSUE TITLE
Viper Sting not working

### ISSUE THREAD

**Issue by Tjockisen** [SunwellWoW/Sunwell-TBC-Bugtracker#3922]
Description: 

Viper Sting doesn't work the way it should
<img width="1680" alt="skarmavbild 2018-12-30 kl 18 02 02" src="https://user-images.githubusercontent.com/46265465/50549438-3019cd80-0c5d-11e9-89d5-896e696991d8.png">
<img width="1680" alt="skarmavbild 2018-12-30 kl 18 02 05" src="https://user-images.githubusercontent.com/46265465/50549444-3e67e980-0c5d-11e9-8ecc-dfd5c41d7011.png">
<img width="1680" alt="skarmavbild 2018-12-30 kl 18 02 11" src="https://user-images.githubusercontent.com/46265465/50549446-458ef780-0c5d-11e9-9431-753f073c9c8d.png">
<img width="1680" alt="skarmavbild 2018-12-30 kl 18 02 13" src="https://user-images.githubusercontent.com/46265465/50549449-4889e800-0c5d-11e9-8ecd-d8ef792e02cf.png">

How it works: 

Viper Sting reduces my enemy's mana, but does not increase my own
How it should work: 

Viper Sting should both reduce my enemy's mana and increase my own 
Source (you should point out proofs of your report, please give us some source):

**Comment by YoshGit** [comment]
Source? My understanding is that this is actually correct behavior for tbc.

**Comment by notsofamous** [comment]
No... just no...

**Comment by Mikov1605** [comment]
It drains enemy mana, and gives the Hunter mana. Works like drain mana from warlock

**Comment by AshhSunwell** [comment]
Wrong xpac buddy

**Comment by Mikov1605** [comment]
https://wow.gamepedia.com/Viper_Sting_(hunter_ability)
Read The patch changes. Oh, and the Word "drain" means it leeches the mana to The Hunter. Worked on wotlk the same way, was removed on cata because its op

**Comment by firngrod** [comment]
Notice that the tooltip on the website indicates the mana restoration for the hunter while the tooltip in-game does not.  This also indicates that the patch notes are incomplete.  Nowhere do they say that the tooltip got changed, at least, which it clearly did.  Other omissions are likely to have occurred.

Looking through article history on wow.gamepedia's article for the ability, it becomes clear that this ability is working as intended:
[Wiki article on Viper Sting as of July 2008, four months before WotLK release](https://wow.gamepedia.com/index.php?title=Viper_Sting_(hunter_ability)&oldid=1513160)

Quote:
> Notes:  Although the game description says "Drain", it does not transfer mana to the caster.

EDIT:
Browsing through, the mana gain text was added to the wiki page March the following year, months after the release of Wrath of the Lich King.

**Comment by akrom23** [comment]
https://wow.gamepedia.com/index.php?title=Viper_Sting_(hunter_ability)&oldid=1513160
Works as intended.
