### ISSUE TITLE
Don Carlos Missing - OHF

### ISSUE THREAD

**Issue by sebastian-sl** [SunwellWoW/Sunwell-TBC-Bugtracker#3924]
Description: 
In the Caverns of Time Instance "Old Hillsbrad Foothills" there should be an NPC called Don Carlos with his wolf pet patrolling on the road. He usually starts his way at Southshore and is available in both difficulties (Normal and Heroic). He also should stand in Tanaris (near Gadgetzan) to give you the Quest "Nice Hat...".

How it works: 
He isnt at the spot hes supposed to be close to Gadgetzan and he is nowhere in the Instance. I walked the instance/road and try to target him anywhere but i couldnt find him.

How it should work: 
Like i said, he should patroll in the instance and be close to Gadgetzan in Tanaris.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=12513/nice-hat
https://www.wowhead.com/npc=28126/don-carlos
http://wowwiki.wikia.com/wiki/Don_Carlos
http://wowwiki.wikia.com/wiki/Quest:Nice_Hat...

**Comment by Dootz** [comment]
Hi according to wowhead he was added later in patch 2.4.3.
