### ISSUE TITLE
Lurker

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#3926]
- [ ] The whirl knockback isnt hitting melee, range is way too small.

- [ ] The Coilfang Guardians dont move at all

- [ ] Spout does no damage if you run straight through it.

- [ ] Geyser doesnt deal damage or knock you back

- [ ] Issues ressing people on top of the platform. They couldn't accept the ress, it just disappeared. Ressing from the water seemed to work.

**Comment by badmannerkid** [comment]
I believe the res issue has something to do with line of sight, we were having same issue. But yeah, be on death screen with release button, get ressed, press accept, stay dead with no release spirit option available. Upon relog you're sat at 15% HP at the coilfang GY as if you've just accepted a res, except you're outside the instance now
