### ISSUE TITLE
[Trash - Raid] Gruul Lair Issues

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#3927]
Description: 
1. Trash from the the begining of instance is respowning even if you kill HKM.
![wowscrnshot_123018_204736](https://user-images.githubusercontent.com/43553985/50551379-c232cd80-0c7f-11e9-91a4-c4bdb78e9d3d.jpg)

2. Each meele mob (Brute) is atacking all his skills from the start of fight in the same moment.
![aaaaaa](https://user-images.githubusercontent.com/43553985/50551453-d0cdb480-0c80-11e9-8685-fe2ca4781a03.jpg)

3. And the last part: Over and over again repetive Combat bug - almost after each single mob you killd.
 

How it works: 

How it should work: 
1. Trash dont respown after boss is dead.
2. Mobs use their abilities with global cd
3. No Combat bug.

Source (you should point out proofs of your report, please give us some source):

**Comment by Arom** [comment]
Gruul is also moving at 100% speed meaning a hunter can basically solo him - How is this not fixed so long after t4 has released?
