### ISSUE TITLE
Spawn bug

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#393]
New bug which seems to occur with recent core fixes.
Many of spawns (guid 0) are now neutral (they were hostile before and should stay hostile). Furthermore, they only chase players but don't attack them till player doesn't hit it.

Happened with Defias Pirate + Defias Companion, Antu'sul and his minion and much more.

![image](https://user-images.githubusercontent.com/22802214/45516318-02427300-b7ab-11e8-9c38-8496a255c61b.png)
![image](https://user-images.githubusercontent.com/22802214/45516515-9f051080-b7ab-11e8-9681-d62067bba523.png)
![image](https://user-images.githubusercontent.com/22802214/45516551-b643fe00-b7ab-11e8-8112-6ef6a37ea964.png)

**Comment by notsofamous** [comment]
Still neutral

**Comment by akrom23** [comment]
@notsofamous When did you test it?

**Comment by lukaasm** [comment]
Again, retest required :)

Creature totems/guardians should now have proper faction & pvp flags if summoned by a spell.

If NPC summons neutral mobs now, it is DB issue and needs to be fixed by hand in the database, for that please create a separate issue with a list of mobs.

**Comment by notsofamous** [comment]
Works!
