### ISSUE TITLE
Nether Vortex is BOE and can be traded to other players.

### ISSUE THREAD

**Issue by Sippiey** [SunwellWoW/Sunwell-TBC-Bugtracker#3937]
Description:  Nether vortex, the reagent to craft the tier 3 version of the black smithing weapons are tradeable which means anyone can just buy the best in slot weapons without raiding.

How it works:  Nether Vortex is tradeable.

How it should work: Nether Vortex should be binds when picked up, until late expansion 2.3+ or something. Just like Primal nether from heroics.

Source (you should point out proofs of your report, please give us some source): 
If you question this if this is how its suppose to be, i can only laugh.

**Comment by MarcusStu** [comment]
I can confirm this, dropped from TK trash earlier today.

**Comment by Tenoutoften** [comment]
http://web.archive.org/web/20080307234724/http://thottbot.com:80/i30183

**Comment by ghertruda** [comment]
pls fix ty

**Comment by Dootz** [comment]
fixed, live
