### ISSUE TITLE
[Quest] CLUCK!

### ISSUE THREAD

**Issue by firngrod** [SunwellWoW/Sunwell-TBC-Bugtracker#3939]
Description: 
It is possible to pick up this quest, but it is not possible to "activate" the chicken once you have the quest.  It is possible to turn it in if someone else activates the chicken.

How it works: 
As in the description:  It is possible to pick up the quest after /chicken'ing the chicken to friendly.  Immediately upon picking up the quest, the chicken goes rogue again.  While you have the quest, it seems impossible to friendly the chicken again.  If someone without the quest friendlies the chicken, you can then complete the quest.  The chicken cannot be friendlied once the quest is completed.

How it should work: 
Either it should be possible to activate the chicken while on the quest or the chicken should stay friendly for a while after you pick up the quest.

Source (you should point out proofs of your report, please give us some source): 
I could paste a loooooooong chat log of me /chicken'ing, but...

PS:  The egg that the chicken lays is also monstrously big.  Didn't get a screenshot of it.

**Comment by Piootrek** [comment]
You must /cheer on him while having complete quest.
