### ISSUE TITLE
Azaloth Freed

### ISSUE THREAD

**Issue by nhthor** [SunwellWoW/Sunwell-TBC-Bugtracker#3941]
Description: 
I got the Scroll of Demonic Unbanishing from a warlock, used the scroll on Azaloth and the quest didn't complete

How it works: 
I got the Scroll of Demonic Unbanishing from a warlock, used the scroll on Azaloth and the quest didn't complete

How it should work: 
The quest should be completed, as I "freed" Azaloth using the scroll...

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, from what i've heard, there's a bug where it doesn't say completed but if you freed him you can turn it this quest.

**Comment by Azathothh** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2671
