### ISSUE TITLE
Scroll of Protection doesnt stack with MotW

### ISSUE THREAD

**Issue by Lyn3452** [SunwellWoW/Sunwell-TBC-Bugtracker#3942]
Description: Scroll of Protection doesnt stack with MotW. It removes MotW and MotW removes the Scrollbuff

How it works: The Scroll overrides MotW and the other way around.

How it should work: The Scroll should stack like any other Scroll with all Raidbuffs.

Source (you should point out proofs of your report, please give us some source): 

https://www.wowhead.com/item=27500/scroll-of-protection-v#comments

**Comment by MarcusStu** [comment]
Same issue with all scrolls. They should stack. (Spirit, Protection, Agility)

**Comment by akrom23** [comment]
@MarcusStu 
https://wow.gamepedia.com/index.php?title=Scroll&oldid=1538436

> Scroll buffs do not stack with player buffs that affect the same stat.

#3872.
