### ISSUE TITLE
[NPC/Loot] Bloodpetal Trappers in Un'goro Crater are dropping Dinosaur Bones

### ISSUE THREAD

**Issue by blackwife** [SunwellWoW/Sunwell-TBC-Bugtracker#3945]
Description: When on "Roll the Bones" Dinosaur Bones are dropping from Bloodpetal Trappers.

How it works: Flowers drop dinosaur bits.

How it should work: Flowers are not dinosaurs, so they should not drop dinosaur bits.

Source (you should point out proofs of your report, please give us some source): 
Just killed one and looted it for a bone.

**Comment by Mikov1605** [comment]
TRAPPERS(other plants dont) MUST drop it, https://classicdb.ch/?npc=6512

**Comment by Mikov1605** [comment]
This is working correct, you can close it
