### ISSUE TITLE
Bugged quest - Drain Schematics

### ISSUE THREAD

**Issue by Imjustabear** [SunwellWoW/Sunwell-TBC-Bugtracker#3947]
Description: Hello, i've problem with quest from topic. I was in the place where i should be to complete quest. As you can see on screenshot quest dont want to be completed. Deleting "CACHE" folder didnt help.

How it works: Screenshot shows. 

How it should work: Quest should be complete in quest log. 

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/UhCPOSd

**Comment by Dootz** [comment]
Hi, i just tested it  on live and it works fine. Have you checked if you can return it to questgiver regardless of status in questlog? https://www.wowhead.com/npc=17841/ysiel-windsinger . It might be an addon issue (visual) but server should see it as completed.

**Comment by Dootz** [comment]
I don't see https://www.wowhead.com/item=24330/drain-schematics in you inventory. This item is required to complete this quest. If you removed it, it is possibly cause or your issue.

**Comment by Dootz** [comment]
closed due to lack of activity
