### ISSUE TITLE
Liquid Stone doesn't exist

### ISSUE THREAD

**Issue by Krinksx** [SunwellWoW/Sunwell-TBC-Bugtracker#3949]
Description: 
The quest Liquid Stone doesn't exist I have done the pre-rec quest but the option to pick up the quest just isn't there

How it works: 
You hand in Gyro... What?
and Liquid Stone does not become available to accept

How it should work: 
You hand in Gyro... What?
and Liquid Stone does become available to accept

Source (you should point out proofs of your report, please give us some source): 
https://db.excalibur.ws/?quest=715

**Comment by blackwife** [comment]
This quest has a side requirement of the earth elemental chain, have you also done those quests?

**Comment by Dootz** [comment]
Hi, there are few requirements for this quest to become available:
- minimum level of 35
completed quest https://www.wowhead.com/quest=712/study-of-the-elements-rock
and "Gyro... What?"

Then it is possible to pick up quest Liquid Stone from Lucien Tosselwrench (which is standing few yards behind Lotwil Veriatus).

If you have any questions please let me know.
