### ISSUE TITLE
Pet follows

### ISSUE THREAD

**Issue by Pizzle93** [SunwellWoW/Sunwell-TBC-Bugtracker#395]
Decription: 
Pet moves only when outranged

How it works: 
see above

How it should work: 
Should automatically and instantly follow

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
There is still an initial pet movement delay, but it should work better after:
https://github.com/SunwellWoW/Sunwell-TBC/commit/1d8bea9832212e39ec4314f59c5b2773296bbfc4

**Comment by Pizzle93** [comment]
Works great now, thank you
