### ISSUE TITLE
Herblism - Warp Splinter (normal)

### ISSUE THREAD

**Issue by JakeTheMFSnake** [SunwellWoW/Sunwell-TBC-Bugtracker#3954]
Description: 
Last boss in The Botanica Normal is suppose to be "herb-able" from a player with herblism.
When a player tries to herb the boss it says that the skill is too low.
But, a player with skinning instead, can skin the boss and get the herbs.
(Note that we had a skinner and herber in the group, with max skill)

How it works: 
Players with herblism gets the error message "Skill not high enough" even with full skill and it shows that you should be able to herb the Warp Splinter.
Players with skinning can instead skin the Warp Splinter. Shows that you can skin the target and it works.
Pics:
[https://cdn.discordapp.com/attachments/501054932577681424/529664783889334283/skinning.jpg](url)
[https://cdn.discordapp.com/attachments/501054932577681424/529683033750503424/WoWScrnShot_010119_145128.jpg](url)

How it should work: 
Players with herblism should be able to herb the Warp Splinter.
Players with skinning should not be able to herb the warp splinter.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/npc=17977/warp-splinter#herbalism

**Comment by NoMoreGoodNames** [comment]
Already reported 19 days ago and still not fixxed ...

https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3442
