### ISSUE TITLE
Grey mobs provide xp

### ISSUE THREAD

**Issue by Raivokaapio** [SunwellWoW/Sunwell-TBC-Bugtracker#3956]
Description: 
When I have killed grey mobs, they provide me xp. At least in Felwood. My char was lvl 58 and mobs were 47-48 grey to me. Same thing in feralas lvl 49 grey mobs

How it works: 
Mobs provide xp when killed. 

How it should work: 
Grey mobs shouldn't give any xp when killed.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_010119_202430](https://user-images.githubusercontent.com/44444594/50575243-57aa9a80-0e03-11e9-8fb8-ac6a4b18afb7.jpg)

**Comment by rcsikos** [comment]
Can confirm, experienced the same thing the other day in stv.

**Comment by koostosh** [comment]
Level 47 mob should provide xp to 58-level player. Works as intended
