### ISSUE TITLE
You can't send message of this type until you reach level 15

### ISSUE THREAD

**Issue by blackabbath** [SunwellWoW/Sunwell-TBC-Bugtracker#3957]
Description: 
Every action, every mob kill is accompanied by this annoying message https://i.gyazo.com/0c9ef8b328f7a2927c25071dad5f297a.png I'm not trying to send message or talk to anyone. But it displays! 8((((((((

How it works: 
https://i.gyazo.com/0c9ef8b328f7a2927c25071dad5f297a.png

How it should work: 
It should work **only once** when lowbies login to a character.

Source (you should point out proofs of your report, please give us some source):

**Comment by Donvito24** [comment]
If You using an addon, the addon did this. I talked with a GM and he says after You will reach lvl 15, this message will no longer there.

**Comment by blackabbath** [comment]
> If You using an addon, the addon did this. 

what addon? 0_0

**Comment by Donvito24** [comment]
I dunno. GM told me, if I use an addon, the addon did this.

**Comment by blackabbath** [comment]
yes, you were right - some addon have a conflict...
