### ISSUE TITLE
[NPC]Kargath Bladefist

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#3958]
Description: 
After killing him on normal mode, you remain in combat(because we didnt killed some mobs,that he spawns,  and they disappeared)

How it works: 
After killing him, his spawned adds disappear, but u keep combat.

How it should work: 
After defeating him, all his adds disappear, and you get out of combat

Source (you should point out proofs of your report, please give us some source):

**Comment by zanthed1** [comment]
This also happens on Heroic Mode. Slightly unrelated to the original topic but he will also sometimes go through the ground while casting his charge + cleave. He resets after some time underground and cannot be attacked.
