### ISSUE TITLE
Instacasting cheater

### ISSUE THREAD

**Issue by Yzzomrots** [SunwellWoW/Sunwell-TBC-Bugtracker#3962]
Description: 
River (47 Female Dreanei Hunter) came to try to steal the mining nodes I was at. I attacked and began the usual routine. (I was 49) He pet immuned my Freezing trap which was weird but what really jumped out was she was instant casting a 1.5 second cast ability called Scare Beast by passing any interrupts from damage (including pet) or racials. I do have a screenshot showing my pet hitting her as she is casting.

How it works: 
Scare Beast is a 1.5 second cast only usable on beasts which can be interrupted by receiving damage.
How it should work: 
Scare Beast is a 1.5 second cast only usable on beasts which can be interrupted by receiving damage.

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?spell=14327

**Comment by notsofamous** [comment]
This is a bugtracker, not a place to report player abuse. Make an in game ticket instead.

**Comment by Yzzomrots** [comment]
They refer ppl to the bugtracker

**Comment by koostosh** [comment]
Could not reproduce
