### ISSUE TITLE
[Item] Scryer's Bloodgem and Xi'ri's Gift. 

### ISSUE THREAD

**Issue by zanthed1** [SunwellWoW/Sunwell-TBC-Bugtracker#3963]
Description: Scryer's Bloodgem and Xi'ri's Gift put the same 'Spell Power' buff on you for 150 spell power and 280 healing for 15 seconds. 

How it works: The two trinkets don't share a cooldown besides the 15 second default CD on trinkets, however when trying to activate the other after the 15s it will tell you "Spell is not ready yet". The item is not displayed as CD but it is unusable.

How it should work: You should be able to use the trinkets 15 seconds after each other.

Source (you should point out proofs of your report, please give us some source): https://gyazo.com/1cdc44ce6f38f995a9fb8a3f1a7215da

**Comment by Twistwarp** [comment]
When is this going to be fixed? these are quite good entry level trinkets so kinda good that they work!

Edit: I think it is because the 2 trinkets use the same buff id or something.
