### ISSUE TITLE
Windfury totem has ICD while imbued windfury does not.

### ISSUE THREAD

**Issue by Sippiey** [SunwellWoW/Sunwell-TBC-Bugtracker#3965]
Description: Windfury totem shouldn't have any internal CD as it only procces on Auto attacks anyways and can't procc on itself. 

How it works: Right now it has 3 sec ICD or maybe more who knows. You can't get back to back windfury thats for sure.

How it should work: Windfury totem should have no internal cooldown, but imbued windfury should have 3 sec internal, which it does not. I'm playing a fury warrior right now and im only able to get windfury for half of the amount that i should. 

What this means right now is that Enha shaman without ICD(or much lower than 3s) on their imbued windfury are insanely much stronger than they should be. Rets are getting the full benefit of WF since their attack speed is above 3, while a fury warrior with dual wield will miss out on atleast half of the windfury proccs. 

These windfury issues along with Crusader strike proccing SoB/C which has been reported 3 weeks ago, makes enha and rets much stronger than intended compared to a fury warrior/rogue.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Windfury_Totem?oldid=1431588
" It will ONLY trigger on white (auto-attack) swings, and cannot trigger off itself. 
The Windfury proc from the totem does not have a hidden cooldown like Windfury Weapon"

Make my class relevant, thank you.

**Comment by FrauHolle86** [comment]
keep me in loop =)

**Comment by Kiszh** [comment]
Can confirm, WF totem barely ever procs despite the fact that it shouldn't have an ICD, outside of not being able to proc off itself. 

http://web.archive.org/web/20081019205344/http://elitistjerks.com:80/f47/t15809-shaman_windfury/

Edit with old EJ thread showing WF totem having no ICD (see the first table). The post also stipulates that WF weapon should have and ICD of 3 seconds that covers both weapons, regardless of which procs WF.

**Comment by SolitudeFTW** [comment]
I can confirm. When will this be fixed?

**Comment by Kiszh** [comment]
This bug is so absurdly gamebreaking, it's documented and it's been a month while quest RP scripts are being fixed. Please fix it.
