### ISSUE TITLE
Mind controled mobs not showing abilities on action bar

### ISSUE THREAD

**Issue by maseta9** [SunwellWoW/Sunwell-TBC-Bugtracker#3967]
Description: I've been noticing since I runned Gnomeregan that the mobs you control with the priests Mind Control don't allow you to use the abilities they should have available. An example are the dwarves from Gnomeregan, which have the ability to drop mines, but the only ability available is to attack. Another example of this is a mob found within the Botanica that is supposed to allow you to buff up your character with a lot of spell power. It's a great handicap for MC.

How it works: Mind controlled mobs won't allow you to use their abilities (they don't show up in the action bar)

How it should work: Abilities from a mind controlled mob should show up on your action bar as you cast the spell on them.

Source (you should point out proofs of your report, please give us some source): http://wowwiki.wikia.com/wiki/Bloodwarder_Mender this is the botanica mob. I don't have proof right now from inside the game, I will however comment a screenshot later.

**Comment by Azmoddan** [comment]
Bump.
