### ISSUE TITLE
Jewelcrafting

### ISSUE THREAD

**Issue by Solarmight** [SunwellWoW/Sunwell-TBC-Bugtracker#3968]
Description: Jewelcrafting

How it works: While crafting a Thorium Setting it takes away 3 Thorium Bar, while the recipe requires only 1 Thorium Bar.

How it should work: It should only cost 1 Thorium Bar instead of 3

Source (you should point out proofs of your report, please give us some source):

**Comment by syk7** [comment]
The Change was implemented in a later patch
