### ISSUE TITLE
Quest Problem "The rethban's challenge"

### ISSUE THREAD

**Issue by Brollaf** [SunwellWoW/Sunwell-TBC-Bugtracker#3969]
Description: Quest

How it works:  When I launch the quest, my game freeze "wow isn't responding anywmore". Can't play cause my game bug the same suring each downloading. I have to wait one hour (in order quest timer fall and i failed the quest) if i want to play again on the server.

How it should work: 
 Normally the quest should begin normally and i could reach it :p !

Source (you should point out proofs of your report, please give us some source): 

hard to proof it cause my game isn't playable during one 1h after i launch the quest.

**Comment by Dootz** [comment]
Hi,
unfortunately i was not able recreate your issue. I would start with checking your questlog. Please check if you have other quests that have to be completed within specific time period. If you have them (probably on "Failed") please remove it. Next i would disable all addons. If above fails please contact us here with your character's name and we will try to help you in-game.
