### ISSUE TITLE
Pet speed

### ISSUE THREAD

**Issue by Pizzle93** [SunwellWoW/Sunwell-TBC-Bugtracker#397]
Decription: 
Pet speed doesn't match owner speed (try backpeddaling, pet still goes at normal speed)

How it works: 
see above

How it should work: 
Should match speed of owner

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC/commit/1d8bea9832212e39ec4314f59c5b2773296bbfc4

**Comment by Pizzle93** [comment]
Works great now, thank you
