### ISSUE TITLE
Leotheras the Blind Demon Form

### ISSUE THREAD

**Issue by Proseccobabe** [SunwellWoW/Sunwell-TBC-Bugtracker#3972]
Description: Leotheras the Blinds demon form Inner Demon cast is interruptable

How it works: You kick the spell and he won't cast it in that demon form anymore.

How it should work: You should not be able to interrupt it.

Source (you should point out proofs of your report, please give us some source): 
Idk man. Can't find it. Just happened in our raid tho

**Comment by ghertruda** [comment]
Whirlwind in human form doesnt stack after application,inner  demons are CCable, Summoners infront of Leotheras are stunnable

**Comment by ghertruda** [comment]
Leotheras in demon form is counterspellable

**Comment by leylandpaladin** [comment]
![image](https://user-images.githubusercontent.com/45656368/50632981-a9b20400-0f5a-11e9-9717-83cfbe465c8d.png)

Meleeing during whirlwind sometimes also
