### ISSUE TITLE
Missing mobs on path of conquest

### ISSUE THREAD

**Issue by leylandpaladin** [SunwellWoW/Sunwell-TBC-Bugtracker#3978]
Description: 

Eclipsion soldiers and Eclipsion Spellbinders particaly missing in Path of conquest, making it harder to farm them.

How it works: 

![path of conquest](https://user-images.githubusercontent.com/45656368/50634245-0b746d00-0f5f-11e9-9c93-f33201cce0e3.jpg)

Mobs are missing in zone marked on map

How it should work: 

Mobs should be there

Source (you should point out proofs of your report, please give us some source): 

Check their spawn locations

https://www.wowhead.com/npc=22016/eclipsion-soldier

**Comment by Wojtyas** [comment]
I assume they were simply killed :o all of creatures are present there and have 5min respawn timer.

![image](https://user-images.githubusercontent.com/22802214/50639831-1fba6900-0f63-11e9-806a-8c8dbd9d6282.png)

**Comment by leylandpaladin** [comment]
Your shot is from upper part of the mountian, i ment place down the road, and it's empty even on ur screenshot, i'm farming this place for hours every day and I can't be wrong, I did that on all tbc realms I ever played. Pls open ticket again and double check that. I marked area I wanted you to check on your screenshot. On my shot there is also lava stream, on urs this lava steam is too far. You checked wrong place.


![50639831-1fba6900-0f63-11e9-806a-8c8dbd9d6282](https://user-images.githubusercontent.com/45656368/50641879-6bc4d800-0f7a-11e9-9b90-a4ae04dfed6d.png)




BONUS: some videos from probably retail, dude making quest and there is tons of mobs on area i'm trying to describe

https://www.youtube.com/watch?v=rnMQtGgvGl0

Asmongold's netherweave farming guide also shows this place

https://www.youtube.com/watch?v=ZJKrMWe-t-Q&list=PLJIZi_sHIbr0kx_--utZpdJF1AsN62I27

Please don't be that quick on your decisions.
