### ISSUE TITLE
Pet runs behind owner

### ISSUE THREAD

**Issue by Pizzle93** [SunwellWoW/Sunwell-TBC-Bugtracker#398]
Decription: 
Pet runs behind owner

How it works: 
see above

How it should work: 
Pet should run beside owner

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC/commit/1d8bea9832212e39ec4314f59c5b2773296bbfc4

**Comment by Pizzle93** [comment]
Works great now, thank you
