### ISSUE TITLE
Containment Beam in Shadow Labyrinth

### ISSUE THREAD

**Issue by Pikseh** [SunwellWoW/Sunwell-TBC-Bugtracker#3981]
Description: 
![containment beam](https://user-images.githubusercontent.com/3406509/50641656-f3095000-0f68-11e9-9885-e68ef491a89f.png)
In room where you fight the first boss in Shadow Labs, if you use Avenger's Shield on the caster mobs that stand around the pillars, the last shield charge spins off into the roof hitting an invisible mob called "Containment Beam". These beams are what keep the boss banished until all the caster mobs are killed, but it should not be targetable by any spells, not Avenger's Shield either. This was tested in the normal mode of the dungeon. See the combat log of the linked image to see that two of the three casters are hit, but that the last caster is not hit; instead the "Containment Beam" is hit.

How it works: 
Avenger's Shield bounces onto an invisible mob in the roof instead of hitting the last caster (there are three casters per pillar)

How it should work: 
The invisible "Containment Beam" should not be targetable by spells. It should not even be considered a mob.

Source (you should point out proofs of your report, please give us some source):

**Comment by zanthed1** [comment]
This also occurs with Chain Lightning.
