### ISSUE TITLE
Gnomish death ray trinket

### ISSUE THREAD

**Issue by medduz** [SunwellWoW/Sunwell-TBC-Bugtracker#3983]
Description: 
The gnomish engineering trinket "Gnomish death ray" is still not working. Even though changelog entry # 1023 says its effect is "scripted"

How it works: 
Damages your HP, nothing else.

How it should work: 
Damage your HP then fire a burst dmg "beam" at you opponent.

**Comment by RealSlyGuy** [comment]
Second this issue. I just basically murder myself every time I use it, which is sucky, cuz it is an awesome trinket!
