### ISSUE TITLE
[The Tempest Keep] Void Reaver

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#3987]
- [ ] Void Reaver sometimes casts his threat knockback ability on the person that is 2nd on threat instead of the primary threat target

- [ ] Stomp range is large, probably intended to avoid the "sweet spot" tactic

- [ ] Threat table on him needs looking at very closely. Its very finicky and somehow we had a ranged pull threat even though they were 16th on the meter. We used both Omen and Diamond Threat Meter

TRASH:

- [ ] Crystalcore Devastators hit tanks for around 24k arcane damage. One shots them. Needs to be tuned down.

**Comment by notsofamous** [comment]
There is not supposed to be a "sweet spot" tactic, just a common bug on many TBC servers.
