### ISSUE TITLE
[Hunter][Pet] Weird pull/aggro

### ISSUE THREAD

**Issue by Iperyth** [SunwellWoW/Sunwell-TBC-Bugtracker#3992]
Description: 
During Kara run, for some reason my pet pulled mobs from huge distance from which it should not be able to. First time it was through the wall from the room next to us while I was AFK for couple of minutes. Friend of mine noticed that whole pack run to the pet, killing it and running to me.
2nd time it pulled pack from the other side od corridor, while standing BEHIND the line of totems near to the rest of the group. Regardles of being always on passive, after it's death pack aggroed me which (as far I know) shouldn't take place.

**Comment by firngrod** [comment]
I have experienced some similar issues with pets and agro.  It seems like their agro range is larger than players'.  At the time, my pet was a lower level than myself, so I put it down to that.  I presume that wasn't the case for you?

I am not certain, but I don't think I remember ever having a pet get agro while just walking around in retail, so I think there was some sort of agro range reduction formula in place for pets, and this is possibly off here?

**Comment by ozzmann** [comment]
I also keep experiencing this wierd pet aggro range. +Sometimes when your pet dies close to the mobs --> Revive Pet from lets say 40yd of the mobs --> Mobs aggro your pet instantly after Revive Pet.

**Comment by Iperyth** [comment]
> I also keep experiencing this wierd pet aggro range. +Sometimes when your pet dies close to the mobs --> Revive Pet from lets say 40yd of the mobs --> Mobs aggro your pet instantly after Revive Pet.

Yeah, happened to me few time as well. 



> I have experienced some similar issues with pets and agro. It seems like their agro range is larger than players'. At the time, my pet was a lower level than myself, so I put it down to that. I presume that wasn't the case for you?
> 
> I am not certain, but I don't think I remember ever having a pet get agro while just walking around in retail, so I think there was some sort of agro range reduction formula in place for pets, and this is possibly off here?

Since I lost my previous pet b/c stable bug (no refunds) I tried to lvl up highest lvl ravager, which is 63. Aggro range is so huge and XP gain so low that it makes it almost impossible to  lvl it up all the way to 70. And it was supposed to get 70 in a week just by doing just daily quests...
