### ISSUE TITLE
Tabard vendor doesn't have option to recover tabards

### ISSUE THREAD

**Issue by Tepmaister** [SunwellWoW/Sunwell-TBC-Bugtracker#3994]
Description: 
Tabard vendor in Orgrimmar doesn't have option to recover your lost tabards. I accidently deleted my Purple Trophy Tabard of the Illidari after doing the quest The Battle of the Crimson Watch. And tabard vendors should be able to recover your tabards you lost.

How it works: 
Tabard vendor has only vendor when you click on her.

How it should work: 
Tabard vendors should be able to recover your lost tabards. She even has the chat cursor on her when hovered, but still only has the vendor option.

Source (you should point out proofs of your report, please give us some source):

**Comment by MadderThenMad** [comment]
I don't think there was a feature like this in TBC

**Comment by kinglobster** [comment]
wotlk feature, unlucky for ur tabard tho
