### ISSUE TITLE
[Raid] Instantly get saved to raid IDs with no warning

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#3997]
Description:  If you enter a raid while in a raid group that has a different ID even though yours is fresh, you will automatically get saved to that ID regardless if the raid leader is inside or not.

How it works:  No warning about being saved. You can instantly get saved to a fully cleared raid and screw yourself out of a weekly lockout.

How it should work: Should have a warning or 1 min countdown for locking people into a raid ID. This is incredibly frustrating that this can even happen. Please look at ways to fix this as soon as possible as it can be detrimental to the server.

Source (you should point out proofs of your report, please give us some source):

**Comment by Eternae1** [comment]
Please note, there is no warning or message to click yes or no on. It instantly saves you without your choosing.

**Comment by Scipios** [comment]
This is TBC, this feature was only implemented with WotLK.

**Comment by Eternae1** [comment]
Alright well I made a ticket about it and the GMs said "raid group probably clicked accept for ID lockout by mistake" we didnt click accept or yes to anything, just instantly got saved and screwed out of a week's lockout. No response on discord either.

**Comment by Scipios** [comment]
> the GMs said "raid group probably clicked accept for ID lockout by mistake" 

I guess the GM didn't know that you don't have this feature in TBC.
