### ISSUE TITLE
[SPELL] Improved Healing Wave

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#4]
Decription:  each of talent point should reduce casting time of healing wave by 0.1s

How it works: each of talent point of Improved Healing Wave (5/5) reduces casting time of Healing Wave by 0.2s instead of 0.1s, which means resto shaman gain extra 0.5s spell casting reduction

How it should work: each of talent point should reduce spell cast by 0.1s

Source (you should point out proofs of your report, please give us some source): 
talent description

**Comment by Azathothh** [comment]
related with #3 i believe :P

**Comment by Kokaina** [comment]
Fixed.
