### ISSUE TITLE
[Paladin][Alliance][Quest][Bug] Divination Scryer Item Causes DC/Rollback

### ISSUE THREAD

**Issue by F4play** [SunwellWoW/Sunwell-TBC-Bugtracker#40]
Decription: Divination Scryer Item (ID: 18746) causes DC/Rollback. Part of the paladin charger quest line, specifically quest name "Judgment and Redemption" (ID: 7647)

How it works: Head to scholomance, specifically rattlegore's room (rattlegore ID#: 11622), use quest item in the middle of the room, causes DC/Rollback at the end of the cast of the Divination Scryer Item

How it should work: At the end of the cast an event where four different types of spirits spawn in waves will begin. 
They are Banal, Malicious, Corrupted, and Shadowed Spirits. Several of one type will appear throughout the room. Paladins are most useful in this fight because judging specific seals will do an AoE damage to nearby spirits and stun them for 4 seconds. Each spirit is weak to a specific seal.

Once the Aspect of Shadow is killed Death Knight Darkreaver will spawn, you fight him and once he's killed you can talk to Darkreaver’s Fallen Charger to redeem him and complete the Judgment and Redemption quest

Source (you should point out proofs of your report, please give us some source): 
https://sites.google.com/site/paladinwarhorseguide/
https://www.youtube.com/watch?v=ajs1iV28eQE - Video from 10 years ago

**Comment by akrom23** [comment]
Already fixed.
