### ISSUE TITLE
[NPC] Arcane Guardian

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#4002]
Description: 

https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3971
How it works: 
You closed it to fast, wrongly. Please look at it and correct

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, i receive email notifications when you reply. I saw your message. I'll re-check it today :)

**Comment by Mikov1605** [comment]
Didnt knew that, sorry ;)
