### ISSUE TITLE
An enchant done in trade window doesn't show

### ISSUE THREAD

**Issue by username-is-not-taken** [SunwellWoW/Sunwell-TBC-Bugtracker#4004]
Description: 
When enchanting an item through trade window, the enchant does not show up in the "will not be traded" item slot where the item to be enchanted is placed. The enchant is also done right away, rather than when both parties agree to the trade.

How it should work: 
Item to be enchanted is placed in the "will not be traded"-slot -> Enchant is done in the trade window (but not applied) -> Both parties agree to the trade -> After the trade is successful, the enchant is applied and tips etc are exchanged.

Source (you should point out proofs of your report, please give us some source): 
I don't have any prints right now (except for people thinking I'm scamming them by not enchanting their items), but I'll edit and add one when I can remember to print.

**Comment by Eternae1** [comment]
Enchanters can also get screwed over if its their mats, people can wait til you chant their gear and cancel trade, walking away with an enchanted piece of gear for free.

**Comment by ZaoQ** [comment]
just be persistant on them to give you gold beforehand, solution until fix
