### ISSUE TITLE
Mysterious Arrows/Bullets Non-existent

### ISSUE THREAD

**Issue by Filosof93** [SunwellWoW/Sunwell-TBC-Bugtracker#4010]
Description: 
TBC's first epic projectiles are not available on Nightbane.
It should be available since both SSC and TK is out. Right now Hunters are using level 68 projectiles, gimping their DPS in higher-tier raiding by a bunch.
How it works: 
It is not existing on the server. Eventhough we are basically on patch 2.2.0 (TK & SSC)

How it should work: 
It should be sold by Apprentice Darius outside Karazhan and in later patch also in Shattrath. Price from Apprentice Darius should be 1G for 200 arrows/Bullets. It requires Revered with The Violet Eye to Equip/Buy.

Source (you should point out proofs of your report, please give us some source): 
Raiding T5 content with blue arrows should tell the tale on its own.

**Comment by notsofamous** [comment]
SSC and TK are both patch 2.0, karazhan ammunition was added in 2.3 (ZA patch)
