### ISSUE TITLE
Had arena points taken away, never got it back.

### ISSUE THREAD

**Issue by GreendayTBC** [SunwellWoW/Sunwell-TBC-Bugtracker#4011]
Description: 
So after last weeks reset I had gotten my arena points under "PVP", but after a few days when my friend still hadn't recieved his points, I looked under PVP and saw that it was rerolled/taken away which lead to me only having 1 week of arena points instead of 2.. and havent gotten a proper answer or fix from GM's - but they told me to make a bugtracker for a developer to check this problem?? Aka I had 600 arena points, but now im back to 1st weeks cap of 295 ish.. pls help before tmrws reset ^^

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
GM's told me to do a bug tracker report, cause they had no power over the system in that way or something...

**Comment by akrom23** [comment]
Write ticket ingame - this is not bug.
