### ISSUE TITLE
RIP. [Druid Bleed]

### ISSUE THREAD

**Issue by mjk6994** [SunwellWoW/Sunwell-TBC-Bugtracker#4012]
Description:  Rip is STILL not scaling from Attack Power. Considering this is the most used ability of Feral DPS, it's making them extremely shitty in both Arena in PvE.

How it works: There is no attack power scaling with Rip.

How it should work:  Should scale with attack power. 

Source (you should point out proofs of your report, please give us some source):  https://cdn.discordapp.com/attachments/432981313117618217/531053471009472515/unknown.png 
https://cdn.discordapp.com/attachments/432981313117618217/531053587757924353/unknown.png

Here, we have a rip damage without a Terestians Staff and one with which is the equivalent of fucking 1082 attack power and it still only hits for 101. 

Also, when are you guys gonna fix fucking Harolds Brooch? Also, stop tagging shit "Resolved not yet implemented" then never doing anything with it and claiming "THIS MANY BUGS FIXED" whattajoke

**Comment by Kittykatreporter** [comment]
Can you please give any proof that bleeds should scale DYNAMICALY with ap? As far as i remember, bleeds back in tbc scaled only when re-applied ( like in tiger's fury case ).

**Comment by Cherryxo** [comment]
Rip should NOT scale dynamically. Rip should work like other DoTs and be snapshotted. 

Quick example I found is https://youtu.be/Ok3hD-_Zuno?t=489 (a reupload of https://www.warcraftmovies.com/movieview.php?id=78801) at ~1:45 you can see that he is using a trinket which gives AP on use. At the time linked you can see that he opens up on a warrior and pops his trinket, he applies rip and it's ticking (with trinket up) for 364. At 8:25 the trinket effect runs out and just after that you can see the rip is still ticking for 364.

**Comment by Kittykatreporter** [comment]
@akrom23 pls review this again and don't "fix" anything without legit proof...

**Comment by mjk6994** [comment]
@Kittykatreporter You're right it shouldn't scale DYNAMICALLY. But it doesn't scale AT ALL. Both of these dots were applied seperately. zzzzzz both of you need to stop. thx

**Comment by mjk6994** [comment]
Good thing i said DYNAMICALLY somewhere in my post tho. jk. didnt once.

**Comment by mjk6994** [comment]
https://cdn.discordapp.com/attachments/432981313117618217/532654040564367374/unknown.png

https://cdn.discordapp.com/attachments/432981313117618217/532654134499868682/unknown.png

Notice both don't scale at all. There should be 6% per point. And with 2433 AP, level 1 rip should do 445.98 over 12 seconds. While level 5 should be doing 1675.92.

Before you try to reject a bug, use your head, thanks.

**Comment by Cherryxo** [comment]
based on your shitty evidence you provided in OP it's a legit conclusion to draw when reading the post. stop being an ass and focus on the issue instead.

**Comment by Cherryxo** [comment]
???? I'm simply responding to the guy above me. you need to take a chill pill and focus on the issue instead of being an ass.

**Comment by Kittykatreporter** [comment]
Next time think about putting a COMBAT LOG in such reports, cuz from screenshots it looks like you put 1 rip and swap staff. No one tries to reject a bug, and no one said about rip is scaling properly atm.

**Comment by mjk6994** [comment]
@Kittykatreporter Shut the fuck up and let the devs do their jobs.

**Comment by mjk6994** [comment]
> ???? I'm simply responding to the guy above me. you need to take a chill pill and focus on the issue instead of being an ass.

And nah dude, it's annoying to deal with bug fixes left and right that ain't even bug fixes making shit worse from people who don't know what they're talking about or devs implementing shit that shouldn't even be implemented. For Example, the whole Seer Udalo mob that should be in normal Arc, but isn't because some said it shouldn't be so they took him out with confirming. Let's not forget the numerous shit that's in that shouldn't be in til 2.1, prisons etc. Let's take a look at numerous bugs that are marked as resolved, and not yet implemented and still havent been "implemented" a month later. And then actual bugs that haven't been fixed, like mobs in Gruul's 1 hitting because MStrike isn't on GCD. 

I have every right to be pissed about a server I've invested money and time into.

**Comment by mjk6994** [comment]
Holy shit, looks good man. @akrom23 I'd kiss you if i could.
