### ISSUE TITLE
Swamp Gas in SteamVault

### ISSUE THREAD

**Issue by Bugadin** [SunwellWoW/Sunwell-TBC-Bugtracker#4013]
Description:  There should be a Swamp gas close to Mekgineer Steamrigger which is definitly not there.

How it works: 

How it should work:  Swamp Gas has also been found regularly near Mekgineer Steamrigger in the Steamvault instance.

Source (you should point out proofs of your report, please give us some source): 

http://wowwiki.wikia.com/wiki/Swamp_Gas

**Comment by Wojtyas** [comment]
There are Swamp Gases in Zang as intended. Have any proof it should be near location u mentioned?

**Comment by Bugadin** [comment]
The last 2 servers I played had this swamp gas. Also, it's said in the wiki: ''Swamp Gas has also been found regularly near Mekgineer Steamrigger in the Steamvault instance.''
It was located in the second's boss platform.
