### ISSUE TITLE
Warrior melee hit range bugged

### ISSUE THREAD

**Issue by Xvixxx** [SunwellWoW/Sunwell-TBC-Bugtracker#4015]
Description: 
warrior hits through walls and his melee hit range is to large

How it works: 

that they cant hit through pillars or hit someone from 20 yards away

How it should work: 

should be normal melee range not range 

Source (you should point out proofs of your report, please give us some source):

**Comment by Bugadin** [comment]
I reported this since beta but, instead of chek it, it was closed.
Melee's range, sometimes at some situations, gets bugged and u hit some yards far than you should.

**Comment by akrom23** [comment]
@Xvixxx Screenshot, please.

**Comment by Bugadin** [comment]
> @Xvixxx Screenshot, please.

Details here:
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4023

**Comment by zmthc93** [comment]
its not just warriors it is all classes as far as I know

**Comment by akrom23** [comment]
So it's duplicate?
