### ISSUE TITLE
Crafting. inventory full bug

### ISSUE THREAD

**Issue by Krys23** [SunwellWoW/Sunwell-TBC-Bugtracker#4016]
Description: 
I recently "created" well tried to create a Arcanite Bar. Then found out my bags were full yet it proceeded to create. 
TL;DR I was left with a 1 day cd and loss of mats and no Arcanite Bar. Down 20g at level 44.

How it works: 
Currently when you create a item through professions when your bags are full the item vanishes to god knows where. 

How it should work: 
When you attempt create something and your bags are full it shouldnt create

Source (you should point out proofs of your report, please give us some source): 
Try it right now :)

**Comment by firngrod** [comment]
#3379

**Comment by Wojtyas** [comment]
Already working on it, its on our internal BT marked as prio.
