### ISSUE TITLE
' Into the Depths' doesn't work

### ISSUE THREAD

**Issue by blackabbath** [SunwellWoW/Sunwell-TBC-Bugtracker#4017]
Description: 
This quest is unable to turn-in. No effect when you trying to turn-in at altar at Sunken Temple.

How it works: 
While interacting to the altar, it write some text about statues dependence, but it's unable to complete the quest. It doesn't matter you did correct statues interaction order or not; no matter what you do: statues first or go directly to altar.
https://i.gyazo.com/a8441b5cd262d66342ff5cd1d082aa5a.jpg

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by firngrod** [comment]
I was just down there.  Instead it offered me to complete the Chained Essence of Eranikus quest, which I had already completed.  Something funny going on.
