### ISSUE TITLE
Tar Creepers does disarming too often

### ISSUE THREAD

**Issue by blackabbath** [SunwellWoW/Sunwell-TBC-Bugtracker#4018]
Description: 
Mobs like **Tar Creepers** and **Tar Beasts** located at Lakkari Tar Pits @ Un'Goro does disarming too often.

How it works: 
They cast 'Sticky Tar' every 1-3 seconds which causing impossible for melees to kill them solo.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Duplicate https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3228
