### ISSUE TITLE
Hellboar's buff is bugged [Hellfire Peninsula] [a lot of damage at 1 time]

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#4019]
Description: 
Starving Hellboar buff makes a lot of damage when you hit this boar. It looks like these boars have multiple copies of this buff.

How it works: You hit the boar one time and get a lot of 24 damage hits.

How it should work: You hit the boar one time and get only one 24 damage per hit.

Source (you should point out proofs of your report, please give us some source): 
![hellboar](https://user-images.githubusercontent.com/46404642/50727869-52668c00-1132-11e9-982b-84a8529c49d7.png)

**Comment by Wojtyas** [comment]
Duplicate https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2439
