### ISSUE TITLE
Bug: Amplify Curse not consumed when using Curse of Agony/Doom

### ISSUE THREAD

**Issue by kyotpls** [SunwellWoW/Sunwell-TBC-Bugtracker#4020]
**Description:** 
When _Amplify Curse_ is used, followed up by _Curse of Agony_ or Curse of Doom, the _Amplify Curse_ still persists, even if Agony is refreshed or reput several times to Mob A and even Mob B.

**How it works:** 
As stated in the description, when you pop "Amplify Curse" followed up by _Curse of Agony_ or _Curse of Doom_, the _Amplify Curse_ buff is not consumed and still persists.

**How it should work:** 
When Amplify Curse is used, and then followed up by a _Curse of Agony_ or _Curse of Doom_ it should consume the buff and apply the 50 % increased effect to your spent Curse.

**Source (you should point out proofs of your report, please give us some source):** 
https://gyazo.com/24be39b08ff1d6af357e6cc0bbb20b4d (Curse of Agony)
https://gyazo.com/63ba3b64dfb286abb7441ea1f8009120 (Curse of Agony + Curse of Doom)

However the "Amplify Curse" is consumed when using _Curse of Exhaustion_:
https://gyazo.com/6da16e79994eaddb35a5682a087ccbc2

**Comment by Thalles777** [comment]
I'm having the same issue. It worked fine up until level 63 and now it doesn't consume the buff when used.
