### ISSUE TITLE
Pyroguard Emberseer encounter

### ISSUE THREAD

**Issue by edekk** [SunwellWoW/Sunwell-TBC-Bugtracker#4022]
Description: 
Pyroguard Emberseer encounter does not work.

How it works: 
When you click Blackrock Altar, nothing happens.

How it should work: 
When you click Blackrock Altar, mobs surrounding Pyroguard Emberseer should aggro and then, when you're done with them, you should click altar once more to activate the boss itself.

Source (you should point out proofs of your report, please give us some source): 
![pyroguard](https://user-images.githubusercontent.com/23091085/50733118-85873a80-1187-11e9-9ad0-cb58315c7224.jpg)

https://imgur.com/aA3JwhW

**Comment by Dootz** [comment]
according to newer report still needs some work. Should be doable after next server update. I'll close this report as one mentioned before refers to whole instance and lists more bugs.
