### ISSUE TITLE
Melee autoattack's bug when kiting

### ISSUE THREAD

**Issue by Bugadin** [SunwellWoW/Sunwell-TBC-Bugtracker#4023]
COPY PASTE FROM WHAT I WROTE A MONTH AGO IN TEST SERVER BECAUSE IT KEEPS HAPPENING.
Description:
Melee range seems to work decently but there is a bug at kiting, which is a bit difficult to reproduce, that happens when players fights at melee range. The bug has to do with melee range but it's not the same as that bug that happened to all melees 1 week ago.

How it works: When you are fighting at melee range and you kite your enemy (you slow him and go back a bit to avoid his damage) the last autoattacks before players separate keeps landing on each other a few miliseconds. The number of AA that someone land on the other depends on your speed attack: As a rogue, I can land him 2-3 AA and the warrior lands me 1 most cases.
Then, range turns correctly again until you try to kite again.

How it should work: At melee range, if a player kites other, the last autoattacks right after you separate from the other player shouldn't land on the enemy in both cases( enemy to me or viceversa). The autoattack's animation should get canceled until enemy player is in range again.
This is an annoying bug that turns some matches(mage vs warr, rogue vs warr, hunter vs any melee... and so on) nearly impossible.

Source (you should point out proofs of your report, please give us some source):

https://ibb.co/HPBT422 On this picture, we can see that the rogue avoid the warrior's AA and lands him
a critic
https://ibb.co/6rx8gL6 On this one we can se the warrior's AA animation and how the rogue avoid it.

https://ibb.co/dBG9tqz Same case but we both parry.

**Comment by akrom23** [comment]
This is called melee leeway?

**Comment by Bugadin** [comment]
> This is called melee leeway?

Yes, it's called melee leeway. The bug here(and I know now what is exactly wrong) is that, if you or your target becomes slowed more than 29% of normal speed melee leeway mechanic HAS TO STOPPED.

This guy explains it VERY WELL. Please, read it all because it's a huge problem in PvP:

https://vanilla-twinhead.twinstar.cz/?issue=8237


**PROOFS ON SUNWELL**: https://gyazo.com/1c3b18abebecf4a4427ff38f8e26e646
Work as intended, both players are running and I can hit him.



https://gyazo.com/1474a14c1392f323b7e1e5168cc5c2f2
https://gyazo.com/ea67aa02046c28a14c9eef3d0b2938a8
This is **NOT** correct because I'm hitting him even when he is slowed to 70%

Thank you for your support.

**Comment by akrom23** [comment]
Thanks for explanation :)

**Comment by Bugadin** [comment]
No problem. I managed to explain it better when I realized that this(which I knew there was something wrong but I wasn't able to explain it well) has a name and is called ''melee leeway''

Please, check this one too where I added proofs of what was going wrong
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4005
