### ISSUE TITLE
Stealth breaking

### ISSUE THREAD

**Issue by Feorblade** [SunwellWoW/Sunwell-TBC-Bugtracker#4025]
Description: 

Stealth is breaking when standing near or in buildings that are on fire (for example in Alterac Valley or Old Hillsbrad Foothills)
How it works: 

described above
How it should work: 

stealth should not break
Source (you should point out proofs of your report, please give us some source):

**Comment by Azmoddan** [comment]
Can be somehow related to #198 and I think it is not a bug, since burning buildings should deal a small amount of damage just as a bonfire I guess? Gotta check it.

**Comment by akrom23** [comment]
#3530
