### ISSUE TITLE
Talents that reduce silence duration not working when locked, only on blanket silences >GAMEBREAKING ARENA BUG< 

### ISSUE THREAD

**Issue by zmthc93** [SunwellWoW/Sunwell-TBC-Bugtracker#4029]
Description: 
Talents that reduce silence duration not working when locked by an interrupt spell, only on blanket silences.
The talents I know for sure are not working are 'Improved Concentration Aura' for Holy Paladin and 'Focused Mind' for Resto Shaman.
I believe the talents are working as intended for 'blanket' silence effects like 'Silence' and 'Improved Counterspell' only.
Similar talents I have overlooked or item 'Talisman of the Breaker' may also not be working but I have not tested or seen proof of these.

How it works: 
Talents which reduce duration of silence mechanics are not applied when interrupted.
EXAMPLE
I am casting a healing wave, I get counterspelled. The default nature lockout time from counterspell is 8 seconds. With 3/3 in 'Focused Mind' talent the nature lockout should be 5.6 seconds. On this server it remains 8 seconds even with these talents.

How it should work: 
When you are interrupted on cast the lockout time should be reduced by 30% as talent states.

Source (you should point out proofs of your report, please give us some source): 
Here is a video provided by player Kada demonstrating bug clearly from Holy Paladin perspective:
https://www.youtube.com/watch?v=W-dBRNIaHyk

**Comment by zmthc93** [comment]
>High Priority
>10 days ago
>no one assigned

you guys all playing on netherwing too?

**Comment by akrom23** [comment]
@zmthc93 Got some proofs from retail?
It says about DURATION of EFFECT (read: aura duration), not lockout of specific spell.
Silence duration is properly reduced.
Lockouts are done independently by interrupt effect.

**Comment by zmthc93** [comment]
hi, the proof is that it says 'Interruption' effect,
if it was only meant for silence effect this word would not be included in the tooltip

**Comment by zmthc93** [comment]
but I can tell you that it reduced lockout time on live, will find proof now

**Comment by akrom23** [comment]
Not needed - should be fixed.

**Comment by zmthc93** [comment]
many thanks keep up the good work!
