### ISSUE TITLE
Spawn issues

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#403]
Hi there,
I detected few issues with spawning pets/guardians with recent core fixes.

1. Master 8127 -> Summon 8156
Till recent updated master was summoning 4x 8156 creatures on pull. For now he spawns only one of them tho his pull yell is doubled. Seems like he just can't have more of those creatures at once.

2. Master 7337 -> Summon 8477
In this case, summon is present even when master is out of combat and should stay/walk with his master as script says. Till recent fixes, everytime master was loosing that kind of pet, he revived it after evade. For now he doesn't revive it and also looks like he can summon this pet only once.

3. Master 13282 -> Summon 13456
In this case, master is a boss who split (disappear) into few spawns and when they are defeated he appears back again. He split spell has some cooldown and he may use it even few times in a single battle. Till now, everytime he used that he appears back again when spawns were dead. For now, when he uses his split spell for the SECOND time then no spawns appear. It breaks boss entirely cuz he doesn't appear no more but combat is present. So I once again believe in that his spawns may be summoned only once.

**Comment by lukaasm** [comment]
> Master 8127 -> Summon 8156
> Till recent updated master was summoning 4x 8156 creatures on pull. For now he spawns only one of them tho his pull yell is doubled. Seems like he just can't have more of those creatures at once.

Dootz changed script from EventAI to SmartAI

> Master 7337 -> Summon 8477
> In this case, summon is present even when master is out of combat and should stay/walk with his master as script says. Till recent fixes, everytime master was loosing that kind of pet, he revived it after evade. For now he doesn't revive it and also looks like he can summon this pet only once.

Should be fixed after
https://github.com/SunwellWoW/Sunwell-TBC/commit/fc56559eafa45d2797a1fc3b489ec5e18f03f049

**Comment by akrom23** [comment]
Need test!

**Comment by notsofamous** [comment]
1. Works.

2. He does summon a new pet, however his pet doesn't attack you if you just attack the master. 
video: https://i.gyazo.com/31735f7a733c2aa1d38c61dc33004147.mp4

3. Works, tested him through several phase changes.

**Comment by lukaasm** [comment]
This fix is not live yet :(

**Comment by notsofamous** [comment]
14 hours ago!!!! add the tag when you want me to test!

**Comment by lukaasm** [comment]
Tagging after-commit, so I don't forget :P I will try to defer tagging after an update.

**Comment by notsofamous** [comment]
Works no, but minions despawn as soon as the master is killed. The minion should stay alive and keep fighting until they get out of combat.

**Comment by Wojtyas** [comment]
Fixed & implemented.
