### ISSUE TITLE
Spell Reflection not totally working (Warrior)

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#4034]
a spell that you spell reflected is not shown as damage done by you (the spell doesn't belong to the warrior, he should) and therefore isn't building threat.

**Comment by MiekZer** [comment]
http://wowwiki.wikia.com/wiki/Spell_Reflection

Bc icon Patch 2.1.0 (22-May-2007): Reflected spells generates threat as if the damage were dealt by a normal attack. Also, this threat is subject to the usual threat multipliers granted by Defensive Stance and/or Defiance. This change was not officially noted, but it has been confirmed by several players.

**Comment by neheri** [comment]
I've been reflecing a lot and it definitely gives warrior aggro. Not sure about to who damage belongs though.

**Comment by MiekZer** [comment]
Ok after retest I have the feeling that it's giving threat on some spells and not on some other spells.
If I reflect a DOT it looks like it's not giving threat.
When I reflect a spell it's working? (but giving low threat ?? should give more in defensive stance maybe?)

**Comment by MiekZer** [comment]
After many retests I could see a threat bump only when reflecting in mechanar the first hit of the robot when he's charging. I'm not even sure we're supposed to be able to reflect that since it's a buff on him making extra damage magic on attack.
On every other spells there is literally no threat or such a small amount of threat that it's not noticeable if it really was the spellreflect or your auto attack.

**Comment by neheri** [comment]
As for me, reflect gives significant amount of threat, I've been reflecting in mecha, SV, even SP to hold slave casting mobs. It's usually enough to keep them off healer. Would need to test with debug command though to check that, If I have time today will go to SV and see.

**Comment by MiekZer** [comment]
Used .debug threatlist to check various spell reflects and due to the reflected spell not belonging to the warrior (you can check on combat logs and various damage meter that the reflected spell doesn't appear) it's not submitted to defensive stance extra threat generation

**Comment by akrom23** [comment]
Tested - works good.
In defensive stance:
![wowscrnshot_022719_123648](https://user-images.githubusercontent.com/1035215/53487687-84d69a80-3a8c-11e9-92e3-3051f885cd4f.jpg)

In battle stance:
![wowscrnshot_022719_123718](https://user-images.githubusercontent.com/1035215/53487696-8607c780-3a8c-11e9-8235-d38d5eba43e8.jpg)
