### ISSUE TITLE
Pet cant spent focus

### ISSUE THREAD

**Issue by Snikeyxo** [SunwellWoW/Sunwell-TBC-Bugtracker#4035]
Description: 
My pet is bugged, wont use any spells or focus, no abilities in pet skill tap.

How it works: 
My pet will only attack, and use spells not related to focus

How it should work: 
My pet should work 

Source (you should point out proofs of your report, please give us some source): 
My hunter Rako (Orc) Pet = Alex (70 ravager). my 2 other stabled pet work fine.

**Comment by edekk** [comment]
There used to be a bug when you would use a macro consisting of couple of buffs like Rapid Fire, Bestial Wrath, trinkets etc. That would bug the pet making it use no skills. Quick resolve would be to command your pet to follow and /petattack right after. 

I bet your pet is using skills normally when engaging into combat but bugs out at certain circumstances. 

Please provide more feedback if bug persist regardless.

**Comment by Snikeyxo** [comment]
I found out later last night that my pet has unlearned all of its abilities, however they were still showing on my pet bar. But if I go to spell book and into pet tab, it's empty, and I think it started when I tought my pet it's final ability, sending it to 0 training point's. It's a huge problem as the pet will only auto attack, kill command, and stun.

Get Outlook for Android<https://aka.ms/ghei36>

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
