### ISSUE TITLE
Druid Alterac valley flag cap bug URGENT

### ISSUE THREAD

**Issue by RarecandyMage** [SunwellWoW/Sunwell-TBC-Bugtracker#4036]
Description: 
Druids are re-capping the flags in the alterac valley bunkers in stealth and CAPPING THE FLAG DOES NOT BREAK STEALTH...
CRITICAL BUG FIX URGENT
How it works:  DRuid begins to cap flag in stealth.  Does not break stealth.

How it should work: DRuid begins to cap flag in stealth.  Stealth should break.

Source (you should point out proofs of your report, please give us some source):

**Comment by mjk6994** [comment]
cant replicate at all

**Comment by zmthc93** [comment]
think there is some interaction with shadowmeld saw a night elf druid doing it yesterday at stormpike aid station

**Comment by akrom23** [comment]
Got screenshots?

**Comment by akrom23** [comment]
No response.
