### ISSUE TITLE
[NPC]Mo'Arg Weaponsmith

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#4037]
Description: 
He should drop Legion teleporter device with a 30% chance.

How it works: 
Killed 12 of them, no device. I guess loot chance is lower or im just a pretty unlucky person.

How it should work: 
https://wotlk-twinhead.twinstar.cz/?npc=19755

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Seems to be working fine for me. But we'll increase it a bit from next update.
