### ISSUE TITLE
Last restart may have cause item deletion

### ISSUE THREAD

**Issue by Zodddd** [SunwellWoW/Sunwell-TBC-Bugtracker#4039]
Description: 
item deleted after last server restart

How it works: 
Had a healing cloak which without a doubt was there

How it should work: 
Should still be in backpack because didn't vendor it or disenchant

Source (you should point out proofs of your report, please give us some source): 
i dont have any before/after pictures, but upon this change some items were mailed back to me. my assumption is that this one item was missed out from that process? my healing staff and another item were returned with a customer support tag

**Comment by BugReporterupper** [comment]
it's not a bug it's called server roleback unfortunately
