### ISSUE TITLE
Execute warrior 

### ISSUE THREAD

**Issue by nikolajdt** [SunwellWoW/Sunwell-TBC-Bugtracker#4041]
Description: 
The warrior spell Execute hits for less than its supossed to.
I'll upload a screenshot of a "normal" execute hit, and if you want more screenshots of it then i'll gladly provide it. 

How it works: 
After i swapped from using 2x 1h weapons to my 2h weapon from my level 30 class quest, execute dropped from doing around 150-200 damage to 70-100 damage. I already tried to clear cache folder, swap weapon again and so on, but nothing seems to change it. 
![executehit](https://user-images.githubusercontent.com/46456349/50786688-84076080-12b4-11e9-950f-a2e2acce30d1.PNG)

How it should work: 
It should hit a minimum of 125 damage, + 3 damage for each rage point consumed. 
![execute](https://user-images.githubusercontent.com/46456349/50786699-89fd4180-12b4-11e9-81b4-8edab4e4da85.PNG)

Source (you should point out proofs of your report, please give us some source):

**Comment by babno** [comment]
armor is a thing that reduces damage.

**Comment by nikolajdt** [comment]
So your basicly trying to tell me that every mob ive fighted from level 31-34 (got the new execute spell which seems to hit for atleast the ammount it supposed to) got enough armor to reduce my damage around 40-75% procent? As i said, even if i had 80 rage and did an execute then it still would only hit for around around 90 damage. 
125+(35*3) = 230 
230/90 = 0,39
which basicly means i did 39% of the total damage, so the mob must had an armor making it reduce 61% damage?

**Comment by babno** [comment]
Most mobs do have 30-40% armor. I was mostly bringing up that your statement of "It should hit a minimum of 125 damage, + 3 damage for each rage point consumed." is wrong as it doesn't take into account armor, and that the screen shot of the combat log looks perfectly fine taking that into account.

**Comment by foxxhound** [comment]
That is indeed damage pre-mitigation. Armor is significant especially on most mobs. I can assure you, Execute his as intended, especially on players. I.e. Getting executed for 4 - 6k.
