### ISSUE TITLE
Bug: Fear costing the same in all ranks

### ISSUE THREAD

**Issue by kyotpls** [SunwellWoW/Sunwell-TBC-Bugtracker#4042]
**Description:** 
Warlock's _Fear_ costs the same amount of mana in all ranks. This is incorrect. It should cost different amounts of mana considering which rank is being used. This is crucial for PVP to be using lower mana cost on Rank 1 _Fear_ just like druids using Rank 1 _Entangling Roots_ or Mage using Rank 1 _Frostbolt_ or _Polymorph_

**How it works:** 
In the spellbook on the spell tooltips it says that all ranks of _Fear_ costs the same, even Rank 1 and Rank 3. This is not how spells are supposed to work in TBC. In TBC there is different **duration** and **mana cost** on spells. Rank 1 lasts 10 sec, Rank 2 lasts 15 sec and Rank 3 Lasts 20 sec (in PVE). Whilst in PVP all ranks have a duration of 10 seconds. So there should be a benefit to use Rank 1 (lower mana cost)

**How it should work:** 
_Fear_ should have different mana cost dependant on which rank you use. I don't know the excact numbers on what each rank should cost (I'm hoping you guys can find this as I could not). But please fix this for us.

**Source (you should point out proofs of your report, please give us some source):** 
https://gyazo.com/028b2faf5d2b85c21448884a5d2b48dc

**Comment by notsofamous** [comment]
Source? It could be the same as resurrection spells, all ranks cost the same amount of mana.

**Comment by firngrod** [comment]
Wiki article on Fear as of just before Wrath launch:
https://wow.gamepedia.com/index.php?title=Fear&oldid=1641758
Spell costs 12% of base mana, meaning all ranks should cost the same.

**Comment by kyotpls** [comment]
That is incorrect, that page is showing spell costs as of retail. Just look at mage frostbolt i.e:

https://wow.gamepedia.com/Frostbolt

It says 2 % of base mana, which is not the case in TBC. All spells in retail is based around your base mana pool.

**Comment by kyotpls** [comment]
I've seen several videos and pages telling to use rank 1 in PVP scenarious. This is one example I've recovered:

https://gyazo.com/4a251980a27272187a34469b2fe02b8d

**Comment by firngrod** [comment]
You have linked the current BFA version of frost bolt.  All spells were normalized this way at some point.  Looking at the article as it was during BC, we see that the ranks had fixed mana costs at that time.

Same article as of August 8th 2008:
https://wow.gamepedia.com/index.php?title=Frostbolt&oldid=1565718

**Comment by firngrod** [comment]
Did a little more browsing of the Fear Wiki article.  It appears that the rank mana cost equalization happened around March of 2008.  This article will have updated after the in-game change.  Wrath was released in November.

Last version of the article with rank dependent mana cost:
https://wow.gamepedia.com/index.php?title=Fear&direction=prev&oldid=1278777

EDIT:
This explains BC guides including the rank dependent mana cost.  When the guide was written, this was the case, but it was patched away before 2.4.3, which is the patch Sunwell.pl is emulating.

**Comment by firngrod** [comment]
Basically, one should reference the latest versions of wiki articles before October 2008 (Patch 3.0.x released on October 14th 2008).

**Comment by Wojtyas** [comment]
This is up to 2.4.3 client version.
