### ISSUE TITLE
[Quest] Cipher of Damnation - Ar'tor's Charge

### ISSUE THREAD

**Issue by peanutcheese** [SunwellWoW/Sunwell-TBC-Bugtracker#4043]
Description: 
quest ID 10540
upon accepting quest NPC won't spawn me a spirit guide (yes I checked for debuff)

How it should work: 
the NPC should spawn you a spirit guide that can find veneratus the many for you

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
weird I just accepted this quest and received debuff + npc spawned. From what i understand neither happend for you yesterday?

**Comment by Dootz** [comment]
another player accepted it on mount and spirit spawned without problem. Weird, maybe server reset fixed it.

**Comment by Mikov1605** [comment]
It does work
