### ISSUE TITLE
[Dungeon] Gatewatchers in heroic mech aren't dropping badges

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#4044]
How it works: They drop only a key piece

How it should work: They should drop a badge of justice for everyone when on heroic mode.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/gMaDUFgxbgk?t=566

**Comment by Mikov1605** [comment]
They should drop a key piece since 2.3, both. Then u combine the pieces and You can open "Cache of the Legion". Up To admins if they allow these guys To drop badges till patch 2.3 or if they leave it. 
Source: 
https://www.wowhead.com/npc=19218/gatewatcher-gyro-kill
Comment section

**Comment by Wojtyas** [comment]
Confirmed, we will change it. **HEROIC** only.
