### ISSUE TITLE
Warlock pets wont auto-attack on defense mode for yellow enemys

### ISSUE THREAD

**Issue by toeofjesus** [SunwellWoW/Sunwell-TBC-Bugtracker#4047]
Description: 
Warlock pets (have tried Imp and Voidwalker) when using defensive stance for pets, pets will not attack yellow mobs if you engage first. Pet will only attack if you do it manually. This only occurs on yellow enemy's. (red enemy's work perfectly) 

How it works: 
When pet is on defensive stance and I engage a yellow enemy, pet will not engage and will sort of glitch  to the side of me. Pet will not attack unless I manually press the attack button on the pet hotbar. 

How it should work: 
Pet should attack yellow enemy when on defensive stance when I engage enemy  or get attacked by enemy. 

Source (you should point out proofs of your report, please give us some source): 
Try this on a warlock with your pet out and engage a yellow-named enemy (enemy that is netural) Pet will not attack enemy unless you manually do so on pet action bar.

**Comment by kyotpls** [comment]
Same happens to me. I've noticed that warlock pets never attack themselves most of the time in defensive stance one combat is entered. This clarifies my suspicion.

**Comment by Azmoddan** [comment]
As a warlock I can confirm and it is pretty annoying.
