### ISSUE TITLE
[Dungeon] Steamvault

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#405]
### **Trash:**

- [x] 1. Coilfang Warrior base damage should be 1177-1664, when engaged uses all abilities properly.

- [x] 2. Coilfang Siren base damage should be 1092-1543, when engaged uses Lightning Bolt but Arcane Flare is used very rarely, never casts Fear (Spell ID 38660) spell.

- [x] 3. Coilfang Engineer base damage should be 1177-1664, when engaged uses all abilities properly.

- [x] 4. Bog Overlord base damage should be 3282-4641, when engaged uses all abilities however it doesnt try to cast Fungal Decay to stack it but waits till the debuff wears off before casting it again. Should be immune to all CC.

- [x] 5. Coilfang Myrmidon base damage should be 1177-1664, when engaged uses Cleave but does not use Execute (Spell ID 7160) when their target is below 20% health or Sweeping Strikes. Comments mention should be immune to Mind Control, not sure about other forms of CC such as fear, snare, root etc.

- [x] 6. Coilfang Oracle base damage should be 1092-1543, when engaged uses all spells properly.

- [x] 7. Tidal Surger base damage should be 1289-1821, when engaged uses all abilities properly.

- [x] 8. Steam Surger base damage should be 351-496, when engaged uses all abilities properly.

- [x] 9. Coilfang Sorceress base damage should be 1092-1543, when engaged uses all spells properly.

- [x] 10. Coilfang Slavemaster base damage should be 1177-1664, when engaged uses all abilities properly.

- [x] 11. Dreghood Slave base damage should be 706-999, when engaged does not use Enrage ability at all. They should reset aggro every few seconds.

- [x] 12. Coilfang Leper base damage should be 410-579, when engaged uses some of abilities, should have https://db.excalibur.ws/?npc=21338#abilities 

### **Bosses:**

- [x] 13. Hydromancer Thespia base damage should be 1576-2227, when engaged uses all abilities properly.

- [x] 14. Coilfang Water Elemental base damage should be 351-497,  when engaged uses Water Bolt Volley however its doing only 380 damage, comments mention it should deal 700-1000 damage on normal.

- [x] 15. Mekgineer Steamrigger base damage should be 2091-2957, when engaged uses all abilities properly.

- [x] 16. Steamrigger Mechanic base damage should be 570-700, during combat uses all abilities properly.

- [x] 17. Warlord Kalithresh base damage should be 1699-2403, when engaged only uses Spell Reflection, he should use Impale on random target on his threat list that ticks for 500 on normal (if Impale is recast on same target it should stack up to 3 times), Head Crack on main target and the Naga Distiller event is missing.

**Comment by Anselm123** [comment]
Is there any sources for the damage for the trash and such you're quoting? Because just running this in t5 equivilent gear and getting auto'd for 1-1.8k a mob is kinda lul worthy

**Comment by Anselm123** [comment]
it's basically going to force any group to be 3 CC or GTFO which completely fucks over progression into raiding tiers if you can't easily have your shamans and stuff in 5 mans heroics for attunements

**Comment by Kokaina** [comment]
@Anselm123 Whole stats (dmg+hp) are taken from prenerf notes so they may be slightly, or even sometimes significantly increased. Thats why we put them on beta tests to see how people can handle those things. TBH personally im not also a big fan of putting a lot of massive changes on dungs but focus on well scripted mechanics. I'm pretty sure we will consider if its worth to make dungs such hard on our main realm.

**Comment by Anselm123** [comment]
Well i'll have more experience come today we're going to do some more today and see. But we had t5 equivilent gear and i was getting hit pretty hard with 60% reduction, will be pretty overtuned for blues/few epics even with 3 cc. 

You need to tuned this shit around having 1 cc, we can't progress into T5 if our non cc dps can't go into heroics.
