### ISSUE TITLE
Nalpak

### ISSUE THREAD

**Issue by Alkimor** [SunwellWoW/Sunwell-TBC-Bugtracker#4051]
Description: NPC Nalpak don't have a quest - Deviate Hides - quest for Wailing Caverns

How it works: 

How it should work: NPC Nalpak must take this quest without prequest, and this quest don't have a prequest

Source (you should point out proofs of your report, please give us some source): 
https://classic.wowhead.com/quest=1486/deviate-hides#comments
![74820-deviate-hides](https://user-images.githubusercontent.com/30193603/50843050-08231c00-1379-11e9-8900-62241530c0cb.jpg)

**Comment by Dootz** [comment]
Hi, I just checked it on live and it appears to work correctly without any prequests.  All you need is level 13 Horde character.
![obraz](https://user-images.githubusercontent.com/25490436/50850807-43bee580-137b-11e9-9a91-e376da68c0af.png)

**Comment by Alkimor** [comment]
In TBC this quest only for the Horde?

**Comment by Dootz** [comment]
hmm... i guess there was a time when tauren druid - Nalpak offered quest for horde and night elf - Ebru for alliance. But since Deviate Eradication is accessible for horde I don't see any reason to not allow Alliance to pick up Deviate Hides. Thanks for pointing it out
