### ISSUE TITLE
Amitel

### ISSUE THREAD

**Issue by Amitel** [SunwellWoW/Sunwell-TBC-Bugtracker#4053]
Description: 
going to the body, I fell beyond the map as a ghost and can not get back to the map,cane you help me pls

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, I'm not sure if this issue is still relevant because I found that you logged out in Shattrah. Just to make sure that you're there i summoned you few yards further. If it ever happens again you can use teleport option on our website.
