### ISSUE TITLE
 [Dreadsteed of Xoroth]

### ISSUE THREAD

**Issue by Konyagi** [SunwellWoW/Sunwell-TBC-Bugtracker#4056]
Description: 
Completing the quest in Dire Maul

How it works: 
After summoning the dreadsteed, the lord spawns together with 2 dreadsteeds. After killing the lord and the 2 dreadseeds the spirit of the dreadsteed attacks aswell insted of giving the option to turn in. I have completed the quest but the spirit is dead so can't turn in

How it should work: 
After summoning the dreadsteed there should only spawn a dreadsteed, after killing the steed the lord spawns to fight with and the spirit should be spoken to so you can turn in quest.

**Comment by Konyagi** [comment]
Do you have an estimate when the fix will be live?

**Comment by Dootz** [comment]
I hope it'll be on live tomorrow. It's waiting for update :(

**Comment by Konyagi** [comment]
I could complete the quest after the fight, but it still spawns 2 dreadsteeds insted of 1.
