### ISSUE TITLE
Bug Pet.....

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#4065]
Description: 
 I would like to report a bug with the hunter's pet. Because it can not be fed and disappears after a few minutes.

How it works: 
There is no application in the spellbook to feed the pet. And pet should not disappear after a few minutes.

How it should work: 
It should not disappear. When he feeds pet he is happy.

Source (you should point out proofs of your report, please give us some source): 
The source is that I am playing with a hunter and the pet should not disappear and in spellbok there should be an application where the pet is fed ....

**Comment by firngrod** [comment]
Did you complete the second half of the quest, sending you to the trainer in your main city, where you should learn the Feed Pet skill, among others?

**Comment by ghost** [comment]
> Description:
> I would like to report a bug with the hunter's pet. Because it can not be fed and disappears after a few minutes.
> 
> How it works:
> There is no application in the spellbook to feed the pet. And pet should not disappear after a few minutes.
> 
> How it should work:
> It should not disappear. When he feeds pet he is happy.
> 
> Source (you should point out proofs of your report, please give us some source):
> The source is that I am playing with a hunter and the pet should not disappear and in spellbok there should be an application where the pet is fed ....
