### ISSUE TITLE
Swapping weapons

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#407]
Swapping weapons should reset the swing timer to prevent abuse of fast attack speed weapons.

**Comment by akrom23** [comment]
I believe it works fine. Some proofs?

**Comment by notsofamous** [comment]
Classic wow demo: https://i.gyazo.com/8c40040dfd148b114ffe50251d3d289f.mp4
Auto attacks never start because swing timer is reset with each weapon swap

Sunwell: https://i.gyazo.com/5fda9f2621c78e763a0445814687f90f.mp4
Auto attacks keep happening even if you spam swap weapons
