### ISSUE TITLE
Mass dispel causes output from sealth / prowl

### ISSUE THREAD

**Issue by Grasswalker** [SunwellWoW/Sunwell-TBC-Bugtracker#4070]
Description: 
Mass dispel causes output from sealth / prowl
How it works: 
Mass dispel causes output from sealth / prowl
How it should work: 
Mass dispel causes combat in priest and rogue or druid in sealth and dispel buffs only like wild, thorns.
Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/spell=24450/prowl
"Prowl - School | Physical"
https://www.wowhead.com/spell=1784/stealth
"Sealth - School | Physical"
this is not a magic buff that you can dispel

**Comment by firngrod** [comment]
This was apparently how it worked prior to 2.2.0 where it was changed to no longer remove stealth.  As such, it should not dispel stealth on this server.

https://wow.gamepedia.com/index.php?title=Mass_Dispel&oldid=1637411

**Comment by Bugadin** [comment]
Actually, it removes stealth and it shoouldn't.

**Comment by Devrak** [comment]
Yes it should not , however i remember reading somewhere that if a rogue has a buff that gets mass dispeld then stealth is also broken, later it was deemed a bug and changed, not sure about the timing.

**Comment by akrom23** [comment]
#3764.
