### ISSUE TITLE
Enemy HP is displayed incorrectly

### ISSUE THREAD

**Issue by Ituhdudu** [SunwellWoW/Sunwell-TBC-Bugtracker#4071]
Description: 
Enemy HP should be displayed as a % value and not as an integer.

How it works: 
Currently enemy HP is displayed as an exact value.

How it should work: 
Enemy HP should be displayed as a % of their total health.

Source (you should point out proofs of your report, please give us some source): 
Many people believe this was changed in patch 2.3 http://wowwiki.wikia.com/wiki/Patch_2.3.0
however, the change in patch 2.3 only applies to friendly units, not enemies.
"There are now options for displaying health and mana values on your health/mana bars for you/your party/your target and to display that information either as percentages or as numbers."

If you look at https://wow.gamepedia.com/Patch_3.0.2_(undocumented_changes)
"Health values appear on targets; mobs, boss, NPC, or player (regardless of group or faction)." It is clear that "regardless of group or faction" means that in patch 3.0.2 they changed this to be an integer. This is a change that only went into effect during WotLK, not TBC.

Video proof: https://www.youtube.com/watch?v=QyTyNaiEJKs&feature=youtu.be&t=8m15s
You can see the priest targeting an enemy and his health is displayed as a %, then he switches to a friendly target and their health is displayed as an integer.

**Comment by Devrak** [comment]
Half correct only NPC health values should be displayed as %  idk if its worthwhile to fix this as most use unit frames that have mob db with them

Blizzard target frame health check code from targetframe.lua
 


	if ( UnitIsPlayer("target") ) then  
		local unitHPMin, unitHPMax, unitCurrHP;  
		unitHPMin, unitHPMax = this:GetMinMaxValues();  
		unitCurrHP = this:GetValue();  
		this:GetParent().unitHPPercent = unitCurrHP / unitHPMax;  
		if ( UnitIsDead("target") ) then  
			TargetPortrait:SetVertexColor(0.35, 0.35, 0.35, 1.0);  
		elseif ( UnitIsGhost("target") ) then  
			TargetPortrait:SetVertexColor(0.2, 0.2, 0.75, 1.0);  
		elseif ( (this:GetParent().unitHPPercent > 0) and (this:GetParent().unitHPPercent <= 0.2) ) then  
			TargetPortrait:SetVertexColor(1.0, 0.0, 0.0);  
		else  
			TargetPortrait:SetVertexColor(1.0, 1.0, 1.0, 1.0);
		end  
	end  

`

**Comment by Ituhdudu** [comment]
No, it's pretty clear from the patch notes and video link that enemy players HP is also supposed to be displayed as a % and not as an integer.
Also this fix is very easy to implement, when they fixed it on HellGround's relaunch the developer said it only took a few minutes of work.

**Comment by Devrak** [comment]
vid is Published on Jul 30, 2012 .. its had to say what patch it is from blizzard did alot of rework in 2.4.0 - 2.4.3 and not a lot is documented as ppl were focusing on 3.0.2 ptr at that time

**Comment by Ituhdudu** [comment]
It is not hard to tell at all, go look at the patch notes I linked. It is very explicit "regardless of group or faction"

https://www.warcraftmovies.com/movieview.php?id=92583
here is the WCM link from 2008.

This has been fixed on multiple other TBC projects, it is a change from WotLK there is no denying this.

**Comment by Silroth** [comment]
Just a reminder that this idiot is making same "bug reports" on every TBC server just so he can see which developer will cave to his demands and then he will mock the devs for wasting time on such unimportant things. Same thing happened on Hellground(Wargate), Ares TBC and other servers.

**Comment by Ituhdudu** [comment]
You can look at the proof i provided and see it is very clear that enemy HP was always displayed as a % in TBC, it was only changed in patch 3.0.2 as i linked above.
This isn't something that takes a lot of the devs time to change, and it's ultimately their decision. You don't have to be so rude.

**Comment by E1ectroShock** [comment]
I think most of players are glad to see integers instead of percents

**Comment by akrom23** [comment]
We won't change that.
