### ISSUE TITLE
Health Regen in Combat

### ISSUE THREAD

**Issue by Vartonis** [SunwellWoW/Sunwell-TBC-Bugtracker#4072]
Description:  You do not regen any health in combat unless healed or take a potion. 

How it works: Currently, in combat you do not regenerate any health at all. 

How it should work: You should slowly regain health while in combat. For example if I'm a druid and I root a non caster I should be able to slowly regen health and mana without healing. If I'm a mage and I keep something sheeped, I should slowly regen health/mana. 

Source (you should point out proofs of your report, please give us some source): This is how the game has always worked

**Comment by foxxhound** [comment]
As far as my knowledge goes, unless you're a troll you don't have any in-combat HP regeneration.
![image](https://user-images.githubusercontent.com/45742349/50944571-f9af3000-145e-11e9-90d2-4a286d522689.png)

Spirit states HP will regenerate by a fixed amount while OUT of combat. 

Trolls are the only race that regenerates HP in combat. 
As seen in the wiki: http://wowwiki.wikia.com/wiki/Health_regeneration

**Comment by ahlens** [comment]
There is no hp regen in combat.

**Comment by Rangelkent** [comment]
#3210 Troll racial is also bugged still

**Comment by akrom23** [comment]
This is completely wrong - there is no health regen in combat from spirit (with some exceptions).
There are some auras that allows to regen health in combat (e.g. Demon Skin, Demon Armor).
