### ISSUE TITLE
Karazhan ring quset

### ISSUE THREAD

**Issue by Cowb0ySMURF** [SunwellWoW/Sunwell-TBC-Bugtracker#4074]
Description: Supposed to give you a choice of 4 quests for a ring

How it works: 
Gave me 1 quest, not correct ring

How it should work: 
should give choice of 4 quests

Source (you should point out proofs of your report, please give us some source): 
Character: Elasar

**Comment by nkumnberlin** [comment]
He offers four different quests, with different rings.

**Comment by Devrak** [comment]
I did the questline 9h ago and got offered 4 different quests for 4 different rings, working as intended do you have any addon that skips gossip maybe ?

**Comment by Cowb0ySMURF** [comment]
I do not.
