### ISSUE TITLE
Drain Life skill lvl 4 bug

### ISSUE THREAD

**Issue by Barol94** [SunwellWoW/Sunwell-TBC-Bugtracker#4076]
Description: 
I am unable to purchase the drain lvl 4 from the warlock trainer. I cannot even see it as "available" it's like it doesn't even exist. I can only buy lvl 5,6 etc but cannot do that without buying lvl 4.

How it works: 
I cannot buy the talent from the trainer because it does not even show on the talents list.

How it should work: 
I should be able to purchase that skill from the trainer and then buy rest of them.

Source (you should point out proofs of your report, please give us some source): 
Here You can see the screens:

![1](https://user-images.githubusercontent.com/46563134/50968110-6f0c1680-14da-11e9-9c0c-3027b6cb26eb.png)
![2](https://user-images.githubusercontent.com/46563134/50968117-70d5da00-14da-11e9-8999-947a1576a241.png)

On the first one You can see that I am unable to purchase the Drain life lvl 5 without purchasing lvl 4 and on the second one as You can see, lvl 4 is not even available to buy.  Since lvl should be available from lvl 46, lvl 4 should be available earlier but it dissapeared somehow. Thank You in advance for Your help.

**Comment by Devrak** [comment]
maybe its only this particular trainer have you tryed others ?
