### ISSUE TITLE
[Hunter][pets] Pet attack speed

### ISSUE THREAD

**Issue by nenovike** [SunwellWoW/Sunwell-TBC-Bugtracker#4080]
Description: 
Before pet system change in wotlk and further in cata etc. some pets had different attack speed than rest of their family. For example rare pet Death Flayer https://www.wowhead.com/npc=5823/death-flayer had attack speed of 1.6, not 2.0 as rest of Scorpids.

How it works: 
Death Flayer has attack speed of 2.0 and probably other pets have wrong attack speeds too.

How it should work: 
Death Frayer should have attack speed of 1.6.
http://www.companioncodex.com/bestiary/ there is a list of classic mobs and their corresponding attack speeds. I did not found such for pets added in TBC.

Source (you should point out proofs of your report, please give us some source): 
http://www.companioncodex.com/bestiary/ - whole database
https://www.wowhead.com/npc=5823/death-flayer - there are comments from 2.1.3 saying Death Flayer's attack speed was indeed 1.6 back then.

**Comment by akrom23** [comment]
https://forum.nostalrius.org/viewtopic.php?f=38&t=293#p2339
https://www.reddit.com/r/classicwow/comments/9spju6/hunter_pet_attack_speed_normalization/e8ryfzz/

https://wow.gamepedia.com/Patch_2.0.3_(undocumented_changes)

> All pet attack speeds have been normalized to 2.0.
