### ISSUE TITLE
Feign Death not working

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#4081]
When you use feign death you are clearing your threat from the mob, but...
After a certain amount of time it looks like the feign death never happened but you wont see your threat jumping high (due to your previous threat coming back) on the threat meter. In result the boss will run on you and you'll just die because you reached 130+% without being able to anticipate it due to invisible threat on threat meters.
Also, when this happens and if your FD is up and you try to use it again it wont matter the boss will still run and kill you.

**Comment by flapse32** [comment]
Can confirm this.

**Comment by MiekZer** [comment]
Maybe bug related to the fact that we cancel it very fast after we click on the FD button and if there is a double check server side it may bug ??

x did FD : erase threat client side (your threat meter)
200 ms delay
mob y receives FD information.
200 ms delay
is x still FDed
200 ms delay
YES : erase threat server side / NO : don't erase threat

But it's clearly not related to a resist since it happens everytimes for me at least.

**Comment by badmannerkid** [comment]
this needs to get looked at. between this and the hunter t5 two set generating too much threat it makes the class feel very cumbersome to play while raiding

**Comment by Filosof93** [comment]
Can confirm that something is wrong. I've thought my FD just fail too often up until lately.

**Comment by akrom23** [comment]
If you resist, the threat won't be cleared.
Provide some screenshots or video.

**Comment by MiekZer** [comment]
Some screens:
https://www.noelshack.com/2019-04-1-1548046468-bug1.png
https://www.noelshack.com/2019-04-1-1548046469-bug2.png
https://www.noelshack.com/2019-04-1-1548046471-bug3.png

**Comment by akrom23** [comment]
@MiekZer Everytime you used FD because of overaggro?

**Comment by MiekZer** [comment]
On these screens I used FD when I was below the tank but close to him in threat.
I will try to see what happens when I wait to be above the tank before using FD.

**Comment by akrom23** [comment]
Got a question about resist:
Let's say hunter fight against pack of 4-5 mobs. Hunter uses feign death and one of these mobs resists.
Does it mean that the whole pack should resist and still attacking hunter?
Or maybe only this one should resist and evade?
And what about the message on the screen?

**Comment by MiekZer** [comment]
Against a large pack of (regular) mobs, according to this : "As the level (relative to the hunter) and number of enemies become higher, the likelihood of the spell being resisted becomes higher." I'd say that if one mob resists then the whole pack will still run on you. It's maybe due to mob linked at the beginning of the fight, if you fd and one linked mob resists then his pack will still run and attack you.
Against a boss with adds however I never noticed (during retail or on other private server) the problem that your threat against the boss wont be cleared because it resisted on one add.
Also the message should be "Resisted" when your feign death spell is resisted.

**Comment by flapse32** [comment]
so hyped for this to be fixed 💃

**Comment by Ironjudgment** [comment]
@akrom23 
not fixed after 
Piootrek Today at 18:59
@here 
There will be quick restart on Nightbane in 30minutes from now - realm maintenance.

To test this I have made a macro on my FD to also do a .debug threatlist command and made an entirely seperate chat window for it. You can observe that none of my FD's reset my agro.

I am **Ironbow**.

https://youtu.be/s7feJ4qNoPE?t=4105

Agro reset component of FD didn't work on trash or bosses at all but you could still kite and FD :S

**Comment by akrom23** [comment]
Because it's not live yet.
