### ISSUE TITLE
[NPC] Daggern Muckdweller in Zangarmarsh

### ISSUE THREAD

**Issue by Popmycherrybug** [SunwellWoW/Sunwell-TBC-Bugtracker#4084]
Description: The Muckdwellers keep applying their paralytic poison when they should let it tick down and only reapply if you dispel it (now they re-apply when it's about 25-26 seconds left)

How it works: Well, as said above, that's what they do.

How it should work: They should ONLY re-apply it if you dispel it, as they should look for it to actually stun you (btw, a lot of mobs seems to do this, re-apply their dots after just 1 tick. Same with the threshers/flayers in Un'goro)

Source (you should point out proofs of your report, please give us some source): The source or evidence is really just how we all remember it from retail, how it works on retail nowadays, and "logic". Also you can see some videos of it and also read up on it on wowhead if you look for the quest AND the paralytic poison spell itself.

**Comment by Mikov1605** [comment]
Note: most mobs recast their poison, example: Hydra in zangar

**Comment by Dootz** [comment]
fixed, live.
