### ISSUE TITLE
[Item] Necklace of the Deep was taken out of the game, but is still sold on AH

### ISSUE THREAD

**Issue by AJvanLoon** [SunwellWoW/Sunwell-TBC-Bugtracker#4085]
Description: 

On December 11, a bug report was made (rightfully) requesting that Necklace of the Deep be taken out of the game for being a 2.1 item.  I suppose it was removed shortly after. 

However, all JC's who already learned it from the trainer kept the recipe - essentially giving them a monopoly on an item that shouldn't be available in the first place.

How it works: 

The JC recipe for Necklace of the Deep was taken out of the game, but a few JC can still make it.

How it should work: 

Either this item should just become available again - not like it's _that_ 'deep' either - or it should be completely removed from the game, meaning all JCs on the server should lose the ability to craft it.

Source (you should point out proofs of your report, please give us some source): 

- Just check the AH for the current availability
- https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3122
- https://www.wowhead.com/item=32508/necklace-of-the-deep

**Comment by MiekZer** [comment]
x10 profit each time they click on their craft :)

**Comment by Dootz** [comment]
we decided to add it to trainers.
