### ISSUE TITLE
Shutting Down Manaforge Duro

### ISSUE THREAD

**Issue by Nicklastoft** [SunwellWoW/Sunwell-TBC-Bugtracker#4086]
Upon acquiring the "Duro Access Crystal" i tried clicking the Duro Control Panel to start the event, in order to complete the quest.

The control was not clickable.

After contacting a GM, he reset the object, and made it clickable.

Upon clicking on the now "fixed" object, it still did not start the event. GM told me to report this here, as he was unable to fix it himself. He mentioned something about the event still being in progress from an earlier attempt by someone else.

Obviously the control panel should just always be clickable, and always able to start the event.

**Comment by Mikov1605** [comment]
No, not always. There is a cooldown after someone started it

**Comment by Nicklastoft** [comment]
I highly doubt that cooldown is intended to last 30mins or more.
I tried the day after and got the quest completed, but i dont know if this problem still persists.

**Comment by neheri** [comment]
Please notice that all Manaforge quests are not working properly right now.

The mobs should not only attack the player, they should rather focus on running towards control panel and if left for 15 seconds without attacking them, they stop entire shutting down process.

You can see example here (left hand side):

https://youtu.be/eUI-uk2Xafc?t=139
