### ISSUE TITLE
[Boss][Karazhan] Netherspite - Losing aggro with red debuff

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#4087]
Description: It seems like Netherspite keeps aggro on person only inside red beam. He should attack player with red debuff instead. 

How it works: When you leave red debuff Netherspite returns to having normal aggro table.

How it should work: When you have red debuff netherwing should always attack you.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Netherspite

Perseverance (red) - Tank beam:
Lasts for 20 sec after leaving the beam.
Hits Netherspite:
Damage taken reduced by 1% per tick.
Hits Player:
Netherspite will aggro you.

**Comment by notsofamous** [comment]
Taking a tick from the red beam gives you the highest threat, if you stop taking ticks from red beam you'll stop being number 1 on threat.

> If no one is standing in the Red Beam, Netherspite uses his standard aggro table.

Meaning if you have the red debuff but is not standing in the beam, he will use normal aggro table.

Working as intended.

**Comment by neheri** [comment]
My bad.
