### ISSUE TITLE
[Upper Blackrock Spire - Door bug making it imposible to complete even after fix]

### ISSUE THREAD

**Issue by aeyers** [SunwellWoW/Sunwell-TBC-Bugtracker#4088]
Description: The door / gate after Rend dosn't open upon killing Rend

How it works: After completing the event for Rend and Gyth the gate to continue into the rest of the instance dosn't open.

How it should work: After killing Rend and Gyth the door / gate should open.

Source (you should point out proofs of your report, please give us some source):

**Comment by aeyers** [comment]
Working like a charm now!

**Comment by Dootz** [comment]
fixed, live.
