### ISSUE TITLE
spiritual attunement using the healers max hp in calculation

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#4090]
related to #3300 I have figured out the nature of the problem I believe. So the code for spiritual attunement likely looks something like below

int missing_health = max_health-current_health;
if (missing_health<heal) mana_return = missing_health*.1;
else mana_return= heal*.1;

The issue is that max_health is looking at the healers max health, and not the paladin getting healed. So if the healer only has 7k max health, any healing while the paladin is above 7k won't give mana and any healing bringing the paladin from below 7k to above 7k will give partial mana.

**Comment by ZaoQ** [comment]
any update on this issue?

**Comment by babno** [comment]
Zero progress, it's quite unfortunate and a major class bug.

**Comment by Atrecom** [comment]
Tired of such a sh*t.
![1](https://user-images.githubusercontent.com/44858756/51610558-1b63e900-1f2e-11e9-8e46-f1f0b1f3fdb5.jpg)

**Comment by akrom23** [comment]
@babno Not quite right.
This is our code:
```
// heal amount
basepoints0 = triggeredByAura->GetModifierValue()*std::min( damage, GetMaxHealth() - GetHealth() ) / 100;
```
Damage is the amount of heal.
This code don't allow to gain mana from overheal. And this is the question - only efective heals should count?

EDIT: Okay - I know where is the problem :)

**Comment by akrom23** [comment]
Got a question: I know that in TBC combat logs do not show overheals. So what number should be displayed as a heal done/gain - only effective amount of heal?

**Comment by babno** [comment]
Yeah I'll bet you anything that GetMaxHealth() is getting the healers max health and not the paladins.

As to the combat log, I think it should remain as is. My main point of reference is recount, a tbc era addon, tracks overheal. If you hide overhealing and only display effective healing in the combat log then it wouldn't work.

**Comment by akrom23** [comment]
Alright. Thanks for the info.

**Comment by babno** [comment]
And thank you for fixing it. I look forward to it being implemented asap, been a rough few months.
