### ISSUE TITLE
Formula: Enchant 2H Weapon - Savagery Droprate

### ISSUE THREAD

**Issue by MadderThenMad** [SunwellWoW/Sunwell-TBC-Bugtracker#4091]
Description: Formula: Enchant 2H Weapon - Savagery http://db.hellfire-tbc.com/?item=22554 seems to be far much lower then it should be a specially on Heroic.

How it works: I've killed over 150  yet I've never even seen it (I have enchanting kills were divided between Heroic and Normal). I remember that this recipe droprate was being fixed on old Hellgrund cuz it was bugged. May I ask for checking the droprates of this recipe on both normal and heroic?

https://tbc-twinhead.twinstar.cz/?item=22554 (5%)
http://db.hellfire-tbc.com/?item=22554 (2%)

How it should work: 

The droprate of recipe should be somehow at least similar to what other instance recipes are:

http://db.hellfire-tbc.com/?item=22533 - Bracer Fortitude
http://db.hellfire-tbc.com/?item=22544 - Boots Dexternity 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
drop rate will be increased 2% -> 8%

**Comment by Dootz** [comment]
fixed, live.
