### ISSUE TITLE
[Shaman] Fire Elemental Appears as an Enemy and is Target-able (even fights Hunter pets) 

### ISSUE THREAD

**Issue by BarrahSunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#4093]
Description: [Shaman] Fire elemental appears as a "red" mob upon being summoned.

How it works: When you summon Fire elemental with the totem, the fire elemental spawns and attacks whatever you are attacking, BUT, the elemental appears red, and if you "tab" to target, it seems to always be the first target, and even will fight hunter pets.

How it should work: The elemental shouldnt be flagged as an enemy? Right?

Source (you should point out proofs of your report, please give us some source):

**Comment by zanthed1** [comment]
This only happens if the fire totem is destroyed or replaced. It is neutral but not hostile.
