### ISSUE TITLE
[NPC] Southsea Swashbuckler

### ISSUE THREAD

**Issue by ahlens** [SunwellWoW/Sunwell-TBC-Bugtracker#4094]
**Description:** 
[Southsea Swashbucklers](http://classicdb.ch/?npc=7858) stay in place during the fight, and they barely attack. It's a dummy target. If you are ranged, you take no hits.

![wowscrnshot_011119_211558](https://user-images.githubusercontent.com/23612673/51065509-754ae180-1605-11e9-9ba6-70aa05663baa.jpg)

**Comment by Dootz** [comment]
fixed, live.
