### ISSUE TITLE
[NPC][Spell] Dust Cloud

### ISSUE THREAD

**Issue by ahlens** [SunwellWoW/Sunwell-TBC-Bugtracker#4096]
**Description**: 
Spell [Dust Cloud](https://www.wowhead.com/spell=7272/dust-cloud) used by [Elder Plainstrider](https://www.wowhead.com/npc=2957/elder-plainstrider#abilities) in Mulgore doesn't do anything. 

Frankly speaking, I don't know what it should do...
![wowscrnshot_120318_002317](https://user-images.githubusercontent.com/23612673/51065621-310c1100-1606-11e9-9e3e-a7bdbbdfb1a1.jpg)

**Comment by Dootz** [comment]
fixed, live.
