### ISSUE TITLE
[Paladin][Talent][Bug] Precision doesn't increase melee/spell hit chance

### ISSUE THREAD

**Issue by F4play** [SunwellWoW/Sunwell-TBC-Bugtracker#41]
Decription: Tier 2 protection talent [Precision] doesn't increase melee/spell hit chance

Talent ID's - 
1 Point (1%): 29590
2 Point (2%): 29591
3 Point (3%): 29592

How it works: No increase to melee/spell hit chance on character stats

How it should work: Should increase melee/spell hit chance at the rate of 1% per talent point spent

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
+hit% from talents is not displayed in characters statistics.
