### ISSUE TITLE
Snare resistance 

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#410]
Decription: 
If someone has extra snare resistance (from talent/enchant/meta gem), this causes them to resist the attack/spell completely. Instead of just resisting the snare. The damage should still go through.

**Comment by akrom23** [comment]
So what should happen with the slow effect? Not applied/sent immune/sent resisted? Some video?

**Comment by notsofamous** [comment]
I don't think there should be any message other than the damage applied.
