### ISSUE TITLE
Elemental Focus does not trigger from lightning overload

### ISSUE THREAD

**Issue by olleiparken** [SunwellWoW/Sunwell-TBC-Bugtracker#4104]
Description: 
Elemental Focus does not trigger from bonus spells cast by Lightning Overload.

How it works: 
Elemental Focus does not trigger from bonus spells cast by Lightning Overload.

How it should work: 
A Lightning Overload crit should trigger Elemental Focus.

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Elemental_Focus

**Comment by Wojtyas** [comment]
Patch 2.1.0 (2007-05-22): This talent now reduces the cost of the next damage spell by 60%. It will also now trigger from bonus spells cast by  [Lightning Overload].
