### ISSUE TITLE
NPC Bloodmaul Skirmisher

### ISSUE THREAD

**Issue by Popmycherrybug** [SunwellWoW/Sunwell-TBC-Bugtracker#4105]
Description: Heal themself to 100%

How it works: They heal themself to 100% with their ability "Bloodmaul Rage" or whatever it's called

How it should work: According to the buff, it should only give them 20% max hp, so that's what it should heal (like warrior shout)

Source (you should point out proofs of your report, please give us some source): I mean, read the ability

**Comment by Dootz** [comment]
fixed, live.
