### ISSUE TITLE
Offhand arena weapon cost

### ISSUE THREAD

**Issue by SomeGuyEksDee** [SunwellWoW/Sunwell-TBC-Bugtracker#4109]
Description: 
Bugged s1 offhand weapon price.

How it works: 
For whatever reason Offhand weapon has same arena point price as mainhand.

How it should work: 
Main hand weapon cost should be the same as it is now, offhand should cost 1125, theres no arena point cost on link below, but if you look at amount of honor it costs it's less as mainhand aswell. I can't find link propper arena point cost coz it's 2019 you know, but the general idea is mainhand costs more than offhand. It doesn ton supposed to be equal.
Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Season_1_Arena_rewards    https://imgur.com/a/H7IsdVC link from another private server ;)

**Comment by SlizeTBC** [comment]
Yea def. not correct like it is now. 1MH + 1 OH should be the same price as 1 2handed weapon.

**Comment by Dootz** [comment]
fixed, live.

**Comment by dachdagger** [comment]
Still costing too much...
