### ISSUE TITLE
[NPC] Caludron Lords

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#4111]
Description: During cauldron quest chain in WPL every cauldron lord is doubled. 

How it works: There are always 2 cauldron lords.

How it should work: There should be 1 cauldron lord per cauldron.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_011319_101813](https://user-images.githubusercontent.com/37372869/51083562-9b16da00-171c-11e9-9cb4-f71977bc778f.jpg)

**Comment by Dootz** [comment]
fixed, live.
