### ISSUE TITLE
Your target is dead

### ISSUE THREAD

**Issue by justchatta** [SunwellWoW/Sunwell-TBC-Bugtracker#4113]
Description: Playing as Paladin Draenei . I keep getting "your target is dead " error every time I kill anything while having seal of righteousness active.

How it works: If I have Seal of Righteousness active and I last hit a mob, I will get error " your target is dead ". If I dont use seals for a kill , everything works fine.

How it should work: I shouldnt be getting any kind of errors for killing mobs.

Source (you should point out proofs of your re
![wowscrnshot_011319_145415](https://user-images.githubusercontent.com/46649350/51086215-2b1c4a00-1744-11e9-8732-64996a4680d0.jpg)
port, please give us some source):

**Comment by firngrod** [comment]
I'm guessing that the seal is trying to apply it's effect, and that's what produces the error message?  Is it possible to test whether the message appears if the target dies from the seal damage?
