### ISSUE TITLE
Missing NPC Murgurgula

### ISSUE THREAD

**Issue by dafairygirl** [SunwellWoW/Sunwell-TBC-Bugtracker#4115]
Description: The NPC Murgurgula is missing from the murloc coastline in Azuremyst Island. It's an NPC marked with a silver dragon (but he's not a rare spawn) who when killed drops the item "Gurf's Dignity" which starts a quest of the same name. I leveled through the zone on 2 toons and looked for him several times, and he's not there. 

How it works: 

It doesn't.
How it should work: 
He should be a patrolling mob amongst the other murlocs west of stillpine hold. 

Source (you should point out proofs of your report, please give us some source): 
The NPC: https://www.wowhead.com/npc=17475/murgurgula#screenshots
The Dropped item: https://www.wowhead.com/item=23850/gurfs-dignity
The resulting Quest: https://www.wowhead.com/quest=9564/gurfs-dignity

**Comment by dafairygirl** [comment]
Also the murlocs seem to have an unusually high drop rate for Plans: Copper Chain Vest

**Comment by firngrod** [comment]
I'm not absolutely certain, but I think I got and completed that quest.  There is a chance that you were just unlucky.

**Comment by Dootz** [comment]
fixed, live.
