### ISSUE TITLE
Boots of blasting on the drop table, SSC/TK.

### ISSUE THREAD

**Issue by Sippiey** [SunwellWoW/Sunwell-TBC-Bugtracker#4117]
Description: The 2.1 recipes in T5 has been removed on this server but somehow you guys managed to add the boots of blasting to the drop table, boe boots with t5 standard that will be sold by the high level guilds for insane cash, easy fix.

How it works:  Trash and maybe even bosses drops pattern: boots of blasting, i have already sen 8+ of these recipes.

How it should work: They should not be in the game until 2.1.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=30282/pattern-boots-of-blasting

**Comment by Bugadin** [comment]
Does still drop? What will happen with the boots that were already crafted? This isn't fair at all xD

**Comment by Dootz** [comment]
As far as i know boots of blasting are no longer in loot tables, and pattern was brought back.

**Comment by Bugadin** [comment]
I suppose it doesn't since yesterday because the boots dropped the last Sunday
