### ISSUE TITLE
Druid Spell - Nature's Grace 

### ISSUE THREAD

**Issue by BugReporterupper** [SunwellWoW/Sunwell-TBC-Bugtracker#4119]
Description: 

Nature's Grace (Balance Druid Talent) is being procced by random spell casts and DoT ticks, even when a critical strike isn't made.

It also consumes the Nature's Grace proc from instant-cast-spells such as moonfire and another Balance Druid Talent, Nature's Grasp.

Finally, Nature's Grace does not proc from healing spells such as Healing Touch.

How it should work: 

All spell criticals grant the next spell cast 0.5 reduced cast time.

The only time Nature's Grace should proc is when a spell critical strike is made.
Nature's Grace should ONLY be consumed by a spell with cast time.
Nature's Grace should proc from ANY spells casted that are critical strikes, be it Balance or Restoration spells.

I'm too lazy to make a video showing the whole problem with the spell, but here is a screenshot showing that spell criticals, or at least Healing Touch doesn't proc Nature's Grace, when it should, to show that I'm at least not babbling :).

https://steamcommunity.com/sharedfiles/filedetails/?id=1624049497

**Comment by BugReportguru** [comment]
Since the server was released Nature's Grace wasnt working properly.
Please make sure the buff gets only consumed by a cast with REDUCED cast time.
Otherwise spamming wrath is not affected by this because when the spell actually critically hits the target, you are allready casting your next spell (with standard cast time) which consumes the buff.

**Comment by Jinzo25** [comment]
After the server restart it rproccs completely randomly, on crits or non crits and consumes casted spells as well like the guy before described. So its pretty broken, the same way it was before and right after the server released.

**Comment by Jinzo25** [comment]
https://imgur.com/a/EDJAIMh

The two Screenshots: 
1st: No proc on a crit
2nd: Proc on a non crit
