### ISSUE TITLE
Cannot be resurrected bug

### ISSUE THREAD

**Issue by Trolltilla** [SunwellWoW/Sunwell-TBC-Bugtracker#4120]
Description: 

Sometimes and it happens quite often after dying in an instance or raid your corpse bugs out and you cannot get resurrected, which means you have to run back. You can imagine how annoying this is in a raid situation when people can't get ressed.

How it works: 

As described above.

How it should work: 

You should be able to resurrect people always.

Source (you should point out proofs of your report, please give us some source):

**Comment by mjk6994** [comment]
Can confirm

**Comment by mjk6994** [comment]
Was unable to rez a player after releasing, attempted to reload, relog, and reinvite.

**Comment by akrom23** [comment]
@Trolltilla @mjk6994 Got some screenshots ot video?

**Comment by koostosh** [comment]
could not reproduce
