### ISSUE TITLE
Master looter recipes issue

### ISSUE THREAD

**Issue by pinkisnotgay** [SunwellWoW/Sunwell-TBC-Bugtracker#4129]
Description: 
Lately I've experienced an issue where master looter was ON and enchanting recipe dropped from Aran. The recipe was only visible for the enchanters, but all the enchanters from the raid were able to loot it as if it was FREE FOR ALL, without the need of lootmaster. This also applies to other things like leatherworking recipes.

How it works: 
You can loot pattern/recipes that are only visible to proffession owners while masterlooter is on, as if they loot was set to FREE FOR ALL.

How it should work: 
You shouldn't be able to loot them like that, masterlooter should be able to distribute them.

Source (you should point out proofs of your report, please give us some source):

**Comment by pinkisnotgay** [comment]
Same thing happened yesterday. I was doing Arcatraz and 35agility recipe dropped, I had masterlooter on and despite being the leader + enchanter at the same time, just picked it up as if it was FFA.

**Comment by pinkisnotgay** [comment]
Yet another example of the same issue, that's why it makes it really annoying, because you can't reserve a recipe in your own karazhan run.
![masterlooter issue](https://user-images.githubusercontent.com/44933866/51286534-b96a2780-19f3-11e9-85f9-845470e20a10.jpg)

Person was able to pick up the recipe before master looter even opened the boss.

**Comment by pinkisnotgay** [comment]
Apparently you can do the same when group loot is on.
This needs immediate fix.
@Wojtyas

**Comment by kiterama** [comment]
push!  really annoying bug

**Comment by kiterama** [comment]
This is what happened today during ssc.
We got random drop nether vortex and I was master looter. I always have Autoloot on. I right clicked a mob and the vortex immidiately got to my inventory without asking for anything. This is totally shit .. now the vortex is worthless for our guild since I dont need it anyways.
