### ISSUE TITLE
[Quest] WWhat Came First, the Drake or the Egg?

### ISSUE THREAD

**Issue by rajoe** [SunwellWoW/Sunwell-TBC-Bugtracker#4131]
Decription:
The quest requires you to right click drake eggs then use an item on them to change them randomly into 1 of 3 mobs which drop items to complete the quest. Currently the eggs do NOT spawn anything so you cannot complete the quest.

How it works: You click the egg, get an animation, and nothing happens.

How it should work: The "Nether Drake Egg" should spawn either a whelp which you use an item on. This item changes the whelp into one of the three following creatures that drop a quest item to complete:

Proto-Nether Drake
Adolescent Nether Drake
Mature Nether Drake

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
#2367
