### ISSUE TITLE
[Shaman] Yet another grounding totem bug report

### ISSUE THREAD

**Issue by username-is-not-taken** [SunwellWoW/Sunwell-TBC-Bugtracker#4137]
Description: 
I'm not entirely sure how this mechanic is supposed to work, but I believe chain lightnings that get redirected to grounding totem should not bounce. As it is now, chain lightnings that get redirected to grounding totem bounces off the totem to additional targets (and if, as in my case, there's only one target nearby, it bounces twice to that target).

How it should work: 
As the tooltip says.

Source (you should point out proofs of your report, please give us some source): 

![cl-ground](https://user-images.githubusercontent.com/45629295/51143526-14164e80-184f-11e9-927e-1e50e96ddb77.png)

**Comment by baade123** [comment]
that is a yikes

**Comment by Thempest** [comment]
I noticed this too and think the same, it shouldn't bounce of it.

**Comment by akrom23** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3022#issuecomment-449926857

> Grounding Totem must also be in LoS + range of the spell's source to work as well.
I think only the shaman or party member must be in range of the totem instead.

So...
