### ISSUE TITLE
Dark Iron Legacy ! (BRD Key quest)

### ISSUE THREAD

**Issue by pinkisnotgay** [SunwellWoW/Sunwell-TBC-Bugtracker#4138]
Description: 
Once you are dead you should be eligible to pick up a "Dark Iron Legacy" quest.

How it works: 
Nothing happens, for some reason you cannot accept the quest.

How it should work: 
You should be able to accept the quest.

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/ce6adb107d774034b632c0df3e0ea9ed

**Comment by baade123** [comment]
you are able to pick up the quest alive >_>

**Comment by baade123** [comment]
so yes bug but no problem i guess XD

**Comment by pinkisnotgay** [comment]
Still a bug.
