### ISSUE TITLE
[Paladin] Threat for Healing Spells is Double the Intended Value

### ISSUE THREAD

**Issue by chme3921** [SunwellWoW/Sunwell-TBC-Bugtracker#4141]
Description: Healing spells are intended to do 0.5 threat per health healed, with the exception being Paladins due to increased threat generated from instant mana gains, mostly from the Illumination talent. Because of this, Blizzard in Vanilla gave Paladins an additional 0.5 multiplier to threat on healing spells to counter-act this, bringing the total threat per health healed to 0.25.

This makes dungeon runs, specifically with Warrior tanks, borderline unplayable as the Paladin pulls aggro on nearly everything sans the kill target.

How it works: Paladin healing threat is 0.5 threat per health restored.

How it should work: Paladin healing threat should be 0.25 threat per health restored.

Source (you should point out proofs of your report, please give us some source): 

http://wowwiki.wikia.com/wiki/Threat

**Comment by chme3921** [comment]
still pulling aggro from every tank in dungeons, makes heroics painful as people are starting to reject holy paladins from groups. this is a 3 second fix, just fix it

**Comment by NoCandy** [comment]
I agree the multiplier is not working as intended, I will try to get a screenshot with a threatmeter next time I go to a dungeon.

**Comment by mchayes** [comment]
This is also extremely annoying when it comes to CC. Since threat is apparently still produced on mobs in Polymorph/Banish etc, any holy paladin is doomed to die once CC breaks and a taunt fails.

**Comment by akrom23** [comment]
> Example: You are a Paladin casting a heal (threat is normally .5x healing done). For healing, Paladins also have an innate threat reduction (.5x)

From the link in first post.

**Comment by chme3921** [comment]
you just made it worse, im doing quadruple threat and pulling on Curator now

**Comment by akrom23** [comment]
It's not live yet @chme3921
