### ISSUE TITLE
Deadly throw from PVP gladiator gloves [ROGUE PVP]

### ISSUE THREAD

**Issue by Bugadin** [SunwellWoW/Sunwell-TBC-Bugtracker#4142]
Description: Deadly throw should interrupt casts when you equip grand marshal's leather gloves or Gladiator's leather gloves. It was working as intented until today, which it doesn't now.

How it works: Deadly throw doesn't interrupt

How it should work: Deadly throw SHOULD interrupt when equipping  Grand marshal's leather gloves or Gladiator's leather gloves.

Source (you should point out proofs of your report, please give us some source): Just try it, it's easy to test it.

**Comment by milk92** [comment]
Can confirm this is bugged since today. Did work previously
