### ISSUE TITLE
Warlock pet macro(specificly Felguard)

### ISSUE THREAD

**Issue by Wobbey291** [SunwellWoW/Sunwell-TBC-Bugtracker#4144]
Description: 
I am trying to use the Intercept ability from the felguard on a macro and any type of macro does no seem to work. It seems only clicking the ability makes him use it.

How it works: 
using
/cast Intercept    makes it work with the range that the ability has but the felguard just wont use it
using
/use [pet:Haaghun,harm]Intercept     does about the same thing. the only difference is that the image of the icon of the macro becomes the one from the pet
How it should work: 
Simply using /cast Intercept should do the trick

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Works fine.
