### ISSUE TITLE
The beast boss and ace of the beasts

### ISSUE THREAD

**Issue by darknessangelo** [SunwellWoW/Sunwell-TBC-Bugtracker#4145]
Description: 
Been farming Ace of beasts for a while, killed boss The Beast around 25 times and still no drop. Can you please check and refer if it drops from the boss and has around 5% drop rate? Thank you.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by pinkisnotgay** [comment]
It's on the loot table.

**Comment by aeyers** [comment]
I got it on my 44th kill.

**Comment by akrom23** [comment]
It is 5% chance.
