### ISSUE TITLE
[Boss] Fathom-Lord Karathress

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#4147]
Description: His adds are bugged.

How it works: 
Fathom-Guard Tidalvess' windfury can proc off windfury so he can instagib any tank at the moment. It's just luck now how many times WF procs. 

Grounding totem does not work with his frost shock.

Fathom-Guard Caribdis cyclone stays in one place so person is kept infinitely in the air, which causes her to evade. You can keep her evaded, kill other adds and kill her after she's evaded.

Cyclone is invisible.

Cyclone doesn't move.

How it should work: 
Tidalvess Windfury should proc only once. 
Grounding totem should work with his frost shock.
Carbidis cyclones should be visible, sould move and you should be able to leave them.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/pub88sW4Jxs

The group with the Tidalvess (Shaman) tank should contain a shaman, who keeps Grounding Totem up at all times, to negate Tidalvess' Frost Shock.

**Comment by neheri** [comment]
Just tested it, not fixed. His WF still procs infinitely. If you survive or not it's just luck. Just received x4 hits for 22k total. 

On the second attempt I survived him. On the first attempt I am 100% sure he procced WF from WF (4 hits). 

Can confirm that vortexes from priest are now visible. They should be bigger and move faster. Just as here:

https://youtu.be/pub88sW4Jxs

**Comment by neheri** [comment]
We one shoted him yesterday so there was no much testing. I survived shaman, not sure if his WF attacked more than 2 times in a row, will test him again on next ID.

Another bug I found:

Priestess' vortexes are now fine however you can kill them with thunder clap (lol). Make them immune to damage or something like invalid target.

**Comment by Moobe123** [comment]
Still not fixed btw. Got 2x WF procs on autoatk yesterday.
