### ISSUE TITLE
Significantly less damage and more resists on mobs 1 or more levels higher than you.

### ISSUE THREAD

**Issue by Moistcookie** [SunwellWoW/Sunwell-TBC-Bugtracker#415]
Decription: I was killing level 1 and 2 boars in the Orc/Troll starting zone (Valley of Trials) on a fresh level 1 troll shaman. The level 1's were taking normal damage with my lightning bolt, but upon attacking level 2 mobs with my lightning bolt, they were only taking 4 damage compared to the 13-15 damage the level 1's were taking, additionally, they were resisting my lightning bolts at least 50% or 60% of each cast. Note that this also happens on level 3 and up. I tried it on level 7 boars as a level 6, and it seems like it works as intended, but it still does significantly low damage sometimes, but not as much as the level 2's.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Cannot reproduce. Everything worked fine. Needs retest.

**Comment by Moistcookie** [comment]
I think the damage reduction isn't there anymore, but mobs do have a very high chance to resist spells if the mob is just 1 level higher than the player.

**Comment by Wojtyas** [comment]
Fixed for now. Feel free to reopen when new issue related with that bug occurs.
