### ISSUE TITLE
Pet dissapeared

### ISSUE THREAD

**Issue by kirkj89** [SunwellWoW/Sunwell-TBC-Bugtracker#4150]
Description: Hunter pet dissapeared after putting in stables

How it works:
After training King B and leveling with him to 58. Get to outland and put him in my stables and hes gone. Relogging did nothing. So frustrating, I know I can train something else but he had so many training points to max out skills and prowl is super fun in pvp as a NE. 

How it should work:
Pet should be stables. Not completely gone

PLEASE IF THERES A GM OUT THERE FIX THIS! I'm still in shock that I just lost all that work

**Comment by nickycakes** [comment]
this happened to me with my level 70 ravager i've had since level 11.  this really needs to be fixed considering the ungodly amount of time it takes to level pets, especially at max level

**Comment by nickycakes** [comment]
![image](https://user-images.githubusercontent.com/2413942/51492440-7093e380-1de4-11e9-9d72-0c07b1ff4112.png)

![image](https://user-images.githubusercontent.com/2413942/51492448-7984b500-1de4-11e9-936e-a0a3167fd293.png)

here's a conversation with an extremely unhelpful gm who insinuated it was my fault

**Comment by kirkj89** [comment]
Yeah they are completely useless. Multiple people have reported and they
just claim they've never heard of it

**Comment by YoshGit** [comment]
Yep can confirm there is a bug out there and GMs are unhelpful. Got a similar response
