### ISSUE TITLE
Windfury totem doesn't proc from Seal of Command 

### ISSUE THREAD

**Issue by Felynda** [SunwellWoW/Sunwell-TBC-Bugtracker#4151]
Description: 
Windfury totem doesn't proc from Seal of Command. In reverse it does work correctly, Seal of Command can proc from a Windfury totem hit.

How it works: 
Currently on server you will never see a windfury proc from Seal of command hit.

How it should work: 
Each Seal of Command hit should have 20% chance to proc Windfury totem.

Source (you should point out proofs of your report, please give us some source): 
A few Elitist Jerks forum posts screenshotted from http://web.archive.org/web/20080913120506/http://elitistjerks.com:80/f31/t17193-paladin_retribution_dps_theorycraft/
![soc proc wf 2](https://user-images.githubusercontent.com/45050227/51244636-db2cc580-1985-11e9-90a2-e3935952bf3a.png)
![soc proc wf 3](https://user-images.githubusercontent.com/45050227/51244642-dd8f1f80-1985-11e9-9ad0-b8aff38759d1.png)

**Comment by babno** [comment]
The windfury proc happens before the SoC proc. Looks like the windfury procced from the normal melee swing. I don't think SoC should proc windfury.

**Comment by Devrak** [comment]
Seal of Command ( original ) proc is considered a special melee attack that is followed 0.5 sec after melee attack and can trigger weapon trinket / based procs including Windfury and also benefit from vengeance if it was applied with the melee attack that procced it the unintended consequence of this was seal twisting.

Seal of Command ( custom sunwell community edition )  has seal twisting disabled and as a consequence it works just like seal of blood and does not proc anything other than vengeance.  

Its up to staff to decide what to do about this.

**Comment by Atrecom** [comment]
As far as I played paladin here, i`ve got SoC proc from WF, not reversed:
SO it looked like:
 AA+SoC + (WF+SoC).
Oneshotted that shaman...ouch :D

**Comment by akrom23** [comment]
Windfury proc only from melee attacks.

**Comment by Felynda** [comment]
@akrom23  That is exactly the point, Seal of Command IS a melee attack. It just deals holy damage, that's why it can proc Windfury Totem. Please look at the Elitist Jerks thread for proof.

**Comment by Devrak** [comment]
Yes it is a melee attack that does holy damage, and it should proc any weapon procs including windfury ... On retail it was delayed by 0.5 sec after weapon attack witch in turn made seal twisting possible since seal is a weapon proc much like windfury

**Comment by akrom23** [comment]
I see a lot of reports on other bugtrackers. Will look into it later.

**Comment by Felynda** [comment]
We're only trying to give you guys proper information, if you want us to help search specific infos just ask. :)

**Comment by akrom23** [comment]
What about Heroic Strike, Mortal Strike, Cleave, Slam, Devastate (warrior), Sinister Strike, Ambush, Backstab, Hemorrhage (rogue), Shred, Ravage, Mangle (Druid), Seal of Blood, Crusader Strike (paladin), Strormstrike (shaman), etc. - all of these should proc WF?

**Comment by Atrecom** [comment]
No it shouldn`t proc from special melee attacks like Mortal etc

**Comment by akrom23** [comment]
So proc from Seal of Command (special melee attack) and not proc from e.g. Sinister Strike (special melee attack)? ****ing logic, blizz :)

**Comment by Atrecom** [comment]
Like the fact WF cant proc form Crusader. 
Btw, Seal of blood for example: cant proc from Crusader strike. So SoC cant. Ezzz :D

**Comment by akrom23** [comment]
Yeah.
https://github.com/netherspite/cc-buglist/issues/44
Really, need more info guys, because I'm confused right now.. :)
I can fix this problem, but I'm not sure that it shoud work like this.

**Comment by akrom23** [comment]
I will add 0.5 sec delay to SoC to enables Seal Twisting.
Windfury proc from SoC still needs confirmation.

**Comment by Atrecom** [comment]
Well. I can test today, but it will take some time. dont fix anything. let me get some procs.

**Comment by Atrecom** [comment]
Oh, dear. May be u`ll add some training dummies to Shatt? Just to test smth about spells much faster

**Comment by akrom23** [comment]
Not needed anymore. I will fix it.

**Comment by Atrecom** [comment]
Okay. thx. So it will be in this way:
AA + wf
If SoC procs, wf can proc from it. Sure?

**Comment by akrom23** [comment]
- SoC triggers WF.
- Add 0.5 sec delay to SoC.
- Add 1 sec internal CD to SoC.
- Implement Seal Twisting (cast SoC -> melee attack swing -> cast other seal -> SoC proc -> other seal proc from SoC)

**Comment by Devrak** [comment]
:+1:  i am actually looking into windfury at the moment there have been alot of changes over the years gotta google for a while.

**Comment by Devrak** [comment]
Windfury Rules:

- White Attacks ( Auto Attack ) - Proc Windfury
- On Next Swing Attacks that consume auto attack ( Heroic Strike, Cleave etc.) - Proc Windfury
- Extra Weapon Attacks ( Blikstrike , Reckoning, Seal of Command ) - Proc Windfury
- Special Attacks ( Instantly deals x damage type CS MS etc ) - Do not Proc Windfury
- Weapon Extra Damage Attacks ( weapon does aditional x damage SoR, SoB etc ) - Do not proc windfury

Seal of command is an Extra Weapon attack by mechanic It has ( Should have ) separate weapon damage roll, delay, hit table, It should have an icd preventing proc chains.

Resources:
https://wowwiki.fandom.com/wiki/Blinkstrike
https://www.engadget.com/2007/08/09/blue-notes-windfury-and-voice-chat/
https://www.mmo-champion.com/threads/603849-sword-spec-and-windfury
https://wowwiki.fandom.com/wiki/Seal_of_Command_(old)?oldid=1432430

**Comment by Atrecom** [comment]
If i`m not mistaken only shamans got ICD on WF procs on their weapons, not totem. m?

**Comment by Devrak** [comment]
Yes the 3sec Icd is for weapon enchant and not totem also there is a limit that windfury proc attacks cannot trigger windfury 

The only thing i was not able to completely figure out is how seal of command icd is working The 1s icd is a theorycrater assumption .... 

In a case where an extra attack is triggered ( proced ) by seal of command attack that attack cannot proc seal of command ( to prevent chain )

In a case where an extra attack is triggered ( proced ) by white attack should it be possible to get double seal of command procs ? one from white swing 1 from extra ( ? ) all other seals can get double proc The mechanic here would be that SoC has Icd on procing from extra attacks ( ? ) Help wanted on this.

**Comment by Atrecom** [comment]
Soooo, does ur post say it should be 2 different ways:
1. (Aa+wf)/soc
2. (Aa+soc)/wf
 And never (aa+wf)+(soc+wf)?

And can't understand, do u ask a question or giving the answer?
