### ISSUE TITLE
Inner Focus Priest bug

### ISSUE THREAD

**Issue by Szusterx** [SunwellWoW/Sunwell-TBC-Bugtracker#4154]
Description: Inner focus CD buggd

How it works: 
After i use   IF cd wont show up  on action bar and in spellbook.  Its 3 min CD -  i didnt relog instantly  just after 10 min and  IF was still buggd on my bar and spellbook. Happends me with and without addons.

How it should work: 
CD should show up after use if + any spell 

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/Rde8oGw

**Comment by akrom23** [comment]
Nee more info here: #2915.
