### ISSUE TITLE
Arena matchmaking system is broken

### ISSUE THREAD

**Issue by estenv** [SunwellWoW/Sunwell-TBC-Bugtracker#4157]
Description: 
Arena matchmaking system is not working like it should. This is currently turning a lot of people away from arena and even making them quit the server as the pvp is not enjoyable. When teams with huge rating differences constantly have to play against each other with short queue times it's a very unenjoyable experience for both teams (low rated team gets stomped with no chance, high rated team wastes endless hours getting +1 point wins)

How it works: 
- You can face opponents with 300-500 rating lower than you with very short queue times (<60 sec)
- You very rarely face opponents at your rating, typically there can be multiple teams at 1900+ rating queueing for hours and both of them will only play against 1500 teams and never face each other even once (experienced this multiple times)

How it should work: 
- You should NOT get fast queues against teams with a large rating difference to you
- You SHOULD get fast queues against team at your own rating

Source (you should point out proofs of your report, please give us some source): 
- Very hard to provide any source for this as the details are not known but the matchmaking worked fine on every other HG core server I've played so I think you may have broken it somehow. Take literally any MM system (Hellfire/StockHG/Mangos) and it should be a huge improvement over this.

**Comment by kinghunterx** [comment]
yo this needs fix asap otherwise arena is gonna be deader than it is, fix this asap pls ty

**Comment by zmthc93** [comment]
-made multiple posts about this topic on forums and was asked for 'proof that it isn't working as intended' and post was locked
-there is also a bug with requeue where u can force games to start vs far lower teams faster by requeuing
-system should start looking teams the same rating as you and then slowly expand search parameters -+ rating as time passes until two teams matchmaking range intersects and game is triggered (should not be too hard to script this)

**Comment by milk92** [comment]
Allo dev's u sleeping? Go fix this shit.... Or we all go to Dogwing

**Comment by akrom23** [comment]
Some changes applied.
Needs test.

**Comment by Bugadin** [comment]
> -made multiple posts about this topic on forums and was asked for 'proof that it isn't working as intended' and post was locked
> -there is also a bug with requeue where u can force games to start vs far lower teams faster by requeuing
> -system should start looking teams the same rating as you and then slowly expand search parameters -+ rating as time passes until two teams matchmaking range intersects and game is triggered (should not be too hard to script this)

Listen to this guys because all he said it's correct.

For example: you can force a game if you queue a minute, leave queue and then requeue.
