### ISSUE TITLE
Surprise Attacks

### ISSUE THREAD

**Issue by Divezy** [SunwellWoW/Sunwell-TBC-Bugtracker#4158]
Description: Last talent in Combat tree doesn't work.

How it works: 
Special attacks are still dodging.
https://imgur.com/a/Ys60pLB

How it should work: 
Special attacks shouldn't be dodged.

Source (you should point out proofs of your report, please give us some source): Well talent description says it all.

I know it was here many times but it looks like nobody noticed.

**Comment by Bugadin** [comment]
Confirmed, I hope it get fixed soon.
