### ISSUE TITLE
Absent NPC in Stormwind

### ISSUE THREAD

**Issue by Jumpinlord** [SunwellWoW/Sunwell-TBC-Bugtracker#4159]
Description: In Stormwind city must be Frederick Stover, 30 lvl NPC that sells arrows, quivers and bows.

How it works: He's absent so I can't buy Jagged Arrow ( Lina Stover doesn't sell it).

How it should work: This NPC added in patch 1.11.1.7272.

Source (you should point out proofs of your report, please give us some source): http://wowwiki.wikia.com/wiki/Empty_Quiver

![wowscrnshot_011719_091338](https://user-images.githubusercontent.com/45316748/51299259-7a0dfc00-1a30-11e9-9819-3c583b7428ac.jpg)

**Comment by Dootz** [comment]
added
