### ISSUE TITLE
[Quest/Profession] Finishing the quest "Triage" does not increase First Aid skillcap to 300.

### ISSUE THREAD

**Issue by UlrikSagen** [SunwellWoW/Sunwell-TBC-Bugtracker#4160]
Description: 
After finishing the quest "Triage" it did not increase my first aid skill cap to 300. I am still at 225/225 

How it works:
You finnish the quest as normal, but nothing happenes.

How it should work: 
You finnish the quest and your first aid skill cap raise to 300.

Source (you should point out proofs of your report, please give us some source):

**Comment by Mikov1605** [comment]
https://www.wowhead.com/quest=6624/triage#comments
One of the comments says the doctor should teach us automatically

**Comment by Shika88** [comment]
Same problem for me

**Comment by Felynda** [comment]
Are you horde or Alliance? I am alliance and it worked perfectly for me a few weeks ago.

**Comment by Shika88** [comment]
Horde. I still have bandage from the quest. Is It normal?

**Comment by UlrikSagen** [comment]
Im also Horde, and did also have the Triage bandage in my bags after turning the quest in,
I contacted a GM and got it fixed.

**Comment by Shika88** [comment]
How do i contact a GM?

**Comment by UlrikSagen** [comment]
Press the red question mark at the bottom of your screen. Then press "talk to a GM".

**Comment by Shika88** [comment]
Thank you :)

**Comment by blackabbath** [comment]
Still not work for the Horde.
For the alliance it works without issues.

**Comment by Reflekz** [comment]
@blackabbath Alliance does NOT work currently

literally just did it and we had to have a GM come and fix the 3-4 of us who didnt get the max skill to 300 upon completing the quest.

**Comment by Cherryxo** [comment]
After you've completed the quest you can talk to him and train it.
