### ISSUE TITLE
Second Wind Procs even on resists... 

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#4161]
Description:   Posting again since last report got closed...... and its still not fixed...
Warrior arms talent, second wind (Shown in link but with incorrect rage tooltip on website) will proc even when stuns/roots resist.
**https://db.excalibur.ws/?spell=29838**
How it works: 
if your stun or root resists on warrior,  it gives him second wind buff... ( which gives player rage/health) which is just mocking the reason it exists in the first place (to give you *something* for not being able to do anything) 

How it should work: 
it should not proc on resists.

Source (you should point out proofs of your report, please give us some source): 
easy to test, im betting it might evven work when you resist low level cc too (but maybe not)

**Comment by akrom23** [comment]
Tested - does not proc on resist.
