### ISSUE TITLE
Qiff Area 52

### ISSUE THREAD

**Issue by za-x-az** [SunwellWoW/Sunwell-TBC-Bugtracker#4162]
Description:  a goblin by name Qiff was added in patch 2.2.0.7272 considering we are playing emulated patch 2.0/2.1 or something like that right now he and what he is selling should not be in the game amt!

How it works: 
He should NOT be in game until patch 2.2.0

How it should work: 
He should BE in the game after patch 2.2.0

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/npc=19575/qiff

**Comment by notsofamous** [comment]
A lot of comments from patch 2.0 talking about him being in Area 52.

2.0 Comments:

> sit next to him and watch =P that's how i got mine.

> My theory on how his name came about is as follows.
Qiff is a green goblin, but notice how he is in Area 52 and not any where else.
Kif Kroker of Futurama is the personal assistant to Captain Zapp Brannigan.
With him being in Area 52 and in Netherstorm, one can safely say that they thought of this name by none other than watching Futurama.

2.1 Comments:

> Been camping that Khorium power core for more than 2hours now. The other stuff he sells has: a 20min respawn on bolts, aprox 60 mins on adamantite frame and flares. Khorium power core - still waiting...

> Khorium power core did not appear after a rolling restart.

> Qiff is not part of any faction. Which means no discount on goods or repairs for honored rep.

> i camped him from midnight, 00:00 - 5:30 in the morning, no spawns, then again from 13:30-15:05 The respawn time is very long for sure, but finaly got it

> In the time it takes you to camp this you can easily farm the money to buy the stuff off the AH. Just do some daily quests.

Etc... Obviously he was in game prior to patch 2.2

**Comment by za-x-az** [comment]
> A lot of comments from patch 2.0 talking about him being in Area 52.
> 
> 2.0 Comments:
> 
> > sit next to him and watch =P that's how i got mine.
> 
> > My theory on how his name came about is as follows.
> > Qiff is a green goblin, but notice how he is in Area 52 and not any where else.
> > Kif Kroker of Futurama is the personal assistant to Captain Zapp Brannigan.
> > With him being in Area 52 and in Netherstorm, one can safely say that they thought of this name by none other than watching Futurama.
> 
> 2.1 Comments:
> 
> > Been camping that Khorium power core for more than 2hours now. The other stuff he sells has: a 20min respawn on bolts, aprox 60 mins on adamantite frame and flares. Khorium power core - still waiting...
> 
> > Khorium power core did not appear after a rolling restart.
> 
> > Qiff is not part of any faction. Which means no discount on goods or repairs for honored rep.
> 
> > i camped him from midnight, 00:00 - 5:30 in the morning, no spawns, then again from 13:30-15:05 The respawn time is very long for sure, but finaly got it
> 
> > In the time it takes you to camp this you can easily farm the money to buy the stuff off the AH. Just do some daily quests.
> 
> Etc... Obviously he was in game prior to patch 2.2

the comments can be wrong on patch info connected to them i dont know or its right they thing is that he is noted as added patch 2.2.0.7272 and on other tbc server i have played on witch was progressive he was added in patch 2.2.0 and i cant find any sources saying he was added before.

**Comment by notsofamous** [comment]
You can check the dates the comments were posted on... "By onesimus (873 – 8·4) on 2007/02/27 (Patch 2.0.8)"

There is even a screenshot of him uploaded on 2007/02/22. Patch 2.2 was released about 7 months later. 

You can look at other NPCs in Netherstorm and it'll say they were also added in patch 2.2: https://www.wowhead.com/npc=19645/papa-wheeler
https://www.wowhead.com/npc=20907/professor-dabiri
https://www.wowhead.com/npc=21732/nandirx


You can also compare the NPC ID of Qiff (19575) to an NPC added in patch 2.1. In this case, Teron Gorefiend (22871). Qiff has a much lower ID suggesting he was added earlier, i.e. before patch 2.1.

**Comment by za-x-az** [comment]
> You can check the dates the comments were posted on... "By onesimus (873 – 8·4) on 2007/02/27 (Patch 2.0.8)"
> 
> There is even a screenshot of him uploaded on 2007/02/22. Patch 2.2 was released about 7 months later.
> 
> You can look at other NPCs in Netherstorm and it'll say they were also added in patch 2.2: https://www.wowhead.com/npc=19645/papa-wheeler
> https://www.wowhead.com/npc=20907/professor-dabiri
> https://www.wowhead.com/npc=21732/nandirx
> 
> You can also compare the NPC ID of Qiff (19575) to an NPC added in patch 2.1. In this case, Teron Gorefiend (22871). Qiff has a much lower ID suggesting he was added earlier, i.e. before patch 2.1.

I see where u are going with that, but that logic doesn't work when talking id on an NPC in a game he can have been meant to be in from let's say 2.0.0 but some last minute change pushed him to be added in 2.2.0 then he would have a lower ID than another NPC that was made close to launch of TBC

the same can be true with an item ID.
the only place that logic work is the version number.

**Comment by notsofamous** [comment]
There's overwhelming evidence of this NPC being in game at launch. Screenshots, comments, NPC ID... everything lines up.

> The Burning Crusade Patch 2.0.3 (2007-01-09): Added. 
https://wow.gamepedia.com/Qiff


The fact that every NPC in netherstorm says that it was added in 2.2 is also evidence that the "added in patch" thing isn't accurate on wowhead.

**Comment by Dootz** [comment]
I think we'll leave him where he is now. But thank you for bringing it up.
