### ISSUE TITLE
A Dip In The Moonwell not working.

### ISSUE THREAD

**Issue by RarecandyMage** [SunwellWoW/Sunwell-TBC-Bugtracker#4163]
Description: Use an item to take control of a mechanical robot.  Use robot to gather water from moonwell, seems bugged.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=2U57vcgMlFs

**Comment by Azmoddan** [comment]
What is bugged? You can't cancel the control buff? Precise yourself.

**Comment by Dootz** [comment]
he attached video. he doesnt get credit apparently :(

**Comment by Dootz** [comment]
I tried many different things but I was not able to recreate it. Worked fine for me everytime. Are you sure you have empty slot in you bags? Because item is created upon spellcast and you need to have space for it in bags.

**Comment by RarecandyMage** [comment]
I'm going to test the quest with an open bag slot maybe that was the issue.
EDIT: WORKS, Maybe the issue was my bags were full.
