### ISSUE TITLE
Rogue Poison Quest missing

### ISSUE THREAD

**Issue by Vandarc** [SunwellWoW/Sunwell-TBC-Bugtracker#4164]
Description:  So ive got lvl 20. Went to OG and grabed the Quest"Deep Cover" for the Rogues Posion. Went to the wanted area, did the flare and logged out after. After a day ive logged in and the guy was killing me. Obviously since i didnt do the flare. 
So after i was left without the quest and i cant pick it up either.  I had the flare still in my inventory up to like an hour ago. Deleted it was hoping it might trigger something. But still nothing. 

Edit: i will just start a new char from 0 again. Feels bad wasting 24 hours playtime hehe, but i need my poisons or this Rogue is kinda useless. And i know how to avoid that bug on a new Char. But that Bug is still a thing i guess :)

**Comment by kmayberry91** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1963
