### ISSUE TITLE
[NPC]Dragonmaw Elite

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#4166]
Description: 
This NPC desnt count for the quest Infiltrating Dragonmaw Fortress

How it works: 
![image](https://user-images.githubusercontent.com/43579401/51377591-96329b80-1b0b-11e9-9a08-2a57ab750d31.png)

How it should work: 
Quest Descriptions says "ANY orc at Dragonmaw Fortress will count"

Source (you should point out proofs of your report, please give us some source):

**Comment by Bugadin** [comment]
Can confirm it.
