### ISSUE TITLE
[Talent][Imporant]Ignite - please fix it already

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#4169]
Description: 
i know its open here - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3979 - but still, noone cared to fix this. Adding high priority and ignoring it for 10 days isnt the thing we, fire mages, expect. Its a mayor dps loss with two fire mages in a group/raid.

How it works: 
Ignite is overwritten by 2nd ignite(from any fire mage).

How it should work: 
It should be posibble to have seperate ignites on the target. For example, maghteridon 25, 3 fire mages in group, all 3 land a critical fire spell crit. All 3 should put ignite on target.

Source (you should point out proofs of your report, please give us some source):

**Comment by MadderThenMad** [comment]
Upvote for this...
