### ISSUE TITLE
Bug: Can't Banish warlock pets. Recieving error: Target is tapped.

### ISSUE THREAD

**Issue by kyotpls** [SunwellWoW/Sunwell-TBC-Bugtracker#4171]
**Description:** 
When attempting to banish a warlock pet (i.e Felhunter) a error message appears saying "Target is tapped" and the cast won't start. This was not a problem yesterday or the previous days. This is very gamebreaking when playing against other warlocks. Please sort this issue.

**How it works:** 
Attempting to cast banish on warlock pet. Is then denied by recieving error message "Target is tapped"

**How it should work:** 
Should be able to start a banish cast without any issue.

**Source (you should point out proofs of your report, please give us some source):** 
![tapped1](https://user-images.githubusercontent.com/37027911/51388122-cc324880-1b28-11e9-9385-8bfa24ad85c9.jpg)
![tapped2](https://user-images.githubusercontent.com/37027911/51388127-cf2d3900-1b28-11e9-9571-623d733e7a20.jpg)
![tapped3](https://user-images.githubusercontent.com/37027911/51388135-d0f6fc80-1b28-11e9-8b7a-23dec61b5f70.jpg)

**Comment by ZaoQ** [comment]
Is it applied?
