### ISSUE TITLE
Grey enemies in dungeons 

### ISSUE THREAD

**Issue by maseta9** [SunwellWoW/Sunwell-TBC-Bugtracker#4173]
Description: Sometimes when you are in a dungeon and give the lead to a specific bugged person (this becomes annoying when the bugged person is the party's tank), from that moment on all enemies who are pulled by that person will be automatically tagged as a grey named mob and no one will be able to loot the mob when dead, not even the person who pulled it in the first place. It has an easy fix, with a log out and log in it fixes itself, but it's still pretty annoying.

How it works: If a player is bugged and has the lead of the group inside a dungeon, the target enemy will become tagged when pulled and won't drop any items for anyone in the party.

How it should work: Enemies should be lootable by the party doing the dungeon.

Source (you should point out proofs of your report, please give us some source):

**Comment by twoPlusThree** [comment]
I've noticed some gray mobs in dungeon (stockades) when entering an instance solo without a group too.
