### ISSUE TITLE
PvP accessories - General's Mooncloth

### ISSUE THREAD

**Issue by mhdemn** [SunwellWoW/Sunwell-TBC-Bugtracker#4176]
So from what I've been able to learn the pvp accessories for PvP healing weren't introduced until 2.4.3. So please add the cloth healing pieces or remove the leather, mail and plate ones, I guess. Huge unfairness for priests.

**Comment by notsofamous** [comment]
There isn't any Cloth, Mail or Plate Healing offset in s1. 

And by that I mean **it literally doesn't exist**, so there is nothing they can put in game.

**Comment by mhdemn** [comment]
well you should literally check the vendor and see for yourself

**Comment by notsofamous** [comment]
I have? By literally doesn't exist I mean that blizzard did not create these items. There is nothing in the database for them to add to the vendor.
