### ISSUE TITLE
Sha`tar reputation via Fel armament or Arcane Tome

### ISSUE THREAD

**Issue by Petarrda** [SunwellWoW/Sunwell-TBC-Bugtracker#4179]
Description: When you turn 1x fel armament/ arcane tome, your reputation with aldor/scryer increase with 350 and also your reputation with sha`tar should increase by 175.

How it works: 
It increase indeed the reputation with the specific faction, but it dosen`t with the sha`tar.

How it should work: 
Should increase the reputation with sha`tar by 175 at every piece you turn, untill honored.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Fel_Armament

**Comment by wombo2u** [comment]
Yes, your rep with shatar is increased until you reach honored. Not after that. It is working as intended
