### ISSUE TITLE
[Warlock][Spell][Pet] Succubus Seduction and Lesser Invisibility

### ISSUE THREAD

**Issue by Aikamz** [SunwellWoW/Sunwell-TBC-Bugtracker#4181]
Description: 
Succubus Seduction and Lesser Invisibility have multiple issues that make this pet useless in its current state.

How it works:
1) Lesser Invisibility has diminishing returns. If you have it set on auto-cast, she will just spam it and oom herself. Sometimes she even spams it while in combat.
2) When your Succubus is out of range to cast Seduction, Lash of Pain or Soothing Kiss it will give error instead of making her run in range and start casting. You can cast petattack from the same distance without any issues.

How it should work: 
1) There should be no DR on Lesser Invisibility.
2) If your Succubus is out of range and you order her to cast Seduction, Lash of Pain or Soothing Kiss, she should move in range without breaking Lesser Invisibility and then drop Invisibility and start casting the ability.

Source (you should point out proofs of your report, please give us some source):

**Comment by Aikamz** [comment]
The 2nd point is general issue with other pets as well.

**Comment by zocks** [comment]
fix it please makes succubus unusable as a pet in competitive pvp

**Comment by akrom23** [comment]
> 2\. If your Succubus is out of range and you order her to cast Seduction, Lash of Pain or Soothing Kiss, she should move in range without breaking Lesser Invisibility and then drop Invisibility and start casting the ability.

@Aikamz Do you have any proof?
