### ISSUE TITLE
Priest cant power word shield on other peoples pet. Critical for arenas

### ISSUE THREAD

**Issue by OnMyPeak** [SunwellWoW/Sunwell-TBC-Bugtracker#4182]
Description: you cant use the power word shield on a hunters pet no matter what you do.

How it works: the power word shield spell is grey when targeting a pet.

How it should work: you should be able to power word shield a pet.

Source (you should point out proofs of your report, please give us some source): 
just try use a power word shield on a hunters pet in your group.

**Comment by Azmoddan** [comment]
@jeppe010 it works now or not?

**Comment by OnMyPeak** [comment]
@dolamor tried it 12h ago. Still didnt work
