### ISSUE TITLE
Stealth tickrate is awful

### ISSUE THREAD

**Issue by Aikamz** [SunwellWoW/Sunwell-TBC-Bugtracker#4183]
Description: 
Stealth tickrate is too low for competitive PvP. Renders stealth detection useless.

How it works: 
Tested it multiple times. 50% of the time rogue won't be revealed once he enters stealth detection range for few seconds until stealth update happens. Other times rogue is visible the second he is on top of the flag.
https://www.youtube.com/watch?v=MMECUuHKGoA
Both players have 60ms ping. Rogue isn't even sprinting.

How it should work: 
Rogue should be visible the second he enters Stealth detection range.

Source (you should point out proofs of your report, please give us some source):

**Comment by Bugadin** [comment]
True, I guess stealth detection isn't working properly. I'm not sure if it's the stealth's detection range or the way it ''updates'' to detect stealth's people in range like Aikamz says.

It happens with perception too and also with druid's stealth. It should be WAY EASIER to detect stealth people with perception or paranoia.

**Comment by Bugadin** [comment]
I think it's working fine now, thank you
