### ISSUE TITLE
[Item] Leggings of Beast Mastery

### ISSUE THREAD

**Issue by vakoz** [SunwellWoW/Sunwell-TBC-Bugtracker#4185]
#### Description:
Bonus from item http://db.darkwizard.pl/?item=31328 is not working at all.
"Equip: Increases your pet's attack power by 70, armor by 490 and Stamina by 52."
#### How it works: 
Those are stats from my character.
Pet bonus stats from hunter's stats (after - before item equipped);
![wowscrnshot_012019_003519](https://user-images.githubusercontent.com/15368930/51433774-6e018480-1c52-11e9-954b-5655b21179b9.jpg)
stamina: 117 - 104 = 13
attack power:  240 - 233 = 7
armor: 1487 - 1249 = 238
And only those values are added to pet's stats after equipping leggings (no single bonus stat from item's equip effect):
![wowscrnshot_012019_003619](https://user-images.githubusercontent.com/15368930/51433792-f4b66180-1c52-11e9-8b67-3ebf2534f942.jpg)
**Edit: also I tried to relog and dismiss pet, but it doesn't change anything**
#### How it should work: 
Item should provide stats from tooltip:
Equip: Increases your pet's **attack power by 70**, **armor by 490** and **Stamina by 52**.
#### Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?item=31328

**Comment by Wojtyas** [comment]
Can be only visual cuz we had this kind of issue before we will check for sure.

**Comment by vakoz** [comment]
Yes, you are right. I just tested it with Beast Lore and values are correct
