### ISSUE TITLE
[NPC]Random Mobs all over The world are gray

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#4186]
Description: 

Happened with Rift Lord, astromancer (mechanar trash) , Julianne, some mobs i encountered in shadowmoon
Its annoying because tagged mobs cant be cced
How it works: 
Description

How it should work: 

They obviously should be tagged only after attacking thrm
Source (you should point out proofs of your report, please give us some source):

**Comment by Bugadin** [comment]
All mobs, including raids and dungeons.
