### ISSUE TITLE
Warrior talent Defiance

### ISSUE THREAD

**Issue by GeorgieTragnar** [SunwellWoW/Sunwell-TBC-Bugtracker#4188]
Description: 
the +6 expertise is added only when in defensive stance, but it should in all stances (also the official 2.3 patch notes imply that +6 expertise is at all times which the elitistjerks support)

How it works:
+6 expertise only in def stance

How it should work:  
+6 expertise in all stances (at all times)

Source (you should point out proofs of your report, please give us some source): 
"Up to Defiance (with last stand option). 
With 3 points of Defiance giving 6 points of expertise in all stances (since 2.3), this is a particularly attractive option for a lot of currently full-DPS warriors. Between the shield specialization route and the toughness route, it's likely better for raid offtanking to go for improved shield block. Two charges give significantly better crush protection. The 15% threat from defiance also makes a large impact on the levels of sustained TPS one can maintain. "

https://web.archive.org/web/20100405064432/http://elitistjerks.com/f81/t18771-protection_guide/
http://wowwiki.wikia.com/wiki/Patch_2.3.0

**Comment by firngrod** [comment]
Technically, as of 2.3.0, it was only defensive stance.  It was patched to all stances in 2.3.2.  According to patch notes, this was the original intent.

http://wowwiki.wikia.com/wiki/Patch_2.3.2

**Comment by Ibuprofeno** [comment]
All mechanics should be properly tuned to 2.4.3 it being changed in 2.3+ should make no difference to get this fixed.
Otherwise I'll start listing every change pre-2.4.3 to have 2.0 mechanics? This is unrealistic.

**Comment by firngrod** [comment]
Indeed.  I just wanted to point to the more definitive proof to make it easier for the devs to verify, rather than them looking into how it was at 2.3.0 as OP suggested and possibly deciding that the expertise should only apply to defensive stance because that's how it was at that point.

**Comment by GeorgieTragnar** [comment]
This is wrong point, because devs are aiming at 2.4.3 mechanics and in 2.4.3 patch this talent worked for all stances (since the patch 2.3.2).
