### ISSUE TITLE
Shattrath Armorsmith trainer missing

### ISSUE THREAD

**Issue by leafwork** [SunwellWoW/Sunwell-TBC-Bugtracker#4189]
![wowscrnshot_012019_153914](https://user-images.githubusercontent.com/46874632/51445388-df304e80-1cc9-11e9-8ce3-de9c160da7a1.jpg)
Description: 
The armorsmith trainer in Shattrath (Zula Slagfury) is not present.

How it works: 
The armorsmith trainer in Shattrath (Zula Slagfury) is not present.

How it should work: 
Zula Slagfury should be at the second anvil next to the weaponsmith trainer.

Source (you should point out proofs of your report, please give us some source):

**Comment by Phildo9** [comment]
Bump
