### ISSUE TITLE
Escort NPC's move too fast

### ISSUE THREAD

**Issue by Bezawitt** [SunwellWoW/Sunwell-TBC-Bugtracker#419]
Decription:  Escort NPC's currently move faster than a character

How it works: When doing an escort, the npc moves too quickly. It is difficult to keep pace when running along side an escort npc.

How it should work: You should be able to easily out-pace the npc you are escorting

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=uJZYfAOPtsc

**Comment by Riztazz** [comment]
Which escort, i believe this is specific mob issue, not escorts in general

**Comment by Bezawitt** [comment]
The ones I tested were all 3 Chicken escorts (Tanaris/Hinterlands/Feralas) and Kaya Flathoof
