### ISSUE TITLE
Magtheridon clickers on cubes

### ISSUE THREAD

**Issue by GeorgieTragnar** [SunwellWoW/Sunwell-TBC-Bugtracker#4191]
Description: 
clickers currently get damage in a wrong way, because currently they get a dot that deals dmg to them instead getting damage from the channel itself(similar as warlock hellfire spell) when clicking the cube

How it works: 
players get dot on them when they click the cube that cannot be taken down

How it should work: 
players get 800dmg per tick from the channel itself and the dmg stops when they stop channeling

Source (you should point out proofs of your report, please give us some source): 
"Will deal 800 damage per second to a player channeling it. If all 5 cubes are clicked at once, the Blast Nova will be interrupted and Magtheridon will not attempt to cast it for another minute."

http://wowwiki.wikia.com/index.php?title=Magtheridon_%28tactics%29&diff=569943&oldid=569187

**Comment by RPAncap** [comment]
¨Does the dot stop when he stops clicking the cube ?

**Comment by GeorgieTragnar** [comment]
That's the thing it does not
