### ISSUE TITLE
Engineering Recipe Discombobulator Ray Unavailable

### ISSUE THREAD

**Issue by RealSlyGuy** [SunwellWoW/Sunwell-TBC-Bugtracker#4192]
Description: You should be able learn "Discombobulator Ray" from the Dataport: 3005-D in the Tinkerer section just past the backdoor in Gnomer. It should give you the recipe directly to your engineering book as long as you have the "DELTA Access Card" in your backpack, which I do. (low drop rate off mobs in that section.)

How it works: It looks clickable, but no notification pops-up nor anything learned when clicking on it. Basically, nothing happens.

How it should work: On click with DELTA Access Card in inventory, you should get a notification in text saying, "Your learned Discombobulator Ray, recipe added to your Engineering notebook." or whatever. At that point, you should now have access to make the super coveted (by me) Discombobulator Ray!

Source (you should point out proofs of your report, please give us some source): Added in patch 1.11.1.5462, should be accessible in 2.4.3. https://www.wowhead.com/item=4388/discombobulator-ray#comments Check comments for how it should be accessible, and why it is SO AWESOME!

**Comment by RPAncap** [comment]
Can confirmm was there aswell and those machines dont work.
