### ISSUE TITLE
[Warlock][Spell]Warlock - Eye of Kilrog - Can't use pet bar or commands after eye desummons

### ISSUE THREAD

**Issue by Ember0090** [SunwellWoW/Sunwell-TBC-Bugtracker#4193]
Description: After using Eye of Kilrog and having it desummoned or timed out, the current pet bar disappears and the control commands can't be used until the user interface is reloaded.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azmoddan** [comment]
Might be a core bug as it is globally bugged - happened for me when used quest item that summon guardian-type mob for you or a mob that you can control and have to use one of its skills.

@akrom23

**Comment by babno** [comment]
I've noticed this as well. As a temporary work around if you mount and then dismount your pet bar comes back.
