### ISSUE TITLE
Advanced target Dummy [Engineering]

### ISSUE THREAD

**Issue by Bugadin** [SunwellWoW/Sunwell-TBC-Bugtracker#4194]
Description: Advanced target dummy doesn't drop anything when it dies and it should drop 
https://vanilla-twinhead.twinstar.cz/?npc=2674

How it works: Dummy follows you and doesn't drop anything when it dies.

How it should work: He shouldn't follow you and he should drop the items on the list.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Advanced_Target_Dummy
https://youtu.be/kmLySuPehPQ?t=34
https://vanilla-twinhead.twinstar.cz/?npc=2674

**Comment by RealSlyGuy** [comment]
Yay! Very excited when this is fixed! Actually the most economical way to get Fused Wiring before being able to engineer Fused Wiring for crafting Goblin Jumper Cables! Yay!

**Comment by Bugadin** [comment]
Thank you Afgann

**Comment by Afgann** [comment]
There are still some problems with looting, trying to figure it out, for now dummy won't follow owner.

**Comment by Bugadin** [comment]
Did you find anything? @Afgann

**Comment by Bugadin** [comment]
Is it really fixed...? Because it's not lootable

**Comment by Afgann** [comment]
It isn't, closed because of fixed label, my bad.

**Comment by Bugadin** [comment]
It's not fixed yet. It drops loot but you can't take it.

**Comment by Bugadin** [comment]
any new? @Afgann @akrom23

**Comment by RPAncap** [comment]
Can confirm this still happens. Could you guys fix this ... it is pretty important thing - as looting target dummies is one of the main ways of getting Fused Wiring which is required to make Repair Bots (as the TBC ones are not avaliable in this patch).

**Comment by RPAncap** [comment]
Still the same : here is the video
https://youtu.be/W1krSTPszL8
