### ISSUE TITLE
Mob respawn

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#4197]
Description: 
Mob respawn often bugs out.

How it works: 
In many places (eg Shadowmoon Valley Wind Elementals, Incendosaurs and many more) mobs don't respawn if a player character is in close proximity to the spawn point.

How it should work: 
Mobs respawn at the end of their spawn timer regardless if there's someone close or not.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azmoddan** [comment]
Some mobs might have few spawn-points, are you sure those elementals should spawn every time in the same place?

**Comment by akrom23** [comment]
More info, please.
