### ISSUE TITLE
Sending Mails from Trial Accounts to friends

### ISSUE THREAD

**Issue by Aequita** [SunwellWoW/Sunwell-TBC-Bugtracker#4198]
**Description:** 
When trying to send a mail from a character with level<14 to somebody who got you on their friend list, an error message sometimes appears when said character is offline.
Something along the lines of "Trial accounts are permitted from this action" (can't recall it 100% correctly)

**How it works:** 
Receiver has to go online for you to be able to send a mail with a level<14 character. 

**How it should work:** 
Being able to send mails to people who got you on their friend list, no matter if they are online or not.

**Source (you should point out proofs of your report, please give us some source):** 
Currently unavailable to create a screenshot.
Will attach later if necessary.

**Comment by koostosh** [comment]
could not reproduce
