### ISSUE TITLE
[Mage][talent][spell][bug] All armor spells and some mage talents are refreshed multiple times

### ISSUE THREAD

**Issue by Nijlas** [SunwellWoW/Sunwell-TBC-Bugtracker#42]
Decription: [30482][27215][7301][27124] Armor spells when refreshed, will be refreshed 2-3 times in the combat log. Same goes for Ignite [12848] Clearcasting proccs

How it works: 
When spells are refreshed on players and target, it refreshes 2-3 times as seen in combat log

How it should work: 
It should be refreshed once

Source (you should point out proofs of your report, please give us some source): 
![untitled](https://user-images.githubusercontent.com/42065276/43641896-a19e371e-9725-11e8-9f70-a8f4c4c39fe9.png)

**Comment by Riztazz** [comment]
re-test please

**Comment by akrom23** [comment]
Won't fix. Needs aura system rewrite.
