### ISSUE TITLE
Warlock Succubus quest

### ISSUE THREAD

**Issue by zolano123** [SunwellWoW/Sunwell-TBC-Bugtracker#4203]
Warlock quest devourer of souls does not work for my character keeps repeating do not meet requirements and will not let me retake the quest.  Spoke to a few gms about it but they could not assist told me to report here.

**Comment by sodix90** [comment]
yes quest giver dosnt give me the quests iam now level 70 cant get my succubus/felhunter

**Comment by Dootz** [comment]
Hi, do you remember which quest from chain you did as last one? Do you play on Alliance or Horde side?

**Comment by sodix90** [comment]
I was able to find it after GM teleported me to UC Horde side

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
