### ISSUE TITLE
trinket usage

### ISSUE THREAD

**Issue by lolproxoxo** [SunwellWoW/Sunwell-TBC-Bugtracker#4204]
Description: 
Xi'ri's Gift shares use cooldown (15 sec) with Scryer's Bloodgem how it should, but it already shares full CD (1 min 30 secs). It's not a visual cd, but u cant use Xi'ri's Gift after Scryer's Bloodgem buff fades or vice versa

How it works: 
Xi'ri's Gift shares use cooldown (15 sec) with Scryer's Bloodgem how it should, but it already shares full CD (1 min 30 secs). It's not a visual cd, but u cant use Xi'ri's Gift after Scryer's Bloodgem buff fades or vice versa
How it should work: 
Xi'ri's Gift shouldn't share full CD (1 min 30 secs) with Scryer's Bloodgem

Source (you should point out proofs of your report, please give us some source):

**Comment by wombo2u** [comment]
Some trinkets share cd, perfectly normal
