### ISSUE TITLE
(Delete this, I made the best report)

### ISSUE THREAD

**Issue by arkatik** [SunwellWoW/Sunwell-TBC-Bugtracker#4205]
How it works: 
When you catch intercept use shadowstep, warrior unfolds and continues to intercept

How it should work: https://youtu.be/Ba6Ty72eSH8?t=55

Source (you should point out proofs of your report, please give us some source):

**Comment by Bugadin** [comment]
So... what's exactly the bug? I mean, should that happens or not? Does it happen in sunwell?

**Comment by arkatik** [comment]
warrior as if running around an obstacle and 
he is catching up after shadowstep...try to repeat

**Comment by wombo2u** [comment]
This is purely a spell batching issue, same with 2 rogues sapping each other or similar. It can't be changed just like that

**Comment by arkatik** [comment]
@akrom23 yesterday this bug was repeated in the arena, fix pls

ps **druid charge-->shadowstep** work fine
