### ISSUE TITLE
Rogue Vanish Deaggro Failure

### ISSUE THREAD

**Issue by Killadoza** [SunwellWoW/Sunwell-TBC-Bugtracker#4207]
Description: Multiple times tonight, I have used Vanish to leave combat and deaggro mobs, but on three occasions, the mobs stayed in combat, never even pathing away and back as if i entered stealth and immediately left. As a disclaimer, no DoTs were on me at the time.

How it works: Vanish will intermittently fail to disengage or deaggro mobs

How it should work: Upon Vanishing, enemies should head back to their previous spot and fully heal, as is normal for a reset

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@Killadoza Send some screenshots with combat log.

**Comment by akrom23** [comment]
No response. Closed.
