### ISSUE TITLE
Six Of Blessings

### ISSUE THREAD

**Issue by Lichbait** [SunwellWoW/Sunwell-TBC-Bugtracker#4208]
Description: 
Six of Blessings doesn't drop

How it works: 
Doesn't drop

How it should work: 
Does drop

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/item=31887/six-of-blessings

**Comment by pinkisnotgay** [comment]
Just because you are struggling to buy it for last couple days on Global, doesnt mean it's not dropping. There are people with Blessing Deck completed already.
Also TBC cards were introducted in 2.1

**Comment by Lichbait** [comment]
>There are two completed decks on the server, therefore 6's rarity isn't
abnormal
*Sips Tea*

**Comment by akrom23** [comment]
It has very, very low chance, but it does drop.
