### ISSUE TITLE
Vanish / Stealth bug ( high priority) !!!

### ISSUE THREAD

**Issue by arkatik** [SunwellWoW/Sunwell-TBC-Bugtracker#4211]
Description: 

How it works: after using Vanish or Stealth you are still noticeable for a few seconds. 
So, a few seconds after using  [vanish] or [ stealth] to other players are you still visible and they make blinding, intercept, sap etc, or or just blow.

How it should work:[Vanish]  Allows the rogue to vanish from sight, entering an improved stealth mode for 10sec. Also breaks movement impairing effects.

Source (you should point out proofs of your report, please give us some source): 
easy to check by yourself

**Comment by akrom23** [comment]
Is it something new?

**Comment by arkatik** [comment]
> Is it something new?

and it already was? how long ago ? 
pvp is not real on NB :(( 
bg play 6-12 ppl, there are almost no arenas

**Comment by akrom23** [comment]
@arkatik Got some screenshots? I need to know in which situations it's broken.

**Comment by babno** [comment]
You can see through stealth from a limited distance, longer distances with things like engi goggles or perception.

**Comment by SlizeTBC** [comment]
No man, it's just a game mechanic that not working correctly. Like if you Vanish they can still see you for like 1sec and attack you, and get you out of Stealth again.

**Comment by SlizeTBC** [comment]
Normally Attacks, which were made at the same time a Rogue uses Vanish, should Evade and fully be dodged by the Rogue so he can stay in Stealth and is out of combat, but somehow this is not working correctly.

**Comment by arkatik** [comment]
after CoSh and Vanish priest easy drop my stealth using a shot wand
![wowscrnshot_012419_120029](https://user-images.githubusercontent.com/45844525/51673079-cda2bb80-1fd5-11e9-9ea1-56fbc5b42e74.jpg)

**Comment by SlizeTBC** [comment]
Yea thats exactly what I was trying to explain.

**Comment by arkatik** [comment]
works correctly vanish ? (sorry for the bad quality)
https://www.youtube.com/watch?v=yX9oOQUI7cg

**Comment by akrom23** [comment]
Thanks for the video.

**Comment by arkatik** [comment]
> Thanks for the video.

There are many more points to test:
intercept - shadowstep dont work 
intercept after use vanish 
poly after use vanish etc

**Comment by arkatik** [comment]
tru story guys...ench killed me when I was in the improved stealth for a few seconds :((
![wowscrnshot_012419_175041](https://user-images.githubusercontent.com/45844525/51690285-0dcb6380-2001-11e9-868a-c98841676d70.jpg)

**Comment by akrom23** [comment]
I found what is the cause of these problems.

**Comment by arkatik** [comment]
> I found what is the cause of these problems.

it's good)
How soon can you apply fixes?

**Comment by akrom23** [comment]
Today I guess :)

**Comment by baade123** [comment]
I also notice that i can see rogues from 30+ yards away for about 3-6 seconds after they stelath and they can see me too (i went stealth and 3 seconds later i got charged from warrior from far away)

**Comment by akrom23** [comment]
@arkatik @baade123 @SlizeTBC @babno Please, test it again.

**Comment by arkatik** [comment]
@akrom23 i que bg...I will test now

**Comment by arkatik** [comment]
@akrom23 
and so let's get started:
https://youtu.be/xBaUKJ_NUjA **death coil-->vanish** nice
https://youtu.be/ii6O7ZaRsTo **cast fear--> stealth** nice
https://youtu.be/-DKah0wcqCY bad test vanish but it works
https://youtu.be/iMHqkuXYHAw attacks not drop stealth now, but need test with hunters.

and last test...I did not understand how I lost stealth. Warlock tells it a secret ^_^
https://youtu.be/Nh_GnSjMPmw

combat log with this fight:
![wowscrnshot_012519_133257](https://user-images.githubusercontent.com/45844525/51745121-97833b80-20aa-11e9-9c17-090f3f849b5b.jpg)

**Comment by akrom23** [comment]
Okat, these bugs are not related to these issue - report them (if already not).
What about that?
What about stealth tickrate?

**Comment by arkatik** [comment]
> What about stealth tickrate?

need more tests, but i think need fix
1-2 hours and I will say for sure

**Comment by akrom23** [comment]
Please, test it in arena/bg.

**Comment by arkatik** [comment]
i test now on bg
the arena will play tomorrow, we'll see

**Comment by arkatik** [comment]
yea...need fix
https://youtu.be/qsUbUBip-1c

**Comment by akrom23** [comment]
? What needs fix?

**Comment by arkatik** [comment]
@akrom23  on last videos shaman after sap teleported ) look at it

**Comment by akrom23** [comment]
I see - you can report it.
But again - this is not related to the fix and to the issue described here, in the first post.

**Comment by arkatik** [comment]
> I see - you can report it.
> But again - this is not related to the fix and to the issue described here, in the first post.

ok, when there is more evidence, I will make a separate report
