### ISSUE TITLE
Blessing of Sanctuary Bug

### ISSUE THREAD

**Issue by Rasnia** [SunwellWoW/Sunwell-TBC-Bugtracker#4212]
Description:  Blessing of Sanctuary has reduced damage

How it works: when i block with an attack, it gives 61 holy damage with over 300 spellpower

How it should work: if usually did over 240-50 dmg with over 300 spellpower, so when i block it should deal 240 holy dmg

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/8YsCq9X

**Comment by akrom23** [comment]
Nope.
#3558
