### ISSUE TITLE
Can't Backstab from Behind. Game Breaking.

### ISSUE THREAD

**Issue by lordazurescens** [SunwellWoW/Sunwell-TBC-Bugtracker#4213]
Description: 
very often in pvp and sometimes in pve, with a target standing still not spinning they are completely unhittable by backstab from any spot around them in 360 degrees.

How it works: 
The target gets stunned. or just decides he wants to stand completely still. no spinning. and you can't hit him with backstab or ambush. no matter where you stand. This is not a latency issue. It has something to do with the rogue casting backstab desynching. both partys see the rogue behind the target unable to backstab from any position. 

Its possible the fix to face stabbing broke backstabbing.

How it should work: 
you should be able to backstab a target while standing behind it.

Source (you should point out proofs of your report, please give us some source): 
Working on getting some videos footage.

**Comment by akrom23** [comment]
Just tested and works fine.
Provide the videos.

**Comment by akrom23** [comment]
Okay, probably found the issue.
Just test after the update.

**Comment by lordazurescens** [comment]
There is definetly an issue i can't always replicate it. It is game breaking if someone learns how to abuse it in arena. Pretty much pointless to pvp with daggers at the moment with this issue.

I can't tell if its an issue with the person casting Backstab or if the target.

**Comment by akrom23** [comment]
@lordazurescens Please, test it again.

**Comment by baade123** [comment]
I have a video of this very clearly on my feral druid, its actually why i stopped doing pvp... can retest tho.

**Comment by akrom23** [comment]
@baade123 Please, do it.
