### ISSUE TITLE
Unable to swap Violet Eye rep ring more than once

### ISSUE THREAD

**Issue by Kgdruid** [SunwellWoW/Sunwell-TBC-Bugtracker#4216]
Description: Unable to swap Violet Eye rep ring more than once

How it works: once exalted, you can not swap your chosen ring more than once.

How it should work: should be allowed to change ring as many times as necessary.

Source (you should point out proofs of your report, please give us some source):

**Comment by Cherryxo** [comment]
You provide 0 info on what is actually happening when you try to switch ring.
This quest should not even be in the game [until patch 2.1](https://wowwiki.fandom.com/wiki/Violet_Eye) (at the bottom, patch notes), but, possible workaround until this is resolved. Have not tried it

>As of 2.1, there is a bug involving swapping your Violet Signet for a second time, given that you are alternating between three types of signets (which is entirely possible if you are a Druid, Shaman, Paladin, or clicked the wrong ring when you were first given a choice): if this is the second time you swap your Signet type, the game will think you currently have the ring that you originally picked when you hit Friendly reputation. This will cause you to get the wrong quest, which will ask for you to return that original, first ring, and not the one you currently have - so you can't swap your ring.

>For example (as in my case), if a character picks the Archmage ring, then later wants to switch to the Restorer ring, and later wants the Protector ring, they will be stuck with the Restorer ring, because Archmage Leryda will be asking for you to turn in the Archmage ring that does not exist.

>**There is a simple fix to this, however - destroy your current ring, and talk to Archmage Leryda, and she will restore your first ring. This is verified by GMs; if you'd rather see for yourself, and you don't mind the four hour wait you can open a ticket and ask them yourselves.**

>Just thought I'd like to help people who have this problem, because it sure confused me for quite a while, and had me digging in my bank for twenty minutes.

https://www.wowhead.com/quest=11034/restorer-no-more#comments

**Comment by Dootz** [comment]
fixed, live
