### ISSUE TITLE
Pet names

### ISSUE THREAD

**Issue by chocochip95** [SunwellWoW/Sunwell-TBC-Bugtracker#4218]
Description: 

How it works:  Hunters pet can't be named if someone else is using the name

How it should work: Hunters pets should be named whatever, names aren't exclusive for hunters pets

Source (you should point out proofs of your report, please give us some source):  It's always been like this on retail.

**Comment by Bugadin** [comment]
I don't know if u are wrong or not but I'm pretty sure I rather prefer not to change it because Gladdy and so many addons get bugged when the hunter's name and the pet's name is the same.

I'm pretty sure that's your goal: same name in arenas so focus, gladdy and so on gets bugged as hell and it turns to an easy win for the hunter.

NO, THANK YOU.

**Comment by chocochip95** [comment]
@Bugadin Not at all acutally, i just wanted to call my boar "Mistercochon" and i couldn't lol. Even if you don't like it, it's a bug and should be fixed.

**Comment by Devrak** [comment]
Pets cant use player names as it will result in unpredictable client behavior even potentially crash it.

**Comment by chocochip95** [comment]
How is that even possible? It's still a bug, on retail i could call my pet whatever i wanted and it didn't make any difference.

**Comment by Azmoddan** [comment]
You didn't point any proofs.

**Comment by chocochip95** [comment]
I shouldn't need to point out proof for something so obvious like this. On every server you can call your pet what you want. On retail you can call your pet what you want.

**Comment by Azmoddan** [comment]
https://us.battle.net/forums/en/wow/topic/5575477044
Your pet name might be disallowed by naming policy?

**Comment by chocochip95** [comment]
Thanks for that source saying you can name your pet whatever you want lol. But i don't think "mistercochon" is disallowed by the naming policy, and it also wasn't the only name i  tried.

**Comment by akrom23** [comment]
As Dolamor said - your name is disallowed by naming policy. Blame Blizzard.
