### ISSUE TITLE
Tidal charm works in lvl 70 PvP with no fail chance

### ISSUE THREAD

**Issue by estenv** [SunwellWoW/Sunwell-TBC-Bugtracker#4221]
Description: 
Tidal charm is being used by multiple people in arenas, it should not work properly against lvl 70 targets

How it works: 
Tidal charm works 100% of the time vs lvl 70 targets

How it should work: 
It should have a high fail chance

Source (you should point out proofs of your report, please give us some source): 
Item tooltip

**Comment by Ibuprofeno** [comment]
Not only Tidal Charm, every lvl cap is bugged: iron grenades/(any other low lvl bomb) should have a fail chance against lvl70s but it doesn't (not such a game breaking bug as they're only cheaper).
