### ISSUE TITLE
Master Looter issue

### ISSUE THREAD

**Issue by Swegkingu** [SunwellWoW/Sunwell-TBC-Bugtracker#4222]
Description:  Master Looter has to loot everything.

How it works:  Master Looter has to loot everything, even grays.

How it should work:  Master Looter is not supposed to have to loot anything under the threshold set.

Source (you should point out proofs of your report, please give us some source):

**Comment by MiekZer** [comment]
and the lowest treshold is Uncommon means a masterlooter is not supposed to be able to ninja soul essences in Karazhan.

**Comment by pinkisnotgay** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4129
Another bug related to master looter

**Comment by Swegkingu** [comment]
Seriously, this is getting annoying.
