### ISSUE TITLE
Alchemist unable to proc more than x2 ?

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#4224]
Since the alchemist respec fix I never had more than a x2 proc.
And I have differents characters with different alchemist specs. I've never seen more than a x2 proc on potions/flasks/transmutation.
Not even poiting the fact that the transmutation proc rate should be 20% but looks more like 5%.

Anyone else or I'm just very unlucky crafting 100-200 potions and seeing only (and rare) x2 procs.

**Comment by kyotpls** [comment]
https://cdn.discordapp.com/attachments/525080467150471182/538543983370960906/unknown.png

screenshot from Nightbane. x4 Proc right there

**Comment by MiekZer** [comment]
Hello, was done after the alchemist respec fix?

**Comment by kyotpls** [comment]
Dunno when it was implemented but he got it on saturday around 3:00 ST I believe

**Comment by xethra89** [comment]
I got a x3 proc of Major Agility elixir's yesterday.

**Comment by MiekZer** [comment]
Ok ok.
I can only be more lucky next time then :P
