### ISSUE TITLE
Respawning at lurker

### ISSUE THREAD

**Issue by haloani** [SunwellWoW/Sunwell-TBC-Bugtracker#4225]
Description: 
Ressing at Lurker in ssc

How it works: 
attempting to ress somebody ends up with the receiver not being able to ress, and having to reboot wow and then proceed to spawn alive at the graveyard.

How it should work: 
upon being ressurected you should spawn at the position of the caster, as is the case for every other ress in the game

Source (you should point out proofs of your report, please give us some source):

**Comment by arkatik** [comment]
yesterday it happened to us in Karazhan at Netherspite

**Comment by zanthed1** [comment]
Have had this issue at Lurker as well. The fix for it currently is to release then resurrect. Inconvenient to find all the bodies but better than the alternative.
