### ISSUE TITLE
Alchemy discovery for cauldrons

### ISSUE THREAD

**Issue by malboroman1** [SunwellWoW/Sunwell-TBC-Bugtracker#4229]
Description: 
Making major resistance potions for shadow, fire, nature, ice, and arcane can cause a discovery for a raid-use cauldron. I made 13 batches of resistance potions and could not get any discoveries for a cauldron. The chances of this happening (if working correctly) is a little less than 1%.

How it works: 
The discovery rate is either the same as for regular potions and elixirs or not implemented.

How it should work: 
The discovery rate for cauldrons is about 30%.

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Discovery

**Comment by Adrestiah** [comment]
These Items were added in patch 2.1 
you cannot discover them until then. 
https://www.wowhead.com/item=32839/cauldron-of-major-arcane-protection
https://www.wowhead.com/item=32852/cauldron-of-major-shadow-protection
