### ISSUE TITLE
[Mage]/[Core] Ice block/death negate mage T5 2set

### ISSUE THREAD

**Issue by MessiahLFY** [SunwellWoW/Sunwell-TBC-Bugtracker#4231]
Description: T5 2set for mages increases damage and mana cost of Arcane Blast by 20%. 

How it works: When mage use Ice block or died he will lose T5 2set and need to reequip some part of equip to get it back. Btw. in combat you cant reequip armors so after using Ice Block mage lose this buff for the rest of fight.

How it should work: Mages are supposed to have T5 2set still active even when They die or use Ice Block

Source (you should point out proofs of your report, please give us some source): 
https://i.postimg.cc/L5sQLqB2/Wo-WScrn-Shot-012819-165412.jpg
https://i.postimg.cc/SKqrc2k3/Wo-WScrn-Shot-012819-165403.jpg

Here can you see mana drops also.
https://postimg.cc/gallery/1nf3dvpuq/

**Comment by CaillouZsn** [comment]
pls send help
https://streamable.com/zth8j
