### ISSUE TITLE
Shadow Step. PVP. Landing position.

### ISSUE THREAD

**Issue by lordazurescens** [SunwellWoW/Sunwell-TBC-Bugtracker#4232]
Description: 
When you use shadow step. it puts you behind the target. Some larger player models[Tauren/Druid Forms] Cause you to be put much farther away from them then other smaller models.

How it  works: 
On the above targets you are thrown so far to the edge of your melee range. that in pvp regardless of latency. it can put you out of melee range making it impossible to use.  

Ex. Druid roots you. you stun druid. then you shadow step the Stunned immobile druid. Then you land outside of melee range. and can't do anything.

How it should work: 
The hit boxes on those models need to be changed. or you have to make shadow step land closer to the targets.

Source (you should point out proofs of your report, please give us some source): 
Ill collect some pictures when server is back up of example given

**Comment by Bugadin** [comment]
In addition, rogues get stucked when they use shadowstep sometimes. Then, you stay stucked until you restart the game. I have no idea about why it happens.

**Comment by akrom23** [comment]
@lordazurescens @Bugadin Provide a video (preferably with combat log).

**Comment by koostosh** [comment]
Some modifications were made to target computing, please retest
