### ISSUE TITLE
Totem of Wrath

### ISSUE THREAD

**Issue by Lichbait** [SunwellWoW/Sunwell-TBC-Bugtracker#4233]
Description: 
spell hit gained from this item is not working

How it works: 
Number of average resists per fight suggest this aura is certainly not working properly. 

How it should work: 
Should give a party-wide 3% spell hit buff

Source (you should point out proofs of your report, please give us some source):

**Comment by baade123** [comment]
ive heard mention of this...

**Comment by zanthed1** [comment]
I have also had issues with this, as well as my guildmates complaining. Will post some screenshots of recount next raid.

**Comment by zanthed1** [comment]
https://gyazo.com/f4e884682ed4aab36e9f9d4866bf69ca
https://gyazo.com/feaae860e56c1273a988379cb6214908
https://gyazo.com/213edaa17f88dad6a193968d65ecd665
I have 9% hit with talents, 3.96% from gear, and 3% from Totem of Wrath at all times. Expected resist is 1.04% but consistently being around 3% is not a coincidence.
https://gyazo.com/b8088e867482f1dd1ec24048067285be
Screenshot from a warlock in our raid with 100% totem of Wrath uptime.

**Comment by Lichbait** [comment]
[https://imgur.com/7I7Hih2](url)

61 shadowbolts and 5 resists with 13%+totem of wrath is statistically impossible if wrath is working.

**Comment by BobjaneTmart** [comment]
Hmm, with my resists. its usually like 3-5 resists in a row in a boss fight, (hit capped with shaman totem).  andi  pray it doesn't happen again but sometimes does? Like literally Cast Vampiric Touch, SwP - resist , SwP resist, SwP Resist, SwP resist ...... Always 3-5 resists in a row for my self as a priest, and my other guild mate has the same.

**Comment by MiekZer** [comment]
I give my voice to this confirming it's not working for a 12% spellhit alliance warlock sticking the totem (and his draenei shaman), resists are much more than 1%

**Comment by akrom23** [comment]
Works fine.

W/o Totem of Wrath:
![wowscrnshot_021219_085822](https://user-images.githubusercontent.com/1035215/52620643-6164fa80-2ea5-11e9-8cc2-ba8948b4ba04.jpg)

With Totem of Wrath:
![wowscrnshot_021219_090516](https://user-images.githubusercontent.com/1035215/52620651-675adb80-2ea5-11e9-9967-77658c33ac1f.jpg)

**Comment by Jeansapin** [comment]
Hmmm excuse be but it's only 200 shadowbolts ... And as a spellhit capped warlock you should do 1%, not 1,5% ...

Have you changed something recently about it ? Or did you just tested it.

If you could let us, or yourself if you want, try it on more than 200 bolts it would be awesome ...

EDIT : By the way, do you have a shaman in your party ? I can't see him. You just summoned this totem, but it would be better if you could make a shaman, and /inv him with the totem on ...

**Comment by Lichbait** [comment]
also try it natural hit cap (202 hit warlock), without shaman totem.

**Comment by MiekZer** [comment]
I think that summoned totem via gm command (and totem directly belonging to you) may have different interaction than totem sumonned by shaman in your party...

**Comment by akrom23** [comment]
@MiekZer No, this is the same.
@Jeansapin @Lichbait 200 casts are enough to see the difference and the result.
Against 73 lvl mob, I need 17% as I remember correctly. So that's why i got less than 202 - i wanted to check if totem add 3%.
@Jeansapin - 12 + 3 != 17.

**Comment by Lichbait** [comment]
You only need 16%. 202 is the cap without totem for warlocks. Is the tested resist percentage 1% if you cap without a totem? Perhaps spell hit itself is broken.

**Comment by akrom23** [comment]
@Lichbait Without totem I have 12.76, as you can see. Got 4% resist.
With totem it is 15.76% - got 1.5%. For me it works fine.
These numbers ofc are not 100% accurate, because of low numbers of resists.
