### ISSUE TITLE
[Core] Evade

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#4234]
Description: When we were doing Morogrim trash yesterday, one of the mob from 5 mobs pack got lost under textures and couldn't get out. This caused entire pack to evade several times. We tried to kill the pack more than 5 times, every time after certain amount of time entire pack evaded, but the mob lost under the textures couldn't get out and was stuck there. We couldn't kill the pack at all because of this and we had to open a ticket and ask for help, but only thing that really helped us was server restart.

Mobs in instances should never evade. You should be able to pull last boss and he shouldn't evade until the entrance (unless some special circumstances occur like him not being able to climb or jump into water). However now sometimes in instances, sometimes in open world, you fight the mob, don't move, down him to 20% and he suddently evades for some reason.

This can happen to bosses. Imaigine fighting Kael, downing him to 20% and then having him evade.

How it works: Evade mechanic is broken partially because of broken pathfinding but not only because of that. Mobs can evade even if you don't move. Evade sometimes happen in instances. 

How it should work: Mobs should not evade without a reason. They should not get stuck under the textures (maybe implement death and respawn instead of running to their place?). 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Trash should evade if one of the mob evades (not all trash packs):
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/616

Your problem here is the mob evades because it's stuck in textures (or e.g. mob is not accessible). This  evade is some kind of "protection" - in case of never ending combat with mob in textures.
Sadly, pathfinding is not perfect and never will be. 

In this situation, you should always ask GM to reset/move/kill the mob.

**Comment by neheri** [comment]
This is very bad. It happens several times per raid. Maybe we should invite a GM to every raid to follow us and reset every 3rd pack that bugs out? We lose a lot of time each raid because of it and other guilds too. 

I understand that this is caused by pathfinding, which is one of the worst I've ever seen on any server I played. Honestly you should designate one person to only fix broken waypoints and pathfinding in general because it's visibile everywhere, lvl 5 troll on echo isles, lvl 30 in tarren mill cave, lvl 60 in zeth'gor, lvl 70 in ohf castle, 25 lvl 70 raiders in SSC will see this major bug. 

Maybe implementing other mechanism, like teleporting bugged out mob to his spawn place instead of him trying to run to his spawn would be good temporary workaround.

**Comment by akrom23** [comment]
We may consider not evading the whole pack because of textures.
