### ISSUE TITLE
[NPC] Tainted Elemental

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#4236]
Description: After recent fixed Enchanted elementals seem to move at proper speed. However one of tainted elemental spawned during Lady Vashj encounter was moving towards her like enchanted elemental.

How it works: Tainted elemental was moving towards Vashj.

How it should work: Tainted elemental should never move.

Source (you should point out proofs of your report, please give us some source):

**Comment by neheri** [comment]
Regarding Enchanted elementals.

Under the textures, LoS, can't attack him.

![wowscrnshot_012919_195222](https://user-images.githubusercontent.com/37372869/51933680-27561c00-2402-11e9-86f6-5451c340308a.jpg)

**Comment by baade123** [comment]
elementals still walking straight under the ground un attack-able- also tainted ones despawn in 10 seconds or so from spawning...
