### ISSUE TITLE
[Hunter] [Spell] Hunter's Mark

### ISSUE THREAD

**Issue by street-racer777** [SunwellWoW/Sunwell-TBC-Bugtracker#4237]
Description: 
Hunter's Mark is not working

How it works: 
do not increase ranged attack power against that target by 110 and by additional 11 each time they are struck by a tanged attack, up to a maximum of 440(rank 4).

How it should work: 
should increase ranged attack power against this target by 110 and an additional 11 each time they are hit by a tangential attack, up to a maximum of 440 (level 4).

Source (you should point out proofs of your report, please give us some source): 
Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/MccEEqM
some test:
without mark: https://www.youtube.com/watch?time_continue=165&v=WgNTP9f7mt4
with mark: https://www.youtube.com/watch?time_continue=94&v=DY7ahppYCiw
Check AVG dmg in video.

**Comment by akrom23** [comment]
You should check this against low level mob with low armor (e.g. mage).
Your ranged damage is randomized and can be modified by many buffs and reduced by your target's armor.

**Comment by akrom23** [comment]
Okay, there is an issue.

**Comment by flapse32** [comment]
Dunno what u changed but now it just resists every single feign death i do, 20 times in a row xD

**Comment by akrom23** [comment]
@flapse32 Not this issue.
