### ISSUE TITLE
[Hunter] [Spell] Feign Death

### ISSUE THREAD

**Issue by vakoz** [SunwellWoW/Sunwell-TBC-Bugtracker#4239]
Description: 
When I use Feign Death it does nothing and red string "resisted" appears in the middle of the screen. You don't see animation, no "buff" effect is applied, enemies don't lose target. Cooldown is used.

How it works: 
It doesn't. Bug is prob connected with this fix: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4081

How it should work: 
It worked yesterday irrc

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
It means that your target resisted your feign death.
Give me some screenshots and tell me about your level, your target's level.

**Comment by Ironjudgment** [comment]
It has worked fine for my hunter on Vashj. I have resisted once for every ~30 FD used.

**Comment by vakoz** [comment]
Ohh I completly forgot to mention. It doesn't work in PvP. It's critical bug in hunter class.
My level: 70
Enemy level: 1
https://streamable.com/y3yey
Doesn't interrupt fireball casting, no target loss, no animation, no Feign Death effect applied. Also we should be able to use Feign Death without having taget. Right now if you don't have target it displays "resisted" and there is no animation / Feign Death effect. Feign Death was little buggy before (hunter's and warlock's pets didn't lose target after using FD), but now it isn't working at all, making hunter unplayable.

**Comment by akrom23** [comment]
@vakoz It works fine.
There is a chance that your FD will be resisted.
I'll look into it

**Comment by vakoz** [comment]
Now it seems that everything is working. Good job

**Comment by flapse32** [comment]
Dunno what u changed but now it just resists every single feign death i do, 20 times in a row xD

**Comment by flapse32** [comment]
The resist chance is alot higher then it should be, but i think the issue is if u resist one time on a boss fight u will resist every single time after that.

**Comment by flapse32** [comment]
80% chance of resist so far, half way trough kara

**Comment by akrom23** [comment]
@flapse32 Send some screenshots.
https://wow.gamepedia.com/Feign_Death

> 

+Level | %Old resist | %New resist
-- | -- | --
0 | 4 | 4
1 | 5 | 5
2 | 6 | 6
3 | 37 | 17
4 | 48 | 28
5 | 59 | 39
6 | 70 | 50

Moreover,:

> As the level (relative to the hunter) and number of enemies become higher, the likelihood of the spell being resisted becomes higher.

In dungeons, combat pulse works, so you have a lot of mobs in your hostile list.

**Comment by flapse32** [comment]
Dunno how much help a screenshot would be, i dont have a addon that can show details of how many times FD resist. But its over 80% last night. And 80% is rly just waaaaay to much. Try go into kara and test Feign death on bosses and you will see what im talking about.

**Comment by akrom23** [comment]
@flapse32 I want to know how many enemies you've got on your hostile list.
Bosses are special case - you won't drop combat with them (aggro drops as normal).

**Comment by flapse32** [comment]
Well all the bosses has been bosses where there was only 1 mob i was hostile to (The boss)
I know that u wont drop combat, that works as intended. But the threat dosent drop cus FD will resist ALL the time. And its not a overexertion, its literally happening every single time. 99% of the time on boss fights. I think the FD resist works normal on trash mobs in kara tho. Its mostly when its a boss and there only is 1 mob hostile to you.

**Comment by akrom23** [comment]
You are sure that aggro does not drop?
Message "Resisted" is displayed also when you successful drop aggro from boss - it's a bug and I will fix it.

**Comment by flapse32** [comment]
Oooooh , that might explain ALOT.

**Comment by flapse32** [comment]
Diamond threat does not react to it tho, so im not sure. But i did not overaggro on any of the bosses. (Dident try to either)

**Comment by flapse32** [comment]
Hmmm wierd, im in ssc and it appears its normal . works perfect atm.
In kara yesterday it was just totally fucked.

**Comment by akrom23** [comment]
Because I fixed it ;)

**Comment by flapse32** [comment]
Ur a legend mate!
