### ISSUE TITLE
Warrior Charge or Intercept---->Shadowstep !!!

### ISSUE THREAD

**Issue by arkatik** [SunwellWoW/Sunwell-TBC-Bugtracker#4240]
**Description:** 
_When you catch intercept use shadowstep, warrior unfolds and continues to intercept.
Repeated it for developers, because they probably didn't understand what was going on. 
(I reported this a week ago)
See how it works on Sunwell._

**How it works:** 
https://youtu.be/I95YVuqJXNA _(warrior intercept)_ **bug**
https://youtu.be/5JDHvt7ttIA  _(warrior charge)_ **bug**

**How it should work:** 
https://youtu.be/Ba6Ty72eSH8?t=55 _(Acrono, Retail)_
https://youtu.be/W0hpKZ075Ss (Druid charge, Sunwell) - **WORK FINE**

@akrom23 fix as soon as possible.

**Comment by akrom23** [comment]
@arkatik What about mage's Blink? The same result?

**Comment by arkatik** [comment]
> @arkatik What about mage's Blink? The same result?

@akrom23 
it's a warrior mechanic bug
I don't have a warrior or mage to do an extra test
