### ISSUE TITLE
Robe of the Elder Scribes

### ISSUE THREAD

**Issue by MadderThenMad** [SunwellWoW/Sunwell-TBC-Bugtracker#4241]
Description: It has no hidden cooldown (should be 50 sec) making it completely broken (it makes it actually + 162 bsd robe considering 20% chance to hit).

How it works: As above. 

How it should work: 

Proc chance varies between patches but even considering 2.4 20% chance there still should be internal cooldown of 50 sec // no internal cooldown but far much lower proc chance (around 5%). Overall this makes it a complete bullshit item better then probably T6. (160 flat bsd  considering 100% uptime is a lot).

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=28602/robe-of-the-elder-scribes#comments
https://tbc-twinhead.twinstar.cz/?issue=101
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2148
http://bbs.comefromchina.com/threads/557370/ -> REALLY GOD OVERIVIEW OF ALL INTERNAL COOLDOWN ITEMS PLEASE TAKE A LOOK

**Comment by Dootz** [comment]
Hi, there's 45 second cooldown on this proc. I've tested it by casting multiple fireballs for couple minutes and it never proced earlied than 45 sec after previous proc
