### ISSUE TITLE
Pet Vanished from Stable

### ISSUE THREAD

**Issue by Pwncakey** [SunwellWoW/Sunwell-TBC-Bugtracker#4242]
Description: 
I placed my pet into the stable, and when I went to retrieve him he was no longer there. He was level 57, Best Friend, and I have spent DAYS working with this pet to get him where he was.

How it works: 
You put the pet in, and it stays in there

How it should work: 
You take the pet out, and he stays by your side.

Source (you should point out proofs of your report, please give us some source): 
If he was removed due to name banning, you should have let me rename him. I want my monkey be respawned for me to retame as I already sat for HOURS in Ungoro just waiting for him to spawn the first time. I'm already sour about the levels and time I've put into him.

**Comment by YoshGit** [comment]
Had this happen to me too. Can confirm it’s a bug but unfortunalty I have no useful info on root cause.

**Comment by vakoz** [comment]
I wanted to get new pet to learn abilities. I'm glad that checked out bugtracker. There are actually multiple reports on this, but I guess they contain not enough information to track the issue. How long did you have your pet in the stable? Is it possible that pet loyalty level drops in the stable and then it runs away?

**Comment by Pwncakey** [comment]
I have had this pet for a good 2-3 weeks along with my original tame when I started on the server a month+ ago and none of my pets have lost loyalty while in the stable. I do believe someone took issue with the name and instead of letting me know, they simply made my WhippedCrack vanish.

**Comment by nickycakes** [comment]
yeah lost a pet to this as well #4150

**Comment by Pwncakey** [comment]
Fix implemented but as for us getting our pets back we're just fucked?

**Comment by Pwncakey** [comment]
SO ya'll closed my ticket but didn't talk to me or anything. But it's fixed right? So if I go get the pet again and it vanishes are y'all gonna do something or just sit on your thumbs and twiddle?
