### ISSUE TITLE
Mind Control in PvP

### ISSUE THREAD

**Issue by jrrbt** [SunwellWoW/Sunwell-TBC-Bugtracker#4244]
Description:  Cant move the mind controlled target (aka enemy player)

How it works: Mind controlled target (enemy player) can't be moved or start attacking someone. You and the controlled target are just sitting at one place. If the priest casted the spell try to move the mind control is broken.

How it should work: For 8 sec we should be able to move the controlled target and to attack enemys. 

Source (you should point out proofs of your report, please give us some source): Blizzard

**Comment by akrom23** [comment]
@jrrbt Cannot reproduce it - works fine.

**Comment by zanthed1** [comment]
This problem can occur when the target is feared and you Mind control them. You do not regain control after fear in that case - that should be able to be reproduced easily.
