### ISSUE TITLE
Spiritual Attunement not restoring mana from HoTs

### ISSUE THREAD

**Issue by Pikseh** [SunwellWoW/Sunwell-TBC-Bugtracker#4248]
Description: The passive ability Spiritual Attunement restores mana to the paladin whenever he or she recieves healing from another player that is not overhealing (so only actual healing) equal to 10% of the amount healed. However, this does not work with healing over time components like Lifebloom, Renew, Rejuvenation and the HoT part of Regrowth.

How it works: You receive 10% of actual healing from direct healing from other players as mana.

How it should work: You receive 10% of actual healing from direct and over-time healing from other players as mana.

Source (you should point out proofs of your report, please give us some source): The spell description has no restrictions saying that it must be direct healing, only that it must be healing from other players.

Linked is a picture showing how I get mana from a Flash Heal but not from the over-time healing of Lifebloom.
![sa](https://user-images.githubusercontent.com/3406509/52083799-ba2cbd00-25a0-11e9-8d61-d760a0f71e51.jpg)

**Comment by babno** [comment]
May be related to the fix that was implemented for #4090

take care not to break direct heals again please :P
