### ISSUE TITLE
AV drek reset

### ISSUE THREAD

**Issue by Saiie** [SunwellWoW/Sunwell-TBC-Bugtracker#4249]
Description: 
Drek in AV just randomly resets to full hp, adds around him doing the same. Sometimes impossible for aliance to win AV.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by baade123** [comment]
Balinda is totally bugged out doing resets constantly and also drek hits like a wet noodle even with towers up still..... complete bogus. joke.

**Comment by Cherryxo** [comment]
[#4062](https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4062)

**Comment by akrom23** [comment]
@Saiie @baade123 @Cherryxo Happens only if adds around him are alive?

**Comment by Saiie** [comment]
No, he resets even without adds, galv is bugged as well, ran to the wall after reset and got stucked there.
