### ISSUE TITLE
Core/Misc: DespawnOrUnsummon

### ISSUE THREAD

**Issue by Riztazz** [SunwellWoW/Sunwell-TBC-Bugtracker#425]
Decription: 
When DespawnOrUnsummon is called for unit, it should disappear without showing dying animation

How it works: 
Player can see creatures dying animation

How it should work: 
Player sees the dying animation before creature is despawned

Source (you should point out proofs of your report, please give us some source):

**Comment by Nadiirr** [comment]
#396 Might be similar issues.
