### ISSUE TITLE
Netherwing Mines absolutely empty

### ISSUE THREAD

**Issue by blackabbath** [SunwellWoW/Sunwell-TBC-Bugtracker#4252]
Description: 
Netherwing Mines which are located at Netherwing Lodge are empty.  I came for hunter's pet ravager 70 lvl but no - there are only winds, **zero of living entities....**

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
have no any proves, but i'm not sure blizz did any totally empty location.

**Comment by zmthc93** [comment]
netherwing shill confirmed

**Comment by Pikseh** [comment]
This should not be implemented before the release of Black Temple iirc.
