### ISSUE TITLE
Seal of blood don't attack

### ISSUE THREAD

**Issue by fr0nze** [SunwellWoW/Sunwell-TBC-Bugtracker#4253]
Description: 
seal of blood don't attack ALL melee attack

How it works: 
the description says that, seel of blood has to beat each Millie attack ,but since yesterday he began to pass Millie atki Crusader strike working time through time. would you like to know what happened ?!

How it should work: 
All melee attacks deal additional Holy damage equal to 40% of normal weapon damage, but the Paladin loses health equal to 10% of the total damage inflicted.
Unleashing this Seal's energy will judge an enemy, instantly causing 40 Holy damage at the cost of health equal to 33% of the damage caused.

Source (you should point out proofs of your report, please give us some source): 
https://pastenow.ru/2042737b5ec7fb0aab3b266ff03e506d

5 melle attack  + 2 Crusader strike =7 attack melle > Seal of blood = 3 ( must be min. 7 )

**Comment by akrom23** [comment]
#3919
@fr0nze  As stated there, Seal of Blood should not proc from Crusader Strike?

http://forum.warmane.com/showthread.php?t=359651&p=2832880&viewfull=1#post2832880
> Crusader strike isn't supposed to proc WF, SoB, SoR or any damage seal. It can only proc seal of light, seal of wisdom and seal of justice.

Also, maybe you missed/dodged melee attack?
