### ISSUE TITLE
Questions to dev about healers threat

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#4254]
Can you give the source where you've read that healers should be unable to generate threat on cc'd targets?

Also, is healing (minus overheal) threat is actually splited by the number of mobs in the fight? Including temporary adds spawning.
Let's say there are 3 mobs, then every heals threat should be divided by 3 and then applied to the 3 mobs.
Let's say Curator is spawning an add, then heals should be divided by 2 and then applied to Curator and it's add.

**Comment by akrom23** [comment]
https://vanilla-twinhead.twinstar.cz/?issue=7652
https://github.com/ccshiro/corecraft/blob/master/server/src/game/HostileRefManager.cpp#L56
Threat is splited.
This is not forum.
