### ISSUE TITLE
Escape artist

### ISSUE THREAD

**Issue by ventuzor** [SunwellWoW/Sunwell-TBC-Bugtracker#4255]
Description: 
Escape artist doesn't remove all slow and immobilize affect, sometimes it doesn't remove druid's roots, rogue's slow

**Comment by firngrod** [comment]
I encourage you to look into the following articles:

https://wow.gamepedia.com/index.php?title=Escape_Artist&oldid=1588354
https://wow.gamepedia.com/index.php?title=Vile_Poisons&oldid=1375456
https://wow.gamepedia.com/index.php?title=Subtlety_(druid_talent)&oldid=1373730

TL;DR:
Escape Artist is a dispell attempt.  Specifically druids and rogues have talents to give their buffs/debuffs a chance to resist dispells.  Works as intended.
