### ISSUE TITLE
Tempest Keep [Void Reaver] [Bleeds] Video Proof.

### ISSUE THREAD

**Issue by lordazurescens** [SunwellWoW/Sunwell-TBC-Bugtracker#4258]
Description: Void Reaver is bleed immune. He should not be.

How it works: 
Void Reaver is immune to bleed at the moment

How it should work: You should be able to bleed him. Proof below from retail.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=HpUR4fvATeo Look at target during fight. He has bleeds on him.

**Comment by notsofamous** [comment]
Patch 2.4: Non-corporeal Undead and Mechanical creatures are now susceptible to bleed effects. 
https://wowwiki.fandom.com/wiki/Patch_2.4.0

Boss is in a pre nerf state.
