### ISSUE TITLE
Hunter / Warlock Pets HP

### ISSUE THREAD

**Issue by arkatik** [SunwellWoW/Sunwell-TBC-Bugtracker#4260]
Description: 
I know that was written about this, but developers didn't do anything. Hunters pets have way too much HP!!!

How it works: 
On Sunwell hunters pets have 9-10k hp unbuff.
Pls watch screen, 68 lvl pet have 9k hp
![wowscrnshot_020219_222602](https://user-images.githubusercontent.com/45844525/52168984-fe06fa00-2739-11e9-9ccc-0c9ab6cbfcd0.jpg)

How it should work: moovies from retail, pet have **7117 hp...not 9k or 10k.**

https://youtu.be/NoKD723_yAM?t=749

**Comment by flapse32** [comment]
Wind serpent supposed to have 5k hp? cus thats what my serpent has. yesterday it had 7.5k

**Comment by akrom23** [comment]
@flapse32 Just calculates your pet's stats.
Pets had too much hp.

**Comment by flapse32** [comment]
the stats might have been wrong, but is 5k hp rly normal? Looks like on that TBC clip he has 7.1k with druid buffs. even with stamina talents on pet and on the hunter it dosent come close to 7.1k hp

**Comment by flapse32** [comment]
![image](https://user-images.githubusercontent.com/46076151/53022010-a4514000-345a-11e9-9b2e-ea6123ccbd45.png)

![image](https://user-images.githubusercontent.com/46076151/53022073-c054e180-345a-11e9-8624-b9de7cf02afd.png)

**Comment by akrom23** [comment]
Show me your pet's stats.

**Comment by flapse32** [comment]
![image](https://user-images.githubusercontent.com/46076151/53022173-eda18f80-345a-11e9-901f-6aa4ac92447b.png)

**Comment by akrom23** [comment]
And your pet's hp is 6k right now?
Move your mouse cursor over the stamina stat.

**Comment by flapse32** [comment]
Yes with talents in BM and with max rank stamina on pet

**Comment by flapse32** [comment]
![image](https://user-images.githubusercontent.com/46076151/53022371-56890780-345b-11e9-9bd1-da00c4be452f.png)

**Comment by akrom23** [comment]
Every stamina point is +10 hp.

**Comment by flapse32** [comment]
Correct, but is the base stamina the same compared to retail?

**Comment by akrom23** [comment]
303 stamina points as base - same on every emulator.

**Comment by flapse32** [comment]
Alright then its not a bug. Thx for info.
