### ISSUE TITLE
Druid's "Cower" doesn't work properly

### ISSUE THREAD

**Issue by recreantus** [SunwellWoW/Sunwell-TBC-Bugtracker#4262]
Description: 
Cower is supposed to be a Feral Druid's best friend. It should reduce threat by a large amount, but here it does next to nothing. Spamming it every cooldown 7 or 8 times in a row still doesn't do anything. It's all just a big DPS loss. So instead what you're left with is waiting 20 seconds into the pull to start attacking and then towards the end of the fight completely stop attacking for 10 seconds. It doesn't matter how well geared the tank is or how many MDs he gets.

How it works: 
Cower barely reduces threat at all, cannot be noticed on Omen or DTM.

How it should work: 
It should lower the Cat's threat by a significant amount. A big chunk of it's threat should be removed from Omen. Cower should work similarly to a Priest's Fade ability.

Source (you should point out proofs of your report, please give us some source):

**Comment by zanthed1** [comment]
Cower is only supposed to drop 1170 threat, which is not much. Not sure if it is not reducing it at all, or just less than you would have expected. http://db.hellfire-tbc.com/?spell=27004

**Comment by akrom23** [comment]
Just tested and worked.
@recreantus Send some pics.

**Comment by nimeral** [comment]
https://wowwiki.fandom.com/wiki/Cower_(druid_ability)?oldid=995760 1170 indeed
