### ISSUE TITLE
[Druid] Force of Nature

### ISSUE THREAD

**Issue by lordazurescens** [SunwellWoW/Sunwell-TBC-Bugtracker#4263]
Description: Druids Treants do not attack Yellow named mobs. they refuse to attack them even if you are.
Doesn't matter if you cast after or before you initiate combat.

How it works: 
The Treants don't see to want to attack any neutral [yellow colored name] mobs.

How it should work: 
They should attack your target. when you are in combat. till either it dies or the treants die.

Source (you should point out proofs of your report, please give us some source): Easily testable. works like this 100% of the time.
![image](https://user-images.githubusercontent.com/45920509/52171779-e37c5300-2730-11e9-8104-c633afad4cdb.png)

**Comment by akrom23** [comment]
#4064
