### ISSUE TITLE
Transmute: Mithril to Truesilver 20 hour cooldown!! Really!!? :O

### ISSUE THREAD

**Issue by Splinterskul** [SunwellWoW/Sunwell-TBC-Bugtracker#4264]
Description: 
Hey, I just went into a huge amount of trouble getting my lvl 35 alchemist to learn the Transmute Mithril to Truesilver ability. Only to find that after finally collecting all required to do so it has a 20 hour cooldown! :O I mean thats a little bit excessive dont you think? can you please do something to shorten the cooldown time to maybe 2mins at most, this is highly inconvienient. lol

How it works: I transmute 1x Mithril to Truesilver (cooldown of 20 hours!)

How it should work: I transmute 1x Mithril to Truesilver (no cooldown) I can continue to transmute provided I have the mats. especially because transmuting one takes 1 min approximately already

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
https://wow.gamepedia.com/Transmute:_Mithril_to_Truesilver

> Transmuting mithril to truesilver will trigger a 20 hour transmute cooldown on the Philosopher's Stone
