### ISSUE TITLE
Heeding the Call Druid Questline

### ISSUE THREAD

**Issue by polididly** [SunwellWoW/Sunwell-TBC-Bugtracker#4265]
Description: I died on the quest Body and heart and the cenarion lunardust disappeared from my bag so i abandoned the quest and now the first quest (Heeding the call) is gone and i cant continue forward with the bear questline 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Did you visit Turak Runetotem (https://www.wowhead.com/npc=3033/turak-runetotem)? He should have this quest (Body and Heart) for you to pick up.
