### ISSUE TITLE
Darkmoon card crusade spell power stacks

### ISSUE THREAD

**Issue by mgperera** [SunwellWoW/Sunwell-TBC-Bugtracker#4267]
Description: So darkmoon crusade is supposed to give 1 stack from spell and bonus from effects, such as ignite or the scorch debuff, and it gives 1x per mob hit from area of effect spells, i.e: arcane explosions / consecration 8 mobs you get fully stacked spell power buff. But consecration is giving 0 stacks.
Something "similar" is happening with other spells, such as when i judge Crusader or Wisdom, it shud give 1 stack for the judge and 1 for the debuff being applied, but its not doing so

How it works: Consecration, judgements and debuff effects should give 1 stack of crusade's spell damage buff

How it should work: Consecration and any judgement, except the damaging ones (command and righteousnes), are not giving the buff

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/item=31856/darkmoon-card-crusade

**Comment by akrom23** [comment]
@mgperera Do you have any proof that Consecration should proc?

**Comment by mgperera** [comment]
Other than personal experience and the top voted comments on wowhead, not right now sorry, I'll do some more searching and testing.

**Comment by akrom23** [comment]
@mgperera Not needed anymore.

**Comment by mgperera** [comment]
Hey mr. akrom, just a piece that i forgot to point out is that meele attacks from a paladin that refresh a seal also gives an spell power stack since it's the refreshing of a spell debuff on target.

> This has been changed for us paladins. As of patch 2.2, auto-attack and Judgement now proc both the attack power and spell damage stack. Previously, attack only added an AP stack, and Judgement only added a SP stack. Having Judgement proc the AP one is really just gravy, this is a nice buff to the card since you no longer have to constantly cast Judgement or Consecration whenever they're up to keep up the spell damage stack going. 
Seal of Command will also proc both stacks. Nothing else about the trinket appears to have changed.
Edit: A slight correction, this new effect appears to only work when one of your Judgements is on the target. It seems the spell damage portion is now increased by the refreshing of a Judgement. Oddly, Crusade Strike does not proc the spell damage portion, and I'm really unsure why Judgement increases the AP bonus. *shrug* Whatever. 

Again this is info from wowhead comments, it also states that it was implemented on patch 2.2, but since its a game mechanic rather recipe i thought it would be in game
tyvm for your attention and effort
