### ISSUE TITLE
[PALADIN] Seal of Justice doesnt remove bonus from druid

### ISSUE THREAD

**Issue by Atrecom** [SunwellWoW/Sunwell-TBC-Bugtracker#4268]
Description: Seal of Justice doesnt remove bonus from druid`s water form

How it works: 

How it should work: Should remove bonus

Source (you should point out proofs of your report, please give us some source): 
cant. thx

**Comment by baade123** [comment]
i dont know about this but if you're going to be fixing justice plz make it work properly vs feared targets... you will notice it says "immune to fear effects" or whatever but if you get feared, you get feared.

**Comment by akrom23** [comment]
@baade123 Make a separate report.
EDIT: Reopened #3159

**Comment by Atrecom** [comment]
Same again. now with 2nd rank. just test w/o creenshots
