### ISSUE TITLE
Critter rage gain

### ISSUE THREAD

**Issue by KimmoKM** [SunwellWoW/Sunwell-TBC-Bugtracker#427]
Currently, attacking critters does not grant any rage. Attacks against critters should grant rage as normal.

"One of the best ways of banking rage (where possible) is to attack critters like snakes or rats. As well as the rage gained by the attack itself, by entering combat, the warrior's rage decay is briefly halted. Each critter essentially offers the warrior an opportunity for free, instant rage generation."
https://wow.gamepedia.com/Rage#Rage_decay

A surprisingly big deal when it comes to tanking 5-mans.

**Comment by Riztazz** [comment]
PTR Updated, re-test please

**Comment by KimmoKM** [comment]
Appears to work now.
