### ISSUE TITLE
Chat flood protection 

### ISSUE THREAD

**Issue by BobjaneTmart** [SunwellWoW/Sunwell-TBC-Bugtracker#4271]
INCREASE FROM 4 LINES, IN PARTY / RAID / GUILD PLEASE.

Simple things such as a macro needed for raids / guilds makes it difficult with only 4 lines...

FOR EXAMPLE.  the slacker(Tells you whos not buffed with what) Addon. In a casual guild with raiding,  this addon is REALLY important to keep on top of everyone.... 

Recount.... Comparing everyones DPS / HPS / Interrupts, etc . once again REALLY important as a guild to be doing this......... sometimes Peoples Recounts bug out and are not the SAME!

Like please . Would literally be 2 clicks of a button for you to change.....

**Comment by Azathothh** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4270
