### ISSUE TITLE
Priest mind control

### ISSUE THREAD

**Issue by BobjaneTmart** [SunwellWoW/Sunwell-TBC-Bugtracker#4272]
Description: 
casting mind control on a mob. and having no "unique moves" from said mob.

How it should work: 
When MC on a mob. there should be UNIQUE spells to use. THEY all only have auto attack. 

Source (you should point out proofs of your report, please give us some source): wowhead or Google

**Comment by akrom23** [comment]
@BobjaneTmart What mob?
