### ISSUE TITLE
[Item] Darkmoon Card: Crusade

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#4274]
Description: AOE spell hits doesn't proc the card properly.

How it works: Each Seed destroyed, even with 10 targets hit, grants only 1 stack.

How it should work: The card should grant a lot of stacks with most spells. Not only aoe but also 2 stacks with scorch, a stack with each arcane missile fired and so on.

There should be a stack granted per mob hit by default and a list of spells excluded from this.
From what I've found the following spells shouldn't grant additional stacks:

- cone of cold (1 stack in total, no matter how many enemies hit),
- Lightning Capacitor bolt proc (0 stacks)

Source (you should point out proofs of your report, please give us some source): 

https://www.wowhead.com/item=31856/darkmoon-card-crusade#comments

AOE spells sometimes grant multiple procs
Arcane Explosion grants 1 proc per enemy hit.
Flamestrike grants 1 proc per enemy hit, the dot does not grant additional procs.
Cone of Cold grants 1 proc only.
BLIZZARD DOES NOT PROC THIS TRINKET
Could not test with Blastwave, input would be helpful.

https://wowwiki.fandom.com/wiki/Darkmoon_Card:_Crusade

This trinket is of significant use to any spell/melee Hybrid class (Enhancement Shamans, Protection Paladins, and Retribution Paladins). Other classes may find specific uses for it. For example, the card procs off twice for each tick of Scorch, and off of each missile from Arcane Missiles, so after five casts or two casts respectively, the card will be fully stacked.

**Comment by akrom23** [comment]
#4267
