### ISSUE TITLE
[priest] spirit tap

### ISSUE THREAD

**Issue by leeroymk** [SunwellWoW/Sunwell-TBC-Bugtracker#4275]
Description: 
5/5 spirit tap does not give mana regeneration in 100% of cases after killing mobs and gaining experience when playing in a group

How it works: 
works correctly in 1v1 combat, sometimes activated when killing multiple NPCs, not 100% of the time

How it should work: 
must be activated after killing every NPC for whom the experience or honor

Source (you should point out proofs of your report, please give us some source): 
playing in a group from 1 to 42 level

**Comment by firngrod** [comment]
According to wiki articles about the talent during TBC, the priest needs to get the killing blow on the mobs for this talent to take effect.  Group play is explicitly mentioned in this regard.  Would this account for what you are seeing?

https://wow.gamepedia.com/index.php?title=Spirit_Tap&oldid=1432198

**Comment by siof** [comment]
talent should proc only from killing blows
