### ISSUE TITLE
[warlock] Curse of Recklessness

### ISSUE THREAD

**Issue by leeroymk** [SunwellWoW/Sunwell-TBC-Bugtracker#4276]
Description: 
can cast on player first Curse of Recklessness, then fear. the target continues to run in fear
Curse of Recklessness does not activate the mode of immunity to the effect of fear. 

How it works: 
Curse of Recklessness does not activate the mode of immunity to the effect of fear

How it should work: 
the target should be immune to fear.

Source (you should point out proofs of your report, please give us some source): 
tested in duel

**Comment by akrom23** [comment]
Nope. Target should not be immuned to fear, but can move/cast spells.
