### ISSUE TITLE
Viper Sting simply doesn't work

### ISSUE THREAD

**Issue by Raimzz** [SunwellWoW/Sunwell-TBC-Bugtracker#4278]
Description: **Viper Sting** (mine currently Rank 2) doens't give any mana when used on mobs(who also have mana) not sure about PvP.

How it works: **It doesn't work** xd
![wowscrnshot_020519_203030](https://user-images.githubusercontent.com/47364987/52298375-7fa19680-298b-11e9-9c61-2174ed227bfc.jpg)
![wowscrnshot_020519_203032](https://user-images.githubusercontent.com/47364987/52298376-803a2d00-298b-11e9-9650-ac80c4b538de.jpg)

How it should work: Drain 848 mana over 8 sec. 

Source (you should point out proofs of your report, please give us some source): 
****

**Comment by akrom23** [comment]
More info here:
#3922.
