### ISSUE TITLE
[Hunter][Pet] Kill Command not working without pet target (again?)

### ISSUE THREAD

**Issue by zefurr** [SunwellWoW/Sunwell-TBC-Bugtracker#4279]
Description: 
Kill command isn't doing damage when pet has no target.

This seems to have been brought up previously but was resolved? #1604

How it works: 
Kill command isn't doing damage when pet has no target.

How it should work: 
When pet has no target the Hunter's target should be hit by Kill Command

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=ubVUjiZEVAE

I am wearing hunter 4 piece dungeon 3 set. I still gain the buff when my pet has no target, but it deals no damage and kill command is put on cooldown.

When pet has a target, works properly (damage done, buff gained, kill command put on cooldown)

**Comment by akrom23** [comment]
@zefurr What about that: https://wow.gamepedia.com/Kill_Command?

> Patch 2.2.0 (2007-09-25):
No longer affects the Hunter’s current target.

**Comment by zefurr** [comment]
Huh... that is... interesting. Surprising bit of game design there... it allows me to use an ability and put it on cooldown with no effect (aside from the d3 4-piece armor pen buff)

I'm tempted to interpret that patch note to mean that if the Hunter and the pet both have different targets then the default behavior of Kill Command is to use it on the pet's target.

As a side note the other patch note from your quote is:
> Patch 2.2.0 (2007-09-25):
> Will not charge the hunter mana if their pet is on passive.

As you can see in my video, my pet is on passive. and it is still charging me mana.
But it's also still giving me the armor pen buff.
But from the way that patch note is written, it sounds like if I kept my pet on passive (which I do most of the time) that Kill Command would never cost any mana, even when my pet is attacking something. Passive refers to his behavior mode, while Attack/Follow/Stay refer to orders.

A reasonable inference would be that if the pet does not have a target then Kill Command should cost no mana, have no effect (no damage of aggro), it would still go on cooldown, and the d3 4 piece armor pen buff would probably be an oversight that is still gained.

By contrast, decent game-design would dictate that Kill Command simply wouldn't be castable if the pet had no target. (Or that it would be allowed to be cast on the hunter's target for full effect)
