### ISSUE TITLE
Ilkrud Magthrull

### ISSUE THREAD

**Issue by Moistcookie** [SunwellWoW/Sunwell-TBC-Bugtracker#428]
Decription: Level 24 quest mob named Ilkrud Magthrull in Ashenvale located at Fire Scar Shrine at the south-west corner of the map. 

How it works: He only casts shadow bolts at the player and his pet Succubus might have too much HP. I also I saw his pet Succubus was level 40 once. Not sure what triggered that.

How it should work: In addition to casting his shadow bolts, he is supposed to cast an ability called "Ilkrud's Guardians" that summons 2 voidwalker pets. It's a 5 second cast (interruptable) and he's supposed to cast it roughly 8-10 seconds after the encounter starts. Some say he summons it at 50% health, but from what I've seen, it's always been on a timer on vanilla servers.

Source (you should point out proofs of your report, please give us some source): [https://www.wowhead.com/npc=3664/unused-ilkrud-magthrull#comments](url) The NPC [https://www.wowhead.com/spell=6487/ilkruds-guardians](url) The ability

Read the comments for further information if you wish.

**Comment by Dootz** [comment]
will be fixed with next ptr update. Thank you for report.
