### ISSUE TITLE
Disfunction of Grounding totem (arena)

### ISSUE THREAD

**Issue by Sexygreat** [SunwellWoW/Sunwell-TBC-Bugtracker#4282]
Description: 
Greetings! I found out that grounding totem is not working as it supposed to work on arena. Its not working in los. We were playing against hunter/druid team. All the time when I put grounding behind the colomn my partner is still in roots. 

How it works: 
It is not working in los.

How it should work: 
This totem must always work behind the geodata. 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3022#issuecomment-449926857
> Grounding Totem must also be in LoS + range of the spell's source to work as well.
I think only the shaman or party member must be in range of the totem instead.

So...?
