### ISSUE TITLE
[Rogue] Stealth

### ISSUE THREAD

**Issue by jonikurk** [SunwellWoW/Sunwell-TBC-Bugtracker#4287]
Description: "That ability is not ready yet" comes up when trying to stealth.

How it works: If you try to stealth / vanish in hunters flare, you are unable to stealth again. Even if you go out of the flare and are out of combat, instead you get "That ability is not ready yet" and you need to relog in order to stealth again.

How it should work: Stealth should be usable when you go out of flare and are out of combat.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@jonikurk Send some screenshots.

**Comment by jonikurk** [comment]
![stealthflare](https://user-images.githubusercontent.com/35528774/52495189-9db00680-2bd8-11e9-9958-9d8932f42aa1.jpg)
![stealthflare2](https://user-images.githubusercontent.com/35528774/52495200-a7396e80-2bd8-11e9-8eed-ebf59d4a9591.jpg)
![vanishflare](https://user-images.githubusercontent.com/35528774/52495207-ab658c00-2bd8-11e9-9236-e4ba652a309f.jpg)
![vanishflare2](https://user-images.githubusercontent.com/35528774/52495210-adc7e600-2bd8-11e9-9372-51aae1c379b7.jpg)

**Comment by Bugadin** [comment]
Can confirm it happens sometimes but not only with the hunter's flare.
