### ISSUE TITLE
Stuck in place after pvp trinket

### ISSUE THREAD

**Issue by Feorblade** [SunwellWoW/Sunwell-TBC-Bugtracker#4288]
Description: 

When I use PvP trinket to break fear, I'm stuck in place until another CC hits me. In arena, I was unable to move after using trinket on fear. Once he procced a mace stun on me, I was able to move my character. Similar things have happened to me in BG's and world PvP
How it works: 
Character gets stuck in place after using PvP trinket

How it should work: 

I should not be stuck in place 
Source (you should point out proofs of your report, please give us some source): 

I saw another post asking for a screenshot of combat log so here's a screenshot of that, I'm not sure if it will be of any help.

https://i.imgur.com/HoZxCtp.png

**Comment by zefurr** [comment]
Just to spread the knowledge, when this does happen reloading my UI typically fixes the problem.

Obviously not super useful mid-fight. But if you survive it can get you moving again without having to log out

**Comment by akrom23** [comment]
@Feorblade Not able to reproduce it :/

**Comment by Devrak** [comment]
physical fear + any slow effect / spellfear + any slow or phy + spell fear at the same time maybe issue is there that server is not sending client the info that char can move again after fear breaking.

**Comment by akrom23** [comment]
@Devrak I tried with Intimidating Shout + Psychic Scream - just like the screenshot shows. Everything works fine locally.
I would be gratefull if someone could do some tests in duel.

**Comment by akrom23** [comment]
Related: #4168.

**Comment by Devrak** [comment]
Another thing the #4068 issue or related  ... as a cast debuff fear also gets no refresh event at the moment while it breaks addons i have no idea how much it messes up the client itself a test with fear then refresh fear before it fades then again refresh fear before it fades and try to break out ... what happens idk. ill try to get and do some duels if i have time later today.

**Comment by Feorblade** [comment]
I would like to add that I was able to Shadowstep while I was stuck in place, but even after stepping to a target, I wasn't able to my character I was merely stuck in a new location. Maybe it has something to do with holding your move key while being CC'd and using your trinket?

**Comment by akrom23** [comment]
Guys: screenshots with combat log, please.
