### ISSUE TITLE
Pet Vanished Again! But I know what happened!

### ISSUE THREAD

**Issue by Pwncakey** [SunwellWoW/Sunwell-TBC-Bugtracker#4289]
Description: 
My pet has vanished from the stable yet again, but this time I know exactly what happened.

How it works: 
So after taming my new rare gorilla, I returned to the stables and switch my pets out, back to Jammies who was waiting peacefully in there. However when I went to switch, I guess because I was mounted I placed WhippedCrack back, and Jammies vanished!

How it should work: 
I should be able to switch them out just fine and have it summon but for some reason my pet vanished instead.

Source (you should point out proofs of your report, please give us some source): 
My own damn eyes.

**Comment by akrom23** [comment]
@Pwncakey Jump into our Discord and poke me (Anakin#5545).
