### ISSUE TITLE
Netherspite breath and beams bug

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#4296]
Green beam is supposed to regen full your mana bar with each tick. This is not working.

Nether breath is not supposed to be interrupt. He should be immune to interrupt.

**Comment by MiekZer** [comment]
I didn't see on the changelog tbc anything about updating the green beam.
Here is the source : 
First of all you can see there https://wowwiki.fandom.com/wiki/Patches/2.x (and check patches one by one) that there was no changes about beams. (A quick overview of KZ changes patchs after patchs is presented here https://www.reddit.com/r/wowservers/comments/4hyi88/kara_per_patch_nerf_changes_to_adress_all/).

Now from wowwiki : https://wowwiki.fandom.com/wiki/Netherspite
Similar to the red beam, mana is restored to the new maximum with each tick. 

I also suggest that you take a look at every buffs and debuffs beams are supposed to give because I don't really think it's actually well scripted, blue beam carriers are for example too easy to heal and do not receive the debuff I think (but not sure I didn't take blue beam yet)

Beams buffs/debuffs didn't change till the first retail version of Netherspite and this is not a 2.1+ change that green beam is supposed to refill mana bar with each tick.

**Comment by neheri** [comment]
Breath still can be interrupted.
