### ISSUE TITLE
Ilhoof not sacrificing main target

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#4297]
Pre nerf (pre 2.1 kara) Ilhoof is supposed to be able to sacrifice even his main target aka the tank. I have never seen a sacrifice on the tank (with the tank having aggro and not because he lost aggro and then got sacrified)

**Comment by Ironjudgment** [comment]
Support.
Patch changes from 2.1
https://wowwiki.fandom.com/wiki/Patch_2.1.0

> Terestian Illhoof will no longer sacrifice his primary target.

@MiekZer It would be best to include any sources next time and stick to the bug report method (which asks about sources aswell).

**Comment by MiekZer** [comment]
since this fix I have seen some chains casted on nobody (but at least I've seen it casted on the tank so it's working) but now there is a new bug with chains casted on nobody, you see the animation of chains smoke in the middle but the chain doesn't appears and nobody is teleported in the middle. It happened often during the fight.
