### ISSUE TITLE
High Astromancer Solarian damage is bugged!

### ISSUE THREAD

**Issue by shadywildone** [SunwellWoW/Sunwell-TBC-Bugtracker#4299]
Description: The damage tuning on High Astromancer Solarian seems overtuned and incorrect. Our fully geared tier 4 bear tank got 1 hit by a melee swing from High Astromancer Solarian.

How it works: High Astromancer Solarian is melee swinging inbetween arcane missile attacks, one shotting her target, including our main tank. Also her wrath of the astromancer is dealing twice the correct damage, from 5k to 9.5k damage when it explodes on the main target.

How it should work: She is supposed to be casting arcane missiles the entire first phase of the fight. Her wrath of the astromancer should only deal 5k damage maximum to the target afflicted with the debuff.

Source (you should point out proofs of your report, please give us some source): https://gyazo.com/88b4c4c520e1611ec9b61249557643f7

**Comment by neheri** [comment]
Crushing blows deal 150% damage.

However we also noticed her damage is very high, probably due to being pure arcane. 

https://github.com/Schaka/TBC-research/issues/22

From CC github is should be:

* **High Astromancer Solarian:** 6157-8696

with Crushing blow this could be up to: ~13k.
