### ISSUE TITLE
Old Towns Tavern has npcs walking all over the place 

### ISSUE THREAD

**Issue by leahnie956** [SunwellWoW/Sunwell-TBC-Bugtracker#430]
Decription: 
Old Towns Tavern has npcs walking all over the place 

How it works: 
should walk normally 

How it should work: 
needs to rescript all of it

Source (you should point out proofs of your report, please give us some source): 
![qrher](https://user-images.githubusercontent.com/25886407/45728475-c5e98b00-bb8d-11e8-9317-1739309c2fde.png)
![unknown](https://user-images.githubusercontent.com/25886407/45728481-c97d1200-bb8d-11e8-9c36-47002e7c5762.png)

**Comment by Dootz** [comment]
will be fixed with next ptr update. Thank you for report.
