### ISSUE TITLE
[Hunter] [Spell] Hunter's Mark 

### ISSUE THREAD

**Issue by street-racer777** [SunwellWoW/Sunwell-TBC-Bugtracker#4301]
Description: 

hunter's mark do not  completely work.
How it works: 

hunter's mark do not  additional 11 each time they are struck by a tanged attack, up to a maximum of 440(rank 4).

How it should work: 

should increase ranged attack power against this target by 110 **and an additional 11 each time they are hit by a tangential attack, up to a maximum of 440 (level 4).** With talent  "[Improved Hunter's Mark]" this should be increase meele atack power.

Source (you should point out proofs of your report, please give us some source): 

https://imgur.com/a/0QwVTLh 
Description: 
On left screenshot: pet was attack [hunter's mark] **without** talent.
On central screenshot: pet was [hunter's mark] **with** talent.
On right screenshot: pet was **with**  [Greater Blessing of Might] and **without** [hunter's mark].

**On all tests, all time, I and my friend use only autoshoots for start trigger the second condition [hunter's mark].**

**Comment by street-racer777** [comment]
Before this test my friend was take off all proc items and buffs.
On left screenshot: pet was attack [hunter's mark] **without** talent.              **AVG meele 194**
On central screenshot: pet was [hunter's mark] **with** talent.                         **AVG meele 206**
On right screenshot: 
pet was **with** [Greater Blessing of Might] and **without** [hunter's mark]. **AVG meele 238**

[Hunter's mark] should be increase RangeAP and MeeleAP(with talent) for 440.
As a result [Hunter's mark] (440AP for range and meele with talent) it has less buff damage in comparison with [Greater Blessing of Might](221 AP for range and meele with talent).
From this we conclude that [hunter's mark]  buff only 110AP.

**Comment by zefurr** [comment]
"Causes 100% of your Hunter's Mark ability's BASE attack power to apply to melee attack power as well"

My interpretation of this is that BASE refers to the initial 110 attack power provided by Rank 4 Hunter's Mark.

But that's just my perspective

**Comment by Ironjudgment** [comment]
#4237
