### ISSUE TITLE
Item Description - Rep Keys

### ISSUE THREAD

**Issue by Ironjudgment** [SunwellWoW/Sunwell-TBC-Bugtracker#4305]
Description: 
Tooltip description of reputation keys is incorrect - at least during this patch.

How it works: 
Tooltip description shows that reputation keys are usable at honored stage.

How it should work: 
On this patch, tooltip description should mirror the actual requirements - Revered.

Source (you should point out proofs of your report, please give us some source): 
I only have a screenshot for the Sha'tar Key but it is the case for all of them.
https://i.imgur.com/E52oAiX.png

**Comment by zefurr** [comment]
Clear your cache
