### ISSUE TITLE
[Item] Serpent-Coil Braid

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#4306]
Description: 

How it works: 
You dont gain 25% more mana when you use a mana gem

How it should work: 
You gain 25% more mana when you use a mana gem

Source (you should point out proofs of your report, please give us some source):

**Comment by Ironjudgment** [comment]
any screenshots, vidoes? Right now your bug report does not tell us anything.

**Comment by ZaoQ** [comment]
it works, my friend made a mistake, pls close this issue .)
