### ISSUE TITLE
Hunter - Kill command not working

### ISSUE THREAD

**Issue by grzessam** [SunwellWoW/Sunwell-TBC-Bugtracker#4309]
Description: When I strike a critical I recieve an option to use Kill Command but when I use it I recieve invalid target information and Kill Command don't execute. It worked couple of days before

How it works: Kill Command despite striking critical cannot be used because of invalid target

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@grzessam Provide screenshots.

**Comment by grzessam** [comment]
![obraz](https://user-images.githubusercontent.com/47526184/52564850-768a4c80-2e05-11e9-97df-c5872855def5.png)

**Comment by grzessam** [comment]
I spam kill command by pressing 2 button and recieve invalid target. Tested on multiple mobs and tried in macro as well. In both cases it's not working

**Comment by akrom23** [comment]
Cannot reproduce it.

**Comment by grzessam** [comment]
I've switched owl to cat in stable master and kill command started to work. Now I will switch again and see what happens

**Comment by grzessam** [comment]
Kill command isn't working for Owl. After I switched to cat again I've noticed that I use kill command but it doesn't do any damag. In combat log there is no information about kill command. It's weird because I've used kill command yesterday while using owl and:
1. I could use kill command when using owl as a pet.
2. Kill command dealt dmg - now it's not

**Comment by street-racer777** [comment]
https://www.youtube.com/watch?v=VaEtgZU2IZw&feature=youtu.be

**Comment by MiekZer** [comment]
+1 no damage done

**Comment by Diobloxx** [comment]
Checked dps logs and confirmed it doesn't show Kill command anymore even though it's on cooldown.

**Comment by MiekZer** [comment]
First boss Karazhan : attumen and midnight stacked. Can't kc on midnight invalid target (but can kc on attumen, can also kc phase 2)

Looks like if your pet is closer to target A than with target B you cannot kc on B.

**Comment by Fixedcoco** [comment]
https://ibb.co/cwj6m5X
