### ISSUE TITLE
SWD bugged

### ISSUE THREAD

**Issue by Freshbtw** [SunwellWoW/Sunwell-TBC-Bugtracker#4314]
Description: Shadow Word: Death does not deal damage to the priest if the target takes absorbed damage. Pretty gamebreaking for pvp.

How it works: Caster does not take damage from an absorbed SWD

How it should work: Caster should take damage from an absorbed SWD

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=QWM7uprjW5g
https://www.youtube.com/watch?v=CGS2nAEfp08
https://www.twitch.tv/videos/379090566?t=00h16m10s

**Comment by arkatik** [comment]
I confirm that this bug was on Saturday when I played the arena.
This is critical for pvp.
put a label **High priority** and fix as soon as possible, or you will not see a single priest in the arena

**Comment by arkatik** [comment]
@Wojtyas , @akrom23 
Tomorrow is the last day to play arena, but how to play if the bug exists?
This is critical for pvp and this should be fixed immediately.
it feels like you're specifically killing a dead pvp...
