### ISSUE TITLE
[Enchanting] Formula: Enchant Weapon - Major Spellpower.

### ISSUE THREAD

**Issue by pinkisnotgay** [SunwellWoW/Sunwell-TBC-Bugtracker#4319]
Description: 
Throughout last 2 weeks I've spent over 10+ hours and killed over 1150 Bashi'r Spell Thiefs
Formula: Enchant Weapon - Major Spellpower doesn't drop. I was talking to Crafty via Game Ticket and he told something about the drop rate "it's really low 5.2% from npc 20614, and 1% from npc 22242". According to his words the recipe should drop from both Raazani Spell Thief (npc 20614) and Bashi'r Spell Thief. (npc 22242). I even recieved a link to database from him, ( http://db.darkwizard.pl/?npc=20614 )  but there's nothing confirming that Raazani's drop the recipe, but that's not the biggest issue here.
Since FIX 
#1266
Core | Author: Dootz
Database / Loot
Apexis Shard and Ogri'la Depleted items removed from loot (hopefully)."'

The recipe is nearly impossible to get, I've met many other players that are struggling the same way as I do. Spending multiple hours, even days trying to obtain it and eventually giving up on it. 

How it works: 
Formula: Enchant Weapon - Major Spellpower should drop from Bash'ir Spell Thiefs, but since mentioned fix went live, it doesn't anymore.
How it should work: 

Bash'ir Spell Thiefs should drop the mentioned Recipe.

Source (you should point out proofs of your report, please give us some source):

**Comment by Mikju1** [comment]
Same here haven't seen it dropping! farming like grazy those spellthief's!

**Comment by NoCandy** [comment]
I got it after killing 9 thiefs today confirmed working, you are just unlucky.
