### ISSUE TITLE
High Astromancer Solarian fps drop

### ISSUE THREAD

**Issue by flapse32** [SunwellWoW/Sunwell-TBC-Bugtracker#4321]
Description: High Astromancer Solarian

How it works: My guild had 20 people in a raid dropping to 5 fps on Solarian boss fight. It was fine to begin with and it got worse and worse the longer we were fighting the boss. Was not just the adds phase it was just in general. Was unplayable. This is the first time it happend and it only happend to 20 people out of 25, so maybe a addon? eitherway its worth to give it a look and see for yourself.

How it should work: Should not drop from 180 fps to 5 when every other boss is fine.

Source (you should point out proofs of your report, please give us some source):

**Comment by mchayes** [comment]
Did your guild swap to DiamondThreatMeter by chance?

**Comment by flapse32** [comment]
We all have it i believe yes

**Comment by flapse32** [comment]
But i mean this is the first time it happend, and we have used Diamondthreatmeter multiple kills now.

**Comment by Wojtyas** [comment]
Dunno if I should consider it as bug or what. It looks like its clientside issue not realm, will ask dev anyway.

**Comment by flapse32** [comment]
Going to raid it again tonight, will let you know the outcome.

**Comment by flapse32** [comment]
Edit: Its diamondthreatmeter that causes the huge lag spike. 99% sure

**Comment by koostosh** [comment]
Not a server side bug
