### ISSUE TITLE
[Hunter] Crit chance below normal values

### ISSUE THREAD

**Issue by Piezito** [SunwellWoW/Sunwell-TBC-Bugtracker#4322]
Description: Hunter 70, was trying to see why my crit chance was low so I respecced to empty all point talents, and kept the necessary items to have  224 AGI with no crit chance from items, with this value I have 0 crit chance, image explain it all

How it works: crit chance below normal values

How it should work: crit chance stacked correctly

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_021319_161531](https://user-images.githubusercontent.com/47603358/52722749-8e500500-2fac-11e9-881f-e140cc4b138e.jpg)

EDIT: 273 AGI with +10 crit chance from Valano's Longbow and still 0 crit chance

![wowscrnshot_021319_163812](https://user-images.githubusercontent.com/47603358/52723520-f6ebb180-2fad-11e9-8c4e-f2f577e635cd.jpg)

**Comment by notsofamous** [comment]
What's your weapon skill?

**Comment by akrom23** [comment]
@Piezito @notsofamous is right. Crit chance depends on your skill weapon.
