### ISSUE TITLE
Kill Command does no dmg now.

### ISSUE THREAD

**Issue by VintherMN** [SunwellWoW/Sunwell-TBC-Bugtracker#4323]
Description: Kill Command does no damage.

How it works: You use kill command after a crit, and it does damage to your target, assuming ur pet is also targeting your target. Kill Command however does no damage after using it, and puts it on cooldown.

How it should work: Kill Command should be doing damage..

Source (you should point out proofs of your report, please give us some source): 
http://db.excalibur.ws/?spell=34026 
states KC should be doing damage..

**Comment by Ironjudgment** [comment]
Can confirm. KC not wokring. https://www.youtube.com/watch?v=x3YEoKLKJAo

I don't know if it's the same issue as #4309 since there's no 'Invalid Target', it consumes mana and applies cooldown on skill. 

And #4309 is Resolved - 'Fix NOT Live Yet'.

**Comment by flapse32** [comment]
Can also confirm, u somehow made kill command do no dmg whatsoever.... jeeeez

**Comment by flapse32** [comment]
It works normal now again after the server update.
