### ISSUE TITLE
[Item] Felsteel Shield Spike

### ISSUE THREAD

**Issue by pinkisnotgay** [SunwellWoW/Sunwell-TBC-Bugtracker#4325]
Description: 
Felsteel Shield spike is not working properly. The damage should vary betwen 26 and 38, but it usualy deals less damage. From 23 to 25

How it works: 
It deals less damage than it's supposted to.

How it should work: 
Damage should vary between 26-38

Source (you should point out proofs of your report, please give us some source): 
![felsteel shield spike 2](https://user-images.githubusercontent.com/44933866/52752731-2fae7980-2ff4-11e9-8ba2-b010d241b8b0.png)
![felsteel shield spike 3](https://user-images.githubusercontent.com/44933866/52752732-2fae7980-2ff4-11e9-8495-6ccfff06299a.png)
![felsteel shield spike](https://user-images.githubusercontent.com/44933866/52752733-30471000-2ff4-11e9-8298-83856d98bf6e.png)

**Comment by blackwife** [comment]
Shield spike damage is affected by armor.  It looks like the variance is off, but the total damage done is fine.
