### ISSUE TITLE
Water mote clouds in Zangarmarsh give motes of life.

### ISSUE THREAD

**Issue by Leiffis** [SunwellWoW/Sunwell-TBC-Bugtracker#4326]
Description: Mote clouds that can be extracted with [Zapthrottle Mote Extractor] in Zangarmarsh should give the engineer motes of water, NOT motes of life. 

How it works: Engineer gets motes of life from Zangarmarsh gas clouds.

How it should work: Engineer should get motes of water from the gas clouds in Zangarmarsh.

Source (you should point out proofs of your report, please give us some source): 

Issue was mentioned earlier in:
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3309
but recieved no fixes.

https://wowwiki.fandom.com/wiki/Gas_cloud 
(This article mentions that "Swamp Gas" should yield motes of water.)

**Comment by Wojtyas** [comment]
Back in 2.0 u could gain mote of life from them. Will be changed with adequate patch change.
