### ISSUE TITLE
Aeonus drop

### ISSUE THREAD

**Issue by RoDavid4** [SunwellWoW/Sunwell-TBC-Bugtracker#4328]
Description: 
he never drops healing wrist or trinket, i run it like 20 or 30 times, never seen it

How it works: 

NEVER DROPS
How it should work: 

it should drop the items eventually

**Comment by NoCandy** [comment]
Just 2 days ago a warrior comented that the wrist drops every time, ive seen the trinket multiple times aswell. For me those 2 items are the most common drops.

**Comment by firngrod** [comment]
Had the same thing happen to me on retail.  I must have run that instance more than 30 times before I got the Primalsurge Bracers.  RNJesus loves you not, I guess.

**Comment by RoDavid4** [comment]
drop rate MUST BE bad, there is no way i NEVER see the fuckyn wrist, there is almost 0 mail healing items plus rshaman DON'T HAVE D3 SET and resto shaman DON'T HAVE pvp OffSet so.... how the hell can i gear up playing in a low pop server when the boss DON'T WANT TO GIVE ME THE WRIST

i just can't, i don't want spirit gear, i see the stupid hourglass soooooo many times resto shaman wrist drop rate IS NOT RIGHT and resto shamans NEED IT.

**Comment by RoDavid4** [comment]
18 fuckyn dragons every run 18!!!!!!!!
