### ISSUE TITLE
Melee auto attacks ignore LoS

### ISSUE THREAD

**Issue by Aikamz** [SunwellWoW/Sunwell-TBC-Bugtracker#4330]
**Description:** 
Melee auto attacks have no line of sight check. You can attack through walls, pillars etc.

**How it works:** 
You target enemy that is in melee attack range but not in line of sight and start auto attack. The attack will go through.
Pets can also attack through walls if they are in range. If they are not they will run around.

**How it should work:** 
Obviously you should not be able to attack through walls?

Source (you should point out proofs of your report, please give us some source): 
Melee attack through wall:
![image](https://user-images.githubusercontent.com/20050120/52902299-8e077200-3217-11e9-8aa4-7db5cbfaef36.png)
![image](https://user-images.githubusercontent.com/20050120/52902313-b2634e80-3217-11e9-948d-62ce2327668d.png)

Pet attack through wall:
![image](https://user-images.githubusercontent.com/20050120/52902303-99f33400-3217-11e9-9e9d-45a4beb59b33.png)

**Comment by akrom23** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/227
