### ISSUE TITLE
Stables Broken Sunwell 

### ISSUE THREAD

**Issue by BillNyeTGG** [SunwellWoW/Sunwell-TBC-Bugtracker#4333]
Description: I switch my pet out on my stables with it out (NOT DISMISSED) and the pet i was pulling out disapeared and i had just got it to 70 and max loyalty the same day and now i have to start from scatch? this is a huge issue and needs to be resolved i now cant raid because of it and something should be done about it 

How it works: there there is a chance when your switching pets at the stable you could lose one of them even if there not dismissed 

How it should work: you should be able to just quick swap different specs as you want.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@BillNyeTGG Jump into our Discord and poke me (Anakin#5545).
