### ISSUE TITLE
Lady Vashj becomes loot pinata after phase 2

### ISSUE THREAD

**Issue by nickycakes** [SunwellWoW/Sunwell-TBC-Bugtracker#4336]
Description: 
lady vashj bugs after phase 2 ends and stands there doing nothing until dead.  

How it works: 

last 2 ids, vashj has stopped doing anything after phase 2 is completed.  assumed according to the changelog that it had been fixed, since last week but seems like not.  will take a video next week and post if it's still bugged.

How it should work: 

she should do things other than nothing in phase 3

Source (you should point out proofs of your report, please give us some source):

**Comment by xethra89** [comment]
https://clips.twitch.tv/MoldyBraveWerewolfNerfBlueBlaster

**Comment by Ironjudgment** [comment]
another instance of http://sunwell-community.com/index.php?/topic/6630-atlantis-horde-guild-vashj-bug-kill/ ?

Has Atlantis Horde killed Vashj using the bug again or not, since it doesn't show in the clip?

For comparison my guild killed it legit last night. https://youtu.be/20loNo0E4Z4?t=100

**Comment by nickycakes** [comment]
doesn't look like the same bug.  for us she just stands there doing nothing after we complete phase 2.  no idea what triggers it, but if someone can clue us in so we can play the encounter legit, that would be awesome.
