### ISSUE TITLE
Item/Spell Greater Rune of Warding

### ISSUE THREAD

**Issue by mgperera** [SunwellWoW/Sunwell-TBC-Bugtracker#4337]
Description: 
Not getting a single proc out of this consumable. Tracked auras gained and absorbs done thru many many mobs from stratholme entrance to the living side, not a single procof the 400 physical dmg absorb from greater rune of warding.

How it works: not getting a single proc out of the item

How it should work: 25% on being hit to absord the next 400 phyisical dmg

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/vRdfwnR
https://www.wowhead.com/item=25521/greater-rune-of-warding

**Comment by koostosh** [comment]
Works as intended. 25% chance, 400absorb, 90s cooldown.
There is no aura applied when this item is triggered, so it might not be detected by addon. Absorb is visible in combat log.
