### ISSUE TITLE
[S1][Druid]Gladiator's Idol of Resolve - Doesn't Work

### ISSUE THREAD

**Issue by plzdontcry** [SunwellWoW/Sunwell-TBC-Bugtracker#4338]
Description: 
Simply doesnt work

How it works: 
Doesnt work

How it should work: 
The idol should give a buff after you used Mangle for 6 sec, either in bear and cat, this buff should give 26 resilience.

Source (you should point out proofs of your report, please give us some source): 
![incat](https://user-images.githubusercontent.com/47726198/52951168-53b9e400-3381-11e9-94a7-b1e6d8bae4cb.png)
![inbear](https://user-images.githubusercontent.com/47726198/52951173-5b798880-3381-11e9-8360-b295a7b7e0fe.png)
You can see on these picture , no buff appears on combat log.
I have got the 43 resilience, from the trinket, and belt!

**Comment by Ironjudgment** [comment]
@plzdontcry for Source, you can simply take a clip of you showing that you use mangle and buff not appearing with your character stats window open or some screenshots

**Comment by plzdontcry** [comment]
I tested, works, thank you!

**Comment by plzdontcry** [comment]
Only there is 1 thing what i dont understand, this buff is 6 sec, and mangle Cooldown 6 sec too, but if i spam only mangle (with opto-mehanik keyboard) i still have a 0,5 sec without this buff , so its looks like i only have this buff for 5,5 sec instead of 6.
