### ISSUE TITLE
Hunter pets spawning with missing HP after dissmount

### ISSUE THREAD

**Issue by Lorious** [SunwellWoW/Sunwell-TBC-Bugtracker#4343]
Description: 
https://youtu.be/SrsPOzT36rs
Even without gearchanges during dissmount the pet spawns with less than 100% HP, check video.

How it works: 
https://youtu.be/SrsPOzT36rs

How it should work: 
They should spawn with 100% HP

Source (you should point out proofs of your report, please give us some source): 
Check video

**Comment by akrom23** [comment]
When you used mount, your hp decreased. Talent?

**Comment by Lorious** [comment]
I had a riding set the first tries but as you can see in the video I disable that in the later tries.

**Comment by akrom23** [comment]
Okay.

**Comment by Lorious** [comment]
https://youtu.be/2zpbehqTBaw - Test with no gear!

We just found somethiing interesting, my pet get's like no HP from my gear stamina but TOOOONS from power word fortitude (On main char not on pet). He lost like 20% hp when I removed the buff. Trying to find a priest to help test.

**Comment by Lorious** [comment]
Seems like my pet drops around 300 hp whenever he spawns after dismount, he lost 5,5% when i was wearing gear and 6,9% when I wasn't. Looks like some sort of fixed amount.

**Comment by akrom23** [comment]
The bug with Power Word: Fortitude is known: #2102

**Comment by akrom23** [comment]
Cannot reproduce this bug.

**Comment by Jonsbe** [comment]
Standing in orgrimmar, alt doing to hunter mark of the wild 14 stats, pet goes from 4.9k to lose hp to 4k. And total gains to 5.1k health but still on buff loses health.

**Comment by Jonsbe** [comment]
99 bugs, fix 1 bug... now 101 bugs song.

**Comment by akrom23** [comment]
@Jonsbe Breathe...
Fixed - not live.
