### ISSUE TITLE
Flame Cap does not proc on ranged hits

### ISSUE THREAD

**Issue by zefurr** [SunwellWoW/Sunwell-TBC-Bugtracker#4345]
Description: 
As a hunter I've used 7 flame caps without getting a single proc across the entire duration for any of them. I also used one and ran into melee range to spam wing clip and did manage to get a few procs. I'm left to believe that flame cap is not proc on ranged attacks, contrary to the tooltip. It is also possible that the proc rate for ranged attack is obscenely low (Or I am obscenely unlucky)

How it works: 
Flame Cap says:
"Use: Chance to strike a ranged or melee target for 40 fire damage. Also increased fire spell damage by up to 80. Lasts 1 min."

Flame cap is not proccing on ranged attacks.

How it should work: 
Flame cap should proc on ranged attacks.

Source (you should point out proofs of your report, please give us some source): 
Observation.

**Comment by MiekZer** [comment]
I also tried and it never procced.

**Comment by MiekZer** [comment]
Now working.
