### ISSUE TITLE
Leotheras whirlwind bleed stacks

### ISSUE THREAD

**Issue by VintherMN** [SunwellWoW/Sunwell-TBC-Bugtracker#4348]
Description: Leotheras the blind in SSC has an ability called Whirlwind - and if hit by this ability you will gain a bleed debuff.

How it works: Leotheras casts whirlwind and if hit multiple times by the whirlwind, the bleed debuff that he applies to you stacks.

How it should work: The bleed debuff from whirlwind is NOT supposed to stack, according to several retail TBC videos, and also according to wowwiki/wowpedia. According to these sources he is supposed to apply one non-stacking bleed that deals 2500 dmg per tick every 3 seconds. If hit several times by the whirlwind, the bleed is reset to its full duration every time you are hit.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=9IAVxJg_47o (leo starts at 11:33)
https://wow.gamepedia.com/Leotheras_the_Blind
https://wowwiki.fandom.com/wiki/Leotheras_the_Blind

**Comment by Bugadin** [comment]
False, that how it worked on retail. The bleed stacks on prenerf content.
