### ISSUE TITLE
Sunstrider Isle guards run for no reason

### ISSUE THREAD

**Issue by leahnie956** [SunwellWoW/Sunwell-TBC-Bugtracker#435]
![image](https://user-images.githubusercontent.com/25886407/45790399-44a3fe00-bc4a-11e8-9ab3-fe4cb877bc5f.png)

**Comment by akrom23** [comment]
I guess that's not a bug. It's only clientside visual and happened on blizzard too.

**Comment by Dootz** [comment]
i followed this npc for a while, looks fine.
