### ISSUE TITLE
Warlock : Ritual of Souls CD Visual issue

### ISSUE THREAD

**Issue by Espranty** [SunwellWoW/Sunwell-TBC-Bugtracker#4350]
Description: 
Cant see Cool-down of Ritual of Souls spell after casting it .

How it works: 
When u cast Warlock's Ritual of Souls spell .. it doesn't show the 5 minutes Cool-down on spell (Appears as if it's still Usable) .. Which makes knowing when its ready again Annoying (Having to spam cast it after a wipe till its off CD)

How it should work: 
When u cast any ability (all working fine except this Spell) , it should Trigger a Visualisation of its Remaining Cool-down

Source (you should point out proofs of your report, please give us some source):

**Comment by Ironjudgment** [comment]
Screenshot, video?

**Comment by Espranty** [comment]
I'll take a Screenshot next raid (Right after i pop Ritual of Souls) and post it here . Ty for Reply

**Comment by akrom23** [comment]
@Espranty Any news here?

**Comment by Espranty** [comment]
ye, gonna post 2 screenshots now , Before and After using the Spell

**Comment by Espranty** [comment]
@akrom23 Dont worry about the Model edit, this was taken yesterday on Nightbane <3

1/ This is a Before pic, showing that im Currently casting the spell , Also u can see the icon on the right side of my bars (Targeted) .
https://imgur.com/a/OsKYQip

2/ This is After Successful cast of Ritual of Souls (You can see the Table on Ground) , Also hovering over the spell showing no CD Trigger after Successful (or even un-successful cast) , Below the Ritual of Souls icon , u can see a Soul stone on CD and how the CD should Look like ,for comparison .
https://imgur.com/a/UZkx1cl
https://imgur.com/a/9AkTk5O

Thank you .
