### ISSUE TITLE
Warlock :  Curse of Doom gets removed Randomly .

### ISSUE THREAD

**Issue by Espranty** [SunwellWoW/Sunwell-TBC-Bugtracker#4351]
Description: 
Curse of Doom gets totally removed (Randomly) during its Duration.

How it works: 
Randomly ( happened to many other locks too, i checked ) when i Cast Curse of Doom on a Target , Usually it works fine and finishes its full duration and Tick the Big damage ....
However, Like once /Twice every raid night . when i cast it , During the duration , it gets Removed Completely ... Its not Visual bug , because the damage doesn't actually tick at the Supposed end of Duration , and we checked if we had Total of over 40 Debuffs on target , but we weren't even close to that many debuffs .

How it should work: 
Curse of Doom should either be Completely Resisted on Cast .. or continue its full duration and Tick .
Ty

Source (you should point out proofs of your report, please give us some source):

**Comment by Ironjudgment** [comment]
Video, screenshot?

**Comment by Espranty** [comment]
> Video, screenshot?

Unfortunately i dont Stream , nor Record using Fraps etc .. and without Video record its almost impossible to prove, since it happens randomly during Raid night ..

 but i tell you Sir , every other warlock in my Guild , and Friend locks from other guilds had this issue at least once .. its a thing, good Sir

**Comment by Trsko** [comment]
Hey, This happens to CoE and CoR aswell.

**Comment by akrom23** [comment]
Extended combat log will be very helpful.

**Comment by Espranty** [comment]
i started Recording our raids lately,  once i see it happens in one of our future raids, ill post a video of it , Sorry for the delay

**Comment by koostosh** [comment]
Could not reproduce.
