### ISSUE TITLE
Flask of Petrification

### ISSUE THREAD

**Issue by mchayes** [SunwellWoW/Sunwell-TBC-Bugtracker#4361]
Description: 
Theres a bug regarding an item called _Flask of Petrification_. Washed up uses a nice niche tactic on Solarian avoiding her bomb mechanic. The issue comes with REMOVING the flask prior to it actually running out.  In their chatchannel they refer to it as "_coconutting, to coconut_"

How it works: You can go into several washed up VODs and check how they do solarian. They run out with the bomb debuff; drink a flask and then how to break the effect. Simply **_Rightclick_** an NPC.
https://clips.twitch.tv/SweetShyCarabeefDxAbomb

In this case the hunter can't remove it because the character is attempting to autoshoot instead of going into a combat stance. Probably would have worked if he'd use raptor strike.

So again. The issue here is that right click removes the _flask of petrification_ effect. Not that it removes something in a bossfight.

How it should work: 
Nothing should be able to remove the _Flask of Petrification_ effect.

Source (you should point out proofs of your report, please give us some source): 
https://wowwiki.fandom.com/wiki/Potion_of_Petrification
![image](https://user-images.githubusercontent.com/20542656/53248972-32296700-36b7-11e9-8ce6-5287000e88cb.png)

**Comment by Spoohne** [comment]
Rat fuck
