### ISSUE TITLE
Cold Snap should reset GCD.

### ISSUE THREAD

**Issue by hyxgod** [SunwellWoW/Sunwell-TBC-Bugtracker#4362]
Description: 
(MAGE) Technically Cold Snap has gcd which it shouldnt. When you use for example Cone of cold > Cold Snap > Cone of cold it doesnt procc the second one instant. The gcd is supposed to reset when using cold snap so you can procc another cone of cold instant = 2x in 1gcd. On Nightbane, the Cold Snap spell does reset the gcd by the LOOKS only, and not practically. Hope you understand my explanation!

How it works: 
Cold Snap triggers GCD.

How it should work: 
Cold Snap should reset the GCD.

Source (you should point out proofs of your report, please give us some source):

**Comment by babno** [comment]
No way in hell should it work like that. The GCD is not a frost spell.
