### ISSUE TITLE
Scroll stacking

### ISSUE THREAD

**Issue by flapse32** [SunwellWoW/Sunwell-TBC-Bugtracker#4363]
Description: Example Scroll of agility V, will stack with Scroll of agility IV

How it works: All scrolls stacks up, i think alot of people will hate getting this fixed but its not blizzlike at all.

How it should work: Scrolls should not stack with lower or higher ranked scrolls of the same stat.

Source (you should point out proofs of your report, please give us some source):

**Comment by flapse32** [comment]
Agility dosnt stack anymore, but Strength does.

**Comment by akrom23** [comment]
@flapse32 I forgot about the strength :)
