### ISSUE TITLE
Paladin: Seal of blood / Seal of command going of spell damage

### ISSUE THREAD

**Issue by Vasalina** [SunwellWoW/Sunwell-TBC-Bugtracker#4366]
Description: Seal of blood and Seal of command scales on Spell damage and not Attack power. For example if you use Spell damage trinket your Seal of blood hits will hit very hard (Its broken for pvp) and on the other hand Ret paladins that have geared full Attack power are doing way less damage than they are suppose to cause the seals isnt scaling on them.

How it works: Seal of bloods and Seal of commands procs scales on Spell power

How it should work: Seal of blood and Seal of commands procs should scale on Attack power.

Source (you should point out proofs of your report, please give us some source): https://wow.gamepedia.com/Seal_of_Blood
"The seal only scales with weapon damage, not spell damage. It therefore heavily favors melee-geared Paladins " 
"Note that the Judgement does scale with spell damage." (This is working correct)

**Comment by Devrak** [comment]
No, Seal of command scales with spell power, judgements also scale with spell power and seal of blood is based of weapon damage, Seals never ever have scaled with attack power in tbc ( maybe u confusing with ap -> sp talent in wotlk ) and ret paladin is doing exactly what it is supposed to so dps wise It was only viable in retail tbc with seal twisting.

- Invalid

Extra: it appears SoCommand is using normalized weapon speed ( 3.3 ) for ppm calculations resulting in way less procs for slow weapons ... it however should use actual weapon speed prior to any haste effects for ppm calculations.

**Comment by akrom23** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4267#issuecomment-460244763

**Comment by Vasalina** [comment]
If Seal of blood also is suppose to work with spell power than its working correctly cause it is. By using spell damage gear and spell damage trinket every Seal of blood proc (every swing) hits for alot and makes Seal of blood top damage ability. 

So in pvp it just didnt feel normal, I was killing 70s at level 64 just by using a spell damage trinket and seal of blood. It felt to good so i just checked "https://wow.gamepedia.com/Seal_of_Blood" Which does state its not suppose to go off spell damage (Only the judgement), But that might be incorrect and in that case i stand corrected.

**Comment by Felynda** [comment]
Seal of Blood should not scale with spell damage at all . You can find multiple sources of this. Yesterday in arena I got killed by a protection paladin abusing this bug. He was hitting for 300 SoB damage every swing with a blue caster weapon and full tanking gear. Seal of Command is supposed to scale with spell damage and does so properly on the server, don't change that.

In regards of the scaling with attack power from both Blood and Command; They already scale with attack power. Damage is calculated from weapon damage (0.7 command and 0.35 blood) and weapon damage scales with attack power.

**Comment by Devrak** [comment]
Did you have judgement of crusader on upon you because it does and should boost SOB damage ? 
Ps. No offense but did you go to make a coffee or something that a ~200dps tank killed u or is this story a fiction :D

**Comment by Felynda** [comment]
Seal of Blood is supposed to get 0 damage increase from Judgement of the Crusader. If you believe otherwise please cite a source.
About my pvp skills, you go duel a prot pala as a melee class and see how it goes :D

**Comment by Atrecom** [comment]
Okay. let`s take a look on some screenshot.
I dont think i cant crit 3.8k with spell-damage scaling system. AP is everything for SoC as far as 3.8 a-speed weapon.
![97cplxegife](https://user-images.githubusercontent.com/44858756/53550818-b7de6400-3b48-11e9-813b-71cc867be0a0.jpg)

**Comment by Vasalina** [comment]
I already understood it sacled with AP, However if you test it it also scales with spell power which was very insane for world pvp while leveling with a spell dmg trinket. That is all im saying

**Comment by Devrak** [comment]
Nice crit Same with SoB .. with haste beeing the queen :smiley:  leveling is broken for many classes and blizzard was barely able to keep balance for dps classes on top tier... rogues for example with current gear are not strong dps however with sunwell gear they are competetive and there are locks who can do 1k single target dps in green gear. ( offtopic )

**Comment by akrom23** [comment]
@Vasalina @Devrak @Felynda Sanctity Aura should increase damage of SoB?

**Comment by Devrak** [comment]
Yes. 

SoB, SoC, SoR modifiers ( paladin ) Sanct Aura ( 10% )  Sanct Talent ( 2% ) Vengeance Stacks ( 15% )  Crusade ( 3% )( if targets is valid for it ) One-handed specialization ( 5% ) ( when using 1hander )

**Comment by akrom23** [comment]
Vengeane increases physical and holy damage.
So SoB should gain doubled benefits from it?

**Comment by Devrak** [comment]
Yes SoB and SoC get double benefit from it.

**Comment by Devrak** [comment]
To not confuse the double is 1) 15% increased phy damage witch increases weapon damage ( since seals scale of it 2) from 15% increase in holy damage in seals damage calculations.

**Comment by akrom23** [comment]
Okay.

**Comment by Devrak** [comment]
Same applies to Improved Sanct Aura 2% damage bonus / 1 handed specialization 5% damage bonus / buffs like darkmoon fire / Blessing Of Auchinduon  % damage increase and lastly Avenging Wrath ( 30 % )

- any flat ( that affects all damage ) % modifier gives double benefit to SoB , SoC due to it affecting weapon damage first and then seal damage witch is based on weapon damage.

**Comment by Devrak** [comment]
@akrom23 If you have some extra time could you please fix #3464 any raid that has prot and holy paladins run into that issue and since heals are more important prot paladins are forbidden to use sactuary blessing

**Comment by akrom23** [comment]
@Devrak: Done.

**Comment by Devrak** [comment]
@akrom23 tys again from all prot paladins on that one.

**Comment by ghost** [comment]
> 
> 
> 
> 
> Extra: it appears SoCommand is using normalized weapon speed ( 3.3 ) for ppm calculations resulting in way less procs for slow weapons ... it however should use actual weapon speed prior to any haste effects for ppm calculations.

What about this, can anyone confirm or deny?
I have a long term feeling that I get way less procs with my 3.7 than I should. However, it's kinda hard to evaluate on actual fights, and I don't even raid as ret consistently, only few bosses here and there.

**Comment by Devrak** [comment]
Have to look after next server update it might be fixed now :smiley:

**Comment by weebxx** [comment]
Now that u changed that,Seal of Blood doesnt benefit from Judgement of the Crusader.How does that make any sense since SoB tooltip says "deals holy dmg" and Judgement of the Crusader says "increases holy damage"? Ret dps is utter shit atm.

**Comment by sockagg** [comment]
tbh with you all guys: SoB SHOULD NOT scale with spellpower - BUT it SHOULD scale with holy damage increasing spells 100%! If SoB and SoC would not benefit from holy damage increasing spells like Judgement of the Crusader then the "Sanctity Aura"-Skill from the Retribution talent tree would be totally useless and should not be in the game in the first place. 

SoB and SoC should not scale with spellpower - but Judgement of the Crusader and Sanctity Aura need to be an exception. If you take away holy dmg increase from SoB you can also remove the Sanctity Aura Skill from the game whatsoever.

yours sincerely,

a 100% quitting ret paladin if this change will stay in the game like that.

**Comment by akrom23** [comment]
Sanctity works fine.
Judgement of the Crusader needs a fix. Don't make a drama.

**Comment by weebxx** [comment]
Its all good now,thx for the quick fix.

**Comment by Nakadhino** [comment]
Hello,
i would like to open this theme 1 more time. Seal of Blood and Seal of Command are MELEE HOLY HITS. It should ignore armor, (which it does) should scale from spell dmg, (which it doesnt) BUT not 1:1 to spell dmg. The scale should be lower, and ALSO, it should scale melee and spell crit together. 

Hammer of Wrath and Judgement of Command/Blood should count melee + spell crit as well.

Since there are no Target Dummies i cant run tests, i will when they come. 

But if you still have access to old HG database, there its been working how it should, ive been testing it on HG those times. And i have never played another content, so im arguing ONLY from TBC experience, and not confused by another patch.

(the link which someone posted above isnt for tbc seals mechanisms)

as a non-direct prove:

1) check talents in retribution tree called -Santified Seals- its increasing melee and SPELL crit, why would it be here, for Exorcism only?!    ----> http://db.hellfire-tbc.com/?spell=35397
2) Check T6 paladin shoulders, it has socket bonus 4 spell dmg. Of course none cares about 4 spell dmg, but its set on that item for some reason.   ----> http://db.hellfire-tbc.com/?item=30997

Thanks for working : )
