### ISSUE TITLE
Formula : Enchant weapon Fiery weapon 

### ISSUE THREAD

**Issue by Trsko** [SunwellWoW/Sunwell-TBC-Bugtracker#4369]
Description: (BRD)  Pyromance Loregrain does not drop this enchanting formula 
https://db.excalibur.ws/?item=11207

How it works: 
I've killed him 35 times, no drop

How it should work: 
should have to kill him only 4-5 times a few more if unlucky

Source (you should point out proofs of your report, please give us some source): 
Source is DB link and that i've killed him 35 times, wouldnt bother making this unless i knew something was fishy.

**Comment by pinkisnotgay** [comment]
It drops, you're just unlucky. I got it on my 2nd kill. 
Close this

**Comment by Trsko** [comment]
Yeah, when? 2 weeks ago or more? because thats the time it stopped dropping and showing up on AH
