### ISSUE TITLE
Itams dissapear from mailbox

### ISSUE THREAD

**Issue by Stenpackad** [SunwellWoW/Sunwell-TBC-Bugtracker#4373]
While i had around 40 stacks of adamantite ores in mailbox, i bought all mats for 1-350 BS from AH.
When the mailbox was full with all those mats my adamantite ores dissapeared.

**Comment by babno** [comment]
I remember a similar issue from retail. I basically used my mail as extra bank slots, and had pages of mail. I scrolled back a few pages and noticed some of my mail disappeared. It was however still there, but the mail won't display more than like 8 pages. I simply needed to empty my mail of what was there, log out for a few minutes, and when I logged in again the "disappeared" items had returned. Maybe try this?

**Comment by koostosh** [comment]
Mailbox has limit on displaying mails depending heavily on amount of items attached. Delete some mails then relog.
