### ISSUE TITLE
Drums of Battle Range

### ISSUE THREAD

**Issue by bshakex** [SunwellWoW/Sunwell-TBC-Bugtracker#4374]
Description:  
Drums of Battle range is too short. Currently you have to stand almost on top of your party members to receive the buff.

How it works: Drums of Battle only apply to party members if you stand directly on them.

How it should work: Drums of Battle should have a 40 yard range.

Source (you should point out proofs of your report, please give us some source):

**Comment by Jonsbe** [comment]
Also like in 2.4.3 it was instant - thats also one crucial fix to do. Atm its something like 5-8y range. Which sucks.

**Comment by Wojtyas** [comment]
Intended patch change. Will be reverted with 2.3 content.

![image](https://user-images.githubusercontent.com/22802214/53301368-58cfd500-3852-11e9-96e5-aea84ea168a9.png)

**Comment by bshakex** [comment]
Snore
