### ISSUE TITLE
Shadow fiend

### ISSUE THREAD

**Issue by Aftershokx** [SunwellWoW/Sunwell-TBC-Bugtracker#4375]
Description: 
After your last fix mana gaining from shadow fiend comletley broken

How it works: 
Fiend damage formula is fine, but modifier on a gaining mana is like x5 from normal values, 600 fiend damage = 1.8k mana

How it should work: 
The Shadowfiend grants up to 11 hits per use, making its attack speed between 1.26 - 1.36 seconds per hit. It will often only produce 10 attacks because of relocation before the first attack or in between attacks.
with 10 hits, mana gain without additional shadow damage or debuffs is [(10*100)*2.5] = 2500 mana.
The Shadowfiend receives 60-66% of your shadow damage bonus over the 15 second duration depending on 10 to 11 attacks, or 6% per hit for 10 hits. This adds, in optimal conditions, an additional 1.5 mana for 1 shadow spell damage per use.
with 10 hits, [((10*100)+(SDmg*0.6))*2.5] = mana gained.

Source (you should point out proofs of your report, please give us some source): 
https://wowwiki.fandom.com/wiki/Shadowfiend?oldid=1599616

**Comment by mchayes** [comment]
Can confirm it's looking shifty:
![image](https://user-images.githubusercontent.com/20542656/53297950-86068e00-3826-11e9-82df-77ec3eca5990.png)

**Comment by akrom23** [comment]
> Fiend damage formula is fine, but modifier on a gaining mana is like x5 from normal values

> 600 fiend damage = 1.8k mana

Hmm?

**Comment by akrom23** [comment]
My results:
![wowscrnshot_022419_122634](https://user-images.githubusercontent.com/1035215/53298511-6d4ea600-382f-11e9-9f0a-04b4c0cc979b.jpg)
