### ISSUE TITLE
[Dungeon] Mana-Tombs

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#438]
[Normal]

Trash:

- [x] Ethereal Scavenger should have an aggro wipe mechanic.

- [x] Ethereal Priest will sometimes interrupt his Heal cast to use PW:S or Holy Nova.

- [x] Ethereal Darkcaster does not cast Mana Burn. If multiple Darkcasters are attacking same target they will not try to cast additional Shadow Word Pain debuff but wait till the debuff falls off before one of them casts it again while other one does nothing.

- [x] Nexus Terror should be immune to Fear, Root, Banish and Enslave, currently they are vulnerable to those CCs.

- [x] Nexus Stalker missing Dual Wield passive ability (dealing damage with offhand for 50%)

- [x] Ethereal Spellbinders not using Counterspell.

Bosses:

- [x] Pandemonius Dark Shell isnt doing damage to melee attackers and he isnt casting 5 Void Blasts but only 3.

- [x] Tavarok Earthquake isnt ticking 3 times but only 1, missing boss immunities.

- [x] Shadow Lord Xiraxis isnt using his spells/abilities. He is vulnerable to Fear, root and other forms of CC while he should be immune like any other dungeon boss.

[Heroic]

Trash:

- [x] Ethereal Scavenger base damage should be 3534-4998. Should have an aggro wipe mechanic.

- [x] Ethereal Crypt Raider base damage should be 3029-4284.

- [x] Ethereal Sorcerer base damage should be 798-1158. Arcane Missiles should deal 2057 damage.

- [x] Ethereal Priest base damage should be 718-1024. Heal for ~9000 (should be Heal for 16000-18000), his PW:S should be 2x stronger than on Normal version.

- [x] Nexus Terror base damage should be 2700-3700. Should be immune to Fear, Root, Banish and Enslave, currently they are vulnerable to those CCs.
EDIT: Still vulnerable to CCs.

- [x] Ethereal Darkcaster base damage should be 1598-2319. Does not cast Mana Burn (Should burn 2800-3200  mana and deal half damage). If multiple Darkcasters are attacking same target they will not try to cast additional Shadow Word Pain debuff but wait till the debuff falls off before one of them casts it again while other one does nothing.

- [x] Mana Leech base damage should be 1150-2000. 

- [x] Nexus Stalker base damage should be 2500-3500. Missing Dual Wield passive ability.

- [x] Ethereal Theurgist base damage should be 649-942.

- [x] Ethereal Spellbinder base damage should be 762-1106. Not casting Counterspell.

- [x] Ethereal Wrath base damage should be 1900-2500. Shadowbolt Volley should hit betweeen 3000-4000(retail wowhead value?).

Bosses:

- [x] Pandemonius base damage should be ~3500-5600. Dark Shell isnt doing damage to melee attackers and he isnt casting 5 Void Blasts (they should deal way more damage on heroic, wowpedia lists the damage as 5000) but only 3. 
EDIT: Currently he is doing Physical damage instead of Shadow with his autoattack, the rest is fixed.

- [x] Tavarok base damage should be 3920-5544. Earthquake isnt ticking 3 times but only 1 and damage should be 1456, missing boss immunities.

- [x] Nexus-Prince Shaffar base damage should be 3400-4700. Casts Fireball for ~1300 (should be Fireball for 1600-2200), Frostbolt for ~1100-1200 (should be Frostbolt for 1475-1925).

**Comment by Riztazz** [comment]
Pandemonius does reflect damage back to melee attackers but its not shown on the screen (do check combat log) and its intended by blizz

**Comment by Riztazz** [comment]
Please re-test after PTR update
