### ISSUE TITLE
Holy resistance exists and is too high on mobs

### ISSUE THREAD

**Issue by Felynda** [SunwellWoW/Sunwell-TBC-Bugtracker#4381]
Description: 
As stated in title. Holy resistance is too high on mobs. While it should not exist at all. The only holy resist that should exist is level based resist. This should only be eight points per level higher, so for a level 73 boss it would be 24.

taken from: https://wow.gamepedia.com/Holy_resistance

How it works: 
Partial resists occur very frequently much more then it should.

How it should work: 
To illustrate how it should work i made this table:

![image](https://user-images.githubusercontent.com/45050227/53355632-bb47d480-3929-11e9-97b4-f99e75acbf25.png)

using the formulae from: https://wowwiki.fandom.com/wiki/Formulas:Magical_resistance

The 5% versus a level 73 mob would be around 1.25% chance to get a 25% damage reduction. Currently on the server you get much more holy resists. 

Source (you should point out proofs of your report, please give us some source): 
Stated above

**Comment by akrom23** [comment]
@Felynda Please, provide screenshots or clips.

**Comment by Felynda** [comment]
Screenshots from how it works on the server right now?
You should really implement combat dummies or a PTR if you expect proper tests, as has been said many times before. 

I can't go mash a boss with a level one weapon, my guild will get mad.

**Comment by akrom23** [comment]
You reported that the hoy resistance is too high on mobs. Show me a screenshot (from our server) where I can find a holy resist and it's a wrong thing.

**Comment by mchayes** [comment]
1 Mechanar run, paladin tank overview. Blessing of sanctuary full resists and retri aura seem to be the culprit. Perhaps thats what OP means?
![image](https://user-images.githubusercontent.com/20542656/53409401-1ed11100-39c1-11e9-8f0b-3fcabc00c3bb.png)

**Comment by akrom23** [comment]
@Felynda Any news?
