### ISSUE TITLE
SotC should increase CS dmg +40%.

### ISSUE THREAD

**Issue by Lexandros1** [SunwellWoW/Sunwell-TBC-Bugtracker#4382]
Description: Seal of the Crusader doesn't increase Crusader Strike's damage by 40%.

How it works: 
 Crusader Strike does the same amount of damage with or without SoTC active.

How it should work: 
Crusader Strike should do +40% more damage (aka 150% weapon damage instead of the normal 110%) when Seal of the Crusader is active. 

Source (you should point out proofs of your report, please give us some source): 

https://wowwiki.fandom.com/wiki/Patch_2.4.2

**Comment by Devrak** [comment]
Its a modifier .. so 154% wep dmg = wep dmg * 1.1 * 1.4

**Comment by Lexandros1** [comment]
Oh ok. As long as its fixed and works as intended.

**Comment by Lexandros1** [comment]
Oh ok. As long as its fixed and works as intended.

**Comment by Lexandros1** [comment]
Why was this report closed?

**Comment by akrom23** [comment]
What about that?
https://www.wowhead.com/forums&topic=36917#p348571

http://www.clanyawa.com/viewtopic.php?t=3363

> In 2.4.2, Seal of the Crusader no longer reduces Crusader Strike's damage.

It seems that only the "damage reduction" part of SoTC should not work with Crusader Strike.

**Comment by Devrak** [comment]
Yes it can be that, would not be the first case where blizzard says one but does the other.
