### ISSUE TITLE
[Rogue]Deadly throw never triggers ruthlessness 

### ISSUE THREAD

**Issue by rmit-s3581619-zengjun-zhang** [SunwellWoW/Sunwell-TBC-Bugtracker#4383]
Description: 
Deadly throw cannot add combo point from having ruthlessness.

How it works: 
1.Rogues have Ruthlessness talents in assassination.
2.Gain some combo points and cast deadly throw.
3. This finishing move never add a combo point to the target.

How it should work: 
Has a chance(60% when has3/3 ruthlessness) to add a combo point to the target

Source (you should point out proofs of your report, please give us some source):

**Comment by kinglobster** [comment]
working as it should
https://wowwiki.fandom.com/wiki/Ruthlessness_(rogue_talent)
