### ISSUE TITLE
Shadowmeld #Urgent #Pvp #Critical #Pve

### ISSUE THREAD

**Issue by crushzx** [SunwellWoW/Sunwell-TBC-Bugtracker#4385]
Description: 
"Activate to slip into the shadows, reducing the chance for enemies to detect your presence. Lasts until cancelled or upon moving. Any threat is restored versus enemies still in combat upon cancellation of this effect."

How it works: 
Can't be activated while in combat ; Doesn't get you out of combat !

How it should work: 

It has a cooldown of 3 minutes, and it can be used in combat. In PvP it will force enemies targeting you to detarget you. Using shadowmeld should temporarily remove you from combat. When you cancel the effect, all aggro that was held towards you is restored if you are still close to hostile mobs.
Rogues and Druids can use it to  re-stealth. 

Source (you should point out proofs of your report, please give us some source): 

https://wowwiki.fandom.com/wiki/Shadowmeld

**Comment by crushzx** [comment]
This is the only usefull alliance ability, we all know how unbalanced tbc is and the server is (horde / alliance ratios) this is why it's a critical bug you guys need to fix !

Thanks for your time and consideration !

**Comment by ruineroffun** [comment]
Welcome to TBC mate, cant be used in combat. Usable in combat part came in wrath of the lich king.
