### ISSUE TITLE
Steadyshot and Hunter's Mark

### ISSUE THREAD

**Issue by Lorious** [SunwellWoW/Sunwell-TBC-Bugtracker#4388]
Description: 
Found this statement on discord.

"#1457 by Anakin
Spell: Ranged spells should gain benefits from Attack Power bonuses (fix Hunter's Mark)"

Can't find the original thread in here so I'm making a new post.

Anyways, something seems off since my autoshots hits harder than my steadyshots does. Especially when Hunter's mark is fully stacked. So this is more of a question, are you sure this is fixed or does "Ranged spells" refer to something other than steady/aimedshots?

How it works: 
Above

How it should work: 
Imho, steadyshot should on average do more dmg per shot.

Source (you should point out proofs of your report, please give us some source): 
There are logs and vods but this is more of a question for developers since it should have been fixed already(?)

**Comment by akrom23** [comment]
Steady Shot get 20% of this aura. Auto shot - bases on your ranged ap.

**Comment by firngrod** [comment]
There's an interesting part in this wiki-article from the time:
https://wow.gamepedia.com/index.php?title=Steady_Shot&oldid=1580415
>    The tooltip is proven to be wrong and the following is the best player-derived formula so far with data taken from
    Formula: DamagePercentageBonus*RangedWeaponSpecialization*(150 + WeaponDamage/WeaponSpeed*2.8 + 0.2*RAP + [Dazed: 175])

My question here is whether WeaponDamage is Attack Damage factoring RAP or damage contribution solely from the weapon itself.  This, I do not know.

**Comment by akrom23** [comment]
We have the same formula for Steady Shot.
As I said: Steady Shot takes only 20% from RAP. - that's why auto shot hits harder.
