### ISSUE TITLE
[Warlock] Imp mana pool issue

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#439]
Decription: Imp has smaller mana pool than he should have.

How it works: Wrong calculation for Imp mana pool from stats 
![image](https://user-images.githubusercontent.com/42102450/45810767-b3756b80-bccb-11e8-88d3-bec19db08c8c.png)

How it should work: Should have way higher mana pool, Imp should have the highest intelligence stat out of all warlock pets and the highest mana pool and mana regen.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented (only SSC realm so far).

![image](https://user-images.githubusercontent.com/22802214/48985876-29071900-f10d-11e8-9bd7-2d27bdce646b.png)
