### ISSUE TITLE
[Item] Archmage Vargoth's Staff

### ISSUE THREAD

**Issue by neheri** [SunwellWoW/Sunwell-TBC-Bugtracker#4390]
Description: If you lose it NPC in netherstorm named Ravandwyr should restore it. I deleted the staff and he doesn't do anything.

How it works: You can't restore staff if you removed the staff and continue quests.

How it should work: Ravandwyr should offer to restore Archmage Vargoth's Staff if you lose it.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=28455/archmage-vargoths-staff#comments
https://www.wowhead.com/npc=19217/ravandwyr#comments

**Comment by neheri** [comment]
I am afraid it's still not working. Still can't get the staff back:

Bank:
![wowscrnshot_022819_172623](https://user-images.githubusercontent.com/37372869/53582373-9fd60700-3b7f-11e9-96ba-da8da28f17c0.jpg)



Inventory:
![wowscrnshot_022819_172656](https://user-images.githubusercontent.com/37372869/53582333-8df46400-3b7f-11e9-8287-612f46623dcd.jpg)

NPC:
![wowscrnshot_022819_173646](https://user-images.githubusercontent.com/37372869/53582393-abc1c900-3b7f-11e9-9f6a-069347eb2d77.jpg)

Quest:

![wowscrnshot_022819_173655](https://user-images.githubusercontent.com/37372869/53582397-af555000-3b7f-11e9-8263-2854e57fcf16.jpg)

**Comment by Wojtyas** [comment]
Roger.

**Comment by neheri** [comment]
Works, thanks
