### ISSUE TITLE
Fishing pools

### ISSUE THREAD

**Issue by flapse32** [SunwellWoW/Sunwell-TBC-Bugtracker#4391]
Description: Fishing catch

How it works: 90% of the time you have to wait to there is 2 sec left and then you catch something.

How it should work: Should be randomized alot more than it is atm.

Source (you should point out proofs of your report, please give us some source):

**Comment by flapse32** [comment]
it seems like there is only 3 times where u can be able to catch it, one after 5 sec, one after 15 sec, one after 25 sec. Surely there should be more points where you can be able to catch it.

Eitherway, the one after 25 sec is happening 90% of the time. This really has to be looked into. 

Also: 
![image](https://user-images.githubusercontent.com/46076151/53519051-a9556580-3ad2-11e9-93fb-a0f2dfe701c0.png)


source: https://wow.gamepedia.com/Fishing


Right now fishing has a 27 second channeling and not 21.

And it says you will have 3-4 seconds to right click before it cancel the channeling.
On this server you have 2-3 seconds. small things, but still useful to fix stuff like this.

**Comment by firngrod** [comment]
As always, it's recommended to look at the wiki article as it was at the time when BC was live:
https://wow.gamepedia.com/index.php?title=Fishing&oldid=1618428

In this case, the information is more or less the same, but still...

**Comment by flapse32** [comment]
Ty, could not find it myself. Eitherway so 22 seconds instead of 27 seconds then.
And 3-4 seconds to pick it up instead of 2-3 seconds. 

Also to point out : 1) At 11.0 – 10.0 seconds remaining. 2) At 6.0 – 5.0 seconds remaining. 3) At 1.1 seconds remaining.
My guess on these is that: 30% of the casts it will be at 11.0 – 10.0 seconds. 30% of the casts it will be at 6.0 – 5.0 seconds. 40% of the casts it will be at 1.1 seconds.

Quote from: https://wow.gamepedia.com/index.php?title=Fishing&oldid=1618428

I dont think the 30% chance is correct on this server. I think its more like 30% 11-10 seconds. 20% 6-5 seconds and 50% at 1.1 seconds remaining

**Comment by koostosh** [comment]
As of pre 2.1 mechanic fishing should be ~27-30 seconds long.
There is 5 seconds time to pick up. (Except when fish hooked 3 seconds before cast ended).
Chances for each possible duration is equal.
