### ISSUE TITLE
[Quest][NPC] Only One may Rise 

### ISSUE THREAD

**Issue by pinkisnotgay** [SunwellWoW/Sunwell-TBC-Bugtracker#4393]
Refering to the https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4152

Issue is supposedly fixed, but the quest is not there.

**Comment by Wojtyas** [comment]
It is blocked in purpose ;) We will provide entire Scarab Lord chain-quest in 2.1 content.
