### ISSUE TITLE
[Hyjal] Portals

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#4399]
At this moment people can enter every portal whenever they want which is BAD hehe.

- [x] Alliance portal (1) should be able to enter since beginning - correct.
- [x] Horde portal (2) should be able to enter after Anetheron is dead (talk with Jaina after should turn on portal).
- [x] Night Elf portal (3) should be able to enter after Azgalor is dead (talk with Thrall after should turn on portal).

![image](https://user-images.githubusercontent.com/22802214/53587335-5d65f780-3b8a-11e9-83c2-621720b931b1.png)

**Comment by Demolla** [comment]
After defeating the two bosses in the human base, the second portal opens up and permits direct access to the Horde camp. After killing two more bosses there, the third gate opens.

So Night Elf portal - should be able to enter after Azgalor is dead, not Kaz'rogal

> 
> 
> At this moment people can enter every portal whenever they want which is BAD hehe.
> 
>     * [x]  Alliance portal (1) should be able to enter since beginning - correct.
> 
>     * [ ]  Horde portal (2) should be able to enter after Anetheron is dead (talk with Jaina after should turn on portal).
> 
>     * [ ]  Night Elf portal (3) should be able to enter after Kaz'rogal is dead (talk with Thrall after should turn on portal).
> 
> 
> ![image](https://user-images.githubusercontent.com/22802214/53587335-5d65f780-3b8a-11e9-83c2-621720b931b1.png)
