### ISSUE TITLE
[Warlock] Succubus Seduction spell

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#440]
Decription: Seduction channel breaks off after 2-3 seconds and when you try casting outside range it gives you "Your pet is out of range" error.

How it works: 

How it should work: Seduction channel should last full duration unless succubus is silenced/stunned/CCed, when you try casting Seduction out of range Succubus should move into range and cast it.

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/304
