### ISSUE TITLE
Fist xmog weapons

### ISSUE THREAD

**Issue by Szelmon556** [SunwellWoW/Sunwell-TBC-Bugtracker#4400]
Description: So actually u can transmog your main weapon into main&onehand weapon, but weapon on offhand slot if u have equipped onehand u cannot transmog into offhand weapon, only into main or one hand (offhand weapons can be xmog only into offhand weapons). Honestly idk how it should work, but for sure mainhand shouldn't xmog into offhand(in meaning of fists weapons) cuz we got something like this (pic). Any chance to fix it and there will be possibility to xmog onehand weapon(on offhand slot) into offhand weapon like fist or dagger?

![wowscrnshot_022819_192424](https://user-images.githubusercontent.com/17564505/53589127-d5ceb780-3b8e-11e9-95d6-8561da87fed1.jpg)
![wowscrnshot_022819_192430](https://user-images.githubusercontent.com/17564505/53589129-d5ceb780-3b8e-11e9-94de-ca9ea0377402.jpg)

**Comment by Ironjudgment** [comment]
This is TBC bugtracker.

**Comment by Szelmon556** [comment]
damn lulw imma blind xD soz
