### ISSUE TITLE
Rogue 41 point talent Surprise attacks

### ISSUE THREAD

**Issue by Feorblade** [SunwellWoW/Sunwell-TBC-Bugtracker#4402]
Description: 

There was a bug tracker post saying you fixed the rogue 41 point combat talent. It isn't fixed

How it works: 

Finishing moves are still being dodged.

How it should work: 

They shouldn't be able to be dodged.

Source (you should point out proofs of your report, please give us some source): 

https://i.imgur.com/OIYO8GU.jpg here you go I've been playing with this bugged fucking talent since server release, would really enjoy to having a functioning talent

**Comment by lordazurescens** [comment]
Talent is still broken i get dodges on finishers in raid all the time.
