### ISSUE TITLE
[Serpentshrine Cavern] Lurker adds cannot be attacked

### ISSUE THREAD

**Issue by balo-git** [SunwellWoW/Sunwell-TBC-Bugtracker#4403]
Description: 
Sometimes adds on the Lurker below fight are unable to be attacked.

How it works: 
During our attempt on of the adds on in the Lurker Below fight did not completely move into position. It stopped early in the water and began attacking us. We were not able to attack it, we received the error messages:
"Invalid target"
"Cannot attack that target"

I placed a hunter trap inside the add and the trap remained there, it did not trigger.

We had traps down before the adds spawned, the first add phase had no issue. But during second add phase one add bugged out. Refer to the video linked below.

It's possible it's related to traps somehow. But the trap that was meant for the add that bugged out was never triggered (but maybe the add believed it had been engaged by the trap and immediately stopped to fight? I'm just tossing ideas out)

We were able to kill Lurker regardless, the bugged add just got healing aggro and began shooting healers.

How it should work: 
Adds should move into position and be able to be attacked/trapped.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=oL_SNvczEEs

**Comment by neheri** [comment]
I can confirm, one of the Coilfang Ambushers went into the water and couldn't be attacked entire fight. We had to kill Lurker with 1 add alive shooting the raid entire encounter.

**Comment by arkatik** [comment]
Yesterday the same thing happened.
I wrote a ticket about what is happening.
Game master read the ticket, but did not come to the rescue and did not answer.
We killed along with the one active mob.

**Comment by babno** [comment]
![image](https://user-images.githubusercontent.com/244626/53702330-c2605e00-3dd3-11e9-999d-f80fc6a4c790.png)
From a few minutes ago. Adds are swimming around. They shouldn't swim once they get the platforms, just stay there and range attack people. If they're feared then they shouldn't leave platform either.

**Comment by babno** [comment]
Now his spout is fucked up, he doesn't rotate at all, but occasionally he will instantly turn 180 degrees for just half a second and then instantly go back.
