### ISSUE TITLE
arcane shot damage and dispel order reversed. 

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#4409]
How it works: Arcane shot dispels and then does damage.

How it should work: It should deal its damage first and then dispel. this is relevant for things like damage reduction effects, absorption effects, blessing of sacrifice, etc. 

Source (you should point out proofs of your report, please give us some source): 
https://tbc-twinhead.twinstar.cz/?spell=27019

**Comment by akrom23** [comment]
```
Effect #1 | (38) Dispel (1)
Effect #2 | (2) School Damage (Physical, Fire, Frost)
```

The first effect is dispel, not damage.
More proofs, please.

**Comment by babno** [comment]
Hard to find stuff for it since it was live for so short a time before blizz realized their mistake and reverted it. Maybe it's using stack logic there, first in last out? Best I can find is https://wowwiki.fandom.com/wiki/Patch_2.3.0
"Arcane Shot (Ranks 6 and above) now dispel 1 Magic effect in addition to their normal damage." the language suggests the dispel was added on after the damage, where as they would have said it "dispels and then deals damage" were it the other way around.

**Comment by akrom23** [comment]
This is not a proof at all.

**Comment by babno** [comment]
twinstar does use stack logic. For example immolate, obviously does upfront fire school damage and then the periodic damage. And if we look at immolate on twinstar https://www.wowhead.com/spell=44267/immolate


Effect #1 | Apply Aura: Periodic DamageValue: 2 every 3 seconds (SP mod: 0.13)

Effect #2 | School Damage (Fire)Value: 8 (SP mod: 0.2)

Effect #2 in both these spells happens first.

**Comment by akrom23** [comment]
@babno Because Periodic damage is done after 2 sec and it's an aura...

**Comment by babno** [comment]
If the initial damage is resisted then no dot aura will be applied. Always. However the dot can be resisted even if the initial damage happens. Initial damage happens first then the aura. Effect 2 happens then effect 1.

**Comment by babno** [comment]
Moonfire, another example where the initial damage happens first and then the dot. https://tbc-twinhead.twinstar.cz/?spell=8921 again effect 1 happens after effect 2 on twinhead.

**Comment by akrom23** [comment]
And again - Dot is an aura and yes - is applied before the initial damage. Damage from DoT is done after specific amount of time.
Effects are always applied in order in which they are given in game files.

Just give me a proof that Arcane Shot damage should be done before the dispel - otherwise I'll close it.

**Comment by babno** [comment]
What you're saying makes no sense. For what you're saying to be true, the following would happen in the case of resist.
Immolate dot applied to target, immolate damage resisted by target, check for resist and then retroactively remove the dot.

I'm guessing you don't know what the stack is, so I will explain it. You have tasks on papers you need to do. First to account for them all, you put them down into a stack. First you put down effect 1-dispel. Next ontop of that you put down effect 2-damage. Now you have everything you need to do on the stack. So you take the top item of the stack off and do it, which is effect 2-damage, and that is the first thing that gets done.

This is order logic is extremely common in programming. So the human documentation (the tooltip) has damage first, and according to the you the game files, the programming documentation, also damage first according to stack logic.

**Comment by akrom23** [comment]
You are completely wrong and don't understand what I'm trying to explain. This is how it works and it works just fine.
You didn't provide any proofs about the bug described here.
