### ISSUE TITLE
[Dungeon] Auchenai Crypts

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#441]
[Normal]

Trash:

NOTE: Non-elite packs of patrols that spawn and walk from one point to another are not doing their thing, multiple packs are all grouped up together on a huge pile of bones doing nothing. Phasing Stalker and all others that are named Phasing X belong to these spawn patrol packs. They should patrol the entire dungeon from start to end.

- Auchenai Necromancer Will randomly interrupt his spells to cast other ones, doesnt cast Seed of Corruption. When engaged should yell one of his lines (at start of dungeon there is one Auchenai Necromancer that doesnt belong there).

NOTE: When you pull one from the Auchenai groups/packs the one who is attacked first should summon one of the non-elite mobs to help him (which currently happens), however when you attack other elite mobs that are part of that pack they do not summon one of the non-elites to help them, only time they do that is if they are pulled first but then the other elites in pack do not summon their non-elite. Non-elite should be summoned even if you use CCs such as sheep/fear/trap on elites in pack, only time they shouldnt summon a non-elite is when a priest Mind Controls them but they summon a non-elite after Mind Control ends.  Some packs summon their non-elites to help but they arent aggroing anyone they just stand still (they should attack same target as the elite that summoned them).

- Phantasmal Possessor Possess ability doesnt work. Should be immune to all CCs.

- Auchenai Monk Currently vulnerable to CCs, should be immune to all CCs.

- Auchenai Soul-Priest not using Falter ability.

- Raging Soul this mob is missing from dungeon. They should be on Bridge of Souls invisible, when players walk on bridge they should appear and start casting Rage at once, if completed it will destroy the casting Raging Soul and do a big knockback to nearby enemies (it can knock off players over the bridge into the abyss). They should have a 5 minute respawn timer so players cannot waste time on bridge.

- Angered Skeleton does not use Infuriate ability (every time someone does a critical on them they should use it). Should reset/drop aggro every few seconds.

- Raging Skeleton Should reset/drop aggro every few seconds.

Bosses:

- Shirrak the Dead Watcher does not use Focus Fire ability (which targets a players location and pulses barrage of fire damage every second)

- Exarch Maladaar When Stolen Soul unit is killed the debuff is not removed.
Avatar of the Martyred Does not use Sunder Armor ability.

[Heroic]

Trash:

- Auchenai Necromancer base damage should be 1050-1400. Same problem as on normal with spells being interrupted, doesnt cast Seed of Corruption (should be Seed of Corruption for 3000 over 18s and 2495 explosion).

- Auchenai Vindicator base damage should be 1625-2375. Shadow Shock is hitting for ~900 (should be Shadow Shock for 2900-4000).

- Auchenai Monk base damage should be 1800-2500. Should be immune to CCs. 

- Auchenai Soul-Priest base damage should be 950-1350. Not using Falter ability.

- Phantasmal Possessor base damage should be 925-1200.

- Unliving Soldier base damage should be 1350-2000.

- Unliving Cleric base damage should be 550-800.

- Unliving Sorcerer base damage should be 900-1100.  

- Unliving Stalker base damage should be 1000-1450.

Phasing Clerics/Stalkers/Sorcerers/Soldiers have same stats as Unliving versions.

- Raging Soul missing from heroic aswell.

- Angered Skeleton base damage should be 1600-2250. Does not use Infuriate ability (every time someone does a critical on them they should use it). Should reset/drop aggro every few seconds.

- Raging Skeleton base damage should be 1600-2400. Should reset/drop aggro every few seconds.

- Reanimated Bones base damage should be 825-1070.

- Stolen Soul base damage should be 1300-2100. Should use max rank abilities/spells of targeted player.

Bosses: 

- Shirrak the Dead Watcher base damage should be 3156-3767. Does not use Focus Fire ability (should deal 3750-3850 per pulse).

- Exarch Maladaar base damage should be 2900-4000.  When Stolen Soul unit is killed the debuff is not removed.
Avatar of the Martyred base damage should be 3300-4600. Does not use Sunder Armor ability.

**Comment by Riztazz** [comment]
resolved, i will let you know when PTR is updated
