### ISSUE TITLE
Rivenspike Proc Rate Too Low

### ISSUE THREAD

**Issue by YoshGit** [SunwellWoW/Sunwell-TBC-Bugtracker#4411]
Description: 
Item Rivenspike's proc rate feels lower than it should be.

How it works: 
Rivenspike stacks are falling off often before reaching maximum stacks.

How it should work: 
I recall that in the past it was very easy to apply and maintain max stacks on a target. No hard evidence as I haven't tested this extensively, but #4407 reminded me that the proc rate felt off. The proc rate should be approximate to Annihilator (or higher if PPM based since the weapon is slower).

Source (you should point out proofs of your report, please give us some source): 
Like #4407 its hard to find hard evidence, but past experience and comments lead me to believe the proc rate is lower than it should be.

Wowhead comment from patch 6.2 "Nerfed, along with Bashguuder **(which had a rather high proc rate)**, sometime around the August 5th hotfixes in 6.2 to no longer proc (at least in raids?). Prior to this, it was a rather large boon to physical damage (since current raid bosses appear to have rather low armor). Ironically, however, Arms warriors in Mythic don't see usage due to their ridiculous uptime on Colossus Smash, anyway."

**Comment by pinkisnotgay** [comment]
Just get an Annihilator )))
