### ISSUE TITLE
Rogue Fleet footed Talent not giving 15% movment.

### ISSUE THREAD

**Issue by lordazurescens** [SunwellWoW/Sunwell-TBC-Bugtracker#4413]
Description: 
Talent is not giving correct movement speed gain.

How it works: seems to be giving 10% instead of 15%. I've tested with a paladin on follow. i dunno if its a bug with boot speed enchant i tried with and without. both seemed to stay around 10% paladin would eventually outpace me with pursuit.

How it should work: 
should give you 15% movement speed when not mounted.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
I've tested it with new rogue. First point in this talent adds +8% movement speed, and second +15%. There are no additional modifiers for this spell set, so it should use base value of 15 always. Maybe your test was affected by something else, like mentioned boot enchant, but I've also tested it with boots enchant and it seemed normal.

**Comment by Devrak** [comment]
paladin had only 2 TP in pursuit ? cus its 5%/10%/15% or by chance its run speed meta and that bugs it out ?

**Comment by lordazurescens** [comment]
tested again. seems to be fine. 

maybe i was just having a latency issue or it was a terrain thing. 
Sorry for the false alarm
