### ISSUE TITLE
[Instance] Heroic kargath bladefist bugs

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#4414]
Firstly, the stealthed assassins spawn too quickly and also will just randomly pull. Half our attempts we ended up pulling them with us because someone was .2 seconds behind the tank in moving. We also noticed several times they seemed to get pulled by the non elite adds that spawn and run into the fight. There's zero chance that we pulled them as we were all on the southern stairs and the assassins from the northern pulled (running right alongside a non elite add).

Secondly his blade dance he is targeted people and can target the same person repeatedly and just sit on them until dead. 
![image](https://user-images.githubusercontent.com/244626/53676603-caed5300-3c72-11e9-9560-321bc4d48b32.png)

He should target certain places, whether or not there is anyone there, and choose a different place every time. Rarely should anyone be hit enough times to kill them outright like the picture above, and never 4 times in a row in 3 seconds. 
https://www.youtube.com/watch?v=ePWMgi-o7uw

**Comment by Crome666** [comment]
still same problem not killable

**Comment by Crome666** [comment]
pls update it to live

**Comment by iluminatix** [comment]
still super buffed, 10k damage to 2-4 group members within 2-3 secs is really too much to heal, we where even there with 2 healers, a well geared group, like full t4 and some t5 items, and still it just rapes with no breaks.... with this state it is actively preventing guilds from attuning to TK... rip #golfclap #poggers - put on high prio, its game breaking for guilds not to be able to progress....

**Comment by iluminatix** [comment]
its not something that can wait several raid resets tbh, giving the guilds who have attunements an unfair advantadge, other cant catch up with no attunement posible

**Comment by babno** [comment]
While still bugged it is doable. 2-4 members taking damage sounds like you're grouping up for corner strat or something. That does not work. You have to spread. It's highly likely he'll just sit on 1 person and try to kill them, and you have to build your group around that. The group I killed with was a warlock, boomkin, resto druid, ele shaman, and protadin. One spin he killed the resto another spin he killed the warlock but both got up with SS and rebirth. The shaman was targeted once as well but could heal him through it because he had higher armor and hp. So you either have to go high armor and burst healing, or soulstones and rebirths.

**Comment by Jonsse** [comment]
Not fixed, should I make another report or continue this?

**Comment by iluminatix** [comment]
even if that is true babno, its not supose to be like this. and no we where not stacking, we tried 6-7 times different ways, and two geared healers couldnt heal through it, glad you got lucky tho, grats

**Comment by babno** [comment]
@iluminatix read the first 3 words of my previous reply. I offered a work around for the bug for people who want to do tk rather than piss and moan.
