### ISSUE TITLE
enslave demon, when feared you directly control demon

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#4415]
If, while enslaving a demon, the warlock is feared (possibly other cc effects as well) then you start directly controlling the demon, similar to the hunter ability eyes of the beast. You can't revert to controlling your character, and even if you die you will continue controlling the demon. If you are resurrected you cannot accept it and the release button goes away as well.

**Comment by Jeansapin** [comment]
It's pretty much the same will all controls that aren't stuns (disorient/fears etc) ...

It's really annoying, if you could fix it asap ...

**Comment by koostosh** [comment]
Does this happen often? I tested it for a while and could not reproduce.

**Comment by babno** [comment]
Happens whenever the warlock is feared pretty consistently for me. I'd say an easy place to test would be arcatraz, enslave one of the screamers and then stand next to the other until it fears you.

**Comment by koostosh** [comment]
This was caused when demon was feared, not warlock. That's why i could not reproduce it.
