### ISSUE TITLE
Issue with crit rating on items or gems. possible large issue.

### ISSUE THREAD

**Issue by lordazurescens** [SunwellWoW/Sunwell-TBC-Bugtracker#4416]
Description: noticed something weird today. switching between gloves. Don't know if its an issue with the paperdoll crit rating, or if its an issue with gem scaling or the items i'm equipping.

How it works: I should gain crit when i equip t4 gloves over flowing thought. but instead i lose crit. pictures below.
crit 27.85
![image](https://user-images.githubusercontent.com/45920509/53690288-aa3a0180-3d35-11e9-92d7-19b60c7257d1.png)

crit 27.74
![image](https://user-images.githubusercontent.com/45920509/53690299-da81a000-3d35-11e9-9596-5550383917a2.png)

i should be gaining 5int + 10crit rating. instead i lose crit quite a good bit of it too.

**Comment by akrom23** [comment]
@lordazurescens What about meta gem in head?

**Comment by lordazurescens** [comment]
its a spell crit meta. i didn't switch the head slot though.

**Comment by akrom23** [comment]
But you're losing a red and blue gem - that's why your meta gem might stop working.
