### ISSUE TITLE
Inner Fire Priest

### ISSUE THREAD

**Issue by darknessangelo** [SunwellWoW/Sunwell-TBC-Bugtracker#4418]
Description: 
When you get hit, stacks dont decrease.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by lak14wto** [comment]
Stacks did decrease properly when you are not shielded, but did not decrease when damage is not taken to shield.. which is how it should be. Now they implemented a change where it decreases even if you are shielded, which is not according to other tbc servers or retail.

**Comment by Freshbtw** [comment]
Stacks indeed should not decrease while shielded.. please stop Breaking stuff that worked in the past..
