### ISSUE TITLE
[Item] Rod of the Sun King 

### ISSUE THREAD

**Issue by Nimo91** [SunwellWoW/Sunwell-TBC-Bugtracker#4423]
Description: Rod of the Sun King (one-handed, 2.7speed mace that drops from KT in Tempest Keep) proc rate is too low, making the weapon weaker/nerfed compared to the t5 weapon equivalents, and taken into account that it drops from the hardest boss encounter t5 has to offer (if scripted retail-like).

How it works: After hitting nagrand bulls/elementals and occasional aliance players for a couple of hours while farming with only the mace equipped in my slot 16 (main hand), ive made a total of 1058 attacks (white/hemo/evis/ghostly), resulting in a total of 39 energy procs or 390 energy gained total. 
https://snag.gy/3sQCVD.jpg
https://snag.gy/pPswe5.jpg
This means the pph of the weapon is around 3.68% in this round of testing.
I could expand the hitpool so the sample size is larger and arguably more representative.

How it should work: Proc rate should most likely be higher than 3.68%. 

Source (you should point out proofs of your report, please give us some source): 
I can't find a reliable source of what the proc on retail actually was.. What i did find tho is: 
http://forum.warmane.com/showthread.php?t=368065 - a guy claiming pph is 5%, yet its simply a comment with no actual proofs.
https://www.wowhead.com/item=29996/rod-of-the-sun-king#comments - couple of comments stating its 27% or 6ppm which is probably ridiculously high.
One of the comment's stating its around 2.5% (a guy probably tested it while dual-wielding).

I also found couple of videos i could provide a link for, from a rogue's PoV on retail (a guy mentioned in the first comment of wowhead forum - Zkygge - UD rogue from Curse} having that mace equipped with a visible combat log and energy gains for a couple of boss fights. Would be quite of work to determine amount of possible energyproc hits and actual energy gains, but im pretty sure some legitimate data could be extrapolated from those videos if it was to be done properly.

I'd appreciate if someone who has access to the PTR could check the PPH on a targetdummy, im a bit tired of hitting bulls without an offhand. Talking PPM about this is ofcourse pointless as it has no ICD and special attacks can proc it hence buffing that PPM artificially, aswell as hasting effects. 
Also worth checking out how it interacts with offhand swordspec proccing the mace and could it still proc, aswell as, does the proc effect gets upped upon bladeflurrying multiple targets. Note that i only tested this in sub/pvp spec on level ~65 mobs

**Comment by bucher444** [comment]
out of 925 strikes, proc 36 times for me, which is 3.89%

**Comment by Nimo91** [comment]
Fixed to which value if i may ask? So i can confirm/deny your fix?

**Comment by Nimo91** [comment]
this "fix" might have broken the relentless strikes talent. Now, on occasions, it procs twice (giving 2x25 energy at once). Also from the latest round of testing i did 705 hits, got 19 procs, making it have 2.69% chance to proc.

**Comment by Wojtyas** [comment]
Not sure if it was already implemented. Feel free to comment - I will reopen ticket if needed.

**Comment by Nimo91** [comment]
Hi, i am commenting on this as it had been implemented and the mace proc chance is even worse than before. not sure if u unintentionally disregarded my previous comment but i got total of 2.69% on my last ru of testing, and on any further im not passing past 3% mark.
Now on top of that, the talent relentless strikes got broken and is proccing twice as much energy on occasions (getting 2x25 energy) resulting in overall energy for rogues being amped and mace energy gain being nerfed (only on the rogues who have the mace obviously).
Thanks for reviewing this once again, i hope this gets fixed soon.
