### ISSUE TITLE
[Hunter?] Another action is in progress

### ISSUE THREAD

**Issue by balo-git** [SunwellWoW/Sunwell-TBC-Bugtracker#4427]
Description: 
Occasionally I become unable to use any abilities at all when engaged with an enemy. This happens with both NPC (PvE) targets as well as player (PvP) targets.

How it works:
Videos on source section below.

Engage a target alongside my pet, sometimes, with no discernible pattern I become unable to use any abilities and any attempt to use abilities generates the error message: "Another action is in progress"

This applies to ranged abilities (shots), traps, feign death, probably everything but I have not tested thoroughly.

Sometimes I am able to clear the issue by mashing escape until the menu appears. Other times I have to wait until the mob/player I am engaging dies, exits combat or leaves rendering distance.

I have never experienced this issue when I did not have my pet present. But since my pet is alongside me most of the time that isn't necessarily the problem. Pulling my pet off the target does not remedy the situation.

It's possible the issue is started by some kind of macro interaction with my pet's kill command macros, but once the issue occurs even trying to click spells directly from my spellbook fails to work (as shown in the first clip below). It might not be related to macros at all, I'm just tossing out ideas.

A friend of mine made a hunter alt and told me today he ran into the same issue. This happened about a week after I gave him my steady shot macro, which is why I mention it as potential cause.

How it should work: 
Abilities shouldn't lock up.

Source (you should point out proofs of your report, please give us some source): 
In the first clip I open my spellbook to see if casting from it directly would work. It doesn't
https://www.youtube.com/watch?v=QRHDK-GZUzc

In the second video I manage to fix the error my mashing Escape until the game menu appears, this fixed the issue. This does not always fix it, but often it does.
https://www.youtube.com/watch?v=ez_xxDca1ko

**Comment by balo-git** [comment]
#showtooltip Steady Shot
/console Sound_EnableSFX 0
/script UIErrorsFrame:Hide()
/cast !Auto Shot
/cast [exists, target=pettarget] Kill Command
/cast Steady Shot
/console Sound_EnableSFX 1
/script UIErrorsFrame:Clear() UIErrorsFrame:Show()

**Comment by balo-git** [comment]
Still happening, will upload after raid.

**Comment by Afgann** [comment]
There was no update probably @balo-git.

**Comment by balo-git** [comment]
Had this happen again yesterday. Is the fix deployed? I see nothing explicitly referencing this issue in the changelog-tbc channel of the discord.
