### ISSUE TITLE
[Serpentshrine Cavern] Lady Vashj encounter breaks in phase 2

### ISSUE THREAD

**Issue by leafwork** [SunwellWoW/Sunwell-TBC-Bugtracker#4428]
Description: 
Lady Vashj encounter broke in phase 2.

How it works: 
After getting 2/4 generators down, everything stopped spawning, so we were unable to continue the encounter. Lady Vashj was still immune. Video linked.

How it should work: 
Elementals/nagas/striders should continue to spawn until the end of phase 2.

Source (you should point out proofs of your report, please give us some source): 
Video: https://youtu.be/9brqT7lCzeg

**Comment by ruineroffun** [comment]
When tank dies, it bugs the bosses for some reason. Your other warr tank died and fairly sure that was the reason Vashj bugged. Seen same happen in many t5 encounters mainly Vashj, Al'ar and Kaelthas.

**Comment by leafwork** [comment]
We've seen Leotheras bug out after killing the warlock tank during the split. I assume this is the same bug.
