### ISSUE TITLE
[dungeon] scarlet monestary

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#443]
graveyard-good

- [x] library - houndmaster loksey stands still and doesn't target or attack for ~5 seconds after engaging even if he has been damaged https://imgur.com/a/XDNv4Vp

- [x] armory - herod doesn't use his whirlwind ability https://vanilla-twinhead.twinstar.cz/?npc=3975#abilities

- [x] cathedral - not all trash is linked to mograine. https://imgur.com/a/Dy1FDu1
- [x] Whitemane doesn't automatically agro to you when she spawns.

**Comment by Dootz** [comment]
thanks for the report, it will be fixed with next ptr update. I'll check #170 as well, thanks for reminding it.
