### ISSUE TITLE
Prayer of Mending

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#4430]
Description:
Prayer of Mending somoetimes heal somoetimes not and somoetimes disappear too fast

How it works: 
When you use Prayer of Mending on target it heals when player with PoM get damage and heal when target block/ressist/miss damage(or somoetimes just no heal). After first "heal" it jumps to random player within 20y( somoetimes after first heal it dispeared) and same next 3 jumps.  And every heal generate threat to healed target.

How it should work: 
Prayer of Mending. Places a spell on the target that heals them for 0 the next time they take damage. When the heal occurs, Prayer of Mending jumps to a raid member within 20 yards. Jumps up to 5 times and lasts 30sec after each jump.And every heal generate threat to healed target.

Source (you should point out proofs of your report, please give us some source): 

https://tbc-twinhead.twinstar.cz/?spell=41635

**Comment by akrom23** [comment]
@BraterinejBratjanuzaj Got some screenshots with combat log or video?

**Comment by ghost** [comment]
I tryed but i dont have got acces to any tank to do video of it

**Comment by ghost** [comment]
Next i will do video from raid from any boss and i will show yuo recount (it will be on Sunday/Monday)

**Comment by ghost** [comment]
https://youtu.be/-tJKcdhXTAk

**Comment by koostosh** [comment]
I see nothing on that clip.
Closing as duplicate
