### ISSUE TITLE
[Raid/Boss] Naxx 40 Sapphiron

### ISSUE THREAD

**Issue by NeonicSupersonic** [SunwellWoW/Sunwell-TBC-Bugtracker#4432]
Description: 
Sapphiron's Frost Breath ignores los, Ice Tombs dont spawn, making boss unkillable.

How it works: 
Sapphiron's Frost Breath ignores los, Ice Tombs dont spawn, making boss unkillable.

How it should work: 
Ice Tombs allow players to los Frost Breath taking no damage from it.  Players inside Ice Tombs should be immune to Frost Breath. Ice Tombs should break once Frost Breath hits them, freeing tombed players and reseting fight back to p1.

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Sapphiron_(tactics)
After casting three Ice Bolts Sapphiron will emote, "Sapphiron takes in a deep breath..." and begin a seven second Frost Breath cast. At the end of the cast everyone in the entire room within line of sight of Sapphiron will be hit for 112,500 to 187,500 Frost damage. To avoid this, just hide behind the ice blocks. Following this Sapphiron will land and once again commence phase one. This is not a threat wipe.

https://imgur.com/a/raUXdzJ

**Comment by pinkisnotgay** [comment]
Just copy over scripting from yout wrath server and lets go!
@Afgann

**Comment by Wojtyas** [comment]
> Just copy over scripting from yout wrath server and lets go!
> @Afgann

if only it would be so easy :D
