### ISSUE TITLE
Freezing trap

### ISSUE THREAD

**Issue by comfik1** [SunwellWoW/Sunwell-TBC-Bugtracker#4436]
Description: 
Freezing trap should have its max duration 10seconds in PvP, like polymorph,sap,fear, etc

How it works: 
Its freaking 12 seconds

How it should work: 
Max duration should be 10seconds

Source (you should point out proofs of your report, please give us some source): 
Every other crowd control abilities that have 10+ duration on mobs - polymorph,fear,sap lasts only 10 seconds excluding diminishing on PvP

**Comment by firngrod** [comment]
According to this list of Diminishing Returns skills, Freezing Trap, as an exception to the rule, does not suffer from diminishing returns.
https://wow.gamepedia.com/index.php?title=Diminishing_returns&oldid=1580531

Looking at the article for Polymorph, it is clearly stated that the duration when used on players is capped at 10 second.
https://wow.gamepedia.com/index.php?title=Polymorph&oldid=1531495

Nothing of the sort is mentioned in the article for Freezing Trap.  This is not proof, of course, but it is indicative.  With a 20 seconds max duration, I would expect that this would have been mentioned.
https://wow.gamepedia.com/index.php?title=Freezing_Trap&oldid=1522083

**Comment by akrom23** [comment]
Just tested and work okay.
@comfik1 Show me video or screenshots.

**Comment by balo-git** [comment]
There are some old 2008 arenajunkies threads stating that it has 12 or 13 second duration.

https://www.google.com/search?q=clever+traps+site%3Aarenajunkies.com&oq=clever+traps+site%3Aarenajunkies.com&aqs=chrome..69i57.12344j0j7&sourceid=chrome&ie=UTF-8

It seems to be generally accepted that it was lasting at least 12 seconds with the Clever Traps talent. It might actually be lasting 13 seconds, but the debuff would of course show 12 seconds immediately (as the 13 second indicator would last only an instant). Difficult to find non-grainy footage with timers visible. Need to see how long it remains at 12s on the debuff, or whether it instantly goes to 11s

**Comment by comfik1** [comment]
Its 13 cuz when i got struck by it it showed 12, i can imagine some talent in surv tree maybe? Dont know hunters talents tbh, but im sure it was more than 10s

**Comment by balo-git** [comment]
Yes the Clever Traps talent increases hunter trap durations by 30%, so I would expect 10s to go to 13s.

At the same time the maximum CC limit was defined at different points in TBC as 12s and later 10s, But old arena junkies post seem to imply Clever Traps was still going for 12/13s on freezing trap

**Comment by RPAncap** [comment]
Unrelated but can any hunters confirm the freezing trap sometimes randomly breaks in PvE ? Or am I just crazy ? :-D

**Comment by flapse32** [comment]
Check dpsmate and u can see what breaks the CC ^^
