### ISSUE TITLE
Phase 3 Vashj post nerf

### ISSUE THREAD

**Issue by Lorious** [SunwellWoW/Sunwell-TBC-Bugtracker#4437]
Description: 
Ehm, you might have nerfed Vashj a bit much!
She is a free kill if you make it to phase 3.

See video from our kill yesterday.
Pretty much no green stuff on the ground and sporebats can down and greeted us with open wings.

How it works: 
https://www.twitch.tv/videos/392186779

How it should work: 
She should atleast put up a fight....

Source (you should point out proofs of your report, please give us some source):

**Comment by aeyers** [comment]
A total of 2 toxic spore bats managed to use their ability during P3. Both of those not even targeting a player. The floor should be covered with the poision cloud at the end of the fight working as a "enrage timer".

P3 this week felt so broken due to how easy it was compared to how hard it should be. Hard to enjoy.

**Comment by neheri** [comment]
I think Vashj was working fine before cry-report here:
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4404

She was challenging, some bats could not be killed at all, making the fight more challenging the longer you were fightning her. That was properly working enrage mechanism. Survi hunters with range talents could get most of bats down.

I really don't like that stuff is neither documented nor tested before "fixing". Some guilds had to really struggle to achieve their first kills while other guilds are just making posts like this and boss afterwards is a joke.

**Comment by aeyers** [comment]
I agree. Its easy enough to youtube the world second by method to see some of the mekanics such as poision clouds aswell as their dmg (around 3k).

https://www.youtube.com/watch?v=SYypbzs9d44&t=708s

**Comment by jowns** [comment]
Well you can sheep & fear the MC targets still too right? Ezmode, should be immune to that xD
