### ISSUE TITLE
[Paladin] Retribution Aura

### ISSUE THREAD

**Issue by pinkisnotgay** [SunwellWoW/Sunwell-TBC-Bugtracker#4438]
Description: 

Retribution Aura is a damage shield and should trigger off  every melee attack (block included) and is not limited by any cooldown.

How it works: 
Retribution aura only triggers off when you take damage

How it should work: 
It should also trigger when you block incoming damage, same as Darkmoon Card: Vengeance

Source:
https://wowwiki.fandom.com/wiki/Reactive_effect
Reactive effects are effects which are triggered by specific events, most often by hits or blocks.

There are two different types of reactive effects:
    _Damage shields_: These have a 100% chance to proc, but can only be triggered by melee attacks. The damage is not considered spell damage.
    Reactive procs: These do not necessarily trigger off every attack. However, they are not limited to melee attacks (unless specifically mentioned otherwise). The damage inflicted is considered spell damage. 

https://wowwiki.fandom.com/wiki/Damage_shield

![retri aura 1](https://user-images.githubusercontent.com/44933866/54035355-7fc6c900-41b9-11e9-9be9-8b0dd5bb358c.png)
![retri aura](https://user-images.githubusercontent.com/44933866/54035363-83f2e680-41b9-11e9-80c3-f590b1177462.png)

**Comment by pinkisnotgay** [comment]
akrom23 commented 8 days ago
,,Next time, just tag me on critical issues."


@akrom23

**Comment by akrom23** [comment]
I believe full blocked hits should not be reflected.
Give me more proofs.

**Comment by pinkisnotgay** [comment]
I think you may be right on this one.
