### ISSUE TITLE
Runed Copper Belt should not be uncommon quality

### ISSUE THREAD

**Issue by samercyn** [SunwellWoW/Sunwell-TBC-Bugtracker#4439]
**EDIT**
This shouldn't even be uncommon quality in TBC.

~~Description: I just bought a few Runed Copper Belts off the auction house to disenchant them but it says I cannot do so.~~

~~How it works: Cannot disenchant Runed Copper Belt~~
![image](https://user-images.githubusercontent.com/30945427/54061015-f4efc980-41cc-11e9-9de3-bd1558e66843.png)

~~How it should work: Runed Copper Belt should be disenchantable.~~

**Comment by Ironjudgment** [comment]
You are showing a WOTLK+ version of this belt. Runed Copper Belt is a white item with no stats in TBC. Possibly deleting your cache will help with that.
http://tbc.cavernoftime.com/item=2857#created-by
https://classicdb.ch/?item=2857

You can see good comparison on twinstar database.
TBC -> https://tbc-twinhead.twinstar.cz/?item=2857
WOTLK -> https://wotlk-twinhead.twinstar.cz/?item=2857
And on WOTLK version you can see it's tagged as 'Disenchantable (1)'

**Comment by samercyn** [comment]
I literally just deleted my cache yesterday and this is still uncommon quality with the WotLK stats.

I suppose the real bug is that it's even uncommon quality at all.

http://db.hellfire-tbc.com/?item=2857 shows it as being uncommon with +3 strength and +2 stamina.

Wowhead comments indicate it was updated in 3.1 to be uncommon quality
![image](https://user-images.githubusercontent.com/30945427/54063808-135dc100-41dd-11e9-8e2e-ccd6743c613d.png)

**Comment by Ironjudgment** [comment]
Hmm, I've just checked in-game and the belt really is uncommon and has stats :S 
Wowiki articale from July 2, 2008.
https://wowwiki.fandom.com/wiki/Runed_Copper_Belt?oldid=1471865

I guess devs need to change it. What I am wandering about is, how many more items are there like that? :D
