### ISSUE TITLE
NPCs after interaction reset waypoints

### ISSUE THREAD

**Issue by Dootz** [SunwellWoW/Sunwell-TBC-Bugtracker#444]
Decription: 
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/16

Now after the interaction, NPC stops. When he starts to move again, he does it from his first waypoint. So he's running through textures to his initial point.

Example:
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/109

**Comment by Riztazz** [comment]
Also first iteration of waypoint movement skips one initial point for whatever reason.
Reproduction:
save yourself at the spawn point of some creature that does waypoint movement, reboot your worldserver, log in and observe

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC/commit/864d40a14aedccca3560fac5f6074300b5859efb

**Comment by Azathothh** [comment]
![wowscrnshot_092218_120621](https://user-images.githubusercontent.com/37483678/45916160-a2f6f980-be61-11e8-8a43-01930c0d07af.jpg)
1. Npc still flying to respawn point
2. Now after interaction npc stops and turns towards us just for like 0.1sec and then keep walking

**Comment by Wojtyas** [comment]
Fixed & implemented.
