### ISSUE TITLE
Classes. Warrior. Heroic Strike and Autoattack.

### ISSUE THREAD

**Issue by Aliashketich** [SunwellWoW/Sunwell-TBC-Bugtracker#4440]
Description: 
I have problem with interrupting Heroic Strike

How it works: 
When I use Heroic Strike and will interrupt this after on Esc (button), Heroic Strike icon selection disappears but Heroic Strike whatever will be used.

How it should work: 
After Esc-button should interrupt Heroic Strike using.

Source (you should point out proofs of your report, please give us some source): 
I'm so sorry, I can't do video for report this, just check please :)

**Comment by Chugunnik** [comment]
Same bug for hunter's Raptor's Strike. It also stops ability to shoot.
