### ISSUE TITLE
Masquerade Gown (Love Stuck Proc)

### ISSUE THREAD

**Issue by KwasekYo** [SunwellWoW/Sunwell-TBC-Bugtracker#4442]
Description: 
Masquerade Gown - a cloth chest with Equip: Chance on spellcast to increase your Spirit by 145 for 15sec. Combined with Resto Druid's Tree of Life Aura should increase healing ticks from healing spells.

How it works: 
The proc increases total spirit, but is not calculated for tree of life aura bonus. Does not increase Lifebloom ticks - even when Lifebloom was casted after buff proc.

How it should work: 
It should increase all healing received while proc is up.

Source (you should point out proofs of your report, please give us some source):

**Comment by babno** [comment]
This is not related to the item but actually tree of life. The aura is set in stone when you shift into tree of life. If you go out and back into tree during the proc the aura will be permanently increased so long as you remain in tree. This is working as intended I believe.

**Comment by koostosh** [comment]
This is how tree of life should work as far as i know, please provide source that it should not otherwise it will not be changed.
