### ISSUE TITLE
[Paladin][Warlock][Pet] Seduction goes through Divine Shield

### ISSUE THREAD

**Issue by balo-git** [SunwellWoW/Sunwell-TBC-Bugtracker#4447]
Description: 
Seduction works against a paladin in divine shield

How it works: 
A paladin can be affected by Seduction while under divine shield.

How it should work: 
A paladin in divine shield should be immune to Seduction.

Source (you should point out proofs of your report, please give us some source): 
https://i.imgur.com/TdeWicE.jpg

**Comment by koostosh** [comment]
Could not reproduce, has it happen more that once?

**Comment by Devrak** [comment]
it is a batch issue.... if a paladin casts bubble while seduction is in-flight at him it gets past shield because as it would seem immunity/reflect is checked upon cast success rather than when it actually hits the target.

**Comment by koostosh** [comment]
Seduction is not delayed spell, it is never "in-flight", thats why there is no reason to re check immunity on spell hit.

**Comment by balo-git** [comment]
It's happened to me on 3 occasions, including the one from the screenshot.

I thought I had a video of it happening as well but I believe I may have crashed before ending the recording, as I cannot find it.

In every case I **_believe_** the seduction hit me shortly after using Divine Shield, and I believe the warlock in question has Seduction on auto cast (or was just mercilessly spamming it between every shadowbolt, even though I had dots on me).
