### ISSUE TITLE
[Raid/Boss] AQ40 The Prophet Skeram

### ISSUE THREAD

**Issue by pinkisnotgay** [SunwellWoW/Sunwell-TBC-Bugtracker#4450]
Description: 

His aggro table keeps on wiping itself all the time. It's not only when he is at 75%, 50%, and 25%
When fighting the boss you need to keep on taunting all the time or he's just gonna run around and smack the raid.

How it should work: 
Shouldn't wipe his threat all the time.

**Comment by jowns** [comment]
Still not fixed, keeps swaping aggro every other sec

**Comment by pinkisnotgay** [comment]
Doesn't matter. Boss is still killable 10man, most of the bosses in AQ40 are just loot piniatas.
