### ISSUE TITLE
[Raid/Loot] [Question] Qiraji Resonating Crystal mounts 

### ISSUE THREAD

**Issue by pinkisnotgay** [SunwellWoW/Sunwell-TBC-Bugtracker#4451]
According to wowhead and Atlas loot, all Qiraji Resonating Crystal mounts (except for Red) should have around 10% (1% red) drop chance from those AQ40 mobs:

Anubisath Defender (npc=15277)
Anubisath Sentinel (npc=15264)
Anubisath Warder (npc=15311) 
Obsidian Eradicator (npc=15262)
Obsidian Nullifier (npc=15312)
Qiraji Brainwasher (npc=15247)
Qiraji Champion (npc=15252)
Qiraji Lasher (npc=15249)
Qiraji Mindslayer (npc=15246)
Qiraji Slayer (npc=15250)

We've cleared up to C'thun twice already and to be honest we only got like 2 mounts per reset only from Anubisath Sentinels. Either we are unlucky or the drop rate seems to be lower than 10%.

Could you check this out?
Best regards.

**Comment by NeonicSupersonic** [comment]
Its lower, everything in AQ supposed to drop mounts like crazy. Usually you get 20 to 30 per run if not more.

**Comment by pinkisnotgay** [comment]
@Dootz Thanks bud.

**Comment by pinkisnotgay** [comment]
Fixed.
