### ISSUE TITLE
Prayer of Mending

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#4452]
Description: Prayer of Mending heal even person with PoM resist/block/dodge/miss damage 

How it works: 

When you use Prayer of Mending on target it heals when player with PoM get damage and heal when target block/ressist/miss damage. After first "heal" it jumps to random player within 20y and same next 4 jumps. 

How it should work:
Prayer of Mending. Places a spell on the target that heals them for 0 the next time they take damage. When the heal occurs, Prayer of Mending jumps to a raid member within 20 yards. Jumps up to 5 times and lasts 30sec after each jump. 

Source (you should point out proofs of your report, please give us some source): 

https://youtu.be/-tJKcdhXTAk

https://tbc-twinhead.twinstar.cz/?spell=41635

**Comment by koostosh** [comment]
I was not able to reproduce any case when person is healed after getting full resist, full block, parry, dodge or miss.
Also I see nothing on clip you provided, please describe what problem you see on it.

**Comment by ghost** [comment]
The problem is that Prayer of Mending heals event target get no damage (on video you can see that tank(Vanhand my target) get PoM and after few sec he get heal for 1790 when he didnt get damage (last damage was 2 sec before and it healed him)

**Comment by ghost** [comment]
Whatch 45 second video there is hit then i healed him use PoM and 1second after he get heal from PoM (1790) and that hit was miss you can see that on my target

**Comment by ghost** [comment]
Same situation 10sec after

**Comment by ghost** [comment]
To See this bug you need to Focus on watching when i use PoM and my target damage tanken

**Comment by ghost** [comment]
1:25 min video you can see that i used PoM and tank dodge dmg and he get heal from PoM

**Comment by ghost** [comment]
I just watched 3 random clips from video and 3 situations that i describe

**Comment by babno** [comment]
At 45 seconds he had SWP on him. It dealt damage, POM then healed him for more than the damage dealt so he remained at full. Same thing at 1:25

**Comment by koostosh** [comment]
Cannot reproduce. All examples in provided video can be explained by dots
