### ISSUE TITLE
frostguard - lvl 58 sword

### ISSUE THREAD

**Issue by alandrarcy** [SunwellWoW/Sunwell-TBC-Bugtracker#4454]
Description: 
proc from sword frostguard "chilled" doesn't proc when Thunder Clap is on and doesn't even overwrite it

How it works: 
It doesn't proc when thunder clap is on

How it should work: 
according to GM, it shouldn't be the same debuff as thunder clap, so it should stack with thunder clap, or at least overwrite thunder clap if its same debuff type

Source (you should point out proofs of your report, please give us some source): GM

**Comment by koostosh** [comment]
Does proc, and is replacing thunder clap as chilled is stronger debuff.

Works as intended
