### ISSUE TITLE
felhunter has no base resistances

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#4455]
Description: 
![image](https://user-images.githubusercontent.com/244626/54162887-91180b80-442d-11e9-9832-0010c52bdfb7.png)

How it should work: Fel hunter base resistance should be twice the level of the warlock, so 140 at level 70

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Felhunter#Strengths

**Comment by koostosh** [comment]
Please provide source from 2.4.3 patch. as of 2.1 resistance should be equal to warlock level

//Edit: Found.

**Comment by babno** [comment]
I don't see anything about felhunter resistances being lowered in 2.1 https://wowwiki.fandom.com/wiki/Patch_2.1.0

**Comment by babno** [comment]
![image](https://user-images.githubusercontent.com/244626/54390527-0f1c2280-4679-11e9-97a7-1be919e3a7c5.png)
looks good now. I will note that the numbers appear in green as if the resistance is from a buff instead of being white as they should be from a base resistance. I tested to make sure it stacks with other resistance buffs and it does, so I don't think it matters in the end.
