### ISSUE TITLE
[Serpentshrine Cavern][Lady Vashj][Shock Blast]

### ISSUE THREAD

**Issue by ghost** [SunwellWoW/Sunwell-TBC-Bugtracker#4457]
Description:
Lady Vashj's Shock Blast and Grounding Totem do not interact correctly

How it works:
Shock Blast doesn't get redirected by Grounding Totem

How it should work:
Shock Blast should be redirected and and destroy Grounding Totem

Source (you should point out proofs of your report, please give us some source): 
https://web.archive.org/web/20080719234047/http://www.wowwiki.com/Lady_Vashj_(tactics)

**Comment by ruineroffun** [comment]
Do you have any proof of that, since it did work previously just fine?

**Comment by ghost** [comment]
I do not have proof that it doesn't work, but it's not that hard to replicate isn't it? (It did work last sunday so it must've been broken due to some 'fixes' on monday or tuesday)

**Comment by ghost** [comment]
Totem works again, muchas gracias to the devs <3
