### ISSUE TITLE
Zuluhed the Whacked

### ISSUE THREAD

**Issue by cibram** [SunwellWoW/Sunwell-TBC-Bugtracker#4459]
Description: 
Mob does not spawn at intented location, nowhere at all. 

How it works: 
It shows in chat a yelling message, but Zuluhed do not spawn. 

How it should work: 
Should work like this: https://www.youtube.com/watch?v=Iy45YwUZKfE 

Source (you should point out proofs of your report, please give us some source): 
![zuluhed](https://user-images.githubusercontent.com/6170518/54275052-bb3b0c00-459a-11e9-8d78-5ae17a791daa.png)

**Comment by Jonsse** [comment]
He spawns on the balcony to the left.
