### ISSUE TITLE
[warrior] rampage stacks extending duration

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#446]
Previously rampage wasn't building stacks from attacks as it should. Now it is, however each time it adds a stack it resets to 30 seconds. This will also happen at 5 stacks, although for a limited amount of time (~30 seconds) and then it will stop being reset. What I think is happening is when I use rampage is says for 30 seconds attacks can apply the AP buff which will last 30 seconds, essentially making it a minute long buff instead of 30 seconds.

**Comment by Pizzle93** [comment]
Confirmed still automatically refreshing on crits
