### ISSUE TITLE
Dropchances of (white) items are way too high.

### ISSUE THREAD

**Issue by Gorebane** [SunwellWoW/Sunwell-TBC-Bugtracker#4465]
Description: 
White items like armor drop way too often, i started to notice it when I was killing mobs in the barrens. I also got way too many small pouches.

I'm not sure if this is only happening with the white items.

Here is an open ticket from months ago saying the same thing.
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/689

**Comment by neheri** [comment]
I happens only from mobs near ~10 level. Easiest example of this bug is drop from Razormane in barrens.

**Comment by Gorebane** [comment]
It also happens with the Plainstriders around Crossroads (in the Barrens).
