### ISSUE TITLE
[Object] Gromsblood and Icecap respawn timers are way too low.

### ISSUE THREAD

**Issue by westerngee** [SunwellWoW/Sunwell-TBC-Bugtracker#4470]
Description: Gromsblood (in Blasted Lands at least, haven't tested it in other zones yet) and Icecap spawns are way too low

How it works: In the current build it seems like these 2 specific herbs (which are integral for Flask of the Titans and Flask of Distilled Wisdom) are on a 20-30 minutes respawn timer for a few weeks now (why has no one else reported that yet), while Herbs like Dreamfoil are still on their regular timer.

How it should work: faster. :)

Source (you should point out proofs of your report, please give us some source): 
I could make a 30 minutes video of me loitering around a herb spawn, but why would I.

**Comment by NeonicSupersonic** [comment]
Its Azeroths dreamfoil(and black lotus/mountain silversage, pbbly plaguebloom aswell) spawns which are broken and far more common than they should be(not to mention redicolous 3 cluster spawns).

Common HG core bug.

**Comment by RPAncap** [comment]
I would say that the spawns in burning steppes are broken - meaning black lotus, silversage and dreamfoil.
However imho plaguebloom and other stuff in plaguelands spawns normally (i.e. much less commonly.)
