### ISSUE TITLE
Judgement of wisdom 

### ISSUE THREAD

**Issue by Vasalina** [SunwellWoW/Sunwell-TBC-Bugtracker#4471]
Description: Judgement of wisdom do not give mana back to the casting paladin.

How it works: Judgement of wisdom is suppose to have a chance to restore 74 mana on hit / spell, This seems to be working for all but the paladin that put it up.

How it should work: Should work for the paladin casting it. Note this is for the judgement that is on an enemy, The seal is working correct.

Source (you should point out proofs of your report, please give us some source): 
Tried 120 swings with 0 giving mana back to me. Cant proove it but should be very easy to test.

EDIT: After re-testing and double checking combat logs it seems i was wrong its working, However its not showing up as a mana gain in  Floatitng combat text which is why i thought it wasnt working in the first place.

**Comment by NeonicSupersonic** [comment]
https://imgur.com/a/X8NnR0f

Works fine for me, perhaps some wierd tier bonuses/talents/enemy immunities interraction?

**Comment by Vasalina** [comment]
It might be thats its not showing up in  Floatitng combat text (Where all other instant mana gain does show up) cause i wasnt checking combat log. 

Edit: It is indeed working, But it is also not showing up through the defaul Floatitng combat text
Normal seal of wisdom and all other instant mana things ive tried (Arcane torrent / Mana pot / Lay on hands) are all showing up correctly in Floating combat text. Judgement of wisdom is not.
