### ISSUE TITLE
Scroll of agility V

### ISSUE THREAD

**Issue by flapse32** [SunwellWoW/Sunwell-TBC-Bugtracker#4472]
Description: Dosent work

How it works: Dosent work at all.

How it should work: Should work

Source (you should point out proofs of your report, please give us some source): 

https://streamable.com/blbmy

**Comment by flapse32** [comment]
EDIT: Apperently dosent stack with agility elixir. Im pretty sure its supposed to stack.

**Comment by Wojtyas** [comment]
Any proof mate?

**Comment by flapse32** [comment]
It has been fixed. you can close this report =)
