### ISSUE TITLE
Magic Resistance Potion overrules flasks

### ISSUE THREAD

**Issue by DreuxPala** [SunwellWoW/Sunwell-TBC-Bugtracker#4475]
Description: 
Magic Resistance Potion overrules flasks

How it works: 
When you pop a magic resistance potion it overrules any flask effect which makes it disappear. You can't use Magic Resistance Potions alongside any flasks.

How it should work: 
You should be able to use both consumables simultaneously as any other potion effect.

Source (you should point out proofs of your report, please give us some source):

**Comment by RPAncap** [comment]
You are correct that it should stack with flask. However keep in mind though that Magic resistance potions should NOT stack with other effects such as pally aura/shammy totems.
Which pretty much makes the usefullness of it close to zero.
