### ISSUE TITLE
Hunter Pet Abilities Not Affected By Happiness

### ISSUE THREAD

**Issue by YoshGit** [SunwellWoW/Sunwell-TBC-Bugtracker#4476]
Description: 
Hunter pet abilities are not affected by their happiness.

How it works: 
Happiness currently increases/decreases the damage done by pet auto attacks but not casted abilities.

Currently a pet's casted abilities deal 100% damage regardless of their happiness.

How it should work: 
When pets are happy, they should deal 125% damage (auto attacks as well as their casted spells). When content they should deal 100% damage. When unhappy they should deal 75% damage.

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_031719_130046](https://user-images.githubusercontent.com/12674486/54495063-e5e8d580-48b6-11e9-96cb-21dc2e4246fc.jpg)
![WoWScrnShot_031719_130050](https://user-images.githubusercontent.com/12674486/54495064-e5e8d580-48b6-11e9-9d91-19568f593879.jpg)
![WoWScrnShot_031719_131028](https://user-images.githubusercontent.com/12674486/54495065-e6816c00-48b6-11e9-8db9-e180265b8c81.jpg)
![WoWScrnShot_031719_131033](https://user-images.githubusercontent.com/12674486/54495066-e6816c00-48b6-11e9-9b7c-3b93b296a6e5.jpg)

**Comment by flapse32** [comment]
pictures shows that it is affected, but maybe not the right amount.
