### ISSUE TITLE
Go to the Front(quest Hellfire Peninsula)

### ISSUE THREAD

**Issue by Alkimor** [SunwellWoW/Sunwell-TBC-Bugtracker#4479]
Description: Wing Commander Gryphongar said me - Take a gryphon and fly over to Honor Point.

How it works: NPC Gryphoneer Windbellow not have function - fly to Honor Point.

How it should work: NPC Gryphoneer Windbellow must have function - fly to Honor Point

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=gAu9GPa1Agg
![WoWScrnShot_031819_234855](https://user-images.githubusercontent.com/30193603/54562879-f1342200-49d8-11e9-9c07-52b9b23c2879.jpg)

**Comment by Dootz** [comment]
![WoWScrnShot_031819_221406](https://user-images.githubusercontent.com/25490436/54564143-56811680-49cb-11e9-9a74-f86ca6ea7818.jpg)

Weird, I just tested it on live and it works correctly. It only works if you have quest https://www.wowhead.com/quest=10382/go-to-the-front taken but not rewarded.
