### ISSUE TITLE
[Dungeon] Zul'Farak

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#448]
- [x] sergeant bly and crew don't move down the steps until after boss is killed, they should move down and help
- [ ] The dwarf priest disappeared and combat bugged me
- [x] You can't talk to bly and turn him aggressive
- [ ] witch doctor zum'rah can give no loot
- [x] shadowpriest and nekrum instantly despawned on death

**Comment by Bezimienny95** [comment]
![wowscrnshot_092018_195716](https://user-images.githubusercontent.com/31216921/45837369-7f239e80-bd0f-11e8-9f37-c842126ba322.jpg)

**Comment by Dootz** [comment]
> witch doctor zum'rah can give no loot

Works fine for me. @Kokaina could you check it. Other issues will be fixed with next PTR update. Thank's for report.

**Comment by blackabbath** [comment]
Witch Doctor Zum'rah doesn't give any loot. Checked on three alliance characters two times.
He should have loot with 100% drop chance!
