### ISSUE TITLE
[Boss/Raid] Naaxx40 Kel'Thuzad

### ISSUE THREAD

**Issue by NeonicSupersonic** [SunwellWoW/Sunwell-TBC-Bugtracker#4480]
Description: 
Kt wont spawn after Saph death.

How it works: 
Kt wont spawn after Saph death.

How it should work: 
Kt should spawn after Saph death with RP yells and all of that, also his throne and portal windows in his room are missing.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=XOpxCUuXDH8
https://imgur.com/a/rlct1Ms

**Comment by pinkisnotgay** [comment]
Mr @afgann pls

**Comment by pinkisnotgay** [comment]
up

**Comment by Afgann** [comment]
Busy with hyjal right now @pinkisnotgay.
