### ISSUE TITLE
[Hunter] [Spell] Hunter's Mark & Improved Hunter's Mark

### ISSUE THREAD

**Issue by ado7e** [SunwellWoW/Sunwell-TBC-Bugtracker#4481]
Description: 
Improved Hunter's Mark as a more powerfull spell should be able to override the non-improved Hunter's Mark

How it works: 
Casting non-improved hunter's mark prevents casting improved hunter's mark.

How it should work: 
Casting improved hunter's mark should be cast even if non-improved is on the target. It should override normal hunter's mark, and should block the possibility to cast the non-improved one while issuing an error message that there's already stronger spell of this type on the boss till it expires.

Source (you should point out proofs of your report, please give us some source): 
well, that's basic, right ?

**Comment by Ironjudgment** [comment]
Support.
Revision as of 17:32, April 4, 2008: Improved Hunter's Mark 
https://wowwiki.fandom.com/wiki/Improved_Hunter%27s_Mark?oldid=1295589

> An Improved Hunter's Mark will overwrite a Hunter's Mark that is not improved by this talent. A higher talent Improved Hunter's Mark will overwrite a lower version.
