### ISSUE TITLE
al'ar moving randomly and to non platforms [critical]

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#4484]
How it works: Boss will go to any one of 6 spots for each transition. Unless you have a tank for each then flame buffets are inevitable and you should only need 2 tanks for alar himself.

How it should work: There are 4 valid spots where it should go and each transition he should go clockwise (or do flame quick, at which point he should fly to one of the platforms by the ramp).

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Al%27ar
" Al'ar spends around 30 seconds on each platform, then moves on to the next, flying clockwise (W, NW, NE, E, repeat)."

**Comment by NeonicSupersonic** [comment]
Its pre nerf, he supposed to use 6 platfroms. 3 tanks can controll all of them (1x2 forward 2x2side).

**Comment by pinkisnotgay** [comment]
https://youtu.be/0jzsVKPKr6I
Working as intended.
Ez close.

**Comment by ruineroffun** [comment]
Love these reports with 0 insight or research done into the encounter. You go buddy!
