### ISSUE TITLE
Mystical Skyfire Diamond

### ISSUE THREAD

**Issue by DesCodes** [SunwellWoW/Sunwell-TBC-Bugtracker#4488]
Description: 15% chance on spell cast to grant the caster 320 spell haste rating for 6 seconds

How it works: the proc grants the caster 4 seconds of 320 spell haste rating

How it should work: the proc on the meta gem is supposed to grant the caster 6 seconds of 320 spell haste rating.

Source (you should point out proofs of your report, please give us some source): 
[gem description](https://wowwiki.fandom.com/wiki/Mystical_Skyfire_Diamond)
[focus buff](https://www.wowhead.com/spell=32837/spell-focus-trigger)

**Comment by koostosh** [comment]
As of 2.4.3 it should be 4 seconds (undocumented change in 2.4.0)
