### ISSUE TITLE
Resistance not stacking properly - GoTW/MoTW doesnt stack with Aura/Totem/Aspect

### ISSUE THREAD

**Issue by RPAncap** [SunwellWoW/Sunwell-TBC-Bugtracker#4489]
Description: 
Hey we noticed todays SSC that our tanks didnt have the proper calculated resistance and by testing we found out that resistance from MoTW/GoTW doesnt stack with resistance from auras.

How it works: 
They dont stack

How it should work: 
They should

Source (you should point out proofs of your report, please give us some source): 
https://wowwiki.fandom.com/wiki/Hydross_the_Unstable/Resistance_Gear

Look how it is calculated in the tables - they are clearly summed together - they should stack.

**Comment by samercyn** [comment]
These should not stack. [Source](https://wowwiki.fandom.com/wiki/Resistance#Sources_of_Resistance)

**Comment by RPAncap** [comment]
Your source is not TBC. It even clearly says an example with 130 res from totem..... I provided TBC source......

**Comment by samercyn** [comment]
All you have to do is go through the history of that Wiki page to see that it has always worked like this. You can also go back to older histories of the Mark of the Wild page ([link](https://wowwiki.fandom.com/wiki/Mark_of_the_Wild?oldid=1641765)) to see that it specifically states "The resistance benefit of any rank of this spell does not stack with other resistance buffs. See Resistances for more information."

MotW and Totem/Aspect/Aura did not stack in Vanilla. This is common knowledge for anyone who raided in Vanilla.

They did not stack in TBC.

They did not stack in WotLK.

They have never stacked.

**Comment by koostosh** [comment]
They should not stack
