### ISSUE TITLE
Blood Pact overlapping

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#449]
It happened for the first time but maybe it may occur with other auras as well.
I was in dungeon, Piootrek and his Imp were outside dungeon but still somehow Blood Pact aura was applied on me.

![image](https://user-images.githubusercontent.com/22802214/45841214-66b88180-bd19-11e8-946f-964f64532574.png)

**Comment by akrom23** [comment]
Cannot reproduce.
Need more tests. It happened after dc/relog?
