### ISSUE TITLE
[Raid/Boss] Molten Core.

### ISSUE THREAD

**Issue by pinkisnotgay** [SunwellWoW/Sunwell-TBC-Bugtracker#4491]
Description: 
Runes of Warding do not work. I've obtained the Aqual Quintessence required to douse all the runes in Molten Core, but after I extinguished them Majodomo Executus didn't spawn. There was no RP even whatsoever.

On top of that runes are also bugged in a way that most of the runes are not clickable normally. You need to open your bag, click the Quintessence and hover over a rune and then click it. That's how you extinguish Magmadar, Gehennas, Garr. 
On the other hand Shazzrah, Golemagg, Baron Geddon and Sulfuron runes are clickable, but you still need the esence to douse them. (Rune of Mazj, Rune of Zeth, Rune of Koro, Rune of Theri)

After you douse runes there is an animation as if you've done in properly, but the circle of fire remains as if it was not doused.

Proof:
https://wow.gamepedia.com/The_runes_of_warding

![WoWScrnShot_032719_104704](https://user-images.githubusercontent.com/44933866/55066574-5ee9e900-507e-11e9-930d-225e7d9c5d3f.jpg)
![WoWScrnShot_032719_104630](https://user-images.githubusercontent.com/44933866/55066576-5f827f80-507e-11e9-831b-c9e1ee47f8eb.jpg)
![WoWScrnShot_032719_104529](https://user-images.githubusercontent.com/44933866/55066577-5f827f80-507e-11e9-80ce-27b12d91544c.jpg)
![WoWScrnShot_032719_104258](https://user-images.githubusercontent.com/44933866/55066579-5f827f80-507e-11e9-94e4-d32249946912.jpg)
![WoWScrnShot_032719_104226](https://user-images.githubusercontent.com/44933866/55066580-601b1600-507e-11e9-8f03-17da571c2343.jpg)
![WoWScrnShot_032719_104200](https://user-images.githubusercontent.com/44933866/55066581-601b1600-507e-11e9-8dd2-9ff27db6adab.jpg)
A bonus:
Trash and 2 minions tied to Golemagg is respawning even though he's dead.

**Comment by westerngee** [comment]
you can also interrupt Baron Geddon's Bomb and his "last service", which makes it laughably easy.
