### ISSUE TITLE
[Object] Workshop Door

### ISSUE THREAD

**Issue by nimeral** [SunwellWoW/Sunwell-TBC-Bugtracker#4492]
Description: Workshop Door only give ONE point of lockpicking

How it works: Workshop Door only give ONE point of lockpicking (or probably the reset timer is too long)

How it should work: Workshop Door should be a way to level lockpicking 

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/forums&topic=116181

**Comment by koostosh** [comment]
From the wowhead thread you linked:

Doors: You'll also encounter doors on your travels. These can be used to increase lockpicking skill, but **be aware that they all have long cooldown timers on them, i.e. you will only be able to gain a skill point from them every twenty-plus minutes.** There are a few ways to get around the cd. For instance go inside SM and pickpocket for a few minutes and the doors will reset. Or you can reset BRD to make everything re-lock.
