### ISSUE TITLE
API SwapRaidSubgroup - not working 

### ISSUE THREAD

**Issue by bagofskum** [SunwellWoW/Sunwell-TBC-Bugtracker#4494]
Description: 

We wrote the following to give us the ability to easily rotate players in our raid group for a variety of reasons, see below:

/run local n1,n2,s1,s2="skum","Shagu"; for i=1,40 do if UnitName("raid"..i) == n1 then s1 = i elseif UnitName("raid"..i) == n2 then s2 = i end; end; if s1 and s2 then SwapRaidSubgroup(s1, s2) end

How it works: 

Currently the API call only works when you are not in combat

How it should work: 

The Combat API shouldn't be protected as of yet (patch 4.0.1) onward it was, thus we should have the ability to do this in combat.

Source (you should point out proofs of your report, please give us some source): 

https://wow.gamepedia.com/API_SwapRaidSubgroup

I can be reached here, or via discord if you need further infomration. 

skumbag#0001 / skumgodx
nickycakes#2232

**Comment by koostosh** [comment]
Either this function is nocombat in 2.4.3 or you have addon conflict that prevents it from being used. 

Wow APIs are client implementation, they cannot be changed by server.
