### ISSUE TITLE
Black Morass portals, client crash

### ISSUE THREAD

**Issue by balo-git** [SunwellWoW/Sunwell-TBC-Bugtracker#4495]
Description: 
As of recently, Black Morass suffers from a couple of major bugs.

How it works: 
Sometimes after killing the second boss, the remaining 6 portals (that is portals 13,14,15,16,17,18) spawn in quick succession (within a few seconds), before the associated mob is killed.

Frequently after killing the third boss, a critical error crashes the client of multiple players inside the instance. Occasionally this repeats on logging back into the character, waiting a few minutes before logging back in usually works. In some cases, loot from the last boss is lost because of this.

How it should work: 
All portals should only spawn after the mob associated with the previous portal is killed, or after a sufficient period of time has passed.

Client shouldn't get a critical error.

Source (you should point out proofs of your report, please give us some source):

**Comment by balo-git** [comment]
To clarify the client crash happens a bit after the boss's death. Players have enough time to roll for items, but not enough to allow the item rolls to expire. It crashes during Medivh's dialogue, and **_might_** potentially be tied to the roleplaying event.

**Comment by NeonicSupersonic** [comment]
More portals supposed to open even if previous portal minibos still alive.

https://wowwiki.fandom.com/wiki/Opening_the_Dark_Portal

The Opening of the Dark Portal Edit
The event begins with Medivh calling for assistance and a portal quickly opening in one of the four designated zones: the first of 18 total waves of infinite dragonkin. Once a given portal has been shut **or enough time has passed**, a consecutive portal will be opened in a different zone and the entire encounter is timed from the opening of the first portal. At waves 6, 12, and 18, there is a boss encounter. All of the portals will spawn mobs that will seek to drain Medivh's shield and eventually kill him.

**Comment by balo-git** [comment]
Fair enough, I'll correct my original report.

At any rate, the issue I'm sometimes observing is the last 6 portals all spawning within a few seconds of eachother. They also sometimes spawn in the same place, in the most recent incident, 5 of them all spawned on top of eachother.
