### ISSUE TITLE
Feral t5 4 set bonus not working [Druid][Item][Critycal]

### ISSUE THREAD

**Issue by Aftershokx** [SunwellWoW/Sunwell-TBC-Bugtracker#4496]
Description: 
Nordrasil x4 set bonus not working correctly. Makes t5 useles for feral tanks, at all.

How it works: 
Increases lacerate bonus damage by 15 damage TOTAL (At 5 stacks)
With x4 set on char(watch max values(x5 stacked)) https://imgur.com/bBV55hr
Without x4 set on char(watch max values(x5 stacked)) https://imgur.com/xY57VI1
How it should work: 
Should increase damage done by lacerate with every aplication(1 stack +15, 5 stacks +75)

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item-set=641/nordrassil-harness#comments

**Comment by koostosh** [comment]
Works as intended. It is supposed to increase damage done by lacerate by 15 with application, not damage done by every tick of lacerate by 15.

Lacerate has 5 ticks, each of them is increased by 3, giving it total of 15dmg increase per application.

**Comment by Aftershokx** [comment]
15 with aplication = 15 per stack on target, lacerate stacks 5 times = 75 base damage on 5 stacks aplyed on target, right now it increases total periodic damage with 5 stacks on target by 15, its totally useless and gives like nothing. It should work like idol of ursok(same description) that works well in here(as I remember). I wasn’t talking about tick damage

**Comment by koostosh** [comment]
Idol of ursoc:
Increases initial and per application periodic damage done by Lacerate by 8.
This bonus:
your Lacerate ability does an additional 15 per application.

iI is not the same description. With 5 stacks every tick gives +15 dmg, meaning total damage done increased by 75 as intended.

**Comment by Aftershokx** [comment]
Just checked in rawr, u r right, sorry for false report
