### ISSUE TITLE
Swimming encounter

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#450]
There are issues when players fight with creatures that are swimming. Creature treats water surface as land and tries to stand on it. 

![image](https://user-images.githubusercontent.com/22802214/45841638-b0559c00-bd1a-11e8-918d-c46a14bf0774.png)

**Comment by Azathothh** [comment]
https://youtu.be/YXsluHPvR8w
https://youtu.be/c83C84_qrxg
Rotgrip looked fine, fishes in Zul'Gurub looked fine.
I've checked other mobs that "walks" underwater at the bottom - Makrura Clacker (.go direct 10290) and they are moving without any problems.
Maybe it's just problem with Thessala Hydra (id 12207)

**Comment by Wojtyas** [comment]
Fixed & implemented.
