### ISSUE TITLE
Disarm works on bosses

### ISSUE THREAD

**Issue by NeonicSupersonic** [SunwellWoW/Sunwell-TBC-Bugtracker#4500]
Description: 
Disarm works on bosses reducing their damage to laughtable amount

How it works: 
Disarm works on bosses reducing their damage to laughtable amount

How it should work:
I am not a warrior player and not 100% sure about every interaction, but disarm should probably do absolutely nothing against bosses even in dungeons. Here you can disarm gruul and moro (both dont use weapons, which alsone should make dsiarm have no effect) to make them do absolutely minimal damage for a disarm duration. Also disarm works (or worked) on Hyjal bosses.

Source (you should point out proofs of your report, please give us some source): 
Easily recreatable

**Comment by koostosh** [comment]
Source that it should not work this way?

**Comment by NeonicSupersonic** [comment]
I know for sure it shouldn’t work against creatures which don’t have weapons (gruul and moro for example), as spell description suggests.

Disarm/5 yd range/Instant/Disarm the enemy's weapon for 10 sec. 
https://wow.gamepedia.com/Disarm
PTR client.png Patch 0.7 (2004-06-15): Will only work on targets that are carrying weapons. Changed to an instant ability. 
https://wowwiki.fandom.com/wiki/Disarm
Disarm is highly useful against mobs that wield weapons, which almost strictly means humanoids and demons. The damage reduction is marked, as much as 50-70%.

As for weapon-wielding bosses, I am still uncertain about what disarm effect should be. I mean, if it has such a huge effect on bosses, why no one in retail tbc lifetime(or wrath since disarm was the same ability afair) not only not stacked warriors against heavy phys dps bosses but also never mentioned disarm as a crucial defensive cd in any warrior guides? Scenario in which ability with such huge potential remains unused just seems very unlikely to me. 

Anyway, Ill keep looking further.

**Comment by NeonicSupersonic** [comment]
Wotlk again, but should be relevant. Brutallus mentioned since its discussion related to wrath talent viability which gives 10% more damage against disarmed target.

http://urbad.net/blue/eu/6178690687-WotLK_Prot_Warrior_guide
Improved Disarm: There’s been a small number of bosses reported in WotLK instances that you can disarm, but as a general rule of thumb it’s impossible, which makes this talent pretty useless. Unless there’s an instance boss like Brutallus where raid dps has to be higher than you can do and the boss can be disarmed, it’s pointless. 

https://deadgoodtanking.wordpress.com/2009/11/
3. Improved Disarm = Disarm is too situational, despite the talent looking nice on paper. Two points wasted.

**Comment by NeonicSupersonic** [comment]
Classic

https://forum.nostalrius.org/viewtopic.php?f=36&t=16057
Disarm
When you get into raiding most bosses are immune to disarm but it can still be useful when tanking a large number of trash mobs or hard hitting trash mobs in BWL.

I havent found direct conformation, but only mentioned usage of disarm in tbc I stumbled upon in my research was disarming Attunemen in kara (based on single comment which as well might be wrong since kara is entry raid open to all kind of people who are easy to impress) and adds on Muru in swp(well, duh, they are not bosses).

**Comment by Lyn3452** [comment]
For a experienced Warrior Player i have to add that the Disarm works on a lot of bosses that dont have weapons. That is true. Some of them are not dealing less damage (Alar, disarmable but no dmg reduce) even when disarmed and some bosses (f. e. Morogrim Tidewalker) are getting reduced damage. Bosses deal disarmed like 10% of their normal damage then and after that duration the worse bug happens, that the boss deals exactly 1 dmg for approximetaly 10 secs (Not 100% sure how about the exact length). So when u have like 3 Warriors you can make bosses deal absolutely zero damage in fights, which make fights boring easy and complete broken. (BTW @NeonicSupersonic Gruul is not disarmable so some bosses have a disarm flag, i think magtheridon has the same). But i think every T5 Boss and i even think every Hyjal Boss at our testing are disarmable (Only Kazrogal and Azgalor should be possible to effecitevely disarmable)
