### ISSUE TITLE
Quest: Hellfire Fortifications Unavailable

### ISSUE THREAD

**Issue by whabt** [SunwellWoW/Sunwell-TBC-Bugtracker#4502]
Description: I am unable to get the pvp daily quest Hellfire Fortifications from Battlecryer Blackeye.  Character name is Sporkus, Horde, Orc hunter.

How it works: When interacting with Battlecryer Blackeye, NPC does not have a quest gossip option, she opens directly to the vendor window.  She does not have a blue question mark above her head.  

How it should work: NPC should have a gossip option to either present the pvp daily quest Hellfire Fortifications or to go to the vendor window.  Other players report that the quest works for them.

Source (you should point out proofs of your report, please give us some source): Other players are currently able to retrieve the quest.

I have tried everything I can to rule out an issue on my end, from deleting wdb/wtf, disabling all add ons, and even unpacking a fresh client and logging in with that.  The quest is in not visible in my log.  My reputation with Thrallmar is 999/1000 exalted. I was able to get the quest once after hitting exalted, the day after completing it is when this behavior began. (it's been a couple weeks now)  I have put in two GM tickets and the most previous one directed me to put this in the bug tracker.  Thanks for all your help, please let me know if any further info would be helpful.

**Comment by koostosh** [comment]
At the begining of TBC this quest was not available on exalted reputation, it was changed later but it is hard to pinpoint exact patch.
Quest should be available after next update
