### ISSUE TITLE
Scholomance - Felcloth bag not learnable

### ISSUE THREAD

**Issue by RPAncap** [SunwellWoW/Sunwell-TBC-Bugtracker#4509]
Description: 
In scholomance when you kill Jandice Barov a book spawns that when you click on it you learn to craft https://db.excalibur.ws/?item=21341. (all tailors in party should be able to learn it)

How it works: 
The book spawns properly but it is not clickable so you cant learn to craft it.

Source (you should point out proofs of your report, please give us some source): 
![Screenshot 2019-04-13 15 32 48](https://user-images.githubusercontent.com/44553524/56080870-c639c400-5e06-11e9-9f78-8dc282097e0f.png)

https://www.wowhead.com/item=21341/felcloth-bag#comments

**Comment by Dootz** [comment]
Hi, you can pick it up from one spawned near her original spawnpoint.
