### ISSUE TITLE
[Spell] Frightening Shout

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#451]
Frightening Shout spell is instant aoe fear that is casted by several creatures and bosses in whole Azeroth (ids on screen).
It works fine in the end but there is one problem from players pov. There are two "Fear" debuffs each cast when there should be only one. It may bug such spells like Fear Ward, Tremor Totem etc.

![image](https://user-images.githubusercontent.com/22802214/45841926-89e43080-bd1b-11e8-8354-c4979ff16ec0.png)

**Comment by akrom23** [comment]
They are different spells.
19134 Frightening Shout - casts on area targets, make them to fear.
29544 Frightening Shout - is the proc effect of spell 19134. When the mob is taken damage, he casts that on primary target.
