### ISSUE TITLE
[item] [profession] [loot] profession-exclusive recipes are rollable for everyone

### ISSUE THREAD

**Issue by westerngee** [SunwellWoW/Sunwell-TBC-Bugtracker#4512]
Description: Profession-exclusive recipes are rollabe for everyone in this last Shadow Labyrinth run I attended.

How it works: Both Blackheart The Inciter and a random trash mob dropped exclusive recipes (in the latter case, screenshot provided, in the former case it was the leatherworking recipe for Stylish Purple Hat). We had neither a Leatherworker nor a Blacksmith with us.

How it should work: Normally, these recipes shouldn't even have been visible, not even mentioning rollable for us so I guess it's just a flagging-thing.

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_041419_063132](https://user-images.githubusercontent.com/39277340/56093436-25f8a380-5ec9-11e9-859f-c9ffdd264232.jpg)

**Comment by Wojtyas** [comment]
@akrom23 I believe its fixed?
