### ISSUE TITLE
Seal of justice broken

### ISSUE THREAD

**Issue by Atrecom** [SunwellWoW/Sunwell-TBC-Bugtracker#4513]
Description: Seal of Justice doesnt remove speed bonuses.

How it works:

How it should work: Should remove bonus

Source (you should point out proofs of your report, please give us some source):
cant. thx

**Comment by koostosh** [comment]
Works as intended.
This skill does not remove speed bonuses, only prevents from moving faster than normal speed.

**Comment by Atrecom** [comment]
Well. if u think is works so...it`s a pity. It should remove bonus from travel mode or ghost wolf. will retest it later. cmon

**Comment by Atrecom** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4515

**Comment by Atrecom** [comment]
Read this too before close.

**Comment by koostosh** [comment]
@Atrecom you provided no explanation what the hell you mean. There is difference between removing buff and reducing speed.
