### ISSUE TITLE
Judgement of Justice not working

### ISSUE THREAD

**Issue by Pikseh** [SunwellWoW/Sunwell-TBC-Bugtracker#4515]
Description: Judgement of Justice does not limit a player's movement speed to 100%, meaning that a player that is for instance judged with Judgement of Justice still moves at 200% if they are mounted or 140% if they use Travel Form or Ghost Wolf.

How it works: See description

How it should work: See description

Source (you should point out proofs of your report, please give us some source):

**Comment by Atrecom** [comment]
O RLY? they closed my post as invalid. duuuude

**Comment by Pikseh** [comment]
> 
> 
> O RLY? they closed my post as invalid. duuuude

Technically your report was wrong though. Any speed increasing buff should not be removed by Judgement of Justice, it's just that its effect should not work above 100% speed. Like, if you use Judgement of Justice on a druid that then uses Travel Form, they go into the form, but will never move above 100% speed while Judgement of Justice lasts.
