### ISSUE TITLE
HYJAL: Anetheron hitting random targets in melee after swam casts

### ISSUE THREAD

**Issue by jowns** [SunwellWoW/Sunwell-TBC-Bugtracker#4518]
Description: Anetheron is hitting random targets in melee after he cast Carrion Swarm sometimes. Is this a part of the "slightly buffed" shitfest or a bug? Its not mentioned in the forum post about the buffs

**Comment by username-is-not-taken** [comment]
![anetheron](https://user-images.githubusercontent.com/45629295/56165030-3e081a00-5fd2-11e9-95d8-6fdbf742665c.png)

great fun

**Comment by NeonicSupersonic** [comment]
Its a bug. Same happened on Solarian before she were fixed, and back then she did melee swings between missiles channels (no interrupts) . Could be mitigated if melee runs out of melee range on wave timer, but still shouldnt be like that.
