### ISSUE TITLE
[Dungeon] Sethekk Halls

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#452]
[Normal]

Trash:

- [x] Avian Warhawk should patrol the area instead of standing still, when engaged does not use Sonic Charge ability. 
- [] NOTE: Trash packs that have multiple Avian Rippers should have 1 Avian Warhawk as their leader.

- [x] Sethekk Talon Lord not using Avenger's Shield ability.

- [x] Sethekk Ravenguard missing Dual Wield passive ability (DW IS FIXED NOW), when engaged uses Enrage but not properly, when 1 Ravenguard is killed the other one should Enrage, right now both of them Enrage when 1 Ravenguard gets on low health.
NOTE: They always come in pairs, right now some of them are put in wrong packs for example one group has 1 Ravenguard 1 Oracle and 1 Shaman while other group has 1 Ravenguard and 1 Shaman. Currently there are way more Ravenguards in dungeon than there should be, should be 3 pairs maximum.  First two immediately after the first boss (Darkweaver Syth) and the others are posted by doorways in the next couple of rooms. 
 There are no Sethekk Guards at all in first part of dungeon and it seems Ravenguards are put in their place instead because in second part of dungeon pairs of Sethekk Guards are where Ravenguards should be.

- [x] Sethekk Guard missing from proper locations and in trash packs (Ravenguards are put in their place currently).

- [x] Sethekk Shaman doesnt cast Summon Dark Vortex.  Only few of them can be found in dungeon, packs that have 2 Sethekk Prophets should prob have 1 Prophet and 1 Shaman instead.

- [x] Dark Vortex should use Shadow Bolt.

- [x] Sethekk Initiate missing from proper locations and in trash packs (Ravenguards are put in their place currently). Should use Sunder Armor and Spell Reflection.

- [x] Avian Darkhawk missing from proper locations and in trash packs (Avian Warhawks are put in their place currently).

- [x] Time-Lost Controller missing from proper locations and in trash packs (Time-Lost Shadowmages are put in their place currently), should use Shrink and Summon Charming Totem. 
- [x] EDIT Charming Totem is not using its Charm (Spell ID 35120) spell and is vulnerable to spell damage while it should be immune to all magic. 

NOTE Area before first boss should have Avian Darkhawk, Sethekk Guard, Sethekk Initiate, Sethekk Oracle, Time-Lost Controller, right now it has Avian Warhawks, Ravenguards and other wrong types of mobs.

- [x] Time-Lost Shadowmage does not use Shadow Missile.

- Time-Lost Scryer does not cast Arcane Destruction on allies.

- [x] Sethekk Prophet put in wrong locations, should use Fear.

- [x] Sethekk Spirit these should spawn when Sethekk Prophet dies but currently they are spawned by default and prob taking place of some other mobs. Should be invulnerable and untargetable but have slow movement speed and use Spirit Burst with each melee attack. Dies after certain amount of time.

- [x] Avian Ripper missing from proper locations, should use Flesh Rip.

- [x] Cobalt Serpent missing from proper locations, should use Frostbolt, Lightning Breath and Wing Buffet and be immune to all CCs.
- [x] NOTE: Cobalt Serpent is using Frostbolt too often and not going into melee range between Frostbolts after using Wing Buffet or if his target is attacking from range.

Bosses:

- [x] Darkweaver Syth 
Syth Fire Elemental is using Arcane Buffet instead of Flame Buffet.

- [x] Talon King Ikiss does not cast Polymorph and his Arcane Explosion seems to be on a random timer instead of 80%, 50%, and 25% health.
NOTE: Missing his voice lines.

[Heroic]

Trash:

- [x] Sethekk Guard base damage should be 6200-8400.

- [x] Sethekk Initiate base damage should be 2250-3200.

- [x] Avian Darkhawk base damage should be 2400-3400.

- [x] Time-Lost Controller base damage should be 1061-1540.

- [x] Sethekk Oracle base damage should be 1100-1600. Arcane Lightning for 5025-5900.

- [x] Sethekk Ravenguard base damage should be 6200-8600. Missing Dual Wield passive ability. Should be immune to all CCs on heroic. Enrage same issue as on normal.

- [x] Time-Lost Scryer base damage should be 1633-1981. Arcane Missiles for 2000-2200 (currently its around 690), not casting Arcane Destruction or Flash Heal and Rejuvenation, should be Flash Heal for 5800-6600 and Rejuvenation ticking 780-810. NOTE: Not using any abilities in Heroic.

- [x] Time-Lost Shadowmage base damage should be 1400-1800. Not casting Shadow Missile.

- [x] Sethekk Shaman base damage should be 1800-2450. Earth Shock for 2600-3550.

- [x] Dark Vortex base damage should be 1400-1800. Slightly stronger version of Shadowbolt on heroic. NOTE: When Dark Vortex is summoned level up animation and sound is seen and heard (this should be hidden), when summoned Dark Vortex goes into melee range and doesnt autoattack or use Shadowbolt at all.

- [x] Sethekk Talon Lord base damage should be 3100-4600.

- [x] Sethekk Prophet base damage should be 1480-2240.

- [x] Sethekk Spirit base damage should be 3200-3800. NOTE: Not summoned upon Sethekk Prophet's death.

- [x] Avian Warhawk base damage should be 2400-3400.

- [x] Avian Ripper base damage should be 500-700.

- [x] Cobalt Serpent base damage should be 6150-8350. Should use Lightning Breath for 3600-3800, Wing Buffet for 2100-2800, Frostbolt for 1750-2150.
NOTE: Same issue as on normal.

Bosses:

- [x] Darkweaver Syth base damage should be 1200-1800. Chain Lightning for 2600-3050 (currently its ~1300).
Syth Fire Elemental is using Arcane Buffet instead of Flame Buffet.
Base damage for Syth Elementals should be 560-790.

- [x] Anzu base damage needs to be higher prob around 6000 (need more info), when engaged doesnt use Dive and Flesh Rip, Spell Bomb is used very rarely. During Banish phases he will still autoattack (this shouldnt happen) and not cast any spells, he should continue casting spells, also sometimes he will randomly interrupt his Banish while Brood of Anzu are alive, he should stop Banish only when all Brood of Anzu are dead.
- [x] Brood of Anzu base damage should be around 750, when engaged doesnt use Screech.

- [x] Talon King Ikis base damage should be 3252-4718. Should cast Polymorph on tank aswell in heroic.
NOTE: Missing his voice lines.

**Comment by Riztazz** [comment]
PTR updated again, please re-test.

EDIT: ToDo: add birds to packs
