### ISSUE TITLE
Shaman Talent Ancestral Awakening animation

### ISSUE THREAD

**Issue by cpypcy** [SunwellWoW/Sunwell-TBC-Bugtracker#4525]
Description: 
Ancestral awakening does not show ghost animation healing target

How it works: 
Instantly heals target without hovering ghost animation.

How it should work: 
It shows ghost animation 0.5s - 1.0s later and heal target.

Source (you should point out proofs of your report, please give us some source): 
Blizzard servers,

**Comment by koostosh** [comment]
Ancestral Awakening is WOTLK skill, i guess you used wrong bug tracker
