### ISSUE TITLE
Chain lightning Damage (Shaman)

### ISSUE THREAD

**Issue by bakfull** [SunwellWoW/Sunwell-TBC-Bugtracker#4529]
Description: 
Chain lightning does not do proper damage. i am recieving lower single target hits with chain lightning (770 to 880 at rank 6 which i am using) then i am with lightning bolt all though lightning bolt is supposed to have a lower damage (591-676 at rank 12 which i am using) 
Conclusion, Chain lightnings spell power scaling is off. (should be the same as lightning bolt and the cap comes from the reduced damage per jump.)

How it works: 
Chain lightning is doing less damage than lightning bolt which has a lower damage range. (single target)

How it should work: 
Chain lightning should perform way better than lightning bolt even on single hits.

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/2ad377602fbacf78e68f5354ff44fd77
https://gyazo.com/15099e6f24a56531b9b777fd56860ccf
https://gyazo.com/ba90be65a809ae720d267a721b6de0b7
https://gyazo.com/b9a8b441ad3fe6e8514a4eb4b26facb1

Linked screenshots show non crit damage and crit damage of both LB and CL (Lightning bolt and Chain lightning) on a "Incandescent Fel Spark" Fire elemental at lvl 71 (all testing done on lvl 71 targets)

**Comment by koostosh** [comment]
> Conclusion, Chain lightnings spell power scaling is off. (should be the same as lightning bolt and the cap comes from the reduced damage per jump.)

Source that chain lightning should have same coeff like lightning bolt?

**Comment by NeonicSupersonic** [comment]
You can check proper values with Dr.Damage addon, and afair cl supposed to be used as ranged cleave only since it has lower %spd coefficient compared to lb and therefore net dps loss on single target.

**Comment by koostosh** [comment]
LB is 2.5 sec base cast, should have 0.7134 coeff
CL is 2 sec base cast, should have 0.5714 coeff
Works as intended unless proven otherwise. Addon is not exactly a legit source of information
