### ISSUE TITLE
[Item] [Zone - any] [Vanilla Herbs respawntimers too way to long]

### ISSUE THREAD

**Issue by westerngee** [SunwellWoW/Sunwell-TBC-Bugtracker#4532]
Description: I do not base this on Nightbane/Angrathar/Mangocore stuff but on actually having played and farmed in Vanilla, still, this is, of course, highly subjective:
Respawn timers for a lot of important vanilla Herbs, namely Dreamfoil, Icecap and Gromsblood, take way too long. And I am not talking about the "fixed" multispawns here.
In the end that means no herbs are on the Auction house or only available at fantasy prices. Getting "healthy economy" system messages feels like a kick in the balls sometimes.
Maybe the problem is that they are linked into a bigger, how could I call it, node-respawn-area, similar to only-one-per-zone Black Lotus respawns in vanilla but on a smaller scale. There ARE multiple spawns of these herbs of course, but usually only one in a certain area and respawn takes 20 minutes and more.

Also on a related issue, the northern Azshara Peninsula seems almost completely devoid of ANY Dreamfoil at all, there are almost NO spawns (like in "nodes"). Azshara should be a paradise for Dreamfoil farming, but no one is ever there (I regularly check from my alliance characters and from my horde auction house alt), that is usually an indicator that there is nothing to gain from this zone.

How it works: It doesn't.

How it should work: More spawns

Source (you should point out proofs of your report, please give us some source): 
Nah, just increase spawns, please.

**Comment by westerngee** [comment]
Also compare it to Mountain Silversage or Golden Sansam spawns, which seem to be just right. Usually 1 node per spawn place and in a timely manner. I expected Dreamfoil, Icecap and Gromsblood on a similar spawn timer but that is not the case.

/edit: Purple Lotus, at least in Azshara, is on a too long spawn timer as well and there are too few spawns overall, too. Normally the Highborne Ruins in the west and in the center of the map (which are not directly submerged or on the beach) should have a few spawns but they hardly do or don't at all.

**Comment by NeonicSupersonic** [comment]
No, they arent. Nost isnt retail vanilla. Provide sources.

**Comment by westerngee** [comment]
> 
> 
> NeonicSupersonic commented LOL DIDN'T READ

I just said compare it to other herbs like mountain silversage, they respawn faster.

**Comment by NeonicSupersonic** [comment]
Mountain silversage is bugged and spawns at all available nodes at once instead of one of 2-3-5 nodes it can spawn from.
