### ISSUE TITLE
Steam vaults trash pulling separately

### ISSUE THREAD

**Issue by tharmon92** [SunwellWoW/Sunwell-TBC-Bugtracker#454]
Description:  Some of the trash packs in steam vaults pull separately 
How it works:  Pulling one of the trash pack mobs can lead to 1 or 2 mobs being pulled instead of all 4 or 5
How it should work: 
All mobs in a pack should pull.
Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/43470107/45877857-37336480-bd6d-11e8-9cb6-d62f135a58d2.png). 

Tested

**Comment by tharmon92** [comment]
![image](https://user-images.githubusercontent.com/43470107/45877985-87aac200-bd6d-11e8-826e-01621ce2d4cb.png)

**Comment by Riztazz** [comment]
re-test after ptr update

**Comment by Riztazz** [comment]
Gonna update PTR In an hour or so and it is ready for re-test, closing.
please open another ticket or write in this one if there are still issues
