### ISSUE TITLE
The state of the server?

### ISSUE THREAD

**Issue by paulmil1** [SunwellWoW/Sunwell-TBC-Bugtracker#4542]
looking now for a tbc server, couldnt find any info on the Sunwells, like nobody said anything about it in the last 6months, 
is the server up and running or the project has been abandoned?

**Comment by danbada** [comment]
Same question today 26.07

**Comment by Azathothh** [comment]
It's best to join discord to ask such questions https://sunwell.pl/discord ,bugtracker is not a place for that.
TBC server is up and running, but it was abandoned so don't expect to meet other players there
