### ISSUE TITLE
Slave pens

### ISSUE THREAD

**Issue by tharmon92** [SunwellWoW/Sunwell-TBC-Bugtracker#456]
Decription:  The slave pennsss

Source (you should point out proofs of your report, please give us some source): 

![image](https://user-images.githubusercontent.com/43470107/45878567-81b5e080-bd6f-11e8-922e-43d6a9a58803.png) 

- [x] should be: Group patrols
actual: stands in one place

![image](https://user-images.githubusercontent.com/43470107/45878596-a447f980-bd6f-11e8-8cda-2b0f0e4ac823.png)

- [ ] should be: Moves at normal speed.
actual: usuain bolt

![image](https://user-images.githubusercontent.com/43470107/45878679-f8eb7480-bd6f-11e8-845f-a95d79010668.png)

- [x] should be: these mobs pull separate
actual: pulls as one big group.

![image](https://user-images.githubusercontent.com/43470107/45878772-4bc52c00-bd70-11e8-8b4d-ba2a055056bd.png)

- [ ] should be: these mobs should pull together
actual: pulls separately

![image](https://user-images.githubusercontent.com/43470107/45878798-639cb000-bd70-11e8-81c4-3c5afadec676.png)

- [x] should be: mobs patrol without stopping
actual: mobs stop while patrolling.

![image](https://user-images.githubusercontent.com/43470107/45878827-79aa7080-bd70-11e8-842b-54b29583821d.png)

- [x] should be: boss patrols
actual: boss stands here :(

![image](https://user-images.githubusercontent.com/43470107/45879077-2d136500-bd71-11e8-8257-ae1d92b8d050.png)

- [x] should be: moves nice and slow
actual: usain bolt

![image](https://user-images.githubusercontent.com/43470107/45879152-677d0200-bd71-11e8-8671-7607ba8c65e0.png)

- [ ] should be: 1. Doesn't get stuck in wall
2. uses poison more often? 
Actual: Gets stuck in wall
2. rarely uses posion mostly auto attacks

**Comment by Riztazz** [comment]
1. not true https://youtu.be/fJIOe9RObsk?t=142

3. not true, they always were linked together on retail

4. that's also not true, i remember pulling one of them from the side

5. because he is chasing you, he should move out of the water slowly which isnt implemented and gonna fix
