### ISSUE TITLE
[Hellfire Quest] Drill the Drillmaster - Enhancement

### ISSUE THREAD

**Issue by Nadiirr** [SunwellWoW/Sunwell-TBC-Bugtracker#46]
Decription: 
Mob's Knockback knocks you so far back the mob resets. Hard to complete quest.
Drillmaster Zurok
GUID: 68898

How it works: 
Mob knocks you back and then will generally reset because you are too far away.

How it should work: 
Mob should have a larger range where he can go so his knockback will not reset him as easy.

Source (you should point out proofs of your report, please give us some source): 
Proof of knockback in wowhead comments. 
http://www.wowhead.com/quest=10937/drill-the-drillmaster#comments

**Comment by Riztazz** [comment]
Please test after restart
