### ISSUE TITLE
Hunter pet - Numerous issues.

### ISSUE THREAD

**Issue by tharmon92** [SunwellWoW/Sunwell-TBC-Bugtracker#461]
![image](https://user-images.githubusercontent.com/43470107/45899024-c78f9a80-bda9-11e8-969d-b7f0bd813acb.png)

- [ ] 

should be: Pet returns to hunter after killing mob.
Actual: pet stands where the mob died

- [ ] 

should be: Pet passive pulls hunter pet back to owner.
actual: Pet passive mode does not

- [ ] 

should be: pet passive stops hunters pet from charging at a mob
actual: hunters pet charges in and cant be stopped (Leeroy)

- [ ] 

should be: hunters pet gains experience when killing mobs
actual: hunter pets does not level up? not 100% sure about this may have been my fault from leveling char up with command.

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC/commit/2b71d87d6b3d5a5645621958f3d9bd11d08b1b3c

Please recheck after the update and give followup about remaining issues if any

**Comment by tharmon92** [comment]
Will do I'll be on tomorrow

**Comment by tharmon92** [comment]
Still seeing issues with passive @lukaasm .

**Comment by tharmon92** [comment]
Passive properly works now to pull pet back.
