### ISSUE TITLE
[Hunter][Mobs][Spell] Freezing Trap doesn't work with mobs out of combat

### ISSUE THREAD

**Issue by Patrulek** [SunwellWoW/Sunwell-TBC-Bugtracker#465]
Decription: 
Place a trap in mob path but dont aggro mob. When mob step into trap, it disappears, but mob doesn't freeze. It looks like Evading behavior, but there's no info about, and you dont get a combat even for a short amount of time. Works for neutral and aggressive mobs.

How it works: 
As above.

How it should work: 
Mob should get cc and start combat.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@Patrulek Cannot reproduce. Some screenshots, please.

**Comment by Patrulek** [comment]
Here you go: https://streamable.com/opdkk

Ps. why cant i just comment this issue? (only "Close and comment" option is active)
