### ISSUE TITLE
[Core] Death?

### ISSUE THREAD

**Issue by dredd-sunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#466]
Decription: It occured only once. I was in a group, doing Maraudon. When I died, characters from my group disappeared, mobs disappeared too. After a while, one mob showed up and he was attacking invisible member of my raid. Only I had this problem. I have no screenshots or videos, so if anyone experienced similar issue, please comment on this issue

**Comment by Wojtyas** [comment]
Feel free to reopen if happens again.
