### ISSUE TITLE
Hellfire Ramparts : Hellfire Watchers renew heals for 7k

### ISSUE THREAD

**Issue by worugru** [SunwellWoW/Sunwell-TBC-Bugtracker#467]
Decription: 
The "adds" of the first boss of hellfire ramparts and normal mode, casts renew as usual but renew ticks for 7k

How it should work: 
It should heal much less

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/tyzaFfl

**Comment by Riztazz** [comment]
can be re-tested after PTR update, closing as it is minor and it was a typo :P
