### ISSUE TITLE
[Warlock] Soul Link 

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#469]
Decription: Second part of spell that increases damage by 5% is not working for demon.

How it works: Soul Link part that increases damage done doesnt increase damage done by affected demon aswell.
![image](https://user-images.githubusercontent.com/42102450/45918764-13b30b80-be8c-11e8-8449-34c4aa6926ce.png)
![image](https://user-images.githubusercontent.com/42102450/45918765-1d3c7380-be8c-11e8-8f22-4ac580bb2139.png)
![image](https://user-images.githubusercontent.com/42102450/45918772-2f1e1680-be8c-11e8-9e5f-670a75a7b7c1.png)
![image](https://user-images.githubusercontent.com/42102450/45918774-347b6100-be8c-11e8-8c14-c2684b690ab1.png)
![image](https://user-images.githubusercontent.com/42102450/45918777-3ba26f00-be8c-11e8-9ba2-0275fb90970a.png)
![image](https://user-images.githubusercontent.com/42102450/45918778-40672300-be8c-11e8-833a-6bd6c6b50876.png)

How it should work: It should increase all damage done by both master and demon.

Source (you should point out proofs of your report, please give us some source):

**Comment by doomnyx** [comment]
can confirm, not working.
