### ISSUE TITLE
[Combat] Combat reset

### ISSUE THREAD

**Issue by dredd-sunwell** [SunwellWoW/Sunwell-TBC-Bugtracker#470]
Decription: When fighting in a group, when your target dies, you get out of combat. Even if you are being healed by a healer (that is in combat), you still won't be put in combat, even though other group members are in combat. This allows, for example, a rogue to Stealth every single kill (stealth->ambush).

How it works: ^

How it should work: When your group is in combat, you should stay in combat too. Combat shouldn't fade when your target dies

**Comment by akrom23** [comment]
Some screenshots?

**Comment by akrom23** [comment]
@dredd-sunwell Some screenshots/video? Cannot reproduce.
