### ISSUE TITLE
Jumping while Teleporting causes Death.

### ISSUE THREAD

**Issue by Nadiirr** [SunwellWoW/Sunwell-TBC-Bugtracker#476]
Jump through a portal that teleports you to a lower position and you will die. 

Tested in Stormwind mage portal and Teldrassil. 

![screenshot_111](https://user-images.githubusercontent.com/36300104/45924093-aa42f500-beab-11e8-9e84-65f75d124f5c.png)

**Comment by Nadiirr** [comment]
Yes I can get it to work over 50% of the time. Only when going from higher elevation portal to lower elevation portal.

Here's a video:
https://youtu.be/8K816B9_cBM
(Currently uploading video - might take 5 minutes)

**Comment by akrom23** [comment]
Could you logout and then try it again?

**Comment by Nadiirr** [comment]
Yeah. I tested it a few more times.

Here is a more detailed way to reproduce:

1) Start at the higher portal.
2) Jump through the portal
3) After you jump and are get teleported don't move. 


I can reproduce 100% of the time when I don't move after teleporting.

**Comment by akrom23** [comment]
I cannot reproduce it in any way you described.

**Comment by Nadiirr** [comment]
Here's another video of it happening.
I think it happens when your character does not move after going through the portal because I can reproduce without jumping as well.

https://youtu.be/XkakDYCY4BU
(Video uploading ETA 15m)

**Comment by akrom23** [comment]
Okay.

**Comment by akrom23** [comment]
Please, re-test after update PTR.

**Comment by notsofamous** [comment]
It sometimes happens when I teleport up.

https://i.gyazo.com/74c488a77dea6a91858b8aab84cef6ee.mp4
https://i.gyazo.com/9af0759af87969e801991c1059223f58.mp4

**Comment by Nadiirr** [comment]
Can confirm. 
It works now <3
