### ISSUE TITLE
Weapon/Armor proficiency

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#478]
Decription: 
There's a bug on item tooltips so it appears that you may be able to equip an item. The text where it says the type of armor or weapon type should be red if you cannot equip it. You cannot actually equip it so it's just a tooltip error.

The level proficiency shows up in red as it should.

Source (you should point out proofs of your report, please give us some source): 
How it looks:
![Image](https://i.gyazo.com/336be01bdd9460efaee2fbd2c04b9f4c.png)

How it should look:
![Image](https://i.gyazo.com/d1e1f2b658bdc61ac7b79b9558caf634.png)

**Comment by akrom23** [comment]
Maybe just visual? Clear cache folder?

**Comment by notsofamous** [comment]
Remains the same after clearing cache.
