### ISSUE TITLE
Fighting under water

### ISSUE THREAD

**Issue by Hnidka** [SunwellWoW/Sunwell-TBC-Bugtracker#480]
Decription: If u pull mob under water and swim to water level mob will stay under water and stop attacking u...

![wowscrnshot_092318_212549](https://user-images.githubusercontent.com/42386888/45932196-19d2e600-bf79-11e8-9dc7-ca4a9497c13c.jpg)

![wowscrnshot_092318_212753](https://user-images.githubusercontent.com/42386888/45932199-1b9ca980-bf79-11e8-88cd-23c039d64f5d.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented (only SSC realm so far).
