### ISSUE TITLE
Horde spawning at the alliance GY

### ISSUE THREAD

**Issue by tharmon92** [SunwellWoW/Sunwell-TBC-Bugtracker#482]
![image](https://user-images.githubusercontent.com/43470107/45932941-84246000-bf52-11e8-88c6-8ab22eb9b860.png)

While running hellfire ramparts I died inside on a horde character and spawned at the honor hold GY.

**Comment by notsofamous** [comment]
I think it's the same problem in Zangarmarsh, horde spawns at Telredor GY instead of Zabra'jin when they die inside an instance.
