### ISSUE TITLE
Hellfire ramparts testing.

### ISSUE THREAD

**Issue by tharmon92** [SunwellWoW/Sunwell-TBC-Bugtracker#483]
General:

- [x] Should be: Changing from heroic to regular changes all of the mobs inside to the regular level / values.
Actual: Changing from heroic to regular didn't change the mobs to the correct state.

![image](https://user-images.githubusercontent.com/43470107/45933354-eda76d00-bf58-11e8-8dde-3dd94c5530bd.png)

- [x] should be: this mob has a patrol distance that doesn't aggro at the door when you zone in
actual: mob will patrol up close enough to the door to pull when just zoned in.

![image](https://user-images.githubusercontent.com/43470107/45933397-c00ef380-bf59-11e8-962c-5003ed6ae990.png)

- [x] should be: mob moves around the corner to shoot you.
actual: mob stands there and waits for you to turn the corner before he can shoot you.
--NADIIR EDIT-- Same as #388 

![image](https://user-images.githubusercontent.com/43470107/45933509-85f32100-bf5c-11e8-94c7-a68eaced9f37.png)

- [x] Not sure if this is a bug or not sure seems like it though check chat. Spamming heal me quick after healers have died for first boss in hellfire ramparts.

- [ ] **Final boss and 2nd boss in hellfire ramparts heroic may need to be tuned up a bit as far as damage values go. More testing is needed to determine.

**Comment by Riztazz** [comment]
Seperate ticket for last issue please
