### ISSUE TITLE
Character not adjusting after strafe/turn

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#485]
**How it works:** 
The character will not properly adjust his facing after turning or strafing. It's reset properly if you jump.
https://i.gyazo.com/96f5932137618e5c7fcf72540cd1fa33.mp4
https://i.gyazo.com/4d5f94c3f0fbdd7b4d23578e3e0c8dec.mp4

**How it should work:** 
The character should be facing forward again after strafing or turning.
https://i.gyazo.com/d6a58df4c2bb814f181bac4cbe2d1b8f.mp4
https://i.gyazo.com/4b8465f288d4902d1092c6e11b079e43.mp4

**Comment by notsofamous** [comment]
Seems to be race specific issue. 

Undead male is broken completely
Tauren male adjusts very slowly
Troll male adjusts very slowly
https://i.gyazo.com/964288401af5a81c8001a9a3f6c78ff5.mp4
Blood elf male adjusts very slowly
Blood elf female adjusts very slowly
Orc male very slow
Orc female very slow
Humale female slow
Dwarf male slow
https://i.gyazo.com/033697182b861086fc51a423862c6b9d.mp4
Dwarf female very slow
Night elf male very slow
https://i.gyazo.com/6cccdcd400d258b346002092a64c43ac.mp4
Night elf female very slow
Gnome male slow
Gnome female slow

Sometimes it takes 10+ seconds for them to adjust after a strafe. Makes the game appear very unresponsive.

Both draenei genders are fairly responsive
Male https://i.gyazo.com/6320c50d70c0ff44bd53a5f3f90d37ee.mp4
Female https://i.gyazo.com/7343111bc8eaaf48e06ef7e22a083f6a.mp4

Works:
Tauren female
https://i.gyazo.com/66bf0a9c2ad0b4e8364f03740facda32.mp4
Troll female
Human male
Undead female
https://i.gyazo.com/313b4294bdf2974e567d963f9ae827b5.mp4
Draenei male

**Comment by notsofamous** [comment]
Zone specific issue? something with mapping?

In stormwind it works just fine, while in some zones the character won't adjust at all.
https://i.gyazo.com/f5ca07269d2a52621ee3162886d60070.mp4

**Comment by akrom23** [comment]
Videos from `How it should work:` made on TBC?

**Comment by notsofamous** [comment]
Yes. If you test it on an undead male character in hellfire/nagrand for example, it's completely broken. Then if you try it in shattrath it works fine. There's something really funky going on.
