### ISSUE TITLE
[Engineering] Mote Extractor does not work.

### ISSUE THREAD

**Issue by Nadiirr** [SunwellWoW/Sunwell-TBC-Bugtracker#492]
Decription: 
Using Mote Extractor on clouds does not work.

How it works: 
It says "you have no target"

How it should work: 
It should extract materials from the cloud.

To reproduce:
1) Get engineering and the items you need:      
.add 23762
.add 23821
.learn 30350
.setskill 202 375
Equip the Helm so you can see items on map.

2) Find a cloud. One is in screenshot below. It's way up in the air on the platform.
3) Try to use the [Zapthrottle Mote Extractor] on the cloud and it does not work.

P.S. the .gob near command returns nothing. Maybe it's a problem with the object not being there.

![screenshot_117](https://user-images.githubusercontent.com/36300104/45939481-ac7a8180-bf87-11e8-81c2-bd8e74268b5b.png)
![screenshot_116](https://user-images.githubusercontent.com/36300104/45939482-ad131800-bf87-11e8-84a1-3ce477e212d4.png)

**Comment by notsofamous** [comment]
Still doesn't work, same error as before.

**Comment by lukaasm** [comment]
Yeah, I believe its not live on PTR yet

**Comment by Nadiirr** [comment]
Works perfect. 
<3
