### ISSUE TITLE
Imp not attacking in defensive stance

### ISSUE THREAD

**Issue by Derpyous** [SunwellWoW/Sunwell-TBC-Bugtracker#498]
Decription: 
The imp sometimes doesn't automatically attacking when engaging a target

How it works: 
Sometimes stands with fireball animation in its hands, but is not casting.

How it should work: 
It should cast.

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/182e096d8133678aa1440734d4d0321a

**Comment by notsofamous** [comment]
Seems to work now.
