### ISSUE TITLE
[Core] Step collision 

### ISSUE THREAD

**Issue by Haipethdev** [SunwellWoW/Sunwell-TBC-Bugtracker#5]
Description: 
Getting stuck going up some stairs: E.g: SI:7 entrance

How it works: 
Getting stuck while auto-running, having to jump to get up

How it should work: 
Not getting stuck.  Should be able to walk up without jumping

Source (you should point out proofs of your report, please give us some source): 
In game testing on char: Tyba

Common issue on cmangos based servers.  I have no idea whether it is due to the way they extract vmaps from client game files or if there is something else in the core handling collision incorrectly.

**Comment by siof** [comment]
If i remember correctly it's handled client side (server can check/alter user position but collisions are in general handled on client side) so probably there is nothing to do on core side.

**Comment by akrom23** [comment]
Yep - it's clientside. Blame it on Blizz.
Do you know servers that it works correctly?

**Comment by Haipethdev** [comment]
I was under the assumption that some collision detection, at least partially, got moved server side after vanilla due to players altering their clients to walk through walls in AQ40 (to avoid significant portions of trash).  I am also fairly certain that Felmyst handled the above behaviour correctly, as did retail.  I am checking with others as we speak, if they can't confirm then by all means close this.

Several servers with this problem also have the same issue under the bridge on Blades Edge Arena.  I am almost certain that this was not the case on retail and on Felmyst.  It will result in players, and pets, which is far worse) getting stuck in arenas which is obviously not good.

**Comment by akrom23** [comment]
There is possibility that
