### ISSUE TITLE
some kind of bug i guess

### ISSUE THREAD

**Issue by dragomir222** [SunwellWoW/Sunwell-TBC-Bugtracker#504]
Decription: I opened one of the door in deadmines, tried to cast my spells on npcs, who were on the other side on the door and I was in line of sight, even though the door was open and the npcs were in front of me

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/500
