### ISSUE TITLE
NPC pets.

### ISSUE THREAD

**Issue by Moistcookie** [SunwellWoW/Sunwell-TBC-Bugtracker#508]
Decription: NPC pets have a lot more health than usual.

How it works: I've notice most NPC pets have around 3600 health or a lot more health than usual, like the voidwalkers in RFC have 3602 health when usually they should have really low health and be like 3 shotable. 123

How it should work: I would keep an eye out for all NPC pets in the game and see if their values are correct for future fixes. Not all mobs should be like this, but RFC is a good example of pets having too much health.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Need proofs.
