### ISSUE TITLE
Mage Blink - vanish player for around 2 secounds

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#509]
Decription: 
**ENG:** Mage after finish blink is additionaly desapeir for like 1-2 secunds. This kind of animatios is used to Invisibility Mage skill. Its looks like mixed animation Blink + invisibility mixed to blink. 

**PL:** Mag po użyciu blinka dodatkowo na jakieś 1-2 sekundy znika. Podobne zachowanie jak w przypadku użycia przez invisibility, Wygląda to tak jak by ktoś podpiął pod blinka dodatkowo niepotrzebnie animacje i mechanike z invisibility.

Z punktu widzenia gracza za sterami Maga po blinku na 1-2 sekundy znika otocznie, co utwierwdza mnie w przekonaniu że mamy zmiksowane skille blink + invisibility.

How it works: 
Like in decription

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Bursztynek** [comment]
![11111](https://user-images.githubusercontent.com/43553985/45978625-1b6dde00-c04d-11e8-8e46-bc295b5bc8dd.jpg)
![22222](https://user-images.githubusercontent.com/43553985/45978636-1e68ce80-c04d-11e8-9031-2b1e01b643bf.jpg)

**Comment by Riztazz** [comment]
re-test please

**Comment by Bursztynek** [comment]
bug fixed.
