### ISSUE TITLE
Ragefire Chasm mob pull

### ISSUE THREAD

**Issue by AgrippinaMinor** [SunwellWoW/Sunwell-TBC-Bugtracker#510]
Decription: 
After pulling second patrol, other mobs flew over lava pools and attacked us.

How it works: 
Not replicated, but these mobs marked with white arrow on screenshot flew/swam over the lava to assist the group in front of us.

How it should work: 
These mobs are not supposed to aggro from this distance.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_092418_233839](https://user-images.githubusercontent.com/36504035/45980879-802c3700-c053-11e8-9659-b5ce58e569b2.jpg)

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/506
