### ISSUE TITLE
Inspiring Presence (draenei passive)

### ISSUE THREAD

**Issue by moemiki** [SunwellWoW/Sunwell-TBC-Bugtracker#511]
Decription: 
Passive ability what should give 1% hit to everyone within 30 yards

How it works: 
The "Buff" is not displayed. Don't know if hidden hit rating is added

How it should work: 
Draenei alone, and players within 30 yards within draenei's group should have a buff, which gives 1% hit

Source (you should point out proofs of your report, please give us some source):

**Comment by grand-lotus-iroh** [comment]
Does not show / appear on Mage either.
