### ISSUE TITLE
Neutral mobs attacking in packs

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#513]
Decription: For example Goretusks at GM Island

How it works: 
After attacking one Goretusk, all nearby come to his aid. It is common on enemy monsters, but not on neutral monsters.

How it should work: 
After attacking a neutral monster, only itself should join the combat, not his "friends"

Source (you should point out proofs of your report, please give us some source): 
Dredd saw it, he recommended me to report it here.

**Comment by akrom23** [comment]
Proof?

**Comment by Mikov1605** [comment]
cant show it on a screen shot, cuz it requires a video to proof. just trust me.
I will explain. There are for example 3 NEUTRAL Goretusks at GM island, close to each other, max 7 yards away from each other. I pull the middle one. He should come alone. But other two also come. This action would be normal on ENEMY mobs, but not on NEUTRAL ones like those Goretusks :)

**Comment by akrom23** [comment]
I meant the proof that this is bug - neutral mobs call for help.

**Comment by akrom23** [comment]
Everything works fine.
