### ISSUE TITLE
Mob cant swim

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#514]
Decription: 
Another problem by my, this time i have been followed by a Goretusk on GM Island. He evaded all my attacks. Plus, after running into water, he gone the way under water, instead swimmining. He just moved on the ground, UNDER the water.

How it works: 
Mob is moving on the ground under water instead swimming.

How it should work:
Mob should swim behind you. 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
#480
