### ISSUE TITLE
Warlock Pet stances

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#515]
Decription: 
Defensive Stance and Aggresive Stance are bugged.

How it works: 
My demon is on defensive stance, it should attack any mob that harms me, but it doesnt. Aggresive stance, he should attack any mob in sight, he actually doesnt .

How it should work: 
After a mob hits me while my pet is on def stance, my pet should immediately join the fight.
Agressive stance means the mob should auto attack any target i attack.

Source (you should point out proofs of your report, please give us some source):

**Comment by notsofamous** [comment]
NPC pets act the same, they won't attack you if you attack their master from a distance.

**Comment by doomnyx** [comment]
Retested:

- [ ] Passive works

- [ ] Defensive: pet attacks when gets aggro, same with master; should be: 
![image](https://user-images.githubusercontent.com/14941185/48736413-6f5f0280-ec4b-11e8-9311-b9adc1fd4b59.png)
that means it should "counterattack", take action only if attacked (or if master is attacked, not aggroed)

- [ ] Aggressive seems ok, minion attacks if in aggro radius, only hostile mobs, can start combat which is correct.

**Comment by Wojtyas** [comment]
Fixed & implemented.
