### ISSUE TITLE
Imp Fireball Animation

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#517]
Decription: 
Imp Fireball Animation bugs

How it works: 
Imp is casting fireball, the mob he attacks dies DURING the cast. After he fails to finish casting, the cast animation is still visible. He literaly moves while the cast animation is on.

How it should work: 
While Imps Fireball is cast, and the targeted mob dies, he should automatically stop casting, and also stop cast animation.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
The same problem as here: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/501
