### ISSUE TITLE
Entering Combat while in a Group

### ISSUE THREAD

**Issue by Espranty** [SunwellWoW/Sunwell-TBC-Bugtracker#518]
Decription: 
You dont actually get into Combat while in an Instance Group Except when u attack 
Furthermore , if ur group wipes and u only attack one mob , Rest of mobs will Reset, except the mob u were attacking .

How it should work: 
Entering Combat by any Raid /Dungeon member within a surtain Range should affect the whole Raid /Group .

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Proof?

**Comment by Riztazz** [comment]
What he meant is we're trying to figure out the proper rule for this one :P
