### ISSUE TITLE
Lvl 1 Creatures makes combat bug

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#519]
Decription: 
ENG:
While using skills like fear or demoralizing shout (skills with no dmg, but still making combat state) during fight. If in fight/ shout area is 1 lvl creature (like snake) it will give you combat bug. Its hard to figure out... coz creatures are small and dont atack you, and they stay as a "neutral".  

PL:
Podczas walki z mobami team używa Demoralizing shout / Demoralizing Roar / Fear , - czyli skilli które nie zadają dmg, ale powodują combat state... jeżeli obok właściwych mobow z ktorymi team walczy, kręci się creature 1 lvl (np. Snake) po zabiciu mobow na graczach zostaje combat bug. Ciężko to wyczuć... bo creatura pozostaje dalej jako neutral. 

Dodatkowa informacja - gdy użyje tego skilla bezpośrednio na 1 lvl creaturze, to nic się nie dzieje, problem występuje tylko gdy atakujemy normalne moby i międzyczasie napatoczy się 1 lvl neutralny mob. 

How it works: 
Jak wyżej.

How it should work: 
ENG: Creature 1 lvl neural, shoud atack the player if he will use skill on it.
PL: Creatura 1 lvl neutral, powinna atakować gracza, jeżeli ten użyje na nim skilla.

Source (you should point out proofs of your report, please give us some source): 

Combat bug - snake:
![combat bug - snake makes combat2](https://user-images.githubusercontent.com/43553985/46029187-0481c700-c0f3-11e8-9dcc-3945fe62dc03.jpg)

After killing Snake - Combat is over:
![combat bug - snake makes combat](https://user-images.githubusercontent.com/43553985/46029204-0fd4f280-c0f3-11e8-9107-6961cc5cf6a6.jpg)

**Comment by akrom23** [comment]
Cannot reproduce it with shouts.

**Comment by Bursztynek** [comment]
2 or 3 days ago i had same problem in SHH (Anzu run), so yes its does.

**Comment by akrom23** [comment]
So I need more info. Maybe some video? Maybe type ingame .debug hostile

**Comment by akrom23** [comment]
Any news?
