### ISSUE TITLE
[Shadowmoon Valley] Quests - Pathfinding - Spells.  (Horde side)

### ISSUE THREAD

**Issue by TBCKillshot** [SunwellWoW/Sunwell-TBC-Bugtracker#52]
Decription: 
I was asked to test Shadowmoon Valley zone with quests and all what comes with it and i came to 
conclusions.

1. As for mobs being incorrect in their path + not doing their spells list goes now:
- [x] Overlord Ol'Barokh does not stop walking when u want to take quest from him.
- [x] Kor'Kron Defenders can be seen on ground instead being in air and guarding area.. (Also can be seen standing in air with no animations).
- [x] Infernal Attackers do not show animation on ground as falling from sky and respawning a new one.(Sometimes u have to fly away and come back for them to even spawn).
- [x]  Felboards do not use their ability aka Charge to stun once u attack them. (They only do basic attacks).
- [x] Dark Conclave Hawkeye + Quest The Setkh 'lon Wreckage has a very,very low drop rate of the books once u kill around 50 to 80 mobs the all 3 books will drop.
- [x] Enraged Fire Spirit,Earth Spirit and Water spirit do not do their abilities as supossed and only use basic attacks.
- [ ]  Enraged Earthen Souls can be seen in area where there shouldn't be any also same goes for Airy souls.
- [x] Eclipsons and Conqueror's are not doing any of their designated abilities and rather use only basic attacks.
- [x] Chancellor and Morok the Mighty spawn at the same place with 2 yards distance and do not preform any of their designated abilities.
- [x] Illidari Watchers only use their basic attacks without using their abilities.
- [x] Uvuros does not do any of his abilities but rather only basic attacks.
- [x] Legion Hold Quest is a instant auto-complete instead of whole chain where ur put in a bag and watching the demon's talk.
- [ ] Frankly,It makes no Sense (Quest) Is not working,once u attempt to click on Arcano Control Unit to control one of scorpions nothing happens.
- [x] The Cipher of Damnation (Quest) - Has a very low drop chance after opening at least 30 boxes it dropped.
- [x] Painmistress Gabrissa - Does not preform any of her abilities rather just basic attacks.
- [x] Illidari Dreadbringers,Shocktroppers,Painlashers do not preform any of their abilities and rather use basic attacks.
- [x] Veneratus the Many - Does not use any of his designated abilities and does only basic attacks.
- [x] Parshah does not roam around as he is supossed to but stands rather in one place near rocks.
- [x] Makazradon is located in totally wrong place and does not move at all.
- [x] Morgoron move in one parameter of 3 yards and does not roam around the Infernals as he is supossed to.
- [x] Destroy Legion Hold Infernals (Quest) - After triggering the bomb in quest the Infernals do not dissapear as they should but still u get quest credit.
- [x] Dormant Infernals rather show up as fiery balls that sometimes avoid to be attacked.
- [ ] Elemental Displacer needed for quest causes server crash + huge rollback and needs fix asap.
- [x] Warbringer Razuun dosen't cast any of his spells.
- [x] Dark Conclave Ritualist only does basic attacks without using  his abilities,also his basic attacks do only 30dmg.
- [ ] (Quest)The Art of Fel Reaver Maintenance is completly bugged with mobs not appearing on proper location,we are able to enter infernals and they disspear(we shouldn't be able to even go in them),We are unable to control Fel Reavers,The location they are found is on completly wrong side from the one it is supossed to be.
- [ ] DoomWalker drops 2 Boe items after killed but has game breaking bug when he hits enrage phase,he hits for 30k+.
- [x] Mature Netherwings can be found standing in air and not flying as supossed (not every.)
- [x] Rocknail Rippers do not follow their normal path and rather climb up objects they are not supossed to.
- [x] Envoy Icarius does not cast any of his spells but rather uses basic attacks.
- [x] Cyrukh the Firelord does not use any of his abilities and spawns with a bit more hp then supossed.
- [x] Ruu'l the Darkener can be found at one spot sitting on his mount and on other side 50 yards away we can see his mount without him being on it . Aka it's a visual bug that needs a hotfix!
- [x] Also all of the mobs here above do not care about LOS and just go straight thru objects + Do not care about LOS.

How it should work: 
- [x] 2)Destroy Legion Hold Infernals (Quest) - After triggering the bomb all infernals should die and respawn in 1 minute.

- [x] 3)The Cipher of Damnation (Quest) Should have a bigger drop rate.

- [ ] 4)Frankly,It makes no Sense (Quest) - We should be able to control one of scorpions using the Arcano Control unit.

- [x] 5)Legion Hold Quest should not be autocomplete and we should fly up to edge of balcony and be hidden inside box looking a schematic of two demons talking.

- [x] 6)Quest The Setkh 'lon Wreckage - Should be increase drop chance ... It drops the total of 3 books on 80 mobs which means u need 3 full loops of killing those mobs with respawn timers .

- [ ] 7 ) Quest The Art of Fel Reaver Maintenance - Should be located where u take quest and not opossite side of it,also the control pannel should work so we can control reaver. Once u pick a key from doctor u cannot open chest cause there isn't any.
![wowscrnshot_080518_111820](https://user-images.githubusercontent.com/42093565/43684516-db980350-98a1-11e8-9090-28cd4489d994.jpg)
![wowscrnshot_080518_110949](https://user-images.githubusercontent.com/42093565/43684519-e8c74266-98a1-11e8-9a7c-f23cb9512269.jpg)
![wowscrnshot_080518_111004](https://user-images.githubusercontent.com/42093565/43684524-f4d68292-98a1-11e8-9922-98a1e3c1e26d.jpg)

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_080418_234832](https://user-images.githubusercontent.com/42093565/43681283-7083a0f8-984f-11e8-8ffb-b8373043cde5.jpg)
![wowscrnshot_080418_234913](https://user-images.githubusercontent.com/42093565/43681285-836d95de-984f-11e8-88ae-4044d558c169.jpg)
![wowscrnshot_080418_234920](https://user-images.githubusercontent.com/42093565/43681291-94f10d18-984f-11e8-940d-180c679504ee.jpg)
![wowscrnshot_080418_235009](https://user-images.githubusercontent.com/42093565/43681292-9e7f95b6-984f-11e8-9c41-dc57e5b40560.jpg)
![wowscrnshot_080418_235245](https://user-images.githubusercontent.com/42093565/43681298-ab1b030a-984f-11e8-9f33-625e1dc4ad28.jpg)
![wowscrnshot_080518_000457](https://user-images.githubusercontent.com/42093565/43681299-b69f8566-984f-11e8-9d6c-03e6f586b57a.jpg)
![wowscrnshot_080518_000924](https://user-images.githubusercontent.com/42093565/43681304-c3106252-984f-11e8-8a0b-d81c1db66aad.jpg)
![wowscrnshot_080518_003018](https://user-images.githubusercontent.com/42093565/43681310-d1839d72-984f-11e8-89a3-a803c98d688c.jpg)
![wowscrnshot_080518_003603](https://user-images.githubusercontent.com/42093565/43681311-d9b28986-984f-11e8-8ddf-b22b7ff60400.jpg)
![wowscrnshot_080518_004537](https://user-images.githubusercontent.com/42093565/43681314-eb5c4032-984f-11e8-867b-13d2d8debd67.jpg)
![wowscrnshot_080518_005143](https://user-images.githubusercontent.com/42093565/43681317-f53549e6-984f-11e8-8820-859195352a94.jpg)
![wowscrnshot_080518_004806](https://user-images.githubusercontent.com/42093565/43681319-00841412-9850-11e8-9009-8d46896b36c5.jpg)
![wowscrnshot_080518_005931](https://user-images.githubusercontent.com/42093565/43681321-0a36d09e-9850-11e8-9465-0a71bac26d8b.jpg)
![wowscrnshot_080518_112442](https://user-images.githubusercontent.com/42093565/43684547-63597eae-98a2-11e8-9c48-a977bb60a290.jpg)
![wowscrnshot_080518_171421](https://user-images.githubusercontent.com/42093565/43687356-d5980892-98d3-11e8-87d9-7d5493aabe7a.jpg)
![wowscrnshot_080518_171426](https://user-images.githubusercontent.com/42093565/43687359-dea20bae-98d3-11e8-8229-b5592b78677a.jpg)

**Comment by KimmoKM** [comment]
I guess I might as well leave my observations in the same issue.

## Mob placement, RP, visuals
* Bonechewer Messenger with his Marauder escorts stands around idle in Bonechewer  ruins at the Terokkar side of the zone border. They should be traveling into SMV and getting ambushed by Wrathwalkers.
* There are Infernal attackers not engaged with Alliance/Horde defenders
* There's Image of Warbringer Razoon next to current spawn location of Makazradon.

## Mob abilities
* Wrathwalkers don't Dual Wield or use their Flame Wave ability
* Felboars are missing their thorns-like ability. Moreover, in addition to the above observation, they were [very prone](http://www.wowhead.com/npc=21878/felboar#comments:id=273533) to charge any passerbys out of combat as well, a rather iconic feature of the zone.
* Felfire Diemetradons and Greater Felfire Diemetradons don't use their Flaming Wound ability.
* Uvuros can be CCd, he [should be immune](http://www.wowhead.com/npc=21102/uvuros#comments:id=55421)
* Legion Fel Cannon doesn't use Fel Cannon Blast ability
* Terrormaster doesn't use hits Fear and Cleave abilities
* Mo'arg Weaponsmith does not use Drill Armor and Chemical Flames abilities
* Overseer Ripsaw didn't use his Gushing Wound and Saw blade abilities
* Mutant Horrors don't use their Enrage and Mutated Blood abilities
* Morgroron doesn't use his War Stomp, Rain of Fire and Mortal Cleave abilities. Moreover, he should be [immune to CC](http://www.wowhead.com/npc=21500/morgroron#comments:id=33311)
* Makazradon doesn't use his Cripple, Rain of Fire and Fel Cleave abilities
* Wrathstalker doesn't use his Flame Wave, Cleave and Enrage abilities
* Prophetess Cavrylin isn't Dual Wielding or using her Melt Flesh or Chaos Nova abilities
* Shadow Council Warlocks don't use their Shadow Bolt or Drain Life abilities

## Quests
* Quest "To Legion Hold" does autocomplete as observed above, but if you do the quest, using the crate disguise still allows you to move and use abilities (see the item description).
* Overseer Ripsaw dropped two Illidari-Bane Shards

**Comment by Nadiirr** [comment]
Added checkmarks to make it easier.
