### ISSUE TITLE
No boss in The Wailing Caverns

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#520]
Decription: 
Jeżeli dobrze pamiętam to przy wodospadzie (Crag of the Everliving) powinien być boss Skum. Obecnie nie jest dostępny.
![wowscrnshot_092518_185751](https://user-images.githubusercontent.com/43553985/46030000-3b58dc80-c0f5-11e8-8a46-16a74aaa42c8.jpg)

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Bursztynek** [comment]
nie pamietam nazwy bossa, poczatkowo wydawalo mi sie ze Skum, ale nie inny jakis.

**Comment by Kokaina** [comment]
This boss is present in WC but not here :D All bosses are present. Will reopen in any case
