### ISSUE TITLE
Ressurection - after releasee spirit - bug

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#523]
Decription: 
Rezurekcja na ciele gracza który wszedł już w formę duszka (użył Release spirit), nie wywołuje żadnej akcji. Ponawialiśmy ressa kilka razy Mag (Agson) nic nie otrzymał. 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_092518_205313](https://user-images.githubusercontent.com/43553985/46036306-7d8a1a00-c105-11e8-8801-fbeebbdeeeec.jpg)

**Comment by Bursztynek** [comment]
ok, sorry, but i ask about this on Facebook massenger, and the answer was clear: 
![asdasd](https://user-images.githubusercontent.com/43553985/46037975-276ba580-c10a-11e8-90d7-043246bec221.png)

**Comment by akrom23** [comment]
Okay then :)
