### ISSUE TITLE
Mail item  - problem "You don't own that item."

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#524]
Decription: 
Like you see on the screen there was some problem with items, I had mail from "Customer Support" with two attachments. I can't pick up the item from mail. Communicate: "You don't own that item." 

![wowscrnshot_092518_220817](https://user-images.githubusercontent.com/43553985/46040234-0c039900-c110-11e8-8fe4-74064bbac637.jpg)

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Fixed after update.
@Bursztynek Unfortunately, these items are lost. Destroy them and buy.
