### ISSUE TITLE
Scholomance extravaganza of issues

### ISSUE THREAD

**Issue by Young991** [SunwellWoW/Sunwell-TBC-Bugtracker#525]
Heres alot of issues we found while running scholo

- [ ] Doors are re clickable.
- [ ] Packs in 3rd room not linking properly.
- [ ] The whole Jandice room pulls when Jandice is pulled.
- [ ] "The ravenian" boss adds are all linked together making the room close to impossible.

- [x] Spectral tutor not spawning clones after X amount of time.
- [x] Jandice clones are immune to magic.
- [x] Missing alot of Risen Constructs on basement.
- [x] Vectus and Marduk are missing.
- [x] Scholomance Occultist is not transforming into Shade.
- [x] Feels like Gandling is teleporting way too frequently.
- [x] Gandling doesn't yell "School is in session!" when you kill all minibosses.
- [x] Gandling does not pat around until engaged.

Testing team: Picketinaa, Comrade, Weaboo, Chupko, Young.

**Comment by Kokaina** [comment]
Really nice, thank you ;)
