### ISSUE TITLE
[Item] Deadly Poison - Question

### ISSUE THREAD

**Issue by Nadiirr** [SunwellWoW/Sunwell-TBC-Bugtracker#527]
Decription: 
Poison can't be applied to lower level weapons.

How it works: 
I try to apply a poison to a weapon and it won't work because of the "level requirement" 

How it should work: 
I think they should allow to be applied to lower level weapons. I think the level requirement of the poisons is for the character applying the poison - not the weapon level.

Source (you should point out proofs of your report, please give us some source): 
![screenshot_129](https://user-images.githubusercontent.com/36300104/46050744-aa7d0380-c0ea-11e8-8e5f-e67a7909a885.png)

**Comment by notsofamous** [comment]
https://youtu.be/k1t0A1cqGcw?t=4m50s

Video from vanilla of a rogue pvping naked with the starting dagger, he uses poisons on it. I don't think anything has changed in TBC.
