### ISSUE TITLE
Scarlet Monastery Library bug

### ISSUE THREAD

**Issue by ryredan** [SunwellWoW/Sunwell-TBC-Bugtracker#528]
Mobs glitching on the ceiling when they go close the entrance of the dungeon.
![wowscrnshot_092518_214909](https://user-images.githubusercontent.com/20247441/46051196-597f0680-c10e-11e8-94db-34a23cd73c8f.png)
![wowscrnshot_092518_214548](https://user-images.githubusercontent.com/20247441/46051197-597f0680-c10e-11e8-9e5f-c9bf64f8c3e1.png)

**Comment by Nadiirr** [comment]
Fixed. 
<3

**Comment by Exorcista** [comment]
Hmm, happened to us in Cath today.
