### ISSUE TITLE
Hunter trap delay

### ISSUE THREAD

**Issue by tharmon92** [SunwellWoW/Sunwell-TBC-Bugtracker#529]
After setting up any trap the delay between setup and activation seems to be too long. Setting a trap should almost instantly cause the mob ontop of the trap to be debuffed with a burn, slow or whatever it may be.

I've attached a random pvp video at 3:50 the hunter drops a trap and you can see the activation demonstrated.

https://youtu.be/NoKD723_yAM

**Comment by akrom23** [comment]
2 seconds if in combat? Source of this information?

**Comment by akrom23** [comment]
I fixed this 2 sec works only in combat. Out of combat  - it's instant.
Still needs info what traps make problems.

**Comment by baade123** [comment]
there should be a  3 second delay, there currently sometimes is NO delay, plz fix

**Comment by baade123** [comment]
for pvp reasons.
