### ISSUE TITLE
[Rogue][Talent]Shadowstep

### ISSUE THREAD

**Issue by Nadiirr** [SunwellWoW/Sunwell-TBC-Bugtracker#531]
Decription: 
After using Shadowstep the mob no longer is targeted.

How it works: 
Target mob - use shadowstep - have to target mob again.

How it should work: 
Target mob - use shadowstep - mob is still targeted.

**Comment by lukaasm** [comment]
https://streamable.com/2759q

Seems to work fine? Tested now on PTR

**Comment by Nadiirr** [comment]
Yeah it's working. 
I promise it wasn't working earlier haha!
closing.

**Comment by lukaasm** [comment]
Yeah, it probably was related to #509
