### ISSUE TITLE
Alliance and Horde Faction Leaders abilities and stats

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#542]
- [x]   Highlord Bolvar Fordragon base damage seems quite low, hits for around 1800 on cloth should be higher but not as much as Magni/Fandral/Tyrande. Currently he has vanilla health, his TBC health should be 1,055,700. Should have the highest armor value out of all faction leader bosses. When engaged doesnt use any of his abilities. Retribution Aura which hits for 200 damage. Cleave (Spell ID 20684) should be used every 6 seconds. Highlord's Justice (Spell ID 20683) should be used every 10-15 seconds. Shield Wall should be used every 30 seconds.Alliance:

- [x]  Highlord Bolvar Fordragon base damage seems quite low, hits for around 1800 on cloth should be higher but not as much as Magni/Fandral/Tyrande. Currently he has vanilla health, his TBC health should be 1,055,700. Should have the highest armor value out of all faction leader bosses.
When engaged doesnt use any of his abilities.
Retribution Aura which hits for 200 damage.
Cleave (Spell ID 20684) should be used every 6 seconds.
Highlord's Justice (Spell ID 20683) should be used every 10-15 seconds.
Shield Wall should be used every 30 seconds.

- [x]  Archbishop Benedictus base damage seems ok considering his role in Stormwind (he hits for ~2000 on cloth). Currently has vanilla health and mana, should have 504,000 health and 352,000 mana.
When engaged doesnt use any of his abilities.
Holy Nova (Spell ID 20694) should be used every 10 seconds or so.
Holy Smite (Spell ID 20695) should be used every 6-8 seconds, targets random player on his aggro list.
Power Word: Shield (Spell ID 20697) should be used every 15 seconds.
Holy Fire? - some comments mention he has an instant single target spell that deals high Holy damage and then leaves a DoT that deals Fire damage over 8 seconds, this spell is used less frequently than other damage spells.
Should yell the following quotes:
Aggro: "Sacrilege! Defend the cathedral!"

- [x] Lady Jaina Proudmoore base damage seems slightly lower, should be in around 2000. Currently has vanilla health, her TBC health should be 1,162,047. Should be immune to silence/interrupt effects.
When engaged doesnt use any of her abilities. 
Fireball (Spell ID 20678) targets random player on her aggro list, should be used every 6 seconds.
Fireblast (Spell ID 20679) targets random on her aggro list, should be used every 10 seconds.
Blizzard (Spell ID 20680) targets random player on her aggro list, should be used every 20-25 seconds.
Summon Water Elementals (Spell ID 20681), summons 3 Water Elementals (when manually summoned the level up animation and sound is seen and heard, this should be hidden), health and damage should be checked. This ability is used once at start of fight then every 1.5 minutes.
Teleport (Spell ID 20682) this should be used on main tank every 30 seconds, teleports the target above Theramore Harbor.
Should yell the following quotes:
Aggro: "You asked for it." or " I hate resorting to violence!"

- [x]  Magni Bronzebeard base damage seems quite low, hits for around 1860 on cloth should be much higher (his base damage should be prob around 5000), missing his Dual Wield passive ability (should hit with offhand for 50% damage).
When engaged doesnt use any of his abilities.
Storm Bolt (Spell ID 20685) should be every 15 seconds on a random player on his aggro list.
Thunder Clap (Spell ID 23931) should be used every 10 seconds.
Avatar (Spell ID 19135) should be first used 15 seconds after entering combat then used every 25 seconds.
Knock Away (Spell ID 20686) should be used every 30 seconds and will drop/reset all aggro after using it.
Should yell the following quotes:
Aggro: "Feel the fury of the mountain!" or "For Khaz'Modan!"

- [x]  High Tinker Mekkatorque base damage seems quite low, hits for around 1200 on cloth should be much higher (prob slightly higher than Bolvar or the same).
When engaged doesnt use any of his abilities.
Bomb (Spell ID 9143) should be used on random player on his aggro list every 10 seconds or so (not quite sure about this timer).
Goblin Dragon Gun (Spell ID 22739) should be used every 15 seconds.
Super Shrink Ray (Spell ID 22742) used on people in melee range (100% uptime).

- [x] Arch Druid Fandral Staghelm base damage seems quite low, hits for around 1200 on cloth should be much higher (around Bolvar and High Tinker). Currently he has vanilla health, his TBC health should be ~1,100,000 and have decent resistance to all schools of magic against lvl 70 players.
When engaged doesnt use any of his abilities.
Summon Treant Allies (Spell ID 20702) should be used every 6-10 seconds (when they are manually summoned for testing purposes level up animation and sound is heard, this should be hidden), damage and health of Treants should be looked into as comments mention that Treants being summoned isnt an issue but if players dont AOE them they can pile up on healers and cause big trouble for the raid over time.
Rejuvenation (Spell ID 20701) this should tick every 3 seconds for huge amount and should be purged/dispelled by players otherwise the fight can go on forever (Wotlk version of this ticks for 42000 but he has 5 million health, maybe TBC version should tick somewhere between 8400 and 14000?), should be used every 15 seconds.
Entangling Roots (Spell ID 20699) should be used every 20-25 seconds, should also drop/reset all aggro and Fandral should move away from tank and then pick random targets for Wrath spam.
Wrath (Spell ID 20698) should be used after drop/reset aggro after Entangling Roots on random targets on his aggro list, used roughly 5 times in a row then resumes normal behaviour.

- [x] Tyrande Whisperwind base damage seems quite low, hits for around 1280 on cloth should be much higher (higher melee AND ranged damage than Fandral). Currently she has vanilla health, her TBC health should be slightly lower than Fandral but still over 1 million.
When engaged doesnt use any of her abilities.
Moonfire (Spell ID 20690) should be used on random target on her aggro list every 8 seconds (even tank).
Cleave (Spell ID 20691) should be used every 6-10 seconds.
Starfall (Spell ID 20687) should be used every 25 seconds.
Searing Arrow (Spell ID 20688) should be used roughly between 12-15 seconds on random target on her list that is not in melee range.

- [x] Prophet Velen base damage seems quite low, hits for around 580 on cloth should be much higher (should have quite high melee damage as he is a new boss introduced in TBC).
When engaged doesnt use any of his abilities.
Holy Nova should be used every 15 seconds, hits for around 2k.
Holy Smite should be used every 12-15 seconds on random target on his aggro list, 2.5 seconds cast time hits for ~3k.  
Staff Strike should be used every 6-10 seconds.
Arcane Blast used in melee range which deals damage and has a knockback (EDIT: After researching more about it the name was wrong as there is only one Holy Blast spell in DB which didnt match the icon, Arcane Blast ability which deals damage+knockback and has a Death Pact icon matches the description perfectly), should be used every 30 seconds.

Horde:

- [x]  Thrall base damage seems quite low, hits for around 1264 on 40% reduction, one comment from TBC says "I was just hit for a little under 13k on leather, with 16.7% reduction", i cannot verify if this a crushing blow but if it isnt a crushing blow that would put his base damage at around 16k which is highly unlikely because Cairne should have the highest melee damage on Horde side. Currently has vanilla health, his TBC health should be 1,055,700.
When engaged uses all abilities however the timers on Chain Lightning and Shock need to be checked, Chain Lightning seems to be used a bit too often and Shock is on a 10+ seconds timer, Chain Lightning should be used every 10 seconds and Shock should be used every 6 seconds. Currently he is vulnerable to interrupts he should be immune to interrupt/silence effects.
Should yell the following quotes:
Aggro: "Lok'narosh!" or "For Doomhammer!" or "Your time has come!"

- [x] Vol'jin missing his weapon, base damage seems quite low, hits for around 800 on 40% reduction, his base damage should be around 2k-2.4k as his spells are bigger danger to the enemy raid than his melee.
When engaged doesnt use any of his abilities.
Hex - AoE Polymorph turning players into frogs should be used every 15 seconds. Has 20 yard range.
Veil of Shadow - AOE curse debuff that reduces healing received by 75% for 15 seconds. Should be used every 20 seconds, if not decursed this ability is responsible for most wipes.
Shadow Shock - instant cast 20 yard range, single target spell that deals high shadow damage to his main target, i think the Spell ID is 17289 but not quite sure. Should be used every 6-10 seconds.
Shadow Word Pain (Spell ID 17146) should be used every 15 seconds on random player on his aggro list.
Should yell the following quotes:
Aggro: "You make big mistake, mon." or "Here come the voodoo!" or "For the Darkspear tribe!"

NOTE: Thrall and Vol'jin arent linked together currently but they should be.

- [x]  Cairne Bloodhoof base damage seems quite low, hits for around 1300 on 40% reduction, should have the highest melee damage out of all Horde faction leaders (my estimate is 9000-12000 base damage as comments regarding him mention he hits like a truck and that his Berserker Charge could easily one-shot a clothie). Currently has 980,000 health he should have 1,209,812 health.
When engaged uses all abilities however the timers need to be checked.
Mortal Strike - should be used every 10 seconds (50% uptime).
Thunder Clap - should be used every 8-10 seconds.
Cleave - should be used every 6 seconds.
Uppercut - should be on a 6-9 seconds timer.
Berserker Charge - first Berserker Charge should be used 30 seconds after engaging and then every 15 seconds afterwards.
Should yell the following quotes:
Aggro: "For honor!"
Raid wipe (leaving combat): "The attackers have fled! Strength and honor to the Horde!"

- [x]  Lady Sylvanas Windrunner base damage seem quite low, hits for around 1270 on 40% reduction, should have similar melee damage as of Varimathras. Currently has 67k health, should have 1,055,700 health. Missing her melee and ranged weapons.
When engaged doesnt use any of her abilities.
Multi-Shot used on random people on her aggro list regardless of tanking, also should be used after Fade when aggro is dropped/reset on random target on her aggro list. Deals normal damage + 1665 to 1935, hits 10 players in total.
Fade (Spell ID 20672) when she uses Fade she drops/resets all aggro and moves to different position and then starts attacking again, seems to be used quite often as many comments mention its very annoying trying to tank her due to her reset/aggro ability and how she ignores the tank to use Shoot and Multi-Shot ability on random players on her aggro list throughout the fight.
Shoot ability which is basicly her range auto-attack if there is nobody in her melee range, she will continue using Shoot ability aswell after Fade + Multi-Shot combo and continue using it if the highest threat target is not in melee range.
Summon Skeleton - First used 5 seconds after engaging then its used on a 10 seconds timer, spawns 3 skeletons that autoattack people on her aggro list.
Should yell the following quotes:
Aggro: "Let none survive!" or "May my aim be true."

- [x]  Varimathras base damage seems quite low, hits for around 1360 on 40% reduction, should have decently high damage (less than Cairne/Thrall but more than Vol'jin). Attack speed should be between 1.6 or 1.8 (not quite sure whether its 1.6 or 1.8 but comments mention he hits faster than other Horde bosses which have the default 2.0 attack speed). Should be immune to silence/interrupt effects.
When engaged doesnt use any of his abilities.
Shadow Bolt Volley (Spell ID 40070) should be used instantly on pull/aggro then used every 10 seconds, hits for around 1800-2200 shadow damage before reduction/resistances and has a really long range as comments mention it hits everyone in the room.
Drain Life AOE (Spell ID 20743) first one is used 30 seconds after pull/aggro then used every 15 seconds.
Dominate Mind simple Mind Control type spell that is used on 3 random players on his aggro list, lasts 10 seconds and is dispellable, first one is used 20 seconds after pull/aggro then used every 20 seconds.
Old comments regarding him mention he should have a great amount of Arcane Resistance even with alliance warlocks using Curse of the Elements on him (my guess is his Arcane Resistance is between 190-210+)
Should yell the following quotes:
Aggro: "Vanquish the weak!" or "Wake up! Time to die!" or "None can oppose me." or "For Sylvanas!"

NOTE: Sylvanas and Varimathras arent linked together currently but they should be.

- [x] Lor'themar Theron base damage seems quite low, hits for around 200 on 40% reduction, should have way higher damage (higher than Halduron Brightwing main hand). NOTE: Should have higher armor than Rommath or Halduron (high armor reduction vs lvl 70 players similar to Bolvar for example)
When engaged doesnt use any of his abilities.
Cleave - 110% cleave used every 6 seconds.
Shock - 4600 nature damage, reflectable 20 yard range, should be on a 10-15 seconds timer.
Mana Burn - targets random player on his aggro list with a mana pool, 950-1050 mana burned and deals 1x shadow damage for each mana burned, 30 yard range used every 20 seconds.
Mass Charm - 15 seconds charm, 50 yard radius around Lor'themar, seems to mind control 1 player on his aggro list every 20-25 seconds.

- [x]  Grand Magister Rommath when engaged doesnt use any of his abilities.
Fireball - 3 second cast cannot be interrupted, deals high damage to his target (Rommath doesnt melee at all Fireball is his main attack)
Flamestrike - 3 second cast cannot be interrupted, deals instant fire damage and additional damage over 8 seconds, targets random player on his aggro list and casts it at his location.
Molten Armor - Causes Fire damage when hit, increases his chance to critically hit with spells by 3%, and reduces the chance he is critically hit by 5%. Can be dispelled or Spell Stolen and lasts 10 min. (If its dispelled or spell stolen he will recast it instantly).

- [x]  Halduron Brightwing base damage seems quite low, hits for around 173 on 40% reduction, should be much higher also missing Dual Wield passive ability. 
When engaged doesnt use any of his abilities.
Multi-Shot - same ability Sylvanas has, targets random player on his aggro list regardless of tanking and hits up to 10 players for weapon damage + bonus damage.
Shoot - same ability as Sylvanas, if his main target is not in melee range he will continue using until tank in melee range picks him up.

NOTE: Lor'themar Theron, Rommath and Halduron arent linked together currently but they should be.

**Comment by Dootz** [comment]
thank you for the detailed report, With next ptr update everything should work fine.

**Comment by Silroth** [comment]
Alliance:

- Highlord Bolvar Fordragon Retribution Aura currently hits for 15 damage while it should be 200 damage, Shield Wall isnt used at all while it should be used every 30 seconds.
NOTE: Currently guards arent spawning periodically when Bolvar is engaged.

- Archbishop Benedictus does not use the Holy Fire ability, vulnerable to silence/interrupt effects while he should be immune (currently you can interrupt his Holy Smite).

- Lady Jaina Proudmoore Summoned Water Elementals glitch out in place and spin around as if they are rooted and they stay in that position until killed. Jaina uses all her abilities properly when engaged. Vulnerable to silence/interrupt effects while she should be immune (currently you can interrupt her Fireball and Blizzard).

- Magni Bronzebeard missing his Dual Wield passive ability, does not use Avatar or Knock Away abilities. Also it seems timers for Storm Bolt and Thunder Clap got mixed up because right now Storm Bolt is used every 5-9 seconds and Thunder Clap is on a 12+ seconds timer.
NOTE: Currently guards arent spawning periodically when Magni is engaged (they should spawn more frequently than in Stormwind because Ironforge doesnt have "royal" type of guards).

- High Tinker Mekkatorque does not cast Bomb ability.

- Fandral Staghelm summoned Treant Allies behave in same manner as Jaina's Water Elementals, they glitch out in place and spin around. Wrath ability seems to be on a generic timer instead of being tied to Entangling Roots combo. Vulnerable to silence/interrupt effects while he should be immune (currently you can interrupt his Wrath and Summon Treant Allies spells).
NOTE: Currently guards arent spawning periodically when Fandral is engaged.

- Tyrande Whisperwind sometimes she will interrupt her Starfall to cast other spells (this shouldnt happen), Searing Arrow hits for ~900 which is quite low, should deal around 2-3k damage. Vulnerable to silence/interrupt effects while she should be immune (currently you can interrupt her Starfall).
NOTE: Currently guards in Tyrande's room arent spawning periodically when Tyrande is engaged.

- Velen Vulnerable to silence/interrupt effects while he should be immune (currently you can interrupt his Holy Smite).
NOTE: Currently guards arent spawning periodically when Velen is engaged.

Horde:

- Thrall Vulnerable to silence/interrupt effects while he should be immune (currently you can interrupt his Chain Lightning).
NOTE: Currently guards arent spawning periodically when Thrall is engaged.

- Vol'jin missing his weapon, when engaged uses all abilities properly.

- Cairne Bloodhoof does not reset properly, instead of going back to his default position he stays near corpse of the player he killed and keeps spamming the "The attackers have fled! Strength and honor to the Horde!" yell non-stop.

- Lady Sylvanas Windrunner missing her melee and ranged weapons, when engaged she runs into melee range while she should stay at range and use Shoot ability until her highest threat target runs into her melee range, Multi-Shot deals only 1350 damage (should be her ranged damage + 1665 to 1935, hitting 10 players in total), she doesnt use Shoot or Summon Skeletons ability at all it seems.
NOTE: Currently guards arent spawning periodically when Sylvanas is engaged.

- Varimathras does not seem to cast Dominate Mind (will need to retest with more people tho), he is vulnerable to silence/interrupt effects which shouldnt happen (currently you can interrupt his Drain Life).

- Lor'themar Theron does not cast Shock or Mana Burn.
NOTE: Currently guards arent spawning periodically when Lor'themar is engaged. 

- Grand Magister Rommath does not cast Flamestrike, he is vulnerable to silence/interrupt effects which shouldnt happen (currently you can interrupt his Fireball), he shouldnt melee at all his "autoattack" is his Fireball.

- Halduron Brightwing Multi-Shot hits for ~1400 (should be higher).


Faction Leaders Honor value - Currently Bolvar gives 110 honor when killed solo, Benedictus 0, Jaina 0, Magni 90, Mekkatorque 0, Fandral 90, Tyrande 120 , Velen 120, Thrall 90, Vol'jin 0, Cairne 80, Sylvanas 80 , Varimathras 0, Lor'themar Theron 80, Halduron 0, Rommath 0.

My suggestion is to increase the honor gained from killing faction leaders but in turn to compensate for that and also increase their respawn so enemy raids cannot farm them, 40k honor from faction leaders spread among 40 man raid is 1k honor per player which seems reasonable, respawn timer can be increased to something between 4-6 hours. This could provide a great incentive for PvP players to invade enemy cities and for the defending faction to defend their leaders.
