### ISSUE TITLE
[Warlock][Spell] Enslave Demon issues

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#543]
- [x] The abilities of the enslaved demons dont automatically show up on the bars.

- [x] When the demon attacks, the master gains weapon skill.

- [x] The demon has no global CD or ability CD on their abilities, leading to enslaved demons being able to do several thousand DPS. MAJOR ABUSE(!)
https://i.gyazo.com/d2b9851c452dd2a179fab2c49ce22e33.mp4

- [x] The demons sometimes dont reset properly after you release them. If released they should stay attacking you, if you run away they should reset to their original position.

- [x] Larger demons should follow you a bit further away so they dont stand on top of you
![Image](https://i.gyazo.com/4057e2e853b94b2c0425faa227c18c75.jpg)

- [x] Something really weird is happening with this specific demon ability. He should pull enemies towards him with it, if you set it on auto cast he will start spam casting it on the master dragging the master up into the air with him. 
When he is released he's stuck in the air.
![Image](https://i.gyazo.com/8add64fd47e1aa9641d5bb3dbbeac7cd.jpg)

Ability: http://db.hellfire-tbc.com/?spell=31705

https://i.gyazo.com/d59c77f94daf9c655efcc78872333826.mp4

- [ ] You should be able to Enslave a demon even if you already have one summoned, this should simply dismiss your current one.

**Comment by Silroth** [comment]
Doomguard has correct abilities now, he should have Dispel Magic, Rain of Fire, War Stomp and Cripple.
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/69

**Comment by notsofamous** [comment]
https://github.com/Looking4Group/L4G_Core/issues/1661

**Comment by akrom23** [comment]
@notsofamous 
> When the demon attacks, the master gains weapon skill.

Cannot reproduce it - fixed?

**Comment by Jekenius** [comment]
Found three more bugs about Enslaving Demons:
1) After you enslaved a demon it won't react on your commands untill you command it to follow you.
![wowscrnshot_112618_153910](https://user-images.githubusercontent.com/45003723/49002722-f0aa1e00-f192-11e8-80a8-35cd76c9b4c5.jpg)
(spamming pet attack bar without effect)
2) 
![wowscrnshot_112618_154223](https://user-images.githubusercontent.com/45003723/49002906-66ae8500-f193-11e8-8891-95828910ca0a.jpg)
![wowscrnshot_112618_154238](https://user-images.githubusercontent.com/45003723/49002908-68784880-f193-11e8-8b8f-f46d34029429.jpg)
Mob doesnt return to it's starting position after dismissing it from enslave and after dismissing doesnt move at all, no patrols or little movements in small area at all.
3)
![wowscrnshot_112618_154526](https://user-images.githubusercontent.com/45003723/49003089-cdcc3980-f193-11e8-8795-68ef188fe82f.jpg)
Tooltip says Lash of Pain is useable only from behind, but 2 mobs fighting each other face by face and LoP is still casting(that yellow number is ability damage and that pet havent abilities except LoP).
