### ISSUE TITLE
[Raid] Boss Armor Values

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#545]
### Please check if armor values are correct for all bosses.

**Gruul's Lair:**
- [x] High King Maulgar: 7700
- [x] Gruul the Dragonkiller: 7700

**Magtheridon's Lair:**
- [x] Magtheridon: 7700

**Zul'Aman:**
- [x] Nalorakk: 7700
- [x] Akil'zon: 7700
- [x] Jan'alai: 7700
- [x] Halazzi: 7700
- [x] Hex Lord Malacrass: 6200
- [x] Zul'jin: 7700

**Serpentshrine Cavern:**
- [x] Hydross the Unstable: 7700
- [x] The Lurker Below: 7700
- [x] Leotheras the Blind: 7700
- [x] Fathom-Lord Karathress 6200
- [x] Morogrim Tidewalker: 7700
- [x] Lady Vashj: 6200

**Tempest Keep:**
- [x] Void Reaver: 8800
- [x] High Astromancer Solarian: 6200
- [x] Al'ar: 7700
- [x] Kael'thas Sunstrider: 6200

**Hyjal Summit:**
- [x] Rage Winterchill: 6200
- [x] Anetheron: 6200
- [x] Kaz'rogal: 6200
- [x] Azgalor: 6200
- [x] Archimonde: 6200

**Black Temple:**
- [x] High Warlord Naj'entus: 7700
- [x] Supremus: 7700
- [x] Shade of Akama: 7700
- [x] Teron Gorefiend: 6200
- [x] Gurtogg Bloodboil: 7700
- [x] Reliquary of Souls:
- Essence of Suffering: 0
- Essence of Desire: 7700
- Essence of Anger: 7700
- [x] Mother Shahraz: 6200
- [x] Illidari Council:
- Gathios the Shatterer: 6200
- [x] Illidan Stormrage: 7700

**Sunwell Plateau:**
- [x] Kalecgos (Dragon): 6200
- Sathrovarr the Corruptor: 6200
- [x] Brutallus: 7700
- [x] Felmyst: 6200
- [x] The Eredar Twins:
- Grand Warlock Alythess: 6200
- Lady Sacrolash: 6200
- [x] M'uru / Entropius: 7700
- Shadowsword Fury Mage: 5700
- Shadowsword Berserker: 7100
- Void Sentinel: 6800
- [x] Kil'jaeden: 6200
- Hand of the Deceiver: 5900
- Sinister Reflection: 5475

http://web.archive.org/web/20080728074357/http://elitistjerks.com/f31/t16629-raid_boss_armor_values/#post496799

**Comment by Dootz** [comment]
great, thanks for the list. I had to correct armor values only for 7 bosses. Rest was fine.

**Comment by notsofamous** [comment]
**Karazhan**

- [ ] Attumen the Huntsman:  7700
- [ ] Midnight:  8200
- [ ] Maiden of Virtue:  6200
- [ ] Julianne:  6200
- [ ] Romulo: 7700
- [ ] Strawman: 7300
- [ ] Roar: 4700
- [ ] The Curator: 6200
- [ ] Shade of Aran: 3800
- [ ] Kil'rek: 3400
- [ ] Terestian Illhoof: 6700
- [ ] Nightbane: 7700
- [ ] Netherspite: 5500
- [ ] Prince Malchezaar: 7700
