### ISSUE TITLE
Alliance and Horde city guards, "royal" guards, elite patrols and Battlemasters.

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#547]
Currently many city guards both normal lvl 65 ones and the "royal" ones have wrong stats/levels etc.

Normal city guards:

- [x] - Storwmind City Guard should have 11650 health and base damage should be 538-625.
- [x] - Ironforge Guard should have 11650 health and base damage should be 538-625.
- [x] - Darnassus Sentinel should have 11650 health and base damage should be 538-625.
- [x] - Exodar Peacekeeper base damage should be 538-625.
- [x] - Orgrimmar Grunt should have 11650 health and base damage should be 538-625.
- [x] - Bluffwatcher should have 11650 health and base damage should be 538-625.
- [x] - Undercity Guardian should have 11650 health and base damage should be 538-625.
- [x] - Silvermoon City Guardian base damage should be 538-625.

"Royal" city guards:

- [x] - Stormwind Royal Guard should be lvl 70, base damage should be ~1375. Should use Shield Bash (Spell ID 11972) and Strike (Spell ID 14516).
- [x] - NOTE: Ironforge "royal" guards do not exist, it seems to compensate for this normal Ironforge Guards should spawn faster when Ironforge is under attack, especially in Magni's throne room. 
- [x] - NOTE: Darnassus "royal" guards do not exist, to compensate for this normal Darnassus Sentinels should spawn faster when Darnassus is under attack, especially in Tyrande's and Fandral's room.
- [x] - Shield of Velen should be lvl 70 and have ~16000 health, base damage should be ~1375. Should use Shield Block (Spell ID 12169) and Revenge which deals moderate damage.
- [x] - Kor'kron Elite should be lvl 70 and have ~16000 health, base damage should be ~1375. Should use Cleave 110% every 6 seconds and Enrage (Spell ID 8599) at low health.
- [x] - Honor Guard should be lvl 70 and have ~16000 health, base damage should be ~1375. Should use Knockdown ability which is a single target that deals damage and stuns the target for 2 seconds.

- [x] - Royal Dreadguard should be lvl 70 and have ~16000 health, base damage should be ~1375. Should use Hamstring (Spell ID 9080), Shield Bash (Spell ID 11972) and Strike (Spell ID 14516).
- [x] - Royal Guard should be lvl 70 and have ~16000 health, base damage should be ~1375. Should use Cleave 110% every 6 seconds and Enrage (Spell ID 8599) at low health.
- [ ] 

Elite city patrols: 3 in each major vanilla city patrolling. They should share same abilities and stats which are:
Health ~19000, base damage 1756-1918, Dual Wield passive ability, Hooked Net (Spell ID 14030) with 100% uptime on target, Sunder Armor (Spell ID 15572) and Stealth detection. Should be immune to all CCs.
 
- Horde

- [x] Seeker Cromwell
- [x] Seeker Nahr
- [x] Seeker Thompson

- [x] Scout Tharr 
- [x] Scout Stronghand 
- [x] Scout Manslayer 

- [x] Hunter Thunderhorn 
- [x] Hunter Ragetotem
- [x] Hunter Sagewind 

- Alliance

- [x] Officer Brady 
- [x] Officer Jaxon 
- [x] Officer Pomeroy

- [x] Huntress Skymane
- [x] Huntress Ravenoak
- [x] Huntress Leafrunner

- [x] Thief Catcher Farmountain 
- [x] Thief Catcher Shadowdelve 
- [x] Thief Catcher Thunderbrew 

- [x] Paths  

- [ ] AI & Stats

IMPORTANT NOTE: All faction city guards should respond to various emotes, if you /wave they should /wave back, if you /salute they should /salute back, if you target them and /rude they should respond with /no, if you do /chicken they should /rude, if you /kiss they should /bow. 

Faction PvP Battlemasters:

- [ ] All Battlemasters should share same abilities and stats which are:

Health 157,200 , base damage ~1400-1700 

- Cleave (Spell ID 15284) should be used every 6 seconds.
- Mortal Strike (Spell ID 16856) should be used every 10 seconds.
- Whirlwind (Spell ID 13736) channeled ability which should be used every 20 seconds.
- Frightening Shout (Spell ID 19134) should be used every 25-30 seconds.

- [x] Unique guards in Orgrimmar: Troll Roof Stalkers were added in TBC to prevent alliance players from hiding on the roof and killing people below in similar fashion how Gadgetzan Snipers were added.

- [x] - Troll Roof Stalker base damage should be ~2200, health should be 104,790, should use Net (100% uptime), Shoot ability for 2000 on cloth.

**Comment by Dootz** [comment]
Hi, thank you for the detailed report. I have one question just to clarify things/ keep fidelity throughout our world.  On which website you base your health and damage values?

**Comment by Silroth** [comment]
@Dootz comments from TBC era (or Wotlk referring to forgotten units that didnt make it for the upgrade) or old videos that have slightly better quality, if hp or damage value seems odd i make a comparison to other units and see if they match or not in a reasonable sense.

For example Blizzard sometimes forgot to update few of those units and comments point that out,
Hunter Thunderhorn wowhead page:
 "Wowvocate on 2009/02/02 (Patch 3.0.8) - Seems they forgot this poor little guy when they did the city guard upgrades."
"Oneck on 2009/03/07 (Patch 3.0.9) - Lol yeah saw him today and he only had 19k health"

**Comment by Dootz** [comment]
Ohh, ok. For now, we've been using mostly sites like http://db.hellfire-tbc.com/, https://tbc-twinhead.twinstar.cz, and few others to cross-check stats. But your sources seems fine too.

**Comment by Silroth** [comment]
https://db.excalibur.ws/ is good aswell, shows a bit more information.
