### ISSUE TITLE
[Bug][Quest] "Inert Scourgestones" Typo in NPC's name

### ISSUE THREAD

**Issue by F4play** [SunwellWoW/Sunwell-TBC-Bugtracker#55]
Decription: Typo in NPC's name. NPC name in the quest text above the description text should be "Commander Ashla**m** Valorfist" not Ashlan. 

Specific Quest ID: 8416

How it works: Ashlan

How it should work: Ashlam

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/npc=10838/commander-ashlam-valorfist

**Comment by Dootz** [comment]
![obraz](https://user-images.githubusercontent.com/25490436/43688845-e3f051ac-98f0-11e8-816f-9c77aa001d9f.png)
http://www.wowhead.com/quest=8416/inert-scourgestones
Looks like it's "blizzlike" typo :D
