### ISSUE TITLE
[Priest][Spell][Dungeons][NPC] Mind Controled Mobs Don't Have spells or perform attacks.

### ISSUE THREAD

**Issue by Exorcista** [SunwellWoW/Sunwell-TBC-Bugtracker#550]
Decription: 
Uppon using spell Mind Control on any humanoid mob on a dungeon, action bars shows just a regular "attack" button thats does zero functions, also right clicking doesnt make the controled mob attack "enemies".

How it works: 
Mind Control spells just serves as a broken CC atm making the controled mob not usefull at all.

How it should work: 
Mobs should have some offensive spells according to theyr class and also be able to autoattack.

Source (you should point out proofs of your report, please give us some source): 
Did run DM:N and SM today both times mobs acted like this, easy to reproduce.

**Comment by Patrulek** [comment]
#130
