### ISSUE TITLE
[Hunter][Spell] Scatter shot

### ISSUE THREAD

**Issue by Patrulek** [SunwellWoW/Sunwell-TBC-Bugtracker#551]
Decription: 
1) When using Scatter Shot on the end of auto attack cast time, the auto attack is interrupted but still doing damage to target, which cause to interrupt Scatter effect.
2) Scatter shot doesn't share DR with other Scatter shots.

How it should work: 
1) If auto attack is interrupted, it shouldnt do any damage to target.
2) Scatter shot should share DR with other scatter shots (http://wowwiki.wikia.com/wiki/Diminishing_returns)

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/870wr
![scatter](https://user-images.githubusercontent.com/7295272/46236799-cef20d80-c380-11e8-81c8-8545130cc9ec.png)

**Comment by akrom23** [comment]
> When using Scatter Shot on the end of auto attack cast time, the auto attack is interrupted but still doing damage to target, which cause to interrupt Scatter effect.

Needs more info. Is it really a bug? Scatter Shot is faster spell than auto shot (Shatter Shot speed is 60, auto shot - 40). If the auto shot is just launched and then you cast Scatter Shot, it is possible, that Scatter Shot will hit target first.

**Comment by Patrulek** [comment]
> Needs more info. Is it really a bug (ignoring the interrupt message)? Scatter Shot is faster spell than auto shot (Shatter Shot speed is 60, auto shot - 40). If the auto shot is just launched and then you cast Scatter Shot, it is possible, that Scatter Shot will hit target first.

Why do you want ignore interrupt message? I get something else in combat log than in gameplay. Log should reflect what is actually happen in game. So either what you see in video is correct behaviour and combat log should be fixed, either this is some bigger bug than just wrong message in combat log.
What you can conclude from message log is that auto attack is interrupted because of using scatter shot, what should be true, but then magically that interrupted auto attack hits the target. If it was interrupted then why it is hitting the target?

> Source? The link is updated to new system. As I remember, Scatter Shot's DR is shared only with Dragon's Breath (or even not)?

Ok, this may be true. Unfortunately couldn't find any older sources about ScatterShot, other that this is Disorient effect (same as Dragon's Breath). And it's hard for me to believe that this spell doesnt share DR even with itself.

**Comment by akrom23** [comment]
I can fix this interrupt message. This is not my point. 
I'm just not sure if Scatter Shot should interrupt auto attack in this situation - because auto attack was casted before Scatter, so there is nothing to interrupt.

**Comment by Patrulek** [comment]
Or i am wrong all the time. I thought that combat log writes one line when auto attack is performed, but now i see that it doesnt. Probably above happen beacause of different shot speed as you mentioned and there is nothing wrong. Ehh, sorry for wasting your time on this one.
If nothing will be done with DRs i think you can close and mark as invalid.

**Comment by akrom23** [comment]
About DR's - still need good source of info :)

**Comment by Patrulek** [comment]
I would want to find any good source about that, but i can't. I also watched some videos but i think it's really uncommon situation that 2x Scatter/DragonsBreath will be casted on the same person.
The only thing other than wowwiki article is this post: http://www.arenajunkies.com/topic/7694-why-do-blindcyclone-share-a-dr/#entry54197
which isn't necesarilly imply that this DR should be shared (althought these spell have equal mechanics type). Another fact is that i heard about batally about Dragon's Breath DR on ArenaTournament (dunno if old or new) and from what i've known, this spell didn't had any DR mechanics, so this could be true also for Scatter.

I'm not able to provide any reliable sources, so you can feel free to close this topic if you want.
#statistics

**Comment by akrom23** [comment]
Okay. Thx for the research.
