### ISSUE TITLE
[Shaman][Spell] Totems doesn't start combat

### ISSUE THREAD

**Issue by Patrulek** [SunwellWoW/Sunwell-TBC-Bugtracker#552]
Decription: 
Place earthbind/searing/whatever offensive totem. Shaman doesn't get combat, only target does (PvP).

How it works: 
As above.

How it should work: 
Shaman also should get combat.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented.
