### ISSUE TITLE
[Dungeon][Scarlet Monastery: Library] Arcanist Doan Detonation

### ISSUE THREAD

**Issue by Exorcista** [SunwellWoW/Sunwell-TBC-Bugtracker#553]
Decription: 
When he shields and cast spell: _**(Detonation=https://www.wowhead.com/spell=9435/detonation)**_ , sayd spell doesnt do any dmg at all.

How it works: 
You can just stand inside the range of it and not take any dmg.

How it should work and source: 
Theres a video here from retail _**min: 0:45**_

https://www.youtube.com/watch?v=SKFeAwMJy8M

**Comment by Dootz** [comment]
can't confirm. Works fine for me. It hit me for something around 680 when my character was at level 30
