### ISSUE TITLE
[Rogue][Spell] Vanish

### ISSUE THREAD

**Issue by Patrulek** [SunwellWoW/Sunwell-TBC-Bugtracker#554]
Decription: 
1) Vanish buff disappear at Earthbind Totem tick (but stealth remains). 
2) Use Vanish while you are afflicted by Curse of Exhaustion or Piercing Howl - you get stealthed but Vanish buff doesn't appear.

Lines: "[player] gains [Vanish]" and "[Vanish] fades from [player]" are interesting here imo.

How it works: 
As above.

How it should work: 
Vanish buff improves your stealth, so it shouldnt disappear in above cases.

Source (you should point out proofs of your report, please give us some source): 
![earthbind_vanish](https://user-images.githubusercontent.com/7295272/46237296-d36bf580-c383-11e8-99c1-ecfa1fa391e1.jpg)
![curse_vanish](https://user-images.githubusercontent.com/7295272/46237297-d6ff7c80-c383-11e8-8718-789b8b2e20a5.jpg)
![piercing_vanish](https://user-images.githubusercontent.com/7295272/46237299-d961d680-c383-11e8-80d7-023374ed1365.jpg)

**Comment by Exorcista** [comment]
[Related to this](https://imgur.com/VDB7119) , basically just pull a mob and hit vanish as fast as u can, chance of this happening seems high since happened to me twice.
