### ISSUE TITLE
Magtheridon

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#562]
Met 2 issues today:

- [x] 1. Boss may randomly yell: "I...am...UNLEASHED!!!" even when he's out of combat and pull suddenly.
Check out screen, I was waiting in next room when he was yelling those two quotes variably. Seems like every 2 minutes after boss evade he's pulling automatically.
![image](https://user-images.githubusercontent.com/22802214/46278077-6e6ff580-c565-11e8-9788-8ddf99e55fdb.png)

- [x] 2. When I pulled channelers boss pulled himself just around 5 seconds later. This timer should be always set to 120 seconds.

- [x] 3. Magtheridon yells "I...am...UNLEASHED!!!" on boss evade while he shouldn't. Maybe it breaks something with next pulls.

- [x] 4. Hellfire Channelers used to skip Shadow Grasp spell cast on boss when they're out of player's visibility.

**Comment by notsofamous** [comment]
- [ ] Standing around in the room for 2 min starts the fight.

- [ ] Hellfire channelers never attempt to recast infernals after the initial ones have despawned (each channeler can have 2 up at the same time, but never more than that).

- [ ] There should be 3-4 fires up at the same time in p2, currently 2-3.

Nihilum VS Magtheridon - World First https://www.youtube.com/watch?v=QpgdAHJANcA

Last Resort vs Magtheridon World 3rd by Kerp https://www.youtube.com/watch?v=v0PNXZYuAnU

**Comment by Silroth** [comment]
- Magtheridon currently has 6.8 million hp which is not his blizzike hp but something CC did (they did this randomly to random units and bosses).

- Hellfire Channelers Soul Transfer should be reverted to pre-nerf value which is "increases damage and casting speed by 30%".

After a wipe if you enter the room sometimes all Channelers and Magtheridon aggro which shouldnt happen.

Badge should be removed from him but Satchel and chest tokens should remain, Blizzard corrected that mistake for a valid reason.

**Comment by akrom23** [comment]
> Hellfire Channelers Soul Transfer should be reverted to pre-nerf value which is "increases damage and casting speed by 30%".

Set, but not properly dispayed on aura bar, because of missing packet flag. But it works okay.
