### ISSUE TITLE
[Warrior skill] Victory Rush - is still activ

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#564]
Decription: 
ENG: Victory Rush - Warrior skill is active all the time, i can make 100% of my dmg only by using this 1 skill.
PL: Victory Rush - Warrior skill nie ma cd, moge go uzywac ile chce i kiedy chce w ciagu tej samej walki.

How it works: 
like in Decription

How it should work: 
ENG: Victory rush is ready to use only after you will kill oponent (that gives you exp or honor)
PL: Victory rush powinine być gotowy do użycia tylko po zabicu przeciwnika (i to takiego ktory daje exp albo honor)

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_100118_211656](https://user-images.githubusercontent.com/43553985/46310705-642f1500-c5c0-11e8-8d43-96b5a90038c5.jpg)

**Comment by notsofamous** [comment]
It shouldn't have a cooldown, but the issue is that it's always activated. Should only be active after you score a killing blow on and enemy that yields honor or xp. (buff lasts 20 sec)

**Comment by Riztazz** [comment]
A typo in aura state:P

**Comment by Bursztynek** [comment]
well... its a bit funny but my friend told me, he left his warior character in Mageterion instance. So...
