### ISSUE TITLE
Attumen the Hunstman - no charge?

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#566]
Decription: 
boss shoud have charge skill - we didnt notice any of charge. 
boss powinien uzywać skilla "szarża" - niezanotowaliśmy pojedynczego użycia.

How it works: 

How it should work: 
Boss is useig all his skills

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Attumen_the_Huntsman  -berserker charge

**Comment by notsofamous** [comment]
Duplicate https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/548
