### ISSUE TITLE
Mobs atack issue in Kara 

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#567]
Decription: 
ENG: I was far away from the group, mobs (after wipe) atacked me. 
After killing me they still atack my dead body.
Plus mobs were anable to atack "Evade" to the rest of group after they resurect.

PL: zostałem w tyle daleko od grupy, grupa zaliczyła wipe, moby przerzuciły się na mnie mimo ze byłem bardzo daleko od grupy.
Po zabiciu mojej postaci moby atakowaly moje martwe cialo.
Dodatkowo gdy reszta grupy się wskrzeciła (i przyszła do mojego trupa) mobów nie dało się bić, gracze mówili że mają "Evade" problem.

How it works: 
step 1 -> die from mobs, "wipe"
step 2 -> dont use [release the spirit]
step 3 -> watch like mobs still atacks your dead body
step 4 -> players from your team use release spirit.
step 5 -> players from your team rush back to the Kara as a ghousts
step 6 -> players from you team resurected (entering the kara)
step 7 -> watch like your team m8ts can't atack mobs. Mobs are ignoring your team, and still atacking your dead body.
step 7a -> players from your team have "Evade problem" 

How it should work: 
ENG:
1. Mobs shoudnt atack me if i was far away from group at all.
2. after killing his target mobs shoud rush to his based spot.

PL:
1. Moby nie powinny atakowac gracza który jest daleko od grupy która złapała combat.
2. po zabicu ostatniego gracza moby powinny wrocić do swojej bazowej pozycji.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_100118_213806](https://user-images.githubusercontent.com/43553985/46311933-eec54380-c5c3-11e8-96e4-19e9fc7cd3ad.jpg)

Evade problem dla pozostałej części grupy - after resurection:
![wowscrnshot_100118_214026](https://user-images.githubusercontent.com/43553985/46312036-30ee8500-c5c4-11e8-9470-1cddcfcc9e0f.jpg)

**Comment by notsofamous** [comment]
Duplicate https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/548

(Task number 10)

**Comment by Bursztynek** [comment]
task number 10 is telling about the 1 part of this issue. - and true its duplicate on this one.

But the secend thing -> mobs still atack dead body is not there.
