### ISSUE TITLE
Meta gem problem - grey

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#568]
Decription: 
**ENG:** Meta gem is still "grey" even if the requirements are fulfilment. Screen. Its not a visual bug.., im lack of 26 BH. Character have like 4 purple gems in other items. And Meta is still grey. 

**PL:** Meta gem jest ciagle szary mimo spełnionych wymagań. Jak na screenie. To nie jest visual bug. brakuje mi 26 BH. Postac ma 4 filotowe gemy w innych itemach. Mimo to Meta jest szary.

How it works: 
like in decription

How it should work: 
ENG: Purple gems shoud count as a blue and red gems to power up Meta gem.
PL: Fioletowe gemy powinny być liczone jako niebieski i czerwony gem by zasilić Meta gema.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_100118_222314](https://user-images.githubusercontent.com/43553985/46314121-f7b91380-c5c9-11e8-99ba-830644195076.jpg)

**Comment by notsofamous** [comment]
Works for me. Requires MORE red gems than blue gems. If you're only using purple gems then:
red = blue
when you need:
red > blue

Exactly how many gems do you have of each colour?
