### ISSUE TITLE
Buff from item is activated after any action

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#569]
Decription: 
Masquerade Gown - chance on spell cast to increase your Spirit by 145 for 15 secs. Buff was activated after i go entry in to Kara.

How it works: 
Were items thats have chance to give you some kind of buff (like in decription), just go do random staff like: entry Kara. Buff is activated 

How it should work: 
only spell casts should activate buff.

Source (you should point out proofs of your report, please give us some source): 

![wowscrnshot_100118_234721](https://user-images.githubusercontent.com/43553985/46317789-86329280-c5d4-11e8-9650-4c7a44ede9ee.jpg)

**Comment by Bursztynek** [comment]
up date:
ENG: buff from items can be activated even if you are chosing your talents in talents tree.
PL: buff z itemów może się aktywować nawet jeżeli wybierasz talenty w drzewie talentów.

![received_2227355450886031](https://user-images.githubusercontent.com/43553985/46335284-3df09000-c627-11e8-8161-46d6fd1e3d7e.jpeg)

**Comment by zapsuu** [comment]
On HG this same bug was on the Darkmoon Faire: Blue Dragon trinket. I remember that this trinket procs from mount up and even when we go into fire.

**Comment by Bursztynek** [comment]
i remeber in old HG DPS trinket from Muru had also a problem with "stuck reset" when u get stucked 440+ AP its hold up for whole fight.

**Comment by zapsuu** [comment]
I think this problem is solved. I tried to repeat this bug, but I can't.
