### ISSUE TITLE
Kara ID problem

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#570]
Decription: 
ENG: After teleporting in to Kara with my friend (both we have same ID 1851) we see comunicat "You are not in this isntance's group. You will be teleported to GM Island in 60 sec." The reson is we that we have in party (in that case even offline, and not a lider) a person who dont have our id or its clean. 
So... we are in our ID and its tells us we are not.

PL: Po teleportowaniu do Kara ja + kolega (obaj mamy te same ID 1851) widzimy komunikat że "za chwile będziemy teleportowani do GM Island" Taka sytuacja wystepuje jak mamy w party osobę z innym lub bez ID, mimo ze dana osoba nie jest liderem ani nawet nie jest online... Gra mówi nam że nasze ID nie jest nasze i zaraz nas wyrzuci.

How it works: 
Like in description.

How it should work: 
Logic - same ID numer, and 1 of us is the lider... so its our ID.

Source (you should point out proofs of your report, please give us some source): 

![wowscrnshot_100118_234754](https://user-images.githubusercontent.com/43553985/46317809-9ba7bc80-c5d4-11e8-8873-e6c91f351fcf.jpg)

**Comment by akrom23** [comment]
The offline was inside the instance?

**Comment by Bursztynek** [comment]
well... its a bit funny but my friend told me, he left his warior character in Mageterion instance. So...

**Comment by akrom23** [comment]
Cannot reproduce. Maybe other players have this kind of problem with IDs?

**Comment by Bursztynek** [comment]
we will try to reproduce and bring you more data.

**Comment by Bursztynek** [comment]
im not eable to reproduce it. Not enaugh ppl online to do Kara.

**Comment by akrom23** [comment]
Any news?
