### ISSUE TITLE
[Mage][Spell] Invisibility

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#571]
Decription: 
Spell
Fades the caster to invisibility over 5 sec, reducing threat each second. The effect is cancelled if you perform or receive any actions. While invisible, you can only see other invisible targets and those whom can see invisible. Lasts 20sec.
How it works: 
1. When the spell is activated, the character receives a debuff for 5 sec, after 5 seconds the debuff disappears and there is no any effect.

How it should work: 
When a character activates an ability, he gains a buff for 5 sec, if during these 5 seconds the character does not receive any damage or does not any actions, it goes into invisibility.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_100218_005150](https://user-images.githubusercontent.com/43764742/46318247-80da4580-c5de-11e8-8c3f-3c1271ffb8cb.jpg)
https://www.youtube.com/watch?v=qDmldQCuHvE

**Comment by arcwizard** [comment]
Invisibility works correctly, with the exception of one minor visual bug: at the time of activation, a debuff(Fadding) appears for a few seconds (as on the first screenshot), although there must be a buff (as in link to video from YouTube). 
But  this is not critical and does not affect anything, only a visual difference.

**Comment by lukaasm** [comment]
Debuff case should also be fixed after:
https://github.com/SunwellWoW/Sunwell-TBC/commit/2266305efd6febad9d73d386b0a381593f782d21

**Comment by arcwizard** [comment]
The transition to invisibility works correctly, but another bug was noticed.
Decription:
Fades the caster to invisibility over 5 sec, reducing threat each second.
How it works:
In the first second after the activation of the spell, the character drops all threat.
How it should work:
Every second for which Invisibility is counting down, the mage will lose threat; however, if he/she chooses to end the fade prematurely, he/she will lose a minimal amount of threat. Once the timer hits 0, the mage gains full invisibility and is removed from combat.

Addition:
The description does not indicate the value, however before the last correction (when activating a spell instead of a buff gave a debuff)  at the time of the 5 second debuff (Fading), the threat was gradually reduced to a certain value (the exact value i was not calculated), and after to fade to complete invisibility, it was completely reset as it should be.
The difference is that during fading to complete invisibility the mage can took damage on 1, 2, 3 or 4 seconds and lose the possibility of transition to invisibility, but if the whole threat is reset in the first second, then he gets an advantage over mage who received damage for example, at 2 seconds.

http://wowwiki.wikia.com/wiki/Invisibility

**Comment by lukaasm** [comment]
I cannot reproduce threat reducing issue:

![obraz](https://user-images.githubusercontent.com/48881/46690141-de374d80-cc01-11e8-90de-48a8b98552a4.png)

I have generated 100k threat on NPC and tried to print threat table after each proc tick( ~1s ).
I have removed manual % calculation and used a real spell for threat reduction but it should generate exactly the same outcome.

.debug threat should be available soon on PTR for threat testing

**Comment by notsofamous** [comment]
Works, can close.

**Comment by Wojtyas** [comment]
Fixed & implemented.
