### ISSUE TITLE
[Mage][Spell+Talent] Blizzard (with Arcane Concentration)

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#572]
Decription: 
Arcane Concentration (5/5 talents): 
Gives you a 10% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 100%.
Blizzard (rank 7):
Ice shards pelt the target area doing 1192 Frost damage over 8sec.

How it works: 
Talent Arcane Concentration works incorrectly when combined with Blizzard, repeatedly proc. during one Blizzard cast (the frequency depends on the number of mobs under the blizzard).

How it should work: 
Chance of proc. Arcane Concentration must be calculated on the activation of the Blizzard.

Source (you should point out proofs of your report, please give us some source): 
Here is a video where a mage with Blizzard kills 30 (!) mobs, pay attention to his buffs, and the frequency of appearance of the Clearcasting buff there. That Mage use Frost Nova either, and for the whole fight, it can be seen Clearcasting only proc. 2 times and both times were only after Frost nova (which have direct damage). 
https://www.youtube.com/watch?v=unusjpGt8bY

**Comment by akrom23** [comment]
So it should be activated on cast, not on hit?

**Comment by arcwizard** [comment]
No, he has to work with different spells in different ways, such as the lasso blast, fire blast, ice bolt (i.e. direct damage and 1 caste for 1 target), a 10% chance will be anyway, because 1 cast = 1 hit. Blizzard is a channel spell, inflicting damage on the area, it cannot be criticized, it doesn't get charges of shaman’s shields, therefore it is difficult to call it direct damage, and in that video you can see that there was no one clearcasting while blizzard, but there were 2 proc from frost nova (which can be critical and takes the charge of the shield when hit) of three castes (however, it is not known how many points this magician put in arcane concentration). Regarding Arcane missiles, there is a chance to get a prok calculated from each missile, and only in 3.0.8 patch they changed it (http://wowwiki.wikia.com/wiki/Patch_3.0.8).

P.S. Now the arcane concentration (and therefore arcane potency) is not working at all, from any spells.

**Comment by arcwizard** [comment]
No, he has to work with different spells in different ways, such as arcane blast, fire blast, ice bolt (i.e. direct damage and 1 caste for 1 target), a 10% chance will be anyway, because 1 cast = 1 hit. Blizzard is a channel spell, inflicting damage on the area, it cannot be criticized, it doesn't get charges of shaman’s shields, therefore it is difficult to call it direct damage, and in that video you can see that there was no one clearcasting while blizzard, but there were 2 proc from frost nova (which can be critical and takes the charge of the shield when hit) of three castes (however, it is not known how many points this magician put in arcane concentration). Regarding Arcane missiles, there is a chance to get a prok calculated from each missile, and only in 3.0.8 patch they changed it (http://wowwiki.wikia.com/wiki/Patch_3.0.8).

P.S. Now arcane concentration (therefore arcane potency) is not working at all, from any spells.

**Comment by akrom23** [comment]
This spell is messy as hell :P
https://github.com/Looking4Group/L4G_Core/issues/2434
Some can give me accurate information? Why blizzard did so many exceptions to only one spell?

**Comment by arcwizard** [comment]
About arcane missiles in this video (https://www.youtube.com/watch?v=c2RtyFh5TnE) you can also see that clearcasting appears earlier than the first missile hits the target (and acts until the next cast, which means that all 5 missiles will receive a bonus from arcane potency), i.e. the calculation on trigger clearcasting doesn't occur at the moment of hit, but immediately after the activation of spell. It may make it possible to assume that calculation of clearcasting goes solely on the first hit (if not info from http://wowwiki.wikia.com/wiki/Patch_3.0.8), but this can only be know if  mage would cast non stop 10-20 spells arcane missiles for one target.
At the expense of the blizzard, i am not sure on 100% how this should work, but I am sure how it shouldn't: it shouldn't give much proc's clearcasting for one cast, and video (https://www.youtube.com/watch?v=unusjpGt8bY) confirms this.

**Comment by arcwizard** [comment]
I either think this is stange, but idk how else it would be possible to interpret what we saw on video https://www.youtube.com/watch?v=c2RtyFh5TnE. But if based on this video, i think the calculation (for chance of triggering, based on the chance of hitting) of clearcasting occurs immediately at the time of subtracting mana: for channel spells this is the moment of activation, for instant spells and casting, this is the moment of end cast.

**Comment by maciekk57** [comment]
What i also noticed, when you trigger clearcasting during channeling arcane missles, you consume this effect if there are some hits left (aka wasting it)

**Comment by zapsuu** [comment]
maciekk57, correctly, I've seen this too.

**Comment by akrom23** [comment]
So, let's summarize that:
1. Generic rule - clearcasting should proc when spell hits target and do damage.
2. Channeled spells - clearcasting should proc on cast/activation (not on first tick), regardless of hit target? So Blizzard can proc Clearcasting event if there are no enemies around? And Arcane Missiles can proc event if target is e.g. immuned to all ticks?

**Comment by grand-lotus-iroh** [comment]
Channeling Arcane Missile **does not** proc Arcane Concentration Clearcasting state... it should. Each Arcane Missile bolt tick should have a 2% to 10% chance on spell hit to proc Arcane Concentration Clearcasting state.

Arcane Concentration Clearcasting state means your next spellcast will be 100% reduced mana (free spell). Please fix broken code.
