### ISSUE TITLE
[Item] The Lightning Capacitor (28785)

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#574]
**Decription:** 

**How it works:** 
Does not produce charges.

**How it should work:** 

> The way, this trinket works is quite complicated and on most sites fairly misunderstood. First of all, the bolt emitted by this trinket is not affected by +spell damage anymore (since Patch 2.1), it can however crit/be resisted and is affected by the characters Nature spell crit and hit chance, and any nature damage vulnerability debuffs (such as Stormstrike). The crits of the bolt do not produce a charge, but any spell-like critical hit inflicted by your character will produce a charge, e. g. Molten Armor, Lightning Shield, etc. and of course single target direct damaging spells and AoE spells.

> The tooltip is somewhat misleading regarding the 2.5 second internal cooldown. Electrical charges CAN be gained on every critical strike except for the first 2.5 seconds after a bolt goes off. This means it's possible to get 3 crits at once (for example, from an AoE spell hitting multiple targets) and fire off a single bolt. However, any further crits will not produce charges until after 2.5 seconds. This effectively limits the bolts to one per 2.5 seconds. A more correct tooltip might read: "Electrical Charge cannot be gained for 2.5 seconds after a Lightning Bolt is fired."

> The effect of this trinket is badly expressed as spell power, but rather as a flat crit-damage bonus and can easily be calculated as dps-gain, as the calculations below will demonstrate.

> Because it is direct nature damage it can be partially resisted, but this is not considered in the following calculations, as most PvE encounters are either completely nature immune or do not have noticeable resistances at all. These calculations refer to single target direct damage casting. The italic lines are examples with 30% nature crit, 94% hit chance and Scorch spamming (34% scorch crit, same hit, 1.5s casting time). It has to be noted, that Arcane Missiles have to be considered as 1s casting time, as every missile can crit and thus produce a charge, 5 missiles in 5 sec is 1 missile / sec. 

**Source (you should point out proofs of your report, please give us some source):** 
https://www.wowhead.com/item=28785/the-lightning-capacitor
http://wowwiki.wikia.com/wiki/The_Lightning_Capacitor

**Comment by zapsuu** [comment]
There is no GCD 2,5 sec. I checked it on my warlock.
I spammed rank 1 shadow bolt (1,2sec) one by one and got 2 stack after 2 casts. It will be easier to check by spamming Searing Pain (more crit talented) or frost mage or arcane missles.

![wowscrnshot_100718_222159](https://user-images.githubusercontent.com/43937876/46586514-eff0e780-ca7f-11e8-85bf-4d75405c5648.jpg)

**Comment by notsofamous** [comment]
That's how it's supposed to work, the CD is only triggered at 3 stacks when the bolt is released

**Comment by Nadiirr** [comment]
Based on the source the cooldown is after the bolt goes off. So looks like it's working properly.

Thanks.
