### ISSUE TITLE
[Item] Quagmirran's Eye (27683)

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#575]
**Decription:** 

**How it works:** 
Refreshes all the time. Does not have a 45 sec internal CD.

**How it should work:** 
45 second internal CD, 10% proc rate.

> Rumored to be 10% proc and 45s internal cooldown after proc. 

> From what I know, the proc rate is about 10% with a 40-or-so second internal cooldown.

**Source (you should point out proofs of your report, please give us some source):** 
http://wowwiki.wikia.com/wiki/Quagmirran's_Eye
https://dwarfpriest.wordpress.com/2007/10/08/procs-when-you-least-need-it/
http://bbs.comefromchina.com/threads/557370/
https://www.wowhead.com/item=27683/quagmirrans-eye&bonus=4105#comments:id=300674

**Comment by lukaasm** [comment]
I will change label to retest needed after PTR update :)
`Resolved - fix NOT live yet` will be used by me to mark issues addressed but not applied on PTR yet.
