### ISSUE TITLE
[Raid] Magtheridon

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#576]
- [x] 1. This guy is never channeling into the node when you enter the instance, works if you pull and reset the trash pack.
![Image](https://i.gyazo.com/d5ebafb6ecd2ba2e3ea430fc91586e9b.png)

- [x] 2. Any trash that isn't killed should be pulled to the boss room if Magtheridon is engaged

- [x] 3. Hellfire channelers all seem to summon Burning Abyssal at exactly the same time, it should be more random.

- [x] 4. Magtheridon only drops 1 chest token + gold right now. He should also drop 2x random epics from his loot table.

**Comment by Kokaina** [comment]
1. Seems to be visibility/reload problem as we figured it out with Anakin.

**Comment by notsofamous** [comment]
Add a out of combat refresh cast?

**Comment by Silroth** [comment]
-  Hellfire channelers all seem to summon Burning Abyssal at exactly the same time, it should be more random.

Timer for Summon Burning Abyssal is not random, its used every 30 seconds, if you are solo testing then you will prob get hit by all 5 of them but with 25 players they wont land them on same person (unless that guy is extremely unlucky)

**Comment by notsofamous** [comment]
https://youtu.be/v0PNXZYuAnU
1:05 fight starts
1:31 can see that an elemental has already spawned to the left in the screen. (it wasn't there at 1:22 when the mage looked left, so it spawn somewhere between that)
1:44 you can see another elemental spawn to the left (~20-13 seconds after we saw the first one)
1:52 another one spawns right in front of the mage
2:09 another one has spawn in the background

2:21 mage looks left and sees 4 elementals now up, one of them (near magtheridon) despawns. This was the first one we saw appear.
2:43 another one despawns, this was the second one we saw.
2:46 one more despawns

etc...

so no, they shouldn't spawn at the same time

**Comment by akrom23** [comment]
> 2. Any trash that isn't killed should be pulled to the boss room if Magtheridon is engaged

How trash can go through the closed gate?

**Comment by notsofamous** [comment]
Glitch through it I guess? 

> Firstly, clear all the trash mobs as they will come to defend Magtheridon should you attack him.

https://wow.gamepedia.com/Magtheridon_(tactics)

**Comment by akrom23** [comment]
It will be very strange.

**Comment by notsofamous** [comment]
https://youtu.be/yomeJ2Mi-iM?t=1m56s

**Comment by akrom23** [comment]
These are not TBC, but I've found this: https://www.wowhead.com/magtheridons-lair#comments:id=68772

> The respawn timer on the trash is 1 hour giving, and if you have megtheridon engaged, and any of HIS channelers are alive and the trash warders respawn, they will aggro into Mags room and kill you all.

Very strange... Maybe they just teleport there?

**Comment by notsofamous** [comment]
No I genuinly think they should glitch through the door

**Comment by akrom23** [comment]
Alright.
