### ISSUE TITLE
Core/Spells: Spell steal

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#578]
Decription: 
Krosh Firehand (Mage council) 
Casts a Spell Shield which a mage can Spellsteal. It reduces incoming spell damage by 75%, and lasts for 30 seconds.

How it works: 
Don't work spellsteal, just don't work. Krosh buff himself Spell Shield and when i use spellsteal game write: "nothing to steal".
Other man which was mage-tank try spellsteal it and could not, u can see it on screenshot.
![wowscrnshot_100218_221119](https://user-images.githubusercontent.com/43764742/46372465-e6d4d480-c693-11e8-8249-c2db7e9649bc.jpg)
After his death, I also tried, but I could not.

How it should work: 
Krosh has a Spell Shield which reduces magic damage taken by 75%. A mage must Spellsteal this to remove the Spell Shield from Krosh and protect himself from Krosh's fireballs...

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/High_King_Maulgar

**Comment by arcwizard** [comment]
Seems the problem is not in Maulgar, but in [spellsteal](http://wowwiki.wikia.com/wiki/Spellsteal), now i used [spellsteal](http://wowwiki.wikia.com/wiki/Spellsteal) in Karazhan when tried steal [Shadow Rejuvenation](https://www.wowhead.com/spell=29587/shadow-rejuvenation#used-by-npc) from [Phantom Attendant](http://wowwiki.wikia.com/wiki/Phantom_Attendant), and there is the same situation, I cannot remove the buffs from anyone.

**Comment by Riztazz** [comment]
Please re-test after PTR update

**Comment by Silroth** [comment]
Works fine now.
