### ISSUE TITLE
Loot issue

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#580]
When raid leader got DC'ed creature loot wasn't assigned to raid no more.

Once leader is back after he log in creature is assigned to raid back again.

![image](https://user-images.githubusercontent.com/22802214/46381249-c4e44d80-c6a5-11e8-9910-ad5ceff13052.png)

**Comment by akrom23** [comment]
Group loot or master loot?
