### ISSUE TITLE
[Paladin] Illumination talent is not working

### ISSUE THREAD

**Issue by kohyb** [SunwellWoW/Sunwell-TBC-Bugtracker#581]
Decription: flash of light costs 180 mana and after critical strike from illumination talent I should receive 108 mana back (60% from 180 mana). After critting I'm getting no mana back. Scrolling text addon is not displaying that (and should). I was testing that on low mana... I had 220 mana, used flash of light and I stayed on 40 mana. At the moment after heal + crit I should have 148 mana.

How it works: After critical strike, character should receive back 60% of mana from spell that was used and is not getting any mana back (flash of light or holy light).

Youtube link:
https://www.youtube.com/watch?v=yfgxM6R3ZxA&feature=youtu.be

**Comment by kohyb** [comment]
> 
> 
> Decription: flash of light costs 180 mana and after critical strike from illumination talent I should receive 108 mana back (60% from 180 mana). After critting I'm getting no mana back. Scrolling text addon is not displaying that (and should). I was testing that on low mana... I had 220 mana, used flash of light and I stayed on 40 mana. At the moment after heal + crit I should have 148 mana.
> 
> How it works: After critical strike, character should receive back 60% of mana from spell that was used and is not getting any mana back (flash of light or holy light).
> 
> Youtube link:
> https://www.youtube.com/watch?v=yfgxM6R3ZxA&feature=youtu.be

Working as should now, crits with healing spells are returning back the right amount of mana.

**Comment by Finvy** [comment]
Issue appears to be persistent on live servers.  See video below demonstrating combat log indicates mana refund but mana bar is not adjusted accordingly.

https://www.youtube.com/watch?v=gtRq-tm7dtw
