### ISSUE TITLE
[Zones][Dungeons/Heroics] Patroling problem.

### ISSUE THREAD

**Issue by Unfairy** [SunwellWoW/Sunwell-TBC-Bugtracker#59]
Decription: 
Patroling mobs problem. lack of scripts.

As I was testing BEM Quests I remembered one of the nastiest things from Hellground / Wargate.
And its lack of patroling mobs in general.
Like, every location, every zone, some of dungeons. Where mobs supposed to patrol with pairs / or just alone - on hellground and wargate they just were staying.
Saw a lot of cases in BEM, I can imagine that its fair for every zone and dungeon, but as I didnt tested it myself - cant say for sure.

**Comment by Nadiirr** [comment]
A bunch of these were fixed. If there are still issues please report specific ones. Thanks <3
