### ISSUE TITLE
Fel Intellect / Fel Stamina - Warlock Demo Talent

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#594]
Decription: 
Fel Intellect - Increase demons Intellect by 15% and warlocks mana by 3%. 
Pets don't get Intellect and mana after getting checking this talent. After resummoning nothing change. Warlock gives 3% mana correctly.

Fel Stamina - Increase demons Stamina by 15% and warlocks hp by 3%.
Same situation as above.

How it works: 
Pets don't get Intellect/Stamina from both of this talents.

How it should work: 
Pets should get 15% Intellect/Stamina after choosing the talents. They should get more mana and hp.

Source (you should point out proofs of your report, please give us some source):

**Comment by Silroth** [comment]
Just tested both, they work but require relogging for the talents to take effect.

**Comment by zapsuu** [comment]
Works good.
