### ISSUE TITLE
[Core] Casts interrupted by turning (with mouse)

### ISSUE THREAD

**Issue by Haipethdev** [SunwellWoW/Sunwell-TBC-Bugtracker#6]
Description: 
Casts, including mounting, are being interrupted by turning with the mouse

How it works: 
Casts being interrupted

How it should work: 
They should continue to cast

Source (you should point out proofs of your report, please give us some source): 
In-game attempting to mount on char: Tyba

**Comment by Azathothh** [comment]
It's interrupted if you're turning with keyboard bind as well, but only if you will stop turning before cast is finished.
So for 2sec cast: 
a)you're turning with keyboard for 1.5sec - it will be interrupted
b) you're turning with keyboard for 2.1sec - it won't be interrupted
With mouse it's always interrupted.
