### ISSUE TITLE
[Core] Buff overwriting

### ISSUE THREAD

**Issue by nimeral** [SunwellWoW/Sunwell-TBC-Bugtracker#600]
Decription: weaker buffs overwrite stronger buffs

How it works: if I apply MotW rank 4, it just overwrites MotW rank 5. Same happens for Rejuvenation (not screenshotted, and not 100% sure it's a bug).

How it should work: if I try to apply a weaker buff, I should receive a message "a more powerful spell is already active", and nothing else should happen

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/36lgKQC

**Comment by notsofamous** [comment]
Same issue as https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/385
