### ISSUE TITLE
Hellfire Ramparts (Normal) Loading bug

### ISSUE THREAD

**Issue by ryredan** [SunwellWoW/Sunwell-TBC-Bugtracker#602]
Description: 
I can not enter the dungeon with a group

How it works: 
When I tried to enter HR Normal with a group multiple times I got stuck in the loading screen, in one of the relogin attempts I was teleported to Desolace, When I try entering alone on Normal mode or in a group on Heroic mode with a group it works fine

How it should work: 
I should enter the dungeon normally.

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/20247441/46631014-82df5f80-cb1c-11e8-89ec-6fd0de72b9fc.png)

**Comment by Wojtyas** [comment]
Was probably present when beta was hit by first dungeon testings. Probably it got fixed.
