### ISSUE TITLE
[Dungeon] Slave Pens Heroic Loading Bug

### ISSUE THREAD

**Issue by Rylanor** [SunwellWoW/Sunwell-TBC-Bugtracker#603]
Decription:  Everyone in my group cannot enter the dungeon upon using the dungeon master to teleport to the dungeon. They get stuck on a loading screen permanently or teleported to Stonetalon mountains where they fall and die.

How it works: The group leader clicks to teleport to the dungeon and all group members except me get stuck on a permanent loading screen and have to restart the client or they get teleported above Stonetalon Mountains where they fall and die.

How it should work: The group clicks to teleport to the dungeon and all group members get teleported there.

Source (you should point out proofs of your report, please give us some source): Player reports and secondhand information.

**Comment by akrom23** [comment]
#602.
