### ISSUE TITLE
Mage: Blink

### ISSUE THREAD

**Issue by Slakbanan** [SunwellWoW/Sunwell-TBC-Bugtracker#605]
Decription: Mages blinks doesnt work in stairs / ramps

How it works: Mages blinks doesnt work in stairs / ramps

How it should work: Mage should be able to use blink in stairs and ramps

Source (you should point out proofs of your report, please give us some source):

**Comment by Silroth** [comment]
Can you provide examples?

**Comment by akrom23** [comment]
Some screenshots?

**Comment by Wojtyas** [comment]
I guess it was fixed while ago. Feel free to reopen in any cases.
