### ISSUE TITLE
Warlock: Ritual of Summoning

### ISSUE THREAD

**Issue by Slakbanan** [SunwellWoW/Sunwell-TBC-Bugtracker#606]
Decription: Warlocks summon

How it works: Warlocks summon require 2 shards instead of 1!

How it should work: It should on require 1 shard!

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Some screenshots?

**Comment by Silroth** [comment]
When Ritual of Summoning is cast it consumes a shard then the spell is recast and consumes another shard which shouldnt happen.
