### ISSUE TITLE
Event timer in Blood furnace

### ISSUE THREAD

**Issue by Slakbanan** [SunwellWoW/Sunwell-TBC-Bugtracker#607]
Decription: The doors opens to quick on second boss!

How it works: The doors to the mobs opens by timer!

How it should work: It should open once one trash pack is killed!

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Once each wave is defeated (or approximately two minutes has passed since the last wave was released) the next wave will come immediately. Once the fourth wave is defeated, the gate will open and Broggok will come immediately.

**Comment by Riztazz** [comment]
closing this one, https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/644 has the same issue and in general is better report
