### ISSUE TITLE
Karazhan

### ISSUE THREAD

**Issue by Slakbanan** [SunwellWoW/Sunwell-TBC-Bugtracker#608]
Decription: Wizard of OZ

How it works: Strawman doesnt get effected by fire spells!

How it should work: Strawman should get effected and shouldnt attack people when he get's hit by fire spells!

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
@Afgann I though it worked last time. He should be disoriented after hit by fire spell ;p
