### ISSUE TITLE
Always stuck in combat in TBC dungeons.

### ISSUE THREAD

**Issue by Moistcookie** [SunwellWoW/Sunwell-TBC-Bugtracker#609]
Decription: Every dungeon I've been in makes the party stuck in combat forever as soon as you pull the first pack. Fixing it to where you drop combat after a fight is done would be sweet.

How it works: Stuck in combat forever, even after all mobs are killed, after pulling first pack in dungeons.

How it should work: Drop combat after each fight is done and all mobs are dead.

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
This probably not related to dungeons itself but dummies on GM island that put you in combat and threat system in general, i will look into it

**Comment by Moistcookie** [comment]
Aight

**Comment by akrom23** [comment]
So everything's okay?
