### ISSUE TITLE
Combat Range

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#61]
Decription: A correction to combat range is needed.

How it works: Combat range (distance that npc will chase player) is set to ~40y, which is extremely low.

How it should work: Combat range (distance that npc will chase player) should be around 60-70y (if someone has a source with exact distance let us know!).

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Those distances are approximate, if someone has source with exact info please share ;)

**Comment by Riztazz** [comment]
please test after restart

**Comment by Kokaina** [comment]
Seems to be ~70y now, well done Ceasar.
