### ISSUE TITLE
Paladin - Righteous Fury is a debuff

### ISSUE THREAD

**Issue by absolutionxi** [SunwellWoW/Sunwell-TBC-Bugtracker#611]
Decription:  Title

How it works: Title

How it should work: Should be a player buff, not a debuff.

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/30010305/46634500-f32eb680-cb05-11e8-9833-ea01053723d8.png)

**Comment by notsofamous** [comment]
Works, can close.
