### ISSUE TITLE
Bleed effects on the mechanical mobs

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#613]
Decription:
We can put bleed effects on the mechanical mobs (for example first trash on Botanica/Mechanar), but we shouldn't can do it.

How it works: 
Mechanical mobs take dmg for bleed effects.
![wowscrnshot_100818_214248](https://user-images.githubusercontent.com/43937876/46635000-2f3c3880-cb53-11e8-981e-c5558d3979b7.jpg)

How it should work: 
Mechanical mobs should be immune on bleed effects.

Source (you should point out proofs of your report, please give us some source):

**Comment by notsofamous** [comment]
Should also be immune to Fear effects, Diseases and any life draining effect (drain life, siphon life, lifestealing) 

![Image](https://i.gyazo.com/deffbd507c32a26658beacc9eb66e9c9.png)
https://us.battle.net/forums/en/wow/topic/3657608499#post-19
http://wowwiki.wikia.com/wiki/Mechanical
