### ISSUE TITLE
Mind Controlled mobs - no GCD

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#614]
How it works: 
MC'ed mobs by priest haven't gcd on their abilities. We can just spam any spell all time. We can spawn a lot of mobs (like on Auchieon Crypts - Auchenai Soulpriests) or spam Moonfire (like Witch naga on Steamvault).  

How it should work: 
Any cast should have 1,5sec gcd.

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/636
