### ISSUE TITLE
Mind Control - agro bug

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#615]
Decription: 
When MC'ed mob attack another one, the agro from the attack make agro on the priest.

How it works: 
Priest take agro, when he attack by MC'ed mob another mob. 
PL: Priest nabija sobie samemu agro atakując kontrolowanym mobem.

How it should work: 
MC'ed mob should take agro, not the priest. The MC'ed mob should can tank another trash until he die or something break MC.

PL: To kontrolowany przez priesta mob powinien nabijać sobie agro i tankować tego moba aż prejowi zostanie przerwane MC, efekt się skończy lub aż mob zginie. Na ten moment jest to niemożliwe, ponieważ tank musi i tak brać agro na siebie.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Seems to be okay. Threat is generated by MC'ed mob and the priest is only with combat with it's target. Nothing more.

**Comment by akrom23** [comment]
Any news?

**Comment by zapsuu** [comment]
I think everything is now alright.

**Comment by akrom23** [comment]
So give me some screenshots or video.

**Comment by zapsuu** [comment]
I think I know, what is a problem.
When my MC mob attack from melee, mobs were focus on him, but when he used a spell/skill, then agro went on me.

![wowscrnshot_111318_210601](https://user-images.githubusercontent.com/43937876/48442502-aab28a80-e78e-11e8-8a23-47ce7386bf47.jpg)
![wowscrnshot_111318_210602](https://user-images.githubusercontent.com/43937876/48442504-aab28a80-e78e-11e8-98f4-1e10abd4b31c.jpg)

**Comment by zapsuu** [comment]
Attack mob by skill (check mob target)
![wowscrnshot_111318_221157](https://user-images.githubusercontent.com/43937876/48444274-c2d8d880-e793-11e8-9e7e-95d436a189be.jpg)
![wowscrnshot_111318_221202](https://user-images.githubusercontent.com/43937876/48444273-c2404200-e793-11e8-8f27-c1be5851d9ac.jpg)

**Comment by zapsuu** [comment]
Agro by melee attacks (MC mobs can melee by backs ;p)
![wowscrnshot_111318_221225](https://user-images.githubusercontent.com/43937876/48444728-10097a00-e795-11e8-83fc-11f77ee351b7.jpg)

**Comment by zapsuu** [comment]
123
