### ISSUE TITLE
Trash packs don't reset after wipe

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#616]
Decription: 
When we kill 1/2 mob in 3 mobs pack and we wipe, the dead mobs don't reset. 

How it works: 
When we kill 1/2 mob in 3 mobs pack and we wipe, the dead mobs don't reset.

How it should work: 
We should kill all mobs in pack without wipe to avoid their reset. After wipe all mobs should reset (return to life).

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Any source/proof? I believe it should work on raids but not sure about dungs.

**Comment by zapsuu** [comment]
https://www.youtube.com/watch?v=AMhMcysXNjw

On this video on 1:40 you can see, that when hunter pull first guardian, the second one takes agro. This is a proof that these 2 mobs are not only 2 mobs, it's a pack, which you have to kill or avoid to push your run. The mechanic is the same as on raids.

https://www.wowhead.com/npc=17958/coilfang-defender#comments

Here you can read that people had problems with them, because they hit really hard and cannot CC them and tank only 1 of them.

**Comment by Kokaina** [comment]
Okey but this is not proof they should both respawn if any of them evades. There are also plenty of packs in pure world but they don't respawn when 2 of 3 adds are killed and we wipe on third. For example 4 alliance npcs walking through barrens, its pack but they won't respawn like u described and im asking about that :P 

Not every pack works like u described, I know they should work like this on raids but just not sure if on dungeons as well. I was searching for videos where people wiped on thrash in 2008 but couldn't find any so far ;(

**Comment by zapsuu** [comment]
If you pull pack in open world, you can always run, lose 2 of 3 mobs and just kill this 1mob. On the instance you cannot do it. I also tried to find it on old movies and on comments in NPC in dungeons, but I cannot find it.

**Comment by Riztazz** [comment]
Obviously because creatures in instances will chase you forever unless scripted otherwise (boss evade when leaving room or something).
I can make a group respawn on evade easily and i know its valid for trash packs in some raid instances but is it valid for 5 mans? I dont think so to be frank

**Comment by akrom23** [comment]
Any news here?

**Comment by Ibuprofeno** [comment]
I can't recall this happening in all content. IIRC it happened in 25M but never in KZ/dungeons. Will try to lurk for a source as I haven't found anything relevant in a quick search.
