### ISSUE TITLE
Spirit of Redemption

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#618]
How it works: 
After priest dead mobs still have agro on the priest and stay on the Spirit of Redemption. They have priest on the target and they don't attack anyone until the Spirit of Redemption effect gone.

How it should work: 
Spirit of Redemption should be untargetable, unattackable and have 0 threat. Trash after kill the priest should rush on rest living players.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
> Decription:
ENG: Priest in our party after wipe coudnt use any skills, game gived comunicat that: "You are dead", He coud move, walk and jump, but nothing else.
PL: Prist z naszego party po wipe i ponownym wejściu do dungeona niemogł uzywac skilli, gra rzucała komunikatem "że jest martwy" ale mogl chodzic, biegac i skakac... nic wiecej

**Comment by akrom23** [comment]
@zapsuu Got some screenshots?

**Comment by akrom23** [comment]
Any news?

**Comment by badmannerkid** [comment]
also worth noting that the angel form of Spirit of Redemption can also still be targeted with buffs (Blessing of Protection for example), and can can still take damage from other abilities

https://streamable.com/9k33e

**Comment by akrom23** [comment]
@badmannerkid You mean auras from totems?

**Comment by Wojtyas** [comment]
Fixed & implemented.
