### ISSUE TITLE
Auchenai Vindicator - AC

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#619]
Decription: 
Mob on the CC summon the add.

How it works: 
I used Cyclon on the Vindicator on pull (I could do it with the priest Mind Soothe spell), turn in the bear and charge, Mob still stay in cyclon, but he spawn the ghost.

How it should work: 
Mob cannot do anything in cyclon.

Source (you should point out proofs of your report, please give us some source):

**Comment by Silroth** [comment]
Auchenai Elites summoning the non-elite adds even while CCed is blizzlike behaviour, all actions that put them in combat cause them to summon the non-elite adds, only priest's Mind Control is different.
