### ISSUE TITLE
[Warrior]Charge

### ISSUE THREAD

**Issue by Nadiirr** [SunwellWoW/Sunwell-TBC-Bugtracker#621]
Decription: 
It can be used in combat. 

How it works: 
It was being used in combat during PVP

How it should work: 
Should not be usable in Combat.

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
Works fine for me
![obraz](https://user-images.githubusercontent.com/48881/46695518-13e33300-cc10-11e8-8ca7-a9d207afd7ce.png)

**Comment by Nadiirr** [comment]
My mistake. 

I tested this on the Open Beta.
Works fine on closed beta.
