### ISSUE TITLE
Arcane Concentration - arcane mage talent

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#622]
Decription: 
Gives you a 10% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 100%.

How it works: 
Buff disappears only after reaching the target. During his flight, we can cast a second spell (instant) for free. The first spell is also free.

How it should work: 
After cast any damage spell the buff should instantly disapper.

Source (you should point out proofs of your report, please give us some source):
On this picture we can see that we have the buff from 4 seconds. We cast Frostbolt and we still keep the buff.
![wowscrnshot_100918_100841](https://user-images.githubusercontent.com/43937876/46655775-cbdef480-cbac-11e8-8394-573a942b2c3d.jpg)

On this picture you can see that Clearcasting fades after when Frostbolt reach the target.
![wowscrnshot_100918_101715](https://user-images.githubusercontent.com/43937876/46656247-e5cd0700-cbad-11e8-8a23-d81f7a911ed7.jpg)

On this picture in the logs you can see that Clearcasting fades after using the Cone of Cold (instant), not after Frostbolt.
![wowscrnshot_100918_102113](https://user-images.githubusercontent.com/43937876/46656099-8a9b1480-cbad-11e8-808b-f4cc45765b8a.jpg)

**Comment by arcwizard** [comment]
"The first spell is also free."
This effect appears only in similar situations when the distance to the target is large and in cases if you first use spells such as frost bolts or fire bolts that take time to reach the target, and then an instant-type spell (fire blast, cone of cold).  In cases where the target is close, or if you have instant spells in cooldown, you will not be able to get 2 free spells. And the fact is that if the clearcasting effect would disappear immediately after the spell was cast, it would break the work of the talent Arcane Potency when using Arcane Missiles, i.e. after the first rocket hit target clearcasting would have disappeared along with the effect of Arcane Potency, and next 4 missiles will not receive a bonus from Arсanу Potency (30% crit chance).
And one interesting description, although it is about Arcane Potency, but it is associated with Clearcasting, and it says: "This talent has somewhat peculiar synergy with Arcane Missiles, and a mage who uses Arcane Missiles as part of his rotation can get the +crit benefit **twice** per Clearcast from this talent; once for a cast of Missiles that procs it, and once again for a second spell that consumes the Clearcast." (http://wowwiki.wikia.com/wiki/Arcane_Potency ).  As I understand it, this implies that clearcasting does not disappear immediately after the start of the cast, but lasts until the last rocket hits. However, it is not possible to verify that this fact (from wowwiki) relates to the TBC patch.

**Comment by akrom23** [comment]
I have a question : if the first missile will trigger the Clearcasting, the rest 4 missiles should be affected by extra crit chance?

**Comment by arcwizard** [comment]
I would like to add:
To eliminate the bug described here, while keeping the bonus of arcane potency for the released spell, I think you can go the following way: the clearcasting buff disappears immediately **after the end of the cast**. This will work for the arcane missile if clearcasting buff will disappears after channel end, but not after first missile reach target. For blizzard, this will not affect, because blizzard can not have a critical effect. In this case, it will not be possible to get 2 free spells, and at the same time all arcane missiles will receive a bonus from arcane potency.
