### ISSUE TITLE
Dungeon (combat bug)

### ISSUE THREAD

**Issue by Slakbanan** [SunwellWoW/Sunwell-TBC-Bugtracker#623]
Decription: We are stuck in combat the whole time!

How it works: Stuck in combat!

How it should work: Shouldnt be stuck in combat after combat 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
Please, be more precision. What dungeon? What mobs? Screenshots?

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/609
