### ISSUE TITLE
Warlock: Soulwell

### ISSUE THREAD

**Issue by Slakbanan** [SunwellWoW/Sunwell-TBC-Bugtracker#624]
Decription: Soulwell didnt spawn for my party member!

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by zapsuu** [comment]
I hadn't this bug, everyone in my party saw my Soulwell lub they could take the Healthstone.

But there is another bug.
One person can click all the stones and Soulwell disapper. From 1 Soulwell you should pick up 10 stones.

**Comment by akrom23** [comment]
Cannot reproduce any of these bugs. Still happens?

**Comment by Azathothh** [comment]
Cannot reproduce as well.
