### ISSUE TITLE
[Sethekk Halls Heroic][NPC] Talon King Ikiss

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#626]
Decription: 
Ability [Slow] -  Movement speed reduced by 60%. Time between melee and ranged attacks increased by 60%. Casting time increased by 60% for 8 seconds. Magic debuff; Can be dispelled. Heroic Mode Only.
How it works: 
On heroic mode, the boss does not use this ability.

How it should work: 
As of 2.1.0, he randomly casts Slow on the party, which lasts for around 10 seconds; this can be devastating before the arcane explosion.

Source (you should point out proofs of your report, please give us some source): 
On screenshots, as you can see, we don’t have a party in the class that can dispel Slow, and we stand before both Arcane Explosion without a [Slow] debuff. The boss never used her for the fight.
![wowscrnshot_100918_225433](https://user-images.githubusercontent.com/43764742/46696188-dbdcef80-cc11-11e8-9129-d7f15dc5ae04.jpg)
![wowscrnshot_100918_225447](https://user-images.githubusercontent.com/43764742/46696195-e26b6700-cc11-11e8-9d35-d6014acd63b9.jpg)

http://wowwiki.wikia.com/wiki/Talon_King_Ikiss

P.S. Maybe we were lucky and the boss did not live long to use Slow ...

**Comment by Dootz** [comment]
works fine for me. He's using it around 15-30 seconds after the pull.

**Comment by arcwizard** [comment]
If the boss used a Slow against you, can close that report. Our fight with him lasted ~ 50 seconds,  I didn't look fight duration, however, on the same screenshots it is clear that in 28 seconds  we took half of his health from him and during that time there were 2 Explosion, but not a single Slow.
