### ISSUE TITLE
[Dungeon] The Steamvault

### ISSUE THREAD

**Issue by Wheezytester** [SunwellWoW/Sunwell-TBC-Bugtracker#627]
Trash:
- Coilfang Engineer(17702) not using 'Net'
- Coilfang Engineers should be using a mining animation https://youtu.be/Qgqc-DTCXzo?t=122
- First 4 mob pack with mob GUID12686 is missing a Coilfang Warrior(17802) which should be patrolling https://www.youtube.com/watch?v=aBY9jqWbz8Q
- Second 4 mob pack with mob GUID453 is missing a Coilfang Engineer(17702), Coilfang Warrior(GUID1550) should be patrolling
- Pack with mob GUID12715 is missing a Coilfang Oracle(17803)
- Patrol in the tunnel with mob GUID1723 is missing one Coilfang Warrior(17802)
- Third 4 mob pack with mob GUID1557 is missing a Coilfang Oracle(17803), Coilfang Warrior(GUID1559)
- Coilfang Warrior(GUID12689) is patrolling too far to the right
- Pack before Hydromancer Thespia, with mob GUID2080 isn't patrolling
- Patrol after Tunnel the Coilfang Sorceress(GUID12624) should be walking in the middle of the patrol
- Coilfang Sirens GUID12628 and 12631 should be stationary and not moving around
- Coilfang Slavemasters(GUID12591 and GUID12587) are not patrolling
- Coilfang Slavemaster should yell 'Assist me. Slaves!'https://www.youtube.com/watch?v=L28kubmLJ74
- Coilfang Slavemaster shouldn't chain all Dreghood Slaves, just the ones they're close to
- Dreghood Slaves don't run to the entrance but run back to their original positions before they dissapear
- Pack with mob GUID 12615 should not be outside untill the door is opened(runs out when 2nd Panel is used) https://www.youtube.com/watch?v=aBY9jqWbz8Q

Bosses:
- Hydromancer Thespia spawns two Lightning Cloud https://www.youtube.com/watch?v=CcB3nYErYC4
- Mekgineer Steamrigger spawns Steamrigger Mechanics way too often https://www.youtube.com/watch?v=3WirTKzw7aA&t=104s
- Two Naga Distillers(GUID12655), 2nd on the right/3rd on the left when facing the boss, are missing in the room with Warlord Kalithresh(GUID12613)
- Warlord Kalithresh doesn't link to a Naga Distiller often enough, approximately every 40sec https://www.youtube.com/watch?v=HN5qDWmKwn8

**Comment by Silroth** [comment]
Hydromancer Thespia spawning two Lightning Clouds on heroic is blizzlike.
Mekgineer spawning extra Steamrigger Mechanics every 7 seconds on heroic is blizzlike.

**Comment by Wheezytester** [comment]
> Hydromancer Thespia spawning two Lightning Clouds on heroic is blizzlike.
> Mekgineer spawning extra Steamrigger Mechanics every 7 seconds on heroic is blizzlike.

You got any proof of that Silroth? https://www.youtube.com/watch?v=3WirTKzw7aA&t=173s Clearly shows that the first clouds despawns 1-2 seconds after the 2nd spawns so it is possible that two clouds are up for a second but she doesn't spawn two at the same time. on Mekgineer Steamrigger you can see that adds come approximately every 20 seconds not every 7 seconds.

https://www.youtube.com/watch?v=yv1UwMJdH0U Confirms the first video and shows exactly the same.

**Comment by Silroth** [comment]
@Wheezytester https://wow.gamepedia.com/Hydromancer_Thespia
"In Heroic mode, the elemental's waterbolt volley does approximately 1900 damage. DPS must be quick to kill the adds. The elementals can be stunned, significantly reducing the amount of damage taken before they are killed. You can also counterspell, bash, etc. their volleys. **Also, Thespia casts 2 clouds at once.**"

https://wow.gamepedia.com/Mekgineer_Steamrigger 
"Steamrigger in heroic mode is almost identical to normal mode, **except that an extra gnome appears every 7 seconds or so**"

**Comment by notsofamous** [comment]
I think the problem is that the clouds should overlap slightly _**sometimes**_, atm she always casts 2 at the same time.

https://youtu.be/3WirTKzw7aA?t=44

There's one already up when a second one is cast. Throughout the video there's often just 1 cloud up.

**Comment by Picajzla** [comment]
The problem with Steamrigger is that the gnomes just have way too much hp. They have around 16k,and fully epic geared grp couldn't deal with them. He also spawns them a bit too often it seems as i think he did his yell around 7 times. We ended up kiting the boss from them. Either way i think it's overtuned and a bit too much for a grp that isn't in full epics. Also it seems like the walls just don't exist as you can't really LoS the casters in the whole dungeon , and when you LoS them they go through walls and ground to you. Mob pathing 10/10 . I'm not sure if that's gonna get fixed till release, but the general feel of the dungeon was horrible

**Comment by notsofamous** [comment]
In this video he seems to spawn one each 15-20 seconds (post 2.1)
https://www.youtube.com/watch?v=t98Q2HZb8bE
More often here (pre 2.1):
https://www.youtube.com/watch?v=OdWQYk6ZK-4

13k HP according to this comment
https://www.wowhead.com/npc=17951/steamrigger-mechanic#comments:id=122636

I think the main issue is just their AI, they never stop healing him no matter how much you attack them. They should stop healing for a few seconds whenever they are attacked.

He should be yelling "Tune em' up boys!" when summoning extra Mechanics, currently "I'm bringin' the pain!"

### Quotes

**Aggro**

    I'm bringin' the pain!
    You're in for a world of hurt!
    Eat hot metal, scumbag!
    I'll come over there!

**Summon**
    Tune 'em up good, boys!

**Killing a player**

    You just got served, punk!
    I own you!

**Enrage** (after 5 min on HC)
    Have fun dyin', cupcake!

**Death**
    Mommy.

**Comment by Picajzla** [comment]
Yeah,you're right. When we dmged them they just kept healing. On this vid,once you touch them they stop doing that

**Comment by neheri** [comment]
> The elementals can be stunned, significantly reducing the amount of damage taken before they are killed. You can also counterspell, bash, etc. their volleys.

At the moment you can only stun them. Shield bash, pummel and counterspell don't work.
