### ISSUE TITLE
[Shaman] Totems

### ISSUE THREAD

**Issue by mlodyszulec** [SunwellWoW/Sunwell-TBC-Bugtracker#629]
Decription: 
Bug związany z odnawianiem totemów 

How it works: 
Stawiając ponownie nowy totem w ostatniej sekundzie czasu trwania zeszłego, nowy znika jakby był to ten wcześniejszy (tracąc manę)

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/630
