### ISSUE TITLE
Game freez after dungeon loading

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#633]
Decription: 
like in tittle, game is freezing like 80% of evry try to get in to dungeon.

How it works: 
Make a party with some friends, 
go to the NPC on GM isle - for lunch dungeon, 
see "loading screen" 
loader is reaching 100% and nothing happends.

How it should work: 
After loading is 100% - dungeon shoud start. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
@Bursztynek still happening?

**Comment by Wojtyas** [comment]
Was probably present when beta was hit by first dungeon testings. Probably it got fixed.
