### ISSUE TITLE
Bleeding effect on mecanical targets

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#634]
Decription: 
Players can use bleeding efect on mecanical mobs, For example: Warrior can use Rend (like on screen)

How it works: 
like in desription and screens

How it should work: 
Rend and other bleeding efect players can use only on living targets

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_101018_205851](https://user-images.githubusercontent.com/43553985/46759942-e14d3f00-ccd0-11e8-94c7-532642115624.jpg)

**Comment by akrom23** [comment]
#613
