### ISSUE TITLE
[Hunter] Pet Autocast Abilities

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#639]
Decription: If a hunter switches zones pet autocast abilities bug out and are no longer usable as such, if hunter wants to use them he has to manually activate them. Basicly any time pet is dismissed (zone change, hunter mounting up etc) this happens.

How it works: 
![image](https://user-images.githubusercontent.com/42102450/46815470-465d6f00-cd7b-11e8-93a3-b85d0cb44654.png)

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by doomnyx** [comment]
Works fine now.
