### ISSUE TITLE
Quests Game Objects

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#64]
Decription: 
During my walkabout through world I realized that game objects, normally used during some quests, are able to use w/o those quests which is wrong.
![image](https://user-images.githubusercontent.com/22802214/43781585-886f3438-9a5d-11e8-915f-4f970dce86e9.png)

How it works: I can "use" quest game objects w/o havin adequate quest. By "use" I mean only click on them cuz nothing really happens after that.

How it should work: Quest game objects should be able to use only when player has appropriate quest.

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
powinny byc w takim stanie tylko przy posiadaniu quest'a lub gm on
