### ISSUE TITLE
[Hunter] Pet Charge ability

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#640]
Decription:  Does not add additional attack power for the boar's next attack, buff is present but it acts as if 0 attack power is added.

How it works: 

How it should work: Should add additional attack power for boar's next attack as stated in tooltip.

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
Cannot reproduce:
![obraz](https://user-images.githubusercontent.com/48881/46968474-99a12b80-d0b3-11e8-85a4-db2c085fe0f3.png)
Works fine for me
