### ISSUE TITLE
[Dungeon] Black Morass

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#641]
[Normal]

Trash:

NOTE: All mobs that spawn from portal evade first attack/spell on them also melee damage of trash mobs is very low, since there is little research about their base damage the values from other lvl 68 dungeons should be taken and adjusted to trash mobs in Black Morass. 

- [x] NOTE: Unable to interact with Sa'at NPC at start of dungeon. Medivh isnt channeling his thing and the visual effects are missing.

- [x] Infinite Executioner missing weapon, uses Strike and Cleave but not Hamstring. EDIT: Does not use Cleave or Hamstring.

- [x] Infinite Chronomancer missing weapon, only Frost AI is present who uses Frost Bolt and Frost Nova, there should be Arcane AI who uses Arcane Bolt and Arcane Explosion.

- [x] Rift Lord missing weapon, when engaged uses all abilities.

- [x] Rift Keeper missing weapon, when engaged uses all abilities.

- [x] Infinite Assassin missing weapon, not using Sinister Strike, Deadly Poison, Rupture ticking or Kidney Shot. EDIT: Uses Kidney Shot but not the rest of abilities.

- [x] Infinite Vanquisher does not use any abilities. Should have Fire AI who uses Scorch and Fire Blast and Shadow AI who uses Shadowbolt and Corruption. EDIT: Shadow AI doesnt use Corruption.

Bosses:

- [x] Chrono Lord Deja doesnt use any abilities at all.

- [x] Temporus uses Hasten and Wing Buffet but not Mortal Wound.

- [x] Aeonus uses all abilities however timers need to be checked.

[Heroic]

Trash:

-

-

-

-

Bosses:

-

-

-

**Comment by Riztazz** [comment]
@Afgann issue updated
