### ISSUE TITLE
[Dungeon Heroic]Botanica 

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#643]
Decription: 
Commander Sarannis: 
- Summons Groups of 4 NPC's During the Fight
- (Normal: 1 Time Summons at 55% HP)
- (Heroic: Summons After 30 Seconds / Repeats Summon Every 60 Seconds)

Nethervine Inciter, Nethervine Reaper:
Different NPCs, but both must have a buff [Sunseeker Blessing](https://www.wowhead.com/spell=34173/sunseeker-blessing#used-by-npc).
Nethervine Reaper either must have ability [Pale Death](https://wow.gamepedia.com/Botanica_walkthrough) (Curse: Stamina reduced by 35%)

How it works: 
- Commander Sarannis don't summon group of 4 NPC's.
![wowscrnshot_101218_210704](https://user-images.githubusercontent.com/43764742/46892513-f01d2880-ce6d-11e8-85f0-30376a2cb6bd.jpg)
![wowscrnshot_101218_210721](https://user-images.githubusercontent.com/43764742/46892521-fa3f2700-ce6d-11e8-9bb5-b5b658d6ac68.jpg)
By a temporary stamp, it can be understood that the battle lasted more than 30 seconds, аnd at the same time, as you can see, there are no corpses 4 NPС.
- Nethervine Inciter and Nethervire Reaper not have buff Sunseeker Blessing, also Nethervine Reaper don't use Pale Death(Curse: Stamina reduced by 35%), this can be seen on the window of the tank in the group, there are no curses on it, and in our group there is no one who could be able to decurse.
![wowscrnshot_101218_212511](https://user-images.githubusercontent.com/43764742/46890376-f360e600-ce66-11e8-83b7-397b67162da6.jpg)

How it should work: 
- Commander Sarannis: HEROIC: After 30 Seconds into the fight (and every subsequent minute the encounter might take) she will spawn four adds that need to be dealt with quickly, 1 elite (healer) and 3 non-elites.
- Nethervine Inciter, Nethervire Reaper must have buff Sunseeker Blessing.
P.S. As far as I remember, there should be a kind of event in which the Sunseeker Channeler periodically give buff (refresh) on 4 nearby satyrs (Nethervine Reaper, Nethervine Inciter), this happens before pull. Unfortunately I didn't manage to find a video with this event, however, in wowhead there is information regarding a buff that they must have.

Source (you should point out proofs of your report, please give us some source):
http://wowwiki.wikia.com/wiki/Commander_Sarannis 
https://www.wowhead.com/spell=34173/sunseeker-blessing#used-by-npc

**Comment by Riztazz** [comment]
PTR updated, closing as this is fixed but if anything pops up, please write in this ticket
