### ISSUE TITLE
[DUNGEON] Blood Furnace

### ISSUE THREAD

**Issue by Wheezytester** [SunwellWoW/Sunwell-TBC-Bugtracker#644]
Blood Furnace
- Laughing Skull Enfocer GUID62739 and GUID 62740 not linked
- Laughing Skull Rogue GUID86448, GUID200961 and GUID200960 are in a static spots and don't move around
- Pulling Shadowmoon Warlock GUID 200973 doesn't chain pull other packs if pulled when close to them
- Laughing Skull Legionare (GUID85669) and Laughing Skull Enforcer(GUID200974) arn't linked
- Laughing Skull Legionare (GUID85670) and Laughing Skull Enforcer(GUID200975) arn't linked
- Shadowmoon Summoner(GUID200978) not linked to Shadowmoon Adepts (GUID200977 and GUID200966), Adepts are linked
- Shadowmoon Summoner(GUID85673), Shadowmoon Summoner(GUID85672) and Shadowmoon Adept(GUID200979) all not linked to each other
- Shadowmoon Technicians(17414) should be 'working'
- Laughing Skull Rogue GUID200987 is in a static spot and doesn't move around
- Nascent Fel Orcs(17398) and some Shadowmoon Technicians(GUID85701) are standing in the 'floors/machines'
- Laughing Skull Rogue uses Poison from a distance rather than as a proc on a melee hit
- Hellfire Familiars arn't linked(Entries will come but I bugged the instance here >.<)

- Can't see Magtheridon

The Maker:
- Acid Spray has no animation
- Mind Control is currently hp based, should that be the case? MC'd the Tank very often for us as well

Broggok:
- All cages have 4 mobs, cage 1 and 2 should have 3 mobs and 3 and 4 should have 4 mobs.
- Cages are on a timer(25seconds), should be everytime a cage is cleared
- Should only one Fel Orc Neophyte for group 2-3-4, rest should be Nascent Fel Orcs
- Fel Orc Neophyte still hitting when feared
- Fel Orc Neophyte charges instantly when coming out of the gate, should be more random

Kelidan the Breaker:
- Rage of Magtheridon doesn't work. Debuff caused by stepping into the pools of blue glowing blood in the corners of the room.
- Doesn't yell 'Closer! Come closer... and burn!' when he pulls everyone in
- Chest before Kelidan the Breaker respawns constantly.

General:
- MC bugg, if during MC you get cc'ed with fear/stun(maybe more forms of cc) you can control your character when  the MC ends even though you are still feared
- Healing threat continues during cc
- Healing threat feels very high (can test in open world)

**Comment by Riztazz** [comment]
- Mind Control is currently hp based, should that be the case? MC'd the Tank very often for us as well
Yes, on heroic he casts it based when he reaches certain health levels

- Cages are on a timer(25seconds), should be everytime a cage is cleared
Actually it should be once cage is cleared or 2 mins have passed, i had a typo in my code which i'll fix so they do not come out every 30 seconds

**Comment by notsofamous** [comment]
MC shouldn't be HP based, it's on a timer. In the video below they get 1 MC the entire fight.

https://www.youtube.com/watch?v=BCl8S178ul4&feature=youtu.be&t=434

**Comment by Riztazz** [comment]
- Laughing Skull Rogue uses Poison from a distance rather than as a proc on a melee hit

Checked retail sniffs and he doesn't have proc aura of any kind on himself, so he is supposed to cast it on timer and if target is within spell range (which is 5y)

**Comment by Riztazz** [comment]
Probably not, gonna fix it.

- Acid Spray has no animation
huh? It does have animation on my client and animations are handled by client alone, nothing i can do with it ;p

**Comment by Riztazz** [comment]
Please open seperate tickets for General bugs, keep instance stuff to instance tickets, everything else will be fixed soon (updating open beta in an hour or so)

**Comment by Silroth** [comment]
@notsofamous Mind Control should be hp based (many comments from TBC era mention this aswell), on Normal he does it once when he reaches 50% and on heroic he does it 3 times at 75% at 50% and at 25%, the video you linked shows overgeared people killing him way too fast but even then you can see he casts the first Mind Control when he goes below 75% and while the first Mind Control is present they bring him below 25% and finish him off quickly so the boss has no chance to cast it again.

**Comment by Riztazz** [comment]
open beta updated. Closing this ticket but if anything new pops up, please write in this one

**Comment by Wheezytester** [comment]
Sorry Riztazz, wrote this report in a bit of a hurry but I'll split it into appropriate tickets next time! 

As for the MC, even if the MC is hp based what Silroth is saying is not how it is on the PTR. Atm he can MC multiple targets if you burt him ti 50% before the first MC ends which is clearly not the case in the video
