### ISSUE TITLE
Flame pathes on Nazan

### ISSUE THREAD

**Issue by Dave-Sigismund** [SunwellWoW/Sunwell-TBC-Bugtracker#649]
Decription: currently invisible flame patches when fighting the final boss in Hellfire Ramparts.

How it works: 
Currently, if you get hit with a fireball, you will not see the flame patch, but it will still be there doing damage to you

How it should work: 
You should be able to see it visually to allow you to avoid it more easily.  We ended up just staying in place and moving slightly if he shot a fireball at us.  at the end I could see a flame patch or two, but they disappeared after I moved through them.

Source (you should point out proofs of your report, please give us some source): Currently uploading a video of the fight, once it's done I will link it in this issue.

https://drive.google.com/file/d/1cZulI-5pIxV13-TJAZxvuCJq7KPwrjPn/view?usp=sharing

**Comment by nennx** [comment]
Still not fixed
