### ISSUE TITLE
Hellfire Ramparts: Bugged to Evade

### ISSUE THREAD

**Issue by thewowboy** [SunwellWoW/Sunwell-TBC-Bugtracker#654]
Decription:  
            In hellfire ramparts there are two mobs that patrol back and forth across the bridge that leads to the last boss. In Blizzards TBC, you could put an AoE down from the beginning of the instance, up to that bridge, or other mobs on the second level from the entrance, and they would aggro you, running all the way through the instance pulling everything along with them. 

How it works: 
              When you lay your AoE down the mobs aggro you, then begin evading until they finally reset. 

How it should work: 
               When you put your AoE down, The mobs should aggro you and begin to make their way to you, pulling every other mob in the instance along with them.  

Source (you should point out proofs of your report, please give us some source): 
here are a video displaying how it SHOULD work. You can youtube search "Hellfire ramparts one pull" for more
https://www.youtube.com/watch?v=31d0KCXST3A

**Comment by Riztazz** [comment]
We're not going to implement blizzard vmap issues they had in the past

**Comment by Riztazz** [comment]
As far as chain pulling goes, its an issue but @Kokaina can you open another ticket for it?
