### ISSUE TITLE
Combustion/Presence of Mind - timer bug

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#655]
Decription: 
Combustion (fire talent): When activated, this spell causes each of your Fire damage spell hits to increase your critical strike chance with Fire damage spells by 10%.  This effect lasts until you have caused 3 critical strikes with Fire spells.

Presence of Mind (arcane talent): When activated, your next Mage spell with a casting time less than 10 sec becomes an instant cast spell.

How it works: 
The CD timer start after we use Combustion/PoM. (wrong)
We cannot recast this spell after CD down, because the actual timer begins to count after the third critical spell/used instant spell. We have to wait some time. It could be few second or 3 minutes (if the cd down and we still have a buff). (this is ok)
PL: CD Combustion/PoM zaczyna się naliczać od momentu odpalenia buffa. Powinien się zacząć naliczać od momentu trzeciego trafienia krytycznego/wykorzystania instant. Mechanika spella działa dobrze, bo musimy faktycznie odczekać równo 3minuty po wykorzystaniu buga. Problem jest z timerem. Do momentu wykorzystania buffa timer powinien być zatrzymany.

How it should work: 
The cd timer should start after we spend last third critical spell/used instant spell.
Timer powinien zacząć się naliczać po wykorzystaniu buffa.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@zapsuu Sources? I've never heard about it.
