### ISSUE TITLE
[Spell][Priest] Power word:Shield

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#659]
Decription: 
 It creates a protective shield around a friendly target which absorbs a set amount of damage. Power Word: Shield also gives the target the Weakened Soul debuff for 15 seconds, which prevents the target from being shielded.

How it works: 
While target under power word:Shield but without debuff (weakened soul), can't refresh this by clicking the spell button (work only with /cancelaura Power word:Shield),and spell button is gray at this time, and turns white only after the buff has fallen.  It’s like the debuff(weakened soul) is gone, but its effect still lasts.  
On this screen there is a moment with a buff(Power word:Shield) and a debuff(weakened soul), the spell button is gray, and there is no possibility to refresh the buff.
![screen1](https://user-images.githubusercontent.com/43764742/47185860-fceac200-d32e-11e8-9cc1-fe31b43452eb.jpg)
Here, the debuff(weakened soul) has already disappeared, the buff(Power word:Shield) is still hanging, but the spell button is still gray, and there is no way to refresh the buff.
![screen2](https://user-images.githubusercontent.com/43764742/47185876-083ded80-d32f-11e8-96cb-88c0edae182f.jpg)
And the moment when there is no buff or debuff, and only at this moment is the use of a spell available.
![screen3](https://user-images.githubusercontent.com/43764742/47185996-68349400-d32f-11e8-9a0e-6517966bb0a1.jpg)

How it should work: 
Right after debuff gone, spell button must be white and spell able to refresh.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Power_Word:_Shield
https://youtu.be/nJ_17BwWieQ?t=20 - The video, although from the classics, which shows that the spell button (button 3) becomes available immediately after the debuff is lost.

**Comment by Wojtyas** [comment]
Fixed & implemented.
