### ISSUE TITLE
Rogue : Poisons damages killing people in duel.

### ISSUE THREAD

**Issue by Jeansapin** [SunwellWoW/Sunwell-TBC-Bugtracker#662]
Decription: Nothing specific, except that the poisons damages are killing people in duel, and it's a bit annoying.

How it works: If an Instant/Woun/Anesthetic poison procs when someone is really low in life, it kills him in duel.

How it should work: It should be avoided by the one that lost the duel, as every damages.

Source (you should point out proofs of your report, please give us some source): 
Can't really find a source about it sorry, but it's obvious here.

**Comment by Jeansapin** [comment]
After few tests, it's nothing about rogues mechanics, it's when 2 sources of damages are striking at the same time ...

**Comment by akrom23** [comment]
Tried several times and cannot reproduce. Some video/screenshots?

**Comment by Jeansapin** [comment]
@akrom23 Try to apply wound poisonon on your 2 weapons,  /duel another player and hit him.
Sometimes (and it could happen with every class), when for example you're finishing a player with Hemorrage, the wound poison can proc. This little damage can kill the guy you just beat (because in duel you're losing when you're at 1 hp). So the poison hits anyway, and kill your friend.

I'm saying that it could happen with every class if theses classes got a kind of proc, doing extra damages on an attack. Just as the rogue poison do.

**Comment by akrom23** [comment]
I'll try. Thx.
