### ISSUE TITLE
Rogue : Combat Spec : Sword Spec

### ISSUE THREAD

**Issue by Jeansapin** [SunwellWoW/Sunwell-TBC-Bugtracker#664]
Decription: The talent Sword Specialization isnt working correctly here.

How it works: Once you got it as a rogue, it can proc on every damages you're doing. On Rupture's ; Poison's ; Trinkets like Romulo's Poison Vial's damages ; Eviscerate ; etc ...
And it's not triggering the mainhand autoattack, it's doing the same damages the spell is doing ... So imagine it procs on an Envenom at 2k5, it can be an 5k damages instantly ...
BTW : Windfury is doing exactly the same thing ... as you can see on this ticket : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/588

How it should work: It should proc on every melee (even if your offhand isnt a sword), and every spell attacking with melee attack, triggering the "Sword Specialization" that is making an extra melee attack with your mainhand (meaning an extra auto attack with the mainhand).

And from this Rogue Guide* : 
"There are two caveats also worth noting. First, your main hand specialization affects all attacks made by your main hand, including special attacks and finishers (other than Shiv and Deadly Throw). Second, the extra attacks granted by Sword Specialization are always performed using your main hand weapon, regardless of which weapon caused the proc. As a result, if you combine Sword Specialization with another weapon specialization and equip a sword in your off hand with the other specialized weapon type in your main hand, your off hand attacks will proc extra main hand attacks which will receive the benefit of your second specialization. By way of example, if you take both fist and sword specializations, and equip a main hand fist with an off hand sword, your extra attacks will gain the 5% increased critical strike chance from your fist specialization."

Source (you should point out proofs of your report, please give us some source): 
The Rogue Guide : https://legacy-wow.com/tbc-rogue-guide/  in "Weapon Specialization and Dual Wield" part

**Comment by akrom23** [comment]
Deadly Throw is treated as a ranged attack.

> How it works: Once you got it as a rogue, it can proc on every damages you're doing. On Rupture's ; Poison's ; Trinkets like Romulo's Poison Vial's damages ; Eviscerate ; etc ...

Evi, Rupture - these are melee spells? Or am I wrong?

**Comment by Wojtyas** [comment]
No proofs, closing. Feel free to reopen when needed.
