### ISSUE TITLE
Stealth Detection

### ISSUE THREAD

**Issue by Jeansapin** [SunwellWoW/Sunwell-TBC-Bugtracker#665]
Decription : "Stealth is an ability that allows players or mobs to sneak around undetected. Most notably a rogue's ability, it is also available (as Prowl) to druids when using their Cat Form, as well as hunter cat pets. Unlike invisibility, anybody has a chance to detect an enemy in stealth mode. The chance of detection increases as you get closer, but also depends on the viewing angle (stand right in front of an enemy and you can guarantee they'll see you), the relative levels, and any perception or subtlety modifiers. "

How it works : After alooooooot of tests, I think that I can easily say that on the server, the effective stealth is working. I mean that every items or talents that can increase the effective stealth works as intended and make you more difficult to spot.
In the other hand, the stealth detection is totally broken. The more you have, the more YOU will get spotted.
I tried it with the item : The Night Watchman ; the sub rogue talent : Heigntened Senses ; the racial human spell : Perception.
Perception is the best way to test it, all rogues can see you from so far when you're under it !

How it should work : The stealth detection should allows you to have a better stealth detection, not make you easier to get detected.

Source (you should point out proofs of your report, please give us some source) : 
http://wowwiki.wikia.com/wiki/Stealth_(mechanic)

**Comment by Wojtyas** [comment]
@Jeansapin can you retest it? Lukaasm did some work here.

**Comment by akrom23** [comment]
Looks good to me.

**Comment by akrom23** [comment]
No response. Closed.

**Comment by Bugadin** [comment]
I forgot to answer because, suddenly, it didn't happen again but it used to happen at those days.
