### ISSUE TITLE
[Shaman] Greater Fire and Greater Earth Elementals

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#666]
Decription: Low damage, low health and some arent using their abilities.

How it works: At lvl 70 Greater Fire Elemental has ~3k health, Fire Shield hits for 81 per tick, Fire Blast for 274, melee for ~260, at lvl 70 Greater Earth Elemental has ~9k health, melee for 41.

How it should work: Should have higher health for both of them, Greater Earth Elemental should have very high armor and deal much higher melee damage and use some kind of AOE Taunt ability every 6 seconds, Greater Fire Elemental should deal Fire damage instead of Physical for melee, Fire Shield and Fire Blast abilities should deal higher damage, also Greater Fire Elemental should have a Fire Nova type ability that deals ~700 damage at lvl 70.

When they are summoned the level up animation and sound is seen and heard (this should be hidden).

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/index.php?title=Fire_Elemental_Totem&oldid=1563567
https://wow.gamepedia.com/index.php?title=Earth_Elemental_Totem&oldid=1553615

**Comment by notsofamous** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/259
