### ISSUE TITLE
[Hellfire Citadel + Coilfang Reservoir] Part 1

### ISSUE THREAD

**Issue by walckir** [SunwellWoW/Sunwell-TBC-Bugtracker#67]
Hello team, this is Mr Dj with a new post for the upcoming TBC Sunwell.

I will be posting the issue in small series that encompass Dungeon bugs.
Similarly to what I did for Angrathar all Armor types represented by different classes will be used to properly keep a track on the rough Damage that it should be taken.

---Damage Issues were found with several mobs, however, as the list is long I have decided to make a separate Topic on that---

***Dungeons Normal Mode***

For the purpose of Testing a tank with 55.48% PD (Physical Damage) reduction was used alongside Cloth wearer and a Leather wearer. It SHOULD BE NOTED THAT ALL TESTING IS DONE USING PRE-BIS TBC Gear.

***_Hellfire Ramparts_***

1. ***Bosses***

--Watchkeeper Gargolmar--
Surge ability was casted all the time for 3 Dungeon runs kicking players to INIFINITY. After a random Crash that no longer happened. DO recommend being checked.

Surge KNOCKBACK radius/Range--> ***https://www.youtube.com/watch?v=ZucKMUb7s_A***
The knockback on the TEST realm is way too high i literary flew away fel times after the crash.

Watcher's--> Renew Mana usage incorrect. It was around 5 mana for a renew.
Healing abilities did NOT work. They started casting but the heal never healed the boss. However, RENEW did affect boss. Only great/heal abilities seem to NOT affect the boss. Same issue was observed in other instances with Heal casting mobs such as COILFANG ORACLE.

Watchers--> Kept spamming Shadow Word:Pain untill they ran out of mana.

--Omor the Unscarred--
Incorrect cast time on "Summon Hound" ability. Issue can be related to Watchers spamming Shadow Pain. He casts Trecherous Aura and immediatelly after he does SUMMON HOUND. For the period of  about 40 seconds I believe I counted about 15 or so Hounds.

Trecherous Aura-->RESISTED EVERY TIME as DOT.. I was level 70, got myself down to 60 to check if i am just too lucky. Outcome was the same, everytime the dot was about to tick --> RESISTED///RESSISTED.

_Shadow Whip--> Has to be tested,as it cannot affect HTTs (Highest Threat Targets)._

--Vazruden and Nazaan--
 Nazan SHOULD only come down once Vazruden is dead/at 30% or Nazan is a bit below 40% health.
He comes down anyway. First time he came after 20 seconds of fight,NOTE that Vazruden was at 80% health. Second time he came after about the same time and Vazruden was this time at 100%.

Support Links: ***https://www.youtube.com/watch?v=ZucKMUb7s_A***
***http://www.tentonhammer.com/guides/the-hellfire-ramparts-guide***

2. ***Patrols/Mobs***

Hollow Scryer--> Missing Fear spell. MIssing FEL infused.

Support links ***:http://wowwiki.wikia.com/wiki/Omor_the_Unscarred***
***http://www.tentonhammer.com/guides/the-hellfire-ramparts-guide***
***https://db.excalibur.ws/?npc=17478#abilities***

Shattered Hand Warhound--> Furious Howl doesnt affect nearby ALLIES. Effect also does not LAST its spell duration (10seconds) instead it is present for roughly 3 seconds on the Target Caster.

Support Links:  ***https://db.excalibur.ws/?npc=17280#abilities***
*** http://wowwiki.wikia.com/wiki/Shattered_Hand_Warhound***

***_Blood Furnace_***

1. ***Bosses***

--The Maker--
First run The Maker did not cast mind control ability. After the same sudden CRASH that someone did by doing a quest or whatever, he turnt out to have Mind control. The mind Control however was for 2 minutes instead of 10 seconds.

Support Links:: ***https://www.wowdb.com/npcs/17381-the-maker#related:casts***

*It had the same issue with SURGE on Watchekeeper. I strongly recommend that this is checked so players dont be hit by it infinite times untill you reach the Universe.*

*Upon Killing DOOR did not OPEN.*

--Kel Dan The Breaker--

Shadowmoon Channeler (the 6 or so mobs around him).
After casting Mark of the Shadow that increases Shadow damage taken, the mark gets automatically removed when the first SHADOW bolt hits you.

2. ***Patrols/Mobs***

Shadowmoon Technician DONT throw MINES on the ground.

Support Links: https://www.wowdb.com/npcs/17414-shadowmoon-technician#related:casts

***_Slave Pens_***

1. ***Bosses***

--Quagmirran--

Naturalist Bite--> After being freed by killing mobs around him and clicking on the cage. He does NOT go out. Additionally, upon clicking on him he does NOT provide buff for Nature resistance.

***_Underbog_***

1. ***Bosses***
 

--Hungarfen--
Mushrooms should leave a poison CLOUD when they explode ,instead they just explode. Damage is correct though.

Supportive Links::  http://www.tentonhammer.com/guides/underbog-guide
http://wowwiki.wikia.com/wiki/Hungarfen

--Swamplord Musel Ek--

Aimed Shot damage INCORRECT-->Was hitting for 15-17 damage.

Supportive links::  https://db.excalibur.ws/?npc=17826#abilities
https://www.youtube.com/watch?v=CV65NpBIv-s

On this one you can see how he ALSO moves out a bit taking his range and casts it. He always does Aimed shot when he has frozen people btw.
https://www.youtube.com/watch?v=fVF2rGQwGhE

Freeze trap doesnt work. It should act as a massive aoe that traps everyone.

Supportive Link :: https://db.excalibur.ws/?spell=31946 

http://www.tentonhammer.com/guides/underbog-guide That should also be used for MULTI shot guide.

--The Black Stalker--

*Static Charge damage incorrect---> Hits for 250, should hit for 750.

Support Links:: http://wowwiki.wikia.com/wiki/The_Black_Stalker
https://www.youtube.com/watch?v=eBuf0HYbBmM
https://db.excalibur.ws/?spell=31715

Levitate doesnt work as well.

Support links:: https://db.excalibur.ws/?npc=17882#controlled-abilities
https://www.wowdb.com/npcs/17882-the-black-stalker#related:casts

NOTE: Heroic hasnt been tested to check the Spore strider spawn mechanic.

***_COILFANG DUNGEON PATROLS/MOBS_***

--Coilfang Observer--
Throw Dynamite incorrect damage (70-90). Also Magma Splash area effect from it is applied TO caster mob instead of PLAYER.

Support Link: https://db.excalibur.ws/?npc=17938#abilities

--Coilfang Defender--
SPell reflect shield seems to be very spontaneous.

10 Times the shield was tested for enemy attacks being reflected. It seemed that up to 3-4 times he reflected the VERY first spell casted after he casts his shield. The rest times the shield SELECTIVELY reflected spells.

--Coilfang Soothslayer--
Mind control doesnt work.

Support LInk :: https://db.excalibur.ws/?npc=17960#abilities

--Coilfang Siren--
No fear ability.

Support link: https://db.excalibur.ws/?npc=17801#abilities

--Coilfang Sorceress--
Frost nova ability incorrect. Both SpellTracker and Combat logged were observed upon the mob Casting Frost nova on me. Frost nova DID do damage ,however, the freeze/root effect did not happen.

--Coilfang Oracle--
It seems all healing mobs cannot CAST HEAVY Direct heals to their targets.
The mob kept casting HEAL while looking at me ,but the spell never affected any friendly mob.

_That will be all within this post,If i have missed anything i shall get back to it and fill it in.
More to come soon. Keep up the good work.!_

**Comment by Kokaina** [comment]
Report cut into pieces.
