### ISSUE TITLE
[Dungeon Heroic Mechanar][NPC] Nethermancer Sepethrea 

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#670]
Decription: 
Nethermancer Sepethrea 
When the fight is initiated, she summons two Raging Flames (Fire Elementals) that are immune to all forms of crowd control. **### They move slowly**, and will chase a randomly selected target, leaving damaging trails of fire behind them.
For Heroic:
Three Raging Flames spawn, rather than two. As of 2.2.0, the elementals act like the Normal mode elementals, except that they **run at 80% speed**, not 50%. They will switch targets quickly if kiting is attempted. 

How it works: 
I don't have the opportunity to measure their speed accurately, but they are clearly moving faster than 100%, because they fast and easily catch up players. I'm not sure that the screenshots will help, but still:
![wowscrnshot_102118_122246](https://user-images.githubusercontent.com/43764742/47265320-903a1800-d526-11e8-8599-a2ab5258f73f.jpg)
![wowscrnshot_102118_122250](https://user-images.githubusercontent.com/43764742/47265322-98925300-d526-11e8-98f5-439bee5e4a00.jpg)
![wowscrnshot_102118_122306](https://user-images.githubusercontent.com/43764742/47265323-9d570700-d526-11e8-83a2-265b072d5f99.jpg)
![wowscrnshot_102118_122308](https://user-images.githubusercontent.com/43764742/47265324-a2b45180-d526-11e8-9bd5-d1ef2d0e946d.jpg)

How it should work: 
Raging Flames spawn must have 80% speed on heroic,

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Nethermancer_Sepethrea

**Comment by Wojtyas** [comment]
Her adds are still moving extremely fast.

**Comment by zapsuu** [comment]
We checked it today. These flames move with 150% speed or so. Tank hasn't any chance to run with 2 adds with frostbrand debuff. Boss is almost unkillable.
