### ISSUE TITLE
[Warlock][Pet Fellhunter ability] Paranoia

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#671]
Decription: 
Paranoia:
Greatly increases the stealth detection of all party members within 30 yds of Felhunter. 
Very useful for trying to find Rogues, Druids, or any class that can play Night Elves, since Night Elves all have the ability to become hidden with Shadowmeld. There is no casting time, cooldown, or mana cost; Paranoia is a permanent buff to anyone in the party who stays within 30 yards of the Felhunter.

How it works: 
Does not affect the detection of opponents in stealth.

Maximum detection distance without paranoia.
![1](https://user-images.githubusercontent.com/43764742/47271164-2f3a3080-d576-11e8-9f09-e31523e7d8d2.jpg)

And on this screen, the distance has changed by 1 step (this can be seen if you look at the steps of the stairs), but the warlock is already with paranoia,  
![2](https://user-images.githubusercontent.com/43764742/47271231-0bc3b580-d577-11e8-8be5-d3dfbbfa7a37.jpg)

How it should work: 
Paranoia must give +30 stealth detection. And accordingly, the detection distance should be greater than without paranoia.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Stealth_(mechanic)#Stealth_tips
https://eu.battle.net/forums/en/wow/topic/3194020017 here wrote about +30 stealth detection. And it's for TBC, as proof: here http://wowwiki.wikia.com/wiki/Paranoia in Patch changes wrote "...the voidwalker now grants Paranoia while under the effects of Consume Shadows."

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/665
