### ISSUE TITLE
Wird mob behavior - movment while in combat

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#673]
Decription: 
mobs act realy wird while combat. 
check this video -> https://youtu.be/e5K-hRg8t2E film is notpublic. 

How it works: 
like in decription.

How it should work: 
If player is running mob should chase him. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Fixed & implemented.
