### ISSUE TITLE
Mobs in Bramble Blade Ravine

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#674]
Decription: 
Mobs (hunter type) should use the "net" and be bind to his pets (boar). at this moment you have simple diferent mobs that you can "tank n spank"

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 

-- On screen, i can pull only "pet"

![wowscrnshot_102218_222737](https://user-images.githubusercontent.com/43553985/47318671-f02ade80-d64c-11e8-9be8-43d800edb997.jpg)

**Comment by Azathothh** [comment]
could you provide any source showing that Bristleback Battleboars should be considered as pets of Bristleback Quilboars? I've tried to find anything and couldn't - seen only screenshots where they've been standing alone, like 2 sepparate NPCs, not like master + pet

**Comment by Bursztynek** [comment]
ok, i cant find any of YT film from that area, and well... im not sure if its proper behavior. I just remeber on Ares WoW this mobs works like i said... but now, true, im not sure its correct.

You can close this ticket.
