### ISSUE TITLE
Last white attack is not showned

### ISSUE THREAD

**Issue by Akounama** [SunwellWoW/Sunwell-TBC-Bugtracker#676]
Decription: 
The mortal white attack on the mob are not showned on screen

How it works: 
If the mob is killed by an auto attack then there is no numbers shown at screen

How it should work: 
The damages should be showned on screen even if it is a mortal strike

Source (you should point out proofs of your report, please give us some source): 

My mortal strike was an auto attack
![wowscrnshot_102218_225547](https://user-images.githubusercontent.com/44381091/47319100-1ac96700-d64e-11e8-8438-1db3cf5852b1.jpg)

My mortal strike was heroic strike
![wowscrnshot_102218_225606](https://user-images.githubusercontent.com/44381091/47319122-2c127380-d64e-11e8-972a-2b2e222ec0da.jpg)

**Comment by akrom23** [comment]
I see in combat log that the last strike is displayed after slain - it's a bug too, right?
