### ISSUE TITLE
[Quest Item] Wendigo Mane

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#677]
Decription: 
[Quest:The Grizzled Den](http://wowwiki.wikia.com/wiki/Quest:The_Grizzled_Den)
Gather 8 Wendigo Manes and bring them to Pilot Stonegear.
[Wendigo Mane](https://www.wowhead.com/item=2671/wendigo-mane)
Dropped by: 
[Wendigo](https://www.wowhead.com/npc=1135/wendigo) - 58% chance
[Young Wendigo](https://www.wowhead.com/npc=1134/young-wendigo) - 58% chance

How it works: 
Wendigo Mane drop with 100% chance from Wendigo and Young Wendigo.
![wowscrnshot_102318_004835](https://user-images.githubusercontent.com/43764742/47321431-105e9b80-d655-11e8-9f7b-88026a1b70fd.jpg)

How it should work: 
Must have 58% drop chance.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Quest:The_Grizzled_Den
https://www.wowhead.com/item=2671/wendigo-mane

**Comment by Silroth** [comment]
Drop rate for those should be 80% not 58% on both vanilla and TBC and there is no issue if its 100% considering private servers have higher population than retail vanilla/TBC servers. You should report if mobs during quests are behaving properly/using abilities.

**Comment by arcwizard** [comment]
Ok, then can close.
