### ISSUE TITLE
Mobs get stuck in textures

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#681]
How it works: 
Some mobs when run away in fear get stuck in textures.
![11](https://user-images.githubusercontent.com/43764742/47323748-5ddf0680-d65d-11e8-8bda-b34a74df2773.jpg)
![12](https://user-images.githubusercontent.com/43764742/47323754-633c5100-d65d-11e8-814b-cf0291715a5a.jpg)
![13](https://user-images.githubusercontent.com/43764742/47323760-68010500-d65d-11e8-9f07-fc60545d5179.jpg)

And in the end, this mob didn't return to its place, and this mob cannot be attacked due to the texture of the tree.
![14](https://user-images.githubusercontent.com/43764742/47323798-95e64980-d65d-11e8-9a55-2dc5c83476bc.jpg)

How it should work: 
They must bypass the textures, and after leaving combat, return to their original place and stand or continue to patrol.

**Comment by arcwizard** [comment]
Some NPC are stuck even where it sometimes seems that they have no place to get stuck.
![wowscrnshot_102718_130347](https://user-images.githubusercontent.com/43764742/47602554-e6a0ce00-d9e0-11e8-929a-b8d331d05f18.jpg)
This NPС could not attack me, and at the same time didn't try to get closer, which gave me the opportunity to shoot him without receiving any damage.

**Comment by Wojtyas** [comment]
Stucking in textures fixed. Movement in water fixed.
