### ISSUE TITLE
Weapon Skill ranking is way to slow

### ISSUE THREAD

**Issue by Frankenberryberry** [SunwellWoW/Sunwell-TBC-Bugtracker#682]
Decription: 
The formula for ranking up your weapon skill is not correct.

How it works: 
On this server even gaining a single point in weapon skill takes an unusual amount of swings.

How it should work: 
Usually a character stays within 5 points of the maximum amount and the chance of getting a skill point becomes almost 100% if you are way behind (for instance leveling from 1 -> 250 out of 300 takes almost no time).

Source (you should point out proofs of your report, please give us some source): 
All other servers works differently.

**Comment by notsofamous** [comment]
Duplicate: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/87
