### ISSUE TITLE
 Can't use flametounge weapon on "low level weapons"

### ISSUE THREAD

**Issue by Frankenberryberry** [SunwellWoW/Sunwell-TBC-Bugtracker#683]
Decription: 
If you cast flametounge weapon while having a low level item equipped it doesn't work.

How it works: 
You can't cast flametounge weapon on low level weapons so when you get it you can't use it unless you've been lucky enough to find a green higher level weapon.

How it should work: 
You should be able to cast it on any weapon regardless of quality since it's a spell.

Source (you should point out proofs of your report, please give us some source):

**Comment by Jhn3712** [comment]
This also happends with Rogues Poisons on "lower level weapons"

**Comment by akrom23** [comment]
Fixed.
