### ISSUE TITLE
Mob summoned pets don't attack

### ISSUE THREAD

**Issue by Frankenberryberry** [SunwellWoW/Sunwell-TBC-Bugtracker#686]
Decription: 
In Skull Rock in Durotar the summoned demons don't attack you if you have attack from range.

How it works: 
They don't attack you.

How it should work: 
They should aggro and attack you.

Source (you should point out proofs of your report, please give us some source):

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/686
