### ISSUE TITLE
[Warlock] Curse of Doom

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#69]
Decription:  0 proc chance, tested on 40 mobs. Doomguard summoned from it has broken stats and wrong abilities.

How it works: After the damage from Curse of Doom kills a target there should be a chance to spawn a Doomguard. Right now the chance is 0.
I manually summoned the Doomguard to see his spells and stats and they are broken. His autoattack damage is very low, his armor is 0 and his stats are 0 aswell.

How it should work: 10% chance to spawn a Doomguard (11859), Doomguard scales with Warlock level (at lvl 60 its 60 Doomguard, at lvl 65 its 65 Doomguard etc) and should have the following abilities:

1. Rain of Fire - This should be a channeled ability with no cooldown, right now he has Rain of Fire ability that has a big cast time and a 5 minute cooldown. He should use spell ID 16005 

2. War Stomp - in video it is shown that War Stomp should be auto-castable

3. Cripple - Spell works fine.

4. Dispel Magic - For some reason he has Rend instead of Dispel Magic, he should use spell ID 15090.

Source (you should point out proofs of your report, please give us some source): 
http://www.tentonhammer.com/guides/warlock-guide-pet-information 10% Chance for Curse of Doom to proc.

https://www.youtube.com/watch?v=3tYPzOyUPm4&t= (How the spell works and you can he deals around 500 damage to that mob with decent armor reduction so you can calculate what his base damage should be)

**Comment by akrom23** [comment]
Summon effect corrected, spells also.
Stats are unknown, so it's hard to get them proper.
This demon is treated as a common mob, so his stats are not inherited from owner.
Melee damage seems to be okay. I checked on the same mobs as this guy from video - did the same amount.

**Comment by Silroth** [comment]
Retested and still has 0% proc chance, tested on about 30 mobs. I manually summoned the Doomguard to test his abilities after fix, War Stomp, Dispel Magic and Cripple work fine but every time he uses Rain of Fire he keeps recasting it over and over again before the first tick can damage the enemy, if i try to move him he still keeps recasting Rain of Fire on himself.

**Comment by Silroth** [comment]
Retested and proc chance is 0% currently.

**Comment by akrom23** [comment]
It works fine.

**Comment by Silroth** [comment]
After recent update works properly now, however when Doomguard is summoned the level up animation and sound is seen and heard (this should be hidden) and stats on summoned Doomguard are a bit weaker than they should be (he has around 4k hp and hits for 200 on lvl 64 mobs in Nagrand)
