### ISSUE TITLE
quest=9685 - Redeeming the dead

### ISSUE THREAD

**Issue by Novat93** [SunwellWoW/Sunwell-TBC-Bugtracker#691]
Decription:  It is currently impossible to use the quest item ''filled shimmering vessel'' (item=24184) on ''Blood knight stillblade'' (npc=17768) in order to complete the quest Redeeming the dead (quest=9685).

Thus it is impossible for Blood Elf paladins to learn the Redemption spell (spell=7328)

How it works: Attempting to use the item on the corpse, results in the error message. ''You have no target''

How it should work: 
You should be able to target the corpse, then resurrect the dead NPC using the quest provided item.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/36EDLVx

**Comment by Mvtsvraev** [comment]
Same issue with Human Paladin quest(The Tome of Divinity) in Elwynn Forest. Corpse can not be targeted.
