### ISSUE TITLE
Wrong place to spirit spown after death.

### ISSUE THREAD

**Issue by Bursztynek** [SunwellWoW/Sunwell-TBC-Bugtracker#696]
Decription: 
Mobs killd me during some Quest in Mulgore, (Sharing the Land - cave part) after i press "Releas spirit" button i was spown instantly near my body. I shoud be spowned in Graveyard.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102318_105032](https://user-images.githubusercontent.com/43553985/47348482-da033980-d6b1-11e8-8d02-6e91977dbc94.jpg)

**Comment by Bursztynek** [comment]
Film -> https://youtu.be/yzo8ko0Z51o

**Comment by Azathothh** [comment]
source of this problem is reported in #699
