### ISSUE TITLE
Wrong debuff-timer on resurerection sickness (Lvl 11-19)

### ISSUE THREAD

**Issue by Jhn3712** [SunwellWoW/Sunwell-TBC-Bugtracker#697]
Decription: 
When you ress on low level (11,12 tested so far) the debuff show that you get the full 10 minutes on your resurerection sickness. However you only get the minutes your supposed to get, so it goes away before the full 10 min, so only a minor displaying bug. (Double checked with friend of mine so it wasnt my UI only)
https://gyazo.com/fdacee2b78cf8a47f24220649f08175d

How it works: 
The debuff shows 10min for level 11, level 12 and so on.

How it should work: 
The debuff shows 1min for level 11, 2 min for 12 and so on, up to level 20 then the full 10min.

Source (you should point out proofs of your report, please give us some source): 
http://wow.allakhazam.com/wiki/resurrection_sickness_(wow)
http://wowwiki.wikia.com/wiki/Resurrection_Sickness

**Comment by Nadiirr** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/697
Duplicate. 

Thank you though <3
