### ISSUE TITLE
[Quest] Rescue the survivors

### ISSUE THREAD

**Issue by ryredan** [SunwellWoW/Sunwell-TBC-Bugtracker#698]
Description: 
The Quest itself works fine but the Draenei Survivors are not behaving properly.

How it works: 
The Draenei Survivors run in a "spleeping" animation

How it should work: 
They should get up and move with their running animation

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102318_065408](https://user-images.githubusercontent.com/20247441/47353708-491d6580-d693-11e8-9b32-c6ebd78472e0.jpg)

**Comment by Jeansapin** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/690
