### ISSUE TITLE
"Unknown" location in Palemane Rock (Mulgore)

### ISSUE THREAD

**Issue by Azathothh** [SunwellWoW/Sunwell-TBC-Bugtracker#699]
Decription: 
![obraz](https://user-images.githubusercontent.com/37483678/47349108-28fd9e80-d6b3-11e8-984d-b5c53efd05a7.png)
it happens in Mulgore > Palemane Rock (inside cave)

How it works: when we're going through Palemane Rock cave, there are "unnamed cells" (not sure if that's how this problem should be described). 
Whole area is in grid 27,32  , i've noticed that it turn's to unknown when cell Y >12 (it goes up to 15).
Cell X inside this cave goes from 6 to 11.
So for example: [7,13] , [10,14], [8,15]  would all have Zone: [0] - <unknown>  Area: [0] - <unknown>

How it should work: i don't think it's possible to find source for it, but it would be logic if for every cell inside this cave zone and area were :
Zone: [215] - Mulgore  
Area: [818] - Palemane Rock

**Comment by Azathothh** [comment]
#696 is caused by this bug - if i'll die in cell 7,13 then bug from #696 happens , if i'll die in 7,12 - it's moving me to graveyard properly

**Comment by akrom23** [comment]
#738
