### ISSUE TITLE
[Druid][Spell] Feral charge issue

### ISSUE THREAD

**Issue by Unfairy** [SunwellWoW/Sunwell-TBC-Bugtracker#7]
Decription: 
Druid's feral talents ability: Feral charge not working properly

How it works: 
Feral charge just immobilize your target

How it should work: 
Druid in bear form charging at enemy, getting melee range and immobilize the target.

Source (you should point out proofs of your report, please give us some source): 
In game attempt 01.08.2018, Tester character: Fairy.

**Comment by Kokaina** [comment]
Fixed and implemented.
