### ISSUE TITLE
[Quest] [Warlock] Suppression

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#70]
Decription: Cannot loot Imprisoned Doomguard item/object after finishing the channel.

How it works: After finishing the channel the item/object containing Imprisoned Doomguard is not lootable.

How it should work: After finishing the channel the item/object should be lootable.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next ptr update
