### ISSUE TITLE
[ZONE] [Elwynn Forest] 

### ISSUE THREAD

**Issue by Mvtsvraev** [SunwellWoW/Sunwell-TBC-Bugtracker#702]
- [ ]  1. NPC - Lee Brown
http://db.darkwizard.pl/?npc=1651
How it works: https://imgur.com/a/eu2Q7fZ
How it should work: He should stand on on the pier
- [x]  2. NPC - Stonetusk Boar(and each other boars in Elwynn Forest)
http://db.darkwizard.pl/?spell=6268#used-by-npc:0+2+1
How it works: Boar used Rushing Charge and gain 2 attacks with bonus damage
Hot it should work: Boar should get bonus damage only on first attack
- [x]  3. NPC - Murloc Lurker
http://db.darkwizard.pl/?npc=732
Mob hit with backstab in face 
https://imgur.com/a/pATUB9h
- [x]  4. .NPC - Hogger
http://db.darkwizard.pl/?npc=448
Completely broken the mechanics of motion
- [x]  5. NPC - Antonio Perelli
http://db.darkwizard.pl/?npc=844
In one part his way he patrols under textures

**Comment by dodgykebaab** [comment]
Can confirm Lee Brown NPC Issue
