### ISSUE TITLE
Earthbind totem

### ISSUE THREAD

**Issue by danelmore** [SunwellWoW/Sunwell-TBC-Bugtracker#705]
Decription: When ever you drop earthbind it gets instant aggro and is killed

How it works: when you drop earthbind it gets instand aggro and is killed every time

How it should work: does not pull aggro from npc

Source (you should point out proofs of your report, please give us some source):

**Comment by notsofamous** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/552

That issue states that you should get into combat when dropping earthbind totem. I disagree, but it would need some research with retail proof.

**Comment by danelmore** [comment]
It's not the issue of getting into combat.  It's the issue of mobs instantly swapping from you to the earthbind totem, which should not happen.  It doesn't taunt like stoneclaw, but mobs are instant swapping and killing it.
