### ISSUE TITLE
 Range for damage from things like "Braziers, Burning Embers"

### ISSUE THREAD

**Issue by dranzergt** [SunwellWoW/Sunwell-TBC-Bugtracker#708]
Decription:  Range for damage from things like "Braziers"

How it works: All things like "Braziers" and stuff like that which deals a static amount of 10 fire damage every 1-2 seconds if the Player stands in range. The thing here ist that the range is to high. so you get 10 damage every 1-2 seconds even if you stand 5 yards away of this Braziers.

How it should work: Should do damage to players if they stand right near the Brazier

Source (you should point out proofs of your report, please give us some source):

**Comment by dranzergt** [comment]
[url=https://abload.de/image.php?img=wowscrnshot_102318_174weo9.jpg][img]https://abload.de/thumb/wowscrnshot_102318_174weo9.jpg[/img][/url]

**Comment by dranzergt** [comment]
https://abload.de/img/wowscrnshot_102318_174weo9.jpg

**Comment by Eternae1** [comment]
Agreed, even campfires / bonfires around the open world have an over-extended range.

**Comment by akrom23** [comment]
#479
