### ISSUE TITLE
Respawn place after dying in Jasperlode Mine

### ISSUE THREAD

**Issue by grzesznikps** [SunwellWoW/Sunwell-TBC-Bugtracker#727]
Simply.

I died at kobolds in Jasperlode mine and got spawned in.. Southshore in Hillsbrad Foothills, instead of nearest graveyard.

![1](https://user-images.githubusercontent.com/44415525/47388875-9e995700-d713-11e8-97b7-425e7c860d25.png)

**Comment by akrom23** [comment]
#738.
