### ISSUE TITLE
[Quest] Powering-our-defenses

### ISSUE THREAD

**Issue by Reykjavikshore** [SunwellWoW/Sunwell-TBC-Bugtracker#729]
Decription: 

https://www.wowhead.com/quest=8490/powering-our-defenses

How it works: 

Crystal is unfriendly and we can attack it. After event quest isnt complete

![wowscrnshot_102318_202348](https://user-images.githubusercontent.com/44321901/47389340-08116980-d704-11e8-8bcf-fbd02a992065.jpg)

![wowscrnshot_102318_202514](https://user-images.githubusercontent.com/44321901/47389346-0cd61d80-d704-11e8-940d-b7efb2b7cce4.jpg)

How it should work: Crystal should be friendly nonattackable. After event if crystal survive it should be complete 

Source (you should point out proofs of your report, please give us some source): 
I do the same quest on ats netherwing and its works there.

**Comment by qtong** [comment]
Problem still persists

**Comment by Reykjavikshore** [comment]
http://db.hellfire-tbc.com/?npc=17086
didnt attack the crystal and u can just stay and wait for finish

not work properly anyway
