### ISSUE TITLE
Ogr'rila Chain

### ISSUE THREAD

**Issue by sleepyx** [SunwellWoW/Sunwell-TBC-Bugtracker#73]
Decription: 
Maggoc does Not Mortal wound, Boulder,Daze, or rock Rumble but he did do double breath which he should not. Maggoc also seems to have an extremely high stealth detection even with full stealth and improved stealth he was able to see me from max aggro range
Vim'gol the Vile does not do unholy growth or summon demon
Slaag only Frenzy's one time 
How it works: 
Maggoc just auto attacks and randomly does double breath(a dragon hawk ability)
Vim'gol the Vile only auto attacks
Slaag only uses frenzy one time at 20% health

How it should work: 
Maggoc should use " Mortal wound,Boulder,Daze,Rock Rumble.
Vim'gol the Vile should summon a demon and use Unholy growth which is interruptible. He also should yell "You dare summon me" upon summon
Slaag only used Frenzy one time during the entire fight which doesn't seem right since its his only spell 

Source (you should point out proofs of your report, please give us some source): 
Check wowhead or any tbc wowhead and it shows they have this ability as

**Comment by Wojtyas** [comment]
Will be available in 2.1 patch. AI will be added to those creatures.
