### ISSUE TITLE
Weapon skill bug. Cant level mace skill after i changed beginner sword to quest mace.

### ISSUE THREAD

**Issue by networm555** [SunwellWoW/Sunwell-TBC-Bugtracker#735]
Decription: Cant level mace skill after i changed beginner sword to quest mace. Probably global problem. People complaining in tbc channel in discord.

How it works:  No skill level increase.

How it should work: Should increase lvlv skill for every suscessfull swing.
 How to reproduce : Start a warrior for example level to lvl 6 then change weapon for a white mace.and try to lvl it.

**Comment by akrom23** [comment]
#682.
