### ISSUE TITLE
Into the Soulgrinder

### ISSUE THREAD

**Issue by sleepyx** [SunwellWoW/Sunwell-TBC-Bugtracker#74]
Decription: 
Quest for the Ogri'la chain

How it works: 
Click Vim'gol's Grimoire to summon Skulloc Soulgrinder. Fight summons adds for over 6 minutes then crashes the sever.

How it should work: 
Fight should summon adds for 3 minutes then at 3:15 Skulloc becomes attack able and able to be killed

Source (you should point out proofs of your report, please give us some source): 
Youtube,Wowhead

**Comment by Dootz** [comment]
will be fixed with next ptr update, thanks for report.
