### ISSUE TITLE
Quest: Free At Last

### ISSUE THREAD

**Issue by Jhn3712** [SunwellWoW/Sunwell-TBC-Bugtracker#747]
Decription:  The NPC fails to path over the bridges and dropped away to somewhere on second to last bridge.

How it works:  NPC Lakota Windsong is the escort quest in Thousand Needles, and she has some issues pathing over the bridges. On second to last bridge before the end of the quest, she disappeared and the quest did not fail or was able to complete. 

How it should work: Path on the bridges and not under, also making it to the end over the last 2 bridges.

Source (you should point out proofs of your report, please give us some source): 
Normal pathing behavior to complete quest. Did not print screen where she disappeared.

/reejh

**Comment by sunwelldude** [comment]
![fat2](https://user-images.githubusercontent.com/44537968/47611658-662aad80-da72-11e8-9a5e-58566a606bf6.jpg)
