### ISSUE TITLE
Open world Chests.

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#750]
Decription: Find a open world chest and open it at max range. Sometimes works sometimes not.

How it works: When I opened a chest in Stonetalon Mountains at max range to avoid aggro, the chest opened but I couldnt loot it. It stayed bugged out for about 5-10minutes and after then relogging several times it went back to an unopened chest. Could also loot it properly by not standing at max range.

How it should work: If it's possible to start the "open chest process" it should be possible to loot the chest as well withot it bugging.

Source (you should point out proofs of your report, please give us some source): 
Sadly forgot to take a screenshot of this but shouldnt be hard to replicate.

**Comment by Eternae1** [comment]
Also if you open a chest and move it will despawn whether or not there is loot still inside (also if you are in a group and the loot hasnt rolled yet it wont finish the roll if chest despawns)

**Comment by badmannerkid** [comment]
yeah, saw this as well

**Comment by akrom23** [comment]
@Feydil Need an exact chest in this zone or coordinates.
