### ISSUE TITLE
Inviting someone to party when attacking a quest mob.

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#753]
Decription: I was killing Besseleth a spider quest mob for the quest "Arachnophobia" and to complete it you have to loot "Besseleth's Fang". In the middle of the fight another player came by so I invited him/her mid fight without reseting the mob. We killed it but no one of us could loot it. (Sadly missing screenshot of this was sure I took one) Also didnt use Web spell.

How it works: Start killing a quest mob and inv someone mid fight without reseting, the quest mob should not be lootable. Does not cast any spells.

How it should work: Even if you inv someone mid fight a quest mob should still be lootable, specialy by the player which tagged it first. Should use Web spell.

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?npc=11921#drop:0+12+1

**Comment by Eternae1** [comment]
This happens with most mobs, if you are fighting something and get invited to a group or invite someone else, you wont be able to loot that mob (because he was tagged to the "groupless party" instead of the player themselves regardless of what group they are in.
