### ISSUE TITLE
[Rogue Spell] - Distract

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#756]
Decription: Distract is a spell used to force enemies to look towards a certain direction or just make them turn around.

How it works: The spell it self is working fine, but mobs which turns around only does it "visually". On the folowing screenshots I used distract to make a mob turn around but then I can't use Garrote from its shown back. I have to move in front of it since it has only turned "visually".
![wowscrnshot_102418_190430](https://user-images.githubusercontent.com/44415275/47448396-33598e80-d7c0-11e8-9207-f71b8ad32cb9.jpg)
![wowscrnshot_102418_190435](https://user-images.githubusercontent.com/44415275/47448404-36ed1580-d7c0-11e8-9b24-2c02507b0eb5.jpg)
![wowscrnshot_102418_190447](https://user-images.githubusercontent.com/44415275/47448409-3a809c80-d7c0-11e8-8536-7752f58d6cbe.jpg)
![wowscrnshot_102418_190453](https://user-images.githubusercontent.com/44415275/47448412-3ce2f680-d7c0-11e8-9dd1-a26482638793.jpg)

How it should work: After using Distract to force a mob to turn around, you should be able to use "from behind" spells according to it's new position.

Source (you should point out proofs of your report, please give us some source):

**Comment by EdgarAllenPwnd** [comment]
Having the same issue with [Rogue Spell]: [Gouge]
Gouge is supposed to incapacitate the enemy where it stands. 
Occasionally, the enemy will also "visually" turn around. So "from behind" attacks wont work despite the visual change in direction.

**Comment by Wojtyas** [comment]
Fixed & implemented (only SSC realm for now).
