### ISSUE TITLE
[NPC] Unseen

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#757]
Decription: 
[Unseen](http://wowwiki.wikia.com/wiki/Unseen)
Unseen are invisible mobs that haunt Raven Hill in Duskwood. They are neutral unless attacked, but since they are invisible to the naked eye most players are totally unaware of their existence. Warlocks who can cast Detect Invisibility, or other players using various means to detect invisible mobs, can see them. In addition, they do not become visible when provoked.

Since they are invisible and neutral, they are generally not a threat to players. However, to any class with an AoE spell they can be extremely dangerous as they are level 49-51 and Duskwood is an 18-30 zone, so any players who encounter them are very likely to be a much lower level.

Flares and tracking cannot detect Unseen. The Warlock's detect invisibility spell allows anyone to see them, but Mages who are invisible can also see them

How it works: 
NPC Unseen is not invisible and aggressive.
![wowscrnshot_102418_201401](https://user-images.githubusercontent.com/43764742/47448727-0659ab80-d7c1-11e8-8486-d77a7cea097c.jpg)
![wowscrnshot_102418_201545](https://user-images.githubusercontent.com/43764742/47448804-46b92980-d7c1-11e8-9043-46ba151e10e6.jpg)

How it should work: 
NPC Unseen should be invisible and neutral. Otherwise, players wouldn't be able to pass the quest to a nearby NPC, since the NPS Unseen would attack them from a great distance.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Unseen
https://www.youtube.com/watch?v=gczV9BIiCIs

**Comment by Eternae1** [comment]
These "Unseen" mobs are also at Manor Mistmantle just to the North of Darkshire. Visible and aggressive lol.
