### ISSUE TITLE
[Normal] Blood Furnace Bosses

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#77]
1. The Maker--
First run The Maker did not cast mind control ability. After the same sudden CRASH that someone did by doing a quest or whatever, he turnt out to have Mind control. The mind Control however was for 2 minutes instead of 10 seconds.

Support Links:: https://www.wowdb.com/npcs/17381-the-maker#related:casts

It had the same issue with SURGE on Watchekeeper. I strongly recommend that this is checked so players dont be hit by it infinite times untill you reach the Universe.

Upon Killing DOOR did not OPEN.

2. Kel Dan The Breaker--

Shadowmoon Channeler (the 6 or so mobs around him).
After casting Mark of the Shadow that increases Shadow damage taken, the mark gets automatically removed when the first SHADOW bolt hits you.

**Comment by Silroth** [comment]
Both Normal and Heroic

- Keli'dan the Breaker is not using his Banish + Fire Nova combo at all, instead he is using some fire based spell that does a slight knock in the air.
NOTE: After defeating him and trying to leave instance through the sewer shortcut behind him the door is closed (door should open after his death)

**Comment by Riztazz** [comment]
Please test after PTR update
