### ISSUE TITLE
Minimap tracker not working for some things

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#771]
Description: If you change your mini-map tracker to Reagents or Profession Trainers they don't show up as a dot on the mini-map no matter how close you are to them. I tried with Repair vendors and they showed up just fine. ( I tested this in The Exodar )

How it works: Mini-map tracker not showing dots on mini-map of selected things to track when in range.

How it should work: Mini-map should show npcs / units that are being tracked such as Reagent vendors or Profession Trainers when in range.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
It's not general bug. These NPCs are missing some npc flags.
We need tests more vendors/NPCs in cities.
