### ISSUE TITLE
[Exploration] From Duskwood to Trisfal

### ISSUE THREAD

**Issue by Mvtsvraev** [SunwellWoW/Sunwell-TBC-Bugtracker#774]
Decription: 
![image](https://user-images.githubusercontent.com/43555021/47463856-2359a300-d7f0-11e8-88fc-bf462fc08c1c.png)

How it works: 
When you enter Darkshire Town Hall your character is displayed in Trisfal Glades

**Comment by akrom23** [comment]
#738.
