### ISSUE TITLE
[Quest/Event] Stitches (Bride of the Embalmer)

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#775]
Decription: 
[Bride of the Embalmer](http://wowwiki.wikia.com/wiki/Bride_of_the_Embalmer_quest_chain_(Old))

How it works: 
After done quest Translation to Ello there was no event with [Stitches](http://db.hellfire-tbc.com/?npc=412#abilities).

How it should work: 
Stitches spawned at Abercrombie's shack upon completion of the quest Translation to Ello and made his way to Darkshire, attacking any players along his path. Only one Stitches was active at a time though, so if another player had just turned the quest in he would not spawn again. Players were not required to assist in the battle against Stitches.

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?npc=412#abilities
https://www.youtube.com/watch?v=rS0rjcQ6YMc

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/437
