### ISSUE TITLE
[Combat] Entering combat with pet + character in def stance after right clicking on a mob that is faaaar away

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#778]
Decription: 
Imp in defensive stance, entering combat from faaaaaaaaaaaaar away 

How it works: 
My Imp is in defensive stance. After i right click on a mob, even if its 80 yards away, my imp starts heading in range to cast fireball. Thats normall. But the mob, which i right clicked on, i also IMMEDIATELY coming after the click to my imp. I may add that its a Neutral kobold from Northshire. 

How it should work: 
After right clicking on a mob, while my demon is in defensive stance, my imp should go towards his target and start casting fireball. After fireball hits , the mob should enter combat with me. Especially a neutral one. Unless the mob is some lvls higher than my imp, then he will come after entering combat range. But a Neutral mob? ONLY after attacking him. Not right clicking

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102518_092828](https://user-images.githubusercontent.com/43579401/47483409-77d54080-d839-11e8-890d-51670b4a1da6.jpg)
![wowscrnshot_102518_092846](https://user-images.githubusercontent.com/43579401/47483420-7c99f480-d839-11e8-9449-3fe3b18c7a73.jpg)

EDIT: Same with unfriendly mobs in packs 
![wowscrnshot_102518_094109](https://user-images.githubusercontent.com/43579401/47483728-3d1fd800-d83a-11e8-9002-0447808b0910.jpg)

**Comment by doomnyx** [comment]
Works fine now, tested with felhunter in open world.
