### ISSUE TITLE
[Rogue Spell] Sap on stealthed mobs

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#791]
Decription: Use Rogue spell Sap on a mob which is stealthed.

How it works: Everything is working fine, the Sap goes off and correct duration but the mob stays stealthed.

How it should work: When a mob in Stealth get the Sap debuff they should be revealed from Stealth.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102518_150051](https://user-images.githubusercontent.com/44415275/47502045-29d73180-d867-11e8-8146-0c6ec83e87bb.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented.
