### ISSUE TITLE
[NPC] -  Marshal Isildor

### ISSUE THREAD

**Issue by Nadiirr** [SunwellWoW/Sunwell-TBC-Bugtracker#8]
Decription:  
NPC moves weird when interacted with and it's hard to accept quests from him.
Marshal Isildor
GUID 68895
To reproduce you can get an alliance character to try to take a quest from him. 

How it should work: 
NPC should stop when player interacts with him. 

Source (you should point out proofs of your report, please give us some source): 
Not needed.

**Comment by Azathothh** [comment]
general error, related to more cases

**Comment by akrom23** [comment]
#16.
