### ISSUE TITLE
[Normal] Underbog Bosses

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#80]
1. Hungarfen--
Mushrooms should leave a poison CLOUD when they explode ,instead they just explode. Damage is correct though.

Supportive Links:: http://www.tentonhammer.com/guides/underbog-guide
http://wowwiki.wikia.com/wiki/Hungarfen

2. Swamplord Musel Ek--

Aimed Shot damage INCORRECT-->Was hitting for 15-17 damage.

Supportive links:: https://db.excalibur.ws/?npc=17826#abilities
https://www.youtube.com/watch?v=CV65NpBIv-s

On this one you can see how he ALSO moves out a bit taking his range and casts it. He always does Aimed shot when he has frozen people btw.
https://www.youtube.com/watch?v=fVF2rGQwGhE

Freeze trap doesnt work. It should act as a massive aoe that traps everyone.

Supportive Link :: https://db.excalibur.ws/?spell=31946

http://www.tentonhammer.com/guides/underbog-guide That should also be used for MULTI shot guide.

3. The Black Stalker--

*Static Charge damage incorrect---> Hits for 250, should hit for 750.

Support Links:: http://wowwiki.wikia.com/wiki/The_Black_Stalker
https://www.youtube.com/watch?v=eBuf0HYbBmM
https://db.excalibur.ws/?spell=31715

Levitate doesnt work as well.

Support links:: https://db.excalibur.ws/?npc=17882#controlled-abilities
https://www.wowdb.com/npcs/17882-the-black-stalker#related:casts

**Comment by Silroth** [comment]
- Swamplord Musel'ek Aimed Shot ability right now deals 5-25 damage and he never casts Hunter's Mark, Multishot, Deterrence or Raptor Strike, Claw (Bear NPC) is missing.

- The Black Stalker isnt casting Levitate.

**Comment by Riztazz** [comment]
Resolved. Please re-test after realm update
