### ISSUE TITLE
[Zone] Cave at top of STV puts you in Felwood.

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#800]
Description: The cave in northern STV called "The Stockpile" puts you in Felwood channels and shows you in Felwood.

How it works: Game thinks person is in Felwood when inside the cave.

How it should work: Cave is inside STV, not Felwood. Should display that you are in STV.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102518_091337](https://user-images.githubusercontent.com/42300476/47511108-c208f280-d836-11e8-951c-4d00dd92e27e.jpg)

**Comment by akrom23** [comment]
#738
