### ISSUE TITLE
[Quest] Corrosion Prevention

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#814]
Decription: There are no visual effect active and nothing happends when quest item is used.

How it works: It's not working at all.

How it should work: By standing close to the Power Core's (The one next to the quest giver should always be on and the other ones turn on and off every 30sec~) in the area you should get Energized And then a channeling beam should happen after using the quest item on an ooze. 

Source (you should point out proofs of your report, please give us some source): 
This is the Power Core which always should be working:
![wowscrnshot_102518_222309](https://user-images.githubusercontent.com/44415275/47528156-b81dd880-d8a4-11e8-9825-0a0ae5d63fe3.jpg)

This is what happends when I use the quest item next to it:
![wowscrnshot_102518_222313](https://user-images.githubusercontent.com/44415275/47528185-ccfa6c00-d8a4-11e8-88a5-f12ea86cb935.jpg)

I know it shows I have 1/10 of this quest completed but I never understood why it did work once, have tested several times afterwards and nothing.

To show what it looks like when working.
https://www.youtube.com/watch?v=D5OylI4CdQY

**Comment by Reflekz** [comment]
I also have 1/10 , and the only thing i can possibly imagine , is I killed the Rare Spawn (The Rot).
Maybe The Rot gives 1 credit ? Which should not be the case.
