### ISSUE TITLE
[NPC] Kolkar Drudge (Kolkar Crag - Durotar)

### ISSUE THREAD

**Issue by Yolosapien** [SunwellWoW/Sunwell-TBC-Bugtracker#816]
Decription: 
When mob Kolkar Drudge in Kolkar Crag - Durotar is pulled it will only walk towards you and not run.

How it works: 
When mob is pulled it will approach you in walking pace.

How it should work: 
When mob is pulled it should approach you in running pace.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102518_221146](https://user-images.githubusercontent.com/44451212/47528727-362eaf00-d8a6-11e8-8fef-354cd3e72843.jpg)

**Comment by Wojtyas** [comment]
I think it's kind of core issue and happens only in specific circumstances. Moved to recently created topic - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1919
