### ISSUE TITLE
[Zone] Auberdine Inn puts you in Ghostlands

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#821]
Description: When you enter the Inn at Auberdine you are moved to the Ghostlands chat channels and are shown in Ghostlands in the Who list.

How it works: Auberdine Inn is considered part of Ghostlands zone.

How it should work: Auberdine Inn is at Darkshore. Should display as Darkshore (and not change since you arent leaving Darkshore when entering / leaving the Inn)

Source (you should point out proofs of your report, please give us some source):

**Comment by Eternae1** [comment]
Also the docks at Auberdine are considered part of Azuremyst Isle (even though they are in Darkshore)

**Comment by akrom23** [comment]
#738.
