### ISSUE TITLE
[NPC] Syndicate Highwayman

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#823]
Decription: 
[Syndicate Highwayman](http://db.hellfire-tbc.com/?npc=2586)
Ability;
[Backstab](http://db.hellfire-tbc.com/?spell=37685)

How it works: 
NPC use Backstab from any side.
![wowscrnshot_102618_010741](https://user-images.githubusercontent.com/43764742/47533438-01295900-d8b4-11e8-90e7-ab512bbf4279.jpg)
![wowscrnshot_102618_010806](https://user-images.githubusercontent.com/43764742/47533440-01295900-d8b4-11e8-9f61-7909caa49c42.jpg)

How it should work: 
Must use only from behide.

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?npc=2586
http://wowwiki.wikia.com/wiki/Syndicate_Highwayman

**Comment by arcwizard** [comment]
Sorry it's late, but better late than never. The melee damage of this NPC is also incorrect (see the screenshot above). He hits with a normal strike with a minimum value of 55 damage, but should have hit no less: 92-17% (my armor) = 76. Accordingly, the damage of Backstab should be higher.
Stats Syndicate Highwayman for TBC:
Level: 30 - 31
Class: Normal
Faction: Syndicate
Health: 1,050 - 1,107
Damage: 92 - 108
Armor: 1,217

**Comment by Dootz** [comment]
:) stats are not yet live on beta, but backstab update is. Thank you for report.
