### ISSUE TITLE
Arcane torrent / Mana tap

### ISSUE THREAD

**Issue by Novat93** [SunwellWoW/Sunwell-TBC-Bugtracker#827]
Decription:  Mana tap incorrectly grants the blood elf resources, while Arcane Torrent on occasion does not expend it's saved up mana tap stacks or grant resources. Mana tap is also usable on certain mobs without a mana pool.

How it works: 
Mana Tap : Grants resources as well as depleting target enemy mana
Mana tap 2 : Is usable on certain mobs, despite the mobs not having a mana pool
Arcane Torrent : Will on occasion not expend the mana tap charges, or grant resources

How it should work: 
Mana tap : Should only deplete target mana
Mana tap 2 : Should exclusively be usable on targets with a mana pool, the amount of mana remaining is not relevant
Arcane Torrent : Should always expend any and all mana tap stacks on the blood elf, and grant resources based on the amount of mana tap stacks, if any.

Source (you should point out proofs of your report, please give us some source): 
Arcane Torrent : 
![arcane torrent](https://user-images.githubusercontent.com/36829235/47547710-ddd3cd80-d8f6-11e8-8afb-ed95e4c726db.PNG)

As you can see, arcane torrent is on cool down. Yet i have 3 stacks of mana tap on my character. This should not be possible, as it would take 90 seconds at the very least to gain 3 stacks of mana tap after using arcane torrent.

![mana tap mana](https://user-images.githubusercontent.com/36829235/47547827-4753dc00-d8f7-11e8-8aa7-b81126bddd30.PNG)

As you can see in the combat log. Mana tap grants the blood elf mana. In addition, contrary to what the combat log implies. The blood elf is not granted 55 mana twice.

This has the potential of giving blood elves a substantial advantage. The mana gained from mana taping seems to be equal to the amount of mana gained from using arcane torrent with 3 stacks of mana tap. Thus the total amount of mana (optimally) gained from mana tap and arcane torrent, is 5 times greater than how it should be.

I will add a screenshot at a later time where i mana tap a mob without a mana pool.

**Comment by notsofamous** [comment]
Duplicate
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/318
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/317

**Comment by Novat93** [comment]
The mana tap giving mana is duplicate. Arcane torrent not functioning, and the fact that you can use mana tap on mobs without a mana pool is not duplicate.

![torrent 2](https://user-images.githubusercontent.com/36829235/47572766-0cc06280-d93c-11e8-82a9-7ab93fc26963.PNG)
Mana tap used on a mob without a mana pool. npc=16364

![torrent 3](https://user-images.githubusercontent.com/36829235/47572813-23ff5000-d93c-11e8-88fc-aeb3cf23d1f1.PNG)
