### ISSUE TITLE
[Quest] Challenge Overlord Mok'Morokk

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#828]
Decription: The elite chased me very far away from aggro point. Also after he killed me, he follows my ghost so as soon as I respawn he attacks me and kills me again. Vanish doesnt work to reset combat as well.

How it works: You accept the quest, the previous neutral/friendly npc becomes attackable which is correct. But he will follow me anywhere, doesnt matter how far away you travel, even as a ghost he will keep follow me.

How it should work: I'm not 100% sure but I'm pretty sure if you travel a certain distance away from him he should reset and return to original location, because if someone like deathruns this mob could be kited to lets say Orgrimmar. Also obviously shouldnt chase dead players.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102618_114528](https://user-images.githubusercontent.com/44415275/47560838-d245ce00-d919-11e8-93ae-b4a9b004e256.jpg)
![wowscrnshot_102618_114742](https://user-images.githubusercontent.com/44415275/47560852-da057280-d919-11e8-9388-a60fcff01bec.jpg)
![wowscrnshot_102618_114822](https://user-images.githubusercontent.com/44415275/47560856-dc67cc80-d919-11e8-9f45-8d6871210c46.jpg)
![wowscrnshot_102618_115511](https://user-images.githubusercontent.com/44415275/47560859-deca2680-d919-11e8-9b5c-929c3b799c9f.jpg)

**Comment by Stondis** [comment]
Happened to me too. https://imgur.com/a/lFXXuIi

**Comment by FrauHolle86** [comment]
same issue 22.11.
