### ISSUE TITLE
Loot in general

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#829]
Decription: After entering Tanaris I managed to obtain 2 epics in the matter of 15-20min which feels too good to be true. Also felt like I came across too many blues during my lvling from 25-35.

How it works: blues/epics dropping at a very high rate.

How it should work: Blues and epics should not be this "common" to obtain. Would make certain twink items for players who want to enjoy the 10-19 or potentialy even 20-29/30-39 pvp brackets worth nothing. And those who come by the rare items wouldnt gain anything from it. From a gold perspective.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102618_125956](https://user-images.githubusercontent.com/44415275/47562542-16879d00-d91f-11e8-8e9e-102fb9c87a1d.jpg)
![wowscrnshot_102618_130000](https://user-images.githubusercontent.com/44415275/47562544-18e9f700-d91f-11e8-9d37-49366eb4f584.jpg)

**Comment by twoPlusThree** [comment]
How this is closed ? drop rates are ridiculous to the point I sell some epic BOE at merchant cause they sell for nothing on the auction house
