### ISSUE TITLE
Ragefire Chasm

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#83]
Issues I encountered on RFC dungeon:

- [x] 1. Molten Elemental: melee damage has to be slightly increased.
- [x] 2. Molten Elemental: should be immune to nature school damage.
- [x] 3. Ragefire Shaman: missing spell - healing touch. I suppose AI needed here for healing touch (to cast on himself and other Ragefire Shamans/Troggs when <40% hp).
- [x] 4. Ragefire Shaman: after running away in fear (on low hp) creature is standing in place w/o any interaction (no casts, no movement).
- [x] 5. Weird behaviour on Ragefire Trogg + Ragefire Shaman pull. Some of them started to attack each other instead of helping. When 1 Trogg was pulled other creatures started to attack this Trogg as well.Range pull (to help) looks to be to big as well.
- [x] 6. Another weird pull behaviour. After Searing Blade Warlok was pulled, almost half of zone pulled with him (boss included) and started to attack each other.
- [x] 7. Lava in Ragefire Chasm should damage players.
- [x] 8. Searing Blade Cultits shouldn't refresh existing CoA debuff on target but cast it on random player w/o this debuff (I mean HIS debuff, not other Cultists).
- [x] 9. Not every Searing Blade Warlock has Voidwalker as his minion. They should be already spawned and walk as formation with they masters.
- [x] 10. Spawned Voidwalker Minion should have same level as his master. For now Warlocks have 15-16 level while minons have level 47.
- [x] 11. Taragaman the Hungerer's Uppercut spell cooldown is to high? **More info needed.**

**Comment by KimmoKM** [comment]
Regarding the point 11, while I don't know about that specific mob, as a general rule summons didn't despawn on retail. Very few, if any, did: ccshiro/cc-buglist#1058 

For example, voidwalkers summoned by Burning Blade warlocks in Durotar seen in [Joana's guide](https://www.youtube.com/watch?v=YcEqpVfrE7U&feature=youtu.be&t=1h13m45s) don't despawn.

**Comment by Kokaina** [comment]
True though.

**Comment by Kokaina** [comment]
- [ ] Taragaman the Hungerer and Bazzalan shouldn't have random movements.
- [ ] Ragefire Shaman should cast Lightning Bolts more often.
