### ISSUE TITLE
quest=8490 - Powering our Defenses

### ISSUE THREAD

**Issue by Novat93** [SunwellWoW/Sunwell-TBC-Bugtracker#836]
Decription: 
The quest will not complete

How it works: 
The quest functions as it is intended. Spawning 6 enemy shades, in 2 waves, which correctly aggro the crystal you spawn via the provided quest item. However, protecting the crystal for the full minute will not complete the quest.

How it should work: 
Defending the crystal for 1 minute should complete the quest.

Source (you should point out proofs of your report, please give us some source): 
![runestone 1](https://user-images.githubusercontent.com/36829235/47572507-6d02d480-d93b-11e8-8409-b08bddd9d5ba.PNG)

The chat log states that the runestone has been succesfully re-activated.

![runestone 2](https://user-images.githubusercontent.com/36829235/47572532-7c821d80-d93b-11e8-903a-6bba269f250a.PNG)

The quest log however, disagrees.

**Comment by qtong** [comment]
Problem still persists
