### ISSUE TITLE
[Quest] Washed ashore

### ISSUE THREAD

**Issue by Raivokaapio** [SunwellWoW/Sunwell-TBC-Bugtracker#838]
Decription: At darshore quest [washed ashore] can't loot beached sea creature. Player can start the loot, but player can't get anything from it. 

How it works: When player starts to loot beached sea creature it just stops without any loot. After the loot Sea creature don't vanish like it should. Now when player start looting it again, it says "the target is already used".
![wowscrnshot_102618_173641](https://user-images.githubusercontent.com/44444594/47573397-df78b200-d945-11e8-9bd1-104444e5720d.jpg)

How it should work: Player loot the beached sea creature, get the quest bones of it. Then this sea creature should vanish and u can complete the quest at quest giver.

Source (you should point out proofs of your report, please give us some source): http://db.darkwizard.pl/?quest=3524

**Comment by amarathTESTER** [comment]
Is this the same issue with admiral orders quest basically atm cannot loot quest giving items from static objects? (Don't want to keep reporting the same bug.)
