### ISSUE TITLE
[Hunter] Pet Following Bugged on Thunder Bluff Elevator

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#843]
Decription: 
pets going "offline" when going on a TB elevator, cannot call revive or dismiss the pet after it bugs on elevator

How it works: 
Hard casting the "dismiss pet" is the only thing that will remedy this issue. then you must re-call the pet after dismissing and it will reappear at your current location

How it should work: 
pet should be able to come on elevator with you without bugging.

Source (you should point out proofs of your report, please give us some source): 
basic pet following

**Comment by badmannerkid** [comment]
Replication:

https://gyazo.com/a1d89acc1727ed6aae517da0e7e1cc0c

https://gyazo.com/050569a610dd34a645899d7440a85dbd

https://gyazo.com/ac3863ff41167278ca9334bef37f2b0d

Target not in line of sight/already control a summoned creature:

https://gyazo.com/1715cdd3c7f16a60608413ebf4085cee

**Comment by lukaasm** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/401
