### ISSUE TITLE
[Hunter] Combat starts upon commanding pet to attack, regardless of range of aggro radius

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#845]
Decription: 
Regardless of how far away your pet is from the target, commanding your pet to attack the target will immediately put you in combat

How it works: 
be 30+ yds away from target, Target Enemy, Command pet to Attack, mob will immediately aggro from 30+ yds away regardless of how physically close your pet is to the mob aggro range

https://gyazo.com/355f25ee5d136d75bc1f250a22c93ce0

https://gyazo.com/fc836dd16d4702bf29404df651c02d2f

How it should work: 
Pet should only aggro the target once it is within the target's aggro radius

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Pet

https://wow.gamepedia.com/Aggro_radius

**Comment by kharbick** [comment]
same thing happens with warlock pets, including imp beginning a cast when commanded with /petattack

**Comment by doomnyx** [comment]
Retesting:
Combat won't start until pet running to mob will aggro/attack it.

Can be closed.
