### ISSUE TITLE
Wailing Caverns

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#85]
### **DONE:**

- [x] 1. Evolving Ectoplasm - talked with Dootz already.
- [x] 2. Druid of the Fang: looks like he doesn't cast Healing Touch spell at all. 
- [x] 3. Druid of the Fang: missing spell Druid's Slumber?
- [x] 4. Lady Anacondra: I couldn't see her Healing Touch spell as well. Maybe its common bug on this instance since Healing Touch (23381) should be used by several creatures here and noone does. Better to check it.
- [x] 5. Lady Anacondra: missing quote on pull: "None can stand against the serpent lords!"
- [x] 6. Lady Anacondra: missing spell Druid's Slumber? **Info needed.
- [x] 7. Deviate Viper guid 27378 falls through ground while on his path. ~~ [Dootz Edit - core issue]
- [x] 8. Lord Cobrahn should move and melee attack players while on Cobrahn Serpent Form.
- [x] 9. Deviate Lasher: guids 18683, 18684, 18686 fall through ground.~~ [Dootz Edit - core issue]
- [x] 10. Deviate Faerie Dragon stays in place while it should walk through Winding Chasm corridor.
- [x] 11. Deviate Dreadfang should cast Terrify spell more often.
- [x] 12. Both waves before Mutanus the Devourer boss should spawn in water instead of high ground.
- [x] 13. Spawns are moving to fast.
- [x] 14. Spawns should be able to loot before their corpses disappear.
- [x] 15. There should be 6x Nightmare Ectoplasm spawned as second wave (which is correct). Each of them should have random (perm) Evolving Ectoplams buff (red/blue/green/black) making them immune to adequate magic school damage (fire/frost/nature/shadow). As far I remember they were all black (corpses disappeared quickly) and had no appropriate immunity (known issue from point 1.)
- [x] 16. When Mutanus the Devourer is spawned there should be emote: "Naralex dreams up a horrendous vision. Something stirs beneath the murky waters."
- [x] 17. Looks like rare boss Trigore the Lasher (3652) doesn't spawn at all near WC dungeon entrance.
- [x] 18. Lord Cobrahn shouldn't cast any spell once he's shapeshifted into Cobrahn Serpent Form.
- [x] 19. Boahn (3672) should have 20h respawn time.
- [x] 20. Matunus casted his Naralex's Nightmare spell on Muyoh NPC. Due this fact event bugged and after Mutanus death nothing happens. He should only cast that on players.
- [x] 21. Lady Anacondra: she should have like 3-4 potential spawn points, actually I figured out that I saw her only in 1.
- [x] 22. Verdan the Everliving (5775) shouldn't have random movements.
- [x] 23. Disciple of Naralex's quote: "At last! Naralex can be awakened! Come aid me, brave adventures!" should be present with last of Fanglords is dead. For now he yells that after returning to him before final fight.
**EDIT: Disciple of Naralex should yell it, not Naralex itself ;p** 
![image](https://user-images.githubusercontent.com/22802214/44958808-7ba5b000-aee5-11e8-8c34-a2bbd026683a.png)
- [x] 24. Disciple of Naralex should finish Serpentine Cleansing cast, he interrupted it himself (or Deviate Vipers did) but still continue event so it's not breaking.
- [x] 25. Next wave shouldn't spawn before previous isn't killed on Mutanus the Devourer event. Lets next wave spawn 5 seconds after previous is cleared.
- [ ] 26. Disciple of Naralex shouldn't take so long break after finishing his Serpentine Cleansing cast. He should start to walk earlier.
- [x] 27. When Disciple of Naralex and Naralex change form to birds they should fly away but through room entrance instead of random fly into water.
- [x] 28. Spawned raptors during disciple escort should appear in gps location:
![image](https://user-images.githubusercontent.com/22802214/45119128-c8de8780-b15a-11e8-86de-ccf8af19390b.png)
- [x] 29. Disciple of Naralex should start to attack creatures who are fightning with players.
- [x] 30. Waves on last boss should be spawned quite deeper in water.
- [x] 31. All Spawned Moccasins from 1 wave appear in one location instead of spread spawn points in entire room.
![image](https://user-images.githubusercontent.com/22802214/45475107-ad1b4880-b73b-11e8-8294-0b716e8a338c.png)
- [x] 32. Nightmare Ectoplasms from second wave don't move when spawned. Even when attacked by players they only stand and watch. One of Ectoplasms spawned just near Disciple which was weird.
- [x] 33. Mutanus the Devourer should spawn in his circle spawn point. For now he spawns near coastline.

**Comment by Kokaina** [comment]
1. Looks like rare boss Trigore the Lasher (3652) doesn't spawn at all near WC dungeon entrance.
2. Lord Cobrahn shouldn't cast any spell once he's shapeshifted into Cobrahn Serpent Form.
3. Spawn on Mutanus the Devourer event are still moving to fast.
4. When Disciple of Naralex casts Serpentine Cleansing spell he evades once got hit from any source which heals him instantly.
5. Looks like Lady Anacondra doesn't spawn in random places but still on the same spot:
![image](https://user-images.githubusercontent.com/22802214/44087210-5a7d06d8-9fbf-11e8-8518-c68deac59660.png)

**Comment by Kokaina** [comment]
On monday I will try to wipe several times during Mutanus event including npcs death so we can see if party can continue dungeon after various endings.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/1750

if Disciple of Naralex dies you need to restart instance and start all over again

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
List updated.

**Comment by Kokaina** [comment]
List updated.
