### ISSUE TITLE
[NPC] Time Watcher

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#850]
Decription: Those mobs are flying randomly in Tanaris which they shhouldnt.

How it works: Found them flying around in Tanaris where they shouldnt be.

How it should work: The Time Watcher dragons should only be inside the Cavern of Time.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102618_222106](https://user-images.githubusercontent.com/44415275/47590786-ace2af80-d96d-11e8-940e-a50a12a625d5.jpg)

**Comment by Reflekz** [comment]
If i may add , I've found where they come in / out.
![wowscrnshot_110218_131204](https://user-images.githubusercontent.com/44597439/47927280-91156700-dea1-11e8-9784-761b7052586d.jpg)

i saw all 3 going down , then maybe a minute after, they popped back out to fly out around tanaris .. haha :)
