### ISSUE TITLE
No Rested EXP

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#854]
Description: Was logged out at an inn (at Booty Bay) for over 24 hours. Logged in and had zero rest exp bonus. I did have the "zzz" when I logged out I made sure, but I wasnt at the inn long enough for it to say "You feel rested" before I logged out so I think this caused the bug.

How it works: Enter an Inn or city and logout (before it says "You feel rested") Log back in after an extended amount of time when rest exp bonus should be gained and none has been gained at all.

How it should work: Enter an Inn or city and logout. As long as you have the "zzz" on your portrait you should be gaining rest exp bonus whether you are logged in or not and whether or not you already had rest exp bonus to start with before logging out. (I thought it was up to 2 full levels of rest exp bonus, but the link I have says 1.5 levels is max rest. Perhaps this was changed at some point?)

Source (you should point out proofs of your report, please give us some source): 
Here is some info about when you should accumulate rest exp and at what rates.
https://wow.gamepedia.com/Rest

**Comment by Eternae1** [comment]
I believe you are also supposed to gain rested exp if logged out for a long time in the open world as well. It is very minimal rest exp bonus though.

**Comment by Eternae1** [comment]
Just tested logging out after it says "You feel rested" and I still did not gain any rest exp, even the little bit I had from when it said "You feel rested" went away completely.

**Comment by ahlens** [comment]
Noticed the same today

**Comment by Eternae1** [comment]
Please re-open this or explain why it was closed. Rested experience is still not working at all and gets removed if you have a little bit and then log out.

**Comment by akrom23** [comment]
Wait for the update.

**Comment by Pizzle93** [comment]
Still not working today, have opened new issue.

**Comment by Eternae1** [comment]
This issue still persists even though the change log on the website says "Reworked rest system."  Has it not been pushed live yet?

**Comment by akrom23** [comment]
Still got the same problem as described on first post?

**Comment by Eternae1** [comment]
Yes. I do not accumulate rested exp while logged out inside a city or inn, or even the wilderness for that matter. And when I am at a city or inn and it says "You feel rested" then I log out, I lose whatever rest exp I had.

**Comment by Pizzle93** [comment]
I actually opened a separate post last night then closed it. My bar turned blue (rested) but just logged on now and I have no rested bonus.
