### ISSUE TITLE
[NPC] Ringo

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#864]
Decription: Does not assist by attacking when engaged in combat.

I also found information about a potential bug which was during retail: 

By Speeddymon (2,546 – 5·30) on 2010/08/09 (Patch 3.3.5)
Seems this NPC bugs sometimes after people finish the escort, causing him to not despawn at Marshall's Refuge, and not respawn at the cave. The reason some would report no problems is because they most likely did it after a server reset (or maintenance, or someone contacted a GM to have the NPC reset), before he bugged again. I'm sure it will be fixed in a future patch.

How it works: Ringo does his voice "scream" of going agressive to attack nearby mobs but right after he goes back to not attack. 

How it should work: Ringo should assist by attacking any mobs attacking him or player/s.

Source (you should point out proofs of your report, please give us some source): 
I seem to have forgot taking a screenshot. Will link the quest he is connected to below tho:
http://db.hellfire-tbc.com/?quest=4491
Ringo: http://db.hellfire-tbc.com/?npc=9999
This is where I found information about the bug mentioned in decription: https://www.wowhead.com/npc=9999/ringo#comments

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1166
