### ISSUE TITLE
Weapon skill training

### ISSUE THREAD

**Issue by KimmoKM** [SunwellWoW/Sunwell-TBC-Bugtracker#87]
Currently, acquiring early weapon skills, even at max level, is a slow process: skill levels 20-21 for example might take tens of hits. However, as you can see in [Joana's Guide](https://youtu.be/mqa11gayS9U?t=18s), when Joana acquires a new weapon type at level 57, the chance of gaining weapon skill point remains almost guaranteed (intellect of course also factors into this) up until it's around 10 levels/50 skill behind your level, and only the last 20 skill or so are remotely slow. Weapon skills were a major annoyance on Hellground, making switching weapons while leveling almost impossible and possibly causing even your primary weapon to fall behind due to 2x rates, which, as you can see, is far from Blizzlike behavior.

I don't know the correct formula, but Trinitycore implementation for example isn't obviously wrong (for all I know, it might be exactly correct).

**Comment by notsofamous** [comment]
https://www.youtube.com/watch?v=1y8nnxTdx3c
Video of a guy lvling weapon skill in wotlk to 368 (max is 400), should give you an idea of the speed you gain skills.

**Comment by Wojtyas** [comment]
Probably was correlated with increased exp rates significantly.
Issue didn't occur on normal rates or slightly increased rates so far.
