### ISSUE TITLE
[Quest] The Grimtotem Weapon

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#879]
Decription: 
[The Grimtotem Weapon](http://wowwiki.wikia.com/wiki/Quest:The_Grimtotem_Weapon)
[Captured Totem](http://wowwiki.wikia.com/wiki/Captured_Totem)
[Plant Captured Totem](https://www.wowhead.com/spell=42452/plant-captured-totem#summons)

How it works: 
Planted Captured Totem don't work.
![wowscrnshot_102718_175358](https://user-images.githubusercontent.com/43764742/47605603-ff24de80-da08-11e8-90a4-c12da62cc55b.jpg)
![wowscrnshot_102718_175404](https://user-images.githubusercontent.com/43764742/47605604-ffbd7500-da08-11e8-8ea7-8e154e91b0d1.jpg)

How it should work: 
https://youtu.be/v8_3A5Ydx8E?t=44

Source (you should point out proofs of your report, please give us some source): 
Links in description and https://youtu.be/v8_3A5Ydx8E?t=44

**Comment by Feydil** [comment]
Must have happened something with the fix after my report, before it worked but the totem could be killed by mobs around it.

**Comment by Dootz** [comment]
weird, i've tested it after fix mentioned by @Feydil and it was working fine. I'll check again.

**Comment by Reflekz** [comment]
I'm there now and I'm getting credits without placing the totem down.
![wowscrnshot_103118_020036](https://user-images.githubusercontent.com/44597439/47767082-c7d85b00-dcb0-11e8-9cca-08676d9d6fe9.jpg)
