### ISSUE TITLE
[Quest]  Corrosion Prevention

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#882]
Decription: 
[Corrosion Prevention](http://wowwiki.wikia.com/wiki/Quest:Corrosion_Prevention)
[Ooze Buster](https://www.wowhead.com/item=33108/ooze-buster)

How it works: 
Ooze Buster don't work.
![wowscrnshot_102718_182601](https://user-images.githubusercontent.com/43764742/47606021-7b6df080-da0e-11e8-9d15-c57b2fdb759c.jpg)
![wowscrnshot_102718_182855](https://user-images.githubusercontent.com/43764742/47606022-7b6df080-da0e-11e8-9b63-ae726de1ae35.jpg)

How it should work: 
https://www.youtube.com/watch?v=9pISOTpykWo

**Comment by neheri** [comment]
Decription: This quest is broken. I found interesting thing - when you click on quest giver it gives you credit.


How it works: You have the q item but it doesn't do anything. Somehow I got 1/10 Oozes disolved however I am not sure how. Power cores do not grant a buff. You can use the quest item without having a buff.

How it should work:

There are objects in various places called "Power Core Fragment". If you get near them 30 yd (?) you get a buff called "Energized!" that lasts for 10 seconds and electric beam connects you with the power core.

Only when you have that buff you can use the Ooze Buster. Using ooze buster on oozes marks them and after they are killed they give the credit.

Source (you should point out proofs of your report, please give us some source):
https://youtu.be/9pISOTpykWo?t=18
https://www.wowhead.com/quest=11174/deprecated-corrosion-prevention

![wowscrnshot_110418_195604](https://user-images.githubusercontent.com/37372869/47968539-ae962c80-e06b-11e8-9831-6c7d3906812c.jpg)
