### ISSUE TITLE
[Quest] Corrupted Sabers

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#885]
Decription: Released the kitten at the moonwell and nothing happened. Could sadly not find a video of what it's supposed to look like when the transformation happends.

How it works: After using the quest item provided by the quest giver the kitten spawns, but after bringing it to the moonwell the kitten doesnt transform and because of that can't complete the quest.

How it should work: After using the quest item provided by the quest giver the kitten should spawn as it does, then when entering the moonwell the kitten should transform into a bigger cat (see screenshot below).

Source (you should point out proofs of your report, please give us some source): 
![wow testing](https://user-images.githubusercontent.com/44415275/47606238-5e86ec80-da11-11e8-953d-d063cc11d092.jpg)
![wowscrnshot_102718_174257](https://user-images.githubusercontent.com/44415275/47606240-69418180-da11-11e8-96ed-d0da35ea85b8.jpg)
![wowscrnshot_102718_174259](https://user-images.githubusercontent.com/44415275/47606241-6ba3db80-da11-11e8-974e-870a3dc6ae4d.jpg)

**Comment by FrauHolle86** [comment]
tested today on PTR --> still same issue --> cat doesnt transform --> quest not doable

**Comment by ZaoQ** [comment]
This quest still doesnt work
