### ISSUE TITLE
Mobs initial aggro ignores movement speed debuffs

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#895]
Description: If you aggro a mob from being inside its aggro range and use a movement slowing effect (such as frostbolt) the mob will ignore the movement speed debuff and still run towards you at its normal speed. (once it reaches and hits you it will pay attention to the movement slows)

How it works: Aggro mob from its aggro range -> Use movement slow on mob while it is still running towards you -> Mob ignores movement slow until it reaches and attacks you.

How it should work: Aggro mob (any type of aggro: body pull, ranged pull) -> Use movement slow on mob while it is still running towards you -> Mob should be slowed regardless of where he is at along his aggro path.

Source (you should point out proofs of your report, please give us some source): Aggro a mob from its range and hit it with a frostbolt or other movement slow effect before it reaches you and you will see what I mean.

**Comment by arcwizard** [comment]
I noticed it the same way, but I thought it was a delay.

**Comment by Wojtyas** [comment]
Fixed & implemented.
