### ISSUE TITLE
[Quest] Spirits of Stonemaul Hold

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#896]
Decription: 
[Spirits of Stonemaul Hold](http://wowwiki.wikia.com/wiki/Quest:Spirits_of_Stonemaul_Hold)
[Energized Totem](http://wowwiki.wikia.com/wiki/Energized_Totem)
[Ogre Remains](http://wowwiki.wikia.com/wiki/Ogre_Remains)

How it works: 
When approaching Ogre Remains, an Stonemaul Spirit appears and attacks. When attempting to interact with Ogre Remains, it disappear and  Stonemaul Spirit does not appear.
![wowscrnshot_102718_214447](https://user-images.githubusercontent.com/43764742/47608133-a285eb80-da29-11e8-8ef2-c7bcab8b16e8.jpg)
![wowscrnshot_102718_214516](https://user-images.githubusercontent.com/43764742/47608134-a285eb80-da29-11e8-8ac7-fd7ebc88d480.jpg)
![wowscrnshot_102718_214536](https://user-images.githubusercontent.com/43764742/47608135-a31e8200-da29-11e8-85cb-71447fdded91.jpg)

How it should work: 
Stonemaul Spirit should only appear after interacting with Ogre Remains.

Source (you should point out proofs of your report, please give us some source): 
In description.

**Comment by ghost** [comment]
I've encountered the same issue

**Comment by ArekJadach** [comment]
me2
