### ISSUE TITLE
[NPC] Crushridge Enforcer, Warmonger, Mage and Muckrake

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#899]
Decription: 
[Crushridge Enforcer](https://www.wowhead.com/npc=2256/crushridge-enforcer)
Level: 38 - 39
Class: Normal
Faction: Ogre
Health: 1,395 - 1,459
Damage: 116 - 135
Armor: 1,772

[Crushridge Warmonger](http://db.hellfire-tbc.com/?npc=2287)
Level: 39 - 40
Class: Normal
Faction: Ogre
Health: 1,459 - 1,524
Damage: 118 - 138
Armor: 1,899
Abilities:
[Enrage](http://db.hellfire-tbc.com/?spell=8269)

[Crushridge Mage](http://db.hellfire-tbc.com/?npc=2255)
Level: 37 - 38
Class: Normal
Faction: Ogre
Health: 970 - 1,004
Mana: 2,861 - 2,975  **
Damage: 96 - 112
Armor: 887
Abilities:
[Bloodlust](http://db.hellfire-tbc.com/?spell=6742)
[Frostbolt](http://db.hellfire-tbc.com/?spell=9672)

[Muckrake](http://db.hellfire-tbc.com/?npc=2421)
Level: 40
Class: Normal
Faction: Ogre
Health: 1,524
Damage: 121 - 139
Armor: 1,964
Abilities:
[Pummel](http://db.hellfire-tbc.com/?spell=12555)
[Disarm](http://db.hellfire-tbc.com/?spell=8379)

How it works: 
All these NPCs have the wrong damage in the melee. Crushridge Warmonger don't use Enrage. Crushridge Mage have wrong mana value and don't use Frostbolt. Muckrake don't use Pummel.
![wowscrnshot_102718_221231](https://user-images.githubusercontent.com/43764742/47608788-be8e8a80-da33-11e8-916a-be249d0cef36.jpg)
![wowscrnshot_102718_222547](https://user-images.githubusercontent.com/43764742/47608789-bf272100-da33-11e8-93db-b494e25ab19e.jpg)
![wowscrnshot_102718_222657](https://user-images.githubusercontent.com/43764742/47608790-bf272100-da33-11e8-81b0-84a24fbc67c8.jpg)
![wowscrnshot_102718_222812](https://user-images.githubusercontent.com/43764742/47608791-bf272100-da33-11e8-9ae2-91ed0bf7b356.jpg)

How it should work: 
All these NPCs must have stats from description, and use their abilities as described.

Source (you should point out proofs of your report, please give us some source): 
In descriptions.
About mana value Crushridge Mage, there value from http://wowwiki.wikia.com/wiki/Crushridge_Mage, because NPC have ability Frostbolt, and the fact that the spell requires more mana than it has in (if get mana value from http://db.hellfire-tbc.com/?npc=2255) it seems strange.

**Comment by Dootz** [comment]
Hi, I'm not sure about those Hellfire damage values. They seem I bit too high, don't you think? I admire your dedication and number of issues you've reported. It's a bit odd for me that other databases like Excalibur (https://db.excalibur.ws/?npc=2287) have numbers almost 2 times lower (for damage). Won't creatures kill a player in 4-5 hits if we buff them to hellfire db values? Also to save you some time, you don't need to include all data related to those npcs in your report. I'm writing a tool to import it automatically, so if you can, feel free just to provide links.

**Comment by arcwizard** [comment]
In fact, this database was recommended to me by one of the GMs of this project. And those values that are listed in the database are basic values, they will be reduced by armor, passive and active abilities of players.
