### ISSUE TITLE
[Priest][Spell] Levitate

### ISSUE THREAD

**Issue by Eurydies** [SunwellWoW/Sunwell-TBC-Bugtracker#9]
Description: The Priest levitate spell grants a permanent slow fall animation.

How it works:  Once levitate is cast, it causes The levitate buff which allows the user to float, walk on water, and slow fall ( similar to the mage spell, slow fall) **after the duration of the spell ( 2 min) runs out, the player will continue to slow fall when jumping off things ( they will however still take full fall damage)**

How it should work:  Once the Duration of the spell is up, all effects should be gone ( IE, no more slow fall)

**Comment by Kokaina** [comment]
Fixed and implemented.
