### ISSUE TITLE
[Mobs pull problem] [Dungeons, zones, raids]

### ISSUE THREAD

**Issue by Unfairy** [SunwellWoW/Sunwell-TBC-Bugtracker#91]
Problem / bug about pulling mobs / mobs being not linked.

How it supposed to work:  Some mobs in game supposed to be linked / pulled together because they are linked by system or just staying close to each other. So pulling one mobs leads to instantly pulling another mobs if they are linked or chain pull of whole pack if they are staying close to each other.
How it works: 
Lets take for example Shadow Labyrinth, Room of 1st boss. Example mobs: Fel Overseer (patrol) and Cabal Ritualist (stationary). When you are pulling Fel Overseer which walks near pack of 3 Cabal Ritualists - as 3 Cabal Ritualists staying clsoe to each other or linked they are supposed to be pulled together.
But in this server if mobs not linked together and if you pull patrol close to one of the mobs, only that mob will  be pulled.
Screenshots:
1. Fel Overseer and Cabal Ritualists out of combat before pull
![wowscrnshot_081118_120205](https://user-images.githubusercontent.com/41975070/43994626-e2246c84-9da8-11e8-8949-045d5e176774.jpg)
2. Pulled Fel Overseer
![wowscrnshot_081118_120212](https://user-images.githubusercontent.com/41975070/43994636-f8fdace0-9da8-11e8-9480-5b644c5c8849.jpg)
3. One of the Cabal Ritualists stopps channeling and getting in combat
![wowscrnshot_081118_120214](https://user-images.githubusercontent.com/41975070/43994640-15e059f2-9da9-11e8-89f3-c80e34b59356.jpg)
4. Fel Overseer and only ONE Cabal Ritualists in combat. 2 Other Cabal Ritualists from pack didnt pulled and stays outside of combat
![wowscrnshot_081118_120218](https://user-images.githubusercontent.com/41975070/43994650-4345ffdc-9da9-11e8-97a0-4b98778f78a4.jpg)

I remember this problem being Fair in Wargate for a lot of dungeons, zones and players being able to abuse it making some quests/dungeons easier to do.
Fixes are either linking problematic packs together or fixing chain aggro / linked aggro.

**Comment by Nadiirr** [comment]
Most of the Linked-aggro is fixed in dungeons. 

But the chain aggro from #382 is still not fixed.

**Comment by Wojtyas** [comment]
Fixed & implemented. There will be new chain pulling system soon as well.
