### ISSUE TITLE
[Quest] Birds of a feather

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#924]
Decription: The quest item used to capture the bird does not work.

How it works: Clicking the nest which spawns either a Male or Female Kaliri Hatchling is working as it should, but when a Female Kaliri Hatchling spawns it's not possible to use the Empty Birdcage.

How it should work: You simply be able to capute a Female Kaliri Hatchling by using the Empty Birdcage quest item. Assuming a Female spawns and not a Male.

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?quest=9397
![wowscrnshot_102818_130913](https://user-images.githubusercontent.com/44415275/47615784-34d2d180-dab4-11e8-8542-34e749a3c292.jpg)

**Comment by Squarz** [comment]
This still isn't working as of 16:00 10th Nov 18
