### ISSUE TITLE
Quest: Vanquish the Betrayers

### ISSUE THREAD

**Issue by Braderman88** [SunwellWoW/Sunwell-TBC-Bugtracker#928]
Description: 
Upon looting the key from Lieutenant Benedict, when using the key on Benedict's chest on the top floor of the castle, the key fails to open the chest. 

How it works: 
Having looted the key, as per the chat window below, I used the key on the chest atop the castle. The opening cast bar, lasting about 5 seconds displayed, then failed to open the key and deleted the key in the process. 

How it should work: 
Benedict's key should open Benedict's chest

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102818_131720](https://user-images.githubusercontent.com/44547519/47616432-9eeb7680-dab4-11e8-92c1-109aa3c4598a.jpg)

This is after the first attempt, it shows I looted the key from Benedict in the chat, but also that it has now been consumed and hasn't opened the chest.

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/826
