### ISSUE TITLE
[NPC] Fel Reaver

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#930]
Decription: Killing quest npc's which he shouldnt.

How it works: If he come close to a neutral/quest npc Fel Reaver will attack and kill the poor npc's.

How it should work: Fel Reaver should not kill any neutral or quest related npc.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102818_152054](https://user-images.githubusercontent.com/44415275/47617217-4cff1c80-dac5-11e8-9e32-60603ade0ded.jpg)
![wowscrnshot_102818_152057](https://user-images.githubusercontent.com/44415275/47617218-4ec8e000-dac5-11e8-8385-1fea2202b40f.jpg)

**Comment by Silroth** [comment]
I dont see how this is a bug, in retail TBC many people kited Fel Reaver into Thrallmar, Honor Hold and even to Shattrah and he was attacking and killing them.

**Comment by Feydil** [comment]
I might be wrong then, if thats the case just close the issue.
