### ISSUE TITLE
[Quest] The Admiral's Orders

### ISSUE THREAD

**Issue by infp40** [SunwellWoW/Sunwell-TBC-Bugtracker#931]
Decription: From the chest that opens "Benedict's Key" I did not get " Admiral Proudmoore's Orders"

How it works: Nothing happened after opening the chest

How it should work: After opening the chest from it you can get Admiral Proudmoore's Orders, which begins The Admiral's Orders

Source (you should point out proofs of your report, please give us some source): 
[Key](https://classicdb.ch/?item=4882#comments)
[Quest](http://classicdb.ch/?quest=830)
![wowscrnshot_102818_174535](https://user-images.githubusercontent.com/44532870/47617642-4b8c1f00-dada-11e8-9031-5d2f30587b87.jpg)
![wowscrnshot_102818_174845](https://user-images.githubusercontent.com/44532870/47617646-50e96980-dada-11e8-88bf-e7ed08eaeec3.jpg)

**Comment by Dootz** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/928

**Comment by hugedude** [comment]
has this been put into a duplicate loop with issue #928? Or is there an actual fix or response to this somewhere else?

I am still having this issue and I cannot find an actual response to it anywhere here. It is now 7th of December and this bug is still happening.
