### ISSUE TITLE
[NPC] Dreghood Brute, Dreghood Geomancer, Fleeing Dreghood Warrior

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#933]
Decription: When the Illidari Taskmaster dies the Dreghood mobs doesnt "flee". Also keeping the player in combat even if they arent agresive unless killed. Vanish etc works to leave combat.

How it works: Assisting the Illidari Taskmaster as intended while the Taskmaster is alive. After killing the Illidari Taskmaster the Dreghood mobs does not "flee" but sticking around until killed or attacked. If the Taskmaster had two assisting him one sometimes ran away when one of them got attacked. Also kept following the player in + keeping the player in combat even if they arent agressive unless killed. Vanish etc works to leave combat.

How it should work: After killing the Illidari Taskmaster the Dreghood mobs should start "fleeing" because they are set "free". Unless if the player is attacking them then they should turn agressive.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102818_161212](https://user-images.githubusercontent.com/44415275/47617927-352b9680-dacd-11e8-8750-3663fff05982.jpg)
![wowscrnshot_102818_161224](https://user-images.githubusercontent.com/44415275/47617933-4bd1ed80-dacd-11e8-890f-39e08fa2d610.jpg)

**Comment by Squarz** [comment]
More bugs/information:

How it works:
Dreghood Brutes don't always transform into Fleeing Dreghood Warriors
After converting from Dreghood Brutes the Fleeing Dreghood Warriors follow the player keeping them in combat.
Dreghood Brutes can move too quickly when engaged: see clip below at 28 seconds
Level up animation (when they transform) is visible to players.
https://streamable.com/96vnq
https://streamable.com/tld3k - Here you can see one Dreghood Brute clipping through the floor and another one getting stuck.

How it should work: 
When the Illidari Taskmaster dies the Dreghood Brutes should transform into Fleeing Dreghood Warriors and run away from the player and despawn.
Combat should drop as soon as they transform.
If they are damaged after the transformation they will engage the player until they are killed/reset.
Level up animation (when they transform) should not be visible to players.
Dreghood Brutes should not gain increased movement speed when engaged.

Source:
https://www.wowhead.com/quest=9387/source-of-the-corruption#comments
"This is how it works: When you damage them (directly or nondirectly) when they are agressive (before the taskmaster dies), it does not prevent them from running away. If you, however, damage them after they turn to "fleeing xxx" and become neutral, they will keep attacking."
