### ISSUE TITLE
[Npcs] Bloodtalon Taillasher and Kul Tiras Sailor

### ISSUE THREAD

**Issue by Reykjavikshore** [SunwellWoW/Sunwell-TBC-Bugtracker#937]
Decription: 

https://vanilla-twinhead.twinstar.cz/?npc=3122#abilities
https://vanilla-twinhead.twinstar.cz/?npc=3128#abilities

How it works: 
Rushing Charge didnt work properly skill add these mobs too much dmg 

![wowscrnshot_102818_155511](https://user-images.githubusercontent.com/44321901/47618421-cfd6a600-daca-11e8-921c-51b1db7bbe26.jpg)
https://vanilla-twinhead.twinstar.cz/?spell=6268

How it should work: 
That skill should give them plus 10 dmg bonus not 40-60

**Comment by Sabre142** [comment]
This should be a high priority

**Comment by tbcfun** [comment]
i just lost interest on testing the beta after trying to do the first quest in razor hill " Vanquish the Betrayers" for 40 minutes as a melee
![premium dmg002](https://user-images.githubusercontent.com/44589302/48347998-3e496580-e680-11e8-8c4d-d9e4dcd60ca1.JPG)
