### ISSUE TITLE
The Barrens quests, mobs and other.

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#94]
- [ ] "The Warsong Reports" quest gives item "Bundle of Reports" to use. After opening the bundle you get 3 Warsong Reports but the bundle does not disappear. If you relog it is still in your bags and you can open it again which will give you 3 more reports. The bundle should be removed from inventory upon opening and receiving 3 reports.

- [x] "Nara Wildmane" quest chained from "Hamuul Runetotem" quest, not completeable when picked up. It says to speak with Nara who is in the same tent as the quest giver, but when you accept the quest it gives credit and you can not speak with Nara Wildmane. You need to leave her area or relog to be able to speak with her and complete quest.

- [ ] "Miner's Fortune" quest gives "A Sack of Coins" as a reward which gives a 6 slot bag and some silver when opened. "A Sack of Coins" does not disappear from inventory and if you relog you can open it again and get more silver and another 6 slot bag to vendor resulting in a slow, but infinite gold source from relogging. "A Sack of Coins" should be removed from inventory once it has been emptied.

- [x] "Weapons of Choice" quest requires 3 items for completion, the item "Razormane War Shield" has an incredibly low drop rate - I cleared all spawns of mobs twice before I got it to drop once. Increased drop rate of "Razormane War Shield" would fix. Also unable to turn in quest even though it says complete in quest log and I have all 3 items in my inventory. Relog did not fix, but abandon and repick quest did fix for turn in.

- [ ] Gann Stonespire (quest giver that patrols Southern Gold Road) will continue to walk on his patrol as you interact with him and not stop at all.

- [x] "Samophlange Manual" quest requires a manual that is made of a "Samophlange Manual Cover" and 5 "Samophlange Manual Page" combined. The pages have a very low drop rate - I completely cleared all mobs in the area twice and got 3 of 5 pages. Increased drop rate of pages would fix.

Source: 
![wowscrnshot_081118_104828](https://user-images.githubusercontent.com/42300476/43997463-c9b69eb6-9d98-11e8-9e5a-7522ebd3eb8c.jpg)
![wowscrnshot_081118_104832](https://user-images.githubusercontent.com/42300476/43997464-c9c723f8-9d98-11e8-8a7d-e711187eccde.jpg)
Warsong Reports.

![wowscrnshot_081118_105318](https://user-images.githubusercontent.com/42300476/43997470-e7115d66-9d98-11e8-9b23-8a5405ec5b3a.jpg)
Mob still lootable with no loot on body or after being looted.

![wowscrnshot_081118_120715](https://user-images.githubusercontent.com/42300476/43997474-0839e30a-9d99-11e8-8bdf-98df57d25286.jpg)
Cannoneer Whessan is spawned inside of a cannon. (I killed him and he respawned there as well)

![wowscrnshot_081118_175813](https://user-images.githubusercontent.com/42300476/43997480-2ed5551c-9d99-11e8-8f1e-96c4fe8e4ea0.jpg)

Herd of Barrens Kodo not moving or patrolling.

**Comment by Dootz** [comment]
Thanks for the report, not marked issues will be handled separately as they are worldwide bugs.
