### ISSUE TITLE
[NPC] Wastewander Rogue, Wastewander Shadow Mage

### ISSUE THREAD

**Issue by arcwizard** [SunwellWoW/Sunwell-TBC-Bugtracker#942]
Decription: 
[Wastewander Rogue](http://db.hellfire-tbc.com/?npc=5615#abilities)
[Wastewander Shadow Mage](http://db.hellfire-tbc.com/?npc=5617#abilities)

How it works: 
Both NPC has wrong dmg.
Wastewander Rogue don't use Backstab, 
![wowscrnshot_102818_192744](https://user-images.githubusercontent.com/43764742/47618964-b68d2400-dae1-11e8-87d6-cc401d31d537.jpg)
Wastewander Shadow Mage don't use any abilities.
![wowscrnshot_102818_194843](https://user-images.githubusercontent.com/43764742/47619011-59de3900-dae2-11e8-9e48-8cb61218880c.jpg)

How it should work: 
They must have stats and abilities from description.

Source (you should point out proofs of your report, please give us some source): 
In description.

**Comment by Eternae1** [comment]
They use Shadowbolt and Immolate on me, but their pet AI seems to be a little off. (sometimes missing pets or pets dont help master) Also their shadowbolts are hitting for too much damage, anywhere from 250 - 350

**Comment by arcwizard** [comment]
When I did the screenshots above, I performed a quest for them, and during the execution of quest, no one NPC used its abilities.
