### ISSUE TITLE
[Spell] Frostbolt after Fireball

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#943]
Decription: 
Frostbolt isnt slowing a target which got first hit by Fireball

How it works: 
I "threw" Fireball at a Kobold Tuneller/Rockhide Boar in Elwynn. It ressisted at tunneler, and got boar hit. Anyway, in both cases, i used Frostbolt thereafter. Target had the debuff, but the movement speed hasnt changed . They were supposed to be slowed by 40%. Both Fireball resisted and hit target werent slowed, even though Frostbolt hit, i casted it even twice on both mobs, but they werent slowed. If i use Frostbolt as my "opener" in mob fights, they get the slowing effect. If Frostbolt is used after Fireball, it wont slow the target down. 
EDIT: If target reaches me, and i trying to run away, the target is actually slowed then. ONLY AFTER reaching me.

How it should work: 
Frostboll should ALWAYS slow the target, if it hits the target of course. (Exceptions are bosses)

Source (you should point out proofs of your report, please give us some source):

**Comment by Eternae1** [comment]
I already made a report about this. It seems mobs are ignoring movement speed slows if they aggro from a body pull or say they break out of frost nova and then you hit them with a frostbolt, they will most likely ignore the slow effect until they reach and attack you.

**Comment by Mikov1605** [comment]
Yeah, exactly

**Comment by akrom23** [comment]
#895.
