### ISSUE TITLE
[NPC] Rajis Fyashe

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#945]
Decription: Did not use any of her spells.

How it works: Auto attack bot.

How it should work: Should cast several spells, can be found in link below.

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?npc=18044#abilities

**Comment by notsofamous** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/288
