### ISSUE TITLE
Line of Sight in the open World

### ISSUE THREAD

**Issue by RPAncap** [SunwellWoW/Sunwell-TBC-Bugtracker#951]
Decription: 
Hey I noticed that I can just cast right through terrain even though I don't have Line of Sight on the mob.

How it works: 
You can cast through hills.

How it should work: 
It should just tell you the target is not in your LoS and not let you cast.

Source (you should point out proofs of your report, please give us some source): 
Here is a short video of what I am talking about https://www.youtube.com/watch?v=wX0gQQGNt2o

**Comment by notsofamous** [comment]
Afaik hills have never caused LoS

**Comment by RPAncap** [comment]
Damn you are correct. 
http://wowwiki.wikia.com/wiki/Line_of_sight

"Terrain (that is, dirt and trees) only block Line of Sight indoors. All dirt and most trees do NOT block spells or abilities when fighting outdoors. "

NOT A BUG.
