### ISSUE TITLE
[Pathing] Saltstone Basilisks

### ISSUE THREAD

**Issue by sunwelldude** [SunwellWoW/Sunwell-TBC-Bugtracker#953]
Decription: 
The pathing on Saltstone basilisks in the shimmering flats is a bit off.

How it works: 
The mobs always reset when you enter water.

How it should work: 
They should follow you into the water.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/drxS2SPt910

**Comment by Wojtyas** [comment]
Fixed and implemented.
