### ISSUE TITLE
Darkshire guards are inside Halloween pumpkins

### ISSUE THREAD

**Issue by leahnie956** [SunwellWoW/Sunwell-TBC-Bugtracker#956]
Decription: 
Darkshire guards are inside Halloween pumpkins

How it works: 
should not be inside

How it should work: 
should not be inside

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/25886407/47621033-baa84a00-dabf-11e8-89c6-f911d9ed037f.png)

**Comment by leahnie956** [comment]
![image](https://user-images.githubusercontent.com/25886407/47621060-0d820180-dac0-11e8-999e-724c5f9711c3.png)

**Comment by Dootz** [comment]
on hold, nearest Hallow's end will occur in next year.
