### ISSUE TITLE
PvP vendors Champion's Hall/Hall of Legends

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#96]
Description: NPCs that sell PvP gear offer wrong gear for 2.0 content patch.

How it works: Currently they offer gear that was made available in 2.4 patch.

How it should work: They should offer gear called Grand Marshal/High Warlord (lvl 70 blue) for HONOR and Gladiator for arena points (lvl 70 purple).  Right now Merciless Gladiator gear is bought with honor in those PvP vendors which shouldnt happen until 2.4 content patch.
PvP gear has multiple cost columns regarding each patch (Merciless Gladiator gear has first cost column for Season 2 when its most expensive, second cost column for Season 3 when it was less expensive than Season 2 and third cost column for Season 4 when it costed honor + marks.

The reason i know/remember this is because i spent some time reverting PvP vendors on a different server to 2.0 content patch before server launch.

IMPORTANT NOTICE: When 2.4 patch launched and Blue quality PvP gear was removed from normal PvP vendors, Blizzard added PvP gear of similar quality to Grand Marshal/High Warlord (lvl 70 blue) to reputation vendors in Outland (Thrallmar/Honor Hold, Cenarion Expedition, Lower City etc) for GOLD. This was a catch up mechanic for fresh lvl 70's to get some basic gear before farming honor to get Merciless Gladiator gear which costed honor + marks in 2.4.  That gear (Blue quality PvP gear introduced in 2.4) from reputation vendors should be removed otherwise nobody will bother getting Grand Marshal/High Warlord PvP gear for honor.

Source (you should point out proofs of your report, please give us some source): http://wowwiki.wikia.com/wiki/High_Warlord%27s_Dreadweave_Hood
Patch 2.4.0 (25-Mar-2008): Removed.
Patch 2.0.1 (05-Dec-2006): Added.

http://wowwiki.wikia.com/wiki/Merciless_Gladiator%27s_Scaled_Helm (1875 honor points in Season 2)
https://www.wowhead.com/item=32041/merciless-gladiators-scaled-helm#comments 14500 honor - 30 AV in Season 4 aka 2.4)

https://www.wowhead.com/item-set=734/vengeful-gladiators-dreadgear#comments 

2.3: Costs a total of 8250 arena points as of 2.3
2.4: As of June 24th, with the release of S4, the prices on all Season 3 gear has been decreased:

Helm: 1500 Arena Points
Shoulders: 1200 Arena Points (1950 Team and Personal Rating)
Chest: 1500 Arena Points
Hands: 900 Arena Points
Legs: 1500 Arena Points

Total Arena Cost: 6,600 Arena Points

https://www.wowhead.com/item=35382/seers-linked-gauntlets#comments (Comment about said reputation PvP gear being added in 2.4)

**Comment by SunwellWoW** [comment]
They will appear with season start
