### ISSUE TITLE
Bridges in STV have bad pathing

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#961]
Description: These bridges around the Southern Savage Coast dont work with pathing too well. Mobs will run around / fall through the bridges and you can Blink and fall through as well.

How it works: Read above, see screenshots.

How it should work: Bridges should work as solid terrain with smooth pathing.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102818_201142](https://user-images.githubusercontent.com/42300476/47626011-73857d80-daee-11e8-9f01-3ac91f85a86d.jpg)
![wowscrnshot_102818_201145](https://user-images.githubusercontent.com/42300476/47626012-73857d80-daee-11e8-98a1-47def92d768b.jpg)

**Comment by Eternae1** [comment]
Also recently noticed the pirates at the ships have bad pathing as well. They can see through parts of the ship and aggro to you, they can fall through the floors and spawn underneath / outside in the water.
![wowscrnshot_102918_005842](https://user-images.githubusercontent.com/42300476/47634128-ed7d2d00-db15-11e8-9577-3d5bb9727cfe.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented.
