### ISSUE TITLE
[Creature] Rare Mob "The Rot" too strong

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#965]
Description: The Rot rare mob in Dustwallow Marsh has way too much HP and deals high damage.

How it works: See screenshot.

How it should work: Should have lower health and more balanced damage to the other mobs / rare mobs in that level range.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102918_003600](https://user-images.githubusercontent.com/42300476/47633485-b443bd80-db13-11e8-822c-c34f895a433d.jpg)

**Comment by Reflekz** [comment]
Health and Damage seems fine , Movement speed seems to be off.

Not sure how to show this without recording. But he can nearly keep up with our 300% mounts.

**Comment by Dootz** [comment]
nah that's fine no need to record. I can easily check it. Thank you.
