### ISSUE TITLE
[Item Description] Hearthstone

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#968]
Decription: 
Description of teleport location is false on Hearthstone

How it works: 
Description shows "Teleports the caster to Elwynn Forest" - which should mean Northsthire

How it should work: 
I got my HS in Goldshire, so description should be "Teleports the caster to Goldshire".

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
After update, all homebinds will be reset and set to starting locations.
