### ISSUE TITLE
[NPC] Guard Roberts health(priest quest)

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#971]
Decription: 
Guard Roberts, the NPC close to goldshire, for Priest class quest has wrong hp

How it works: 
He has full hp all the time.

How it should work: 
He should have like 20% hp, and have 100% after being healed and being granted power word: shield (priest class quest from goldshire)

Source (you should point out proofs of your report, please give us some source):

**Comment by simroman** [comment]
Still doesn't work
