### ISSUE TITLE
[NPC] Msshi'fn

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#973]
Decription: Spawned beneath the ground.

How it works: It's still possible to accept quest and turn in but have to talk with the NPC from specific angles to work.

How it should work: Should be spawned on top of the floor and not beneath.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102918_114905](https://user-images.githubusercontent.com/44415275/47650111-82684080-db7f-11e8-8712-741f78e4ca0f.jpg)

**Comment by Dootz** [comment]
probably will be fixed with next server update.
