### ISSUE TITLE
[NPC] Anwehu, G'eras

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#978]
Decription: Reporting this just in case. These 2 vendors are currently selling Badge of Justice currency items which are supposed to come with the release of Zul'Aman and Sunwell. Should not be available from the beginning.

How it works:

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102918_123931](https://user-images.githubusercontent.com/44415275/47652634-beeb6a80-db86-11e8-85c6-e92264dfbda6.jpg)
![wowscrnshot_102918_123908](https://user-images.githubusercontent.com/44415275/47652641-c14dc480-db86-11e8-8354-02e017326bc2.jpg)

**Comment by Kokaina** [comment]
We will remove patch changes later but thanks for good eye ;)

**Comment by akrom23** [comment]
#309.
