### ISSUE TITLE
Imp under Goldshire Inn attacks when you walk downstairs and the vendor next to him Cylina Darkheart is not clickable

### ISSUE THREAD

**Issue by leahnie956** [SunwellWoW/Sunwell-TBC-Bugtracker#98]
Decription: 
Imp under Goldshire Inn attacks when you walk downstairs and the vendor next to him Cylina Darkheart is not clickable

How it works: 
imp does not attack and vendor is clickable

How it should work: 
imp does not attack and vendor is clickable

Source (you should point out proofs of your report, please give us some source): 
![ethr](https://user-images.githubusercontent.com/25886407/44003901-1ad4e424-9e20-11e8-88fc-453e7b26b1dc.jpg)

**Comment by Azathothh** [comment]
Cylina Darkheart is working as a vendor but for warlocks (selling grimoires) probably shouldn't work for other classes so it's fine. Imp is bugged indeed.
