### ISSUE TITLE
[Item] Ankh of Life improper mechanics

### ISSUE THREAD

**Issue by Eternae1** [SunwellWoW/Sunwell-TBC-Bugtracker#983]
Description: The trinket Ankh of Life heals the target for a set amount, it should be instant cast.

How it works: Trinket is a cast and can be used while moving, additionally moving after casting does not interrupt it either.

How it should work: Trinket should be instant cast.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=1713/ankh-of-life#comments
Comment from 2008 patch 2.3.2: Instant Cast

**Comment by Mikov1605** [comment]
It works fine, the cast has been removed on cata, but on vanilla till tbc it had a 2,5 cat. Look here http://wowwiki.wikia.com/wiki/Ankh_of_Life. NEVER COMPARE ITEMS FROM WOWHEAD(which is up to date with newest wow expansion) to items from tbc

**Comment by akrom23** [comment]
And the winner is...?

**Comment by akrom23** [comment]
https://wow.gamepedia.com/index.php?title=Ankh_of_Life&oldid=1546581

> 2.5 cast

Not a bug.
