### ISSUE TITLE
[NPC] Sharth Voldoun 

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#985]
Decription: His respawn timer is far too long. (The quest he is linked to is "The Final Code")
He also seems to be missing the RP event with Pathaleon the Calculator.

How it works: I timed him and his respawn timer is roughly 25 minutes. Considering that the quest item he drops is 70-80% drop rate, it's not 100% that he will drop it. Which makes it a very tedious quest to complete. Specialy if a lot of players trying to do it.
Sharth Voldoun is also supposed to have a RP event with Pathaleon the Calculator if the player does not aggro the npc immediately.

How it should work: Found this comment on wowhead. 
By Zexion (1,445 – 7·10) on 2007/01/31 (Patch 2.0.6)
The spawn time is 3-5 minutes. Pretty fast so don't worry if he gets ninjad or something.

This is the conversation these 2 NPC's are supposed to have:

Sharth Voldoun: My master, we are honored by your presence. How may I serve thee?
Pathaleon the Calculator's Image: Rise, young Voldoun. Do not worry yourself with pleasantries. I come at the behest of our master, Prince Kael'thas. He bids me to check on the progress of the mana bomb.
Sharth Voldoun: All goes exceedingly well, my lord. Testing of the smaller prototype at the Cenarion Thicket was a complete success. The second bomb is being ritually fueled in the courtyard below even as we speak. And, I've sent a courier to Tuurem to bring the rest of the parts to us here.
Sharth Voldoun: You are satisfied?
Pathaleon the Calculator's Image: For the time being, yes. However, allow my presence to be a motivator. Prince Kael'thas was displeased with the failure of the crystal experiment on Fallen Sky Ridge. This is one of the reasons for why we chose the Cenarion druids as the testing grounds for the bomb.
Pathaleon the Calculator's Image: I need not tell you what will happen should the mana bomb down in the courtyard fail to be used on its target soon? Since moving into the forest, they've become increasingly annoying to our operations: here, at Tuurem and to the south at the Bonechewer Ruins.
Pathaleon the Calculator's Image: I think that we should teach a lesson to both the Horde and the Alliance. One that they will not soon forget!
Sharth Voldoun: I can assure you that we will not fail, my master. I am personally overseeing every aspect of the construction, and I hold the final codes, myself. Within a day's time, I will have the bomb detonated on those nearby pests.
Pathaleon the Calculator's Image: See to it that you do, Sharth, or I will personally see to your slow torture and death.
The player enters...
Sharth Voldoun: You come into my house and threaten ME? I think not!
Pathaleon the Calculator's Image: I believe I may recognize them. Deal with this quickly, Sharth. Then take the mana bomb and destroy their town!

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=10447/the-final-code
Sharth Voldoun: http://db.hellfire-tbc.com/?npc=18554#drop:0+12+1
Pathaleon conversation source: https://wow.gamepedia.com/Pathaleon_the_Calculator%27s_Image#Conversation_with_Sharth_Voldoun

**Comment by notsofamous** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/311
