### ISSUE TITLE
Quest Nagrand  Standarts and Practices

### ISSUE THREAD

**Issue by tbcfun** [SunwellWoW/Sunwell-TBC-Bugtracker#986]
Decription: Elkay'gan the Mystic at Garadar in Nagrand wants you to use the Mag'har Battle Standard at the First Burning Blade Pyre, Second Burning Blade Pyre, and Third Burning Blade Pyre

How it works: Using Mag'har Battle Standard is working but not getting credit for usage
How it should work: 

Source (you should point out proofs of your report, please give us some source): ![wowscrnshot_102918_220344](https://user-images.githubusercontent.com/44589302/47682014-64c0c880-dbcb-11e8-887e-1603170bda82.jpg)
![wowscrnshot_102918_220348](https://user-images.githubusercontent.com/44589302/47682052-7c984c80-dbcb-11e8-82b4-7aed29fded14.jpg)

**Comment by akrom23** [comment]
#300.
