### ISSUE TITLE
[Quest] Who are they?

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#989]
Decription: When accepting the quest the player should get a new "look" but it did not happen.

How it works: After accepting the quest the quest giver will change the way the player looks for a "spy" mission. The quest working fine a part from the player getting the disguise. The NPC's in the area still turn friendly a part from the Hunter which is correct.

How it should work: Should work just as it is + adding the disguise look. See picture of a pretty orc below as an example what it looks like.

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/44415275/47682935-3db7c600-dbce-11e8-9590-e7581b2d5995.png)

**Comment by notsofamous** [comment]
Were you mounted when you accepted the quest?

**Comment by Feydil** [comment]
I know if you are mounted you wont get the disguise, I'm pretty sure I was not. Got a screenshot of me being unmounted. But could still have been mounted when accepting.
