### ISSUE TITLE
[NPC] Firewing Warlock

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#991]
Decription: Firewing Warlock is only using 2 out of 5 spells

How it works: Currently Firewing Warlock is only using Mana Tap and Arcane Torrent.

How it should work: Firewing Warlock should use Mana Tap, Arcane Torrent, Immolate, SHadow Bolt and Sun Shield.

Source (you should point out proofs of your report, please give us some source):
http://db.hellfire-tbc.com/?npc=16769#abilities
![wowscrnshot_102918_203037](https://user-images.githubusercontent.com/44415275/47683454-e87cb400-dbcf-11e8-89a5-9b0ac4925a96.jpg)

**Comment by akrom23** [comment]
#311
