### ISSUE TITLE
[NPC] Isla Starmane

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#992]
Decription: Getting killed by mobs around her.

How it works: To be able to accept this quest as it is now, you have to clear the room she spawns in and then wait for her to respawn. Because the mobs around her is killing her.

How it should work: Isla Starmane should not be hostile for mobs around her until the escort quest she offers is accepted.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102918_203232](https://user-images.githubusercontent.com/44415275/47683564-3b566b80-dbd0-11e8-9b84-4cdbb46f1ec7.jpg)

**Comment by notsofamous** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/311
