### ISSUE TITLE
[Quest] Escape from Firewing Point!

### ISSUE THREAD

**Issue by Feydil** [SunwellWoW/Sunwell-TBC-Bugtracker#994]
Decription: After quest is accepted mobs now ignore Isla Starmane.

How it works: She walks the correct path but all mobs ignore her, so as a Rogue I could simply stealth beside her to complete the quest. IF the player aggro mobs she will assist however.

How it should work: After accepting the quest Isla Starmane offers, she should turn into a hostile target for mobs in the area.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102918_204911](https://user-images.githubusercontent.com/44415275/47683697-a738d400-dbd0-11e8-930b-763fbf467ea4.jpg)
![wowscrnshot_102918_204918](https://user-images.githubusercontent.com/44415275/47683708-adc74b80-dbd0-11e8-9979-fe62f9f1a468.jpg)
![wowscrnshot_102918_204932](https://user-images.githubusercontent.com/44415275/47683729-c9325680-dbd0-11e8-8c3b-952b2f9b0528.jpg)

**Comment by notsofamous** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/311

**Comment by Feydil** [comment]
My bad, have missed your whole report part. Will go through it more properly before reporting from now, Good to know :)
