### ISSUE TITLE
[Loot] Unable to loot personally tagged mobs when joining party

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#999]
Decription: 
Kill a mob, join a group before you loot it, try to loot the mob. The mob will be ineligible to loot. 

Error: "You do not have permission to loot this corpse"

How it works: 
Kill a mob, join a group before you loot it, try to loot the mob. The mob will be ineligible to loot. 

Error: "You do not have permission to loot this corpse"
We were able to replicate this by Player A killing a mob. Player B inviting Player A before Player A looted his dead mob. Player A attempts to loot the mob Player A killed after joining Player B's group. Player A cannot loot Player A's tagged mob because of the error ""You do not have permission to loot this corpse"

How it should work: 
should be able to loot your loot if you killed it, regardless of when you join a new group. 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
#753.
